Adds the T-100Y howitzer and rebalances the mortar, renamed mortar.
tgstation/TerraGov-Marine-Corps pull request #10017
Opened 2022-04-16 05:11 UTC by Pariah919

## About The Pull Request
https://streamable.com/jb3gwo

Adds the T-100Y howitzer, a heavier, draggable version of the mortar. Marines get one roundstart (may change), the shells all cost 3, you get two shells. Its shells are....

White phos, for all your 'spotting' needs. Costs two, but you only get one shell per buy.
HE, when you wanna ruin somones day.
Incend with a LE payload. When you wanna set someone on fire.
Tanglefoot, same as unchanged 80mm mortar. Same cost as WP.

The gun itself is incredibly accurate and a distinct sound.

Mortar renamed to T-50S, and has a few changes...

Aims to make the mortar a more mobile, moveable tool with 
Shells are normal sized, are cheaper (1 for 2) 
HE/Incend nerfed overall, they're cheaper however.
Smoke/Flare unchanged, flare can be fired out of the Howitzer by space magic.
Tanglefoot nerfed, cost down. Still only one shell on buy.

Mortar code changed a bit, sounds are more customizeable, I suppose.

## Why It's Good For The Game
Makes long range artillery and short range artillery more defined in TGMC, and generally makes the mortar feel more like a medium range mortar rather than just artillery. 
Also it just sounds cool.

## Changelog
:cl:
add: Added new howitzer, the T-100Y
code: Mortar code is more malleable instead of snowflakey.
balance: Mortar rebalanced. It costs 1 for 2 shells, the shells are generally less dangerous, it is generally more portable, shells are normal sized instead of bulky. It is now significantly easier to run it on the move, compared to its bigger cousin the howitzer.
balance: Flare and smoke 80mm shells are small sized.
/:cl:

2022-04-16 12:05 UTC, FosterGrime-Heymynameslouie commented
YEAAHHH BABBYYY WOOO

https://user-images.githubusercontent.com/59080633/163674156-c548cc8e-bd7a-4432-bfc7-c98327e57437.mp4

2022-04-16 21:46 UTC, Losenis commented
https://www.youtube.com/watch?v=GW6GSa14xXI

2022-04-17 00:56 UTC, Diegoflores31 commented
turning cm into WW2 literally . do marines really need MORE support fire than now ??

2022-04-17 18:36 UTC, Kuro020 approved these changes

2022-04-18 13:31 UTC, TiviPlus requested changes

2022-04-18 13:31 UTC, TiviPlus commented on code/game/objects/machinery/mortar.dm
> +	)
autodoc where

2022-04-18 13:31 UTC, TiviPlus commented on code/game/objects/machinery/mortar.dm
> +	var/deployed_item = /obj/machinery/deployable/mortar // What item are we gonna deploy?
autodoc and wrong order

2022-04-18 13:31 UTC, TiviPlus commented on code/game/objects/machinery/mortar.dm
> +		to_chat(user, span_warning("You unanchored the gun from the gruond. It may be moved."))
early return
this doesnt even need to be an if use 
ancored = !anchored
and ? :

2022-04-18 13:31 UTC, TiviPlus commented on code/game/objects/machinery/mortar.dm
> +	new /obj/item/encryptionkey/cas(src)
why two binocs

2022-04-18 13:31 UTC, TiviPlus commented on code/game/objects/machinery/mortar.dm
> +	new /obj/item/binoculars/tactical/range(src)
why two binocs

2022-04-19 21:15 UTC, BraveMole approved these changes
Me when MJP's code is actually decent

2022-04-19 21:15 UTC, BraveMole commented on code/game/objects/machinery/mortar.dm
> +	)
Still some autodoc issues

2022-04-21 00:41 UTC, tyeagg commented
flare shells dont work on mortar anymore

2022-04-21 20:32 UTC, Pariah919 commented
> flare shells dont work on mortar anymore

works, made mortar shells small

2022-04-23 20:22 UTC, merged