Handcharger is kill
tgstation/TerraGov-Marine-Corps pull request #10072
Opened 2022-04-27 01:53 UTC by Arctrooper8

## About The Pull Request

Would you like to never run out of APC or lasgun charge? Would you like to power the average American household for a whole year in a matter of second? Would you like to use your bulging marine muscles on grandma's exercise equipment to completely negate any sort of power management?

Well too bad, handcharger is kill.

## Why It's Good For The Game

Negating any sort of power management is bad, especially when current equipment, light, or door power consumption doesn't actually seem to exist. Engis already get a free power cell and have access to around 8 more free ones from a vendor. They can also buy more for 1 point each, they're not exactly lacking for cells (and that's not even mentioning recharger cells).

Perhaps more pressingly is the fact you can charge a lasgun cell in about two cranks, that's practically the blink of an eye. It completely remove any ammo management from the weapon type and while it's certainly tons of fun it is arguably unbalanced.

You can say that it'd be better to nerf instead of complete removal, but any sort of nerf that will actually curtail either usage of the handcharger will essentially banish it to the shadow realm, it's best to just fully kill it in this case.

## Changelog
:cl:
del: For breaking the laws of reality TGMC hand chargers have been taken away by the [REDACTED]
/:cl:

2022-04-27 02:05 UTC, Losenis commented
No fun allowed

2022-04-27 02:07 UTC, Pariah919 commented
![image](https://user-images.githubusercontent.com/46353991/165423947-f80fde59-052b-4868-95fe-c8017027aa12.png)

Handcrank charger, you were a great item, you broke all power balance forever, and made basically infinite ammo for laser guns.

You should've never made it past TM, but its time for you to rest.

2022-04-27 02:07 UTC, Pariah919 approved these changes

2022-04-27 02:18 UTC, Arctrooper8 commented
Git will remember

2022-04-27 02:49 UTC, RipGrayson commented
As sad as I am to see it go, this removal is needed. RIP my favorite piece of exploitable engineering gear.

2022-04-27 05:43 UTC, Al-1ce commented
Total removal is a little bit silly. It should remain a synth item though.

2022-04-27 08:07 UTC, EvilMelonTheSecond commented
Surely this will lead to power management finally getting fixed right? This isn't just a removal of marine tools that uses a problem as an excuse right? 

You could've just blacklisted lasgun cells from the charger if the only intention was to remove the OP aspect. As far as I'm concerned the hand charger contributes almost nothing to the power management issue as it stands since engineers can still use a single cell to restore power to any room then take it back out after they're done.

I'm just a bit annoyed is all, this removal won't change much but remove a small tool for engis. I would've preferred a complete removal IF it was attached to a power management overhaul PR since this alone fixes nothing about it.

2022-04-27 13:58 UTC, Losenis commented
Power management isn't a thing anyone ever gives a shit about unless it's to remove fun stuff. See TG with yellow cores from xenobio. "Negating power management" was never a problem when engis brought a cell or two with them to invalidate it entirely, or even a recharger cell to then remove afterwards. And infinite lasgun ammo wasn't ever a problem either considering bringing an ammo box with you did the same thing anyway; surviving long enough to spend it all was rare.

2022-04-27 18:14 UTC, BraveMole requested changes
So I think handcharger is garbage design, but rn power logistic is just not in a good enough shape to remove it

2022-05-02 17:52 UTC, Arctrooper8 commented
> So I think handcharger is garbage design, but rn power logistic is just not in a good enough shape to remove it

I explained how power logistics is basically non-existent on discord, you can get all three nuke disks easily with one cell.

2022-05-02 17:52 UTC, Arctrooper8 commented
> So I think handcharger is garbage design, but rn power logistic is just not in a good enough shape to remove it

I explained how power logistics is basically non-existent on discord, you can get all three nuke disks easily with one cell.

2022-05-02 19:34 UTC, Losenis commented
Power logistics is nonexistent because there's basically no power logistics system to do much with that'd not massacre shipside if changed. Power logistics would need an entire overhaul in groundside gameplay to be worthwhile, and trying to remove things to force people to pay attention to the at best barebones system (Blue disk on LV doesn't even run on power, for fucks sake) isn't the way to do it. If anything it'll let people know that the system is dogshit.

The removal of the handcharger doesn't fix or improve on anything, it only serves to hide the shortcomings of a system that isn't even affected that much by it. Even when xenos overrun a place you only need wirecutters and a screwdriver to fix, the xenos would sooner HELP you conserve power by slashing the APC and stopping it from getting drained by the equipment.

If anything the handcharger allowed you to take the other option of using the APC's battery to recharge it rather than bringing your own. The APC battery had far lower capacity than a normal one so it CAN actually run out given time before marines all get wiped out. Not only that, the handcharger's use got indirectly nerfed already by the plasma cutter's battery no longer being removable.

2022-05-03 13:57 UTC, Araulius commented
you should probably code the energy generators and smes to be industructable first. since machine assembly was removed. and you can't replace those. if you want there to be a power economy, you have to make engineering groundside power actually viable.

2022-05-05 08:22 UTC, TiviPlus requested changes
What tanya said, I dont think maintainers are interested in this

Feel free to discuss removing lasgun batteries from it though

2022-05-05 08:23 UTC, closed without merging

2022-05-06 00:47 UTC, Derrick2Electricboogaloo commented
> 

I am down for having the ability to repair/rebuild it.

2022-05-07 22:55 UTC, Losenis commented
>Feel free to discuss removing lasgun batteries from it though

Normal ballistic ammo has the option of carrying proper ammo boxes to refill spent magazines to incentivize keeping the empty magazines stored, without handchargers (that normal marines can't even on their own) lasgun batteries have no equivalent.