New hunter ability, swap. Kill silence
tgstation/TerraGov-Marine-Corps pull request #10076
Opened 2022-04-27 17:59 UTC by BraveMole

## About The Pull Request

This ability allow you to swap with one of your illusion clones
Illusions clones no longer update apparences
Kill silence ability

## Why It's Good For The Game

Add a nice skill to hunter toolkit. For now it is impossible for the marine to know with which illusions the hunter swapped (there is just a small sound and that's it), I'll see if I need to telegraph that more (probably)

Silence is a bit useless rn.

## Changelog
:cl:
add: New hunter ability, swap
del: Kill silence ability
/:cl:

2022-04-28 08:05 UTC, TiviPlus requested changes
Rest lgtm

2022-04-28 08:05 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
> +	illusions = list()
should also  call this in the destroy because timers get deleted in destroy

2022-04-28 23:29 UTC, Al-1ce commented
Silence is niche. I've only ever (effectively) used it when attacking small groups or solo's, since the last thing you'd want is them to be calling out for help. With that said, I don't really think hunter needs another deceive/obscure ability after the several currently in place.

2022-04-29 07:16 UTC, Naaanii commented
Yeah, after using and seeing it's effects in combat, silence is actually a really cool ability especially with Hunter's mark which enforces the 'hunting' aspect that this caste has.

2022-05-07 08:07 UTC, TiviPlus approved these changes

2022-05-07 08:29 UTC, merged