MG08 is now moveable (bad) sprite by me. Makes a generic moveable deployable gun.
tgstation/TerraGov-Marine-Corps pull request #10081
Opened 2022-04-28 07:44 UTC by Pariah919

## About The Pull Request
Generic deployable moveable gun.
MG08 now moves. Sprites by me. Very questionable.
https://streamable.com/fv234n

## Why It's Good For The Game
MG08 was pretty wack, this should give it a bit more of a gimmick.

## Changelog
:cl:
balance: MG08 is now moveable.
refactor: Genercized Moveable Mounted gun code.
/:cl:

2022-04-28 07:48 UTC, ilikesaying commented
![image](https://user-images.githubusercontent.com/65475697/165703523-af8f5d3e-330e-4d9a-b7ea-0aa107255828.png)

2022-04-28 17:05 UTC, Kuro020 requested changes
Sprite needs work

2022-04-30 23:06 UTC, Kuro020 approved these changes

2022-05-01 07:54 UTC, TiviPlus approved these changes

2022-05-01 07:55 UTC, merged