The lorenining of Guns- Rifle Edition
tgstation/TerraGov-Marine-Corps pull request #10080
Opened 2022-04-28 04:44 UTC by Pariah919

## About The Pull Request
Companies-
Raummetall- MGs, Certain Rifles (Focus on MGs and Wacky Experimental rifles, T-12 is just there because RMML AR-12 sounds cool)
Kauser- ALF rifles- Skirmish Rifle, LMG, carbine (Focus on that rifle platform overall.)
SCA- Halo guns. (Yes.)
Bauer- Autoshotgun and Chambered sniper (Placeholder) 

DRAFTED SO I DON'T FORGET

## Why It's Good For The Game
Gun lore good, and screw it, we have a new nomelcuture, might aswell spice it up.

## Changelog
:cl:
add: Added new gun lore. 
add: New gun names, more nomenclature.
/:cl:

2022-04-28 15:15 UTC, XSlayer300 commented on code/modules/codex/entries/guns_codex.dm
> +	Ironically, the T-12 submitted by the very group that made the national disaster that the AR-11 (Oringally termed T-11.) ended up winning out all the tests. \
```suggestion
	Ironically, the T-12 submitted by the very group that made the national disaster that the AR-11 (originally designated the T-11) ended up winning out all the tests. \
```

2022-04-28 15:17 UTC, XSlayer300 commented on code/modules/codex/entries/guns_codex.dm
> +	lore_text = "The Kauser ALF series of firearms was born out of a desire to create a modular weapon design that could ergonomically use a simmilar manual of arms to appeal to simplify famaliarity and
```suggestion
	lore_text = "The Kauser ALF series of firearms was born out of a desire to create a modular weapon design that could ergonomically use a similar manual of arms to appeal to simplify familiarity and attract large scale buyers.\
```

2022-04-28 15:18 UTC, XSlayer300 commented on code/modules/codex/entries/guns_codex.dm
> +	It was designed to be simple to use, dissasamble and basically survive every condition, however due to reports of barrel melting from the high use of polymers. It ended up being heavier than its ilk
```suggestion
	It was designed to be simple to use, disassemble and basically survive every condition, however due to reports of barrel melting from the high use of polymers. It ended up being heavier than its ilk to compensate.\
```

2022-04-28 15:19 UTC, XSlayer300 commented on code/modules/codex/entries/guns_codex.dm
> +	The entire ALF-series ended up being panick bought in mass by specialized troops in the Marine Corps, generally Peacekeeper sections or Air Assault sections, it eventually spread by osmosis in popul
```suggestion
	The entire ALF-series ended up being panic bought in mass by specialized troops in the Marine Corps, generally Peacekeeper sections or Air Assault sections, it eventually spread by osmosis in popularity.\
```

2022-04-28 15:20 UTC, XSlayer300 commented on code/modules/codex/entries/guns_codex.dm
> +	lore_text = "The Kauser ALF series of firearms was born out of a desire to create a modular weapon design that could ergonomically use a simmilar manual of arms to appeal to simplify famaliarity and
```suggestion
	lore_text = "The Kauser ALF series of firearms was born out of a desire to create a modular weapon design that could ergonomically use a similar manual of arms to appeal to simplify familiarity and attract large scale buyers.\
```

2022-04-28 15:20 UTC, XSlayer300 commented on code/modules/codex/entries/guns_codex.dm
> +	The Machinegun variant, known as the 'ALF-22' focused on creating a versatile package consisting of a light squad support weapon, with a focus on mobility and accuarate fire over pure magazine size.
```suggestion
	The Machinegun variant, known as the 'ALF-22' focused on creating a versatile package consisting of a light squad support weapon, with a focus on mobility and accurate fire over pure magazine size.\
```

2022-04-28 15:20 UTC, XSlayer300 commented on code/modules/codex/entries/guns_codex.dm
> +	It ended up with a drum magazine, elongated heavy barrel for sustained firing, its overall shape being of a common rifle generally assists it in being easy to pickup and use, and can mount more unde
```suggestion
	It ended up with a drum magazine, elongated heavy barrel for sustained firing, its overall shape being of a common rifle generally assists it in being easy to pickup and use, and can mount more underbarrel attachments compared to its peers in its class.\
```

2022-04-28 15:21 UTC, XSlayer300 commented on code/modules/codex/entries/guns_codex.dm
> +	The entire ALF-series ended up being panick bought in mass by specialized troops in the Marine Corps, generally Peacekeeper sections or Air Assault sections, it eventually spread by osmosis in popul
```suggestion
	The entire ALF-series ended up being panic bought in mass by specialized troops in the Marine Corps, generally Peacekeeper sections or Air Assault sections, it eventually spread by osmosis in popularity.\
```

2022-04-28 15:21 UTC, XSlayer300 commented on code/modules/codex/entries/guns_codex.dm
> +	Most would say the large magazine capacity combined with ease of use and ability to lay down fire with good frontline potiential is the main advantage of this weapon. You will still be one the slowe
```suggestion
	Most would say the large magazine capacity combined with ease of use and ability to lay down fire with good frontline potential is the main advantage of this weapon. You will still be one the slower people in your group, however."
```

2022-04-28 15:22 UTC, XSlayer300 commented on code/modules/codex/entries/guns_codex.dm
> +	lore_text = "The Kauser ALF series of firearms was born out of a desire to create a modular weapon design that could ergonomically use a simmilar manual of arms to appeal to simplify famaliarity and
```suggestion
	lore_text = "The Kauser ALF series of firearms was born out of a desire to create a modular weapon design that could ergonomically use a similar manual of arms to appeal to simplify familiarity and attract large scale buyers.\
```

2022-04-28 15:22 UTC, XSlayer300 commented on code/modules/codex/entries/guns_codex.dm
> +	The entire ALF-series ended up being panick bought in mass by specialized troops in the Marine Corps, generally Peacekeeper sections or Air Assault sections, it eventually spread by osmosis in popul
```suggestion
	The entire ALF-series ended up being panic bought in mass by specialized troops in the Marine Corps, generally Peacekeeper sections or Air Assault sections, it eventually spread by osmosis in popularity.\
```

2022-04-28 15:23 UTC, XSlayer300 commented on code/modules/codex/entries/guns_codex.dm
> +	Most would say it earned its term of a 'Skirmish' rifle due to use in constant Skrimishes, due to a low magazine size, but good overall mobility combined with firepower. Watch your magazine count an
```suggestion
	Most would say it earned its term of a 'Skirmish' rifle due to use in constant skirmishes by frontline troops, due to a low magazine size, but good overall mobility combined with firepower. Watch your magazine count and put the hurt downrange."
```

2022-04-28 15:24 UTC, XSlayer300 commented on code/modules/codex/entries/guns_codex.dm
> +	lore_text = "The Keckler and Hoch 'T-11' was created out of a infamous bid called the 'Advanced Rifle of the Future' project, created out of a need to replace aging weapon stocks in the TerraGov Ars
```suggestion
	lore_text = "The Keckler and Hoch 'T-11' was created out of a infamous bid called the 'Rifle of the future' project, created out of a need to replace aging weapon stocks in the TerraGov arsenal. \
```

2022-04-28 15:25 UTC, XSlayer300 commented on code/modules/codex/entries/guns_codex.dm
> +	Eventually pushback got so large that a new bid was quickly placed within less than a decade, and the T-11, by now christened the 'AR-11'. Was considered a failure and mothballed.\
```suggestion
	Eventually pushback got so large that a new bid was quickly placed within less than a decade, and the T-11, by now christened the 'AR-11', was considered a failure and mothballed.\
```

2022-04-28 15:26 UTC, XSlayer300 commented on code/modules/codex/entries/guns_codex.dm
> +	However, some have been pulled out of longterm storage, and recent spottings have shown modernizations such as removal of the side magazines, an overall more ergomic shape with less brick-like featu
```suggestion
	However, some have been pulled out of long term storage, and recent spottings have shown modernizations such as removal of the side magazines, an overall more ergonomic shape with less brick-like features, and a larger magazine.\
```

2022-04-28 15:26 UTC, XSlayer300 commented on code/modules/codex/entries/guns_codex.dm
> +	Most would say that the unusually large magazine capacity, amazing burst fire capablity allows for an interesting use of a support weapon. But its bulky and unusual shape leading a low amount of att
```suggestion
	Most would say that the unusually large magazine capacity, amazing burst fire capability allows for an interesting use of a support weapon. But its bulky and unusual shape leading a low amount of attachments can hamper it in combat."
```
i swear you need sleep

2022-04-30 12:08 UTC, XSlayer300 commented on code/modules/codex/entries/guns_codex.dm
> +	This particular version of the rifle is modernized with a KTLD gun comptuer and vision scope to allow for quick IFF in hectic engagements, and corrections for the user to stop FF, unlike older varia
```suggestion
	This particular version of the rifle is modernized with a KTLD gun computer and vision scope to allow for quick IFF in hectic engagements, and corrections for the user to stop FF, unlike older variants, it requires no specialized training to use.\
```

2022-04-30 12:09 UTC, XSlayer300 commented on code/modules/codex/entries/guns_codex.dm
> +	Most would say that this rifle blends a feature of a normal rifle and sniper rifle, and has the ups and downs of both. Watch out in close quarters, and use the IFF and NVG features of the scope to y
```suggestion
	Most would say that this rifle blends a feature of a normal rifle and sniper rifle, and has the ups and downs of both. Watch out in close quarters, and use the IFF and NVG features of the scope to your advantage..."
```

2022-04-30 12:09 UTC, XSlayer300 commented on code/modules/codex/entries/guns_codex.dm
> +	lore_text = "The Raummetall 'T-29' was made out of the heavy and unruly corpse of the 'T-28', an attempt to modernize and integrate a KTLD into the T-27 model machinegun. It ended in failure due to
```suggestion
	lore_text = "The Raummetall 'T-29' was made out of the heavy and unruly corpse of the 'T-28', an attempt to modernize and integrate a KTLD into the T-27 model machinegun. It ended in failure due to the overcomplexity of the system, and cost eventually made the project die.\
```

2022-04-30 12:10 UTC, XSlayer300 commented on code/modules/codex/entries/guns_codex.dm
> +	The 'T-29' is effectively a continuation in spirit of the previous project, focusing on simplifying the IFF Computer systems. It only bears a outer resemblance to the T-27, outside of having the sam
```suggestion
	The 'T-29' is effectively a continuation in spirit of the previous project, focusing on simplifying the IFF computer systems. It only bears a outer resemblance to the T-27, outside of having the same basic systems.\
```

2022-04-30 12:10 UTC, XSlayer300 commented on code/modules/codex/entries/guns_codex.dm
> +	The 'T-29 is effectively a incredibly accurate machinegun, it ended up being offered to the Marine Corps after the previous attempt to just modernize the older machineguns failed. It ended up being
```suggestion
	The 'T-29' is effectively a incredibly accurate machinegun, it ended up being offered to the Marine Corps after the previous attempt to just modernize the older machineguns failed. It ended up being christened the 'MG-28' and entered service.\
```

2022-04-30 12:10 UTC, XSlayer300 commented on code/modules/codex/entries/guns_codex.dm
> +	Most would say that this machinegun makes you a walking turret, you'll be slow and unwieldy with no match when it comes to fire suppression on the mov."
```suggestion
	Most would say that this machinegun makes you a walking turret, you'll be slow and unwieldy with no match when it comes to fire suppression on the move."
```

2022-04-30 12:11 UTC, XSlayer300 commented on code/modules/codex/entries/guns_codex.dm
> +	It is basically a General Purpose Machinegun, meant to be used in about every scenario, usually not as well as a specialized gun, however it ended up being well known for its lightweightedness and m
```suggestion
	It is basically a General Purpose Machinegun (GPMG), meant to be used in about every scenario, usually not as well as a specialized gun, however it ended up being well known for its lightness and mobility within its class.\
```

2022-04-30 12:12 UTC, XSlayer300 commented on code/modules/codex/entries/guns_codex.dm
> +	Eventually, it won the bid due to its light weight, and low cost. Despite argugably being worse than most of the competition everywhere else outside of firerate. It was christened the 'MG-28' and en
```suggestion
	Eventually, it won the bid due to its light weight, and low cost for mass production. Despite arguably being worse than most of the competition everywhere else outside of firerate. It was christened the 'MG-28' and entered service.\
```

2022-04-30 12:12 UTC, XSlayer300 commented on code/modules/codex/entries/guns_codex.dm
> +	Most would say that this machinegun makes you a walking dispenser of lead, you'll be slow and unwieldy with no match when it come to emptying a rain of lead on foe... Or friend."
```suggestion
	Most would say that this machinegun makes you a walking dispenser of lead, you'll be slow and unwieldy with no match when it come to emptying a rain of lead on foe... or friend."
```

2022-05-01 04:59 UTC, Pariah919 commented
Will do Rifles, then SMGs and other Smartgun guns, then specialist firearms. But I'd rather do this in batches.

2022-05-01 08:50 UTC, TiviPlus requested changes

2022-05-01 08:50 UTC, TiviPlus commented on code/modules/codex/entries/guns_codex.dm
> +	lore_text = "The Raummetall 'T-60' was designed out of a bid for a cheap and available machinegun that could move to several roles, be it fire support, vehicle mounted or sentry duties.\
t60

2022-05-01 08:50 UTC, TiviPlus commented on code/modules/codex/entries/guns_codex.dm
> +	lore_text = "The Raummetall 'T-29' was made out of the heavy and unruly corpse of the 'T-28', an attempt to modernize and integrate a KTLD into the T-27 model machinegun. It ended in failure due to
T EVERYWHEER

2022-05-12 23:34 UTC, Pariah919 reviewed
T-PTSD from maintainers

2022-05-12 23:34 UTC, Pariah919 commented on code/modules/codex/entries/guns_codex.dm
> +	lore_text = "The Keckler and Hoch T-12 was created out of an order for a robust rifle using a caseless round, after the ergonomic and costly disaster of the 'Rifle of the future' Project. \
```suggestion
	lore_text = "The Keckler and Hoch M-12 was created out of an order for a robust rifle using a caseless round, after the ergonomic and costly disaster of the 'Rifle of the future' Project. \
```

2022-05-12 23:34 UTC, Pariah919 commented on code/modules/codex/entries/guns_codex.dm
> +	Ironically, the T-12 submitted by the very group that made the national disaster that the AR-11 (originally designated the T-11) ended up winning out all the tests. \
```suggestion
	Ironically, the M-12 submitted by the very group that made the national disaster that the AR-11 (originally designated the M-11) ended up winning out all the tests. \
```

2022-05-12 23:34 UTC, Pariah919 commented on code/modules/codex/entries/guns_codex.dm
> +	lore_text = "The Raummetall 'T-29' was made out of the heavy and unruly corpse of the 'T-28', an attempt to modernize and integrate a KTLD into the T-27 model machinegun. It ended in failure due to
```suggestion
	lore_text = "The Raummetall 'M-29' was made out of the heavy and unruly corpse of the 'T-28', an attempt to modernize and integrate a KTLD into the M-27 model machinegun. It ended in failure due to the overcomplexity of the system, and cost eventually made the project die.\
```

2022-05-12 23:34 UTC, Pariah919 commented on code/modules/codex/entries/guns_codex.dm
> +	The 'T-29' is effectively a continuation in spirit of the previous project, focusing on simplifying the IFF computer systems. It only bears a outer resemblance to the T-27, outside of having the sam
```suggestion
	The 'M-29' is effectively a continuation in spirit of the previous project, focusing on simplifying the IFF computer systems. It only bears a outer resemblance to the M-27, outside of having the same basic systems.\
```

2022-05-12 23:34 UTC, Pariah919 commented on code/modules/codex/entries/guns_codex.dm
> +	The 'T-29' is effectively a incredibly accurate machinegun, it ended up being offered to the Marine Corps after the previous attempt to just modernize the older machineguns failed. It ended up being
```suggestion
	The 'M-29' is effectively a incredibly accurate machinegun, it ended up being offered to the Marine Corps after the previous attempt to just modernize the older machineguns failed. It ended up being christened the 'MG-28' and entered service.\
```

2022-05-12 23:34 UTC, Pariah919 commented on code/modules/codex/entries/guns_codex.dm
> +	lore_text = "The Raummetall 'T-60' was designed out of a bid for a cheap and available machinegun that could move to several roles, be it fire support, vehicle mounted or sentry duties.\
```suggestion
	lore_text = "The Raummetall 'M-60' was designed out of a bid for a cheap and available machinegun that could move to several roles, be it fire support, vehicle mounted or sentry duties.\
```

2022-05-14 20:39 UTC, Pariah919 commented on code/modules/projectiles/guns/rifles.dm
> +
```suggestion
```

2022-05-14 20:53 UTC, BraveMole approved these changes

2022-05-14 20:53 UTC, merged