Add automatic weeding to weeds ability
tgstation/TerraGov-Marine-Corps pull request #10098
Opened 2022-04-29 21:58 UTC by Walarks

## About The Pull Request
GIves the "plant weeds" ability the option to turn on automatic weeding. This makes the xeno plant weeds when they move more than 3 tiles away from the last planted node.

## Why It's Good For The Game
Saves worker xeno sanity from repetitive manual labor.

## Changelog
:cl:
qol: add to the weeds menu an option to automatically plant weeds when moving
/:cl:

2022-04-29 22:02 UTC, Lumipharon commented
Neat

2022-04-30 00:35 UTC, ilikesaying commented
now add a weed-whacker

2022-04-30 16:51 UTC, Derrick2Electricboogaloo commented
Okay now where is engineer auto cade placement ability. God forbid we have to put in the manual work this is an unrealistic expectation.

2022-05-01 08:56 UTC, TiviPlus requested changes
+ discord comment
after you fix conflict should be good for tmc

2022-05-01 08:56 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/abilities.dm
> +	to_chat(owner, "<span class='notice'>We will now automatically plant weeds.</span>")
use span_class() macros

2022-05-01 08:56 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/abilities.dm
> +		to_chat(owner, "<span class='notice'>We will now spawn <b>[weed_choice]\s</b> when using the plant weeds ability.</span>")
span macros

2022-05-01 08:56 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/abilities.dm
> +		return
span

2022-05-01 10:32 UTC, Walarks commented on code/modules/mob/living/carbon/xenomorph/abilities.dm
> +		to_chat(owner, "<span class='notice'>We will now spawn <b>[weed_choice]\s</b> when using the plant weeds ability.</span>")
added span macros

2022-05-01 10:32 UTC, Walarks commented on code/modules/mob/living/carbon/xenomorph/abilities.dm
> +		return
ditto

2022-05-01 10:32 UTC, Walarks commented on code/modules/mob/living/carbon/xenomorph/abilities.dm
> +	to_chat(owner, "<span class='notice'>We will now automatically plant weeds.</span>")
added span macros

2022-05-04 19:55 UTC, merged