adds light to explosions
tgstation/TerraGov-Marine-Corps pull request #10106
Opened 2022-04-30 08:14 UTC by tyeagg

## About The Pull Request
add light to explosions, please tm first to see performance impact

## Why It's Good For The Game
they look pretty, easier to determine effect on target with explosions and it doesn't really make much sense how explosions don't create any light

## Changelog
:cl:
add: light to explosions
/:cl:

https://user-images.githubusercontent.com/98577688/166097638-df34bfce-aa1a-45c8-95cd-6b3c4ab8e1a2.mp4

2022-04-30 08:37 UTC, Lumipharon commented
You should probably make them args for explosions so it's easier to tweak. Not all explosions are going to be bright fireballs.

Looks cool though

2022-04-30 16:05 UTC, BraveMole requested changes
the light range and/or power should depend on the strength of the explosion i'd say

2022-04-30 18:05 UTC, Losenis commented
This is actually nice to see

2022-05-01 07:12 UTC, tyeagg commented
https://user-images.githubusercontent.com/98577688/166136059-8885b705-e279-410c-bb73-6483204432d5.mp4

first tat shot didn't explode because aphe doesn't explode on turf

2022-05-08 18:20 UTC, BraveMole requested changes
Also this might be too laggy anyway.

2022-05-08 18:20 UTC, BraveMole commented on code/controllers/subsystem/explosions.dm
> +/datum/controller/subsystem/explosions/proc/explode(atom/epicenter, devastation_range, heavy_impact_range, light_impact_range, flash_range, flame_range, throw_range, adminlog, silent, smoke, light_ra
You are not using any of these arguments

2022-05-08 18:20 UTC, BraveMole commented on code/controllers/subsystem/explosions.dm
> +	explosion_obj.light_range = max_range
this should be done in the explosion light constructor

2022-05-08 23:12 UTC, tyeagg commented
yea im closing this

2022-05-08 23:12 UTC, closed without merging