Labcoat storage change and medical sprite changes
tgstation/TerraGov-Marine-Corps pull request #10115
Opened 2022-05-01 06:10 UTC by Arctrooper8

## About The Pull Request

Changes the lab coat to function storage wise like a medical storage module.
Ports the **old** TG lab coat sprites, not the new ones that were so contentious.
Improves the medical scrubs sprite, making sure it covered the whole human mob whilst improving their overall look.
MDs now also start with a lab coat.
The researcher uniform and lab coat have been resprited.
Removed the unused solid color lab coats.
Removed the armored lab coat due to it's broken sprite and near instant abandonment by researchers.
Moved the snowsuits from labcoat.dm into jobs.dm for better organization.

## Why It's Good For The Game

Right now lab coats can only store two items small items inside their storage. By changing what they can hold to match the medical storage module, the lab coat becomes much more competitive with armor shipside and less likely to be replaced.

New lab coat storage means improved lab coat sprites, these are the old TG lab coat sprites before the new contentious ones were added.
![00doktor!](https://user-images.githubusercontent.com/95723150/166134162-5bbd6234-d5ac-4960-9501-f34f6335a9ed.png)
You can also see the new researcher uniform (also ported from TG) and improved scrubs (they really didn't change much, just a few more pixels).

Because lab coats are now actually useful it makes sense for MDs to have them.
The solid color lab coats didn't show up anywhere else in code or maps.
Armored lab coat sprite doesn't sit right (or in my opinion look that good). And balance wise it's too slow for shipside, and not protective, storage efficient, or modular enough for groundside, leaving it the eternal role of being left on the floor until a roomba eats it. Therefore it also goes in favor of a more standard lab coat.
Why snowsuits were in the lab coat file of all places is beyond me, they have been moved to a better location.

## Changelog
:cl:
balance: Lab coats now have the same storage as a medical storage module.
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: New sprites for all lab coats
imageadd: New researcher uniform and improved scrubs sprite.
/:cl:

2022-05-01 06:23 UTC, Pariah919 commented
mfw those palletes

2022-05-02 12:02 UTC, TiviPlus requested changes
Fix your cl

@Kuro020 review

2022-05-02 12:02 UTC, TiviPlus commented on code/modules/clothing/suits/labcoat.dm
> -		//Why???
dont remove this why comment it calls out this massive garbage

2022-05-02 15:48 UTC, Arctrooper8 commented
CL fixed and why comment readded!

2022-05-02 17:28 UTC, Kuro020 approved these changes

2022-05-04 19:54 UTC, merged