Railgun Changes
tgstation/TerraGov-Marine-Corps pull request #10125
Opened 2022-05-03 05:50 UTC by tyeagg

## About The Pull Request
make railgun better at its job

## Why It's Good For The Game
you can just ignore railgun by standing in the middle of the laser, gives it minirocket stats for clearing weeds and area denial, increased cooldown to 5 minutes and spread to compensate

## Changelog
:cl:
code: railgun targeting changed from pick to rand
balance: increased railgun spread
balance: changed railgun from using hv 30mm to minirocket
balance: increased railgun cooldown to 5 minutes
balance: reduced time it takes to fire and land railgun
/:cl:

https://user-images.githubusercontent.com/98577688/166409471-847f21d9-d772-4210-b66a-ad3af1491310.mp4

2022-05-03 05:51 UTC, tyeagg commented
[#10116](https://github.com/tgstation/TerraGov-Marine-Corps/pull/10116)

2022-05-08 12:12 UTC, TiviPlus requested changes
This should not be using CAS ammo period, why cant you just copy paste relevant code

2022-05-15 08:15 UTC, TiviPlus requested changes
Ill let you use rail gun ammo since you dont seem to be able to figure out how to make it non cas ammo

2022-05-15 08:15 UTC, TiviPlus commented on code/__DEFINES/dropship_equipment.dm
> +#define IS_INTERACTABLE (1<<5)
You need to undo this change idk why you did it

2022-05-20 19:12 UTC, merged