Xeno icons
tgstation/TerraGov-Marine-Corps pull request #10144
Opened 2022-05-06 08:15 UTC by goose4429

## About The Pull Request

Adds new minimap icons for xenos! Each tier and caste is now easily seen on the map. And animated silo icon!

## Why It's Good For The Game

Cool icons are good. 
Animated silo is very good.

## Changelog
:cl:
add: New xeno minimap icons
add: Animated silo icon
/:cl:

2022-05-06 08:26 UTC, Lumipharon commented
Very cool.

2022-05-06 08:38 UTC, Naaanii commented
Bless.

2022-05-06 08:59 UTC, Walarks commented
Georger has new red icon, very based

2022-05-06 16:55 UTC, TiviPlus requested changes

2022-05-06 16:55 UTC, TiviPlus commented on code/controllers/subsystem/minimaps.dm
> +/datum/controller/subsystem/minimaps/proc/add_marker(atom/target, zlevel, hud_flags = NONE, iconstate, icon = 'icons/UI_icons/map_blips.dmi', overlay_iconstates = null)
```suggestion
/datum/controller/subsystem/minimaps/proc/add_marker(atom/target, zlevel, hud_flags = NONE, iconstate, icon = 'icons/UI_icons/map_blips.dmi', list/overlay_iconstates)
```

2022-05-06 16:55 UTC, TiviPlus commented on code/controllers/subsystem/minimaps.dm
> +			blip.overlays += image(icon, i)
```suggestion
	for(var/i in overlay_iconstates)
		blip.overlays += image(icon, i)
```

2022-05-06 16:55 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
> +/mob/living/carbon/xenomorph/proc/update_leader_icon(isleader)
no autodoc

2022-05-07 22:07 UTC, Losenis commented
Jesus christ change the color from red to something else noticeable, the contrast is so low when it's downsized to actual minimap size that you can't tell them apart

2022-05-08 10:14 UTC, magatsuchi requested changes

2022-05-08 10:14 UTC, magatsuchi commented on code/controllers/subsystem/minimaps.dm
> +/datum/controller/subsystem/minimaps/proc/add_marker(atom/target, zlevel, hud_flags = NONE, iconstate, icon = 'icons/UI_icons/map_blips.dmi', list/overlay_iconstates)
please document your new arguement in the documentation above

2022-05-10 10:32 UTC, TiviPlus commented
@Kuro020

2022-05-10 17:25 UTC, Kuro020 approved these changes

2022-05-10 23:34 UTC, Wayland-Smithy commented
Not sure if you fixed this yet, but both larva and hivemind (its physical form not the core) appear as the `xenominion` icon.

2022-05-11 22:23 UTC, merged