ports the admin_delete proc
tgstation/TerraGov-Marine-Corps pull request #10157
Opened 2022-05-08 13:57 UTC by magatsuchi

## About The Pull Request

replaces `atom_delete` with `admin_delete`, which allows turf deletions upto the base turf (which still can't be removed)

also removes a null-caused stack_trace with the `getShuttle` proc because that was getting annoying

## Why It's Good For The Game

qol + admins should be able to delete walls

## Changelog
:cl:
/:cl:

2022-05-08 21:35 UTC, Lumipharon commented
What does this actually do? I was looking in discord, but I see admins delete turfs all the time without issue.

2022-05-08 21:38 UTC, Lumipharon commented
What does this actually do sorry? I was looking in discord, but I see admins delete turfs all the time. Or are they just doing a funni?

2022-05-09 01:04 UTC, magatsuchi commented
> What does this actually do sorry? I was looking in discord, but I see admins delete turfs all the time. Or are they just doing a funni?

they're using buildmode, which is a viable option, but the admin delete procs should be capable of scraping away tiles as well. this doesn't give admins the ability to make space tiles: it just means they can scrape away them now, down to the base turf, which is not space in most instances.

2022-05-10 10:47 UTC, TiviPlus requested changes

2022-05-10 10:47 UTC, TiviPlus commented on code/modules/admin/view_variables/admin_delete.dm
> +/client/proc/admin_delete(datum/delete)
Missing autodoc

2022-05-10 10:47 UTC, TiviPlus commented on code/modules/admin/view_variables/admin_delete.dm
> +		log_admin("[key_name(usr)] deleted [delete] [coords]")
use early returns

2022-05-10 10:47 UTC, TiviPlus commented on code/modules/admin/debug_verbs.dm
> +
```suggestion
	if(!check_rights(R_DEBUG))
		return

```
incorrect perms

2022-05-10 10:47 UTC, TiviPlus commented on code/modules/admin/holder.dm
> +	/client/proc/cmd_admin_delete
```suggestion
	/client/proc/cmd_admin_delete,
```

2022-05-10 10:47 UTC, TiviPlus commented on code/modules/admin/view_variables/admin_delete.dm
> +	var/coords = ""
Why is this completely missing any admin permissions/proccall/etc checks?

2022-05-12 23:43 UTC, magatsuchi commented
fuck

2022-05-12 23:43 UTC, closed without merging