Banish mass crashes to the shadowrealm
tgstation/TerraGov-Marine-Corps pull request #10164
Opened 2022-05-09 00:15 UTC by Lumipharon

## About The Pull Request

Have you ever crashed when loads of bullets are flying around?
Have you ever wanted to fire guns at absurdly high rates of fire?

This PR fixes an extremely old bug that has plagued the server and it seems our predecessors, crashing everyone on screen.
Shout out to @2whatever2 for discovering the source of the bug: When a turf is hit by a bullet, a short bullet bounce animation is played. When a large number of these bounces are done on a single turf, the act of actually REMOVING the image from the turf just randomly mass crashes everyone on screen.

This is a byond bug so who knows why it actually happens, but it seems they way these were being handled was kinda shit code anyway, so I changed it to overlays which has fixed the problem.

This now opens the doors to guns with all the dakka, like so.
https://user-images.githubusercontent.com/7869430/167321668-d3ea4fe4-bbb7-4519-ac08-504f03c81b78.mp4

## Why It's Good For The Game
Mass crashes for everyone on screen because 2 people hit the same wall is bad.
BRRRT is good.

## Changelog
:cl:
fix: Fixed an old bug that would cause screen wide client crashes due to large amounts of shooting
/:cl:

2022-05-09 00:17 UTC, Arctrooper8 commented
Super SG minigun is now possible
![image](https://user-images.githubusercontent.com/95723150/167321791-3692970e-87f6-42cb-b031-dcdc78c3d850.png)

2022-05-09 07:26 UTC, lKiseki commented
madlads
they did it
they fucking fixed it

2022-05-10 10:00 UTC, TiviPlus requested changes

2022-05-10 10:00 UTC, TiviPlus commented on code/modules/projectiles/projectile.dm
> +	update_icon()
```suggestion
		add_overlay(I)
		addtimer(CALLBACK(src, .proc/cut_overlay, I), 3, TIMER_CLIENT_TIME)

```

2022-05-10 22:00 UTC, Lumipharon commented on code/modules/projectiles/projectile.dm
> +	update_icon()
Oh, update_icon isn't needed, honk.

2022-05-11 22:24 UTC, BraveMole reviewed
timer abuse e_e

2022-05-14 11:14 UTC, TiviPlus commented
Flick overlay already used a timer so its an improvement perf wise

2022-05-14 11:14 UTC, TiviPlus commented
misclick

2022-05-14 11:14 UTC, merged