Turret stuff - less broken edition
tgstation/TerraGov-Marine-Corps pull request #10170
Opened 2022-05-09 18:56 UTC by DeltaFire15

## About The Pull Request
Addresses issues discussed in #10152 in a better way than that PR which had a major oversight causing some less than wanted behavior.

Firstly, doors no longer close when dense objects are located on their tile. For mobs, it still varies depending on if the safeties are on or off, although this is not the case for dense objects (The alternative would be to just crush any solid object on their tile when closing which while funny may be annoying to deal with if it happens accidentally, and not more effective than this version).
Additionally, to combat tad turretbussing and simillar methods, aswell as taking into account xenomorph turrets already having a minimum distance to avoid pretty much what marine turret stacking achieves, marine turrets now have a minimum deploy distance they require from eachother simillar to xeno turrets, although theirs is lower (marine turret: 4 tiles for now, xeno turret: 6 as before). Anything lower would be too low to effectively combat the problem and I did not want to make it any higher than neccessary, so this should be a sweet spot that should not interfere with using sentries in their intended way (usually one covering a given area to alert marines and deter weaker xenos), whilst preventing stacking a bunch of turrets together. This affects normal sentries aswell as build-a-sentries, although not other deployables like deployable MG nests or other things of that kind. Note, you can still run the tad with turrets, but will be limited to less coverage than before.

Also once again adds the improvement to sentry deployment because that was the one part in the PR that wasn't broken but got reverted anyways.

## Why It's Good For The Game
The era of the tad turret bus has been long enough. This should reduce the sheer oppressiveness of it as a mobile turret platform aswell as other situations with major sentry stacking, while keeping their general purpose aswell as options in place.

## Changelog
:cl:
code: Once again makes sentries less likely to bypass their turf placement conditions since it got reverted.
balance: Doors no longer close when a dense object is blocking them.
balance: Marine turrets have a minimum placement distance of four tiles, akin to xenomorph turrets, for which it is six.
/:cl:

2022-05-09 19:32 UTC, hyper2snyper commented
I *Really* don't like the distance restrictions.

2022-05-09 20:12 UTC, Derrick2Electricboogaloo commented
LAME ass distance restrictions

2022-05-09 20:43 UTC, UsernameIs-UnAvailable commented
I feel that a better solution to tad turretbussing is to remove two (if not all) of the deployable sentries attachments from the hangar until someone decides to fix the exploit.

2022-05-09 22:40 UTC, Lumipharon commented
> I feel that a better solution to tad turretbussing is to remove two (if not all) of the deployable sentries attachments from the hangar until someone decides to fix the exploit.

This.
The ability to remove sentries from the modules is the real problem. Without that, battle tad means completely compromising fob security (or lots of BAS)

2022-05-10 06:13 UTC, Derrick2Electricboogaloo commented
> 

Amenable to this. I agree they should not be removable.

2022-05-10 10:20 UTC, TiviPlus approved these changes
Code ok balance I didnt read about it

2022-05-10 12:44 UTC, AGasCanister commented
funny how you say the title says "Turret stuff - less broken edition" and at the same time you limit how many sentries can be placed in an area instead of making Tad frontal turrets not movable

2022-05-10 14:27 UTC, DeltaFire15 commented
> funny how you say "Turret stuff - less broken edition" and at the same time you limit how many sentries can be placed in an area instead of making Tad frontal turrets not movable

You do know this is not about the turrets you can attach to dropships with the exo, right?

2022-05-10 15:52 UTC, Losenis commented
>Alternatively, I could just completely blacklist the tad from deployable turrets but this seemed like a better middle ground that also catches some other questionable situations.

If that isn't a sledgehammer approach I don't know what is. Just make the turrets not removable from the modules or have less modules appear on the map as stopgap towards the earlier. Not only does that fuck over any semblance of protection from the tad (The frontal turrets are an actual detriment because they shoot the fucking glass), you're only going to see those 4 turrets be deployed elsewhere.

2022-05-10 18:51 UTC, KornFlaks requested changes

2022-05-10 18:51 UTC, KornFlaks commented on code/datums/elements/deployable_item.dm
>  		user.balloon_alert(user, "You start deploying...")
```suggestion
		user.balloon_alert(user, "Deploying...")
```

Less words the better. The font for balloon alerts are too big...

2022-05-10 18:51 UTC, KornFlaks commented on code/datums/elements/deployable_item.dm
> +					user.balloon_alert(user, "Too close to other sentries, minimum distance is [MARINE_MIN_TURRET_DISTANCE].")
```suggestion
					user.balloon_alert(user, "Other sentries too close")
					to_chat(user, span_warning("Too close to other sentries, minimum distance is [MARINE_MIN_TURRET_DISTANCE]."))
```
Balloon alert is way too long. 5 words or less is ideal and no punctuation,

2022-05-10 18:51 UTC, KornFlaks commented on code/datums/elements/deployable_item.dm
> +			user.balloon_alert(user, "There is insufficient room to deploy [item_to_deploy]!")
```suggestion
			user.balloon_alert(user, "Insufficient room")
```

2022-05-10 18:51 UTC, KornFlaks commented on code/datums/elements/deployable_item.dm
> +					user.balloon_alert(user, "Too close to other sentries, minimum distance is [MARINE_MIN_TURRET_DISTANCE].")
```suggestion
					user.balloon_alert(user, "Other sentries too close")
					to_chat(user, span_warning("Too close to other sentries, minimum distance is [MARINE_MIN_TURRET_DISTANCE]."))
```

2022-05-10 18:51 UTC, KornFlaks commented on code/modules/mining/remote_fob/remote_fob_actions_misc.dm
> +			to_chat(owner, span_warning("This location is too close to other sentries, minimum distance is [MARINE_MIN_TURRET_DISTANCE]."))
```suggestion
					user.balloon_alert(user, "Other sentries too close")
					to_chat(user, span_warning("This location is too close to other sentries, minimum distance is [MARINE_MIN_TURRET_DISTANCE]."))
```

2022-05-10 18:51 UTC, KornFlaks commented on code/modules/mining/remote_fob/remote_fob_actions_misc.dm
> +			to_chat(owner, span_warning("This location is too close to other sentries, minimum distance is [MARINE_MIN_TURRET_DISTANCE]."))
```suggestion
					user.balloon_alert(user, "Other sentries too close")
					to_chat(user, span_warning("This location is too close to other sentries, minimum distance is [MARINE_MIN_TURRET_DISTANCE]."))
```

2022-05-11 21:45 UTC, BraveMole commented
> Turret placement not having minimum distance is already balanced due to turrets EXPLODING and damaging everything around it

What tanya said

2022-05-11 21:45 UTC, closed without merging