Adds and Replaces To_Chat() With Balloon_Alerts()
tgstation/TerraGov-Marine-Corps pull request #10171
Opened 2022-05-09 19:26 UTC by KornFlaks

## About The Pull Request

Doing a pass through Xeno Structures and replacing some of the to_chat messages with (arguably) better looking balloon alert messages.

Does not remove nor replaces all to_chat messages.

Atomized by file for easier review.

## Why It's Good For The Game

Shamelessly copy pasting what RipGrayson said in their (now closed) PR:

> We're moving away from the philosophy of needing to stare at chat in order to see what's going on, runechat did it for speech, balloon_alerts do it for actions. It's just so much easier to see what's going on by looking at your character than it is to dig around in a bunch of text.

> On the aesthetic side it actually looks really cool to see overhead notifications like "Franklin Ramis fixes the internal wiring of platinum miner" or "Queen (236) starts emitting pheremones", it makes us look very smooth.

> So by implementing this not only do we look fancy, but it also enhances team cooperation because xenos/marines can see what their teammates are doing while being focused on combat. (Not that they couldn't before, they would just have to scroll through chat, which made it impractical).

## Changelog
:cl:
qol: Added balloon alerts for xeno structure interactions.
/:cl:

2022-05-10 10:17 UTC, TiviPlus requested changes

2022-05-10 10:17 UTC, TiviPlus commented on code/modules/xenomorph/xeno_structures.dm
>  	return TRUE
```suggestion
	balloon_alert(user, "You only scrape it")
	return TRUE
```
Wordings a bit wierd is this better?

2022-05-10 10:17 UTC, TiviPlus commented on code/modules/xenomorph/xeno_structures.dm
> +		balloon_alert(X, "Filling in tunnel")
```suggestion
		balloon_alert(X, "Filling in tunnel...")
```
This might be better for signifying how its the start

2022-05-10 10:17 UTC, TiviPlus commented on code/modules/xenomorph/xeno_structures.dm
> +		balloon_alert(X, "Removing \the [src]")
```suggestion
		balloon_alert(X, "Removing...")
```

2022-05-10 10:17 UTC, TiviPlus commented on code/modules/xenomorph/xeno_structures.dm
> +			balloon_alert(X, "Stop removing \the [src]")
```suggestion
			balloon_alert(X, "Stoped removing")
```

2022-05-10 10:17 UTC, TiviPlus commented on code/modules/xenomorph/xeno_structures.dm
> +		balloon_alert(X, "Abort refilling")
```suggestion
		balloon_alert(X, "Aborted refilling")
```

2022-05-10 10:17 UTC, TiviPlus commented on code/modules/xenomorph/xeno_structures.dm
> +		balloon_alert(X, "Tearing \the [src]")
```suggestion
		balloon_alert(X, "Destroying...")
```
No src here

2022-05-10 10:17 UTC, TiviPlus commented on code/modules/xenomorph/xeno_structures.dm
> +		balloon_alert(X, "Uprooted [src]")
A lot of the balloon alerts for the fruits below this point use name inserts ([src]) reword those pls

2022-05-10 10:17 UTC, TiviPlus commented
good pr

2022-05-10 18:11 UTC, KornFlaks commented
Done.

2022-05-11 22:33 UTC, BraveMole approved these changes

2022-05-11 22:33 UTC, merged