Fix call of the burrowed unintentional larva queue leaves
tgstation/TerraGov-Marine-Corps pull request #10173
Opened 2022-05-09 22:44 UTC by Wayland-Smithy

## About The Pull Request

Since `attempt_to_join_as_larva()` acts like a toggle now if you are already in the queue when you click the link in chat to Join as a Larva the result will be you get booted as if you clicked the regular button.

This adds a check to prevent that from happening.

Fixes: #10063

## Why It's Good For The Game

Fix good.

## Changelog
:cl:
fix: Fixed call of the burrowed unintentional larva queue leaves.
/:cl:

2022-05-10 10:10 UTC, TiviPlus approved these changes
rest lgtm

2022-05-10 10:10 UTC, TiviPlus commented on code/modules/mob/dead/observer/observer.dm
> +			return
```suggestion
			to_chat(ghost, span_warning("You are already in the queue to become a Xenomorph."))
			return
```

2022-05-11 06:27 UTC, BraveMole requested changes
Does this verb needs to exist ?

2022-05-11 17:22 UTC, Wayland-Smithy commented
Idk, and I don't think that is a good reason to block the PR. It can always be deleted wholesale later.

2022-05-14 11:13 UTC, merged

2022-05-14 11:13 UTC, TiviPlus commented
Fix now remove later