Deployables check whether their turf is blocked more reliably
tgstation/TerraGov-Marine-Corps pull request #10196
Opened 2022-05-12 23:03 UTC by DeltaFire15

## About The Pull Request
Title. Simply makes sure that deployables check whether their tile is blocked after the do_after is finished as trusting conditions to remain the same is usually a bad idea. Thats it.

## Why It's Good For The Game
Fix man good.

## Changelog
:cl:
fix: Deployables should be less likely to have issues with turf blocking conditions changing during deployment.
/:cl:

2022-05-13 12:21 UTC, Naaanii commented
Can you post videos of testing this? Reliably on button tiles, shutter tiles, grass tiles and cade tiles.

2022-05-13 13:19 UTC, DeltaFire15 commented
> Can you post videos of testing this? Reliably on button tiles, shutter tiles, grass tiles and cade tiles.

No, go look at the diff.
I'm not recording stuff for something that changes nothing about the rules of placement and merely double-checks.

2022-05-15 08:13 UTC, TiviPlus requested changes

2022-05-15 08:13 UTC, TiviPlus commented on code/datums/elements/deployable_item.dm
> +			return
```suggestion
			location.balloon_alert(user, "No room to deploy")
			return
```

2022-05-15 20:12 UTC, TiviPlus approved these changes

2022-05-15 20:12 UTC, merged