Removes under barrel stuff from SH-15
tgstation/TerraGov-Marine-Corps pull request #10195
Opened 2022-05-12 22:43 UTC by Arctrooper8

## About The Pull Request

Removes:
Under barrel flamer
Plasma pistol
Under barrel grenade launcher
Under barrel pepperball gun 

## Why It's Good For The Game

Remember when we spent all that time removing under barrel attachments from shotguns because it was considered really strong? I am left wondering why the SG-15 was barely touched. While it may not have the buckshot which has become ubiquitous with shotgun anger, it does still have slugs with their good damage/stun and one should not underestimate flechette. Combining a shotgun that will almost always be using stunning slugs with fire (which has fun effects such as disabling pheroes and forcing you to stun yourself to put out the fire or die slowly) is generally considered unfun to fight against. 

In fact, the SH-15 is the only shotgun with under barrel attachments, this is mostly likely due to the fact is actually in the rifles file (other then the Italian shotgun with an inbuilt UGL).

Overall this is mostly for the same reasons it was remove from every other shotgun.

## Changelog
:cl:
balance: Removed under barrel attachments from the SH-15
/:cl:

2022-05-12 23:11 UTC, Naaanii commented
Pretty sure TX-15 could always have underbarrel stuff before more powercreep was introduced. It's also the only shotgun that takes magazines. I think having underbarrel is a good niche for this gun.

2022-05-12 23:12 UTC, Lumipharon commented
Only the plasma pistol is an issue, if at all. The rest are entirely non issues.

It was a deliberate choice to keep underbarrels on it.

It uses different (weaker) ammo that normal shotguns, the slugs have notably worse CC. It's coded as a rifle as that's functionally what it is.

2022-05-12 23:27 UTC, Arctrooper8 commented
> Only the plasma pistol is an issue, if at all. The rest are entirely non issues.
> 
> It was a deliberate choice to keep underbarrels on it.
> 
> It uses different (weaker) ammo that normal shotguns, the slugs have notably worse CC. It's coded as a rifle as that's functionally what it is.

I think both fire attachments are an issue, as while the SG-15 slug may not be as strong as the normal SH slug it still causes knockback which stuns you and makes you much easier to hit with the plasma pistol and flamer.
And the UGL niche is already taken by the italian shotgun (which is seasonal to be fair)
And let's be honest, nobody uses the mini pepperball gun.

2022-05-13 12:13 UTC, Naaanii commented
> > Only the plasma pistol is an issue, if at all. The rest are entirely non issues.
> > It was a deliberate choice to keep underbarrels on it.
> > It uses different (weaker) ammo that normal shotguns, the slugs have notably worse CC. It's coded as a rifle as that's functionally what it is.
> 
> I think both fire attachments are an issue, as while the SG-15 slug may not be as strong as the normal SH slug it still causes knockback which stuns you and makes you much easier to hit with the plasma pistol and flamer. And the UGL niche is already taken by the italian shotgun (which is seasonal to be fair) And let's be honest, nobody uses the mini pepperball gun.

It knocks back, but doesn't stun, slowdown is a given as the weapon relies on landing consistent shots. Once again this weapon is more like a rifle rather than an actual shotgun so having underbarrel attachments on it is fine. If anything, deleting plasma pistol would be the only solution if it was an actual issue as the auto shottie has had ubf for a long time and while strong, it has never been an actual issue.

2022-05-13 19:43 UTC, lovegreenstuff commented
hey what's up guys it's ya boi

uhhh the original shotgun underbarrel pr that i made for pette intentionally left out tx15 because it was mostly a matter of burst damage, aka buck, being combo'd into shit like another buck or an impact nade and basically oneshotting people

tx15 only does like 85 damage max per shot compared to like 170 for t39 buck, so we just thought it wasnt terribly necessary

since then, impact nades got sent to the shadow realm, flamer damage on hit was set to zero, and masterkey firerate got nerfed, so it's probably less necessary to do so now.

but hey if you want to fuckin uhhhhh keep goin' with this pr, go for it mang

2022-05-14 01:53 UTC, nutsupreme commented
salt pr

2022-05-14 04:20 UTC, Pariah919 requested changes
50/50 on Plasma pistol, I'm fine with it being gone, but I feel T18 carbine is pertty equivalent anyway.
Hard no on the rest of them.

2022-05-15 06:53 UTC, Arctrooper8 commented
The people have spoken. Considering that the SH-15 has different ammo which does reduced damage, and the unique niche having under barrels gives this gun, it is obviously better to let them keep the under barrel attachments.
Except the plasma pistol, because it sucks.
That repulsive duct taped DIY puke green fire pistol, it shouldn't have ever been an attachment.

2022-05-15 08:20 UTC, BraveMole commented
SH 15 needs it niche, and having attachments is fine

2022-05-15 08:20 UTC, closed without merging