You can now unextend and extend the T72.
tgstation/TerraGov-Marine-Corps pull request #10205
Opened 2022-05-14 01:22 UTC by Pariah919

## About The Pull Request
Title.
It starts unextended, and will be normal sized, but cannot fire.
Extending it will make you able to fire, but will make it bulky.

## Why It's Good For The Game
Makes it a bit more unique overall. I think I could make a disposable RPG that can't be extended under any circumstances in another PR, maybe.

## Changelog
:cl:
balance: You can extend and unextend the T-72.
/:cl:

2022-05-14 08:45 UTC, Lumipharon commented
Neat

2022-05-14 11:30 UTC, TiviPlus commented
Whats a t72

2022-05-16 17:10 UTC, Kuro020 approved these changes

2022-05-16 17:11 UTC, Kuro020 commented
> Whats a t72

a gun

2022-05-17 07:06 UTC, TiviPlus requested changes

2022-05-17 07:06 UTC, TiviPlus commented on code/modules/projectiles/guns/specialist.dm
> +	var/extended = 0
Use bools properly

2022-05-17 07:06 UTC, TiviPlus commented on code/modules/projectiles/guns/specialist.dm
> +		extended = !extended
Early return

2022-05-18 06:44 UTC, TiviPlus commented
I said early return the do after not the extended

2022-05-26 07:07 UTC, merged