Adds and Replaces To_Chat() With Balloon_Alerts() in Defiler Abilities
tgstation/TerraGov-Marine-Corps pull request #10221
Opened 2022-05-15 17:46 UTC by KornFlaks

## About The Pull Request

Some more balloon alerts. A large part of these now originate above the target of the ability so hopefully these will work.

## Why It's Good For The Game

Shamelessly copy pasting what RipGrayson said in their (now closed) PR:

> We're moving away from the philosophy of needing to stare at chat in order to see what's going on, runechat did it for speech, balloon_alerts do it for actions. It's just so much easier to see what's going on by looking at your character than it is to dig around in a bunch of text.

> On the aesthetic side it actually looks really cool to see overhead notifications like "Franklin Ramis fixes the internal wiring of platinum miner" or "Queen (236) starts emitting pheremones", it makes us look very smooth.

> So by implementing this not only do we look fancy, but it also enhances team cooperation because xenos/marines can see what their teammates are doing while being focused on combat. (Not that they couldn't before, they would just have to scroll through chat, which made it impractical).

## Changelog
:cl:
qol: Defiler actions now have balloon alerts.
/:cl:

2022-05-18 06:56 UTC, TiviPlus requested changes
Rest lgtm

2022-05-18 06:56 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
> +	owner.balloon_alert(owner, "Defile ready")
Do we really want to add balloon alerts for cooldown finish? This is already visually and audio respresented so this feels more like clutter

2022-05-18 06:56 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
> +			A.balloon_alert(owner, "No effect")
```suggestion
			A.balloon_alert(owner, "Cannot effect")
```

2022-05-18 06:56 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
> +			A.balloon_alert(X, "Cannot reach, not adjacent")
```suggestion
			A.balloon_alert(X, "Cannot reach")
```

2022-05-18 06:56 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
>  	to_chat(X, span_xenodanger("Our stinger successfully discharges accelerant into our victim."))
Do we really want balloon alerts here?

2022-05-18 06:56 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
> +		X.balloon_alert(X, "Emit gas aborted, staggered")
Isnt this already visually represented?

2022-05-18 06:56 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
> +			X.balloon_alert(X, "Emit gas aborted, disabled")
ditto

2022-05-18 06:56 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
> +		alien_egg.balloon_alert(X, "Canceled injection")
balloon_alert_to_viewers?

2022-05-18 06:56 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
>  	return succeed_activate()
Inserts feel like a maybe bad idea here

2022-05-18 06:56 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
>  	to_chat(X, span_xenodanger("Our spines fill with virulent toxins!")) //Let the user know
remove to chat here?

2022-05-18 06:56 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
>  	to_chat(X, span_xenodanger("We are no longer benefitting from [src].")) //Let the user know
ditto

2022-05-19 06:13 UTC, BraveMole approved these changes

2022-05-19 06:13 UTC, merged