Caustic upgrade cades cannot be melted.
tgstation/TerraGov-Marine-Corps pull request #10232
Opened 2022-05-17 19:02 UTC by Pariah919

## About The Pull Request
![image](https://user-images.githubusercontent.com/46353991/168890111-be75d850-6c98-4d7d-9f32-6b0dd8eb6df2.png)
probably more balacned and enjoyable than #10227, but if people want 227 they can reopen it.

## Why It's Good For The Game
More balanced then sandbags, overall. And I feel like foward FOBs could use this. You need quite a bit of metal to make this work.

## Changelog
:cl:
balance: Caustic armor cades are no longer meltable by vomit acid.
/:cl:

2022-05-17 19:03 UTC, Kuro020 commented
better balanced than the sandbag pr

2022-05-17 21:23 UTC, Lumipharon commented
Is this really a good idea?

2022-05-17 21:38 UTC, BraveMole requested changes
You can remove a upgrade.
Also you need enable the xeno meltable flag, not set the whole bitfield

2022-05-18 18:54 UTC, Naaanii commented
This makes more sense as opposed to the sandbag PR as they can still be slashable and spat at and require engineers to set it up. I'd be down to increase the mat cost per upgrade too and maybe buff the other cade upgrades as they seem very underwhelming.

2022-05-18 23:35 UTC, Ragecrabbo commented
> This makes more sense as opposed to the sandbag PR as they can still be slashable and spat at and require engineers to set it up. I'd be down to increase the mat cost per upgrade too and maybe buff the other cade upgrades as they seem very underwhelming.

Honestly this, razorwire seems to be the only cade upgrade you see regularly used in rounds (and actually have a noticable effect) unless engies get bored and are sitting on unlimited req points.

2022-05-18 23:39 UTC, Lumipharon commented
Is this actually a problem though, it's not like anyone thinks fobbing is too weak right? I mean I hope it won't happen, but if you have acid proof cades and keep repairing them, you will HAVE to melee your way through them, which is difficult if ungas have enough firepower.

2022-05-20 14:04 UTC, FosterGrime-Heymynameslouie commented
spedd merhg

2022-05-21 01:46 UTC, Naaanii commented
> Is this actually a problem though, it's not like anyone thinks fobbing is too weak right? I mean I hope it won't happen, but if you have acid proof cades and keep repairing them, you will HAVE to melee your way through them, which is difficult if ungas have enough firepower.

True, but they also can be spat at as they are not immune to spitting. All this really does is stops one drone from freely melting a whole line of unattended cades, or walling and corner melting cades but a runner can still slash them all down or a spitter can still spit them from range.

Caustic cades already feel rather underwhelming with how strong spit castes are, so this change seems alright and doesn't seem too oppressing either.

2022-05-21 08:04 UTC, breadhunt commented
To me this seems like just more of a buff to cading off flanks/unattended cades. Melting isn't that useful in sieges (with competent engis) usually. 

But having to slash an entire cadeline with barbed wire _is_ annoying as FUCK

If it's unmeltable, it shouldn't have barbed wire. Grayson said something similar in sandbag PR, it's just shitty to deal with.
Other than that good PR

2022-05-22 14:56 UTC, BraveMole commented
I'm not sure my comment was clear enough, so:

You can remove upgrades, yet you are not resetting the flags there, leading to a bug

2022-05-24 15:47 UTC, CursedBirb reviewed
Line 773 add this:

resistance_flags = XENO_DAMAGEABLE

Im not a coder but worked for me on local and when removed upgrade acid worked again

2022-05-27 19:20 UTC, Pariah919 commented
#10306 is just this but not hit by smallscale burnout

2022-05-27 19:20 UTC, closed without merging