All Xenos Now Have Overwatch Ability Through Chat
tgstation/TerraGov-Marine-Corps pull request #10255
Opened 2022-05-20 03:28 UTC by KornFlaks

## About The Pull Request

All main caste xenos (not minions) and larva now have the ability to overwatch other xenos through chat (F) button.

However, only the queen is able to arbitrarily select a xeno from the hive to overwatch without seeing their voice in the chat (simply to prevent increasing the number of buttons).

## Why It's Good For The Game

Now larva and young runners can rest inside the safety of the silo and grab popcorn to watch the rest of the hive get railed at the front line without having to actually risk their own lives to see how it is going.

![image](https://user-images.githubusercontent.com/29745705/169444624-f7951d0d-adcf-4557-af4a-a0cd759aa75d.png)

The drone is the player in this image and can now "overwatch" the queen via the (F) button in the chat. However, only the queen's overwatch will result in the eye appearing on the xeno HUD overlay.

## Changelog
:cl:
add: All xenos now have the ability to overwatch other xenos through the chat (F) button.
/:cl:

2022-05-20 04:23 UTC, XSlayer300 commented
But wait, how about Hiveminds and Shrikes? Can they still view xenos without them talking?

2022-05-20 04:38 UTC, KornFlaks commented
Shrikes never had overwatch. With this PR, now they do but they dont get the list though, only queen does.

Hivemind are completely unchanged. This PR does not change anything related to hiveminds.

2022-05-20 14:02 UTC, FosterGrime-Heymynameslouie commented
blessed pr spped merhg

2022-05-20 22:18 UTC, Naaanii commented
Hmm, I think this would be better to be given to hive leaders only.

2022-05-21 09:16 UTC, BraveMole requested changes
this pr does not what you claim it does, I think you confused both prs.

Anyway, adding a button to everyone sucks a bit. Giving everyone hive watch, yes, but that should be done use hivemenu

2022-05-21 09:23 UTC, BraveMole requested changes

2022-05-21 09:23 UTC, BraveMole commented on code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
> +					continue
you can concatenate that with && and else if

2022-05-21 11:02 UTC, Durbles commented
This is a very good change.

2022-05-21 20:23 UTC, private-tristan commented
before:
> "tadpole landing" - young runner (305)
"where" 
"where?" 

after:
> "tadpole landing" - young runner (305)
"cool"

2022-05-22 08:43 UTC, BraveMole approved these changes

2022-05-22 08:43 UTC, merged

2022-05-23 07:28 UTC, Al-1ce commented
> Shrikes never had overwatch. With this PR, now they do but they dont get the list though, only queen does.
> 
> Hivemind are completely unchanged. This PR does not change anything related to hiveminds. Hivemind never had a list either. Players always had to ask someone to talk in chat in order to jump to them.

I think giving shrike the eye-icon or a variation of it would be fair.