Underbarrel weapon rebalance
tgstation/TerraGov-Marine-Corps pull request #10259
Opened 2022-05-21 01:00 UTC by Lumipharon

## About The Pull Request
This PR adds wield time and wielded movement speed maluses to underbarrel weapon attachments.

Underbarrel weapons provide marines huge damage and/or utility buffs with literally zero downside.
This is in comparison with most other attachments that have some sort of downsides for the benefits they provide.

The changes are pretty mild. All 4 underbarrels now add 0.1 second of wield time, and 0.1 extra slowdown with the exception of the plasma pistol, which has 0.2 extra slowdown (as it is generally more powerful with instant damage and fire application at range).

## Why It's Good For The Game
Make underbarrel weapons slightly more reasonable

## Changelog
:cl:
balance: Underbarrel weapons now slightly impact wield times and wielded movement speed for their parent guns.
/:cl:

2022-05-21 01:28 UTC, Naaanii commented
Wield time is good, wield speed seems kind of lame.

2022-05-21 01:39 UTC, Pariah919 commented
I don't really see why you'd nerf all the underbarreled attachments, and honestly other than PP and UBF they're kinda mediocre in general.

2022-05-21 05:07 UTC, Lumipharon commented
> I don't really see why you'd nerf all the underbarreled attachments, and honestly other than PP and UBF they're kinda mediocre in general.

It's 0.1, which is negligible. No one's going to stop using them because of it, and a whole bunch of attachments that provide very tame benefits have genuine drawbacks, compared to underbarrel weapons which have absolutely none, which is super inconsistant.

> Miniflamer is pretty much as good as the plasma pistol, I don't see the need for snowflake nerfs particularly. Perhaps dealing with the attachments themselves would be a better option rather than nerfing underbarrel as a whole.

PP is objectively the most powerful underbarrel since it has the 40 damage flat + fire with no real range limit and 10 shots.
UGL can do more damage but has only 2 shots and no more impact grenades so are less reliable, and you can't use it up close.
MK has a 0.6 damage modifer and only 3 shots. It's only real strength is it gives you stuns, which is OK I guess.
Miniflamer is good, but it got the on hit damage fixed + only 4 tile range, so it's good for area denial but not for killing things.

2022-05-21 06:54 UTC, Naaanii commented
> > I don't really see why you'd nerf all the underbarreled attachments, and honestly other than PP and UBF they're kinda mediocre in general.
> 
> It's 0.1, which is negligible. No one's going to stop using them because of it, and a whole bunch of attachments that provide very tame benefits have genuine drawbacks, compared to underbarrel weapons which have absolutely none, which is super inconsistant.
>
0.1 alone is negligible but it still stacks up with other slowdown values. Hitting underbarrels with a double whammy nerf is also wack. One drawback seems good enough and nerfing underbarrel as a whole seems kind of unnecessary.

2022-05-21 07:33 UTC, goose4429 commented
Smol changes, seem reasonable. But larger underslugs should have more penalty, and plasma pistol is the smallest of all. I'd make them all the same.

2022-05-23 02:36 UTC, Al-1ce commented
> Smol changes, seem reasonable. But larger underslugs should have more penalty, and plasma pistol is the smallest of all. I'd make them all the same.


Agreed. It's overall much more tactile to add a standardized penalty rather than selectively changing slightly different variables just because one is bigger and what-not.

2022-05-23 05:26 UTC, Lumipharon commented
Equalised and added pepperball because I forgot it exists.

2022-05-23 07:17 UTC, Al-1ce commented
> Equalised and added pepperball because I forgot it exists.

Looks good. I've also noticed how almost every other attachment came with a downside, whereas the only downside underbarrels had was that you could pick one. B-18 underslungs are no more!

2022-05-28 17:17 UTC, Lauwma commented
Please do not add slowdown, marines are already quite slowed. Just increase wield time it makes sense.

2022-05-28 18:02 UTC, BraveMole requested changes
I don't like aim slowdown added. wield time is fine

2022-05-30 00:50 UTC, Lumipharon commented
Changed to wield time only

2022-05-31 20:59 UTC, BraveMole requested changes

2022-05-31 20:59 UTC, BraveMole commented on code/modules/projectiles/gun_system.dm
> +	var/aim_speed_mod	= 0
unused

2022-06-01 15:47 UTC, BraveMole approved these changes

2022-06-01 15:47 UTC, merged