killing the codebase one step at a time
tgstation/TerraGov-Marine-Corps pull request #10275
Opened 2022-05-23 03:48 UTC by Mechanelize

## About The Pull Request

inadvertent caste_flags refactor to make rav immune to tanglefoot gas

## Why It's Good For The Game

it is?

## Changelog
:cl:
add: Added new mechanics or gameplay changes
add: Added more mechanics or gameplay changes
expansion: Expands content of an existing feature
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2022-05-23 03:53 UTC, hyper2snyper requested changes
I also didnt see a definition for can_flags anywhere.
btw 'can_flags' is a bad name
make it something like 'xeno_ability_flags'

2022-05-23 03:53 UTC, hyper2snyper commented on code/__DEFINES/mobs.dm
> +#define CASTE_CAN_BE_LEADER (1<<49)
49

2022-05-23 03:53 UTC, hyper2snyper commented on code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
> +	can_flags = |CASTE_CAN_HOLD_FACEHUGGERS|CASTE_CAN_HOLD_JELLY|CASTE_CAN_CORRUPT_GENERATOR|CASTE_CAN_BE_GIVEN_PLASMA
```suggestion
	can_flags = CASTE_CAN_HOLD_FACEHUGGERS|CASTE_CAN_HOLD_JELLY|CASTE_CAN_CORRUPT_GENERATOR|CASTE_CAN_BE_GIVEN_PLASMA
```

2022-05-23 06:15 UTC, KornFlaks commented
> make it something like 'xeno_ability_flags'

Definitely not. Since we have xeno action flags (XACT_USE) and abilities are filed under that.

Maybe xeno_mod_flags for modifiers. Honestly, xeno_can_flags is the most appropriate.

2022-05-23 07:01 UTC, Al-1ce commented
I have the strangest feeling that adjusting xeno flags will result in a shitstorm of bugs.

2022-05-26 21:51 UTC, TiviPlus requested changes
Atomize the balance change please

2022-05-29 08:51 UTC, merged