Maturity and evolution towers only work after shutters opening
tgstation/TerraGov-Marine-Corps pull request #10272
Opened 2022-05-22 15:16 UTC by BraveMole

## About The Pull Request

Tittle

## Why It's Good For The Game

Will discourage fob hugging and xenos immediatly crushing marines. This is more in line with other xeno building, like silos which are not producing anything before the shutters open

This is made with nuclear war in mind, I hope this won't create too much trouble in distress

## Changelog
:cl:
balance: Maturity and evolution towers only work after shutters opening
/:cl:

2022-05-22 16:17 UTC, Naaanii commented
I feel like this only addresses the early game and doesn't do much to curb the powerspike Xenos generally get with their respawns. A way to rework how fast Xenos mature or where towers can be placed would be neat, considering all towers are usually placed in caves by the silo, but forcing them out in the open leaves them open to OBs and other artillery.

2022-05-23 02:30 UTC, Al-1ce commented
This might _seem_ like a sensible change - however as mentioned above would only be marginally effective until the shutters are down, ultimately giving marines much more time to ungaball a weaker and less prepared hive. 

I don't see this harming Nuclear War too much, although Distress is definitely going to be a marine-major most of the time with a change like this in store.

With that said, Marines at round-start have access to a _plethora_ of deadly and effective tools for completely free. Xeno's shouldn't be penalized for a lack of utilization by the opposing team, vice-versa.

2022-05-23 06:51 UTC, Dzhimax commented
the author of this shit is the greatest clown in the history of the world

2022-05-27 16:30 UTC, goose4429 commented
From my experience (300h as xeno, 100h as queen, if you don't think that enough then disregard comment) - evolution towers are literal trash, because you are only constrained by maturity. And maturity towers are mostly only useful after all primos are bought. Roundstart you are growing faster by buying primos. Mid-game primos are again more useful because they have combat impact. Not saying a bad PR, but they definitely need a buff.

2022-06-04 11:32 UTC, TiviPlus requested changes
Only for maturity towrs cus evo is already bad enough

2022-06-10 20:29 UTC, closed without merging