Activated intel computers now show on minimap
tgstation/TerraGov-Marine-Corps pull request #10289
Opened 2022-05-25 16:07 UTC by breadhunt

## About The Pull Request

Intel computers now show on the minimap to both marines and xenos.
They only show when activated by the event, and disable when they're used

![image](https://user-images.githubusercontent.com/80229419/170307132-838e4ef4-cbf7-4350-8ed4-363a51c703fc.png)

Shout at me if minimap sprite seems too obtrusive, but intel computers usually aren't in the way of fighting so I don't think it'll be too much of an issue

## Why It's Good For The Game

The biggest biggest issue with intel computers is that _nobody fucking knows that they exist._ Ever, at all. Which is a shame because they're cool as fuck and really spice up gameplay.
Clearly showing them on minimap will both make them more relevant and easier to understand for new players (hopefully)

## Changelog
:cl:
add: Activated intel computers now show on minimap
/:cl:

2022-05-25 16:34 UTC, Walarks commented
Making intel great again... interesting...

2022-05-25 16:35 UTC, goose4429 commented
You're a hero we don't deserve

2022-05-25 16:47 UTC, Araulius commented
downvoting specifically because this fucks over my stealth engineer ops that I love doing.

2022-05-25 19:02 UTC, breadhunt commented
> downvoting specifically because this fucks over my stealth engineer ops that I love doing. I'm malding bro.

I tried to be specific in the PR description but apparently I failed. Oops

The icon is shown when the _event_ activates it and makes the computer able to be used. I considered adding a special icon for _when it's being printed_ but that'd probably lead to zerging making the (SIDE) objective too hard. Other than giving zenos the chance to actually prep, this won't stop any stealth ops.

Maints might decide to change it anyway though

2022-05-26 07:00 UTC, TiviPlus requested changes

2022-05-26 07:00 UTC, TiviPlus commented on code/modules/events/intel_computer.dm
> +	SSminimaps.add_marker(I, I.z, MINIMAP_FLAG_ALL, "intel") //todo
todo

2022-05-26 17:18 UTC, Kuro020 approved these changes
could do with a better sprite but whatever

2022-05-27 17:34 UTC, merged