Radial menu for metal recipes + small cleanup of mats code
tgstation/TerraGov-Marine-Corps pull request #10342
Opened 2022-05-30 08:50 UTC by breadhunt

## About The Pull Request

Continuation of https://github.com/tgstation/TerraGov-Marine-Corps/pull/10315 , merge conflicts be damned

- Adds a quick-access radial menu for metal. The old recipe menu can be accessed through the + button:
![image](https://user-images.githubusercontent.com/80229419/170953729-70d9b7dd-aaff-4393-9778-cd2a1ee40103.png)
(Feel free to suggest changes to it)

- Removes plasteel box recipe. If any other recipes are added for plasteel feel free to re-add. Plasteel cades can now be made in the same way as sandbags.
- Cleans up sandbag code while we're at it

## Why It's Good For The Game

Old recipe menu was clunky (had to click on it to build cade, click off to move, click back on to build cade again) and obtrusive for beginners.
This makes it easier for new engis to use the menu, and reduces clicks needed.

I don't think it's too hard to access old recipe menu from this (it's one extra click) but if it really becomes an issue I can make it a preference like radial medical wheel. I might also make TGUI recipe menu after this but TGUI is hard and I am lazy, so no promises. Please give me your opinions engi mains.

## Changelog
:cl:
del: Removed plasteel crate recipe
qol: Plasteel cades no longer require a menu to make, just press Z
qol: Metal recipes have a new radial menu, old recipe menu selectable from it
refactor: Cleaned up mat and sandbag code a small bit
/:cl:

2022-05-30 09:04 UTC, Lauwma commented
Speedmerge

2022-05-30 13:59 UTC, Losenis commented
Can you add the old menu accessible through right clicking the stack? Otherwise tying it to two actions on top of ping is gonna be cancer for those who want to use the old menu regardless.

2022-05-30 14:31 UTC, breadhunt commented
> Can you add the old menu accessible through right clicking the stack? Otherwise tying it to two actions on top of ping is gonna be cancer for those who want to use the old menu regardless.

isn't right click already used to separate stacks? I'll see if I can get it on ctrl right click

2022-05-30 19:06 UTC, Derrick2Electricboogaloo commented
So long as I can still access the Z menu for metal this seems really nice.

2022-05-31 10:39 UTC, breadhunt commented
@Derrick2Electricboogaloo @Losenis toggle added in preferences. Like medical wheel, if you disable it, it'll just work as before

2022-06-01 13:27 UTC, TiviPlus requested changes
why did you add the /obj/item/stack/attack_self(mob/user) code if you dont call parent anyway

2022-06-03 04:43 UTC, Kuro020 approved these changes

2022-06-04 11:28 UTC, TiviPlus commented on code/modules/client/preferences_toggles.dm
> +	to_chat(src, span_notice("You will [(prefs.toggles_gameplay & RADIAL_STACKS) ? "now" : "no longer"] use the radial menu when interacting with material stacks."))
if you do not in this pr are then

2022-06-04 11:29 UTC, TiviPlus commented
Also adding here but I said in discord that you need to call parent first in attack self due to signal

2022-06-05 04:27 UTC, Durbles commented
Very good change yes. I can't count how many times I've made razorwire instead of barbed wire because of how clunky the current menu is.

2022-06-13 11:29 UTC, merged