Adds the AGLS-37
tgstation/TerraGov-Marine-Corps pull request #10350
Opened 2022-05-31 04:54 UTC by Pariah919

## About The Pull Request
Adds the AGLS-37 mounted automatic grenade launching system, which launches HE and Fragmentation shells for 100 points.

I stole the sprites from Tye, other than the ammo which was me.
![image](https://user-images.githubusercontent.com/46353991/171094748-e4f9f4a8-f5d7-4661-840f-62f550e0159c.png)

Gun itself
-
It has no swivels, it cannot be turned without grabbing it and redeploying it.
It cannot move on its own.
It has a 0.75 fire rate. Could be tuned further.
30+1 grenades in a drum.
It is not free roundstart, it costs 100 points, 10 per drum of ammo.
It uses the TL-102 scope wholesale.

Ammo
-
HE is just HEDPs with lower det time, they fly until they hit a surface or cross 21 tiles then detonate shortly after.
Frag fires a shell which flies 21 tiles or hits something then splits into 20 fragments, like the TX-54 but it has no mob passing on the shrapnel.
Shrapnel does 25/20/1, 360 cone. 20 shrapnel.

## Why It's Good For The Game
Adds a another unique choice to the mounted weapon category and uses an unused mechanic of grenade canisters for the ability to fire grenades without them instantly exploding in your face, and thus balancing this probably broken thing otherwise.

Fragmentation could be subject to change, but I like it as a mechanic, and the gun itself requires 2 people to effectively use without blowing yourself up due to the short range of the scope.

## Changelog
:cl:
add: Added new automated grenade launcher system for 100 points in req, go buy it. Its cool, fires impact shrapnel shell in a 360 cone like TX-54, and delayed explosive shells equivalent to HEDP.
/:cl:

2022-05-31 05:27 UTC, XSlayer300 commented on code/modules/projectiles/guns/mounted.dm
> +	desc = "The AGLS-37 automatic grenade launching system, it's too heavy to be wielded or operated without the tripod. IFF capable. On the back, it reads 'The Explosions and Fragmentation from this we
```suggestion
	desc = "The AGLS-37 automatic grenade launching IFF capable system, it's too heavy to be wielded or operated without the tripod. On the back, it reads: \"The Explosions and Fragmentation from this weapon ARE NOT friendly fire capable. Kauser is not obligated to buy you new body parts for you or your friends if you lose them.\"\nCan be deployed with Crtl-Click. It CANNOT be turned once deployed, due to a lack of swivels, pick it up to move your cone of fire. Can be repaired with a blowtorch once deployed."
```

2022-05-31 06:00 UTC, lKiseki commented
can someone stop mjp from adding more deployables please thanks

2022-05-31 07:11 UTC, goose4429 commented
>> It is not free roundstart

Finally.

2022-05-31 23:31 UTC, Lumipharon commented
With that fire rate it's gg to any xeno caught in the open, as you'll just be juggled to death without being able to do anything.

2022-06-01 02:09 UTC, novaepee requested changes
Change AGLS fire delay to equal or greater than the grenade launchers. Less than is bad for xenomorphs.

2022-06-01 02:09 UTC, novaepee commented on code/modules/projectiles/guns/mounted.dm
> +	fire_delay = 0.75 SECONDS
Oh, lord. Lumi is right. 0.75 seconds? That's way faster than GL.
![image](https://user-images.githubusercontent.com/6610922/171313710-89894f3c-e06f-41ba-b14c-95093f5ca3fd.png)
![image](https://user-images.githubusercontent.com/6610922/171313766-1e7165b8-3e56-4846-adb6-0161e7db0f19.png)

2022-06-03 04:43 UTC, Kuro020 approved these changes

2022-06-08 19:13 UTC, Pariah919 commented
will wait for lootboxes™️

2022-06-08 19:13 UTC, closed without merging