TGUI Hive Status Revived feat. Compact (Classic) Mode
tgstation/TerraGov-Marine-Corps pull request #10391
Opened 2022-06-05 03:46 UTC by Wayland-Smithy

## About The Pull Request

Continuation of #10273 with the following changes:
- Clicking on a Xenos name in the list will track it.
- Added a "Compact Mode" for the counts of each caste that is very reminiscing of the old Hive Status text.

![image](https://user-images.githubusercontent.com/64715958/172034099-abb37dc3-ac5f-49b0-a53b-6003fe80c052.png)
![image](https://user-images.githubusercontent.com/64715958/172034131-63e7b047-ee0e-4354-8b2d-b6bee6619198.png)
![image](https://user-images.githubusercontent.com/64715958/172034106-42bd7868-77de-4a01-bccf-f3cd2bda01ac.png)

## Why It's Good For The Game

TGUI good.

## Changelog
:cl:
add: Xeno hive status is now a constantly updating TGUI page.
add: Xeno hivemind players can now select a xeno to jump to using the hive status UI overwatch button.
add: Evolving now closes all UI pages open.
add: Xeno purchased primordial tiers now display as a green [PRIMORDIAL] next to the tier population in the hive status UI.
imageadd: Ported CM hive status SSD icon.
qol: Evolution is displayed and can now be accessed through the hive status UI.
qol: Xeno overwatch selection now done through hive status UI. Action button no longer visible.
qol: Xeno overwatch can now be canceled without having to move by selecting the same xeno to overwatch again.
qol: Queen leadership toggle now done through hive status UI. Action button no longer visible.
qol: Queen transfer plasma now possible through hive status UI.
qol: Xeno minimap icons now display next to corresponding xeno names in hive status UI.
qol: Xeno collapse timers now display in hive status UI instead of game tab.
qol: Hive status UI can sort xeno lists by clicking on the column headers. Sorting is done by xeno tier, health points, plasma remaining, and location by alphabetical order to the first 5 letters.
fix: Queen transfer plasma message now only visible to xenos.
fix: Ghost orbiting code now properly returns an accurate reference to the atom it is orbiting.
refactor: Hive upgrades purchasing UI relocated to separate datum.
refactor: Distress mode collapse timers are now a define.
del: Old HTML hive status page now lives at your grandparents' farm upstate.
del: Queen order, the unused direct to xeno version, has been removed.
del: Removed a vestigial time check that checked if a distress beacon could be launched at 10 minutes into a round. Xenos can not hijack before 30 minutes into a round.
/:cl:

2022-06-05 04:10 UTC, Kuro020 approved these changes

2022-06-05 09:21 UTC, Al-1ce commented
Does this affect the compass utility? Will that be removed as it were with the last TGUI xeno-status?

>Compact Mode

I'd really appreciate just a 'classic' mode that reverts to the old style. It's a lot more utilitarian and much more familiar after three years of using it.

2022-06-05 13:17 UTC, Wayland-Smithy commented
> Does this affect the compass utility? Will that be removed as it were with the last TGUI xeno-status?

The compass loses no functionality with this iteration because just like before xenos and structures can be selected as the compass/tracking target.

> > Compact Mode
> 
> I'd really appreciate just a 'classic' mode that reverts to the old style. It's a lot more utilitarian and much more familiar after three years of using it.

Unfortunately so much under the hood has changed that it would be non trivial to keep the entire old UI.

I believe it is a good compromise in the name of progress to have the "Hive Population" section displayed in the old style so by using that and the above section you can find all the same info as before and more with less screen real estate like psy points, burrowed count, and caste totals.

2022-06-06 08:50 UTC, TiviPlus requested changes

2022-06-06 08:50 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
> +/mob/living/carbon/xenomorph/hivemind/proc/jump(mob/living/carbon/xenomorph/xeno)
autodoc

2022-06-06 08:50 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
> +	if(!(status_flags & INCORPOREAL))
src.proc

2022-06-06 08:50 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
> +/datum/action/xeno_action/set_xeno_lead/proc/try_use_action(datum/source, mob/living/carbon/xenomorph/target)
autodoc

2022-06-06 08:50 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
> +/datum/action/xeno_action/activable/queen_give_plasma/proc/try_use_ability(datum/source, mob/living/carbon/xenomorph/target)
autodoc

2022-06-06 08:50 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/hive_datum.dm
> +/datum/hive_status/proc/get_structure_packet(obj/structure/xeno/struct)
autodoc

2022-06-06 08:50 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/hive_datum.dm
> +		. = A.name
Please use a better varname than A

2022-06-06 08:50 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
> +	var/show_structures = TRUE
Why are these not bitflags?

2022-06-08 15:32 UTC, merged

2022-06-12 02:50 UTC, Al-1ce commented
>The compass loses no functionality with this iteration because just like before xenos and structures can be selected as the compass/tracking target.


We can't track other xenos with the compass anymore. That's definitely a loss of functionality and for no apparent reason.

2022-06-15 22:57 UTC, Al-1ce commented
excellent stealthnerf. compass my beloved