Changes shrike's abilities and base health
tgstation/TerraGov-Marine-Corps pull request #10418
Opened 2022-06-08 23:54 UTC by Losenis

## About The Pull Request
Reduces shrike's abily stuns from 1 full second to 0.1s, effectively only working as knockdown. Reduces ability cost and CD by 50%. Increases health by ~25%.

## Why It's Good For The Game
Stun-based castes fall into two areas: Either they stun the enemy and beat them while the enemy can't fight back, or gets melted when they can't stun the marine be it by missing the stun or just there being too many enemies to stun. From playing as and against shrikes, and seeing others while obsing, the "can't stun" scenario leads to them getting straight up deleted due to not having the baseline stats to face marines that actually fight them, since the stuns act as bandaid to the issues of the caste itself. Against a massive group of marines (think an ungaball or a unified silo push), they're almost useless save for healing, pheros, the rare AoE stun that lands, etc. In short, stuns work to hide how bad a caste might be since they'll be fighting people that literally can't fight back in that duration.

This PR is more a proof of concept in balancing a caste's abilities with the scenario in mind that they will be fighting marines that will actively shoot them in combat, rather than assuming the stun will keep them safe. For this, their health is increased considerably as a starting step, as well as their abilities made cheaper and more frequent to use, as they'll be relegated to utility. Ideally it'll be a nerf for the stun aspect, but a buff for other scenarios such as tossing grenades back, keeping marines away, tossing them into hazards like flamers or magmoor's lava, etc. The abilities will keep the 0.1s stun to have them viable as a tool to disrupt a marine for what item it holds, unwielding the gun and dropping it if they have no magharn/belt harness, and disconnecting flamer tanks/SGpacks/miniguns, buffing them in this respect by having the abilities be usable twice as frequently.

Since this is a stab in the dark kind of PR, it should not be merged without good testing and possible changes like more health, sunder, health regen, plasma, etc to account for the removal of stuns or the health + ability changes going overboard.

## Changelog
:cl:
balance: Shrike's Unrelenting Force and Psychic fling had their stun effectively removed. Cooldown and cost reduced by 50%. Health increased by 25%.

/:cl:

2022-06-08 23:55 UTC, Losenis commented
Here's for the first actual pr made in VSC instead of webedit

2022-06-09 00:07 UTC, novaepee commented
LET THE JUGGLE BEGIN!!!!

2022-06-09 01:13 UTC, Al-1ce commented
This is actually really good.

2022-06-09 01:57 UTC, SilencedMP5A5 commented
time to get stunlocked for fucking ever

2022-06-09 01:59 UTC, Losenis commented
The stun is pretty much removed bro

2022-06-09 02:13 UTC, Pariah919 commented
I could get a 10 to maybe 15% increase but 25% makes Shrike as tough as the tank castes in this game, which seems kind of absurd even if its losing its giga stun capablities inexchange for stutterstunning more consistently, which could be better or worse, really.

2022-06-09 05:55 UTC, BraveMole commented
> I could get a 10 to maybe 15% increase but 25% makes Shrike as tough as the tank castes in this game, which seems kind of absurd even if its losing its giga stun capablities inexchange for stutterstunning more consistently, which could be better or worse, really.

I agree, but it is also a proof of concept. Which means that if it is good, other xenos will get more or less same treatment

2022-06-09 05:56 UTC, Lauwma commented
If you want them to be a displacement tool then you'd need to give them the same Crowd Control resistances as a crusher. Else they'll just get slugged to death without any stun to counter attack

2022-06-09 07:17 UTC, ilikesaying commented
really just made marines drop their items trying to land feet first

2022-06-09 08:22 UTC, goose4429 commented
To be honest, shrike being tanky boy with no real offence is a cool thing. I like the concept, we'll see how the stuns will play out.

2022-06-09 19:18 UTC, BraveMole requested changes
Remove comments they completly useless.

If you want to left message to maintainers you use the github review feature

2022-06-09 19:32 UTC, turnop commented
Awful. GARGANTUAN nerf to Shrike making both of its vital stun abilities completely worthless in exchange for pathetic buffs to completely irrelevant stats like HP. This is a gargantuan nerf to the single most important xeno caste in the entire game - shrike is the ONLY caste that is able to actually draw out crybaby marines who camp cades 24/7 and sweaty gamers who never get out of position, and this completely removes that ability.

Enormous nerf to shrike prompted purely by marines crying that a single xeno caste in the game is actually capable of punishing them by turning minor mispositions into secured kills.

2022-06-09 20:12 UTC, goose4429 commented
> Shrike is the ONLY caste that is able to actually draw out crybaby marines who camp cades 24/7 and sweaty gamers who never get out of position

Warrior, boiler, crusher, primo queen/defiler are like: bruh

2022-06-09 20:19 UTC, Losenis commented
>Also that looks completly broken, why are you even changing the cds

Because the abilities would be losing their stun which'd result in a massive nerf if left at that. The idea isn't to nerf as much as rework, and because the ability would be relegated purely to utility and moving marines around instead of stunning them on top of that to kill them (up to 2 seconds due to no shared cooldown + a screen worth of displacement), I figured it could use the frequency buff to work as that more often.

2022-06-09 21:29 UTC, turnop commented
> > Also that looks completly broken, why are you even changing the cds
> 
> Because the abilities would be losing their stun which'd result in a massive nerf if left at that. The idea isn't to nerf as much as rework, and because the ability would be relegated purely to utility and moving marines around instead of stunning them on top of that to kill them (up to 2 seconds due to no shared cooldown + a screen worth of displacement), I figured it could use the frequency buff to work as that more often.

The ability to shuffle a marine 4 tiles, and even further 12, becomes almost literally only useful for moving someone through fire, since the shuffled person is immediately able to move and shrike is a melee only caste. Unless there's a xeno actively waiting on the other end of that fling to recieve the instantly unstunned marine like a football, he could have ran back four or five tiles by the time the Shrike has run seven - while firing his magharness gun the whole time. 

A shrike of equal skill dueling a guy with a magharnessed buckshot or literally just a vali + shield is going to lose hard.

2022-06-09 23:23 UTC, Losenis commented
Yeah if you gear up specifically to counter a caste you're going to have an easier time countering it, that's kind of intended for most xenos. It's like grabbing mimir mk2 for praes. And you can already do that nowadays with t39 slugs and the stagger that doesn't even let it use the ability anyway.

2022-06-11 01:06 UTC, zzurge commented
unnecessary tbh,shrike was fine where it was

2022-06-11 01:28 UTC, Losenis commented
It had two abilities that stunned, displaced, dropped guns, and had no shared cooldown that could lead to a marine being stunned a screen away meaning one would almost always set up the next. That alone was questionable, but it'd lead to stunlocking when other xenos with their own stuns fought in the general area.

And if you couldn't land those stuns you'd get melted extremely fast, so you had to run and wait till you had said stuns back. The stuns themselves made the shrike as a caste pretty bad only made viable by two consecutive abilities that made marines unable to even fight back.

Sure it's fun when you land stuns. But being on the receiving end means you're just watching not even playing the game as your health rapidly drops and get forced into situations you'd otherwise not even get yourself into. This isn't a marine issue only, since you can have this happen if someone is running dual t39 and effectively stunlocks you into marine lines.

Stuns should be rare so as to not lead to stunlocking, because fights don't usually happen 1v1, and a lot of castes have their own stuns. And if stuns get bad enough, the balance concerns would inevitably lead to "just stun them, bro" even if castes are by themselves unviable without them.

The only reason marines don't all premed on synaptizine in a fight is because they don't bother to get it. I assure you that when marines take them and become almost stun immune, the shortcomings of most stun-based castes comes to light _hard_.

2022-06-13 03:24 UTC, Dolth commented
Removing stuns removes the damage ability of the shrike, and 25% HP and speed buff doesn't make up for it since marines out DPS you. Instead I suggest you give ability based small damages, that way shrike isn't about diving and landing a fish/stunlock to kill but actually deal damage while doing so. Less frustrating for both sides.

2022-06-13 05:06 UTC, Al-1ce commented
> Removing stuns removes the damage ability of the shrike, and 25% HP and speed buff doesn't make up for it since marines out DPS you. Instead I suggest you give ability based small damages, that way shrike isn't about diving and landing a fish/stunlock to kill but actually deal damage while doing so. Less frustrating for both sides.

Could implement warrior code. Flinging or screeching a marine into a wall could do damage or something like that.

2022-06-13 08:55 UTC, Dolth commented
Also on a sidenote a xeno with 2 stuns/staggers with low cooldown, 500 hp and ravager speed and drone capacities? That makes no sense.

2022-06-13 10:44 UTC, goose4429 commented
This way, shrike sounds more like a support caste - cant stunlock by itself, but more powerful than before with backup. Sounds good. The actual numbers have to be tested in game.

Speed is probably too high though, and I'd make CDs a bit higher.

2022-06-14 00:02 UTC, MiniMeatwad commented
I say the shrike feels comparable to a drone, and maybe at best it's a drone with egg laying, with the ability to push marines into safety and away from xenos like a combat drone could never dream of doing before. In this area, it is definitely T4.

2022-06-15 11:45 UTC, Starfirejordan commented
shrike is just meh now. this is honestly a nerf as a whole. maybe make there ability more spam-able then yea it would be something more. maybe let them pick up hugger so they can carry them and use there ability to fling them

2022-06-23 00:45 UTC, Losenis commented
New PR which includes this is already up

2022-09-21 14:29 UTC, Losenis commented
Reopening due to lewdcifer's PR as alternative.

Change had been TMd and found good enough to be inlcuded in another pr. This was closed said pr rather than its own contents so it should be good to reopen as an atomized version.

2022-09-21 14:36 UTC, FosterGrime-Heymynameslouie commented
finally
the only accepted good part of the ol stun tweaks

speed mrhge
I wanna jugggle

2022-09-21 14:48 UTC, Losenis commented
>the only accepted good part of the ol stun tweaks

You didn't see four defenders dancing with 0 cooldown fortify?
![DefenderDab](https://user-images.githubusercontent.com/72712909/191536460-1b5ec7dd-c3de-49e3-b8fb-40b96dace8aa.gif)

2022-09-21 18:53 UTC, usnpeepoo commented
this isn't needed at all, shrikes stuns can't even kill anyone after their usage. A marine has every chance to fight back after the initial fling, slashes, screech, slashes. Huge -1

2022-09-21 18:59 UTC, usnpeepoo commented
> Then wouldn't the additional health and speed help shrike more?

this doesn't even matter when you take into account that the shrike will still get out DPS'd and even with a speed increase still be affected by staggers/slows/etc. Shrike is perfectly fine rn, doesn't need this at all

2022-09-21 19:22 UTC, Losenis commented
I don't know, all the people I asked that played shrike with this TMd said they liked it better.

2022-09-25 01:20 UTC, Losenis commented
Bruh

2022-12-21 23:41 UTC, RipGrayson commented
This PR is under active discussion and will probably receive a TM soon.

2022-12-22 15:51 UTC, FosterGrime-Heymynameslouie commented
this is still the best hcange out of the ol cooldown pr from long ago

speded merhg

2022-12-23 08:40 UTC, SpiderPsycho commented
This change makes Shrike completely useless on their own, more useless than they already were. They're a T4 that can be stunned / knockbacked. They're a builder without enough plasma storage or regeneration to properly build and maze like a hivelord or queen can. They're a CQC xeno that doesn't have high burst damage, but is meant for displacing / fishing marines and stunning them, except now they can no longer stun xenos. Even when warriors fish they can stun and deal lots of damage in a burst.

25% increase in health does not matter that much because they have no rapid healing on their own and the level of burst damage marines can do means it doesn't matter. And since they're CQC, shotgunners can melt and stunlock Shrikes to death, except they can't even stun a marine to get away from them. And before someone says the fling gives them distance, so what? If anything that's a benefit to the marine. Marines use ranged weapons. The only time distance would be useful is against a vali user or a buckshot user.

By removing the stuns from fling mean that the decrease in cooldown time is pointless, because it's not like the ability does much of anything if the shrike isn't backed up by other xenos who can stun or who can deal high amounts of burst damage.

Shrike is the T4 xeno for lower pop rounds, or when xenos lose individuals. Doing this turns them from mediocre to useless.

I've been told that xenos MUST work together to secure kills, but frankly there's a limit to that, and as it stands, especially with this PR, that's ridiculous. Shrike was already barely able to secure kills on their own despite being a T4, but now their only function is to toss marines around, which isn't always a good thing. They can no longer contribute to a fight meaningfully by stunning. Marines outnumber Xenos and out-damage them as well. Doing this makes the ratio of power even more unbalanced.

If you intend to remove stun gameplay, fine? But if you don't replace it with anything then you're just leaving a massive gap in the xeno toolbox. I'm awre this has been the status quo for maintainers and devs, to just remove things from xenos and then tell them to cope/seethe/get gud, but that's not exactly good game design is it? And as a maintainer or dev, even for a dumbshit spessman game with xenomorphs fighting pseudo-spartans, your goal is still good game design is it not?

2022-12-23 14:02 UTC, Losenis commented
>but then what about marine stuns?

I tried that along with stagger in a pr that had both xeno and marine changes in one so that it didn't end up removing only one side's. Got told to atomize. Then it got closed. It's not up to me whether it goes through or not, it's up to whoever reviews the PR.

2022-12-23 16:58 UTC, SpiderPsycho commented
> I tried that along with stagger in a pr that had both xeno and marine changes in one so that it didn't end up removing only one side's. Got told to atomize. Then it got closed. It's not up to me whether it goes through or not, it's up to whoever reviews the PR.

If you couldn't remove both then why remove one? It's unbalanced as hell. I don't think I need to tell you that. 

Also please, this PR in general. If you're going to remove stuns from shrike's fling you need to replace it with something else. The shrike doesn't have burst damage ability like woyers or ravagers, and it doesn't have stuns like Praetorians or anyone else for that matter. It's not ranged either so it can't attack and not be directly in the marines' attention.

I suggest you either:

1.  Abandon this anti-stun stuff until something better comes along.
2.  Give shrike's fling a burst of damage, or give shrike higher damage per claw but with a lower attack rate, but I can already tell this will not be recieved well and even I'm not partial to this idea, or that it'd be an improvement or would make stun removal worthwhile.
3. You could alternatively make it so when the shrike flings a marine into a wall, it does damage. Knocking them into razorwire should tangle them in it and damage them too. Knocking them through a window / window frame could trip them, maybe fracture legs, twisted ankle type stuff.
4. Knock marines prone at the very least, though this is pretty much the same as stunning them.
5. An EMP / weapon jamming / confusion causing ability that suppliments the fling, disabling shields, lights and obviously jamming weapons so that the shrike can deal damage without being immediately BTFOd. It would also mean that robot spam for immunity against huggers would be countered, and there would be something that could deal some serious damage to the mech.

2022-12-23 17:47 UTC, Losenis commented
>"until something better comes along"

wyci

2022-12-23 19:36 UTC, Redrover1760 commented
Shrike stun is good because it means that the caste isn't a one-trick pony where all it can do is launch people around and pray that it has fellow xeno teammates to do slight amounts of damage.

There's no reason to remove this.

2022-12-23 19:56 UTC, Passe2142 commented
Shrike, was design around stuns due to old low pop capture gameplay. 
Im neutral to this cause I dont mind change or its stats buff, even being wired to stuns, shrike buffs make it strong with the new stats.
But being a T4 and ruler killing its stuns its punishing a bit to those that need lockdown in risk high reward plays.
People dislike its core style of timing two skills into a play that could get ya kill by being semi squishy, and dont like stuns.
The PR aims to make it more of a frontliner disruptor than a fisher/playmaker style. I would like more instant plays for a frontliner rather than a playmaker, for a playmaker positioning and timing is the core.
Killing stuns in one PR wont fix TGMC design. TGMC is a topdown TDM that has lockdown mechanics for both sides.

2022-12-23 21:07 UTC, Passe2142 commented
If fling and screech did oomph rather than move them a few tiles, like damage on fling into rines/walls, and scree did stagger/slowdown with less throw distance. Shrike wont be just quick combo to move them a few tiles. You have to punish in a sense bad positioning from them and allow a high risk high reward outcome. The duelist class its a bit incomplete. By any means its weaker now but the combo lacks that omph factor to help the team in the front.

2022-12-24 03:19 UTC, Xsdew commented
These changes to Shrike make it a much more effective combat caste. The Shrike has more opportunities to apply the Psychic Fling / Unrelenting Force, with combat sustainment from the additional speed / health / team work with xenos (taking bullets for the shrike). 

It is purely better with the "loss" only being the 1 second of stun. Rapid knockdowns cut down the marines ability to fight which is superior to the one and done stuns of old shrike.

2022-12-24 04:13 UTC, SpiderPsycho commented
> > "until something better comes along"
> 
> wyci

That's a really smartarse response. You're the one coding the removal of something. Why should I be the one to undo your actions when the simple solution is for you not to do it? You're not absolved of responsibility when you say WYCI. It's just you being a brat and breaking the toys because you're angry.

2022-12-24 14:08 UTC, Losenis commented
>That's a really smartarse response.

I'm serious. "Until something better comes along" means someone has to code it, and you can't guarantee it's actually going to be better until you code it yourself, because you don't seem to think this one is good enough and there's no guarantee the next guy won't have the same change philosophy.

2022-12-24 17:38 UTC, srxtreme commented
Salt PR?

2022-12-24 22:14 UTC, Lumipharon commented
I don't agree with the very high speed buff.

Strike probably deserves more than just number tweaks if you think the gameplay isn't good.

2022-12-24 23:10 UTC, Losenis commented
Seems to be doing the trick for people I've been asking ingame.

![image](https://user-images.githubusercontent.com/72712909/209452972-91077730-b7c0-44a7-ba64-e92defcf29c7.png)
![image](https://user-images.githubusercontent.com/72712909/209452976-244b2db9-4231-48bc-ae8c-05db8d60decd.png)
![image](https://user-images.githubusercontent.com/72712909/209452978-a6bac081-f7a2-4a9c-b843-c8585e18cc4b.png)
![image](https://user-images.githubusercontent.com/72712909/209452980-2b94fd0b-ed50-4d4c-b920-80c10d7aa695.png)
![image](https://user-images.githubusercontent.com/72712909/209452993-42cbed7c-8ceb-4ec9-b0a4-4c06a53f4cca.png)
![image](https://user-images.githubusercontent.com/72712909/209452997-4e12bb11-13ca-4bcc-be73-c3a657920257.png)
![image](https://user-images.githubusercontent.com/72712909/209452999-638d79f5-6d6b-49a1-a17f-e336ab9ab3dd.png)

2022-12-26 17:23 UTC, lKiseki commented
> Seems to be doing the trick for people I've been asking ingame.
> 
> ![image](https://user-images.githubusercontent.com/72712909/209452972-91077730-b7c0-44a7-ba64-e92defcf29c7.png) ![image](https://user-images.githubusercontent.com/72712909/209452976-244b2db9-4231-48bc-ae8c-05db8d60decd.png) ![image](https://user-images.githubusercontent.com/72712909/209452978-a6bac081-f7a2-4a9c-b843-c8585e18cc4b.png) ![image](https://user-images.githubusercontent.com/72712909/209452980-2b94fd0b-ed50-4d4c-b920-80c10d7aa695.png) ![image](https://user-images.githubusercontent.com/72712909/209452993-42cbed7c-8ceb-4ec9-b0a4-4c06a53f4cca.png) ![image](https://user-images.githubusercontent.com/72712909/209452997-4e12bb11-13ca-4bcc-be73-c3a657920257.png) ![image](https://user-images.githubusercontent.com/72712909/209452999-638d79f5-6d6b-49a1-a17f-e336ab9ab3dd.png)

(you forgot to put the part where i mentioned that shrike could use a health nerf)

2022-12-26 17:52 UTC, MiniMeatwad commented
Agreed, I blew up a Shrike with a HE RR rocket (non-direct, sunder), and shot a sticky grenade onto it while firing at it with a T-12, and it was only put into critical condition. It survived because it got blown onto weeds, and it ran away faster than I could chase it with sprinting speed from SL move order. Granted, it was heavy armor. Well, maybe it's skill issue, but it was also at the very first level of the Xeno damage indicator with the blood spots.

This is my anecdote from playing the game yesterday.

Also, yeah, it's a lot better without being stunned for a long time, you can actually run away from getting pinned by two Xenos from a stun because it wont make it to you in time if you just run away.

2022-12-26 17:57 UTC, Losenis commented
>(you forgot to put the part where i mentioned that shrike could use a health nerf)

Deadass didn't see it, always kept alt tabbing to the game inbetween

2022-12-27 22:52 UTC, Lumipharon commented
To add to previous comments, I am opposed to this because the speedbuff makes the shrike mechanically faster than any marine trying to chase it. This makes it aids to try kill unless it has skill issue'd hard.

The stun changes I'm kinda eh about, but not opposed to. It nerfs its solo ability but makes it far more useful in group fights simply due to being able to fish twice as often

2022-12-28 04:42 UTC, Redrover1760 commented
I'm dumb, this shrike PR is very good. Stun based gameplay was boring anyways.

2022-12-29 19:58 UTC, Xsdew commented
> Stun based gameplay was boring anyways.

As this PR only changes values, and not design. The Shrike still stuns you. You are just trading 1 second of laying horizontal to a disarm every 6 seconds.

2022-12-31 02:27 UTC, Passe2142 commented
I changed my mind, its more like a disguised cope PR in a sense, You killing stuns for two abilities that lack impact and just saying you are faster and can spam them, doesnt make it fun or a fit for shrike style. Its a playmaker, deal with getting comboed. 
Rines can still stun any castes with hammer, apply stagger with aim mode on repeater that can lock ya out of shuffle,
Being stunned is part of the game. You just killing the fun of a caste and saying look it can be faster and spam this and that. But this and that does nada.

2022-12-31 02:44 UTC, Losenis commented
>Rines can still stun any castes with hammer, apply stagger with aim mode on repeater that can lock ya out of shuffle,

Remove all of them then. I tried anyway. Whenever xenos bring up stun I keep reminding them of how it feels to be on the receiving end with the rocket sledge, in fact.

2022-12-31 04:13 UTC, Passe2142 commented
> > Rines can still stun any castes with hammer, apply stagger with aim mode on repeater that can lock ya out of shuffle,
> 
> Remove all of them then. I tried anyway. Whenever xenos bring up stun I keep reminding them of how it feels to be on the receiving end with the rocket sledge, in fact.
This isnt they have x we should have y or z should be removed cause stuns bad. You cant kill stuns. Prove me wrong if you want. This is core to its style. Wanna know why they found it fun? Due to Health buff. Unless Fling/Scree do something. more than just move them a few tiles , this is a nerf.

2022-12-31 06:18 UTC, Starfirejordan commented
Not gonna lie i hate this new shrike, the spamming of ability with no punishment sucks ballz, before shrike had to think about using its ability and so was stunned for a second? it better then having them scream me into acid turret every fucking second of the day dear lord this displacement spam is hell and annoying, i rather be stunned unable to fight back then constantly flung to my death into these stupid fucken turret

2022-12-31 18:34 UTC, yyzsong commented
Lack of stuns makes shrike's Oz sting basically impossible to land without a bodyblock or something

2022-12-31 22:10 UTC, Lumipharon commented
Saying no because this makes shrike legitimately frustrating to play at low pop, i.e. crash, and almost entirely rely on just displacing into a group of other xenos as opposed to operate by itself.

2022-12-31 22:10 UTC, closed without merging

2022-12-31 22:14 UTC, Losenis commented
>Legitimately frustrating to play at low pop

WHAT ISN'T???

2022-12-31 22:57 UTC, novaepee commented
Two maintainers closed this even with new balance maintainer. This PR has seen its end.

2023-01-02 00:41 UTC, Redrover1760 commented
> Not gonna lie i hate this new shrike, the spamming of ability with no punishment sucks ballz, before shrike had to think about using its ability and so what if im stunned for a second? it better then having them scream me into acid turret every fucking second of the day dear lord this displacement spam is hell and annoying, i rather be stunned unable to fight back then constantly flung to my death into these stupid fucken turret
> 
> Edit: this was written in a mad rage after being constantly launched into turrets in a 1x1 small hall way trying to assult shipside benos

Pit boss moment

2023-01-02 10:56 UTC, ClosetedSkeletonGH commented
> Saying no because this makes shrike legitimately frustrating to play at low pop, i.e. crash, and almost entirely rely on just displacing into a group of other xenos as opposed to operate by itself.

Old (current) shrike on low pop says "Oh, you dont have 3 teammates to cover you at every moment cause of lowpop? Hope you like standing while you eat these two stuns"