Add a new wraith ability: woosh swoosh
tgstation/TerraGov-Marine-Corps pull request #10433
Opened 2022-06-10 17:08 UTC by BraveMole

## About The Pull Request

Add a new ability for wraith, rewind. 

Click on a xeno/human, this saves his position and stats. If he is not dead after 5 seconds, the ability will transport it back to where it was, with the health it had.

## Why It's Good For The Game

Woosh swoosh

## Changelog
:cl:
add: New wraith ability, rewind
/:cl:

2022-06-10 17:38 UTC, SilencedMP5A5 commented
_**KILLER QUEEN! BITES ZE DUSTO!**_

2022-06-10 17:51 UTC, Losenis commented
Woosh Swooshing marines back into the tadpole landing area they thought they were clear of

2022-06-10 19:13 UTC, Kuro020 commented
this ability name is dumb

2022-06-10 20:54 UTC, Lauwma commented
So if they took damage do they heal ? Same thing for fractures ?

2022-06-11 00:24 UTC, private-tristan commented
welcome to a true bean's world

2022-06-11 08:05 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
> +/datum/action/xeno_action/activable/rewind/proc/rewind()
Autodoc

2022-06-11 08:05 UTC, TiviPlus commented
Also no modified icons?

2022-06-12 13:32 UTC, TiviPlus commented
Autodoc review still pending but I'll give it tmc

2022-06-12 19:32 UTC, InterroLouis commented
Ahem. No. That's all. Just no.

2022-06-12 19:52 UTC, Mechanelize commented
![image](https://user-images.githubusercontent.com/52432736/173250752-285273d4-6e5f-4cb3-acbf-b2e5f1bab44b.png)
use this, kuro approved

2022-06-12 21:49 UTC, Mechanelize requested changes
use modern ability sprite instead of old cm one that doesn't match art syle, provided on discord

2022-06-12 22:38 UTC, Arctrooper8 commented
Can you make it so that wraith isn't able to kidnap people across Z levels? For example: if you're sitting and tadpole and it launched you can get pulled back all the way to groundside when Tad is in the air.

2022-06-15 05:36 UTC, Dolth commented
Looks completely broken on paper and unfun for marines but extremly fun for benos so, ehhh I am gonna play wraith and try this for the upcoming rounds.

2022-06-16 11:49 UTC, vilereaver41 commented
Why are you turning wraith into a support caste? that is boring. the intention of wraith was to be an infiltrator and you pretty much killed it. the playstyle from the way i see you made wraith is you assume the wraith is going to find a xeno and stick with it to support them. that barely if ever happens

2022-06-16 15:59 UTC, Mechanelize commented
>the intention of wraith was to be an infiltrator and you pretty much killed it.

It's a new ability with no other changes, it's a straight buff and doesn't hurt its ability as an infiltrator, just gives it the option to play a more support role, same with the portal ability.

2022-06-16 17:11 UTC, Losenis commented
I haven't realized how busted this is with primo bull until I faced it. Primo bull will run through the entire server hitting everyone as fast as it can run into them unlike slashing which has a cooldown, runs at 10+ tiles per second in all directions making hitting it extremely difficult, and with the ability now you only have like 3 or 4 seconds to kill it or it escapes. Not to mention wraith isn't a max 1 alive xeno like queen or shrike so this ability can be chained if there's 2 wraiths or more.

2022-06-18 19:48 UTC, Kuro020 approved these changes
disappointed that its not actually named woosh swoosh

2022-06-18 20:22 UTC, zzurge commented
I miss original wraith

2022-06-18 20:29 UTC, merged