Explosives can no longer be attached to unmanned vehicles
tgstation/TerraGov-Marine-Corps pull request #10431
Opened 2022-06-10 04:13 UTC by lKiseki

## About The Pull Request
Per title.

## Why It's Good For The Game
Plastic explosives have devastation range. These will instakill any mobs that fail to meet the bomb armor check. You can attach one such explosive to unmanned vehicles in general. Instakills in general are _terrible_, hence the PR.

## Changelog
:cl: Lewdcifer
balance: Unmanned vehicles no longer accept explosive attachments.
/:cl:

2022-06-10 04:14 UTC, novaepee commented
What if we just nerf C4 and let unmanned vehicles jihad to their heart's content?

2022-06-10 04:15 UTC, lKiseki commented
> What if we just nerf C4 and let unmanned vehicles jihad to their heart's content?

You effectively kill C4's niche, which is probably not a good idea. It's better to target the problem itself, since C4 is alright.

2022-06-10 05:17 UTC, Derrick2Electricboogaloo commented
I smell salt

2022-06-10 06:04 UTC, FosterGrime-Heymynameslouie commented
coupled with the fact that the light uav thats standard issue for engie's is, well, light, and does in a few acid hits, and slash hits, emits a near blinding light, and is extremely loud which can make it be heard from offscreen. I think if you die to uav suicide c4, you probably deserve it.

2022-06-11 02:12 UTC, InterroLouis commented
C4? Not detpacks?

2022-06-11 02:36 UTC, Pariah919 commented
mfw no VBIED

2022-06-11 08:09 UTC, TiviPlus requested changes
Make it so scout droid cant take explosives instead or change the checks to take expllosive as a turret type

2022-06-11 08:09 UTC, TiviPlus commented
Also ided

2022-06-26 00:55 UTC, closed without merging