Xeno stun tweaks
tgstation/TerraGov-Marine-Corps pull request #10489
Opened 2022-06-17 20:47 UTC by Losenis

## About The Pull Request
Rebalances some xenos to be competitive while toning down their stuns in exchange for buffs in other areas, or other xeno aspects as a whole. Draft while working it out.

## Why It's Good For The Game
The game oughta be fun for both sides, to play as and to play against. Stuns lead to a bit of fun on the one using them, while the ones on the receiving end end up in stunlock city. However, due to stuns playing a large role in the power of a caste, they end up weak in other areas that turn into a mess when they're no longer in a situation they can use their stuns, extreme example being ungaballs of 20+ marines if they're not rushing the 1x1 chokes so that they're fighting only a few at a time.

A smaller scale PR had been TM'd for the shrike and after talking with some people, it seems that even though initially it was tedious and difficult to get used to the new gameplay, they found it not only fun to play the new shrike, but also fun to play against as well. This PR would be the next step in toning down stuns for xenos as a whole but also giving them something in return while thinking of them as a team rather than castes in a vacuum.

This does NOT aim to remove ALL stuns from xenos.

Changes:

Shrike:
HP increased by 25%, speed equalized to ravager. Stun effectively removes from fling and unrelenting force, knockdown remains. Cooldown and cost of abilities reduced by half.

Boiler, Spitter, Praetorian:
Acid spray turf duration increased by 2x. Buffs them as an area denial tool since inevitably fewer stuns means xenos won't be able to keep marines from just bumrushing forward even harder.

## Changelog
:cl:
add: Added new mechanics or gameplay changes
add: Added more mechanics or gameplay changes
expansion: Expands content of an existing feature
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2022-06-17 20:48 UTC, Losenis commented
Ayo vsc was meant to put this as draft, the fuq

2022-06-18 04:08 UTC, Lumipharon commented
I disagree with this because status effects are the main factor that makes combat something more than just damage vs health, and brings a level of depth to the game.

That said, if you do want to remove stagger because you don't like loss of ability useage, why don't you just change what stagger does to xenos instead of removing it from marines?

2022-06-18 04:22 UTC, Losenis commented
Do you have any suggestions as to what stagger should do that isn't covered by any existing status effect?

>I disagree with this because status effects are the main factor that makes combat something more than just damage vs health

And I disagree with that assesment, it turns into damage vs health in "do I have enough health to survive the stun before I'm able to do anything/do I have enough health to crit the marine before he 1hand t39s a slug at me?". I don't remember when was the last time I took anything but heavy armor because of that.

2022-06-18 08:09 UTC, goose4429 commented
While some of the stuff looks nice, other parts are nonsensical.

>> Boiler, Spitter, Praetorian: Acid spray turf duration increased by 2x. Buffs them as an area denial tool since inevitably fewer stuns means xenos won't be able to keep marines from just bumrushing forward even harder.

What? It is _not_ an area denial tool. This is quite literally intended as a stun, to initiate attack or break of pursuers. Prae stun allows you to actually be able to go CQC instead of chilling at the edge of the screen and pressing RMB from time to time. Moreover, they allow for _large_ portions of damage. 

And buffing it from 10 to 20 secs or whatever just means marines will move forward 10 sec later. And that is given you've use it in the right place, and not just as a damage tool. You can buff it 10x and it would still be trash. To sum up, this is a direct strong nerf to prae and spitter, without reasonable stuff to change it.

2022-06-18 08:18 UTC, goose4429 commented
>> Defender: Forward charge stun equalized to tail sweep. Gives around 5s of stagger (for marines, it means around a 50% damage debuff). Range increased to 6. Purpose is making it less of a midcombat stun and more of a mobility ability that'll still tank your plasma, be it as initiation or retreat tool. I'd reduce windup to 0 but for some reason people want the windup and I still don't get why, probably stockholm syndrome, it just really likes to bug out when you're getting shuffled or moving.

As for defender, everything is done here: https://github.com/tgstation/TerraGov-Marine-Corps/pull/10448
People quite literally told you it's bad, and you do it again. 

It's a good thing you've realised it needs something to compensate for lack of stun, but 3sec of stun != 5sec of stagger. Stun allows quick killing, while stagger does nothing if marine just runs away. It only works if a marine stands there and shoots you, which does not happen most of the time - usually you're shot by others, while the target escapes. Range does nothing, you can buff it to 100 tiles if you want and give defender binocular vision - then at least it would be a funny mobility tool. 

Calling it "escape tool" or whatever doesn't make up for the fact that defender is intended to _defend_, and giving it escape tool instead of disable/initiation tool is not even funny. Once again, overall strong nerf. Killing potential is lost, and some irrelevant number increase doesn't make up for it. I don't understand how you find even comparable 3 secs of full disable over 5 secs of half damage (even damage-wise it's less, half of stagger is not utilized while marine is getting up).

2022-06-18 08:22 UTC, goose4429 commented
> Removed stagger from **most** of them.

**Most - which?** Only weapon I know which _could_ be changed this way is repeater, which has 1sec shoot delay and 1 sec stagger.

**Shrike** change is "good enough", since you've offset changes in stuns by insane buffs (HP+25%, -50% CD, speed). Try to offset other changes same way if you want them.

2022-06-18 10:16 UTC, Lumipharon commented
> Do you have any suggestions as to what stagger should do that isn't covered by any existing status effect?

No, because I think stagger is a good status effect.

> > I disagree with this because status effects are the main factor that makes combat something more than just damage vs health
> 
> And I disagree with that assesment, it turns into damage vs health in "do I have enough health to survive the stun before I'm able to do anything/do I have enough damage to crit the marine before he 1hand t39s a slug at me?". I don't remember when was the last time I took anything but heavy armor because of that.

It's conditional, and is entirely within your control. Without status effects it is not conditional, it is the entire game. Castes that cannot simply facetank and still contribute to the fight rely on status effects as a balancing factor, because as you put it 'do I have enough health to survive the damage before I'm able to do anything/do I have enough damage to crit the marine before I go horizontal'. There is no more "I objectively cannot survive the amount of firepower they have, but I can apply useful damage and still escape alive if I am smart with my stun usage." This is pretty fundamental to a top down game, where one side is mostly ranged damage based, and the other is mostly melee damage based.

2022-06-18 15:06 UTC, Losenis commented
>What? It is not an area denial tool.

I never claimed it was, I'm just buffing that aspect of them. Preemptively aciding a path is as dumb as it gets if you're only giving a marine lik 8 acid damage to their feet, but after spraying a push into a 1x1 choke it helps in keeping marines back just a few more second. Wording issue maybe?

>And buffing it from 10 to 20 secs or whatever just means marines will move forward 10 sec later. And that is given you've use it in the right place, and not just as a damage tool.

Yeah, that's intended. And 10 sec is a long while when it means every other xeno has 10 sec of cooldown or healing before said push. It's just not meant to be used in open ground or to cover one or two tiles, that's trash and it's still going to be trash.

>To sum up, this is a direct strong nerf to prae and spitter, and just a nerf to boiler

What? I didn't change anything about them other than increasing the acid turf's duration, how the hell is that a nerf? You can change the code for yourself, nothing about them had been nerfed.

>People quite literally told you it's bad, and you do it again.

They didn't offer any suggestions other than the person telling me I should add stun and another adding the windup back, and so I did. There's only so much that "this is bad" can do if there's no "here's how it can be better" to follow up. If you have any suggestions that'd give defender something in return in exchange for the stun's nerf, either say so or don't be surprised that the same is attempted. This is a draft for a reason.

>No, because I think stagger is a good status effect.

If that was the case the revolver wouldn't have been getting a hundred thousand nerfs given it kept its staggerspam. Stagger is ok on paper until you realize marines have little to no reason to not just grab stagger weapons en masse, which is also what got the old tesla's aoe stagger canned as well. Dual T39 can staggerlock you into the ground, and while dual wielding a shotgun can be a problem, that is easily replicated by just having one other marine out of 40+ in the general area just carrying a t39 as well.

It's only a good status effect in practice if you're not the one on the receiving end of it, you only have to ask ocelot.

2022-06-18 15:30 UTC, goose4429 commented
> What? I didn't change anything about them other than increasing the acid turf's duration

Yeah, changed my comment. Put something to indicate that you actually didn't.
And CLs good.

> They didn't offer any suggestions other than the person telling me I should add stagger

Yeah, I feel that. Pinged you in discord.

2022-06-19 04:57 UTC, Lumipharon commented
> If that was the case the revolver wouldn't have been getting a hundred thousand nerfs given it kept its staggerspam. Stagger is ok on paper until you realize marines have little to no reason to not just grab stagger weapons en masse, which is also what got the old tesla's aoe stagger canned as well. Dual T39 can staggerlock you into the ground, and while dual wielding a shotgun can be a problem, that is easily replicated by just having one other marine out of 40+ in the general area just carrying a t39 as well.
> 
> It's only a good status effect in practice if you're not the one on the receiving end of it, you only have to ask ocelot.

Revolver was a problem because it was highly spammable, with super low rate of fire and no need to reload for extended periods of time due to being a normal item.

Dual t39 has a similar issue but I just nerfed its akimbo stats to make it unreliable outside of pb range, although time will tell if that's sufficient.

The problems you've described are indicative of overaccessibility to status effects (and akimbo in general being fucking problematic due to combining high ROF with zero slowdown, but thats a whole other conversation), not the status effects itself.

If one guy is being a team player with slug shotgun, great. He cannot shoot past friendlies, and sacrifices raw dps/reload speed for status effects.

2022-06-19 22:49 UTC, Pariah919 commented
why isn't this atomized

2022-06-20 10:01 UTC, Al-1ce commented
Having been the first person to respond to your defender PR, I am a little surprised to see you try to do this again to an even larger extent.

Worth a TM? Yes. A merge? Probably not. Even in premise this sounds like a bad idea.

2022-06-20 22:11 UTC, shelteredfreak commented
I honestly think these changes arent too bad. 

A faster, more frequent (although less strong) stun is arguably stronger than a high cost, high cooldown stun.

Straight up buff to spray is good, especially with the dozen or so times I've seen marines just fucking run through it anyways.

A four second stun was honestly quite dumb tbh. And its hard to pull off anyways what with the windup and low range, hopefully this might fix that up a bit.

Why did stagger even ever exist, there is already stuns. I don't think stagger is a good effect at all, especially because if you are something like a queen or ravager, you are just gonna get bumrushed and buttfucked by one guy with slugs all because you cant use any of your abilities.

I know this doesn't mean much, but I really like this and hope it gets merged. It would be nice to mix up the gameplay a bit regardless.

2022-06-21 09:56 UTC, Autisem commented
crowd control is perfectly normal thing to have in a game and it does add some depth to combat.

That being said, stagger on xenos is an ass concepts and im glad its removed because there is no way to counter it other then "doge lmao"

2022-06-21 19:59 UTC, TiviPlus requested changes
![image](https://user-images.githubusercontent.com/57223640/174887175-7a55acdb-bc6e-4ce3-9c6a-91a298647c10.png)

2022-06-21 22:30 UTC, Losenis commented
> ![image](https://github.com/assets/57223640/7a55acdb-bc6e-4ce3-9c6a-91a298647c10)

![image](https://user-images.githubusercontent.com/72712909/174907490-0ddd2479-90a9-4169-8fb2-2dacda27d228.png)

2022-06-22 09:30 UTC, goose4429 commented
> Hunter: Replaced stealthed normal attack's stun with a blind + blur. A competent hunter can chain the stun with a pounce for a double stun with no cooldown that can bring someone down to almost crit from full health unless they're a chonky boi with heavy tyr2. Ideally this also gives a reason to use it outside of soloing marines, since a blinded marine is more prone to shooting randomly and potentially causing FF. Not the most fun thing to be around with, but hopefully is a better alternative.

Bruh. I'll just say that hunter is intended to be an ambusher. It IS the guy to solo marines. And it's less of an ambush if one stun is gone and marine can just run away, even if with funny screen effects. I do not support nerfs  aimed at weak caste's main combat role, making it even more useless.

2022-06-22 15:19 UTC, Losenis commented
>give him stagger resist

The guns are already getting their stagger lowered, so hunter shouldn't be getting staggered at all now. In fact no xeno should be getting staggered.

2022-06-26 08:59 UTC, goose4429 commented
> the game oughta be fun for both sides, to play as and to play against. 
> nerfs two xeno castes for no reason
nice test merge

2022-06-26 15:16 UTC, Losenis commented
If you have any ideas to make it not a nerf while still having the stun removed, I'd love to hear them. Unless stun is the only way you can stay competitive even with a hundred buffs elsewhere, in which case skill issue. Or you're just shitting on it to push your own pr before this one is even TMd in the server itself, that's cool too.

2022-06-26 19:17 UTC, goose4429 commented
> If you have any ideas to make it not a nerf while still having the stun removed, I'd love to hear them. Unless stun is the only way you can stay competitive even with a hundred buffs elsewhere, in which case skill issue. Or you're just shitting on it to push your own pr before this one is even TMd in the server itself, that's cool too.

Quite literally told you in comments above. Don't try to make it look like you care, lol.

2022-06-27 00:54 UTC, Losenis commented
The defender change that was canned when everyone had their input so I changed it into something weird and yet got called as being "the same", or the hunter stagger immunity that got canned when I was told to get rid of gun stagger changes for the TM? I went over your pr to see what your vision is and it's effectively just old defender with still as much stun as shrike's two stun abilities combined. Stuns being so common should go and stay go, come up with something else.

2022-06-29 01:10 UTC, lKiseki commented
I've stated my thoughts to Losenis personally a few times, but I wanted to put them out there in this PR, since there's some things I like and some things that I just can't help but squint at. I will be offering my feedback for various of these changes in no particular order, in hopes that it will serve to further this PR's development. Without further ado;

**Defender:** The changes have put Defenders in a complicated spot. I thought the stagger would be a great way to counteract the changes to Forward Charge, considering it's a 50% damage debuff, but that doesn't seem to be the case. Defender does not seem to have the speed nor the damage to make up for the loss of a valuable stun _(overtuned as it was)_, and struggles greatly when pursued. My suggestions for Defender are as follows; note that you're not meant to do _all_ of these suggestions if you choose to heed them, it's just multiple ideas I throw at Losenis to see if there's anything they'd personally prefer.
- Allow Forward Charge to be immediately used after Fortify. This will make it a more safer option to use, coupled with its buffed distance and stagger.
- Increase its running speed. This will slightly alleviate the caste's difficulties with rushers and help in a few other niche scenarios.
- Buff Crest Defense somehow.

**Shrike:** Easily my favorite out of these changes. New Shrike is an experience and a half. It's definitely changed a decent deal compared to what it was before, and I find myself liking these changes. The decreased cooldown and costs on its abilities make them that much more useful despite the loss of stuns, and the stat changes for Shrike give it an extra edge in combat that makes Shrike that much more enjoyable to play. I'd say Shrike has a tad bit too much durability currently, and could stand to lose a bit of health _(like 50 or so)_. I do have a few couple suggestions for this caste, despite it all...
- After these changes, Shrike seems to be a tad bit too durable. You could decrease its health and add stagger to its Unrelenting Force ability, rewarding proper usage of the ability with increased durability but offsetting it with a max. health loss.
- Could increase its slash damage just a bit, since it's definitely not doing that much damage in combat.

**Acid Puddle Changes:** To be completely honest, they're hardly noticeable. I wouldn't suggest buffing them further, either. Could just leave them be after your changes.

**Hunter:** Hunter was always a very oppressive caste, be it in 1v1 scenarios or as a backliner. This can be partially attributed to having two stuns, and being able to easily follow up with a third stun given proper conditions. Taking away one of its stuns was a good move for sure, but the changes you made to it are hardly compensating for it. I'd suggest giving it the same treatment as Shrike's fling and making it a 0.1s knockdown; should better compensate.

2022-06-29 02:31 UTC, Losenis commented
These feedback posts are what I live for.

For the defender, I'm still thinking on how to go forward with it. The ideas are noted, though another idea I had in mind is to just accept the windup and do what I did with the shrike, IE lessening cost and CD of the ability in exchange of stuns. I'm not entirely sure how it'd either synergize or clash with tail sweep yet, probably with tail sweep being there for multiple marines while charge is for a single one, or using both together really.

I'm not too fond of increasing speed not due to my own reasons but rather because I've heard enough people wanting the defender to be the slow tanky caste in thematic, which is also what had been said about no windup initially.

As for fortify, it does have a 1 second cooldown. It's past my knowledge how to make it have no cooldown on one single ability but it might be viable to give it very little cooldown to make it more attractive to use midcombat without the "Oh no now I'm stuck for 1 full second doing nothing" instances. Not gonna lie it already sounds funny to imagine a defender microing mid-fight vs a T35 and fortifying each shot, and now that I think of it, it COULD give an edge vs low firerate high damage weapons. Pure theoreticals, though. Will have to ask if I can.


The acid spray is meant to be situational, on the offensive it'll have almost zero effect unless you land a lucky spray on the tad or somewhere else the marines can't walk away from. It's on pushes that they have a noticeable effect, at least when I played prae. Spraying the hallway of prison to cover the retreat of wounded xenos just stalls the marines for a great while, as the area denial tool it's meant to be. The few that realize they can just run through it usually aren't followed by the great majority either.


And hunter is the most difficulty I'm having with regarding changes. I can't argue that it doesn't suck right now, but even thogh the bumpslash stun that would just set up a pounce once up had to go, the potential buffs have been tried and were disastrous sometimes. Speed and damage had 2 hunters almost soloing groups back in the day that was most notable in big red by the open spaces to run around in, and health might turn it too tanky for what it's meant to be as if it was a tanky runner. The blind was the best I could come up with, but I misjudged the effect and it does basically nothing given the hunter would stay in melee range anyway.

There is an idea, but I've yet to figure out how to implement it. Adding the warrior's lunge grab to the hunter's pounce and having the speed penalty of dragging someone not happen for a second or two. Think a hunter in LV jumping out the vines and dragging a marine into the darkness, that kind of theme. Details like stun time, duration of ability, the range of the drag, and so I'm not even bothering with till I know how to code it in, though.

2022-07-05 07:09 UTC, Zaffinomlb commented
At the time of me writing these changes to the hunter stealth attack might not have been merged yet.

If that is the case then I will look into the matter again, but as it stands now there is no knockdown at all. That being also said this is considered a massive nerf to the ability, I don't think that can be denied. I see what you are wanting to go for with the possibility of a damage modifier from stealth (I know that's currently not how it works) but I just feel that would be a savage by another name. Stealth savage so to speak.

Generally, don't like the change but I am also bias in this matter.

2022-07-05 14:32 UTC, Losenis commented
It wasn't even supposed to be TMd since 3 days ago since it lost the TMC tag over new commits, it hasn't been updated since then ingame.

2022-07-21 20:24 UTC, BraveMole commented
Nah this won't cut it. Feddback is globally bad and it's a pain to play xenos with that

2022-07-21 20:24 UTC, closed without merging

2022-07-22 02:53 UTC, Losenis commented
"Feedback is globally bad"
Am I living in a parallel world or something

2022-07-22 20:13 UTC, goose4429 commented
> "Feedback is globally bad" Am I living in a parallel world or something

Yes