Ports TG's/Tau Ceti's welding effect
tgstation/TerraGov-Marine-Corps pull request #10504
Opened 2022-06-21 03:42 UTC by RipGrayson

## About The Pull Request

Title.
Ports the TG port of Pariah Station's port of Tau Ceti's welding effect, adds support for it to many objects.
Because we have multi-tile objects I had to slightly alter the logic so the welding flame looks neater when applied to large doors.

## Why It's Good For The Game
It looks really neat and gives good visual feedback for when somebody is welding an object.
This example gif is from the TG codebase, but the same effect applies here if a marine welds a wall.
![165455987-2917c11a-14e2-4a4e-adf6-50bd9d4e212c](https://user-images.githubusercontent.com/49290523/174711386-7a87f807-0c41-46be-bb4e-7f1560d40e46.gif)

## Changelog
:cl:
add: Ported TG's welder effect for use when welding doors/objects.
/:cl:

2022-06-21 03:44 UTC, novaepee commented
Really good vfx to show that engineers are fixing cades.

2022-06-21 06:24 UTC, Nanu308 commented
Put Ckey next to the CL at the top, so people can see who added it ingame

2022-06-21 07:08 UTC, chesse20 commented
can we recolor this for the plasmacutter

2022-06-21 08:17 UTC, TiviPlus requested changes

2022-06-21 08:17 UTC, TiviPlus commented on code/game/objects/items/tools/maintenance_tools.dm
> +		if((target.dir == 1) || (target.dir == 2))
A) dirs should use proper defines (ex: 1 = NORTH)
B) why not use & (ie thing.dir & NORTH)

2022-06-21 08:17 UTC, TiviPlus commented on code/game/turfs/walls/walls.dm
>  		playsound(src, 'sound/items/welder.ogg', 25, 1)
remove all src.proc() in this file you added

2022-06-21 14:37 UTC, Losenis commented
Finally, now people will understand why I'm actually slugging them when I'm next to the cades getting shuffled

2022-06-21 16:53 UTC, Kuro020 approved these changes

2022-06-21 16:58 UTC, Losenis commented
Wait does this also apply to repairing combat robots and yourself? Please say yes

2022-06-21 22:27 UTC, Lumipharon commented
The only way this could be cooler is if you could move the weld effect while welding (i.e. make it follow the crack of an airlock, or randomly move spots when fixing shit)

2022-06-22 01:39 UTC, RipGrayson commented
> Wait does this also apply to repairing combat robots and yourself? Please say yes

As of the most recent commit the welding effect will show when repairing metal limbs, but it's vaguely glitchy and I need to bugfix it more.

> The only way this could be cooler is if you could move the weld effect while welding (i.e. make it follow the crack of an airlock, or randomly move spots when fixing shit)

There's no ability to randomly adjust x or y coordinates for overlay effects that I'm aware of. If there were I wouldn't have to make a whole new effect just to get the welding flame to properly center on multi-tile doors

2022-06-22 01:59 UTC, Lumipharon commented
> There's no ability to randomly adjust x or y coordinates for overlay effects that I'm aware of. If there were I wouldn't have to make a whole new effect just to get the welding flame to properly center on multi-tile doors

Dunno if it would actually be practical, but you can do it. 
You can check out gun attachment codes for x and y offsets and how it works there, then you could just be x_offset = rand (-5, 5), update_overlay etc. 

Then for welding airlocks closed you could have a different overlay effect, where the effect moves during the animation to follow where the airlock opening is. Actually come to think of it, that would also probs be easier for the randomisation above as well. Just make the overlay animation more frames, and have it move around in the animation itself. Of course that means you might need to have different animations for different objects.

If you don't want to mess with in this PR though, I can play with it after it's merged.

2022-06-22 20:57 UTC, MereWalker commented
It's the small things that make the difference. Thank you for this!

2022-06-25 21:18 UTC, BraveMole requested changes

2022-06-25 21:18 UTC, BraveMole commented on code/game/objects/items/tools/maintenance_tools.dm
> +		if((target.dir & NORTH) || (target.dir & SOUTH))
```suggestion
		if((target.dir & NORTH|SOUTH))
```
Should work, not tested

2022-06-27 07:23 UTC, TiviPlus approved these changes

2022-06-27 07:23 UTC, merged