Smart pistol
tgstation/TerraGov-Marine-Corps pull request #10511
Opened 2022-06-22 09:18 UTC by goose4429

## About The Pull Request

re-upload of https://github.com/tgstation/TerraGov-Marine-Corps/pull/10465 because branch rebase gave me binary aids.

About The Pull Request
Adds TX-13, the smartpistol to the game. Design is based on Calico M-950 and balanced for the actual game.
It is mostly a flavor gun, since only SGs, Cap and ERTs can use it. And SGs are unlikely to prefer pistol to proper MG.

Stats are mostly same as TP-14. Captain has the gun roundstart. FC has captain's mateba roundstart.
Weapon sprite done by Crow (Crovus) and approved by Ocelot.

![image](https://user-images.githubusercontent.com/42085626/174992748-d5d55d34-56f4-470c-92c2-65e407f45ea4.png)

## Why It's Good For The Game

Good looking, unique pistol.
More people will be going Captain. /s

## Changelog
:cl:
add: Added TX-13, the smartpistol
balance: Captain has cool Smartpistol belt. Cool Mateba belt moved to FC.
/:cl:

2022-06-22 17:26 UTC, Kuro020 approved these changes

2022-06-22 17:28 UTC, Kuro020 requested changes
ok the mob sprites need work, ignore the approval just saw that

2022-06-23 19:25 UTC, Kuro020 approved these changes

2022-06-24 12:53 UTC, Pariah919 reviewed
Move FC stuff to vendor options, and swap this over to 25 round magazines or slap the 88Mods level of slowdown onto the wielded statistics, I'd rename this to smart personal defense weapon over pistol but that's optional.
Slap the Mateba into the Captains Locker.

2022-06-27 07:26 UTC, TiviPlus requested changes
Why for captain

2022-06-29 12:08 UTC, TiviPlus requested changes

2022-06-29 12:08 UTC, TiviPlus commented on code/game/objects/items/storage/belt.dm
> +	. = ..()
No numbers in types please

2022-06-29 12:08 UTC, TiviPlus commented on code/modules/projectiles/guns/pistols.dm
> +	desc = "The TX-13 is a latest solution for personal officer defence produced by Terran Armories. A cutting-edge miniaturization technology allows mounting of smartgun IFF system on the pistol, albei
Why is this using TX instead of the naming convention

2022-06-29 12:08 UTC, TiviPlus commented on code/modules/projectiles/guns/pistols.dm
> +	item_state = "tx13"
ditto

2022-06-29 14:24 UTC, TiviPlus approved these changes

2022-06-29 14:24 UTC, merged