Prae acid spray buff
tgstation/TerraGov-Marine-Corps pull request #10522
Opened 2022-06-25 08:48 UTC by goose4429

## About The Pull Request

Makes spray cover ground a bit faster. Removes slow after use.

## Why It's Good For The Game

Imagine standing still, open to stagger, for almost a second for spew to actually start moving towards marines, only to see them casually walking away faster than spit covers the ground.

Slowdown is questionable. I always thought it's just me getting slowed by shotguns or something, but then found out there is an actual slowdown applied to prae just because it used its only skill. What. I do not see what purpose it serves, and it leaves you open to any kind of counterattack - especially since you can just move diagonally towards prae to dodge the slow spray, and gun it down, while its slowed and has its only skill spent.

If it opens any kind of balance problems, it is possible to increase delay change spray in other ways.

## Changelog
:cl:
balance: Prae Spray no longer slows after use, and is quicker to cover ground
/:cl:

2022-06-25 10:02 UTC, Vallat commented on code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
> +			addtimer(CALLBACK(src, .proc/continue_acid_cone_spray, T, next_normal_turf, distance_left, facing, direction_flag, spray), 2)
```suggestion
			addtimer(CALLBACK(src, .proc/continue_acid_cone_spray, T, next_normal_turf, distance_left, facing, direction_flag, spray), 0.2 SECONDS)
```

2022-06-25 22:48 UTC, usnpeepoo commented
prae is already powerful enough, removing the slow is the only thing that should be acceptable

2022-06-26 00:17 UTC, Naaanii commented
Double buff isn't good for an already decent caste. Agree with the above comment, removing slowdown would be nice.

A big aoe knockdown doesn't really need to be faster as the slight warning sign and windup allows people to try and dodge it but a Prae in range can also practically make it undodgeable so a faster spray is really not needed.

2022-06-26 09:25 UTC, goose4429 commented
> Double buff isn't good for an already decent caste. Agree with the above comment, removing slowdown would be nice.
> 
> A big aoe knockdown doesn't really need to be faster as the slight warning sign and windup allows people to try and dodge it but a Prae in range can also practically make it undodgeable so a faster spray is really not needed.

Making it less dodgeable is the purpose of PR.
Dodging shotgun PB or a rocket is pretty hard, you know? But for spit, you just walk away, and it literally allows you to outrun it.

2022-06-26 12:25 UTC, Naaanii commented
> > Double buff isn't good for an already decent caste. Agree with the above comment, removing slowdown would be nice.
> > A big aoe knockdown doesn't really need to be faster as the slight warning sign and windup allows people to try and dodge it but a Prae in range can also practically make it undodgeable so a faster spray is really not needed.
> 
> Making it less dodgeable is the purpose of PR. Dodging shotgun PB or a rocket is pretty hard, you know? But for spit, you just walk away, and it literally allows you to outrun it.

Shotgun PB isn't really area denial CC so I don't understand the comparison, rockets are a one shot burst damage sort of deal. Only light armour can actually outrun a spray effectively, and if hit by the spray, they're most likely going to die for wearing light armour, and like I said, a well placed and timed spray is undodgeable especially in cqc which Xenos excel at. Making it faster than all other sprays just makes it overtuned and without the slowdown, the double buff just makes Prae way too strong at range and CQC (which it already is). Added speed also kind of removes the point of the warning icon and leaves little counter play to the ability other than just predicting or using future vision.

2022-06-26 15:10 UTC, Losenis commented
>Imagine standing still, open to stagger, for almost a second for spew to actually start moving towards marines, only to see them casually walking away faster than spit covers the ground

Either you:
Sprayed at max range
Sprayed alone at marines expecting it
Sprayed out in the open without obstructions for marines
Combination of the above

Spray can absolutely massacre marines already in the middle of a fight given it's not only a stun but also a constant source of burn damage that cover several tiles, and in that specific case it being burn damage is actually worse for marines given it causes more pain and will weaken/crit the marines far faster than the brute damage the other xenos would be inflicting.

2022-06-27 07:26 UTC, TiviPlus requested changes
Double buff definitely not gonna be accepted

2022-06-27 10:57 UTC, goose4429 commented
Apparently double buffs are not accepted. Reverted speed buff.

Funny:
Quite literally searched "buff" and half of actual buffs are double buffs.
https://github.com/tgstation/TerraGov-Marine-Corps/pull/10499
https://github.com/tgstation/TerraGov-Marine-Corps/pull/9695
https://github.com/tgstation/TerraGov-Marine-Corps/pull/9578

2022-06-29 13:52 UTC, Naaanii commented
> Apparently double buffs are not accepted. Reverted speed buff.
> 
> Funny: Quite literally searched "buff" and half of (relevant) merged buffs are double buffs. #10499 #9695 #9578

2 were features in a not so great spot or severely unused and the AMR got completely reverted in the end.

Prae is already in a good spot and doesn't even require buffs but slowdown removal sounds like a good idea with stuns being tweaked.

2022-07-16 16:14 UTC, goose4429 commented
Funny 20 days old one-line PR

2022-07-16 16:14 UTC, closed without merging