Updates Hypospray belt and chem colours.
tgstation/TerraGov-Marine-Corps pull request #10549
Opened 2022-06-29 02:58 UTC by Arctrooper8

## About The Pull Request

New hypospray belt:
![image](https://user-images.githubusercontent.com/95723150/176340944-be6bd96a-b0d3-4e1d-b18d-768dc3574bb9.png)
order of items (bottle means a bottle of the previously listed chem): Big Bicard, Bottle, Big Kelo, Bottle, Big Trama, bottle, Big Tricord, bottle, Big dylo, Big Ina, Big Dex, Big Space, Big imialky (a mixture hypo that displays how multiple chems in one hypo works) big QC, normal hypervene, health analyzer.

New colours:
QC: (pink because it restores blood and halts IB)
![image](https://user-images.githubusercontent.com/95723150/176339664-85e22120-b6fc-4e88-a202-2359d4eec185.png)
Nanoblood: (red for blood)
![image](https://user-images.githubusercontent.com/95723150/176339685-bc906e15-9e3a-4f64-a90e-9a16c5ad495e.png)
Oxy: (Black because it's a stronger painkiller)
![image](https://user-images.githubusercontent.com/95723150/176339725-fc5e37ea-8e88-45e5-a789-2ad25541d018.png)
Para: (Light grey because it's a weaker painkiller)
![image](https://user-images.githubusercontent.com/95723150/176339753-0a54009a-2efd-4b67-abda-c67bab61f166.png)
RR: (Dark Red because it has red in the name and it's a dangerous drug)
![image](https://user-images.githubusercontent.com/95723150/176341726-0e321336-5225-4595-ad7d-7955fe5c3518.png)

Also updates all hypospray descriptions to explain what they do on examine.

## Why It's Good For The Game

Hypospray belt is a bit of a joke right now, it's clunky to use, lacks most of the chems you'd need, and simply pales in comparison to the other belts.

By changing the chem liquid colors to match pill bottles you can have a better visual indicator of what each hypospray is, useful when they move around so much.
Using big hyposprays also 

## Changelog
:cl:
expansion: Changes a few chem colours, nanoblood, QC, painkillers, and RR.
del: Fully removes Bottlecases.
qol: Chemical liquid colours now match their pill bottles.
qol: Premade Hypospray descriptions have been updated to explain what their chems do.
balance: Changes the content of Hypospray belt.
fix: No more invisible things in hypospray belt.
/:cl:

2022-06-29 06:55 UTC, goose4429 commented
Why are you removing bottle cases?

2022-06-29 17:32 UTC, Kuro020 approved these changes

2022-06-29 23:24 UTC, Arctrooper8 commented
> Why are you removing bottle cases? I'm using it without regards to your hypo belt. Please don't remove things 'just because' - people asked me what happened to injector case like 10 times already. Now you're removing bottle cases because... why? You want to break corpsman vendor and people loadouts again?

How are you even getting bottle cases without the hypospray belt? They're only used in the hypo belt. If you're talking about syringe cases (which do the exact same thing) those are still there.

> Also, giving 10 big hypos is an overkill. Although I feel that it's a cool thing to do to make it more useful. Still, 10 too many - its 80 corpsman points.

Big hypos are overpriced for what they give, they're twice as big as a normal hypo yet cost 4 times. I feel a corpsmen only medical belt that can only hold hypos, injectors, beakers, and bottles having a bunch of big hypos isn't that absurd. Especially when you see how much pill bottles can hold.

> Also, the problem with belt was low chem capacity. Normal belt has max 21x240u chems, this PR in current state has 12x(120u+60u) = 6x180u. That's still super meh. That is also the reason why cases are a thing.

Exactly why I gave them Big hyposprays, the bottle cases were a clunky solution and somewhat questionable solution. 

> **As for fixes, fix good. Sprites good. Other than that, in current state PR bad. You should split balance changes and sprite changes into different PRs. Atomize.**

If worst comes to worst I'll split them, but I feel they're related enough that I can justifty them being in the same PR.

Overall, this probably isn't gonna make hypospray belt used more. But it will make it less painful for those trying it or doing a gimmick.

2022-06-30 07:21 UTC, goose4429 commented
> How are you even getting bottle cases without the hypospray belt? They're only used in the hypo belt. If you're talking about syringe cases (which do the exact same thing) those are still there.

Huh, okay then. But still, have problem - see below.

> Big hypos are overpriced for what they give, they're twice as big as a normal hypo yet cost 4 times. I feel a corpsmen only medical belt that can only hold hypos, injectors, beakers, and bottles having a bunch of big hypos isn't that absurd. Especially when you see how much pill bottles can hold.

I think making big hypo cost 8 or so would be reasonable, probs will do soon. But anyway, there's a high chance that maints will ask to rebalance just because of this. I'd make non-relevant hypos (QC or whatever) smaller just to save you nerves. 

> Exactly why I gave them Big hyposprays, the bottle cases were a clunky solution and somewhat questionable solution.

But you've decreased total chem capacity. That's what I am saying. It's possible to overcome it easily just by taking pill bottles and using them to refill hypos, but that doesn't help the belt much. I'd just stick with both big hypos and big cases. I don't really get why you'd remove them, mostly because leftclick bottle leftclick hypo is same as rightclick case leftclick hypo, and latter has more chems.

> Overall, this probably isn't gonna make hypospray belt used more. But it will make it less painful for those trying it or doing a gimmick.

Hope so. Although chem capacity for base meds is _really_ low. I'm rooting for cases to be intact, so that belt is actually much better.

2022-07-10 07:57 UTC, TiviPlus requested changes
As a side note I hate reviewing balance prs and you not atomizing that out is why it took me this long

2022-07-10 07:57 UTC, TiviPlus commented on code/game/objects/items/reagent_containers/hypospray.dm
> +		var/image/filling = image('icons/obj/reagentfillings.dmi', src, "[icon_state]10")
use update overlays

2022-07-10 07:57 UTC, TiviPlus commented on code/game/objects/items/reagent_containers/hypospray.dm
> +			if(10 to 24) 		filling.icon_state = "[initial(icon_state)]10"
Dont use same line ifs

2022-07-10 07:57 UTC, TiviPlus commented on code/game/objects/items/reagent_containers/hypospray.dm
> +/obj/item/reagent_containers/hypospray/advanced/proc/display_reagents(mob/user)
Autodoc

2022-07-15 09:06 UTC, merged