Makes red alert security level live up to its name
tgstation/TerraGov-Marine-Corps pull request #10552
Opened 2022-06-29 17:42 UTC by RipGrayson

## About The Pull Request

Have you ever wondered why during red alert there's no theming at all? If you didn't see the announcement when you might not even know that the ship is under a dangerous threat at all.

This PR fixes that, when the ship changes to red security level, all lights on the ship gain a red tint. (as well as a minor reduction in intensity for atmosphere). In addition, changing to delta will also sound self destruct alarms through the ship until either the alert is changed or the xenos manage to knock out power.

~~I also fixed like five lines of code that were keeping icons from displaying correctly for tables~~

## Why It's Good For The Game

The effect is cool and really gives the impression that the ship is under attack. It is a shame that currently the ship can be under attack by xeno forces and there's no blaring alarms or overt indication that things have gone wrong.

## Changelog
:cl:
expansion: Red alert now makes lights red when active.
expansion: Delta alert will now sound self destruct alarms when active.
fix: Fixed fancy tables not displaying correctly
fix: Fixed invisible blockers being visible
soundadd: Added a warning sound for self destruct during Delta alert levels.
imageadd: Added some custom icons for red tinted lights during red alert.
/:cl:

2022-06-29 17:59 UTC, Kuro020 approved these changes

2022-06-29 19:29 UTC, goose4429 commented
No hell march music 0/10
https://www.youtube.com/watch?v=e3YzmjmAGoI

2022-06-30 02:42 UTC, Derrick2Electricboogaloo commented
Very nice. I have always wanted something such as this. I want to feel as if shit is about to go really bad

2022-06-30 02:46 UTC, FosterGrime-Heymynameslouie commented
based pr spede merhg

2022-07-04 15:47 UTC, TiviPlus requested changes

2022-07-04 15:47 UTC, TiviPlus commented on code/datums/marine_main_ship.dm
> +			light.light_color = "#ffffff"
use color defines please

2022-07-04 15:47 UTC, TiviPlus commented on code/datums/marine_main_ship.dm
> +						SD.set_picture("default")
```suggestion
						SD.set_picture("default")
```

2022-07-04 15:47 UTC, TiviPlus commented on code/datums/marine_main_ship.dm
> +						SD.set_picture("redalert")
```suggestion
						SD.set_picture("redalert")
```

2022-07-04 15:47 UTC, TiviPlus commented on code/datums/marine_main_ship.dm
> +				FA.update_icon()
```suggestion
				FA.update_icon()
```

2022-07-04 15:47 UTC, TiviPlus commented on code/game/objects/effects/misc.dm
> +	mouse_opacity = 0
use the opacity define please

2022-07-04 15:47 UTC, TiviPlus commented on code/modules/power/lighting.dm
> +/obj/machinery/light/mainship/
```suggestion
/obj/machinery/light/mainship
```

2022-07-04 15:47 UTC, TiviPlus commented on code/modules/power/lighting.dm
> +	var/datum/looping_sound/alarm_loop/lightalarm
This isnt very performant and is probably going to overlap and maybe be earrapey

2022-07-14 17:38 UTC, merged