Adds code to enable preventing reagent container refills
tgstation/TerraGov-Marine-Corps pull request #10551
Opened 2022-06-29 15:54 UTC by QualityVan

## About The Pull Request
The frame from #7814 , but purely as an option. No gameplay changes, the var enabling it isn't active on anything.

## Why It's Good For The Game
Lets rarer chems be available in vendors in a limited amount, rather than forcing them to either be absent or infinite.

## Changelog
:cl:
code: Reagent containers can be set to not allow restocking after use.
/:cl:

2022-06-29 20:46 UTC, Weedmaster77 commented
like what chems?

2022-07-03 11:10 UTC, TiviPlus requested changes

2022-07-03 11:10 UTC, TiviPlus commented on code/game/objects/items/reagent_containers/reagent_container.dm
> +/obj/item/reagent_containers/proc/has_initial_reagents()
autodoc

2022-07-04 09:26 UTC, Autisem commented
This should prop be done per reagent bottle from the vendor and not on vendor level, does this mean you cannot refil bica bottles anymore?

2022-07-04 15:21 UTC, merged