Ghost qol: health scanner, various teleporter support
tgstation/TerraGov-Marine-Corps pull request #10622
Opened 2022-07-22 23:29 UTC by TheOneAndMightyRed

## About The Pull Request

Ghosts get a health scanner, toggleable in the Ghost verb tab.
Added support for ghost interaction (by clicking on said objects) for:
- Medevac beacon and stretcher
- Linked ASRS teleporters
- Xeno tunnels
- Shuttle computer

Opened as draft because its like 1:30 am here and i wanna sleep.
To-do:
- Make access_ghost.dm not shit.
- Actually test my shit properly.

## Why It's Good For The Game

As it turns out, people die a lot in a PvP server and become ghosts for a good 30 minutes.
Being able to follow people through various teleportation methods as a ghost good.
Orbit menu searching and WASDing around the map to get to the linked teleporter bad.
Easy way for ghosts to go shipside/ groundside good.
Using convoluted jump menu in ghost tab bad.
Health scanner so people can point and laugh at the guy who got forcefed 4 inaprov pills and is unconcious for 20 minutes straight good.

## Changelog
:cl:
qol: Ghosts get a health scanner. Toggable in ghost menu ("Toggle Health Scanner" verb).
qol: Ghosts can teleport through ASRS deployable teleporters.
qol: Ghosts can teleport through Medevac equipment.
qol: Ghosts can teleport through Xeno tunnels.
qol: Ghosts can teleport using the Shuttle control computers located at each LZ and CIC.
/:cl:

2022-07-23 19:50 UTC, Wayland-Smithy commented
Very nice! I've been meaning to hookup ghost attack for teleporters and portals. Mind adding `/obj/effect/wraith_portal` to your list? Just needs to check if `linked_portal` is valid and force move to it.

2022-07-24 07:13 UTC, TheOneAndMightyRed commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +	if(!linked_beacon || !linked_beacon.loc) //TODO: Redo medevac links
This and the other medevac checks probably require a rewrite on how linking stretchers work in da future.
Outside the scope of PR therefore a TODO.

2022-07-27 11:36 UTC, BraveMole requested changes

2022-07-27 11:36 UTC, BraveMole commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +	if(!linked_beacon || !linked_beacon.loc) //TODO: Redo medevac links
!linked_beacon?.loc should work. Same remark for the rest

2022-07-27 11:36 UTC, BraveMole commented on code/modules/mob/dead/observer/observer.dm
> +	var/obj/item/healthanalyzer/ghost/healthscanner = new()
No new in declaration , should be in Init

2022-07-27 11:36 UTC, BraveMole commented on code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
> +	linked_portal ? user.forceMove(get_turf(linked_portal)) : null
Use a if that is terrible

2022-07-28 09:01 UTC, BraveMole requested changes

2022-07-28 09:01 UTC, BraveMole commented on code/modules/mob/dead/observer/observer.dm
> +	var/obj/item/healthanalyzer/ghost/healthscanner
autodoc

2022-07-29 10:56 UTC, TheOneAndMightyRed commented on code/game/objects/items/scanners.dm
> +	patient = Target
Need an example on how to do that. Can ya point me to a part of the code where that was implemented in?

2022-08-07 18:53 UTC, TheOneAndMightyRed commented
Gonna reopen when i got time to fix stuff.

2022-09-03 08:43 UTC, TheOneAndMightyRed commented
Hopefully git actually does what i want it to do, gimme a moment

2022-09-03 08:44 UTC, TheOneAndMightyRed commented
wew it still works

2022-09-04 07:44 UTC, XSlayer300 commented
Will the refresh button ever work? Just reminding that since the topic of ghost stuffs.
![image](https://user-images.githubusercontent.com/35091844/188303056-3d3e93a7-d902-4f7b-a40d-1d5f8d3cf6af.png)

2022-09-04 09:37 UTC, TheOneAndMightyRed commented
Uuuh i assume that is on the orbit menu? I very rarely use the orbit menu so i don't know much about it. But lemme take a look anyway.

2022-09-04 09:43 UTC, BraveMole requested changes
I'm not sure I was clear enough on discord so here it is:

The idea is really good, but giving ghost an /obj/item/healanalyzer is not acceptable. The probably only good way of adding this feature is by refactoring health analyzer to be a component.

2022-09-09 01:02 UTC, closed without merging