AR-21 Skirmish rifle (AP buff)
tgstation/TerraGov-Marine-Corps pull request #10621
Opened 2022-07-22 22:30 UTC by Liznerd

## About The Pull Request

Changes the 10x25mm (heavy rifle bullet) penetration from 10 to 15 and the sunder from 1.25 to 1.5

## Why It's Good For The Game

makes the AR-21 a real "bigger than average round" rifle, always overshadowed by the BR-64

## Changelog
:cl:
balance: Buffed AR-21 AP and sunder
/:cl:

2022-07-24 21:17 UTC, Lumipharon commented
This buffs the MG-27, MKH, and ALF.
Incidently this makes the projectile almost identical to the mpi bullet.

2022-07-25 22:59 UTC, Liznerd commented
> This buffs the MG-27, MKH, and ALF. Incidently this makes the projectile almost identical to the mpi bullet.

MG-27 uses 10x27mm, the next one is the storm rifle i think and im pretty sure it uses its unique ammo type, no idea about the last one

2022-07-25 23:04 UTC, Lumipharon commented
> > This buffs the MG-27, MKH, and ALF. Incidently this makes the projectile almost identical to the mpi bullet.
> 
> MG-27 uses 10x27mm, the next one is the storm rifle i think and im pretty sure it uses its unique ammo type, no idea about the last one

calibre has no connected with projectile type used, it is used purely for sorting the actual bullet items.
The default_ammo var is what actual projectile is actually fired.
![image](https://user-images.githubusercontent.com/7869430/180889071-28c8a321-ecab-4f7a-a6ed-e079b88018b4.png)

2022-07-26 04:30 UTC, Liznerd commented
> > > This buffs the MG-27, MKH, and ALF. Incidently this makes the projectile almost identical to the mpi bullet.
> > 
> > 
> > MG-27 uses 10x27mm, the next one is the storm rifle i think and im pretty sure it uses its unique ammo type, no idea about the last one
> 
> calibre has no connected with projectile type used, it is used purely for sorting the actual bullet items. The default_ammo var is what actual projectile is actually fired. ![image](https://user-images.githubusercontent.com/7869430/180889071-28c8a321-ecab-4f7a-a6ed-e079b88018b4.png)

oh looks like you are right, any idea on how to only improve the ar-21? looks like you understand the code better, would be terrible to make a seasonal weapon broken  yes

2022-07-26 06:06 UTC, Lumipharon commented
Either creat a new ammo type for the gun, or really just use the mpi bullet.

2022-07-27 02:56 UTC, Liznerd commented
> Either creat a new ammo type for the gun, or really just use the mpi bullet.

got it, what is the mpi bullet thing anyways?

2022-07-27 04:30 UTC, Lumipharon commented
> > Either creat a new ammo type for the gun, or really just use the mpi bullet.
> 
> got it, what is the mpi bullet thing anyways?

rifle/mpi or whatever... for the mpi.

2022-08-06 13:53 UTC, Pariah919 requested changes
Sunder only and this is fine by me.

2022-08-10 00:54 UTC, closed without merging