Add overlay short description on hypospray and pill bottles
tgstation/TerraGov-Marine-Corps pull request #10664
Opened 2022-08-01 15:09 UTC by BraveMole

## About The Pull Request

Title

## Why It's Good For The Game

Cm has it and I won't allow TGMC to fall behind in QOL in any department

## Changelog
:cl:
add: Add overlay short description on hypospray and pill bottles
/:cl:

2022-08-02 03:39 UTC, Arctrooper8 commented
Pictures? I'm confused by what this actually is.

2022-08-04 11:09 UTC, TiviPlus requested changes
As a side note could later make this setable by players

2022-08-04 11:09 UTC, TiviPlus commented on code/game/objects/items/reagent_containers/hypospray.dm
> +	var/mutable_appearance/desc= mutable_appearance()
```suggestion
	var/mutable_appearance/desc = mutable_appearance()
```

2022-08-04 11:09 UTC, TiviPlus commented on code/game/objects/items/reagent_containers/hypospray.dm
> +	description_overlay = "Md"
Suggestion, maybe capitalize the D? Ie MD is 2 chems Md is one chem

2022-08-04 11:09 UTC, TiviPlus commented on code/game/objects/items/storage/firstaid.dm
> +	var/mutable_appearance/desc= mutable_appearance()
```suggestion
	var/mutable_appearance/desc = mutable_appearance()
```

2022-08-07 18:08 UTC, merged