Self Harm Toggle
tgstation/TerraGov-Marine-Corps pull request #10732
Opened 2022-08-08 19:47 UTC by RikuTheKiller

## About The Pull Request

Similarly to another PR made by a maintainer (The same maintainer that helped me make this one.), this PR prevents you from accidentally hitting yourself. Except this one, like, actually works.

It adds a keybind for toggling self-harm. It prevents you from hitting yourself while on harm intent while unarmed and hitting yourself at all while holding a weapon. Eating, healing, or hitting yourself with anything else still works just fine. (And if you want to do suicide, simply toggle it back on.) It defaults to on.

## Why It's Good For The Game

Maybe because hitting yourself with a harvester mid-fight and breaking your bones isn't exactly, well, great? (Or any weapon, for that matter.)

## Changelog
:cl:
add: new keybind for toggling self-harm, defaults to on
/:cl:

2022-08-08 19:50 UTC, BraveMole requested changes

2022-08-08 19:50 UTC, BraveMole commented on code/game/objects/items/weapons/weapon.dm
> +		return ..()
```suggestion
	return ..()
```
the else is useless in that context

2022-08-08 19:50 UTC, BraveMole commented on code/modules/mob/mob_defines.dm
> +	var/do_self_harm = TRUE
should probably put that var near in_throw_mode

2022-08-09 07:40 UTC, RikuTheKiller commented
Guess I'll just fetch upstream while I'm here.

2022-08-11 08:59 UTC, merged

2022-08-13 12:38 UTC, Texicos commented
they removed the fucking skill issue from TGMC, can't have shit