Fixes storage module destroying all their contents
tgstation/TerraGov-Marine-Corps pull request #10759
Opened 2022-08-13 21:41 UTC by JohnFulpWillard

## About The Pull Request

Destroying or unequipping the storage module will now cause it to drop all its contents to the floor.

## Why It's Good For The Game

Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/6055

## Changelog
:cl:
fix: Storage modules will now drop their contents when unequipped/destroyed.
/:cl:

2022-08-13 21:50 UTC, BraveMole approved these changes

2022-08-13 21:50 UTC, BraveMole commented on code/modules/clothing/modular_armor/attachments/storage.dm
> +		for(var/obj/item/all_items as anything in storage.contents)
```suggestion
		for(var/obj/item/all_items AS in storage.contents)
```
We have an alias for as anything in TGMC

2022-08-13 21:50 UTC, BraveMole commented on code/modules/clothing/modular_armor/attachments/storage.dm
> +	for(var/obj/item/all_items as anything in storage.contents)
ditto

2022-08-13 22:21 UTC, Lumipharon commented
What is this fixing? Module storage is not deleted when you remove it.
![image](https://user-images.githubusercontent.com/7869430/184515224-95e7b2b9-b09b-4795-83ff-adce472ea519.png)

2022-08-13 22:27 UTC, BraveMole commented
> What is this fixing? Module storage is not deleted when you remove it.

Yeah it just empties it ?

2022-08-14 02:32 UTC, Losenis commented
Is it possible that this is only on jaeger exoskeleton? I remember very well this actually working when I need to move contents from a loadout with a xenonaut of one weight to a xenonaut of another weight. I was even able to interact with the module outside the armor to put or retrieve items from it.

2022-08-14 02:36 UTC, Losenis commented
Tried to replicate bug report with both xenonaut and exoskeleton, it works as intended. Something else might've caused the bug to happen, this fix isn't necessary and might not actually fix what could've really happened.

![image](https://user-images.githubusercontent.com/72712909/184520095-c619af30-56ea-4269-8578-187c53f94b8c.png)

2022-08-14 02:40 UTC, JohnFulpWillard commented
> Tried to replicate bug report with both xenonaut and exoskeleton, it works as intended. Something else might've caused the bug to happen, this fix isn't necessary and might not actually fix what could've really happened.

If the contents carry over to the physical item (which seems odd, but im more used to working with modsuits) then I'll keep it on the Destroy in case the suit is somehow qdel'ed

2022-08-14 03:08 UTC, Lumipharon commented
> > Tried to replicate bug report with both xenonaut and exoskeleton, it works as intended. Something else might've caused the bug to happen, this fix isn't necessary and might not actually fix what could've really happened.
> 
> If the contents carry over to the physical item (which seems odd, but im more used to working with modsuits) then I'll keep it on the Destroy in case the suit is somehow qdel'ed

Almost all storage items in the codebase have storage in the same way, so the bugreport is incorrect (it's over a year old to be fair), the storage is working entirely as intended.

I wouldn't recommend even leaving this for qdel, because if you're quelling the storage container you typically want to delete the contents also (I.e. gibbing).

2022-08-14 18:46 UTC, BraveMole commented
I remember that happening though, and don't remember having seen a fix though. 

I guess that's good

2022-08-14 19:13 UTC, BraveMole requested changes
![image](https://user-images.githubusercontent.com/25491240/184551437-14b10269-b955-4ee1-944a-6963880f91d6.png)

Storage do not hard dels though

2022-08-15 12:49 UTC, breadhunt commented
> I remember that happening though, and don't remember having seen a fix though.
> 

This was an issue, but hyper fixed it with his attachie reworks (since storage modules are now technically armour attachments)
Bless for going to the effort to fix the issue anyway, though

2022-08-16 08:22 UTC, SkeletalElite commented
Back when I opened the issue report it was definitely the case, I remember testing it. Removing the storage module would 100% delete anything inside of it.

It's possible the issue was fixed but the issue was never closed though, I haven't played in ages.

2022-08-23 10:38 UTC, closed without merging