Spears Have Normal Reach While Unwielded
tgstation/TerraGov-Marine-Corps pull request #10758
Opened 2022-08-13 12:41 UTC by RikuTheKiller

## About The Pull Request

Spears can no longer reach 2 tiles while unwielded. It's as simple as that.

The spears now also have slightly higher damage while unwielded than before. This is because it's now assuming you're holding from the middle, which makes it a rather effective short-ranged stabbing weapon, however it's still not as good as a sword at, well, hurting things.

## Why It's Good For The Game

Right now you can use shields and a spear together with only lesser damage as a downside, this fixes that and gives swords an actual purpose. (Also affects the harvester spear.) Two handed weapons shouldn't be more effective while held in one hand compared to a one handed weapon. Also, have you ever tried using a spear with one hand by holding it at the end? You really don't have that much force. And your accuracy is so low that hitting a mobile target is almost impossible anyways.

## Changelog
:cl:
balance: spears now have shorter reach while unwielded, but also deal slightly higher damage while unwielded than before
/:cl:

2022-08-13 13:02 UTC, QualityVan commented on code/game/objects/items/weapons/twohanded.dm
> +	force = 30
Did you mean to reduce this from live?

2022-08-13 13:22 UTC, FosterGrime-Heymynameslouie commented
![image](https://user-images.githubusercontent.com/59080633/184496029-1fff27d1-9167-43d1-9a19-03370eda92c2.png)

RIP larping as a 18th century spearsman fighintg against spooky aliens

2022-08-13 13:37 UTC, RikuTheKiller commented on code/game/objects/items/weapons/twohanded.dm
> +	force = 30
Oh, woops, gonna fix that.

2022-08-13 13:39 UTC, RikuTheKiller commented
> ![image](https://user-images.githubusercontent.com/59080633/184496029-1fff27d1-9167-43d1-9a19-03370eda92c2.png)
> 
> RIP larping as a 18th century spearsman fighintg against spooky aliens

Honestly? They're holding it from the middle. It's not that effective anymore at that point. A little bit longer range? Yeah, sure, but honestly that's not much longer than a sword.

2022-08-13 15:42 UTC, TiviPlus requested changes
Cool argument but it already does almost half damage this is a salt pr isnt it

2022-08-13 16:05 UTC, RikuTheKiller commented
> Cool argument but it already does almost half damage this is a salt pr isnt it

I don't even play against spear users? I sometimes use spears myself.

Anyways, it's because half damage isn't even close to enough of a debuff for essentially having a ranged melee weapon. (Reminder that in the case of the harvester you can't even have it dropped out of your hand.)

2022-08-13 17:02 UTC, Naaanii commented
Looks fine. If there's wield slowdown, would be better to remove it otherwise it's good to make wielding actually have benefits vs one handing.

2022-08-13 17:28 UTC, Losenis commented
>it's because half damage isn't even close to enough of a debuff for essentially having a ranged melee weapon

You say that until some dunga fracs your groin with a misclicked spear to the rouny on top of you because it's pixelhunting without aim mode

2022-08-13 18:22 UTC, bowlofcereal commented
Using spear one handed massively lowers its damage to pointlessness if you see anyone using shield and spear its because they are new and don't understand there is a damage debuff. 

Unnecessary PR considering the above statement I have made and what others have already stated.

2022-08-14 08:23 UTC, Al-1ce commented
Xeno main here. Spear already has enough drawbacks on it's own. outside of being low damage on it's own. This just isn't needed.

2022-08-14 12:14 UTC, RikuTheKiller commented
After considering all the points made by everyone in the comments, I'll be closing this PR.

2022-08-14 12:14 UTC, closed without merging