Shield hard armor works, bullet pen applies
tgstation/TerraGov-Marine-Corps pull request #10776
Opened 2022-08-16 19:19 UTC by QualityVan

## About The Pull Request
Hard armor on shields had two issues: if it was more than the damage taken the shield didn't absorb anything at all, and if it wasn't then it still increased the damage the mob took.
Bullet pen didn't apply to shields at all. With this it'll increase the damage the shield itself takes (mob damage is unaffected) for absorption shields like riot and reduce block chance for binary shields like eswords. 

## Why It's Good For The Game
Bugfixes

## Changelog
:cl:
add: High-pen bullets deal more damage to shields
fix: Shield hard armor reduces damage instead of increasing it
/:cl:

2022-08-17 20:59 UTC, BraveMole requested changes
Fix good, but question: do we still want hard armor to be in the code anyway ?

2022-08-17 21:18 UTC, QualityVan commented
Shields actually have some bullet hard armor, just to tone down FF further (it makes it worse right now because bugs but y'know). Beyond that though I think it does have uses in terms of a way to intuitively restrict weaker guns/castes from damaging specific emplacements, like how miner reinforcement locks destruction to only large xenos.
Also it'd be a pain to remove.

2022-08-19 13:54 UTC, BraveMole approved these changes

2022-08-19 13:54 UTC, merged

2022-08-19 18:26 UTC, Serxule commented
yeah shields block bullets from FF, but only a few