Fix piercing projectile hitting the same atom multiple times
tgstation/TerraGov-Marine-Corps pull request #10804
Opened 2022-08-21 22:28 UTC by BraveMole

## About The Pull Request

Title. Based on projectile perf improvment.

## Why It's Good For The Game

## Changelog
:cl:
fix: Fix piercing projectile hitting the same atom multiple times
/:cl:

2022-08-21 23:07 UTC, BraveMole commented on code/modules/projectiles/projectile.dm
> +	var/list/atom/hit_atoms
todo: should be lazy list

2022-08-21 23:08 UTC, BraveMole commented on code/modules/projectiles/projectile.dm
> +	hit_atoms = list()
todo: should be null

2022-08-24 04:36 UTC, Wayland-Smithy commented
No more TAT penetrator (x2) 👏 👏

2022-08-26 00:01 UTC, DeltaFire15 requested changes

2022-08-26 00:01 UTC, DeltaFire15 commented on code/modules/projectiles/projectile.dm
> +	hit_atoms = list()
Also maybe just hit_atoms = null instead of creating a new list that just gets deleted right after anyways.

2022-09-02 23:22 UTC, Lumipharon commented
This works in testing, I unno if the server wasn't updated for a day or two or something.

2022-09-03 13:01 UTC, merged