Printable Tadpole Guns
tgstation/TerraGov-Marine-Corps pull request #10818
Opened 2022-08-23 03:14 UTC by novaepee

## About The Pull Request

To enable tadpole guns into existence, the TerraGov Marine Corps' Logistic Division decided that allowing POs to print out tadpole guns is a go.

## Why It's Good For The Game

Marines never see the existence of different tadpole guns, but this PR is more complex than it seems.

Tadpole and Condor will have to share fabricator points. This means that if tadpole wants to use other weapons beside the machine gun, condor will have to wait. This makes tadpole have to help with miners so that they can use req points to purchase fabricator points, and they are quite expensive.

Also, you have to buy ammo from req.

## Changelog
:cl:
add: Enable PO to print out more guns for tadpole
balance: combat tadpole is getting reinforced a lot
/:cl:

2022-08-23 03:15 UTC, novaepee commented
Not going to lie, this will make tadpole more oppressive, but need to see people's thoughts on this, see how much they want this in, and what needs to be changed if we let PO do this.

2022-08-23 03:54 UTC, FosterGrime-Heymynameslouie commented
the cabal of po mains (like 3 people and a potted plant) approves of this

also in terms of how oppresive it can be, how expensive it should be should ought to mitigate it, although only testing would give the right information on trying to find the sweet spot.
really like them being potentially seen outside of req basement hell.

2022-08-23 03:55 UTC, Lumipharon commented
The fact that this shares CAS points offsets a lot of the potential power of this, since it becomes impractical to be running effective CAS while also splashing out on nice tad upgrades.

2022-08-23 08:11 UTC, Weedmaster77 commented
One question I have is will all the mounts that are currently onboard like the 4 sentry and 2 flare launchers are they still going to be there round start for the tad and alamo to use. Because if you take away the sentries that are spawn round start you'll never see the tad used again in ,my opinion but if the 500 points for a additional sentry mount on top of those that you spawn normally with everything seems fine. Plus making the other mountable guns printable seems like a nice idea making them easier to get earlier since tad seems to be used more then CAS and also seems to be used more effectively more often.

2022-08-23 16:08 UTC, Losenis commented
Finally, tadpole and condor POs killing each other while I nab the tadpole myself

2022-08-24 00:05 UTC, novaepee commented
> are they still going to be there round start for the tad and alamo to use

Yes.

2022-08-24 08:38 UTC, Al-1ce commented
The fabricator point production rate should be increased to balance things beteeen condor/cas. Otherwise this might actually become a nerf.

2022-08-27 08:15 UTC, Starfirejordan commented
I suggest leaving tadpole weapons systems as buyable because point between the two will become restrictive too much
unless you buff point genes or straight up make "tadpole printer" to balance it so the PO dont fight over point and most likely FF each other because "oh no i cant buy my missiles because the stupid other PO bought a minigun emplacement for there stupid Tad they have done nothing with!!"

2022-08-27 08:24 UTC, Lumipharon commented
IC issues are completely fine, it's literally just adding more options to the vendor. And points can still be bought with req points.

2022-08-29 15:48 UTC, MereWalker commented
I suggest making a tadpole fabrication bench. So condor and tadpole don't inadvertently kill each other over what gear the points are used on. Also can we get tadpole version 4 make it bigger and give it more guns. With love.

2022-08-29 16:11 UTC, Losenis commented
Bigger tadpole would be a devastating nerf given the spaces it can JUST fit into right now and how fewer walls it'd need to block it from landing anywhere

2022-08-29 16:58 UTC, MereWalker commented
Revert it to the chad cave pole. I loved that design. It was so good too. Maybe somewhat unfair but letting it go into caves a little bit would be nice.

2022-08-29 19:10 UTC, Losenis commented
Wasn't it forbidden from cavepoling over the front being indestructible and blocking caves with it? Now that the front is very much destructible, cavepole might be interesting

2022-08-29 19:24 UTC, MereWalker commented
> 

You bout to make me act up. Please don't make me excited about cavepole unless you for real for real.

2022-09-01 17:36 UTC, TiviPlus requested changes
Why add 2 aquisition methods one will always be superior
Why force tad and cas pos to fight over the points

2022-09-01 19:29 UTC, novaepee commented
> Why add 2 aquisition methods one will always be superior 

As of right now, no one buys tadpole guns from req. It's barely in use.

> Why force tad and cas pos to fight over the points

They can get more points by having tadpole acquire miners.

2022-09-02 16:43 UTC, TiviPlus commented
That doesnt answer either of my questions

2022-09-02 16:43 UTC, TiviPlus commented
Misclick

2022-09-02 16:48 UTC, Naaanii commented
Dropship fabricator pass buff or changes would make this more interesting. Should probably delete it from req though if it's going to be in the fabricator.

2022-09-05 00:49 UTC, Al-1ce commented
The tadpole covering miners isn't something that'll happen every round. If anything, it's pretty infrequent. I think relying on that would hardly be a band-aid to this problem. 

Increasing the overall point generation would cover both the Condor and the Tadpole. IC issues that spawn from this are a direct consequence from not doing exactly that. By allowing the tadpole to spend these points, it's adding an additional drain that wasn't ever counted for in the past.

2022-09-05 18:12 UTC, novaepee commented
I will let tye figure this out.

2022-09-05 18:12 UTC, closed without merging