CLF ERT refresh
tgstation/TerraGov-Marine-Corps pull request #10826
Opened 2022-08-24 12:29 UTC by Lumipharon

## About The Pull Request
Updates the CLF ERT with new loadouts.

This isn't particularly trying to make CLF more powerful (although it probably does do that), but mainly give them more variety.
The CLF are impoverished angry colonists, so presumably have to scrounge up whatever weaponry they can get, or buy stuff off the UPP/SOM where they can.

To this end, added a whole bunch of different loadouts to spice them up a bit. Oh also they have lights on their suits now. woo.

Additionally, tweaked the balance of the Skorpion, which was utter dog shit. It's still bad, but hopefully isn't entirely useless now.

Also a few minor sprite fixes etc.

## Why It's Good For The Game
Variety is good.

## Changelog
:cl:
add: The CLF now carry a much larger variety of equipment
balance: Improved the performance of the Skorpion SMG
/:cl:

2022-08-25 06:11 UTC, MereWalker commented
The scorpion is crazy good vs marines the last time I used it. Which was a long time ago. Could these be used in combat as well? Like a factions system.

2022-08-25 08:31 UTC, Lumipharon commented
> The scorpion is crazy good vs marines the last time I used it. Which was a long time ago. Could these be used in combat as well? Like a factions system.

Dunno if it was changed in the past, but right now it's hot garbage.

2022-08-29 20:13 UTC, BraveMole requested changes

2022-08-29 20:13 UTC, BraveMole commented on code/modules/clothing/under/marine_uniform.dm
> +	starting_attachments = list(/obj/item/armor_module/storage/uniform/black_vest)
Spacing

2022-08-29 21:58 UTC, Lumipharon commented on code/modules/clothing/under/marine_uniform.dm
> +	starting_attachments = list(/obj/item/armor_module/storage/uniform/black_vest)
done

2022-09-01 18:19 UTC, merged