Allows the AI to grab coordinates with ctrl click
tgstation/TerraGov-Marine-Corps pull request #10833
Opened 2022-08-25 19:17 UTC by lbnesquik

## About The Pull Request
Clicking Ctrl click on a turf you can see will now print the coordinates in your chat. 
I'd have liked to have it copy into your clipboard, but I'm not sure byond can do that. 

## Why It's Good For The Game
This would allow the AI to more easily provide drop pod coordinates, and targeting information for artillery pieces. 
I think this is a buff for the role, but nothing you couldn't do with a (working) webmap before. 

## Changelog
:cl:
add: Gave the AI the ability to Ctrl-click turfs to get their coordinates. 
/:cl:

2022-08-25 19:31 UTC, Naaanii commented
Based PR.

2022-08-27 21:06 UTC, BraveMole requested changes

2022-08-27 21:06 UTC, BraveMole commented on code/_onclick/ai.dm
> +/* Turf */
What ?

2022-08-28 21:03 UTC, BraveMole requested changes

2022-08-28 21:03 UTC, BraveMole commented on code/_onclick/ai.dm
> +	var/turf/T = get_turf(src)
I dont event know what get turf is doing on a turf.... maybe it gravs the area

Anyway you just want src, you do not need loc or that line

2022-08-29 17:21 UTC, BraveMole requested changes

2022-08-29 20:12 UTC, merged