Add an item which allows the AI to remote target for artillery pieces.
tgstation/TerraGov-Marine-Corps pull request #10834
Opened 2022-08-25 19:22 UTC by lbnesquik

## About The Pull Request
The device is a little module which you can attach to the mortar or howitzer. Doing so will link it with the current active AI, if there is one. 

From there, the AI can use shift click on a turf to transmit coordinates to the linked artillery piece. It can also click on the piece itself to unlink itself from it, at which point the device falls to the ground. 

It can be found in req and engineers lockers at a fairly high price. 

## Why It's Good For The Game
I always felt like the AI could use more ways to do some sort of overwatch+, which currently, it currently can't really do. 
This PR would give it a boon for helping to coordinate marines, and bring it a little more towards a command role.

I think this is a buff, but it isn't quite as strong as it may sound. For one thing, the AI vision remains limited to the view afforded to it by cameras, and it lacks dark vision. This is a **lot** less range than the rangefinders allow, so no surprise sniping. It also costs a fair bit of investment, something which could be lowered if the device doesn't actually perform.

## Changelog
:cl:
add: Added a device which allows the AI to remotely target artillery pieces. 
/:cl:

2022-08-25 19:35 UTC, Naaanii commented
Seems unnecessary as Mortar and Howies already come with range finders and generally a spotter fires shells themselves.

AI being able to get coordinates past the range of range finders is a bit powercreepy as howies don't have accuracy maluses with range. AI having stuff to do isn't bad but this seems a bit unnecessary.

Then again, AIs can also access consoles to quick fire OBs instead of FCs or SLs having to wait for the lase.

2022-08-26 11:12 UTC, Weedmaster77 commented
Like the idea since I have seen the AI give cords manual to Howy gunner so this make it easier for the AI and gunner and also makes it a item. Would just hope its not more then like 25-30 points in REQ since it seems like such a uncommon sight to have a AI working with Howy crew.

2022-08-27 08:19 UTC, Starfirejordan commented
good luck both your pr are idea I had that tivi already denied soooo good luck with that

2022-08-28 08:20 UTC, Al-1ce commented
> the lack of accuracy maluses for range makes this a bit powercreepy.

There are no accuracy maluses for any piece of artillery in the game, outside of operator error. Why would it matter now, all of the sudden?

2022-08-28 19:10 UTC, Naaanii commented
> > the lack of accuracy maluses for range makes this a bit powercreepy.
> 
> There are no accuracy maluses for any piece of artillery in the game, outside of operator error. Why would it matter now, all of the sudden?

There used to be and still is with Mortar iirc, Howie doesn't have any. This just allows deeper range of artillery without having to actually move the howitzer closer to the frontline.

Then again, manual coordinates could be given but also, less downtime, hence powercreepy.

2022-09-04 09:33 UTC, BraveMole requested changes
I don't really see a lot of situation where this will be usefull. 

Ai has limited vision due to camera, you are way better off with a marine spotter.

2022-09-08 17:04 UTC, BraveMole requested changes

2022-09-08 17:04 UTC, BraveMole commented on code/game/objects/machinery/mortar.dm
> +		for(var/mob/living/silicon/ai/AI AS in GLOB.ai_list)
Should not be a for, because that code doesn't work if there are multiple ais.

Also, does this work if there are no ais ?

2022-09-08 17:04 UTC, BraveMole commented on code/game/objects/machinery/mortar.dm
> +	ai_targeter.loc = src.loc
A direct loc set ? Also should use get turf

2022-09-08 17:04 UTC, BraveMole commented on code/modules/mob/living/silicon/ai/ai.dm
> +	if(linked_artillery == mortar)
Only usefull if linked artillery is not null, so put that in the other if scope

2022-09-13 06:22 UTC, BraveMole requested changes

2022-09-13 06:22 UTC, BraveMole commented on code/game/objects/machinery/mortar.dm
> +	var/obj/item/ai_target_beacon/ai_targeter
Autodoc

2022-09-13 06:22 UTC, BraveMole commented on code/game/objects/machinery/mortar.dm
> +	ai_targeter.loc = get_turf(src)
You need to use move or forcemove

2022-09-13 18:42 UTC, BraveMole commented on code/modules/reqs/supplypacks.dm
> +	cost = 50
that's hella expensive.

2022-09-13 20:16 UTC, BraveMole requested changes

2022-09-13 20:16 UTC, BraveMole commented on code/modules/mob/living/silicon/ai/ai.dm
> +/mob/living/silicon/ai/proc/associate_artillery(mortar)
Autodoc

2022-09-13 20:16 UTC, BraveMole commented on code/game/objects/machinery/mortar.dm
> +/obj/machinery/deployable/mortar/proc/unset_targeter()
Doc

2022-09-13 20:16 UTC, BraveMole commented on code/game/objects/machinery/mortar.dm
> +		switch(tgui_alert(usr, "This artillery piece is linked to you. Do you want to unlink yourself from it?", "Artillery Targeting", list("Yes", "No")))
You can do the same thing with a single if. Including the user.linked artillery == src

2022-09-13 20:16 UTC, BraveMole commented on code/game/objects/machinery/mortar.dm
> +		return
No need for a return at the end of the proc + add an empty line anyway

2022-09-13 20:16 UTC, BraveMole commented on code/game/objects/machinery/mortar.dm
> +		var/mob/living/silicon/ai/AI
Why are you defining then declaring in two different lines

2022-09-14 19:03 UTC, BraveMole requested changes

2022-09-14 19:03 UTC, BraveMole commented on code/game/objects/machinery/mortar.dm
> +		if(!GLOB.ai_list)
you need to check the len, that's cleaner.

2022-09-17 07:32 UTC, merged

2022-09-18 22:29 UTC, Derrick2Electricboogaloo commented
FINALLY!

2022-09-18 22:32 UTC, Derrick2Electricboogaloo commented
> I don't really see a lot of situation where this will be usefull.
> 
> Ai has limited vision due to camera, you are way better off with a marine spotter.

Not to mention it makes buying and building camera's a lot more useful other than vision. And hopefully encourages people to utilize that type of equipment.