Burns contribute to delimb
tgstation/TerraGov-Marine-Corps pull request #10849
Opened 2022-08-28 11:06 UTC by QualityVan

## About The Pull Request
Same total damage needed as before, just burns are legal.

## Why It's Good For The Game
Previously, having any burn damage at all on a limb made it impossible for it to be amputated due to how maximum limb damage was limited. Fixes that.

## Changelog
:cl:
fix: Burn damage counts towards maximum limb damage for delimbs instead of making them impossible.
/:cl:

2022-08-28 13:03 UTC, Lumipharon commented
As mentioned in discord, this completely breaks HvH balance.

2022-08-28 14:48 UTC, Losenis commented
You can get burn damage even if you're dead by being on a fire tile, this'll absolutely skyrocket the number of delimbs and make magmoor essentially impossible to play

2022-08-28 16:03 UTC, Serxule commented
>  make magmoor essentially impossible to play

who takes magmoor in account for balance? its literally never chosen

2022-08-28 17:01 UTC, blackdav123 commented
> > make magmoor essentially impossible to play
> 
> who takes magmoor in account for balance? its literally never chosen

it is relevant because this would mean falling into lava and dying would result in all your limbs falling off in the goofiest way possible

better solution would be to allow burn damage to reach up to the damage cap and make any subsequent brute damage cause the delimb

2022-08-28 17:32 UTC, novaepee commented
> > make magmoor essentially impossible to play
> 
> who takes magmoor in account for balance? its literally never chosen

Magmoor is gone.

2022-08-28 21:05 UTC, Losenis commented
It only takes a map getting another "get burn damage if you step on it" hazard before the argument is back in play. Flamers already do burn damage to corpses by the fire tile anyway.

2022-08-29 20:56 UTC, BraveMole requested changes
Feels like the solution has vastly more impact than just fixing the bug.

2022-08-29 23:17 UTC, Serxule commented
probably just make it so delimbing requires brute damage when damage is maxed and that fixes the problem (unless its already like that)

2022-08-29 23:39 UTC, Weedmaster77 commented
Don't like this idea at all it's just going make more marines get sent shipside for new limbs when it happens between 3 and 10 times a round on a pretty far non-steamroller round. Delimbing is powerful enough with brute damage burn doesn't need to make it even more punishing then it already is. An when ravs and warriors can just pop your arms, hands and legs off pretty easy with enough targeting which skilled xeno plays do pretty often. Also with light armor being the most commonly used armor delimbing is frequent enough . An with my many hours of un-suiting dead marines to rev I can confidently say that.

2022-08-30 13:13 UTC, Al-1ce commented
Generally balancing your PR off of somebody falling into lava is a bad idea.

2022-08-30 18:41 UTC, Losenis commented
It's not just lava, it's that tiles that do burn damage continue to do so even when the person is dead. See also: space, blue fire, WP smoke (probably), both combined in incen OB, some rare bug floating around that had corpses constnatly get tiny bits of damage that I never could pinpoint enough to bug report, etc. Lava just happens to be the thing most people already are familiar with, which is why it's the center of the argument. Magmoor wasn't the only one with map hazards either, there was that other map with the green toxin rivers that did the same thing without setting you on fire, as well as barrenquilla when it was in rotation. With brute damage it also happens but there aren't that many things out there to actually make it as pronounced, though one thing you can do in HvH is take a corpse's helmet off, help intent click it with knife, and you'd keep doing brute damage despite dead till you decap it.

The change clashes with too many things that may be bugs, oversights, intended mechanics, and so on for its own good.

2022-08-31 14:17 UTC, QualityVan commented
Took the suggestion of requiring a brute hit in addition to reaching damage cap to cause a delimb. Should prevent the concerns raised about hvh and lava/fire.

2022-08-31 14:41 UTC, Losenis commented
inb4 delimbed by a cigarette
![image](https://user-images.githubusercontent.com/72712909/187706509-b7c9d416-321d-4834-97ff-e22f1eb2136e.png)

2022-09-04 09:25 UTC, BraveMole requested changes
Like we talked in discord, I think I'd prefer having the delimb threshold be a percentage of max_damage. Let's say 80-90 %

2022-09-05 14:36 UTC, RikuTheKiller commented
QV this overall makes it easier to delimb people.

I raised this point when the idea was originally brought up as well.

2022-09-05 14:39 UTC, RikuTheKiller commented
Right now this makes arms easier to delimb. I'd recommend making it a flat 25 instead of a ratio so you can always just use that as a reference. (Take for example the arms, 150 isn't a 20% increase to 125, get your math right.)

2022-09-05 14:57 UTC, Losenis commented
Is this actually necessary at all? Even a gamer that burns himself to avoid delimb just trades that to get killed faster assuming he actually burns the correct limb. Delimb is already extremely punishing because it means you get a robot limb that can't get healed by chems nor bandages/ointment and needs you to carry two more items they may not really have space for without a loadout change midround. At that point I personally just DNR and wait for the next round because even if it's possible to play like that it's not terribly fun.

2022-09-06 08:39 UTC, RikuTheKiller commented
> Is actually necessary at all?

Yes, since you don't have to do it intentionally to benefit from it, just take some acid or flame damage and you're fully immune to delimbs, no intention to abuse this required.

2022-09-06 14:27 UTC, Losenis commented
"benefit from it"

Bro you're dead

2022-09-06 22:52 UTC, Texicos commented
Death is preferable to a fracture or delimb

2022-09-06 23:28 UTC, Losenis commented
Not playing is preferable tbh

2022-09-07 14:32 UTC, QualityVan commented on code/modules/organs/limbs.dm
> +		droplimb() //If the limb's at its max damage and takes any brute, it severs
```suggestion
		droplimb()
```

2022-09-10 07:06 UTC, merged