Expand Pillar of Spring's AI core slightly
tgstation/TerraGov-Marine-Corps pull request #10911
Opened 2022-09-09 19:22 UTC by lbnesquik

## About The Pull Request
![image](https://user-images.githubusercontent.com/24830358/189427813-f45c883f-1998-413b-a55c-54589fd0a979.png)

## Why It's Good For The Game
The AI core on POS is very small, and being against the wall to the right weakens in a lot. 
This makes the AI not look as shoved into a storage closet, and it makes the core decently stronger. 

## Changelog
:cl:
add: Expanded the AI core on Pillar of Spring
/:cl:

2022-09-09 20:23 UTC, RipGrayson requested changes
While I'm not against giving the AI more space, I don't like the one tile corridor here.
![miles](https://user-images.githubusercontent.com/49290523/189436471-cb2a7f30-9005-4ef6-9505-5eeb142a072c.png)

As a general rule we don't do one tile corridors except in maintenance areas, they tend towards very binary positions where one side effortlessly controls the area by virtue of limited space to move and dodge.

2022-09-09 20:50 UTC, RipGrayson commented
> Any idea on how to change this? Besides encroaching on the armory, or moving it somewhere else?

There's very little excess space in PoS CIC, I don't see how you could enlarge the AI area without cramping something else. My gut instinct is that the AI should have its own little area near the CIC, probably made out of repurposed flavor rooms that nobody uses anyway.

2022-09-09 22:50 UTC, MereWalker commented
Place it in the staff quarters. Wait.. that got taken out. Uhh maybe put it in atmos?

2022-09-09 22:52 UTC, Losenis commented
This is actually a good change because in hijack you could just acid the wall and kill the AI very fast, since there was no glass on the wall side

2022-09-09 23:03 UTC, closed without merging

2022-09-09 23:16 UTC, QualityVan commented
What if you included the left hall in that image as part of the core and cut the center wall/door?

2022-09-10 02:05 UTC, MereWalker commented
You could put it in engineering.