Add name and area to planted supply beacon
tgstation/TerraGov-Marine-Corps pull request #10923
Opened 2022-09-11 20:00 UTC by lbnesquik

## About The Pull Request
![image](https://user-images.githubusercontent.com/24830358/189546674-31db20e2-fd18-43de-a571-30b1c84230c5.png)

## Why It's Good For The Game
It makes it clearer for people to say which beacon they should send things to.

## Changelog
:cl:
qol: Added name & area to supply beacons
/:cl:

2022-09-11 22:29 UTC, Losenis commented
Speedmerge

2022-09-12 02:13 UTC, Weedmaster77 commented
good idea

2022-09-14 08:44 UTC, TiviPlus requested changes

2022-09-14 08:44 UTC, TiviPlus commented on code/game/objects/machinery/squad_supply/supply_beacon.dm
> +	name = "transmitting orbital beacon - [get_area(src)] - [H]"
It should probably reset its name on being picked up

2022-09-14 19:38 UTC, TiviPlus approved these changes

2022-09-14 19:38 UTC, merged