Adds Optical Imager Ballistic Goggles
tgstation/TerraGov-Marine-Corps pull request #10932
Opened 2022-09-12 20:07 UTC by AzonStarfall

## About The Pull Request

Adds a set of craftable Optical Imager ballistic goggles, in a similar manner to the MedHud Ballistic Goggles.

To craft them, just click a set of ballistic goggles with the optical imagers.

The new goggles have no armor, inherited from the Optical Imagers.

## Why It's Good For The Game

This continues the mechanical theme of combining HUDs with Ballistic Goggles. Serves no substantial gameplay benefit, aside from aesthetics.

## Changelog
:cl:
add: Adds craftable Optical Imager Ballistic Goggles
/:cl:

2022-09-13 01:22 UTC, MereWalker commented
FINNALY IVE BEEN WAITING! IF YOU CAN PLEASE ADD MESON GOGGLES!

2022-09-13 05:43 UTC, AzonStarfall commented
> FINNALY IVE BEEN WAITING! IF YOU CAN PLEASE ADD MESON GOGGLES!

Just for you <3

2022-09-14 08:45 UTC, TiviPlus requested changes

2022-09-14 08:45 UTC, TiviPlus commented on code/modules/clothing/glasses/glasses.dm
> +		if(prescription)
elseif please

2022-09-14 16:42 UTC, TiviPlus approved these changes

2022-09-15 14:19 UTC, merged