Mech p2, greyscale mechs
tgstation/TerraGov-Marine-Corps pull request #10955
Opened 2022-09-14 11:50 UTC by TiviPlus

I left in the todos brave because weapons arent done yet

2022-09-14 11:52 UTC, Kuro020 approved these changes

2022-09-16 18:18 UTC, BraveMole requested changes

2022-09-16 18:18 UTC, BraveMole commented on code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
> +	if(length(GLOB.clients) > 1)
No that's awfull, can't you hide that being a indef testing ?

2022-09-16 18:54 UTC, TiviPlus commented on code/modules/vehicles/mecha/combat/greyscale/greyscale_constructor.dm
> +/obj/machinery/computer/mech_builder/proc/update_ui_view()
It was laggy cus it had 3 ByondUIs, I removed 2 after you tested and its better so if you really wanna know go you should prolly test locally

2022-09-16 18:58 UTC, TiviPlus commented on code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
> +		. += limb.get_overlays()
Fixed it but forgot to remove comment oops

2022-09-19 19:30 UTC, BraveMole approved these changes

2022-09-19 19:30 UTC, merged