Projectile hit proc fixes
tgstation/TerraGov-Marine-Corps pull request #11003
Opened 2022-09-19 12:51 UTC by Lumipharon

## About The Pull Request
Changed the explosive ammo flag to trigger do_at_max_range() (and added a turf arg) instead of on_hit_turf().
This specifically fixes TAT APHE ammo exploding correctly on the clicked tile, while avoiding funny multiple explosion bugs again.

Then updated both  do_at_max_range() and on_hit_turf() for all relevant projectiles to check for turf density. If the turf is dense it instead triggers on the projectile's turf (i.e. the turf before the wall or whatever).
Some projectiles specifically want to hit dense turfs, so of course these are excluded.

Currently some projectiles check this, but did the same thing in multiple different ways, while others didn't check at all, meaning you could trigger certain effects like explosions and fireballs through walls, and other funny things.

## Why It's Good For The Game
Bug fixes good
Consistant code good

## Changelog
:cl:
refactor: refactored some projectile on hit code
/:cl:

2022-09-20 19:07 UTC, BraveMole requested changes

2022-09-20 19:07 UTC, BraveMole commented on code/modules/projectiles/ammo_datums.dm
> +	var/target = T.density ? P.loc : T
target is a useless var

2022-09-21 01:18 UTC, Lumipharon commented on code/modules/projectiles/ammo_datums.dm
> +	var/target = T.density ? P.loc : T
Cut the var out/

2022-09-21 10:21 UTC, QualityVan commented on code/modules/projectiles/ammo_datums.dm
> +		burn_mod = 3
I don't like this duplicating code from pp's turf hit. Better off using a drop_flame

2022-09-23 15:26 UTC, merged