New HvH gamemode Sensor Capture [MDB ignore] pt2
tgstation/TerraGov-Marine-Corps pull request #11001
Opened 2022-09-19 08:26 UTC by tyeagg

## About The Pull Request
this is basically combat patrol but crash but on a faster pace kinda.
Marines must capture and activate 5 sensor towers and hold it for 150 seconds, activating sensor towers will increase game end timer and if all towers are fully activated marines win.
SOM must stop marines from reactivating all towers until the game end timer is over

## Why It's Good For The Game
could be fun

## Changelog
:cl:
add: sensor capture gamemode
imageadd: sensor tower minimap blips
/:cl:

2022-09-19 21:12 UTC, MereWalker commented
Be sure there are a few places only som can get to and out of so marines can't spawn camp them. Just a thought. Look forward to having an additional hvh mode! Best of luck and can't wait for more updates!

2022-09-21 14:21 UTC, Autisem commented
Giving objectives would imo mape CP much better already.

2022-09-21 21:43 UTC, Lumipharon commented
Unless I'm misunderstanding, all 5 towers have to be activated, and you have to stop the SOM from deactivating them?

That sounds quite difficult to manage as splitting your forces is usually death, while SOM can send one funni man to try recap towers.

2022-09-21 23:25 UTC, tyeagg commented
> Unless I'm misunderstanding, all 5 towers have to be activated, and you have to stop the SOM from deactivating them?
> 
> That sounds quite difficult to manage as splitting your forces is usually death, while SOM can send one funni man to try recap towers.

2022-09-21 23:57 UTC, Lumipharon commented
> no you just have to hold a tower for 150 seconds and it adds to a point pool and than som cant deactivate it

Ah cool, that makes more sense. It does put the shoe on the other foot a bit though, in that SOM will need to be able to respond to marines capping multiple towers, although that's probably less of an issue.

2022-09-22 07:40 UTC, TiviPlus requested changes

2022-09-22 07:40 UTC, TiviPlus commented on code/datums/gamemodes/game_mode.dm
> +	var/sensors_activated = 0
This should be a sensor specific var

2022-09-22 07:40 UTC, TiviPlus commented on code/game/objects/effects/landmarks/landmarks.dm
> +	. = ..()
```suggestion
	..()
```

2022-09-22 07:40 UTC, TiviPlus commented on code/game/objects/structures/sensor_tower.dm
> +	var/activated = FALSE // if all segments are finished
This entire object and it's procs are missing autodoc

2022-09-22 07:40 UTC, TiviPlus commented on code/game/objects/structures/sensor_tower.dm
> +	balloon_alert_to_viewers("[user] activates [src]!")
dont use [src] in baloon alerts and even generally avoid inserting names
these should be as short as possible, and remember that players can see where it is on the map (so no specified what is being affected needed)

2022-09-22 07:40 UTC, TiviPlus commented on code/game/objects/structures/sensor_tower.dm
> +	var/current_time = timeleft(D.game_timer)
Not going to force you but generally single name vars are not cool

2022-09-27 12:30 UTC, TiviPlus requested changes
Rest LGTM

2022-09-27 12:30 UTC, TiviPlus commented on code/game/objects/structures/sensor_tower.dm
> +/obj/structure/sensor_tower_patrol/proc/update_control_minimap_icon()
autodoc

2022-09-27 12:30 UTC, TiviPlus commented on code/game/objects/effects/landmarks/landmarks.dm
> +	. = ..()
Request still pending

2022-10-09 14:20 UTC, merged