Terra Experimental Powerpack
tgstation/TerraGov-Marine-Corps pull request #11009
Opened 2022-09-20 11:09 UTC by tyeagg

## About The Pull Request
powerpack for energy weapons self recharges and around 2 times ammo cap of normal energy magazine also slightly nerfs mg ammo cap so it doesn't recharges faster than it fires
![image](https://user-images.githubusercontent.com/98577688/191242676-6d580e18-81f7-4762-bbbb-83ee678ad294.png)

## Why It's Good For The Game
new niche for energy weapons but needing to sacrifice backpack space

## Changelog
:cl:
add: te-pp10 powerpack
balance: energy mg slight ammo count nerf
/:cl:

2022-09-20 11:53 UTC, FosterGrime-Heymynameslouie commented
something I didnt even know we needed
very cool pr that finally does something about laser weapons

also I wonder if lumi would make a loadout out of this for hvh

2022-09-20 11:55 UTC, Kuro020 requested changes
Sprite needs work, ping me on artwork later so I can destroy your hopes and dreams

2022-09-20 12:00 UTC, Lumipharon commented
The charge rate is pretty high. Volkite weapons use notably more charge than lasers.
And related to that, why are you nerfing the laser mg?

2022-09-20 15:36 UTC, Losenis commented
![image](https://user-images.githubusercontent.com/72712909/191301821-8add4c44-6690-40e6-96e8-abab014d1fe8.png)

2022-09-20 20:59 UTC, revelation-8468 commented
can you link laser guns directly into the power pack?

2022-09-20 22:27 UTC, ilikesaying commented
> can you link laser guns directly into the power pack?

Looking at the accepted magazines for the lasguns change, looks like you can.

2022-09-21 10:42 UTC, BraveMole requested changes

2022-09-21 14:23 UTC, Autisem commented
cool concept but hand chargers are honestly more effective as of right now. especialy when you lose backpack slot for it. maby making energy weapons stronger somehow? otherwise its quiet steep price

2022-09-21 20:14 UTC, Losenis commented
PLEASE TELL ME THIS WILL WORK WITH THE POWERFIST

2022-09-22 06:09 UTC, Al-1ce commented
It looks like there'll be about five of these for free roundstart. What's stopping someone from taking one off and putting on another for "infinite" ammo?

2022-09-22 13:22 UTC, UntoldTactics commented
yes pls
time to be support unga and recharge my comrades cells

2022-09-23 15:29 UTC, BraveMole requested changes
Do not change laser balance just to add your power pack

2022-09-23 20:41 UTC, Lumipharon commented
That's still a high charge rate, especially consider the capacity buff.
Volkite uses 30 or 36 charge per shot with a charge rate of 32.
Lasers charge is a bit wack, but this is still effectively infinite bullets. 625 shots with 2.5 regenning every 2 seconds? You would to be spamming ridiculously hard to ever really use that up.

2022-09-24 00:59 UTC, tyeagg commented
> That's still a high charge rate, especially consider the capacity buff. Volkite uses 30 or 36 charge per shot with a charge rate of 32. Lasers charge is a bit wack, but this is still effectively infinite bullets. 625 shots with 2.5 regenning every 2 seconds? You would have to be spamming ridiculously hard to ever really use that up.

tested constant fire with laser mg and nope it doesnt recharge faster than laser mg

2022-09-24 03:15 UTC, Lumipharon commented
> > That's still a high charge rate, especially consider the capacity buff. Volkite uses 30 or 36 charge per shot with a charge rate of 32. Lasers charge is a bit wack, but this is still effectively infinite bullets. 625 shots with 2.5 regenning every 2 seconds? You would have to be spamming ridiculously hard to ever really use that up.
> 
> tested constant fire with laser mg and nope it doesn't recharge faster than laser mg

It doesn't need to is my point. As long as you never run out, how much charge you have left doesn't matter. It just acts as a huge buffer, you're realistically never going to run out unless you're literally running around without ever letting go of mouse 1.

2022-09-26 22:53 UTC, Pariah919 reviewed
Seems wack, talk to me on discord.

2022-09-27 12:47 UTC, TiviPlus requested changes

2022-09-27 12:47 UTC, TiviPlus commented on code/modules/projectiles/magazines/energy.dm
> +	charge_amount = 10
I dont get why this has self recharge but rest lgtm

2022-10-02 08:14 UTC, helper-2 commented
Wait, you want to add a backpack that stores energy worth of 4 lasgun batteris, when even the usual satchel stores 5 of them, and that powerbank don't selfrecharge itself.
Do I understand correctly?

2022-10-14 21:38 UTC, helper-2 commented
I don't want this pr to die.

2022-10-16 03:47 UTC, closed without merging

2022-10-16 04:25 UTC, FosterGrime-Heymynameslouie commented
it was never meant to be