Xenomorphs can pull objects again
tgstation/TerraGov-Marine-Corps pull request #11011
Opened 2022-09-20 20:43 UTC by lKiseki

## About The Pull Request
Per title. One of Tivi's wishlist items.
This PR removes a check that prevented xenomorphs from pulling objects, thereby allowing them to do it.

## Why It's Good For The Game
Further encourages xenomorphs to interact with the environment, which leads to a less restrictive gameplay experience.
Bear in mind this implies many other concerns will be enabled, but it is preferable to tackle them rather than take the easy way out.

## Changelog
:cl: Lewdcifer
add: Xenomorphs can now pull objects (again).
/:cl:

2022-09-20 20:47 UTC, MLGTASTICa commented
finnally... i can setup traps.. with welding fuel tanks.

2022-09-20 20:53 UTC, novaepee commented
Carrier mains setting traps, rejoice!

2022-09-20 20:53 UTC, Naaanii commented
Time for rouny to pounce and pull Sadar's away from marines.

2022-09-20 22:01 UTC, shelteredfreak commented
Make xenos be slowed down when dragging things based on their size. 

Rouny being extremely slow when dragging stuff like a dog dragging a stick that's too big versus a Warrior dragging a marine (just an example, I don't recommend actually letting xenos drag marines) by their damn neck with no slowdown.

2022-09-20 22:13 UTC, Strayed-Raven commented
What shelteredfreak said. also this invalidates rouny steal. you might have to restrict weapons to a degree from regular objects. not saying they can't drag. but weapons might need to make them slower than other items

2022-09-20 22:17 UTC, shelteredfreak commented
> What shelteredfreak said. also this invalidates rouny steal. you might have to restrict weapons to a degree from regular objects. not saying they can't drag. but weapons might need to make them slower than other items

Well the difference is that Rounys snatch steals the gun no matter what, and slows them down regardless. The only way a xeno can grab a gun if they can drag is if the marine drops their gun. High chances they wont because 90% of marines have a mag/belt harness.

2022-09-20 22:29 UTC, Losenis commented
Sounds like most of the time it'll be used purely to steal shit off people being revived. You can argue that a corpsman shouldn't be reviving that close to xenos, but he's not the one being punished, you are, and you have no say in the matter due to being dead.

2022-09-20 22:38 UTC, shelteredfreak commented
> Sounds like most of the time it'll be used purely to steal shit off people being revived. You can argue that a corpsman shouldn't be reviving that close to xenos, but he's not the one being punished, you are, and you have no say in the matter due to being dead.

Gives me an idea of making a module or something default in jaeger armor that allows medics to defib you and such without taking your armor off.

2022-09-20 22:50 UTC, Lumipharon commented
Rouny steal req gun, it drops to the floor after 2 sec
Rouny then drag gun to brazil
COPE

2022-09-20 23:01 UTC, RipGrayson commented
Speaking of, is there anything to keep xenos from dragging mission important objects like discs or the nuke to brazil? In certain modes xenos could theoretically make the game unwinnable by stashing important objects inside their silo fog.

2022-09-20 23:47 UTC, ivanmixo commented
> Speaking of, is there anything to keep xenos from dragging mission important objects like discs or the nuke to brazil? In certain modes xenos could theoretically make the game unwinnable by stashing important objects inside their silo fog.

Nukes are anchored structures til all the 3 disks are in. And why is the disk on the floor?

2022-09-21 00:15 UTC, lKiseki commented
> Make xenos be slowed down when dragging things based on their size.
> 
> Rouny being extremely slow when dragging stuff like a dog dragging a stick that's too big versus a Warrior dragging a marine (just an example, I don't recommend actually letting xenos drag marines, edit: dead marines, I feel like xenos should also be able to drag alive marines faster based on their size) by their damn neck with no slowdown.

This is already a thing. To tell you the truth, once upon a time xenos were actually able to pull objects. Many objects had drag delays, and still do, meaning xenos will have varying movement speeds based on what they're dragging.

2022-09-21 00:15 UTC, lKiseki commented
> What shelteredfreak said. also this invalidates rouny steal. you might have to restrict weapons to a degree from regular objects. not saying they can't drag. but weapons might need to make them slower than other items

This has already been considered, but initially speaking, it will not be done. Should maintainers change their mind, it can be done.

2022-09-21 00:16 UTC, lKiseki commented
> Speaking of, is there anything to keep xenos from dragging mission important objects like discs or the nuke to brazil? In certain modes xenos could theoretically make the game unwinnable by stashing important objects inside their silo fog.



> Speaking of, is there anything to keep xenos from dragging mission important objects like discs or the nuke to brazil? In certain modes xenos could theoretically make the game unwinnable by stashing important objects inside their silo fog.

Like Ivanmixo said, the probability of such items being stolen sounds pretty low. However, a blacklist can certainly be made if pulling certain objects proves to be an issue.

2022-09-21 00:19 UTC, RipGrayson commented
> > Speaking of, is there anything to keep xenos from dragging mission important objects like discs or the nuke to brazil? In certain modes xenos could theoretically make the game unwinnable by stashing important objects inside their silo fog.
> 
> Nukes are anchored structures til all the 3 disks are in.

Provided the marines haven't secured the nuke immediately after they get the disks, it's trivial for the xenos to take the nuke for a long trip. Especially since the usual design philosophy is to put the nuke in xeno territory.

>And why is the disk on the floor? A blacklist will probably be needed, though.

Perhaps a marine had it out for whatever reason, maybe their storage is full and they're trying to free space first, maybe they're transferring the disc to somebody else like their SL or FC. Imagine a runner pounces them, the disc drops, and the rouny runs away dragging the disc at light speed. 
The xenos could probably play keep a way for quite a while, long enough to either drag the round out or let attrition kill the marines before they can activate the nuke.

2022-09-21 02:26 UTC, lKiseki commented
> Provided the marines haven't secured the nuke immediately after they get the disks, it's trivial for the xenos to take the nuke for a long trip. Especially since the usual design philosophy is to put the nuke in xeno territory.

To be fair, if a nuke isn't anchored, you _can_ push it. Whether xenos can pull the nuke or not feels irrelevant to me considering this fact. I'm pretty sure they'd have better luck just pushing it too, since it's faster.

> Perhaps a marine had it out for whatever reason, maybe their storage is full and they're trying to free space first, maybe they're transferring the disc to somebody else like their SL or FC. Imagine a runner pounces them, the disc drops, and the rouny runs away dragging the disc at light speed. The xenos could probably play keep a way for quite a while, long enough to either drag the round out or let attrition kill the marines before they can activate the nuke.

You can reprint disks, and if you screwed up like that, I'd say it's your fault. Nothing you can't fix, either way.

2022-09-21 03:54 UTC, Lumipharon commented
> You can reprint disks, and if you screwed up like that, I'd say it's your fault. Nothing you can't fix, either way.

If you're fighting your way to the nuke, and queen screes you as you're trying to unbolt it and the disk gets stolen, that's uh, gonna be pretty cope.

2022-09-21 06:48 UTC, FosterGrime-Heymynameslouie commented
> > You can reprint disks, and if you screwed up like that, I'd say it's your fault. Nothing you can't fix, either way.
> 
> If you're fighting your way to the nuke, and queen screes you as you're trying to unbolt it and the disk gets stolen, that's uh, gonna be pretty cope.

 If you're fighting your way to the nuke, you get to nuke, place disks in and unbolt it and queen screes you as you're trying to pull it out and the nuke gets to take a trip to brazil, that's uh, gonna be pretty cope.

this is a pretty good pr nonetheless, I believe a good blacklist on the things that cant be pulled are the ones that xenos cant already acid, which are usually round critical items
so no pulling disks or nuke 

other than that this is a pretty cool PR
I cant wait to drag flashbangs infront of a push and stun everyone with line of sight of me

2022-09-21 11:11 UTC, Naaanii commented
> > Provided the marines haven't secured the nuke immediately after they get the disks, it's trivial for the xenos to take the nuke for a long trip. Especially since the usual design philosophy is to put the nuke in xeno territory.
> 
> To be fair, if a nuke isn't anchored, you _can_ push it. Whether xenos can pull the nuke or not feels irrelevant to me considering this fact. I'm pretty sure they'd have better luck just pushing it too, since it's faster.
> 
> > Perhaps a marine had it out for whatever reason, maybe their storage is full and they're trying to free space first, maybe they're transferring the disc to somebody else like their SL or FC. Imagine a runner pounces them, the disc drops, and the rouny runs away dragging the disc at light speed. The xenos could probably play keep a way for quite a while, long enough to either drag the round out or let attrition kill the marines before they can activate the nuke.
> 
> You can reprint disks, and if you screwed up like that, I'd say it's your fault. Nothing you can't fix, either way.

Nuke and disks being draggable is fine imo. However, it would be better to make sure that it cannot pass through fog, at least the nuke. Such cheese isn't healthy, whereas disks can be reprinted, several copies can be printed to prevent one disk being lost an issue for marines.

Marines already know how to remove disks from the nuke to keep it anchored and active too, so I don't think it's really an issue with Xenos being able to drag it.

2022-09-21 11:15 UTC, FIXTHERADBOXPLEASE commented
Won't this just let the Xenos drag every req gun to the silo the second any stun forces a drop? Unless it means big objects only.

2022-09-21 11:28 UTC, MathiasOrtega commented
> > Sounds like most of the time it'll be used purely to steal shit off people being revived. You can argue that a corpsman shouldn't be reviving that close to xenos, but he's not the one being punished, you are, and you have no say in the matter due to being dead.
> 
> Gives me an idea of making a module or something default in jaeger armor that allows medics to defib you and such without taking your armor off.

Something to not have to take armor off would be fair. But shouldn’t be a module slot to sacrifice.

2022-09-21 17:30 UTC, Losenis commented
Oh god you can be a shrike and fling the guy away and then unrelenting force his gun into the maze to get acided

2022-09-21 17:31 UTC, Losenis commented
Wait I just thought of an actual balance concern, wouldn't this make carriers extremely dangerous by dragging their huggers and forceshuffling marines into walking onto their huggers?

2022-09-21 20:41 UTC, lKiseki commented
> Wait I just thought of an actual balance concern, wouldn't this make carriers extremely dangerous by dragging their huggers and forceshuffling marines into walking onto their huggers?

Eyup. This was the first thing that was brought up, too. I'll wait on maintainers before I do more changes, though.

2022-09-22 03:26 UTC, ivanmixo commented
Not sure how balanced xenos being able to drag flares is, nerfs their usefulness pretty significantly

2022-09-22 06:08 UTC, Al-1ce commented
> Not sure how balanced xenos being able to drag flares is, nerfs their usefulness pretty significantly

It would be easy to add to a blacklist of undraggable items. Usually if a xeno is by a flare they're being shot at anyways though.

2022-09-22 13:01 UTC, Zar000 commented
They can drag nuke discs

2022-09-22 16:21 UTC, ivanmixo commented
> > Not sure how balanced xenos being able to drag flares is, nerfs their usefulness pretty significantly
> 
> It would be easy to add to a blacklist of undraggable items. Usually if a xeno is by a flare they're being shot at anyways though.

Easier to drag them away somewhere than stand there and melt them though. Maybe add a delay to xenos pulling objects? As in a timer before they can pull something.

2022-09-22 23:16 UTC, Al-1ce commented
> Easier to drag them away somewhere than stand there and melt them though. Maybe add a delay to xenos pulling objects? As in a timer before they can pull something.

Again, it won't be able to be dragged if it's added to a blacklist. That's the intent. - And I believe slowdown is being applied based on the size of the object being pulled regardless. Disk dragging is not good and we shouldn't have it in the game, period.

2022-09-22 23:48 UTC, revelation-8468 commented
i think all items should be on the blacklist

oh wait

2022-09-23 00:06 UTC, Naaanii commented
PC, flares and guns are draggable as it stands.

2022-09-23 00:16 UTC, Lumipharon commented
Having to make a convoluted blacklist of things you can't drag is a pretty clear sign that dragging is not a good idea honestly.

2022-09-23 05:22 UTC, Nickkoranda commented
Massively exploitable if you're smart enough, doesn't bring much besides cucking marines in ways that aren't fun (I wish carrier could move things tho).

2022-09-23 20:13 UTC, Losenis commented
>And I believe slowdown is being applied based on the size of the object being pulled regardless

Comically large tweezers better fully immobilize crushers trying to pull them

2022-09-24 01:14 UTC, novaepee commented
Either there is xeno pulling or there is no xeno pulling. Blacklist is not negotiable unless you convince Tivi and Bravemole.

![image](https://user-images.githubusercontent.com/6610922/192073946-aff3809e-0ac8-4f9d-8d65-3eed27affc45.png)

2022-09-24 01:30 UTC, MathiasOrtega commented
You have opened a whole can of worms with this. One on hand yea it’s fine for xens to move things for their benefit. But not having a blacklist is just an open artery at this point.

2022-09-24 21:11 UTC, Notamaniac commented
What's happened so far with xeno pulling

1. Flares being pulled by any caste, allowing xenoes to quickly negate any light disadvantage, and also pull away flares that might've been too risky to sit and acid.
2. Defenders using roller beds to tailsweep/charge stun, buckle the marine to the roller bed and drag them far away. Doubly so if they manage to crit a marine on a roller bed, allowing them to drag them far far away without the oxy loss from crit drag.
3. Unanchored nukes being pushed into wraith portals, which can then freely be dragged away halfway across the map. Xenoes can force marines to play tag with a runner dragging the nuke.
4. Welder tanks being much more easily weaponised and pushed not only against the FOB, but into the middle of marine pushes.
5. RR's and other expensive req equipment being pulled away as soon as they are dropped, to be safely melted.
6. Xenoes using wheel chairs to transport dead bodies

2022-09-24 21:32 UTC, MiniMeatwad commented
What about body drag? Return of the body drag means you can safely make xenos more punishable without making them collapse in 5 minutes because they can't permanently kill anybody.

2022-09-24 22:09 UTC, Losenis commented
It's starting to sound like enabling pulling for xenos is causing a ton of unintended gaming behaviors. Most things xenos need to be able to pull can also be made destructible like marines piling up water tanks or other things that do need pulling otherwise.

2022-09-25 00:28 UTC, Strayed-Raven commented
Just today I have seen a drone pull around an open roller bed. Make of this what you will.

2022-09-25 04:59 UTC, Lumipharon commented
Trying to use a plasmacutter is complete agony now. Any stun and cya later PC.

2022-09-25 13:04 UTC, Naaanii commented
PCs could use a magharness now.

2022-09-25 14:39 UTC, Weedmaster77 commented
Xenos being able to drag the nuke when they could push it around already is really a bad idea xenos just play keep away with the nuke now it most definitely need to be blacklisted for there dragging if dragging is going to be left to merged. Letting them push it around is fine but dragging is just unfair when they can run away with it faster then any marine can keep up with it.

2022-09-26 18:34 UTC, bowlofcereal commented
Got shrike stunlocked and watched as another xeno dragged my weapon into the maze to never be seen again. Repeat this another 5 times. Also the fact that xenos can steal mission critical equipment or limited items.

Guys. Please. Not a good idea, and I normally advocate for xeno buffs. This is just unfair stuff.

2022-09-26 22:55 UTC, Pariah919 requested changes
This is a terrible idea as testing has shown.

2022-09-27 00:11 UTC, Lumipharon commented
PC impossible to use, even with the belt harness PR since the PC itself goes in the belt slot.
Benos dragging stasis bags, dragging flashbangs into fire for 20 year aoe stuns on marines, etc.

I'll say it again, this PR can only work with a blacklist, and that's bad because it will not be IC obvious to less experienced players what can and can't be dragged, and it will constantly need updating/get battled over as people find new ways to abuse it.

2022-09-27 17:48 UTC, Losenis commented
They're dragging stun grenades into fire and activating them in an ungaball now. I lost sight of what benefit this brought other than runners bringing donk-pockets to fob for shits n giggles. What actual benefit is there to outweigh having to blacklist essentially every item in the game with any meaningful reason for being pulled in the first place?

2022-09-28 09:28 UTC, comfyorange commented
#### Test Merge Updated

##### Server Instance
TGMC

##### Merged By
GAME\oj

##### Revision
Origin: fd13cccb034c3ed8b1e7f742ecb93ac14c7e70a6
Pull Request: 9f0309a5b970acf04cca83f6e379e2376bfa931e
Server: 8139b1c1260f0a002dbaf1f4ef6d0f367ace6046

##### Comment
oranges was here 2

2022-09-28 12:07 UTC, FosterGrime-Heymynameslouie commented
due to the very polarizing and just really annoying and borderline extreme unfun behavior with flashbang I think it would be best to 

make it so that only carriers can drag items for obvious reasons

they could still hide their traps n stuff and also if they really want to do the flashbang thing they are exposing themselves alot especially with their squishy bodies


or maybe you could just replace HVX flashbang with HVH

2022-09-29 00:35 UTC, Al-1ce commented
> due to the very polarizing and just really annoying and borderline extreme unfun behavior with flashbang


Why the hell are marines using flashbangs in HvX? They're normally not supposed to be able to, even mechanically.

2022-09-29 00:39 UTC, Losenis commented
They're not using them, they spawn in sec sections and can be activated by fire much like normal grenades. Xenos can go and pull them.

2022-09-29 04:34 UTC, lKiseki commented
> They're dragging stun grenades into fire and activating them in an ungaball now. I lost sight of what benefit this brought other than runners bringing donk-pockets to fob for shits n giggles. What actual benefit is there to outweigh having to blacklist essentially every item in the game with any meaningful reason for being pulled in the first place?

Solved this in #11098.

2022-09-29 20:32 UTC, comfyorange commented
#### Test Merge Deployed

##### Server Instance
TGMC

##### Merged By
GAME\tiviplus

##### Revision
Origin: f672f018d98fbc3542ada38d6260f37d4c50d0e3
Pull Request: 10e2ed555605fd54ac29eee5d1076710e28210d5
Server: 0f2e13d46370ed4b71632488688e40bdd3acef2e

##### Comment
No comment set - Fast Add
[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

2022-09-29 22:53 UTC, comfyorange commented
#### Test Merge Removed

2022-09-30 20:17 UTC, comfyorange commented
#### Test Merge Deployed

##### Server Instance
TGMC

##### Merged By
GAME\tiviplus

##### Revision
Origin: 244e28c96322ec39d06af2ab8d05ce6051299714
Pull Request: 10e2ed555605fd54ac29eee5d1076710e28210d5
Server: b22fb77831c1f2dbc2222fb125416ba2220e64c4

##### Comment
No comment set - Fast Add
[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

2022-09-30 20:19 UTC, comfyorange commented
#### Test Merge Updated

##### Server Instance
TGMC

##### Merged By
GAME\tiviplus

##### Revision
Origin: 244e28c96322ec39d06af2ab8d05ce6051299714
Pull Request: 10e2ed555605fd54ac29eee5d1076710e28210d5
Server: 08424fe2de96d50e0d4e6739f9184a5fd165907b

##### Comment
No comment set - Fast Add
[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

2022-10-01 16:09 UTC, comfyorange commented
#### Test Merge Updated

##### Server Instance
TGMC

##### Merged By
GAME\tiviplus

##### Revision
Origin: 3398322f1f506d5ac8ae36ca492d3fb015506b02
Pull Request: 10e2ed555605fd54ac29eee5d1076710e28210d5
Server: 8a3c8b025777ba377bb061b61a5c7ec23f61e9af

##### Comment
No comment set - Fast Add
[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

2022-10-01 23:34 UTC, Losenis commented
This ain't it, chief. Still invalidates flares and any illumination, indirectly buffs any displacement ability because the important items will go with them (IE shrike), and there's no reason to drag anything that wouldn't already be a huge issue for marines. If magharn/beltharness weren't meta, they will absolutely be now to the point of suicide if you go without any of them, and that's assuming a runner doesn't steal your stuff ignoring said things to then drag it away to get acided. Any items worth dragging will get acided.

2022-10-02 17:43 UTC, blackdav123 commented
Does not feel good to play around imo. Dragging shit as a xeno means spending time doing things that do not involve fighting and generally feel more like a chore than an advantage, and the classic "acid every weapon before the marines can get to them" was already a fun playstyle that people would deliberately play around. This also creates more balance considerations for every single item and whether they should be draggable or not. On the marine side it feels really shitty to have to wait in fob for even longer every round hoping that req will fill every order for a lost gun. I've seen people filling crates with spare weapons as they would with grenade launchers just to solve this issue. 

I dont think this is a feature worth keeping.

2022-10-03 11:00 UTC, ThelastArchiver commented
as everyone says that the problem is that they steal req weapons and simply walk away with them iam wondering how they even got to you as for one the only attachment you can put onto sadar is a mag harness getting the sadar stolen because not wearing a mag harness is a skill issue same for sg minigun ,minigun, shotgun and railgun only that those can also have a flashlight too as attachment at the top but considering sg night vision and the general low use of flashlights overall there is no reason to not put a magharness on these guns before taking them down as for the req sniper if you get somehow caught alone with a sniperrifle because you are not with the ungaball that is also your own fault the only req weapon that is actually in danger here is the scout rifle as most people probably rather use a scope here instead of a mag harness. This concludes my essay to why req weapons arent really endangered by this exept through marine incompetence.

2022-10-03 13:03 UTC, merged

2022-10-03 13:37 UTC, DerpiestBruh commented
real

2022-10-03 15:01 UTC, iLikeMemes commented
![wireless grab](https://user-images.githubusercontent.com/76254234/193610048-f5ac31fb-b932-499b-82a9-955c53842bcc.png)

psychic weed grab moment.

(you can attempt to grab things with ctrl-click outside of your grab range and it will still do the grab windup)

2022-10-03 15:06 UTC, DerpiestBruh commented
intended say goodbye to your ammo boxes :)

2022-10-03 17:43 UTC, Mechswordsman commented
> as everyone says that the problem is that they steal req weapons and simply walk away with them iam wondering how they even got to you as for one the only attachment you can put onto sadar is a mag harness getting the sadar stolen because not wearing a mag harness is a skill issue same for sg minigun ,minigun, shotgun and railgun only that those can also have a flashlight too as attachment at the top but considering sg night vision and the general low use of flashlights overall there is no reason to not put a magharness on these guns before taking them down as for the req sniper if you get somehow caught alone with a sniperrifle because you are not with the ungaball that is also your own fault the only req weapon that is actually in danger here is the scout rifle as most people probably rather use a scope here instead of a mag harness. This concludes my essay to why req weapons arent really endangered by this exept through marine incompetence.

"It is already meta, so there is nothing wrong with forcing it to be even more so, forever".  Just because the existing problem was bad, doesn't make this also not bad for the state of gameplay.  I guess nobody wanted to try other things with their attachie spots.

2022-10-03 19:04 UTC, Losenis commented
"Dude just use a magharness" they saw as runner gets an ability to bypass magharness, possibly setting a precedent for future abilities

2022-10-03 19:06 UTC, Losenis commented
Oh the shitshow got merged, bluename moment

2022-10-03 20:35 UTC, Strayed-Raven commented
This is what happens when something is on a wishlist i guess

2022-10-04 11:32 UTC, comfyorange commented
#### Test Merge Removed

2022-10-09 21:09 UTC, Losenis commented
You ever gotten shufflehugged by a hugger dragged around by a runner and there's fuckall you can do about it because even the runner will tank whatever shot goes towards the hugger, assuming you can even hit it in the first place? Yeah that's happening.

2022-10-18 18:19 UTC, MiniMeatwad commented
Add drag slowdown equivalent to dragging human bodies, and cancel it if you get shot. Considering you can steal the code from psydrain and normal xeno body pulling, i'm sure it's not THAT hard.

That way xeno pulling is not used to do cheesy shit in combat, it's just for pulling fuel tanks and shit in the way.