Shield rebalance
tgstation/TerraGov-Marine-Corps pull request #11020
Opened 2022-09-21 09:50 UTC by Lumipharon

## About The Pull Request
So I'm a dumb dumb and didn't realise that the default coverage of shield items against all projectiles is... 100%
i.e. until your shield gets degraded, it absorbs all incoming projectile damage.

Changed it to instead block 60% of bullet, laser and energy damage, and reduced fire block from 80 to 70.
This should have very little impact on HvX but is rather needed for HvH.

## Why It's Good For The Game
Full damage invulnerability is not ideal.

## Changelog
:cl:
balance: Reduced the percentage of damage absorbed by shields for bullet, lasers, energy and fire
/:cl:

2022-09-21 15:28 UTC, BraveMole approved these changes

2022-09-22 11:46 UTC, TiviPlus requested changes
use defines pls

2022-09-23 09:48 UTC, Lumipharon commented
> use defines pls

One day I'll actually remember without you reminding me... maybe.

2022-09-23 10:07 UTC, RikuTheKiller commented
A bit too hard a nerf, 70% - 75% at full durability would be more ideal in my opinion.

2022-09-23 13:34 UTC, merged