Adds the Pheromone Tower (VSC edition)
tgstation/TerraGov-Marine-Corps pull request #11041
Opened 2022-09-23 00:55 UTC by lKiseki

## About The Pull Request
This is NOT a web commit. Damned maintainers...

Adds a new **xenomorph structure** to the game, called the **Pheromone Tower**.
This structure can be purchased using the Mother's Blessings menu, for **150 psychic points**.

![Untitled](https://user-images.githubusercontent.com/59634950/191857261-97043da9-67db-4785-a82b-d79c69684155.png)

This structure **can be interacted with**, allowing you to **select the type of pheromone** that it will emit.
It can emit **recovery**, **warding**, and **frenzy**, and the strength of these pheromones is the maximum possible strength (**Very strong**, comparable to a mature queen's).
Its range is **22 tiles**, on par with a mature Queen's pheromones range.
Its **color**, and the **faint light** it emits, **change** according to the selected pheromone type.

## Why It's Good For The Game
- Adds more options for xenomorphs to the Mother's Blessings menu.
- Allows certain castes like the Queen/Empress to emit other types of pheromones, rather than being forced to emit Recovery at all times if they want to assist their team (the same applies to a Shrike in the absence of a Queen).

## Changelog
:cl: Lewdcifer
add: Adds the Pheromone Tower to the game, alongside its related sprites.
/:cl:

2022-09-23 01:23 UTC, Kuro020 approved these changes

2022-09-23 01:31 UTC, FosterGrime-Heymynameslouie commented
speede merhg instantly

also I think it should be like, 50 psy points or be buildable normally just with an abnormally long ass cooldown because getting psy points to begin with is a bit of a hassle already. I think.

2022-09-23 03:17 UTC, private-tristan commented
150 psypoints seems crazy expensive for this, as foster said, maybe it should instead emit a weak Z-level wide pheromone (scaling with number of towers)?

also who can change the pheremones of the tower? it'd be quite troublesome if someone kept switching it around, maybe only queen/shrike+leaders+hivelord

2022-09-23 04:39 UTC, lKiseki commented
In lieu of the above posts, I've decided to drop the cost from **200** (my mistake here, was supposed to be 150 but I overlooked that) to **100**. I will not drop it any further, however, since tier 5 pheromones are no joke.

2022-09-23 04:41 UTC, lKiseki commented
> also who can change the pheremones of the tower? it'd be quite troublesome if someone kept switching it around, maybe only queen/shrike+leaders+hivelord

Anyone can. If maintainers believe it pertinent, it can be done, but my personal feelings on the matter are against such a restriction.

2022-09-23 04:43 UTC, Pariah919 requested changes
> In lieu of the above posts, I've decided to drop the cost from **200** (my mistake here, was supposed to be 150 but I overlooked that) to **100**. I will not drop it any further, however, since tier 5 pheromones are no joke.
>
400 PP minimum at tier 5 pheros considering I know the main reason anyone would use this is to stack resting weeds, and this frees up queen pheros to be far more flexible.

2022-09-23 05:46 UTC, lKiseki commented
> 400 PP minimum at tier 5 pheros considering I know the main reason anyone would use this is to stack resting weeds, and this frees up queen pheros to be far more flexible.

I beg your pardon? Pheromone towers, worth 400 psychic points _(100 more than maturity and evolution tower)_, because it can be stacked with resting weeds and gives queen flexibility?

I think I'd rather wait and see what Tivi or Mole say. I'm open to the idea of increasing its cost back to **200** if need be, but 400 is just outrageous. Don't forget the fact that this is a purchase, not something they're given for free. It has to be worth the cost.

2022-09-23 07:20 UTC, UntoldTactics commented
Is anyone not noting that its still limited in range? It has to be within close proximity (relative) to marines. That means it's likely to be destroyed if marines push- its good for hive defense but otherwise its very...tactically odd, and might only be viable in certain mazes or in FOB sieges. The cost should accordingly probably be on the lower side or it just won't be used as much if ever.

2022-09-23 09:04 UTC, XSlayer300 commented on code/modules/xenomorph/xeno_structures.dm
> +	name = "Pheromone Tower"
```suggestion
	name = "Pheromone tower"
```
consistancy for the maturity tower above.

2022-09-23 18:57 UTC, KrabSpider commented
I can see the recovery tower being used for setting up a healing bay in out of the way locations and such.

2022-09-23 21:08 UTC, TiviPlus requested changes
Rest LGTM

2022-09-23 21:08 UTC, TiviPlus commented on code/modules/xenomorph/xeno_structures.dm
> +	var/aura_range = 22
diameter or radius?

2022-09-24 06:19 UTC, MereWalker commented
Should make it emit low light for red, slightly brighter light for yellow and harsh light for blue.You can also choose to ignore me. Nonetheless I like this for xenos.

2022-09-24 19:05 UTC, Weedmaster77 commented
Anything above T3 pheros from a tower seems way to much from a structure for only 100 PP it need to be like 25 PP-30 PP for T1, 30 PP- 50 PP for T2,50 PP-100 PP for T3,120 PP -150 PP for T4 and 200 PP-250 PP forT5 pheros. Then give the tower the ability to upgrade it to the next Tier. An thinking T5 for 100 is a good idea is so broken T5 needs to be at least 200-250 if not more or it just takes away the usefulness of pheros caste so much which people aright don't want to play so taking away a large reason of play them for a place-able 100 PP T5 tower is a bad idea.

2022-09-25 20:13 UTC, merged