Adds M43 Sunfury mk1 to marine vendor and some tweaks about it
tgstation/TerraGov-Marine-Corps pull request #11052
Opened 2022-09-25 09:15 UTC by CabbageOnTable

## About The Pull Request

Basically pr adds m43 sunfury mk1 and things to it in marine vendor:
*Adds 20 high cap mags to sunfury (80 shots)
*Adds basic mags (30 shots)
*Adds selfrechargeable mags (30 shots) req only
![image](https://user-images.githubusercontent.com/114332059/192135559-45d6cd66-4a94-4e49-a0d6-81085d0a5915.png)

*All sunfury's from vendor have pulse lense for auto mode
*Adds efficiency and wide lenses to marine vendor
![image](https://user-images.githubusercontent.com/114332059/192135586-cd048bb2-9c56-40ff-844e-d78cabae7cf1.png)

*Adds selfrechargeable cells, high cap cells, focus lens, heat lens to reqs (fit to sunfury only).
![image](https://user-images.githubusercontent.com/114332059/192135630-3fdfc2cd-0c52-4b68-af67-02280691a7bd.png)

*More attachement for sunfury (flamer, underslug, masterkey, tactical sensor, PP-7, T-47, pepperball)
![image](https://user-images.githubusercontent.com/114332059/192135680-554f8a53-e75f-4b36-b9e1-8b5c7d129283.png)

## Why It's Good For The Game

Adding a new (old) laser gun, with a few tweaks to make it fun and playable, I didn't change the gun's damage and rate of fire. A self-charging battery does not charge instantly, if you want to shoot non-stop then you need 3-4 mags and that's about 20 points in req. By itself, Sunfury doesn't hit very hard, it doesn't have IFF and aim mode, so I consider those attachments is fair and not going to break balance. Pulse fire is fun.

## Changelog
:cl:
add: M43 Sunfury mk1 to marine vendor and things to it
add: M43 Sunfury mk1 selfrechargeable cell
expansion: Expands list of M43 Sunfury mk1 attachements
fix: Fix M43 sunfury mk1 codex ammo amount
/:cl:

2022-09-25 09:49 UTC, FosterGrime-Heymynameslouie commented
cool pr, finally good to see one of the long lost guns dug out of purgatory

question though, will sunfury retain the old laser projectile or will it be hitscan?

2022-09-25 10:00 UTC, CabbageOnTable commented
I think the highlight of the sunfury is the old laser projectile. I want to see at least one projectile laser gun for marines (non-req). And that's why I wrote this pr

2022-09-25 10:25 UTC, FosterGrime-Heymynameslouie commented
> I think the highlight of the sunfury is the old laser projectile. I want to see at least one projectile laser gun for marines (non-req). And that's why I wrote this pr

oh ok, cool just wanted to know

speded mrhge

2022-09-25 14:18 UTC, Kuro020 requested changes
I know that tivi and mole are gonna qdel this pr when they see it, but anyways
The sunfury sprite is not up to standard unga guns, get a better sprite

2022-09-25 21:17 UTC, Losenis commented
Based, I missed the old lasgun so damn much

2022-09-26 20:31 UTC, closed without merging

2022-09-26 22:46 UTC, Losenis commented
It's a non-hitscan laser weapon, after the hundred hitscan lasers that got put in to replace the old one it turned out to be pretty unique as a trait.