Adds particle visuals to some of Defiler's abilities
tgstation/TerraGov-Marine-Corps pull request #11120
Opened 2022-10-02 23:37 UTC by lKiseki

## About The Pull Request
Adds some particles to some of Defiler's abilities, visually enhancing them. Proof of concept below.

**REAGENT SLASH:**

https://user-images.githubusercontent.com/59634950/193481262-e9d864dc-59a1-4359-9acb-f944105d38f6.mp4

**EMIT NEUROGAS:**

https://user-images.githubusercontent.com/59634950/193481282-394fcb5c-18af-4945-bd9c-f820cc975abc.mp4

Note that I used reagent slash for this just for show. In practice, it looks like so:

https://user-images.githubusercontent.com/59634950/193481315-afcab5ef-8471-4546-8f91-bdf8e9fb6713.mp4

## Why It's Good For The Game
Game look pretty. Therefore, game good.

## Changelog
:cl: Lewdcifer
imageadd: Added particle visuals to Defiler's Reagent Slash and Emit Neurogas abilities.
/:cl:

2022-10-02 23:38 UTC, lKiseki commented
Someone in the Discord expressed a concern regarding whether particles were visible over smoke. This is false. Proof below:

https://user-images.githubusercontent.com/59634950/193481384-b2acfba3-27ce-4d8a-8878-d4fc75df760f.mp4

2022-10-03 00:02 UTC, Kuro020 approved these changes

2022-10-03 00:47 UTC, novaepee commented
pretty

2022-10-04 11:37 UTC, 567Turtle commented
thank you very c

2022-10-04 21:32 UTC, TiviPlus requested changes

2022-10-04 21:32 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
> +	var/mob/living/carbon/xenomorph/X = owner
please invert these (ie deactivate becomes activate)
Usually toggles mean TRUE = ON, FALSE = OFF and this is inverted

2022-10-04 21:32 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
> +	if(deactivate)
ditto

2022-10-05 09:53 UTC, TiviPlus approved these changes

2022-10-05 09:53 UTC, merged