Vali Necro Warning Adjustment
tgstation/TerraGov-Marine-Corps pull request #11150
Opened 2022-10-06 15:24 UTC by Jalopkomit18

## About The Pull Request
Currently Vali alerts to impending after 12 secs, giving necro hud and periodic text warnings. Changes to two step warning, with text warning only at 10 secs onwards, and necro hud appearing at 17 secs onwards. This translates to text warning appearing at 10 seconds left and necro hud appearing at 3 seconds left. Values still undecided until tested.

## Why It's Good For The Game
Current vali warning is imprecise and misleading imo. //in prog

## Changelog
:cl:
qol: Vali necro warning divided into two warnings at separate intervals
/:cl:

2022-10-14 21:09 UTC, Jalopkomit18 commented
Adjusted values to have text only warning occur starting at 10sec onwards. Necro hud warning occurs at 15sec onwards, and also has its own text warning distinct from the regular warning. Ready to merge.

2022-10-15 19:37 UTC, TiviPlus commented
Did you test this?

2022-10-15 23:41 UTC, Jalopkomit18 commented
> Did you test this?

Yes. The only thing I'm worried about is that with lag and network delay, the timers may be too short. I added a buffer already even though I wanted the final timer to be shorter, but if it's too short still I can change the numbers around again.

2022-10-16 08:40 UTC, BraveMole requested changes

2022-10-16 08:40 UTC, BraveMole commented on code/datums/components/chem_booster.dm
> +		if(world.time - processing_start > 15 SECONDS && world.time - processing_start < 20 SECONDS)
You are checking the same thing twice. And also you can cache world.time - processing start in a var

2022-10-16 23:05 UTC, Lumipharon requested changes

2022-10-16 23:05 UTC, Lumipharon commented on code/datums/components/chem_booster.dm
> +		var/necrotized_counter = FLOOR(min(vali_necro_timer, 20 SECONDS)/200 + (vali_necro_timer-20 SECONDS)/100, 1)
```suggestion
		vali_necro_timer = world.time - processing_start
		var/necrotized_counter = FLOOR(min(vali_necro_timer, 20 SECONDS)/200 + (vali_necro_timer-20 SECONDS)/100, 1)
```
We want to make sure  the value is accurate

2022-10-17 05:59 UTC, BraveMole requested changes

2022-10-17 05:59 UTC, BraveMole commented on code/datums/components/chem_booster.dm
> +		if(vali_necro_timer > 15 SECONDS)
You do not have to indent that, it being in main scope is fine

2022-10-17 05:59 UTC, BraveMole commented on code/datums/components/chem_booster.dm
> +	if(connected_weapon && vali_necro_timer < 20 SECONDS)
Rather than checking timer < 20 two times, you can just check if once and early return it is above.

Ex: 
If(timer > 20)
      Return

2022-10-20 18:41 UTC, merged