MP is back in Theseus
tgstation/TerraGov-Marine-Corps pull request #11168
Opened 2022-10-08 18:01 UTC by novaepee

## About The Pull Request

Prepare for the MP

## Why It's Good For The Game

Soon mech is here

## Changelog
:cl:
expansion: add MP room in Theseus
/:cl:

2022-10-08 18:14 UTC, RipGrayson requested changes
![tile42](https://user-images.githubusercontent.com/49290523/194721704-c78bbb62-848f-41db-a4f2-dba32b4efb15.png)
It looks odd being so open, please give this area shutters (and a button to open them).

2022-10-09 20:03 UTC, TiviPlus approved these changes

2022-10-09 21:49 UTC, RipGrayson approved these changes

2022-10-09 21:49 UTC, merged

2022-10-09 21:53 UTC, FosterGrime-Heymynameslouie commented
it begins