[WIP] Mech ability/utility modules
tgstation/TerraGov-Marine-Corps pull request #11161
Opened 2022-10-08 12:35 UTC by TiviPlus

Code is 90% done just waiting for kuro to sprite
Adds for starters:
Zoom
actuator overload
cloak smoke
tanglefoot smoke

2022-10-08 13:59 UTC, XSlayer300 commented on code/modules/vehicles/mecha/equipment/tools/greyscale_tools.dm
> +	desc = "generates a large amount of cloaking smoke to disguise nearby friendlies. Sadly, huge robots are too difficult to hide with it."
```suggestion
	desc = "A multiple launch module that generates a large amount of cloaking smoke to disguise nearby friendlies. Sadly, huge robots are too difficult to hide with it."
```

2022-10-09 19:48 UTC, Kuro020 approved these changes

2022-10-11 20:42 UTC, BraveMole requested changes

2022-10-11 20:42 UTC, BraveMole commented on code/modules/vehicles/mecha/equipment/tools/greyscale_tools.dm
> +	var/flag_controller
= NONE

2022-10-11 20:42 UTC, BraveMole commented on code/modules/vehicles/mecha/equipment/tools/greyscale_tools.dm
> +	if(icon_state)
Call update icon imo

2022-10-11 20:42 UTC, BraveMole commented on code/modules/vehicles/mecha/equipment/tools/greyscale_tools.dm
> +	M.add_overlay(overlay)
Ditto

2022-10-11 20:42 UTC, BraveMole commented on code/modules/vehicles/mecha/equipment/tools/greyscale_tools.dm
> +	chassis.cut_overlay(overlay)
Ditto

2022-10-11 20:42 UTC, BraveMole commented on code/modules/vehicles/mecha/combat/gygax.dm
> +		chassis.add_overlay(ability.overlay)
Update icon ? This time less convinced

2022-10-11 21:01 UTC, TiviPlus commented on code/modules/vehicles/mecha/equipment/tools/greyscale_tools.dm
> +	var/flag_controller
```suggestion
	var/flag_controller = NONE
```

2022-10-11 21:19 UTC, merged