Adds a new event, Queen Mother's fireproofing
tgstation/TerraGov-Marine-Corps pull request #11185
Opened 2022-10-09 23:20 UTC by RipGrayson

## About The Pull Request

It's a new event, Tivi wants more of them and I sat down and made some.

Queen Mother's fireproofing acts like a team wide application of hivelord gel, it's low probability and limited to two times. It cannot activate unless the xeno team has enough players for a Queen.

## Why It's Good For The Game

More events good.

## Changelog
:cl:
add: Added a new event, Queen Mother fireproofing.
/:cl:

2022-10-13 09:26 UTC, Autisem commented
how long does this last? it feels like this would happen alot when its not needed and wear off when it is needed

2022-10-16 09:12 UTC, Lumipharon requested changes

2022-10-16 09:12 UTC, Lumipharon commented on code/modules/events/queen_mothers_fireproof.dm
> +	for(var/mob/living/carbon/xenomorph/X in GLOB.alive_xeno_list)
Don't use X, use proper var names.

2022-10-16 09:12 UTC, Lumipharon commented on code/modules/events/queen_mothers_fireproof.dm
> +/datum/round_event/queen_mothers_fireproof/proc/fireproof_xeno(mob/living/carbon/xenomorph/X)
var names.

2022-10-16 09:12 UTC, Lumipharon commented on code/modules/events/queen_mothers_fireproof.dm
> +	var/sound/queen_sound = sound(get_sfx("queen"), channel = CHANNEL_ANNOUNCEMENTS)
```suggestion
	var/sound/queen_sound = sound(get_sfx("queen"), channel = CHANNEL_ANNOUNCEMENTS, volume = 50)
```
default volume is 100, 50 is what's used for queen mother announcements

2022-10-23 13:37 UTC, RipGrayson commented
I've decided I don't like this event, it doesn't leave a lasting impact on the round besides the 60 seconds it's active.

2022-10-23 13:37 UTC, closed without merging