Adds a new event, hostile ert
tgstation/TerraGov-Marine-Corps pull request #11183
Opened 2022-10-09 23:08 UTC by RipGrayson

## About The Pull Request

It's a new event, Tivi wants more of them and I sat down and made some.

Hostile ERT is very a low chance event that has a chance of spawning an ERT squad of between 1-5 hostiles if the marines are stomping the xenos. It has a low chance of happening, is restricted to a single event, and requires the xenos to have less than 4-5 members left and the marines to have over 30. 

I expect this one might be contentious, and the numbers are open to change, the idea is to give the marines a slight bit of extra challenge if they're just rolling the xenos.

## Why It's Good For The Game

More events good.

## Changelog
:cl:
add: Added a new event, hostile ERT.
/:cl:

2022-10-09 23:12 UTC, Lumipharon commented
The issue here is that ert goes shipside, and even a small ert can potentially roll shipside quite quickly. This may also serve to further delay rounds where benos are already defeated and just delaying.

2022-10-09 23:15 UTC, RipGrayson commented
> The issue here is that ert goes shipside, and even a small ert can potentially roll shipside quite quickly. This may also serve to further delay rounds where benos are already defeated and just delaying.

I'm willing to code in extra checks if needed, or tighten the existing ones to prevent the event from triggering when it shouldn't.

2022-10-10 09:41 UTC, Oscari-pog commented
Perhaps make them land somewhere groundside instead? Pick a few areas on each map so they dont drop on FOB, and have them land on a random one

2022-10-11 10:46 UTC, TiviPlus requested changes

2022-10-11 10:46 UTC, TiviPlus commented on code/modules/events/hostile_ert.dm
> +	var/selected_ert = pick("CLF Cell","Sectoid Expedition","Sons of Mars Squad","USL Pirate Band","The Bone Zone","Pizza Delivery")
```suggestion
	var/selected_ert = pick("CLF Cell", "Sectoid Expedition", "Sons of Mars Squad", "USL Pirate Band", "Pizza Delivery")
```
Bone zone is a meme

2022-10-11 19:27 UTC, BraveMole requested changes
This event should definitelly happen groundside, not shipside

2022-10-11 20:21 UTC, RipGrayson commented
This is going to be a draft until I rewrite it to drop pod the ERT groundside

2022-10-12 06:35 UTC, Derrick2Electricboogaloo commented
Brave already asked what I was going to ask, I am definitely amenable to seeing a potentially hostile 3rd party show up on ground. Could make things interesting.

2022-10-19 01:22 UTC, Rexdyer1 commented
If you want to make this have a greater impact on the groundside, instead of having them go to the ship, it shouldn't be too hard to make a small pod room, or just spawn some hostile ert's in supply pods and have them land on the planet. Hostile ert shipside most rounds will likely outnumber any doc's or RO's and wipe easily.

2022-10-28 02:30 UTC, RipGrayson commented
Closing this until I have more time to work on it

2022-10-28 02:30 UTC, closed without merging