Vote refactor
tgstation/TerraGov-Marine-Corps pull request #11200
Opened 2022-10-11 12:05 UTC by Lumipharon

## About The Pull Request
Refactors vote code to remove snowflakey spaghetti regarding gamemodes with specific maps.

Gamemodes now have whitelists and blacklists for ship and ground maps, making it easier in the future as new gamemodes and map dependencies are added.

Now instead of having specific bits of code to load a specific map, as an example voting combat patrol will trigger a ship map vote which will default to combat patrol base as it will be the only valid option.

## Why It's Good For The Game
Less sphaghetti

## Changelog
:cl:
refactor: Refactor vote code to be less spaghetti
/:cl:

2022-10-11 12:06 UTC, Lumipharon commented
@TiviPlus This will require a config change. Combat Patrol Base (and I guess twin pillars) can now be votable like the rest of the maps, as they'll be blacklisted out of the votes when other modes are in play.

2022-10-11 14:17 UTC, TiviPlus commented
Noted

2022-10-12 16:51 UTC, TiviPlus requested changes
What exactly do I need to edit in config btw

2022-10-12 16:51 UTC, TiviPlus commented on code/datums/gamemodes/game_mode.dm
> +	var/list/black_list_ground_maps =list(MAP_WHISKEY_OUTPOST)
```suggestion
	var/list/black_list_ground_maps = list(MAP_WHISKEY_OUTPOST)
```

2022-10-12 20:16 UTC, Lumipharon commented on code/controllers/subsystem/vote.dm
> +					//	continue
Whoops forgot to delete.

2022-10-12 20:18 UTC, Lumipharon commented
> What exactly do I need to edit in config btw

In the shipmap config, I believe that patrol base and twin pillars have "voteweight 0" which needs to be removed.

2022-10-13 06:08 UTC, BraveMole requested changes
It is whitelist and blacklist, one word.
Rest lgtm

2022-10-13 14:13 UTC, BraveMole approved these changes

2022-10-13 14:13 UTC, BraveMole commented on code/controllers/subsystem/vote.dm
> +				var/ground_change_required
You should set them to false for clarity

2022-10-13 14:20 UTC, TiviPlus approved these changes

2022-10-13 15:15 UTC, merged