projectile based artillery + balance
tgstation/TerraGov-Marine-Corps pull request #11214
Opened 2022-10-12 09:33 UTC by tyeagg

## About The Pull Request
artillery fires a projectile instead of just a set time till shell lands
mortar is more mobile with lower deploy 
howitzer is a proper long range artillery now with high projectile speed but a high minimum range
also makes mortar flare and cas flare have a visual effect

## Why It's Good For The Game
better for mortar

## Changelog
:cl:
add: Added new mechanics or gameplay changes
add: Added more mechanics or gameplay changes
expansion: Expands content of an existing feature
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2022-10-12 10:09 UTC, FosterGrime-Heymynameslouie commented
holy shit, mortars actually make sense now 

spdde mghred

2022-10-12 11:43 UTC, Starfirejordan commented
FINALLY!! MORTAR AND ARTY ARENT BULLSHIT ANYMORE!! too many people took Arty and mortar for granted and its ability to lay down heavy fire that shreds anything that dares stands in its way

2022-10-12 14:27 UTC, Losenis commented
We rimworld now

https://www.youtube.com/watch?v=1dsraNAtI2M

2022-10-12 14:45 UTC, lbnesquik commented
Why did you delete the howitzer whistling noise? Does it not play anymore?

Are the effects visible to xenos? Like, can they see the projectile flying? That has some balance implications.

2022-10-13 13:08 UTC, lbnesquik commented
Nice. Can xenos see the shot coming, tho?

2022-10-13 14:57 UTC, TiviPlus requested changes

2022-10-13 14:57 UTC, TiviPlus commented on code/game/objects/machinery/mortar.dm
> +		user.balloon_alert(user, "[src]'s barrel is still steaming hot. Wait a few seconds and stop firing it.")
Too long for a balloon alert + has name insert

2022-10-14 19:47 UTC, TiviPlus commented
sleep isnt allowed btw

2022-10-16 19:05 UTC, TiviPlus requested changes

2022-10-16 19:05 UTC, TiviPlus commented on code/game/objects/machinery/mortar.dm
> +		amount_to_fire = length(chamber_items)
```suggestion
	var/amount_to_fire = fire_amount
	if(!amount_to_fire )
		amount_to_fire = length(chamber_items)
```

2022-10-16 19:05 UTC, TiviPlus commented on code/game/objects/machinery/mortar.dm
> +	var/turf/T = locate(coords["targ_x"] + coords["dial_x"], coords["targ_y"]  + coords["dial_x"], z)
proper var name for this pls

2022-10-16 19:05 UTC, TiviPlus commented on code/game/objects/machinery/mortar.dm
> +	G.ceiling_debris_check(2)
proper var name pls

2022-10-16 19:05 UTC, TiviPlus commented on code/game/objects/machinery/mortar.dm
> +		qdel(mortar_shell)
why do you qdel the mortar shell if you JUST put it in the list, this will hard del and add nulls

2022-10-16 19:05 UTC, TiviPlus commented on code/game/objects/machinery/mortar.dm
> +		qdel(mortar_shell)
forcemove it and instead qdel after it has fired

2022-10-17 01:26 UTC, tyeagg commented on code/game/objects/machinery/mortar.dm
> +		var/turf/impact_turf = pick(turf_list)
it was but with very higher amounts of fire the list will become empty meaning it will stop firing and cause a runtime

2022-10-18 08:51 UTC, TiviPlus commented on code/game/objects/machinery/mortar.dm
> +		shake_camera(M, 1, 1)
why

2022-10-18 08:54 UTC, TiviPlus requested changes
https://github.com/tgstation/TerraGov-Marine-Corps/pull/11214#discussion_r997914915

2022-10-18 20:22 UTC, comfyorange commented
#### Test Merge Deployed

##### Server Instance
TGMC

##### Merged By
Lewdcifer

##### Revision
Origin: e3409a458c7646f94667b86b4118a2ddefe029be
Pull Request: a0a25592d700b035d85c4ddba5417f235d7b1346
Server: 0cb0114322ab5bff59011db8ad0dde81bec04f0e

##### Comment

[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

2022-10-18 22:24 UTC, MiniMeatwad commented
I don't think this is how mortar works. Howitzer? Sure, give it a direct fire ability. Mortar? Give it a minimum delay. You're firing it into the sky, it's not gonna hit instantly.

2022-10-18 22:40 UTC, comfyorange commented
#### Test Merge Updated

##### Server Instance
TGMC

##### Merged By
Lewdcifer

##### Revision
Origin: 0a6bcd46aec7f644f8feb2d1a994d8165e1bbb91
Pull Request: a0a25592d700b035d85c4ddba5417f235d7b1346
Server: b101d8efcdad4319a5d4f1caffb0cf6a69621100

##### Comment

[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

2022-10-18 23:38 UTC, Starfirejordan commented
The mortar round sprite when fired looks bad ngl, also does mortar and arty have there own set ranger from how far they can fire?

2022-10-19 00:58 UTC, Starfirejordan commented
Complaint: arty spread way to fucking high

2022-10-19 05:25 UTC, Starfirejordan commented
> Yeah the spread is wack. Even over a comparatively short distance, my mortar shells are scattering around 30 tiles off target. The scatter per tile travells needs to be severely tuned down, and/or the total possible scatter capped.
> 
> Also why are mortars now click to fire? You drop in a mortar shell, that causes it to detonate. I get changing the howie, but not the mortar.

mortar isnt even meant to have spread wtf

2022-10-19 05:53 UTC, Starfirejordan commented
the arty keeps firing at locations it perversely targeted instead of the updated cords when trying to use bino with it linked

2022-10-19 08:37 UTC, tyeagg commented
> the arty keeps firing at locations it perversely targeted instead of the updated cords when trying to use bino with it linked I think this is why the "spread" is so bad, it because it still targeting the old cord instead of properly updating and then spreading, making you think the spread is stupidly big? idk

no its just comically large spread

2022-10-20 19:58 UTC, TiviPlus requested changes

2022-10-20 19:58 UTC, TiviPlus commented on code/modules/projectiles/ammo_datums.dm
> +	var/datum/effect_system/smoke_spread/smoketype = /datum/effect_system/smoke_spread/tactical
autodoc

2022-10-20 21:16 UTC, Lumipharon commented
This also makes mortar super strong close range, encouraging solo use. Since the travel time is so short you can fairly reliably just blap benos right on their heads.

2022-10-21 15:27 UTC, lbnesquik reviewed
I think this PR has some notable balance implications. 

Artillery didn't use to have spread, unless you set it manually. That was intended behavior, meant to deter blind firing and encourage having a spotter. Having spread for all shots is not nothing. Especially the rather hefty spread we saw during tests. 

The dynamic travel time is nice, but there should have a minimal delay, both logically and for gameplay reasons. It should probably be 1-3 seconds instead of half a second. Also, logically speaking, given we don't alter the powder charge, I'm not sure a mortar would have different travel times for anything it hits.

2022-10-22 17:36 UTC, comfyorange commented
#### Test Merge Updated

##### Server Instance
TGMC

##### Merged By
naaanii

##### Revision
Origin: af73cb5a187ee4479e42fb50efc36e8fbcfdfc30
Pull Request: a0a25592d700b035d85c4ddba5417f235d7b1346
Server: a82a7b9a2e34a0152938b45c435209b017c35eac

##### Comment

[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

2022-10-22 17:39 UTC, comfyorange commented
#### Test Merge Updated

##### Server Instance
TGMC

##### Merged By
Tiviplus

##### Revision
Origin: af73cb5a187ee4479e42fb50efc36e8fbcfdfc30
Pull Request: d7d8b81fe5488e4bbc0b8d60eab3fa015f44a522
Server: 2592483a876e876dcb90a7aa0c54b0fa595184c4

2022-10-23 02:42 UTC, Starfirejordan commented
question what did you even change with the spread

2022-10-23 05:53 UTC, Liznerd commented
damn the howie sucks, yeah the proyectile gets there super fast, maybe too much but the precision is FATAL, like missing by entire binoc screen, just please i beg you, give it some MUCH NEEDED PRECISION!!!

2022-10-23 06:28 UTC, Starfirejordan commented
Suggestion changes

Howi and mortar:
change how spread works, make it take 15-20 tiles for 1 spread instead of 10

Howi: 
Make it better hitting at long range so it can be used as arty thus less spread with travel
Make the round slower aswell 

Mortar:
Make it better at close range as missing awhile in view of area is stupid af

2022-10-23 06:33 UTC, Starfirejordan commented
> Yeah the spread is wack. Even over a comparatively short distance, my mortar shells are scattering around 30 tiles off target. The scatter per tile travells needs to be severely tuned down, and/or the total possible scatter capped.
> 
> Also why are mortars now click to fire? You drop in a mortar shell, that causes it to detonate. I get changing the howie, but not the mortar.

also yea why mortar have to click to fire? it shouldnt be

2022-10-24 05:52 UTC, comfyorange commented
#### Test Merge Updated

##### Server Instance
TGMC

##### Merged By
Lewdcifer

##### Revision
Origin: af73cb5a187ee4479e42fb50efc36e8fbcfdfc30
Pull Request: d7d8b81fe5488e4bbc0b8d60eab3fa015f44a522
Server: 99de39021678299d1ff1c63ce1c4f70ed66a98d9

##### Comment

2022-10-24 19:42 UTC, comfyorange commented
#### Test Merge Updated

##### Server Instance
TGMC

##### Merged By
Tiviplus

##### Revision
Origin: 1a0d30d9b48151b309e3ce11f7ab98481c77c9a9
Pull Request: d7d8b81fe5488e4bbc0b8d60eab3fa015f44a522
Server: 7adad29020eeb4be86efb0ddff82c4d7eb2491b2

##### Comment

[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

2022-10-25 04:34 UTC, Starfirejordan commented
![image](https://user-images.githubusercontent.com/102649696/197683438-ef386056-35ce-489c-aa26-9b53668484e5.png)
mortar should be added to req like the other tadpole weapon systems ngl that or a tadpole fabricator made for them

2022-10-25 06:58 UTC, tyeagg commented
what the fuck are you talking about

2022-10-25 14:07 UTC, Starfirejordan commented
> what the fuck are you talking about

![image](https://user-images.githubusercontent.com/102649696/197795801-8ef2b8aa-d20b-4136-ad1a-0e3b7008516a.png)
half the deployable mount meant for Tadpole are in req and not fabricator because idk

2022-10-25 19:20 UTC, comfyorange commented
#### Test Merge Updated

##### Server Instance
TGMC

##### Merged By
Lewdcifer

##### Revision
Origin: ba11e493e0e54387094b1aee3f723c962e51dc58
Pull Request: d7d8b81fe5488e4bbc0b8d60eab3fa015f44a522
Server: 17e47d3e33fcc9f6a5b8340311880374c53990ce

##### Comment

2022-10-25 19:29 UTC, comfyorange commented
#### Test Merge Updated

##### Server Instance
TGMC

##### Merged By
Lewdcifer

##### Revision
Origin: ba11e493e0e54387094b1aee3f723c962e51dc58
Pull Request: d7d8b81fe5488e4bbc0b8d60eab3fa015f44a522
Server: 1c1e4b98bed5b49a08101b5d08554feba05f2f0b

##### Comment

[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

2022-10-27 04:42 UTC, Pariah919 reviewed
Needs some adjustments but it seems alright to me.

2022-10-27 08:45 UTC, TiviPlus commented
I think tyes too lazy to make adjustments so ill merge and anyone can do it

2022-10-27 08:47 UTC, merged