Orion Fatigue, the latest bing in the military fashion system
tgstation/TerraGov-Marine-Corps pull request #11278
Opened 2022-10-17 05:07 UTC by novaepee

## About The Pull Request

Here comes the newest clothing that marines want! Originated from the Orion Military Outpost to serve their mission, this dashing rambo-esqe uniform makes any marines spend their entire paycheck for!

## Why It's Good For The Game

Good art demands to be in game. Kuro approves

## Changelog
:cl:
add: Orion Fatigue! Find it at the nearest clothing vendor!
/:cl:

2022-10-17 14:41 UTC, Losenis commented
ASS STRAPS

2022-10-18 00:16 UTC, MereWalker commented
Too bad we can rappel whatsoever. If we could the straps would be cool. Nonetheless look forward to the drip.

2022-10-18 01:52 UTC, Strayed-Raven commented
I will take a future addition of the Sneaking suit from MGS3. Otherwise cannot wait to see how this blends

2022-10-18 09:07 UTC, TiviPlus requested changes

2022-10-18 09:07 UTC, TiviPlus commented on code/game/objects/machinery/vending/marine_vending.dm
> +			/obj/item/clothing/under/marine/orion_fatigue =-1,
```suggestion
			/obj/item/clothing/under/marine/orion_fatigue = -1,
```

2022-10-19 01:34 UTC, Alexeivichi commented
METAL GEAR.

2022-10-21 18:47 UTC, TiviPlus approved these changes

2022-10-21 21:49 UTC, merged