Gelidafix
tgstation/TerraGov-Marine-Corps pull request #11275
Opened 2022-10-16 22:33 UTC by Derrick2Electricboogaloo

## About The Pull Request

Found some APCs in some areas of the map where there were duplicates. No doubt from CM areas that no longer exist

## Why It's Good For The Game

Fixes good

## Changelog
:cl:
fix: Removes multiple APCs in areas of the map where it causes issues
fix: Removes Some cables in the walls
/:cl:

2022-10-16 22:53 UTC, RipGrayson approved these changes

2022-10-16 23:09 UTC, RipGrayson requested changes
Actually, this PR uses the version of Gelida before this https://github.com/tgstation/TerraGov-Marine-Corps/pull/11224 and so has locked/welded doors. Please either update your map the latest version, or remove the offending locked and welded varedits.

2022-10-17 00:58 UTC, Derrick2Electricboogaloo commented
> 

Can do give me bit.

2022-10-25 15:48 UTC, Derrick2Electricboogaloo commented
I am going to close this for now until I can resolve some sourcetree problems.

2022-10-25 15:48 UTC, closed without merging