Add nymphs to the game
tgstation/TerraGov-Marine-Corps pull request #11273
Opened 2022-10-16 10:07 UTC by BraveMole

## About The Pull Request

Cutie spreading weeds

## Why It's Good For The Game

Cute targets for marines, usefull for xeno.
WIP

## Changelog
:cl:
add: Add nymphs to the game, cute auto weeders that comes from nymphs nest
/:cl:

2022-10-16 10:11 UTC, FosterGrime-Heymynameslouie commented
can you select what kind of weeds they spew out?

also the dawn of lesser beings serving xenos is now nigh

speded mergh instantly

2022-10-16 15:18 UTC, Autisem commented
any idea what can create these nests? or that still being brain stormed?

2022-10-17 06:00 UTC, BraveMole commented
> any idea what can create these nests? or that still being brain stormed?

Probably psy points

2022-10-17 13:37 UTC, lbnesquik commented
Will they induce notable amounts of lag?

2022-10-17 14:38 UTC, BraveMole commented
> Will they induce notable amounts of lag?

It is just a minion

2022-10-17 21:32 UTC, TiviPlus requested changes

2022-10-17 21:32 UTC, TiviPlus commented on code/modules/xenomorph/xeno_structures.dm
> +	SSspawning.spawnerdata[src].max_allowed_mobs = max(1, MAX_SPAWNABLE_MOB_PER_PLAYER * SSmonitor.maximum_connected_players_count * 2)
why arent these args?

2022-10-18 06:11 UTC, lKiseki commented
I have come to make an announcement. They've taken us for fools, brothers and sisters.
![image](https://user-images.githubusercontent.com/59634950/196349291-21e1cb5f-b2b6-44b1-a92b-9c3eac849403.png)
Do you find this cute? Do you truly think this is CUTE?

![image](https://user-images.githubusercontent.com/59634950/196349393-be87d36c-c2fa-4ffb-a451-d3dcb591ceca.png)
DOES THIS LOOK LIKE THE FACE OF MERCY TO YOU?

2022-10-18 16:15 UTC, Kuro020 approved these changes

2022-10-20 07:06 UTC, Oscari-pog commented
Those are whole fucking ants man I thought it was gonna be like cute lil' mini benos

2022-10-20 18:11 UTC, BraveMole commented
> Those are whole fucking ants man I thought it was gonna be like cute lil' mini benos

They are cute shutup

2022-11-01 01:10 UTC, closed without merging