SADAR Changes, Has Aim Mode, added 'Dumbfire' HE/WP rocket types, Reworked AP, doubled Req rocket amounts.
tgstation/TerraGov-Marine-Corps pull request #11290
Opened 2022-10-18 03:50 UTC by Pariah919

## About The Pull Request
Dumbfire Rockets
-
Dumbfire rockets in general have a higher payload, act like LE rockets from RR but cannot be aimed precisely and have lowered damage (But not sunder for now, might be changed.).

HE has 7 heavy/light payload, 50 damage.

WP has 7 effect radius rather than 3.

AP Rocket
-
Redubbed a kinetic penetrator since LOSAT is the coolest shit ever, also so the .5 falloff makes any sense.

It has no sunder anymore.
It does 40 more damage, which is enough to just about make most castes have a very bad day with 360 total damage.
Rasied pen to 200 to emphasize whatever gets hit with this is going to have a *very, very bad day*.

Rockets in general
-
Redid their names, LG is laser guided (old rockets). 'Dumbfire' is new LE styled rockets, they go until they hit something,.
Req now gives you 2 rockets per crate, rather than one. Sole exception is AP rockets which are slightly cheaper as they no longer remove armor at all.

Aim Mode
-
4 seconds in total from no wield to aim mode.
4 slowdown in total.

## Why It's Good For The Game
Makes the SADAR into a true bunker buster, with AP rockets being your xeno removal wonder but having absolutely no sunder if the xenomorph doesn't die, which makes it less punishing to get hit and survive.

Aim mode makes the Miniscopeless SADAR much more useable, and allows for more dynamic use of it with the newly added dumbfire rockets.

Dumbfire rockets should allow for more unique use of the SADAR itself and busting defenses with it, while Laser-Guided rockets have old style SADAR of precision application of hurt rather than total destruction.

AP now works like the high-end hurt machine it should be, but it no longer punishes with insanely high sunder, use LG HE for that.

## Changelog
:cl:
balance: SADAR Rework- Has Aim mode (1.4 seconds to aim.) Dumbfire rockets that go past your clicks added, they have a much higher payload compared to normal rockets, AP rocket reworked from 325Dam/150Pen/100Sunder to 360Dam/200Pen/0Sunder.
balance: Rocket amounts from req doubled, aside from AP rockets which cost one less from 6 to 5.
/:cl:

2022-10-18 04:04 UTC, novaepee commented
>SADAR
>aim mode
>what

2022-10-18 04:24 UTC, Lumipharon requested changes

2022-10-18 04:24 UTC, Lumipharon commented on code/modules/projectiles/ammo_datums.dm
> +	explosion(T, 0, 7, 7, 2)
```suggestion
	explosion(T, 0, 7, 0, 2)
```
Makes it clearer what its actual effect is. Also fucking huge heavy explosion.

2022-10-18 04:24 UTC, Lumipharon commented on code/modules/projectiles/magazines/specialist.dm
> +	icon_state = "wp_rocket"
```suggestion
```
It already inherits this, no need to specify it gain

2022-10-18 04:24 UTC, Lumipharon commented on code/modules/projectiles/ammo_datums.dm
> +	effect_radius = 7
I can smell the salt already.

2022-10-18 04:52 UTC, lKiseki commented
This is one heck of a powercreep PR if I've ever seen one.
Let's go down the list, I suppose.

## General changes
- You gave SADAR aim mode. I'm not going to elaborate on this one, and all I will ask is: _Why?_
- You doubled the amount of rockets gained in requisitions orders. except for AP, which is instead 1 point cheaper. Very much unnecessary, and hardly justified, given what I'm looking at.

## AP rocket
Does no sunder now. Alright, cool... _But,_ here's the catch, which makes it even worse than before: **320 damage increased to 360**, and **150 penetration raised to 200**, as if the previous value wasn't already enough to skip armor entirely.
0.5 damage falloff is practically meaningless -- after 6 tiles traveled, that's 3 less damage. It would have to travel 80 tiles to go down to the previous value of 320, which was already very high by xeno health standards.
So with that in mind, let's take a look at the implications of these changes:
- Instantly kills Runners and Wraiths, **skipping crit.** Yes, this does so much damage that they just die.
- Will knock the following castes **straight into crit**: Drones, Sentinels, Defenders, Hunters, Bulls, Warriors, Hivelords, Carriers, and Boilers.
- The following castes **barely survive**: Widow, Praetorian (they have EXACTLY 360 HP at ancient, so this puts them at 0), Defiler, Crusher, Gorger, Queen, Shrike, and King.

You're not gonna be caring much about the sunder when you've been instantly knocked into crit, are you?
Oh, right. I'd like to mention this: this was tested using Ancient xeno health values.
May God have mercy on you if you run into this before Ancient.

## Dumbfire rockets
New rocket type that, instead of detonating on the tile you target and/or being limited in range to your screen, has 20 range and will detonate when it hits something. Has 50 damage on a direct hit, which is pretty bad. The catch? **Ignites on a direct hit, 7 tiles of heavy and light explosion.** High friendly fire potential.
AND, as if that weren't enough? **It deals 100 sunder.** I double checked this on local. I'm hoping it's an unintended side effect of giving it `AMMO_SUNDERING` and not replacing the `sundering = 100` from its parent type.
If it isn't, this just makes it into a way better HE rocket. Full sunder, incendiary, _and_ a big heavy explosion, all wrapped into one neat package, just for you.

## Concluding thoughts
**Massive powercreep**. I have no better words to describe it.
AP rockets have pointless changes that only make it much more worse to deal with it.
Dumbfire rockets are just better HE rockets.
Aim mode (_why?_)

Needless to say, I heavily disapprove of this PR as a whole.

2022-10-18 05:33 UTC, Oscari-pog commented
Straight up just a massive buff worded in a way that tries to make it seem like it has downsides

2022-10-18 08:56 UTC, iLikeMemes commented
I smell a marine main.

2022-10-18 11:03 UTC, MereWalker commented
Not a fan of these changes. To make sadar used again miniscope would be the way to go. That isn't the world we live in anymore. May as well scrape the pr alone with the sadar.

2022-10-18 12:08 UTC, Naaanii commented
Let's go.

2022-10-18 15:22 UTC, TiviPlus commented
Aimmode hard no
AP rocket undecided
dumb rocket yes
doubling rocket count no

2022-10-18 16:02 UTC, Araulius commented
Just PB the xenos with your rocket bro. It's not hard.  AP has no splash.

2022-10-18 18:33 UTC, Losenis commented
>Instantly kills Runners and Wraiths

Speedmerge, fuck those fucking fuckers

2022-10-19 03:06 UTC, Al-1ce commented
You have to pick between wanting these to be a common and free thing from roundstart intended to be a finisher, or something rare and expensive that can turn a rouny into red paste in an instant. Both are valid options. Minding the aim mode, this PR actually seems to fix the problem of SADARs being more or less useless.

2022-10-19 03:13 UTC, Al-1ce commented
SADAR's have existed in a sort of grey-zone for a long time now. It seems we can't really decide weather or not we want these to be powerful and punishing, or weak and easy to shrug off. You can't find an even middle ground for a rocket launcher. It has to be one extreme or the other. Completely useful, albeit rare and expensive -- or situationally useless and free from roundstart.

Honestly? I'd rather this than the current state of things. SADARs should be costly and rare at the expensive of being much more threatening. 

With all of that said, aim-mode on an RPG is silly and isn't present in grenade launchers for a reason.

2022-10-19 03:14 UTC, Al-1ce commented
SADAR's have existed in a sort of grey-zone for a long time now. It seems we can't really decide weather or not we want these to be powerful and punishing, or weak and easy to shrug off. You can't find an even middle ground for a rocket launcher. It has to be one extreme or the other. Completely useful, albeit rare and expensive -- or situationally useless and free from roundstart.

Honestly? I'd rather this than the current state of things.

2022-10-19 12:44 UTC, Naaanii commented
Make each shell 20 points too to compensate.

2022-10-19 16:00 UTC, BraveMole requested changes

2022-10-19 16:00 UTC, BraveMole commented on code/modules/projectiles/ammo_datums.dm
> +	effect_radius = 7
Wow no

2022-10-19 16:00 UTC, BraveMole commented on code/modules/projectiles/ammo_datums.dm
> +/datum/ammo/rocket/wp/dumbfire
what the hell is that name

2022-10-19 16:00 UTC, BraveMole commented on code/modules/projectiles/magazines/specialist.dm
> +/obj/item/ammo_magazine/rocket/sadar/dumb
Find another name than dumb. Unguided ?

2022-10-19 16:00 UTC, BraveMole commented on code/modules/reqs/supplypacks.dm
> +/datum/supply_packs/weapons/rpg_wp_dumb
no

2022-10-19 16:00 UTC, BraveMole commented on code/modules/reqs/supplypacks.dm
> +/datum/supply_packs/weapons/rpg_regular_dumb
no doubling

2022-10-19 16:00 UTC, BraveMole commented on code/modules/projectiles/ammo_datums.dm
> +	explosion(T, 0, 7, 0, 2)
You are mixing datums order here. do all parent rocket stuff then define children

2022-10-19 16:00 UTC, BraveMole commented on code/modules/projectiles/ammo_datums.dm
> +	damage = 50
50 damage, instead of 200 ...?

2022-10-20 06:18 UTC, Al-1ce commented
> Make each shell 20 points too to compensate.

The rocket launcher itself is currently free, so this is a good compromise. Maybe somewhere around 10-15 will be better for the long-term once we see how this works through testing.

2022-10-20 23:04 UTC, Al-1ce commented
> The SADAR is free? When did that happened.

T-160s can be found in the 'Specialized' tab of the marine equipment vendor in limited quantities. Always have been.

2022-10-20 23:40 UTC, Lumipharon commented
> > The SADAR is free? When did that happened.
> 
> T-160s can be found in the 'Specialized' tab of the marine equipment vendor in limited quantities. Always have been.

that ain't a sadar.

2022-10-21 00:58 UTC, Naaanii commented
> > Make each shell 20 points too to compensate.
> 
> The rocket launcher itself is currently free, so this is a good compromise. Maybe somewhere around 10-15 will be better for the long-term once we see how this works through testing.

It's not. Recoiless Rifle is free which is the T-160.
SADAR is the big brother of the RR that's 120 points.

2022-10-22 17:36 UTC, comfyorange commented
#### Test Merge Deployed

##### Server Instance
TGMC

##### Merged By
naaanii

##### Revision
Origin: af73cb5a187ee4479e42fb50efc36e8fbcfdfc30
Pull Request: 74857997a38efc10d283630bd7832f99e37ca697
Server: a82a7b9a2e34a0152938b45c435209b017c35eac

##### Comment

[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

2022-10-22 17:39 UTC, comfyorange commented
#### Test Merge Updated

##### Server Instance
TGMC

##### Merged By
Tiviplus

##### Revision
Origin: af73cb5a187ee4479e42fb50efc36e8fbcfdfc30
Pull Request: 74857997a38efc10d283630bd7832f99e37ca697
Server: 2592483a876e876dcb90a7aa0c54b0fa595184c4

##### Comment

2022-10-22 19:55 UTC, zzurge commented
id like to say that i literally almost never see the sadar deployed...like at all anymore, people dont buy it,its even more expensive than the gamer shotgun

2022-10-23 10:11 UTC, Starfirejordan commented
Test AP, insta crits majority of xenos and i mean criting near death not entered crit, and gibs almost any xeno that isnt past mature
just.. put AP back to how it was, dont make AP a butt fuck rocket

2022-10-23 17:13 UTC, Goblinu commented
> id like to say that i literally almost never see the sadar deployed...like at all anymore, people dont buy it,its even more expensive than the gamer shotgun

As someone who frequently see's SADARS deployed, being on the revieving end of one is the least enjoyable thing in the game. To be instacritted by a single shot is just fun when youre a t3

2022-10-23 17:43 UTC, Araulius commented
throwing this out there. Consider a rocket type that does medium damage, but giga slowdown.

2022-10-23 18:25 UTC, Al-1ce commented
>SADAR/whatever

Guh. Not sure why I was thinking of the T-160. My previous points still stand.

2022-10-24 05:52 UTC, comfyorange commented
#### Test Merge Updated

##### Server Instance
TGMC

##### Merged By
Lewdcifer

##### Revision
Origin: af73cb5a187ee4479e42fb50efc36e8fbcfdfc30
Pull Request: 74857997a38efc10d283630bd7832f99e37ca697
Server: 99de39021678299d1ff1c63ce1c4f70ed66a98d9

##### Comment

2022-10-24 19:42 UTC, comfyorange commented
#### Test Merge Updated

##### Server Instance
TGMC

##### Merged By
Tiviplus

##### Revision
Origin: 1a0d30d9b48151b309e3ce11f7ab98481c77c9a9
Pull Request: 74857997a38efc10d283630bd7832f99e37ca697
Server: 7adad29020eeb4be86efb0ddff82c4d7eb2491b2

##### Comment

[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

2022-10-25 19:29 UTC, comfyorange commented
#### Test Merge Updated

##### Server Instance
TGMC

##### Merged By
Lewdcifer

##### Revision
Origin: ba11e493e0e54387094b1aee3f723c962e51dc58
Pull Request: 74857997a38efc10d283630bd7832f99e37ca697
Server: 1c1e4b98bed5b49a08101b5d08554feba05f2f0b

##### Comment

[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

2022-10-27 15:36 UTC, comfyorange commented
#### Test Merge Updated

##### Server Instance
TGMC

##### Merged By
Lewdcifer

##### Revision
Origin: de3c2c8ebf8e37758d277c25b7907d8059064f00
Pull Request: 74857997a38efc10d283630bd7832f99e37ca697
Server: 54f6b1801c5e375491da3123d1bedf3c5c653b16

##### Comment

[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

2022-10-29 00:56 UTC, comfyorange commented
#### Test Merge Updated

##### Server Instance
TGMC

##### Merged By
Lewdcifer

##### Revision
Origin: 74ddc18f3425d2a813310b95d0a2e0f96909bce9
Pull Request: 74857997a38efc10d283630bd7832f99e37ca697
Server: 0630093ff9a7e29366983fccc1d30b0735259a83

##### Comment

2022-10-31 18:13 UTC, comfyorange commented
#### Test Merge Removed

2022-11-18 00:56 UTC, closed without merging