Resprites glass windows and windoors, makes them 3/4ths compliant
tgstation/TerraGov-Marine-Corps pull request #11304
Opened 2022-10-20 01:33 UTC by RipGrayson

## About The Pull Request

Title.
I did the windows myself, the windoor sprites are by https://github.com/aGhostCoder, with some minor adjustments.

## Why It's Good For The Game

No longer will TGMC have to feel envy when we look at CM and see their shiny 3/4ths wall sprites, no longer will other servers look down and laugh at us for not having correct perspective on our wall objects! I will personally strangle any and all incorrect perspective sprites so hard their original spriters will feel my fury from 1000 servers away!

## Changelog
:cl:
imageadd: Created new versions of the glass window sprites, implements some windoor sprites from another artist (see the PR for details).
imagedel: Removed some old glass window sprites.
/:cl:

2022-10-20 08:56 UTC, lbnesquik commented
The soul....

2022-10-20 13:01 UTC, RipGrayson commented
> The soul....

Soul is secondary to eliminating the 1 dimensional eyesores this codebase got from CM.

2022-10-20 15:52 UTC, Kuro020 commented
> The soul....

I hate soul

2022-10-20 15:52 UTC, Kuro020 approved these changes

2022-10-21 20:09 UTC, TiviPlus requested changes

2022-10-21 20:09 UTC, TiviPlus commented on code/game/objects/machinery/doors/windowdoor.dm
> +	if(dir == 1)
use NORTH pls

2022-10-21 20:09 UTC, TiviPlus commented on code/game/objects/structures/window.dm
> +	var/tinted = FALSE
```suggestion
	///are we tinted or not
	var/tinted = FALSE
```

2022-10-21 20:09 UTC, TiviPlus commented on code/game/objects/structures/window.dm
> +	if(dir == 1)
ditto

2022-10-21 20:09 UTC, TiviPlus commented on code/game/objects/structures/window.dm
> +	if(dir == 8 || dir == 4)
ok in general please change all the dir checks to use the defines pls

2022-10-21 20:09 UTC, TiviPlus commented on code/game/objects/structures/window.dm
> +			add_overlay(image(icon, "windowstake", layer = ABOVE_ALL_MOB_LAYER))
```suggestion
		if(tinted)
			add_overlay(image(icon, "twindowstake", layer = ABOVE_ALL_MOB_LAYER))
			return
		add_overlay(image(icon, "windowstake", layer = ABOVE_ALL_MOB_LAYER))
```

2022-10-22 20:02 UTC, TiviPlus requested changes

2022-10-22 20:02 UTC, TiviPlus commented on code/game/objects/machinery/doors/windowdoor.dm
> +	if(dir == 1)
still pending

2022-10-22 20:09 UTC, TiviPlus approved these changes

2022-10-22 20:19 UTC, merged