Help intent clicking starts removing huggers
tgstation/TerraGov-Marine-Corps pull request #11300
Opened 2022-10-19 13:04 UTC by Jordanstolethepreciousslam

## About The Pull Request
Clicking on human with empty hand will now start removing hugger from their face if they have one. This has lower priority than putting out fire so hilarity ensues.
## Why It's Good For The Game
Removing huggers is a pain in ass. You need to drag victim's sprite onto yourself then click the corresponding item slot and THEN you start removing it. I do not consider it to be a balance change for two main reasons
1. Removing huggers with hands is a noob trap that put's two marines out of combat for at least 4 seconds and will not work out if anybody shuffles them. Removing huggers with fire is the most reliable option to deal with them.
2. Abilities should not be balanced by janky, user unfriendly interfaces. Hugger removal time can be increased if needed, but not the complexity of controls.
## Changelog
:cl:
qol: huggers can now be removed without using equip menu
/:cl:

2022-10-19 15:11 UTC, Licherr commented
![image](https://user-images.githubusercontent.com/47250417/196731320-b6422a34-4395-4d3a-b462-dbeb07db03bf.png)

2022-10-19 15:52 UTC, BraveMole requested changes

2022-10-19 15:52 UTC, BraveMole commented on code/modules/mob/living/carbon/human/human_attackhand.dm
> +			if(istype(src.wear_mask, /obj/item/clothing/mask/facehugger) && H != src)
```suggestion
			if(istype(wear_mask, /obj/item/clothing/mask/facehugger) && H != src)
```

2022-10-19 15:52 UTC, BraveMole commented on code/modules/mob/living/carbon/human/human_attackhand.dm
> +				H.stripPanelUnequip(src.wear_mask, src, SLOT_WEAR_MASK)
```suggestion
				H.stripPanelUnequip(wear_mask, src, SLOT_WEAR_MASK)
```

2022-10-19 15:55 UTC, Jordanstolethepreciousslam commented on code/modules/mob/living/carbon/human/human_attackhand.dm
> +				H.stripPanelUnequip(src.wear_mask, src, SLOT_WEAR_MASK)
Done

2022-10-20 08:53 UTC, lbnesquik commented
17 thumbs in less than a day. Speed merge.

2022-10-20 18:41 UTC, merged