Fix deltatime
tgstation/TerraGov-Marine-Corps pull request #11313
Opened 2022-10-20 20:30 UTC by TiviPlus

Spooky didnt implement it properly now it is

2022-10-22 22:05 UTC, BraveMole requested changes
It is still stupid between tg and tgmc right ? Cannot you fix that ?

2022-10-24 22:22 UTC, TiviPlus commented
Isnt that what i fixed

2022-10-24 22:22 UTC, TiviPlus commented
or wdym

2022-10-27 23:29 UTC, Lumipharon approved these changes

2022-10-27 23:32 UTC, merged