Closet destruction
tgstation/TerraGov-Marine-Corps pull request #11334
Opened 2022-10-23 14:17 UTC by SiegeB0t

## About The Pull Request
Explosions and plasma cutters now release the contents of a locker.

## Why It's Good For The Game
Punishes bad grenade placement.
Makes locker/explosive interactions more interesting.
Prevents PC users from qdeleting their cowardly comrades hiding in lockers.

## Changelog
:cl:
balance: Makes unlocked lockers/crates more vulnerable to explosions.
fix: Plasma cutter now deconstructs objects rather than simply deleting them. 
/:cl:

2022-10-23 14:57 UTC, Losenis commented
Make it so that it also applies to acid, xenos can delete the entirety of a locker's contents by acid in the same way.

2022-10-24 02:35 UTC, Naaanii commented
Crates having this would also be nice.

2022-10-24 04:42 UTC, SiegeB0t commented
This applies to crates as well. "About The Pull Request" updated.

2022-10-26 10:04 UTC, Lumipharon requested changes

2022-10-26 21:20 UTC, SiegeB0t commented on code/game/objects/structures/crates_lockers/closets.dm
> +			contents_explosion(EXPLODE_HEAVY)
I thought it would be funny but I have no justification for it. so...

2022-10-27 08:53 UTC, TiviPlus approved these changes

2022-10-28 00:20 UTC, Lumipharon approved these changes

2022-10-28 00:20 UTC, merged