Orbit UI rework: Adds icons, health bars, better view.
tgstation/TerraGov-Marine-Corps pull request #11338
Opened 2022-10-24 00:02 UTC by jlsnow301

## About The Pull Request
Reworks the orbit UI to be quite a bit more interactive. Could probably use TM'd, it's hard to test every icon and case.

![Screenshot 2022-10-23 165540](https://user-images.githubusercontent.com/42397676/197424742-a51eb115-214b-4c53-9c4a-eb489dd216d2.png)

## Why It's Good For The Game
Better observer experience. Adds funny names, icons, health bars.

## Changelog
:cl:
qol: Reworks the Orbit UI to be much more interactive. Colors buttons on health, collapsible sections, job icons, and more.
/:cl:

2022-10-24 00:17 UTC, Lumipharon commented
Nice

2022-10-25 09:16 UTC, TiviPlus requested changes
Ui is very nice

2022-10-25 09:16 UTC, TiviPlus commented on code/modules/mob/dead/observer/orbit.dm
> +				serialized["icon"] = icon2base64(orbit_icon)
This seems very wasteful, couldnt you just cache this easily?

2022-10-25 17:10 UTC, lKiseki commented
Beautiful update, love what you did here.

Just here to report a bug, though;
![image](https://user-images.githubusercontent.com/59634950/197838332-f5024ae8-92a9-4145-9147-9945f68434c7.png)
There's currently a bug where the orbit UI will show all of these icons in the Marines tab.

2022-10-25 17:36 UTC, jlsnow301 commented
There's currently a bug where the orbit UI will show all of these icons in the Marines tab.

lol, nice, on it right now

2022-10-25 19:20 UTC, comfyorange commented
#### Test Merge Removed

2022-10-25 21:36 UTC, jlsnow301 commented
Should be safe to put on TM again.

2022-10-26 11:41 UTC, Edelor68 commented
Does this fix #11049?

2022-10-26 16:47 UTC, jlsnow301 commented
> Does this fix #11049?

i don't think so, the underlying issue there seems that they get categorized as NPCs or something (mind == null). 
i will test it and report the results.

2022-10-29 00:48 UTC, XSlayer300 commented
Disabling Auto-observe does not unobserve the selected target. Whereas before, you disable auto-observe to disable spectating the person and their inventory.

You can still disable spectating the person by orbiting another target while auto-observe is off, which is weird.

2022-10-29 00:56 UTC, comfyorange commented
#### Test Merge Updated

##### Server Instance
TGMC

##### Merged By
Lewdcifer

##### Revision
Origin: 74ddc18f3425d2a813310b95d0a2e0f96909bce9
Pull Request: e3d723deb37eb08ac9d44567914a3a87023f4f1b
Server: 0630093ff9a7e29366983fccc1d30b0735259a83

##### Comment

2022-10-29 02:04 UTC, jlsnow301 commented
> You can still disable spectating the person by orbiting another target while auto-observe is off, which is weird.

I turned it to a client state, I'm not totally against just reverting this to fix it (I just don't like server states)

2022-10-31 18:13 UTC, comfyorange commented
#### Test Merge Removed

2022-10-31 20:34 UTC, TiviPlus approved these changes

2022-10-31 20:34 UTC, merged