Corrects Sulaco having regular tables/chairs
tgstation/TerraGov-Marine-Corps pull request #11350
Opened 2022-10-25 18:15 UTC by RipGrayson

no more having fun by deconstructing tables/chairs roundstart to get a huge advantage over xenos

## About The Pull Request

Apparently I missed this map when doing https://github.com/tgstation/TerraGov-Marine-Corps/pull/10248, while I was fixing that oversight I also changed tables so you can't game them by deconstructing them into parts and then turning the parts into metal.

I also removed a random check that existed to prevent building in a hangar.

## Why It's Good For The Game

Oversights bad, it needs done because apparently it's becoming an issue again.

## Changelog
:cl:
balance: You can no longer deconstruct Sulaco's tables and chairs for metal.
fix: Fixed an oversight where you could deconstruct tables for parts, then parts for metal.
/:cl:

2022-10-25 20:13 UTC, Derrick2Electricboogaloo commented
Stop taking away STs ability to recycle to get metal, it is lame.

2022-10-25 20:15 UTC, Derrick2Electricboogaloo commented
I just noticed the "It is an issue again" who? Who is making it an issue, have you actually observed rounds on Sulaco for scraping? I can tell you it does not happen, and if it does. You do not get that much metal from the tables anyways. You took away chairs already. In fact recycling on the other ships really does not happen often, if ever. Observe and see. You will probably go atleast 10 rounds+ without seeing it. All I am sensing is xeno cope. Not realizing metal is not expensive to buy, when they feed us points.

2022-10-25 20:23 UTC, RipGrayson commented
> Stop taking away STs ability to recycle to get metal, it is lame.

There's no point in turning this PR into a battleground over an already done balance change. Whatever debate there was over this was finished when https://github.com/tgstation/TerraGov-Marine-Corps/pull/10248 was merged. 

At this point it's a consistency thing, no point in doing just some of the ships.

If you want to revert those changes, feel free to open a PR and argue it to the other maintainers. I'm merely enforcing standardization across ships and will not respond further any further to arguments carried over from the previous PR.

2022-10-27 02:40 UTC, Lumipharon commented
Can you still just chuck the parts into an autolathe to get the metal that way?

2022-10-27 08:52 UTC, TiviPlus requested changes

2022-10-27 08:52 UTC, TiviPlus commented on code/game/objects/items/frames/table_rack.dm
> +	var/dropmetal_on_deconstruct = TRUE
couldnt you just deconstruct_type = null on the child and check if deconstruct_type exists instead?

2022-10-28 19:52 UTC, TiviPlus requested changes

2022-10-28 19:52 UTC, TiviPlus commented on code/game/objects/items/frames/table_rack.dm
> +	if(iswrench(I) && !(deconstruct_type == null))
```suggestion
	if(iswrench(I) && deconstruct_type))
```

2022-10-30 11:49 UTC, merged