Hod head module
tgstation/TerraGov-Marine-Corps pull request #11359
Opened 2022-10-26 06:02 UTC by Pariah919

## About The Pull Request
Literally what it says on the tin.
Sprite by me.

## Why It's Good For The Game
People wanted it, I suppose.

## Changelog
:cl:
add: Hod Head module has been added as a counterpart of the Hod chestpiece module
/:cl:

2022-10-26 06:13 UTC, QualityVan commented
Should put it down with the hod body instead of lumped inside tyr.

2022-10-26 13:22 UTC, Losenis commented
Speedmerge

2022-10-26 13:30 UTC, XSlayer300 commented on code/modules/clothing/modular_armor/attachments/modules.dm
> +	name = "Hod Helmet System"
```suggestion
	name = "\improper Hod Helmet System"
```

2022-10-26 13:31 UTC, XSlayer300 commented on code/modules/clothing/modular_armor/attachments/modules.dm
> +	desc = "Designed for mounting on a modular helmet. When attached, this system provides substantial resistance to most gunshot wounds by providng high internal padding within the helmets structure."
```suggestion
	desc = "Designed for mounting on a modular helmet. When attached, this system provides substantial resistance to most gunshot wounds by providing high internal padding within the helmet's structure."
```

2022-10-27 02:38 UTC, Lumipharon requested changes
Also yeah, move it under the main hod attachment

2022-10-27 02:38 UTC, Lumipharon commented on code/modules/clothing/modular_armor/attachments/modules.dm
> +	icon_state = "mod_ff"
Make a new item sprite. mimir hat is basically just a cropped mimir suit, so you can do the same.

2022-10-30 11:53 UTC, Al-1ce commented
> Show sprite aaaaugh

Click the thing that says 'checks' and look for IconDiff.

2022-10-31 19:58 UTC, bowlofcereal commented
the fact that we need this speaks volumes of marine skill issue

2022-11-04 17:18 UTC, TiviPlus approved these changes

2022-11-05 00:00 UTC, Lumipharon commented
whoops, meant to merge this.

2022-11-05 00:00 UTC, merged

2022-11-05 00:16 UTC, Losenis commented
LETS FUCKING GOOOO

2022-11-05 03:28 UTC, QualityVan commented
Still haven't actually moved the helmet code to be down with the chest module.