SOM machinegun
tgstation/TerraGov-Marine-Corps pull request #11375
Opened 2022-10-29 12:44 UTC by Lumipharon

## About The Pull Request
Adds the V-41 general machine gun to the SOM arsenal.
Its basically a MG-60 equivilent, but with slightly strong damage per bullet at the cost of lower ROF and bullets per mag.

Shout out to Crow for the great sprites.

![image](https://user-images.githubusercontent.com/7869430/198832173-5881ad94-1c1a-4778-8d45-3f7da80f177a.png)

It's not a spectacular gun or anything, but adds more variety for the SOM, and in particular for sensor cap may come in handy for defence.

## Why It's Good For The Game
More SOM dakka good

## Changelog
:cl:
add: Added the V-41 machine gun for the SOM
/:cl:

2022-10-29 18:14 UTC, Mannybrado commented
ADD AIM MODE FOR IT PLEASE THANKS :D

2022-10-29 22:57 UTC, XSlayer300 commented on code/datums/quick_load_outfits.dm
> +	name = "V-41 Rifleman"
```suggestion
	name = "V-41 Machinegunner"
```

2022-10-29 23:03 UTC, XSlayer300 commented
also, V-41 guys do not have mesons or something, intentional?

2022-10-29 23:29 UTC, Lumipharon commented
> also, V-41 guys do not have mesons or something, intentional?

Yeah, just the vets (and actual engies) that have em.

2022-10-29 23:30 UTC, Lumipharon commented
> ADD AIM MODE FOR IT PLEASE THANKS :D

It has it yes

2022-10-30 12:06 UTC, TiviPlus requested changes

2022-10-30 12:06 UTC, TiviPlus commented on code/modules/projectiles/gun_attachables.dm
> +/obj/item/attachable/stock/v41stock
no numbers in typepaths

2022-10-30 12:57 UTC, Lumipharon commented on code/modules/projectiles/gun_attachables.dm
> +/obj/item/attachable/stock/v41stock
whoops

2022-10-30 13:34 UTC, merged