Decreases jab blur
tgstation/TerraGov-Marine-Corps pull request #11370
Opened 2022-10-28 00:10 UTC by Losenis

## About The Pull Request

Warrior primo jab will no longer blur you for so long it can stack with itself or others

## Why It's Good For The Game
Turns out that it lasts for long enough that it can actually stack with itself/other warrior punches and effectively blind you harder than having actual proper eye damage which is pretty absurd. Lowers it to a third of its duration so that while it still impacts the fight the warrior is in it wont last for centuries after the warrior runs. It was purely cosmetic anyway since you can tell that the big purple thing is a xeno to shoot at.

## Changelog
:cl:
balance: Primordial warrior's blind duration lowered.
/:cl:

2022-10-28 00:13 UTC, FIXTHERADBOXPLEASE commented
Salt PR?

2022-10-28 00:27 UTC, Lumipharon commented
How many warriors are chain jabbing you to actually make blur matter? And how are you not dead before it matters except for like, heavy tyr + shield?

2022-10-28 06:53 UTC, Al-1ce commented
Your reasoning seems heavily situational and reliant on exceptions.

2022-10-28 10:50 UTC, DerpiestBruh commented
sus

2022-10-29 14:20 UTC, Dgeen commented
You wrote that you reduce the blur. But in fact, you also reduce the blinding. Misleading is not very good, do you know that? Although I don't know why to describe something in a typical salt pr

2022-10-29 14:50 UTC, Losenis commented
I lowered the visual effects overall by a third. Instead of being condescending and accusing of malice you could've just said "hey maybe keep the blinding aspect" and I'd have done so without problem.

2022-10-30 01:19 UTC, ivanmixo commented
People have a shitfit whenever you try to touch anything about warrior, so.

2022-10-30 11:48 UTC, TiviPlus requested changes
If your problem is the stacking then why not use a max?

2022-11-10 00:56 UTC, closed without merging

2022-11-10 11:34 UTC, Naaanii commented
You can also reduce the duration within Imi which is funny.