Fixes hivemind breaking hive status and chat and fixes hivemind core getting killed upon hijack
tgstation/TerraGov-Marine-Corps pull request #11398
Opened 2022-10-31 20:41 UTC by ivanmixo

## About The Pull Request

Fixes hivemind breaking hive status and chat and fixes hivemind core getting killed upon hijack. Bit messy, but the whole hivemind file is very messy and I don't feel like refactoring it.

## Why It's Good For The Game

Bugs that severely gimp the xenos bad. Hivemind core getting destroyed on hijack was not intended.

## Changelog
:cl:
fix: Fixed hivemind breaking hive status and chat and fixes hivemind core getting killed upon hijack
/:cl:

2022-11-01 19:54 UTC, TiviPlus approved these changes

2022-11-02 11:36 UTC, Lumipharon requested changes

2022-11-02 11:36 UTC, Lumipharon commented on code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
> +	xeno_structure_flags = CRITICAL_STRUCTURE | DEPART_DESTRUCTION_IMMUNE
```suggestion
	xeno_structure_flags = CRITICAL_STRUCTURE|DEPART_DESTRUCTION_IMMUNE
```

2022-11-02 14:04 UTC, ivanmixo commented on code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
> +	xeno_structure_flags = CRITICAL_STRUCTURE | DEPART_DESTRUCTION_IMMUNE
really

2022-11-03 04:45 UTC, vilereaver41 commented
hivemind was causing this? omfg iv been blaming admins

2022-11-03 21:41 UTC, merged