Mech Repair Now Fumbles
tgstation/TerraGov-Marine-Corps pull request #11419
Opened 2022-11-01 19:37 UTC by Ben10083

## About The Pull Request
Mech Repairs now have a skill check, failing it leads to fumble.

## Why It's Good For The Game
I am an undercover agent dispatched by the xeno mains to nerf all fun marines have, I will now be making it so the private can't repair the mech as easily as the synth. 

## Changelog
:cl:
balance: Fumble added to mech repairs.
/:cl:

2022-11-01 21:24 UTC, TiviPlus requested changes

2022-11-01 21:24 UTC, TiviPlus commented on code/modules/vehicles/mecha/mecha_defense.dm
> +			return
```suggestion
		if(!do_after(user, 30 * (SKILL_ENGINEER_ENGI - skill), TRUE, user, BUSY_ICON_UNSKILLED))
			return
```

2022-11-01 21:57 UTC, Ben10083 commented
Talked with Tivi over discord, fumble time is now 30 ticks and fumble occur for each repair.

2022-11-02 18:16 UTC, TiviPlus requested changes

2022-11-02 18:16 UTC, TiviPlus commented on code/modules/vehicles/mecha/mecha_defense.dm
> +			if(!do_after(user, 30 * (SKILL_ENGINEER_ENGI - skill), TRUE, user, BUSY_ICON_UNSKILLED)) //repeat for different text for ongoing repairs
```suggestion
	var/skill = user.skills.getRating("engineer")
	while(obj_integrity < max_integrity)
		if(skill < SKILL_ENGINEER_ENGI)
			user.visible_message(span_notice("[user] fumbles around figuring out how to repair [src]."),
			span_notice("You fumble around figuring out how to repair [src]."))
			if(!do_after(user, 30 * (SKILL_ENGINEER_ENGI - skill), TRUE, user, BUSY_ICON_UNSKILLED))
```

2022-11-02 18:25 UTC, TiviPlus commented on code/modules/vehicles/mecha/mecha_defense.dm
> +			span_notice("You fumble around figuring out how to repair [src]."))
use a balloon alert instead

2022-11-02 18:25 UTC, TiviPlus approved these changes
Rest fine

2022-11-03 17:23 UTC, TiviPlus requested changes
Since balloon alerts are onmap they should be short which means no name inserts usually

2022-11-03 17:23 UTC, TiviPlus commented on code/modules/vehicles/mecha/mecha_defense.dm
> +			user.balloon_alert_to_viewers("[user] fumbles around figuring out how to repair [src].")
```suggestion
			user.balloon_alert_to_viewers("fumbles around trying to repair")
```

2022-11-03 17:23 UTC, TiviPlus commented on code/modules/vehicles/mecha/mecha_defense.dm
> +			user.balloon_alert_to_viewers("started welding [src]", "started repairing [src]")
```suggestion
			user.balloon_alert_to_viewers("started welding", "started repairing")
```

2022-11-03 21:30 UTC, merged