Mech Pilot Job Slots
tgstation/TerraGov-Marine-Corps pull request #11421
Opened 2022-11-01 20:08 UTC by Ben10083

## About The Pull Request
Mech pilot slots now scale like synths, every 40 marine pop is +1 pilot.

## Why It's Good For The Game
Scaling is good, people wanted this and admins and currently brute forcing this change.

## Changelog
:cl:
add: Mech Pilot slots now scale like Synthetic slots.
/:cl:

2022-11-04 16:59 UTC, TiviPlus requested changes

2022-11-04 16:59 UTC, TiviPlus commented on code/datums/jobs/job/marines.dm
> +		/datum/job/terragov/command/mech_pilot = SYNTH_POINTS_REGULAR,
dont use the synth define for mp

2022-11-04 16:59 UTC, TiviPlus commented on code/datums/jobs/job/marines.dm
> +	jobworth = list(/datum/job/xenomorph = LARVA_POINTS_REGULAR, /datum/job/terragov/squad/smartgunner = SMARTIE_POINTS_MEDIUM, /datum/job/terragov/silicon/synthetic = SYNTH_POINTS_REGULAR, /datum/job/t
if  you're gonna us ethe multiline format then make it multiline

2022-11-06 19:09 UTC, TiviPlus approved these changes

2022-11-06 19:59 UTC, Lumipharon approved these changes

2022-11-06 20:04 UTC, Lumipharon requested changes

2022-11-06 20:04 UTC, Lumipharon commented on code/datums/jobs/job/shipside.dm
>  	job_flags = JOB_FLAG_LATEJOINABLE|JOB_FLAG_ROUNDSTARTJOINABLE|JOB_FLAG_ALLOWS_PREFS_GEAR|JOB_FLAG_PROVIDES_BANK_ACCOUNT|JOB_FLAG_ADDTOMANIFEST|JOB_FLAG_PROVIDES_SQUAD_HUD|JOB_FLAG_CAN_SEE_ORDERS
```suggestion
	job_flags = JOB_FLAG_LATEJOINABLE|JOB_FLAG_ROUNDSTARTJOINABLE|JOB_FLAG_ALLOWS_PREFS_GEAR|JOB_FLAG_PROVIDES_BANK_ACCOUNT|JOB_FLAG_ADDTOMANIFEST|JOB_FLAG_PROVIDES_SQUAD_HUD|JOB_FLAG_CAN_SEE_ORDERS|JOB_FLAG_ALWAYS_VISIBLE_ON_MINIMAP
```

2022-11-06 20:17 UTC, merged