Masks no longer protect against ash/sandstorms
tgstation/TerraGov-Marine-Corps pull request #11447
Opened 2022-11-03 21:25 UTC by Sunsidec

## About The Pull Request

Masks no longer protect against inclement weather, meaning marines outside are at risk.

## Why It's Good For The Game

Anyone with more than two minutes of playtime will wear a mask as there is no downside to doing so, and therefore this mechanic only negatively impacts one side whilst letting the other roam free. This will hopefully force both sides into more close encounters within buildings while taking shelter from storms, whilst at the same time not removing the ability for both to quickly dart in and out of the weather outside.

## Changelog
:cl:
balance: Masks no longer make marines immune to inclement weather.
/:cl:

2022-11-04 03:17 UTC, Losenis commented
Is there a possibility to make damage from sandstorms be only nonbleeding brute? At the moment they cause bleeding so you're gonna end up drained of your blood by 10 bleeding bodyparts. Also due to it being brute rather than burns like LV's acid rain, someone caught outside runs the risk of getting fractured bones in freak instances, which is pretty stupid.

Sandstorms are stupidly brutal for marines compared to acid rain. Another idea is changing it to burn damage and pretend it's superheated particles or friction burns or something.

2022-11-04 04:48 UTC, Lumipharon commented
I'm not personally opposed to this, but sand kills unga rather quickly, so this'll be entertaining.

2022-11-04 14:15 UTC, Strayed-Raven commented
You would have to rework sand itself to ever get this reasonable.

2022-11-04 14:26 UTC, Losenis commented
![image](https://user-images.githubusercontent.com/72712909/199999242-fb8d4032-523c-47ef-9a50-e152e9b5b88f.png)

2022-11-04 17:07 UTC, TiviPlus requested changes
This code has not been tested and does not work

2022-11-04 17:07 UTC, TiviPlus commented
On a note of what you want to be happening please respond to criticism in the comments

2022-11-04 20:09 UTC, Sunsidec commented
> This code has not been tested and does not work

Hubris, will fix this tomorrow. 


> On a note of what you want to be happening please respond to criticism in the comments

Above

2022-11-06 06:27 UTC, Mechswordsman commented
> Is there a possibility to make damage from sandstorms be only nonbleeding brute? At the moment they cause bleeding so you're gonna end up drained of your blood by 10 bleeding bodyparts. Also due to it being brute rather than burns like LV's acid rain, someone caught outside runs the risk of getting fractured bones in freak instances, which is pretty stupid.
> 
> Sandstorms are stupidly brutal for marines compared to acid rain. Another idea is changing it to burn damage and pretend it's superheated particles or friction burns or something.

Not to mention, the sandstorms also cause lung damage when you're not wearing a mask, and if masks don't protect from them, you'll see people more or less instantly get crit from the lung damage and die from that before the bleed even gets bad.

2022-11-06 12:33 UTC, Sunsidec commented
> This code has not been tested and does not work

![image](https://user-images.githubusercontent.com/78281369/200170968-df5eeb10-dd19-474f-9d27-0173b773d4a8.png)

Seems to work just fine in execution on my end. Sandstorm deals damage through gas masks (takes 34 times to crit, not blocked or lessened by armour), unless I'm missing something!

> Is there a possibility to make damage from sandstorms be only nonbleeding brute? At the moment they cause bleeding so you're gonna end up drained of your blood by 10 bleeding bodyparts. Also due to it being brute rather than burns like LV's acid rain, someone caught outside runs the risk of getting fractured bones in freak instances, which is pretty stupid.
> 
> Sandstorms are stupidly brutal for marines compared to acid rain. Another idea is changing it to burn damage and pretend it's superheated particles or friction burns or something.

Sandstorms ARE stupidly brutal, taking somewhere around 30 seconds to crit through regular armour but at the same time a lot of Big Red is buildings connected to each other which you can use for short distances. The broken bones are somewhat extreme, but the occurrence of which seems to be massively rare and serve to further discourage travel - I'd like to see the impact of leaving the damage & type as-is and see the impact of such, before making changes to it. Need to keep in mind that any changes to the damage amount would also impact xenos, so changing it to burn might be the preferable option, but that comes with it's own downsides regarding making weather have very little variation / the massive amount of pain burn damage causes to marines.

> You would have to rework sand itself to ever get this reasonable.

Above. As far as I'm concerned this was the original intent, but happy to reconsider and tweak after seeing it in live practice.

> Not to mention, the sandstorms also cause lung damage when you're not wearing a mask, and if masks don't protect from them, you'll see people more or less instantly get crit from the lung damage and die from that before the bleed even gets bad.

If this is a thing, it's not clearly signposted, as the proc referenced is just brute damage.

2022-11-06 21:56 UTC, MereWalker commented
Just a pitch in the dark. Maybe adding an additional inconvenience to marines. Filter swapping/changing of oxygen tanks. Granted they should take not much space whatsoever like tiny so as to not screw over space management. Have a slot added to masks that hold the item to allow for "safe breathing". Just a thought. A very inconvenient thought.

2022-11-06 23:19 UTC, Sunsidec commented
> Just a pitch in the dark. Maybe adding an additional inconvenience to marines. Filter swapping/changing of oxygen tanks. Granted they should take not much space whatsoever like tiny so as to not screw over space management. Have a slot added to masks that hold the item to allow for "safe breathing". Just a thought. A very inconvenient thought.

That just sounds like adding an extra step to making storms not doing anything again, and the only people falling for it are the aforementioned people with less than two minutes of playtime.

2022-11-07 01:59 UTC, MereWalker commented
No no. Still not immune to storms and the such just smoke gas the such.

2022-11-10 17:23 UTC, Sunsidec commented
> If you wanted to tone it down just a little you could make sandstorms respect armor instead of being flat damage.

It seemed to be fine enough during the TMs. Forced marines to stay inside, whilst small jaunts still being possible to move between structures. I'm happy enough with the damage as it currently is.

2022-11-11 21:12 UTC, merged