Xenomorph pheromones update when maturing
tgstation/TerraGov-Marine-Corps pull request #11443
Opened 2022-11-03 17:06 UTC by Penwin0

## About The Pull Request
When maturing pheromone strength changes are applied without having to turn them off and on again.
Tested it, both auras of single xenos and leader auras from queen both update properly.

## Why It's Good For The Game
It's how people expect it to work considering the ammount of poor clueless benos running around with unupdated pheromones

## Changelog
:cl:
tweak: Xenomorph pheromones update when maturing.
/:cl:

2022-11-03 17:09 UTC, lKiseki commented
Good stuff. May wanna correct the changelog to say "fix" instead of "tweak", though. Changelogs use predetermined keywords to label changes.

2022-11-03 17:20 UTC, Penwin0 commented
I set it to say tweak unsure if you used GBP here and were picky with it, doesn't really matter much but sure.

2022-11-03 21:35 UTC, TiviPlus requested changes

2022-11-03 21:35 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
> +			hive?.update_leader_pheromones()
dont use istype src, put it on the child

2022-11-04 16:27 UTC, TiviPlus approved these changes

2022-11-04 16:27 UTC, merged