Explosive pouches maximum item size increased
tgstation/TerraGov-Marine-Corps pull request #11440
Opened 2022-11-03 06:25 UTC by lKiseki

## About The Pull Request
Per title. I find it weird that explosive pouches cannot hold certain items such as recoilless rockets, so here we are

## Why It's Good For The Game
Explosive pouches can hold recoilless rockets, giving those builds an alternative in storage options.

## Changelog
:cl: Lewdcifer
balance: Explosive pouches can hold bigger items (such as recoilless rockets).
/:cl:

2022-11-03 06:36 UTC, Lumipharon commented
RR is free round start, them not fitting in the explosive pouch is a deliberate balancing factor.

2022-11-03 06:59 UTC, lKiseki commented
> RR is free round start, them not fitting in the explosive pouch is a deliberate balancing factor.

Yes, I'm aware, hence why I made this PR. I find it weird that you can't just use one of your pouch slots in an explosive pouch to carry three rockets. Feels like a decent tradeoff, and I don't really understand why it'd be denied.

2022-11-03 23:34 UTC, Pariah919 reviewed
I don't personally like RR rockets fitting in pouches as its a deliberate design change and this is mainly targeted to that.

2022-11-04 02:30 UTC, RyderFive commented
RR being balanced around forcing people to use a snowflake satchel that can only hold the rockets besides crates, and storage creeped to hold the RR without really fixing the issues it has/had is pretty meh. 

Ignoring how bad it was before the recent buffs, and the rework it kinda needs. Giving more storage options, and undoing the weird snowflake storage creep satchel dependency would be a better direction for the RR imo.

Not to mention have fun trying to get it during highpop times since there's only 2

2022-11-09 20:44 UTC, BraveMole requested changes
I think the consensus among maintainers was:

Ok for rockets in pouch, but 4 rockets probably too much.

How about a new pouch holding rockets that can hold 2-3 ?

2022-11-20 00:56 UTC, closed without merging