TGUI update
tgstation/TerraGov-Marine-Corps pull request #11451
Opened 2022-11-04 08:12 UTC by SplinterGP

## About The Pull Request
yep, added more stuff, seeing if i can fix things and make it work woo.

## Why It's Good For The Game

## Changelog

2022-11-04 08:14 UTC, SplinterGP commented on code/modules/mob/living/silicon/ai/examine.dm
> +	null
```suggestion
	return null
```

2022-11-07 01:10 UTC, SplinterGP commented
should be good to go, tgui say stuff is in tgui folder but aint ingame, needs later porting

2022-11-07 11:13 UTC, TiviPlus commented
Ran all test suites.
=> Finished 'tgui-test' in 11.459s
=> Finished 'tgui-tsc' in 14.564s
[warn] packages/tgui/interfaces/MarineCasship.tsx
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
=> Target 'tgui-prettier' failed in 20.35s, exit code: 1
=> Finished 'tgui-eslint' in 22.51s
=> Target 'tgui-lint' failed
=> Target 'lint' failed

2022-11-07 18:30 UTC, TiviPlus requested changes

2022-11-07 18:30 UTC, TiviPlus commented on code/modules/mob/living/carbon/human/human_attackhand.dm
> +	visible_message(span_notice("[src] examines [p_them()]self."))
Balloon alert to viewers this

2022-11-12 18:39 UTC, TiviPlus commented
Merging because zachary isnt responding

2022-11-12 18:39 UTC, merged