Misc bombvest code improvements
tgstation/TerraGov-Marine-Corps pull request #11464
Opened 2022-11-06 15:30 UTC by TiviPlus

## About The Pull Request
Added missing spans
Added better admin logging
changed from ctrl click to the existing rclick framework
Changed the admin OB to have a little more fluff
multiple do_afters will no longer be queued

## Changelog
:cl:
qol: bomb vest can no longer spam progress bars
qol: bomb vest warcry is set with right click instead of ctrl click
admin: improvced bomb vest logging
/:cl:

2022-11-06 16:35 UTC, DemonOfHatred commented
ya know what would be funny and fucked up? if you could activate the bomb vest while in a locker

2022-11-07 15:47 UTC, InterroLouis commented
Except thermal dampening cloaks are lockers.

2022-11-09 19:35 UTC, Lumipharon requested changes

2022-11-09 19:35 UTC, Lumipharon commented on code/game/objects/items/explosives/bombvest.dm
> +	name = "oribital bombardment vest"
```suggestion
	name = "orbital bombardment vest"
```

2022-11-09 20:31 UTC, merged