Supply drop event
tgstation/TerraGov-Marine-Corps pull request #11511
Opened 2022-11-10 01:33 UTC by Lumipharon

## About The Pull Request
Adds a new event for HvH gamemodes, although it fully works in HvX as well.

One faction in the game mode is chosen as the 'sending' faction, and they receive a notification telling them where the supply drop will be landing and when.
![image](https://user-images.githubusercontent.com/7869430/200976800-015114f8-a6f4-4fc5-aaa7-a90c5614862f.png)

After a short delay, any other factions are notified of the hostile supply drop as well, giving the friendly faction a bit of a head start.
![image](https://user-images.githubusercontent.com/7869430/200977000-50b0e392-8c51-45ad-94b7-e6df7d2dd660.png)

When the supply drop is generated, it lands in a random open turf in the target area, and everyone is notified.
![image](https://user-images.githubusercontent.com/7869430/200977202-27203691-b52c-49e6-ac67-846854c9a115.png)

The supply drop for TGMC and SOM are a randomised supply crate containing medical supplies, or weapons and equipment of various rarities.
![image](https://user-images.githubusercontent.com/7869430/200977416-895b9d8c-6a22-4aa9-a503-f68b78a335ad.png)
![image](https://user-images.githubusercontent.com/7869430/200977718-97611214-0f9b-4034-8506-b77eef2d47c6.png)

Or if it's a funni alien supply drop, it's a larb.
![image](https://user-images.githubusercontent.com/7869430/200977368-ac13335b-0d50-4373-ab78-91a1f368f29f.png)

As mentioned, the event supports any faction, or even multiple factions, so it's future proofed for gamemodes with new or more factions, and badmins can trigger it safely in HvX modes. Any faction without a specific supply drop will default to the marine one.

changed loot box code a little, they now support multiple rolls on the table is specified.

Oh also added a burstfire SOM shotgun for supply drops only. Because it was satisfying as hell to use when Tye made one, but probs not balanced for general use.

## Why It's Good For The Game
More events are kool
New objectives to fight over in HvH is good

## Changelog

:cl:
add: Adds supply drop event to HvH
add: Added a supply drop specific SOM burst shotgun
/:cl:

2022-11-10 01:34 UTC, FosterGrime-Heymynameslouie commented
holy shit

noodle in the box

a boxed noodle

2022-11-10 06:01 UTC, zzurge commented
woah based

2022-11-10 07:53 UTC, XSlayer300 commented on code/game/objects/items/loot_box.dm
> +	name = "Supply drop"
```suggestion
	name = "supply drop"
```

2022-11-10 07:53 UTC, XSlayer300 commented on code/game/objects/items/loot_box.dm
> +	desc = "A box of valuable military equipment"
```suggestion
	desc = "A TGMC-marked box full of valuable military tactical equipment."
```

2022-11-10 07:53 UTC, XSlayer300 commented on code/game/objects/items/loot_box.dm
> +	name = "Supply drop"
```suggestion
	name = "supply drop"
```

2022-11-10 07:54 UTC, XSlayer300 commented on code/game/objects/items/loot_box.dm
> +	desc = "A box of valuable SOM military equipment"
```suggestion
	desc = "A rugged box composed of valuable SOM military materiel."
```

2022-11-10 08:27 UTC, Oscari-pog commented
Finally, ayylmaos in HvH

2022-11-11 20:57 UTC, TiviPlus requested changes
didnt read through fully but use the qdel intitialize hint instead of qdel

2022-11-12 18:44 UTC, TiviPlus approved these changes

2022-11-12 18:44 UTC, merged