Adds a hotkey for place acid well
tgstation/TerraGov-Marine-Corps pull request #11554
Opened 2022-11-14 11:46 UTC by lorianss

## About The Pull Request

Adds a hotkey for "Place acid well" - xeno 's ability

## Why It's Good For The Game

Easy access to the use of the ability 
Improving the quality of the game

## Changelog

:cl:
add: Xenomorphs can quickly build acid wells, as well as collapse the top panel with abilities (since all abilities can be used using keyboard shortcuts).
/:cl:

2022-11-14 18:26 UTC, TiviPlus commented
Checking long list formatting
code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm:309:	keybinding_signals = list(
	KEYBINDING_NORMAL = COMSIG_XENOABILITY_PSYCHIC_CURE,
long list underindented, should be two tabs

2022-11-14 18:27 UTC, TiviPlus commented
Also add a sensible default if you dont mind

2022-11-19 01:26 UTC, Lumipharon requested changes

2022-11-19 01:26 UTC, Lumipharon commented on code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
> +	KEYBINDING_NORMAL = COMSIG_XENOABILITY_PSYCHIC_CURE,
Shouldn't this be the new define?

2022-11-20 21:27 UTC, Lumipharon commented on code/datums/keybinding/xeno.dm
> +	keybind_signal = COMSIG_XENOABILITY_PLACE_ACID_WELL
```suggestion
	keybind_signal = COMSIG_XENOABILITY_PLACE_ACID_WELL
	hotkey_keys = list("T")
```
Add a keybind default here like this. Doesn't actually have to be T.

2022-11-20 21:59 UTC, Lumipharon approved these changes

2022-11-20 22:17 UTC, merged