Large Flamethrower Tank buff.
tgstation/TerraGov-Marine-Corps pull request #11555
Opened 2022-11-14 15:18 UTC by Naaanii

## About The Pull Request
Increases the ammo for the large flamethrower tank from 75 to 100.

## Why It's Good For The Game
The large tank, while refillable also terribly pales in comparison to the 500 ammo backtank and even the 50 ammo incinerator tank.
This should keep it a bit closer in line with the backtank while also not being a strictly better/worse option. 

## Changelog

:cl:
balance: Increases Large flamethrower tank's capacity from 75 to 100. (76 to 101)
/:cl:

2022-11-15 11:14 UTC, FIXTHERADBOXPLEASE commented
Blatant powercreep.

2022-11-15 20:10 UTC, Pariah919 requested changes
No.
Buff back tank at most.

2022-11-17 20:58 UTC, Coastfront commented
Doesn't need a buff and feels unnecessary to do so.
As others have pointed out: you could already carry more fuel total using large tanks than with the back tank.

The advantage of the individual tanks over the back tanks isnt meant to be capacity per magazine, its meant to be total fuel stored and the fact that you dont need to reload from stuns>
The advantage of the back tank in function isnt higher total capacity, its higher "magazine" capacity as you do not need to reload, ever, until you get stunned or outright run out of ammo.
Buffing the large tanks to 100 fuel doesent functionally impact anything but their main weakness: having to reload semi-frequently.

2022-11-17 22:02 UTC, DemonOfHatred commented
we literally DO NOT need more buffs for marines thanks.

2022-11-20 13:48 UTC, BraveMole commented
Powercreep

2022-11-20 13:48 UTC, closed without merging