Unique Flaregun Flare
tgstation/TerraGov-Marine-Corps pull request #11576
Opened 2022-11-19 22:34 UTC by Pariah919

## About The Pull Request
Uses the Mortar flare.
Only flaregun can fire it.

https://user-images.githubusercontent.com/46353991/202874135-d7bfaff2-08bd-4f1a-8cc3-f2f1b126a27e.mp4

## Why It's Good For The Game
Gives flare gun more utility, and makes sense that it would have something like it to me.

## Changelog

:cl:
add: Added new flaregun flare type, works exactly like mortar flare.
/:cl:

2022-11-19 22:51 UTC, iLikeMemes commented
As a flare enthousiast I really like this, However I do think it **_might_** be too strong for it to be an unlimited item in the marine vendor. I cant really say for sure as i am not 100% sure how long those flares last. 
other than that,
**speed merge**

2022-11-19 22:58 UTC, DemonOfHatred commented
Theres already so many things that give off light, the endless revolver spam for one. not needed.

2022-11-19 23:02 UTC, Lumipharon commented
This needs to significantly weaker (probably durationwise) than cas/mortar flares.

2022-11-19 23:28 UTC, Losenis commented
Does it really? It already sacrifices the funny "set xeno on fire if hit" thing that you can shove into underbarrel attachments, even already triggered flares. And normal flares you can grab and throw further away once you need light further ahead, not so much with these.

2022-11-19 23:55 UTC, FosterGrime-Heymynameslouie commented
how about give flare guns iff instead of a stronger flare
I think it would give flare guns more utility

cm does it and it's a huge qol iirc

2022-11-20 02:40 UTC, novaepee commented
> how about give flare guns iff instead of a stronger flare I think it would give flare guns more utility
> 
> cm does it and it's a huge qol iirc

In code, a flare is a grenade not a bullet, so you have to make it IFF worthy.

2022-11-20 03:34 UTC, FosterGrime-Heymynameslouie commented
> > how about give flare guns iff instead of a stronger flare I think it would give flare guns more utility
> > cm does it and it's a huge qol iirc
> 
> In code, a flare is a grenade not a bullet, so you have to make grenade IFF which is not an easy feat.

oh

2022-11-20 09:31 UTC, Al-1ce commented
I like this very much. Duration shouldn't be nerfed to the point that this becomes obsolete, though.

2022-11-20 11:43 UTC, FIXTHERADBOXPLEASE commented
Great. A PR that found a way to powercreep flares, of all things. Not just that, but one that removes all xeno counterplay to them.

2022-11-20 15:24 UTC, zzurge commented
LET THERE BE LIGHT

2022-11-20 19:35 UTC, MereWalker commented
Should make it last for 12 seconds and it then fizzles out. You could also make it flicker it's light so doesn't bright light all the time. Just a thought.

2022-11-21 11:40 UTC, Araulius commented
My dude decided to make a special flare for the flare gun, but not a special cas flare for the flare gun

2022-11-23 11:20 UTC, Overdrive659 commented
This is cool as fuck, however;

Consider either-
limiting flare gun for SLs, FCs and other command
limiting flare guns + ammo in vendors

Currently, this makes the flare gun VERY powerful: It has no xeno counterplay, as xenos cannot apply acid to it, and it is a lot brighter than normal flares.
When CAS uses its flares it feels balanced, having that much light for that duration. Making that handheld and infinate.... IDK man.

2022-11-24 10:54 UTC, Al-1ce commented
I think making this an engi item would be overall better and also make sense. Also maybe as a selectable pouch in the loadout vendors with a limited amount of ammo.

2022-11-24 10:55 UTC, Al-1ce commented
I think this would be perfect as an engineer item.

2022-11-30 17:21 UTC, TiviPlus requested changes

2022-11-30 17:21 UTC, TiviPlus commented on code/game/objects/items/explosives/grenades/marines.dm
> +	return
why is thzis a grenade attack self should be calling parent

2022-12-03 04:22 UTC, XSlayer300 commented on code/game/objects/items/explosives/grenades/marines.dm
> +	name = "\improper M60 FLHA Flare"
```suggestion
	name = "\improper M60 FLHA flare shell"
```

2022-12-06 05:06 UTC, Starfirejordan commented
causing an issue that makes CAS flares not work
![image](https://user-images.githubusercontent.com/102649696/205821062-50bae63d-f44a-4834-8735-42600775bd1e.png)

2022-12-07 02:03 UTC, Pariah919 commented
too tired to finish this off, I'll come back to this in a while.

2022-12-07 02:04 UTC, closed without merging