Spiderlings ain't no bitches
tgstation/TerraGov-Marine-Corps pull request #11583
Opened 2022-11-20 17:09 UTC by Zar000

## About The Pull Request

Spiderlings will now avenge widow when she dies, pursuing any nearby marines and mauling them. This only lasts 10 seconds or untill they die from other causes.

## Why It's Good For The Game

Currently spiderlings just kinda.. look at their dead mother.
Unless widow got gibbed, in which case they would just run around stupidly.
Now however, they will attack any marine in sight, if there are none, they get brazil'd.

## Changelog

:cl:
add: widow spiderlings will avenge widow
/:cl:

2022-11-21 18:50 UTC, BraveMole requested changes

2022-11-21 18:50 UTC, BraveMole commented on code/modules/mob/living/carbon/xenomorph/castes/spiderling/spiderling.dm
> +	for(var/mob/living/carbon/human/victim in view(SPIDERLING_RAGE_RANGE, x))
use cheap_get_humans_near

2022-11-21 18:50 UTC, BraveMole commented on code/modules/mob/living/carbon/xenomorph/castes/spiderling/spiderling.dm
> +	x.next_move_slowdown -= SPIDERLING_RAGE_SPEED
what is the point of that

2022-11-21 18:50 UTC, BraveMole commented on code/modules/mob/living/carbon/xenomorph/castes/spiderling/spiderling.dm
> +	if(isnull(possible_victims))
it's not null, you initialized it. Check for size

2022-11-21 21:24 UTC, Lumipharon approved these changes
Looks cool, although I note that the pick() means the spiderlings could ignore like 10 ungas and try rush the dude behind them.

2022-11-22 06:42 UTC, Lumipharon approved these changes

2022-11-22 06:42 UTC, merged