Age of Vali: Rownin Skeleton and more Fatigue
tgstation/TerraGov-Marine-Corps pull request #11627
Opened 2022-11-25 04:43 UTC by novaepee

## About The Pull Request

will edit this later once I fix standing issue

## Why It's Good For The Game

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2022-11-26 06:50 UTC, FosterGrime-Heymynameslouie commented
the tyr module looks funky

like you have marines shoulder bike safety pads and called it a day

2022-11-26 09:29 UTC, Al-1ce commented
The uniforms all sort of look the same but I think any variation is good.

2022-11-26 12:19 UTC, TiviPlus requested changes
is this is just harness 2 why does harness exist

2022-11-26 16:45 UTC, SilencedMP5A5 commented
let us put modules on harness + give harness (and jackets) usable light ranges 2023

2022-11-28 00:37 UTC, Losenis commented
>It's under xenonaut parent so synths can't use it

Balls, there goes the 0 armor pure utility armor

2022-11-28 19:08 UTC, novaepee commented on code/modules/clothing/modular_armor/modular.dm
> +	desc = "A light armor, if you can even called it that, made by SSgt Rownin for dedicated marines that want to travel light and have agility in exchange of protection. Alt-Click to remove attached it
Made up lore

2022-11-28 19:09 UTC, novaepee commented on code/game/objects/machinery/vending/marine_vending.dm
> +			/obj/item/clothing/under/marine/lv_fatigue = -1,
New fatigues that Ghost provided.

2022-11-28 19:09 UTC, novaepee commented on code/modules/clothing/under/marine_uniform.dm
> +	)
New fatigues that Ghost provided.

2022-11-29 21:13 UTC, Lumipharon approved these changes

2022-11-29 21:13 UTC, merged