Mech portal immunity
tgstation/TerraGov-Marine-Corps pull request #11644
Opened 2022-11-29 00:35 UTC by Lumipharon

## About The Pull Request
You can no longer send mechs through portals. No more funny banish/portal wombo combos.

Added a flag for portal immunity, there's probs other stuff that could use it.

## Why It's Good For The Game
ggnoreing mechs is very lame.

## Changelog

:cl:
balance: rebalanced something
/:cl:

2022-11-29 01:14 UTC, FIXTHERADBOXPLEASE commented
Salt PR?

2022-11-29 07:05 UTC, Al-1ce commented
Salt PR?

2022-11-29 10:40 UTC, Araulius commented
i ded please remove

2022-11-29 21:57 UTC, zzurge commented
DEWIT

2022-11-30 00:52 UTC, SpiderPsycho commented
Cope. This is the one trick xenos have to bamboozle the mech. Sorry your power creep has a counter.

2022-11-30 10:04 UTC, Tailiik commented
Pure copium

2022-11-30 10:20 UTC, TiviPlus requested changes
fix your cl

2022-11-30 10:20 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
> +	if(!linked_portal || !COOLDOWN_CHECK(src, portal_cooldown) || crosser.anchored || ishuman(crosser) || (crosser.resistance_flags & PORTAL_IMMUNE))
human should have the flag or you should just use an ismech imo

2022-11-30 10:48 UTC, RikuTheKiller commented
Still utter copium even if you delete comments.

It's both funny and gives the portals a reason to exist again. It also needs the wraith's full attention to pull off.

I don't see this as much more than a marine main cope PR.

2022-11-30 11:02 UTC, SpiderPsycho commented
Marine cope is marine cope. The only reason this is going through is because marines are the ones complaining about it. Whenever some new stupidly overpowered thing comes out for marines, Xenos are just told to suck it up and 'cope', as if we actually have a method to do this mythical coping. Meanwhile when a marine complains the devs will bend over backwards to "fix" it.

There is currently no counterplay to the mech. It is literally just an 'unga' machine. The pilot gets to live out his fantasy of solo charging xenos with no consequences, since it can just jetpack out before taking any somewhat significant damage. We can't stun it, pull it, push it, but we **can** portal it. It's our only method of singling the thing out. Even then it's not a true counterplay, it's just taking it to an area where enough of us can damage it to the point that it dies. _**And even then**_ the pilot's body might be recovered, so they can run along and print a trillion more mechs. 

The only other 'option' for dealing with mechs is to ignore them because we can do nothing to them. If you're going to apply this 'fix' then give Xenos a concrete way of countering the mech.

2022-11-30 11:03 UTC, TiviPlus commented
Spamming cope doesnt work you know

2022-11-30 11:04 UTC, TiviPlus approved these changes

2022-11-30 17:17 UTC, merged