Ravager Vampirism Rework
tgstation/TerraGov-Marine-Corps pull request #11684
Opened 2022-12-06 19:32 UTC by Zar000

## About The Pull Request
Makes vampirism actually do something.

Ravager will heal for 25% of missing health per hit with a cooldown.

DRAFT TODO
- Currently no cooldown
- No visuals

## Why It's Good For The Game

Primo is currently useless, reward for continued prolonged fights is rather low and if anything discouraged, this will change that.

## Changelog

:cl:
add: New primo to ravager
balance: The primo for ravager
/:cl:

2022-12-06 21:16 UTC, Lumipharon commented
uwot? This seems hilariously high considering the low cooldown and it stacks with superrage healing.
Superrage had to get nerfed due to its absurd healing factor, keep in mind.

2022-12-06 23:58 UTC, Luxyboo commented
i feel like 10% would be much better than 25% though it would need some testing.

2022-12-07 00:47 UTC, FIXTHERADBOXPLEASE commented
Yeah, Ravager's primo is both underwhelming and counter-intuitive. This is a good step away from that. Even if bumped down to something small like 10 or 15%, it'd still be preferable.

2022-12-07 00:48 UTC, Al-1ce commented
> uwot? This seems hilariously high considering the low cooldown and it stacks with superrage healing. Superrage had to get nerfed due to its absurd healing factor, keep in mind.

The health cap to use superrage is too low to be efficiently used. I can say this with confidence as someone who usually goes ravager.

2022-12-08 23:21 UTC, TiviPlus requested changes

2022-12-08 23:21 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
> +/datum/action/xeno_action/vampirism/proc/play_particles(attacker)
inline

2022-12-08 23:21 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
this can bug out and due to tidi make it so the particles get deleted preemtively
also leaves a hanging ref so this will hard del

2022-12-18 09:09 UTC, merged