Queen screech now gives stagger
tgstation/TerraGov-Marine-Corps pull request #11692
Opened 2022-12-07 12:57 UTC by MLGTASTICa

## About The Pull Request
Queen screech gives stagger

## Why It's Good For The Game
The ability is better used against larger groups of marines , by providing them with the damage debuff , instead of it currently being used on solo marines to secure easy kills.

## Changelog

:cl:
balance: Queen screech now gives a maximum of 15 stagger , adjusted based on distance , with the minimum being 3.
/:cl:

2022-12-07 13:02 UTC, EvilMelonTheSecond commented
As long as the stun remains it will be used against solo marines. This buff won't change how its used.

2022-12-07 13:20 UTC, MLGTASTICa commented
> Contributor

it will always be used against solo marines , but now this makes it not be useless against larger groups , and perhaps better for initiating pushes against marines

2022-12-08 02:29 UTC, UntoldTactics commented
Pretty good thing. Queen screech as a whole being used against solo marines is purely because securing a kill is vital. Plus, if your alone and encounter a queen that's a you problem.

The stagger will definitely make it actually more useful against large groups, as it often doesn't do too much in that specific regard, since marines just get right back up, usually only works well when screeching a dying group, but thats just a finisher.

2022-12-10 14:16 UTC, BraveMole requested changes

2022-12-10 14:16 UTC, BraveMole commented on code/modules/mob/living/carbon/human/human_defense.dm
> +	var/stagger_amount = LERP(15, 3, dist_pct) * reduction // 15 Next to queen , 3 at max distance.
All of those vars are complely uneeded, just put that line in the adjust_stagger

Same for stam damage, etc

2022-12-16 14:17 UTC, Lumipharon commented
I'm not opposed to stagger on screech, but uh, I fail to see how applying 30(?) seconds of 50% damage on an unga would make me want to solo screech someone any less.

2022-12-16 17:58 UTC, RipGrayson approved these changes

2022-12-21 04:56 UTC, RipGrayson commented
I've got to move things along, I'm merging this in 24 hours if we don't have any objections.

2022-12-21 09:42 UTC, Lumipharon commented
> I've got to move things along, I'm merging this in 24 hours if we don't have any objections.

for reference buckshot does 1 stack of stagger, warrior punch does 3 (6 if grappled). Up to 30 seconds of 50% damage on everyone screen wide is very strong.

I would have it much lower like LERP(7, 3, dist_pct).

2022-12-21 23:45 UTC, RipGrayson requested changes
I defer to Lumi's superior knowledge here, please reduce the stagger, 30 seconds of 50% damage is way too strong.

2022-12-22 10:57 UTC, Lumipharon approved these changes

2022-12-22 11:08 UTC, merged