Camouflage marines
tgstation/TerraGov-Marine-Corps pull request #11786
Opened 2022-12-25 11:39 UTC by Lumipharon

## About The Pull Request
Can you spot the 8 marines in this picture? Research states that 80% of SOM terrorists, and 65% of xenomorphs cannot. Are YOU a terrorist or alien?
![image](https://user-images.githubusercontent.com/7869430/209466381-d8d0da05-db00-4065-b894-49cac25b4315.png)

Makes xenonaut armour spawn with it's coloured variants based on the ground map, like jaeger does. You can still change the colour manually of course.

Additionally added desert camo as a default for Chigusa.

Also made xenonauten hats not a child of jaeger helmets as they're not greyscale/hyperscale so never should have been, and they were inheriting a bunch of random shit they didn't need to.

## Why It's Good For The Game
Marines in need of a huge buff via advanced camouflage

## Changelog

:cl:
add: Xenonauten armour spawns with map appropriate colours where applicable
/:cl:

2022-12-25 12:53 UTC, Naaanii commented
GUERILLA WARFARE! LET'S GOOOO!!!

2022-12-25 16:10 UTC, Losenis commented
> Black drip nerf

Disgusting

2022-12-25 21:20 UTC, SilencedMP5A5 commented
this image is gaslighting me

_where are the ungas oh god oh fuck_

2022-12-26 00:36 UTC, MereWalker commented
I genuinely can't see it. Please where is my giant red circle.

2022-12-27 23:07 UTC, Strayed-Raven commented
black drip nerf.

2022-12-28 07:03 UTC, UntoldTactics commented
I mean okay but I hope that image is a joke. Xenos have literal thermal vision after all, and idk how your making marines register at -5 degrees celcius or whatever

2022-12-31 03:41 UTC, MereWalker commented
Please! I need the red circle! I've been looking for DAYS now. At least tell me they are real!

2023-01-08 22:50 UTC, Kuro020 approved these changes

2023-01-10 09:54 UTC, TiviPlus requested changes

2023-01-10 09:54 UTC, TiviPlus commented on code/datums/loadout/old_typepaths.dm
> +/obj/item/clothing/head/modular/m10x/standard
read the comment in this file pls

2023-01-10 10:41 UTC, Lumipharon commented on code/datums/loadout/old_typepaths.dm
> +/obj/item/clothing/head/modular/m10x/standard
Reading is for nerds.

2023-01-13 15:17 UTC, TiviPlus requested changes
Wont this break loadouts meaning you want to convert old ones or did you discuss that w/ brave

2023-01-13 20:25 UTC, Lumipharon commented
> Wont this break loadouts meaning you want to convert old ones or did you discuss that w/ brave

I talked with brave. Considering we're breaking Jaeger fundamentally so those loadouts will have to be remade, I thought it better to just have this at the same time and same situation

2023-02-02 13:36 UTC, merged