Secrete resin refactor
tgstation/TerraGov-Marine-Corps pull request #11848
Opened 2023-01-02 00:59 UTC by iLikeMemes

## About The Pull Request

It's now easier to give a xeno a building range

resin_range_max is a new xeno define which defines the maximum range from which a xeno can build, which defaults to zero.

as a result this cleaned up some hivemind and hivelord code and i also fixed a typo.

## Why It's Good For The Game

This code makes me not want to cry

## Changelog

:cl:
spellcheck: Fixed a typo in hivemind's change form ability description
code: Cleaned up some secrete resin code related to hivelord and hivemind
refactor: Refactored secrete resin code
/:cl:

2023-01-03 11:21 UTC, iLikeMemes commented
somethings are fucked apparently so let me mark this as draft whilst i fix those

2023-01-03 14:18 UTC, iLikeMemes commented
anyways this is 100% ready now.

2023-01-04 00:35 UTC, Lumipharon requested changes

2023-01-04 00:35 UTC, Lumipharon commented on code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
> +	var/resin_max_range = 0
autodoc

2023-01-04 12:08 UTC, Lumipharon approved these changes

2023-01-04 12:08 UTC, merged