Rouny takeover
tgstation/TerraGov-Marine-Corps pull request #11854
Opened 2023-01-02 20:01 UTC by Zar000

## About The Pull Request

## Why It's Good For The Game

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2023-01-02 21:43 UTC, ZahaSanko commented
based PR speedmerge

2023-01-03 02:05 UTC, novaepee commented
![image](https://user-images.githubusercontent.com/6610922/210291497-1bdffef6-2264-4ed8-ae2d-f4c3f3ae84be.png)
Ehh? Why are you deleting Warlock?

2023-01-04 19:42 UTC, Zar000 commented
> ![image](https://user-images.githubusercontent.com/6610922/210291497-1bdffef6-2264-4ed8-ae2d-f4c3f3ae84be.png)
> Ehh? Why are you deleting Warlock?

Oh shit thanks, thought merge conflict resolved properly

2023-01-10 03:29 UTC, ClosetedSkeletonGH commented
> > ![image](https://user-images.githubusercontent.com/6610922/210291497-1bdffef6-2264-4ed8-ae2d-f4c3f3ae84be.png)
> > Ehh? Why are you deleting Warlock?
> 
> Oh shit thanks, thought merge conflict resolved properly

Warlocks walking animation is still broken

2023-01-13 15:20 UTC, TiviPlus requested changes
rest looks ok I guess

2023-01-13 15:20 UTC, TiviPlus commented on code/modules/admin/fun_verbs.dm
> +		return
R_FUN please

2023-01-13 15:20 UTC, TiviPlus commented on code/modules/admin/fun_verbs.dm
> +	set desc = "Turns all living xenos into rouny versions of themselves"
should say it toggles

2023-01-15 12:37 UTC, TiviPlus approved these changes
kuro

2023-01-15 15:35 UTC, merged

2023-01-15 15:44 UTC, SpiderPsycho commented
If the Praetorian sprite is the one with the femboy socks I will be disappointed. There are no femboys in the Xenomorph hive, they are all female. Therefore, the Praetorian should have lacy stockings.

2023-01-15 16:45 UTC, AtlasRules commented
> If the Praetorian sprite is the one with the femboy socks I will be disappointed. There are no femboys in the Xenomorph hive, they are all female. Therefore, the Praetorian should have lacy stockings.

jesse what the fuck are you talking about