Heavy Minigun and Dual AC are now not-hardpoint only (and necessary emplaced gun price changes)
tgstation/TerraGov-Marine-Corps pull request #11878
Opened 2023-01-06 12:09 UTC by maikilangiolo

## About The Pull Request
1. Dual AC and minigun are now not TAD-only guns (hardpoint locked) but can moved like other emplaced guns
2.1 Prices were changed for emplaced guns based on a different tiers I proposed to Lumi, following a logic of light vs medium vs heavy: MG08 300 -> 400, HSG 800 --> 600, Minigun 750 --> 600 , Dual AC 600 --> 700, TAT 600 --> 900
2.2 HSG, HMG and Minigun are light emplaced guns vs the heavier AGSL and now Dual AC, and the heaviest TAT, which was too cheap to replace and you get one free roundstart anyway.
2.3 Ammo costs adjusted for the HSG. It had a 300 round magazine that costed 100 points vs the TAD hsg that had 500 round for 30 points. I essentially swapped the two around, since paying 300% the cost for 40% less ammo is stupid.
3. Other misc changes to bring the guns in line w/ each other: minigun and HSG (un)deploy time is the same as they are the same class, dual AC deploy time and HP increased to match the AGLS since they are also the same class and intended to be sidegrades. Armor bumped up accoding to #11108 to bring the guns in line with HSG and MG08, since they are no longer safely tucked in tadpole.
4. Note that otherwise no other changes have been made to the stats, they fixed minigun is just a marine minigun but fixed, and the dual AC does 25 damage only without firing fast. This PR is also intended to let people (probably only me) test these guns and rebalance them if needed for marine use, considering they were freed from req hell. It is likely the dual AC might need a tweak since it looked like it was intended to be a cheap weapon and I bumped it up in cost.

## Why It's Good For The Game
More variety for marines, no more req hell for the beatiful and cool guns Tye made, and hopefully the start of a minor rework or emplaced guns to make them more fun and apply needed changes, both buffs and nerfs (arguably mostly nerfs).

## Changelog

:cl:
add: added the mounted minigun and mounted dual cannon to normal marine use
balance: rebalanced cost of HSG ammo between marine and tadpole version
balance: rebalanced cost of mounted guns according to a sensible hierarchy of power vs availability
/:cl:

2023-01-07 01:47 UTC, Lumipharon requested changes

2023-01-07 01:47 UTC, Lumipharon commented on code/modules/projectiles/guns/mounted.dm
> +	soft_armor = list(MELEE = 0, BULLET = 100, LASER = 0, ENERGY = 0, BOMB = 80, BIO = 100, FIRE = 0, ACID = 20)
why does this have giga armour? 100 bullet and 80 bomb?

2023-01-07 01:47 UTC, Lumipharon commented on code/modules/projectiles/ammo_datums.dm
> +	P.proj_max_range -= 5
this meants you can pierce like 6-7 turfs without issue, which is probably not good.

2023-01-07 01:47 UTC, Lumipharon commented on code/modules/projectiles/guns/mounted.dm
> +/obj/item/weapon/gun/standard_minigun
minor but why is this 'standard' minigun, when there is already a standard minigun?

2023-01-07 01:47 UTC, Lumipharon commented on code/modules/projectiles/guns/mounted.dm
> +	soft_armor = list(MELEE = 0, BULLET = 100, LASER = 0, ENERGY = 0, BOMB = 80, BIO = 100, FIRE = 0, ACID = 20)
giga armour

2023-01-07 01:47 UTC, Lumipharon commented on code/modules/reqs/supplypacks.dm
> +	cost = 30
Why are all these ammo packs so cheap? Literally less than a minion.

2023-01-07 05:15 UTC, FIXTHERADBOXPLEASE commented
Req prices don't seem to line up with the changes in #11815 no? Having more mounted gun variety will be great though.

2023-01-16 08:23 UTC, maikilangiolo commented
As far the "standard minigun" thing, I added it desperately thinking that somehow it's what caused my debug to fail, when it was an unrelated missing line elsewhere (since other emplaced guns had the "standard" thing).

Magazine prices for minigun and dual AC are not mine, I forgot to mention that. Tye himself priced them at 3 points, so I also lowered the small HSG mag cost to 3 (now 30)

2023-01-19 20:47 UTC, maikilangiolo commented
@Lumipharon 
Changes: 
- Dual AC mag 50 --> 80
- dual AC mag size bulky --> normal
- minigun fire delay 0.15 --> 0.10, removed iff, added 0.05 aim mode fire delay. This changes the DPS as Sergei outlines
![Screenshots_2023-01-19-21-44-31](https://user-images.githubusercontent.com/40152611/213556174-a552d092-4015-4385-b43a-b83e6c7aa512.png)
![Screenshots_2023-01-19-21-37-29](https://user-images.githubusercontent.com/40152611/213556180-9fb4e9a9-a5b4-4af5-be99-e22db808f8e0.png)

2023-01-20 19:28 UTC, XANAv2 commented
Could we potentially keep the old guns on the old vehicle hard points as well as these new ones? As this just makes them exclusive to infantry.

2023-01-21 11:16 UTC, maikilangiolo commented
> Could we potentially keep the old guns on the old vehicle hard points as well as these new ones? As this just makes them exclusive to infantry.
> 
> Either that or I'm dumb and can't find them.

You can still use them on tad, just not on the hardpoint.

2023-01-23 14:18 UTC, maikilangiolo commented
nevermind

2023-01-28 21:48 UTC, Lumipharon approved these changes

2023-01-28 21:51 UTC, Lumipharon requested changes
wait, why are random map files showing as being changed? And for WO are those guns the actually deployed versions, or just a gun on the floor someone has to setup?

2023-02-02 09:57 UTC, closed without merging