Bloodpack resprite and visual upgrade
tgstation/TerraGov-Marine-Corps pull request #11916
Opened 2023-01-11 19:58 UTC by Blundir

## About The Pull Request

Resprites bloodpack, adding actual reagent filling bar (like on beakers, hyposprays, etc), adds blood type icon on every blood type bloodpack.
![dreamseeker_KDq4AICpBw](https://user-images.githubusercontent.com/100090741/211905045-1d729ce9-6596-4473-8717-5a080f978f02.png)

![dreamseeker_UxI8P3rtRo](https://user-images.githubusercontent.com/100090741/211905052-0f0fd8d0-8f42-4e64-84ef-a955d29090bd.png)

## Why It's Good For The Game

Part of the reject CM cycle, here is how it looked before:
![dreammaker_CZam5QVZuL](https://user-images.githubusercontent.com/100090741/211905007-a3021015-c269-425a-ae05-9ef53db643d1.png)

New sprites look better, more fitting, provide more functionality.

## Changelog

:cl:
add: added reagent filling overlay, blood type overlay for bloodpack
imageadd: added new icons for bloodpacks 
/:cl:

2023-01-11 21:10 UTC, Lumipharon commented
old ones look sharp enough to cut

2023-01-11 22:44 UTC, lbnesquik commented
I prefer the old ones, honestly.

2023-01-11 23:27 UTC, Al-1ce commented
The bloodpack meta begins.

2023-01-13 14:52 UTC, TiviPlus requested changes

2023-01-13 14:52 UTC, TiviPlus commented on code/game/objects/items/reagent_containers/blood_pack.dm
> +		add_overlay(image('icons/obj/items/bloodpack.dmi', "[blood_type]"))
incorrect update overlays usage
The way it works is you call update_icon and then update_overlays returns a list of overlays to add

2023-01-18 02:13 UTC, Kuro020 approved these changes

2023-01-29 00:49 UTC, closed without merging