Pillar of Spring 2023 Expansion Part 2: NOT UNO EDITION
tgstation/TerraGov-Marine-Corps pull request #11912
Opened 2023-01-11 02:48 UTC by novaepee

## About The Pull Request

Expand starboard of PoS!

Add more lights in medbay.

Update NOT UNO card sprites!

Allow marines to spawn in with NOT UNO cards!

Vend out NOT UNO decks from the Utility tab in the Armament vendor!

## Why It's Good For The Game

Since I have expanded portside of PoS for medbay and trauma bay, I ought to do the same for starboard. With the INCREASED AWARENESS OF NOT UNO, I want this PR to increase accessability of NOT UNO.

We have NOT UNO for 3 years, and yet UNTIL TODAY, we saw its usage. We need more of it!

## Changelog

:cl:
add: Expand starboard of PoS!
Add: more lights in medbay.
imageadd: Update NOT UNO card sprites!
add: Allow marines to spawn in with NOT UNO cards!
/:cl:

2023-01-11 15:19 UTC, TiviPlus requested changes
Free with your xbox

2023-01-11 15:19 UTC, TiviPlus commented on code/game/objects/items/toys/cards.dm
> +	desc = "A flashy deck of Nanotrasen KOTAHI playing cards that are definitely NOT UNO. Usually sold alongside crayon packages."
revert

2023-01-11 15:19 UTC, TiviPlus commented on code/modules/client/preferences_gear.dm
> +	display_name = "kotahi (NOT UNO)"
```suggestion
	display_name = "Kotahi deck"
```

2023-01-15 01:10 UTC, RipGrayson requested changes
Missing a wall here
![van16](https://user-images.githubusercontent.com/49290523/212503973-02243d5d-5890-47b9-a419-d36d025b7d3f.png)
These AI nodes aren't connected
![van17](https://user-images.githubusercontent.com/49290523/212503974-ea251035-bb3a-4b24-bd0b-ec0c0475b533.png)

2023-01-15 02:16 UTC, merged