Jaeger MK2 PR return of spriter sanity
tgstation/TerraGov-Marine-Corps pull request #11932
Opened 2023-01-14 00:11 UTC by Pariah919

## About The Pull Request
tl;dr for now
revert to manual colors, map colors only
removal of arms/legs

## Why It's Good For The Game
better maintainablity since hyperscale is awful

## Changelog

:cl:
add:Jaeger stuff
/:cl:

2023-01-15 13:00 UTC, RaidarV commented
salt pr ? :trollface:

2023-01-15 15:39 UTC, Kuro020 approved these changes
RIP bozo

2023-01-15 17:07 UTC, Tailiik commented
Visor color is gone too? But muh ODST cosplay requires blue visor

2023-01-15 17:18 UTC, Kuro020 commented
![image](https://user-images.githubusercontent.com/52428261/212556381-0a9b76fb-302c-4f17-b576-ed1f618137d5.png)
EVA skull not in the picture because I'm lazy

2023-01-15 17:20 UTC, Kuro020 commented
![image](https://user-images.githubusercontent.com/52428261/212556591-c740c099-2a89-4e22-876b-44176d110212.png)
I forgor EOD 💀

2023-01-15 17:46 UTC, TiviPlus requested changes
I dont see emissibles on the helmets

2023-01-15 17:46 UTC, TiviPlus commented on code/datums/greyscale/greyscale_configs.dm
> -	json_config = 'code/datums/greyscale/json_configs/modularlegs.json'
json config removal?

2023-01-15 22:43 UTC, Lumipharon requested changes
Fix the helmet variant names in the DMI as mentioned and the json files tivi mentioned, otherwise everything is surprisingly ok

2023-01-17 20:27 UTC, Lumipharon commented
Kuro says add the no hair flag. 
![image](https://user-images.githubusercontent.com/7869430/213005499-146a076e-7829-4a95-802c-404353ede3ea.png)

2023-01-19 07:29 UTC, Tupinambis commented
So I like the sprites but I think the names are a bit crap.
I'd format it roughly as [Armor Class] [Aesthetic] [Type]

Ex: Light Scout Exosuit
Medium EVA Exosuit
Heavy Assault Exosuit
Xenonautin -> Light/Medium/Heavy Armor Vest
Scout Helmet
Xenonautin -> Open/Closed Combat Helmet 
Rownin -> Combat Harness 

Easy readability good, "Jaeger Skirmisher light exo" not even telling you the armor type until the third word is bad, especially for reading down a list.

2023-01-22 11:02 UTC, Lumipharon commented
Closing as I'm opening the new one.

2023-01-22 11:02 UTC, closed without merging