Introduces the Style Line of equipment
tgstation/TerraGov-Marine-Corps pull request #11934
Opened 2023-01-14 03:07 UTC by lKiseki

## About The Pull Request
Introduces the **Style** line of equipment. As its name may allude to, this line of equipment is specifically designed to prioritize style without compromising gameplay. It includes modular armors that accept common modules, plus three new modules designed specifically to alter the armor values of any given Style piece of equipment.
Currently, there are only two armors that form part of this line. More may be added later down the line if spriters feel like it.
##
### Style Line: The Rundown
- Features the Leather Jacket and the Duster, both of which have their own variants that can be acquired by using green facepaint on them.
  - The Duster is a new armor option that is part of the Style line. It has eight variants: drab, snow, black, desert, red, blue, purple, and gold.

![dustergaming](https://user-images.githubusercontent.com/59634950/212499855-b314f03d-f2b7-4193-a8d9-212132cb734d.png)
### Sprites courtesy of Fitz Sholl, from our Discord.
_( Dunno if they'd like me to add their Discord handle, but yeah. Credit where it's due, since the sprites aren't mine. )_
- These have their own category in the Armor vendor, dubbed "Style Line".
- Adds Equalizer armor modules. 
  - Equalizer modules alter the stats of armor to match that of existing armor presets (light, medium, heavy). These can only be used by the Style Line.
  - By default, the Style line of equipment has no armor and no movement penalties. 
- Existing storage and armor modules are compatible with this line of equipment.
  - Equalizer modules occupy their own equipment slot, meaning other modules remain usable with an Equalizer.
- The reinforced leather jacket and reinforced leather jacket with webbing have been refactored to become a single modular armor, now part of the Style line.
  - The webbing variant can now be acquired by using green facepaint on a Leather Jacket.
  - The leather jacket can be found in the new armor vendor category.

## Why It's Good For The Game
- Gives players a greater amount of freedom in terms of style without compromising important aspects of gameplay, such as armor and movement speed.
- Adds more armor options for player loadouts, all of which are compatible with existing storage and armor modules, making them as viable as any other option.

## Changelog
:cl: Lewdcifer
add: Introducing the Style line of equipment, designed to prioritize style without compromising gameplay.
add: Includes modular armors that accept existing storage and armor modules, available under their own category in standard armor vendors.
add: Three new armor modules have been added: the Equalizer modules. These only work with the Style line, and will alter their stats to match those of existing armor presets (light, medium, heavy).
add: All options have existing variants, accessible by using green facepaint on them.
add: A new armor addition to the game, the Duster, is part of this line of equipment.
refactor: The reinforced leather jacket and its webbing variant have been turned into a single item and merged into the Style line. Its webbing variant can be accessed by using green facepaint.
/:cl:

2023-01-14 03:11 UTC, Kuro020 approved these changes
TGMC NOW FEATURING DANTE FROM THE DEVIL MAY CRY SERIES

2023-01-14 03:19 UTC, lKiseki commented
![image](https://user-images.githubusercontent.com/59634950/212448423-55e62eef-7f28-4825-a93e-5f3e3d1d12c9.png)

2023-01-14 06:50 UTC, RaidarV commented
![Dante Laugh](https://user-images.githubusercontent.com/61937036/212459749-9916f3bc-07a8-4fb6-aae0-de9ba27b7266.png)

TGMC'S NEW EXPANSION NOW FEATURING MALESTATIC "Tonī Reddogureibu" FROM HIT SERIES "UNGA MAY COPE™®©"

2023-01-14 07:39 UTC, Tupinambis commented
We RimWorld now

2023-01-14 07:43 UTC, XSlayer300 commented on code/modules/clothing/modular_armor/attachments/modules.dm
> +	name = "\improper Armor Equalizer"
```suggestion
	name = "armor equalizer"
```

2023-01-14 07:44 UTC, XSlayer300 commented on code/modules/clothing/modular_armor/attachments/modules.dm
> +	name = "\improper Light Armor Equalizer"
```suggestion
	name = "light armor equalizer"
```

2023-01-14 07:44 UTC, XSlayer300 commented on code/modules/clothing/modular_armor/attachments/modules.dm
> +	name = "\improper Medium Armor Equalizer"
```suggestion
	name = "medium armor equalizer"
```

2023-01-14 07:45 UTC, XSlayer300 commented on code/modules/clothing/modular_armor/modular.dm
> +	name = "\improper Leather Jacket"
```suggestion
	name = "leather jacket"
```

2023-01-14 07:45 UTC, XSlayer300 commented on code/modules/clothing/modular_armor/modular.dm
> +	name = "\improper Duster"
```suggestion
	name = "duster"
```

2023-01-14 07:46 UTC, XSlayer300 commented on code/modules/clothing/modular_armor/modular.dm
> +	desc = "A light, loose-fitting long coat, for those that want to have more style."
```suggestion
	desc = "A light, loose-fitting colorable long coat, for those that want to have more style."
```

2023-01-14 10:06 UTC, wezsel11 commented
stops time and charges into the xeno with his japanese katana. The blade is inserted into the exoskeleton of the xeno piercing its organs. Vergilli teleports behind the xeno and returns time to normal. The xeno behind him explodes into a wave of gore. Xeno blood rains for a few seconds but all the drops seems to have missed Vergilli. Not one drop has fallen upon him and he laughs as he brushes off the dust from his shoulder. I says with a quiet voice: "You should have been more motivated."

2023-01-14 15:25 UTC, Kuro020 requested changes
you had to add in more colors didnt you, anyways
![image](https://user-images.githubusercontent.com/52428261/212479550-5cc6a8be-e7d4-469b-adeb-5f0c02a42cfb.png)
this shit is neon, desaturate it to be in line with the red and blue

2023-01-14 19:17 UTC, shelteredfreak commented
speed mergngfefneufn plz

2023-01-15 00:29 UTC, AtlasRules commented
I will pay whoever sprited these good money for two piece suits.

2023-01-15 00:34 UTC, shelteredfreak commented
bonus points if I can add arm plates and leg plates to it so I can have the Elite Riot Gear from Fallout New Vegas

Now I just need to find a helmet to match with a swat mask to top it all off....

2023-01-15 15:38 UTC, Kuro020 approved these changes

2023-01-15 15:52 UTC, Tailiik commented
> bonus points if I can add arm plates and leg plates to it so I can have the Elite Riot Gear from Fallout New Vegas
> 
> Now I just need to find a helmet to match with a swat mask to top it all off....

That would be cool except jaeger is going bye bye :'c 

Looks neat though

2023-01-15 19:16 UTC, Tupinambis commented
Should either only be one armor type or have different sprites for different levels of armor.

Also I thought we were doing away with non standard colors on armor.

2023-01-15 20:22 UTC, Coastfront commented
> > bonus points if I can add arm plates and leg plates to it so I can have the Elite Riot Gear from Fallout New Vegas
> > Now I just need to find a helmet to match with a swat mask to top it all off....
> 
> That would be cool except jaeger is going bye bye :'c
> 
> Looks neat though


Just make its tyr appearance have arm and leg plates for fallout new vegas.

2023-01-15 23:22 UTC, novaepee commented
![image](https://user-images.githubusercontent.com/6610922/212572775-f48f5ce8-d7b1-426a-aaf3-d532cde0688d.png)

xeno winrates died because of drip

2023-01-16 10:46 UTC, RaidarV commented
![image](https://user-images.githubusercontent.com/61937036/212660002-53332ea8-4017-4ee0-8c26-b98ddd3c124e.png)

YOU CANNOT KILL MEEEE

I AM UNGAAA

2023-01-16 19:38 UTC, Aporhtonoma commented
beautiful but uuuh where pink?

2023-01-20 17:39 UTC, TiviPlus approved these changes

2023-01-20 17:39 UTC, merged