Xenomorphs EORD respawn
tgstation/TerraGov-Marine-Corps pull request #11946
Opened 2023-01-16 00:11 UTC by hyper2snyper

## About The Pull Request

You can respawn as a primordial xenomorph in EORD respawn!

Support for hiveless xenos.

## Why It's Good For The Game

More EORD fun!

## Changelog

:cl:
add: xenomorphs EORD respawn!
/:cl:

2023-01-16 00:16 UTC, novaepee commented
![image](https://user-images.githubusercontent.com/6610922/212575279-43aaa6fe-c67e-4517-849e-2bfc156de892.png)

2023-01-16 03:29 UTC, shelteredfreak commented
Primordial Bagilite (Kicking Bird) has risen to lead the hive!

Hey, as long as I live long enough to see this go in, all is well.

2023-01-17 04:23 UTC, carlarctg commented on code/modules/mob/living/carbon/xenomorph/castes/king/king.dm
> +			name = "[hive ? hive.prefix : "Disowned "]King ([nicknumber])"	 //Young
i think it'd be awesome if you changed 'Disowned' to 'Feral' to symbolize how they're wild and hiveless

optional: darken hiveless xenos to differentiate them as well

2023-01-20 18:02 UTC, TiviPlus requested changes

2023-01-25 03:00 UTC, Luxyboo commented
can you make xeno respawn a choice rather than random chance?

2023-01-26 17:34 UTC, carlarctg commented
bugs i noticed: your pheromones don't actually buff you, even though you do emit them, presumably because of hive shenanigans

same with weeds - you don't seem to heal from them? i might be wrong

and of course no xeno abilities work in xvx but that's out of scope

2023-01-26 20:41 UTC, Ragecrabbo commented
> bugs i noticed: your pheromones don't actually buff you, even though you do emit them, presumably because of hive shenanigans
This is a thing even with non-snowflake xenos in EORD, im guessing the round ending might be the cause of this(?)
> same with weeds - you don't seem to heal from them? i might be wrong
Weeds take 10 seconds of not taking any damage before they start to heal you if you lack recovery pheros because the evil coder cabal wants to oppress poor innocent xenomains.

2023-01-29 04:08 UTC, Liznerd commented
eh i prefer to keep it all humans in EORD, Benos just get spawned in the middle of a ton of humans and they get WIPED

2023-02-01 05:17 UTC, Durbles commented
After playing a lot of EORDs with this testmerged it's a really fun change. 10/10.

2023-02-04 14:30 UTC, FosterGrime-Heymynameslouie commented
are there select xenos that dont get spawned in?
rarely see defilers, carriers and widows

also pheros dont seem to work, they have the outline whenver you select the phero but dosent actually get filled up, I assume this is because of different teamed hives?

cool change 11/5

2023-02-05 05:21 UTC, carlarctg commented
it would definitely be great if more xeno types were spawnable, maybe as player preference

im a bit tired of the endless queen and king spam in eord. where are the widows and spitters and bulls! is plasma the issue? give zenos infinite plasma during eord.

2023-02-17 01:40 UTC, Lumipharon commented
bxzzzzt

2023-02-28 00:47 UTC, closed without merging