New cosmetic robot types
tgstation/TerraGov-Marine-Corps pull request #11993
Opened 2023-01-21 07:13 UTC by Blundir

## About The Pull Request

Adds 4 new cosmetic robot types, sprites by The Lord#9786, with small edits by me.
![dreamseeker_z8eatjjXHM](https://user-images.githubusercontent.com/100090741/213848312-8355c871-41e8-41f1-961b-9744c87b71f9.png)
![dreamseeker_YaSyVRk5kP](https://user-images.githubusercontent.com/100090741/213848318-3825223a-bcb7-4a53-806c-6be2726e3c32.gif)
![dreamseeker_sE6sFESpfT](https://user-images.githubusercontent.com/100090741/213848327-54810e22-139b-466c-a7d3-56e2cf702cdb.gif)
![dreamseeker_AX1uXB4dBD](https://user-images.githubusercontent.com/100090741/213848330-223ad1b2-8ec7-40ac-aee2-53bb62b59ffe.gif)
![dreamseeker_ybPH3UNS6u](https://user-images.githubusercontent.com/100090741/213848333-df38af54-400a-400f-a226-569c47ca749e.gif)

You can pick up robot type at character editor
![QDw898Vp5e](https://user-images.githubusercontent.com/100090741/213848366-7fe62622-1423-44e4-b3d3-69c8b9bba8d7.png)

Also new robot types have corresponding sprites for huds
![dreamseeker_hvRa58CZLh](https://user-images.githubusercontent.com/100090741/213848380-9f94e445-9cf3-450c-aae9-1ecea7b81554.png)

## Why It's Good For The Game

More variety to a customization poor race.

## Changelog

:cl:
add: Added 4 new cosmetic robot types
/:cl:

2023-01-21 07:25 UTC, Coastfront commented
While I do not like these sprites, even a mound of dirt stands taller than a voided flat plane. And they look better than what already exists.

god please allow robots to sculpt even a pitable face beyond their preset look

2023-01-21 07:32 UTC, zee11zee commented
Alpha is looking excellent, I would like to say if this is going through I will be a Robo main

2023-01-21 17:40 UTC, Kuro020 commented
Gonna have to test these with the new robot armor sprites before i approve it

2023-01-21 19:25 UTC, Blundir commented
> Gonna have to test these with the new robot armor sprites before i approve it

I can just make sprite sheets for it, in case there'd be any problem

2023-01-21 19:59 UTC, GreatKingWombat commented
Any way to add an auto option, if you don't have a preferred squad set?

2023-01-21 23:42 UTC, Blundir commented
> Any way to add an auto option, if you don't have a preferred squad set?

They aren't connected to squad code in any way and their squad aesthetics are trivial, nothing stops you from using non corresponding ones.

2023-01-22 11:34 UTC, Al-1ce commented
> They aren't connected to squad code in any way and their squad aesthetics are trivial, nothing stops you from using non corresponding ones.


It shall remain an unwritten rule.

2023-01-23 19:17 UTC, Kuro020 approved these changes

2023-02-02 11:59 UTC, Ragecrabbo commented
These look really nice although im not a fan of the red bandana thing (eye?) on the blue robot and the skins kinda blend in to the background floor sprites too much but otherwise these are solid quality and i really enjoy the animated visors.

2023-02-02 13:21 UTC, TiviPlus requested changes
Some parts are stinky but its not your fault fix these and its fine

2023-02-02 13:21 UTC, TiviPlus commented on code/datums/jobs/job/terragov.dm
> +					return /mob/living/carbon/human/species/robot/bravada
You can just early return here with (GLOB.join_as_robot_allowed)

2023-02-02 13:21 UTC, TiviPlus commented on code/game/objects/items/storage/backpack.dm
> +		"Ratcher Combat Robot" = 'icons/mob/species/robot/backpack.dmi')
```suggestion
		"Hammerhead Combat Robot" = 'icons/mob/species/robot/backpack.dmi',
		"Ratcher Combat Robot" = 'icons/mob/species/robot/backpack.dmi',
		)
```

2023-02-02 13:21 UTC, TiviPlus commented on code/game/objects/items/storage/holsters.dm
> +		"Ratcher Combat Robot" = 'icons/mob/species/robot/backpack.dmi')
```suggestion
		"Hammerhead Combat Robot" = 'icons/mob/species/robot/backpack.dmi',
		"Ratcher Combat Robot" = 'icons/mob/species/robot/backpack.dmi',
		)
```

2023-02-02 13:21 UTC, TiviPlus commented on code/game/objects/items/storage/holsters.dm
> +		"Ratcher Combat Robot" = 'icons/mob/species/robot/backpack.dmi') //robots have their own snowflake back sprites
```suggestion
		"Ratcher Combat Robot" = 'icons/mob/species/robot/backpack.dmi',
		)
```

2023-02-05 08:40 UTC, merged