Jaeger update
tgstation/TerraGov-Marine-Corps pull request #12000
Opened 2023-01-22 11:02 UTC by Lumipharon

## About The Pull Request
Finishing the Jaeger mk.II PR since MJP died to death.
Still WIP as I need to resolve an issue with allowing hair to correctly show masked, but fully functional otherwise.

Updates Jaeger to kill hyperscale colours and lego construction.
Updates all Jaeger types including fresh palettes (this also applies to Xenonauten), as well as adding the new Gungnir heavy jaeger suit.

![image](https://user-images.githubusercontent.com/7869430/213912243-8d1e3f08-0133-4bf5-b2ed-3dc929516c04.png)
![image](https://user-images.githubusercontent.com/7869430/213912245-b2e0f431-3815-465d-9abd-39af5b07ba51.png)

This will cause most loadouts to implode due to the removal of the XM02, but such is life.

## Why It's Good For The Game
Better maintainability compared to hyperscale on the spriter end, better overall look than grayscale. Hyperscale was made in mind with the tool to make it sane to use that never came out, and lego pieces are hard to maintain as well, and aren't used, and cause a lot of confusion for new players.
The mass of colors makes the marine force look like power rangers, this alleviates that overall, and makes the art style more consistent and in line with itself.

## Changelog

:cl:
add: New map variants colors for Jaeger/Xenonauten.
add: Gungnir heavy jaeger armour
del: Jaeger is now an armour and helmet set, no more lego pieces
del: Removed hyperscale colours from Jaeger
/:cl:

2023-01-22 11:33 UTC, Al-1ce commented
Standardization? Standardization. +1 from me.

2023-01-22 12:35 UTC, Aporhtonoma commented
marine drip nerf pr is here

2023-01-22 15:22 UTC, Kuro020 approved these changes
How many prs it takes to kill a jaeger?

2023-01-22 17:33 UTC, chizzy376 commented
Amazing, lovely stuff, even got the digits on the PR. Can't wait for PR #13000 to remove Jaeger entirely.

2023-01-22 17:52 UTC, novaepee commented
FOURTH #11859 TIME #11865 THE #11932 CHARM!

2023-01-22 18:18 UTC, FIXTHERADBOXPLEASE commented
"My specific, perfect, entirely infalliable brand of Jaegar Removal HAS NEVER BEEN TRIED."
Jokes aside, Marines have needed a nerf for a long time. I'm correctly calculating that the mental effects from this PR will be far more damaging to Marine performance than any numbers adjustment.

2023-01-23 01:23 UTC, shelteredfreak commented
A sad necessity, but I can cope with it (haha) only if more Jaeger suits get added as time goes by. 

I will miss my Scout Helmet, Assault/Scout Chest, Assault Armplates, Helljumper Legplates drip. But maybe more drip is to come, even if it is less customizable.

2023-01-23 04:51 UTC, Tailiik commented
The new stuff looks good but I am coping about losing visor recolor

2023-01-24 22:26 UTC, Kuro020 commented
> A sad necessity, but I can cope with it (haha) only if more Jaeger suits get added as time goes by.
> 
> I will miss my Scout Helmet, Assault/Scout Chest, Assault Armplates, Helljumper Legplates drip. But maybe more drip is to come, even if it is less customizable.

they will, this pr has a new one already, gugnir

2023-01-25 14:03 UTC, Kuro020 commented
> Keep the option to remove specific plates like leg and arm plates for funny builds.

the sprites arent lego

2023-01-30 04:24 UTC, novaepee commented
> You should make it so we can colour the armors the same colours jeager already had, i will support this only if I can paint my armor angelic gold/honey/red colours >:|

Kuro says no.

2023-02-01 05:14 UTC, Durbles commented
As much as I like the sheer customizability of jaeger I think some standardisation is in order, so I think this PR is good :)

2023-02-01 14:11 UTC, spookydonut approved these changes

2023-02-01 15:51 UTC, Starfirejordan commented
Inb4 the server blows up and rages

2023-02-01 16:10 UTC, docRoboRobert commented
Skirmisher helmet goes invisible when painted, on EOD armor when facing west modules turn invisible

2023-02-01 16:21 UTC, docRoboRobert commented
All modules still have the old sprites

2023-02-01 17:12 UTC, Kuro020 commented
style line cant attach the armor anymore with this pr

2023-02-01 19:11 UTC, Jalopkomit18 commented
When you color skirmisher jaegar drab, the sprite goes invisible.

2023-02-01 19:32 UTC, RaidarV commented
Green/Drab isn't green.

2023-02-01 20:50 UTC, Ragecrabbo commented
my customizable armor...

2023-02-01 23:25 UTC, Al-1ce commented
After experiencing this, I can't really say I like it all that much.

2023-02-02 00:53 UTC, XANAv2 commented
I tend to agree with the majority of the comments, I really miss my old colorable armor, the Xenonauten armor sets were meant to be for people who didn't understand jaeger.  Give us back our colorable armor REEEEEEEEEEEEEEEEEEEEE

2023-02-02 01:02 UTC, Tailiik commented
Drab skirmisher either has no sprite or is improperly set, it turns invisible when you make it drab. 

Also the color schemes are kinda fugly, I get wanting to standardize the colors but the drab isn't even close to matching the existing drab stuff.

2023-02-02 01:21 UTC, Tupinambis commented
Sideways armor sprites being angled when literally nothing else is makes them look really ugly tbh, and I don't really dig the glowing visors.

Visors could use more color options, armor in general could get a color pass, and I think side sprites should be in line with every other armor sprite instead of being angled akwardly.

2023-02-02 01:22 UTC, Lumipharon commented
> Sideways armor sprites being angled when literally nothing else is makes them look really ugly tbh, and I don't really dig the glowing visors.
> 
> Visors could use more color options, armor in general could get a color pass, and I think side sprites should be in line with every other armor sprite instead of being angled akwardly.

visors have always glowed, this is unchanged. You can toggle it off on your helmet.

2023-02-02 01:23 UTC, Strayed-Raven commented
Sideways sprite theme is wack looking on Gungir helmet. You can see the green dot eye no matter what side the helmet faces. Even though it is on the way side of the left

2023-02-02 03:19 UTC, Coastfront commented
It takes an angle of talent immeasurable by conventional efforts, to not only replace a stone walls brick, but to have the replacement weaken it further than a gap would.

The only nice thing I have to say about this is that it kills the lego.

95% of the reason people would wear jaeger, was for color customization. Since that's getting the axe why must we dig up a fetid rotted corpse over just burying it. 
A silent symphony is allowed no ensemble, non-customizable jaeger should meet no gaze.

2023-02-02 03:34 UTC, Tailiik commented
> 

_What_

So many hidden ass mechanics in ss13

2023-02-02 12:54 UTC, aGhostCoder commented
I know this PR will be merged but I will make it clear that I no longer plan to help, or add, anymore drip as I had already made my frustrations clear. Anything I was doing is now cleared, sorry to any obligations I promised. _Seeing every player I had talked to for months now tell me in game, and privately, their frustrations I can safely say the reason I even began helping again no longer exists._ I don't wish to contribute to a code-base seemingly so focused on changing things for the sake of change.

I don't understand why you only made four variants, and even more that their difference is literally just a complete color-hue.
I don't understand: **"-cause a lot of confusion for new players."**
Xenonaut was the answer for that said confusion, but even then it takes a minute to teach how it works. Not only that but it actually encourages communication; it's usually the first conversation that forces a player to actually communicate.
_Furthermore do we hold Xeno's hands when they don't understand random mechanics?_ I would say not, considering we actively joke about it being a skill-issue. We don't hold this position for literally anything else.
I don't understand: **"The mass of colors makes the marine force look like power rangers, this alleviates that overall, and makes the art style more consistent and in line with itself."**
This reasoning never made sense to me because what is our art-style? Our art style was this for about roughly three years.
Mecha isn't our art style but we added it anyways: That reasoning can easily apply to capes, and every other item, because the reasoning comes across as: "I don't like it when people make themselves look stupid." You could've just removed the colors you don't like. Like pink, a color no one even uses the majority of the time.

I wish you luck with your development, but I'm done. Please take care.

2023-02-02 13:04 UTC, AtlasRules commented
welp i think the reason above is enough reason to not merge this pr

2023-02-02 20:06 UTC, Alexeivichi commented
I know I'm back pedaling with my previous opinions but I fully agree with Ghost. I'm back pedaling because reassurances were kind of broken and I was too hopeful. The end product from this PR doesn't appeal to me. And by people's reactions, it doesn't appeal to them either.

I don't want to speak for Bird/Hyper2Snayper who worked on the colouring, but I'm frankly upset and share his frustration that he didn't get to do more for Jaegar to expand our cosmetic options which he has stated he wanted. The man's made visorless versions and those sadly never saw the light of day, and frankly it would have been amazing to have those even if we never would have gotten the retractable visors that TGMC once talked about and instead got the open-pattern infantry helmet as a compromise.

Having Jaegar customization and construction was a massive plus for TGMC over the standardization of CM. The reasons that Jaegar has to be killed so people will stop using 'god awful colours' is generally a poor idea because you're also executing people who enjoy good and easily identifiable colour schemes. For everyone terrible Jaegar you see, you see dozens upon dozens of 

The arguement that Jaegar is too confusing to new players doesn't work well. Anedotically: My wife who's played TGMC, who has used Xenonauten out of fear of Jaegar being too complicated and is extremely reluctant to learn new things in fear of excessive stress, LEARNED Jaegar out of the sheer fact it looked amazing, and made it her main stay.

Non-anedotically, and generally speaking, SS13 has a hell of a learning curve with a large amount of its systems and mechanics, and anyone who's committed to playing the game would not be turned away from Jaegar, as you can easily find new players who at first use Xenonuaten/PAS before turning over to Jaegar for an upgrade with better aesthetics and a personalized touch.

Anyways, enough of my blind rant. This isn't a good PR to replace a clearly superior system (Which sadly has 'to go' because it APPARENTLY lacks maintenance in the code, according to what I've been told in the general development discord channel). I'll end it with a bit of vitriol too before I get a gitbanned for toxicity by people who have formerly engaged in the same toxic behaviour and faced bans for it (You know who you are.):

It is fucking hilarious that people claiming to be artists and such of different technical field lacking the skin and temperament to actually take criticism in its full glory and work in improving themselves on a general feedback instead of roleplaying a digital ostrich. Credit where credit's due: There have been times when said people have improved upon things upon backlash, but we keep going back to Square 1 with how things are conducted sometimes. While it's 100% encouraged to punish and ban those who maliciously attack our community members and contributors with no other intent than causing harm, a promise arises when people giving valid criticism are given the same treatment to the point that even administrative staff have become fed up and disillusioned with the state of the development hell that TGMC experiences. I've seen this time and time again: It creates and echo chamber when you shut yourself off and don't listen to the general opinion. You become a distorted disillusioned version of what you want and you socially alienate people, but if you find people who share that and make friends with them instead... Have fun and goodbye.

This PR and armor hasn't broken me as I'm a Xenonauten-main, but it has disrupted a lot of people's interest in the game and alienated quite a few. I share their frustration.  If you want to know, ask them to speak up. Ghost clearly shows that he's a good example of those kinds of people fed up with it.

(Point out whatever typos or criticisms you like, I'm tired. I'm no doubt in the wrong with this rant, but I've stopped caring and I found it's better to just move on honestly for all of our sakes.)

Aleksey clocking out. It's been real. I welcome the next generation of players to keep TGMC's corpse alive until it's reborn into whatever it sees fit.

2023-02-02 20:14 UTC, Coastfront commented
On the arguement for "art style" when are capes, mechs, half of synths wackier outfit options, etc getting removed.

The cares of all of 5 people for the artstyle are and should be drowned by the majorities ocean of apathy towards the games art direction. Nobody who we should actually cater to cares about the games art style because people only care about the gameplay for the most part.

2023-02-02 20:40 UTC, Kuro020 commented
The art style argument was wroten by mjp, I have always said the same thing about why hyperscale is being removed, the system works fine on paper but making dmis for it is time consuming as all hell, and having a section of sprites on the server that can never be touched because it's literally painful to do so does not seem reasonable to me, and that is why its gonna get removed.

Hyper made a tool to solve that but the tool doesnt work, I've been asking about the status on it getting fixed for about 6 months now and it hasnt moved an inch, so I'll take it that its never gonna get fixed at all.

I won't comment on "shutting down criticism" because honestly it would be a waste of time on my part, this pr has been up for two weeks, the sprites were constantly posted on the server, and only when it got TMed did I receive "feedback" (It was just a bunch of yelling on artwork, and I didnt ask for a slowdown on the channel or deletes any messages either).

If people are gonna leave over this pr, its their right to do so, they don't have to agree with the way I'm handling our sprites but the decision to remove hyperscale is done.

2023-02-02 22:41 UTC, Lumipharon commented
UnTM'd until updated.

Updates on what is happening.
Lego will return. The default vendor will just vend the stand armor/hat set, but old lego will be available via the surplus vendor so will work fine in loadouts.

Hyperscale stays dead. As previously stated it's a maintainability issue not an art one. PR desc was just copy pasta of what MJP wrote so I'll update that in a sec.

Colours will be the four map colours, and the four squad colours.

So you won't be able to have hot pink/baby blue funni unga, but there should still be a lot of colour variation between lego bits and 8 colours.

Apologies if the changes have not been to people's liking so far, but hey, that's why it was only TM'd.

2023-02-02 23:40 UTC, aGhostCoder commented
Lumi actually contacted me, and I appreciate them reaching out to me. So I'd like to further clarify onto what I said in case anyone reads this message: I do understand why hyperscale is dying, I don't agree that it's unmaintainable but it is incredibly tedious and annoying to set up new sprites. So fair enough to that end.

I will also point out, like I did privately, a fun fact for everyone to know: It's useful a lesson.
In another server, unrelated to SS13, I was hosting a halloween costume event. I spent a month planning said event, told everyone repeatedly about the event. I had repeatedly said this fifty times in text, and voice, posted it three times in announcements: Do you know what happened on the day of the event? There were still people who complained I didn't tell anyone. How? Because someone might be away for that month, someone might not read the github or discord, and in fact that someone might just live a under actual rock.

I still plan to take my leave, as I feel it's important to take a step back and breathe. Besides I have to deal with this daily, so I have to rebuild my energy.
![image](https://user-images.githubusercontent.com/88966002/216475386-0b608376-cfe9-44b8-9eab-13f7fd54110b.png)

2023-02-03 05:40 UTC, Durbles commented
> Coastfront

If the artstyle of this game doesn't matter then you should have zero comment on this PR, since it doesn't matter and no-one cares.

2023-02-03 09:41 UTC, Al-1ce commented
> If the artstyle of this game doesn't matter then you should have zero comment on this PR, since it doesn't matter and no-one cares.



I... think you may be lliterate or fail to understand that we do _not_ actually have a defined artstyle. This server is a frankenstein of dozens of spriters with their own unique takes on the setting and style.

MAYBE, just _perhaps_ if you're too dull to actually provide any meaningful feedback, it would be better not to comment at all.

2023-02-03 22:20 UTC, LoveMirror commented
> > If the artstyle of this game doesn't matter then you should have zero comment on this PR, since it doesn't matter and no-one cares.
> 
> I... think you may be lliterate or fail to understand that we do _not_ actually have a defined artstyle. This server is a frankenstein of dozens of spriters with their own unique takes on the setting and style.
> 
> MAYBE, just _perhaps_ if you're too dull to actually provide any meaningful feedback, it would be better not to comment at all.

Tell that to Kuro and get promptly evicted from the artwork channel.
Such is life on niche ss13 gamemodes.

2023-02-05 01:50 UTC, Durbles commented
> > If the artstyle of this game doesn't matter then you should have zero comment on this PR, since it doesn't matter and no-one cares.
> 
> I... think you may be lliterate or fail to understand that we do _not_ actually have a defined artstyle. This server is a frankenstein of dozens of spriters with their own unique takes on the setting and style.
> 
> MAYBE, just _perhaps_ if you're too dull to actually provide any meaningful feedback, it would be better not to comment at all.

Calm down buddy pal.

2023-02-05 02:46 UTC, SilencedMP5A5 commented
> UnTM'd until updated.
> 
> Updates on what is happening. Lego will return. The default vendor will just vend the stand armor/hat set, but old lego will be available via the surplus vendor so will work fine in loadouts.
> 
> Hyperscale stays dead. As previously stated it's a maintainability issue not an art one. PR desc was just copy pasta of what MJP wrote so I'll update that in a sec.
> 
> Colours will be the four map colours, and the four squad colours.
> 
> So you won't be able to have hot pink/baby blue funni unga, but there should still be a lot of colour variation between lego bits and 8 colours.
> 
> Apologies if the changes have not been to people's liking so far, but hey, that's why it was only TM'd.

we appreciate you listening to us

2023-02-05 03:19 UTC, Kuro020 commented
Update, lego jaeger will not have squad colors on this pr because lego is ass to recolor (surprise), someone else can do it and suffer later

2023-02-06 00:03 UTC, chesse20 commented
me ghosting every round that i don't get charlie squad becuase i can't have purple armor

2023-02-06 03:03 UTC, Kuro020 commented
> Update, lego jaeger will not have squad colors on this pr because lego is ass to recolor (surprise), someone else can do it and suffer later

Another update after enslavi- I mean convincing some discord fellas to do my job for me (thanks mjp and poofy heart heart heart) squad colors are gonna happen again

Uhu

2023-02-06 03:03 UTC, Kuro020 commented
> me ghosting every round that i don't get charlie squad becuase i can't have purple armor

all colors are available to everyone, its not squad locked

2023-02-06 20:46 UTC, Xsdew commented
> Will we have the jeager colours though, squad colours is one thing but what we really want is the classic jeager colour variants.

Only Map and Squad Colors.

2023-02-06 20:48 UTC, TiviPlus commented
if I have to mark one more comment as off topic im locking this PR and noone may comment so behave

2023-02-07 16:27 UTC, TiviPlus requested changes
Im not reviewing the rest this PR is ridiculous
You lump like 5 completely unrelated changes together into an unreviewable soup

For starters what I can easily see being split:
badges
capes
old armor
new armor

ping me on discord if you want to argue otherwise

2023-02-07 16:27 UTC, TiviPlus commented on code/modules/clothing/modular_armor/attachments.dm
> +	INVOKE_ASYNC(src, /atom/proc/attackby, I, user)
.proc

2023-02-07 16:27 UTC, TiviPlus commented on code/modules/clothing/modular_armor/attachments.dm
> +	//greyscale_config = /datum/greyscale_config/modularchest
?

2023-02-11 18:00 UTC, TiviPlus requested changes

2023-02-11 19:59 UTC, novaepee commented on code/__DEFINES/equipment.dm
> +#define HIDE_EXCESS_HAIR (1<<11)	//Trims hair based on an alpha mask, but still allowing ponytails etc.
FOR ME

2023-02-11 21:26 UTC, Lumipharon commented on code/modules/clothing/modular_armor/attachments/visors.dm
> +	greyscale_colors = "#ffffff"
done

2023-02-11 21:27 UTC, Lumipharon commented on code/datums/greyscale/json_configs/cape.json
>  			"type": "icon_state",
Is there an issue with putting them in one config? And nothing is hyperscale now, so do they actually interact with ssgreyscale?

2023-02-11 21:27 UTC, Lumipharon commented on code/datums/greyscale/json_configs/old_visors.json
> +		}
Is this an issue?

2023-02-11 21:37 UTC, Lumipharon commented on code/game/objects/machinery/vending/marine_vending.dm
> +			/obj/item/clothing/head/modular/marine/old/skirmisher = -1,
they're deprecated and won't be touched, apparently. Made a gorillion categories though.

2023-02-11 21:49 UTC, Lumipharon commented on code/modules/clothing/modular_armor/attachments/cape.dm
> +	greyscale_colors = "#ffffff"
done

2023-02-11 21:49 UTC, Lumipharon commented on code/modules/clothing/modular_armor/attachments/cape.dm
> +	greyscale_colors = "#a51c1c"
done

2023-02-11 21:50 UTC, Lumipharon commented on code/modules/clothing/modular_armor/attachments.dm
> +		to_chat(user, span_warning("\the [paint] is out of color!"))
done

2023-02-11 21:52 UTC, Lumipharon commented on code/__DEFINES/equipment.dm
> +#define HIDE_EXCESS_HAIR (1<<11)	//Trims hair based on an alpha mask, but still allowing ponytails etc.
?

2023-02-11 21:53 UTC, Lumipharon commented on code/modules/clothing/modular_armor/attachments/chest_plates.dm
> +	icon = 'icons/mob/modular/old_jaeger/chest_plates.dmi'
it is still jaeger, codewise and sprite wise, as discussed in discord.

2023-02-11 21:53 UTC, Lumipharon commented on code/modules/clothing/modular_armor/attachments.dm
> +	examine_list += "Right click the [parent] with paint to color the [src]"
done

2023-02-11 21:53 UTC, Lumipharon commented on code/modules/clothing/modular_armor/attachments.dm
> +/obj/item/armor_module/proc/handle_color(datum/source, obj/I, mob/user)
done

2023-02-11 21:57 UTC, Lumipharon commented on code/modules/clothing/modular_armor/attachments.dm
> +	greyscale_colors = "#ffffff"
done

2023-02-11 21:59 UTC, Lumipharon commented on code/game/objects/machinery/vending/new_marine_vendors.dm
> +	desc = "A set of light Xenonauten pattern armor, including an armor suit and a fancier helmet."
MJP pls. done

2023-02-11 21:59 UTC, Lumipharon commented on code/game/objects/machinery/vending/new_marine_vendors.dm
> +	desc = "A set of heavy Xenonauten pattern armor, including an armor suit and a fancier helmet."
done

2023-02-11 22:09 UTC, Lumipharon commented on code/modules/clothing/modular_armor/attachments.dm
>  	update_icon()
I unno, I didn't touch this. done

2023-02-11 22:09 UTC, Lumipharon commented on code/modules/clothing/modular_armor/attachments.dm
> -		if(FACTION_TERRAGOV)
because its unused, civil war is dead (don't ask me to kill all the code)

2023-02-11 22:10 UTC, Lumipharon commented on code/modules/clothing/modular_armor/attachments.dm
> +	update_icon()
whoops

2023-02-11 22:12 UTC, Lumipharon commented on code/modules/clothing/modular_armor/attachments/badges.dm
whoops, they're suppose to be a child of greyscale, not armor

2023-02-11 22:13 UTC, Lumipharon commented on code/modules/clothing/modular_armor/modular.dm
> +	desc = "A Infantry-pattern Jaeger combat exoskeleton made to work with modular attachments for the ability to function in many enviroments. This one seems to have a moderate amount of armor plating.
done

2023-02-11 22:13 UTC, Lumipharon commented on code/modules/clothing/modular_armor/attachments/visors.dm
>  	slot = ATTACHMENT_SLOT_VISOR
they're greyscale

2023-02-11 22:13 UTC, Lumipharon commented on code/modules/clothing/modular_armor/modular.dm
>  /obj/item/clothing/suit/modular/xenonauten
done

2023-02-11 22:13 UTC, Lumipharon commented on code/modules/clothing/modular_armor/modular.dm
> +	name = "XR-1 armor plating"
done

2023-02-11 22:13 UTC, Lumipharon commented on code/modules/clothing/modular_armor/modular.dm
> +/obj/item/clothing/head/modular/robot
done

2023-02-11 22:13 UTC, Lumipharon commented on code/modules/clothing/modular_armor/modular.dm
> +	name = "Jaeger Mk.I Pattern Infantry Helmet"
done

2023-02-11 22:14 UTC, Lumipharon commented on code/datums/elements/special_clothing_overlay.dm
>  		special_icon = SSgreyscale.GetColoredIconByType(greyscale_type, list(color_string))
As below, all greyscale attachments use the same setup for sanity and easier maintainability, even if they have only one layer.

2023-02-13 13:33 UTC, FosterGrime-Heymynameslouie commented
this pr killed ghost and he died of death for the 2nd time this makes me incredibly sad
Godbless his soul

2023-02-13 15:11 UTC, TiviPlus requested changes

2023-02-13 15:11 UTC, TiviPlus commented on code/__DEFINES/equipment.dm
> +#define HIDE_EXCESS_HAIR (1<<11)	//Trims hair based on an alpha mask, but still allowing ponytails etc.
what does this comment even mean

2023-02-13 15:11 UTC, TiviPlus commented on code/datums/elements/special_clothing_overlay.dm
>  		special_icon = SSgreyscale.GetColoredIconByType(greyscale_type, list(color_string))
terrible but ok

2023-02-13 15:11 UTC, TiviPlus commented on code/game/objects/machinery/vending/marine_vending.dm
> +			/obj/item/clothing/head/modular/robot/heavy = -1,
This is still soup

2023-02-13 15:11 UTC, TiviPlus commented on code/modules/clothing/modular_armor/attachments/badges.dm
in that case do they inherit the necessary defaults

2023-02-13 15:11 UTC, TiviPlus commented on code/modules/clothing/modular_armor/attachments/chest_plates.dm
> +	icon = 'icons/mob/modular/old_jaeger/chest_plates.dmi'
as discussed in discord change it

2023-02-13 20:05 UTC, Lumipharon commented on code/modules/clothing/modular_armor/attachments/badges.dm
yes

2023-02-14 03:27 UTC, RoyalEntomologist commented
i can get behind the need case for this, since super modularized clothing is a nightmare to maintain; however, i personally don't enjoy this just because of the execution alone. the sprites need a lot of love. 

personally i'm also not totally sure i understand why combat robot armors were changed out for new sprites and modularization couldn't just be added? mildly related but allowing for such stuff as engineering storage modules on the armor actually feels like a significant balance implication since it's upping the slots robos have for their healing doodads from 2 to 5 (alternatively, i can completely free up one pocket i usually use for a tool pouch)

other miscellany: 
- combat robot helmet icons are broken and appear as the error icon
- the engineering storage module has no set sprite and appears invisible
- robot armor sprites are mis-aligned on n/s facing views
- i think the helmets might also be misaligned on the n/s views

yea. good idea, execution needs a significant amount more spriter investment

2023-02-14 03:44 UTC, Lumipharon commented
All the issues are already fixed. engie modules aren't invisible, they're just asspouches now. Ask whoever sprited them

2023-02-14 05:27 UTC, novaepee commented
![image](https://user-images.githubusercontent.com/6610922/218647388-c0f483e3-95df-43b5-8d28-8175ef5a8c42.png)

![image](https://user-images.githubusercontent.com/6610922/218647415-6aa5547c-66ef-4cb4-8c51-a1c8424afba6.png)

infantry open helmet for bravo, charlie, and delta have no side and back sprites. Also, infantry open helmet hides face.

2023-02-14 17:36 UTC, Zaffinomlb commented
Dogshit PR

2023-02-14 19:47 UTC, Kuro020 commented
> Zaffinomlb reads my mind, I don't like this PR.

That's alright, nobody has to agree with colors going, but this is a maintainability problem so this has to happen regardless. I recognize that people like colors, and so as a means to try and reach halfway I did 8 colors, kept old jaeger, redid robros and xenonauten and added the  8 new nu jaeger sets, thats the best that can be done

2023-02-14 20:27 UTC, Kuro020 commented
> > > Zaffinomlb reads my mind, I don't like this PR.
> > 
> > 
> > That's alright, nobody has to agree with colors going, but this is a maintainability problem so this has to happen regardless. I recognize that people like colors, and so as a means to try and reach halfway I did 8 colors, kept old jaeger, redid robros and xenonauten and added the 8 new nu jaeger sets, thats the best that can be done
> 
> If it has to happen then so be it, sorry if I was overly negative on the matter, i agree that a lot of bright rainbow colours for the marines makes the round look sillier but I would say a good compromise would be to make most of the stand-out colours like purple to be darkened as to blend them together with a base black/grey pattern or just remove the light/bright variations of a color group (I mean like the jeager armor red color options, instead it would be one red color theme) I'm also completely fine with armor no longer being divided into pieces.

its not about how it looks, its about hyperscale being incredibly frustating to work with, the dude that made helljumper instantly burnt out after doing it because of how bad it is, this is a pr to save tgmc spriter's sanity

2023-02-14 20:30 UTC, srxtreme commented
This happened three days after one of the maintainers played TGMC. Salt PR?

2023-02-14 21:47 UTC, Tailiik commented
![jaeger oof](https://user-images.githubusercontent.com/71854016/218870603-023e73e3-b7eb-4ce5-8119-3a86feb66833.png)

With this newest version jaeger armor loads from loadouts invisible, and also helmet visor colors don't save

2023-02-14 21:59 UTC, RaidarV commented
I uhh

I still don't liek the colors man.

2023-02-14 22:47 UTC, Kuro020 commented
> I uhh
> 
> I still don't liek the colors man.

noted, but any color changes come after merge, this pr is huge and has been up for too long

2023-02-14 23:38 UTC, Zaffinomlb commented
There seems to be issues where changing the color on some of the new and old jaeger sprites just turns the items invisible entirely. Another issue persists where in spawning a saved loadout with the new items causes visors to just be removed entirely.

An aside why not just to the deed right and just kill jaeger instead of mulling about poking at it slowly dying?

2023-02-15 01:52 UTC, pilotmans commented
This is beautiful, good thing I don't know the difference between gray scaling or hyper-scaling or i could have been very sad.

2023-02-15 02:40 UTC, Lumipharon commented
> There seems to be issues where changing the color on some of the new and old jaeger sprites just turns the items invisible entirely. Another issue persists where in spawning a saved loadout with the new items causes visors to just be removed entirely.
> 
> An aside why not just do the deed in ernest and just kill jaeger instead of mulling about poking at it slowly dying?

you need to give me specifics here.
Also when I've loaded loadouts with helmets the visors work fine, but I saw Elsa not get theirs, so not sure what's happening there as I haven't touched how loadouts work at all.

2023-02-15 03:39 UTC, Zaffinomlb commented
> > There seems to be issues where changing the color on some of the new and old jaeger sprites just turns the items invisible entirely. Another issue persists where in spawning a saved loadout with the new items causes visors to just be removed entirely.
> > An aside why not just do the deed in ernest and just kill jaeger instead of mulling about poking at it slowly dying?
> 
> you need to give me specifics here. Also when I've loaded loadouts with helmets the visors work fine, but I saw Elsa not get theirs, so not sure what's happening there as I haven't touched how loadouts work at all.

One example that comes to mind would be the Mk1 Assault Jaeger helm does not color when put in squad colors, just turns invisible, and only the visor remains. Happens with a few others, can't recall which.

2023-02-15 19:14 UTC, Tailiik commented
> > There seems to be issues where changing the color on some of the new and old jaeger sprites just turns the items invisible entirely. Another issue persists where in spawning a saved loadout with the new items causes visors to just be removed entirely.
> > An aside why not just do the deed in ernest and just kill jaeger instead of mulling about poking at it slowly dying?
> 
> you need to give me specifics here. Also when I've loaded loadouts with helmets the visors work fine, but I saw Elsa not get theirs, so not sure what's happening there as I haven't touched how loadouts work at all.

I have had the old helljumper helmet spawn with no visor and also offset so my head was poking through

2023-02-16 03:35 UTC, Lumipharon commented
Sorry Tivi...

Fixed a bunch of loadout related issues, this PR should be good to merge now.

2023-02-18 05:30 UTC, Lumipharon commented
Added Tivi's CI fix. Also this says no conflicts with base but the tag wasn't removed. I unno why.

2023-02-18 08:22 UTC, merged