Adds a new Marine gun- The Magnum
tgstation/TerraGov-Marine-Corps pull request #12009
Opened 2023-01-25 00:49 UTC by Pariah919

## About The Pull Request
Adds a new marine revolver, inspired by the RU-TGMC .500 Revolver, with some sounds ~~ripped~~ borrowed from them.
Sprites by Ocelot, overall a resprite of the RU-TGMC one however.
Most stats gotten from here https://github.com/SpacelessBay/TerraGov-Marine-Corps/pull/10
Some stats by me. (Mostly ammo datum stats)

For the gun itself..
It has terrible gun handling overall, use the stock.
It has .5 windup before firing.
.75 fire delay.
It is avaliable in standard vendors.
Ammo stats are 75/40/.5 with 1 stagger, 1 knockback and no screenshake.

## Why It's Good For The Game
Adds a new interesting semi-sidearm to the marine arsenal. Its basically a pocket slug thrower. Should make it interesting to use over other traditional guns in the arsenal already, and be a fun thing to shoot people with.

## Changelog

:cl:
add: Added new Marine Magnum. It has a windup to fire, staggers on hit, and deals solid damage.
/:cl:

2023-01-25 01:41 UTC, Losenis commented
Does it knock marines down on FF?

2023-01-25 01:43 UTC, 567Turtle commented
> Does it knock marines down on FF?

I fucking hope it does

2023-01-25 02:29 UTC, Kuro020 approved these changes

2023-01-25 03:40 UTC, Xsdew commented
May I recommend if it isnt already the case. That the revovler is become too big to fit inside G8 pouches and backpacks/satchels.

2023-01-25 03:58 UTC, 567Turtle commented
> May I recommend if it isnt already the case. That the revovler is become too big to fit inside G8 pouches and backpacks/satchels.

BOOOOO, I'm pretty sure the revolvers in game can be chungused already, why make it so these ones cant?

2023-01-25 04:50 UTC, KerbalCitizen commented
>.75 fire delay.
>1 stagger
Thinking.

2023-01-25 05:08 UTC, SilencedMP5A5 commented
> > .75 fire delay.
> > 1 stagger
> 
> Thinking.

it has a windup so its probably fine

2023-01-25 09:25 UTC, KerbalCitizen commented
> > > .75 fire delay.
> > > 1 stagger
> > 
> > 
> > Thinking.
> 
> it has a windup so its probably fine

I don't know how windup interacts with fire delay tbh. The way I imagine it is:
0 seconds: Begin windup
0.25 seconds: First shot fired
0.75 seconds: Begin windup
1.00 seconds: Second shot fired just as fire delay ends

No clue if you can begin windup during fire delay, but if you can, keeping a xeno constantly staggered with that big of a margin (1 stagger, 0.75 time between shots) seems pretty good. I believe the closest standard weapon is leicaster repeater, which has 1 stagger and 1 (10 in code, I assume 1 second?) fire delay. Then the seasonal desert eagle, which I believe is better than repeater at stagger.

2023-01-26 08:54 UTC, DerFlammenwerfer commented
> > > > .75 fire delay.
> > > > 1 stagger
> > > 
> > > 
> > > Thinking.
> > 
> > 
> > it has a windup so its probably fine
> 
> I don't know how windup interacts with fire delay tbh. The way I imagine it is: 0 seconds: Begin windup 0.25 seconds: First shot fired 0.75 seconds: Begin windup 1.00 seconds: Second shot fired just as fire delay ends
> 
> No clue if you can begin windup during fire delay, but if you can, keeping a xeno constantly staggered with that big of a margin (1 stagger, 0.75 time between shots) seems pretty good. I believe the closest standard weapon is leicaster repeater, which has 1 stagger and 1 (10 in code, I assume 1 second?) fire delay. Then the seasonal desert eagle, which I believe is better than repeater at stagger.

The answer is no, you can't, because it will tell you the gun isn't ready to fire. You can't begin the windup during the delay.

2023-01-27 20:39 UTC, GreatKingWombat commented
> Show the the stats like damage and pen lad

75/40

2023-01-28 01:28 UTC, pilotmans commented
uhhh i just put the revolver in the revolver belt holster and revolver's texture is just "ERROR"

2023-01-28 14:19 UTC, docRoboRobert commented
Windup between shots too big, recoil with full attachments and stock is too big even when not dual wielding, not worth using at all at it's current state

2023-01-28 15:04 UTC, Zoldorf commented
Something that's relatively small that needs to be addressed, the gun can fit inside of the revolver belt even with a T-47 railscope, stock and barrel charger or extended barrel, when it should be too big to do so.

2023-01-28 16:37 UTC, GreatKingWombat commented on code/modules/projectiles/guns/revolvers.dm
> +	desc = "The R-76 magnum is an absolute beast of a handgun used by the TGMC, rumors say it was created as a money laundering scheme by some general due to the sheer inpracticality of this firearm. Hi
"The R-76 magnum is an absolute beast of a handgun used by the TGMC. Rumors say it was created as a money laundering scheme by some general due to the sheer inpracticality of this firearm. Hits hard: recommended to be used with its stock attachment. Chambered in 12.7mm."

There's more to mid-sentence punctuation than commas.

2023-01-28 19:57 UTC, SilencedMP5A5 commented
its too weak imo

2023-01-29 06:10 UTC, XSlayer300 commented on code/modules/projectiles/gun_attachables.dm
> +	name = "T-76 Magnum Stock"
```suggestion
	name = "T-76 magnum stock"
```
not on my watch

2023-01-31 22:57 UTC, XSlayer300 commented
Make sure to add the Magnum to the EORD spawn pool.

2023-02-02 01:18 UTC, XANAv2 commented
also, there is a glitch with build a sentry, it's supposed to pop the cylinder. So, you can shove a speed loader in but it doesn't, reload that way, it makes it a pain to use. This is a problem with most revolvers, and nobody has fixed it, i explained this in a ticket before this in the bug's section.

2023-02-05 02:44 UTC, SilencedMP5A5 commented
discovered a bug with shoulder mount that lets you shoot twice sometimes if you spam it during the windup

additionally, sometimes the gun just straight up stops working after you die

2023-02-09 20:36 UTC, Lumipharon requested changes

2023-02-09 20:36 UTC, Lumipharon commented on code/modules/projectiles/ammo_datums.dm
> +/datum/ammo/bullet/revolver/t76/on_hit_mob(mob/M,obj/projectile/P)
```suggestion
/datum/ammo/bullet/revolver/t76/on_hit_mob(mob/M, obj/projectile/P)
```

2023-02-09 20:36 UTC, Lumipharon commented on code/modules/projectiles/guns/revolvers.dm
> +		/obj/item/attachable/scope/marine,
```suggestion
```

2023-02-09 20:36 UTC, Lumipharon commented on code/modules/projectiles/magazines/revolvers.dm
> +	desc = "A revolver speed loader for the R-76 Magnum, mind your shoulder, will probably stagger anything it hits."
this uh, desc is kinda misleading

2023-02-09 20:41 UTC, Pariah919 commented on code/modules/projectiles/magazines/revolvers.dm
> +	desc = "A revolver speed loader for the R-76 Magnum, mind your shoulder, will probably stagger anything it hits."
```suggestion
	desc = "A revolver speed loader for the R-76 Magnum, mind your shoulder, will stun most moderately sized targets on impact."
```

2023-02-10 00:31 UTC, Lumipharon approved these changes

2023-02-10 00:31 UTC, merged

2023-02-10 17:05 UTC, chizzy376 commented
make it req only