King HP scaling change
tgstation/TerraGov-Marine-Corps pull request #12014
Opened 2023-01-25 19:43 UTC by Pariah919

## About The Pull Request
OLD HP Scaling
450->500->600->700
New
525->550->575->600

## Why It's Good For The Game
King HP scaling right now is absurd, the difference is insane between levels, the EHP is insane at 700HP, this should help alleviate that atleast a bit, while making younger levels of kings more consistent between themselves.

## Changelog

:cl:
balance: King HP scaling changed from 450->500->600->700 to 525->550->575->600.
/:cl:

2023-01-25 19:49 UTC, Naaanii commented
Kill the funny slash damage as well.

2023-01-25 19:50 UTC, shelteredfreak commented
ok now buff slash damage and make it more linear :)

2023-01-25 20:00 UTC, Araulius commented
mf's will nerf king hp but mech tanking 4 benos at once for over a minute is fine

2023-01-25 20:07 UTC, Araulius commented
> Kill the funny slash damage as well.

kill his only damage dealing ability? WEW

2023-01-25 22:09 UTC, Losenis commented
> mf's will nerf king hp but mech tanking 4 benos at once for over a minute is fine

Implying anyone wants mechs other than MP mains and c*ders

2023-01-25 22:43 UTC, Lumipharon requested changes
Make it max out at 650. It only has channeled CC, with no ranged attacks or sticky, and is slow. So reducing its HP doesn't just make it a lot easier to kill, it makes it considerably harder to use its abilities without dying.

We can revisit later if needed.

2023-01-25 23:03 UTC, srxtreme commented
King is fine the way it is in my opinion. It's a xeno that actually forces/encourages the marines to change up their playstyle a bit, and utilize weapons other than just holding M1 with whatever they have on hand. God knows rockets and railguns are rather underutilized.

2023-01-25 23:47 UTC, Strayed-Raven commented
reminder two drones and gorger give king EHP of almost 2k

2023-01-26 00:58 UTC, Losenis commented
>other than just holding M1 with whatever they have on hand

Holding M1 is the only way to actually make it fuck off with the amount of HP and damage it has though. If you're not holding M1 get ready to be delimbed through heavy armor and then chestfracced in the same fight.

2023-01-26 09:03 UTC, DerFlammenwerfer commented
> Make it max out at 650. It only has channeled CC, with no ranged attacks or sticky, and is slow. So reducing its HP doesn't just make it a lot easier to kill, it makes it considerably harder to use its abilities without dying.
> 
> We can revisit later if needed.

It's not the base HP being targeted so much as the EHP it has when boosted by other xenos. With support from drones and Gorger alone it can reach 2k EHP as it exists currently.

2023-01-26 16:56 UTC, Naaanii commented
> > Kill the funny slash damage as well.
> 
> kill his only damage dealing ability? WEW

Roar and beam also do damage. Being tanky and 'slow' is no excuse for having 30 slash damage with scalings that make little to no sense either.

2023-01-26 17:00 UTC, Naaanii commented
> Make it max out at 650. It only has channeled CC, with no ranged attacks or sticky, and is slow. So reducing its HP doesn't just make it a lot easier to kill, it makes it considerably harder to use its abilities without dying.
> 
> We can revisit later if needed.

Would be better to remove the shitty lock in place mechanics forcing it to stay in place. Forcing it in place for a 'risk and reward' gimmick is lame because players will just never use it unless it's reward and just continue to use the absurd base stats to facetank while being able to freely slash. Lowering the absurd HP and base stats along with removing the forced lock in channels gives more flexibility and mobility without making it like another Warlock tier caste where you just focus on off screening with your abilities.

2023-01-26 17:43 UTC, Araulius commented
> > > Kill the funny slash damage as well.
> > 
> > 
> > kill his only damage dealing ability? WEW
> 
> Roar and beam also do damage. Being tanky and 'slow' is no excuse for having 30 slash damage with scalings that make little to no sense either.

how about the fact it's a tier 4 caste worth oodles of points, and there can only be one at a time? the wave attack's damage is minimal, and the beam requires a target stay still for about 2 seconds before they get hit. (they never stay still)

2023-01-26 20:03 UTC, Naaanii commented
> > > > Kill the funny slash damage as well.
> > > 
> > > 
> > > kill his only damage dealing ability? WEW
> > 
> > 
> > Roar and beam also do damage. Being tanky and 'slow' is no excuse for having 30 slash damage with scalings that make little to no sense either.
> 
> how about the fact it's a tier 4 caste worth oodles of points, and there can only be one at a time? the wave attack's damage is minimal, and the beam requires a target stay still for about 2 seconds before they get hit. (they never stay still)

It's literally free. The beam also goes through walls, negating any building, surgery or even using kits.

2023-01-26 21:29 UTC, bowlofcereal commented
a xeno that does 30 slash damage and can shoot through walls and stun you for 4 seconds is very mid balancing, on top of the fact that its now free.

this PR don't got nothing to do with mechs so I don't know why you feel the need to continuously bring it up, as you imply that every single marine wants the mech in its current unfinished and buggy state (we don't). got to find a better strawman to use guys c'mon this is elementary level PR arguing

2023-01-27 01:57 UTC, Araulius commented
> > > > > Kill the funny slash damage as well.
> > > > 
> > > > 
> > > > kill his only damage dealing ability? WEW
> > > 
> > > 
> > > Roar and beam also do damage. Being tanky and 'slow' is no excuse for having 30 slash damage with scalings that make little to no sense either.
> > 
> > 
> > how about the fact it's a tier 4 caste worth oodles of points, and there can only be one at a time? the wave attack's damage is minimal, and the beam requires a target stay still for about 2 seconds before they get hit. (they never stay still)
> 
> It's literally free. The beam also goes through walls, negating any building, surgery or even using kits.

the primo ability laser beam is free guys. it's free!

2023-01-27 02:07 UTC, Araulius commented
late game xeno gets: kingus with chonky hp, and primo abilities and what not.

late game marines gets: b18 horde, one shot rockets, 100 to 0 sunder one shot weapons, uncounterable sky fire,  chain stunning melee weapons, funny one burst and your maze is dead fire, etc. that is the mid-late game.

Early game marines have access to: neigh melee immunity with riot shields, the ability to deny melee shuffle vali, tyr 1 and 2 melee resist, and acid immunity.

But you suggest that *xeno scaling* is the issue here. xeno scaling. Xeno scaling that does not compete well at *all* with marine mid-late game.

Marines have so many tools to deal with melee damage. if you don't like melee damage, consider using the tools available to you? You have tyr, shields, and fracture immunity as early game options. Why does kingus need a nerf when you have so many options?

2023-01-27 11:08 UTC, Naaanii commented
> late game xeno gets: kingus with chonky hp, and primo abilities and what not.
> 
> late game marines gets: b18 horde, one shot rockets, 100 to 0 sunder one shot weapons, uncounterable sky fire, chain stunning melee weapons, funny one burst and your maze is dead fire, etc. that is the mid-late game.
> 
> Early game marines have access to: neigh melee immunity with riot shields, the ability to deny melee shuffle vali, tyr 1 and 2 melee resist, and acid immunity.
> 
> But you suggest that _xeno scaling_ is the issue here. xeno scaling. Xeno scaling that does not compete well at _all_ with marine mid-late game.
> 
> Marines have so many tools to deal with melee damage. if you don't like melee damage, consider using the tools available to you? You have tyr, shields, and fracture immunity as early game options. Why does kingus need a nerf when you have so many options?

King is literally round start in an average pop round though. There's no scaling when you have it at the start of the game. King's base stats weren't even meant for this rework or any of these abilities in mind. There is no literally no reason to argue for it unless you just want to abuse the stat stick which makes it even more flawed in design.

2023-01-28 21:25 UTC, merged

2023-01-28 21:26 UTC, pilotmans commented
Beautiful

2023-01-28 21:29 UTC, pilotmans commented
> Pariah the goofy anti-xeno c*der with another nerf, mind nerfing mechs to compensate then since even now they are better than king and can tank 9 xenos at once.

As a marine player i can say mechs are just not fun to exist now something lighter like a mobile suit or that one PR request that added a incredibily vulnerable attack helicopter would be more fun but also be able to more easily be taken out by xenos

2023-01-28 22:51 UTC, Losenis commented
>Play xeno
>Mech is a damage sponge that doesn't give a shit
>Play marine
>Mech is a moving shotblocker you can't PB out of the way and bodyblocks you to death

The only ones that like mechs are MP mains and c*ders with stockholm syndrome