Tactical reload pill bottles
tgstation/TerraGov-Marine-Corps pull request #12075
Opened 2023-02-03 00:45 UTC by Xander3359

## About The Pull Request
You can now refill pill bottles from packets.

## Why It's Good For The Game
Cuts down on some carpal tunnel by allowing you to click a pill bottle with a packet to refill the bottle from the packet.

## Changelog

:cl:
add: You can now reload pill bottles from pill packets.
/:cl:

2023-02-03 01:26 UTC, ilikesaying commented
basedbasedbasedbasedbased

2023-02-03 01:30 UTC, Losenis commented
![image](https://user-images.githubusercontent.com/72712909/216489557-1a53abfa-0718-46a6-b0fc-09a4a39c0e90.png)

2023-02-03 02:19 UTC, FosterGrime-Heymynameslouie commented
TACTICAL MEDICINE

2023-02-03 03:47 UTC, tanker4390 commented
It may be a poor idea to continue copypasting this proc on high-level objects; perhaps it can instead be broken up into vars and placed lower on the tree? for example
```
.../storage/attackby(I, user)
      if (istype(I, refill_type)
            return do_refill(I, user)
      ...

.../storage/proc/do_refill(I, user)
      this()

.../storage/xeno_holder/rouny_holder/attackby(I, user) //only holds rounys
      if (istype(I, .../rouny_holder))
            var/.../rouny_holder/RH = I
            if (RH.closed)
                  return ..()
            return do_refill(RH, user)
      return ..()

.../storage/xeno_holder/do_refill(I, user)
      for (things in I)
            special_code_for_transferring_xenos(src) //overridden e.g. for automatically creating handfuls
```

2023-02-03 04:01 UTC, Araulius commented
it's almost like removing standard pill bottles from being available to marines did nothing during the med rework. shocker.

2023-02-03 05:52 UTC, ivanmixo commented
Shhhh dont tell them

2023-02-03 07:03 UTC, KerbalCitizen commented
Currently the best method to fill pill bottles with packets is to empty the packet on the floor, then do it again with another packet, and click on the pile of pills with pill bottle. This is really just a QoL PR.

2023-02-03 09:34 UTC, Al-1ce commented
Could this be done vice-versa?

2023-02-03 11:02 UTC, Xander3359 commented
> Could this be done vice-versa?

You cannot refill packets.

2023-02-07 10:39 UTC, Autisem commented
could you make it so you can restock pill packets back into the vendor? watching a pile of empty pill packets grow in medbay is kinda jaring.

Other then that, holy fuck finaly

2023-02-07 20:40 UTC, Lumipharon requested changes

2023-02-07 20:40 UTC, Lumipharon commented on code/game/objects/items/storage/firstaid.dm
> +/obj/item/storage/pill_bottle/attackby(obj/item/I, mob/user, params)
This should be calling to parent first.

2023-02-07 23:18 UTC, Xander3359 commented on code/game/objects/items/storage/firstaid.dm
> +/obj/item/storage/pill_bottle/attackby(obj/item/I, mob/user, params)
done

2023-02-08 08:02 UTC, Lumipharon commented
> It may be a poor idea to continue copypasting this proc on high-level objects; perhaps it can instead be broken up into vars and placed lower on the tree? for example
> 
> ```
> .../storage/attackby(I, user)
>       if (istype(I, refill_type)
>             return do_refill(I, user)
>       ...
> 
> .../storage/proc/do_refill(I, user)
>       this()
> 
> .../storage/xeno_holder/rouny_holder/attackby(I, user) //only holds rounys
>       if (istype(I, .../rouny_holder))
>             var/.../rouny_holder/RH = I
>             if (RH.closed)
>                   return ..()
>             return do_refill(RH, user)
>       return ..()
> 
> .../storage/xeno_holder/do_refill(I, user)
>       for (things in I)
>             special_code_for_transferring_xenos(src) //overridden e.g. for automatically creating handfuls
> ```

This is a good point. I didn't realise this is just copypasta from flare refilling, so a storage level proc like this example would be better.

2023-02-09 04:38 UTC, Lumipharon requested changes

2023-02-09 04:38 UTC, Lumipharon commented on code/game/objects/items/storage/storage.dm
> +				return do_refill(I, user)
```suggestion
	if(length(refill_types))
		for(var/typepath in refill_types)
			if(istype(I, typepath))
				return do_refill(I, user)
```

2023-02-09 04:38 UTC, Lumipharon commented on code/game/objects/items/storage/storage.dm
> +		if(length(contents) >= max_storage_space)
max storage space is the volume the object can hold, which is not necessarily the number of slots. i.e. a satchel has a max of 15, which translates to 5 normal sized object, or 15 injectors.

2023-02-09 09:35 UTC, Lumipharon approved these changes

2023-02-09 09:35 UTC, merged