New TAT ammo, and three AGLS changes
tgstation/TerraGov-Marine-Corps pull request #12072
Opened 2023-02-02 13:08 UTC by maikilangiolo

## About The Pull Request
Added Beehive and Napalm AT36 ammo. They work exactly like GL54 airbust and incendiary, but scaled up for 37mm usage. They have the mech airbust slowdown and the GL54 1 tile knockback on direct hit (consistent with the other airbust shells, and makes sense with the moderate velocity of the ammo). Both new rounds have great FF potential, and are on par with other shells when comparing effectiveness.

AGLS changes included are doubledd reload time (it was too fast), HP nerf (500 hp is TAT levels of HP), and armor buff (20 acid to bring it in line with the others, 100 bomb to avoid self nuking, especially because the ammo randomly drops in front of you). As well as a bug fix with turf targeting for AGLS frag ammo.

## Why It's Good For The Game
More ammo variation for the gun that arguably should enjoy juggling different ammo types for different targets and situations. And, no more fucked stats for the AGLS.

## Changelog

:cl:
add: added Napalm and Beehive AT36 shells
balance: AGLS reload 2 seconds --> 4 seconds
balance: AGLS HP 500 --> 300, bomb armor 75 --> 100, acid armor 0 --> 20
fix: fixed AT36 HE ammo being described as "high velocity" when its actually very slow
/:cl:

2023-02-02 20:27 UTC, Lumipharon requested changes
Don't make it 100 bomb armour. FF immunity is cringe.

2023-02-04 03:16 UTC, Lumipharon commented
You should put a video on the pr btw

2023-02-04 09:06 UTC, maikilangiolo commented
> You should put a video on the pr btw

videdo added

2023-02-07 10:01 UTC, Lumipharon requested changes

2023-02-07 10:01 UTC, Lumipharon commented on code/modules/projectiles/guns/mounted.dm
> +	soft_armor = list("melee" = 0, "bullet" = 50, "laser" = 0, "energy" = 0, "bomb" = 80, "bio" = 100, "fire" = 0, "acid" = 20)
defines.

2023-02-07 11:26 UTC, Lumipharon approved these changes

2023-02-07 11:26 UTC, merged