Makes acid melt flares faster
tgstation/TerraGov-Marine-Corps pull request #12109
Opened 2023-02-06 16:18 UTC by Zar000

## About The Pull Request

Exactly what the title says

## Why It's Good For The Game

Marines have a lot of tools to light up areas, some of them, such as howie flares & CAS flares have almost no counter-play other than waiting them out.

The thrown flares however, we can melt but it takes forever unless queen / boiler does it.

This still makes it take a while with drone level acid, but 2x faster.

## Changelog

:cl:
balance: All acids melt flares 2x faster and boiler makes it very fast.
/:cl:

2023-02-06 16:49 UTC, docRoboRobert commented
after the flare boxes massive buff i'd say this is needed.

2023-02-07 20:54 UTC, Lumipharon requested changes

2023-02-07 20:54 UTC, Lumipharon commented on code/game/objects/effects/aliens.dm
> +		ticks += delta_time * min((acid_strength * flare_strength_multiplier), flare_strength_max_melt_rate) // we dont wanna make it possible to melt flares too fast
Having the typecheck here is snowflake. There should be a proc on the target side to return an acid time or whatever.

2023-02-09 00:27 UTC, Tailiik commented
It would be very funne if a primo prae could trigger flare melt with ranged spit

2023-02-13 21:27 UTC, Lumipharon requested changes
Make this a proc instead of an object var as discussed.

2023-03-01 03:28 UTC, Mannybrado commented
maintainers help

2023-03-17 00:57 UTC, closed without merging