Adds ICC, a new hostile ERT, and a minor SoM blurb change.
tgstation/TerraGov-Marine-Corps pull request #12174
Opened 2023-02-14 21:22 UTC by Pariah919

## About The Pull Request
Adds ICC, a new Hostile ERT, their allies are the SoM.
Adds ICC jobs which are the standards, leaders, guards and medics.
Adds 2 ICC guns. The Trenchgun for the leader, and the coilgun for the Guardsman.

ICC have bring an incredibly high amount of explosives with them, with high bomb resist to help them create mayhem on a HvH ship activity. They also all have 2 engineering and 2 construction skill outside of the medics, who have much lower.
![ICC](https://user-images.githubusercontent.com/46353991/218865581-b1fdf850-91d1-4b39-b4f5-853b3c81255d.gif)
(armor sprites by Fitz. These guys are using a lot of placeholder stuff still.)

## Why It's Good For The Game
New ERT which is the actual main enemy of TGMC in the lore. So that's cool. Also I w

## Changelog

:cl:
add: Added new Hostile ERT, ICC. They're allied to SoM and are strapped with a large amount of explosives and engineering equipment.
spellcheck: SoM ert blurb has been redone to clairify a few things, such as the addition of ICC as an ally and grammar stuff.
/:cl:

2023-02-14 21:29 UTC, Kuro020 approved these changes

2023-02-14 23:24 UTC, XSlayer300 commented on code/modules/projectiles/guns/specialist.dm
> +	desc = "The ML-120 coilgun is the most common seen coilgun in ICCAF use, firing magnetic projecitles at a incredibly high velocity, requires some windup but will penetrate walls, your foes, and your
```suggestion
	desc = "The ML-120 coilgun is the most commonly seen coilgun in ICCAF use, firing magnetic projecitles at a incredibly high velocity. It requires some windup but will penetrate walls, your foes, and your friendlies too. So watch out... Uses specialized canisters to reload."
```

2023-02-15 00:16 UTC, FosterGrime-Heymynameslouie commented
should replace clf tbh
very cool

2023-02-15 00:44 UTC, zzurge commented
As much as i love this its a criminal shame that i may never see them in a match

2023-02-15 03:03 UTC, Lumipharon requested changes

2023-02-15 03:05 UTC, Pariah919 commented on code/modules/clothing/head/helmet.dm
> +/obj/item/clothing/head/helmet/marine/icc
I'll normalize it with the armor.

2023-02-15 03:05 UTC, Pariah919 commented on code/modules/clothing/suits/marine_armor.dm
> +	soft_armor = list(MELEE = 60, BULLET = 65, LASER = 40, ENERGY = 60, BOMB = 100, BIO = 10, FIRE = 55, ACID = 40)
I'll drop it to 85, you're probably right.

2023-02-15 03:17 UTC, FIXTHERADBOXPLEASE commented
Dripmongers deployed.

2023-02-15 05:24 UTC, Pariah919 commented on code/modules/projectiles/ammo_datums.dm
> +/datum/ammo/bullet/coilgun
Removed wallpierce.

2023-02-15 07:22 UTC, Al-1ce commented
It would be wise to add a small blurb to all SoM that the ICC are their allies.

2023-02-15 09:26 UTC, ThelastArchiver commented
the return of the knights

2023-02-20 21:17 UTC, Lumipharon requested changes

2023-02-20 21:17 UTC, Lumipharon commented on code/datums/jobs/job/icc.dm
> +	faction = FACTION_USL
bruh

2023-02-20 21:17 UTC, Lumipharon commented on code/datums/jobs/job/icc.dm
> +	ears = /obj/item/radio/headset/distress/som
wuh

2023-02-20 21:17 UTC, Lumipharon commented on code/datums/jobs/job/icc.dm
> +	H.equip_to_slot_or_del(new /obj/item/ammo_magazine/rocket/som/heat, SLOT_IN_L_POUCH)
25% of the entire ert all having HE and thermobaric rockets is an extremely bad idea.

2023-02-21 20:39 UTC, Lumipharon approved these changes
RPG chance is honestly still kinda high, you should really just add more loadouts. Should be fine for testing though.

2023-02-21 21:05 UTC, merged