cooler combat sound effects
tgstation/TerraGov-Marine-Corps pull request #12189
Opened 2023-02-17 13:39 UTC by tyeagg

## About The Pull Request
makes some sounds cooler, explosion sounds are now different if its devastating or heavy or light
got sounds from this foxhole mod thats cool https://liquidpopsicle.itch.io/liquid-sound-overhaul

https://user-images.githubusercontent.com/98577688/219667363-838166d2-1d09-487c-bebd-974a6067569d.mp4

https://user-images.githubusercontent.com/98577688/219666852-7778c911-e5bf-4ff3-ad1d-6f95f9174ac0.mp4
## Why It's Good For The Game
sounds gooder

## Changelog

:cl:
add: different sounds for different explosion types
soundadd: new explosion sounds
soundadd: new bullet ricochet and miss
sounddel: removed old explosion sounds
/:cl:

2023-02-18 00:21 UTC, yyzsong commented
Finally, xenos can have the true Somme experience they've all been waiting for. Thank you tyeagg

2023-02-18 01:34 UTC, Mannybrado commented
new hit sounds kind of suck
other ones are cool

2023-02-18 02:15 UTC, tyeagg commented
> new hit sounds kind of suck
> other ones are cool

there are no changes to mob hit sound thats just the sound when bullets dont penetrate the armor on mobs

2023-02-18 13:24 UTC, TiviPlus approved these changes
rest lgtm

2023-02-18 13:24 UTC, TiviPlus commented on code/game/sound.dm
> -			S = pick('sound/bullets/energy_ricochet1.ogg')
why remove this?

2023-02-18 22:32 UTC, Lumipharon commented
I like the mid/large explosion sounds, but the small explosions sound kinda weird coming from grenades.

Also can you keep in the existing small explosion sounds? They are used for stuff like airburst rounds and I specifically don't want them to sound like actual explosives.

2023-02-20 08:03 UTC, Lumipharon approved these changes

2023-02-20 08:06 UTC, Lumipharon requested changes

2023-02-20 08:06 UTC, Lumipharon commented on code/modules/projectiles/projectile.dm
> +			pitch = 55000
This shouldn't run in the ammo doesn't have the relevant sound to begin with. Also you could probs just chuck it in the playsound line itself.

2023-02-20 20:36 UTC, Lumipharon approved these changes

2023-02-20 20:37 UTC, merged