New combat robot self maint sound
tgstation/TerraGov-Marine-Corps pull request #12207
Opened 2023-02-20 00:28 UTC by novaepee

## About The Pull Request

Title.

## Why It's Good For The Game

QV reused welding and deconstruction for combat robot self healing, and it's not his fault. I like to expand the soundscape of TGMC so that we don't overuse one ogg.

## Changelog

:cl:
soundadd: New combat robot self maint sound
/:cl:

2023-02-20 00:50 UTC, Zangeiti commented
sounds like it would get annoying after awhile imo

2023-02-20 00:58 UTC, QualityVan commented
Agree that some variation would be good.

2023-02-21 01:57 UTC, FIXTHERADBOXPLEASE commented
Reminds me of the leg-repairing sound from EYE.

2023-02-23 08:48 UTC, Lumipharon requested changes
If the sound is the same regardless of damage type, take out the sound to play from those if statements.

2023-02-24 03:47 UTC, Lumipharon commented on code/datums/status_effects/debuffs.dm
> +	playsound(owner, sound_to_play, 50, 0, 12)
```suggestion
	playsound(owner, sound_to_play, 50, sound_range = 12)
```

2023-02-24 03:47 UTC, Lumipharon approved these changes

2023-02-24 04:12 UTC, merged