Adds more loadouts to EORD
tgstation/TerraGov-Marine-Corps pull request #12200
Opened 2023-02-19 03:21 UTC by carlarctg

## About The Pull Request

Refactored and reworked EORD loadout selection to pick from all the subtypes of normal ERT factions. Added spec ops to this list.

Added the HvH loadouts for SOM and terragov soldiers that are handled by randomly picking from the relevant subtype outfits.

Added a 7% chance to spawn in as a 'rare faction', skeletons, Imperial Guardsmen, and sectoids.

Moved species changing of skeletons and sectoids from the ERT call proc to when the outfit is applied.

## Why It's Good For The Game

After a certain amount of time playing the game, you start to realize how stale the EORD loadouts are. There's actually not that much variation, and it gets especially stale considering one of the factions (UPP) has 3 nigh identical loadouts.

Adding this many new loadouts, especially with the HvH and rare factions will make EORD feel a lot more fresh as players will have access to a lot of new loadouts. This will also let them practice with these loadouts before getting them in an actual game, as some sort of pseudo-tutorial.

## Changelog

:cl:
refactor: Refactored and reworked EORD loadout selection to pick from all the subtypes of normal ERT factions. Added spec ops to this list.

add: Added the HvH loadouts for SOM and terragov soldiers that are handled by randomly picking from the relevant subtype outfits.

add: Added a 7% chance to spawn in as a 'rare faction', skeletons, Imperial Guardsmen, and sectoids.

code: Moved species changing of skeletons and sectoids from the ERT call proc to when the outfit is applied.
/:cl:

2023-02-20 10:13 UTC, ThelastArchiver commented
based pr speedmerge

2023-02-23 10:41 UTC, TiviPlus requested changes
Rest lgtm

2023-02-23 10:41 UTC, TiviPlus commented on code/modules/mob/mob_verbs.dm
> +		do_eord_respawn(liver)
You could achieve the same result by doing
	if(!isliving(usr))
        return
	var/mob/living/liver = usr

2023-02-23 10:41 UTC, TiviPlus commented on code/datums/emergency_calls/sectoid.dm
>  	H.fully_replace_character_name(M.name, H.real_name)
??

2023-02-23 10:41 UTC, TiviPlus commented on code/datums/emergency_calls/skeleton.dm
>  	H.fully_replace_character_name(M.name, H.real_name)
??

2023-02-23 10:41 UTC, TiviPlus commented on code/datums/jobs/job/job.dm
> +/mob/living/proc/apply_assigned_role_to_spawn(datum/job/assigned_role, client/player, datum/squad/assigned_squad, admin_action = FALSE, eord_spawn = FALSE)
eord_spawn unused

2023-02-23 10:41 UTC, TiviPlus commented on code/datums/jobs/job/job.dm
> +/mob/living/carbon/human/apply_assigned_role_to_spawn(datum/job/assigned_role, client/player, datum/squad/assigned_squad, admin_action = FALSE, eord_spawn = FALSE)
ditto

2023-02-23 10:41 UTC, TiviPlus commented on code/modules/mob/mob_verbs.dm
> +		do_eord_respawn(liver)
side note this appears to break respawning as ghost

2023-02-23 10:41 UTC, TiviPlus commented on code/datums/gamemodes/_game_mode.dm
> +				do_eord_respawn(H)
code/modules/mob/mob_verbs.dm L113 means this will not just give the job as before but will ghost the current mob and create a new one

2023-02-23 19:14 UTC, carlarctg commented on code/datums/emergency_calls/sectoid.dm
>  	H.fully_replace_character_name(M.name, H.real_name)
![image](https://user-images.githubusercontent.com/53100513/221007555-fe563909-89ce-405c-8086-c63719d9cdbc.png)

2023-02-23 19:14 UTC, carlarctg commented on code/datums/emergency_calls/skeleton.dm
>  	H.fully_replace_character_name(M.name, H.real_name)
![image](https://user-images.githubusercontent.com/53100513/221007569-4ecc930e-2b52-4ebd-ae3e-d3d0f72869cc.png)

2023-02-28 06:49 UTC, carlarctg commented
Added ICC and deathsquad (to rare factions), handled review

did not test this push - testmerge first

2023-02-28 08:22 UTC, TiviPlus requested changes
ugly but good enough

2023-02-28 08:22 UTC, TiviPlus commented on code/datums/jobs/job/sectoid.dm
> +	..()
```suggestion
	. = ..()
```

2023-02-28 08:22 UTC, TiviPlus commented on code/modules/mob/mob_verbs.dm
> +/proc/do_eord_respawn(mob/respawner)
Autodoc

2023-02-28 18:00 UTC, carlarctg commented
Autodocced, suggestioned, moved deathsquad to a 2% chance if the 7% chance rolls because I've been told they're nigh unkillable. A little spicy fun if the stars align.

2023-02-28 23:17 UTC, Lumipharon commented
Why is DS a loadout option? You're unkillable, I might as well just give myself godmode.

2023-03-01 03:18 UTC, Lumipharon requested changes
This is pretty buggy. It doesn't actually respawn you or create a new body, it just regens your current body and tries to equip a new outfit to it. And since you already have one on, it only fills any empty slots.

2023-03-05 19:00 UTC, chesse20 commented
This is broken, it took away my existing loadout that i was already wearing before eord and i didn't die

2023-03-09 22:21 UTC, Lumipharon commented
When the game ends it shoves you in a new body and sends both your new and old body to EORD.

2023-03-12 16:36 UTC, chizzy376 commented
This PR used to make it so when you died and hit EORD respawn you respawned as the same guy but with the slots you had empty re-filled, I think it was better that way 2 weeks ago when it worked that way... man it also had like infinitely more loadouts back then, what happened??? could you like bring those back it was really fun then I think I really enjoyed it myself it had more variety and everything haha

2023-03-14 17:01 UTC, TiviPlus commented
Pending fixes

2023-03-26 13:36 UTC, merged