Grenades no longer require throw mode to throw
tgstation/TerraGov-Marine-Corps pull request #12214
Opened 2023-02-21 15:01 UTC by Xander3359

## About The Pull Request
WE HAVE THE TECHNOLOGY, WE CAN MAKE HIM BETTER.
This makes it so that grenades throw on /afterattack , instead of just enabling throw mode.

## Why It's Good For The Game
Throw mode is janky, being able to avoid it (while still supporting it) is a better way.

## Changelog

:cl:
add: Grenades throw on click regardless of intent.
/:cl:

2023-02-21 15:05 UTC, ivanmixo commented
They automatically toggle throw mode for you when you activate them, though? So you never have to toggle it yourself and can just click immediately after activation. This is begging for misclicks lol

2023-02-21 15:10 UTC, Xander3359 commented
> They automatically toggle throw mode for you when you activate them, though? So you never have to toggle it yourself and can just click immediately after activation. This is begging for misclicks lol

They don't turn off throw mode if you ever unequip the grenade. Thats my main annoyance

2023-02-21 18:40 UTC, Oscari-pog commented
This is actually terrible ngl

2023-02-21 18:49 UTC, Jalopkomit18 commented
What happens if you click when the grenade is not primed? Will it still throw, or not do anything like it should? If it doesn't throw when not primed, I see no reason why this shouldn't be merged. Having it toggle throw mode adds a lot of jank. However, if you do toggle throw mode manually with this pr, what happens?

2023-02-21 19:44 UTC, Xander3359 commented
> What happens if you click when the grenade is not primed? 

It doesnt throw if it's not primed. If you want to throw un-primed grenades, you have to turn on throw mode and toss it yourself.

You can turn on throw mode and throw a primed grenade as well (If it makes you happy)

2023-02-21 20:15 UTC, Lumipharon commented
If your issue is with dropping nades not turning off throw mode... why don't you make drop turn off throw mode?

2023-02-22 01:05 UTC, Xander3359 commented
I would rather divorce throwing things from throw mode to be honest. Things like throwing knives/nades, objects which are intended to be thrown, should just function without needing to fuck around with throw mode. 

Throw mode should be used consciously when you intent on throwing something for any personal reason. The only times you should enter throwing intent is when you intend on throwing something, not because you are forced into throw intent to pick throw a nade.

Primed grenades are always intended on being thrown, if you pick up a live grenade to re-throw it you have to manually re-enable throw mode, but on this build you can simply pick it up and toss it without having to fumble your keys.

2023-02-22 02:46 UTC, Al-1ce commented
I am convinced you have never thrown a grenade in this codebase before.

2023-02-22 05:19 UTC, XElectricX commented
Great PR. Those that hate it should ask themselves if they think throwing knives should use throw mode as well.

2023-02-22 13:04 UTC, TChalkman commented
When you prime a grenade, it toggles your throw mode. It doesn't turn it on, only toggles it. Which causes things like:

-If you prime flares and want to just drop them instead of throw, throw mode will still be on and you'll have to press throw key or click twice.
-If you get tackled, stunned, or dropped... before throwing, throwing mode literally REFUSES doing anything except throwing what's on hand (or do nothing, if the hand is empty). This means you need to click twice on a grenade to grab it. You might also accidentally throw your weapon if you try to use it instead, etc.
-If for some reason you had throw mode already on, priming a grenade will toggle your throwing mode OFF. 

I agree with this PR. There are so many things that could go wrong when using any kind of grenade, and its not like they're so different from throwing knives. Why would you ever want to NOT throw a primed grenade? You aren't going to MELEE someone with it or something. 
And since you need to prime the grenade before throwing, there shouldn't be any issue with accidentally throwing an unprimed nade or anything like that
Half the reason an experienced player wants to use a GL is not because of just the grenade delay, but to avoid getting trolled by the throwing system

2023-02-24 04:59 UTC, Strayed-Raven commented
please merge this. im tired of throwing guns in the middle of battle just because i get stunned after priming a nade and then taking my rifle out.

2023-02-24 05:14 UTC, Naaanii commented
Disguised nerf for skill issues. So real.

2023-02-24 05:38 UTC, Tailiik commented
Ignore the haters, eliminating jank is good.

2023-02-25 14:52 UTC, Notamaniac commented
How much jank would it involve to turn this into a preference?

2023-02-25 23:57 UTC, Xander3359 commented
> How much jank would it involve to turn this into a preference?

Is there any time you have a primed grenade in hand that you wouldnt want to throw?

2023-02-26 00:34 UTC, Al-1ce commented
> Is there any time you have a primed grenade in hand that you wouldnt want to throw?

That's not the point. The point is forcing new mechanics that don't actually add anything to the game. Any SS13 veteran will use throw-mode by instinct. 

Don't fix what isn't broken. This PR is retarded.

2023-02-26 12:45 UTC, Xander3359 commented
> Any SS13 veteran will use throw-mode by instinct.

Any TGMC veteran will just prime and throw, as currently priming a grenade puts you in throw mode.
Gameplay wise, this change should be unnoticed by most of the marines in most cases except the few that are positive.

2023-02-26 14:18 UTC, Losenis commented
This is a good change because anyone who hasn't gotten stockholm syndrome'd into the current throwing mechanic would intuitively think "I must throw the grenade after priming it, therefore I must prime the grenade and enable throw mode", which can actually result in you disabling throw mode with the primed nade in your hand. The current mechanic has the possibility of fucking up on people, this pr makes it more reliable by having it throw regardless of intent. There's no real reason to reject this PR other than people who are used to what the old way was given it has zero benefits over this. I don't think even muscle memory would conflict with the PR getting merged since it'd still throw regardless.

2023-02-26 22:49 UTC, Xander3359 commented
> I don't think even muscle memory would conflict with the PR getting merged since it'd still throw regardless.

This exactly, wether you are on throw mode or not, you will throw the grenade no matter what.

2023-03-01 08:54 UTC, TiviPlus requested changes
Rest lgtm

2023-03-01 08:54 UTC, TiviPlus commented on code/game/objects/items/explosives/grenades/grenade.dm
> +	playsound(src, 'sound/effects/throw.ogg', 30, 1)
replace with /mob/living/carbon/throw_item ?

2023-03-01 09:28 UTC, Xander3359 commented on code/game/objects/items/explosives/grenades/grenade.dm
> +	playsound(src, 'sound/effects/throw.ogg', 30, 1)
yeh

2023-03-01 09:33 UTC, TiviPlus approved these changes

2023-03-01 09:42 UTC, merged

2023-03-02 07:38 UTC, Al-1ce commented
Another bad PR merged. Oh the misery.

2023-03-02 13:17 UTC, Losenis commented
>bad pr

absolute state of ungabrains