Moves end round info to its own panel, second try
tgstation/TerraGov-Marine-Corps pull request #12235
Opened 2023-02-24 22:23 UTC by RipGrayson

## About The Pull Request

Reopening of https://github.com/tgstation/TerraGov-Marine-Corps/pull/12151 without the strange commits.

You know how when you play regular SS13 and you finish a round a panel pops out in the middle of your screen with the round info? This is that but for TGMC.
I mostly used code from TG for this, but there's a few minor areas that received minor rewrites.
It should display all the info and stats that are normally displayed at the end of a round, I've verified this locally but it needs a TM to be entirely sure.

Pictures soon.
~~A week later apparently~~
![endround](https://user-images.githubusercontent.com/49290523/220958890-49fa79bd-497c-4aac-9e35-3ae8ee6c63e9.png)

## Why It's Good For The Game

Have you ever had a round end, the stats and results get pushed to chat and then it scrolls so fast you have to scroll up for five minutes to find out who won, fighting against the tide of new chat messages? This should put an end to that for good, the panel is placed in the middle of the screen and there's a handy button for reopening it.

To my knowledge, CM and TGMC are the only codebases that do not push a notification to the screen on round end, and I intend to change this. ~~I also need this for future features I'm working on~~

## Changelog
:cl:
qol: Round end info is now displayed in its own panel instead of in chat
/:cl:

2023-02-25 02:59 UTC, SilencedMP5A5 commented
when do we get more detailed round statistics

2023-02-25 04:03 UTC, RipGrayson commented
> when do we get more detailed round statistics

Whenever they're added, currently this just pushes any round stats you would normally see in chat to its own panel.

2023-02-25 07:50 UTC, Joe13413 commented
powercreep pr

2023-02-25 09:26 UTC, Al-1ce commented
Allowing a preference to toggle this between UI and the chat is a necessity. If that isn't plausible to add, I really do not like this.

2023-02-25 17:01 UTC, TiviPlus requested changes
rest lgtm

2023-02-25 17:01 UTC, TiviPlus commented on code/datums/gamemodes/_game_mode.dm
> +/datum/game_mode/proc/personal_report(client/C, popcount)
Autodoc

2023-02-25 21:35 UTC, Ragecrabbo commented
Show roundend report againShow roundend report againShow roundend report againShow roundend report againShow roundend report againShow roundend report againShow roundend report againShow roundend report againShow roundend report againShow roundend report againShow roundend report againShow roundend report againShow roundend report againShow roundend report againShow roundend report againShow roundend report againShow roundend report againShow roundend report againShow roundend report againShow roundend report again

2023-02-25 21:44 UTC, Lumipharon requested changes

2023-02-25 21:44 UTC, Lumipharon commented on code/datums/gamemodes/_game_mode.dm
> +		display_report(C)
```suggestion
	display_report()
```

2023-02-25 21:44 UTC, Lumipharon commented on code/datums/gamemodes/_game_mode.dm
> +/datum/game_mode/proc/display_report(popcount)
```suggestion
/datum/game_mode/proc/display_report()
```
popcount isn't used unless I'm entirely blind

2023-02-26 01:45 UTC, XSlayer300 commented
Make sure this ONLY appears if you've joined the game proper (as a marine/ERT or a xeno) and not if you just observed the round or somehow killed yourself in vahalla.
![image](https://user-images.githubusercontent.com/35091844/221387678-54a4ed17-e7d9-429b-8599-f45178575b13.png)

2023-02-26 04:14 UTC, RipGrayson commented
> Make sure this ONLY appears if you've joined the game proper (as a marine/ERT or a xeno) and not if you just observed the round or somehow killed yourself in vahalla. ![image](https://user-images.githubusercontent.com/35091844/221387678-54a4ed17-e7d9-429b-8599-f45178575b13.png)

That sort of thing will probably be implemented later, I would have to touch the jobs system and massively complicate what's already written.

2023-02-26 06:28 UTC, Lumipharon commented
It also uses the hvh end game wording in hvx, referring to the brave men and women of the tgmc and som

2023-02-27 04:42 UTC, XElectricX commented
Finally don't have to scroll up to see the round end stats, though having it as a preference sounds fair. Also what exactly is the button sprite supposed to be? Looks very bad.

2023-02-27 05:11 UTC, RipGrayson commented
> Finally don't have to scroll up to see the round end stats, though having it as a preference sounds fair. 

Probably something that will happen later, you'll need two procs for each displayed statistic and to modify both the preferences panel and the logic involved in displaying end round stats. It's an extra complication that can wait until after the PR itself has been merged.

>Also what exactly is the button sprite supposed to be? Looks very bad.

Feel free to make a new one, it's a codersprite and I have no ability/inspiration to make a new one.

2023-02-28 08:45 UTC, TiviPlus commented
There will be no preference

2023-03-01 07:29 UTC, Al-1ce commented
> There will be no preference

Cringe.

2023-03-02 17:20 UTC, TiviPlus approved these changes

2023-03-07 12:49 UTC, merged