The flamer hydrocannon extinguishes the user.
tgstation/TerraGov-Marine-Corps pull request #12323
Opened 2023-03-04 14:48 UTC by Xander3359

## About The Pull Request
Makes the hydrocannon extinguish the user.

## Why It's Good For The Game
Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/11928

## Changelog

:cl:
fix: flamer hydrocannon extinguishes the user.
/:cl:

2023-03-04 16:29 UTC, FIXTHERADBOXPLEASE commented
Seems like powercreep and disincentivizes teamwork.

2023-03-04 16:52 UTC, QualityVan commented
Poor implementation. For one, you're extinguishing yourself every single time a turf gets sprayed.
I'm also unfond of this conceptually since every other gun the only way you can shoot yourself is via suiciding. Bring surt or a handheld.

2023-03-04 20:23 UTC, Xander3359 commented
With the old extinguisher you used to be able to extinguish yourself. With the new attachment, you no longer can.

2023-03-05 02:34 UTC, Lumipharon requested changes
What QV said, this isn't right.

2023-03-05 11:19 UTC, Xander3359 commented
![image](https://user-images.githubusercontent.com/66163761/222957316-a89ff982-85f0-4705-a3ec-358f37bbe5dd.png)

2023-03-05 11:19 UTC, closed without merging