Deletes RND
tgstation/TerraGov-Marine-Corps pull request #12321
Opened 2023-03-04 11:13 UTC by Xander3359

## About The Pull Request
Deletes RND and things associated to it.

## Why It's Good For The Game
We don't have RND, this is dead code.

## Changelog

:cl:
del: Removed RND, old unused code.
/:cl:

2023-03-04 12:26 UTC, tyeagg commented
you should atleast replace the deleted map ones with prop computers

2023-03-04 14:32 UTC, RipGrayson requested changes
Replace the deleted RND stuff on the maps with props please.

2023-03-04 16:28 UTC, FIXTHERADBOXPLEASE commented
Erm isn't it just there for decoration?

2023-03-04 19:59 UTC, RipGrayson approved these changes

2023-03-05 09:45 UTC, TiviPlus approved these changes

2023-03-05 10:42 UTC, merged