Powerfist is easier to unload. No longer sends the user flying.
tgstation/TerraGov-Marine-Corps pull request #12332
Opened 2023-03-05 23:57 UTC by Xander3359

## About The Pull Request
You no longer need a screwdriver to unload the powerfist. Click it with off-hand while holding it or right click it.
Powerfist no longer sends you flying if you accidentally (or intentionally) punch yourself.
Powerfist can now use up the entire cell worth of charge (So you can punch 10x on level 3 instead of 9 times which was a bug)

## Why It's Good For The Game
Makes powerfist less janky to unload (why screwdriver???).
![image](https://user-images.githubusercontent.com/66163761/222993453-1da4f7f8-4fbe-462d-a07f-6636a7ecc651.png)

## Changelog

:cl:
add: Powerfist cell is easier to remove.
del: You can no send yourself flying with your own powerfist.
fix: powerfist cell can properly reach 0 charge.
/:cl:

2023-03-05 23:59 UTC, QualityVan commented on code/game/objects/items/weapons/misc.dm
> +			user.visible_message(span_userdanger("You punch yourself!"))
Won't this show to everyone nearby?

2023-03-06 00:14 UTC, Xander3359 commented on code/game/objects/items/weapons/misc.dm
> +			user.visible_message(span_userdanger("You punch yourself!"))
uh, maybe.

2023-03-06 00:21 UTC, Losenis commented
Make it tac-reloadable pls

2023-03-06 05:53 UTC, Naaanii commented
Loading good.

Self punch is funny though <s>and you can literally prevent it with the toggle self harm keybind lol</>

The fist is also not rooted in place so your arm isn't meant to rip off either.

2023-03-06 08:34 UTC, ThelastArchiver commented
i think it was meant in a way how force works you cant punch yourself away the same way you cannot just liftyourself up by pulling yourself up

2023-03-06 09:17 UTC, FosterGrime-Heymynameslouie commented
![image](https://user-images.githubusercontent.com/59080633/223067790-5c1fdbc8-c03c-453b-876d-9a9007f33e36.png)

lol

2023-03-06 11:00 UTC, RaidarV commented
Make it launch the way you are facing (like the original idea) but you drop the powerfist.

2023-03-09 09:44 UTC, TiviPlus requested changes
Rest whatever

2023-03-09 09:44 UTC, TiviPlus commented on code/game/objects/items/weapons/misc.dm
> +	var/powerused
this var has no reason to exist

2023-03-09 09:44 UTC, TiviPlus commented on code/game/objects/items/weapons/misc.dm
> +		user.apply_damage(force * setting, BRUTE, user.zone_selected, MELEE, penetration = src.penetration)
no src.var

2023-03-12 12:59 UTC, merged