Survivors are back.
tgstation/TerraGov-Marine-Corps pull request #12337
Opened 2023-03-06 13:35 UTC by Naaanii

## About The Pull Request
Title.

Survs no longer have the best of all skills and most have been toned down to marine specialisation equivalent.
Survs have slightly better CQC and Melee skills.

Following aims have been addressed:
Prevent rush ✔
Xenos now have RTS instant build. (If you get rushed with this, I simply have no words).

No gamer gear ✔
Slowdown added to armour. Some new weapons are also added for flavour, but apart from repeater, they're not exactly gamer gear.

No noob traps ✔
Most map reworks have removed noob traps.
Magmoor no longer has lava land but rather a lake or something but its somewhat harder to cheese and can be addressed if needed.

A non-killing Xeno objective ✔
Survivors can have a jump start on disks now that nukewar is the sole gamemode. Further objectives can be added later.

## Why It's Good For The Game
Survs were fun and now are more challenging than ever.
Xenos have RTS build, the ability to build structures like acid turrets, mat towers and silos will refund the points survivors add passively unlike its hunt counterpart. On top of that survs give larva points for joining AND getting drained/cocooned if they fail to kill any Xenos, which will be most likely.

If anything, survs might need further buffs/qols or objectives to focus on but this feels like a good starting point.

## Changelog

:cl:
add: Survivor is now pickable again
add: Adds repeater, garand and Ppsh to survivor rng starting guns.
balance: Adds slowdown to survivor armor
balance: Lowers survivor medic and engi skills to match squad corpsmen and engineers.
balance: Gives survivors slightly better CQC and Melee skills.
/:cl:

2023-03-06 13:37 UTC, Pariah919 commented
>Following aims have been addressed:
Prevent rush ✔
Xenos now have RTS instant build. (If you get rushed with this, I simply have no words).
>
don't you just die to a hivelard running up to you, and rts building on you?

2023-03-06 13:38 UTC, Naaanii commented
> > Following aims have been addressed:
> > Prevent rush ✔
> > Xenos now have RTS instant build. (If you get rushed with this, I simply have no words).
> 
> don't you just die to a hivelard running up to you, and rts building on you?

Probably. At least survs can't rush Xenos.

2023-03-06 13:39 UTC, Naaanii commented
> > > Following aims have been addressed:
> > > Prevent rush ✔
> > > Xenos now have RTS instant build. (If you get rushed with this, I simply have no words).
> > 
> > 
> > don't you just die to a hivelard running up to you, and rts building on you?
> 
> Probably. At least survs can't rush Xenos.

On a side note, rushing LZs would prevent them getting cheesed but yeah, it's going to be rough for them.

2023-03-06 14:29 UTC, RaidarV commented
I will be attributing this year's survivor pr to myself (cause I was the one pointing out Naani he should add them back in according to couple years old comment in code). 

And since I have the @Balance role in Discord, my word must obviously be taken with utmost serious-ity and this PR must be merged.

Also based sphehd mherhjg now.......

2023-03-06 14:38 UTC, MiniMeatwad commented
> Xenos now have RTS instant build. (If you get rushed with this, I simply have no words).
Why would you even add survivors with this in mind? Just wall them in remotely and kill them with the entire hive.

Adding a check for it may be a bit expensive with how it's currently coded, and it prevents xenos from building.

> Most map reworks have removed noob traps.
Subject to change, also said many times in similar form throughout TGMC history, yet never true. New players will die to anything.

> Survivors can have a jump start on disks now that nukewar is the sole gamemode. Further objectives can be added later.
Same idea, since disks are supposed to be a win condition for marines. No flavor here.

2023-03-06 15:36 UTC, chizzy376 commented
> Why not just remove survivor armor entirely and have them scavenge armor found in lockers/prespawned corpses? Also survs will likely get absolutely shafted by instant ranged building unless they park themselves right next to either LZ so i would propose some sort of placable item similar to teleporter or dispenser that prevents xeno building in a small area around it (until shutters open maybe or just have them have a timer after being deployed).

Sir there's no armor spawns on maps

2023-03-06 15:38 UTC, MiniMeatwad commented
> i would propose some sort of placable item similar to teleporter or dispenser that prevents xeno building in a small area around it

Maybe give turfs flags for not being built on, add it to the list of checks, and give them a structure that once deployed marks the surroundings with the flag?

2023-03-06 17:10 UTC, RipGrayson commented
> > Why not just remove survivor armor entirely and have them scavenge armor found in lockers/prespawned corpses? Also survs will likely get absolutely shafted by instant ranged building unless they park themselves right next to either LZ so i would propose some sort of placable item similar to teleporter or dispenser that prevents xeno building in a small area around it (until shutters open maybe or just have them have a timer after being deployed).
> 
> Sir there's no armor spawns on maps

This is a point, since survivors have been deprecated for some time now, not all maps have the spawns for them. They need added back if Tivi decides this is a thing that is happening.

2023-03-06 23:57 UTC, shelteredfreak commented
Finally, some good fucking PRs (Kidding, all of the ones I've seen so far are great. But this is a change I've been preaching for ages about)

2023-03-07 04:00 UTC, Joe13413 commented
maybe survivors could have an area around them where quickbuild is disabled? probably just a good idea on paper but tossing it out there. A fundamental rework to quickbuild could also solve this but otherwise based as fuck PR. i've wanted to try survivors for so long but i dont want to go to CM

2023-03-07 10:24 UTC, Coastfront commented
This is a call for a star-headed screw in a land where none may drive it.
It's not pointless yet nor does it really have a considerable reason to exist.

With quickbuild, survivors either will have to just hide, camp the lz, or just get unceremoniously obliterated by getting literally walled off from their own defenses and then killed, if xenos either get rushed or SOMEHOW can't kill a survivor when they can now literally instantly cut them off from their own defenses, then the xenos are idiots.

Inversely, if there was something added to stop quickbuild in an area around survivors then they are now an important meta role because they can cuck xenos from being able to easily prep importantly areas quickly if they can manage to hold important positions, making them into a role that marine vets will play as a throw away again to cuck xenos.

They're a role whose single niche has been waterlogged and swept away as silt in this river, where once was a hill for them to burrow is now a vally that they have no right to exist in.
They are either doomed to be irrelevent psi point fodder, as I refuse to believe in quickbuilds current state survivors could unironically hope to make it to the shutters opening unless if xenos allow or it are just outright entirely incompetent, with not a single decent player on their team. and basically any other effort to buff them to where they're not just objectively fucked is going to flow naturally into them being the meta role that vets play to cuck xenos and will make them too actually important.

The games balance kept going without them, for good reason. And thus there really isn't an immense need nor place for them.

2023-03-07 18:41 UTC, Aporhtonoma commented
I wake and see this beauty speedmerge
also on the point some people say about a hivey gaming all over you we got flag turfs for benos building preshutters maybe expand em a bit but if you are that worried chill outside the lz .Its the darksouls difficulty of marine gameplay and I want in.

2023-03-08 00:18 UTC, Arturlang commented
> > Following aims have been addressed:
> > Prevent rush ✔
> > Xenos now have RTS instant build. (If you get rushed with this, I simply have no words).
> 
> don't you just die to a hivelard running up to you, and rts building on you?

Keep in mind weeds are still required for quickbuild, and hivelord can't use weed walk off weeds. So unless they stand still while the hivelord weeds around them, they'll probably be fine

2023-03-08 10:48 UTC, TiviPlus commented
As said in discord you need to handle rts building properly, proper rush prevention and actually add objectives

For the rest of you text walling I wouldn't get your hopes up yet

2023-03-08 10:48 UTC, TiviPlus requested changes
.

2023-03-08 10:52 UTC, Naaanii commented
Will work on it.

2023-03-08 12:04 UTC, Autisem commented
honestly let them keep the non combat skills. it lets survivors be employed as non-combat roles instead which I think is neat concept

2023-03-08 12:07 UTC, Naaanii commented
> honestly let them keep the non combat skills. it lets survivors be employed as non-combat roles instead which I think is neat concept

They still have it. Its just not max-rank.

2023-03-08 12:15 UTC, Arturlang commented
Could simply make painting not possible around living humans in a screen's or more width @Naaanii

2023-03-08 12:22 UTC, Autisem commented
> > honestly let them keep the non combat skills. it lets survivors be employed as non-combat roles instead which I think is neat concept
> 
> They still have it. Its just not max rank.

Not too famaliar with medical code, but does this not make them kinda wack at surgery? I dont know what corpsman level is but yeah

2023-03-08 12:22 UTC, Naaanii commented
> Could simply make painting not possible around living humans in a screen's or more width @Naaanii

Will look into it but also need to find a way for survivors to not rush. Dying to a survivor is a skill issue in itself but it still shouldn't be allowed as rushing to deny building caves can also be an issue.

Furthermore, it's also possible to wall off entire sections of maps to just corner survivors and then delete them to regain the walls used after a survivor has been eliminated so fixed locations where building is limited and not instant sounds like a better idea.

2023-03-08 12:24 UTC, Naaanii commented
> > > honestly let them keep the non combat skills. it lets survivors be employed as non-combat roles instead which I think is neat concept
> > 
> > 
> > They still have it. Its just not max rank.
> 
> Not too famaliar with medical code, but does this not make them kinda wack at surgery? I dont know what corpsman level is but yeah

They shouldn't have surgery skills with gun skills either way.

2023-03-08 12:38 UTC, Autisem commented
> > > > honestly let them keep the non combat skills. it lets survivors be employed as non-combat roles instead which I think is neat concept
> > > 
> > > 
> > > They still have it. Its just not max rank.
> > 
> > 
> > Not too famaliar with medical code, but does this not make them kinda wack at surgery? I dont know what corpsman level is but yeah
> 
> They shouldn't have surgery skills with gun skills either way.

why not? seems like a nice reward for surviving that you can have some one be an extra supporting unit like the synths, otherwise they are just more sweaty marines(which is not bad but kinda sad since could be a fun way to add value)

2023-03-08 12:42 UTC, Naaanii commented
Specialised roles exist for that and it's better for them to focus on combat. Ironically, they're even better than FC without leadership perks.

2023-03-08 17:15 UTC, Aporhtonoma commented
i know this is a mapper thing but we can just fogwall the caves till shutters open since if the intention is for survivors is to not rush benos and non hunt down hive missions it should not obstruct them (and honestly if you intentionally leave the fog wall and die to them its on you) .

2023-03-18 12:42 UTC, docRoboRobert commented
test when.

2023-03-29 00:48 UTC, closed without merging