Vending machine no longer dispenses empty guns.
tgstation/TerraGov-Marine-Corps pull request #12344
Opened 2023-03-07 14:39 UTC by Xander3359

## About The Pull Request
For some reason vending machines check if a gun is being vended, if it, it makes the gun empty. I am removing this check.

Also, removed the RL72 rocket from the vendor (since you literally cannot reload the oneuse RL).

## Why It's Good For The Game
Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/12019

## Changelog

:cl:
fix: RL72 is no longer broken in valhalla
fix: Guns no longer vend empty.
/:cl:

2023-03-08 10:43 UTC, TiviPlus requested changes

2023-03-08 10:43 UTC, TiviPlus commented on code/game/objects/machinery/vending/vending.dm
> +	else if(ispath(R.product_path,/obj/item/weapon/gun))
Too snowflake this needs a proper fix

2023-03-09 19:55 UTC, Xander3359 commented on code/game/objects/machinery/vending/vending.dm
> +	else if(ispath(R.product_path,/obj/item/weapon/gun))
What kind of fix do you want for it?

2023-03-13 03:37 UTC, Lumipharon approved these changes

2023-03-13 03:37 UTC, merged