PT belt is here
tgstation/TerraGov-Marine-Corps pull request #12356
Opened 2023-03-08 22:23 UTC by novaepee

## About The Pull Request

Add in the PT belt.

You can put it in your armor so that you won't get run over by mech. Truly, innovative technology.

## Why It's Good For The Game

fluff

## Changelog

:cl:
add: PT belt is here
/:cl:

2023-03-09 02:05 UTC, XSlayer300 commented on code/modules/clothing/modular_armor/attachments/modules.dm
> +	name = "\improper Physical training reflective belt"
```suggestion
	name = "\improper physical training reflective belt"
```

2023-03-09 09:47 UTC, TiviPlus requested changes
Whats the point of this exactly you need to explain in the pr

2023-03-09 12:56 UTC, Moggram commented
> Whats the point of this exactly you need to explain in the pr

I see some one has never been in the army.

2023-03-09 19:39 UTC, GreatKingWombat commented
No fun allowed I guess.

2023-03-10 04:39 UTC, Al-1ce commented
> Can the mech ran you over though, what the belt even do lad

It's like one of those yellow/neon vests police might wear. It's meant for high-visibility. Nothing else.

2023-03-10 05:27 UTC, novaepee commented
will make it attach to uniform instead of armor lel

2023-03-10 20:20 UTC, merged