More Xeno abilities have stagger immunity. More can be used while resting.
tgstation/TerraGov-Marine-Corps pull request #12384
Opened 2023-03-11 08:42 UTC by Naaanii

## About The Pull Request
Resting, planting weeds and mainly Xeno spits have the stagger immune trait.
Abilities like spawning huggers, making resin traps, jelly and creating spiderlings can be used while resting.

## Why It's Good For The Game
Some nice QOLs for Xenos to make stuff while resting.

Stagger should stop Xenos from using more useful and higher impact abilities rather than basic ones. I'd lop spits in with resting and weed planting with this. This should also make stagger feel less oppressive and slightly easier to balance in the forseeable future as the biggest issue with stagger spam is also the ability to make Xenos unable to unrest and permacuck ranged castes out of spits.

Panic hugger should be stagger immune for a 'panic' ability.

## Changelog

:cl:
qol: Drone and Hivelord can create jelly while resting.
qol: Carrier can place traps while resting.
balance: Xenos can unrest/rest and plant weeds while staggered.
balance: Xenos can spit while staggered.
balance: Carrier can choose hugger types and can spawn huggers (not throw) while staggered.
balance: Carrier can panic hugger while staggered.
/:cl:

2023-03-11 08:49 UTC, QualityVan commented on code/modules/mob/living/carbon/xenomorph/abilities.dm
> +	use_state_flags = XACT_USE_LYING| XACT_USE_STAGGERED //Can use this while staggered
Extra space here. Comments are all kinda useless.

2023-03-11 09:25 UTC, Naaanii commented on code/modules/mob/living/carbon/xenomorph/abilities.dm
> +	use_state_flags = XACT_USE_LYING| XACT_USE_STAGGERED //Can use this while staggered
Real

2023-03-11 11:56 UTC, Oscari-pog commented
Calling a flat buff a QoL

2023-03-11 12:41 UTC, Naaanii commented
> Calling a flat buff a QoL

Using abilities that don't impact gameplay while resting is a QoL indeed.

2023-03-11 17:06 UTC, Barnet2 commented
Good PR.

2023-03-11 18:26 UTC, Zangeiti commented
> > Calling a flat buff a QoL
> 
> Using abilities that don't impact gameplay while resting is a QoL indeed.

stagger should still cuck xeno spits, and this isn't just a QoL change

2023-03-11 20:43 UTC, Naaanii commented
> > > Calling a flat buff a QoL
> > 
> > 
> > Using abilities that don't impact gameplay while resting is a QoL indeed.
> 
> stagger should still cuck xeno spits, and this isn't just a QoL change

And it's labelled with both.

2023-03-11 21:08 UTC, Lumipharon requested changes
Rest/unrest, choose huggos, and panic drop are all fine for staggered use, the other ones I don't really agree with.

2023-03-14 04:01 UTC, Lumipharon commented
What about all the other stuff? I meant specifically those 3 changes I were fine with. Being able to do stuff while resting is cringe and I would fix xenos being able to rest mid channel on things if I wasn't lazy.

2023-03-14 05:19 UTC, Naaanii commented
> What about all the other stuff? I meant specifically those 3 changes I were fine with. Being able to do stuff while resting is cringe and I would fix xenos being able to rest mid channel on things if I wasn't lazy.

There's not much difference when doing those things while resting or not.
Jelly has a long enough CD for it to not matter.
Spiderlings the same.
Carriers can't make more than one trap on tile and had this interaction before.
Essence link also makes no difference.

Don't really see how any of these are 'cringe' without any further explanation.

2023-03-15 23:20 UTC, Mannybrado commented
You can already make huggers while rested. Dunno about spiderlings.

2023-03-26 00:46 UTC, closed without merging