backblast particles
tgstation/TerraGov-Marine-Corps pull request #12393
Opened 2023-03-12 17:05 UTC by tyeagg

## About The Pull Request
backblast particles for rocket launchers

https://user-images.githubusercontent.com/98577688/224560364-205ea63e-25f7-4d88-a34b-da9a75227912.mp4

## Why It's Good For The Game
looks nice

## Changelog

:cl:
add: particles for rl backblast
/:cl:

2023-03-12 19:49 UTC, novaepee commented
Does Alamo also release backblast particles when flying away?

2023-03-12 21:06 UTC, Lumipharon approved these changes
Neat

2023-03-13 10:15 UTC, TiviPlus requested changes

2023-03-13 10:15 UTC, TiviPlus commented on code/modules/projectiles/guns/specialist.dm
> +	backblast.particles.velocity = list(x_component * 1, y_component * 1)
Multiplying by 1?

2023-03-13 10:15 UTC, TiviPlus commented on code/modules/projectiles/guns/specialist.dm
> +
Should use QDEL_NULL_IN or even better just add the particle holder to vis contents as needed so you dont need to recreate it every time

2023-03-19 13:59 UTC, merged