Adds "Rewrite Loadout" button to the loadout vendor.
tgstation/TerraGov-Marine-Corps pull request #12405
Opened 2023-03-13 11:21 UTC by Xander3359

## About The Pull Request
Ports https://github.com/Cosmic-Overlord/TerraGov-Marine-Corps/pull/35
![image](https://user-images.githubusercontent.com/66163761/224686795-b0326f5c-155a-4103-8b7b-a91db4de4104.png)
![image](https://user-images.githubusercontent.com/66163761/224687526-3768b3f2-b1ca-4969-8b46-662c5cadb9a4.png)
![image](https://user-images.githubusercontent.com/66163761/224687592-633b1ef4-37a4-44dd-adf9-a34bb0f4ed52.png)

## Why It's Good For The Game
It's just better loadout management.

## Changelog

:cl:
add: "Rewrite loadout" button in Loadout Vendor
/:cl:

2023-03-13 11:58 UTC, maikilangiolo commented
No fucking way. We have the technology

2023-03-14 16:36 UTC, TiviPlus requested changes

2023-03-14 16:36 UTC, TiviPlus commented on code/modules/tgui_input/alert.dm
> +/datum/tgui_alert/New(mob/user, src_object, message, title, list/buttons, timeout, autofocus)
?? what is this

2023-03-14 19:29 UTC, Xander3359 commented on code/modules/tgui_input/alert.dm
> +/datum/tgui_alert/New(mob/user, src_object, message, title, list/buttons, timeout, autofocus)
idk I've just ported it from RU

2023-03-18 23:04 UTC, zzurge commented
I kneel

2023-03-20 21:47 UTC, Lumipharon approved these changes

2023-03-20 21:50 UTC, merged