Slight Xeno crash buffs
tgstation/TerraGov-Marine-Corps pull request #12435
Opened 2023-03-15 07:42 UTC by Naaanii

## About The Pull Request
Xenos always get Elder when evolving.

## Why It's Good For The Game
When Xenos were allowed to carry on maturity points most of the times, Xenos would be ancient and get elder when evolving.
Since maturing was made more consistent, in crash it wasn't the case since maturity points still started from 0 while T1s start at elder but when evolving to T2 or anything more, they would be dropped back down to young rather than mature.

This should help reintroduce the previous interaction without making Xenos too powerful whilst also being a bit of a slight buff when Xenos evolve instantly.

## Changelog

:cl:
balance: Xenos get Elder when evolving, regardless of Tier.
/:cl:

2023-03-24 12:51 UTC, MiniMeatwad commented
Because you're setting the upgrade value, you're also potentially removing upgrade value. This means crash Xenos cannot benefit from keeping their upgrade progress when they stay as a lower tier.

2023-03-24 14:07 UTC, Naaanii commented
> Because you're setting the upgrade value, you're also potentially removing upgrade value. This means crash Xenos cannot benefit from keeping their upgrade progress when they stay as a lower tier.
> 
> Also the guy who did this (Whoever did crash) was highly insistent that it's intentional game design and that it's not a bug, which is funny.

What upgrade value is being removed exactly?

2023-03-24 22:39 UTC, Lumipharon requested changes
As QV said, this means reverting back to T1 will REDUCE your maturity points back to TIER_ONE_MATURE_THRESHOLD which is severely nerfing the xeno.

This also removes the bonus from t2 evos so this seems like a funny xeno nerf pr.

2023-03-25 01:23 UTC, Naaanii commented
> As QV said, this means reverting back to T1 will REDUCE your maturity points back to TIER_ONE_MATURE_THRESHOLD which is severely nerfing the xeno.
> 
> This also removes the bonus from t2 evos so this seems like a funny xeno nerf pr.

I literally tested this and it doesn't

It doesn't remove the T2 bonus because it grants the maturity points required for T1 so when Xenos evo into T2, they're mature so it changes nothing.

Even regressing to larva and evoing back into a T1 does not reset your maturity points.

2023-03-25 05:11 UTC, Lumipharon commented
Oh cool, turns out finish_evolve has a hard check to stop maturity from decreasing. Its still bad to just rely on that though, as regardless you're just hard setting the maturity points which can mean decreasing it. Better to have a check here as well. i.e. = max(current amount, TIER_ONE_MATURE_THRESHOLD )

2023-03-27 09:16 UTC, Lumipharon approved these changes

2023-03-27 10:03 UTC, merged