Hyposprays can draw reagent with right click.
tgstation/TerraGov-Marine-Corps pull request #12454
Opened 2023-03-17 08:35 UTC by Xander3359

## About The Pull Request
Copy-pastes reagent drawing functionality over to afterattack_alternate, so you can draw reagents using right click.

## Why It's Good For The Game
The UI is clunky and slow, this goes around the problem in a TG-esque way. Being able to draw reagents with right click instead of having to open the UI, set it to draw mode and then left click your container.
I HAVE NOT TOUCHED THE UI OR DRAW MODE, just added draw mode innately to right click.

## Changelog

:cl:
add: Hyposprays can now draw reagent with right click.
/:cl:

2023-03-18 13:23 UTC, FIXTHERADBOXPLEASE commented
Hypo-medic is getting more and more viable... good

2023-03-19 02:35 UTC, Lumipharon requested changes
Don't copy paste functionality.

2023-03-27 09:09 UTC, Lumipharon requested changes

2023-04-05 09:56 UTC, Lumipharon requested changes

2023-04-05 09:56 UTC, Lumipharon commented on code/game/objects/items/reagent_containers/hypospray.dm
> +		return FALSE
Why is this after the if statement above? This is also missing from the alt attack

2023-04-05 09:56 UTC, Lumipharon commented on code/game/objects/items/reagent_containers/hypospray.dm
> -///Draws reagent from container A.
you deleted the autodoc?

2023-04-05 09:56 UTC, Lumipharon commented on code/game/objects/items/reagent_containers/hypospray.dm
> +							span_notice("You take a blood sample from [A]."), null, 4)
This doesn't have anything to do with "can draw reagent". I would just make this a separate draw_blood proc or something.

2023-04-05 21:13 UTC, Lumipharon requested changes

2023-04-05 21:13 UTC, Lumipharon commented on code/game/objects/items/reagent_containers/hypospray.dm
> +		return FALSE
This should probs still be in the afterattack proc. That also means you don't need the alt_draw_mode arg.

2023-04-05 21:13 UTC, Lumipharon commented on code/game/objects/items/reagent_containers/hypospray.dm
> +		return FALSE
This also needs to be in the attack proc(s), as its going to runtime otherwise on the range checks.

2023-04-05 21:13 UTC, Lumipharon commented on code/game/objects/items/reagent_containers/hypospray.dm
> +		return
Why are these checks in this proc? Its a bit confusing to have checks spread across the two procs, it should probably all be in the can_draw proc.

I think you may have done it this way due to how you currently have the attack proc configured? By having the inject mode check there per my other comment, you won't have that issue.

2023-04-05 22:57 UTC, Lumipharon requested changes

2023-04-05 22:57 UTC, Lumipharon commented on code/game/objects/items/reagent_containers/hypospray.dm
> +///Always draws reagents on right click
We don't want to overwrite existing autodoc, we only do it for new procs.

2023-04-05 22:57 UTC, Lumipharon commented on code/game/objects/items/reagent_containers/hypospray.dm
> +///Returns TRUE if we successfully draw from something
Do this as proper multiline autodoc or just make it one line. It doesn't really need to be this detailed.

2023-04-07 23:21 UTC, Lumipharon approved these changes

2023-04-07 23:22 UTC, merged