Adds the Heimdallr Armor Module, a flare launcher
tgstation/TerraGov-Marine-Corps pull request #12477
Opened 2023-03-20 20:44 UTC by carlarctg

## About The Pull Request

Adds the Heimdallr Armor Module, a flare launcher

Codewise a gun beacuse apparently its the best way to do it

Fires flares like the experimental armor module

## Why It's Good For The Game

It's cool

## Changelog

:cl:
add: Adds the Heimdallr Armor Module, a flare launcher
/:cl:

2023-03-21 01:34 UTC, Xander3359 commented
![image](https://user-images.githubusercontent.com/66163761/226499539-2a03a795-aa6a-4666-82b0-e58e3c43631c.png)
They are PROC_REF now

2023-03-21 02:33 UTC, Losenis commented
How does this work for storage? Does it give the armor storage to contain the flares it'd launch?

2023-03-21 07:22 UTC, Xander3359 commented
> a way to mass-reload by just using a flare box on it.

It's already possible to add this to any storage simply by using var/refill_types 
![image](https://user-images.githubusercontent.com/66163761/226540701-fc36c705-584c-4836-a239-d8a66c316575.png)

2023-03-21 11:07 UTC, Goblinu commented
The flare powercreep continues

2023-03-21 12:53 UTC, Kuro020 approved these changes

2023-03-24 12:52 UTC, Naaanii commented
> The flare powercreep continues

Annoy Zaro #12109

2023-03-24 13:18 UTC, TiviPlus requested changes
Debatable if should be free but the balance screamers will figure it out

2023-03-25 01:53 UTC, 567Turtle commented
FUCK...

2023-03-25 02:08 UTC, 567Turtle commented
Rename to Sol, the god of the sun in Norse mythology so I don't have to rename my pr ty :) #12507 [12507](https://github.com/tgstation/TerraGov-Marine-Corps/pull/12507)

2023-03-25 02:56 UTC, 567Turtle commented
Nevermind I renamed mine to Freyr

2023-03-26 20:19 UTC, Lumipharon requested changes

2023-03-26 20:19 UTC, Lumipharon commented on code/modules/projectiles/guns/grenade_launchers.dm
> +	flags_gun_features = GUN_AMMO_COUNTER|GUN_IFF
why's it IFF?

2023-03-26 20:19 UTC, Lumipharon commented on code/modules/projectiles/guns/grenade_launchers.dm
> +	max_chamber_items = 7
max_shells and max_chamber_items say 7, desc says 14.

2023-03-26 20:19 UTC, Lumipharon commented on code/modules/projectiles/guns/grenade_launchers.dm
> +/obj/item/weapon/gun/grenade_launcher/multinade_launcher/able_to_fire(mob/user)
is uh, this not supposed to be at the flare_cannon level?

2023-04-11 00:41 UTC, closed without merging