adds the vali claymore
tgstation/TerraGov-Marine-Corps pull request #12485
Opened 2023-03-21 22:41 UTC by 567Turtle

## About The Pull Request

Adds the vali claymore, deals 90 damage and takes 20 ticks to swing. Has to be held with two hands for full effect.

![image](https://user-images.githubusercontent.com/91508746/226757907-967fa458-fc27-4b07-956e-3e7ff856d48e.png)

## Why It's Good For The Game

Kuro asked me too, the sprites look cool and more choices are always nice.

## Changelog

:cl:
add: Harvester claymore, available at marine vendors
/:cl:

2023-03-22 00:14 UTC, ivanmixo commented on code/game/objects/items/storage/holsters.dm
> +	INVOKE_ASYNC(src, .proc/handle_item_insertion, new_item)
```suggestion
	INVOKE_ASYNC(src, PROC_REF(handle_item_insertion), new_item)
```
515

2023-03-22 09:28 UTC, Oscari-pog commented
I was fully expecting a vali claymore mine

2023-03-22 12:26 UTC, iforgotmeword commented
Sadly I thought the same I was about to so happy about bootleg OT 

(Still really mad they removed bootleg OT

2023-03-22 13:36 UTC, 567Turtle commented
> This should use the other sprites that cs - m made, also ![image](https://user-images.githubusercontent.com/52428261/226920904-28cbeaf1-2d00-4a17-9f77-0742aaa738fb.png) uhhhhhhhhhhhhhhhhhhhhhhhh

I have no clue how or why the other sprites there got deleted I'll fix it later and add the new spdites

2023-03-23 21:46 UTC, zzurge commented
One step closer to crescent rose...

2023-03-24 00:38 UTC, Kuro020 approved these changes

2023-03-24 01:17 UTC, Jalopkomit18 commented
Everyday we grow closer to monster hunter. Add hunting horn next

2023-03-24 13:16 UTC, TiviPlus requested changes
rest lgtm

2023-03-24 13:16 UTC, TiviPlus commented on code/game/objects/items/weapons/twohanded.dm
> +	var/codex_info = {"<b>Reagent info:</b><BR>
Autodoc

2023-03-25 00:29 UTC, Al-1ce commented
Sprites are a bit weird. The wire/connecting thing really screws up the perspective and makes it look less like a sword and more like a green 2x4

2023-03-25 10:41 UTC, chizzy376 commented
The green handheld plank

2023-03-26 06:56 UTC, 567Turtle commented
> Sprites are a bit weird. The wire/connecting thing really screws up the perspective and makes it look less like a sword and more like a green 2x4

Send any sprite issues you have to Lactose as I can't sprite for shit and they're the ones who made it thank you

2023-03-26 14:39 UTC, docRoboRobert commented
Totally not made for vergili.

2023-03-26 21:53 UTC, Lumipharon commented
autodoc is 3 forward slashes

2023-03-27 04:36 UTC, 567Turtle commented
autodoc is 3 slashes meh meh meh

2023-03-27 10:55 UTC, TiviPlus commented on code/game/objects/items/weapons/twohanded.dm
> +	var/codex_info = {"<b>Reagent info:</b><BR>
```suggestion
	/// Lists the information in the codex
	var/codex_info = {"<b>Reagent info:</b><BR>
```

2023-03-27 11:03 UTC, merged

2023-03-29 01:38 UTC, Al-1ce commented
In after sight this is pretty unbalanced.