CIC-Overwatch and CAS missions get minimaps, improves AIs minimap
tgstation/TerraGov-Marine-Corps pull request #12496
Opened 2023-03-22 21:31 UTC by DeltaFire15

## About The Pull Request
This PR adds a minimap to CIC's consoles while in the overwatch camera view, which updates its z to the one currently viewed (or none if the z is minimapless).
Similarly, the AI minimap is now improved to track whichever z the AI's eye is on currently.
CAS also gets a minimap while running strike missions, and this might allow it to give it laze locations on the minimap at a later time (would be out of scope for this PR and I'm already doing enough here)

The locator also tracks the eyes and not the user in CIC / wherever, for all of these added / modified minimaps.
Minimap code may contain a little bit of signal sorcery to achieve this but it should work fine. Please do testmerge this before fullmerging, as there may nonetheless be things I missed or oopsied.

Also fixes two minor minimap related things,
one is that *default_overwatch_level* for minimaps didn't work properly due to a missing return call (though *default_overwatch_level*s aren't used at the moment now that I made AIs able to view different z's maps)
second was that miners used to runtime due to doing some minimap related things twice

## Why It's Good For The Game
CIC: Overwatch is supposed to be able to coordinate marines and be their eyes, which is somewhat difficult without easy access to the minimaps every single groundside marine has. This should make keeping an eye on the force as a whole easier, while also helping navigate the map.

AI: AIs minimap at the moment is effectively useless, only ever showing the ship's map which only matters when xenos board. This should allow it to be a more useful "eye" to the marines, akin to CIC.

CAS: As CAS pilot, it can sometimes be difficult to ascertain where marines are, aswell as where major combat is happening, especially ever since lazes were made unneccessary to deploy into strike mode. This should make it easier to locate marines and engagements, while also being able to coordinate somewhat better.

Bugfixes: Fix man good.

## Changelog

:cl:
add: CIC Overwatch now has a minimap while using the camera system.
add: CAS now has a minimap while on a groundside strike mission.
balance: AI's minimap now tracks the z the AI's eye is on, instead of only shipside
fix: Miners no longer cause minimap-related runtimes every init.
fix: default_overwatch_level for minimaps should now work properly.
code: Minimaps now support tracking atoms which aren't the owner of the action.
/:cl:

2023-03-22 23:23 UTC, ClosetedSkeletonGH commented
Huge

2023-03-22 23:43 UTC, Lumipharon commented
Nice

2023-03-24 13:29 UTC, TiviPlus requested changes
rest ltgm

2023-03-24 13:29 UTC, TiviPlus commented on code/game/objects/machinery/miner.dm
> +/obj/machinery/miner/proc/init_marker()
autodoc

2023-03-24 14:52 UTC, DeltaFire15 commented on code/game/objects/machinery/miner.dm
> +/obj/machinery/miner/proc/init_marker()
forgor

2023-03-24 14:55 UTC, DeltaFire15 commented
> Make it for the tadpole too? I do wish sometimes I could actually see where marines and bodies are without having to land then relaunch and work on memory.

Shouldn't be much of a hassle to do, but I'd prefer getting this merged first without increasing the things I touch even further. I'll code and PR that seperately once this is merged.

2023-03-25 20:00 UTC, zzurge commented
Someone remember AI exists in a PR,i kneel

2023-03-26 13:32 UTC, TiviPlus approved these changes

2023-03-26 13:32 UTC, TiviPlus commented on code/controllers/subsystem/minimaps.dm
> +	)
move this to above new var definitions

2023-03-26 15:20 UTC, DeltaFire15 commented on code/controllers/subsystem/minimaps.dm
> +	)
done.

2023-03-28 02:07 UTC, merged