Resolves overwatch consoles bricking in some scenarios
tgstation/TerraGov-Marine-Corps pull request #12537
Opened 2023-03-28 23:29 UTC by DeltaFire15

## About The Pull Request
Overwatch consoles can get a little uppity if their camera eye gets deleted, especially when tracking.
This adds an additional layer of safety that should ensure the overwatch console always has its eye reference and user removed.
Fixes #11977 

## Why It's Good For The Game
Fix man good.

## Changelog

:cl:
fix: Overwatch consoles should no longer brick under certain eye-deletion related conditions.
/:cl:

2023-03-29 20:40 UTC, Lumipharon requested changes

2023-03-29 20:40 UTC, Lumipharon commented on code/game/objects/machinery/computer/camera_advanced.dm
> +/obj/machinery/computer/camera_advanced/proc/clear_eye_ref()
autodoc

2023-03-30 17:40 UTC, DeltaFire15 commented on code/game/objects/machinery/computer/camera_advanced.dm
> +/obj/machinery/computer/camera_advanced/proc/clear_eye_ref()
guh

2023-03-30 22:11 UTC, Lumipharon approved these changes

2023-03-30 22:12 UTC, merged