Mountned autocannon rework
tgstation/TerraGov-Marine-Corps pull request #12595
Opened 2023-04-02 19:59 UTC by Pariah919

## About The Pull Request
Mounted autocannon rework. It now spawns as a moveable gun like the TAT, it is not roundstart if you're wondering..
It is now dedicated wall destroyer, dealing bonus true damage to walls, mostly effective against softer wall types like resin walls.

Overall, it fires faster, has a FULLER AUTO MODE, and the gun is balanced for heavy rifle firerate alongside the fuller auto.

Further in detail belowl
<details>

Left is new|Right is old.

Gun
-

Now has autoburst! Fires both barrels at once, mind the scatter!
Fire delay 0.5|0.25
Scope upgraded to TAT level.
Armor, coverage upgraded to TAT level.
Still has IFF.

Ammo
-

In general now has a minimum accurate range of 5 tiles, and does true damage to walls.

Normal
Damage profile of 30/50/1 from 40/100/8. Does 15 true damage to walls.

Flak
Damage profile of 40/20/5 from 40/20/12. Does 5 true damage to walls.

</details>

Sprites
![image](https://user-images.githubusercontent.com/46353991/229375844-0f8edd7f-fdbb-4e88-a1ed-cb3a9a51d246.png)

by crow, so credit to him.

## Why It's Good For The Game
Makes the autocannon unique and have a niche at the same time in both wall destruction and very long range fire support.

## Changelog

:cl:
balance: Autocannon reworked, it now has a new sprite by Crow, it now does bonus damage to walls, it does much less sunder and damage, now fires much faster and with an autoburst.
/:cl:

2023-04-02 21:59 UTC, Pariah919 commented
#12595  is better

2023-04-03 07:06 UTC, maikilangiolo commented
> Fire delay 0.5|0.25

Old fire delay was 0.5, not 0.25

Anyway, this needs a TM because it's promising

2023-04-03 16:11 UTC, Kuro020 approved these changes

2023-04-04 13:02 UTC, iforgotmeword commented
I call for the gun being nerfed or limited by making it AT OR AC 

marines are kind of getting a lot of wall breaking tools already

2023-04-16 11:43 UTC, Lumipharon commented
This is a significant dps buff even before calculating fullerauto. @Pariah919

2023-04-17 02:33 UTC, Pariah919 commented
> This is a significant dps buff even before calculating fullerauto. @Pariah919

Yeah I suppose so, you think upping the fire delay to like .35 or .4 would be good with the fuller auto included?

2023-04-19 15:33 UTC, srxtreme commented
This makes the autocannon (an expensive deployable like TAT), worse at damaging a Queen (high armor target, 65 bullet at ancient) than an AR11 (a rifle).
If the goal of the PR was to make autocannon a joke then it was a glorious success.

2023-04-19 16:00 UTC, maikilangiolo commented
After the changes requested by Lumi, this has turned in a major nerf PR. It does less damage than before (yes, even per second: 80 (before) and 75 (now)), it doesn't even do true damage vs high armor castes like before, it does less sunder (2.5 vs 16), the burst is quite honestly not worth using. The spread makes you waste half and more (depending on !fun! RNG) of your (very limited) shots at just 5 tiles of range. The fall off has risen to 5% out of 30 damage, laughable now that it doesn't even have the initial ROF to back it up.

Either maints see reason without requesting inane number changes at a whim, or please, MJP, close this PR. If you made this gun 500 points cheaper and give it larger mags, maybe it would be serve a purpose from time to time. As it stands, it's out done in damage and sunder by almost every gun with no purpose (the wall damage is too little and not worth for such a small magazine).

Fyi, the HSG still does 160 DPS 40 AP 20 SPS, vs this neutered and honestly quite sad 75 DPS 50 AP 2.5 SPS. And it's free roundstart, cheaper, with bigger mags and can be picked up. It also breaks resin walls better.

2023-04-23 22:35 UTC, Lumipharon requested changes

2023-04-23 22:35 UTC, Lumipharon commented on code/modules/projectiles/guns/mounted.dm
> +	burst_amount = 12
probs need a lower burst scatter mult, or just lower scatter in general. The burst scatter scales with burst amount, so its pretty high.

2023-04-23 22:35 UTC, Lumipharon commented on code/modules/projectiles/guns/mounted.dm
> +	burst_delay = 0.25 SECONDS
could probs make this lower. The long delay between bursts means you get punished pretty bad just shooting wildly, and its a little slow.

2023-04-23 22:35 UTC, Lumipharon commented on code/modules/projectiles/ammo_datums.dm
> +	flags_ammo_behavior = AMMO_BALLISTIC|AMMO_SUNDERING|AMMO_PASS_THROUGH_TURF|AMMO_EXPLOSIVE
Why does flak pass through walls lol?

2023-05-05 00:38 UTC, closed without merging