Hivelord's new ability: Recycler Redux
tgstation/TerraGov-Marine-Corps pull request #12648
Opened 2023-04-07 23:02 UTC by novaepee

## About The Pull Request

#12309

## Why It's Good For The Game

"Dying as xenomorph always gave an fair more opressive feeling than dying as marine. Not only you lost time to age depending on your caste but you also gave a significant amount of points. The new skill recycle aims to give xenos the possibility to at least fight for the bodies of fallen xenos and try to recover a bit from the lost. Also this skill is a hivelord exclusive making the caste more wanted and interesting."

Bring back salvage bodymass, essentially. Lefunny didn't comply with Lumi's demand, so PR was closed due to stale. We need xenomorphs content.

## Changelog

:cl: novaepee, Lefunny
add: New hivelord ability recycle. Use it on dead xenos to gain some psy points and larva progress.
soundadd: recycle has a fun eating sound.
imageadd: recycle ability sprite.
/:cl:

2023-04-10 13:36 UTC, EvilMelonTheSecond commented
> We need xenomorphs content.

So buffs are content? Are you just saying random buzzwords to get this old mechanic merged? From what I remember salvage bodymass was REMOVED because the justification you said did not justify keeping it in the game. I do not mind the balance side of things but trying to sneak a balance PR as a "feature" or "content" PR bothers me.

2023-04-10 22:21 UTC, Lumipharon requested changes

2023-04-10 22:21 UTC, Lumipharon commented on code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
> +	var/mob/living/carbon/xenomorph/X = owner
proper var names

2023-04-10 22:21 UTC, Lumipharon commented on code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
> +	playsound(X, 'sound/vore/escape.ogg', 40, channel = channel)
pls no vore.

2023-04-10 22:21 UTC, Lumipharon commented on code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
> +	succeed_activate() //dew it
this should be in use_ability, not can_use

2023-04-10 22:21 UTC, Lumipharon commented on code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
> +	. = ..()
Doesn't need a call to parent

2023-04-10 22:21 UTC, Lumipharon commented on code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
> +	if(!do_after(X, 7 SECONDS, FALSE, victim, BUSY_ICON_DANGER, extra_checks = CALLBACK(X, TYPE_PROC_REF(/mob, break_do_after_checks), list("health" = X.health))))
Pretty sure that's not the right extra_check to use.

2023-04-14 18:38 UTC, ivanmixo commented on code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
> +	hivelord.stop_sound_channel(channel)
```suggestion
	playsound(hivelord, 'sound/effects/alien_recycler.ogg', 40)
```
What's the point of starting the sound only to stop it immediately?

2023-04-14 19:04 UTC, Pariah919 commented
This isn't even xenomorph content, its just powercreep. Being able to gib bodies is le big cringe considering its the main form of point gen for most marines you can already drag corpses, giving it to hivelord is even more cringe *as you already have so much utility in one caste.*

2023-04-16 01:34 UTC, RikuTheKiller commented
> This isn't even xenomorph content, its just powercreep. Being able to gib bodies is le big cringe considering its the main form of point gen for most marines you can already drag corpses, giving it to hivelord is even more cringe _as you already have so much utility in one caste._

Just recover the corpses before a hivelord notices them. It's really not that hard considering most hives only have 1 or 2 hivelords and also hivelords spend a lot of their time building and backlining.

2023-04-17 04:09 UTC, Lumipharon requested changes

2023-04-17 04:09 UTC, Lumipharon commented on code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
> +		return FALSE
This should already be checked by parent, unless you explicitly give it the override.

2023-04-18 21:48 UTC, Lumipharon approved these changes

2023-04-19 00:19 UTC, ivanmixo commented on code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
> +	if(!do_after(owner, 7 SECONDS, FALSE, recycled_xeno, BUSY_ICON_GENERIC, extra_checks = CALLBACK(src, PROC_REF(can_use_ability))))
```suggestion
	if(!do_after(owner, 7 SECONDS, FALSE, recycled_xeno, BUSY_ICON_GENERIC, extra_checks = CALLBACK(src, PROC_REF(can_use_ability), target, TRUE, XACT_USE_BUSY)))
```

2023-04-19 00:23 UTC, ivanmixo reviewed
Should fix it being broken

2023-04-19 00:23 UTC, ivanmixo commented on code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
> +		return FALSE
```suggestion
		if(!silent)
				hivelord.balloon_alert(hivelord, "Too far")
		return FALSE
```

2023-04-19 00:23 UTC, ivanmixo commented on code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
> +		return FALSE
```suggestion
		if(!silent)
				hivelord.balloon_alert(hivelord, "Cannot while burning")
		return FALSE
```

2023-04-19 00:23 UTC, ivanmixo commented on code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
> +		hivelord.balloon_alert(hivelord, "Sister isn't dead")
```suggestion
	if(victim.stat != DEAD)
		if(!silent)
			hivelord.balloon_alert(hivelord, "Sister isn't dead")
```

2023-04-19 00:23 UTC, ivanmixo commented on code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
> +		hivelord.balloon_alert(hivelord, "Cannot recycle")
```suggestion
	if(!iscarbon(target)||!isxeno(target))
		if(!silent)
			hivelord.balloon_alert(hivelord, "Cannot recycle")
```

2023-04-19 00:23 UTC, ivanmixo commented on code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
> +/datum/action/xeno_action/activable/recycle/can_use_ability(atom/target)
```suggestion
/datum/action/xeno_action/activable/recycle/can_use_ability(atom/target, silent = FALSE, override_flags)
```

2023-04-19 04:08 UTC, Lumipharon approved these changes

2023-04-27 06:24 UTC, Naaanii commented
Kill larva point refund or the gibbing.

2023-04-27 08:47 UTC, Lumipharon commented
I'm kinda eh about this.

As it is, the ability is very strong overall, and represents a significant increase in larva generation over time, on top of reducing marine req point production significantly.

I don't think such a larve balance change is really needed, and if it wasn't it really shouldn't be focused on a single caste like this, as it really does make them a 'mandatory' pick.

2023-04-28 22:09 UTC, maikilangiolo commented
Deny points *and* get larva points back? On the hivelord too, which already is very strong. Kinda cringe

2023-04-29 03:32 UTC, novaepee commented
> Deny points _and_ get larva points back? On the hivelord too, which already is very strong. Kinda cringe

The larva points got removal if you read the PR.

2023-05-01 22:31 UTC, Lumipharon approved these changes

2023-05-01 22:31 UTC, merged