razorwire now costs 2 metal, barbed wire 1
tgstation/TerraGov-Marine-Corps pull request #12678
Opened 2023-04-10 17:32 UTC by MacBlaze1

## About The Pull Request

1 unit of razorwire now costs 2 metal, 1 unit of barbed wire now costs 1 metal. This means that with 50 metal, you can make 25 razorwire, or 50 barbed wire. This will change how much stuff engineers can build and reinforce. This does not affect razorBURN grenades. Only handbuild razorwire.

## Why It's Good For The Game

Compared to razorburn, razorwire is very expensive. I believe this should make it so that razorwire is good for prepared positions, and razorburn remains good for quick plans. This does not change the actual damage, effects, or the fact crushers can delete razorwire at 50 integrity. Only the cost. 

## Changelog

:cl:
balance: razorwire now costs 2 metal, down from 3, and barbed wire now costs 1. 
/:cl:

2023-04-10 17:50 UTC, QualityVan commented
I guess my question is, even with this change why would you ever use metal for creation over razorfoam grenades?

2023-04-10 19:21 UTC, MacBlaze1 commented
> I guess my question is, even with this change why would you ever use metal for creation over razorfoam grenades?

pre prepared positions are incredibly powerful, and even though razorburn grenades are large, the ability to place razorwire where you want leads to tactical advantages. For example, placing razorwire behind barricades to prevent crushers from full speed charging or getting stuck. Or to prevent melee of cades. If the cades CANT be damaged, then thats additional EHP.

2023-04-10 19:23 UTC, Mrrpip commented
Might as-well ask, as barbed wire affects cade HP and what not, will this have any effects on deconstruction refunds?

2023-04-10 19:30 UTC, MacBlaze1 commented
> Might as-well ask, as barbed wire affects cade HP and what not, will this have any effects on deconstruction refunds?

Yes. Deconstruction refunds are based off of % of HP * stack amount of mat to construct

2023-04-10 19:38 UTC, QualityVan commented
> pre prepared positions are incredibly powerful, and even though razorburn grenades are large, the ability to place razorwire where you want leads to tactical advantages.

Sure, but you can preplace razor wire where you want with grenades too. Not like the stuff decays.

>deconstruction

Oh, yeah, you'll want to adjust razorwire's deconstruction since otherwise I think it's an infinite metal dupe with this change. And the manual razor wire creation via combining barbed wire and rods, since otherwise that'll still use two metal worth of rods.

2023-04-10 19:47 UTC, MacBlaze1 commented
> > pre prepared positions are incredibly powerful, and even though razorburn grenades are large, the ability to place razorwire where you want leads to tactical advantages.
> 
> Sure, but you can preplace razor wire where you want with grenades too. Not like the stuff decays.
> 
> > deconstruction
> 
> Oh, yeah, you'll want to adjust razorwire's deconstruction since otherwise I think it's an infinite metal dupe with this change. And the manual razor wire creation via combining barbed wire and rods, since otherwise that'll still use two metal worth of rods.

Nah its not an infinite metal dupe, deconstruction is based off of stack amount and obj integrity. Its about 8.33 points per razorburn razorwire, and 8.0 per metal razorwire, which is pretty nice, except currently you CANT deconstruct razorburn razorwire for a full return.

2023-04-12 14:12 UTC, QualityVan approved these changes
Turns out my memory's rubbish and you get four rods per metal sheet, not two. Should be good to go unless someone's opposed for balance reasons.

2023-04-12 21:18 UTC, Lumipharon commented
I don't really like it because it makes wired cades cheaper. Cades aren't a problem and that change specifically has been rejected before.

2023-04-13 22:54 UTC, QualityVan commented
further iteration is required

2023-04-14 03:55 UTC, QualityVan commented on code/game/objects/items/stacks/barbed_wire.dm
> -	if(!istype(I, /obj/item/stack/rods))
You can just cut the rest of this proc since razorwire making was the only thing it did.

2023-04-14 04:00 UTC, QualityVan requested changes
Adjust structure/razorwire deconstruction, since it shouldn't be producing barbed wire now. Back into a razorwire stack, or metal/rods if you want to make partial materials more granular. Up to you.

2023-04-14 05:27 UTC, QualityVan approved these changes

2023-04-14 16:58 UTC, TiviPlus approved these changes

2023-04-15 22:15 UTC, Lumipharon commented
Why'd you remove the other construction method btw?

2023-04-16 01:27 UTC, MacBlaze1 commented
> Why'd you remove the other construction method btw?

@Lumipharon I cant make the cost of razorwire 2 without reducing barbed wires cost, since barbed wire can be used to make razorwire

2023-04-18 21:48 UTC, merged