Human topic cleanup
tgstation/TerraGov-Marine-Corps pull request #12706
Opened 2023-04-12 19:40 UTC by ivanmixo

## About The Pull Request

Whole bunch of 8 year old indent hell and single letter non descriptive vars. Replaced with early returns and better vars.

Yes, this is mostly outdated code for MP and stuff. Suffer.

## Why It's Good For The Game

Cleaner code is better.

## Changelog

:cl:
refactor: Cleaned up the human topic proc
/:cl:

2023-04-13 16:09 UTC, QualityVan commented on code/modules/mob/living/carbon/human/human.dm
> +		if(usr.incapacitated() || !get_dist(usr, src) <= 7 || !hasHUD(usr,"squadleader"))
dist <= 7 needs parens or the ! will evaluate first
or just flip to > i guess

2023-04-13 16:09 UTC, QualityVan commented on code/modules/mob/living/carbon/human/human.dm
> +		if(!newfireteam || H.incapacitated() || !get_dist(H, src) <= 7) //We might've moved away or gotten incapacitated in the meantime
same here

2023-04-14 01:44 UTC, Lumipharon requested changes
Jesus christ, this file lol.

2023-04-14 01:44 UTC, Lumipharon commented on code/modules/mob/living/carbon/human/human.dm
> +			if(istype(wear_id, /obj/item/card/id/dogtag))
Can just make these one line.

2023-04-14 01:44 UTC, Lumipharon commented on code/modules/mob/living/carbon/human/human.dm
> +				if(!DT.dogtag_taken)
early return?

2023-04-14 01:44 UTC, Lumipharon commented on code/modules/mob/living/carbon/human/human.dm
> +			var/obj/item/what = get_item_by_slot(slot)
I know this was already here, but lmao var name

2023-04-15 09:27 UTC, Lumipharon approved these changes
Probs fine but going to TM in case there's any oversights.

2023-04-16 23:51 UTC, merged