Makes transfusion less annoying to use
tgstation/TerraGov-Marine-Corps pull request #12730
Opened 2023-04-15 19:45 UTC by RikuTheKiller

## About The Pull Request

This PR makes transfusion not cancel if the target moves and cancel if the target takes damage. It does not get cancelled if the target takes damage while in critical, though being knocked into critical still counts as a cancel. (Since this ability often comes in handy for saving crit xenos while tanking for them.)

On a more technical note, I've also split IGNORE_LOC_CHANGE into IGNORE_TARGET_LOC_CHANGE and IGNORE_USER_LOC_CHANGE and turned IGNORE_LOC_CHANGE into a combination of the two. This shouldn't have any effects in-game.

## Why It's Good For The Game

Okay, so transfusion is a great ability and all, but it's just really frustrating to use. Why? Because xenos don't stay still. Like, at all. When they're building, they move 1 tile exactly when your ability is about to finish. Even when you'd think they'd be idle, they keep moving anyways since it seems to be engrained in every xeno player's brain that standing still is equal to death.

Now, you may say "just tell them to stop moving" and to that I say "getting them to listen takes 5 times longer than the ability itself, not to mention constantly asking people to stop moving is obnoxious" which is why I made this PR.

The change to make it cancel when the target takes damage is so that it isn't a straight up buff to transfusion, which really isn't needed at the moment, it's already a strong ability that is owned by a strong caste.

This PR also solidifies transfusion as an ability to be used outside of combat, which it already sort of is since the only xeno that I can think of that stays still for long enough while being shot is a fortified defender.

## Changelog

:cl:
balance: Gorger's transfusion ability is no longer cancelled by the target moving. In exchange, it's cancelled if the target takes damage.
/:cl:

2023-04-15 19:46 UTC, RikuTheKiller commented
Also this was tested in-game with jimmyl and most, if not all edge cases have been taken care of.

2023-04-15 20:28 UTC, mc-oofert commented
> Also this was tested in-game with jimmyl and most, if not all edge cases have been taken care of.

me

2023-04-15 23:08 UTC, Arctrooper8 commented
Gorger enthusiasts rejoice!

2023-04-20 00:27 UTC, Lumipharon requested changes

2023-04-20 00:27 UTC, Lumipharon commented on code/modules/mob/living/carbon/xenomorph/castes/gorger/abilities_gorger.dm
> +	var/target_health //Used to keep track of the target's previous health for extra_health_check()
autodoc

2023-04-20 00:27 UTC, Lumipharon commented on code/modules/mob/living/carbon/xenomorph/castes/gorger/abilities_gorger.dm
> +/datum/action/xeno_action/activable/transfusion/proc/extra_health_check(mob/living/target)
autodoc

2023-04-21 02:59 UTC, Lumipharon approved these changes

2023-04-21 04:29 UTC, Lumipharon requested changes

2023-04-21 04:29 UTC, Lumipharon commented on code/__DEFINES/mobs.dm
> +#define IGNORE_LOC_CHANGE IGNORE_USER_LOC_CHANGE | IGNORE_TARGET_LOC_CHANGE
```suggestion
#define IGNORE_LOC_CHANGE (IGNORE_USER_LOC_CHANGE|IGNORE_TARGET_LOC_CHANGE)
```
honk. This break uh, a lot of stuff.

2023-04-21 04:56 UTC, Lumipharon approved these changes

2023-04-23 22:39 UTC, merged