Impact Particle Effects
tgstation/TerraGov-Marine-Corps pull request #12752
Opened 2023-04-19 08:54 UTC by tyeagg

## About The Pull Request
bullet impacts now use particles also adds bloom filter to filteriffic

https://user-images.githubusercontent.com/98577688/233021143-7745377b-2dbc-4a1f-b587-81a4cbc1d4cf.mp4

## Why It's Good For The Game
looks cool also may fix the whole bullet ping getting stuck

## Changelog

:cl:
add: particle effects for bullet impacts
imageadd: debris for bullet impacts
code: variables to determine what debris an object spews out when its impacted by a projectile
/:cl:

2023-04-19 22:00 UTC, Al-1ce commented
pretty !

2023-04-20 17:04 UTC, XElectricX commented
Holy hell bless with another Tyeagg particle PR. Speed merge. Probably much better for performance too and stops the weird bug of impact effects not qdel-ing themselves.

2023-04-25 17:36 UTC, TiviPlus requested changes
rest ltgm

2023-04-25 17:36 UTC, TiviPlus commented on code/game/atoms.dm
> +	var/debris_bloom = FALSE
Gross here is
A) Atom vars, could this be an element or something instead
B) FALSE/string mixing
C) string should be defines

2023-04-25 17:36 UTC, TiviPlus commented on code/modules/projectiles/projectile.dm
> +			QDEL_NULL(debris_visuals)
hit == src?
also wont timers not run on qdeleted objects anyway

2023-04-25 17:36 UTC, TiviPlus commented on code/game/objects/effects/temporary_visuals/miscellaneous.dm
> +	alpha = 175
new vars above new definitions

2023-05-02 07:37 UTC, TiviPlus approved these changes

2023-05-02 07:37 UTC, TiviPlus commented on code/datums/elements/debris.dm
> +/datum/element/debris/proc/on_impact(datum/source, obj/projectile/P)
Autodocs

2023-05-02 22:49 UTC, Lumipharon commented
Particle effects are definitely the future, but during the current TM these are way over the top to the point of being distracting. A group of marines shooting in the direction of a wall creates a giant continuous fountain of debris exploding out.

2023-05-03 13:38 UTC, FosterGrime-Heymynameslouie commented
> Particle effects are definitely the future, but during the current TM these are way over the top to the point of being distracting. A group of marines shooting in the direction of a wall creates a giant continuous fountain of debris exploding out.

sounds pretty cool to look at honestly

2023-05-04 19:01 UTC, pilotmans commented
This is beautiful, this is just quality.

2023-05-07 07:49 UTC, merged