Woe And Suffering/Atomization - Ports some tgstation controller code
tgstation/TerraGov-Marine-Corps pull request #12768
Opened 2023-04-21 17:53 UTC by mc-oofert

## About The Pull Request

**TESTMERGE FIRST YA FUCKWADS**

holy shit how much i hate this
anyway atomized pr 
renames flags_atom to flags_1 and initialized_1
The following controllers were replaced with tgstation ones with alterations to work with TGMC: Admin, Failsafe, Master, Globals
Most if not all subsystems have been changed to support the new code
200+ files are simply from the flags_1 change

holy shit is there a lot to link

## Why It's Good For The Game

new code good + atomized pr + pilltadpole needs this to work + ratio 

## Changelog
should be none but there may so testmerge

2023-04-21 18:12 UTC, ivanmixo commented on code/__DEFINES/MC.dm
> +/datum/controller/subsystem/fluids/##X
We have a fluids subsystem?

2023-04-21 18:12 UTC, ivanmixo commented on code/__DEFINES/subsystems.dm
> +#define DB_MAJOR_VERSION 5
This needs to be matched up with current db

2023-04-21 18:12 UTC, ivanmixo commented on code/__DEFINES/MC.dm
> +#define MOVEMENT_SUBSYSTEM_DEF(X) GLOBAL_REAL(SS##X, /datum/controller/subsystem/movement/##X);\
We have a movement subsystem?

2023-04-21 18:12 UTC, ivanmixo commented on code/__DEFINES/subsystems.dm
> +#define WARDROBE_CALLBACK_REMOVE 2
I don't think we have a wardrobe SS so these are just pointless.

2023-04-21 18:12 UTC, ivanmixo commented on code/__DEFINES/subsystems.dm
> +#define SSFLUIDS_DT (SSplumbing.wait/10)
Again fluid subsystem.

2023-04-21 18:12 UTC, ivanmixo commented on code/__DEFINES/subsystems.dm
> +#define SSAIR_REBUILD_QUEUE 2
We don't have atmos , make sure we actually need these

2023-04-24 08:26 UTC, TiviPlus requested changes
This is unreviewable you need to split these and link prs if you are porting

2023-04-24 08:53 UTC, mc-oofert commented
> This is unreviewable you need to split these and link prs if you are porting

skill issue

2023-05-07 00:43 UTC, closed without merging