Quickbuild no longer triggers on left click
tgstation/TerraGov-Marine-Corps pull request #12770
Opened 2023-04-21 20:46 UTC by RikuTheKiller

## About The Pull Request

This is a bugfix, building isn't meant to trigger on left click.

## Why It's Good For The Game

Not randomly placing a wall while destroying stuff is rather neat for sanity's sake.

## Changelog

:cl:
fix: Quickbuild no longer triggers on left click.
/:cl:

2023-04-22 07:06 UTC, Lumipharon approved these changes

2023-04-22 14:17 UTC, TiviPlus requested changes

2023-04-22 14:17 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/abilities.dm
> +	if(toggled && !modifiers["left"])
```suggestion
	if(toggled && !modifiers[BUTTON] == LEFT_CLICK)
```

2023-04-23 02:34 UTC, MLGTASTICa commented
This will affect the Xeno Meta

2023-04-28 19:22 UTC, merged