AI notification update
tgstation/TerraGov-Marine-Corps pull request #12834
Opened 2023-04-26 17:13 UTC by RipGrayson

## About The Pull Request

This PR creates a stripped down notify_ghost system for the AI. The AI can click the notifications to go to the triggering event.

Additionally, I have integrated the system with the OB system. 
Instead of scrabbling to find an appropriate overwatch console and running through the buttons (by which point the OB laser has probably gone out) the AI has a notification (and new sound) for OB lasers and can press the button to fire the OB automatically. 

Right now the AI receives a notification for the following events;

When the Alamo is locked by xeno activity
When the tadpole is destroyed
When a disk is generated
When the nuke is activated
When a CAS laser is activated
When a OB targeting laser is activated

The system is easily added to, and it can be expanded upon as needed. With the exception of the OB laser, clicking any of the alerts will take you to the site of the event.

## Why It's Good For The Game

For what is theoretically the embodiment of the ship's intelligence the AI really doesn't have that much info about operations. It can't tell when much of anything happens, aside from basic statistics. With this PR the AI should be able to stay better informed about the state of the operation, and act as auxiliary command as needed.

Also the AI is frequently called on to fire OBs, currently the system is awful. The AI has to find the main overwatch console, scroll down, find the person lasing, select them, and press fire. By the time the AI completes this task, 90% of the time the person lasing has been either killed or had to move, usually earning a chewing out by whatever command was expecting the OB to happen. 

With the new system the AI merely has to press the alert and confirm they want to fire the OB at a target laser, no hassle needed.

## Changelog

:cl:
qol: The AI now receives alerts about important events.
qol: The AI can now press an alert to fire an OB instead of operating the overwatch console.
code: Created a modified version of the ghost notification system for AI use.
/:cl:

2023-05-02 18:21 UTC, BraveMole requested changes
The ob solution cannot pass, you probably want to cut it so the rest can be merged.

2023-05-02 18:21 UTC, BraveMole commented on code/game/objects/effects/overlays.dm
> +		if("railgun")
Should be defines

2023-05-02 18:21 UTC, BraveMole commented on code/modules/mob/living/silicon/ai/ai_notifications.dm
> +	if(!A)
please, full variable name

2023-05-02 18:21 UTC, BraveMole commented on code/modules/mob/living/silicon/ai/ai_notifications.dm
> +/mob/living/silicon/ai/proc/receive_laser_cas(datum/source, obj/effect/overlay/temp/laser_target/cas/incoming_laser)
autodoc on everything

2023-05-03 15:15 UTC, RipGrayson commented on code/_onclick/hud/ai.dm
> +	var/atom/target = null
In this case, /mob/living/silicon/ai/proc/notify_ai sets the target for /atom/movable/screen/alert/ai_notify when called

2023-05-23 03:58 UTC, Lumipharon approved these changes

2023-05-27 08:45 UTC, merged