Makes the SD interface streamlined and adds timer to detonation
tgstation/TerraGov-Marine-Corps pull request #12888
Opened 2023-05-03 03:07 UTC by JackTheJackhammer

## About The Pull Request

This pull request does 2 things:
1. it makes the SD interface more 'modern' and inline with most other interfaces in the game (see: shuttle interface)
2. adds a timer that displays time to detonation and a percentage bar

see:
![2](https://user-images.githubusercontent.com/77555989/235825855-464e5d7c-4ac8-4616-9327-82aef80af585.PNG)
![1](https://user-images.githubusercontent.com/77555989/235825857-b2837c36-913e-4989-8f06-036f6fcc851a.PNG)

## Why It's Good For The Game

People aught to have a easier way to see how much time is left on the SD. 
Muhrene not built for math, muhrene built for unga.

also it looks better

## Changelog

:cl:
qol: Reconfigured SD interface
add: Adds an indicator for how long the SD has left to activate.

/:cl:

2023-05-03 03:12 UTC, JackTheJackhammer commented
1 check fail, gonna do in morning

2023-05-04 22:06 UTC, TiviPlus requested changes
rest lgtm

2023-05-04 22:06 UTC, TiviPlus commented on code/game/objects/machinery/self_destruct.dm
> +	var/list/temps = list()
hi unused vars

2023-05-05 03:49 UTC, JackTheJackhammer commented on code/game/objects/machinery/self_destruct.dm
> +	var/list/temps = list()
damned

2023-05-06 19:15 UTC, merged