Plasma guns
tgstation/TerraGov-Marine-Corps pull request #12946
Opened 2023-05-11 15:03 UTC by TiviPlus

## About The Pull Request
Added six new plasma guns: [Plasma pistol, Plasma rifle, Plasma carbine, Plasma minigun, Plasma cannon, Plasma sniper]
They have their own firemodes and have overheat mechanics

## Changelog
:cl:
add: Added the plasma series of weapons
/:cl:

2023-05-11 15:35 UTC, FosterGrime-Heymynameslouie commented
THE PLASMA MACHINE GUN IS HERE

2023-05-11 20:57 UTC, Mrrpip commented
To save our mother earth from any alien attack!

2023-05-12 05:30 UTC, Naaanii commented
Where niche?

2023-05-12 23:40 UTC, 1kajowsmol commented
> Where niche?

joe niche

2023-05-27 17:06 UTC, Kuro020 approved these changes

2023-05-27 17:09 UTC, DeltaFire15 commented
"code/modules/projectiles/gun_system.dm:		overheat_timer = addtimer(CALLBACK(src, .proc/complete_overheat, overheat_smoke), overheat_time, TIMER_STOPPABLE)
ERROR: Outdated proc reference use detected in code, please use proc reference helpers.
"

2023-05-27 23:15 UTC, Lumipharon commented
Overheat seems wack.

Many firemodes will not overheat even if you m1 the entire mag. Other modes like the basic rifle overheat super fast. And again, I don't see how anything stops marines just juggling two plasma guns to bypass overheat.

Trifire is bugged, it fires all projectiles from the firer.

2023-05-27 23:15 UTC, imsxz commented
bouncy goes thru shooter

2023-05-27 23:47 UTC, 1kajowsmol commented
currently seems like overheat does basically nothing and also the shotgun mode on the carbine is op as fuck and breaks reinforced walls in like 4 mags, idk about actual damage.

2023-05-28 00:00 UTC, Kuro020 commented
standard rifle firemode is using the wrong projectile sprite

2023-05-28 00:00 UTC, imsxz commented
carbine shotgun burst crits xenos and kills them in under 0.5s from full HP. base damage seems insanely high regardless of bugged burst.

short and neat descriptions that accurately described each of the firing modes would be nice when i examine a gun. dont like the wall of lore personally when im trying to figure out what it does.

2023-05-28 00:01 UTC, imsxz commented
the plasma thrower and plasma cannon among other things have  icons that are way too big for your inventory

2023-05-28 00:14 UTC, Kuro020 commented
the plasma sniper scope doesnt actually do anything, gotta make it a permanent attachment

2023-05-28 00:18 UTC, Kuro020 commented
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/52428261/92b8df26-5418-423c-be91-2472c6817b8e)

2023-06-17 22:58 UTC, Lumipharon commented
@TiviPlus you probs don't need the flags on every guin if they're the same lol

2023-06-17 23:21 UTC, Lumipharon requested changes

2023-06-17 23:21 UTC, Lumipharon commented on code/modules/projectiles/gun_system.dm
> +	heat_meter.animate_change(heat_amount/100, 5)
this is spamming runtimes with deployed sentries for some reason.

2023-06-18 06:21 UTC, Lumipharon commented on code/modules/projectiles/gun_system.dm
> +	heat_meter.animate_change(heat_amount/100, 5)
Oh it breaks sentries entirely, apparently

2023-06-27 11:24 UTC, XSlayer300 commented on code/modules/codex/entries/guns_codex.dm
> +/datum/codex_entry/plasma_weapons
what is this point of adding a codex entry if you haven't listed them yet in the generic plasma weapon code?

2023-06-27 12:04 UTC, XSlayer300 commented on code/modules/projectiles/guns/plasma.dm
> +	fire_mode = GUN_FIREMODE_AUTOMATIC
```suggestion
	fire_mode = GUN_FIREMODE_AUTOMATIC
```
>tri-fire
>fully-automatic

2023-06-27 12:05 UTC, XSlayer300 commented on code/modules/projectiles/guns/plasma.dm
> +	fire_mode = GUN_FIREMODE_AUTOBURST
inverted from tri-fire.

2023-06-27 12:07 UTC, XSlayer300 commented on code/modules/projectiles/guns/plasma.dm
> +		"Tri-fire" = /datum/lasrifle/base/plasma_rifle_mode/pistol_trifire,
```suggestion
		"Tri-fire" = /datum/lasrifle/base/plasma_rifle_mode/pistol_trifire,
```
Name it bouncy mode or something, it's not even three round burst.

2023-06-27 12:09 UTC, XSlayer300 commented on code/modules/projectiles/guns/plasma.dm
> +	icon_state = "plasma_cannon"
No icon exists.

2023-06-27 12:40 UTC, FosterGrime-Heymynameslouie commented
will there be an ammo box specific for it like the t60 ammo box and t12 ?

2023-06-27 13:17 UTC, FosterGrime-Heymynameslouie commented
the scope for the marksman rifle dosent seem to work

also the plasma rifle when being vended out and placing a new mag shows 83 ammo but when changing fire modes to the other 2 will show 53 instead and the overcharge mechanic wont work anymore

2023-06-27 13:56 UTC, ivanmixo commented
https://github.com/tgstation/TerraGov-Marine-Corps/assets/22431091/abac9aee-de11-425e-ac7c-d561acde4b06

Please reconsider the whole heavy mode on the cannon, this is not okay.

2023-06-27 14:37 UTC, AusarAtkin commented
Plasma Pistol on standard mode kill Primo King and Queen in one mag, it shoot as fast as you can click, and kill most primo t3 and t2 in half a mag, and it wont ever overheat magdumping the whole mag.

2023-06-27 14:58 UTC, Kuro020 commented
Plasma cannon fire rate is probably on byond tick instead of seconds, should fix that, also give all the guns (aside from the pistol) the two handed required to fire flag

2023-06-27 16:54 UTC, carbous commented
So my feedback on those guns, I  didn't try the pistol, canon and flamer yet. The rifle is quite decent, it seems to do what it was meant to, good sunder, decent damages but not too much and the marksman mode is funny. The sniper was quite bad, good sunder but overral less than the other plasma rifle simply because it's could get hard to get a hit in (still better than the laser sniper). The carbine was' damages were alright, not too much, however I think it's ammo size might be a bit too big. I also worry about the sunder dealt, coupled with it's high firerate, it might be a bit too much.

2023-06-29 01:29 UTC, XSlayer300 commented on code/modules/projectiles/guns/plasma.dm
> +	desc = "The PL-73 Plasma Thrower is a high-quality weapon designed to deliver powerful performance in even the most challenging combat situations. With its sleek, durable design and intuitive contro
```suggestion
	desc = "A heavy duty minigun-like plasma-discharging weapon, for those who want to go all out in a superheated siege. Comes with multiple charge settings that either rapid fire plasma bolts, discharge plasma energy into flames, or deliver a massive plasma ball which deals heavy damage. Kongjian's sleek PL series of plasma-discharging weapons acts as a competitor to TE series of laser weapons used by the TGMC, allowing flexibility even in the most stressful combat situations, though the usage of highest quality materials and specifications made large-scale use and procurement all but impossible. Uses proprietary WML plasma batteries, and overheats when used too much, depending on setting."
```

2023-06-29 01:29 UTC, XSlayer300 commented on code/modules/projectiles/guns/plasma.dm
> +	desc = "Introducing the PL-02 Plasma Sniper Rifle, the ultimate long-range weapon for those who demand nothing but the best. With its advanced features and sleek design, the PL-02 is the perfect add
```suggestion
	desc = "Kongjian's answer to the marksman question, the PL-02 isn't as flexible compared to the other TGMC plasma weapons, but it is just as fierce and incredibly accurate as the most weapons in the arsenal. Kongjian's sleek PL series of plasma-discharging weapons acts as a competitor to TE series of laser weapons used by the TGMC, allowing flexibility even in the most stressful combat situations, though the usage of highest quality materials and specifications made large-scale use and procurement all but impossible. Uses proprietary WML plasma batteries, and overheats when used too much, depending on setting."
```

2023-06-29 01:29 UTC, XSlayer300 commented on code/modules/projectiles/guns/plasma.dm
> +	desc = "Introducing the PL-38 Plasma Rifle, a versatile weapon for any combat situation. With its sleek design and advanced features, the PL-38 is the perfect addition to any soldier's arsenal. This
```suggestion
	desc = "The versatile jack-of-all-trades standard plasma rifle, with a fully automatic charge setting as well as a stronger, 'marksman' mode for the accurate role. Kongjian's sleek PL series of plasma-discharging weapons acts as a competitor to TE series of laser weapons used by the TGMC, allowing flexibility even in the most stressful combat situations, though the usage of highest quality materials and specifications made large-scale use and procurement all but impossible. Uses proprietary WML plasma batteries, and overheats when used too much, depending on setting."
```

2023-06-29 01:29 UTC, XSlayer300 commented on code/modules/projectiles/guns/plasma.dm
> +	desc = "Introducing the PL-51 Plasma Carbine, a compact and lightweight weapon designed for close to mid-range combat. With its sleek design and advanced features, the PL-51 is the perfect addition
```suggestion
	desc = "The lightweight plasma weapon for adaptive ranged combat. Coming with a shotgun and a burst 'tri-fire' setting for close and long engagements, in addition to the standard fully-automatic mode. Kongjian's sleek PL series of plasma-discharging weapons acts as a competitor to TE series of laser weapons used by the TGMC, allowing flexibility even in the most stressful combat situations, though the usage of highest quality materials and specifications made large-scale use and procurement all but impossible. Uses proprietary WML plasma batteries, and overheats when used too much, depending on setting."
```

2023-06-29 01:29 UTC, XSlayer300 commented on code/modules/projectiles/guns/plasma.dm
> +	desc = "Introducing the PL-85 Plasma Pistol, a sleek and reliable weapon for any combat situation. With its compact design and advanced features, the PL-85 is the perfect sidearm for any soldier. Th
```suggestion
	desc = "A highly compact pistol by energy weapon standards, the PL-85 was designed to last in desolated environments as an emergency service sidearm for non-combative personnel. Features a semi-auto, full-auto and a 'bouncy' mode setting. Kongjian's sleek PL series of plasma-discharging weapons acts as a competitor to TE series of laser weapons used by the TGMC, allowing flexibility even in the most stressful combat situations, though the usage of highest quality materials and specifications made large-scale use and procurement all but impossible. Uses proprietary WML plasma batteries, and overheats when used too much, depending on setting."
```

2023-06-29 01:32 UTC, XSlayer300 commented
screw you

_un GPTs your GPT description_

2023-07-02 14:40 UTC, XSlayer300 commented
also, *cough cough*

![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/35091844/b5bc44f6-9378-4153-b6ab-cc326e41b2df)

2023-07-02 18:39 UTC, ivanmixo commented
> i don't approve this if you don't add it to the pool of eord weapon spawns

I don't approve you using dreammaker :hampter:

2023-07-04 09:14 UTC, Lumipharon commented
Fixed a couple of bugs, and loaded a pile of basic walance tweaks, mainly for stats that were missing/wack/not in the right place.
They'll still need testing and tweaking, but this should give it a more sane baseline.

2023-07-04 17:33 UTC, blackdav123 commented
overheats are really hard to reach and magdumping with most guns wont even overheat
in the rare case you are dumping two mags the overheat only lasts for a second which barely slows down the firerate at all
on the cannon in particular the overheat is almost as long as the firedelay so there is nearly no interference from the overheat
some guns like the carbine on shotgun and pistol on standard deal ridiculous amounts of damage, with a single mag from the pistol able to kill a primo king 

for these guns to be anywhere near balanced the overheat mechanic needs to be much more punishing than a single second of shooting lost

2023-07-04 17:39 UTC, blackdav123 commented
also the pistols are fake sidearms and dont fit into pistol holsters, and they can take pistol lace as well as mag harness.

2023-07-04 17:51 UTC, ivanmixo requested changes
The plasma pistol is all kinds of fucked. Has 83 shots when first vended and seems to fire standard mode rounds while being full auto. It can also take attachies it shouldn't apparently.

Need to also reconsider if they should all be onehanded. And look over what attachies they can take.

2023-07-04 22:05 UTC, Lumipharon commented
Unfugged pistol issues and some carbine issues. The 2 big guns can no longer be one handed.

2023-07-05 00:51 UTC, XSlayer300 commented
Holster sprite isn't here.

2023-07-05 01:24 UTC, Aporhtonoma commented
shotgun machinegun is strong as all hell massive spread with massive mag and massive firerate bad
minigun can and WILL set the entire screen on fire in less than a second with a bullet to spare bad
minigun has incidiary ammo... with decent damage... bad
the sniper , rifle i dint try or dint go against that much so i dont have an oppinion on but they actually seem ok
the overheat mechanic is non existant basically.It might have come into play once when i was spamming globs with the minigun.Make it more punishing or easier to proc please.

2023-07-05 05:00 UTC, FosterGrime-Heymynameslouie commented
the description should probably be moved to the lore information section when looking for relevant information instead of being in the description, because its a rather long description that dosent really explain what the firemodes do, and also the firemode description on the relevant information panel has nothign

2023-07-05 16:47 UTC, imsxz commented
Hop on and play xeno against these mister coder. Carbine tri-shot and whichever one makes the big glob of fire are stupid strong. Other ones have insane damage too but those 2 are the most unreasonable.

2023-07-05 16:49 UTC, imsxz commented
also i played a couple rounds as marine and never triggered/noticed overheat while magdumping. Have to try very hard to force overheat to trigger. Basically a fake mechanic

2023-07-05 19:41 UTC, ivanmixo requested changes
Reconsider tri fire mode damage/fire rate. Also the falloff and letting guns that can be one handed having tri fire in general.

2023-07-05 19:44 UTC, Texicos commented
Carbine needs the can't fire unwielded flag

2023-07-23 07:41 UTC, Lumipharon commented
was this good to TM again? I don't know what was happening with people updating the walance

2023-07-28 17:47 UTC, TiviPlus commented
Apparently they did it

2023-07-31 20:22 UTC, TiviPlus commented
i broke some sprites though

2023-08-25 06:57 UTC, Texicos commented
when merge

2023-09-09 22:16 UTC, Pariah919 commented
someone said appreantly them being broken is my fault but i had nothing to do with this beyond yelling random 2 sentence ideas at blase

2023-09-09 23:05 UTC, FosterGrime-Heymynameslouie commented
6 months in the making

6th times the charm

2023-09-11 04:01 UTC, Joe13413 commented
gotta love how descriptive this PR is
"adds plasma guns, they have uhhh overheat and unique fire modes" yeah bro can you tell me whats up with these new weapons?

2023-09-11 07:47 UTC, Victor239 commented
These guns were pretty insane in the test merge this weekend to the point most marines were saying "this is busted OP" and xenos "this is beyond unfun". Lore text says "Plasma weapons are rare and powerful" so this shouldn't be in the vendor for starters, maybe give them to a very rare ERT.

2023-09-19 12:53 UTC, XSlayer300 commented on code/modules/projectiles/guns/plasma.dm
> +	name = "\improper PL-73 plasma thrower"
```suggestion
	name = "\improper PL-73 plasma thrower"
```

You know, eventually we'll have to change it to TL or TX or something.

2023-10-05 16:50 UTC, Tristan63 commented
the emprah protects

2023-10-14 16:27 UTC, ButterChugger commented
I want to believe

2023-10-28 14:16 UTC, Kuro020 commented
I still believe

2023-11-08 18:28 UTC, Kuro020 commented
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/52428261/561f248d-528e-4e2a-80f3-d53147f508ca)

2023-11-12 00:40 UTC, closed without merging

2023-11-12 00:41 UTC, David-Stormwell commented
Krill issue