Stops the Weight Bench from being deleted when select wheel is closed
tgstation/TerraGov-Marine-Corps pull request #12967
Opened 2023-05-13 02:08 UTC by JackTheJackhammer

## About The Pull Request

Makes it so that the Weight Bench no longer gets banished to the shadowrealm if you dont wish to change the weights.

## Why It's Good For The Game

The TGMC can now stop having to buy a new weight bench everytime someone changes their mind and banishes the Weight bench

## Changelog
:cl:

fix: Weight Benches no longer disappear when unselecting the radial wheel.

/:cl:

2023-05-13 06:46 UTC, Lumipharon requested changes

2023-05-13 06:46 UTC, Lumipharon commented on code/game/objects/structures/benchpress.dm
> +		return
shouldn't this be before plates is set?

2023-05-13 18:48 UTC, JackTheJackhammer commented on code/game/objects/structures/benchpress.dm
> +		return
oh wait yeah you have a point

2023-05-14 05:26 UTC, Lumipharon commented on code/game/objects/structures/benchpress.dm
> +		return
@JackTheJackhammer it hasn't changed?

2023-05-15 23:28 UTC, Lumipharon commented
it didn't change my man.

2023-05-17 10:05 UTC, Lumipharon approved these changes

2023-05-17 10:05 UTC, merged