Fixes nades erroniously appearing primed when they aren't
tgstation/TerraGov-Marine-Corps pull request #12982
Opened 2023-05-14 22:35 UTC by ivanmixo

## About The Pull Request

Yes. Tested by putting a nade into a GL and taking it out, usually this makes it appear like it's about to go off (with the flashing !)

## Why It's Good For The Game

Bug bad.

## Changelog

:cl:
fix: Fixed nades erroniously appearing primed when they aren't
/:cl:

2023-05-14 22:47 UTC, Lumipharon commented
the ! is specifically for dangerous nades, not all nades, afaik, so it check for both dangerous and active.

2023-05-14 23:59 UTC, Lumipharon approved these changes

2023-05-15 00:00 UTC, Lumipharon commented on code/game/objects/items/explosives/grenades/grenade.dm
>  		overlays += new /obj/effect/overlay/danger
Oh, this is also wrong, although I know its old code. update overlays should just return a list of overlays it should currently have. So:
. += new /obj/effect/overlay/danger

2023-05-15 00:00 UTC, Lumipharon requested changes
comment

2023-05-15 23:21 UTC, Lumipharon approved these changes

2023-05-15 23:21 UTC, merged

2023-05-16 17:45 UTC, Derrick2Electricboogaloo commented
Finally!