Puts important FC sword/tablet/etc. in vendor. Removes it from human FC.
tgstation/TerraGov-Marine-Corps pull request #12993
Opened 2023-05-16 19:33 UTC by Mrrpip

## About The Pull Request

OK, don't panic, the title is a bit eh. Writing ain't my strong suit, in a nutshell, removes the .45, sword, tablet and pouch from the human FC. But places it in their gear vendor as a set they can take. This set is never mutually exclusive with any other, so you'll always be able to take it.

![image (2)](https://github.com/tgstation/TerraGov-Marine-Corps/assets/38842059/91feedd0-02b7-4b76-9b58-f959c5a48c59)

Now, in terms of practicality: This allows both humans and robots to get the cool stuff, without me having to figure out how to properly code.

Additionally, adds the robot essential/armor kits to the clothing vendor.

![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/38842059/200a8693-a741-43db-93d9-0a16fb671dce)

![image (1)](https://github.com/tgstation/TerraGov-Marine-Corps/assets/38842059/6b1cffe0-b941-4317-a08d-fbaa2e3bf2a4)

On the backend side of things, moves the FC clothes vendor's inventory into the same file as the rest

## Why It's Good For The Game

Well, uh....I mean, The sword and gun are not important. The tac-binos, tablet and what not, probably are. So uh...Here you go, I guess?

## Changelog

:cl:
qol: Robots can now access the human FC's gear trough the FC gear vendor. Now you can be swashbuckling captain robbit or something. I dunno.
/:cl:

2023-05-16 21:34 UTC, Lumipharon requested changes
Just make robot outfits yo.

2023-05-16 21:35 UTC, Mrrpip commented
> Just make robot outfits yo.

If I knew how, I would....Er...Yo.

But I don't. Because I don't code often.

2023-05-16 23:56 UTC, Mrrpip commented
Alright. After some discussions, Lumi has a plan.

...One that I'm not exactly capable of coding, plan is to close this, Lumi does that. Hopefully they have better luck.

2023-05-17 00:00 UTC, closed without merging

2023-05-17 17:12 UTC, Aroliacue commented
As one of maybe three Combat Robot FCs, I approve of this epic P- Oh it's closed, L