Text to speech
tgstation/TerraGov-Marine-Corps pull request #13004
Opened 2023-05-17 22:10 UTC by TiviPlus

## About The Pull Request

https://github.com/tgstation/tgstation/pull/74775/files
https://github.com/tgstation/tgstation/pull/75501

60 ish voiceds to choose from robots should sound like robots, pref toggle
Will need me to get config from mso

## Why It's Good For The Game
Its not >:)

## Changelog

:cl:
add: Added text so speech
/:cl:

2023-05-17 22:35 UTC, Three333Digit commented
IT'S HERE!!!!!!!!

2023-05-17 23:09 UTC, novaepee commented
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/6610922/4e4eddef-bd0e-4453-aab9-e9ddea31c76a)

2023-05-17 23:10 UTC, novaepee commented
![the-voices-voices-in-my-head](https://github.com/tgstation/TerraGov-Marine-Corps/assets/6610922/834f57da-2590-4796-a24c-258685d4b0e7)

2023-05-17 23:13 UTC, zzurge commented
Give me the plant

2023-05-18 00:23 UTC, Araulius commented
inb4 someone uses this to shout the gamer word.

2023-05-18 03:34 UTC, FosterGrime-Heymynameslouie commented
![clown-clowntoclown](https://github.com/tgstation/TerraGov-Marine-Corps/assets/59080633/43250070-3d7d-4b15-8f32-bd0c864f2baf)

2023-05-18 07:54 UTC, Aroliacue commented
FINALLY, OORAH

2023-05-19 16:38 UTC, novaepee commented
No TTS on xenomorphs and EORD humans. Need to check if ERT get TTS.

2023-05-19 23:07 UTC, Aporhtonoma commented
the single greatest addition that has ever been implemented in tgmc

2023-05-20 03:32 UTC, RipGrayson commented
This is quite possibly the funniest thing I've ever seen on TGMC 10/10

2023-05-20 05:46 UTC, BlueHNT commented
It causes immense delays.. Even if it's funny, that fun is costly.

2023-05-20 05:52 UTC, lKiseki commented
Ever since the addition of TTS as a test merge, there has been a sharp increase in game lag and time dilation. Although I like the fun related to the voices and the memes, I do not believe that the sheer amount of lag that this provides (and it is by no means a small amount) is worth it, especially in TGMC -- we have a fast-paced, relatively competitive environment, and this lag is really causing an impact.

I would at least like to see TTS held off until such time as more upgrades can be done to the server; the lag is far too great for me to personally consider this to be worth it.

2023-05-20 12:34 UTC, Watermelon914 commented
Text to speech isn't going to have any significant performance impact to the server.
The only performance impact that TTS might have is with client IO, which specifically means that if you have bad latency, your game might freeze up when receiving the TTS audio files but this only really happens to a small selection of players. You can fix this by turning TTS off for yourself in the preferences menu.

2023-05-21 05:28 UTC, ProfessorPopoff commented
Ladies, Gentlemen, anything in-between and off to the side...

This is it. 

It's over.

2023-05-21 05:51 UTC, Lumipharon requested changes
need an early return

2023-05-21 05:51 UTC, Lumipharon commented on code/modules/client/preferences_ui.dm
> +				INVOKE_ASYNC(SStts, TYPE_PROC_REF(/datum/controller/subsystem/tts, queue_tts_message), ui.user.client, "Hello, this is my voice.", speaker = choice, local = TRUE)
```suggestion
			if(!choice)
				return
			tts_voice = choice
			if(TIMER_COOLDOWN_CHECK(user, COOLDOWN_TRY_TTS))
				return
			TIMER_COOLDOWN_START(ui.user, COOLDOWN_TRY_TTS, 0.5 SECONDS)
			INVOKE_ASYNC(SStts, TYPE_PROC_REF(/datum/controller/subsystem/tts, queue_tts_message), ui.user.client, "Hello, this is my voice.", speaker = choice, local = TRUE)
```

2023-05-24 07:05 UTC, grinkgo commented
is there a less cringe way to preview all the voices

2023-05-24 10:20 UTC, CCorvet commented
Some voices should probably the removed, like the child voices
Also yeah, some different way to check how the voices sound would be neat.

2023-05-25 08:49 UTC, Lumipharon approved these changes
We have reached the peak. It's all downhill from here.

2023-05-25 08:50 UTC, merged