Vali flail
tgstation/TerraGov-Marine-Corps pull request #13128
Opened 2023-06-01 01:02 UTC by tanker4390

## About The Pull Request
A new melee weapon for use with the Vali system. This one has a reach of 3 for maximum range.
Deals 60 damage when wielded, with 1.5s attack delay.

![Screenshot 2023-05-30 230637](https://github.com/tgstation/TerraGov-Marine-Corps/assets/91577829/afac5e47-4ad1-4ec7-b519-1b0c451a4687)

![Screenshot 2023-05-30 230519](https://github.com/tgstation/TerraGov-Marine-Corps/assets/91577829/ab1f153c-404c-4f64-9019-be979f00300c)

![Screenshot 2023-05-30 230540](https://github.com/tgstation/TerraGov-Marine-Corps/assets/91577829/75ab96fd-6e21-43b9-8e59-e608dd003272)

## Why It's Good For The Game
More loadout choices and playstyles.

## Changelog

:cl: Tanker
add: Added the Harvester flail for use with the Vali system.
/:cl:

2023-06-01 01:07 UTC, Kuro020 requested changes
>vali flail
>is a vali sword on a cord

uhhhhhhhhhhhhhhhhhhhhhhhhhh, yeah this needs better sprites, if maints approve the idea I'll sprite something for it

2023-06-01 01:19 UTC, tanker4390 commented
> uhhhhhhhhhhhhhhhhhhhhhhhhhh, yeah this needs better sprites, if maints approve the idea I'll sprite something for it

Yeah sorry I was a bit lazy with the sprites, not to mention that I don't know where I was going sprite-wise with "harvester flail"

2023-06-01 01:53 UTC, Pariah919 commented
I feel like one day we'll just have a vali gun at this point.

2023-06-01 01:55 UTC, bowlofcereal commented
thats not a flail 💀 

https://en.wikipedia.org/wiki/Kusarigama

2023-06-01 02:44 UTC, Lumipharon commented
Not really a fan of 'vali spear +'

2023-06-01 02:51 UTC, blackdav123 commented
there are a lot more interesting ways you can make a weapon like this instead of just "vali with 3 range this time"

give it a sweeping attack like ravage or something

2023-06-01 02:58 UTC, tanker4390 commented
> [vali spear II, rework]

Okey, I'll see how I can rework it... maybe the other weapons can have their own special attacks, too? I'll see to it

2023-06-01 23:21 UTC, chizzy376 commented
Do we really need another longer tile reach vali weapon?

2023-06-02 17:29 UTC, theta891 commented
more vali weapons is based

a shame its not a vali claw or fist

2023-06-03 08:22 UTC, TiviPlus requested changes
Rest is whatever imo

2023-06-03 08:22 UTC, TiviPlus commented on code/game/objects/items/weapons/twohanded.dm
> +	var/obj/effect/abstract/particle_holder/particle_holder
autodoc

2023-06-03 08:22 UTC, TiviPlus commented on code/game/objects/items/weapons/twohanded.dm
> +/obj/item/weapon/twohanded/flail/proc/activate_particles(mob/living/user, direction)
autodoc

2023-06-03 08:54 UTC, ClosetedSkeletonGH commented
The amount of melee marines I've seen recently are ridiculous. The amount of melee tools there are is ridiculous. The more melee tools there are, the more melee marines there will be, the more marines will just throw. Getting stared at by 4 marines who dont bring a gun isnt fun and I feel like more vali weapons just encourage it.

2023-06-03 13:25 UTC, tanker4390 commented
> The amount of melee marines I've seen recently are ridiculous. The amount of melee tools there are is ridiculous. The more melee tools there are, the more melee marines there will be, the more marines will just throw. Getting stared at by 4 marines who dont bring a gun isnt fun and I feel like more vali weapons just encourage it.

The purpose of this PR isn't to "make more melee marines," simply to add more melee. The loadout is the marine's choice, and therefore their fault if it does not perform well.

2023-06-03 23:17 UTC, CCorvet commented
Maybe as a way to balance it, it could significantly less damage 1 tile distance, modestly less damage at 2 tile distance, and full at 3?

That way instead of just spear plus, it rewards spacing and still rewards xeno blood.

Also could instead of injecting chems like other vali weapons, it doing some snowflake interactions like that slow sweep, but maybe also root/pull xenos in closer? Reverse of powerfist.

For balance could also make it a 2 handed weapon to have any range, with one handed just being a vali knife with MAYBE extra armor peon. If so the damage penalties should only apply when wielded.

Get over here sound effect when this ability is used mandatory.

2023-06-04 05:10 UTC, zzurge commented
No scythe,i cri

2023-06-04 08:11 UTC, TiviPlus approved these changes
get kuro approval
sidenote I see a bunch of new created and modified sprites in icondiff dunno if thats intended

2023-06-06 16:55 UTC, theta891 commented
> The amount of melee marines I've seen recently are ridiculous. The amount of melee tools there are is ridiculous. The more melee tools there are, the more melee marines there will be, the more marines will just throw. Getting stared at by 4 marines who dont bring a gun isnt fun and I feel like more vali weapons just encourage it.

vali is easy to counter just stop being a dumbass 

so many xenos feed vali users endless blood thats not how you deal with them

grow a brain xeno main

2023-06-07 03:18 UTC, ClosetedSkeletonGH commented
> vali is easy to counter just stop being a dumbass

so many xenos feed vali users endless blood thats not how you deal with them

grow a brain xeno main

you have 0 reading comprehension. nowhere in this is it saying melee weapons are good. its me saying theyre overbloated and cause marines to throw, along with in general being a theme conflict and are unfun to go against (easy stomps cause bad players)

2023-06-09 02:14 UTC, theta891 commented
> you have 0 reading comprehension. nowhere in this is it saying melee weapons are good. its me saying theyre overbloated and cause marines to throw, along with in general being a theme conflict and are unfun to go against (easy stomps cause bad players) or have on your team

if you think more melee tools is causing marines to throw you dont understand why marines loose

2023-06-10 00:23 UTC, ivanmixo reviewed
You didn't put it in a vendor from what I can tell, probably not intended.

2023-06-12 03:47 UTC, cheapcents commented
> Yeah sorry I was a bit lazy with the sprites, not to mention that I don't know where I was going sprite-wise with "harvester flail"

You could've asked the guy who made the vali sprites to help you

2023-06-25 00:58 UTC, closed without merging