Marine light medical belt
tgstation/TerraGov-Marine-Corps pull request #13147
Opened 2023-06-03 06:35 UTC by tanker4390

## About The Pull Request
Light medical belt, available infinitely in clothing vendors. Can hold 15 slots of various medical items.

![216548462-38bdd814-f702-40fb-81dd-ea7a593d8691](https://github.com/tgstation/TerraGov-Marine-Corps/assets/91577829/7a45c89b-3e8a-40de-8475-72890e2428f4)

## Why It's Good For The Game
Gives marines the option to fumble around with more medical supplies. I thought the lack of a specialized medical belt among its pouch and other counterpart was odd.

## Changelog

:cl: Tanker
add: Added a lightweight medical belt for marines to use.

2023-06-03 06:53 UTC, Lumipharon commented
I swear we've had this PR before. Isn't this almost exactly the same as a medical rig?

2023-06-03 08:31 UTC, ClosetedSkeletonGH commented
dark medical belt rises

2023-06-03 08:57 UTC, Mrrpip commented
[        /obj/item/reagent_containers/hypospray/autoinjector,](https://github.com/tgstation/TerraGov-Marine-Corps/blob/acd84e5c4dde86c7155cd23d00355dcd4e72db62/code/game/objects/items/storage/belt.dm#L100)

Balance concerns and redundancies aside. I believe this is already covered by 

https://github.com/tgstation/TerraGov-Marine-Corps/blob/acd84e5c4dde86c7155cd23d00355dcd4e72db62/code/game/objects/items/storage/belt.dm#L103

2023-06-03 09:01 UTC, Mrrpip commented
As Github's weird with line pointing out, I believe it's the same with line 102 and 99. (Pill bottles and packets.)

2023-06-03 13:30 UTC, tanker4390 commented
> I swear we've had this PR before. Isn't this almost exactly the same as a medical rig?

Almost... It has less slots, and can't hold the same objects the med rig can.

2023-06-03 14:52 UTC, QualityVan requested changes

2023-06-03 14:52 UTC, QualityVan commented on code/game/objects/items/storage/belt.dm
> +		/obj/item/reagent_containers/dropper,
I'm not wild about this in the first place, but if you're designing expanded medical storage for standard marines to use it needs to be limited to things standard marines should be using: packets, autoinjectors, stacks, and not a whole lot else. Total space is on the high end, but in keeping with pouches.

2023-06-05 12:36 UTC, QualityVan commented
Please don't mark things as resolved on your own, it makes rereviewing more of a nuisance.

Waiting on kuro for sprites.

2023-06-05 22:37 UTC, Lumipharon commented
This is the equivilent of 10 mags worth of storage, this is super efficient storage for basic ungas. Not really a fan. If you want to go medic, go medic. This just lets a basic unga carry every med conceivable, although yes I know they can loot medical if they really want.

2023-06-06 01:59 UTC, yyzsong commented
Honestly, I think ten slots would be a better fit. Fifteen slots for meds is almost as good as a medical storage rig, and is even pretty decent compared to the lifesaver bag (which has 21 slots)



> This is the equivilent of 10 mags worth of storage

What does this mean

2023-06-06 02:32 UTC, Losenis commented
>Ammo belt is 2 ammo pouches + 1 slot, good
>Medical belt is 2 medical pouches + 1 slot, suddenly bad

I wish the average IQ being room temperature celsius only extended to within the game

2023-06-16 18:34 UTC, Kuro020 approved these changes

2023-06-17 02:02 UTC, QualityVan commented
As mentioned, this is a lot of storage, but belt slot is generally important and this is on par with being about the same as both pouch slots. It's entirely possible that both this and the PFC-available pouches should have their size tuned down, but I'm leaving that for future considerations right now.

2023-06-17 02:03 UTC, merged