adds outfits for robot shipside roles
tgstation/TerraGov-Marine-Corps pull request #13172
Opened 2023-06-06 11:18 UTC by coldironwarrior

## About The Pull Request

creates robot outfits for: chief medical officer, medical officer, medical researcher; staff officer; captain; and associated rebel roles

robots will now spawn with all their role-related pocket and belt goodies, as well as a default robotic armor mount

captain and staff officer robot outfits include light body armor and a helmet.

## Why It's Good For The Game

important and limited role-related gear should be available to players regardless of race they play

## Changelog

:cl:
fix: Combat robots spawning in roles that have roundstart gear will now have that gear equipped, along with a robotic armor mount
/:cl:

2023-06-06 11:33 UTC, Gregormack commented
Any screenshots? no?

2023-06-06 22:18 UTC, Ragecrabbo commented
As someone who made the mistake of picking CMO as my robot character and instantly necrotizing every person i attempted surgery on due to lacking medical clothes i absolutely welcome this PR.

2023-06-07 00:33 UTC, ClosetedSkeletonGH commented
> As someone who made the mistake of picking CMO as robot character and instantly necrotizing every person i attempted surgery on due to lacking medical clothes i absolutely welcome this PR.

this doesn't fix this at all, make an issue report. This just makes CMO robots spawn with a belt

2023-06-08 10:42 UTC, ZAMODA commented
May I make a request to allow robots to wear more decorative hats (cowboy hats, sunhats, etc) or would that be too out of scope for this PR?

2023-06-08 22:11 UTC, Lumipharon commented
Why are smelly shipside roles spawning with combat armor?

2023-06-11 03:02 UTC, coldironwarrior commented
> Why are smelly shipside roles spawning with combat armor?
 fixed

2023-06-11 07:09 UTC, Lumipharon requested changes
Also I seem to have made the rebel FC have the rebel robo outfit, but not the rebel human outfit. If you could do me a favour and update that in this pr as well?

2023-06-11 07:09 UTC, Lumipharon commented on code/datums/jobs/job/shipside.dm
> +	ears = /obj/item/radio/headset/mainship/mcom/rebel
you need to add this outfit to the rebel job, same goes for the others.

2023-06-17 02:37 UTC, QualityVan commented
Still working on this? It'd be nice to get it in before/alongside #13190 since that'll prevent the latter from torturing robots.

2023-06-25 21:36 UTC, coldironwarrior commented
i just deleted the rebel stuff since it got removed

2023-06-25 23:11 UTC, Lumipharon approved these changes

2023-06-25 23:11 UTC, merged