Fix King roar reliability
tgstation/TerraGov-Marine-Corps pull request #13203
Opened 2023-06-10 07:13 UTC by Wayland-Smithy

## About The Pull Request

Applies the roar effects in a 2 tile wide band instead of 1 while tracking victims to make sure they are not hit more than once, so that simply moving towards the King does not negate one of its most effective abilities.

## Why It's Good For The Game

Fix good.

## Changelog

:cl:
fix: King's roar no longer misses things moving towards the King,
/:cl:

2023-06-11 03:16 UTC, ivanmixo requested changes
Harddel potential here, cut the list after the roar is done rather than before

2023-06-11 03:22 UTC, ivanmixo commented
Actually how would you ever even get hit twice in the first place?

2023-06-11 04:32 UTC, Lumipharon commented
Being able to avoid the roar was intentional btw. Its also possible with prae/boiler/spitter abilities.

2023-06-11 18:36 UTC, Wayland-Smithy commented
> Harddel potential here, cut the list after the roar is done rather than before

Done. I had tested both ways, but didn't consider the harddel.

> Actually how would you ever even get hit twice in the first place?

I'm sure there are contrived ways like something pushes you (xeno, explosion, right after you are hit. I think it's worth preventing the potential salt.

> Being able to avoid the roar was intentional btw. Its also possible with prae/boiler/spitter abilities.

I get that, but you still have to step in acid and take damage. Timing your step towards the king is easy with any time dealation and avoids 100% of the damage and effects. Is that fair for a T4?

2023-06-12 18:57 UTC, ivanmixo commented
> I'm sure there are contrived ways like something pushes you (xeno, explosion, right after you are hit. I think it's worth preventing the potential salt.

I don't think the stun is severe enough to warrant it and it's not exactly implausible to get thrown back into a shockwave. But whatever.

2023-06-12 18:58 UTC, ivanmixo approved these changes

2023-06-18 04:20 UTC, merged