Refactor nuke to use timers
tgstation/TerraGov-Marine-Corps pull request #13228
Opened 2023-06-12 23:11 UTC by forestbbbbbbb

## About The Pull Request

Refactors the nuke to use timers, it shouldn't take twice the time set to explode anymore (i think)

## Changelog

:cl:
refactor: nuke uses timers
/:cl:

2023-06-12 23:24 UTC, ClosetedSkeletonGH commented
1 nuke second being 2 real seconds was bogus. Ive never once seen marines lose a nuke hold ever with the extra 3 minutes tacked onto it, this wont change anything imo

2023-06-13 18:58 UTC, ivanmixo requested changes
Not sure about the balance implications of nuke taking half as long as before. 

Double it so we retain old behavior and atomise this PR so it can be discussed separately.

2023-06-13 18:58 UTC, ivanmixo commented on code/game/objects/machinery/nuclearbomb.dm
> +/obj/machinery/nuclearbomb/proc/enable()
Autodoc

2023-06-13 18:58 UTC, ivanmixo commented on code/game/objects/machinery/nuclearbomb.dm
> +/obj/machinery/nuclearbomb/proc/disable()
Autodoc

2023-06-13 18:58 UTC, ivanmixo commented on code/game/objects/machinery/nuclearbomb.dm
> +	var/timer
Autodoc

2023-06-13 18:58 UTC, ivanmixo commented on code/game/objects/machinery/nuclearbomb.dm
> +	var/time = 180
Add a unit like `SECONDS` to this var define as well.

2023-06-13 20:45 UTC, ivanmixo approved these changes
LGTM

2023-06-14 13:43 UTC, merged