King is a real ruler now + shrike can send hive message
tgstation/TerraGov-Marine-Corps pull request #13223
Opened 2023-06-12 16:11 UTC by Blundir

## About The Pull Request

King is proper ruler now, it can summon burrowed larva, it stops hive collapse timer, it has death timer like queen, it can now send hive message, it can hijack the dropship, it can purchase primo upgrades, drone can instantly evolve into king just like into any other t4.
![w7l6x51zwA](https://github.com/tgstation/TerraGov-Marine-Corps/assets/100090741/60e83993-e218-4d4b-b103-5507658e8354)
![5NJ0H73qIF](https://github.com/tgstation/TerraGov-Marine-Corps/assets/100090741/8e861d50-b201-4999-ab5e-95c4c28f8468)

Additionally, shrike can now send hive messages as well.

Entire pr is a port of bunch of things from RUTGMC
https://github.com/Cosmic-Overlord/TerraGov-Marine-Corps/commit/540bd606855058c3a75219c0d2ece35edf6feb38
https://github.com/Cosmic-Overlord/TerraGov-Marine-Corps/commit/c1ebd1f7520b532e96abb4c09d8433c0b9855136
https://github.com/Cosmic-Overlord/TerraGov-Marine-Corps/pull/92
https://github.com/Cosmic-Overlord/TerraGov-Marine-Corps/pull/71
![dreamseeker_nbJfUPAJTo](https://github.com/tgstation/TerraGov-Marine-Corps/assets/100090741/48abb266-2ac0-45d9-89f9-705b062e8fbc)
![dreamseeker_W2DojGfjoi](https://github.com/tgstation/TerraGov-Marine-Corps/assets/100090741/928089d6-13e0-4065-b3d8-f56a39f07cbc)
![dreamseeker_1ITV4va0wB](https://github.com/tgstation/TerraGov-Marine-Corps/assets/100090741/c79773e7-3adc-463a-b8a7-b1c6e383bb35)

## Why It's Good For The Game

King not being a proper T4 makes it very frustrating, unique 1 slot xeno locked by high pop must have some game changing abilities to it.

## Changelog

:cl:
add: king has hive message, call of the burrowed abilities
add: drone can instantly evolve into king when pop is high enough
add: king can hijack dropship
add: king has evolve timer after his death (similar to the queen)
add: king has ability to buy primordial upgrades
add: shrike can now send hive messages
add: hive message now specifies which t4 caste sent the message
soundadd: king has his own sound when spawning (similar to the queen)
soundadd: king has his own sound when sending a hive message
/:cl:

2023-06-12 16:46 UTC, ivanmixo requested changes

2023-06-12 16:46 UTC, ivanmixo commented on code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
> +			to_chat(X, span_xenoannounce("<h2 class='alert'>The words of the princess reverberate in your head...</h2><br>[span_alert(input)]<br><br>"))
Shrike. Also this could be a switch statement.

2023-06-12 16:46 UTC, ivanmixo commented on code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
> +		//Display the queen's hive message at the top of the game screen.
This comment should be above the for loop not below

2023-06-12 18:55 UTC, ivanmixo approved these changes

2023-06-12 23:51 UTC, RuneQuesteER commented
> instantly evo to king
oh no

2023-06-13 00:17 UTC, Blundir commented
> > instantly evo to king
> > oh no

12 pop lock is still there

2023-06-13 22:26 UTC, merged