Adds Russian Red autoinjectors to Marinemed Vendor
tgstation/TerraGov-Marine-Corps pull request #13256
Opened 2023-06-15 15:50 UTC by KerbalCitizen

## About The Pull Request

Puts 30 RR autoinjectors into the marinemed vendor. 

## Why It's Good For The Game

RR is available in relatively large quantities because of the 6 RR pill bottles in Medplus vendor and 1 RR pill bottle in tadpole medical vendor. The squad marine only vendor also lets you choose injector pouch with your 2 options of pouches, which contains an RR injector. It contains 10u of RR and 5u of ryet, 15u dose setting by default. 

## Changelog

:cl:
add: Added 30 RR autoinjectors to Marinemed vendor
/:cl:

2023-06-15 16:32 UTC, FosterGrime-Heymynameslouie commented
me omw to inject 30 rr injectors onto the RO (he denied my order)

2023-06-16 02:23 UTC, ivanmixo approved these changes

2023-06-16 08:00 UTC, QualityVan requested changes
I'm not fond of this, especially with them being refillable. Something being available in initial loadouts doesn't mean it should be infinite from the general vendors.

2023-06-16 12:22 UTC, KerbalCitizen commented
> I'm not fond of this, especially with them being refillable. Something being available in initial loadouts doesn't mean it should be infinite from the general vendors.

I talked with marilyn about the ryet in there, first of all why is there, then secondly some concerns of farming ryet with it. The russian red itself is practically unlimited because I've never seen all of the starting RR get used up before, especially if one groundside medbay vendor is operational to give more RR pill bottles. There should be no real balance change by having unlimited RR since people never use up the currently large but limited stock. For other stuff like the synap injector in injector pouch or the sandbags and barbed wire in construction pouch, there is a big balance change if someone just made them unlimited because they're very useful and it's easy to use up the entire free supply of them. 

I was planning on changing the mix in the injectors to something more reasonable like 20u RR and 10u oxy with 15u default dose setting, which also stops ryet farming. I was under the assumption that I should make a separate PR for that because I hear atomize a lot.

2023-06-16 13:22 UTC, ivanmixo commented
> I'm not fond of this, especially with them being refillable. Something being available in initial loadouts doesn't mean it should be infinite from the general vendors.

Massive non issue because of the aformentioned pill bottles. Why would RR of all things be an issue if it were refillable?

2023-06-17 01:42 UTC, QualityVan commented
6 pill bottles is significantly less than infinite, and those don't contain rye. RR heals 20 damage per life tick for a not particularly significant downside (especially in situations where the alternative is dying and getting psidrained). 

>The russian red itself is practically unlimited because I've never seen all of the starting RR get used up before

'People don't make full use of it' isn't actually an argument in favor of buffing things.

2023-06-17 01:42 UTC, QualityVan approved these changes

2023-06-17 02:05 UTC, merged