SMG-25 changes
tgstation/TerraGov-Marine-Corps pull request #13273
Opened 2023-06-16 22:18 UTC by Pariah919

## About The Pull Request
Changes -
- Has gained all the unbarreled gun attachments (masterkey/PP/masterkey/mini/UGL)
- Has rifle level akimbo maluses.
- Has rifle-level fallof damage multiplier. (0.5)

## Why It's Good For The Game
Makes the SMG-25 more unique in its class, its basically a rifle with the damage profile and handling of an SMG now.

## Changelog

:cl:
balance: SMG-25 can now fit underbarreled guns.
balance: SMG-25 and its elite version now have higher akimbo maluses, and have less damage falloff over distance.
/:cl:

2023-06-16 23:33 UTC, Wayland-Smithy commented
Overall a buff unless akimbo. Do SMGs really need less falloff?

2023-06-17 02:34 UTC, Pariah919 commented
> Overall a buff unless akimbo. Do SMGs really need less falloff?

SMG-25 is basically only good because of akimbo, this nerfs the accuracy (if I remember my numbers right) but gives it rifle level falloff to complement the rifle level fire delay.

2023-06-17 05:29 UTC, Lumipharon commented
I'll stab you with a spork.

2023-06-17 08:23 UTC, maikilangiolo commented
> Overall a buff unless akimbo. 

Which is good. The akimbo smg25 is crazy

2023-06-17 17:32 UTC, ivanmixo approved these changes
An actual cross of smg and rifle, wow.

2023-06-18 11:40 UTC, Lumipharon commented
I don't think it should have the improved falloff, it's superior to actual rifles like the t18.

2023-06-18 11:41 UTC, Lumipharon requested changes
I don't think it should have the improved falloff, as that's better than many rifles, like the T18.

Also the akimbo vars you've tweaked really only effect it at long range. If you want to actually reduce akimbo effectiveness, hit the akimbo firedelay penalty.

2023-06-18 19:46 UTC, Pariah919 commented
> I don't think it should have the improved falloff, as that's better than many rifles, like the T18.

T-18 has a better burstfire than this, could just set it to t-18 falloff which is .9 I guess.

> Also the akimbo vars you've tweaked really only effect it at long range. If you want to actually reduce akimbo effectiveness, hit the akimbo firedelay penalty.

fair enough

2023-06-30 02:11 UTC, merged