cooler cooler explosions now using particles
tgstation/TerraGov-Marine-Corps pull request #13305
Opened 2023-06-19 15:16 UTC by tyeagg

## About The Pull Request
directed by michael bay

light and heavy explosion

https://github.com/tgstation/TerraGov-Marine-Corps/assets/98577688/d79aaea9-9ced-43ad-8a23-807528be768e

devastation explosions and lots of light explosions at once

https://github.com/tgstation/TerraGov-Marine-Corps/assets/98577688/802f8f1d-898f-4df0-9bfe-e23ff2b93357
## Why It's Good For The Game
looks cool
## Changelog
:cl:
add: particle explosions
del: effect system for explosions
imageadd: more smoke icons
code: removed the small anim arg from explosions
/:cl:

2023-06-19 21:47 UTC, Kapu1178 commented
"PRIVATE, DO YOU SEE THAT BUILDING?"
"YES SIR"
"WELL I DON'T WANT TO!"
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/75460809/d41241e3-8731-4164-a98e-b9aeeef30baf)

2023-06-20 23:35 UTC, Lumipharon approved these changes

2023-06-21 22:28 UTC, TiviPlus reviewed
Rest looks good enough

2023-06-21 22:28 UTC, TiviPlus commented on code/game/objects/effects/temporary_visuals/explosions.dm
> +	QDEL_IN(large_kickup, 25)
You can just make this 2 timers and avoid a lot of timer churn

2023-06-21 22:28 UTC, TiviPlus commented on code/game/objects/effects/temporary_visuals/explosions.dm
> +	icon_state = null
You can move I to below the return

2023-06-22 16:37 UTC, TiviPlus requested changes

2023-06-22 16:37 UTC, TiviPlus commented on code/game/objects/effects/temporary_visuals/explosions.dm
> +	var/obj/effect/abstract/particle_holder/large_kickup
Not nulled in destroy, leaving hanging ref

2023-06-27 00:55 UTC, Lumipharon approved these changes

2023-06-27 00:55 UTC, merged