Ports the Clown from RU
tgstation/TerraGov-Marine-Corps pull request #13303
Opened 2023-06-19 12:34 UTC by Blundir

## About The Pull Request

Adds adminbuse job, the clown, i don't really think it needs further explanation.
Admins can open a job slot for it.
Additionally, ported the infamous waddling effect.
![dreamseeker_MJJKqCZFXf](https://github.com/tgstation/TerraGov-Marine-Corps/assets/100090741/50a25d1c-a948-4b47-936b-88d72b24c464)

Complete with hud, minimap icons, custom radio prefixes and other.
![dreamseeker_FE2BaLhqYT](https://github.com/tgstation/TerraGov-Marine-Corps/assets/100090741/01d81754-880a-450d-a69a-391bcb205c38)

Basically port of my stuff from RU.

## Why It's Good For The Game

HONK. More admin stuff is good, as well as good jokes.

## Changelog

:cl:
add: Added the Clown
/:cl:

2023-06-20 18:52 UTC, ivanmixo requested changes

2023-06-20 18:52 UTC, ivanmixo commented on code/datums/jobs/job/shipside.dm
> +	to_chat(M, {"Your primary job is to uphold the fun, pranks, entertainment and good mood aboard the ship. Marines can get sad after a few weeks of cryosleep!"})
```suggestion
	to_chat(M, "Your primary job is to uphold the fun, pranks, entertainment and good mood aboard the ship. Marines can get sad after a few weeks of cryosleep!")
```

2023-06-20 18:52 UTC, ivanmixo commented on code/modules/clothing/shoes/miscellaneous.dm
> +	var/enabled_waddle = TRUE
doc

2023-06-21 14:56 UTC, Wirpy commented
speedmerge this now

2023-07-02 00:56 UTC, closed without merging