HYPERSCALE RETURNS!
tgstation/TerraGov-Marine-Corps pull request #13318
Opened 2023-06-20 07:51 UTC by hyper2snyper

## About The Pull Request
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/43631032/3bf8d068-94ce-4c90-8335-f02dae2fc88a)
HYPERSCALE RETURNS!!

This re-implements the old hyperscale system in a new and improved manner. Gone are the days of slicing sprites up into a million in order to apply hyperscale, now all that is needed is a sprite with a clear defined palette. (It does not even need to be greyscale! (Although you probably want it to be since it gets converted into greyscale for sorting so it's best for interpretation to sprite in greyscale.))
Just look at these sprite sheets!!
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/43631032/057ad251-17ad-444d-b1f3-bd54dea93500)
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/43631032/ad3cfad1-3efc-4956-84e2-9c6a1d4c49df)

The image does not show all the hyperscale items, so I will list them:

- Jaeger MK1
- Jaeger MK2
- Style line hats
- Style line duster
- Capes and Kama
- Xenonaut Gear
- Robot armor
- All visors including Robot and the heavy xenonaut helmet

Codewise:
Hyperscale works under the greyscale system and generates at runtime.
This is the process of generation:
1) At Subsystem setup, when the greyscale configs are all initialized, the hyperscale sprites colors are gathered and sorted by darkest to lightest greyscale values, this color list is stored on the config.
2) When an armor piece is colored, a byond builtin to swap the colors is called and the existing colors are swapped out with the palette. This is then passed like normal through the system.
The most expensive part of the system only happens at game init, and has very little impact on even my machine. I think it will be fine.

I have also added a utility "prefix" var on greyscale configs to reduce icon file and config bloat. Will probably add more.

## Why It's Good For The Game
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/43631032/e6b56f8e-d68c-4b48-a498-4dc4d67c30cd)
Doesn't this just look cool??

## Todo

- [ ] Fix Loadouts (This will probably mean a wipe of old greyscale.)
- [ ] Fix up any odd sprites, particularly capes. Kuro will probably help me with this.
- [ ] Documentation and cleanup.
- [ ] Testing and fixes.

This brings the best of both worlds. It allows easy addition of colors. Colors are curated and palettes. Sprites are maintainable as they are simply greyscale.

## Changelog
:cl:
add: Hyperscale system added to greyscale.
add: Hyperscales Jaeger Mk1, Mk2, Robot armor, Style line, Xenonaut.
/:cl:

2023-06-20 08:12 UTC, Barnet2 commented
We are so back.

2023-06-20 08:16 UTC, cazuccmuss commented
speedmerge...

2023-06-20 08:25 UTC, zzurge commented
MY DRIP GAME IS ABOUT TO COME BACK

2023-06-20 09:55 UTC, DorfGuy1 commented
the robots still don'tlook as good as they used to

2023-06-20 12:57 UTC, Kuro020 approved these changes
The suffering is over, the golden age begins now

2023-06-20 15:08 UTC, Alexeivichi commented
We never left.

2023-06-20 15:29 UTC, novaepee commented
One of hyper's many projects. Stay tune for more.

2023-06-21 10:19 UTC, Lumipharon approved these changes
Seems OK at first look

2023-06-21 13:39 UTC, Guidesu commented
Right clicking on the M10XE with the painting tools does nothing.
The helmet on M10XE loses storage aswell.
Could you somehow make the modules like helmet visor like TYR and mirmir be colorable so it can fit the color scheme of a armour?

2023-06-21 13:40 UTC, Guidesu commented
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/67030229/b6c57b61-3d99-4064-8280-69b6079b7469)
Looks ugly like this

2023-06-21 13:40 UTC, Weedmaster77 commented
The armor changes are nice but why cant we still have the old cloak coloring system back it was far better and made it easier to match clothing colors an for only one type of item don't think its that much of a problem to leave it as was.

2023-06-21 14:01 UTC, 1kajowsmol commented
um scout helmet is invisible, and visors cant be colored......... 
![Screenshot 2023-06-21 230019](https://github.com/tgstation/TerraGov-Marine-Corps/assets/71049852/0f29cb1a-78b5-41f7-85c9-86860cb42174)

2023-06-21 14:12 UTC, ilikesaying commented
Round ID 21787
![Screenshot 2023-06-22 000602](https://github.com/tgstation/TerraGov-Marine-Corps/assets/65475697/72e895b1-b73b-4de7-98d9-3046c1033b9b)
![Screenshot 2023-06-22 000622](https://github.com/tgstation/TerraGov-Marine-Corps/assets/65475697/1034c014-facc-4a79-954d-f912138f8e56)

there's supposed to be a EOD jaeger exoskeleton here
![Screenshot 2023-06-22 000712](https://github.com/tgstation/TerraGov-Marine-Corps/assets/65475697/398c7e3b-4997-41f9-9d21-03cd687db109)

2023-06-21 22:16 UTC, Tailiik commented
>Remove hyperscale because it's too hard to maintain 
>Make limited colors because muh art direction consistency or something
>Bring back hyperscale because actually lol lmao it isn't too hard to maintain
>But also nerf cape colors 
>And also why test pr let's make armor invisible all day 
>Honk

In all seriousness I dunno if it's because the pr in general is broken or what but you can't recolor visors now, the one part of helmets that actually do show up, honk

2023-06-21 22:26 UTC, hyper2snyper commented
> > Remove hyperscale because it's too hard to maintain
> > Make limited colors because muh art direction consistency or something
> > Bring back hyperscale because actually lol lmao it isn't too hard to maintain
> > But also nerf cape colors
> > And also why test pr let's make armor invisible all day
> > Honk
> 
> In all seriousness I dunno if it's because the pr in general is broken or what but you can't recolor visors now, the one part of helmets that actually do show up, honk

The visors should be colorable. Theres something really weird going on.

2023-06-21 23:26 UTC, Kuro020 commented
> > Remove hyperscale because it's too hard to maintain
> > Make limited colors because muh art direction consistency or something
> > Bring back hyperscale because actually lol lmao it isn't too hard to maintain
> > But also nerf cape colors
> > And also why test pr let's make armor invisible all day
> > Honk
> 
> In all seriousness I dunno if it's because the pr in general is broken or what but you can't recolor visors now, the one part of helmets that actually do show up, honk

maybe, its easier to maintain now because hyper redid the system and it isnt cbt to sprite it anymore? imagine that

2023-06-22 01:42 UTC, Pixelknightly commented
> > Remove hyperscale because it's too hard to maintain
> > Make limited colors because muh art direction consistency or something
> > Bring back hyperscale because actually lol lmao it isn't too hard to maintain
> > But also nerf cape colors
> > And also why test pr let's make armor invisible all day
> > Honk
> 
> In all seriousness I dunno if it's because the pr in general is broken or what but you can't recolor visors now, the one part of helmets that actually do show up, honk

This IS the pr being tested. That's why it's called a "testmerge"
Also what kuro said.

Did you even bother to read the PR description? Or atleast familiarize yourself with what the tags mean?
Is that why you're honking a clown horn?

2023-06-22 04:42 UTC, Neskah commented
The pseudo-shading stuff is cool, but this is a straight downgrade from the less restrictive color picker system, IMHO. Can't do little nuanced things like color your visor to match svalinn energy shields, etc, or color both elements of a cape the same shade as to have it look like it doesn't have a pattern. Things looked cool before, and now they're just ever-so-slightly different looking with significantly more restrictions. If this is an implementation strictly to eliminate our horde of femboy medics that's the most rational argument I can think of. (Or if it was somehow implemented as an optional system.)

Also, robot helmets have no visor or storage, and robot body armor's sprite does not have visual upgrades when held in the hand.

2023-06-22 06:46 UTC, Sirsnek15 commented
> The pseudo-shading stuff is cool, but this is a straight downgrade from the less restrictive color picker system, IMHO. Can't do little nuanced things like color your visor to match svalinn energy shields, etc, or color both elements of a cape the same shade as to have it look like it doesn't have a pattern. Things looked cool before, and now they're just ever-so-slightly different looking with significantly more restrictions. Also, robot helmets have no visor or storage, and robot body armor's sprite does not have visual upgrades when held in the hand.

literally everything listed here is a bug, not intended, there are no reasons or wants for these things to be changed in this way. Its not a downgrade, just a VERY bugged upgrade that needs fixing

2023-06-22 23:24 UTC, Lumipharon commented on code/__DEFINES/loadout.dm
>  GLOBAL_LIST_INIT(accepted_loadout_versions, list(5, 6, 7, 8, 9, 10, 11))
```suggestion
GLOBAL_LIST_INIT(accepted_loadout_versions, list(5, 6, 7, 8, 9, 10, 11, 13))
```
Needed for loadout imports.

2023-06-24 04:29 UTC, Neskah commented
> 

Oh, fair. Are we intended to be able to use full RGB coloration on cloaks/visors?

2023-06-25 06:26 UTC, hyper2snyper commented
> > 
> 
> Oh, fair. Are we intended to be able to use full RGB coloration on cloaks/visors?

Alright so there seems to be some miscommunication here. Everything about your first comment is actually ok. None are bugs, the color wheel is gone.

So the current issue of regular sprites is that maintenance and multiple colors are exponential, the walls of sprites should attest to that. The issue with greyscale is that you lose out on all manner of color shifting. Yellows, reds and oranges all look terrible. However it's capable of many many colors. Hyperscale is the happy medium.

We used to have hyperscale about a year ago, it was always meant to replace both color wheel and manual presets. However, it was very hard to sprite for and byond issues caused it to be deleted for some time. (I also had a lot of life stuff so I couldn't work on it)

Color wheel is gone so that better looking palettes can instead be used.

However, this is only the first in my planned color and drip related prs. The next one should expand this system and make it easier to spread. Depending on permission (if I can convince kuro) and implementation (if I can get it to work in the code) I do plan on allowing both color wheel and palettes for secondary colors such as visors and cape trims. For cape trims I also plan to add a bunch of variants including the ability to remove it. 

I hope this cleared some stuff up.

2023-06-25 08:17 UTC, TiviPlus requested changes
Impressively simple solution very nice

2023-06-25 08:17 UTC, TiviPlus commented on code/datums/greyscale/layer.dm
> +			for(var/y=0, y<icon.Height(), y++)
```suggestion
		for(var/x=0 to icon.Width())
			for(var/y=0 to icon.Height())
```
might need --icon.Height()

2023-06-25 08:17 UTC, TiviPlus commented on code/datums/greyscale/layer.dm
> +				if(!pixel || (pixel in icon_file_colors)) continue;
```suggestion
				if(!pixel || (pixel in icon_file_colors))
					continue
```

2023-06-25 08:17 UTC, TiviPlus commented on code/datums/greyscale/layer.dm
> +				for(var/i=1, i<=length(icon_file_colors), i++)
Ditto use byond format

2023-06-25 08:17 UTC, TiviPlus commented on code/datums/greyscale/layer.dm
> +	for(var/i=1, i<=length(icon_file_colors), i++)
Ditto use byond format

2023-06-25 08:17 UTC, TiviPlus commented on code/datums/loadout/loadout_manager.dm
> +			attachments.Add(new_module)
dunno why this is in a seperate proc?

2023-06-25 08:17 UTC, TiviPlus commented on code/modules/clothing/modular_armor/attachments.dm
> +	examine_list += "Right click the [parent] with paint to color the [src]"
```suggestion
	examine_list += "Right click the [parent] with paint to color [src]"
```

2023-06-25 08:17 UTC, TiviPlus commented on code/modules/clothing/modular_armor/modular.dm
> +			selection = "Preset Colors"
Use defines for these strings please

2023-06-25 08:17 UTC, TiviPlus commented on code/modules/clothing/modular_armor/modular.dm
> +
Ditto

2023-06-25 22:55 UTC, Lumipharon commented
Causes #13351 
Was fixed in the jaeger rework.

2023-06-27 00:56 UTC, Lumipharon approved these changes

2023-06-27 00:56 UTC, merged