Gorger buff of the year (RUTGMC port)
tgstation/TerraGov-Marine-Corps pull request #13317
Opened 2023-06-20 01:53 UTC by Blundir

## About The Pull Request

- Feast now works on all xenos in 4 tile radius, cooldown decreased from 180 to 30
- Feast healing now has visual effect when it's active
- Drain and Carnage drain real blood from people (30u)
- Transfusion range increased from 2 tiles to 3
- You can move while casting Transfusion
- Psychic Link cooldown from 50 to 15
- Psychic Link doesn't require to stand still
- Gorger now has passive plasma regen up to 10% of maximum plasma

![dreamseeker_41t1jVpGkr](https://github.com/tgstation/TerraGov-Marine-Corps/assets/100090741/d5e3faa5-7c06-43b5-97e2-c9a617aa5869)

100% port of https://github.com/Cosmic-Overlord/TerraGov-Marine-Corps/pull/122 and https://github.com/Cosmic-Overlord/TerraGov-Marine-Corps/pull/129

## Why It's Good For The Game

Gorger is really uncomfortable to play in general, these are merely QoL considering what state he is in right now, Gorger cannot sustain effectively neither offensive or support abilities, some abilities are very rarely used in general, this tries to correct that (very successfully, considering RU experience with it). Probably needs a testmerge to estimate how good/bad these changes are. These changes are present on RU for 3 months without any balance issues.

## Changelog

:cl:
add: Drain and Carnage drain real blood from people (30u)
add: Feast now works on all xenos in 4 tile radius
qol: gorger can cast transfusion while moving
qol: gorger regenerates 10% of blood automatically
qol: Psychic Link doesn't require to stand still
balance: Transfusion range increased from 2 tiles to 3
balance: Feast cooldown from 180 to 30
balance: Psychic  cooldown from 50 to 15
/:cl:

2023-06-20 01:57 UTC, lKiseki commented
Woah woah woah that's one too many eggs in one basket. Gorger doesn't even _need_ half of these.

2023-06-20 02:42 UTC, Blundir commented
> > Drain and Carnage drain real blood from people (30u)
> 
> Unlikely will pass since QV has plans for blood.
> 
QV seen my plans fod gorger and haven't said anything about blood

2023-06-20 04:24 UTC, blackdav123 commented
feast actually working as a support ability with the increased radius and indicator is helpful

2023-06-20 06:12 UTC, maikilangiolo commented
> Woah, woah, woah. That's one too many eggs in one basket. Gorger doesn't even _need_ half of these.

This tbh 💀💀

2023-06-20 17:38 UTC, chizzy376 commented
Gorger is currently okay, but 3/4 of his kit is useless. This PR makes his kit actually useful, good stuff. Though I'm a bit miffed about the 30u blood drain

2023-06-20 19:29 UTC, Araulius commented
marines have unlimited isopills, blood isn't and issue

2023-06-20 19:31 UTC, private-tristan commented
Does drain blood drain apply to corpses?

2023-06-21 14:20 UTC, Blundir commented
> Does drain blood drain apply to corpses?

No

2023-06-25 14:56 UTC, ivanmixo commented
Being about to directly drain marine blood level is problematic due to how severe the hunger slowdown from "low" (like 90%) blood is.

2023-06-26 02:13 UTC, Blundir commented
> Being about to directly drain marine blood level is problematic due to how severe the hunger slowdown from "low" (like 90%) blood is.

In practice, to drain a single marine to that point is a challenge on itself, also there is still isotonic everywhere, nano blood for extreme cases, having low blood has more counters than sources at the moment

2023-06-26 02:26 UTC, Lumipharon requested changes

2023-06-26 02:26 UTC, Lumipharon commented on code/datums/status_effects/xeno_buffs.dm
> +	for(var/mob/living/carbon/xenomorph/affected_xeno AS in GLOB.hive_datums[XENO_HIVE_NORMAL].xenos_by_zlevel["[X.z]"])
Not that it'll matter often, but this is hard coded to normal hive.

2023-06-26 02:26 UTC, Lumipharon commented on code/modules/mob/living/carbon/xenomorph/castes/gorger/abilities_gorger.dm
> -		return FALSE
why have these checks been removed?

2023-06-26 02:26 UTC, Lumipharon commented on code/modules/mob/living/carbon/xenomorph/castes/gorger/abilities_gorger.dm
> +	cooldown_timer = 30 SECONDS
This seems exceptionally low but eh.

2023-06-26 02:33 UTC, Lumipharon commented
Also does feast actually apply to other xenos? I don't see anything in the code, unless I'm missing something.

2023-06-26 02:41 UTC, Lumipharon requested changes
Feast concerns me, a lot.

2023-06-26 02:41 UTC, Lumipharon commented on code/datums/status_effects/xeno_buffs.dm
> +		adjustOverheal(affected_xeno, heal_amount / 2)
This also seems like, incredibly, mega strong considering there is no AOE/stacking cap, and its going to be very spammable. I am somewhat doubtful of this.

2023-06-26 02:41 UTC, Lumipharon commented on code/datums/status_effects/xeno_buffs.dm
> +		if(!line_of_sight(X, affected_xeno, 4) || get_dist(X, affected_xeno) > 4)
is dist even needed if you're already doing LOS with a cap of 4 tiles?

2023-06-26 02:41 UTC, Lumipharon commented on code/modules/mob/living/carbon/xenomorph/castes/gorger/abilities_gorger.dm
> +	if(!line_of_sight(owner, target_xeno, 3) || get_dist(owner, target_xeno) > 3)
I know this was existing code, but again, I am fairly sure line_of_sight fails if they're outside of the specified range anyway.

2023-06-27 05:04 UTC, Aporhtonoma commented
gorger actually draining blood?! Oh hell yea

2023-06-27 08:19 UTC, Naaanii commented
Draining real blood lol. Draining 30u lmao.

Gorger powercreep PR of the year.

2023-06-27 08:52 UTC, Lumipharon commented
@Blundir There's just too much going on in this PR/very strong changes. Redo it with a single change at a time and it'll be a lot more comfortable to balanc/TM.

2023-06-27 08:52 UTC, closed without merging

2023-06-27 08:52 UTC, spookydonut commented
We're happy to consider these changes separated out in to separate PRs but as a package deal this is too big a balance change to consider merging.

2023-06-27 13:59 UTC, Blundir commented
Hell nah

2023-06-29 00:17 UTC, Arturlang commented
@Blundir this looks great and yeah atomize this more, especially love not having to stop playing the game for psy link