evolution without client
tgstation/TerraGov-Marine-Corps pull request #13310
Opened 2023-06-19 19:05 UTC by Blundir

## About The Pull Request

Enables evolution points collecting even when there is no client/soul.

100% port of this https://github.com/Cosmic-Overlord/TerraGov-Marine-Corps/pull/174

## Why It's Good For The Game

Good thing for cases when a client crashes and has to reload, or during any other unforsee disconnecting issues, which compensates the time client wasn't connected, additionally, would lower the damage to the hive by having ssd xeno ready to evolve if a ghost takes it, without any need to wait for evolution.

## Changelog

:cl:
add: evolution points tick even if xeno has no client/soul
/:cl:

2023-06-19 20:29 UTC, Wayland-Smithy commented
aghost buff 👻

2023-06-20 18:45 UTC, ivanmixo requested changes

2023-06-20 18:45 UTC, ivanmixo commented on code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
> +	if(!client || !ckey) // stop evolve progress for ssd/ghosted xenos
```suggestion
	if(!client || !ckey)
```

2023-06-21 07:05 UTC, ivanmixo approved these changes

2023-06-21 09:55 UTC, merged