new/list => list()
tgstation/TerraGov-Marine-Corps pull request #13347
Opened 2023-06-23 20:18 UTC by ivanmixo

## About The Pull Request

Old syntax.

## Why It's Good For The Game

 It's better list inits are consistent.

## Changelog

:cl:
code: Converted instances of new/list to the list wrapper
/:cl:

2023-06-23 21:26 UTC, Kapu1178 requested changes
new /list(num) populates the list with that many nulls.

2023-06-23 21:26 UTC, Kapu1178 commented on code/game/objects/machinery/computer/security.dm
> +						var/prelist = list(2)
these are not equivalent

2023-06-23 21:26 UTC, Kapu1178 commented on code/game/objects/machinery/computer/skills.dm
> +						var/prelist = list(2)
these are not equivalent

2023-06-23 22:02 UTC, ivanmixo commented on code/game/objects/machinery/computer/security.dm
> +						var/prelist = list(2)
Thanks for pointing this out

2023-06-26 01:33 UTC, Lumipharon approved these changes

2023-06-26 01:33 UTC, merged