Close Air Support TLC pack
tgstation/TerraGov-Marine-Corps pull request #13387
Opened 2023-06-29 00:43 UTC by Kapu1178

## About The Pull Request
- Cleans up CAS code a bit
- Adds two lase features

## Changelog

:cl:
add: CAS will now get JUMP links in chat when a lase is deployed.
add: CAS now has a Jump to Lase ability button.
code: Cleaned up CAS code. Please contribute CAS features. I beg you.
/:cl:

2023-07-01 21:24 UTC, TiviPlus requested changes
Please split your File move and changes in future or I will force you to atomize

2023-07-01 21:24 UTC, TiviPlus commented on code/modules/condor/cas_misc.dm
Please dont use misc files for love of god just name after whats in em (actions)

2023-07-01 21:24 UTC, TiviPlus commented on code/modules/condor/cas_chair.dm
> +				to_chat(usr, "<span class='warning'>Combat has not yet initiated, CAS unavailable.")
use spans

2023-07-01 21:24 UTC, TiviPlus commented on code/modules/condor/cas_chair.dm
> +				to_chat(usr, "<span class='warning'>Unable to launch, low fuel.")
ditto, or even better use balloon alerts

2023-07-01 23:01 UTC, Kapu1178 commented on code/__DEFINES/cas.dm
> +#define CAS_JUMP_LINK(location) "(<a href='?_src_=usr;cas_jump=\ref[location];'>JUMP</a>)"
It was originally but I later redid how I handled the JUMP message. I wanted to keep it in to incentivize people to make more CAS features.

2023-07-01 23:01 UTC, Kapu1178 commented on code/modules/condor/cas_misc.dm
> +		to_chat(plane.eyeobj.eye_user, text)
See previous comment.

2023-07-01 23:01 UTC, Kapu1178 commented on code/modules/condor/cas_chair.dm
> +				to_chat(usr, "<span class='warning'>Unable to launch, low fuel.")
Leftover from file move.

2023-07-01 23:02 UTC, Kapu1178 commented on code/modules/condor/cas_chair.dm
> +	QDEL_NULL(cockpit)
Moved file contents, did not author.

2023-07-01 23:02 UTC, Kapu1178 commented on code/modules/condor/cas_shuttle.dm
>  	fuel_left--
I thought it'd be unlikely fuel mechanics would be changed soon (if ever), indefinite flight makes testing anything that happens during flight easier. Will revert if asked.

2023-07-01 23:04 UTC, Kapu1178 commented on code/modules/condor/cas_chair.dm
> +				to_chat(usr, "<span class='warning'>Combat has not yet initiated, CAS unavailable.")
Moved file contents, did not author.

2023-07-05 09:44 UTC, TiviPlus commented on code/modules/condor/cas_shuttle.dm
>  	fuel_left--
mhmmm I guess

2023-07-05 09:45 UTC, TiviPlus commented on code/__DEFINES/cas.dm
> +#define CAS_JUMP_LINK(location) "(<a href='?_src_=usr;cas_jump=\ref[location];'>JUMP</a>)"
its dead code, and since CAS_JUMP_LINK (the hard part) exists it's kinda silly

2023-07-05 20:52 UTC, merged