Adds an APC sanity unit test
tgstation/TerraGov-Marine-Corps pull request #13462
Opened 2023-07-10 18:42 UTC by ivanmixo

## About The Pull Request

Adds an APC sanity unit test
## Why It's Good For The Game

Areas that need APCs should have APCs and areas that don't shouldn't have APCs. No area should have multiple APCs.
## Changelog
:cl:
add: Adds an APC sanity unit test
/:cl:

2023-07-11 01:17 UTC, XElectricX commented
This is beyond overdue. Thanks Ivan.

2023-07-11 04:04 UTC, ivanmixo commented
It's kinda not ideal because it only tests the map currently being ran, should figure out a way to somehow make it so runs on all maps, although this would inflate the hell out of the actions. TG does it though. But we have a lot more maps than them. Bleh.

2023-07-11 08:01 UTC, QualityVan commented on code/modules/unit_tests/apc_area_sanity.dm
> +				Fail("Unneded APC at [found_apc.x], [found_apc.y], [found_apc.z]")
```suggestion
				Fail("Unneeded APC at [found_apc.x], [found_apc.y], [found_apc.z]")
```

2023-07-12 03:06 UTC, RipGrayson approved these changes

2023-07-13 22:00 UTC, TiviPlus requested changes
Also grayson changed file codes again or whatever theyre called

2023-07-13 23:00 UTC, ivanmixo commented on code/modules/unit_tests/apc_area_sanity.dm
> +	for(var/area/tested_area in world)
I guess I could restrict it to just ground and station.

2023-07-18 16:40 UTC, merged