sentries now need line of sight to actually acquire a target
tgstation/TerraGov-Marine-Corps pull request #13472
Opened 2023-07-12 14:54 UTC by MacBlaze1

## About The Pull Request

This fixes #13471

## Why It's Good For The Game

This bug makes it possible to cheese sentries by having them target you while you are behind a wall.

## Changelog

:cl:

fix: fixed sentries targeting mobs when they cant actually see and shoot them
/:cl:

2023-07-12 17:02 UTC, ThelastArchiver commented
does this also work for xeno turrets?

2023-07-12 18:20 UTC, hyper2snyper commented
Sentries already check path. There's a reason they don't try to shoot through walls. This is unnecessary.

2023-07-12 20:36 UTC, MacBlaze1 commented
> Sentries already check path. There's a reason they don't try to shoot through walls. This is unnecessary.

fixed now it works

2023-07-12 20:36 UTC, MacBlaze1 commented
> does this also work for xeno turrets?

its for all deployable turrets so probably

2023-07-12 20:45 UTC, hyper2snyper approved these changes
Very cool

2023-07-13 04:27 UTC, MacBlaze1 commented
> Very cool

Lumi doesnt want the PR because it may allow xenos to cheese in other ways

2023-07-13 17:54 UTC, chizzy376 commented
> Sentries already check path. There's a reason they don't try to shoot through walls. This is unnecessary.

![exploit](https://github.com/tgstation/TerraGov-Marine-Corps/assets/80391698/0ca908fc-d446-4abb-bb79-71506afcbc2c)
Why are you lying

2023-07-13 17:58 UTC, MacBlaze1 commented
> > Very cool
> 
> Lumi doesnt want the PR because it may allow xenos to cheese in other ways

actually nvm I took the wrong intent away its moreso he is concerned about xenos not being targeted when peeking corners

2023-07-13 21:57 UTC, TiviPlus requested changes
Looks excessively underperformant

2023-07-14 20:38 UTC, MacBlaze1 commented
> Looks excessively underperformant

made more performant, tested and works

2023-07-27 15:32 UTC, TiviPlus approved these changes
I dont like it 100% but ok

2023-07-27 15:32 UTC, merged

2024-01-20 14:06 UTC, chizzy376 commented
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/80391698/769a39ae-1112-4103-accc-b70a315ccce9)
Not fixed.