Adds ML-41 Autoshotgun to ICC Guard loadouts
tgstation/TerraGov-Marine-Corps pull request #13487
Opened 2023-07-14 19:36 UTC by Pariah919

## About The Pull Request
Adds ML-41 Autoshotgun to ICC guards.
Adds 12G Frag rounds, fires 4 pellets that do 1 light explosion on hit.

Gun stats below
<details>
Fire delay-> .9
Aim slowdown-> 0.6
Wield delay-> 0.55

Only has flechette and frag rounds.
</details>

## Why It's Good For The Game
More interesting cool stuff for ERTs, also https://www.youtube.com/watch?v=_0-QRmtlLAQ

## Changelog

:cl:
add: Added new 12G Frag rounds, only for ICC so far.
add: New ML-41 12G autoshotgun, it can fire 12G flechettes and fragmentation rounds.
/:cl:

2023-07-14 21:25 UTC, TiviPlus approved these changes

2023-07-15 00:47 UTC, Lumipharon requested changes
This is an autofire impact grenade launcher, only it essentially fires 3 impact grenade every click.

Depending on RNG this can 1 hit crit full health marines.

2023-07-24 21:01 UTC, Pariah919 commented
waiting for #13508

2023-07-24 21:34 UTC, Pariah919 commented
i'll reopen this instead

2023-07-24 21:34 UTC, closed without merging