Likely fix for cross-z tts and misc sendspeech improvements
tgstation/TerraGov-Marine-Corps pull request #13596
Opened 2023-07-26 20:35 UTC by TiviPlus

## About The Pull Request
humans_by_zlevel works now and replace another one i added
TTS should no longer cross z for ghosts, tm would be good

## Changelog

:cl:
fix: fixed  TTS for ghosts going across zlevels
/:cl:

2023-07-26 23:37 UTC, Strayed-Raven commented
I told that you can hear TTS in certain spots as Ghost even outside their range. Knew it

2023-07-27 09:58 UTC, Lumipharon requested changes

2023-07-27 09:58 UTC, Lumipharon commented on code/game/sound.dm
> +	for(var/mob/living/carbon/human/H AS in SSmobs.dead_players_by_zlevel[z])
??

2023-07-28 04:18 UTC, Texicos commented
broke all groundside local chat on lawanka

2023-07-28 23:48 UTC, Lumipharon commented
> broke all groundside local chat on lawanka

I don't see this?

2023-07-28 23:48 UTC, Lumipharon approved these changes

2023-07-28 23:48 UTC, merged