Basic Valhalla fixes and (incredibly) minor additions
tgstation/TerraGov-Marine-Corps pull request #13612
Opened 2023-07-27 16:57 UTC by KM-Catman

## About The Pull Request

Removes several items in Valhalla with broken sprites. (Armor pieces, Lockers, Books, etc)
Replaces the Prep room doors with their Marine prep room versions.
Makes all the walls and windows of the Valhalla testing room unbreakable (Primarily to help Perma EORD Valhalla players).
Adds a fluttering friend to a small room in Valhalla.
Materializes the ▋▋▋▋▋ in the Chaplain's closet.

## Why It's Good For The Game

Basic Valhalla map improvements. Probably the first of several. Making the spawn room walls indestructible lowers the incentive for people to spam rockets everywhere, having the broke sprites fixed/removed is just a basic clean-up thing, and adding a few plushies never hurt anyone.

## Changelog

:cl: Meowosers
add: Three friends have been added to the Valhalla station
add: The Prep room in Valhalla has had it's walls reinforced
fix: Removed several broken sprites from the Valhalla station
/:cl:

2023-07-27 17:57 UTC, RipGrayson approved these changes

2023-07-27 22:01 UTC, KM-Catman commented
I'd prefer if this wasn't merged yet. Grayson has advised that I combine it with a separate Valhalla change first.

2023-07-28 00:10 UTC, KM-Catman commented
Alright, added a shitload to the PR. All done now

2023-07-28 02:33 UTC, RipGrayson requested changes
I'm going to exercise my maintainer given privilege of complaining about meaningless cosmetic details.

Please make the floor tiles here red instead of black.
![wall10](https://github.com/tgstation/TerraGov-Marine-Corps/assets/49290523/b2308161-becf-4184-8286-04f8cdc8e28e)

Something like this anyway, but it doesn't have to be exact.
![wall11](https://github.com/tgstation/TerraGov-Marine-Corps/assets/49290523/b94b8218-3408-4909-aee9-f73b3126f287)

2023-07-28 03:06 UTC, RipGrayson approved these changes

2023-07-28 18:18 UTC, KM-Catman commented
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/97270834/15276860-723b-4515-b641-6e66b8caa66c)
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/97270834/2a5edf92-04fa-4296-8131-52662028f469)
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/97270834/0b3fefb0-e0a7-4886-93a6-895188df1284)

2023-07-30 01:19 UTC, RipGrayson requested changes
![wall15](https://github.com/tgstation/TerraGov-Marine-Corps/assets/49290523/9144a844-8cb8-40d3-b078-01e0b02269bb)
You have space tiles here, they need fixed before I can merge

2023-07-30 01:59 UTC, KM-Catman commented
> 

Damnit, on it. Will this add another 24 hour delay or no?

2023-07-30 02:01 UTC, KM-Catman commented
There, space sufficiently duct taped

2023-07-30 03:19 UTC, merged

2023-07-30 22:52 UTC, ivanmixo commented on code/datums/jobs/job/fallen.dm
> +	skills_type = /datum/outfit/job/civilian/synthetic
Yeah?