Magnum skins
tgstation/TerraGov-Marine-Corps pull request #13667
Opened 2023-08-01 04:58 UTC by Lumipharon

## About The Pull Request
More gamba for the gamba box.

![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/7869430/8ceda921-4aa5-4935-8325-7943d2960253)

## Why It's Good For The Game
Gambling is good. Marines didn't need those points anyway.

## Changelog

:cl:
add: R-76 magnum is now available in gold, silver and nickle flavours via black market lootboxes in req
/:cl:

2023-08-01 05:56 UTC, zee11zee commented
LETS GOOOO!!!

2023-08-01 08:24 UTC, maikilangiolo commented
Cool, now make the gun actually good instead of a reskinned slug shotgun with windup and less ammo

2023-08-02 19:30 UTC, ivanmixo requested changes

2023-08-02 19:30 UTC, ivanmixo commented on code/modules/projectiles/gun_attachables.dm
> +	desc = "A custom rail mounted zoom sight scope designed specifically for the R-76 Magnum. Allows zoom by activating the attachment. Use F12 if your HUD doesn't come back."
```suggestion
	desc = "A custom rail mounted zoom sight scope designed specifically for the R-76 Magnum. Allows zoom by activating the attachment."
```

Uh let's not continue this trend. There isn't a case where using a scope should ever make your hud disappear.

2023-08-03 01:03 UTC, Lumipharon commented
dunno why the icon diff bot is losing its mind.

2023-08-03 04:58 UTC, ivanmixo approved these changes

2023-08-09 04:06 UTC, merged