TGMC flag in display
tgstation/TerraGov-Marine-Corps pull request #13679
Opened 2023-08-02 19:53 UTC by novaepee

## About The Pull Request

## Why It's Good For The Game

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2023-08-03 08:00 UTC, Arctrooper8 commented
It looks kind of goofy due to the perspective of the wall. It's pinned to the top of the wall but doesn't drape down at all just being a continuous straight down flag.

The TGMC logo looks pretty nice, but I feel the trident and spear are really touch and go and a bit weird for a bunch of guys who fly around in spaceships wearing power armor.

The "military vibe" in general I personally feel just doesn't fit in the basically low roleplay reality of TGMC, we're the wacky CM offshoot that has xenos dribbling basketballs while the marine in pink power armor throws knives at a badly drawn silly looking runner, command is never enforced and there's no organization or anything. And all of that's a good thing that gives TGMC it's own special TGMC vibes.

2023-08-11 22:49 UTC, ivanmixo requested changes

2023-08-11 22:49 UTC, ivanmixo commented on code/game/objects/structures/signs.dm
> +	icon = 'icons/obj/flag.dmi'
Why, it's already set

2023-08-14 22:16 UTC, Kuro020 requested changes
elsa why is the flags pinned to the roof

2023-08-24 20:43 UTC, closed without merging