Ghost teleport support/ Medevac timer
tgstation/TerraGov-Marine-Corps pull request #13705
Opened 2023-08-06 16:43 UTC by Redory

## About The Pull Request

Added ghost teleport support for:
- Medevac
- Xeno tunnels
- ASRS teleporter
- Wraith portal
- Shuttle computer

While redoing the medevac linking system i implemented a simple timer onto the medevac roller so you can see the cooldown in realtime in your inventory:
<h5>(No, that is not a stack of medevacs in your hand, i swear!)</h5>

![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/41807890/06b40154-b186-44a2-a83d-172484ce24ca)

Inspecting a medevac beacon also shows the status of the medevac stretchers and who is currently carrying them:
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/41807890/dc2098c9-da16-44e0-a624-08b52778862f)

## Why It's Good For The Game

Ghost man teleport gud.
WASD around and orbiting random people to get to ship/ teleporter bad.
I AM A GHOOOOST AND WISH TO WHOOOSH AROUND FASTER

## Changelog

:cl:
qol: Ghosts can teleport using Medevacs, Xeno tunnels, ASRS teleporters, Wraith portals and Shuttle computers.
qol: Medevac stretchers now have a realtime cooldown on their sprite when in inventory.
qol: Medevac beacons now list all linked stretchers and show their cooldowns.
/:cl:

2023-08-06 19:30 UTC, lbnesquik commented
Does that mean ghosts can click to see where the medivac bed goes?

2023-08-06 20:05 UTC, Redory commented
> Does that mean ghosts can click to see where the medivac bed goes?

yes

2023-08-08 03:51 UTC, ivanmixo requested changes

2023-08-08 03:51 UTC, ivanmixo commented on code/modules/shuttle/marine_dropship.dm
> +	return new observer_state(GLOB.access_state)
Uh.. no new. Look at how the other states are done.

2023-08-08 03:51 UTC, ivanmixo commented on code/game/objects/structures/teleporter.dm
> +	if(!kit || !kit.linked_teleporter)
Replace !kit with !istype(kit) so you get a null check and type check in one.

2023-08-08 03:51 UTC, ivanmixo commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +	if(LAZYLEN(linked_beds + linked_beds_deployed) > 1)
```suggestion
	if(length(linked_beds + linked_beds_deployed) > 1)
```

2023-08-08 03:51 UTC, ivanmixo commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +	if(R && istype(R, /obj/item/roller/medevac))
istype should account for there not being an `R`. Also chill with the single letter var names, make them descriptive.

2023-08-08 03:51 UTC, ivanmixo commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +	desc.maptext = MAPTEXT(display_timer_cooldown)
Add an 's' to it so it's indicative of it being seconds and not it looking like a stack.

2023-08-14 21:12 UTC, ivanmixo requested changes
Few minor things left

2023-08-14 21:12 UTC, ivanmixo commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +	if(rollerbed && istype(rollerbed, /obj/item/roller/medevac))
Checking for rollerbed is not necesarry here, just keep the istype check. Same for line 737

2023-08-14 21:12 UTC, ivanmixo commented on code/modules/shuttle/marine_dropship.dm
> +	var/input = tgui_input_list(user ,"Choose a port to teleport to:" ,"Ghost Shuttle teleport" ,destinations ,null, 0)
```suggestion
	var/input = tgui_input_list(user ,"Choose a port to teleport to:", "Ghost Shuttle teleport", destinations, null, 0)
```

2023-08-14 21:12 UTC, ivanmixo commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +		var/input = tgui_input_list(user ,"Choose a medevac to teleport to:" ,"Ghost Medevac teleport" ,destinations ,null, 0)
```suggestion
		var/input = tgui_input_list(user ,"Choose a medevac to teleport to:", "Ghost Medevac teleport", destinations, null, 0)
```

2023-08-14 21:12 UTC, ivanmixo commented on code/modules/xenomorph/xeno_structures.dm
> +		var/input = tgui_input_list(user ,"Choose a tunnel to teleport to:" ,"Ghost Tunnel teleport" ,destinations ,null, 0)
```suggestion
		var/input = tgui_input_list(user ,"Choose a tunnel to teleport to:", "Ghost Tunnel teleport", destinations, null, 0)
```

2023-08-16 21:55 UTC, ivanmixo requested changes

2023-08-16 21:55 UTC, ivanmixo commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
>  /obj/item/roller/medevac/Destroy()
`holder` still needs to be nulled

2023-08-18 18:15 UTC, ivanmixo approved these changes

2023-08-18 18:15 UTC, merged