Blood regen changes
tgstation/TerraGov-Marine-Corps pull request #13751
Opened 2023-08-10 13:49 UTC by Sebbe9123

## About The Pull Request
This pr moves blood regen from just happening very slowly (0.5) when you'd lost blood to now regen based on how much nutrition you have.
at 450 nutrition and up (fat) you regen 1 whole blood per life tick (or whatever blood works in).
250 to 450 nutrition (The green zone) You regen 0.5 per blood tick.
0 to 250 (starve zone) You regen 0.1 blood per blood tick.

## Why It's Good For The Game
It made no sense to ALWAYS regen 0.5 blood per tick no matter how much blood you have lost and randomly lose a LOT of nutrition for no tradeoff.
Now you regen blood based on how much food you have in you, which I believe is how it works on all other servers and lets regenning blood not SOLELY rely on a medic shoving iso and nano in you.

## Changelog

:cl:
refactor: Natural blood regen now regens in tiers based on how much nutrition you have.
/:cl:

2023-08-11 22:47 UTC, ivanmixo commented
Why did you mark this as a refactor

2023-08-12 14:26 UTC, QualityVan requested changes
This isn't really a refactor, but I do like this on a basic level. Always sort of weird how it works right now. It does in a certain sense add an incentive to being fat, but I really can't see that outweighing the drawback of the slowdown.

2023-08-12 14:26 UTC, QualityVan commented on code/modules/mob/living/blood.dm
> +				if(450 to INFINITY)
Use the NUTRITION_OVERFED defines for these, since those're the thresholds you're keying off anyway.

2023-08-12 14:37 UTC, Sebbe9123 commented
> This isn't really a refactor, but I do like this on a basic level. Always sort of weird how it works right now. It does in a certain sense add an incentive to being fat, but I really can't see that outweighing the drawback of the slowdown.

I'm trying to work out a similar solution to nutrition levels as blood has when you go over the "maximum" limit. It strongly resonates within me in a wrong way that you can have infinite nutrition, and i strongly believe that the "fat slowdown" really does not fit for our gameplay, nor is it a mechanic anyone likes and punishes new people. 
As for the requested changw i'll do it when i'm back home, spending the weekend at my brother's watching his dog while he is at a wedding.

2023-08-14 21:01 UTC, ivanmixo approved these changes

2023-08-14 21:18 UTC, merged

2023-08-15 02:45 UTC, Xander3359 commented
And just like that, a day of improvement for the TerraGov Marine Corps. A day where, the maintainers choose to smile upon us, for they witness our pain and provide our salvation. 
The blessed kings of the codebase have freed us from this pain, this starvation, this decay, this miserable existence.
They have decreed "Thee shalt not starve from bloodloss in vain" and "Thou shalt heal blood from your nutrition levels"

The marine force is happy now, for all 2 nanite users are now no longer starving ungas, passing out in the field, they are now fatmaxxing MREs for the rest of eternity.
I envy them, a simple existence in bliss, unawares of the battles that took place in this PR, benefitting happily from a change they will not ever know has happened. But I do not hate them, for they are happier, and one must take pride in knowing they are capable of spreading joy to the people.