Un-unfuns blood regen and adds more to it
tgstation/TerraGov-Marine-Corps pull request #13801
Opened 2023-08-15 09:27 UTC by Sebbe9123

## About The Pull Request
Makes some adjustments to blood regen by making it 3 tiered based on your levels of blood.

## Why It's Good For The Game
The previous iteration made you starve when you went below 90% to regen your blood and players reported that it wasn't very fun. This aims to make the regen better when you are near full blood. It also makes blood regen better when you are close to death but with small amounts of tox.

## Changelog

:cl:
balance: Rebalances blood regen to be more player friendly above 90%
balance: Adds a tier below 50% blood to quickly bring you above 50%
/:cl:

2023-08-15 19:10 UTC, chizzy376 commented
> It also makes blood regen better when you are close to death but with small amounts of tox.

So if I'm correctly reading this, you're going to die faster if you are already dying? Why is this a good idea? I didn't know donating blood irl was poisoning me all this time

2023-08-16 19:28 UTC, ivanmixo approved these changes

2023-08-18 03:57 UTC, QualityVan requested changes

2023-08-18 03:57 UTC, QualityVan commented on code/modules/mob/living/blood.dm
> +			if(BLOOD_VOLUME_SURVIVE to BLOOD_VOLUME_OKAY)
The toxloss from this is very high, and low blood already has damage applications innately. Beyond that, I'm not convinced that dividing nutrition effects between low and very low blood is helpful either for comprehension or gameplay. The safe to normal buffer zone and base regen is good and should address the main issue.

2023-08-18 03:57 UTC, QualityVan commented on code/modules/mob/living/blood.dm
> +			if(BLOOD_VOLUME_OKAY to BLOOD_VOLUME_SAFE) //Regens blood from 50% ish to 90% using nutrition.
OKAY is 60% of normal.

2023-08-18 08:41 UTC, QualityVan approved these changes

2023-08-21 02:51 UTC, ivanmixo commented
Seems okay

2023-08-21 02:51 UTC, merged