Bench pressing makes you not fat anymore.
tgstation/TerraGov-Marine-Corps pull request #13821
Opened 2023-08-18 15:30 UTC by Xander3359

## About The Pull Request
If you bench press you become not fat.

## Why It's Good For The Game
Credit akimomi on discord:
"Fat slowdown isn't a good mechanic, it's not enjoyable for marines and doesn't add anything to the game except as a way to punish new players for eating food and people taking advantage of the ability to have infinite nutrition.
It doesn't fit for TGMC."

Someone then said lifting should remove fat so here we go.

## Changelog

:cl:
add: Bench press is a great way to lose weight
/:cl:

2023-08-18 15:31 UTC, novaepee commented
![6ddcbadb2d44d8bf721421eee37c655071af6a9e943c1507f2365965d7cee9e2](https://github.com/tgstation/TerraGov-Marine-Corps/assets/6610922/df736246-54b0-4088-87c5-865b19905612)

2023-08-18 15:47 UTC, FIXTHERADBOXPLEASE commented
Can confirm this works in real life too.

2023-08-19 08:06 UTC, QualityVan approved these changes
I'm wondering if this'd fit better with a flat reduction instead of immediate drop to cap, but that's nitpicking and it's fine as is.

2023-08-20 09:19 UTC, TiviPlus requested changes

2023-08-20 09:19 UTC, TiviPlus commented on code/game/objects/structures/benchpress.dm
> +		finishmessage = pick("You no longer feel overweight.","You clothes are no longer too tight.","YOU BECOME LESS FAT!")
Why are you setting instead of using nutrition

2023-08-30 16:18 UTC, merged