Add Hotaru armor, another Japanese-Inspired Armor
tgstation/TerraGov-Marine-Corps pull request #13864
Opened 2023-08-23 20:39 UTC by novaepee

## About The Pull Request

![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/6610922/521aac54-807e-4be0-9f44-f10851fa9c40)

MAGENTA
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/6610922/e8707df1-4676-4c89-889c-7c1cbbe8d131)

![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/6610922/6b74788e-f46f-4069-b006-73f6c6193416)

## Why It's Good For The Game

More armor! Permission from ilikesaying but Griffer-249 to port this armor to TGMC.

## Changelog

:cl: novaepee, OrcaOrca the spriter
add: Add Hotaru armor, another Japanese-Inspired Armor! find it in the style line tab!
/:cl:

2023-08-23 21:55 UTC, Kuro020 approved these changes
I'm not pink, I'm 100% MAGENTA

2023-08-24 00:11 UTC, ilikesaying commented
It's Riotrooping time
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/65475697/ef3675e0-a624-4b62-8ea0-1098cfde3c2b)

2023-08-27 03:51 UTC, Lumipharon commented on code/game/objects/machinery/vending/marine_vending.dm
> -			/obj/item/clothing/head/modular/marine/ranger = -1,
wuh?

2023-08-27 08:33 UTC, TiviPlus requested changes
Gelida changes?
Baneling?
I think you may have broken some stuff

2023-08-27 17:58 UTC, novaepee commented
my git got fucked

2023-08-27 17:58 UTC, closed without merging