2 more new tadpoles
tgstation/TerraGov-Marine-Corps pull request #13898
Opened 2023-08-29 02:04 UTC by XANAv2

## About The Pull Request
This is my second rendition of what i was planning now that the tadpoles are in, many of these ideas i have heard from players in-game in Valhalla, in occ, and more.

Pirate Tad: the spiritual successor to the Viking tad, except now with metal plating underneath the wood facade, comes with six cannons (mounted rocket launchers) constricted in 6 corridors, and 6 individually controllable blast doors that act as gun ports. 30 rounds of ammo, pirate outfits for 8 crewmembers, 4 harpoons, 2 meson eyepatches, 2 health hud eye patches in addition to a parrot that will probably get in the way. (Note the cannons not attaching in the editor means they may not function as intended.)

![_pirate](https://github.com/tgstation/TerraGov-Marine-Corps/assets/93561523/542e87be-713e-433c-b138-3fd7c8d80b9d)

Helicopter Tad: One player recently wanted this one, I modeled it after a Huey, it has 2 "door gun" mounts to compensate for its lack of sentry guns. Let me know if nudging the gun mounts has any unintended effects. 

![_huey](https://github.com/tgstation/TerraGov-Marine-Corps/assets/93561523/d857cba6-435b-4fa0-8df0-487be9cfdd0a)

This would have been 6 if i knew how to code, specifically, modify the code of vendors so the fifth and sixth tad may come later.
## Why It's Good For The Game
More options for, tad piolets, for more variety in tactics and strategies. 
🆑
2 more tadpoles added
pirate tad
helicopter tad
/🆑

2023-08-29 02:48 UTC, XANAv2 commented
> All of these look dreadful. Seriously chill out with the hard points, 3 is already really really pushing it. The first one is a clear grief pick yet it's not marked as admin only.

We shall see, i may remove 3 of the 7 mortars and hard points i was originally going for 4 but symmetry was a problem i also may position the hard points to prevent them from being used for anything other than mortars effectively. 

Additionally, I think a 3 by 3 tad is very good, many of the drawbacks i have found when tadding are the lack of landing zones, in heavily walled-up areas, or the inability to fit in certain areas to deploy marines that you normally wouldn't be able to do.

2023-08-29 02:58 UTC, Lumipharon commented
Yeah please no more hardpoint spam ones. The existing triple one is only not broken due it being super narrow

2023-08-30 07:45 UTC, iforgotmeword commented
All of the Tads seem busted or in some way bad Let go one by one 

Compact Tad:
you do know the primary downside to Tad is Mazes (a̶n̶d̶ ̶m̶a̶p̶p̶e̶r̶s̶) and TAD overall is borderline OP it's just most people don't know how to use it. the 3X3 tad removes the ONLY counter to tad being mazes so that already OP there is a reason pill wasn't added it wasn't because it was meme it was because it was BUSTED.

there is no fixing this one it just too OP

Pirate Tad:
6 hardpoints... no just no that is dumb and the placement sucks the angle of fire is useless
And the size is just too big to be of any kind of use It's a 12X8 that IS BIG the biggest tad right now is the huller and is at 8X9
On top of that mounted rocket launchers? that is just too much for a round start
Also that many hull walls?

![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/101154175/2e4e5ef0-f295-47b4-bf96-fbb37b03abde)
(I think something like this would be better to make up for the round-start weapons the tad doesn't have any hull)

Helicopter Tad:
too big simple as. 11X7 is too hard to land
And the tail is just a bad idea 
as well it doesn't do anything different from the other Tads. The normal tad is the smallest, the carrier has a lot of hulls and a door, the big tad is big, and combat has no walls... what does this tad do? if you want size the big does it better and so on

Mortar Tad:
While yes the mortar hard points have been nerfed hard It's still 4 mortars **ROUND START** 
if the OG mortar hardpoint was OP at 1 round start 4 is roundstart is bad

2023-08-30 17:49 UTC, XANAv2 commented
> ![image](https://user-images.githubusercontent.com/101154175/264265200-2e4e5ef0-f295-47b4-bf96-fbb37b03abde.png) (I think something like this would be better to make up for the round-start weapons the tad doesn't have any hull)
>
was also planning on an 8 by 12 requisitions tad with a similar idea in mind, accept **I need help with vender coding**.
also, Comisar swords are actually very powerful if you can get a hit in, additionally, however I would probably make it thinner as i double walled them for a reason, Xenos can easily screw over wood walls. I know it's a proof of concept however and I appreciate that. 

Helicopter Tad:
too big simple as. 11X7 is too hard to land
And the tail is just a bad idea
as well it doesn't do anything different from the other Tads. The normal tad is the smallest, the carrier has a lot of hulls and a door, the big tad is big, and combat has no walls... what does this tad do? if you want size the big does it better and so on

A fair criticism I could shorten the tail down, probably will. originally it was to make it a bit harder to advantageously bring the 2 weapon mounts. to bare. it was meant to be a balance between marine carry capacity and firepower.

Compact Tad:
you do know the primary downside to Tad is Mazes (a̶n̶d̶ ̶m̶a̶p̶p̶e̶r̶s̶) and TAD overall is borderline OP it's just most people don't know how to use it. the 3X3 tad removes the ONLY counter to tad being mazes so that already OP there is a reason pill wasn't added it wasn't because it was meme it was because it was BUSTED.

there is no fixing this one it just too OP

You say that now until it is gassed by a defiler, boiler, or primo spitter.  all those clumped together marines and piolets in one space, additionally the crusher can just sail through the middle and kill everybody. How about a cheeky warlocks harassing it, or a king just firing its laser through the center killing everybody or doing its piercing AOE.   If you think ahead oh dear god the behemoth, more funny piercing AOE.  It's a high-risk high reward tad, the reward is, you can better get around the map and reach spots you normally couldn't and deploy marines. the risk is, you and your numerous marine cargo may perish if under heavy attack from certain casts.

2023-08-31 00:53 UTC, pilotmans commented
All of these tads are quite cool in my opinion with questionable practicality, though the helicopter tad would be a bit better if shrunk down a bit and made a "Tad" narrower.

2023-08-31 03:05 UTC, XANAv2 commented
> All of these tads are quite cool in my opinion with questionable practicality, though the helicopter tad would be a bit better if shrunk down a bit and made a "Tad" narrower.
> 
> This Heli-Tad also kind of reminds me of this PR: #11783

Wow never knew pr:11783 existed 

also i probably could do that.

2023-08-31 03:40 UTC, pilotmans commented
> 

That was quick!

2023-08-31 15:42 UTC, XANAv2 commented
I try to actively work on my pr's. Check every morning and evening

2023-09-01 15:03 UTC, iforgotmeword commented
The heli tad looks a lot better but I still think the tail is a problem (seeing it’s a hull) and makes about the same as combat

2023-09-01 20:56 UTC, XANAv2 commented
> The heli tad looks a lot better but I still think the tail is a problem (seeing it’s a hull) and makes about the same as combat

The hull is meant to add additional defenses and the tail is ascetic, but it would lose its helicopter look if you removed it, the only way I could see to fix it would be to use a 3 by 3 tail sprite work decal like the landing jets, helicopter Rotar blades that spin on the sides of it.  If you have any solutions to that problem I could use now and not need to fix later when i learn how to code better i would love to hear them.

2023-09-02 05:38 UTC, zzurge commented
Based

2023-09-03 09:39 UTC, mc-oofert commented
personally i think this is fucking hilarious because this is what i made the system for
tgmc is still a silly crayoneater vs stun machine game and trying to stay serious with the code failed like 1 year ago

2023-09-03 09:41 UTC, mc-oofert commented
> All of these look dreadful. Seriously chill out with the hardpoints, 3 is already really really pushing it. The first one is a clear grief pick yet it's not marked as admin only.

someone hates fun

also whoever added the gimmick tad admin toggle isnt fit for playing ss13 to begin with

2023-09-03 18:53 UTC, XANAv2 commented
> > All of these look dreadful. Seriously chill out with the hardpoints, 3 is already really really pushing it. The first one is a clear grief pick yet it's not marked as admin only.
> 
> someone hates fun
> 
> also whoever added the gimmick tad admin toggle isnt fit for playing ss13 to begin with

My thoughts exactly, I would probably be playing on Bee Station if I wasn't able to do crazy shit like this. I have more entertaining ideas as well, just need a person to teach me how to code.

2023-09-04 03:28 UTC, ivanmixo commented
1st one is a grief pick, basically pill pole 2 (which was denied mind you)

2nd one has way too many hardpoints and gives a bunch of costly equipment (the hardpoint RRs) for absolutely free.

3rd is.. fine. Might be okay as a sidegrade to standard, but good luck landing it. People will get fished like hell if they dare to mount the guns on that thing so that balances out it having two hardpoints I suppose.

4th has too many hardpoints and too much free shit. I get you intend them for a mortar but if you stuck guns onto the hardpoints it'd be basically unattackable if you had people man two of the guns, not to mention it being a complete upgrade to the carrier tad.

Overall not a fan of the gamer gear you intend on putting on tad for free, tad models should really be able to stand on their own without having to give them roundstart gear. I get gimmick tads but it's a bit much considering how important tadpole is currently for the way rounds flow.

Oh you also deleted the changelog for some reason in the PR template. Put that back.

2023-09-04 04:33 UTC, mc-oofert commented
> 1st one is a grief pick, basically pill pole 2 (which was denied mind you)

1984 no fun allowed

2023-09-04 04:34 UTC, mc-oofert commented
hey maybe you should fix the shuttle system so the shuttle manipulator works and that wouldnt be an issue

2023-09-04 16:05 UTC, XANAv2 commented
> 1st one is a grief pick, basically pill pole 2 (which was denied mind you)
Actually, has purpose, as i mentioned in a previous comment its squishy for a tad, yet powerful as it basically makes the tad able to access areas it's not supposed to. 
> 
> 2nd one has way too many hardpoints and gives a bunch of costly equipment (the hardpoint RRs) for absolutely free.

There are 6 hardpoints limited in firing angle, the walls are unbreakable so marines can't just plasma cutter them. 

> 3rd is.. fine. Might be okay as a sidegrade to standard, but good luck landing it. People will get fished like hell if they dare to mount the guns on that thing so that balances out it having two hardpoints I suppose.

I actually nudged the gun mounts an insane amount, as an experiment, so depending on how it works, you could be safely remotely controlling the gun from a safe distance where the gun mount actually is or you could be stuck to the gun, just depends on how it's coded.

> 
> 4th has too many hardpoints and too much free shit. I get you intend them for a mortar but if you stuck guns onto the hardpoints it'd be basically unattackable if you had people man two of the guns, not to mention it being a complete upgrade to the carrier tad.
I fixed the mortar tad (it has 4 mortar pods for symmetry), however I made most weapons besides mortars useless, as I put unbreakable walls between them, which will cause weapons to ether spawn in, in a direction they can't be used, or lock the gunner out when they get hit by a stagger/ the tad moves and are fazing through the walls making them extremely uncomfortable to use. 
> 
> Overall not a fan of the gamer gear you intend on putting on tad for free, tad models should really be able to stand on their own without having to give them roundstart gear. I get gimmick tads but it's a bit much considering how important tadpole is currently for the way rounds flow.
> 
> Oh you also deleted the changelog for some reason in the PR template. Put that back. (do i need to open a pr just to get them, eh ill just copy another one)

2023-09-04 16:06 UTC, XANAv2 commented
> hey maybe you should fix the shuttle system so the shuttle manipulator works and that wouldnt be an issue

not sure how to

2023-09-04 16:34 UTC, mc-oofert commented
> > hey maybe you should fix the shuttle system so the shuttle manipulator works and that wouldnt be an issue
> 
> not sure how to

that wasnt meant towards you that was meant towards the other nerd

2023-09-04 22:10 UTC, XANAv2 commented
> > > hey maybe you should fix the shuttle system so the shuttle manipulator works and that wouldnt be an issue
> > 
> > 
> > not sure how to
> 
> that wasnt meant towards you that was meant towards the other nerd

Oh!

2023-09-13 01:10 UTC, Tailiik commented
> I fixed the mortar tad (it has 4 mortar pods for symmetry), however I made most weapons besides mortars useless, as I put unbreakable walls between them, which will cause weapons to ether spawn in, in a direction they can't be used, or lock the gunner out when they get hit by a stagger/ the tad moves and are fazing through the walls making them extremely uncomfortable to use.

"Balancing" something excessive by making it just...cease to work when something very commonplace happens to it is stupid as fuck. Like, you don't even need to get stunned by a xeno to make the gooby 4brazillion hardpoints turret not function, just get shuffled or move off of it without rotating it to be able to be mounted again? Whar

"It has 4x as many hardpoints as the original but it's fine because if you press the wrong directional key you have to use a ripley to fix it" W h a r r r r (arrrrrrrr pirate tad joke)

2023-09-14 20:04 UTC, XANAv2 commented
> > I fixed the mortar tad (it has 4 mortar pods for symmetry), however I made most weapons besides mortars useless, as I put unbreakable walls between them, which will cause weapons to ether spawn in, in a direction they can't be used, or lock the gunner out when they get hit by a stagger/ the tad moves and are fazing through the walls making them extremely uncomfortable to use.
> 
> "Balancing" something excessive by making it just...cease to work when something very commonplace happens to it is stupid as fuck. Like, you don't even need to get stunned by a xeno to make the gooby 4brazillion hardpoints turret not function, just get shuffled or move off of it without rotating it to be able to be mounted again? Whar
> 
> "It has 4x as many hardpoints as the original but it's fine because if you press the wrong directional key you have to use a ripley to fix it" W h a r r r r (arrrrrrrr pirate tad joke)

Yea i removed that and compact as i wana get this pr through, mostly because i just learned how to make a new vendors, so i can finally make a new pr for those. 2 to 3 tads

2023-09-16 22:46 UTC, XANAv2 commented
I am currently working on fixing some of the tads such as how the helicopter tad has no back end to it or how its missing its top

2023-09-17 13:48 UTC, mrhugo13 commented
![dreamseeker_2023-09-17_15-48-21](https://github.com/tgstation/TerraGov-Marine-Corps/assets/17747087/9ab66b61-d1f0-4f0b-9632-c7e19b8911bb)

Currently trying to deploy the heli tad on arachne looks like this

2023-09-17 17:22 UTC, Mannybrado commented
why god

2023-09-18 02:25 UTC, RipGrayson requested changes
Helicopter tad appears to be entirely broken in game, needs fixed before another TM can be done

2023-10-10 10:48 UTC, TiviPlus commented
@RipGrayson ?

2023-10-22 00:40 UTC, closed without merging