hotaru armor 2.0
tgstation/TerraGov-Marine-Corps pull request #13893
Opened 2023-08-27 18:14 UTC by novaepee

## About The Pull Request

## Why It's Good For The Game

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2023-08-27 18:17 UTC, Kuro020 approved these changes

2023-08-27 18:35 UTC, novaepee commented
on god, i don't understand where the linter is coming from

2023-08-27 18:43 UTC, hyper2snyper requested changes

2023-08-27 18:43 UTC, hyper2snyper commented on code/modules/clothing/modular_armor/attachments/arm_plates.dm
> +obj/item/armor_module/armor/arms/marine/hotaru
```suggestion
/obj/item/armor_module/armor/arms/marine/hotaru
```
This'll fix the linter

2023-08-28 07:40 UTC, ilikesaying commented
**_C O M P L E T E_**

2023-08-29 22:56 UTC, ivanmixo approved these changes
Meme

2023-08-29 22:56 UTC, merged

2023-09-02 21:32 UTC, Tailiik commented
You can't attach the armor pieces to the xm-02 :hampter: