Adds shivs to Prison
tgstation/TerraGov-Marine-Corps pull request #13934
Opened 2023-09-07 00:27 UTC by RipGrayson

## About The Pull Request

Title, it's as simple as that.

## Why It's Good For The Game

Lumi wanted it, now you can shank xenos in dark areas of Prison.

## Changelog

:cl:
add: Added shivs to Prison
/:cl:

2023-09-07 14:07 UTC, ivanmixo requested changes

2023-09-07 14:07 UTC, ivanmixo commented on code/game/objects/items/weapons/blades.dm
> +/obj/item/weapon/knife/shiv
This path is fucked up, `/obj/item/weapon/knife` doesn't exist. So you're defining it along with this. Suggest a repath to `/obj/item/tool/kitchen/knife/shiv`.

2023-09-07 14:07 UTC, ivanmixo commented on code/game/objects/items/weapons/blades.dm
> +	sharp = IS_SHARP_ITEM_ACCURATE
Repath also makes this line unnecesarry.

2023-09-07 15:41 UTC, ivanmixo approved these changes

2023-09-08 14:13 UTC, Sirsnek15 commented
do they accept pistol laces?

2023-09-08 21:43 UTC, merged