Gun Smoke Particles
tgstation/TerraGov-Marine-Corps pull request #13963
Opened 2023-09-16 15:41 UTC by tyeagg

## About The Pull Request
when you fire gun smoke come out

https://github.com/tgstation/TerraGov-Marine-Corps/assets/98577688/41aa6b1d-5af0-40c6-9d37-4d3c79c33dee

## Why It's Good For The Game
looks cool

## Changelog

:cl:
add: smoke particles for gun firing
/:cl:

2023-09-16 16:49 UTC, novaepee commented
TGMC: The Woo Edition

![tumblr_n2v3gbDdnT1sgrxw6o1_500-4208352554](https://github.com/tgstation/TerraGov-Marine-Corps/assets/6610922/98f7615d-7f94-425e-9bc3-835dbd2266a5)

2023-09-16 16:55 UTC, yyzsong commented
Please do not make firefights even more of a headache than they usually are.

2023-09-16 21:08 UTC, Kuro020 approved these changes
Speedmerge or @TiviPlus is cringe

2023-09-18 10:05 UTC, Lumipharon requested changes
Why do energy weapons have this?

2023-09-18 10:05 UTC, Lumipharon commented on code/modules/projectiles/guns/grenade_launchers.dm
> +	flags_gun_features = NONE|GUN_SMOKE_PARTICLES
bruh

2023-09-18 21:24 UTC, Lumipharon commented
It looks weird if you're shooting while moving, since the player sprite moves smoothly but the gun smoke will appear on their actual tile (i.e. the gun smoke will appear in front of you).

2023-09-18 22:14 UTC, AzonStarfall commented
Looks really nice, but how will this hold up stability-wise when we have 50+ marines on a highpop round all spraying additional particles? Would the effects be minimal?

2023-09-19 02:00 UTC, iforgotmeword commented
is this server sided?
if yes: time dilation goes BRRRRRRRRRRRRRRR

2023-09-19 04:57 UTC, tyeagg commented
> is this server sided? if yes: time dilation goes BRRRRRRRRRRRRRRR

particles are like the very few things that byond has rendered clientside and also multicore, the only thing server side is the objects that hold the particle

2023-09-19 21:31 UTC, lbnesquik commented
Test merge for performance

2023-09-23 18:04 UTC, TiviPlus approved these changes

2023-09-26 23:06 UTC, merged