Adds Omni-Phero towers to crash
tgstation/TerraGov-Marine-Corps pull request #14264
Opened 2023-10-24 17:59 UTC by Xander3359

## About The Pull Request
Phero towers on crash emit all 3 pheremones at a greater range.

## Why It's Good For The Game
After the addition of phero towers, xenos still struggle a lot in crash due to the typical lack of a Queen.
While this won't necessarily help xenos contest most disks, it will surely aid them a lot when it comes to getting fog camped.

## Changelog

:cl:
add: Pheremone towers on crash emit all 3 types at a wider range.
/:cl:

2023-10-24 18:32 UTC, DeltaFire15 commented
Isn't this basically mapwide queen tier phero of all types, given crash silos are distributed over the map and 48 is a HUGE radius? Seems very scuffed for marines to go against.

2023-10-24 18:35 UTC, Xander3359 commented
> Isn't this basically mapwide queen tier phero of all types, given crash silos are distributed across the map and 48 is a HUGE radius? Seems very scuffed for marines to go against.

Currently the range will rarely go outside of caves.
I could leave the range as it was before (which was 32), but yeah it's basically Queen pheros of all types when near a silo.

2023-10-25 03:06 UTC, Joe13413 commented
yo uh what the fuck is this
you gotta remember that level 6 warding is +15 soft armor in ALL categories
and level 6 frenzy is about -0.3 to -0.4 slowdown
those are some pretty insane buffs, and i don't really think max level pheros should be basekit

2023-10-25 07:18 UTC, Xander3359 commented
> those are some pretty insane buffs, and i don't really think max level pheros should be basekit

And I don't think marines should  be able to easily camp fog because xenos have to 4 xenos compared to the 15 marines holding all the 2-tile hallways going in/out of silo.

2023-10-31 01:24 UTC, Kuro020 approved these changes

2023-11-04 16:16 UTC, Breadeagle commented
Silo camps can be truly fucked up because the structures inside fog aren't actually immune to explosives. If the tunnel is destroyed xenos can't actually get out without fighting past. In fact this change might miss the fact that structures are destructible but not rebuildable. The pheromone coverage is probably fine but some maps have way better or worse coverage than others. Probably effects small maps a lot more favourably but given that one of them is Orion, which is super marine sided, eh. 

As Closetedskeleton mentions, caste coverage can be really bad due to crash being low pop. They're not likely to even have weeds or walls, much less pheromones.

2023-11-11 12:48 UTC, psykzz requested changes

2023-11-11 12:48 UTC, psykzz commented on code/modules/xenomorph/xeno_structures.dm
> +	current_aura = SSaura.add_emitter(src, AURA_XENO_FRENZY, aura_radius, aura_strength, -1, FACTION_XENO, hivenumber)
+1 for this we need to ensure towers can hold multiple emitters

2023-11-11 12:48 UTC, psykzz commented on code/modules/xenomorph/xeno_structures.dm
> +	return X.balloon_alert(X, "Cannot change") //We're already emitting all the pheros.
The return of balloon_alert shouldn't be returned here.
We should `return FALSE`, to ensure no other action is performed.

2023-11-11 13:55 UTC, Xander3359 commented
After some discussion on discord, this is just a band-aid fix for a fundamentally broken gamemode.
I'm closing this PR because I don't think this actually solves any real issues that the mode has.

2023-11-11 13:55 UTC, closed without merging