Larva Queue: Now while playing Minions
tgstation/TerraGov-Marine-Corps pull request #14262
Opened 2023-10-24 08:32 UTC by ZeWaka

## About The Pull Request
Per the [xeno rework design doc](https://hackmd.io/@uckgLKizQP6QNGj1w6mHQg/r14h9qS9h), people should be able to play as minions while waiting in the larva queue:
> Prospective xeno players can play as a minion while waiting.

**STILL WIP I JUST DRAFTED THIS FOR NOW OKAY**
It '''should''' work I just need to fix the bindings gosh

https://github.com/tgstation/TerraGov-Marine-Corps/assets/4741640/09b395dd-5c18-44cc-888c-8906397b1382

## Why It's Good For The Game

~~Gives me more opportunities to harass marines 24/7~~

Allows xeno players to not be stuck around twiddling their thumbs while malding over dying to busted wallhack lasers
Don't interrupt the flow of gameplay for new players so they don't go 'aw shucks' and leave

## Changelog

:cl:
add: You can now continue to wait in/join the xeno larva queue while playing as a minion
/:cl:

2023-10-24 12:01 UTC, vilereaver41 commented
awesome!

2023-10-27 18:40 UTC, ZeWaka commented on code/modules/mob/login.dm
> +	canon_client = client
This was actually missing from a tg port, this should hopefully help with client logout cleanup since it can actually clean up now.

2023-10-28 21:12 UTC, TiviPlus requested changes
rest lgtm

2023-10-28 21:12 UTC, TiviPlus commented on code/datums/components/larva_queue.dm
> +	src.action = new
```suggestion
	waiter = client
	action = new
```
redundant

2023-10-28 21:12 UTC, TiviPlus commented on code/datums/components/larva_queue.dm
> +	. = ..()
```suggestion
	waiter = null
	QDEL_NULL(action)
	return ..()
```

2023-10-28 21:12 UTC, TiviPlus commented on code/datums/components/larva_queue.dm
> +		return TRUE
etc

2023-10-28 21:12 UTC, TiviPlus commented on code/datums/gamemodes/_game_mode.dm
> +/datum/game_mode/proc/handle_collapse_timer(datum/dcs, mob/source, list/items)
autodoc

2023-10-28 21:12 UTC, TiviPlus commented on code/modules/mob/login.dm
> +	SEND_SIGNAL(src.client, COMSIG_CLIENT_MOB_LOGIN)
```suggestion
	SEND_SIGNAL(client, COMSIG_CLIENT_MOB_LOGIN)
```

2023-10-28 21:12 UTC, TiviPlus commented on code/modules/mob/logout.dm
> +		SEND_SIGNAL(src.canon_client, COMSIG_CLIENT_MOB_LOGOUT, src)
```suggestion
	if (canon_client)
		SEND_SIGNAL(canon_client, COMSIG_CLIENT_MOB_LOGOUT, src)
```

2023-10-29 00:14 UTC, ZeWaka commented on code/datums/components/larva_queue.dm
> +	src.action = new
waaa iTs MoRe cLeAR
(ok will do later)

2023-10-29 06:13 UTC, ZeWaka commented on code/datums/gamemodes/_game_mode.dm
> +// Displays the orphan hivemind collapse timer, if applicable
```suggestion
/// Displays the orphan hivemind collapse timer, if applicable
```

2023-10-29 08:36 UTC, TiviPlus commented on code/datums/gamemodes/_game_mode.dm
> +		src.handle_xeno_respawn_timer(dcs, source, items)
```suggestion
	if (isobserver(source) || isxeno(source))
		handle_collapse_timer(dcs, source, items)

	if (source.can_wait_in_larva_queue())
		handle_larva_timer(dcs, source, items)
		handle_xeno_respawn_timer(dcs, source, items)
```

2023-10-29 08:36 UTC, TiviPlus commented on code/datums/gamemodes/_game_mode.dm
> +			items += "Burrowed larva: [stored_larva]"
```suggestion
	if(!(flags_round_type & MODE_INFESTATION))
		return
	var/larva_position = SEND_SIGNAL(source.client, COMSIG_CLIENT_GET_LARVA_QUEUE_POSITION)
	if (larva_position) // If non-zero, we're in queue
		items += "Position in larva candidate queue: [larva_position]"

	var/datum/job/xeno_job = SSjob.GetJobType(/datum/job/xenomorph)
	var/stored_larva = xeno_job.total_positions - xeno_job.current_positions
	if(stored_larva)
		items += "Burrowed larva: [stored_larva]"
```

2023-10-29 20:38 UTC, lbnesquik commented
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/24830358/58591f17-a12f-4515-b38e-3887f924476c)
Man hard at work

2023-11-03 09:28 UTC, merged