Ports the CM Canister pouch
tgstation/TerraGov-Marine-Corps pull request #14308
Opened 2023-10-28 13:24 UTC by Xander3359

## About The Pull Request
This adds the Reagent Canister Pouch.
It's a pouch with an inner reagent storage container, and a hypo that refills from the inner storage.
By default, it holds 1200u of BKTT which is the equivalent of 5 pill bottles, and the 60u Hypospray.

## Why It's Good For The Game
Ports a cool feature from CM. Very cool toy to have.

## Changelog

:cl:
add: Port the CM Reagent Canister Pouch
/:cl:

2023-10-28 13:31 UTC, Alexeivichi commented
My name is Aleksey and I support this.

2023-10-28 14:07 UTC, Kuro020 requested changes
>CM sprite
At least be a decent coder and beat up Orca for a sprite

2023-10-28 14:47 UTC, Tommy-211 commented
This is huge

2023-10-28 18:30 UTC, BonkaiB commented
Pogu

2023-10-30 00:11 UTC, ButterChugger commented
Speed merge

2023-10-31 01:24 UTC, Kuro020 approved these changes

2023-10-31 09:47 UTC, TiviPlus requested changes
Even after you rewrote it you still wouldve been faster just redoing it from scratch lol

2023-10-31 09:47 UTC, TiviPlus commented on code/game/objects/items/storage/reagent_pouch.dm
> +		. += examine_info
```suggestion
	. += get_examine_info(user)
```

2023-10-31 09:47 UTC, TiviPlus commented on code/game/objects/items/storage/reagent_pouch.dm
> +		return "You don't know what's in it."
early returns

2023-10-31 09:47 UTC, TiviPlus commented on code/game/objects/items/storage/reagent_pouch.dm
> +	overlays.Cut()
use images + update overlays properly

2023-10-31 09:47 UTC, TiviPlus commented on code/game/objects/items/storage/reagent_pouch.dm
> +		return FALSE
usr when you have user

2023-10-31 09:47 UTC, TiviPlus commented on code/game/objects/items/storage/reagent_pouch.dm
> +	if(istype(held_item, /obj/item/reagent_containers/hypospray))
more early trurns

2023-10-31 09:47 UTC, TiviPlus commented on code/game/objects/items/storage/reagent_pouch.dm
> +		. += display_info
```suggestion
	. += display_contents(user)
```

2023-10-31 09:47 UTC, TiviPlus commented on code/game/objects/items/storage/reagent_pouch.dm
> +		return "You don't know what's in it."
more early returns

2023-10-31 23:29 UTC, BraveMole requested changes

2023-10-31 23:29 UTC, BraveMole commented on code/game/objects/items/storage/reagent_pouch.dm
> +	for(var/datum/reagent/R in reagents.reagent_list)
You can probably use as in

2023-10-31 23:29 UTC, BraveMole commented on code/game/objects/items/storage/reagent_pouch.dm
> +		for(var/datum/reagent/R in inner.reagents.reagent_list)
AS

2023-11-03 09:25 UTC, TiviPlus approved these changes
rest lgtm

2023-11-03 09:25 UTC, TiviPlus commented on code/game/objects/items/storage/reagent_pouch.dm
> +	return ..()
early returns
tochat does not return anything

2023-11-07 19:47 UTC, ivanmixo requested changes

2023-11-07 19:47 UTC, ivanmixo commented on code/game/objects/items/storage/reagent_pouch.dm
> +	return span_notice("[src]'s contains: [dat.Join(" ")]")
`pressurized reagent container's contains:` ?

2023-11-07 19:47 UTC, ivanmixo commented on code/game/objects/items/storage/reagent_pouch.dm
> +		return span_notice("[src] is empty!")
Wouldn't you want it to say it's empty if it's 0 too? Just do `!reagents.total_volume`

2023-11-07 19:47 UTC, ivanmixo commented on code/game/objects/items/storage/reagent_pouch.dm
> +	var/obj/item/reagent_containers/glass/reagent_canister/inner
Harddel. Make sure this is qdel_nulled in destory

2023-11-07 19:47 UTC, ivanmixo commented on code/game/objects/items/storage/reagent_pouch.dm
> +	if(contents.len > 0)
```suggestion
	if(length(contents) > 0)
```

2023-11-07 19:47 UTC, ivanmixo commented on code/game/objects/items/storage/reagent_pouch.dm
> +///Removes the reagent canister from the pouch. Returns FALSE if there is no canister to remove
```suggestion
///Attempts to remove the reagent canister from the pouch. Returns FALSE if there is no canister to remove
```

2023-11-07 19:47 UTC, ivanmixo commented on code/game/objects/items/storage/reagent_pouch.dm
> +		return to_chat(user, span_warning("There already is a container inside [src]!"))
run to_chat then return instead of returning to_chat

2023-11-07 19:47 UTC, ivanmixo commented on code/game/objects/items/storage/reagent_pouch.dm
> +	if(inner.reagents.total_volume == 0)
```suggestion
	if(!inner.reagents.total_volume)
```

2023-11-07 19:47 UTC, ivanmixo commented on code/game/objects/items/storage/reagent_pouch.dm
> +	if(inner.reagents.total_volume > 0)
This will always be true because of the previous if statement

2023-11-07 19:47 UTC, ivanmixo commented on code/game/objects/items/storage/reagent_pouch.dm
> +	if(isnull(inner.reagents.total_volume))
```suggestion
	if(!inner.reagents.total_volume)
```

2023-11-07 19:47 UTC, ivanmixo commented on code/game/objects/items/storage/reagent_pouch.dm
> +/obj/item/storage/pouch/pressurized_reagent_pouch/proc/get_display_contents(mob/user)
Also a thing about this proc, you're returning notices in some of the cases, while not in others. Why? Same thing applies for the other get_display... procs

2023-11-08 20:06 UTC, merged