Adds 3 bottles to NT Med.
tgstation/TerraGov-Marine-Corps pull request #14314
Opened 2023-10-29 18:37 UTC by Xander3359

## About The Pull Request
Adds Tricordrazine, Isotonic and Paracetamol bottles to the NT Med.

## Why It's Good For The Game
These have a packet variant, so it should be fine to add this to the vendor to make chemistry mildly less tedious.

## Changelog

:cl:
add: Tricord, Paracetamol and Isotonic to NTMed
/:cl:

2023-10-31 09:48 UTC, TiviPlus commented
@QualityVan

2023-11-02 15:37 UTC, QualityVan requested changes
Bottle refilling for chem production is awful and I hate it but it's not dead yet so this is fine, none of these chems are particularly likely to be trouble. What's up with the map changes?

2023-11-02 15:37 UTC, QualityVan commented on code/game/objects/items/reagent_containers/glass/bottle.dm
> +	desc = "A small bottle. Contains tricordrazine - used to aid the body in blood restoration."
.

2023-11-02 15:37 UTC, QualityVan commented on code/game/objects/items/reagent_containers/glass/bottle.dm
> +/obj/item/reagent_containers/glass/bottle/isotonic
Given that the reagent shows up as sal-glu and this is (in principle) for use in chemistry, do you want to label it that way instead? I'm fine with either.

2023-11-02 19:39 UTC, RipGrayson approved these changes

2023-11-03 13:45 UTC, QualityVan approved these changes

2023-11-05 09:42 UTC, merged