Makes hiveminds sprite dependent on the type of weed theyre on + new hivemind sprites
tgstation/TerraGov-Marine-Corps pull request #14370
Opened 2023-11-04 00:28 UTC by ClosetedSkeletonGH

## About The Pull Request
**Visual changes:**

**All new sprites/anims:**
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/120620754/40275dba-f02c-4f04-b0cc-805ea24ffae5)

-If hivemind moves onto normal weed/no weeds, it becomes a standard colored hivemind

-If hivemind moves onto sticky weeds, it becomes a sticky hivemind

-If hivemind moves onto resting weeds, it becomes a resting hivemind

-Hivemind remanifesting no longer looks buggy by hivemind moving to face the previous direction post manifesting 
-Hivemind nolonger flickers on demanifestation/remanifestation

Video of visual changes:

https://github.com/tgstation/TerraGov-Marine-Corps/assets/120620754/614fd526-5e43-45a2-8d2d-130ff55a5bcd

(ignore the sliding post manifestation in this vid, ive fixed that)

https://github.com/tgstation/TerraGov-Marine-Corps/assets/120620754/2b4f0634-6834-4962-af33-76cdd0d039a1

https://github.com/tgstation/TerraGov-Marine-Corps/assets/120620754/0abc38ba-8550-468c-bd71-8965353cf24c

**Gameplay changes:**

-Hivemind has had its fast and slow manifestation/demanifestation merged into one because slow demanifestation was flat out ugly and fast tele was too fast. Now tele's are just a standard speed of 1.1 (and 1 second movement prevention)

(this means that hivemind normal demanifestation and remanifestation is slightly slightly faster, but hivemind double click tele and minimap tele is a bit slower, barely noticeable besides looking better)

## Why It's Good For The Game

General sprite improvements that makes the hivemind look significantly cooler, also old hivemind sprite was just 3 colors total, which wasnt bad at all but it was meant for old weeds, not our current weeds
## Changelog
:cl:
add: Hivemind sprite changes depending on the type of weed it is on
balance: Hivemind demanifestation and remanifestation
fix: Hivemind no longer flickers on tele
fix: Hivemind direction of manifestation is normalized

/:cl:

2023-11-04 00:39 UTC, coldironwarrior commented
finally...it's here

2023-11-04 01:43 UTC, aarrisu commented
someone post awoos dog in this pr

2023-11-04 14:45 UTC, lbnesquik commented
Very nice

2023-11-04 20:22 UTC, Kuro020 approved these changes
based

2023-11-05 00:16 UTC, Xander3359 requested changes

2023-11-05 00:16 UTC, Xander3359 commented on code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
> +// handles hivemind updating with their respective weedtype
This isn't autodoc'ed anymore (it needs 3 slashes)

2023-11-05 00:16 UTC, Xander3359 commented on code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
> +		return
If you're gonna early return here, you don't need the else beneath it

2023-11-05 00:16 UTC, Xander3359 commented on code/modules/mob/living/carbon/xenomorph/xenomorph.dm
> +	if(loc_weeds_type == found_weed?.type)
You should check !found_weed on top of what you've got here, instead of using ?

2023-11-05 01:40 UTC, Xander3359 commented on code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
> +		update_icon_state()
```suggestion
		update_icon()
```
You're only supposed to change it in the proc that changes the icon states, not where you're calling it. Update_icon is meant to handle calling update_icon_state for you.

2023-11-05 01:40 UTC, Xander3359 commented on code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
> +/mob/living/carbon/xenomorph/hivemind/update_icon_state()
This is the only place that needed to be changed.

2023-11-05 07:11 UTC, Xander3359 approved these changes

2023-11-05 19:46 UTC, chizzy376 commented
Suggestion for dirt
![poopmind](https://github.com/tgstation/TerraGov-Marine-Corps/assets/80391698/73ce0272-8256-4793-8d0f-4d5681811267)

2023-11-06 21:12 UTC, yyzsong commented
Floating purple eye attack

2023-11-06 22:39 UTC, Lumipharon requested changes

2023-11-06 22:39 UTC, Lumipharon commented on code/game/objects/effects/weeds.dm
> +#define NORMAL_COLOR ""
this should really be like, an actual define, not just a blank. Not sure if you'll need to update anything else to take this into account though.

2023-11-06 22:39 UTC, Lumipharon commented on code/modules/mob/living/carbon/xenomorph/xenomorph.dm
> +		if(!(isnull(loc_weeds_type)))
why are you doing null checks specifically?

2023-11-08 19:58 UTC, Lumipharon requested changes

2023-11-08 19:58 UTC, Lumipharon commented on code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
> +	icon_state = "Hivemind_[initial(loc_weeds_type.color_variant)]"
is this not erroring? loc_weeds_type could be null, couldn't it?

2023-11-09 22:09 UTC, Lumipharon approved these changes

2023-11-09 22:09 UTC, merged

2023-11-09 22:14 UTC, psykzz commented on code/modules/mob/living/carbon/xenomorph/xenomorph.dm
> +	update_icon()
Why is this duplicated?