Cryo directions
tgstation/TerraGov-Marine-Corps pull request #14404
Opened 2023-11-07 21:06 UTC by Lumipharon

## About The Pull Request
Cryo now ejects patients based on the tube's direction.
Normally this is just south, but a couple (iteron and the northern med on ice colony) now face north so you don't get ejected into a wall.

## Why It's Good For The Game
Ejecting into space bad

## Changelog

:cl:
fix: Certain cryo tubes will no longer eject their occupant into a wall
/:cl:

2023-11-07 22:19 UTC, novaepee commented
"this doesn't account for walls or anything, but i don't forsee that being a problem."

![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/6610922/47633608-a2d5-4a58-889c-7d97f0912927)

2023-11-08 01:12 UTC, Kuro020 approved these changes

2023-11-08 01:28 UTC, RipGrayson requested changes
Cryo tubes on Gelida seem to empty into a wall
![gelbase](https://github.com/tgstation/TerraGov-Marine-Corps/assets/49290523/20afac92-85a3-49f3-9d94-e67e92070792)
(I know this isn't technically your fault, but it should be fixed anyway)

2023-11-08 01:45 UTC, Lumipharon commented
> Cryo tubes on Gelida seem to empty into a wall ![gelbase](https://user-images.githubusercontent.com/49290523/281230650-20afac92-85a3-49f3-9d94-e67e92070792.png) (I know this isn't technically your fault, but it should be fixed anyway)

Maps updated

2023-11-08 15:06 UTC, RipGrayson approved these changes

2023-11-08 18:22 UTC, merged