Port VV stuff from TG
tgstation/TerraGov-Marine-Corps pull request #14497
Opened 2023-11-20 11:14 UTC by Xander3359

## About The Pull Request
I've split my head open on a rock trying to get this to work.
WIP
Ports VV stuff from TG

## Why It's Good For The Game
Better admin 👍 

## Changelog

:cl:
admin: Port VV Stuff from TG
/:cl:

2023-11-25 06:14 UTC, vvvv-vvvv requested changes

2023-11-25 06:14 UTC, vvvv-vvvv commented on code/modules/admin/view_variables/topic.dm
> +	if(href_list["Vars"])
you need to change hrefs where it was `vars=` to `Vars=`

2023-11-25 14:11 UTC, Xander3359 commented on code/__DEFINES/vv.dm
> +#define VV_HK_SPIN_ANIMATION "atom_spin" //Unused, from TG
Bit out of scope for now.
There's a lot more TG stuff I want to work on in a followup

2023-11-25 14:12 UTC, Xander3359 commented on code/__HELPERS/_planes.dm
> +// This file contains helper macros for plane operations
I think this was multi-z, which again, I'll probably start working on in a followup

2023-11-25 14:16 UTC, Xander3359 commented on code/__DEFINES/_helpers.dm
> +#define hex2num(X) text2num(X, 16)*/
I did try, I simply don't understand how, and after having asked for help in multiple places, I never really got an answer. I don't know anything about hex so I left it here for someone who is more competent than I to implement it.

2023-12-10 09:46 UTC, TiviPlus commented
fell free to ping me when you need reviews for this btw

2023-12-15 15:16 UTC, ivanmixo requested changes
Good work besides these few things. Would really like it if stuff was autodocced even if you aren't the one who wrote the code, for consistency's sake. (and you're missing a lot of docs here)

2023-12-15 15:16 UTC, ivanmixo commented on code/__DEFINES/_helpers.dm
> +#define TYPEID(thing) copytext(REF(thing), 4, 6)
https://github.com/tgstation/TerraGov-Marine-Corps/blob/e3391cee330686cbacc80eeb32ebedc856dc8f5f/code/__DEFINES/typeids.dm#L5

2023-12-15 15:16 UTC, ivanmixo commented on code/__DEFINES/vv.dm
> +#define IS_VALID_ASSOC_KEY(V) (!isnum(V)) //hhmmm..
Whar

2023-12-15 15:16 UTC, ivanmixo commented on code/__HELPERS/type2type.dm
> +//word of warning: using a matrix like this as a color value will simplify it back to a string after being set
autodocing these would be cool

2023-12-15 15:16 UTC, ivanmixo commented on code/__HELPERS/type_processing.dm
> +/proc/make_types_fancy(list/types)
Autodoccing these would also be cool

2023-12-15 15:16 UTC, ivanmixo commented on code/modules/admin/view_variables/mark_datum.dm
> -/**
Poor autodoc what'd he do to you :(

2023-12-15 15:16 UTC, ivanmixo commented on code/modules/admin/view_variables/mass_edit_variables.dm
> +	set desc="(target) Edit all instances of a target item's variables"
```suggestion
	set desc = "(target) Edit all instances of a target item's variables"
```

2023-12-15 15:16 UTC, ivanmixo commented on code/__DEFINES/_helpers.dm
> +#define text_ref(datum) (isdatum(datum) ? (datum:cached_ref ||= "\ref[datum]") : ("\ref[datum]"))
Seems you have an older version of this, just make it equal to mainline tg again instead. 

https://github.com/tgstation/tgstation/blob/281e82d2237aba5beab54b5defc0bc0016018681/code/__DEFINES/_helpers.dm#L29

2023-12-27 22:02 UTC, TiviPlus approved these changes

2023-12-29 22:52 UTC, merged

2024-12-05 20:54 UTC, MiniMeatwad commented
"Set Species", "Jump To" dropdown menu options are broken.

2024-12-06 18:22 UTC, Xander3359 commented
> "Set Species", "Jump To" dropdown menu options are broken.

I'll look into it when I have some free time