Fixes a quickbuild bug
tgstation/TerraGov-Marine-Corps pull request #14532
Opened 2023-11-24 22:33 UTC by ivanmixo

## About The Pull Request

I honest to god have no idea how nobody noticed this epic logic error and how it's been unreported so long.

Added a safety net in case this somehow happens again.

## Why It's Good For The Game

bug bad

## Changelog

:cl:
fix: Xenos should no longer have quickbuild outside of prep
/:cl:

2023-11-24 23:42 UTC, yyzsong commented
Do the thing where it autocloses this issue https://github.com/tgstation/TerraGov-Marine-Corps/issues/14522

2023-11-25 06:08 UTC, vvvv-vvvv requested changes

2023-11-25 06:08 UTC, vvvv-vvvv commented on code/modules/mob/living/carbon/xenomorph/abilities.dm
> +		stack_trace("[src] ([key_name(src)]) didn't have their quickbuild signals unregistered properly and tried using quickbuild after the subsystem was off!")
src is a /datum/action here

2023-11-25 15:23 UTC, ivanmixo commented on code/modules/mob/living/carbon/xenomorph/abilities.dm
> +		stack_trace("[src] ([key_name(src)]) didn't have their quickbuild signals unregistered properly and tried using quickbuild after the subsystem was off!")
```suggestion
		stack_trace("[owner] ([key_name(owner)]) didn't have their quickbuild signals unregistered properly and tried using quickbuild after the subsystem was off!")
```

2023-11-26 21:28 UTC, Lumipharon approved these changes

2023-11-26 21:28 UTC, merged