Makes hijack more cinematic
tgstation/TerraGov-Marine-Corps pull request #14566
Opened 2023-11-29 02:53 UTC by Barnet2

## About The Pull Request
Explosion on alamo landing when AI announces that the Alamo is crash landing
New crash soundeffect for when alamo lands
6 pipes burst 15 second after alamo lands with 5 seconds to react to them, shakes the ship and plays a klaxon.

## Why It's Good For The Game
Spices up hijack landing, the 6 pipes only burst once so it just adds to the chaos of initial hijack. The burst themselves are as strong as a HEDP nade + Incen nade, so it lands on your cadeline it will damage but not destroy it. Be careful for the alamo explosion, though!

## Changelog

:cl:
add: More explosions when Alamo lands during a hijack
soundadd: Alamo crash sound effect, pipes bursting and klaxon for ship hijack
/:cl:

2023-11-29 19:46 UTC, Derrick2Electricboogaloo commented
Should have the alarms be playing from the moment of the first explosion.

2023-11-30 18:44 UTC, chizzy376 commented
Not really cinematic when the alamo qdels everything near the exits, which I know is already a thing but I wish your pr removed it
> It's to prevent xenos getting stuck

There are no hijack positions that I can think of where xeno exits get blocked by walls

> It's to prevent camping

This is already prevented by the alamo making every human stunned for 2 seconds after alamo crashlands

2023-11-30 19:18 UTC, vvvv-vvvv commented on code/modules/shuttle/marine_dropship.dm
> +	playsound_z(4, 'sound/effects/dropship_crash.ogg', 50) //plays crash sound in transit for xenos landing
```suggestion
	for(var/level in SSmapping.levels_by_trait(ZTRAIT_MARINE_MAIN_SHIP) + SSmapping.levels_by_trait(ZTRAIT_RESERVED))
		playsound_z(level, 'sound/effects/dropship_crash.ogg', 50)
```

2023-11-30 19:19 UTC, vvvv-vvvv commented on code/modules/shuttle/marine_dropship.dm
> +		playsound_z(3, 'sound/effects/double_klaxon.ogg', 5)
```suggestion
		for(var/level in SSmapping.levels_by_trait(ZTRAIT_MARINE_MAIN_SHIP))
			playsound_z(level, 'sound/effects/double_klaxon.ogg', 5)
```

2023-11-30 19:20 UTC, vvvv-vvvv commented on code/game/objects/items/explosives/grenades/marines.dm
> +
```suggestion
```

2023-11-30 19:29 UTC, vvvv-vvvv commented on code/modules/shuttle/marine_dropship.dm
> +		shake_camera(current_mob, 7, 1)
```suggestion
		shake_camera(current_mob, 0.7 SECONDS)
```

2023-11-30 19:31 UTC, vvvv-vvvv commented on code/modules/shuttle/marine_dropship.dm
> +	for(var/i = 1 to 6) //6 pipe explosions on hijack crash
```suggestion
	for(var/_ = 1 to 6) //6 pipe explosions on hijack crash
```

2023-12-02 23:17 UTC, TiviPlus requested changes
Another case of "couldve just done it manually instead"

2023-12-02 23:17 UTC, TiviPlus commented on code/game/objects/effects/overlays.dm
> +	qdel(src)
???????? just use explosion()

2023-12-02 23:17 UTC, TiviPlus commented on code/game/objects/items/explosives/grenades/marines.dm
> +	prime()
delete

2023-12-02 23:17 UTC, TiviPlus commented on code/modules/atmospherics/machinery/pipes/pipes.dm
> +		GLOB.mainship_pipes += src
why cant you just loop the pipenetwork datum

2023-12-02 23:17 UTC, TiviPlus commented on code/modules/shuttle/marine_dropship.dm
> +		playsound_z(3, 'sound/effects/double_klaxon.ogg', 5)
like I said just have this on a loop instead of whatever this is

2023-12-02 23:17 UTC, TiviPlus commented on code/modules/shuttle/marine_dropship.dm
> +	for(var/i = 1 to 6) //6 pipe explosions on hijack crash
fwiw this is a subjective style choice

2023-12-10 07:02 UTC, Barnet2 commented
I'll reopen when I am not working on a map.

2023-12-10 07:02 UTC, closed without merging