doubles CD timer on hivemind heal from 5 to 10 seconds
tgstation/TerraGov-Marine-Corps pull request #14564
Opened 2023-11-29 01:55 UTC by coldironwarrior

## About The Pull Request

doubles CD timer on psychic heal from 5 to 10 seconds

## Why It's Good For The Game

i thought giving hivemind the same heal as queen would be better for the caste and the game versus shrike heal; after seeing how it plays for a fair bit, im not confident the frequency of the availability of the heal is quite what i'd like.

this still makes it more available and frequent than shrike heal,  but not the level of the queen heal. it's pretty good regardless of 5 or 10 seconds anyways, since anyways, since you can instantly teleport to whoever you wanna heal and be there for them.

## Changelog
:cl:
balance: made hivemind's heal ability have a 10 second cooldown instead of a 5 second cooldown
/:cl:

2023-12-01 03:53 UTC, Lumipharon commented on code/modules/mob/living/carbon/xenomorph/castes/hivemind/abilities_hivemind.dm
> +/datum/action/xeno_action/activable/psychic_cure/queen_give_heal/hivemind/can_use_action(silent = FALSE, override_flags, selecting = FALSE
wrong typepath now btw

2023-12-06 14:07 UTC, ivanmixo requested changes
If you're still interested at least make the checks pass

2023-12-07 01:05 UTC, Lumipharon commented
Bruh, what is happening in this pr.
Fix the typepath
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/7869430/0201b122-2ef2-49c3-9045-a62e2c9896ef)

2023-12-07 03:04 UTC, coldironwarrior commented
> Bruh, what is happening in this pr. Fix the typepath ![image](https://private-user-images.githubusercontent.com/7869430/288590243-0201b122-2ef2-49c3-9045-a62e2c9896ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MTg1MjMsIm5iZiI6MTcwMTkxODIyMywicGF0aCI6Ii83ODY5NDMwLzI4ODU5MDI0My0wMjAxYjEyMi0yZWYyLTQ5YzMtOTA0NS1hNjJlMmM5ODk2ZWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDdUMDMwMzQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDMwYzhiYmZlMWViYWFhYmQwMjQzM2JjNmI4NTI4N2NiY2I3OWQwMmI2NzU2OGM0YWZkYjgxOTdlZWIyMWQ5OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.I6SPGKw1n17mk8-1uxBuIML1s3iWfKIb2IWV0GfJrAo)

you overestimate my ability to Actually Code, and especially to Read

2023-12-07 03:52 UTC, coldironwarrior commented
your honor, i've discovered the culprit:
#14467 it's none other than lumi himself.
i rest my case

2023-12-09 09:25 UTC, Lumipharon commented
Actually what has happened to this pr, this is a 1 line change, and you've done all this other stuff since you opened it.

Why are you now setting the cooldown duration when checking can_use_action?

Bruh.

2023-12-09 14:19 UTC, coldironwarrior commented
> Actually what has happened to this pr, this is a 1 line change, and you've done all this other stuff since you opened it.
> 
> Why are you now setting the cooldown duration when checking can_use_action?
> 
> Bruh.

because i didnt realize you refactorered the xeno ability proc which caused a merge conflict, which i tried to fix when it initially appeared but didnt realize why it was conflicting, which caused the horrible amalgamation of commits afterwards. if something gets merged in a file when someone else has something open in it, expect it to get messy.

i use `cooldown_duration` here because Every Other Instance of putting a xeno ability on cooldown uses the variable `cooldown_duration`. 

![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/29965103/05066e72-5d88-4d29-ae4b-9e6fb0d0262e)
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/29965103/0c1ef319-623b-4bba-9f5d-add3c1a1c6bb)
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/29965103/ba5442ae-099c-46af-b6ee-d0ce29af11a4)
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/29965103/e85c9c46-97cd-471e-9378-5b2affce7807)
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/29965103/aecc2753-c53d-4330-abb3-1cbc2ee5492b)
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/29965103/68116eea-65fa-49f1-a0c8-1136995e6f0c)
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/29965103/b9a48685-de67-474b-9bc4-d2cbbac725e8)


im trying to change a value of something, im not gonna go through and refactor all of the ways cooldowns on xeno abilities operate, if that's what you're asking of me.

2023-12-09 14:23 UTC, closed without merging