PMC Medical Contractor DLC
tgstation/TerraGov-Marine-Corps pull request #14611
Opened 2023-12-08 01:24 UTC by SELFHELL

## About The Pull Request

Adds a medic to the PMC ERT, Loadouts consists of:

Advanced Medical/Defib Gloves
VP-70 Pistol with 2 Magazines
PMC SMG with 3 additional magazines
Medical HUD 
Pressurized BKTT Canister (Pouch)
Standard Medic Autoinjector Pouch
Full Lifesaver Rig
Lightpack Backpack

## Why It's Good For The Game

![aleks](https://github.com/tgstation/TerraGov-Marine-Corps/assets/99771731/3a6b6792-e749-41a1-9bc3-9a2d53743061)

Should spice up the PMC ERT with a medic role that has been abnormally absent. Ill try and add some sprites if the whole concept gets the thumbs up from maints.
## Changelog
:cl:
add: PMC Medic
/:cl:

2023-12-08 01:35 UTC, Lumipharon commented
They don't have medics because they're already exceptionally powerful.

2023-12-08 01:37 UTC, Xander3359 requested changes

2023-12-08 01:37 UTC, Xander3359 commented on code/datums/jobs/job/pmc.dm
> +/datum/outfit/job/pmc/gunner
```suggestion
/datum/outfit/job/pmc/medic
```

2023-12-08 01:37 UTC, Xander3359 commented on code/datums/jobs/job/pmc.dm
> +	w_uniform = /obj/item/clothing/under/marine/veteran/pmc/webbing
This is a black webbing, so idk how you intend on putting a gun in a storage that can't hold it...

2023-12-08 01:50 UTC, SELFHELL commented on code/datums/jobs/job/pmc.dm
> +	back = /obj/item/storage/backpack/lightpack
Didnt assume that they would ever need to recharge the glove defibs,

2023-12-09 00:05 UTC, Strayed-Raven commented
Do not think PMC needs medics really. maybe a hard limit of 1

2023-12-18 23:46 UTC, Lumipharon commented
Again, I still don't see WHY the strongest ERT by a significant margain needs this.

2023-12-19 17:28 UTC, Oscari-pog commented
Because operator medics are badass and also really think that people exaggerate the consequence of a singular PMC medic appearing with the rest of the squad

He really isnt gonna be any game changing

2023-12-20 16:09 UTC, ivanmixo commented
I agree, this isn't necessary. Sorry for taking so long

2023-12-20 16:09 UTC, closed without merging