2024 tips update
tgstation/TerraGov-Marine-Corps pull request #14748
Opened 2024-01-03 20:55 UTC by novaepee

## About The Pull Request

New year, new tips.

## Why It's Good For The Game

You know the drill, and so do I.

## Changelog

:cl:
spellcheck: 2024 tips update
/:cl:

2024-01-03 20:56 UTC, novaepee commented
I would like the community to submit tips. Help players out with some protips!

2024-01-03 20:58 UTC, iamafsh commented on strings/tips/marine.txt
> +Go to Vahalla to experiment with loadouts and weapons. You don't reset your respawn time in Vahalla!
```suggestion
Go to Valhalla to experiment with loadouts and weapons. You don't reset your respawn time in Valhalla!
```

2024-01-03 21:59 UTC, Wirpy commented
1# TGMC Lore drop;
didu know 
they moth sax
on tg 
se 
sex

2# Tip:
ban evade
d
im in

3# Tip:
Keep your moth saxes safe, wear protection

4# Help wanted:
how do if get unbanned asd amin

5# TGMC Lore drop;
Lichnarök is a real and canon event in TGMC lore, consult lore masters for further information

6# TGMC Lore drop;
TGMC, the only server where an admin attempted grand larceny of a freddy fazbear head

7# TGMC Lore drop;
harpidi toilet

8# Tip:
You can change colour as a xenomorph by interacting with the silo

9# Tip: 
Imagine how stupid the average marine is then realize half of all marines are stupider than that

10# Tip:
Seek the wisdom of the curve, It will grant thee thy enlightment thous'th seek 

11# Tip: 
Use smelling salts to increase your performance, beware of fiery computers!

12# 
real

13# Tip:
Sexoids aren't real, grow up. Sectoids on the other hand are real and will mindblast you.

14# 
moth sax

15#  
TGMC is fucking horrible and here are all the reasons why

1: The staff are so fucking stupid, especially that Generic DM, all they all do all day is have gay xeno sex and deny us players the things we not only want but DESERVE (more crayons)

2: The players are also so fucking stupid, they are all either ungas or crayons eaters and there is no inbetween, all they do is rush to the front line and die

3: Codebase bad, so much shit code and bad PRs, xeno respawn rework is dumb and they salivated over it for WEEKS but there have been nothing on the PRESSING MATTERS we as players have asked for for YEARS (more crayons!!!!)

4: They have no forum you can use to tell them how dumb they are, all they have is stupid gaycord and gitgay

5: Too many ANIME

6: Fuck you TGMC you smell like pile of crayons

2024-01-03 22:12 UTC, Helg2 commented
You could add something like `Remember! Dying is gay!` to the meme category

2024-01-03 23:32 UTC, 1kajowsmol commented
You can roll in snow, or walk into water to put out fire instantly. (some people especially don't know the snow part)

2024-01-04 02:42 UTC, Wisemonster commented
If meme suggestions are allowed, may I suggest "Alert! There is a red xeno in the FOB!"? For a more serious suggestion, a tip saying "If you are low on blood, eating food can help you replenish missing blood."

2024-01-04 03:07 UTC, yyzsong commented
**Xeno:**
as a ravager, rage mode will make you stagger immune, reset your armour, give you additional fury and boost your speed for a time. Use it as an escape tool, especially if you're too low on fury to endure.
as a ravager, stepping on a tile of fire will give you 50 fury. This has a one second cooldown between uses.
as a ravager, don't get overconfident.
as a ravager, you will regenerate your fury, up to a point.

as a hunter, entering stalk/walk mode while stealthing will make you more transparent. 
remove the tip about standing still. I'm pretty sure that doesn't do anything

as a caste with acid, you can click directly on a lower-level acid puddle to upgrade it.

as a warlock, your offensive abilities can be cast through glass. Give laser-using marines a taste of their own medicine.

as a gorger, your drain ability can be used on corpses to heal incredibly fast, and scales up with pheromones.
as a gorger, you have very little armour. You do not have to consider sunder as much as other castes.
as a gorger, overheal will let you drain corpses even if you're taking damage! This also applies to anyone else that you've overhealed.
as a gorger, you may psy drain for free.

as a ravager or gorger, you will not be affected by tanglefoot or the tesla rifle. However, pepperballs and the smartgunner's tanglefoot DMR ammo still will.

as a shrike, queen, or king, hijacking the alamo will kill every xeno that you leave groundside, as well as destroying every structure and resetting your psy count. However, dead xenos will be refunded as burrowed larva. Call burrowed after a hijack!

rounies aren't real. Stop asking.
rounies are real. Don't let them tell you otherwise.

remove xeno tip 23 about camping fob before defenses are set. that's a CM thing

2024-01-05 23:46 UTC, TheUSSWatercooler commented
Spaceacillin loses effectiveness against severe wound infections. Polyhexanide will pick where it left off at, at the cost of some toxin damage and drowsiness.

You can use bicardine in vali weapons to heal brute on corpses.

Inaprovaline, Russian Red, and Neuraline injections can quickly bring a marine from death's door to walking.

Wash your hands.

2024-01-06 14:40 UTC, Sirsnek15 commented
Marine: An entire MRE can fit in your boot.

2024-01-17 02:05 UTC, ivanmixo requested changes

2024-01-17 02:05 UTC, ivanmixo commented on strings/tips/xeno.txt
> +When placing resin walls, they start at 40% their max health then gain health over time until hitting their max health. For hivelords, they are start at 70%.
```suggestion
When placing resin walls, they start at 40% their max health then gain health over time. Walls made by hivelords start at 70% health.
```

2024-01-17 02:05 UTC, ivanmixo commented on strings/tips/xeno.txt
> +Robot healthbars are not directly one to one with their actual health. they will still have some fight left in them after it shows their health has hit critical.
```suggestion
Robot healthbars are not directly one to one with their actual health. They will still have some fight left in them after it shows their health has hit critical.
```

2024-01-17 02:05 UTC, ivanmixo commented on strings/tips/xeno.txt
> +If something comes up in real life while you’re a xenomorph, head back to the silo and use the “ghost” command to let others take over your body. Your name will be cleared
```suggestion
If something comes up in real life while you’re a xenomorph, head back to the silo and use the “ghost” command to let others take over your body.
```

2024-01-17 02:05 UTC, ivanmixo commented on strings/tips/xeno.txt
> +As a ravager, rage mode will make you stagger immune, reset your armour, give you additional fury and boost your speed for a time. Use it as an escape tool, especially if you're too low on fury to en
```suggestion
As a ravager, rage mode will make you stagger immune, reset your armour, give you additional fury and boost your speed for a time. Use it as an escape tool, especially if you're too low on rage to endure.
```

2024-01-17 02:05 UTC, ivanmixo commented on strings/tips/xeno.txt
> +As a ravager, stepping on a tile of fire will give you 50 fury. This has a one second cooldown between uses.
It's just a passive increase now while you're on fire

2024-01-17 02:05 UTC, ivanmixo commented on strings/tips/xeno.txt
> +As a ravager, you will regenerate your fury, up to a point.
```suggestion
As a ravager, you will regenerate your rage, up to a point.
```

2024-01-17 02:05 UTC, ivanmixo commented on strings/tips/xeno.txt
> +As a hunter you can swap places with one of your mirages by pressing the button again.
Duplicate tip

2024-01-17 02:05 UTC, ivanmixo commented on strings/tips/xeno.txt
> +In crash, marines have landed when nuke disks appear on the map.
Ehhhhh this is really a bug in my opinion and not an actual feature. I'd leave it out

2024-01-17 02:05 UTC, ivanmixo commented on strings/tips/marine.txt
> +Acid Upgrade prevents xenos from spewing acid all over undefended barricade.
```suggestion
The caustic upgrade prevents xenos from spewing acid all over an undefended barricade.
```

2024-01-17 02:05 UTC, ivanmixo commented on strings/tips/marine.txt
> +Hunger will slow you down. A single protein bar will fill many, if not every, people. Take an extra protein bar too much and you become slower (ironic) and fat.
will fill many, if not every, people

lol i get its funny but it was removed for a reason

2024-01-17 02:05 UTC, ivanmixo commented on strings/tips/marine.txt
> +If you are low on blood, eating food can help you replenish missing blood.
```suggestion
If you are low on blood, eating food can help you replenish blood.
```

2024-01-17 02:06 UTC, ivanmixo commented on strings/tips/marine.txt
> +Any marines can link plasteel barricades together using a crowbar. Click one, and then click one adjacent. Repeat as needed.
```suggestion
Any marine can link plasteel barricades together using a crowbar. Click one, and then click one adjacent. Repeat as needed.
```

2024-01-17 19:57 UTC, novaepee commented on strings/tips/marine.txt
> +Stasis bags prevents brain death timer from ticking, meaning that if corpsmen have a lot of patients, they can prevent brain death via stasis bags.
DNR is specific in that the player intentionally op out to not get revived. Brain death is not intentional on the player's part. I know we use DNR and brain death as the same, though I prefer that we don't mix these up.

2024-01-17 20:42 UTC, ivanmixo approved these changes

2024-01-17 20:45 UTC, merged