Backend improvement to campaign overview UI
tgstation/TerraGov-Marine-Corps pull request #14746
Opened 2024-01-03 04:13 UTC by Lumipharon

## About The Pull Request
The icons are now loaded as a spritesheet, so no need to spam icons with every update.

## Why It's Good For The Game
Perf good

## Changelog

:cl:
code: Some backend improvements to campaign overview UI
/:cl:

2024-01-03 12:14 UTC, Lumipharon commented
Also yes, the nested stuff on the icons is nasty, I'll fix that later, since it was already there.

2024-01-04 03:05 UTC, ivanmixo requested changes

2024-01-04 03:05 UTC, ivanmixo commented on code/_globalvars/lists/flavor_misc.dm
> +/proc/init_campaign_asset_icons()
doc

2024-01-04 03:05 UTC, ivanmixo commented on code/modules/asset_cache/asset_list_items.dm
> +	var/list/icon_names
doc

2024-01-04 04:05 UTC, ivanmixo approved these changes

2024-01-04 04:05 UTC, merged