Fix glass being able to be merged into any other glass type
tgstation/TerraGov-Marine-Corps pull request #14760
Opened 2024-01-05 09:03 UTC by SplinterGP

## About The Pull Request
Fixes #14638 

## Why It's Good For The Game
Fixes bug yay

## Changelog

:cl:
fix: glass can't turn into other glass types by merging it into a reinforced/phoron glass stack
/:cl:

2024-01-05 09:05 UTC, SplinterGP commented
there was possibly a fix i could do without editing map but it would change more stuff so i just did this

2024-01-05 09:11 UTC, SplinterGP commented
thinking about this now, can glass be saved in loadouts ? or some other thing that could magically spawn the removed glass type ? if so tell me please

2024-01-05 10:23 UTC, Lumipharon requested changes
this seems... not ideal. Why don't you just add a merge blacklist var or something?

2024-01-07 02:42 UTC, ivanmixo approved these changes

2024-01-07 02:54 UTC, ivanmixo commented
A blacklist just seems a bit much, maybe you could just experiment with making the merging logic strict about type?

https://github.com/tgstation/TerraGov-Marine-Corps/blob/fc032ebe0f345bde399029a5031b75db14126c74/code/game/objects/items/stacks/stack.dm#L336

Doing `if(S.type == merge_type)` would make it accept only the exact type laid out in `merge_type`, without having to do all this. If you decide to do this be sure to look at all instances where it's checked to make sure they're right

2024-01-07 03:31 UTC, Lumipharon commented
> A blacklist just seems a bit much, maybe you could just experiment with making the merging logic strict about type?
> 
> https://github.com/tgstation/TerraGov-Marine-Corps/blob/fc032ebe0f345bde399029a5031b75db14126c74/code/game/objects/items/stacks/stack.dm#L336
> 
> Doing `if(S.type == merge_type)` would make it accept only the exact type laid out in `merge_type`, without having to do all this. If you decide to do this be sure to look at all instances where it's checked to make sure they're right

Considering we have separate types for spawning different stack quantities, a strict type check won't work.
Blacklist is the exact thing needed for this tbh.

2024-01-07 20:27 UTC, SplinterGP commented
yeah it cant be a strict type check, and i mean i did this solution because it looks more or less the way it is on other stacks, they just dont have children they shoulndt merge with but i can add a blacklist no problem although basically only glass would use it

2024-01-08 21:32 UTC, TiviPlus commented
this is ugly but the others sound cursed so ship it

2024-01-08 21:32 UTC, merged