Adds Acid pools
tgstation/TerraGov-Marine-Corps pull request #14779
Opened 2024-01-08 21:20 UTC by TiviPlus

## About The Pull Request
2x3 structure, 200 tac points, heals sunder at a rate of 1 per 2 seconds when you rest on it (subject to change)

## Why It's Good For The Game
Hivelord no longer soft mandatory + more things to spend on

## Changelog

:cl:
add: Added acid pools, a sunder healing structure for xenos purchasable with tactical psychic points
/:cl:

2024-01-08 21:21 UTC, yyzsong commented
XROS... I'D NEVER THOUGHT I'D SEE THE DAY

2024-01-08 21:21 UTC, TiviPlus commented
requires tac points pr to compile btw

2024-01-08 21:24 UTC, Kuro020 approved these changes
I thought i'd never see the day tivi would stop being lazy

2024-01-09 04:20 UTC, Ragecrabbo commented
Great addition in my opinion. 
Lack of any defenses of its own and requiring to be placed somewhat close to where the fighting is means its always at risk of being destroyed and unlike phero towers you cant just put it in a hard to reach spot and wall it up. One thing i'd like to see added to it is maybe a tiny healing buff for flavor and so xenos without meaningful amounts of armor or sunder get a benefit out of resting there, which in turn could better enable counterplay from smart marines using tarp/cas/offscreen weapons.
I hope to see this ingame either way though.

2024-01-11 21:50 UTC, ivanmixo requested changes

2024-01-11 21:50 UTC, ivanmixo commented on code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
> +	name = "Larva Pool"
Larva pool

2024-01-11 21:50 UTC, ivanmixo commented on code/modules/xenomorph/xeno_structures.dm
> +	desc = "A pool of weak viscous acid that solidifies quickly when removed from it's pool. Swimming is not reccomended due to the lack of lifeguard."
```suggestion
	desc = "A pool of weak viscous acid that solidifies quickly when removed from the pool. Swimming is not recommended due to the lack of a lifeguard."
```

2024-01-12 04:41 UTC, novaepee commented
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/6610922/ee04d8cf-41fa-4d37-b5f4-ad4055e8b8ef)

2024-01-12 23:12 UTC, lbnesquik commented
2x3? That's a weird shape.

2024-01-13 18:27 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
> +	name = "Larva Pool"
```suggestion
	name = "Acid Pool"
```

2024-01-13 19:54 UTC, ivanmixo approved these changes

2024-01-16 01:22 UTC, merged