Axe sweep attack
tgstation/TerraGov-Marine-Corps pull request #14775
Opened 2024-01-07 21:05 UTC by Lumipharon

## About The Pull Request
Atomised change so Tivi doesn't burst a vein later.

Adds a sweep attack to the breaching axe, very similar to ravage. Costs stamina, can't stun, and missing anyone lying down.

Unlockable only via a trait which will be available in a future pr.

Also fixed a bug where I forgot to unregister a signal on a component axe has.

## Why It's Good For The Game
special attack cool, atomised change gud.

## Changelog

:cl:
balance: Added a sweep attack to the boarding axe as a future unlockable
/:cl:

2024-01-08 00:34 UTC, Lumipharon commented
Draft for now as I need to review blinkdrive/jetpack to make them more compatible.

2024-01-10 21:36 UTC, TiviPlus requested changes
No reason this cant be rclick/normal click functionality

2024-01-10 22:40 UTC, Lumipharon commented
These need to be action buttons.
If there is more than one, right click is no longer going to cut it, and resorting to random alt + click combos or whatever is extremely cringe, and ultimately limited by those param combos that are already used for other things, while also providing no visibility on what abilities you have available, cooldowns, cost, etc.

No xeno players would want all their actions to be converted in the same way, and having these as actions keeps abilities consistant.

2024-01-11 21:58 UTC, ivanmixo approved these changes

2024-01-11 22:00 UTC, merged