Campaign: New loadout system and perk system
tgstation/TerraGov-Marine-Corps pull request #14789
Opened 2024-01-09 23:46 UTC by Lumipharon

## About The Pull Request
Requires/includes #14776 so probs review/merge that first.
Code is like 98% done so is fine for review if a maint wanted to get started.

Main things before this is completely ready is still populating some loadout stuff which is pretty boiler plate.
Also some code to actually add credits from missions or whatever.
Also some spritework for icons and such.

### Loadouts
Adds a new loadout system for Campaign. You now get (some) customisation back.
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/7869430/2a0446ef-1475-4ed3-9305-3a9e4c03d52b)

A new action button lets you open up a UI where you can customise your loadout for all available jobs in your faction.
Every slot has a list of selectable items.
You populate all your choices, then hit equip and you're good to go.

https://github.com/tgstation/TerraGov-Marine-Corps/assets/7869430/911a4157-480e-48fc-a9c8-699e1c918119

The loadout(s) are preserved for your character, so you can adjust or change them next mission, or while you're dead etc.

Some items either having a whitelist (i.e. you need another item to equip it) or a blacklist (equipping this forbids other items).
Some can have an equip cost (i.e. a cost every time you equip a loadout with it), or have to be unlocked with a one off cost.
Certain selections (mainly your main weapon) also help determine the contents of your loadout. i.e. guns with a UGL will likely have grenades in their bag or webbing, etc).

### Perks
You can now unlock perks that apply permanent bonuses to your character.
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/7869430/6f6668f7-e7ff-407e-b190-9e5c9fbc53e3)

These vary from job to job, but most are universal. i.e. most gun skills.
Most perks are skill related currently, but there are others, such as max HP boosts, the ability to walk silently, and a couple to unlock special melee abilities etc.

Loadouts are still mainly confined to existing available stuff in campaign (SOM especially don't really have any cosmetic items since none exist for them), but this will expand in the future after this is successfully released.
Likewise I have plans to greatly expand the perk system.

I also hope to make the interface look a lot nicer, someone please pay gregor so I can have big icon buttons instead of what I currently have.

## Why It's Good For The Game
Customisation without 20 minute prep time is good. Individual progression equals far better player investment.

## Changelog

:cl:
add: Added a new perk system for Campaign mode
add: Added a new customisable loadout system for Campaign mode
/:cl:

2024-01-09 23:59 UTC, Loafin34 commented
Will one of the perks be mag switching? (tap gun with mag to reload it without caring if mag was out of gun or not)

2024-01-10 00:46 UTC, Kuro020 approved these changes

2024-01-10 21:19 UTC, Lumipharon commented
> Will one of the perks be mag switching? (tap gun with mag to reload it without caring if mag was out of gun or not)

Uh, you mean tactical reloads? That's already a thing.

2024-01-14 07:15 UTC, shelteredfreak commented
>adds Perks
Can we play Campaign 24/7 now? Please and thank you. 

I might miss xenos, but maybe you can add some xeno missions and xeno support to Campaign someday...

2024-01-14 20:34 UTC, ivanmixo requested changes
Minor stuff

2024-01-14 20:34 UTC, ivanmixo commented on code/__DEFINES/assert.dm
> +/proc/assertion_message(file, line, condition, message)
doc

2024-01-14 20:34 UTC, ivanmixo commented on code/datums/gamemodes/campaign/individual_stats.dm
> +				to_chat(user, "<span class='warning'>One or more prerequisites missing for this perk.")
use the macros for these spans

2024-01-14 20:57 UTC, ivanmixo approved these changes

2024-01-14 20:57 UTC, merged

2024-01-14 21:21 UTC, Tommy-211 commented
You know what i love? more hvh game modes that nobody will play after the first week of it's release

2024-01-21 12:23 UTC, chizzy376 commented
I like this approach, but I wish it told you what the skills do when upgraded. I.e., corpsman getting the better medicine perk, how much they benefit from it