Visible cooldown timer
tgstation/TerraGov-Marine-Corps pull request #14802
Opened 2024-01-11 20:40 UTC by Lumipharon

## About The Pull Request
Ability type actions now display their actual cooldown time remaining instead of a random clock symbol.

https://github.com/tgstation/TerraGov-Marine-Corps/assets/7869430/cf7e665c-7db2-4b83-86c9-0ba0f023eeef

## Why It's Good For The Game
Useful information on your screen is good.

## Changelog

:cl:
qol: Ability type actions now display their cooldown remaining
/:cl:

2024-01-11 21:43 UTC, ivanmixo requested changes
Also make sure this works fine with the savage cooldown maptext on runner

2024-01-11 21:43 UTC, ivanmixo commented on code/game/objects/effects/countdown.dm
> +	var/datum/action/ability/attached_action
Autodoc

2024-01-11 21:43 UTC, ivanmixo commented on code/game/objects/effects/countdown.dm
> +		return qdel(src)
Returning qdel? Any particular reason?

2024-01-11 21:43 UTC, ivanmixo commented on code/game/objects/effects/countdown.dm
> +		qdel(src)
Think you forgot a return below the qdel

2024-01-11 22:18 UTC, Lumipharon commented
Yep, works fine with savage, that timer is positioned differently.
That should also probs be a countdown instead of an MA overlay though.

2024-01-11 22:19 UTC, Lumipharon commented on code/game/objects/effects/countdown.dm
> +		return qdel(src)
updated

2024-01-13 16:21 UTC, ivanmixo approved these changes

2024-01-14 12:43 UTC, merged