Evolution Changes
tgstation/TerraGov-Marine-Corps pull request #14909
Opened 2024-01-26 02:21 UTC by Barnet2

## About The Pull Request
Xenomorphs can now evolve to any xenomorph in the next tier, and to T4. For example, Runner can now evolve to Spitter or even Queen if there is a slot open. Queen and King still cannot evo, and Shrike can only evo to queen and king. Plus, larva can only evolve T1's.

## Why It's Good For The Game
This is a relic of trying to associate castes with eachother, like the Runner is red and Ravager is red too, so they should be in the same tree. Even for xenos that aren't really related at all (see: warrior and warlock). This allows for more flexibility in Xenomorph play, especially roundstart when Xenos go drone; they can now evo to whatever they want after quickbuild.

## Changelog

:cl:
balance: Xenomorphs can now evolve to any caste above their tier and T4, with exceptions made for the T4's and larva
/:cl:

2024-01-26 03:04 UTC, Wisemonster commented
This is going to make filling in for missing roles significantly easier. For example, currently if you wanted to go crusher from spitter, you'd have to de-volve to defender/runner, evolve to warrior/bull, then go crusher. This pr makes it so all'd you need to do is evolve to crusher. I'm all for this buff.

2024-01-26 03:10 UTC, SomrNetwork commented
https://github.com/tgstation/TerraGov-Marine-Corps/assets/114457130/9735b12c-f993-47d8-a18c-55b318423ae0

2024-01-26 03:10 UTC, bowlofcereal commented
Yeah why not this doesn't really change the game in the long run

2024-01-26 03:11 UTC, novaepee commented
if this PR gets merged, i can die knowing that i don't have to maintain this chart anymore
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/6610922/49ba9ba2-cdbf-4744-82f7-cac9c66ea376)

2024-01-26 03:19 UTC, aarrisu commented
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/131525549/31568788-210c-4df4-bb3a-be78d7fd66d4) i like this pr :3

2024-01-26 03:19 UTC, yyzsong commented
God fuckin' damn finally
can you remove the "you can only evo to drone" restriction you get when there's no hive leaders while you're at it?

2024-01-26 10:21 UTC, chizzy376 commented
Good work barnie ^^

2024-01-26 16:15 UTC, TiviPlus requested changes

2024-01-26 16:15 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/evolution.dm
> +			if(isxenoshrike(src))
dont use istype(src, check what mob it is instead

2024-01-26 16:15 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/evolution.dm
> +
use early returns: queen and sking return null instead of list() like the fail state

2024-01-26 16:15 UTC, TiviPlus commented on code/_globalvars/lists/mobs.dm
> +GLOBAL_LIST_INIT(xeno_types_tier_shrike, list(/mob/living/carbon/xenomorph/queen, /mob/living/carbon/xenomorph/king))
just make this inline, I dont see a usecase for this glob that isnt snowflake evo handling

2024-01-26 19:12 UTC, BonkaiB commented
thought on it, seems fine in the long-run

2024-01-27 15:19 UTC, ivanmixo approved these changes

2024-01-27 17:09 UTC, merged