No lobby wait time by default
tgstation/TerraGov-Marine-Corps pull request #14940
Opened 2024-01-28 19:56 UTC by XElectricX

## About The Pull Request

Simply makes the lobby wait time 0 by default. Should have no effect on any live server since the config overrides the default entries.

## Why It's Good For The Game

A giant thorn in my side, and probably other developers. No more having to type out the starting early command.

## Changelog

:cl:
config: The lobby wait time is 0 by default
/:cl:

2024-01-31 22:14 UTC, ivanmixo requested changes
This is uhhhh... what if I want to test something in lobby? Bit guh. Also you're editing the fuckin code instead of the actual config txt file what is wrong with you

2024-01-31 22:37 UTC, XElectricX commented
> This is uhhhh... what if I want to test something in lobby? Bit guh. Also you're editing the fuckin code instead of the actual config txt file what is wrong with you

It doesn't do anything if you have something set in the config. This is just the default number used if there is no config entry.

2024-02-01 10:09 UTC, ivanmixo commented
Edit the txt instead

2024-02-01 12:50 UTC, TiviPlus commented
Yea this is useful by default just edit your own txt if you dont need it

2024-02-01 12:50 UTC, closed without merging