Vents Now Damage Mobs Inside of Them
tgstation/TerraGov-Marine-Corps pull request #14962
Opened 2024-01-30 22:39 UTC by Wisemonster

## About The Pull Request
Title, mobs will now take 1 brute damage per life tick while inside of a vent.

## Why It's Good For The Game
Currently, xenos can camp vents indefinitely. This means that a xeno could just stall by hiding inside of a vent, or if all the vents are welded, the xeno is just stuck until a vent is unwelded. This will help prevent stalling xenos inside of vents, or help free xenos stuck in purgatory by killing them.

## Changelog

:cl:
balance: Mobs will now take 1 brute damage per life tick while inside of vents.
/:cl:

2024-01-30 22:40 UTC, Wisemonster commented
If 1 brute damage is too low, I can increase it. Also wasn't sure where to put the check, so if the life loop isn't a good spot, let me know.

2024-01-30 22:43 UTC, Derrick2Electricboogaloo commented
I swear it used to be a thing that if you managed to weld all vents they just died.

2024-01-30 22:45 UTC, novaepee commented
death sentence to larva hiding in vents

2024-01-30 22:51 UTC, Wisemonster commented
Ok, I can add an exception to larva if it's needed, though unlike other castes, larva can squeeze under doors

2024-01-30 23:30 UTC, Lumipharon commented
What, why? you can't stall in vents because it doesn't count xenos in vents.
If you get trapped that's a tremendous skill issue as you'd have to watch them seal like 80 vents.

2024-01-31 00:21 UTC, Wisemonster commented
Sure, getting trapped is a skill issue, but if a T2 or higher get's stuck in the vents, does that mean the xenos deserve to be permanently down 1 slot?

2024-01-31 00:23 UTC, Lumipharon commented
How are you getting stuck in the vents? This is genuinely impossible unless you just fluoride stare at marines slowly welding 80 vents.

2024-01-31 00:27 UTC, Kuro020 commented
you have a nuke, use it

2024-01-31 00:27 UTC, closed without merging

2024-01-31 00:28 UTC, RipGrayson requested changes
Not judging the merits of this PR, but if you're going to damage the xenos for crawling in vents they need a flavor text telling them that they're taking damage. It's bad form to harm players without any indication that it's happening.
Edit: Nevermind, closed as I was writing this.

2024-01-31 00:32 UTC, Kuro020 commented
If delaying is a issue dont nerf a whole mechanic that is overall fine because of said single issue, find a better way to do it

2024-01-31 00:37 UTC, Wisemonster commented
To clarify, I didn't know when I made this pr that vent xenos do not count towards the round ending, I might make an alternative where when all connected vents are welded, it'll kill any mobs inside