SMG-45 HP->Squashhead, new sound
tgstation/TerraGov-Marine-Corps pull request #14975
Opened 2024-01-31 23:36 UTC by Pariah919

## About The Pull Request
SMG 45 HP is replaced by new squashhead rounds.
New fire sound.

## Why It's Good For The Game
People kept yelling at me that the hollowpoints were useless so here you are, enjoy.

## Changelog

:cl:
add: New squashhead bullets for SMG-45
del: SMG-45 HP
soundadd: New firesound for SMG-45
/:cl:

2024-02-01 00:01 UTC, Lumipharon requested changes

2024-02-01 00:01 UTC, Lumipharon commented on code/modules/projectiles/ammo_datums.dm
> +	armor_type = "bomb"
?

2024-02-01 00:51 UTC, Kuro020 requested changes
we got discovered, just make it target bullet armor and do something else for it

2024-02-01 01:10 UTC, Kuro020 approved these changes

2024-02-01 11:59 UTC, srxtreme commented
Woe Curse of weak ammo type upon ye

2024-02-02 01:19 UTC, ivanmixo requested changes
also shatter on a full auto gun? buh

2024-02-02 01:19 UTC, ivanmixo commented on code/modules/projectiles/ammo_datums.dm
> +	var/shatter_duration = 3 SECONDS
doc

2024-02-04 23:02 UTC, Oscari-pog commented
3 seconds of shatter is too long on a automatic gun

2024-02-14 19:42 UTC, ivanmixo approved these changes

2024-02-14 21:42 UTC, merged