Disables tadpole, makes hijacking have the same people check as capturing, reduces PO slots to 1
tgstation/TerraGov-Marine-Corps pull request #14981
Opened 2024-02-01 23:54 UTC by Pariah919

## About The Pull Request
See title. Kills stealthjacking.
Reduces PO slots to 1.
## Why It's Good For The Game
Tadpole is terrible for gameflow, and removing it is would fix a lot of the game flow problems we usually encounter with logistics and such. Also stealthjacking is kinda cringe with summon making it so easy.
## Changelog
:cl:
del: Disables tadpole in nuclear war.
balance: You can no longer hijack as long as there are 6~ marines groundside.
/:cl:

2024-02-01 23:57 UTC, Wisemonster commented
Reduce the PO numbers, unless you want POs fighting over the CAS

2024-02-02 00:00 UTC, Pariah919 commented
> Reduce the PO numbers, unless you want POs fighting over the CAS

it was always two so i'm just too liazy to bother

2024-02-02 00:02 UTC, Lumipharon requested changes
You need to change PO to 1 with this.

2024-02-02 00:13 UTC, Lumipharon commented on code/modules/shuttle/marine_dropship.dm
> +		for(var/N in GLOB.alive_human_list)
there's a humans_by_zlevel glob you know

2024-02-02 02:47 UTC, MiniMeatwad commented
Don't know about killing tadpole. Nerf it into uselessness first so we can give it an inglorious end in its deathbed.

2024-02-02 02:53 UTC, Henri9576 commented
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/46168172/408a7f67-5281-4405-805c-ee99b7311cc5)

2024-02-02 03:06 UTC, Loafin34 commented
why merge this? tad is necessary to healbus or securing xenos. otherwise the marines are stranded.

2024-02-02 05:09 UTC, Wisemonster commented
> why merge this? tad is necessary to healbus or securing xenos. otherwise the marines are stranded.

Except fulton packs exist for securing xenos.

2024-02-02 06:21 UTC, efzapa commented
> > Reduce the PO numbers, unless you want POs fighting over the CAS
> 
> it was always two so i'm just too liazy to bother

its literally a one line change
god's least lazy TGMC coder, truly

2024-02-02 06:23 UTC, efzapa commented
> why merge this? tad is necessary to healbus or securing xenos. otherwise the marines are stranded.

we are slowly looping back around to 3 hour long CM rounds, calling it now

2024-02-02 07:12 UTC, SimplySmiley123 commented
> > why merge this? tad is necessary to healbus or securing xenos. otherwise the marines are stranded.
> 
> we are slowly looping back around to 3 hour long CM rounds, calling it now

Yuuup. Slowly becoming what TGMC swore to destroy.

2024-02-02 12:28 UTC, Woker2004 commented
Well, I was expecting the mass marine nerfs, but not this quickly

2024-02-02 16:06 UTC, AusarAtkin commented
With how hard it is to secure FOB and Backline even with 60-70 pop, how would you fill the big gaping hole Tadpole role left behind? 
Or is this meant to be remove it first and fix it later kind of PR?

2024-02-02 17:09 UTC, SimplySmiley123 commented
> With how hard it is to secure FOB and Backline even with 60-70 pop, how would you fill the big gaping hole Tadpole role left behind? Or is this meant to be remove it first and fix it later kind of PR?

I think it's just remove first and **don't** fix later kind of PR

2024-02-02 21:32 UTC, Aporhtonoma commented
THE GREATEST MARINE BUFF JUST DROPPED

2024-02-02 21:46 UTC, TheWiznard commented
put me in the screenshot when this gets merged with 32 thumbs down

2024-02-02 22:10 UTC, ButterChugger commented
Next up, removal of PO entirely due to that one time I got hit by a guardian bomb.

Removal of a fun mechanic for xenos AND marines in the same breath? Do you just want fun to cease?

2024-02-03 07:30 UTC, Kestaral commented
I thought the tadpole improved game-flow by making rounds more fast paced because marines don't have to run back to fob for resupplies? I feel like most people enjoy more fast paced rounds. And i don’t think anyone likes taking back and forth trips to the fob for resupplies, where you can easily get killed because xenos tend to target people by themselves or in small groups.

2024-02-03 09:01 UTC, TellyLsc commented
"noooooooooo you cant just bring 100 ammo boxes and other supplies into the frontlines!" the PR

2024-02-03 10:13 UTC, Tommy-211 commented
What the fuck what the actual fuck what on earth 
what the fuck why dude tad is so fucking key to winning an operation, how does it hinder game flow in the fucking slightest it is literally the number 1 support vehicle / transport for marines that make is so that they don't have to spend 30 minutes walking from 2 disks because its covered in cancerous maze spam. This is literally the most tragically retarded thing I have seen on this github in a while.

2024-02-03 22:10 UTC, yyzsong commented
> Removal of a fun mechanic for xenos AND marines

Which one is that again

2024-02-04 11:22 UTC, FIXTHERADBOXPLEASE commented
This PR will singlehandedly increase Marine winrates by 5000% if merged.

2024-02-04 15:29 UTC, SimplySmiley123 commented
> This PR will singlehandedly increase Marine winrates by 5000% if merged.

Xeno* winrates

2024-02-04 15:47 UTC, Barnet2 commented on code/datums/jobs/job/shipside.dm
> +	total_positions = 1
You forgot to reduce the PO slots in nuclear_war.dm so two PO's can still spawn in

2024-02-04 16:11 UTC, Kuro020 commented
From what I can see without tad marines cant really do the disks on lower pop (40 popish) so this removal isnt gonna work out, closing

2024-02-04 16:11 UTC, closed without merging