Deletes
tgstation/TerraGov-Marine-Corps pull request #14986
Opened 2024-02-02 20:52 UTC by Xander3359

## About The Pull Request

## Why It's Good For The Game

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2024-02-03 08:56 UTC, TellyLsc commented
Why? specialclick can be rebinded while the click code stuff can't, right? What if I want to examine items by holding shift+click on items which is only possible because it's rebindable?

2024-02-04 12:41 UTC, ivanmixo requested changes

2024-02-04 12:41 UTC, ivanmixo commented on code/_onclick/click.dm
> +	if(examinate(A))
Put it in `ShiftClick` instead

2024-02-04 16:45 UTC, ivanmixo approved these changes

2024-02-04 16:45 UTC, merged