delete specialclick
tgstation/TerraGov-Marine-Corps pull request #14988
Opened 2024-02-02 21:35 UTC by Xander3359

## About The Pull Request
delete specialclick

## Why It's Good For The Game
This was dumb.
We had some things coded onto CTRL click
And then we had other things coded onto specialclick (Which is defaulted to CTRL)
???
I'm deleting specialclick in favor of keeping our click code.

## Changelog

:cl:
del: Deletes "specialclick" keybind
/:cl:

2024-02-02 23:57 UTC, coldironwarrior commented on strings/tips/marine.txt
> +As a marine, you can climb over waist-high obstacles like sandbags, window frames or tables by CTRL+click on them or drag-clicking yourself onto them.
`by using CTRL+click on them` or `by CTRL+clicking`

2024-02-03 08:54 UTC, TellyLsc commented
Why? specialclick can be rebinded while the click code stuff can't, right? What if I want to climb windows by holding alt+click on window which is only possible because it's rebindable?

2024-02-04 13:43 UTC, ivanmixo requested changes

2024-02-04 13:43 UTC, ivanmixo commented on strings/tips/marine.txt
> +As a marine, you can climb over waist-high obstacles like sandbags, window frames or tables by CTRL+click on them or drag-clicking yourself onto them.
```suggestion
As a marine, you can climb over waist-high obstacles like sandbags, window frames or tables by CTRL+clicking them or drag-clicking yourself onto them.
```

2024-02-04 14:58 UTC, ivanmixo approved these changes

2024-02-04 14:58 UTC, merged

2024-02-04 20:15 UTC, Al-1ce commented
Really not a fan of this.