Tadpole Officer
tgstation/TerraGov-Marine-Corps pull request #15004
Opened 2024-02-04 20:03 UTC by Barnet2

## About The Pull Request
Reduces PO slot to one, adding a new role: Tadpole Officer
100 hour timelock, has engi skill instead of pilot skill
Pilot Officer by default can no longer pilot tad

## Why It's Good For The Game
Attempts to fix two issues:
1. PO's arguing over who gets what (condor/tad)
2. New players picking PO and griefing
Number one is self explanatory. Number two should be somewhat remedied (but not completely fixed due to the nature of the tadpole) with a high timelock.

## Changelog

:cl:
add: New role: Tadpole Officer
balance: Reduces PO slot to one
/:cl:

2024-02-04 20:14 UTC, Al-1ce commented
This has been tried a dozen times already and for whatever reason it always gets shot down.

2024-02-04 22:21 UTC, efzapa commented
> This has been tried a dozen times already and for whatever reason it always gets shot down.

mostly due to people coping about their precious playtime being lost

2024-02-05 01:54 UTC, novaepee commented
we should call PO CAS pilot if this pr gets merged

2024-02-05 05:34 UTC, Loafin34 commented
sovl removed.. also job bloat.

2024-02-05 08:00 UTC, spookydonut commented
this is dumb

2024-02-05 11:35 UTC, FosterGrime-Heymynameslouie commented
this is really good I dont understand why people dislike it
basically creates distinction between cas and po so they dont have to do a fist fight between who gets what when they have conflicting intrests
obliterates grief, seriously why does po in general has such little timelock?
spedmgehr

2024-02-05 13:31 UTC, Woker2004 commented
Barnet I will state, please rename old PO to CAS pilot to avoid confusion, other than that I can agree with this change

2024-02-05 16:50 UTC, AusarAtkin commented
Do other roles can still pilot Tad with access on their id, or its going to be like a mech and its pilot?

2024-02-05 18:49 UTC, 1kajowsmol commented
needs tm for like.. several days to really get a feel. seems good idea tho

2024-02-05 20:23 UTC, Woker2004 commented
> This cannot be done due to how persistence works based off of job names. It would kill existing PO hours.

There are like only one person who cares about PO hours, Cassie is the only one who really would care

2024-02-05 22:13 UTC, Barnet2 commented
> > This cannot be done due to how persistence works based off of job names. It would kill existing PO hours.
> 
> 
> 
> There are like only one person who cares about PO hours, Cassie is the only one who really would care

That does not matter, maintainers want to keep the hours so PO will stay named PO, no exceptions.

2024-02-05 22:49 UTC, Woker2004 commented
> That does not matter, maintainers want to keep the hours so PO will stay named PO, no exceptions.
Maints back at it with another 1984

2024-02-06 19:09 UTC, TiviPlus requested changes
rest lgtm

2024-02-06 19:09 UTC, TiviPlus commented on code/game/objects/effects/landmarks/marine_spawns.dm
> +
should probably use a different icon, no?

2024-02-06 19:09 UTC, TiviPlus commented on code/game/objects/items/devices/tablets.dm
> +				req_access = list(ACCESS_MARINE_PILOT, ACCESS_MARINE_TADPOLE)
copy paste dat, network codes are still shared despite job being split

2024-02-06 19:09 UTC, TiviPlus commented on code/__DEFINES/jobs.dm
> +#define XP_REQ_TADPOLE_OFFICER 3000
Remove the new define and set it to expert, we will increase the define after to 20/25h

This was agreed on in maintainer chat

2024-02-06 19:09 UTC, TiviPlus commented on code/__DEFINES/jobs.dm
> +#define TADPOLE_OFFICER "Tadpole Officer"
This name is not new player friendly (new player thinks tadpole is an animal), rename it to something like transport pilot
Might want to rename rest of code for consistency as well

2024-02-06 19:09 UTC, TiviPlus commented on code/datums/jobs/job/shipside.dm
> +You are to ensure the Tadpole's survival and to transport marines around, acting as a mobile bunker. In the case of it's death, you are relegated to the FOB and the Alamo.
Is this official admin policy? Last I checked currently if tad dies the PO can go do whatever. Get me a ruling from headmins on this please

2024-02-06 19:09 UTC, TiviPlus commented on code/datums/jobs/job/shipside.dm
> +		<b>Duty</b>: Pilot the Condor, a modular attack aircraft that provides close air support with a variety of weapons ranging from the inbuilt gatling to wing mounted rockets; or the Tadpole, a versat
Changed the choose but didnt remove the option lol

2024-02-06 19:09 UTC, TiviPlus commented
> > > This cannot be done due to how persistence works based off of job names. It would kill existing PO hours.
> > 
> > 
> > There are like only one person who cares about PO hours, Cassie is the only one who really would care
> 
> That does not matter, maintainers want to keep the hours so PO will stay named PO, no exceptions.

Like I said in discord this also ties to job bans so this is an admin issue

2024-02-06 19:10 UTC, TiviPlus commented
> > Do other roles can still pilot Tad with access on their id, or its going to be like a mech and its pilot?
> 
> They just need the access, yes. The only ones with tad access by default are the TO, FC and SLs.

I don't see you adding tad access to SLs here?

2024-02-06 23:12 UTC, breadhunt commented
> this is dumb

hard disagree, other than what foster already said this makes tad PO/cas PO significantly easier to balance (no more CSE/synth as PO+ for tad), streamlines pre-drop ("hey do we have a tad po? ok lemme check manifest")
there are a lot of benefits from this which make it worth adding -- significantly more so i would argue than roles like ST or CL

2024-02-07 22:34 UTC, Kuro020 approved these changes

2024-02-08 11:07 UTC, chizzy376 commented
> This has been tried a dozen times already and for whatever reason it always gets shot down.

Because walancers hate the idea of a PO officer being self sustainable
Look at Derrick's CSE jobban for example 😂

2024-02-08 19:44 UTC, bowlofcereal commented
> > This has been tried a dozen times already and for whatever reason it always gets shot down.
> 
> Because walancers hate the idea of a PO officer being self sustainable Look at Derrick's CSE jobban for example 😂
> 
> This is a good PR and the only reason you don't want it to get merged is because you HATE good change

![what](https://github.com/tgstation/TerraGov-Marine-Corps/assets/50346600/f129526a-7dc6-496b-8511-8ff9d22cc5e6)

2024-02-08 19:58 UTC, TiviPlus approved these changes

2024-02-08 19:59 UTC, merged