Reqtorio Expansion V 1.4
tgstation/TerraGov-Marine-Corps pull request #15045
Opened 2024-02-09 18:42 UTC by Naaanii

## About The Pull Request
Adds missing railgun ammo, SR-127 flak ammo, deployable floodlights and deployable cameras to reqtorio.
Reworks the drop pod recipe into a generic equipment recipe. (Recipe unchanged)

## Why It's Good For The Game
More stuff, more fun.

## Changelog

:cl:
add: Added HVAP and smart railgun rounds to reqtorio.
add: Added SR-127 flak ammo to reqtorio.
add: Added deployable floodlights to reqtorio.
spellcheck: Added a missing period to drop pod factory description.
/:cl:

2024-02-09 21:02 UTC, Woker2004 commented
C4 reqtorio when? but jokes aside it is decently nice. though the deployable floodlights are by far the best one added here

2024-02-09 21:14 UTC, Naaanii commented
> C4 reqtorio when? but jokes aside it is decently nice. though the deployable floodlights are by far the best one added here

I can add that to this actually.

2024-02-09 21:59 UTC, Woker2004 commented
> I can add that to this actually.

holy based

2024-02-09 22:25 UTC, Kuro020 approved these changes

2024-02-09 22:32 UTC, TellyLsc commented
reqtorioing floodlights and using them as glorified flares until xenos complain that the map is too bright

2024-02-10 04:39 UTC, FosterGrime-Heymynameslouie commented
would also adding sandbags to reqtorio be alright?
cool pr nonetheless speedmrhg

2024-02-10 12:16 UTC, TiviPlus commented on code/modules/factory/parts.dm
> +/obj/item/factory_part/railgun_hvap_magazine
```suggestion
	recipe = GLOB.railgun_magazine

/obj/item/factory_part/railgun_hvap_magazine
```

2024-02-10 12:16 UTC, TiviPlus commented on code/modules/factory/parts.dm
> +/obj/item/factory_part/railgun_smart_magazine
```suggestion
	recipe = GLOB.railgun_magazine

/obj/item/factory_part/railgun_smart_magazine
```

2024-02-10 12:16 UTC, TiviPlus requested changes
.

2024-02-11 09:29 UTC, Naaanii commented
> would also adding sandbags to reqtorio be alright? cool pr nonetheless speedmrhg

I don't think any form of cades or defences should be in reqtorio as neat as they would be to have.

2024-02-11 15:41 UTC, TiviPlus commented on code/modules/factory/unboxer.dm
>  /obj/item/factory_refill/minigun_powerpack_refill
```suggestion
	refill_amount = 20

/obj/item/factory_refill/minigun_powerpack_refill
```

2024-02-11 16:24 UTC, merged

2024-02-12 15:17 UTC, Woker2004 commented
Let us begin C4 trolling