Interactive emote fixes
tgstation/TerraGov-Marine-Corps pull request #15042
Opened 2024-02-09 04:46 UTC by XElectricX

## About The Pull Request

Fixes:
- Was adding the interaction to the list on the wrong mob, oops
- Clashing with hugs and headpats, now use a TGUI selection system when right clicking on help intent

## Why It's Good For The Game

We need our funny emotes working.

## Changelog

:cl:
fix: Fix interactive emotes
/:cl:

2024-02-09 04:48 UTC, XElectricX commented
Literally the same branch I was using what is wrong with you git.

2024-02-10 00:10 UTC, ivanmixo requested changes

2024-02-10 00:10 UTC, ivanmixo commented on code/_onclick/click.dm
> +	if(ismob(A) && a_intent == INTENT_HELP && Adjacent(A) && interaction_emote(A))
In the.. .fucking `RightClickOn`. Really?

2024-02-11 22:37 UTC, ivanmixo approved these changes
Prob fine

2024-02-20 23:55 UTC, merged

2024-02-21 04:07 UTC, Passe2142 commented
It sorta triggers when you wanna use an ability as xeno a pop up first then chains the ability. Would be cool if I could bind it to something else or toggle it on/off, pop up pain is real.