Newt expansion Part 1
tgstation/TerraGov-Marine-Corps pull request #15077
Opened 2024-02-12 06:08 UTC by Scarlet-Oduko

## About The Pull Request

Main Overview: Makes newt a playable job, along with making them a sub-type of human aka carbon. Lower health but faster then base speed, comes with inbuilt damage reduction for brute and burn since they won't be able to wear armor. Gear is restricted to outfit + they cannot shoot guns or operate any heavy weapons like a synth.

To-Do: Traits for gear so they delete/don't drop on delimb or gib. sprite adjustments, specie innate ability (a ranged one so they are not completely defenseless out of melee), special interaction with research analyzer

Planned: Part two of this expansion will be focused on digsite upgrades for newt and digsite stuff in general to make them more worthwhile.

## Why It's Good For The Game

Newt always had some basic function as an ai companion, expanding on this to be fully playable, and with the recent researcher changes, I thought I might as well also put some more content to encourage them to be used, this is part one of an overall content expansion for researchers to pad out digsites.

## Changelog

:cl:
add: makes newt playable, new species that comes with innate weaknesses and buffs, newt has an innate ranged ability
imageadd: Sprites associated with newt and their outfit

/:cl:

2024-02-12 06:15 UTC, thatguythere03 commented
![fitzshollsealofquality](https://github.com/tgstation/TerraGov-Marine-Corps/assets/53490682/5ce3f016-c285-40c6-b8dc-e53190da6cc5)

2024-02-12 06:16 UTC, Scarlet-Oduko commented
> ![fitzshollsealofquality](https://private-user-images.githubusercontent.com/53490682/303980118-5ce3f016-c285-40c6-b8dc-e53190da6cc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MTg4NTEsIm5iZiI6MTcwNzcxODU1MSwicGF0aCI6Ii81MzQ5MDY4Mi8zMDM5ODAxMTgtNWNlM2YwMTYtYzI4NS00MGM2LWI4ZGMtZTUzMTkwZGE2Y2M1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDA2MTU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViNDI3MmI0ZDViYmNjOWY0NTA2YmE5Yjc3MThkN2Y0MDNjMWFiNzFhOTY5N2RmYjMyZjA2MjA2MDVjMTZkMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hrLUYHGxQ9yJ_WAab59yrYaK16WarAyZpqGWp2yj4Hc)

oh yeah, couldn't have done it without fitz, they provide all the sprites.

2024-02-12 12:40 UTC, Woker2004 commented
I do not know why I thought I was looking a Sybil github for a second, but I think it'd be a nice change for more variety, although that would make newt more up to date than AI, which is funny

2024-02-12 13:22 UTC, FosterGrime-Heymynameslouie commented
wait a minute, would there be multiple newts since its now considered a job or would it only be locked to one?

also the thought of having a researcher and newt  combo ala a man and his dog is really cool
(dear God I jusr realized the kind of worse case scenario players whod main newt to be like)

2024-02-12 16:40 UTC, Scarlet-Oduko commented
> wait a minute, would there be multiple newts since its now considered a job or would it only be locked to one?
> 
> also the thought of having a researcher and newt combo ala a man and his dog is really cool (dear God I jusr realized the kind of worse case scenario players whod main newt to be like)

It’s only locked to one, much like the FC and such.

2024-02-12 19:08 UTC, Scarlet-Oduko commented
> I would make this so it's not combat focus but like roleplay focused if anything, similar to the one civie role or what not

All Corporate liaison does is shout propaganda, if people treat newt as a frontline dive xenos to get kills I’ll address it as I see it. Right now Newt is just speed and melee. Meant to help protect their savior the medical researcher.

they will be getting support stuff and all. They’re just a companion for researcher

2024-02-12 19:28 UTC, Woker2004 commented
> All Corporate liaison does is shout propaganda, if people treat newt as a frontline dive xenos to get kills I’ll address it as I see it. Right now Newt is just speed and melee. Meant to help protect their savior the medical researcher.
> 
> they will be getting support stuff and all. They’re just a companion for researcher

Just make newt only have like 5 melee damage, newt was added as a meme and should stay like one, though you could allow newt to understand xenos I guess? But if you want a fast melee person be bio light armor vali sword

2024-02-12 19:38 UTC, Scarlet-Oduko commented
> > All Corporate liaison does is shout propaganda, if people treat newt as a frontline dive xenos to get kills I’ll address it as I see it. Right now Newt is just speed and melee. Meant to help protect their savior the medical researcher.
> > they will be getting support stuff and all. They’re just a companion for researcher
> 
> Just make newt only have like 5 melee damage, newt was added as a meme and should stay like one, though you could allow newt to understand xenos I guess? But if you want a fast melee person be bio light armor vali sword

Very weird reasoning, the whole point is to make newt something more then they were. Just because something’s a ‘meme’ doesn’t mean it has to stay one. Nor should it in my opinion

2024-02-12 20:56 UTC, Woker2004 commented
> the whole point is to make newt something more then they were. Just because something’s a ‘meme’ doesn’t mean it has to stay one. Nor should it in my opinion

Newt, was never spouse to even be combat based, he was just a meme to be there and ultimately just stay shipside, I'd just remove to combat aspect, we already have melee, that is more significant than what your planning here, also it should really stay as roleplay

2024-02-12 21:08 UTC, SzkieletorNutric commented
Don't you fuckin' do it...

2024-02-12 21:15 UTC, Scarlet-Oduko commented
> > the whole point is to make newt something more then they were. Just because something’s a ‘meme’ doesn’t mean it has to stay one. Nor should it in my opinion
> 
> Newt, was never spouse to even be combat based, he was just a meme to be there and ultimately just stay shipside, I'd just remove to combat aspect, we already have melee, that is more significant than what your planning here, also it should really stay as roleplay

Agree to disagree, concepts change, this is a tdm server. This is a flavor thing even if they’re combat capable. I have much planned and I don’t intend to stop unless a maintainer tells me to. I don’t care what’s seen as a meme. Quite frankly it’s better to make it more then a meme. We come for the wacky content by god I’m gonna give it to the people! Viva la newt.

2024-02-12 21:26 UTC, SzkieletorNutric commented
> digsite stuff in general to make them more worthwhile

Digsites have always been more than worthwhile. The improvement they require instead is additional, unique and functional content in the form of implants and equipment that benefits the entire marine force, not gimmicks that are locked to a literal department pet and a role separate from the Researcher.

The bottom line is, when an admin takes over a pet just for the sake of pulling a joke and being a meme - it's actually funny and 'wacky'.
When you suggest to make an animal into a whole separate role and glue to it vague promises of functions that will potentially influence the overall balance of the game, it is anything but.

2024-02-12 21:32 UTC, Woker2004 commented
> When you suggest to make an animal into a whole separate role and glue to it vague promises of functions that will potentially influence the overall balance of the game, it is anything but.

Basically stole the words out of my mouth

2024-02-12 21:38 UTC, Woker2004 commented
Just not trying to be mean or anything, but odds are this will get closed when you PR it, maybe on another station like TG station or monkeystation wouldn't mind it, but as a Team Deathmatch server it kinda doesn't fit

2024-02-12 21:39 UTC, Scarlet-Oduko commented
You misunderstand this then, this is a completely serious PR and not meant to be ‘haha newt’. If you’re not going to give proper feedback for what I’m doing and simply trying to bash the thing as a meme then I’m just not gonna continue this conversation. I have a lot planned. 

I even stated that I would be expanding digsites with not just newt content, So have a good day.

2024-02-12 21:43 UTC, Woker2004 commented
There really isn't much to say about it feedback wise, it's just a pet that stays shipside

2024-02-14 20:11 UTC, Scarlet-Oduko commented
> Please add Gourmand as a playable variant.

That’ll most likely come in part two, I plan on making digsite rewards for both newt and marines, and the newt rewards will most likely be flavored around all the other cats like artificer getting bombs

2024-02-16 19:38 UTC, Ragecrabbo commented
Neat idea though kind of a weird addition to the game. Hopefully this will see light of day although i wonder what their niche will be to seperate them from other support roles such as synth.

2024-02-16 21:09 UTC, Scarlet-Oduko commented
> Neat idea though kind of a weird addition to the game. Hopefully this will see light of day although i wonder what their niche will be to seperate them from other support roles such as synth.

Right now there a little companion for researchers to help keep them safe/company when moving towards digsites. I plan on expanding researcher content as a whole once this is (hopefully) merged. Which will flesh out newts role based on equipment that will be able to be given to them. Based on the slugs from the game.

2024-03-16 19:07 UTC, Kuro020 approved these changes

2024-03-16 19:57 UTC, RipGrayson approved these changes

2024-03-17 21:04 UTC, Lumipharon requested changes
there's uh, a lot of snowflake here

2024-03-17 21:04 UTC, Lumipharon commented on code/modules/mob/living/carbon/human/species.dm
> +	brute_mod = 0.8 //some innate brute defense so they have some protection
less health but then they just have sythn dam reduction anyway to make up for it

2024-03-17 21:04 UTC, Lumipharon commented on code/modules/organs/limbs.dm
> +		return update_icon()
as before I don't see why this is needed

2024-03-17 21:04 UTC, Lumipharon commented on code/modules/power/cell.dm
> +			return
stahp. I'm not going to mark every but if snowflake, you get the idea

2024-03-17 21:04 UTC, Lumipharon commented on code/datums/actions/species_actions/catslug_action.dm
> +	newspear.fire_at(target, X, X, newspear.ammo.max_range)
So you have a nodrop spear, and you don't actually throw you spear you just summon a magic projectile version?

2024-04-02 00:39 UTC, closed without merging