Sentinel nade is now transparent
tgstation/TerraGov-Marine-Corps pull request #15070
Opened 2024-02-12 00:25 UTC by Barnet2

## About The Pull Request
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/20828943/88deaf81-2521-4ce3-bb24-014d4a222790)
You can now see through it woohoo

## Why It's Good For The Game
Sent primo is arguably the best in the game, gives a T1 a spammable, high damage gas that has no risk. The main benefit of gas is as a smoke screen that blocks LoS, given all the other benefits it has it should not block vision.

## Changelog

:cl:
balance: Sentinel gas nade is now transparent (you can see through it)
/:cl:

2024-02-12 00:30 UTC, Zangeiti commented
**I LOVE GAS SPAM I LOVE GAS SPAM I LOVE GAS SPAM!!!!!!!!!!11**

2024-02-12 00:32 UTC, Kuro020 approved these changes

2024-02-12 02:10 UTC, QualityVan requested changes
Should remove hugger pacify if it's translucent.

2024-02-13 00:05 UTC, Lumipharon approved these changes

2024-02-13 00:05 UTC, merged