Conveyor code improvement
tgstation/TerraGov-Marine-Corps pull request #15085
Opened 2024-02-13 09:37 UTC by Lumipharon

## About The Pull Request
Code improvement to some funny conveyor code to be less guh.
Removes some unused and/or broken code, and generally cleans up a bit.

Originally I was going to change how conveyors worked but then decided that the overall effect would look worse so, just a refactor.

## Why It's Good For The Game
Less shitty code.

## Changelog

:cl:
code: Cleaned up some conveyor code
/:cl:

2024-02-17 18:27 UTC, TiviPlus requested changes

2024-02-17 18:27 UTC, TiviPlus commented on code/modules/recycling/conveyor2.dm
> +	to_chat(user, span_notice("You set [src]'s direction [conveyor_flags & CONVEYOR_INVERTED ? "backwards" : "back to default"]."))
balloon alert?

2024-02-17 18:27 UTC, TiviPlus commented on code/modules/recycling/conveyor2.dm
> +		return //how
shouldnt some of these be returning PROCESS_KILL

2024-02-17 18:27 UTC, TiviPlus commented on code/modules/recycling/conveyor2.dm
> +	var/turf/locturf = loc
dunno why locturf is cast

2024-02-17 18:27 UTC, TiviPlus commented on code/modules/recycling/conveyor2.dm
> +/obj/machinery/conveyor/proc/update()
autodoc?

2024-02-19 07:23 UTC, Lumipharon commented on code/modules/recycling/conveyor2.dm
> +	var/turf/locturf = loc
leftover thing

2024-02-23 20:37 UTC, TiviPlus approved these changes

2024-02-23 20:37 UTC, merged