Crusher sunder buff
tgstation/TerraGov-Marine-Corps pull request #15144
Opened 2024-02-19 16:29 UTC by Barnet2

## About The Pull Request
Crusher sunder recovery doubled (0.5 base to 1 base)
Sunder max of 50

## Why It's Good For The Game
I won't sit here and deny that Crusher is a great caste. However, as one of the namely 3 castes that have a lot of armor (queen, king and crusher) it has a weird relation with health, range and armor. Queen and King both have a good chunk more health to rely on, namely. However one thing they have that Crusher does not is a semblance of range. King can operate with Roar, Petrify and Off-guard. Queen obviously has spit and scree. Crusher is only melee with a highly telegraphed charge for moving in and out of combat. Given that Crusher is melee and relies more on armor than health, a sunder max is justified so that Crusher will keep usefulness without having to be out of combat for ten years healing sunder, whereas Queen can still spit and King can still roar.
Crusher sunder recovery is not necessary but I think it would be good to have for the same reasons as above, if it's too much I can just go with the sunder max.

## Changelog

:cl:
balance: Crusher has a sunder max of 50% and double sunder recovery
/:cl:

2024-02-19 17:47 UTC, Naaanii commented
Double buff is kinda iffy and pools exist. I think sunder cap is kind of neat but also the stronger buff.

2024-02-19 18:57 UTC, Arkansas-Bar-Association commented
Max sunder of 50% is crazy, I understand regenerating fast but that's just gonna make crushers very oppressive

2024-02-19 23:05 UTC, Arturlang commented
50% max already means you half of your ehp, crusher is very reliant on having armor, alternative could be hard armor

2024-02-19 23:11 UTC, Barnet2 commented
> 50% max already means you half of your ehp, crusher is very reliant on having armor, alternative could be hard armor

There should still be a way to make the Crusher weaker, but not useless.

2024-02-20 05:41 UTC, AusarAtkin commented
Isnt 50 sunder max a bit too much?, and why not just give it defender's ability instead to heal sunder in a pinch?

2024-02-20 07:11 UTC, Looking4bros commented
Hmmmm, Perhaps a reduction in Melee armor to 75 would be a fitting counterbalance...

2024-02-20 13:20 UTC, MiniMeatwad commented
I've found 60% sunder was just right to make just about any non-AP weapon capable of killing a crusher.

2024-02-20 22:27 UTC, novaepee commented
xeno golden age

2024-02-20 22:58 UTC, Woker2004 commented
the buff crusher needs is clearly diagonal charge due to caves :clueless:

2024-02-23 01:52 UTC, Kuro020 commented
you should edit the tittle and stuff to reflect the changes

2024-02-26 17:25 UTC, TiviPlus requested changes

2024-02-26 17:25 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
> +	sunder_multiplier = 0.5 //takes half sunder
```suggestion
	sunder_multiplier = 0.5
```

2024-02-26 17:25 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
> +	sunder_multiplier = 0.8 //takes 80% sunder
```suggestion
	// *** Sunder *** //
	sunder_multiplier = 0.8
```

2024-02-26 20:25 UTC, merged