bunch of defib code improvements
tgstation/TerraGov-Marine-Corps pull request #15155
Opened 2024-02-21 06:07 UTC by Neocloudy

# I highly doubt this is ready at all. I'm opening this at 12am and just wanna be done with it. Maybe TM after code is approved/fixed.
## About The Pull Request
Defibrillators have had a lot of code changes. I'm opening this at 12am and wanna be done. So this likely has a couple issues.
- `check_revive` proc because I genuinely hate looking at defibs and seeing two big blocks for every reason someone can be unrevivable.
- shock cooldown separated, so now you can shock instantly after turning on the defib
- examining the defib shows how many uses are left
- defib icons reworked, now use overlays instead of having an icon state for absolutely every possible defib state
- dmdoc
- new defib charge/release sounds (from CM-SS13)

## Why It's Good For The Game
Code improvements and QoL are both really good for coders and players.

## Changelog

:cl:
qol: examining a defibrillator shows how many uses are left
code: check_revive proc for defibs, may cause issues
code: defibrillator sprites now use overlays
soundadd: new defib release and defib charge sounds (from CM-SS13)
/:cl:

2024-02-21 14:03 UTC, QualityVan requested changes
Sound files are being uncooperative and not downloading properly, though that might be on my end. Charge doesn't sound any different as far as I can tell.

2024-02-21 16:27 UTC, Neocloudy commented on code/game/objects/items/defibrillator.dm
> +	defib_heal_amt *= skill * 0.5 //more healing power when used by a doctor (this means non-trained don't heal)
yes, that's probably how it was supposed to work but there was an `else` making it not apply unless you weren't fumbling

2024-02-21 16:28 UTC, Neocloudy commented on code/game/objects/items/defibrillator.dm
> +	if(!check_revive(H, user))
i am not sure either, but originally, there was a big list of if checks for before shocking and right when you shock them.

maybe they perma mid defib? idk.

2024-02-21 17:31 UTC, Neocloudy commented
> Sound files are being uncooperative and not downloading properly, though that might be on my end. Charge doesn't sound any different as far as I can tell.

unironically a case of works on my machine (i was able to download defib_release.ogg fine, but idk)

charge sound should be slightly better quality and slightly lower volume

2024-02-22 17:48 UTC, QualityVan requested changes

2024-02-22 17:48 UTC, QualityVan commented on code/game/objects/items/defibrillator.dm
> +/obj/item/defibrillator/update_icon()
You kind of missed what I was saying here. Icon state changes should go in an update_icon_state, overlay changes should go in an update_overlays, and neither of those two should be called directly.

2024-02-22 17:48 UTC, QualityVan commented on code/game/objects/items/defibrillator.dm
> -*/
Left this deleted.

2024-02-22 17:48 UTC, QualityVan commented on code/game/objects/items/defibrillator.dm
> +	defib_heal_amt *= skill * 0.5 //more healing power when used by a doctor (this means non-trained don't heal)
SLs fumble since they only have novice med skill. Either way, balance change, keep it separate.

2024-02-22 17:48 UTC, QualityVan commented on code/game/objects/items/defibrillator.dm
> +	SHOULD_CALL_PARENT(FALSE)
Absolutely not. Once you figure out the proper way to handle appearance for defib, you should have a better way to do this.

2024-02-23 02:32 UTC, Neocloudy commented
it should be ready for review again, but i have a weird check in so defib gloves won't get the overlay updates. i don't know how *else* to solve it so i'm open to a better idea :D

2024-03-03 01:41 UTC, QualityVan approved these changes
Sorry for the delay. I've been trying to figure out a way to handle child overlays here which isn't awful, and have so far only managed to come up with bad options. However, now Lumi's making #15246 so that gets solved.

Still needs approval from @Kuro020 for art and someone who can actually check the sound files to make sure they're fine and also permitted to use in terms of licensing.

2024-03-03 03:09 UTC, Lumipharon requested changes

2024-03-03 03:09 UTC, Lumipharon commented on code/game/objects/items/defibrillator.dm
> +				overlays += "+full"
bro why are you making this + instead of _ ?

2024-03-05 10:11 UTC, ivanmixo approved these changes

2024-03-05 11:50 UTC, Neocloudy commented
marge conflict will be fixed next time i'm at my computer, probably night or maybe afternoon in the us

2024-03-09 15:51 UTC, QualityVan commented on code/game/objects/items/defibrillator.dm
> +/obj/item/defibrillator/internal/update_icon_state() // we have to do some messing around for the glove sprites to update
This can all just be in the glove iconstate stuff instead.

2024-03-11 11:28 UTC, Lumipharon requested changes

2024-03-26 00:38 UTC, closed without merging