Adds a accuracy malus to Puppeteer and Widow minions
tgstation/TerraGov-Marine-Corps pull request #15166
Opened 2024-02-22 06:26 UTC by Barnet2

## About The Pull Request
Instead of a 70% chance to hit a selected limb, widow and puppet minions now have a 5% to hit. Accuracy for Widow, Puppeter and all other castes have not been changed.
## Why It's Good For The Game
Widow and Puppeteer can use their minions as disposables to get free chest fracs. With this change they have to actually get into the fray, and even with that the free fractures won't be so free anymore. Their extremely low TTK has not changed, just less chance for more permanent forms of damage in exchange.
## Changelog
:cl:
balance: Widow and Puppeteer minions have a 5% chance to hit their selected limb (chest) instead of a 70% chance.
/:cl:

2024-02-22 15:07 UTC, MiniMeatwad commented
Might be more like 24.5%, but yeah

2024-02-22 20:15 UTC, blackdav123 commented
I think it would make more sense as a 1/6 chance to hit so that the targeted limb is equally likely to be hit instead of less likely.

2024-02-26 02:13 UTC, Kuro020 approved these changes

2024-02-26 17:04 UTC, TiviPlus requested changes

2024-02-26 17:04 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
> +	var/accuracy_malus = 0
if it shouldnt go over 70 why not add a sanity unit test

2024-02-26 20:25 UTC, merged