Boiler Root Removal
tgstation/TerraGov-Marine-Corps pull request #15170
Opened 2024-02-23 03:06 UTC by Barnet2

## About The Pull Request
Removes being needed to root to fire.

## Why It's Good For The Game
There was actual genuine balance concerns to giving Boiler root, but it made the caste even more unfun to play with. There are other variables we can change about Boiler to keep it fun; the addition of antigas nades is one, we can also look at caste limits and the glob itself. There were many things to try before putting in Root, which I think most can agree is extremely unfun.

## Changelog

:cl:
balance: Boiler no longer has to root to fire
/:cl:

2024-02-23 07:54 UTC, Zangeiti commented
we love gas spam in this house

2024-02-23 18:43 UTC, Looking4bros commented
Cades are vestigial structures left over from early development.

2024-02-23 19:52 UTC, Woker2004 commented
As a boiler player, I don't think root should be killed, it's just the rooting/uprooting speed in my opinion

2024-02-23 20:08 UTC, Woker2004 commented
I do think thar we should buff prae if this gets Merged in my opinion

2024-02-23 21:44 UTC, Wisemonster commented
Ya'll realize this will only go through if the pr making anti-gas nades more available/cheaper goes through, right? I'd be glad to see boiler root go simply cause it makes an already easy to catch caste (speed-wise) a joke against any kind of sniper or diving vali user if they are caught with their pants down (rooted).

2024-02-23 22:17 UTC, SimplySmiley123 commented
> Ya'll realize this will only go through if the pr making anti-gas nades more available/cheaper goes through, right? I'd be glad to see boiler root go simply cause it makes an already easy to catch caste (speed-wise) a joke against any kind of sniper or diving vali user if they are caught with their pants down (rooted).

At the same time barely anyone really wants to deal with even more gas and something besides warlock cheesing any holds.

2024-02-24 07:24 UTC, timothymtorres commented
Boiler players switched to baneling so gas worries never really went away.

2024-02-24 19:52 UTC, Ragnuv commented
I would only be comfortable with this if the boiler range got cut down hard. Boiler root is hardly a problem when you're using a caste that can borderline outrange tac binocs and almost every gun marines have. If the problem with boiler is getting killed while rooted, just don't go melee range to root?

2024-02-26 02:13 UTC, Kuro020 approved these changes

2024-02-26 02:53 UTC, Woker2004 commented
A better solution would make the unrooting, not rooting, faster

2024-02-26 02:59 UTC, MiniMeatwad commented
> I would only be comfortable with this if the boiler range got cut down hard. Boiler root is hardly a problem when you're using a caste that can borderline outrange tac binocs and almost every gun marines have. If the problem with boiler is getting killed while rooted, just don't go melee range to root?

If you get CAS on you and you're rooted, you're dead no questions asked. Death is overwhelmingly punishing for xenos so it's not very fair lol

Maybe just make any damage cancel bombardments and drop the cooldown as if they'd fired anyways if you want to achieve a similar effect to root

2024-02-26 17:07 UTC, TiviPlus requested changes
rest lgtm

2024-02-26 17:07 UTC, TiviPlus commented on code/_globalvars/bitfields.dm
> +		"ABILITY_USE_BURROWED" = ABILITY_USE_BURROWED
readd comma

2024-02-26 20:23 UTC, TiviPlus approved these changes

2024-02-26 20:24 UTC, merged