GL-81 now fits attachments + Magharn now works for belt guns
tgstation/TerraGov-Marine-Corps pull request #15238
Opened 2024-03-02 00:18 UTC by blackdav123

## About The Pull Request
The single shot grenade launcher now fits the same attachments as the multi shot one (Magharn, rail flashlight, miniscope).

Additionally, guns that fit on the belt will now function properly with magharness (GL81, pepperball, MP-19, maybe more).

## Why It's Good For The Game
Consistency with the other GL, hopefully enabling loadouts to use this now that it has mag harness. Its a good side option for rushers to use and has a slightly slower fire rate of 1.25 seconds between grenades vs 1.2 on the GL70, so adding magharness should make it worth placing into loadouts.

As for the belt change, it seems inconsistent that guns can be used with mag harness on a slot that mag harness wont even work on so hopefully these niche guns can be a little more useful.

## Changelog

:cl:
balance: GL-81 can now fit magnetic harness, mini scope, and rail flashlight.
fix: Mag harness will now function properly for guns that equip to the belt slot.
/:cl:

2024-03-02 00:28 UTC, Xander3359 commented
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/66163761/69341a90-2dc4-4581-9336-41725ac545fc)

2024-03-02 18:27 UTC, ivanmixo commented
Why is this one PR. These changes have 0 relation to eachother and should be seperate.

2024-03-02 18:29 UTC, blackdav123 commented
> Why is this one PR. These changes have 0 relation to eachother and should be seperate.

found the bug while testing this and it was a very easy fix

2024-03-04 00:10 UTC, ivanmixo commented
Still 2 completely unrelated changes

2024-03-04 00:52 UTC, blackdav123 commented
> Still 2 completely unrelated changes

the bug affects two weapons and this one adds a third, I think its pretty reasonable to fix that in this PR

2024-03-04 08:41 UTC, ivanmixo commented
Split it up into two prs, atomisation

2024-03-05 10:09 UTC, ivanmixo commented
@Kuro020 judgement

2024-03-05 18:45 UTC, TiviPlus approved these changes
code ok

2024-03-13 04:00 UTC, Kuro020 requested changes
>scope
Very funny, but no, no GL with scopes

2024-03-14 01:03 UTC, Kuro020 approved these changes

2024-03-15 10:18 UTC, merged