addresses some issues
tgstation/TerraGov-Marine-Corps pull request #15249
Opened 2024-03-03 09:10 UTC by Xander3359

## About The Pull Request
Updates groundside humans post-TGUI check when capturing alamo (To address an alleged exploit)
Hijacking the alamo now greys out the "Capture The Alamo" button
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/66163761/ff30abcf-5f1a-4695-bbe8-ce1c560f4930)

Adds a check to be able to capture the alamo. If you hijack, you can no longer cap.

## Why It's Good For The Game

## Changelog

:cl:
fix: Xenos can no longer corrupt the alamo controls mid-transit
fix: Xenos can no longer capture the alamo mid-transit
/:cl:

2024-03-03 12:44 UTC, lbnesquik commented
Why is it good for the game? It sounds like a good thing to me for xenos to be able to back out.

2024-03-03 16:36 UTC, blackdav123 commented
> Why is it good for the game? It sounds like a good thing to me for xenos to be able to back out.

xenos can cap with all marines alive groundside by doing this

2024-03-03 17:11 UTC, lbnesquik commented
> > Why is it good for the game? It sounds like a good thing to me for xenos to be able to back out.
> 
> xenos can cap with all marines alive groundside by doing this

Ah! That's a very valid reason actually.

2024-03-05 10:09 UTC, ivanmixo requested changes
Undo whatever change was done to the rustg file

2024-03-05 16:26 UTC, ivanmixo approved these changes

2024-03-05 16:31 UTC, merged