scout droid fix port from rutgmc
tgstation/TerraGov-Marine-Corps pull request #15265
Opened 2024-03-04 08:10 UTC by coldironwarrior

## About The Pull Request

ports https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/186

## Why It's Good For The Game

scout droids are meant to grant nightvision. AI is meant to have restricted vision.
scout droids of current do not have nightvision. AI deploying to one then returning to core gives the AI nightvision.
bugs bad.

## Changelog
:cl:
fix: fix scout droids not having nightvision
fix: fixes AIs getting permanent nightvision after deploying to their scout droid
/:cl:

2024-03-05 10:18 UTC, ivanmixo requested changes
I'd rather not have vars being assigned a value then reassigned the value if the case is true.  Can't you just

```dm
/mob/living/silicon/ai/update_sight()
	if(HAS_TRAIT(src, TRAIT_SEE_IN_DARK))
		see_in_dark = max(see_in_dark, 8)
		lighting_alpha = LIGHTING_PLANE_ALPHA_MOSTLY_INVISIBLE
		eyeobj.see_in_dark = max(eyeobj.see_in_dark, 8)
		eyeobj.lighting_alpha = LIGHTING_PLANE_ALPHA_MOSTLY_INVISIBLE
		return ..()
	eyeobj.see_in_dark = initial(eyeobj.see_in_dark)
	eyeobj.lighting_alpha = initial(eyeobj.lighting_alpha)
	see_in_dark = initial(see_in_dark)
	lighting_alpha = initial(lighting_alpha) // yes you really have to change both the eye and the ai vars
	return ..()
```

2024-03-05 12:51 UTC, coldironwarrior commented
updated but untested atm, will re-request review after i get a chance to run it and make sure it works

2024-03-06 06:07 UTC, coldironwarrior commented
works on my machine or something, ready for re-review

2024-03-06 16:17 UTC, TiviPlus approved these changes

2024-03-07 07:58 UTC, ivanmixo approved these changes

2024-03-07 07:58 UTC, merged