Restores pre-root boiler dig mechanic
tgstation/TerraGov-Marine-Corps pull request #15341
Opened 2024-03-11 00:44 UTC by Barnet2

## About The Pull Request
Basically when you select bombard you take 3 seconds to dig in, but can move freely at any time during this. This was behavior removed with root that I forgot to bring back.

## Why It's Good For The Game
Should have been brought back with root removal to restore pre-root behavior.

## Changelog

:cl:
balance: Restores pre-root boiler dig mechanic, have to sit still and wait 3 seconds before firing a glob (you can still move, but cancels the channel)
/:cl:

2024-03-11 00:47 UTC, MiniMeatwad commented
Oh lol

2024-03-11 05:44 UTC, Xander3359 commented
Wait this whole time bombard had no channel? So boiler was giga buffed? LMAOOOOOOOO

2024-03-11 20:32 UTC, Lumipharon requested changes

2024-03-11 20:32 UTC, Lumipharon commented on code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
> +/mob/living/carbon/xenomorph/boiler/proc/set_bombard_pointer()
autodoc

2024-03-11 20:32 UTC, Lumipharon commented on code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
> +/mob/living/carbon/xenomorph/boiler/proc/reset_bombard_pointer()
autodoc

2024-03-11 20:32 UTC, Lumipharon commented on code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
> +		to_chat(X, span_notice("We relax our stance."))
don't use X

2024-03-11 21:24 UTC, Helg2 commented
> I believe that a caste like boiler, which can completely destroy marine cohesion, destroy cades and deal lethal damage OFFSCREEN should have a lot more risk.

If only the game had something like a marine high damage offscreen weapon, which is totally free, and with which marines totally cannot cooperate to kill xenos in a few seconds. HMMMMMMMMMMMMMM.

2024-03-11 22:11 UTC, mkvrs commented
> If only the game had something like a marine high-damaging offscreen weapon, which is totally free, and with which marines totally cannot cooperate to kill xenos in a few seconds. HMMMMMMMMMMMMMM.

Hmm yes...!
sr 127?
Sure it'll make them go away for a while, shooting at their general direction does that too.
But does it stop them from just ignoring the maybe one or two sniper rifle users that DO bother to target boilers? 
No it doesn't, they just peek out, bombard and repeat.
''and with which marines totally cannot cooperate to kill xenos in a few seconds.''
Please tell me what you would do, flank it? Go behind it?  These maps don't allow such things, xenos don't allow such things to happen. The only option left would be to bumrush the boiler which either results in marines getting obliterated by the hive or the boiler just running away in mach 5.

2024-03-11 22:46 UTC, Helg2 commented
> Please tell me what you would do

3 cooperated overcharged shots from the laser sniper rifle, will most probably obliterate the boiler. 
If you can't simply cooperate with others, this is simply a skill issue.
If you either can't flank the boiler, this is again a skill issue.

2024-03-11 22:49 UTC, coldironwarrior commented
if we do this, would it be possible (although i know it's not original behavior) to remove the wind-up from zoom?

root + zoom was 4 seconds to initiate; this + zoom is 4 seconds to initiate, and i feel like wind-up on zoom is goofy and all wind-up should be on bombard ability (as is here). i'd be down for the whole One Second less of prep time required too, adding dig back is pretty significant for counter-balancing already, i feel.

2024-03-11 23:04 UTC, mkvrs commented
> 3 cooperated overcharged shots from the laser sniper rifle, will most probably obliterate the boiler. If you can't simply cooperate with others, this is simply a skill issue. If you either can't flank the boiler, this is again a skill issue.

3 Laser users that somehow, wont FF and hit shots on the boiler at the same time without the boiler running away? They don't have root anymore, how will this work?
You will never see this, you won't see it happen with AMR's either.
And on the matter of flanking, please think about how they can see you before you see them.
The only viable and easily applicable solution to boilers ends up being artillery, which often gets cucked by the maps and co-operation
Though when it isn't cucked it kind of does the job.

2024-03-12 20:34 UTC, Lumipharon requested changes
Bruh, I said move it to the bottom, there are still other procs for the ability under where you've put it lol.

ALL existing proc definitions, then the new proc, then the related new boiler procs

2024-03-12 22:28 UTC, Kuro020 approved these changes

2024-03-12 22:31 UTC, Lumipharon approved these changes

2024-03-12 22:40 UTC, merged