Fix huggers for REAL
tgstation/TerraGov-Marine-Corps pull request #15391
Opened 2024-03-15 18:28 UTC by Kapu1178

## About The Pull Request
In my previous PR i claimed I made huggers prioritize orthogonal movement. I had a brainfart and mixed up Euclidean and Manhatten distance. This corrects my error.

## Changelog

:cl:
fix: Huggers *actually* prioritize orthogonal marines over diagonal marines.
/:cl:

2024-03-15 18:41 UTC, ivanmixo commented on code/__HELPERS/math.dm
> +/proc/get_dist_manhatten(atom/A, atom/B)
doc

2024-03-18 16:49 UTC, TiviPlus requested changes

2024-03-18 16:49 UTC, TiviPlus commented on code/__HELPERS/math.dm
> +/proc/get_dist_manhatten(atom/A, atom/B)
its spelled manhattan not manhatten

2024-03-18 18:24 UTC, Kapu1178 commented on code/__HELPERS/math.dm
> +/proc/get_dist_manhatten(atom/A, atom/B)
its so joever. fixed.

2024-03-19 20:23 UTC, Lumipharon approved these changes

2024-03-19 20:23 UTC, merged