Adds modulars to Jungle Outpost
tgstation/TerraGov-Marine-Corps pull request #15413
Opened 2024-03-18 03:47 UTC by blackdav123

## About The Pull Request

## Why It's Good For The Game

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2024-03-19 22:45 UTC, Lumipharon commented
Neat. One thing though, I notice on at least one modular area, you've chosen to make the stairs outside of the modular itself? seems kinda cursed to do it that way.

2024-03-22 18:47 UTC, TiviPlus approved these changes

2024-03-22 18:47 UTC, TiviPlus commented on code/game/area/campaign_maps/jungle_outpost.dm
>  /area/campaign/jungle_outpost/outpost/medbay
```suggestion
	icon_state = "bar"

/area/campaign/jungle_outpost/outpost/medbay
```

2024-03-23 16:39 UTC, RipGrayson requested changes
I'm not sure why checks aren't failing, but your hydro modulars have an improper type that needs corrected. Otherwise mapping looks fine.

2024-03-23 17:46 UTC, merged