"Improves" the hypersleep bay console code some more
tgstation/TerraGov-Marine-Corps pull request #15474
Opened 2024-03-27 00:24 UTC by lbnesquik

## About The Pull Request
This time, we removed the GLOB.blablaba spam and replace it with list reference.
Should be much more readeable now. It also checks lists fewer times, meaning it should be better with large amounts of gear.
Also, slight typo correction.

Associated list will come later, when I got the energy to learn something new. 

## Why It's Good For The Game
Code improvements

## Changelog

:cl:
code: Improved Hypersleep bay code further
/:cl:

2024-03-30 08:44 UTC, TiviPlus requested changes

2024-03-30 08:44 UTC, TiviPlus commented on code/game/objects/machinery/cryopod.dm
> +		active_glob_cryo_items_list -= I;
```suggestion
		active_glob_cryo_items_list -= I
```

2024-03-30 08:44 UTC, TiviPlus commented on code/game/objects/machinery/cryopod.dm
> +	active_glob_cryo_items_list -= I;
```suggestion
	active_glob_cryo_items_list -= I
```

2024-04-02 02:36 UTC, Lumipharon requested changes
you don't need a var. When I said a single list, I meant a single GLOB list of lists. So instead of all this if(DRUGS) list = blah stuff, you just ref GLOB.CRYOSTUFF[DRUGS]

2024-04-02 16:31 UTC, lbnesquik commented
> you don't need a var. When I said a single list, I meant a single GLOB list of lists. So instead of all this if(DRUGS) list = blah stuff, you just ref GLOB.CRYOSTUFF[DRUGS]

Yeah I figured sort of what you meant, I just pushed this out last week to quickly fix those issues.

2024-04-14 00:45 UTC, closed without merging