Whistle now makes every human in range warcry
tgstation/TerraGov-Marine-Corps pull request #15485
Opened 2024-03-28 11:38 UTC by Barnet2

## About The Pull Request

https://github.com/tgstation/TerraGov-Marine-Corps/assets/20828943/9353a204-8f20-4a8b-8325-24287f540243

## Why It's Good For The Game
It's FUN. Also code improvement.

## Changelog

:cl:
add: Whistle makes every human in range do the *warcry emote
/:cl:

2024-03-28 15:53 UTC, MLGTASTICa commented
Xenos will be crippled after this massive marine buff gets merged.

2024-03-29 21:28 UTC, TiviPlus commented on code/game/objects/items/whistle.dm
> +		TIMER_COOLDOWN_START(src, COOLDOWN_WHISTLE_WARCRY, 15 SECONDS)
```suggestion
	else
		TIMER_COOLDOWN_START(src, COOLDOWN_WHISTLE_WARCRY, 15 SECONDS)
		for(var/mob/living/carbon/human/human in get_hearers_in_view(warcryrange, user.loc))
			human.emote("warcry")

	TIMER_COOLDOWN_START(src, COOLDOWN_WHISTLE_BLOW, 3 SECONDS)
```

2024-03-29 21:28 UTC, TiviPlus requested changes

2024-03-29 21:28 UTC, TiviPlus commented on code/game/objects/items/whistle.dm
> +	var/warcryrange = 9
also autodoc

2024-03-30 08:34 UTC, merged