Campaign mission: Raiding Base
tgstation/TerraGov-Marine-Corps pull request #15500
Opened 2024-03-29 02:00 UTC by Lumipharon

## About The Pull Request
New mission, just for TGMC until I have a map for the SOM to use.

TGMC forces are trying to assault a SOM base hidden in TG territory that has been raiding their supply lines.
As the base is underneat a mountain, the TGMC are aiming to deploy a orbital beacon into the base itself. If they can defend it long enough, an orbiting destroyer will launch a precision guided, bunker busting missile to blow up the base, disabling it for good.

SOM forces need to repel the TGMC forces from their base and if necessary, C4 any orbital beacon deployed before target lock is aquired.

Marines have three beacons, so lose if they run out of time, beacons, or manpower.

Added callback functionality to the deployable item component to add extra checks for deploying (in the case of this pr, we specify a set of areas the beacon can be deployed in, which you can check by examining the beacon).

Fixed a random door not being opaque when it should be. Also fun fact: If a double door dir is specified as 2 instead of 1, it fucks up the opacity and it will only be opaque on one tile. wew.

## Why It's Good For The Game
New mission gud.

## Changelog

:cl:
add: Campaign: Added a new mission - Raiding Base for TGMC
/:cl:

2024-03-30 09:17 UTC, TiviPlus requested changes

2024-03-30 09:17 UTC, TiviPlus commented on code/datums/components/deployable_item.dm
> +		deploy_check_callback = _deploy_check_callback
why the if though

2024-03-30 09:17 UTC, TiviPlus commented on code/datums/gamemodes/campaign/missions/raiding_base.dm
> +///Makes the bang
Not a very descriptive autodoc

2024-03-30 09:43 UTC, Lumipharon commented on code/datums/components/deployable_item.dm
> +		deploy_check_callback = _deploy_check_callback
I have no idea

2024-03-30 09:44 UTC, Lumipharon commented on code/datums/gamemodes/campaign/missions/raiding_base.dm
> +///Makes the bang
updated

2024-03-30 16:24 UTC, RipGrayson requested changes
![carp6](https://github.com/tgstation/TerraGov-Marine-Corps/assets/49290523/52849617-5cad-4792-9ffc-609ab5411838)
This is really the only outright mapping error I see here, otherwise approved.

2024-03-31 14:55 UTC, RipGrayson approved these changes

2024-03-31 21:36 UTC, merged