Expands Valhalla With A Vehicle Area, Adds Assault Vehicle Category to Valhalla Req Vendor
tgstation/TerraGov-Marine-Corps pull request #15564
Opened 2024-04-04 03:47 UTC by Wisemonster

## About The Pull Request
Expands Valhalla with an area for testing vehicles (currently only the tank), and adds a vehicle ammo category to the valhalla req vendor, currently only contains the tank ammo. Requires the tank elevators/vendor pr to be merged before the tanks can actually be spawned in there by non-admin players.

## Why It's Good For The Game
Prepares Valhalla for testing Assault vehicles whenever they are fully merged.

## Changelog

:cl:
add: Expanded west side of Valhalla with an assault vehicle area
add: Added an Assault Vehicle category to the Valhalla requisition vendor; added tank ammo to said category
/:cl:

2024-04-04 03:48 UTC, Wisemonster commented
Note: the picture was before I added a bunch of cosmetic oil splatters around the assault vehicle area.

2024-04-04 21:35 UTC, Wisemonster commented
Ok, it looks like I might have to replace the lattices next to the rwalls on the z-level, cause otherwise it's runtiming

2024-04-05 01:35 UTC, Wisemonster commented
Ok, turns out what the linter means by neighbor is something on the same tile, so I just gotta fix some lattices on the same tiles as the walls

2024-04-07 10:38 UTC, TiviPlus requested changes
Tank vendor currently only supports one vend of assault/non assault and this is shared globally

2024-04-07 10:38 UTC, TiviPlus commented on code/game/objects/machinery/vending/marine_vending.dm
>  		),
```suggestion
		),
```

2024-04-07 10:38 UTC, TiviPlus commented on code/game/objects/machinery/vending/marine_vending.dm
> +		"Assualt Vehicle" = list(
```suggestion
		"Assault Vehicle" = list(
```

2024-04-07 14:43 UTC, Wisemonster commented
Alright. I could place a tank in the area as a sort-of quick fix, or I could wait until multiple assault vehicles are spawnable then update the area with the tank vendor.

2024-04-08 21:15 UTC, Wisemonster commented
> Tank vendor currently only supports one vend of assault/non assault and this is shared globally

To clarify, you mean the tank vendor connected to the elevator, not the tank parts vendor, right?

2024-04-14 08:23 UTC, TiviPlus commented
> > Tank vendor currently only supports one vend of assault/non assault and this is shared globally
> 
> To clarify, you mean the tank vendor connected to the elevator, not the tank parts vendor, right?

Uhh wdym they're the same thing, but theres a globally tracked "this vehicle has been vended"

2024-04-14 08:24 UTC, TiviPlus commented
You can do the place a few tanks workaround as a lazy fix and people blowing them up can cope but it should be changed eventualy

2024-04-14 15:14 UTC, Wisemonster commented
Alright, updated pr to add a couple of tanks to the area, along with the parts for the tanks' primary and secondary slots. Removed the fabricator cause it's not going to do anything except maybe cause problems for living assault/transport crewmen till multiple vehicle elevators can exist.

2024-04-20 18:29 UTC, TiviPlus approved these changes

2024-04-20 18:30 UTC, TiviPlus commented
@RipGrayson

2024-04-20 23:38 UTC, RipGrayson requested changes
Please move this carp somewhere else, two tiles away from any walls/windows or Valhalla's interior
![carp7](https://github.com/tgstation/TerraGov-Marine-Corps/assets/49290523/5b18d9d3-18bd-45a3-9ac7-ce30ca9fbc94)
You have space tiles here
![carp8](https://github.com/tgstation/TerraGov-Marine-Corps/assets/49290523/4ed6d949-bfcc-4d6f-bbcc-f8fa5958b606)

2024-04-20 23:54 UTC, Wisemonster commented
Alright, moved the carp and replaced the space tiles

2024-04-21 02:24 UTC, merged