Increases RG 220 wield delay
tgstation/TerraGov-Marine-Corps pull request #15592
Opened 2024-04-06 15:20 UTC by Yttriums

## About The Pull Request
ided pr
Increases RG 220 wield delay from 1.2 to 2.4 seconds.

## Why It's Good For The Game

Currently, RG 220 is a very powerful operational weapon which easily farms early kills and snowballs the game for marines. 

Because it's wield time is significantly shorter than other weapons of it's size/strength, it's incredibly safe to run as a primary weapon - you can wield it quickly out of stuns and force xenos off of you with a single shot.

This change forces RG220 users to carry a backup weapon or consider their positioning more carefully, similar to other weapons of it's caliber.

## Changelog

:cl:
balance: Increased RG220 wield delay from 1.2 to 2.4 seconds
/:cl:

2024-04-06 22:10 UTC, Lumipharon commented
This comes back to it being a real poor idea to give it more than one shot per reload.

2024-04-07 01:26 UTC, Yttriums commented
> This comes back to it being a real poor idea to give it more than one shot per reload.

Maybe true. Still, marines shouldn't be power cleaning this weapon up to their shoulders in less time than an HPR

2024-04-07 11:32 UTC, Naaanii commented
It already has a high fire delay and can't be used really well with other weapons because of said fire delay. (Funny juggle PR). You're better off removing the extra shots per mag.

2024-04-07 14:00 UTC, Yttriums commented
> It already has a high fire delay and can't be used really well with other weapons because of said fire delay. (Funny juggle PR). You're better off removing the extra shots per mag.

My point about using a backup weapon has nothing to do with juggling - the point is that you can fire this large, heavy weapon too quickly out of getting stunned. You shouldn't be able to wake up from a stun/knockdown and use this within 1 second - it's a man-sized railgun. You should have to reach for a secondary.

I'm not interesting in nerfing the weapon into the ground - I just want it to play like a heavy weapon.

2024-04-07 15:51 UTC, Kuro020 requested changes
2.4 is too much, make it 2.0 and we'll see

2024-04-07 17:12 UTC, lbnesquik commented
I think we can give it a try.

2024-04-09 15:14 UTC, TiviPlus approved these changes

2024-04-12 04:01 UTC, merged