Bring back banelings as minions
tgstation/TerraGov-Marine-Corps pull request #15612
Opened 2024-04-08 17:57 UTC by BraveMole

## About The Pull Request

Banelings are back. No more pod, it is a minion, if it dies, it dies.

## Why It's Good For The Game

They are cute. Probably a bit too strong for now, I will nerf if needed

## Changelog

:cl:
add: Bring back banelings as minions
/:cl:

2024-04-08 18:07 UTC, 00ze-cyclone commented
This solve nothing to the issue of baneling.
It’s still endlessly reswpaning fucker that can just dive in the middle of the ungaball with no risks at all or way to prevent the gassing.
It already was a minion in effect.

2024-04-08 21:41 UTC, TiviPlus commented
Uhh no 90% of the issue was the pod meaning you cant kill them for good

2024-04-09 01:38 UTC, coldironwarrior commented
he lives?

2024-04-09 03:53 UTC, novaepee commented
so back

2024-04-09 08:34 UTC, SimplySmiley123 commented
> Uhh no 90% of the issue was the pod meaning you cant kill them for good

And making it a minion that will get spammed out  and doesn't cost anyone anything solves it in what way?

2024-04-09 09:47 UTC, mkvrs commented
we love infinite simplemob victories in this house

2024-04-09 12:28 UTC, Yttriums commented
🙏🙏🙏🙏🙏

2024-04-09 15:42 UTC, TiviPlus requested changes
Rest lgtm

2024-04-09 15:42 UTC, TiviPlus commented on code/datums/keybinding/xeno.dm
> +	hotkey_keys = list("E")
Erm?

2024-04-09 15:42 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/baneling/abilities_baneling.dm
> +	var/static/list/baneling_smoke_list = list(
New vars after old and autodoc

2024-04-09 21:21 UTC, Arturlang commented
Could remove acid and neuro, so it can't do much actual damage on it's own

2024-04-13 21:30 UTC, efzapa commented
this is just bane but people get to infinitely spam it (now with no cooldown cause minions are SSD mobs) 

the state of TGMC is something these days

2024-04-15 14:21 UTC, CVSthePharmacy commented
don't let this get merged, this goes against the entire reason it was removed

2024-04-20 18:20 UTC, merged