select_reagent() loads new reagent
tgstation/TerraGov-Marine-Corps pull request #15637
Opened 2024-04-12 01:48 UTC by Xander3359

## About The Pull Request
Selecting a new reagent in your harvester weapon will switch your old chem with the new chem.

## Why It's Good For The Game
Some QOL, allows you to be more adaptable with your chems, since you no longer need to smack a corpse in order to purge the old reagent.

## Changelog

:cl:
qol: Selecting a new vali chem will purge the old loaded reagent and load up the new chem
/:cl:

2024-04-14 10:17 UTC, Lumipharon requested changes

2024-04-14 10:17 UTC, Lumipharon commented on code/datums/components/harvester.dm
> +	reagent_select_action.owner.update_inv_l_hand()
As mentioned in discord, make a check to see which hand actually needs updating

2024-04-22 10:16 UTC, Lumipharon approved these changes

2024-04-22 10:16 UTC, Lumipharon requested changes

2024-04-22 10:16 UTC, Lumipharon commented on code/datums/components/harvester.dm
> +	item_parent.update_icon()
use update_appearance now

2024-04-22 12:24 UTC, Xander3359 commented on code/datums/components/harvester.dm
> +	item_parent.update_icon()
done

2024-04-24 22:31 UTC, Lumipharon approved these changes

2024-04-24 22:31 UTC, merged