Add Toggle Fullscreen client verb
tgstation/TerraGov-Marine-Corps pull request #15645
Opened 2024-04-13 06:24 UTC by antropod

## About The Pull Request

Adds client verb OOC->Toggle Fullscreen.

## Why It's Good For The Game

I find myself switching between fullscreen and windowed mode a lot, mostly for reconnecting to a game from menu. I find it frustrating to go to prefs every time to change window modes, so I decided to make a verb for it. I placed it in OOC tab to mirror tgstation's UI.

## Changelog

:cl:
add: Add Toggle Fullscreen client verb
/:cl:

2024-04-17 16:26 UTC, TiviPlus approved these changes
im ok with this if you remove another toggle in exchange

2024-04-17 17:12 UTC, antropod commented
what?

2024-04-17 17:20 UTC, TiviPlus commented
we're trying to move away from verbs so I dont like adding more. remove an unused or bad one e.g toggle_radial_medical and I will consider it as balancing it out

2024-04-17 17:22 UTC, antropod commented
I'm not here to trade, I see a problem -> I propose a solution by making a PR that solves the problem.

2024-04-18 08:59 UTC, TiviPlus commented
You're creating more problems in my eyes that should be compensated out

2024-04-23 14:01 UTC, ivanmixo requested changes

2024-04-23 14:02 UTC, ivanmixo commented on code/game/verbs/ooc.dm
> +	var/datum/preferences/prefs = src.prefs
This should also be a toggle in the preferences menu, not a verb.

2024-04-23 23:28 UTC, antropod commented on code/game/verbs/ooc.dm
> +	var/datum/preferences/prefs = src.prefs
I deliberatly made it a verb in OOC tab to mirror other servers like tgstation and shiptest.

2024-04-23 23:36 UTC, ivanmixo commented on code/game/verbs/ooc.dm
> +	var/datum/preferences/prefs = src.prefs
What other servers do is kinda irrelevant here, our implementations aren't the same

2024-04-23 23:44 UTC, antropod commented on code/game/verbs/ooc.dm
> +	var/datum/preferences/prefs = src.prefs
I thought it will make new people less confused

2024-04-23 23:46 UTC, antropod commented on code/game/verbs/ooc.dm
> +	var/datum/preferences/prefs = src.prefs
I see now why you don't want another verb in Preferences tab, there is like 50 others. Now it makes sense.

2024-05-05 00:42 UTC, closed without merging

2024-05-05 21:00 UTC, Looking4bros commented
Is it possible to add client verbs without putting them anywhere in the stat panel? so you can just BYOND command line it?