Fix powerpacks double reloading
tgstation/TerraGov-Marine-Corps pull request #15732
Opened 2024-04-26 01:13 UTC by Xander3359

## About The Pull Request
Fix powerpacks double reloading

## Why It's Good For The Game
bugfix

## Changelog

:cl:
fix: Fix powerpacks double reloading
/:cl:

2024-04-26 01:17 UTC, lbnesquik commented
Does this fix the ICC ammo belt and flamethrowers back fuel?

2024-04-26 01:20 UTC, Xander3359 commented
> Does this fix the ICC ammo belt and flamethrowers back fuel?

Anything that is a worn magazine

2024-04-26 22:35 UTC, Lumipharon requested changes

2024-04-26 22:35 UTC, Lumipharon commented on code/game/objects/items/power_cells.dm
> +	var/magazine_flags
?why

2024-04-27 02:33 UTC, Xander3359 commented on code/game/objects/items/power_cells.dm
> +	var/magazine_flags
I forgor

2024-04-27 05:00 UTC, Lumipharon approved these changes

2024-04-27 05:00 UTC, merged