tank resprite
tgstation/TerraGov-Marine-Corps pull request #15755
Opened 2024-04-28 02:51 UTC by tyeagg

## About The Pull Request
resprites tank also renames it because couldnt bother to resprite the logo
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/98577688/5eadc342-e08f-4c29-9b8f-687ec6edac6a)

## Why It's Good For The Game
better looking and scifi setting

## Changelog

:cl:
imageadd: new tank module sprites
imageadd: new tank weapon sprites
imageadd: new tank sprite
/:cl:

2024-04-28 03:13 UTC, tyeagg commented
forgot to update damage sprites

2024-04-28 22:26 UTC, tyeagg commented
dont merge noticed a mistake

2024-04-30 03:42 UTC, Pockets-byte commented
this results in environment camo being removed

2024-05-01 11:44 UTC, Wirpy approved these changes
sprite approval, merge that fat boy

2024-05-01 18:44 UTC, TiviPlus requested changes
Don't see zoom in the icon diff?
Also APC sprites look like they've been shifted down, make sure it looks fine if you havent already
Missing the tread animation?

2024-05-01 18:44 UTC, TiviPlus commented on code/modules/vehicles/armored/armored_modules.dm
> +	var/is_hull_module = FALSE
clarify it's for visuals pls

2024-05-01 22:44 UTC, tyeagg commented
> Don't see zoom module in the icon diff?
> Also APC sprites look like they've been shifted down, make sure it looks fine if you havent already
> Missing the tread animation?

Zoom module is just very small its the red eyes on the turret

2024-05-04 08:07 UTC, TiviPlus approved these changes

2024-05-04 08:54 UTC, merged