Tele COPE
tgstation/TerraGov-Marine-Corps pull request #15810
Opened 2024-05-06 09:28 UTC by Lumipharon

## About The Pull Request
What's worse than a SOM engineer throwing a COPE sentry at you?
A SOM SL calling in a teleporter delivered COPE on you.

Adds the ability to summon up to 2 COPE sentries via teleporter. Like TGMC sentry/supply pods, this is enabled simply by activating the teleporter asset, and lasing like all air support.

For maints: I also reorganised the files, as it was all crammed in one giant DM. Only the stuff in the teleport.dm file is new though.

## Why It's Good For The Game
While the teleporter is situationally very strong, in practical terms drop pods are SIGNIFICANTLY more useful, due to being very flexible for individual drops.

This adds a bit more utility to the teleporter, even when you're not using it to deploy troops or supplies.

## Changelog

:cl:
add: Campaign: Activating the teleporter asset gives access to a teleport COPE air support type
/:cl:

2024-05-14 20:02 UTC, TiviPlus requested changes

2024-05-14 21:48 UTC, Lumipharon commented on code/datums/fire_support/fire_support.dm
> +		addtimer(CALLBACK(src, PROC_REF(do_impact), impact_turf), 0.15 SECONDS * i)
I unno, old code or something, probably from CAS GAU

2024-05-15 18:14 UTC, TiviPlus requested changes
rest looks ok

2024-05-15 18:14 UTC, TiviPlus commented on code/game/objects/structures/orbital_cannon.dm
> +	var/list/turf_list = range(range_num, target)
RANGE_TURFS, range() returns all atoms

2024-05-15 21:45 UTC, Lumipharon commented on code/game/objects/structures/orbital_cannon.dm
> +	var/list/turf_list = range(range_num, target)
whoops

2024-05-20 13:04 UTC, merged