Tank nerf
tgstation/TerraGov-Marine-Corps pull request #15815
Opened 2024-05-07 16:38 UTC by chizzy376

## About The Pull Request
PR made by Bill
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/80391698/e2865166-3e02-401b-80fb-bc1f495556f8)

## Why It's Good For The Game
"Xenos won't die instantly" -Bill Torres

## Changelog

:cl: 
balance: changed tank's rocket from 100 sunder to 20
balance: changed tank's minigun ltaap penetration from 10 to 15
/:cl:

2024-05-07 16:46 UTC, Woker2004 commented
You do know tank is made out of paper right now? Anyways make the tank shell do at least 80 Sunder because you get limited amount and it is, I don't know, a fucking tank round, if your doing 20 sunder on hit just add a HE round that has bigger radius

2024-05-07 22:08 UTC, womk2004 commented
> ## Changelog
> 🆑 balance: changed tank's rocket from 100 sunder to 20
Also it is a Tank shell not a Tank Rocket

2024-05-08 10:19 UTC, SimplySmiley123 commented
> You do know tank is made out of paper right now? Anyways make the tank shell do at least 80 Sunder because you get limited amount and it is, I don't know, a fucking tank round, if your doing 20 sunder on hit just add a HE round that has bigger radius

Yeah, the tank, and by proxy, the APC seem to lately just fold the instant a xeno gets to touch 'em. Forcing a very passive playstyle with them if they want to survive for longer then 5 minutes after the LZ gates open.

And regarding tank shells I would love to see some variants to them, an anti-tank shell for ruining a target's armour and sundering them hard at cost of lack of AOE, and an HE round that deals less sunder but causes a larger explosion on impact.
Cuz frankly going from 100 to 20 on a _god damn tank shell_ is, kinda ridiculous in it's current state of being a glass cannon.

2024-05-08 23:07 UTC, Lumipharon commented
>nerf pr buffs minigun

This sunder nerf seems quite extreme

2024-05-09 17:45 UTC, CVSthePharmacy commented
hi chimmy, also no close this pr please, that is a massive nerf to an already nerfed tank, don't kick a dead horse man...

2024-05-14 19:30 UTC, TiviPlus requested changes
otherwise ok

2024-05-14 19:30 UTC, TiviPlus commented on code/modules/projectiles/ammo_types/heavy_ammo.dm
> -	penetration = 10
set it explicitly instead of inheriting

2024-05-14 19:31 UTC, TiviPlus commented
> > nerf pr buffs minigun
> 
> This sunder nerf seems quite extreme

Pretty sure it was originally supposed to have 0 sunder

2024-05-14 19:32 UTC, TiviPlus commented
Paper issues should be adressed seperately by actually standardizing the anti vehicle buffs instead of beign "lol lmao" kneejerk mech changes

2024-05-15 13:49 UTC, chizzy376 commented on code/modules/projectiles/ammo_types/heavy_ammo.dm
> -	penetration = 10
Done

2024-05-15 13:51 UTC, CVSthePharmacy commented
don't merge these nerfs.... changing the title doesn't make it not a nerf.

2024-05-15 18:34 UTC, merged