HvH faction remastering and adding: Vyacheslav Security Detail pt.1
tgstation/TerraGov-Marine-Corps pull request #15844
Opened 2024-05-11 06:36 UTC by SomrNetwork

## About The Pull Request
With the climb of Campaign, I've gotten an inspiration to make and remaster some factions. Starting with my first, the Vyacheslav Security Detail. A Syndicate PMC squad sent to assist in ICC and SoM operations. Equipped with Crasher ballistic armor and Cold War weaponries. Consisting of the following:

The C550 Assault Rifle, chambered in 10x27mm
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/114457130/a094fe94-f9ea-4a34-8a6c-4ddefc566a23)

The L26 Support MG, chambered in 5.56mm
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/114457130/1bbf6112-eaa4-49eb-a79a-ccd17b148eb0)

The C17 PDW, firing AP .45 ACP
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/114457130/fee8e05e-5a38-4a73-895c-37fe0b05d7a5)

The L12 pump-action Shotgun, 12 gauge
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/114457130/ddb43bfe-89a2-47dd-99bb-2505c6e428de)

The XM104 'Divider' Revolver, firing incendiary .357
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/114457130/d03f63d2-0d52-4ed1-921f-12e99dfe0193)

The C96 pistol, chambered in 9mm parabellum
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/114457130/cf83fd94-ebca-41dd-81b4-e0484ec75285)

The C153 shoulder launcher, fires HE and ~~Chemical warheads~~ Incendiary rounds
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/114457130/2381b436-efef-42e5-82b7-a93e52877ba4)

and the armory:

![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/114457130/79cfd872-64f6-48b3-a4e7-45ea12554f24)

![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/114457130/2a8022df-c41e-40aa-9cf9-72830638a9c5)

![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/114457130/c803be8f-357d-4dbd-9a4e-345b7bee6604)

![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/114457130/1a8ea7af-f65f-4f56-aba4-37c0fb679296)

also there's now new magfed revolver code 👍 

extras:
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/114457130/15546ce2-9fa9-418e-990e-72ceda82d55a)

![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/114457130/eb52327e-937a-4517-89a8-376a191a7549)

![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/114457130/3b19845c-ec9c-4bf5-80c2-4e6122641bd3)

## Why It's Good For The Game

Campaign seems to lack a few faction varieties. I want to assist in adding a slight amount of variation with lore, factions, guns and armor. And, since TGMC has slightly more factions than ICC/SoM, I wish to balance it too.

## Changelog

:cl:
add: vsd faction
add: New magfed revolvers!
imageadd: campaign portrait and UI
imageadd: VSD armor and weapons
balance: faction balance
/:cl:

2024-05-11 06:36 UTC, SomrNetwork commented
time to update the branch to current TGMC!!

2024-05-11 06:42 UTC, Tailiik commented
Looks good, you might wanna put a comment on the crasher armor declaration that it is used for your faction though so it doesn't get snapped when the mk3ening happens.

2024-05-11 06:44 UTC, SomrNetwork commented
kuro doesn't touch much of the faction armors. I don't really think he'd touch the ERT crasher armor anyway

on another note
WHAT THE FUCK
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/114457130/88722650-7e5d-4207-9f69-dd8b42bc37ec)

2024-05-11 06:54 UTC, lbnesquik commented
"We need bad guys for our f-" 

The russians : 
![Uploading ronaldo-win-ronaldo-award-ezgif.com-resize.gif…]()

2024-05-11 06:55 UTC, lbnesquik commented
"We need bad guys for our f-"

**The Russian PMC :** 

![ronaldo-win-ronaldo-award-ezgif com-resize](https://github.com/tgstation/TerraGov-Marine-Corps/assets/24830358/20508d50-f582-4e87-9349-4e7825e5b81a)

2024-05-11 07:23 UTC, Lumipharon commented
bro how old is your branch, and did you just ignore all the conflicts when you pulled master?

2024-05-11 07:24 UTC, SomrNetwork commented
> bro how old is your branch, and did you just ignore all the conflicts when you pulled master?

this project started 3 months ago so

2024-05-11 09:08 UTC, Tonklaatech commented
Z TARDS RISE UP!!!

2024-05-11 09:16 UTC, Lumipharon requested changes
My eyes are glazing over from the volume of gear you're adding, but here's a couple of things to fix

2024-05-11 09:16 UTC, Lumipharon commented on code/__DEFINES/_radio.dm
>  #define FREQ_AI 1351
hrm.

2024-05-11 09:16 UTC, Lumipharon commented on code/modules/clothing/glasses/glasses.dm
> +/obj/item/clothing/glasses/vsd/nvg
did you just copy paste the entire code for existing nvg's?

2024-05-14 13:34 UTC, SomrNetwork commented
now waiting on kuro's sprite approvals

2024-05-14 22:26 UTC, Lumipharon commented
yeah just an FYI I wouldn't even want to look at walance until sprites are reviewed.

2024-05-16 00:09 UTC, Kuro020 approved these changes

2024-05-18 14:01 UTC, SomrNetwork commented
its been 3 days since Kuro's approval

2024-05-19 08:00 UTC, Lumipharon requested changes

2024-05-19 08:00 UTC, Lumipharon commented on code/datums/gamemodes/campaign/rewards/allies.dm
> +		/datum/job/vsd/juggernaut/campaign_bonus = 2,
this is like, more dudes than the CLF ert, but they're better than PMC?

2024-05-19 08:01 UTC, Lumipharon commented
wotdis sprite 
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/7869430/ccda6e5b-cff6-48dd-b88a-f11a863d1088)

its like not even the same palette as the other guns, and is just really low quality.

2024-05-19 08:56 UTC, SomrNetwork commented on code/game/objects/items/explosives/grenades/explosive_grenades.dm
> +	light_impact_range = 5
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/114457130/f748bb03-fd9e-4af5-84e6-ef3df6dad8a2)

2024-05-19 08:57 UTC, SomrNetwork commented on code/modules/clothing/head/helmet.dm
> +	soft_armor = list(MELEE = 20, BULLET = 40, LASER = 10, ENERGY = 10, BOMB = 10, BIO = 10, FIRE = 20, ACID = 30)
overlooked, fixing

2024-05-19 08:57 UTC, SomrNetwork commented on code/modules/clothing/suits/marine_armor.dm
> +/obj/item/clothing/suit/storage/marine/vsd/larmor/desert
i'm not giving them a facepaint to color it or ANY way to color it

2024-05-19 08:57 UTC, SomrNetwork commented on code/modules/projectiles/guns/rifles.dm
> +	desc = "The Syndicates main all purpose machine gun, chambered in 5.56. It's design seems... outdated yet still reliable. Fires rapidly with devasting kicks, at a cost of movement speed."
this is the biggest problem so far

2024-05-19 13:41 UTC, SomrNetwork commented
time to annoy Lumi again!!

2024-05-21 03:45 UTC, Lumipharon requested changes

2024-05-21 03:45 UTC, Lumipharon commented on code/datums/gamemodes/campaign/rewards/campaign_asset_jobs.dm
> +		/datum/outfit/job/vsd/standard/gruntone/campaign,
camel_case. /grunt_one. or just /one

2024-05-21 03:45 UTC, Lumipharon commented on code/modules/clothing/glasses/night.dm
> +	item_flags = DELONDROP
whydis?

2024-05-21 03:45 UTC, Lumipharon commented on code/modules/projectiles/guns/rifles.dm
> -		/obj/item/weapon/gun/grenade_launcher/underslung/mpi,
I was only questioning the mpi UGL btw, since thats just a normal UGL but with a custom sprite specifically to fit the MPI, and it is unremovable.

2024-05-21 03:45 UTC, Lumipharon commented on tgmc.dme
> -#include "code\game\area\riptide.dm"
?

2024-05-21 03:45 UTC, Lumipharon commented on tgmc.dme
> -#include "code\game\objects\items\fishing.dm"
?

2024-05-21 03:48 UTC, Lumipharon commented on code/game/objects/items/explosives/grenades/explosive_grenades.dm
> +	light_impact_range = 5
yeah, and m15 doesn't fit in a ugl... although looking again this one doesn't either so that's fine.

2024-05-22 02:11 UTC, SomrNetwork commented
What the fuck tgstation bot

2024-05-25 08:13 UTC, merged

2024-05-25 09:42 UTC, SomrNetwork commented
i'm pretty sure this is still testmerged but yipee!!

2024-05-25 11:41 UTC, Lumipharon commented
I wanted to tm for walance but ok