Ravager Rage Screenshake no longer effects the ravager
tgstation/TerraGov-Marine-Corps pull request #15896
Opened 2024-05-18 17:53 UTC by yyzsong

## About The Pull Request
see title

## Why It's Good For The Game
Getting such heavy screenshake when you pop rage is very disrupting, and can lead to you getting killed if you try and use it to make advantage of the damage and speed boost. An earlier PR for this was closed so the screenshake could be "Reduced to fluff levels," but no such PR has been made and I don't think there's an amount of screenshake low enough to be considered "fluff"

## Changelog

:cl:
balance: Ravager's Rage no longer shakes the screen of the ravager who used the ability
/:cl:

2024-05-18 20:44 UTC, Isy232 commented
Yes please

2024-05-19 08:07 UTC, Lumipharon requested changes
Its kind of in the name "cheap_get_humans_near" that this is not what you think it it.
Please test your prs.

2024-05-19 14:26 UTC, ivanmixo commented
Lumi it's `cheap_get_humans` + `cheap_get_xenos`, this will work..

2024-05-19 20:29 UTC, yyzsong commented
> Its kind of in the name "cheap_get_humans_near" that this is not what you think it it. Please test your prs.

I did and it worked.

2024-05-19 21:42 UTC, Lumipharon commented
I redarded, couldn't see it on phone view

2024-05-19 21:42 UTC, Lumipharon approved these changes

2024-05-19 21:42 UTC, merged