Minor Boiler QOL changes
tgstation/TerraGov-Marine-Corps pull request #15890
Opened 2024-05-17 15:06 UTC by Notamaniac

## About The Pull Request

Changes the pips on globule storage to simple numbers for readability purposes
![globstorage](https://github.com/tgstation/TerraGov-Marine-Corps/assets/17688334/527793c2-3780-4e45-a843-330330f511f2)
Removes the dedicated 60(!!) sprite icon file for globules
Changes globule creation tochat() messages to balloon alerts, with the amount of globlues currently in reserve.

## Why It's Good For The Game

Mostly for readability, in the midst of combat you don't really have that much time to squint and count how many pips you have.

## Changelog

:cl:
qol: Boiler globules in reserve are now listed as a number on the create globule ability button. You're also told how many globules of your current acid type are in reserve when making a globule.
qol: Changed several boiler to_chat() messages to balloon alerts.
/:cl:

2024-05-23 14:56 UTC, dopamiin0 commented
i didnt even know there was a pip change i just prayed or tried to count in my head this is huge

2024-05-23 23:34 UTC, Lumipharon requested changes

2024-05-23 23:34 UTC, Lumipharon commented on code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
> +		X.balloon_alert(X,"Neuro globule prepared - [X.neuro_ammo] in reserve.")
As a rule try keep balloon alerts very short. They have key information from A: they presumably know what buttons they're pressing, and B: The action button has more info that they can read.

2024-05-23 23:34 UTC, Lumipharon commented on code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
> +	corrosiveglob_maptext.maptext = "<span class='maptext' style=font-size:8px><font color=green>[X.corrosive_ammo]</span>"
span macros

2024-05-23 23:34 UTC, Lumipharon commented on code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
> +	neuroglob_maptext.maptext = "<span class='maptext' style=font-size:8px><font color=yellow>[X.neuro_ammo]</span>"
span macros

2024-05-23 23:34 UTC, Lumipharon commented on code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
> +	neuroglobnumber.maptext = "<span class='maptext' style=font-size:8px><font color=yellow>[X.neuro_ammo]</span>"
some more span macros

2024-05-24 01:50 UTC, Lumipharon commented
Don't self close reviews please, it makes it hard to check

2024-05-24 01:52 UTC, Lumipharon approved these changes

2024-05-24 01:52 UTC, merged