Adds brake function to roller beds
tgstation/TerraGov-Marine-Corps pull request #15944
Opened 2024-05-28 23:48 UTC by Wisemonster

## About The Pull Request
Adds a brake funtion to roller beds, allowing humans to toggle their anchor state on and off. Roller beds deploy with their anchor on by default.

## Why It's Good For The Game
Currently, using roller beds groundside carries the massive risk of a xeno coming by and kidnapping the patient, guaranteeing a perma. This will hopefully reduce the chances of this happening, and make roller beds much more useful for corpsmen.

## Changelog

:cl:
balance: Roller beds now have brakes that can be toggled with right click. They deploy with the brakes enabled.
/:cl:

2024-05-28 23:51 UTC, XElectricX commented
Super cool and needed but probably shouldn't be on by default. If I use it in an emergency to get a downed marine out, that's a split second gone to trying to disable the break.

2024-05-29 00:36 UTC, Lumipharon commented
having this on by default makes it incredibly annoying yeah

2024-05-29 00:54 UTC, Wisemonster commented
Alright, gonna change it to be off by default

2024-05-29 04:25 UTC, Clay500z commented
Aw, seeing my patients get kidnapped was funny. Atleast it'll still happen to bald corpsmen that don't know about the brakes.

2024-05-29 11:38 UTC, Lumipharon requested changes

2024-05-29 11:38 UTC, Lumipharon commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +		balloon_alert(user, "You release the brakes")
just make them short. 'brakes on' 'brakes off' or whatever

2024-05-29 13:19 UTC, QualityVan commented
This does kind of feel like skill issue to me. When would this be useful when you couldn't just unbuckle the patient instead? It does make sense for surgery, but that's not a corpsmen concern and this PR is explicitly presented as for corps benefit.

2024-05-29 15:18 UTC, Wisemonster commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +		balloon_alert(user, "You release the brakes")
Done

2024-05-29 15:47 UTC, XElectricX commented
> This does kind of feel like skill issue to me. When would this be useful when you couldn't just unbuckle the patient instead? It does make sense for surgery, but that's not a corpsmen concern and this PR is explicitly presented as for corps benefit.



> This does kind of feel like skill issue to me. When would this be useful when you couldn't just unbuckle the patient instead? It does make sense for surgery, but that's not a corpsmen concern and this PR is explicitly presented as for corps benefit.

Makes sense if you got triage going on with marines inside stasis bags clipped to roller beds. Though this advanced so your average unga medic won't do it but still a huge benefit to groundside doctors.

2024-05-30 23:08 UTC, Lefunny commented
Skill issue from marines, shouldn't be fixed by coding babysitting tbh

2024-05-31 13:01 UTC, lbnesquik commented
I'm for it. Good PR.

2024-05-31 23:28 UTC, Lumipharon approved these changes

2024-05-31 23:28 UTC, merged