Adds another layer of walls around parts of xeno valhalla
tgstation/TerraGov-Marine-Corps pull request #15948
Opened 2024-05-30 00:12 UTC by Wisemonster

## About The Pull Request
Title

## Why It's Good For The Game
Xenos keep finding ways to escape containment, this should hopefully prevent future incidents till someone patches the exploit itself.

## Changelog

:cl:
fix: Xeno Valhalla is now more secure with an extra layer of walls.
/:cl:

2024-05-30 00:13 UTC, Wisemonster commented
Note it would be better to patch the exploit itself, however this will also help prevent any future displacement bugs from allowing xenos to escape.

2024-05-30 00:16 UTC, Lumipharon commented
Just add the kill blockers.

2024-05-30 00:38 UTC, Wisemonster commented
Alright, replaced the extra layer of walls with a forcefield.

2024-05-30 11:55 UTC, gpinrgrmoma commented
if you've ever seen aliens stuff, you should know xenos will always escape containment........

2024-06-01 01:02 UTC, RipGrayson requested changes
If you're going to do this, make the forcefields kill blockers instead of regular forcefields

2024-06-01 04:27 UTC, Wisemonster commented
Alright, replaced the forcefields with the kill tele things around other ship maps

2024-06-01 05:10 UTC, merged