Reorganizes `Xeno/Actions.dmi`
tgstation/TerraGov-Marine-Corps pull request #16062
Opened 2024-06-11 12:26 UTC by Helg2

## About The Pull Request
Reorgs it in it's own folder.

## Why It's Good For The Game
Organisation is nice.

## Changelog

Not player-facing.

2024-06-14 23:47 UTC, Lumipharon approved these changes

2024-06-14 23:49 UTC, Lumipharon requested changes
wait, have you tested this? All the generic overlay stuff is in the general dmi. Is that going to work with abilities in a different dmi?

2024-06-14 23:58 UTC, Helg2 commented
I'll recheck to be sure, as I don't remember currently.

2024-06-15 10:06 UTC, Helg2 commented
I think this is fine
Before:
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/93882977/70cc17b3-c633-48f6-85f3-eff84efad7fc)
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/93882977/b6786d9f-52be-4b38-84ab-e9a6fd1f6bc9)
After:
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/93882977/aa2f4e69-e61a-4453-af89-2a25c30433fd)
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/93882977/fa875867-da84-4665-95fe-bfab1dc80541)

2024-06-17 00:26 UTC, Lumipharon approved these changes

2024-06-17 00:26 UTC, merged