Adjusts King's Laser Against APC/Tank
tgstation/TerraGov-Marine-Corps pull request #16089
Opened 2024-06-16 01:14 UTC by Wisemonster

## About The Pull Request
Adjusts the King's laser against the apc/tank to deal damage against their hitboxes. Also reduces the damage from 150 damage per 0.3 seconds to 15 damage per tile per 0.3 seconds

## Why It's Good For The Game
Consistancy and intuitiveness, Also currently King's laser shreds APCs/Tanks. This will make it more forgiving to being briefly caught by the king's laser, while also making it usable on more parts of said vehicles outside of the center.

## Changelog

:cl:
balance: King's laser now deals damage to tanks/APCs based on the tiles hit, 15 damage per tile every 0.3 seconds, down from 150 every 0.3 seconds.
/:cl:

2024-06-16 05:50 UTC, TheLeopold commented
By the way, laser's description says that it can only hurt living beings.
You might want to change that.

2024-06-16 13:48 UTC, iforgotmeword commented
that is a pretty big nerf to a very very long cast time power
making 40 per tile per 0.3 i think would be better
or 10 damage per 0.1 sec per tile

2024-06-16 15:58 UTC, Wisemonster commented
> that is a pretty big nerf to a very very long cast time power making 40 per tile per 0.3 i think would be better or 10 damage per 0.1 sec per tile

Both of these would increase King's damage against tanks/APCs. Keep in mind, King's current dps against these vehicles is 450. This pr changes that to 135 (180 if it's also hitting the middle)

2024-06-16 16:49 UTC, Kuro020 approved these changes

2024-06-17 00:12 UTC, Lumipharon requested changes

2024-06-17 00:12 UTC, Lumipharon commented on code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
>  				var/obj/vehicle/veh_victim = victim
can't typecast as vehicle now

2024-06-17 00:30 UTC, Wisemonster commented on code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
>  				var/obj/vehicle/veh_victim = victim
Fixed

2024-06-18 01:38 UTC, Lumipharon approved these changes

2024-06-18 01:38 UTC, merged