Fixes Boiler Direct Hits
tgstation/TerraGov-Marine-Corps pull request #16095
Opened 2024-06-16 18:35 UTC by Wisemonster

## About The Pull Request
Fixes boiler direct hits on mobs reducing the smoke size.

## Why It's Good For The Game
#16056 unintentionally made direct hits with boiler globs reduce the size range down to one. This fixes a bug, and bugs are bad, therefor pr is good.

## Changelog

:cl:
fix: Boiler globs getting a direct hit should no longer reduce their smoke size
/:cl:

2024-06-16 22:50 UTC, Lumipharon requested changes

2024-06-16 22:50 UTC, Lumipharon commented on code/modules/projectiles/ammo_types/xenos/gas_xenoammo.dm
> +	drop_nade(target_turf.density ? get_step_towards(target_turf, proj) : target_turf, proj.firer)
what are you doing? this is just needs to swap proj for proj.firer

2024-06-17 00:11 UTC, Lumipharon approved these changes

2024-06-17 00:21 UTC, spookydonut approved these changes

2024-06-17 22:18 UTC, merged