Reduce the amount of flame particles spawned from fire
tgstation/TerraGov-Marine-Corps pull request #16108
Opened 2024-06-18 00:35 UTC by Wisemonster

## About The Pull Request
Title, reduces the particles spawned from 8 to 2

https://github.com/tgstation/TerraGov-Marine-Corps/assets/87689371/58afd7b3-b17a-4e61-b935-daef2828f64e
## Why It's Good For The Game
8 is an incredibly high number of particles considering how abundant fire is in the game. For reference, a standard flame grenade will create fire particles equivalent to 26 stacks of the melting debuff, which has particles similar to fire stats wise. This should hopefully fix issues like #14167, where users are lagging due to a massive amount of particles being generated.
## Changelog
:cl:
fix: Reduced the amount of particles generated from fire from 8 to 2. This should hopefully fix large amounts of fire tiles causing lag
/:cl:

2024-06-18 08:36 UTC, Helg2 commented
Well, fire with barely any particles looks quite plain, maybe just cut it to 4 instead of 2?

2024-06-18 22:34 UTC, Lumipharon requested changes
As mentioned in discord, I'm not happy with this when its some kind of byond/computer issue.
We use shit loads of particles for other things and the vast majority of players have no issues.

2024-06-19 16:28 UTC, TiviPlus commented
Do you also have proofs for your claim

2024-06-19 18:13 UTC, Wisemonster commented
https://github.com/tgstation/TerraGov-Marine-Corps/assets/87689371/89105ae0-d5d6-4b71-8afe-47237d9bc990

2024-06-19 18:15 UTC, Wisemonster commented
If you want evidence that it's the particles causing the lag, then I can record a video of the fire without their particles to show it not lagging.

2024-06-26 23:06 UTC, Lumipharon commented
Closing this for the reasons above, we need a proper resolution, not to avoid the issue.

2024-06-26 23:06 UTC, closed without merging