Couple campaign fixes
tgstation/TerraGov-Marine-Corps pull request #16110
Opened 2024-06-18 02:17 UTC by Lumipharon

## About The Pull Request
Fixes an error that popped up today due to yet more null entries in glob lists.
Since we can't seem to reliably avoid them, I'm just clearing nulls before these two proc as they're gamemode critical if they runtime.

## Why It's Good For The Game
Leader not being selected is bad.

## Changelog

:cl:
fix: Campaign: Fixed an edge case where a leader would not be chosen
/:cl:

2024-06-18 06:30 UTC, TiviPlus approved these changes

2024-06-18 06:32 UTC, TiviPlus requested changes
Actually this is supposed to be mostly used for the maintenance as why don't you just check isnull or remove the as

2024-06-18 15:19 UTC, TiviPlus requested changes
You still have the null clearing

2024-06-18 21:35 UTC, Lumipharon commented
I  brain gud

2024-06-19 16:29 UTC, TiviPlus approved these changes

2024-06-19 16:29 UTC, merged