fixes VSD (again)
tgstation/TerraGov-Marine-Corps pull request #16129
Opened 2024-06-21 09:31 UTC by SomrNetwork

## About The Pull Request
title

## Why It's Good For The Game
missing icon sprites and naked specs in campaign are not good

## Changelog

:cl:
fix: vsd LMG icon and naked spawning specs in campaign
/:cl:

2024-06-21 09:32 UTC, SomrNetwork commented
don't turn into tailstab pr 2

2024-06-22 07:21 UTC, TiviPlus requested changes

2024-06-22 07:21 UTC, TiviPlus commented on html/changelogs/archive/2024-04.yml
> +=======
merge markers

2024-06-22 22:48 UTC, Lumipharon approved these changes

2024-06-22 22:48 UTC, merged