Fireball's AoE now applies fire stacks
tgstation/TerraGov-Marine-Corps pull request #16168
Opened 2024-06-25 04:54 UTC by Wisemonster

## About The Pull Request
Title, the AoE of the fireball will now apply 2 stacks of melting fire.

## Why It's Good For The Game
Currently, if you get hit by the AoE damage of a fireball and immediately leave the impact area, you get 0 fire stacks applied to you. This pr makes it so getting hit by the fireball's AoE will do more than just act as a minor inconvenience for whoever was hit.

## Changelog

:cl:
balance: The impact AoE damage of pyrogen's fireball will now inflict 2 stacks of melting fire on hit.
/:cl:

2024-06-26 23:00 UTC, Lumipharon requested changes
Bruh, I just realised, why the fuck did we call this status effect 'melting fire' when we already have a 'melting' status effect? oh well

2024-06-26 23:00 UTC, Lumipharon commented on code/modules/projectiles/ammo_types/xenos/pyrogen_xenoammo.dm
> +			if(!isxeno(fired))
early continue

2024-06-27 02:09 UTC, Wisemonster commented on code/modules/projectiles/ammo_types/xenos/pyrogen_xenoammo.dm
> +			if(!isxeno(fired))
Alright, done

2024-06-28 00:50 UTC, Lumipharon approved these changes

2024-06-28 00:50 UTC, merged