Removes headsets from spawning in Valhalla
tgstation/TerraGov-Marine-Corps pull request #16244
Opened 2024-07-03 10:15 UTC by Wisemonster

## About The Pull Request
Title

## Why It's Good For The Game
Valhalla marines shouldn't be getting access to headsets.

## Changelog

:cl:
fix: Fixed an issue with headsets in Valhalla
/:cl:

2024-07-03 10:43 UTC, Wisemonster commented
Ok, turns out there was also a way to get an ASRS tablet, so I added a fix for that as well

2024-07-04 18:01 UTC, ivanmixo requested changes
Uh, what? This doesn't solve a thing. You're adjusting the outfits for the human dummies xenos can spawn, not the actual valhalla marines spawning in

2024-07-04 18:25 UTC, Wisemonster commented
It's not a copypasta of the xeno button, because it's literally the xeno button but with a proc to allow added onto it, similar to how the vehicle spawner button works. I didn't make a new button, but rather just added onto the xeno button so marines could use in Valhalla and then renamed it (See #16212) The outfits allow for limited HvH testing until #16236 is merged.

2024-07-05 01:04 UTC, ivanmixo approved these changes

2024-07-05 01:04 UTC, ivanmixo commented on code/game/objects/machinery/buttons.dm
> +/obj/machinery/button/valhalla/vehicle_button/proc/spawn_vehicles(mob/living/user)
Forgor doc here as well

2024-07-05 10:19 UTC, Wisemonster commented on code/game/objects/machinery/buttons.dm
> +/obj/machinery/button/valhalla/vehicle_button/proc/spawn_vehicles(mob/living/user)
Alright, gave it an autodoc

2024-07-05 15:11 UTC, merged