Adds civil war loadouts
tgstation/TerraGov-Marine-Corps pull request #16259
Opened 2024-07-04 20:27 UTC by blackdav123

## About The Pull Request
Adds a redcoat and bluecoat loadout.
Adds full martini belts to make this work.
Quick equip vendors for these WIP

## Why It's Good For The Game
Civil war events should be easy to run.

## Changelog

:cl:
add: Added redcoat and bluecoat loadouts
add: Added a full martini belt
/:cl:

2024-07-09 01:17 UTC, Lumipharon requested changes
Was this intended to be actually merged, or was this just a america day thing?

2024-07-09 01:17 UTC, Lumipharon commented on code/datums/quick_load_outfits.dm
> +	var/requirejob = TRUE
camel_case

2024-07-09 01:19 UTC, blackdav123 commented
> Was this intended to be actually merged, or was this just a america day thing?

merged please, ive seen this event flop a few times due to being too hard to set up

2024-07-09 10:07 UTC, lbnesquik commented
Aren't redcoats and bluecoats from the american revolt with the UK?

2024-07-10 00:29 UTC, Lumipharon approved these changes

2024-07-10 00:30 UTC, Lumipharon requested changes

2024-07-10 00:30 UTC, Lumipharon commented on code/datums/quick_load_civilwar.dm
> +/datum/outfit/quick/civilwar
actually, more camel case

2024-07-10 00:30 UTC, Lumipharon commented on code/datums/quick_load_civilwar.dm
> +/datum/outfit/quick/civilwar/redcoat
same

2024-07-14 00:28 UTC, merged

2024-07-17 04:35 UTC, Woker2004 commented
HOLY BASED, now we need a 13 second reload musket