SSD takeover now loads your active character slot
tgstation/TerraGov-Marine-Corps pull request #16253
Opened 2024-07-04 07:39 UTC by Ldip999

## About The Pull Request

SSD takeover will now load your active character slot (meaning name, gender, hair, eyes, age, ethnicity, flavour text, basically everything except subrace (human/robot/vatgrown)) with a check to see if the character is already in the round (optional, and based on config value)

## Why It's Good For The Game

Round removal is bad and we and other branches of ss13 have been trying to remedy it for years, and TGMC offers a variety of colourful options, including respawning after 30 minutes (With a fancy valhalla to test out things while waiting, great idea by the way!), taking over a newly born vatgrown soldier, the larva queue, taking over minion xenos, or least commonly used, taking over an SSD marine. 
This PR aims to address this, by trying to remedy the inherent problems that come with playing an already estabilished character, that will feel alien and such. Already, the names are randomized (meaning that thankfully, you don't have to play as candice balls), but the visual appearance, gender, and the randomized name just feels alien and uncomfortable, so this PR aims to address this by (attempting to) load in your current character slot.
## Changelog

:cl:
qol: Taken over SSD mobs will now load your active character slot if possible
/:cl:

2024-07-04 08:34 UTC, Ragecrabbo commented
![theology of the matrix, www thescottsmithblog com, person becoming agent](https://github.com/tgstation/TerraGov-Marine-Corps/assets/85963263/6332b3cb-e993-4418-9c54-9a0378c413da)

2024-07-04 09:39 UTC, Wisemonster commented
Isn't this to prevent a bunch of "John TGMC" duplicate bodies lying around?

2024-07-04 11:37 UTC, Ldip999 commented
Define "John TGMC"

2024-07-04 12:15 UTC, Notamaniac commented
John TGMC dies, then takes over a SSD body. Another John TGMC is now in the round. That John TGMC dies, then takes over another SSD body. There are now 3 John TGMC's in the round.

(though i'm assuming that 'load your character slot if available' means that there's some check to avoid duplicate characters in the round)

2024-07-04 12:24 UTC, Ldip999 commented
> with a check to see if the character is already in the round (optional, and based on config value)
Depends on the server config. If it's set so, then we already could have 50 John TGMCs, limited only by the respawn timer. This will use the same logic and config flags for detecting and rejecting duplicate characters

2024-07-04 14:49 UTC, Ldip999 commented
It is currently set so that you can't have duplicates

2024-07-05 01:43 UTC, Lumipharon reviewed
I don't get what this is trying to resolve? When you take an ssd body it random names you already, does it not?

2024-07-05 17:49 UTC, Ldip999 commented
> I don't get what this is trying to resolve? When you take an ssd body it random names you already, does it not?

You are correct, it does give you a random name, however it still feels alien. That's what this PR aims to remedy. To make the taken over character more yours and that you'll feel more comfortable playing it, not to mention carrying over all RP aspects your character (that isn't already in the round) may have, such as friendships and such. Overall a better, more fun, more comfortable experience.

2024-07-06 18:14 UTC, TiviPlus requested changes

2024-07-06 18:14 UTC, TiviPlus commented on code/datums/actions/observer_action.dm
> +		to_chat(usr, "<span class='warning'>Someone has already joined the round with this character name. Please pick another.<spawn>")
use span class macros and fix wherever you pasted this from as well

2024-07-06 19:08 UTC, Ldip999 commented
Like so?

2024-07-09 16:57 UTC, TiviPlus commented
correct

2024-07-09 16:57 UTC, merged