Xeno seethrough button reset verb
tgstation/TerraGov-Marine-Corps pull request #16261
Opened 2024-07-04 22:34 UTC by Ldip999

## About The Pull Request

Adds a verb in the alien tab that resets your seethrough button.

## Why It's Good For The Game

Currently there is a bug where on reconnect (the one that happens due to lag for an example, not a full relaunch of the game) you have a chance to lose your alien seethrough. This PR attempts to remedy this by adding a verb under the alien tab to fix it on demand if it should be missing for any reason.

## Changelog

:cl:
fix: Adds xeno seethrough button reset verb incase it goes missing
/:cl:

2024-07-05 04:27 UTC, Lumipharon commented
uh, why don't we just fix the bug instead of adding a funny work around verb?

2024-07-05 13:21 UTC, TiviPlus requested changes
What lumi said

2024-07-05 17:38 UTC, Ldip999 commented
Because I don't know what the bug is. Why isn't chat fixed instead of the little ooc>fix chat verb?

2024-07-09 01:13 UTC, Lumipharon commented
some old code being shit isn't justification for adding new shitcode

2024-07-10 15:21 UTC, TiviPlus commented
Chat load also has a chance to fail because of random networking bs

2024-07-17 23:49 UTC, ivanmixo commented
I think this sets a bad precedent, issues should be properly addressed instead of having buttons to temporarily fix them

2024-07-17 23:49 UTC, closed without merging