Makes the 1000 Hour time role for FC "Brigadier General"
tgstation/TerraGov-Marine-Corps pull request #16292
Opened 2024-07-07 23:31 UTC by efzapa

# BEFORE YOU SCREAM AT ME, THIS DOES NOT TOUCH THE TIME REQS, JUST PAYGRADE

## About The Pull Request

Simply moves the 1000 hour time role for FC down to BGen, and adds the proper paygrades inbetween Col and Gen.

## Why It's Good For The Game

Having a full 4 Star General out on the battlefield slinging guns in my honest opinion does not really fit. This combined with the fact that the FC can, even with both roles maxed out, be at the same paygrade and rank. (even though they are technically not in the same branch of military for some reason)

This will also free up slots and paygrades for Admins to spawn in as, should they wish to arepee or do event rounds, while still letting those sweaty FC mains to be a proper Flag Officer

## Changelog

:cl:
add: 1000 hour FC is now a Brigadier General
/:cl:

2024-07-10 14:38 UTC, Pariah919 commented
Kinda breaks consistency with the rest of the 1K hour ranks, they're all generally super huge rank ups for people to see and have the ability to be able to make fun of you for playing way too much TGMC.

2024-07-10 22:00 UTC, efzapa commented
> Kinda breaks consistency with the rest of the 1K hour ranks, they're all generally super huge rank ups for people to see and have the ability to be able to make fun of you for playing way too much TGMC.

being a Brig General is still a pretty decent rank regardless tbh

only one that might match it is SL 1000 hour one

2024-07-17 15:03 UTC, TiviPlus requested changes
Don't approve since this just makes this more obscure for no clear gain, for admins that need an event rank or wherever you can add a commander in chief role or similar

2024-07-17 19:47 UTC, efzapa commented
Commander in Chief for a single op on a single ship in the middle of buttfuck nowhere is exactly why i made this but ¯\_(ツ)_/¯

gotta have the funny high roles, no lore

2024-07-17 19:47 UTC, closed without merging