Organ defines, get_organ_slot, remove_organ_slot
tgstation/TerraGov-Marine-Corps pull request #16359
Opened 2024-07-17 16:46 UTC by Ldip999

## About The Pull Request

Adds organ defines, and for the human_helper procs, adds get_organ_slot and remove_organ_slot

## Why It's Good For The Game

Makes things easier to use, edit, and harder to fuck up, also less lines, also makes porting things from TG easier since they use get_organ_slot and organ defines

## Changelog

:cl:
code: Organ defines, get_organ_slot, remove_organ_slot
/:cl:

2024-07-17 18:51 UTC, QualityVan requested changes
This is a lot of replacing list access with proc calls which is some extra processing, but most of this is infrequent enough that it shouldn't really matter.
Check linters.

2024-07-17 18:51 UTC, QualityVan commented on code/modules/mob/living/carbon/human/human_helpers.dm
> +///Removes organ slot by name
Spacing

2024-07-17 18:51 UTC, QualityVan commented on code/modules/mob/living/carbon/human/human_defense.dm
> +	internal_organs_by_name -= ORGAN_SLOT_HEART
Shouldn't this be using remove?

2024-07-17 18:51 UTC, QualityVan commented on code/modules/mob/living/carbon/human/human_helpers.dm
> +/mob/living/carbon/human/proc/get_organ_slot(var/string)
For both this and remove it's not actually getting or removing the slot, right? It's returning the organ itself.

2024-07-22 10:34 UTC, TiviPlus approved these changes

2024-07-22 10:34 UTC, merged