Neuraline shows up on med scan now
tgstation/TerraGov-Marine-Corps pull request #16365
Opened 2024-07-18 04:58 UTC by PibeCantina

## About The Pull Request

Makes neuraline show up on scanner

## Why It's Good For The Game

You'd think for something with an OD so devastating and a secondary effect it would show up on scanner.

## Changelog
:cl:
qol: Neuraline shows up on scanner now
/:cl:

2024-07-22 06:44 UTC, Looking4bros commented
I had assumed this had already been changed back when they made water and everything else show up on the scanner. I also wouldn't expect people to see neuraline in someone's system as it has a .4 metabolism and 5u OD. Giving it roughly 20 seconds to even see it. Not factoring in how rare it is.

2024-07-23 00:40 UTC, Lumipharon requested changes

2024-07-23 00:40 UTC, Lumipharon commented on code/modules/reagents/chemistry/reagents/medical.dm
> +	scannable = TRUE
its true be default, just remove the line.

2024-07-26 04:01 UTC, QualityVan approved these changes

2024-07-26 04:01 UTC, merged