acid code cleanup
tgstation/TerraGov-Marine-Corps pull request #16391
Opened 2024-07-23 00:29 UTC by Lumipharon

## About The Pull Request
Refactors a bit of acid code to be less horrible.

Its still kinda horrible, but less snowflake and funny atom var.

Mainly things are now done by atom procs as appropriate, and with signals for some behaviors instead of funny checks during process.

## Why It's Good For The Game
Better code.

## Changelog

:cl:
code: Cleaned up some acid code
/:cl:

2024-07-23 15:43 UTC, TiviPlus requested changes
Some tochat could be replaced with ballons but looks good enough

2024-07-23 15:43 UTC, TiviPlus commented on code/game/objects/effects/aliens.dm
> +		qdel(current_acid)
Return initialize qdel instead?

2024-07-23 15:43 UTC, TiviPlus commented on code/game/objects/effects/aliens.dm
> +	span_danger("Corrosive substances burn and seethe all over you upon retrieving the acid-soaked [item]!"))
This is super long and should use the pronoun helpers

2024-07-23 15:43 UTC, TiviPlus commented on code/game/objects/effects/aliens.dm
> +	for(var/datum/limb/limb in human_user.limbs)
As?

2024-07-24 07:25 UTC, Lumipharon commented
updated

2024-07-25 23:40 UTC, Lumipharon commented
@TiviPlus should be good to merge now

2024-07-28 12:46 UTC, merged

2024-08-13 20:35 UTC, MiniMeatwad commented
@Lumipharon Acid does not disappear if you pick up an item.