Solid turf C4
tgstation/TerraGov-Marine-Corps pull request #16421
Opened 2024-07-31 05:04 UTC by Lumipharon

## About The Pull Request
C4 now works on solid turfs like mineral walls.

## Why It's Good For The Game
Currently these turfs can be instantly deleted with the plasma cutter, but is otherwise functionally indestructable.

C4 means more people can actually interact with these turfs meaningfully, but without the unlimited spam that the PC entails.

In particular, tank crews will probably appreciate people being able to clear the occasional wall without hoping there is some PC nerd running around.

I was originally going to make dev explosions do this instead of specifically C4, but that would notably be pretty wack with HE OB.

## Changelog

:cl:
balance: C4 works on dense turfs like mineral walls
/:cl:

2024-08-01 06:26 UTC, Apple-107 commented
> I was originally going to make dev explosions do this instead of specifically C4, but that would notably be pretty wack with HE OB.

Please atleast try this because it'd be funny as fuck

2024-08-01 22:10 UTC, Kuro020 approved these changes

2024-08-01 22:36 UTC, chizzy376 commented
> > I was originally going to make dev explosions do this instead of specifically C4, but that would notably be pretty wack with HE OB.
> 
> Please atleast try this because it'd be funny as fuck

you can HE mortar nondense jungle walls (indestructible by normal means) one by one if you are patient

2024-08-02 20:20 UTC, RipGrayson commented
This needs tested in case it derails map balance

2024-08-05 07:18 UTC, TiviPlus approved these changes

2024-08-05 17:34 UTC, RipGrayson requested changes
Alright, I've decided that I don't like this while C4 can be made en-masse after https://github.com/tgstation/TerraGov-Marine-Corps/pull/15045. This is going to lead to situations where a massive amount of C4 destroys all solid walls in a map and mappers have to work around it. If we're going down this path I would would prefer if the wall destroying C4 was a special type of C4 that was harder to get at the very least.

2024-08-05 22:39 UTC, Lumipharon commented
death.

2024-08-05 22:39 UTC, closed without merging