remove ACCESS_MARINE_TADPOLE from SLs
tgstation/TerraGov-Marine-Corps pull request #16458
Opened 2024-08-11 18:21 UTC by YehnBeep

## About The Pull Request

This removes ACCESS_MARINE_TADPOLE from SLs

## Why It's Good For The Game

Currently, the Transport Officer - even joining 5 minutes after round during prep phase - will likely find the tadpole has already been selected by an SL and somewhat prepped according to their preferences.

Latejoining after deployment, it's often the case that an SL has taken the tadpole down to the planet and then abandoned it. Perhaps engineers or other players have cared about protecting it, or perhaps it's been totally lost at this point. If the latter is not the case, it often gets used as a personal medevac or resupply elevator by SL players.

APC and Tank crew don't really need to worry about the vehicles they are supposed to crew being used in this way, and I don't think TO should effectively be a 'roundstart or nothing' role.

In case of an emergency, Synths can, of course, still pilot the tadpole. Though this PR does mean SLs can't pilot as an emergency function using their own ID, it's presently being used as a personal-toy-rather-than-emergency capacity anyways.

But it's also worth noting that if the TO falls in battle, SLs or anyone else will still be able to use their ID to run an emergency takeoff/evacuation.

## Changelog

:cl:
del: Squad Leaders can no longer pilot the tadpole.
/:cl:

2024-08-11 22:26 UTC, jonash07 commented
any role can select the tad model so this literally does not fix the core issue

2024-08-11 23:18 UTC, YehnBeep commented
> any role can select the tad model so this literally does not fix the core issue

Even were this true, I doubt they'd select a tad they cannot fly.

However, upon inspection, the tadpole picker console appears to be access restricted.

2024-08-12 16:25 UTC, lbnesquik commented
I'm for it.

2024-08-14 21:36 UTC, YehnBeep commented
> Absolutely +1 as long as there's an easier way for SLs to view + visually explain plans to a TO. Something like the ability to draw on a tadpole-specific minimap, along with a camera system that allows SLs to peek at the proposed landing zone.
> 
> Otherwise, you'll just get fucked! Lots of new players play TO, which is in theory fine, but can't know context-specific names for places simply because they don't know the map yet. This could make rappel ops a lot, lot, LOT harder to organise purely because there is literally no way to communicate what you need from tadpole. Yeah sure buddy, go land "east engineering", cause I physically can't give you ANY more precision than that. Oh woops, you landed at the wrong engineering and now we're dead. Oops!
> 
> While we're at it CAS flares or whatever showing for TOs would be wonderful and really cool. But I suppose you can already kind of do that by just asking nicely! (shit, I need to try that, actually0

Another thing I'd love to see is a way to highlight a landing area, of course, _before_ actually comitting to landing - so people know not to place stuff. Or to indicate an area that needs to be cleared of walls.

2024-08-15 06:14 UTC, JackTheJackhammer commented
The problem is semi-low pop (like 40 players ig?). When theres only SLs and sometimes an RO on station, the tadpole is ever more important. It provides as a mobile base-of-fire and more concretely, as a position where marines can get resupplied.

2024-08-15 06:48 UTC, YehnBeep commented
> The problem is semi-low pop (like 40 players ig?). When theres only SLs and sometimes an RO on station, the tadpole is ever more important. It provides as a mobile base-of-fire and more concretely, as a position where marines can get resupplied.

That's exactly about the level where I tend to see this happening. Higher pop usually has a TO, and if not, the alt roles that can use it if they want to (but they don't always want to).

Of course, if the SLs in question said "Hey everyone I'm going up for some supplies, anyone need anything?" or "I'm going up to get medical treatment, anyone else need to visit medbay while I'm going?", it wouldn't have bothered me enough to go through the trouble of opening a PR.

But when it's "I'm going to silently use the tad when I personally need supplies/medical" (And typically use the autodoc even with medbay staff present...), then just abandon the tad when they don't use it, maybe it will survive maybe it won't. Depending on how much engineers might care to fortify and xenos might care to pressure.

Well, seeing that sort of stuff is what bothered me enough to open this. I don't see FCs and Synths do stuff like this - when they want to use the tad, typically it's for good reason and team benefit that I've seen. Possibly because the positions are higher responsibility inherently.

But also, even with Synth(s), an FC, and SLs present, the tad doesn't always get used, and marines do win without it. Like other vehicles, it can be a big advantage used properly, but it's not vital, either. Even under ideal circumstances, even with a TO present or someone filling in that manages it well, Xenos might successfully rush it and take it out, and marines may still win the match in this case too.

2024-08-15 09:13 UTC, lbnesquik commented
Perhaps a middle ground solution would be a 'Return to the ship' option. I know we kept the tadpole manual on purpose, but given we don't have tadpole pilots as frequently as before the nerfs, now it might be pallable. 

Something like a button on the tadpole menu to make it automatically takeoff after a set timer, and something to call it back from the console used to select the model in the first place. Maybe restrict it once the TO is alive. Or, give the TO the option to restrict it, using one of those fancy combat tablets.

2024-08-18 16:20 UTC, ivanmixo commented
> Currently, the Transport Officer - even joining 5 minutes after round during prep phase - will likely find the tadpole has already been selected by an SL and somewhat prepped according to their preferences.

The dibs system seems like an administrative issue. 

You could just make it so SLs get locked out of tad access if there's a TO/whatever present.

2024-08-18 21:43 UTC, Kuro020 requested changes
Feels like this needs some admin rulling, because sometimes the Tad pilot doesnt exist or dies for some reason, and having sls pilot it is good

2024-08-25 06:58 UTC, Pariah919 commented
Yea this seems like a #policy issue. Go whip up a random headmin.

2024-08-26 02:33 UTC, Lumipharon commented
this is, if anything at all, an admin/policy issue. Blanket removing SL access heavily fucks the marines since they effectively rely on the tad, regardless of whether a TO actually exists/is alive

2024-08-26 02:33 UTC, closed without merging