Fixes stuff like capes and kamas applying it's overlays while inhands
tgstation/TerraGov-Marine-Corps pull request #16495
Opened 2024-08-29 19:23 UTC by Helg2

## About The Pull Request
Fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/15812
Tested locally on a downstream, so it may fuck something up.

## Changelog

:cl:
fix: fixed stuff like capes and kamas applying it's overlays while inhands.
/:cl:

2024-08-29 19:24 UTC, Helg2 commented
Why is changelog invisible

2024-09-01 09:50 UTC, ivanmixo requested changes
Put all the args in while you're there

2024-09-01 09:50 UTC, ivanmixo commented on code/datums/components/attachment_handler.dm
> +/datum/component/attachment_handler/proc/apply_custom(datum/source, mutable_appearance/standing, inhands)
```suggestion
/datum/component/attachment_handler/proc/apply_custom(datum/source, mutable_appearance/standing, inhands, icon_used, state_used)
```

2024-09-01 14:05 UTC, ivanmixo approved these changes

2024-09-01 14:05 UTC, merged