Metnal Mining Operation (REVIVAL)
tgstation/TerraGov-Marine-Corps pull request #16504
Opened 2024-09-01 20:01 UTC by PibeCantina

## About The Pull Request
Revival about this map that i actually really liked but it was TM'd exactly one round and killed by the author.

First, big thanks to Grayson and Blackdav to get me to work this map and helping me sort out some problems my dumbass is creating trying to make this shit.

Link to original PR: https://github.com/tgstation/TerraGov-Marine-Corps/pull/14870

Map screenshots:

TO DO LIST:
Fix the fucking runtimes
Decorate the new areas
Touch caves around to make it more vehicle friendly/More expansive on the southwest
Making proper disk paths
Making crash a thing 

## Why It's Good For The Game

mmmmm ap

## Changelog

:cl:
add: Added Menthal Mining map
imageadd: Added some icons and images map exclusive
config: Added map to config
/:cl:

2024-09-02 22:40 UTC, RipGrayson requested changes
Fix the space tiles here
![stasharea](https://github.com/user-attachments/assets/8913e335-f82f-44a7-ae5a-6c0363c3a510)
This area needs widened
![stasharea2](https://github.com/user-attachments/assets/1c5c2f48-0f69-48bd-ace3-dc3434b3c84a)
Ditto
![stasharea4](https://github.com/user-attachments/assets/ff90dd78-2550-4222-9d62-12d0df30a170)
Why is there this random hole in the top right LZ?
![stasharea3](https://github.com/user-attachments/assets/07887e43-7378-4616-9c19-f7de06b78306)

2024-09-03 19:53 UTC, yyzsong commented
slopnal slopping sloperation

2024-09-06 01:59 UTC, RipGrayson commented
Not sure about caves, but we can have a TM for the sake of feedback

2024-09-09 21:17 UTC, Ermac10108 commented
The LZ does not give the tank enough room to get out of the Alamo Cargo Door without demolishing the walls

2024-09-09 21:17 UTC, Ermac10108 commented
Also said LZ walls are not Rwalls

2024-09-09 21:38 UTC, Ermac10108 commented
Sandstorms are invisible

2024-09-10 20:17 UTC, MiniMeatwad commented
Encountered merge conflicts while test merging one or more sources! (Inner exception: Test Merge #16504 at 0c07e08 conflicted! Conflicting files:

	- /_maps/_basemap.dm

	- /config/maps.txt)

2024-09-18 19:08 UTC, Looking4bros commented
I like, is nice cozy map.

2024-10-04 23:11 UTC, PibeCantina commented
xd grayson already took the tag (reload your tabs kids)

2024-10-30 19:51 UTC, Aporhtonoma commented
I would like to request some research spots outside caves since all of them are inside currently

2024-10-30 20:37 UTC, PibeCantina commented
> I would like to request some research spots outside caves since all of them are inside currently

Mostly rng on the spawn of those, but i added a bunch more research sites to the map since it did have too little

2024-10-31 19:12 UTC, ivanmixo commented
I'm not really a fan of this map. It is absurdly open and thus marines can dominate just about every area with ease, while caves are nigh impossible for them to push. Should really try harder to strike a balance. There are multiple screens worth of open air for a very wide portion of the outside areas, essentially allowing marines to get two disks for free, while the last disk and nuke are almost impossible due to how tight and winding the caves area. 

I'd really consider making caves less hostile to marines while making the outside less hostile to xenos. This map honestly feels like it's missing at least 5 or 6 buildings outside, and some of the corridors in caves are a trap, being as little as 2(!!) tiles wide.

2024-11-23 18:28 UTC, yyzsong commented
Remove the portable flashers from the security area. They are dense, movable objects that require acid to destroy. Annoying.

2024-12-05 02:45 UTC, Barnet2 requested changes
![image](https://github.com/user-attachments/assets/a7975a06-3bfd-4803-abbf-4df7342aa9f0)

Missing dropship console: /obj/machinery/computer/shuttle/shuttle_control/dropship

2025-01-04 03:43 UTC, merged