Improves Rappel
tgstation/TerraGov-Marine-Corps pull request #16576
Opened 2024-09-20 20:32 UTC by blackdav123

## About The Pull Request

- Rappel now allows more than one person to use it at once
- Rappel no longer retracts after every person using it
- Rappel now allows fireman carrying
- Rappel takes longer to use

## Why It's Good For The Game
Rappel currently sucks. Only one person can use it at a time, and shuffling the one person is extremely easy. Going up it requires the TO to replace it over and over, making it require constant attention and impossible to use to help small groups retreat. It also disallows fireman carrying so medics get little use out of it. These problems all combine to make it incredibly clunky and hardly worth the same slot as the HSG.

This PR intends to encourage its use in both large and small team play, rather than only as a way to move individuals up and down as it currently is. The time it takes to go up and down has been doubled to compensate, and make xenos capable of shuffling people and keeping them from going up.

## Changelog

:cl:
balance: The rappel system is now far easier to use.
/:cl:

2024-09-22 22:28 UTC, Kuro020 approved these changes

2024-09-26 22:26 UTC, Lumipharon requested changes

2024-09-26 22:26 UTC, Lumipharon commented on code/game/objects/structures/rappel_system.dm
> -	if(!step(user, get_dir(user, src)))
this means you can rappel out of solid objects etc.

2024-09-26 22:26 UTC, Lumipharon commented on code/game/objects/structures/rappel_system.dm
> +	if(!do_after(user, 8 SECONDS, NONE, src, BUSY_ICON_GENERIC) || user.lying_angle || user.anchored)
this would probs be better if it was just one do_after

2024-10-02 02:34 UTC, Lumipharon approved these changes

2024-10-02 02:40 UTC, merged