Adds the ICC LVRT 'Fallow' vehicle.
tgstation/TerraGov-Marine-Corps pull request #16597
Opened 2024-09-27 21:28 UTC by Pariah919

## About The Pull Request
![image](https://github.com/user-attachments/assets/514a4960-320f-446e-b51d-4e222b2b0642)
![image](https://github.com/user-attachments/assets/c9328116-fd89-4e6b-8fb5-280acc4ffcff)
Adds the Fallow. Its an ICC vehicle (With probably very bad stats since I didn't really balance them so far) and is 2x2 in size.
It is a light recon vehicle, so its very fast and nimble. It can be armed with either a 30mm SARDEN Autocannon with awful ROF, good damage and 7 round clips, or a 76mm low velocity cannon (with HEAT and HE) as well as a coaxial MG in place of the standard pintle secondary.
You can try it out in Valhalla.
It comes in funny camo only.

## Why It's Good For The Game
Adds more variety of non-marine vehicles to the game. And more vehicle variety in general.

## Changelog

:cl:
add: Added new ICC Recon Vehicle 'Fallow'. You can try it out in Valhalla. It has no other spawn areas.
/:cl:

2024-09-27 21:41 UTC, despong commented
we're so fucking back

2024-09-28 03:09 UTC, Looking4bros commented
add a new ERT shuttle that can be crashed into the ship like the Alamo does on Hijack and you got a fun little surprise. :)

2024-09-28 19:58 UTC, Aporhtonoma commented
coaxial MG? like actual mg used by an actual normal marine from outside? THATS AWESOME

2024-09-29 16:08 UTC, lbnesquik commented
> coaxial MG? like actual mg used by an actual normal marine from outside? THATS AWESOME

Coaxial means it shares the axis of the main gun. 
![Something like this.](http://www.gunmasters.com/100_1903.JPG)

2024-09-29 20:29 UTC, Kuro020 approved these changes

2024-10-01 05:24 UTC, despong commented
i hope you find out how to offset the turret because its going to look really silly when the turret faces n/s while the hull is facing w/e

2024-10-06 18:31 UTC, ivanmixo requested changes

2024-10-06 18:31 UTC, ivanmixo commented on code/modules/vehicles/armored/icc_recontank.dm
> +	var/obj/item/armored_weapon/gun = new /obj/item/armored_weapon/icc_coaxial()
```suggestion
	var/obj/item/armored_weapon/icc_coaxial/gun = new(src)
	gun.attach(src)
```

2024-10-19 15:08 UTC, TiviPlus approved these changes

2024-10-19 15:08 UTC, merged