Adds Smoker Zombie
tgstation/TerraGov-Marine-Corps pull request #16632
Opened 2024-10-05 18:42 UTC by blackdav123

## About The Pull Request
Adds a new zombie, the Smoker.
Has an ability to emit a smokescreen to help hordes of zombies close the gap on people with guns.
AI Smokers will use this ability when 2 tiles from a target or when below 50% health.

https://github.com/user-attachments/assets/1ef9d794-b7f7-43b1-b52e-b31738f453a0

## Why It's Good For The Game
More variety for zombie events

## Changelog

:cl:
add: Added new zombie type, the Smoker.
/:cl:

2024-10-05 22:53 UTC, Arturlang commented
way too much smoke

2024-10-06 16:03 UTC, iforgotmeword commented
I think zombies sided cloak smoke would be better if you want it be that size

2024-10-07 13:46 UTC, despong commented
boomer l4d2 
i think making it pop when it dies and having it gas with neurotoxin or the other defiler gasses would be funny

2024-10-07 13:59 UTC, blackdav123 commented
smoke radius is now 4 instead of 6

2024-10-08 01:11 UTC, Lumipharon requested changes

2024-10-08 01:11 UTC, Lumipharon commented on code/modules/mob/living/carbon/human/zombie.dm
> +	var/turf/T = get_turf(owner)
don't do single letter vars

2024-10-08 01:11 UTC, Lumipharon commented on code/modules/mob/living/carbon/human/zombie.dm
> +/datum/action/ability/emit_gas/proc/toggle_particles(activate)
autodoc

2024-10-08 02:23 UTC, Lumipharon approved these changes

2024-10-08 02:23 UTC, Lumipharon commented on code/modules/mob/living/carbon/human/zombie.dm
> +/// Toggles particles on or off, depending on the defined var.
```suggestion
/// Toggles particles on or off
```

2024-10-08 02:24 UTC, merged