Buffs smg90 firerate
tgstation/TerraGov-Marine-Corps pull request #16648
Opened 2024-10-08 03:10 UTC by blackdav123

## About The Pull Request
Increases smg90 firerate from 400 rpm to 480 rpm.

## Why It's Good For The Game
Smg90 was never a problematic gun and was hit pretty hard by the xeno buffs as many of the low armor castes it was good against (such as runner and carrier) got over a 40% durability buff vs the smg90. This gives a 20% firerate buff to help bring the gun back to a healthy spot.

## Changelog

:cl:
balance: Raised smg90 rpm from 400 to 480.
/:cl:

2024-10-08 03:15 UTC, Lumipharon requested changes
going to explode your nuts for the funny powercreep pr. also this pr literally does nothing whatsoever

2024-10-08 03:19 UTC, closed without merging

2024-10-08 03:19 UTC, blackdav123 commented
real

2024-10-08 12:09 UTC, iforgotmeword commented
Late but if you made it do less damage per shot sure 

but a pure buff is kinda not needed the Smg90 is really good even after the buff

2024-10-10 10:53 UTC, SimplySmiley123 commented
> Late but if you made it do less damage per shot sure
> 
> but a pure buff is kinda not needed the Smg90 is really good even after the buff

Nobody uses it when squashead smg45 exists and mp19 is better for running and gunning.