Having 100% Fire Armor Gives You Actual Fire Immunity
tgstation/TerraGov-Marine-Corps pull request #16658
Opened 2024-10-11 10:12 UTC by Runian

## About The Pull Request
Fire and the type of fire that Pyrogen uses now considers soft armor (instead of hard armor) and also prevents your body temperature from increasing. This means:
- No more endless screaming for walking through fire.
- No more taking damage for walking through fire.
- No more getting too hot for walking through fire.
- Because of all of the above, your very fragile splints no longer instantly break for walking through fire.

## Why It's Good For The Game
I hope that H-Armor + Surt not getting actual fire immunity is a bug and not a feature.

## Changelog
:cl:
fix: All types of fire no longer damages or heats you up if you have 100% fire soft/hard armor.
/:cl:

2024-10-11 10:46 UTC, FosterGrime-Heymynameslouie commented
I believe the surt with heavy armor is intended in this pr

heavy slowdown but fire immune with surt

https://github.com/tgstation/TerraGov-Marine-Corps/pull/16029

2024-10-12 17:16 UTC, Mannybrado commented
the surt buff all surtheads were waiting for

2024-10-13 01:45 UTC, Lumipharon requested changes
I would just sap the hard armour checks for soft armour. The hardarmour checks are a legacy from how surt used to work

2024-10-14 20:14 UTC, Lumipharon approved these changes

2024-10-14 20:14 UTC, merged