Fixes skinks equipping C4 as a weapon
tgstation/TerraGov-Marine-Corps pull request #16700
Opened 2024-10-26 19:42 UTC by blackdav123

## About The Pull Request
Skinks are not meant to have any combat capabilities.

## Why It's Good For The Game
No more unavoidable dev explosive.

## Changelog

:cl:
fix: Skinks can no longer take c4 as a weapon.
/:cl:

2024-10-26 19:44 UTC, TiviPlus requested changes

2024-10-26 19:44 UTC, TiviPlus commented on code/modules/vehicles/unmanned/unmanned_vehicle.dm
> +			return equip_turret(I, user)
```suggestion
		if(allow_explosives)
			return equip_turret(I, user)
```

2024-10-26 19:54 UTC, ivanmixo commented on code/modules/vehicles/unmanned/unmanned_vehicle.dm
> +		if(allow_explosives)
```suggestion
	if(istype(I, /obj/item/explosive/plastique) && allow_explosives)
```

2024-10-27 13:11 UTC, ivanmixo approved these changes

2024-10-27 15:15 UTC, Kuro020 approved these changes

2024-10-29 16:32 UTC, merged