Adds new marine race: Prototype Supersoldier
tgstation/TerraGov-Marine-Corps pull request #16725
Opened 2024-11-03 14:00 UTC by TiviPlus

## About The Pull Request

See https://hackmd.io/ExRkEaTGR5GyECMeeQB1XA?view

naming Convention: [A-Z][num][A-Z] - [Fighting Role] e.g A2V Saboteur
Basically physically taller and weaker human (Slower at speed of walking with no shoes, 30 instead of 50 default max stam and -25 crit threshold instead of -50), but they get access to "Stims" which is temp buffs to stuff like melee, deafness immunity, stam increases, etc.

Every 10 minutes you need to reselect stims which needs a cast time, you can have up to 5 active at once, sequences are savable accross rounds, you can have up to 10 total

Default options is
scatter decrease, no stack
accuracy increase, no stack
no_ear_damage, no stack
no_flashbang, no stack
no_footsteps, no stack
portal_toggle (makes you go through wraith portals if you want to), no stack
speed_increase, negates default speed decrease
stam_usage_decrease, stacks with decreasing returns, removing 30% cost every time
stamina_regen, stacks
melee skill increase, stacks until it reaches skill 2
powerloader skill increase, stacks but only up to below shipside level skills

Also included misc code improvements while making this

## Why It's Good For The Game

This is more intended as a flex option for marines thats shittier by default but can adapt as needed and also provide something for people building specific strats to fiddle with

Numbers subject to change as usual lmao

## Changelog

:cl:
add: Added the new marine "Prototype Supersoldier" race which is weaker by default but can use stimulants to be more flexible
/:cl:

2024-11-03 14:10 UTC, FosterGrime-Heymynameslouie commented
ZENKAI BOOST MARINE

2024-11-03 14:58 UTC, Kuro020 approved these changes

2024-11-03 15:31 UTC, iforgotmeword commented
awful fucking idea
speed merge now :)

2024-11-03 17:59 UTC, Pariah919 commented
This seems like a bad idea and will lead to constant abuse by niche strats and being a downgrade everywhere else. 80% of those stims are bad, useless, or so incredibly niche it makes half the Dead by Daylight perk pool look usable. The other half is straight buffs.
Ignoring the max height change, which is ugly and will always look ugly since you're streching sprites by code.

2024-11-03 18:24 UTC, blackdav123 commented
might be worth rolling the ear and flashbang into one perk

2024-11-03 19:25 UTC, DrAmazing343 commented
VALIBROS...
>stam
>melee skill
>wraith portal
ARE WE FUCKING BACK???

2024-11-03 20:00 UTC, Apple-107 commented
holy based

2024-11-03 21:28 UTC, FunkyMonke47 commented
NANOMACHINES, SON

2024-11-03 23:20 UTC, yyzsong commented
Fuck you bring back elves

2024-11-04 03:07 UTC, Lumipharon commented
Wait, do ~~Aeldari~~ PROTOTYPE SUPER SOLDIERS just look exactly like normal humans lol?

2024-11-04 04:25 UTC, ilikesaying commented
Taller Humans

2024-11-24 01:01 UTC, Lumipharon requested changes
Super. Army. Soldiers.

2024-11-25 00:44 UTC, iforgotmeword commented
Personally after trying it out it's just funky
is all I got to say

It's something I wouldn't personally be using but more variety is always good

2024-11-25 05:16 UTC, Runian commented on code/datums/actions/species_actions/prototype_supersoldier_action.dm
> +	cast_say = "Adminstering adrenaline..."
typo. Adminstering -> Administering

2024-11-25 10:17 UTC, FunkyMonke47 commented
this is pretty funky, but there really aren't that many options here. Going melee is a meme with the higher pain crit threshold. (you will get crit once and dragged to brazil) And besides that, it's just being a super accurate gun boi or being able to run forever, I guess. (would not be surprised if that's pretty op with light armor.) But like, nothing is really stopping anyone from adding extra options in the future with pr's, so we'll see I guess.

2024-11-26 23:13 UTC, Nerev4r commented
the stim UI is kinda quirky if you switch between different setups

2024-11-27 00:33 UTC, PibeCantina commented
Stims are kinda buggy when you try to change the order. 
Also race is not that good in general (that's fine!!), i think recoil reduction stims would be cool.........

2024-11-27 02:34 UTC, yyzsong commented
five buffs is way too many given how fucking dogshit most of these are.

2024-11-28 18:52 UTC, Aporhtonoma commented
If anything moves you during injection of stims it fails and it does not let you to continue stimming from where you left off. Even if you change the order of stims

2024-12-08 20:58 UTC, Lumipharon commented
This seems purpose built to enable cringe builds we have gone out of our way to nerf into the ground.
I.e. high speed akimbo spam etc.

2024-12-10 09:23 UTC, Looking4bros commented
A shame Melee Skill was nerfed ong. The crit reduction is a bit much for attempting sustained Vali use(as much a meme as it is) as before the xenomorph stat buffs fighting near crit threshold was normal, and if the ticks don't line up nicely to heal out of it, it's usually a death sentence.

Charged Claymores going from roughly 144 to 187 on lightly armored ~~marines~~ Xenomorphs is pretty dope.

2024-12-10 17:46 UTC, tttruancy commented
> This seems purpose built to enable cringe builds we have gone out of our way to nerf into the ground. I.e. high speed akimbo spam etc.

Hard agree. While this is food for the powergamers, the long term on this is that we will end up nerfing 1-handable guns to compensate for the supersoldiers, which will in turn make those weapons unviable outside of supersoldier powergaming. 

 The game is hard enough to balance without this added dimension.

2024-12-11 04:05 UTC, FunkyMonke47 commented
eh, the higher pain crit threshold is way more of a downside than you'd think. And honestly, most dual wields you can manage with this are just kinda memes. You can sprint for a really long time, but once again, trying to chase xenos when you can get crit faster and dragged forever when you get pain crit, makes it kinda a high risk high reward kinda thing.

2024-12-13 19:42 UTC, Apple-107 commented
Shit's amazing, awesome PR, absurdly funny and a xope generator at its finest.

Maybe don't merge it.

2024-12-20 15:24 UTC, Vincent983 commented
you can't spawn in valhalla as these for some reason

2025-01-08 03:49 UTC, Looking4bros commented
For Melee, the 25 crit threshold difference is felt, however, with gigga mixes, it is reminiscent of RR, only in that you dip between crit and not crit more often. Funny, but not as effective, and leans towards ganked earlier. Niche, may try it with spear.

As there are zero buffs i would take situationally right now, The ability to lock in, or renew the timers of the current stims would be most appreciated. The thought that i could lose the wopping ~15 damage per hit i'm trading the crit threshold for mid fight rests on me.

Only "situational" buffs i could think of would be Engineering/Medical/Surgical skill buff. Otherwise.. :shrug:

Very :eyes:

Was also some UI issues, but the buttons for the loadouts worked even if they read the list of stims wrong in the menu.

2025-01-11 02:59 UTC, Looking4bros commented
This stuff is baller with Spear, even when not using it with Tricordrazine(the damage dealing chem). This is also permissive of Researchers (me) playing like a sidegrade Corpsmen/Doctor hybrid. sidegrade, as you're without the medivac and other points stuff, but have some surgical skill. 👍 pretty neat.

2025-01-11 17:10 UTC, merged

2025-01-14 05:34 UTC, Looking4bros commented
could we get them in Valhalla? 👁️ :eye: