Give (some) privacy back to nuke activation
tgstation/TerraGov-Marine-Corps pull request #16770
Opened 2024-11-27 21:03 UTC by AusarAtkin

## About The Pull Request

Prevent activating nuke from showing both your ic name and ckey in dchat

## Why It's Good For The Game

Good for people that want to keep their IC secret

## Changelog

:cl:
fix: fixed nuke notification in dchat
/:cl:

2024-11-27 23:41 UTC, Helg2 commented
Why hide IC name from the message tho?

2024-11-28 08:21 UTC, AusarAtkin commented
> Why hide IC name from the message tho?

Because this is the simplest fix, and the important bits is logged anyway.

2024-12-02 23:02 UTC, Lumipharon requested changes
add an admin log

2024-12-03 03:46 UTC, Lumipharon approved these changes
oh, so there is

2024-12-03 03:47 UTC, merged