reverts kuro shrike speed nerf and also health buff
tgstation/TerraGov-Marine-Corps pull request #16815
Opened 2024-12-13 17:49 UTC by yyzsong

## About The Pull Request
Changes shrike's speed from -0.4 -> -0.6
## Why It's Good For The Game
Shrike losing this much speed really hurts it as a caste especially given that they have no sort of gapclosing ability like, say, warrior does. Its two stuns also move marines away from it, meaning that it's heavily dependent on positioning to make full use of the duration of the stun for things like oze sting.

It's also worth mentioning that 0.2 slowdown for a measly _100 health_ and _2 slash damage_ is nowhere near a worthwhile trade; to bring up warrior again, it got 100 hp, a sunder mult, and three slash damage for _0.1 movespeed._

It may be worthless to point out but shrike is also an essential part of xeno, so being forced into this sluggish ass caste to prevent the hive from collapsing is just really fucking annoying.
## Changelog
:cl:
balance: Buffed shrike's movespeed (-0.4 -> -0.6)
balance: reverted shrike HP buff (500 -> 400)
/:cl:

2024-12-13 18:38 UTC, Pariah919 commented
This is basically the only movement change that actually mattered in practice. If this gets in it basically means the entire 'i'm making xenos slower' is basically untrue from kurrito PR.

2024-12-13 18:38 UTC, ivanmixo commented
Just to reiterate what I said on discord, I don't think shrike should be both tankier and more damaging AND faster compared to pre-kurt buffs. Should either be speedy or tankier, not both. 



> It's also worth mentioning that 0.2 slowdown for a measly _100 health_ and _2 slash damage_ is nowhere near a worthwhile trade

This is a comical statement, almost reminds me of when people whine about tank *only* critting xenos. These are both major, major buffs.

2024-12-13 20:37 UTC, Naaanii commented
Finally.

Also keeping the slash and health buffs are kinda cringe. At least remove one of them if you're not doing a flat revert.

2024-12-13 23:51 UTC, yyzsong commented
> tankier

no matter what they never feel tanky... 😔

2024-12-14 05:11 UTC, Apple-107 commented
> > tankier
> 
> no matter what they never feel tanky... 😔

I dont think many people understand just how much dps you will eat in moderately common scenarios

2024-12-14 12:41 UTC, tttruancy commented
Definitely agree on the issue with shrike following up it's own stuns, it's very cringe to watch a shrike fling a marine, chase, and get one slash at best before the marine is actionable again.

2024-12-15 13:37 UTC, Kuro020 requested changes
If you want to buff shrikes speed, make it -0.5 and leave hp at 450, were not going back to speedy fast shrike

2024-12-16 13:43 UTC, iforgotmeword commented
Why is speedy shirke bad? At most I can think delay

2024-12-17 16:10 UTC, ivanmixo approved these changes

2024-12-17 16:10 UTC, merged

2025-01-29 06:57 UTC, SpiderPsycho commented
This is not a good change. Functionally this change just gives shrike a marginal speed increase PRIOR to a fight and less health. 

So in practice this is what happens:
1. Get into a fight marginally faster
2. Get staggered/slowed down because marines have an abundance of slowdown/stun weapons
3. Aformentioned movement increase is gone
4. You're stuck trying to disengage and missing 100HP

Functionally this is a nerf. This speed increase, especially such a minor speed increase, isn't enough to actually matter in shrike engagements. Made all the worse when Shrike is necessary on lowpop nuke war and is the only T4 avaliable. If you're going to make this an actual rebalance, increase the movement speed so that it's actually significant and or give the shrike more total plasma to play around with since they're weeding and in combat.