TGMC Christmas 2024
tgstation/TerraGov-Marine-Corps pull request #16820
Opened 2024-12-17 06:06 UTC by RipGrayson

## About The Pull Request

![Gemini_Generated_Image_qcr42lqcr42lqcr4](https://github.com/user-attachments/assets/f4e26f6a-d8d3-47d5-bd13-690a2a4f114d)

With Thanksgiving officially over, it's time to move onto the next holiday.
Introducing the TGMC Christmas PR, this PR

-Adds festive decorations to all ships and shuttles.
-Adds Christmas food and drink to all ships and shuttles.
-Places Christmas trees throughout the ships.
-Implements gifts with randomly generated presents inside, much like TG already does (for the sake of balance the items are much more curated compared to TG.)
-Allows players the magical chance to meet Santa and his elves face to face.
-Various other surprises and things I can't be bothered to note.

This PR isn't meant to be merged, only TMC'ed. At a later date I _might_ add some of the holiday stuff into the code itself for easier reuse in future Christmases.

## Why It's Good For The Game

We didn't have Christmas in 2021, I have taken it upon myself to fix this problem. If you don't like this PR you are officially a scrooge who needs to embark on a vaguely allegorical journey to learn the true meaning of Christmas.

## Changelog
:cl:
add: Added Christmas. If you're seeing this in game the PR was merged somehow, whoops.
/:cl:

2024-12-18 17:19 UTC, MLGTASTICa commented
No mention of boiler lobbing gifts instead of globs. Christmas ruined.

2024-12-20 16:40 UTC, ivanmixo requested changes

2024-12-20 16:40 UTC, ivanmixo commented on code/game/objects/items/storage/pouch.dm
> -	storage_datum.storage_slots = 7
?

2024-12-20 23:41 UTC, RipGrayson commented on code/game/objects/items/storage/pouch.dm
> -	storage_datum.storage_slots = 7
Accident, probably caused by copypasting code from old branch

2024-12-21 19:52 UTC, TiviPlus approved these changes

2024-12-27 02:37 UTC, RipGrayson commented
It's not Christmas anymore

2024-12-27 02:37 UTC, closed without merging

2025-12-06 06:08 UTC, RipGrayson commented
Christmas is here again