Xeno acid mortar & jaw now show up on map and in hive status
tgstation/TerraGov-Marine-Corps pull request #16830
Opened 2024-12-19 04:42 UTC by Mantlecrawler

## About The Pull Request
Adds a minimap icon for acid maw & jaw and makes them show up on hive status
![image](https://github.com/user-attachments/assets/a384ef3e-fdd0-48e6-8c25-749e9d615b66)
![image](https://github.com/user-attachments/assets/0e6fccbf-dfbc-48ae-abd9-54e2e8ef15b2)
## Why It's Good For The Game
Quality of life
## Changelog

:cl:
qol: Acid Maw & Jaw now show up on hive status and on minimap
/:cl:

2024-12-19 05:13 UTC, Lumipharon commented
McXonalds

Also why did you only make one icon?

2024-12-19 05:35 UTC, Mantlecrawler commented
> McXonalds
> 
> Also why did you only make one icon?

I couldnt easily fit a J in for Jaw and i couldnt think of anything else to properly represent it

2024-12-22 20:52 UTC, Lumipharon commented
You do know xeno icons are like 80% just recolours of other xeno icons right? Add a second one

2024-12-22 23:46 UTC, Mantlecrawler commented
@Lumipharon 
![image](https://github.com/user-attachments/assets/03e5752c-4fd5-4b85-9bc1-45da4caf86b6)

2024-12-29 20:53 UTC, Lumipharon requested changes

2024-12-29 20:53 UTC, Lumipharon commented on code/modules/xenomorph/maw.dm
> +	. = ..()
```suggestion
	return ..()
```

2024-12-29 20:53 UTC, Lumipharon commented on code/modules/xenomorph/maw.dm
> +	minimap_icon = "acid_jaw"
where's the other one bozo

2024-12-29 20:55 UTC, Mantlecrawler commented on code/modules/xenomorph/maw.dm
> +	minimap_icon = "acid_jaw"
thats jaw, maw is above goober

2024-12-29 21:03 UTC, Lumipharon approved these changes

2024-12-30 22:22 UTC, merged