Removes a crash site from research outpost
tgstation/TerraGov-Marine-Corps pull request #16858
Opened 2024-12-31 15:56 UTC by yyzsong

## About The Pull Request
The way this crashsite is positioned cuts off one of the entrances as well as well as one of the entrances to the southern disk site. Kinda cringe.

## Why It's Good For The Game

## Changelog

:cl:
balance: removes a landing site in research outpost for marines in the crash gamemode.
/:cl:

2024-12-31 16:03 UTC, blackdav123 commented
i just added this one i think the fights it does have are a lot more interesting than other sites and would be sad to see it go

2025-01-04 04:08 UTC, Barnet2 requested changes
It does seem like a nifty fighting area, but I also dislike having Canterbury spots simply blocked off. Perhaps a bit more and up to the left—either way, keep it around the spot and just adjust to allow it to exist.

2025-01-13 19:51 UTC, yyzsong commented
moved the landing site, here's the new one
![image](https://github.com/user-attachments/assets/cd4585df-6ceb-42ef-9774-7aeda2f61fa2)
![image](https://github.com/user-attachments/assets/6f007ad0-e69b-47c7-9041-0d9113103a00)

2025-01-14 19:28 UTC, Barnet2 approved these changes

2025-01-21 05:49 UTC, merged