Headphones
tgstation/TerraGov-Marine-Corps pull request #4647
Opened 2020-08-05 16:53 UTC by TiviPlus

## About The Pull Request

Uses ytdl
since it uses goonchat output you cant lag the server with it, and theres a limiter on the music list

## Why It's Good For The Game

My ingame sound breaks when I play music on spotify :(

## Changelog
:cl:
add: Added headphones that play music off of youtube
/:cl:

2020-08-05 17:20 UTC, Hughgent commented on code/modules/clothing/head/headphones.dm
> +	if((C.prefs.toggles_sound & SOUND_MIDI) && C.chatOutput?.working && C.chatOutput.loaded)
This might not need the prefs check, because the player is actively choosing to 'listen to music'

2020-08-05 18:12 UTC, psykzz commented
I love the idea but i dont think it can go through, we have issues already with youtube blocking us for admin use, if we give that to the players we'd likely be forever blocked.

2020-08-05 20:15 UTC, TiviPlus commented
Don't know till we try!

2020-08-19 12:18 UTC, TheBimmer231 requested changes
That's some garbage honestly, Ping me, I'll help you out.

2020-09-08 22:14 UTC, TiviPlus commented
Ytdl keeps breaking iwth this, sad

2020-09-08 22:14 UTC, closed without merging