PSG Auto Sniper
tgstation/TerraGov-Marine-Corps pull request #4740
Opened 2020-08-26 10:45 UTC by David-Stormwell

## About The Pull Request

Adds a brand new will be req only NV IFF automatic sniper rifle! It shares the same stats as the normal bolt action, but is a tad slower with a 1.75 second fire delay vs the bolt action's 1.35.
Also fixed a small typo in the bolt action sniper rifle's desc from "Uses 10x24mm box magazines." to "Uses 8.6×70mm box magazines.".

## Why It's Good For The Game

It's been planed for a while, and more guns that fit the theme for marines to work towards when getting points and miners up as a treat!

## Changelog
:cl:
add: Added a Automatic NV, IFF Sniper rifle.
imageadd: added some icons for the Auto Sniper and NV scope.
imagedel: Replaced the old NV scope with the new one.
spellcheck: fixed a small typo in the Bolt action sniper rifle's desc.
/:cl:

2020-08-26 10:47 UTC, ilikesaying commented
David is going on another genocide spree

2020-08-28 08:05 UTC, SilencedMP5A5 commented
does it still have lase

2020-08-28 14:07 UTC, TheBimmer231 approved these changes
I will not approve this sprite until a shorter one Is made, I already voiced my concern over the length but I guess It was ignored, too bad.

2020-08-28 14:08 UTC, TheBimmer231 requested changes
fuck I actually approved, my bad, but yeah, ping me.

2020-08-28 22:54 UTC, David-Stormwell commented
> 
> 
> does it still have lase

No

2020-08-28 23:05 UTC, SilencedMP5A5 commented
kinda bad then ngl

2020-09-01 07:38 UTC, TheBimmer231 approved these changes
still fucking long as hell, but acceptable.

2020-09-02 11:36 UTC, TiviPlus approved these changes

2020-09-09 04:31 UTC, XSlayer300 commented on code/modules/projectiles/guns/rifles.dm
> +	name = "\improper T-81 Automatic Sniper Rifle"
```suggestion
	name = "\improper T-81 automatic sniper rifle"
```

2020-09-09 04:32 UTC, XSlayer300 commented on code/modules/projectiles/guns/rifles.dm
> +	desc = "The T-81 AS is the TerraGov Marine Corps Automatic Sniper Rifle. It is rather well-known for it's night vision scope and IFF ammo, it however lacks a burst fire mode. It is mostly used by pe
```suggestion
	desc = "The T-81 is the TerraGov Marine Corps's automatic sniper rifle. It is rather well-known for it's night vision scope and IFF ammo, it however lacks a burst fire mode. It is mostly used by people who prefer to do more careful shooting than most. Uses 8.6x70mm caseless IFF caliber."
```

2020-09-09 04:32 UTC, XSlayer300 commented on code/modules/projectiles/magazines/rifles.dm
> +	name = "T-81 Automatic sniper rifle magazine"
```suggestion
	name = "\improper T-81 automatic sniper rifle magazine"
```

2020-09-12 13:26 UTC, merged