Adds a recoilless rifle, bag to carry the ammo and its rockets.
tgstation/TerraGov-Marine-Corps pull request #4768
Opened 2020-09-04 23:26 UTC by Pariah919

## About The Pull Request
Adds a light recoilless rifle to eventually be added to marines once I get sprites one day.
Otherwise it adds it, the bag to carry the ammo, and the ammo itself.
It has LE (big small explosion over a big area)/HE (Big explosion over a small area) and HEAT (Big explosion over a small area and big direct damage).

## Why It's Good For The Game
More options for marines, I'm gonna add this to req in a pack where you get 3 LE/1 HEAT/2 HE+Bag+Rifle one day.

## Changelog
:cl:
add: Added a recoilless rifle and bag for it.
/:cl:

2020-09-04 23:27 UTC, tgstation-server commented
You currently have a negative Fix/Feature pull request delta of -42. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

2020-09-19 00:34 UTC, TiviPlus reviewed
Will review again later

2020-09-19 00:34 UTC, TiviPlus commented on code/modules/projectiles/ammo_datums.dm
> +	sound_bounce	= "rocket_bounce"
```suggestion
	hud_state_empty = "shell_empty"
```

2020-09-19 00:34 UTC, TiviPlus commented on code/modules/projectiles/ammo_datums.dm
> +	sound_bounce	= "rocket_bounce"
```suggestion
```

2020-09-19 00:34 UTC, TiviPlus commented on code/modules/projectiles/ammo_datums.dm
> +	sound_bounce	= "rocket_bounce"
```suggestion
```

2020-09-19 00:34 UTC, TiviPlus commented on code/modules/projectiles/guns/specialist.dm
> +	name = "\improper T-160 recoilless rifle"
better type name please, for example /recoilless_rifle

2020-09-19 00:34 UTC, TiviPlus commented on code/modules/projectiles/guns/specialist.dm
> +	unload_sound = 'sound/weapons/guns/interact/launcher_reload.ogg'
```suggestion
```
smh at least check your copypaste

2020-09-20 03:35 UTC, Hathkar commented
Looks a bit too much like an RPG when on the back and wielded.

2020-09-21 19:23 UTC, Chaznoodles commented
Seems weird that the shells don't fit in G8 storage or backpacks/satchels, whereas you can fit whole mortar shells or big RPG rockets in them.

2020-09-22 22:50 UTC, TiviPlus requested changes
Make it either a standard squad leader equipment that makes you worse at using it the more leadership you have (ideal option) or make it req only.
SLs using all their points to be wannabe specs is lame

2020-09-22 23:09 UTC, TiviPlus approved these changes
TM for a few rounds to see how putting it in req plays out, will merge after

2020-09-24 22:38 UTC, TiviPlus approved these changes

2020-09-24 22:39 UTC, merged

2020-09-24 22:39 UTC, tgstation-server commented
Your Fix/Feature pull request delta is currently below zero (-45). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.