makes sadar into another rocket type
tgstation/TerraGov-Marine-Corps pull request #4929
Opened 2020-09-30 22:35 UTC by Pariah919

## About The Pull Request
makes sadars into another rocket type and makes a generic rpg

## Why It's Good For The Game
makes it so you can't get the regular rocket so it doesn't load into other rocket launchers

## Changelog
:cl:
add: Added a generic rpg
fix: fixed the ability to load ap/wp/he sadar rockets in other rpgs
w a player might be affected by the changes rather than a summary of the PR's contents. -->

2020-10-01 00:34 UTC, Hughgent commented on code/modules/projectiles/guns/specialist.dm
> +	desc = "The M-5 is the primary anti-armor used around the galaxy. Used to take out light-tanks and enemy structures, the T-152 rocket launcher is a dangerous weapon with a variety of combat uses. Us
Missed at T-152

2020-10-01 00:35 UTC, Hughgent approved these changes

2020-10-02 17:32 UTC, TiviPlus requested changes
What hugh said

2020-10-04 07:58 UTC, Fikou commented on code/modules/projectiles/guns/specialist.dm
> +	desc = "The M-5 is the primary anti-armor used around the galaxy. Used to take out light-tanks and enemy structures, the T-152 rocket launcher is a dangerous weapon with a variety of combat uses. Us
```suggestion
	desc = "The M-5 is the primary anti-armor used around the galaxy. Used to take out light-tanks and enemy structures, the M-5 rocket launcher is a dangerous weapon with a variety of combat uses. Uses a variety of 84mm rockets."
```

2020-10-07 09:51 UTC, TiviPlus approved these changes

2020-10-09 20:47 UTC, merged