Adds a SLR to the game
tgstation/TerraGov-Marine-Corps pull request #4955
Opened 2020-10-05 04:06 UTC by Pariah919

## About The Pull Request
I'll probably make this an ERT gun for freelancers one day.

## Why It's Good For The Game
Adds a non marine gun that's in the style.

## Changelog
:cl:
add: Added new rifle. Its in req. That's it.
/:cl:

2020-10-05 04:06 UTC, tgstation-server commented
You currently have a negative Fix/Feature pull request delta of -51. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

2020-10-05 10:52 UTC, XSlayer300 commented on code/modules/projectiles/magazines/rifles.dm
> +	desc = "A 10mm battle rifle magazine."
```suggestion
	desc = "A 7.62mm battle rifle magazine."
```

2020-10-07 09:44 UTC, TiviPlus requested changes
Either make it unique or replace an existing gun and give it to someone

2020-10-09 20:52 UTC, Hughgent requested changes
Missing a bunch of the on mob sprites

back and suit come to mind.

2020-10-10 03:05 UTC, closed without merging