razorwire rebalancing
tgstation/TerraGov-Marine-Corps pull request #4982
Opened 2020-10-09 16:16 UTC by MacBlaze1

## About The Pull Request

this PR makes razorwire effective again, with crushers at max speed dealing 63 damage BEFORE any effects from the razorwire are applied, meaning that 2 acid spits from a spitter or praetorian hits this then the crusher charges, it will destroy the razorwire without consequences to the crusher. Razorwire cannot be repaired at all

## Why It's Good For The Game

this makes razorwire usuable again, but without the inability to do its main function. Marines now have to use metal to maintain a razorwire shield effectively. There is no BS weld repairing infinity. Better hope its in good enough shape and when it breaks repair it fast.

## Changelog
:cl:
del: Removed the ability to repair razorwire with a welder
balance: crushers at full charge now deal 63 damage to razorwire, instead of 105. The razorwire still has 100 health.
/:cl:

2020-10-09 21:02 UTC, Hughgent approved these changes
code looks ok

2020-10-10 13:25 UTC, Daftspy commented
Razorwire isnt good but this seems worse.

2020-10-10 16:38 UTC, MacBlaze1 commented
> Razorwire isnt good but this seems worse.

attacking the razorwire when electrified will make you take a shitton of damage 
before this, crushers would instantly destroy razorwire, making it useless
razorwire is incredibly cheap to make and build, so I feel this price for literally hard countering a crusher isnt too bad

2020-10-10 22:39 UTC, jroinc commented
Seems good to me. The one thing I'd change is to allow razorwire to be repaired in some way.

Allow welding but double the weld timer, add 2 metal rods, something similar.

Just cause my OCD's gonna bug the shit outta me at the FOB.

2020-10-13 15:37 UTC, TiviPlus commented on code/game/objects/structures/razorwire.dm
> +		return
```suggestion
	if(istype(I, /obj/item/stack/sheet/metal))
		var/obj/item/stack/sheet/metal/metal_sheets = I
		visible_message("<span class='notice'>[user] begins to repair \the [src].</span>")
		if(!do_after(user, 2 SECONDS, TRUE, src, BUSY_ICON_FRIENDLY) || obj_integrity >= max_integrity)
			return
		if(!metal_sheets.use(1))
			return
		repair_damage(max_integrity * 0.30)
		visible_message("<span class='notice'>[user] repairs \the [src].</span>")
		update_icon()
		return
```

2020-10-13 15:37 UTC, TiviPlus commented on code/game/objects/structures/razorwire.dm
>  	if(isxeno(user))//I am very tempted to remove this >:)
```suggestion

	if(!istype(I, /obj/item/grab))
		return
	if(isxeno(user))//I am very tempted to remove this >:)
```

2020-10-16 16:37 UTC, TiviPlus requested changes
The PR was fine until you made the new changes so undo the repair thing and explain the sunder change or revert it

2020-10-16 17:05 UTC, MacBlaze1 commented
> The PR was fine until you made the new changes so undo the repair thing and explain the sunder change or revert it

ren told me to do this

2020-10-17 17:08 UTC, TiviPlus approved these changes

2020-10-17 17:08 UTC, merged