adds slouch hats to tgmc
tgstation/TerraGov-Marine-Corps pull request #5004
Opened 2020-10-13 00:10 UTC by Pariah919

## About The Pull Request
adds slouch hats, by nixon

## Why It's Good For The Game
style is cool

## Changelog
:cl:
Nixon, Pariah919
add: Added new slouch hats

2020-10-13 00:10 UTC, tgstation-server commented
You currently have a negative Fix/Feature pull request delta of -49. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

2020-10-13 08:24 UTC, TiviPlus requested changes
make the typepath more legible ie something like /slouch
Also your CL is broke

2020-10-14 21:15 UTC, TiviPlus approved these changes

2020-10-14 21:15 UTC, merged

2020-10-14 21:15 UTC, tgstation-server commented
Your Fix/Feature pull request delta is currently below zero (-50). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.