Fixes Imperial Guard armor
tgstation/TerraGov-Marine-Corps pull request #5014
Opened 2020-10-14 20:02 UTC by ondrej008

## About The Pull Request

I hate the person that put the m_ prefix into the held .dmi, but not the worn .dmi

## Why It's Good For The Game

armor isn't invisible anymore

## Changelog
:cl:
fix: haha funny imperial ERT now has armor (shocking)
/:cl:

2020-10-14 20:05 UTC, Hughgent commented
Yo, got a picture of this working?

2020-10-14 20:18 UTC, ondrej008 commented
> 
> 
> Yo, got a picture of this working?

![obrazek](https://user-images.githubusercontent.com/8739855/96040768-216ccc80-0e6b-11eb-837e-a761e9f12fe3.png)

2020-10-15 22:55 UTC, TiviPlus requested changes

2020-10-15 22:55 UTC, TiviPlus commented on code/modules/clothing/suits/marine_armor.dm
> +	item_state = "fuck_whoever_broke_my_fucking_armor"
hmmmmmmm

2020-10-29 16:33 UTC, ondrej008 commented on code/modules/clothing/suits/marine_armor.dm
> +	item_state = "fuck_whoever_broke_my_fucking_armor"
do I have to change this

2020-11-01 13:53 UTC, TiviPlus commented on code/modules/clothing/suits/marine_armor.dm
> +	item_state = "fuck_whoever_broke_my_fucking_armor"
yes

2020-11-18 00:12 UTC, closed without merging