Replaces the M39 with a different gun, the MR25
tgstation/TerraGov-Marine-Corps pull request #5031
Opened 2020-10-15 23:36 UTC by Pariah919

## About The Pull Request
title. Its a 1:1 replacement. No stat changes other than giving it baseline accuracy.
Need mr25b2 inhands

## Why It's Good For The Game
More guns in the style is good.

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2020-10-15 23:37 UTC, tgstation-server commented
You currently have a negative Fix/Feature pull request delta of -51. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

2020-10-16 20:54 UTC, TiviPlus requested changes
remove the unused sprites
is the stock used anywhere and if no remove it too

2020-10-17 01:57 UTC, Pariah919 commented
@TiviPlus i did ur changes

2020-10-17 15:38 UTC, TiviPlus approved these changes

2020-10-17 15:39 UTC, merged