Toolbox Tournament Trophy and co.
tgstation/TerraGov-Marine-Corps pull request #5044
Opened 2020-10-18 00:11 UTC by XSlayer300

## About The Pull Request
Adds the toolbox trophy at EORD and the Thunderdome arena, in addition to other features said below.

## Why It's Good For The Game
They had fought well. Don't forget that one PR with fixes is better than having more.

## Changelog
:cl:
add: Added the Toolbox Trophy for Toolbox for a Cause 2020 in both EORD and Thunderdome arena. It is indestructable and unacidable.
tweak: In addition to the toolbox trophy, all memorials are now indestructable and unacidable.
fix: MJP FORGOT TO FIX HIS M25 SPRITES AGAIN AAAAAAAAAAAAAAAAAAAAAAAAAAA.<br>and so I fixed it.
fix: Fixed those invisible wooden windows at EORD, along with the other windows that got the typo.
/:cl:

2020-10-18 00:13 UTC, Hughgent approved these changes

2020-10-18 09:15 UTC, TiviPlus requested changes
Fix changelog
The checks broke so post pictures of it on centcom please
You sure you dont want to add RESIST_ALL?

2020-10-20 08:02 UTC, TiviPlus requested changes
Can you make it ONE trophy inside one of the EORD rooms please so that it fits in/doesnt get in the way

2020-10-21 20:03 UTC, TiviPlus approved these changes
We'll win next year 😏

2020-10-21 20:03 UTC, merged