allows engineers to repair three separate barricades at a time, but only 1 repair at a time per barricade
tgstation/TerraGov-Marine-Corps pull request #5049
Opened 2020-10-19 14:38 UTC by MacBlaze1

## About The Pull Request

This PR adds an actioned_list which allows for tracking of do_after targets and should lead to future usage for it, while also allowing engineers to repair 3 separate barricades, only one time each (no spam repairing). 

## Why It's Good For The Game

This will make spitter's incredibly undeescalated spit damage less effective. This does not improve repairing on anything else but metal barricades.

## Changelog
:cl:
add: Added new list in mob_defines that is used for storing action targets.
balance: welders can now repair up to 3 metal barricades, but only 1 repair action per barricade.

/:cl:

2020-10-20 17:26 UTC, Hughgent approved these changes

2020-10-24 09:26 UTC, TiviPlus requested changes
Just turn action list into in assoc list theres no reason to waste memory like this

2020-10-25 16:37 UTC, MacBlaze1 commented
> Just turn action list into in assoc list theres no reason to waste memory like this

did

2020-11-02 20:13 UTC, TiviPlus requested changes
Add a comment to var/action_busy that its deprecated and illl merge

2020-11-18 00:12 UTC, closed without merging