Fixes hivemind weeding
tgstation/TerraGov-Marine-Corps pull request #5075
Opened 2020-10-23 15:26 UTC by TiviPlus

## About The Pull Request

I am going to stab splinter with a rusty nail for using a space

## Changelog
:cl:
fix: Hvemind can weed
/:cl:

2020-10-23 15:32 UTC, Hughgent approved these changes

2020-10-24 03:37 UTC, ilikesaying commented
is he going to get a _**splinter?**_

2020-10-24 07:22 UTC, Shadow-Quill requested changes

2020-10-24 07:22 UTC, Shadow-Quill commented on code/modules/mob/living/carbon/xenomorph/abilities.dm
> +	to_chat(hiveminde, "<span class='xenonotice'>We can't place weeds with no weeds nearby, we got moved to our core.</span>")
why is it hiveminde?

2020-10-24 07:22 UTC, Shadow-Quill commented on code/modules/mob/living/carbon/xenomorph/abilities.dm
> +	to_chat(hiveminde, "<span class='xenonotice'>We can't place weeds with no weeds nearby, we got moved to our core.</span>")
```suggestion
	to_chat(hiveminde, "<span class='xenonotice'>We can't place weeds with any weeds nearby, so we got moved to our core.</span>")
```

2020-10-24 07:26 UTC, SplinterGP commented on code/modules/mob/living/carbon/xenomorph/abilities.dm
> +	to_chat(hiveminde, "<span class='xenonotice'>We can't place weeds with no weeds nearby, we got moved to our core.</span>")
But its with no weeds nearby

2020-10-24 07:26 UTC, SplinterGP commented on code/modules/mob/living/carbon/xenomorph/abilities.dm
> +	to_chat(hiveminde, "<span class='xenonotice'>We can't place weeds with no weeds nearby, we got moved to our core.</span>")
Hivemind cringe, hiveminde ok.

2020-10-24 09:09 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/abilities.dm
> +		return ..()
```suggestion
	if(locate(/obj/effect/alien/weeds) in range(1, owner.loc))
		return ..()
```

2020-10-24 18:20 UTC, SplinterGP commented
> is he going to get a _**splinter?**_

I'll need it 😿

2020-10-24 18:43 UTC, merged

2020-10-25 05:56 UTC, Shadow-Quill commented on code/modules/mob/living/carbon/xenomorph/abilities.dm
> +	to_chat(hiveminde, "<span class='xenonotice'>We can't place weeds with no weeds nearby, we got moved to our core.</span>")
Any would be correct here.