replaces iron sugar with blood bag syringe case
tgstation/TerraGov-Marine-Corps pull request #5115
Opened 2020-10-29 02:34 UTC by Pariah919

## About The Pull Request
you can inject people with blood instead of giving them pills which are pure noobtraps for medics

## Why It's Good For The Game
~~jpr said i'd close this~~ removes a noob trap option and replaces it with something that does the job actually decently

## Changelog
:cl:
add: Added emergency drawable O- blood bags that are drawable, a syringe case that has 2, added to medic vendor
del:ironsugar from medic vendosrs
/:cl:

2020-10-29 02:34 UTC, tgstation-server commented
You currently have a negative Fix/Feature pull request delta of -54. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

2020-10-29 02:39 UTC, jroinc commented
He's just gonna close it, same with every PR.

That said, I like this and think it's balanced. I was trying to think of a decent way to let medics transfer blood, and this is a better way than ironsugar (which is still useful, but for very, very longterm healing).

2020-10-30 18:14 UTC, Hughgent approved these changes

2020-10-30 18:14 UTC, Hughgent commented on code/game/objects/items/reagent_containers/blood_pack.dm
> +	icon_state = "bottle"
I like the idea, but I would prefer a new sprite for this blood bag, perhaps the current blood bag but thinner.

2020-11-04 16:08 UTC, TiviPlus requested changes
Get a sprite for it

2020-11-13 18:14 UTC, closed without merging

2020-11-13 19:45 UTC, jroinc commented
Called it.