Make Camo Tarps Great Again
tgstation/TerraGov-Marine-Corps pull request #5150
Opened 2020-11-03 07:50 UTC by Surrealaser

## About The Pull Request

Per the changelog.

## Why It's Good For The Game

Makes camo tarps great again for ambushes and guerrilla tactics rather than being nearly worthless and far too situational.

## Changelog
:cl:
tweak: Xenos no longer auto-open camo tarps by moving over them.
tweak: Acid spray and gas, bullets (including spits) and phosphorous gas now all force camo tarp occupants out and affect them.
tweak: Camo tarps now stun their former occupant for 0.5 upon leaving.
refactor: Minor refactors of camo tarps.
/:cl:

2020-11-03 08:49 UTC, SplinterGP commented
Hmm, i like it, just the problems i see is, bullets opening it will cause big FF and xenos not opening on passing over is cool but i think it only opening on spit gas cloud etc, a situational downgrade since bullets or anything will openning it meanwhile seeing by that none of the combat castes except from sentinels evolves would be able to deal with tarps.

2020-11-03 09:39 UTC, Surrealaser commented
> Hmm, i like it, just the problems i see is, bullets opening it will cause big FF and xenos not opening on passing over is cool but i think it only opening on spit gas cloud etc, a situational downgrade since bullets or anything will openning it meanwhile seeing by that none of the combat castes except from sentinels evolves would be able to deal with tarps.

You have to actually shoot the bag to hit it with a bullet.

2020-11-03 18:37 UTC, SplinterGP commented
Ah well shoot the bag itself got.it

2020-11-05 08:29 UTC, AbsoluteJerry commented
I FEEL YOUNG AGAIN. THE TARP IS BACK IN THE GAME BOYYYS!!

2020-11-05 09:23 UTC, spookydonut requested changes

2020-11-05 09:23 UTC, spookydonut commented on code/game/objects/effects/aliens.dm
> +		A.acidspray_act()
```suggestion
		SEND_SIGNAL(A, COMSIG_ATOM_ACID_SPRAYED, src)
```

2020-11-05 09:23 UTC, spookydonut commented on code/game/objects/items/marine_gear.dm
> +
```suggestion
	RegisterSignal(src, COMSIG_ATOM_ACID_SPRAYED, .proc/acidspray_act)
```

2020-11-05 09:23 UTC, spookydonut commented on code/game/objects/items/marine_gear.dm
>  	. = ..()
```suggestion
/obj/structure/closet/bodybag/proc/acidspray_act()
```

2020-11-05 09:23 UTC, spookydonut commented on code/game/objects/items/marine_gear.dm
> +	if(CHECK_BITFIELD(S.smoke_traits, SMOKE_XENO_ACID || SMOKE_BLISTERING ) && !opened && bodybag_occupant)
```suggestion
	if((S.smoke_traits & SMOKE_XENO_ACID|SMOKE_BLISTERING) && !opened && bodybag_occupant)
```

2020-11-05 11:36 UTC, spookydonut commented on code/game/objects/effects/aliens.dm
> +	return
```suggestion
```

2020-11-05 11:40 UTC, spookydonut requested changes

2020-11-05 11:40 UTC, spookydonut commented on code/game/objects/items/marine_gear.dm
> +	RegisterSignal(src, COMSIG_ATOM_ACID_SPRAYED, .proc/acidspray_act)
```suggestion
```

2020-11-05 11:40 UTC, spookydonut commented on code/game/objects/items/marine_gear.dm
> +	. = ..()
```suggestion
/obj/structure/closet/bodybag/Initialize(mapload, foldedbag)
	. = ..()
	RegisterSignal(src, COMSIG_ATOM_ACID_SPRAYED, .proc/acidspray_act)
```

2020-11-05 12:11 UTC, spookydonut requested changes

2020-11-05 12:11 UTC, spookydonut commented on code/game/objects/items/bodybag.dm
> +/obj/structure/closet/bodybag/fire_act(exposed_temperature, exposed_volume)
fire_act() is never called its legacy atmos fire stuff.

2020-11-05 12:11 UTC, spookydonut commented on code/game/objects/items/bodybag.dm
> +		S.Crossed(bodybag_occupant) //tarp isn't acid proof; pass it on to the occupant
you shouldnt do this, calling Crossed directly

2020-11-07 03:39 UTC, Surrealaser commented
For those who are curious why progress isn't being made on this, currently waiting on https://github.com/tgstation/TerraGov-Marine-Corps/pull/5174 to merge.

2020-11-07 19:58 UTC, Hughgent commented
Please 'return to full PR' status when you are ready for another review.

2020-11-14 19:46 UTC, Hughgent approved these changes
Nothing immediately strikes me as wrong.

@spookydonut please set the TMC tag if you also approve.

2020-11-17 02:42 UTC, spookydonut requested changes

2020-11-17 02:42 UTC, spookydonut commented on code/game/objects/items/bodybag.dm
> +	. = ..()
```suggestion
```

2020-11-17 02:42 UTC, spookydonut commented on code/game/objects/items/bodybag.dm
> +/obj/structure/closet/bodybag/proc/acidspray_act()
```suggestion
/obj/structure/closet/bodybag/proc/acidspray_act()
	SIGNAL_HANDLER
```

2020-11-17 09:43 UTC, spookydonut commented on code/game/objects/items/bodybag.dm
> +			H.acid_spray_crossed(S.slow_amt) //tarp isn't acid proof; pass it on to the occupant
```suggestion
			INVOKE_ASYNC(H, /mob/living/carbon/human.proc/acid_spray_crossed, S.slow_amt) //tarp isn't acid proof; pass it on to the occupant
```

2020-11-17 11:15 UTC, spookydonut approved these changes

2020-11-20 23:39 UTC, merged

2020-11-23 14:06 UTC, MiniMeatwad commented
Add back the opening whenever a xenomorph steps over it. It's situational and requires you to place it somewhere xenomorphs wont walk over for a reason. After all it is invisibility with no drawbacks.