Seperates the surplus equipment vendor into a clothing/armor vendor
tgstation/TerraGov-Marine-Corps pull request #5153
Opened 2020-11-03 20:31 UTC by Pariah919

## About The Pull Request
semi temporary measure until someone does tabs, adds a clothing vendor to the game for more organized stuff and so it doesn't have literally 50 or so items.

## Why It's Good For The Game
so the surplus equipment vendor isn't horrifically bloated

## Changelog
:cl:
add: Added new clothing vendor
tweak:added clothing vendor and separated the surplus equipment vendor into a clothing/armor vendor.
/:cl:

2020-11-03 20:31 UTC, tgstation-server commented
You currently have a negative Fix/Feature pull request delta of -60. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

2020-11-05 20:05 UTC, TiviPlus commented on code/game/objects/machinery/vending/marine_vending.dm
> +	icon_state = "marineuniform"
armor_supply if its an armor vendor

2020-11-09 19:11 UTC, Pariah919 commented on code/game/objects/machinery/vending/marine_vending.dm
> +	icon_state = "marineuniform"
done

2020-11-12 16:31 UTC, TiviPlus commented on code/game/objects/machinery/vending/marine_vending.dm
> +
why

2020-11-12 16:31 UTC, TiviPlus commented on _maps/map_files/Theseus/TGS_Theseus.dmm
> +	},
bad varedit

2020-11-13 22:37 UTC, Hughgent commented on code/game/objects/machinery/vending/marine_vending.dm
>  		/obj/item/clothing/suit/modular = 20,
This is now in both vendors. please fix.

2020-11-14 19:48 UTC, Hughgent requested changes

2020-11-14 19:48 UTC, Hughgent commented on code/game/objects/machinery/vending/marine_vending.dm
> +		/obj/item/clothing/suit/storage/marine/harness = 50,
The harness, while yes not actually providing any armor whatsoever, fits into the 'armor' slot so to speak.

also, don't make it 50 of them. Keep it at 5.

2020-11-15 16:26 UTC, Hughgent approved these changes

2020-11-18 12:10 UTC, TiviPlus approved these changes
This can be straight merged it doesnt need tmc

2020-11-18 14:50 UTC, merged

2020-11-18 14:50 UTC, tgstation-server commented
Your Fix/Feature pull request delta is currently below zero (-69). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.