Minor refactor of acid spray crossed
tgstation/TerraGov-Marine-Corps pull request #5174
Opened 2020-11-05 13:01 UTC by spookydonut

## About The Pull Request
god this is still pretty bad but at least its not directly calling crossed()

2020-11-07 20:17 UTC, Hughgent requested changes

2020-11-07 20:17 UTC, Hughgent commented on code/game/objects/effects/aliens.dm
> +	var/datum/limb/affecting = get_limb("l_foot")
for these `get_limb()` please use the associated defines. `BODY_ZONE_PRECISE_L_FOOT` in this example

2020-11-07 20:18 UTC, Hughgent commented
Please also use the PR template

2020-11-08 07:37 UTC, spookydonut commented
> 
> 
> Please also use the PR template

Which part should I be using?

2020-11-08 14:36 UTC, Hughgent commented
Essentially all of it.

2020-11-08 15:17 UTC, Hughgent approved these changes

2020-11-08 17:04 UTC, TiviPlus approved these changes
Non player facing changes dont necessarily need a CL hugh

2020-11-10 05:53 UTC, spookydonut commented
@Hughgent just merge it, dont need TM

2020-11-10 20:44 UTC, merged