Adds new backpack sprites, replaces the old marine backpack sprites
tgstation/TerraGov-Marine-Corps pull request #5176
Opened 2020-11-05 17:26 UTC by Pariah919

## About The Pull Request
Replaces the old marine backpack sprites with new ones made by nixon.
![image](https://user-images.githubusercontent.com/46353991/98274840-c77e9480-1f48-11eb-858b-d670982b41eb.png)
Medic bag comes later.

## Why It's Good For The Game
the bags look better and are more in style.

## Changelog
:cl:
add: Added new backpack sprites
del: Removed old backpack sprites, git will remember them. Nobody else will.
/:cl:

2020-11-05 17:26 UTC, tgstation-server commented
You currently have a negative Fix/Feature pull request delta of -61. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

2020-11-05 18:30 UTC, Hughgent requested changes

2020-11-05 18:30 UTC, Hughgent commented on code/game/objects/items/storage/backpack.dm
> +	desc = "A heavy-duty satchel carried by some TGMC soldiers and support personnel. This one is in black."
The descriptions do not need color information, people will see that just by looking at the sprite.

2020-11-05 18:35 UTC, Hughgent approved these changes

2020-11-05 18:43 UTC, TiviPlus commented
Merge when the other sprites are done

2020-11-06 01:46 UTC, Pariah919 commented
@TiviPlus i've added them

2020-11-06 21:56 UTC, TiviPlus approved these changes

2020-11-06 23:26 UTC, merged

2020-11-06 23:26 UTC, tgstation-server commented
Your Fix/Feature pull request delta is currently below zero (-60). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.