Less Bright Lava
tgstation/TerraGov-Marine-Corps pull request #5193
Opened 2020-11-07 17:24 UTC by Hathkar

## About The Pull Request

Lowers the light_range and light_power of lava.

## Why It's Good For The Game
Lava provides less light, so xenos can stay near choke-points without being extremely obvious.

## Changelog
:cl:
balance: Lowered lava's brightness
/:cl:

2020-11-07 20:48 UTC, Hughgent requested changes
Get rid of the Changelog change

2020-11-07 21:13 UTC, Hathkar commented
Fixed.

2020-11-08 17:15 UTC, TiviPlus approved these changes

2020-11-10 23:41 UTC, Hughgent approved these changes

2020-11-10 23:41 UTC, merged