Sulaco Wire Fix
tgstation/TerraGov-Marine-Corps pull request #5202
Opened 2020-11-09 01:49 UTC by Hathkar

## About The Pull Request
Adds a missing wire to the Sulaco's top floor.

## Why It's Good For The Game

I missed one single wire.

## Changelog
:cl:
fix: Sulaco's powernet on the top floor had a missing wire fixed.
/:cl:

2020-11-10 23:54 UTC, Hughgent requested changes
I am told that these are 'dirty var edits' and need to be removed.

`icon_state` gets updated during `LateInitialize()` anyways.

2020-11-10 23:54 UTC, Hughgent commented on _maps/map_files/Sulaco/Sulaco.dmm
> +	icon_state = "ladderdown";
```suggestion
```

2020-11-11 15:40 UTC, Hathkar commented on _maps/map_files/Sulaco/Sulaco.dmm
> +	icon_state = "ladderdown";
Done

2020-11-13 19:40 UTC, jroinc commented
Does this still permakill people in medbay if cryo's used?

2020-11-13 19:44 UTC, Hathkar commented
> 
> 
> Does this still permakill people in medbay if cryo's used?

That's fixed.

2020-11-14 05:33 UTC, spookydonut approved these changes

2020-11-14 05:33 UTC, merged