Removes Hugger ardstun and replaces it with a new carrier ability
tgstation/TerraGov-Marine-Corps pull request #5226
Opened 2020-11-10 20:38 UTC by TiviPlus

## About The Pull Request

The hardstun just does a lot of stamina damage and a tiny aesthetic knockdown now

The new ability uses huggers to fling back marines from a carrier after a small channel by the carrier, and the range scales with the amount of huggers the carrier was storing at the time

## Why It's Good For The Game

Hardstuns are bad and New abilities is good

## Changelog
:cl:
balance: Removed hugger hardstun
add: Replaced the hugger stun with a new carrier ability powered by huggers: psychic wave
imageadd: New action sprite by Kuro
/:cl:

2020-11-11 00:27 UTC, Hughgent requested changes
alternative variable name `your_babies`

2020-11-11 00:27 UTC, Hughgent commented on code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
> +	var/huggers = length(X.huggers)
```suggestion
	var/total_huggers = length(X.huggers)
```

2020-11-11 00:27 UTC, Hughgent commented on code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
> +		for(var/i=1 to huggers)
```suggestion
		for(var/i=1 to total_huggers)
```

2020-11-11 08:34 UTC, Surrealaser commented
Narratively this is one weird ass ability.

So you charge the facehugger like a bomb of psychic energy? What?

2020-11-12 03:04 UTC, Isy232 commented
Find some way to fit this in maybe a little more.

Like you kill your own children to power your psychic energy?

Dafuq?

2020-11-12 16:28 UTC, TiviPlus commented
If you have better ideas for lore then suggest them but this works fine

2020-11-14 01:19 UTC, Hughgent commented on code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
> +		"<span class='xenowarning'>We contract our spines, crushing [huggers] little ones and releasing their psychic energy!</span>")
```suggestion
		"<span class='xenowarning'>We contract our spines, crushing [total_huggers] little ones and releasing their psychic energy!</span>")
```

2020-11-14 20:11 UTC, Hughgent approved these changes

2020-11-15 02:59 UTC, Surrealaser commented
@TiviPlus Honestly I would just get rid of the insta-hug on direct hits and replace them with a stamina loss + stagger and slow; maybe with knockback while on harm intent.

2020-11-27 01:42 UTC, Hughgent commented
image conflicts!

2020-12-06 15:51 UTC, closed without merging