Updates the database
tgstation/TerraGov-Marine-Corps pull request #5244
Opened 2020-11-13 22:21 UTC by TiviPlus

## About The Pull Request

About time

https://github.com/tgstation/tgstation/pull/51255 and followups
https://github.com/tgstation/tgstation/pull/50843

Also fixed Midround Stickyban queries apparently failing constantly

## Changelog
:cl:
fix: Midround Stickybans will now be applied correctly
refactor: The database now uses Rustg instead of BSQL, meaning the server will crash less
config: Added missing config entries to config, as well as an option for players with enough living time to bypass Bunkers
admin: Admins will now be alerted to new players connecting
admin: Improved database voting system
server: Updated SQL schema
/:cl:

2020-11-13 22:23 UTC, Hughgent commented
Save me @spookydonut!

2020-11-14 05:20 UTC, spookydonut commented
@Hughgent @TiviPlus well lets start with it not passing CI

2020-11-14 17:14 UTC, TiviPlus commented
CI fixed

2020-11-14 17:21 UTC, spookydonut submitted a review, later dismissed
whoever test merges this should be fired from keyholders no matter who they are.

2020-11-16 16:12 UTC, spookydonut commented
attn: @MrStonedOne

2020-11-16 20:21 UTC, optimumtact commented
Does pykyzz not have alter perms to the tgmc database?

2020-11-17 02:36 UTC, spookydonut commented
> 
> 
> Does pykyzz not have alter perms to the tgmc database?

Psy is on break and basically MIA @optimumtact

2020-11-22 12:05 UTC, TiviPlus commented
@optimumtact @MrStonedOne  still waiting

2020-11-22 20:57 UTC, optimumtact commented
I don't have the permissions necessary to apply procedures/triggers, until I have that I can't help you

2020-11-26 01:33 UTC, MrStonedOne requested changes
changes applied. please update the changelog to add the `;` so downstreams can just copy/paste the entire set of queries without errors.

2020-11-26 01:33 UTC, MrStonedOne commented on SQL/database_changelog.txt
> +	ADD COLUMN `last_matched` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER `first_matched`
```suggestion
	ADD COLUMN `last_matched` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER `first_matched`;
```

2020-11-26 11:20 UTC, TiviPlus commented
Woops meant to @spookydonut

2020-11-26 13:57 UTC, merged