Solid Hunter Ryu Taunt Added
tgstation/TerraGov-Marine-Corps pull request #5246
Opened 2020-11-14 04:43 UTC by Surrealaser

## About The Pull Request

Per the title.

## Why It's Good For The Game

Per the title.

## Changelog
:cl:
add: Added Solid Hunter Ryu taunt. Activate on the Hunter by inputting say "*solidhunter
refactor: Minor refactor for icon/visual SFX emote support
/:cl:

2020-11-14 04:50 UTC, Pariah919 commented
this should probably be locked behind fun allowed

2020-11-14 05:59 UTC, MiniMeatwad commented
Fun is always allowed, just ask the people over at the FoB having !Fun!

2020-11-15 11:27 UTC, TiviPlus requested changes

2020-11-15 11:27 UTC, TiviPlus commented on code/datums/emotes.dm
> +		new SFX(user) //put it at the user's location
use lowercase

2020-11-15 11:27 UTC, TiviPlus commented on code/datums/emotes.dm
> +		var/mob/living/L = user
no need for living casting

2020-11-15 11:27 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/update_icons.dm
> +	else if(stat == DEAD)
A) never do empty ifs
B) do this properly with signals instead of snowflake vars

2020-11-15 11:27 UTC, TiviPlus commented on code/modules/mob/living/living_defines.dm
> +	var/emoting = FALSE
Ditto on snowflake vars

2020-11-15 11:27 UTC, TiviPlus commented on code/datums/emotes.dm
> +	var/obj/effect/temp_visual/SFX = null //special/temp visual effects
lowercase

2020-11-15 11:27 UTC, TiviPlus commented on code/datums/emotes.dm
Document all this with autodoc

2020-11-15 11:27 UTC, TiviPlus commented on code/datums/emotes.dm
> +
Either make this a mob proc so the timers on the emoter or make this a QDELETED check

2020-11-15 11:27 UTC, TiviPlus commented
Also lock it behind fun config

2020-11-30 00:14 UTC, closed without merging