Adds new T3 Gourger
tgstation/TerraGov-Marine-Corps pull request #5271
Opened 2020-11-17 14:04 UTC by Walarks

## About The Pull Request

Adds new T3 Gourger

This xeno is supposed to achieve the niche of being a tank that can take marine fire for extended periods of time, while providing a lot of healing for other xenos and itself. To do so it needs to attack marines to gain and store blood, which forces it to expose itself to gain the full effect of its abilities.

I am also open to giving these skills in one form or another to other xenos, but I've personally not thought of any that they fit on. The sprite is placeholder if it ever gets to a testmerge state.

Stats:
Health - 600 - 800
Resistances - 5 - 20%
Speed - same as defiler
Plasma - 100 - 150
Slash Damage - 15 - 20

Abilities:
 - Blood Bank - stores up to 100 blood that is used to enable some of its abilities
 - Drain - 50 plasma, 15s CD - immobilise a marine for 2s and causes it to drop held items. After 2s deals 20 damage (not mitigated by armor) and gain 10 blood. If the channel is broken, the marine also gets freed earlier
 - Rejuvenate/Transfusion:
If cast on another xeno - 5 blood, 2s CD - restores 30% health
If cast on a dead human - no cost, 2s CD - restores health, plasma and sunder at a rate as if resting on weeds. If standing on weeds, this goes on top of the passive restoration benefits.
If cast on itself - 10 blood, 20s CD - over 5s restores 40% health and full plasma
 - Carnage - 100 plasma, 30s CD - attacking heals for damage dealt and gives 5 blood
 - Feast - available at 100 blood, 3m CD - drains 5 blood and restores 10% health per second. Carnage also heals all other xenos in 4 tiles for 70% of damage dealt

## Why It's Good For The Game

I think this xeno's playstyle as a tank that heals/makes tankier xenos around them in exchange of being in-combat isn't currently found among other xenos. Defender is the closest that I can think of, but to me it seems to be more of a T1 warrior with an extra quirk than a tank. Crusher is also tanky but the skills/stats don't fit with its current kit.

## Changelog
:cl:Slotbot
add: Adds new xeno caste
/:cl:

2020-11-17 17:34 UTC, SplinterGP commented
Carnage slash has 2 linter errors, check them at checks.

2020-11-18 11:03 UTC, Chaznoodles commented
Did you mean Gorger, or Gouger? This ain't it chief

2020-11-18 12:04 UTC, TiviPlus requested changes
Needs to either be rav additions or  get a better sprite that isn't a defiler recolor

2020-11-19 07:14 UTC, spookydonut commented
Will people stop trying to add new castes instead of replacing/improving existing castes?

2020-11-19 11:21 UTC, Walarks commented
> Will people stop trying to add new castes instead of replacing/improving existing castes?

I am ok with replacing Ravager with it as Ravager is a big Hunter with more damage/stuns and without stealth.

2020-11-19 12:35 UTC, Walarks commented
Drafting until sprite

2020-11-22 19:42 UTC, BeloneX commented
George.

2020-11-24 11:10 UTC, XSlayer300 commented on code/modules/mob/living/carbon/xenomorph/castes/gorger/abilities_gorger.dm
> +		to_chat(owner, "<span class='warning'>It is outside of our reach! We need to be</span>")
```suggestion
		to_chat(owner, "<span class='warning'>It is outside of our reach! We need to be closer!</span>")
```

2020-11-24 11:11 UTC, XSlayer300 commented on code/modules/mob/living/carbon/xenomorph/castes/gorger/abilities_gorger.dm
> +				to_chat(X, "<span class='notice'>Beyond our reach, we must be close and our way clear.</span>")
```suggestion
				to_chat(X, "<span class='notice'>It is beyond our reach, we must be close and our way clear.</span>")
```

2020-11-24 11:12 UTC, XSlayer300 commented on code/modules/mob/living/carbon/xenomorph/castes/gorger/castedatum_gorger.dm
> +	caste_desc = "A frightening looking, bulky xeno that drips with a familiar red fluid."
```suggestion
	caste_desc = "A frightening looking, bulky alien creature that drips with a familiar red fluid."
```

2020-11-24 11:12 UTC, XSlayer300 commented on code/modules/mob/living/carbon/xenomorph/castes/gorger/castedatum_gorger.dm
> +	caste_desc = "A frightening looking, bulky xeno that drips with a familiar red fluid. It looks a little more dangerous."
```suggestion
	caste_desc = "A frightening looking, bulky alien creature that drips with a familiar red fluid. It looks a little more dangerous."
```

2020-11-24 11:13 UTC, XSlayer300 commented on code/modules/mob/living/carbon/xenomorph/castes/gorger/castedatum_gorger.dm
> +	caste_desc = "A frightening looking, bulky xeno that drips with a familiar red fluid. It looks pretty strong."
```suggestion
	caste_desc = "A frightening looking, bulky alien creature that drips with a familiar red fluid. It looks pretty strong."
```

2020-12-18 00:16 UTC, closed without merging

2020-12-18 00:28 UTC, Walarks commented
reeeeeeeeeeeeeee

2021-02-01 03:41 UTC, Al-1ce commented
Thought this was pretty cool, Tivi was being a bit of a shitter about the sprite anyways.