Changes the pistol sprite of the 88mod/M1911 and replaces the M4A3
tgstation/TerraGov-Marine-Corps pull request #5295
Opened 2020-11-20 19:31 UTC by Pariah919

## About The Pull Request
Replaces the Pistol sprites of the m1911/88mod and replaces the m4a3 with a gun by bimmer, 88mod/m1911 by ocelot
Relores the Generic pistol belt a bit, it has the title of m4a3 now, and is no longer magically tgmc equipment.

## Why It's Good For The Game
Sprites that in the style are good. 
Consistency lorewise.

## Changelog
:cl:
add: Added new gun sprites, RT-3 by bimmer and VP70/M1911 by Ocelot/Przyjaciel
del: Removed old gun sprites, git will remember them, nobody else will. M4A3 pistol is gone
tweak: m276 belt made into m4a3 belt
/:cl:

2020-11-20 19:31 UTC, tgstation-server commented
You currently have a negative Fix/Feature pull request delta of -70. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

2020-11-21 01:41 UTC, Hughgent approved these changes

2020-11-22 00:04 UTC, TheBimmer231 requested changes
stock is poo, DM me.

2020-11-25 08:35 UTC, Pariah919 commented on code/modules/projectiles/guns/pistols.dm
>  	name = "\improper 88 Mod 4 combat pistol"
probably not but its just sprite pr for now

2020-11-26 01:33 UTC, merged

2020-11-26 01:33 UTC, tgstation-server commented
Your Fix/Feature pull request delta is currently below zero (-83). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.