Defender Tweaks: Crest Defense and Tail Sweep
tgstation/TerraGov-Marine-Corps pull request #5406
Opened 2020-12-01 09:37 UTC by Surrealaser

## About The Pull Request

1: Crest Defense now grants immunity to stagger, stun and slowdown from staggering munitions while active.

2: Tail Sweep now inflicts a small amount of soft CC and can affect enemy xenos.

## Why It's Good For The Game

Makes Crest Defense worthwhile, and compensates Tail Sweep for the removal of tackles which means the Stamina damage it inflicts has lost a great deal of value.

## Changelog
:cl:
balance: Crest Defense now provides immunity to the CC from staggering munitions while active.
balance: Tail Sweep imposes a small amount of slowdown and stagger stacks.
tweak: Tail Sweep now works on enemy xenos.
/:cl:

2020-12-01 17:07 UTC, SplinterGP commented
Crest defense is already worthwhile and gives 50% defense tp all of those, if you wanna be immune just like use fortify

2020-12-01 20:40 UTC, Surrealaser commented
@SplinterGP Everyone I've spoken to says Crest Defense is not worth the downsides and was happy with the idea of giving it immunity to staggering munitions; I don't think slowdown immunity alone is sufficient.

2020-12-05 19:46 UTC, Hughgent requested changes

2020-12-05 19:46 UTC, Hughgent commented on code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
> +				affecting = "chest" //Gotta have a torso?!
use the define for this limb zone please.

2020-12-23 00:22 UTC, closed without merging