new PPSh and mosin sprite, Paladin-12 widening because too small. waiting inhands.
tgstation/TerraGov-Marine-Corps pull request #5414
Opened 2020-12-02 22:26 UTC by SplinterGP

## About The Pull Request
gives PPSh and Mosin a new sprite, paladin-12 gets their sprite a bit bigger due to them being too small compared to all other guns.

also there's a small change to typepath, for organizing things, makes irremoveable a type of stock, instead of being a subtype of rifle stock.

![image](https://user-images.githubusercontent.com/29824735/100938750-082fe600-34d4-11eb-9ba1-94175e0d2e36.png)

## Why It's Good For The Game
good sprite

## Changelog
:cl:
imageadd: added new mosin, ppsh sprite and widened Paladin-12 sprite
/:cl:

2020-12-03 19:53 UTC, Smudged commented
When I was talking over on the discord, I just realised that the mosin you sprited looks alooot more like a M1 Garand

From my perspective it's because of the two black bands which makes it more like a garand than mosin, and the wood coloration too

2020-12-07 21:47 UTC, TheBimmer231 requested changes
shotgun needs to have more contrast, especially on the dark side, as for the PPSH, talk to me about the barrel.

2020-12-07 21:48 UTC, TheBimmer231 commented
Just realized the mosin is outrageously long too ⚡

2020-12-07 23:49 UTC, SplinterGP commented
> Just realized the mosin is outrageously long too ⚡

the mosin without being long would look quite odd, since it was also well, long before, and as it is a mosin, but i'll look.

2020-12-16 22:06 UTC, SplinterGP commented
![image](https://user-images.githubusercontent.com/29824735/102412095-c6259a80-3fd1-11eb-8f4c-9af09ed9bb92.png)
![image](https://user-images.githubusercontent.com/29824735/102412107-ca51b800-3fd1-11eb-8bdc-30d9f72d0b6b.png)

2020-12-19 22:29 UTC, Hughgent requested changes

2020-12-19 22:29 UTC, Hughgent commented on code/modules/projectiles/guns/smgs.dm
> +		/obj/item/attachable/attached_gun/flamer,
undocumented balance change. add to CL

2020-12-20 02:56 UTC, SplinterGP commented on code/modules/projectiles/guns/smgs.dm
> +		/obj/item/attachable/attached_gun/flamer,
oh sorry

2020-12-20 02:56 UTC, SplinterGP commented on code/modules/projectiles/guns/smgs.dm
> +		/obj/item/attachable/attached_gun/flamer,
i forgot that in

2020-12-23 16:17 UTC, spookydonut commented
Remove the balance changes and this can be merged

2020-12-24 03:38 UTC, TheBimmer231 requested changes
If you can't make the mosin shorter then remove it, otherwise I'm not approving this PR.

2020-12-26 11:24 UTC, SplinterGP commented
Alright, will shorten mosin stock.

2020-12-26 11:25 UTC, SplinterGP commented
> Remove the balance changes and this can be merged

Its done, the "balance" changes on mosin is just removing barrel and putting the stats from it on gun, since it used barrel for sprite

2020-12-28 03:09 UTC, Pariah919 commented
@SplinterGP remove the mosin barrel

2020-12-31 20:20 UTC, TiviPlus approved these changes

2021-01-08 14:48 UTC, SplinterGP commented
closing until i get able to deal with it.

2021-01-08 14:48 UTC, closed without merging