M-44 update
tgstation/TerraGov-Marine-Corps pull request #5418
Opened 2020-12-03 01:10 UTC by XSlayer300

## About The Pull Request
Because the M-44 deserves more love.

## Why It's Good For The Game

> *ocelot meme here*

## Changelog
:cl:
add: Added the M-44 to more maps.
add: Added gunslinger revolver speedloader for the M-44, which makes bullets ricochet to surfaces.
add: Added a unique gunsound to the M-44.
tweak: The M-44 is now chambered in special ricochet rounds, ammo available in certain maps.
/:cl:

2020-12-04 22:36 UTC, TiviPlus requested changes
Remove the ricochet bullets those shouldn't be in normal gameplay although it's ok in eord

2020-12-04 22:36 UTC, TiviPlus commented on code/modules/projectiles/guns/revolvers.dm
> +//TP-44 COMBAT REVOLVER, not based off on anything.
Unneeded comment change

2020-12-04 22:36 UTC, TiviPlus commented on code/modules/projectiles/guns/revolvers.dm
> +//MARSHALS REVOLVER, leftover from CM.
Can this be fully deleted if yes please do so

2020-12-05 03:48 UTC, XSlayer300 commented
What, the ricochet speedloaders? Also, I cannot change the specific ammo for the EORD weapon tiers.

> Remove the ricochet bullets those shouldn't be in normal gameplay although it's ok in eord

2020-12-06 15:37 UTC, TiviPlus commented
Either way ricochet bullets shouldnt be in normal gameplay this way

2020-12-14 13:40 UTC, XSlayer300 commented
HGECK, GIMME TIME TO DO IRL STUFF FIRST.

2020-12-23 19:30 UTC, SilencedMP5A5 commented
i don't get what's wrong with the bouncy boolets

2020-12-24 03:34 UTC, TheBimmer231 approved these changes

2020-12-27 22:45 UTC, TiviPlus commented
@XSlayer300 ?

2021-01-04 00:28 UTC, closed without merging