Fixes hijack bugs with giving xeno burrowed on hijacking to achieve xeno/marine ratio, also makes silos not break on launching hijacked ship.
tgstation/TerraGov-Marine-Corps pull request #5420
Opened 2020-12-03 03:49 UTC by SplinterGP

## About The Pull Request
It fixes a bug where xenos would not win burroweds to the xeno/marine ratio when hijacking the ship and launching to shipside, it would only happen when one xeno was left behind and the math for it was wrong.

Also makes silos at alamo not break on alamo launch.

## Why It's Good For The Game
fixes a bug, makes shipside fight a fair fight to xenos if they took too much casualties on ground.

## Changelog
:cl:
tweak: makes silos at dropship not break on hijacking dropship
fix: fixes a bug when xenos launching to shipside with hijacked dropship would not give xenos burrowed to the xeno/marine ratio if xenos had less than half marine numbers.
/:cl:

2020-12-03 08:27 UTC, TiviPlus requested changes

2020-12-03 08:27 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/hive_datum.dm
> +	for(var/obj/structure/resin/silo/i in GLOB.xeno_resin_silos)
as() and a better variable name please

2020-12-03 08:27 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/hive_datum.dm
> +			continue
Isshuttlearea maybe?

2020-12-03 18:14 UTC, SplinterGP commented on code/modules/mob/living/carbon/xenomorph/hive_datum.dm
> +	for(var/obj/structure/resin/silo/i in GLOB.xeno_resin_silos)
okay

2020-12-04 08:25 UTC, TiviPlus approved these changes

2020-12-04 08:25 UTC, merged