You cannot headbite someone without a head
tgstation/TerraGov-Marine-Corps pull request #5559
Opened 2020-12-24 21:14 UTC by Hughgent

## About The Pull Request

This one has either a 1 line fix, or a more involved variation. As it currently stands this is the more involved solution.

The 1 line fix is to just add `owner.headbitten = TRUE` to `dropLimb()` for non-synthetics.

The current fix is to remove the brain organ from the mob, and put it into the contents of the new head object. This is not strictly needed as it would only be used for a kind of disembodied head surgery it seems. A holdover from baystation I suspect.

I had considered an additional check in the headbite `can_use()` for head limb status, but I don't think the effort equals the reward in this situation (a slightly more appropriate `to_chat()`).

## Why It's Good For The Game

You cannot headbite someone without a head.
fixes #5301 

## Changelog
:cl: Hughgent
fix: You cannot headbite someone without a head.
/:cl:

2020-12-26 12:02 UTC, TiviPlus requested changes
Tested?

2020-12-26 12:02 UTC, TiviPlus commented on code/modules/organs/limbs.dm
> +				O = owner.internal_organs_by_name["brain"] //This removes (and later garbage collects) the organ. No brain means instant death.
cast as you assign

2020-12-26 20:09 UTC, Hughgent commented
Yeah it didn't work out. going with the 'simple' implementation.

2020-12-27 22:51 UTC, TiviPlus requested changes
The correct fix would be to have the brain correctly be removed and added when beheaded instead of faking the mob being headbit

2020-12-27 23:13 UTC, Hughgent commented
Effort isn't worth the reward in this case.

2020-12-27 23:13 UTC, closed without merging