Dreamchecker Spawn return fix
tgstation/TerraGov-Marine-Corps pull request #5565
Opened 2020-12-25 02:16 UTC by Hughgent

## About The Pull Request

Dreamchecker is complaining about these five things returning values because they are behind a `spawn()`

![image](https://user-images.githubusercontent.com/45076386/103114578-ca326780-4624-11eb-8c9f-d0e899f7a0d6.png)

## Why It's Good For The Game

No change to the overall game

## Changelog
:cl: Hughgent
code: removes the warnings of the codebase related to spawn()
/:cl:

2020-12-26 12:01 UTC, TiviPlus requested changes
Fix the spawn()'s instead please this is a bandaid

2020-12-30 13:10 UTC, TiviPlus commented on code/game/atoms_movable.dm
> +	step(src, turn(dir, 180))
Why not call step direct?

2020-12-30 13:10 UTC, TiviPlus commented on code/game/objects/effects/misc.dm
> +		addtimer(VARSET_CALLBACK(src, loc, null), 2 SECONDS)
Just delete this effect tbh is pretty shit and goes unused

2020-12-30 13:10 UTC, TiviPlus commented on code/game/objects/items/handcuffs.dm
> +	if(!C)	return
ahem

2020-12-30 13:10 UTC, TiviPlus commented on code/game/objects/items/handcuffs.dm
> +/obj/item/restraints/handcuffs/cyborg/proc/make_handcuffed(mob/living/carbon/C as mob, mob/user as mob, p_loc, p_loc_m)
Dont use the as mob things

2020-12-30 13:10 UTC, TiviPlus commented on code/modules/flufftext/Dreaming.dm
> +	return
4 things: 
forgot the / in front of mob
this for loop isnt defined right you should use our stand
Dreaming is a bool
This sleep causes hard deletes ping me if you want more explained, but it needs to  be another proc

2020-12-30 17:03 UTC, Hughgent commented on code/game/atoms_movable.dm
> +	step(src, turn(dir, 180))
to simulate the 'bounce' I presume.

2020-12-31 10:00 UTC, TiviPlus commented on code/game/atoms_movable.dm
> +	step(src, turn(dir, 180))
That's not how code works

2021-01-18 00:43 UTC, closed without merging