Computers Can Be Smashed So They Don't Block Movement
tgstation/TerraGov-Marine-Corps pull request #5572
Opened 2020-12-27 11:46 UTC by Surrealaser

## About The Pull Request

1. Xenos can disable computers by attacking them; 3 hits will disable a computer by default.

2. A disabled computer can't be used and doesn't obstruct pathing. It can be repaired with a welder after a 5 second delay.

3. Broken computers do not obstruct pathing.

## Why It's Good For The Game

Stops computers from being obnoxious, inexplicably indestructible road blocks for the xenos.

## Changelog
:cl:
tweak: Computers can now be disabled by multiple xeno attacks. Disabled computers do not obstruct pathing and can be repaired by a welder.
/:cl:

2020-12-27 14:18 UTC, TiviPlus commented
Balance change reopen after freeze

2021-01-02 12:05 UTC, TiviPlus requested changes

2021-01-02 12:05 UTC, TiviPlus commented on code/game/objects/machinery/computer/computer.dm
> +		if(user.skills.getRating("engineer") < SKILL_ENGINEER_MASTER)
welder act

2021-01-02 12:05 UTC, TiviPlus commented on code/game/objects/machinery/computer/computer.dm
> +			var/fumbling_time = 50 * ( SKILL_ENGINEER_MASTER - user.skills.getRating("engineer") )
copypaste

2021-01-02 12:05 UTC, TiviPlus commented on code/game/objects/machinery/computer/computer.dm
> +			return FALSE
why not use()

2021-01-02 12:05 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
> +		set_disabled()
Use OOP not istype(src) 
also this shouldve been iscomputer

2021-01-02 12:05 UTC, TiviPlus commented on code/game/objects/machinery/computer/computer.dm
> +	..()
. = ..()

2021-01-02 12:05 UTC, TiviPlus commented on code/game/objects/machinery/computer/computer.dm
> +	var/durability = 2 //How many times the computer can be smashed by a Xeno before it is disabled.
Autodoc

2021-01-03 11:38 UTC, TiviPlus commented on code/game/objects/machinery/computer/computer.dm
> +	if(machine_stat & (BROKEN))
remove the excess brackets on the flags

2021-01-03 11:38 UTC, TiviPlus commented on code/game/objects/machinery/computer/computer.dm
> +	if(!machine_stat & (DISABLED) && durability == initial(durability))
ditto

2021-01-03 11:38 UTC, TiviPlus commented on code/game/objects/machinery/computer/computer.dm
> +		var/fumbling_time = 50 * ( SKILL_ENGINEER_MASTER - user.skills.getRating("engineer") )
excess spaces

2021-01-03 11:38 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
> +
excess whitelines fnr

2021-01-04 18:07 UTC, TiviPlus requested changes
How does this affect game critical computers like nuke disks and intel computers

2021-01-04 18:07 UTC, TiviPlus commented on code/game/objects/machinery/computer/computer.dm
> +		var/fumbling_time = 50 * (SKILL_ENGINEER_MASTER - user.skills.getRating("engineer"))
```suggestion
		var/fumbling_time = 5 SECONDS * (SKILL_ENGINEER_MASTER - user.skills.getRating("engineer"))
```

2021-01-08 11:31 UTC, Surrealaser commented
> How does this affect game critical computers like nuke disks and intel computers

Anyone can repair them; if you don't have training it just takes a little more time.

2021-01-08 20:08 UTC, TiviPlus requested changes
Make them immune

2021-01-12 13:03 UTC, TiviPlus approved these changes

2021-01-12 13:03 UTC, merged

2021-01-12 13:03 UTC, tgstation-server commented
Your Fix/Feature pull request delta is currently below zero (-1). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.