Adds the spawn controller
tgstation/TerraGov-Marine-Corps pull request #5587
Opened 2020-12-28 10:28 UTC by TiviPlus

## About The Pull Request

SSspawning

## Why It's Good For The Game

Automated AI and mob spawning

## Changelog
:cl:
refactor: Adds the managed spawner controller
/:cl:

2020-12-30 21:49 UTC, Hughgent requested changes

2020-12-30 21:49 UTC, Hughgent commented on code/controllers/subsystem/spawning.dm
> +	var/datum/callback/post_spawn_cb
autodoc new vars

2020-12-30 22:31 UTC, TiviPlus commented on code/controllers/subsystem/spawning.dm
> +	var/datum/callback/post_spawn_cb
Holders dont need autodoc

2020-12-30 22:31 UTC, Hughgent commented on code/controllers/subsystem/spawning.dm
> +	var/datum/callback/post_spawn_cb
They do

2020-12-31 09:57 UTC, TiviPlus commented on code/controllers/subsystem/spawning.dm
> +	var/datum/callback/post_spawn_cb
No they don't

2021-01-12 13:44 UTC, TiviPlus commented on code/controllers/subsystem/spawning.dm
> +	var/datum/callback/post_spawn_cb
Done

2021-01-26 19:30 UTC, SplinterGP commented on code/modules/ai/spawners/xeno.dm
> +/obj/effect/ai_node/spawner/xeno/runnergang	// RUNNNER GANG RUNNER GANG
that's a rouny

2021-01-26 19:32 UTC, SplinterGP requested changes

2021-01-26 19:32 UTC, SplinterGP commented on code/modules/ai/spawners/xeno.dm
> +////////////////////Tier 4s
```suggestion
////////////////////Tier 3s
```

2021-01-26 19:45 UTC, SplinterGP commented
checks died with self commit, rip

2021-01-26 19:45 UTC, merged