Anti early fob camp
tgstation/TerraGov-Marine-Corps pull request #5628
Opened 2021-01-02 02:08 UTC by BraveMole

## About The Pull Request

You can now weed near LZ shutters even when they are close. You can't put any resin (wall etc), acid wells, jelly pod and such. Tunnel get a pass because why not. Everything that ressembles a fortification will still be banned near FOB before shutters open

## Why It's Good For The Game

Made fighting survivors or early tadpole a pain for no good reason. It still prevent any kind of stupid FOB maze at start, but you can heal near the fight with survs now. 

## Changelog
:cl:
tweak: allow weeding near shutters even before they are opened
/:cl:

2021-01-02 11:57 UTC, TiviPlus commented on code/game/turfs/turf.dm
> +/turf/proc/check_alien_construction(mob/living/builder, silent = FALSE, planned_building)
Autodoc

2021-01-02 14:47 UTC, BraveMole commented on code/game/turfs/turf.dm
> +/turf/proc/check_alien_construction(mob/living/builder, silent = FALSE, planned_building)
Done

2021-01-03 11:20 UTC, TiviPlus commented on code/game/turfs/turf.dm
> +//jelly pod dispensers and hugger traps
This isnt autodocced correctly

2021-01-03 11:20 UTC, TiviPlus commented on code/game/turfs/turf.dm
> +/turf/proc/check_alien_construction(mob/living/builder, silent = FALSE, planned_building)
this isnt sutodocced

2021-01-03 22:11 UTC, davidchan13 commented
This needs to be speed merged, theres no reason the xenos shouldn't be able to weed areas outside of shutters. Marines can still OB, Railgun and Mortar through shutters as is, this hugbox feature never should have been added.

2021-01-04 16:54 UTC, TiviPlus commented on code/game/turfs/turf.dm
> +
```suggestion
 * Proced when constructing every kind of xenos structure, including weeds*/
 */
```

2021-01-04 16:56 UTC, TiviPlus commented on code/game/turfs/turf.dm
> + */
```suggestion
 * Checks for whether we can build advanced xeno structures here
 * Returns TRUE if present, FALSE otherwise
 */
```

2021-01-04 16:58 UTC, TiviPlus commented on code/game/turfs/turf.dm
> + */
```suggestion
 * Return TRUE if allowed, FALSE otherwise
 */
```

2021-01-04 17:25 UTC, TiviPlus requested changes

2021-01-04 17:25 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
> +		return FALSE
Move to can_use_action

2021-01-04 17:37 UTC, TiviPlus approved these changes

2021-01-04 17:37 UTC, merged