Buffs throwing knifes
tgstation/TerraGov-Marine-Corps pull request #5634
Opened 2021-01-02 18:58 UTC by BeloneX

## About The Pull Request

Buffs throwing knifes to deal 100 damage when thrown.

## Why It's Good For The Game

Throwing knifes are the epidemy of useless, it's already hard enough to even hit a hostile target with them, and then it deals barely any damage.

I don't think that 100 damage is overpowered as Xenos move at incredible speeds so you need to have really good reflexes to get a hit off.

## Changelog
:cl:
balance: throwing knifes now deal 100 damage when thrown.
/:cl:

2021-01-02 18:58 UTC, tgstation-server commented
You currently have a negative Fix/Feature pull request delta of -2. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

2021-01-02 19:00 UTC, Jeff-jefferson-jeffery commented
haha doesnt this mean shrike can oneshot people by flinging knives?

2021-01-02 19:28 UTC, davidchan13 commented
This really only buffs FF and EORG. Lets do it.

2021-01-02 19:57 UTC, Pariah919 commented
No.
Remove macros first.

2021-01-02 20:04 UTC, BeloneX commented
> No.
> Remove macros first.

Macros for what?

2021-01-02 21:12 UTC, MLGTASTICa commented
ah yes , knifes that can take out a xeno in 3 hits. balanced.

2021-01-02 22:29 UTC, Chaznoodles commented
No.

2021-01-03 02:38 UTC, neohenry commented
Marines will definitely start doing throwing knife build with a buff, though 100 damage can kill an Ancient Empress with at least 8 knives given. If it was around 75, then it would be okay.

If we punch out the math on how much knives can KO xenos, then we can better gauge the balance for knives. Otherwise, we're just pop shotting.

2021-01-03 04:58 UTC, RenGusta commented
Doing some comparative testing on xenos would help in making your case for this being justified.

2021-01-03 11:25 UTC, TiviPlus requested changes
Unless you remove macros this is a big no

2021-01-03 11:33 UTC, closed without merging

2021-01-03 13:46 UTC, BeloneX commented
> Unless you remove macros this is a big no

I still wasn't told which macros..