Lava Outpost Upgrade/Overhaul
tgstation/TerraGov-Marine-Corps pull request #5641
Opened 2021-01-03 17:09 UTC by mrhugo13

## About The Pull Request
Pretty much just overhauls a bunch of lavaland, adding 6 new locations and moving around a few things.
Adds area sprites and code for said new 6 locations.
compare & contrast differences with the [webmap](https://affectedarc07.github.io/SS13WebMap/TGMC/LavaOutpost/)

## Why It's Good For The Game
Lava outpost has been going out of style due to both having not been getting anything new or interesting to it & being way too large.

The genuine size of it and the amount of tunnels that doesn't **really** lead to anywhere hits new players with a shovel and discourages people from properly learning the map, especially if they are not aware of the webmap feature, also leads to it taking forever to get anywhere of note which makes it generally less fun to play.

This PR should hopefully inject lava outpost with a newer look on things and should help with both shrinking it, getting rid of the unnecessary tunnels and length to make it more enjoyable, aswell as the new locations hopefully making it more dense with interesting locations rather than having the interesting locations be a billion miles away from eachother.

## Changelog
:cl: Vondiech
add: Multiple new locations added to lava outpost
tweak: Multiple things have been moved around and/or adjusted
/:cl:

2021-01-04 09:48 UTC, mrhugo13 commented
Added some additional flavour with remains & mining equipment here and there as-per jerry suggested, also fixed an `outside = FALSE` variable that i missed yesterday.

2021-01-04 16:53 UTC, TiviPlus requested changes
Screenshot of area mapping please

2021-01-05 12:42 UTC, TiviPlus approved these changes

2021-01-05 12:42 UTC, merged

2021-01-05 12:42 UTC, tgstation-server commented
Your Fix/Feature pull request delta is currently below zero (-5). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.