Tick allocation refactor
tgstation/TerraGov-Marine-Corps pull request #5663
Opened 2021-01-05 11:37 UTC by TiviPlus

TG pr is technically but this was previously broken so I need a round of testing before I PR it to TG

2021-01-12 13:16 UTC, TiviPlus commented
Merged upstream

2021-01-21 21:58 UTC, MrStonedOne requested changes
we duplicated a little bit of work: #5787

2021-01-21 21:58 UTC, MrStonedOne commented on code/__DEFINES/_tick.dm
> +#define MAPTICK_MC_MIN_RESERVE 60
try this at something much much lower like 40. tgmc doesn't need the mc to do as much.

2021-01-21 21:58 UTC, MrStonedOne commented on code/__DEFINES/_tick.dm
> +#define TICK_LIMIT_RUNNING_BACKGROUND (100 - TICK_BYOND_RESERVE - MAPTICK_LAST_INTERNAL_TICK_USAGE)
Kill this, it broke things at /tg/ as these things will basically never run above 20 pop.

2021-01-21 21:58 UTC, MrStonedOne commented on code/controllers/master.dm
> +		tick_remaining = ((bg_calc) ? (TICK_LIMIT_RUNNING_BACKGROUND) : (TICK_LIMIT_RUNNING)) - TICK_USAGE
kill the background stuff here. Im pretty sure this is why things broke at /tg/.

2021-01-26 20:25 UTC, TiviPlus commented
Closing in favor of 5787 
because I dont have time to finish this

2021-01-26 20:25 UTC, closed without merging