HvH armor and vendors
tgstation/TerraGov-Marine-Corps pull request #5671
Opened 2021-01-06 03:11 UTC by XSlayer300

## About The Pull Request
Does the following:

- This PR replaces all mentions of M3 armor with PAS. M3 is a CM leftover.
- This PR adds armor variants for all **hostile** ERT for HvH rounds and their job types with it. The values are based on medium armor, medium armor with Tyr 2 and heavy armor with Tyr 2 as they lack req and all of the good stuff they have.
- This PR adds HvH variants for all marine vendors, containing less scoped weapons, shotguns and MGs
- This PR buffs some armors available to PAS level.
 

## Why It's Good For The Game
Because no one wants to take time to make vendors meant for HvH so we already have vendors to quickly make some, not to mention the inferior armor of all hostile ERTs as they have no req.

## Changelog
:cl:
add: Added HvH variants for hostile ERT armor and marine vendors, admin-spawnable only.
tweak: Renamed most M3 armor to PAS.
tweak: Removed the suppressor in NEXUS closets, you can still get them via attachment vendor.
balance: Buffs some armor to PAS-level.
/:cl:

2021-01-06 11:26 UTC, TiviPlus approved these changes

2021-01-06 11:26 UTC, TiviPlus commented on code/game/objects/machinery/vending/marine_vending.dm
> +// want to get shotguns, scoped weapons and MGs? go to the cargo vendor instead.
You can use the autdoc for these

2021-01-06 11:26 UTC, TiviPlus commented on code/game/objects/machinery/vending/marine_vending.dm
> +// HvH version of the vending machine, containing no ammo for spec weapons and restricted ones
ditto
```suggestion
/// HvH version of the vending machine, containing no ammo for spec weapons and restricted ones
```

2021-01-06 11:26 UTC, TiviPlus commented on code/game/objects/machinery/vending/marine_vending.dm
> +//The only way to get LMG, DMR, shotguns and GPMG
Ditto

2021-01-06 11:26 UTC, TiviPlus commented on code/modules/clothing/suits/marine_armor.dm
> +/obj/item/clothing/suit/storage/faction/UPP/hvh
```suggestion
/// Modified version of the armor for HvH combat. Stats are based on medium armor, with tyr mark 2.
/obj/item/clothing/suit/storage/faction/UPP/hvh
```

2021-01-06 11:26 UTC, TiviPlus commented on code/modules/clothing/suits/marine_armor.dm
> +/obj/item/clothing/suit/storage/faction/UPP/commando/hvh
```suggestion
/// Modified version of the armor for HvH combat. Stats are based on medium armor, with tyr mark 2.
/obj/item/clothing/suit/storage/faction/UPP/commando/hvh
```

2021-01-06 11:26 UTC, TiviPlus commented on code/modules/clothing/suits/marine_armor.dm
> +/obj/item/clothing/suit/storage/faction/UPP/heavy/hvh
```suggestion
/// Modified version of the armor for HvH combat. Stats are based on heavy armor, with tyr mark 2.
/obj/item/clothing/suit/storage/faction/UPP/heavy/hvh
```

2021-01-06 11:26 UTC, TiviPlus commented on code/modules/clothing/suits/marine_armor.dm
> +/obj/item/clothing/suit/storage/marine/smartgunner/UPP/hvh
```suggestion
/// Modified version of the armor for HvH combat. Stats are based on heavy armor, with tyr mark 2.
/obj/item/clothing/suit/storage/marine/smartgunner/UPP/hvh
```

2021-01-06 11:26 UTC, TiviPlus commented on code/modules/clothing/suits/marine_armor.dm
> +/obj/item/clothing/suit/storage/marine/som/hvh
```suggestion
/// Modified version of the armor for HvH combat. Stats are on medium armor.
/obj/item/clothing/suit/storage/marine/som/hvh
```

2021-01-06 11:26 UTC, TiviPlus commented on code/modules/clothing/suits/marine_armor.dm
> +/obj/item/clothing/suit/storage/marine/som/leader/hvh
```suggestion
/// Modified version of the armor for HvH combat. Stats are based on medium armor with mark 2 tyr.
/obj/item/clothing/suit/storage/marine/som/leader/hvh
```

2021-01-06 11:38 UTC, XSlayer300 commented on code/game/objects/machinery/vending/marine_vending.dm
> +// want to get shotguns, scoped weapons and MGs? go to the cargo vendor instead.
done.

2021-01-06 11:38 UTC, XSlayer300 commented on code/game/objects/machinery/vending/marine_vending.dm
> +//The only way to get LMG, DMR, shotguns and GPMG
and ditto.

2021-01-08 19:56 UTC, TiviPlus requested changes

2021-01-08 19:56 UTC, TiviPlus commented on code/game/objects/machinery/floodlight.dm
> +	set_light(100)
Remove this

2021-01-10 09:33 UTC, XSlayer300 commented on code/game/objects/machinery/floodlight.dm
> +	set_light(100)
done

2021-01-10 21:51 UTC, TiviPlus approved these changes

2021-01-10 21:53 UTC, merged

2021-01-10 21:53 UTC, tgstation-server commented
Your Fix/Feature pull request delta is currently below zero (-8). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.