Refactors foam code with some of TG foam code
tgstation/TerraGov-Marine-Corps pull request #5680
Opened 2021-01-07 01:00 UTC by SplinterGP

## About The Pull Request
Refactors foam code, also making them apply reagents to mob even if metal foam.
also gets rid of stinky spawn()

## Why It's Good For The Game
Refactor good

## Changelog
:cl:
refactor: refactors foam code.
/:cl:

2021-01-07 21:00 UTC, TiviPlus commented
Didnt even compile 💢

2021-01-07 21:47 UTC, SplinterGP commented
> Didnt even compile 💢

i know right i forgot something

2021-01-10 22:01 UTC, TiviPlus commented on code/game/objects/effects/effect_system/foam.dm
> +	var/fraction = 1/initial(reagent_divisor)
why all these initials on reagent division

2021-01-10 23:00 UTC, TiviPlus requested changes
.

2021-01-13 19:20 UTC, SplinterGP commented on code/game/objects/effects/effect_system/foam.dm
> +	for(var/obj/O in range(0, src))
TG uses this, might replace it for something else.

2021-01-15 19:52 UTC, TiviPlus requested changes

2021-01-15 19:52 UTC, TiviPlus commented on code/game/objects/effects/effect_system/foam.dm
> +	for(var/obj/O in range(0, src))
Yea its awful replace it

2021-01-15 19:52 UTC, TiviPlus commented on code/game/objects/effects/effect_system/foam.dm
> +	for(var/mob/living/L in range(0, src))
same

2021-01-15 19:52 UTC, TiviPlus commented on code/game/objects/effects/effect_system/foam.dm
> +	var/fraction = 1/initial(reagent_divisor)
standing

2021-01-15 19:52 UTC, TiviPlus commented on code/game/objects/effects/effect_system/foam.dm
> +		var/obj/effect/particle_effect/foam/F = new src.type(T)
still standing, remove the src from src.type

2021-01-15 19:52 UTC, TiviPlus commented on code/game/objects/effects/effect_system/foam.dm
> +	chemholder = new /obj()
whyyyyyyyyyyyyyyyyyyyyyy

2021-02-06 02:31 UTC, SplinterGP commented
can do tomorrow

2021-02-22 00:14 UTC, closed without merging