C4 explosion sound
tgstation/TerraGov-Marine-Corps pull request #5690
Opened 2021-01-08 12:17 UTC by EvilMelonTheSecond

## About The Pull Request
Copypasted detpack explosion ring sound and added small explosion area to C4. Hopefully the correct way.

## Why It's Good For The Game
C4 is no longer a magic wall delete for the added I M M E R S I O N

## Changelog
:cl:
tweak: C4 now does small explosion and plays detpack ringing when detonation time is up
/:cl:

2021-01-08 18:35 UTC, TiviPlus requested changes
Please do not webedit in future

2021-01-08 18:35 UTC, TiviPlus commented on code/game/objects/items/explosives/plastique.dm
> +		explosion(plant_target, 0, 0, 0, 1)
```suggestion
		playsound(loc, 'sound/weapons/ring.ogg', 200, FALSE)
		explosion(plant_target, 0, 0, 0, 1)
```
```suggestion
		playsound(src.loc, 'sound/weapons/ring.ogg', 200, FALSE)
		explosion(plant_target, 0, 0, 0, 1)
```

2021-01-08 19:11 UTC, TiviPlus approved these changes

2021-01-10 06:30 UTC, neohenry commented
Man, I like it when C4 just yeet a wall and doesn't hurt marines.

2021-01-10 21:37 UTC, merged