Makes fire rate during autofire update, removes busy check for firing a gun
tgstation/TerraGov-Marine-Corps pull request #5692
Opened 2021-01-08 15:47 UTC by Walarks

## About The Pull Request
Makes fire rate during autofire update if the fire rate of the gun changes.

## Why It's Good For The Game
fix

## Changelog
:cl:
tweak: makes fire rate update while autofiring
balance: removes busy check for firing, making firing while wielding available again
/:cl:

2021-01-08 15:47 UTC, tgstation-server commented
You currently have a negative Fix/Feature pull request delta of -16. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

2021-01-08 16:54 UTC, BraveMole commented
>balance: removes busy check for firing, making firing while wielding available again

but why? Is there a accuracy malus at least

2021-01-08 19:34 UTC, TiviPlus requested changes
This should be on a autofire subsystem, instead of abusing the timer subsystem further

2021-01-15 20:35 UTC, SplinterGP commented
> > balance: removes busy check for firing, making firing while wielding available again
> 
> but why? Is there a accuracy malus at least

its how it used to be, and yes, mid wielding time you have unwielded stats, so while wielding youre basically not wielded yet.

2021-02-04 15:55 UTC, TiviPlus commented
stale,closing

2021-02-04 15:55 UTC, closed without merging