KBs for Healing Infusion + Rally Hive. Healing Infusion code improvement
tgstation/TerraGov-Marine-Corps pull request #5701
Opened 2021-01-10 14:18 UTC by Surrealaser

## About The Pull Request

1. Adds hotkey for Healing Infusion and Hive Rally

2. Improves code for Healing Infusion; hopefully stops inconsistent buff SFX behaviour reported by some.

## Why It's Good For The Game

Bugfixes.

Adds hot keys.

## Changelog
:cl:
add: Hotkeys added for Rally Hive and Healing Infusion.
fix: Possible fix for Healing Infusion SFX inconsistency.
code: Code improvement for Healing Infusion.
/:cl:

2021-01-10 22:04 UTC, TiviPlus requested changes

2021-01-10 22:04 UTC, TiviPlus commented on code/datums/keybinding/xeno.dm
> +	description = "Heals a target xeno restoring sunder and health once per life tick for up to 5 ticks. 60 second duration."
a player will not know what a life tick is

2021-01-10 22:04 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
> +	var/infusion_active = FALSE //Flags whether the infusion is active or not
Autodoc & this is a bool not a flag

2021-01-10 22:04 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
> +	infusion_active = TRUE //Flag the infusion as being active
bool

2021-01-12 13:25 UTC, TiviPlus approved these changes

2021-01-12 13:25 UTC, merged

2021-01-12 13:26 UTC, tgstation-server commented
Your Fix/Feature pull request delta is currently below zero (-11). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.