right click menu has been disabled, right click has been freed
tgstation/TerraGov-Marine-Corps pull request #5710
Opened 2021-01-11 12:17 UTC by Pariah919

## About The Pull Request
Ports this from is12, thanks matt. All credit to him.

Admins still have the ability to setup the pop up menu.

Safety is now right click for guns as a proof of concept

## Why It's Good For The Game
GIves us way more control over our controls. And allows for more use of the mouse rather than having an antiquated shhitty right click menu

## Changelog
:cl:
del: Removed right click menu. Right click is a free man again.
tweak: moved safety from alt click to right click
/:cl:

2021-01-11 12:17 UTC, tgstation-server commented
You currently have a negative Fix/Feature pull request delta of -145. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

2021-01-11 12:39 UTC, BeloneX commented
What the fuck, why?

2021-01-11 12:44 UTC, Chaznoodles commented
> What the fuck, why?
> 
> Nevermind the countless things that require the right click for various functionalities, this is straight-up cursed.

You can alt-click rather than right-click to view stacks and pick things up, it also tends to be less laggy on the client. That's pretty much all right-click is used for.

2021-01-11 12:45 UTC, BeloneX commented
> > What the fuck, why?
> > Nevermind the countless things that require the right click for various functionalities, this is straight-up cursed.
> 
> You can alt-click rather than right-click to view stacks and pick things up, it also tends to be less laggy on the client. That's pretty much all right-click is used for.

Countless things require the right-click menu to toggle specific settings or functionalities.

2021-01-11 12:50 UTC, Pariah919 commented
>What the fuck, why?

>Nevermind the countless things that require the right click for various functionalities, this is straight-up cursed.

Move them to alt right click, right click, alt right click.. etc.. 
Right click menu is a curse on ss13, removing it gives us vastly more control  over the controls

2021-01-11 12:52 UTC, BeloneX commented
Just saw this is a preference, nevermind then.

You should make it be right-clicked by default or else this weird out a lot of people like when Xeno abilities were set to be shift-click by default.

2021-01-11 12:56 UTC, BeloneX reviewed
Misleading changelog, mention that it's a preference you can toggle instead.

2021-01-11 15:59 UTC, Pariah919 commented
>You should make it be right-clicked by default or else this weird out a lot of people like when Xeno abilities were set to be shift-click by default.

right click not being tied to the menu should become the default, and the right click menu should be an exception

2021-01-11 16:15 UTC, Tennessee116 commented
> Move them to alt right click, right click, alt right click.. etc..

If you aren't going to do that, don't merge this.

2021-01-11 19:09 UTC, davidchan13 commented
Right click works from more than 1 tile away. Alt Clicking requires you to be next to the tile to it.

This makes checking for hugger holes, stealthing/hiding xenos and larva, mines, obscured acid wells and any number of things you'd want to do safely at a distance assanine to outright impossible.

2021-01-11 21:41 UTC, SplinterGP commented
> You can alt-click rather than right-click to view stacks and pick things up, it also tends to be less laggy on the client. That's pretty much all right-click is used for.

that's actually not true, you cant use alt-click on distance and alt-click is way slower than right clicking as right click is just a windows thingy and the alt click window is slow as it doenst has an HTML stat-panel, making it way more laggy than right clicking, also right click has "move-to-top" which makes the item be on the top of the piles, nothing much  but helps on organization.

2021-01-12 13:56 UTC, TiviPlus commented
@BeloneX Do not misuse the review feature

2021-01-12 14:07 UTC, TiviPlus requested changes

2021-01-12 14:07 UTC, TiviPlus commented on code/_onclick/click.dm
> +		return
```suggestion
	if(modifiers["shift"] && modifiers["right"])
		ShiftRightClickOn(A)
		return
	if(modifiers["alt"] && modifiers["right"])
		return
	if(modifiers["right"] && RightClickOn(A))
		return
```

2021-01-12 14:07 UTC, TiviPlus commented on code/modules/client/preferences_toggles.dm
> +		to_chat(src, "<span class='interface'>Right click disabled.</span>")
```suggestion
	show_popup_menus = !show_popup_menus
	to_chat(src, "<span class='interface'>Right click [show_popup_menus ? "en" : "dis"]abled.</span>")
```

2021-01-12 14:07 UTC, TiviPlus commented on code/_onclick/click.dm
> +/atom/proc/RightClick(mob/user)
```suggestion

///Called when a owner mob Rightmouseclicks an atom
/mob/proc/RightClickOn(atom/A)
	A.RightClick(src)

///Called when a owner mob Shift + Rightmouseclicks an atom
/mob/proc/ShiftRightClickOn(atom/A)
	A.ShiftRightClick(src)

///Called when a owner mob Alt + Rightmouseclicks an atom, given that Altclick does not return TRUE
/mob/proc/AltRightClickOn(atom/A)
	A.AltRightClick(src)

///Called when a mob Rightmouseclicks this atom
/atom/proc/RightClick(mob/user)
	return

///Called when a mob Shift + Rightmouseclicks this atom
/atom/proc/ShiftRightClick(mob/user)
	return
	
///Called when a mob Alt + Rightmouseclicks this atom, given that mobs Altclick() does not return TRUE
/atom/proc/AltRightClick(mob/user)
```

2021-01-12 14:07 UTC, TiviPlus commented on code/modules/client/preferences_toggles.dm
> +client/verb/toggle_right_click()
```suggestion

///Toggles the right click menu on and off
/client/verb/toggle_right_click()
```

2021-01-13 15:43 UTC, BraveMole commented
I suppose that loading sprites into the alt click menu is making things laggy, maybe make it a preference so that people having issue with that menu can use it more

2021-01-14 10:54 UTC, SpaceLoveSs13 commented
Will Alt-click let us use the "Change pinpointer" on Advanced pinpointers to direct user to a Nuclear Fission Device or on going disk generator? Also right click change to tac binos [I know shift-click exists for tacbino modes, but right click shows new people the way to do it at first]

2021-01-15 04:00 UTC, fernandos13 commented
make it preference
and make so people can CHOOSE whatever they bind to it. safety for me is almost useless tbh. but have it set to pick up health analyzer macro might be kinda better than examine tiles....

2021-01-15 19:54 UTC, TiviPlus approved these changes

2021-01-15 19:55 UTC, TiviPlus commented
Im gonna hold off on merging this till either myself or someone else is available to make more rightclick functions

2021-01-15 20:50 UTC, SplinterGP approved these changes
fine for me, should keep a way to use right click with it off, be it ctrl right click or something, some stuff only has verbs which can be either used on top right tabs or shows on right click.

2021-01-28 18:39 UTC, Pariah919 commented
point to bothering

2021-01-28 19:30 UTC, Pariah919 commented
there's nothing of value left here

2021-01-28 19:35 UTC, Pariah919 commented
i might as well leave this here in hindsight rather than delete it

2021-02-04 16:37 UTC, merged

2021-02-04 16:37 UTC, tgstation-server commented
Your Fix/Feature pull request delta is currently below zero (-257). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.