Fixes Hot drink machine beeps, “Hot drink machine beeps"
tgstation/TerraGov-Marine-Corps pull request #5718
Opened 2021-01-12 15:51 UTC by Chaznoodles

## About The Pull Request

Probably fixes the issue where vending machine say their say, as a result of my previous fix which probably fixed vending machines being understandable by xenos.

## Why It's Good For The Game

Hot drink machine beeps, “Hot drink machine beeps, "please fix me properly this time”

## Changelog
:cl:
fix: Vending machines will no longer make a mockery of their own kind.
/:cl:

2021-01-12 15:53 UTC, Chaznoodles commented
![image](https://user-images.githubusercontent.com/44979174/104338314-49151480-54ee-11eb-9bd7-55ca20fe450e.png)

Real neat, bot

2021-01-15 19:33 UTC, TiviPlus requested changes

2021-01-15 19:33 UTC, TiviPlus commented on code/game/objects/machinery/vending/vending.dm
> +	say("[message]")
```suggestion
	say(message)
```

2021-01-20 09:51 UTC, Chaznoodles commented
Closing, no desire to contribute due to repeated instances of behaviour like below.

![image](https://user-images.githubusercontent.com/44979174/105157668-1e861580-5b05-11eb-90be-624505ab9bbb.png)

2021-01-20 09:51 UTC, closed without merging