Should Fix Healing Infusion Aura Issues For Good
tgstation/TerraGov-Marine-Corps pull request #5750
Opened 2021-01-16 12:44 UTC by Surrealaser

## About The Pull Request

Should completely fix the lingering Healing Infusion Aura bug.

## Why It's Good For The Game

Fixes a bug.

## Changelog
:cl:
fix: Fixes lingering bugs with the Healing Infusion aura visuals.
/:cl:

2021-01-20 19:13 UTC, TiviPlus requested changes

2021-01-20 19:13 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
>  		return FALSE
Unnessesary change

2021-01-20 19:13 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
ditto

2021-01-24 18:43 UTC, SplinterGP approved these changes

2021-01-24 18:44 UTC, merged