Improves the readability of xenoupgrade.dm
tgstation/TerraGov-Marine-Corps pull request #5760
Opened 2021-01-17 11:46 UTC by BeloneX

## Changelog
:cl:
refactor: refactored xenoupgrade.dm to massively improve readability
/:cl:

2021-01-20 19:27 UTC, TiviPlus requested changes

2021-01-20 19:27 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
> +
```suggestion

```

2021-01-20 19:27 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
> +//================//
Missing newline between defenition and the comment, present in several places

2021-01-20 19:27 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
> +//----HIVELORD----//
CARRIER END
HIVELORD START 

Would be more readable, not just here but everywhere else

2021-01-21 21:35 UTC, SplinterGP approved these changes

2021-01-22 20:33 UTC, SplinterGP approved these changes

2021-01-22 20:36 UTC, merged