Alamo reset hijack fix
tgstation/TerraGov-Marine-Corps pull request #5776
Opened 2021-01-20 12:32 UTC by BraveMole

## About The Pull Request

Alamo could stay on hijack state for ever, while it should give control back to marine if the xenos are not crashing the ship for 10 minutes

## Why It's Good For The Game

## Changelog
:cl:
fix: Hijack state correctly resets
/:cl:

2021-01-20 20:10 UTC, TiviPlus requested changes

2021-01-20 20:10 UTC, TiviPlus commented on code/modules/shuttle/marine_dropship.dm
> +		//return FALSE
....

2021-01-20 20:10 UTC, TiviPlus commented on code/modules/shuttle/marine_dropship.dm
> +		//return
....

2021-01-20 21:25 UTC, BraveMole commented on code/modules/shuttle/marine_dropship.dm
> +		//return FALSE
oups, forgot to remove my test

2021-01-24 22:30 UTC, SplinterGP approved these changes

2021-01-24 22:31 UTC, merged