Balance for small arms
tgstation/TerraGov-Marine-Corps pull request #5825
Opened 2021-01-27 17:17 UTC by fernandos13

## About The Pull Request
this balances the small arms
smgs
machinepistols
pistols
revolvers

in many different and small improvements "revolver received a nerf to ROF and a BUFF to dmg" most of pitols got some level of buff tho not all T90 got a nerf per say. its relative in most cases come and see the code closer"

## Why It's Good For The Game
will finally set a standard for small arms. tunning them around the overall balance.

makes most pistols comparable to one another, reduces the revolver from an unintended state to one comparable to the intended state, rebalances T90 and T19 to be closer to one another so it's less one being objectively worse, and more user preference
etc

buffs (TP-14,RT-3,TP-23,M1911,M9,TP-17,Highpower automag,88 Mod 4) to perform better one handed
also tweaks the TP-44,T-19,T-90
TP 44 gets more of a hard hitting slow ROF as its indented for a revover
T-19 now gets a small tweak to perform well one handed but being subpar overall than 2 handed guns
T-90 gets a tweak to nerf the last OP status of it. while making it viable as a SMG. that CAN although not recommended to be one handed

## Changelog
:cl:
balance: **TP-14** bigger magazine less recoil n scatter
balance: **RT-3**  less scatter
balance: **TP-23** bigger magazine, higher RoF,  lower recoil
balance: **M1911** higher RoF,  lower recoil
balance: **Beretta 93R** less scatter
balance: **GOLDEN deagle** no scatter wielded
balance: **M9** less recoil and scatter one handed
balance: **TP-17** _50%_ more damage; _50%_ more damage falloff
balance: **Highpower automag** more stable one handed. and definetly stable two handed;
balance: **88 Mod 4** lower fire delay, burst mode delay now set, better one handed;
balance: **TP-44** now it is slower and damage increase of _25%_
balance: **T-19** buff its one handed abilities and brings it up to be on pair and a middle of pistol smg 
balance: **T-90** nerfs it while making it viable

2021-01-27 17:17 UTC, tgstation-server commented
You currently have a negative Fix/Feature pull request delta of -14. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

2021-01-27 17:17 UTC, TiviPlus commented
freeze

2021-02-03 06:21 UTC, Pariah919 commented
I don't like the changes to revolvers, I think they're fine as is.
Pocket pistol uses its own bullet, don't obscfuate the code please.
Pistol ammo mag upgrade is fine

2021-02-03 11:56 UTC, TiviPlus commented
Unatomized and broken changelog

2021-02-06 19:46 UTC, TiviPlus requested changes

2021-02-06 19:46 UTC, TiviPlus commented on code/modules/projectiles/guns/revolvers.dm
> +	fire_delay = 0.275
I will not accept this change

2021-02-07 00:35 UTC, SilencedMP5A5 commented
i like the changes to the other guns but leave revolver alone please

2021-02-07 17:50 UTC, SplinterGP commented on code/modules/projectiles/guns/revolvers.dm
> +	fire_delay = 0.275
fix above please

2021-02-08 15:23 UTC, fernandos13 commented on code/modules/projectiles/guns/revolvers.dm
> +	fire_delay = 0.275
fixed

2021-02-09 19:26 UTC, TiviPlus approved these changes

2021-02-10 20:52 UTC, SplinterGP requested changes

2021-02-10 20:52 UTC, SplinterGP commented on code/modules/projectiles/guns/smgs.dm
> +	fire_delay = 0.165 SECONDS
```suggestion
	fire_delay = 0.15 SECONDS
```

2021-02-10 20:52 UTC, SplinterGP commented on code/modules/projectiles/guns/smgs.dm
> +	accuracy_mult_unwielded = 0.9
```suggestion
	accuracy_mult = 1.5
	accuracy_mult_unwielded = 0.85
```

2021-02-10 21:13 UTC, SplinterGP approved these changes

2021-02-10 21:15 UTC, merged

2021-02-10 21:15 UTC, tgstation-server commented
Your Fix/Feature pull request delta is currently below zero (-39). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.