police comms to CAS and MORTAR
tgstation/TerraGov-Marine-Corps pull request #5826
Opened 2021-01-27 18:30 UTC by fernandos13

## About The Pull Request
QoL improvement refactors the MP channel to Cas/mortar "fire support one"

## Why It's Good For The Game
https://github.com/tgstation/TerraGov-Marine-Corps/projects/1#card-50871965

## Changelog
:cl:
tweak: MP headset to fire support specialist headset
remove: master of arms headset
fix: Cas and Mortar dedicated channel is now in place
/:cl:

2021-01-27 18:41 UTC, fernandos13 commented
not working YET dont merged it as is even it if compiles

2021-01-27 18:48 UTC, BraveMole commented
If it's still a work in progress, you can add [WIP] to your PR name, that'll give it an automatic tag

2021-01-27 18:54 UTC, fernandos13 commented
thanks!

2021-01-27 18:58 UTC, fernandos13 commented
working now fixed

2021-01-29 16:20 UTC, SplinterGP requested changes

2021-01-29 16:20 UTC, SplinterGP commented on code/game/objects/items/radio/encryptionkey.dm
> +	name = "Fire support specialist Key"
```suggestion
	name = "Fire support radio encryption key"
```

2021-01-29 16:20 UTC, SplinterGP commented on code/game/objects/structures/mortar.dm
> +	/obj/item/radio/headset/mainship/marine/generic/mmpo
```suggestion
	new /obj/item/radio/headset/mainship/marine/generic/mmpo(src)
	new /obj/item/radio/headset/mainship/marine/generic/mmpo(src)
	new /obj/item/radio/headset/mainship/marine/generic/mmpo(src)
```

2021-01-30 20:55 UTC, SplinterGP approved these changes
all good to me

2021-01-30 21:10 UTC, SplinterGP requested changes

2021-01-30 21:10 UTC, SplinterGP commented on code/__DEFINES/radio.dm
> +#define RADIO_CHANNEL_CAS "fire support"
```suggestion
#define RADIO_CHANNEL_CAS "Fire support"
```

2021-01-30 21:24 UTC, SplinterGP requested changes

2021-01-30 21:24 UTC, SplinterGP commented on code/game/objects/items/radio/headset.dm
> +/obj/item/radio/headset/mainship/marine/generic/mmpo
forgot typepath

2021-01-31 20:55 UTC, SplinterGP commented
you just need to replace the old typepath in maps with the new one, if you are in VSC should be easy as just searching the old typepath for the new one

2021-02-04 15:12 UTC, TiviPlus approved these changes

2021-02-04 15:13 UTC, merged