a fix for the meraderm depending on hugged people
tgstation/TerraGov-Marine-Corps pull request #5838
Opened 2021-01-30 10:53 UTC by fernandos13

## About The Pull Request
this makes so scalps can be grinded in larva jelly

## Why It's Good For The Game
strays further yet from capt gameplay and with the trending of less and less larvas getting meraline and dermaline became a pain

## Changelog
:cl:
tweak: scalps can now be grinded for jelly
/:cl:

2021-01-30 10:54 UTC, tgstation-server commented
You currently have a negative Fix/Feature pull request delta of -14. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

2021-01-30 18:41 UTC, David-Stormwell commented
Rename it from larva jelly to something different.

2021-01-30 21:24 UTC, Chaznoodles commented
You can order Lemoline from Req. Just make that somewhat cheaper so advanced chemicals are still reliant on marines holding areas/killing xenos rather than doing the infiniscalp thing.

2021-01-31 01:01 UTC, joookschad commented
> You can order Lemoline from Req. Just make that somewhat cheaper so advanced chemicals are still reliant on marines holding areas/killing xenos rather than doing the infiniscalp thing.

you could also fix scalp code so a xeno can be scalped only one

2021-02-03 02:32 UTC, SplinterGP commented
Xenos can be infinitely scalped, so i'd ask to either make them be scalpable once or some workaround, since xenos also can salvage biomass and get rid of a corpse.

2021-02-03 11:18 UTC, fernandos13 commented
fixed

2021-02-03 17:23 UTC, SplinterGP requested changes

2021-02-03 17:23 UTC, SplinterGP commented on code/datums/elements/scalping.dm
> +/datum/element/scalping/proc/on_attack(datum/source, mob/living/carbon/xenomorph/M, mob/living/user)
```suggestion
/datum/element/scalping/proc/on_attack(datum/source, mob/living/M, mob/living/user)
```
no need for this

2021-02-04 16:25 UTC, TiviPlus requested changes

2021-02-04 16:25 UTC, TiviPlus commented on code/datums/elements/scalping.dm
> +
why is this a visible mesage

2021-02-05 14:20 UTC, fernandos13 commented on code/datums/elements/scalping.dm
> +
oh i set that for everyone mistake

2021-02-10 18:29 UTC, closed without merging