Fix crit/stun/standing drags having no delay
tgstation/TerraGov-Marine-Corps pull request #5862
Opened 2021-02-01 18:30 UTC by TGCMbetcher

## About The Pull Request

Tested all of them had no issues other then I dont have my preferences on the server and had issues headbitting but got it done somehow when I wasnt looking to test that headbites still have no delay. Basically adds delay to stunned and crit marines while also making it harder for wraith to walk up to a marine and teleport him a screen away or into lava.

## Why It's Good For The Game

Its better then decreasing the drag speed on xenos since you are still able to combat drag, just only if you are willing to be shot for 2 seconds before dragging. This allows hunters to sneak out crit marines or very long queen screech stuns fast enough for marines to not react, but only if they have enough time to grab said marine.

The alternative is much worse as marines would be able to hunt them down while dragging and is just worse altogether as no one like slowly dragging bodies into a corner to eat them.

## Changelog
:cl:
del: Removed old things
balance: rebalanced something
fix: fixed a few things
/:cl:

2021-02-06 01:42 UTC, SplinterGP requested changes
Xenos should be able to drag on combat, unless the enemy is down.

2021-02-06 01:42 UTC, SplinterGP commented on code/modules/mob/living/carbon/xenomorph/xenomorph.dm
> +			if(!L.headbitten) //Grab delay vs the non-headbitten dead
```suggestion
			if(L.stat !- CONSCIOUS && !L.headbitten) //Grab delay vs non headbitten unconscious people.
```

2021-02-07 00:29 UTC, TGCMbetcher commented
> Xenos should be able to drag on combat, unless the enemy is down.

So it should be normal for a hunter to drag a guy who stepped on sticky 5 tiles instantly? But they shouldnt be able to drag a stunned marine a screen and a half after a stealth pounce? This is basically a bandaid until hunter speed during dragging is fixed, no other caste has an issue but wraith for teleportation issues. They can literally move you a screen in a second because all the speed bonuses cancel out all the negatives for drag making them drag you at full run. Thats what I told tivi in dev when I asked how to do it, though I pushed this further.

2021-02-07 01:17 UTC, SplinterGP commented
> > Xenos should be able to drag on combat, unless the enemy is down.
> 
> So it should be normal for a hunter to drag a guy who stepped on sticky 5 tiles instantly? But they shouldnt be able to drag a stunned marine a screen and a half after a stealth pounce? This is basically a bandaid until hunter speed during dragging is fixed, no other caste has an issue but wraith for teleportation issues. They can literally move you a screen in a second because all the speed bonuses cancel out all the negatives for drag making them drag you at full run. Thats what I told tivi in dev when I asked how to do it, though I pushed this further.

find out why this happens to hunter then

2021-02-07 01:38 UTC, TGCMbetcher commented
> find out why this happens to hunter then

We already know why, with bonuses they get a -2.2 move speed modifier if they want. That basically kills any attempt to slow them down including corpse drag. They cant be slowed down at all, which is on purpose because theyre supposed to be small agile hunters. That being said they completely break the dragging system and I told everyone, this is a bandaid. Its only temporary. I think corpses should be instantly drug and living ones should have the required time, maybe a chance of drop. But Im not a coder, it took me 3 hours to find this line here and I needed help to change it, then another 45 minutes and 12 tests to get it to do what I want. If they want to have hunters be that fast fine, make it so they cant drag and delete this pull. Otherwise make it so everyone but headbites require the 2 second wind up to drag to make crit drags and stun drags less over powered. At the moment its the kiss of death and NOTHING will save you except maybe jetpacks if you manage to use it.

2021-02-07 01:44 UTC, SplinterGP commented
> > find out why this happens to hunter then
> 
> We already know why, with bonuses they get a -2.2 move speed modifier if they want. That basically kills any attempt to slow them down including corpse drag. They cant be slowed down at all, which is on purpose because theyre supposed to be small agile hunters. That being said they completely break the dragging system and I told everyone, this is a bandaid. Its only temporary. I think corpses should be instantly drug and living ones should have the required time, maybe a chance of drop. But Im not a coder, it took me 3 hours to find this line here and I needed help to change it, then another 45 minutes and 12 tests to get it to do what I want. If they want to have hunters be that fast fine, make it so they cant drag and delete this pull. Otherwise make it so everyone but headbites require the 2 second wind up to drag to make crit drags and stun drags less over powered. At the moment its the kiss of death and NOTHING will save you except maybe jetpacks if you manage to use it.

i  mean runners get slowed down alot, find in code why that happens and do same for hunter

2021-02-07 01:46 UTC, TGCMbetcher commented
Seriously, the fact that a hunter can walk into you and have you a screen away before the stun is over, surrounded by xenos, is beyond broken. This is made specifically to stop that. Full health stunned into a prea a hunter and a drone, nothing will save you when they pull the second stun off.

2021-02-07 01:48 UTC, TGCMbetcher commented
> i mean runners get slowed down alot, find in code why that happens and do same for hunter

Someone mentioned it was the compromise for the 3x speed of runners. Mr. Snoopy said he was already working on it but he hasnt put it up yet so I dont know. Any idea what term I would even search up? It wasnt under grab I know that I looked at 80% of those files before I found this nd it should be included.

2021-02-07 04:04 UTC, TGCMbetcher commented
Alright I think Ive figured out a work around. Im going to make a new tag for small xenos and try to make a fixed move speed when dragging a human. Given that they are small and shouldnt move quick pulling a much heavier object it shouldnt be an issue for sents/drones/runners/hunters to move at crawling speed when dragging. If they want to move corpses they can swallow them and run that way

2021-02-08 18:51 UTC, closed without merging