Adds the AOE-generator  to the ships , adds it as a req purchaseable
tgstation/TerraGov-Marine-Corps pull request #5866
Opened 2021-02-02 01:00 UTC by MLGTASTICa

## About The Pull Request

Adds 1 A.D.V.P.A.C.M.A.N mobile-power generator to each ship map in rotation , adds it to req , 1 generator for 20 points.
## Why It's Good For The Game

Less reliance on easy to saboutage APC's.

## Changelog
:cl:
add:  A.D.V.P.A.C.M.A.N AOE Generator on all ship maps.
add:  A.D.V.P.A.C.M.A.N as a purchaseable requisitions item.
/:cl:

2021-02-02 01:00 UTC, tgstation-server commented
You currently have a negative Fix/Feature pull request delta of -28. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

2021-02-02 05:56 UTC, XSlayer300 commented on code/modules/reqs/supplypacks.dm
> +	name = "Wireless power generator"
```suggestion
	name = "wireless power generator"
```

2021-02-02 15:38 UTC, MLGTASTICa commented on code/modules/reqs/supplypacks.dm
> +	name = "Wireless power generator"
All of them start uppercase.

2021-02-02 17:44 UTC, Swagile commented
please

APC's break sometimes when you build them too, as in certain areas don't allow APC's for some retarded reason

this fixes that

2021-02-02 20:49 UTC, TiviPlus requested changes

2021-02-02 20:49 UTC, TiviPlus commented on code/modules/reqs/supplypacks.dm
> +/datum/supply_packs/engineering/advanced_generator
```suggestion
	cost = 5

/datum/supply_packs/engineering/advanced_generator
```

2021-02-02 21:31 UTC, TiviPlus approved these changes

2021-02-03 01:54 UTC, SplinterGP approved these changes

2021-02-03 01:55 UTC, merged

2021-02-03 01:55 UTC, tgstation-server commented
Your Fix/Feature pull request delta is currently below zero (-38). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.