Fixes a bit over half of the sleeping signal handlers
tgstation/TerraGov-Marine-Corps pull request #5885
Opened 2021-02-03 11:26 UTC by TiviPlus

## About The Pull Request

this probably needs a round or two of tm

## Why It's Good For The Game

## Changelog
:cl:
refactor: refactored doors and carious other code to remove sleeping signals
/:cl:

2021-02-03 20:06 UTC, spookydonut commented on code/datums/marine_main_ship.dm
> +						D.open()
atomise bruh

2021-02-14 18:07 UTC, SplinterGP requested changes

2021-02-14 18:07 UTC, SplinterGP commented on code/game/objects/machinery/doors/airlock.dm
> +	if (operating || src.locked)
```suggestion
	if (operating || locked)
```

2021-02-14 18:08 UTC, SplinterGP approved these changes

2021-02-14 18:20 UTC, merged