adds the t-26, and reprices the autosniper
tgstation/TerraGov-Marine-Corps pull request #5948
Opened 2021-02-06 20:09 UTC by Pariah919

## About The Pull Request
adds the t-26, which is basically the old m42a, you lase a beno to deal more damage. Normal rounds only.
Reprices autosniper to 40 points.

## Why It's Good For The Game
autosniper is overpriced, and the antimaterial rifle is a neat idea

## Changelog
:cl:
add: Added new antimaterial rifle to marines, 120 points. Functions like the old m42a scout sniper
balance: autosniper repriced to 40
/:cl:

2021-02-06 20:09 UTC, tgstation-server commented
You currently have a negative Fix/Feature pull request delta of -288. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

2021-02-06 22:15 UTC, Swagile commented
Ive said this before on your main PR and ill say it again.

You do not want to nerf autosniper price. It is only balanced around the fact that you can't spam it.

Being able to buy tons of these will just bring back TL bolt meta except worse; you can't acid flares to stop this, and on top of it, autosniper can be used to push out for its NVG qualities, making it INSANELY good.

For reference, the tac binos is 30 points, so you'd basically have no real reason to buy tac binos outside of maybe OBing once in a while or railgun.

2021-02-06 23:24 UTC, SkeletalElite commented
It's spelled anti-materiel rifle. It's a different word, not just a different spelling.

2021-02-07 02:33 UTC, SkeletalElite commented on code/modules/codex/entries/guns_codex.dm
>  	It was at first marketed to PMCs and civilians as an expensive accurate long range rifle but it failed due to the lack of need for such a thing for PMCs and the wide variety of options \
Codex entry still refers to it by the m42a

2021-02-07 12:27 UTC, revelation-8468 commented
>120 points

lol wut

2021-02-08 04:10 UTC, SpaceLoveSs13 commented
Doesn't T-26 already exist in the code. It's the Spec grenade launcher that can be obtained from grenediers kit.

2021-02-08 04:42 UTC, Pariah919 commented
that's not an item you can get anymore anyway

Its just the generic gl now

2021-02-08 14:01 UTC, TiviPlus requested changes

2021-02-08 14:01 UTC, TiviPlus commented on code/game/objects/items/portable_vendor.dm
> +		list("Sniper (antimaterial Scoped Rifle, 88 Mod 4 Pistol)", 1, /obj/item/storage/box/squadmarine/sniper, "white", "A kit specializing in long-ranged dispatch."),
Capitilizing
```suggestion
		list("Sniper (Antimaterial Scoped Rifle, 88 Mod 4 Pistol)", 1, /obj/item/storage/box/squadmarine/sniper, "white", "A kit specializing in long-ranged dispatch."),
```

2021-02-08 14:06 UTC, merged

2021-02-08 14:06 UTC, tgstation-server commented
Your Fix/Feature pull request delta is currently below zero (-306). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.