Cryobags freeze the DNR timer
tgstation/TerraGov-Marine-Corps pull request #5956
Opened 2021-02-07 14:42 UTC by BraveMole

## About The Pull Request

Putting a human body in a cryobag will prevent its brain to decay

## Why It's Good For The Game

Since headbiting is on its way out, corps are often overwhelmed with dead bodies. This will make triage easier

## Changelog
:cl:
balance: Cryobags prevents the DNR timer to tick 
/:cl:

2021-02-14 18:50 UTC, TiviPlus commented on code/__DEFINES/mobs.dm
> +#define TIME_BEFORE_DNR 300 //The unit is the second here, due to how life() works
Life() ticks every 2 seconds not 1

2021-02-17 09:22 UTC, TiviPlus approved these changes

2021-02-18 01:51 UTC, SplinterGP requested changes

2021-02-18 01:51 UTC, SplinterGP commented on code/modules/mob/living/carbon/human/human_defines.dm
> +	///How long the human is dead, in seconds
```suggestion
	///How long the human is dead, in seconds
```

2021-02-18 21:55 UTC, TiviPlus commented on code/modules/mob/living/carbon/human/human_defines.dm
> +	var/dead_ticks = 0
Life ticks are 2 seconds not 0.5

2021-02-18 22:08 UTC, TiviPlus approved these changes

2021-02-18 22:12 UTC, merged

2021-02-18 22:12 UTC, tgstation-server commented
Your Fix/Feature pull request delta is currently below zero (-49). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.