webbing is bulky and med webbing nerfs
tgstation/TerraGov-Marine-Corps pull request #5975
Opened 2021-02-08 19:53 UTC by Pariah919

## About The Pull Request
surgery webbing nerf
webbing is bulky unsurprisignly

## Why It's Good For The Game
webbing is bulky

## Changelog
:cl:
fix: webbing is bulky
balance: surgery webbing nerfs, no longer holds brute kits and burn kits
/:cl:

2021-02-08 19:53 UTC, tgstation-server commented
You currently have a negative Fix/Feature pull request delta of -306. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

2021-02-08 19:56 UTC, AGasCanister commented
Trauma kits are needed for organ damage and necrosis, could perhaps limit it to 1 stack of trauma kit in the surgical webbing

2021-02-08 23:37 UTC, fernandos13 commented
lol imagine the guy. oh ye lets nerf the surgery vest. its not like all MOs can do is fix bones and organs lately. lets rest assured its limited to bones only

2021-02-08 23:46 UTC, Texicos commented
To bad it'll still get merged even if the majority fucking hates it

2021-02-08 23:49 UTC, fernandos13 commented
HALVING the corpsman white vest. cause WHO needs a corpsman to carry the
defib
medvac bed
roller bed
HL2 health analyzer
some hypo/injector (in the kit oxy comes for free but most corpsman will get better stuff)
TWEZERS (that are quite big)
all pills (( and better pack extra bic and kelo at least))
brute kits and burn kits and splints (for a entire squad)
oh ye and his ammo.. 
and his food...
and dont forget to pack some custom chems cause IMIALK doesn't come in by default. neither does meraderm neuraline or any of those in variation (you did waste your points so you better find a way to pack those)

2021-02-08 23:51 UTC, fernandos13 commented
also the pr is very misleading cause you skimmed of the biggest nerf of it

halving the corpsman white vest storage

2021-02-09 00:19 UTC, Swagile commented
don't get why we're nerfing corpsman when barely anyone goes corpsmen as is; corpsmen needs more QoL, not less

2021-02-09 18:11 UTC, TGCMbetcher commented
> don't get why we're nerfing corpsman when barely anyone goes corpsmen as is; corpsmen needs more QoL, not less

Yes, QOL is why I dont medic. There is no upside to playing it for yourself and you have to juggle 30 different things. Medic webbing is already bad but now theyre nerfing it more.

2021-02-09 18:42 UTC, SplinterGP requested changes

2021-02-09 18:42 UTC, SplinterGP commented on code/modules/clothing/under/ties.dm
> +
what's this shitcode ?

2021-02-10 18:56 UTC, Pariah919 commented
i'm lazy

2021-02-10 18:56 UTC, closed without merging