pepperball gun
tgstation/TerraGov-Marine-Corps pull request #5995
Opened 2021-02-10 05:24 UTC by Pariah919

## About The Pull Request
makes pepperball gun
it drains plasma on hit
"mjp there's no sprites"
go make me some else I'm deleting this in one day

## Why It's Good For The Game
adds guns for cool more options, its cool

## Changelog
:cl:
add: Added new ungettable pepperball gun
/:cl:

2021-02-10 05:24 UTC, tgstation-server commented
You currently have a negative Fix/Feature pull request delta of -315. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

2021-02-10 12:23 UTC, XSlayer300 commented on code/modules/projectiles/guns/specialist.dm
> +	name = "\improper Pepperball gun"
```suggestion
	name = "\improper TLNL-12 pepperball gun"
```

2021-02-10 12:29 UTC, XSlayer300 commented on code/modules/projectiles/guns/specialist.dm
> +	desc = "A pepperball gun that fires toxins. It fires pepperball balls."
```suggestion
	desc = "A TerraGov less-lethal weapon, it comes in limited numbers and has limited use throughout the military, though sizeable use throughout TerraGov's Navy Police. The variant fires plasma-draining tanglefoot pepperballs in a compressed form, quickly delivering ammunition throughout the field.."
```

2021-02-10 12:30 UTC, XSlayer300 commented on code/modules/projectiles/guns/specialist.dm
> +	caliber = "pepperball" //codex
```suggestion
	caliber = "TGF-Ball" //codex
```

2021-02-10 12:30 UTC, XSlayer300 commented on code/modules/projectiles/magazines/specialist.dm
> +	caliber = "pepperball"
```suggestion
	caliber = "TGF-Ball"
```

2021-02-10 19:20 UTC, TiviPlus commented
MJP there are no sprites

2021-02-13 16:34 UTC, Pariah919 commented
![image](https://user-images.githubusercontent.com/46353991/107855314-7c013f80-6def-11eb-87bf-ebea92a15a46.png)

2021-02-13 16:37 UTC, BraveMole commented
sprite is awfull, please git ban

2021-02-14 17:35 UTC, TiviPlus requested changes

2021-02-14 17:35 UTC, TiviPlus commented on code/modules/projectiles/ammo_datums.dm
> +	var/danger_message = "<span class='danger'>The pepperball explodes with a splat and explodes into purple gas!</span>"
Declare new vars after redefining old ones

2021-02-15 00:55 UTC, TiviPlus approved these changes

2021-02-15 13:36 UTC, XSlayer300 commented on code/modules/projectiles/guns/specialist.dm
> +	desc = "A TerraGov less-lethal weapon, it comes in limited numbers and has limited use throughout the military, though sizeable use throughout TerraGov's Navy Police. The variant fires plasma-draini
```suggestion
	desc = "A TerraGov less-lethal weapon, it comes in limited numbers and has limited use throughout the military, though sizeable use throughout TerraGov's Navy Police. The variant fires plasma-draining tanglefoot pepperballs in a compressed form, quickly delivering ammunition throughout the field."
```

2021-02-15 13:36 UTC, XSlayer300 commented on code/modules/projectiles/magazines/specialist.dm
> +	name = "\improper Pepperball magazine (10x28mm)"
```suggestion
	name = "\improper TGF-Pepperball magazine (TGF-Ball)"
```

2021-02-16 14:37 UTC, Pariah919 commented
test has been done

Idea no good, back to the drawing board

2021-02-16 14:37 UTC, closed without merging