adds more blacklisted versions
tgstation/TerraGov-Marine-Corps pull request #6007
Opened 2021-02-11 15:43 UTC by BeloneX

## About The Pull Request
title

## Changelog
:cl:
server: added more blacklisted versions
/:cl:

2021-02-11 15:43 UTC, tgstation-server commented
You currently have a negative Fix/Feature pull request delta of -21. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

2021-02-12 23:38 UTC, TiviPlus requested changes
I assume this is ported from bee so add it to the description please

2021-02-12 23:38 UTC, TiviPlus commented on code/_globalvars/lists/client.dm
> +	))
```suggestion
	"1408" = "bug preventing client display overrides from working leads to clients being able to see things/mobs they shouldn't be able to see",
	))
```

2021-02-13 09:15 UTC, TiviPlus approved these changes

2021-02-13 09:15 UTC, merged