Adds a cloak implant and fixes implants not activating
tgstation/TerraGov-Marine-Corps pull request #6009
Opened 2021-02-11 17:00 UTC by TiviPlus

## About The Pull Request

## Changelog
:cl:
add: Unobtainable cloak implant
fix: implants activate properly
code: two stealths may no longer be active to avoid alpha bugs
/:cl:

2021-02-11 23:55 UTC, XSlayer300 commented on code/game/objects/items/implants/implant_cloak.dm
> +	<b>Function:</b> Upon activation decreases the reflection rate of light in order to reduce user visibility.<BR>
```suggestion
	<b>Function:</b> Upon activation, this implant decreases the reflection rate of light in order to reduce user visibility.<BR>
```

2021-02-13 16:23 UTC, SplinterGP approved these changes

2021-02-13 16:24 UTC, SplinterGP requested changes

2021-02-13 16:24 UTC, SplinterGP commented on code/game/objects/items/storage/backpack.dm
> +	if (usr?.incapacitated(TRUE))
user always exists
```suggestion
	if (usr.incapacitated(TRUE))
```

2021-02-13 16:37 UTC, SplinterGP approved these changes

2021-02-13 16:37 UTC, merged