:^)
tgstation/TerraGov-Marine-Corps pull request #6014
Opened 2021-02-11 17:53 UTC by Walarks

2021-02-11 17:53 UTC, tgstation-server commented
You currently have a negative Fix/Feature pull request delta of -25. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

2021-02-11 17:54 UTC, Pariah919 commented
denied

2021-02-11 18:30 UTC, TiviPlus approved these changes

2021-02-11 20:02 UTC, InterroLouis commented
Oh no my medic button

2021-02-12 02:41 UTC, TGCMbetcher commented
> denied

Why? All it does is stop accidental FF

2021-02-12 18:35 UTC, SplinterGP commented
> > denied
> 
> Why? All it does is stop accidental FF

name from before

2021-02-12 18:36 UTC, SplinterGP requested changes

2021-02-12 18:36 UTC, SplinterGP commented on code/datums/actions/item_action.dm
> +
Decide yourself on one or the other

2021-02-12 23:35 UTC, TiviPlus commented on code/datums/actions/item_action.dm
> +
Cleared up on discord

2021-02-12 23:36 UTC, merged