Monkey refactor to a species
tgstation/TerraGov-Marine-Corps pull request #6025
Opened 2021-02-12 23:24 UTC by TiviPlus

## About The Pull Request

Todo
- [ ] finish converting stok sprites
- [ ] finish converting naera sprites
- [ ] test more
- [ ] probably tm

## Why It's Good For The Game

One day we may kill /carbon
have fun reviewing this @SplinterGP 

## Changelog
:cl:
refactor: Monkeys are now at last a human species rather than a seperate type
/:cl:

2021-02-13 01:49 UTC, SplinterGP commented
> have fun reviewing this @SplinterGP

You fool, i'm the ultimate mob code reviewer

2021-02-15 07:57 UTC, BraveMole commented
Were monkies able to wear armor / use guns before this? They will have all the inventory slots as well now, right?

Will that not break most of the sprites?

2021-02-18 01:43 UTC, SplinterGP requested changes

2021-02-18 01:43 UTC, SplinterGP commented on code/game/objects/machinery/kitchen/gibber.dm
> +		if(istype(occupant, /mob/living/carbon/human) || istype(occupant, /mob/living/carbon/xenomorph)) // why are you gibbing aliens? oh well
```suggestion
		if(ismonkey(occupant) || istype(occupant, /mob/living/carbon/xenomorph)) // why are you gibbing aliens? oh well
```

2021-02-18 01:43 UTC, SplinterGP commented on code/game/objects/machinery/kitchen/processor.dm
> +	/* mobs */  //there were here once but fuk that noise
```suggestion
```

2021-02-20 00:32 UTC, SplinterGP approved these changes
seems all good to me

2021-02-22 19:07 UTC, SplinterGP commented
all good, everything that came with it is a feature.

2021-02-22 19:08 UTC, merged