Personal Runechat Color
tgstation/TerraGov-Marine-Corps pull request #6045
Opened 2021-02-14 13:38 UTC by XSlayer300

## About The Pull Request
As I requested in #feeback, this is a port of _that one specific server_ that allows us snowflakes to choose our own Runechat color. I also did improvements on the mob_helpers code as well, so it can be a bit of a refractor.

## Why It's Good For The Game
Again, snowflakes.

## Changelog
:cl:
add: Runechat colors can either be randomized or based on your own preferences!
/:cl:

2021-02-14 13:38 UTC, tgstation-server commented
You currently have a negative Fix/Feature pull request delta of -27. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

2021-02-14 14:41 UTC, TiviPlus requested changes

2021-02-14 14:41 UTC, TiviPlus commented on code/datums/chatmessage.dm
> +		target.chat_color_name = target.name
Why is most of this junk not in Login() or pref creation

2021-02-14 14:41 UTC, TiviPlus commented on code/datums/chatmessage.dm
> +	var/list/HSL = rgb2hsl(hex2num(copytext(color, 2, 4)), hex2num(copytext(color, 4, 6)), hex2num(copytext(color, 6, 8)))
All new procs must be documented

2021-02-14 14:41 UTC, TiviPlus commented on code/__DEFINES/runechat_defines.dm
> +GLOBAL_LIST_EMPTY(runechat_color_names)
Why is this global needed exactly

2021-02-14 14:41 UTC, TiviPlus commented on code/modules/client/preferences.dm
> +					to_chat(user, "<span class='danger'>Invalid color. Your color is not bright enough.</span>")
early return

2021-02-14 14:41 UTC, TiviPlus commented on code/modules/client/preferences_savefile.dm
> +
You dont read properly from savefile here?

2021-02-14 14:41 UTC, TiviPlus commented on code/modules/mob/mob_helpers.dm
> +/proc/rgb2hsl(red, green, blue)
Why is this in mob helpers of all places
Also new procs must be documented

2021-02-14 14:41 UTC, TiviPlus commented on code/datums/chatmessage.dm
> +	return final_val
Why is this glob still here?

2021-02-21 19:30 UTC, TiviPlus commented
Author has expressed that they dont believe to have the code knowledge to complete this PR but they are free to ask for a reopen anytime

2021-02-21 19:30 UTC, closed without merging