Ice Cream (Color Gradients)
tgstation/TerraGov-Marine-Corps pull request #6047
Opened 2021-02-14 23:47 UTC by XSlayer300

## About The Pull Request
To-Be-Added

## Why It's Good For The Game
To-Be-Added

## Changelog
:cl:
add: Hair color gradients
/:cl:

2021-02-14 23:47 UTC, tgstation-server commented
You currently have a negative Fix/Feature pull request delta of -27. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

2021-02-15 00:06 UTC, SplinterGP requested changes

2021-02-17 13:01 UTC, Kuro-ai commented
God help us all

2021-02-17 13:07 UTC, XSlayer300 commented
> God help us all

exactly.

2021-02-18 00:02 UTC, BeloneX commented
Can you precisely explain what this does?

2021-02-18 01:11 UTC, SplinterGP commented
> Can you precisely explain what this does?

gradient patterns for hair

2021-02-18 01:22 UTC, SplinterGP requested changes

2021-02-18 01:22 UTC, SplinterGP commented on code/modules/mob/living/carbon/human/update_icons.dm
> +					grad_s = new/icon("icon" = 'icons/mob/hair_gradients.dmi', "icon_state" = gradient.icon_state)
```suggestion
					grad_s = new/icon("icon" = gradient.icon, "icon_state" = gradient.icon_state)
```

2021-02-18 01:22 UTC, SplinterGP commented on code/__HELPERS/global_lists.dm
> +	// Hair Gradients - Initialise all /datum/sprite_accessory/hair_gradient into an list indexed by hair-style name
```suggestion
	// Hair Gradients - Initialise all /datum/sprite_accessory/hair_gradient into an list indexed by gradient-style name
```

2021-02-18 02:42 UTC, SplinterGP approved these changes

2021-02-18 02:43 UTC, merged

2021-02-18 02:43 UTC, tgstation-server commented
Your Fix/Feature pull request delta is currently below zero (-36). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.