Monitor v2
tgstation/TerraGov-Marine-Corps pull request #6058
Opened 2021-02-16 12:53 UTC by BraveMole

## About The Pull Request

Make the monitor more usefull before shutters drop and when shipside

## Why It's Good For The Game

It will make the auto balance feature actually do something even before shutters drop, wich was not the case

## Changelog
:cl:
/:cl:

2021-02-16 12:53 UTC, tgstation-server commented
You currently have a negative Fix/Feature pull request delta of -38. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

2021-02-17 08:47 UTC, TiviPlus requested changes

2021-02-17 08:47 UTC, TiviPlus commented on code/controllers/subsystem/monitor.dm
> +	gamestate = SHIPSIDE
signal handlers

2021-02-17 08:47 UTC, TiviPlus commented on code/controllers/subsystem/monitor.dm
> +	. += GLOB.alive_xeno_list.len * XENOS_LIFE_WEIGHT_PREGAME
early return

2021-02-17 21:05 UTC, TiviPlus approved these changes

2021-02-17 21:05 UTC, merged