Add support for right click human actions
tgstation/TerraGov-Marine-Corps pull request #6069
Opened 2021-02-17 16:27 UTC by TiviPlus

## About The Pull Request

Title

@Walarks this includes item attacks

## Changelog
:cl:
code: Add support for right click human actions
/:cl:

2021-03-05 20:45 UTC, SplinterGP commented on code/_onclick/item_attack.dm
> +	SIGNAL_HANDLER_DOES_SLEEP
bad

2021-03-06 19:50 UTC, spookydonut commented on code/_onclick/item_attack.dm
> +	SIGNAL_HANDLER_DOES_SLEEP
aaaaaaaaaaaaaaaaaaaaa

2021-03-07 04:11 UTC, spookydonut reviewed
ci failure

2021-03-10 19:20 UTC, SplinterGP requested changes

2021-03-10 19:20 UTC, SplinterGP commented on code/_onclick/click.dm
> +			if(proximity)
remove var above
```suggestion
			if(A.Adjacent(src))
```

2021-03-10 19:51 UTC, TiviPlus commented on code/_onclick/click.dm
>  			var/proximity = A.Adjacent(src)
```suggestion
```

2021-03-10 20:51 UTC, merged