Clean up req, unbloat req vendor
tgstation/TerraGov-Marine-Corps pull request #6083
Opened 2021-02-18 18:10 UTC by BraveMole

## About The Pull Request

Remove most of empty crates from req. Move the laser recharger, and the water/mre/flare crate in hangar, closer to alamo/tadpole. Remove the ammo box and grenade box from req vendor to put them in crates in hangar

## Why It's Good For The Game

Req is not as bloated, prep will be quicker

## Changelog
:cl:
tweak: Full ammo and grenade boxes are now in hangard instead of req vendor
tweak: water/flare/mre crates are now in hangar instead of req
/:cl:

2021-02-18 18:10 UTC, tgstation-server commented
You currently have a negative Fix/Feature pull request delta of -41. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

2021-02-18 18:53 UTC, SpaceLoveSs13 commented
Why move ammo and weapons crate? I don't think it's worth the time to go to hanger grab ammo crate, bring it back, load ammo boxes, and put them back on alamo. It's just filling up the same time moving mre/flare/las charger would.

2021-02-18 21:22 UTC, Swagile commented
I think the bluespace pad is the only thing I can think of at the top of my head that isn't really good.

The reason being in pool meta, its better NOT to buy a ASRS pad roundstart and buy 4 fultons (20 points total), and only buy a ASRS pad if you KNOW marines have a dedicated tadpole team or a decent engi team that will secure a FOB miner.

2021-02-18 22:36 UTC, Chaznoodles commented
Powercreep

2021-02-18 23:14 UTC, SplinterGP commented
Engineer stuff should be in engineer Prep, no reason to put this in there for any unga to get, we already saw engineers steal resources from all other engineers before and this lets ANYONE

2021-02-18 23:14 UTC, SplinterGP commented
also atomize

2021-02-18 23:17 UTC, SplinterGP requested changes

2021-02-18 23:17 UTC, SplinterGP commented on code/__HELPERS/global_lists.dm
> +		GLOB.pill_icons += "pill[i]"
undocumented changes, and atomize

2021-02-18 23:19 UTC, SplinterGP requested changes

2021-02-18 23:19 UTC, SplinterGP commented on code/game/objects/structures/crates_lockers/crates.dm
> +	new /obj/item/reagent_containers/hypospray/autoinjector/quickclotplus(src)
why should this be in hangar ? that's medical officer gear

2021-02-18 23:19 UTC, SplinterGP commented on code/game/objects/structures/crates_lockers/crates.dm
> +	new /obj/item/bodybag/cryobag(src)
why should ANY marine have this ? this is medical/corpsman stuff.

2021-02-18 23:23 UTC, SplinterGP requested changes

2021-02-18 23:23 UTC, SplinterGP commented on code/game/objects/items/reagent_containers/pill.dm
> +	pill_id = 22
atomize this

2021-02-27 14:56 UTC, BraveMole commented
> also atomize

Atomize what? I asked you 4 times now, you never answered

2021-03-02 18:42 UTC, TiviPlus requested changes
A) the crates should be in the respective department
B) This comes forfree, change that

2021-03-02 18:46 UTC, BraveMole commented
> A) the crates should be in the respective department

But why? 

> B) This comes forfree, change that

Nothing in this is added for free. Everything that was added is either free in a vendor, or taken from elsewhere. The exception is the poly pills bottle, which can be done for free in medbay

2021-03-04 13:42 UTC, TiviPlus commented
> > A) the crates should be in the respective department
> 
> But why?
> 
> > B) This comes forfree, change that
> 
> Nothing in this is added for free. Everything that was added is either free in a vendor, or taken from elsewhere. The exception is the poly pills bottle, which can be done for free in medbay

Answered in discord

2021-03-04 14:52 UTC, MemeLauncher commented
Just putting the stuff in req that goes to alamo roundstart is enough (not the ammo vendor, im talking about water bottle, MRE, flare, water/fuel tank, lasrifle battery charger), as this is the true pain of roundstart which could be us filling ammo boxes/making miner upgrades. And putting them outside on the hallway to alamo for marines is a gamble, sometimes they just don't bring it to alamo (worst case, destroyed there to feed roomba).

2021-03-27 00:33 UTC, closed without merging