Ports TGChat
tgstation/TerraGov-Marine-Corps pull request #6086
Opened 2021-02-18 21:30 UTC by SplinterGP

## About The Pull Request
Ports [TGChat](https://github.com/tgstation/tgstation/pull/52426) that uses TGUI.

This PR should be quite smaller than TGUI 4.3 port PR since TGUI PR already brought tgchat stuff, this is basically removing goonchat from code, adding few tgchat and changing some stuff on already on /tgui folder like the SCSS

Still has some stuff to finish, like doing the light mode SCSS and some admin to_chat() changes.

this is how i've got it so far, fixed a few things you might see wrong on it on photo:

![image](https://user-images.githubusercontent.com/29824735/108423854-270e6080-7217-11eb-9303-c065fe4a816e.png)

## Why It's Good For The Game
Lighter than goonchat, reduces server load and its better overall, and carries past chat messages between connects(And through all servers that uses TGChat, since its a cache file on your PC).

## Changelog
:cl:
add: Added TGChat in place of Goonchat.
del: Goonchat removed.
code: updated icon2base64 proc to not use a global file that doens't exist anymore.
/:cl:

2021-02-19 10:10 UTC, TiviPlus requested changes
Did you port the reconnect issue workaround?

2021-02-19 10:10 UTC, TiviPlus commented on code/modules/admin/admin_verbs.dm
> +			confidential = TRUE)
Delete all the confidential junk, it was for Replays IIRC and we dont use it

2021-02-19 17:24 UTC, SplinterGP commented
> Did you port the reconnect issue workaround?

ye

2021-02-20 12:37 UTC, TiviPlus requested changes

2021-02-20 12:37 UTC, TiviPlus commented on code/modules/admin/admin_verbs.dm
> +				html = msg,)
trailing comma

2021-02-20 15:37 UTC, TiviPlus commented on code/modules/admin/admin_verbs.dm
> +				html = msg,)
```suggestion
				html = msg)
```

2021-02-21 18:53 UTC, TiviPlus approved these changes

2021-02-21 18:53 UTC, merged