Guns Rattle When Low Ammo
tgstation/TerraGov-Marine-Corps pull request #6096
Opened 2021-02-19 03:48 UTC by XSlayer300

## About The Pull Request
As per title.

## Why It's Good For The Game
WIP

## Changelog
:cl:
tweak: Weapons have a rattling sound when fired at 25% ammo left.
/:cl:

2021-02-19 03:48 UTC, tgstation-server commented
You currently have a negative Fix/Feature pull request delta of -36. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

2021-02-19 03:59 UTC, SplinterGP commented on code/modules/projectiles/gun_system.dm
> +	return 1
```suggestion
	if(flags_gun_features & GUN_SILENCED)
		playsound(user, fire_sound, 25, TRUE, frequency = firing_sndfreq)
		return
    if(fire_rattle)
		playsound(user, fire_rattle, 60, FALSE)
		return
	playsound(user, fire_sound, 60, firing_sndfreq ? TRUE : FALSE, frequency = firing_sndfreq)
	return
```

2021-02-19 04:29 UTC, XSlayer300 commented
Okay, this should be stable.

2021-02-20 03:56 UTC, SplinterGP commented
code of mine tibi, rebiew pls

2021-02-20 12:40 UTC, TiviPlus requested changes
Is this not used anywhere?

2021-02-20 12:40 UTC, TiviPlus commented on code/modules/projectiles/gun_system.dm
> +	var/fire_rattle		= null //Does our gun have a unique empty mag sound? If so use instead of pitch shifting.
Autodoc

2021-02-23 16:26 UTC, SplinterGP commented
it has to be on line above

2021-02-23 16:26 UTC, SplinterGP requested changes

2021-02-23 16:26 UTC, SplinterGP commented on code/modules/projectiles/gun_system.dm
> +	var/fire_rattle		= null ///Does our gun have a unique empty mag sound? If so use instead of pitch shifting.
```suggestion
	///Does our gun have a unique empty mag sound? If so use instead of pitch shifting.
	var/fire_rattle		= null
```

2021-03-01 01:22 UTC, SplinterGP approved these changes

2021-03-02 20:37 UTC, SplinterGP requested changes

2021-03-02 20:37 UTC, SplinterGP commented on code/modules/projectiles/gun_system.dm
> +	return
no need to return in end of proc
```suggestion

```

2021-03-05 01:10 UTC, SplinterGP approved these changes

2021-03-05 20:27 UTC, TiviPlus approved these changes

2021-03-05 20:27 UTC, merged