AI can use fob drone, no more mats limit for it
tgstation/TerraGov-Marine-Corps pull request #6113
Opened 2021-02-19 13:50 UTC by BraveMole

## About The Pull Request

Remove the check making AI unable to use fob drone. The fob drone starts with already full mats, and has no longer any limits in mats. Mats are auto ejected when alamo leaves

## Why It's Good For The Game

QOL additions

## Changelog
:cl:
tweak: AI can use fob drone
tweak: Fob drone is prefilled with mats, no longer any maximum mats you can get
tweak: Mats are automaticly ejected when alamo leaves
/:cl:

2021-02-19 13:51 UTC, tgstation-server commented
You currently have a negative Fix/Feature pull request delta of -49. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

2021-03-04 13:40 UTC, TiviPlus requested changes

2021-03-04 13:40 UTC, TiviPlus commented on code/modules/mining/remote_fob/remote_fob_computer.dm
>  	if(machine_stat & (NOPOWER|BROKEN))
this should not be a seperate proc

2021-03-05 20:36 UTC, TiviPlus approved these changes

2021-03-05 20:37 UTC, TiviPlus commented
tweak: doesnt exist anymore

2021-03-07 05:03 UTC, merged