you can restock hypo clicking on pill bottles
tgstation/TerraGov-Marine-Corps pull request #6169
Opened 2021-02-24 22:21 UTC by fernandos13

you can restock hypo clicking on pill bottles

when you click in a pill bottle with a hypo that have ENOUGH SPACE for its contents (aka 15u free for a 15u pill. or 10u for a 10u pill)

it will use up one of the pills inside the bottle to automatically dissolve inside the hypo
## About The Pull Request

## Why It's Good For The Game
QoL for hypos

## Changelog
:cl:
qol: you can restock hypos by clicking on the pill bottle
/:cl:

2021-02-24 22:36 UTC, David-Stormwell commented
Saves a few clicks, doesn't really change balance at all.

2021-02-27 22:01 UTC, TiviPlus requested changes

2021-02-27 22:01 UTC, TiviPlus commented on code/game/objects/items/reagent_containers/hypospray.dm
> +			to_chat(user, "<span class='warning'>[src] is full.</span>")
Why not >= or <=

2021-02-27 22:01 UTC, TiviPlus commented on code/game/objects/items/reagent_containers/hypospray.dm
> +		if(!M.contents.len)
why is this casted?

2021-02-27 22:01 UTC, TiviPlus commented on code/game/objects/items/reagent_containers/hypospray.dm
> +
use proper descriptive variable names please

2021-02-28 23:59 UTC, fernandos13 commented on code/game/objects/items/reagent_containers/hypospray.dm
> +		QDEL_IN(V, 5)
to avoid the item being deleted before all of its reagents goes in the hypo

2021-03-01 00:00 UTC, fernandos13 commented on code/game/objects/items/reagent_containers/hypospray.dm
> +			to_chat(user, "<span class='warning'>[src] is full.</span>")
good point why not set at more or equal

2021-03-01 00:00 UTC, fernandos13 commented on code/game/objects/items/reagent_containers/hypospray.dm
> +		if(!M.contents.len)
what you mean casted?

2021-03-02 18:24 UTC, TiviPlus approved these changes

2021-03-02 18:24 UTC, merged