Psych balance tweak
tgstation/TerraGov-Marine-Corps pull request #6194
Opened 2021-02-27 22:20 UTC by BraveMole

## About The Pull Request

Xenos will now have psych points everytime a marine join, whether it be at the start of the game, as a late join, or as a respawn. 
1/15th of a silo (60 psych points) per marine. 

Xenos still have free larva everytime a marine join before shutters open, this is not changing

## Why It's Good For The Game

This deals with the issue of people joining up late, and only chosing marine. This system is more fair for xenos, while still retaining the current philosophy of "no free larva for marine respawn"

## Changelog
:cl:
balance: Xenos get psych points everytime marines spawn (60 psych points, 1/15th of a silo)
/:cl:

2021-02-27 22:20 UTC, tgstation-server commented
You currently have a negative Fix/Feature pull request delta of -5. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

2021-02-27 22:28 UTC, TiviPlus commented
You have exceeded your balance freeze Pr allowance and have been fine 10 social credits

2021-03-04 13:35 UTC, TiviPlus requested changes

2021-03-04 13:35 UTC, TiviPlus commented on code/controllers/subsystem/job.dm
>  	job.occupy_job_positions(1)
Istype src

2021-03-05 21:36 UTC, TiviPlus approved these changes

2021-03-05 21:36 UTC, merged