Balance join update
tgstation/TerraGov-Marine-Corps pull request #6198
Opened 2021-02-28 10:07 UTC by BraveMole

## About The Pull Request

Inbalance join popup will now show up when burrowed larva account for 20% of the xenos alive, and the shutters are still shut or xenos are losing 

## Why It's Good For The Game

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2021-02-28 10:07 UTC, tgstation-server commented
You currently have a negative Fix/Feature pull request delta of -5. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

2021-02-28 22:15 UTC, TiviPlus requested changes

2021-02-28 22:15 UTC, TiviPlus commented on code/modules/mob/new_player/new_player.dm
> +				if((SSmonitor.gamestate == SHUTTERS_CLOSED || (SSmonitor.gamestate == GROUNDSIDE && SSmonitor.current_state == XENOS_LOSING)) && ((xeno_job.total_positions-xeno_job.current_positions) >= GLOB.ali
Magic number

2021-02-28 22:15 UTC, TiviPlus commented on code/modules/mob/new_player/new_player.dm
> +				if((SSmonitor.gamestate == SHUTTERS_CLOSED || (SSmonitor.gamestate == GROUNDSIDE && SSmonitor.current_state == XENOS_LOSING)) && ((xeno_job.total_positions-xeno_job.current_positions) >= GLOB.ali
I would also say that one of these checks would be better suited on the lines above to make this one shorter

2021-03-01 15:12 UTC, TiviPlus approved these changes

2021-03-01 15:12 UTC, merged