Making a pool create a tunnel next to it
tgstation/TerraGov-Marine-Corps pull request #6199
Opened 2021-02-28 13:50 UTC by BraveMole

## About The Pull Request

Creating a pool will create a tunnel north of it, if the tile is empty

## Why It's Good For The Game

Makes xenos able to quickly defend pool even if their is not hivelord in their rank. Maybe will allow xenos to spread the pool, which can be a good counter to big unga balls since losing one pool is not the end of the world

## Changelog
:cl:
add: Spawning a new silo will generate a tunnel north of it automaticly 
/:cl:

2021-02-28 13:50 UTC, tgstation-server commented
You currently have a negative Fix/Feature pull request delta of -5. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

2021-02-28 21:35 UTC, Chaznoodles commented
Buffs pools, despite them being near-universally disliked.

2021-02-28 22:07 UTC, BraveMole commented
> Buffs pools, despite them being near-universally disliked. There is absolutely no need for this to be a thing - instead of changing the game around said near-universally disliked addition, address the actual problem in that pools just aren't fun.

You're late, this PR was published 8 hours ago. 
You forgot to dislike this :https://github.com/tgstation/TerraGov-Marine-Corps/pull/6138
and this :https://github.com/tgstation/TerraGov-Marine-Corps/pull/5969

2021-02-28 22:47 UTC, Chaznoodles commented
> > Buffs pools, despite them being near-universally disliked. There is absolutely no need for this to be a thing - instead of changing the game around said near-universally disliked addition, address the actual problem in that pools just aren't fun.
> 
> You're late, this PR was published 8 hours ago.
> You forgot to dislike this :#6138
> and this :#5969

That's not a defence, that's just snark.

2021-03-01 02:31 UTC, usnpeepoo commented
this would actually be extremely helpful for latejoin xenos, since the only way to defend this static object is through cancerwalling, and unless there's a hivelord who knows how to make tunnels any larva that spawns on that pool is basically fucked until they evo and remove all the walls (and hopefully places it back who knows).

2021-03-01 03:45 UTC, TGCMbetcher commented
Can we kill tunnels again? I banged on one for a few minutes the other day and couldnt do it. If we could target the tunnel first fine, but we can already throw an incind and kill it instantly so whats the point. Going to make them fire immune?

2021-03-01 09:01 UTC, Surrealaser commented
Good change; probably because I suggested it, lol

2021-03-09 17:26 UTC, SplinterGP requested changes

2021-03-09 21:15 UTC, SplinterGP approved these changes

2021-03-11 20:17 UTC, TiviPlus approved these changes

2021-03-11 20:17 UTC, merged