Cleans some TGUI interfaces code, adds typescript settings for tgui on vscode and fixes ESLint
tgstation/TerraGov-Marine-Corps pull request #6217
Opened 2021-03-01 22:47 UTC by SplinterGP

## About The Pull Request
due to a oof on tgstation gitignore, the lib files and stuff was ignored (https://github.com/tgstation/tgstation/pull/57326), this fixes that and also cleans some UI's that had some stuff that aint proper anymore (which caused the UI's to die)

import { LabeledListItem } from '../components/LabeledList'; in example

## Why It's Good For The Game
ESLint now works properly on tgui and we got typescript actually working and fixed all UI's dying.

2021-03-01 22:55 UTC, SplinterGP commented
unTM https://github.com/tgstation/TerraGov-Marine-Corps/pull/6206 on merging

2021-03-02 09:53 UTC, TiviPlus requested changes

2021-03-02 09:53 UTC, TiviPlus commented on .vscode/settings.json
> +}
```suggestion
	"tgstationTestExplorer.project.resultsType": "json"
	"tgstationTestExplorer.project.DMEName": "tgmc.dme"
}
```

2021-03-02 18:22 UTC, TiviPlus approved these changes

2021-03-02 18:28 UTC, merged