Allows Pasvest and Marine Harness to be recolored.
tgstation/TerraGov-Marine-Corps pull request #6248
Opened 2021-03-05 23:32 UTC by hyper2snyper

## About The Pull Request

Allows Pas-11 Vest and Marine Harness to be recolored using Facepaint. This replaces the Map Based coloring for the armor pieces.

## Why It's Good For The Game

More cosmetic choices are always good.

## Changelog
:cl:
add: Allows Pas-11 Vest and Marine Harness to be recolored using facepaint like the Jaeger armor pieces.
/:cl:

2021-03-05 23:33 UTC, hyper2snyper commented
why did it ask for a review?

2021-03-05 23:53 UTC, SkeletalElite commented
> why did it ask for a review?

because bimmer is a code owner for icons, you touch icons, it automatically requests review from him

2021-03-06 00:01 UTC, hyper2snyper commented
> > why did it ask for a review?
> 
> because bimmer is a code owner for icons, you touch icons, it automatically requests review from him

ah thanks, didnt know that.

2021-03-06 00:20 UTC, revelation-8468 commented
yes please

2021-03-06 00:23 UTC, hyper2snyper commented
> yes please

definitely, now i dont have to wait for ice colony to do my cool medic outfit

2021-03-06 09:20 UTC, Sulaboy commented
Looking at the code does this remove map variants from their original vending? Like will every map vend the same color armor for pas vests, or will they still bend as map specific?

2021-03-06 09:23 UTC, Sulaboy reviewed
`	-	/obj/item/weapon/twohanded, `
Line 34 marine_armor.do.

I think you snipped out it fitting two handed melees.

2021-03-06 17:45 UTC, hyper2snyper commented
> Looking at the code does this remove map variants from their original vending? Like will every map vend the same color armor for pas vests, or will they still bend as map specific?

When they vend, they will be their standard variant. If someone wants to change its color they would just have to use the facepaint.

2021-03-06 17:47 UTC, hyper2snyper commented
> ` - /obj/item/weapon/twohanded, `
> Line 34 marine_armor.do.
> 
> I think you snipped out it fitting two handed melees.

I dont remember doing any of those, in any case, they shouldnt be removed so ill fix it.

2021-03-07 09:06 UTC, Sulaboy commented
Would it be possible to default it to black?

2021-03-07 20:28 UTC, SplinterGP requested changes
this needs to have copypasta reduced, it's all the same code for all the procs, possibly made an element

2021-03-08 00:11 UTC, hyper2snyper commented
> Would it be possible to default it to black?

I don't see why that would be a problem. Black does look better.

2021-03-08 00:13 UTC, hyper2snyper commented
> this needs to have copypasta reduced, it's all the same code for all the procs, possibly made an element

Do you mean to make it only a single proc to color all three?

2021-03-08 15:51 UTC, SplinterGP commented
> 
> 
> > this needs to have copypasta reduced, it's all the same code for all the procs, possibly made an element
> 
> Do you mean to make it only a single proc to color all three?

Yep, as explained in discord elements can also be used

2021-03-08 18:38 UTC, TheBimmer231 approved these changes

2021-03-09 17:52 UTC, SplinterGP commented
> 
> 
> So I created an element to handle color variants with the help of splinter (thanks much splinter)
> 
> Some testing found that the coloring code is being overwritten or something, so it doesn't work. (Not yet at least)
> 
> I'm considering making the element check for compatibility by looking at the colors list in each object and activating only if the list isn't null, that would allow me to initialize all the armors or whatnot with the element and just fill out the color list of the ones that have variants. (Was an idea I had, it might not work)
> 
> I'll do the autodoc and comments and such once the code actually works.
i'll talk about this later with ya

2021-03-14 19:27 UTC, SplinterGP requested changes

2021-03-14 19:27 UTC, SplinterGP commented on code/datums/elements/coloring.dm
> +/datum/element/color/proc/attackby(obj/source, obj/item/attacked_by, mob/attacker, var/colors, params)
```suggestion
/datum/element/color/proc/attackby(obj/source, obj/item/facepaint/paint, mob/attacker, var/colors, params) 
```

2021-03-14 19:27 UTC, SplinterGP commented on code/datums/elements/coloring.dm
> +	var/obj/item/facepaint/paint = attacked_by
```suggestion
```

2021-03-14 19:27 UTC, SplinterGP commented on code/game/objects/objs.dm
> +	///Variable for colors to be used if the object is given the capability to be recolored using facepaint.
```suggestion
	///lazylist with colors to be used if the object is given the capability to be recolored using the recoloring element.
```

2021-03-14 19:27 UTC, SplinterGP commented on code/game/objects/objs.dm
> +	var/color_list = null
```suggestion
	var/color_list
```

2021-03-14 19:27 UTC, SplinterGP commented on code/datums/elements/coloring.dm
> +	source.icon_state = "[default_icon]_[new_color]"
```suggestion
	source.icon_state = "[initial(source.icon_state)]_[new_color]"
```

2021-03-29 00:35 UTC, closed without merging

2021-03-29 03:02 UTC, Guidesu commented
noooooooooooooooo!!