Make it so requisition can spend some of their money into vouchers for dropships.
tgstation/TerraGov-Marine-Corps pull request #6263
Opened 2021-03-07 02:51 UTC by lbnesquik

## About The Pull Request
It just adds a little consumable card that you can swipe over the dropship to get points. 
You can buy OB's, why not get CAS some points ? 

## Why It's Good For The Game
More flexibility & some love for CAS

## Changelog
:cl:
add: Added a dropship points voucher to req under OPERATIONS. 
/:cl:

2021-03-07 05:20 UTC, SkeletalElite commented
These are a little expensive. Would cost 120 points to get a rocket like the keeper or even more for a fatty/napalm compared to extra OB prices it's pretty ridiculous for an explosive signficantly smallter. I would reccomend reducing the price a bit.

2021-03-07 13:50 UTC, Moggram commented on code/modules/reqs/supplypacks.dm
> +/datum/supply_packs/operations/ob_fuel
```suggestion
/datum/supply_packs/operations/cas_voucher

```

2021-03-07 18:42 UTC, lbnesquik commented
> 
> 
> These are a little expensive. Would cost 120 points to get a rocket like the keeper or even more for a fatty/napalm compared to extra OB prices it's pretty ridiculous for an explosive signficantly smallter. I would reccomend reducing the price a bit.
> 
> edit: If it helps you decide, the base generation rate of req points is 2/minutes while dropship points is 18/minute, but conversion probably shouldn't be 1:1 it should be a little ineffecient but 1:2.5 is nowhere near the base 1:9 value. I'd reccomend maybe every req point being worth maybe 5 dropship points to start with.

Well how about doubling the amount of dosh to 200 ?

2021-03-08 02:24 UTC, Swagile commented
Problem I see here is that this enhances FOB camping a lot more, especially orbit 1 gaus runs (for reference, CAS GAU fires in 1 second after you see the dot on orbit 1). Hence farming a miner or two and giving points to a good CAS pilot means its nearly impossible to siege outside of sitting in caves 24/7 as xenos and hope marines push out. This is especially bad on maps like LV and Ice Colony where there are few cave spots near the main LZ's and the FOB miners.

2021-03-08 16:35 UTC, lbnesquik commented
Maybe. I guess it would be best to leave this open and see if the issue remains after we use the other PR

2021-03-10 21:34 UTC, BraveMole requested changes

2021-03-10 21:34 UTC, BraveMole commented on code/game/objects/items/misc.dm
> +	var/extra_points = 100
new vars need to be autodoc

2021-03-10 21:34 UTC, BraveMole commented on code/game/objects/items/misc.dm
> +	to_chat(user, "It contains [extra_points] points.")
Missing span class

2021-03-11 19:01 UTC, lbnesquik commented on code/game/objects/items/misc.dm
> +	var/extra_points = 100
I don't know what autodoc is

2021-03-11 19:01 UTC, lbnesquik commented on code/game/objects/items/misc.dm
> +	to_chat(user, "It contains [extra_points] points.")
Also clueless

2021-03-11 19:03 UTC, TiviPlus commented on code/game/objects/items/misc.dm
> +	to_chat(user, "It contains [extra_points] points.")
Examine should not have span slasses

2021-03-11 19:04 UTC, TiviPlus requested changes

2021-03-11 19:04 UTC, TiviPlus commented on code/game/objects/items/misc.dm
> +	..()
```suggestion
/obj/item/dropship_points_voucher/examine(mob/user)
	. = ..()
```

2021-03-11 19:04 UTC, TiviPlus commented on code/game/objects/machinery/dropship_part_fabricator.dm
> +		qdel(H)
```suggestion
	if(!istype(H, /obj/item/dropship_points_voucher))
		return
	to_chat(user, "<span class='notice'>You add 100 dropship points to \the [src].</span>")
	SSpoints.dropship_points += 100
	qdel(H)
```

2021-03-11 19:04 UTC, TiviPlus commented on code/modules/reqs/supplypacks.dm
> +	contains = list(/obj/item/dropship_points_voucher)
```suggestion
/datum/supply_packs/operations/cas_voucher
	name = "100 dropship fabricator points"
	contains = list(/obj/item/dropship_points_voucher)
```

2021-03-11 19:39 UTC, lbnesquik commented
Everything should be good now.

2021-03-11 20:10 UTC, TiviPlus approved these changes

2021-03-11 20:10 UTC, TiviPlus commented on code/game/objects/items/misc.dm
> +	icon_state = "centcom"
```suggestion
	icon = 'icons/obj/items/card.dmi'
	icon_state = "centcom"
	///This is the number of points this thing has to give. 
	var/extra_points = 100
```

2021-03-11 20:13 UTC, TiviPlus approved these changes

2021-03-11 20:14 UTC, merged