ROF Compensation Buffs to the GPMG and LMG
tgstation/TerraGov-Marine-Corps pull request #6289
Opened 2021-03-09 03:03 UTC by Kuro-ai

## About The Pull Request

GPMG now fires faster and LMG has a 10% damage bonus.

## Why It's Good For The Game

Fire rate only works in incrementals of 0.05 which means guns like the GPMG (0.165 rof) and LMG (0.180 rof) actually end up with a rof of 0.2 which is the same as the assault rifle,meaning that they are much weaker than what they were supposed to be,I'm compensating that by making the GPMG have 0.15 firerate (same as p90) and making the LMG have a damage bonus of 10%,it's not perfect but IDK if that problem will ever be fixed so letting these guns have worse performance than they should in the meantime doesn't sit well with me.

## Changelog
:cl:
balance:Buffed GPMG fire rate and LMG damage.
/:cl:

2021-03-09 03:09 UTC, bobmancer343 commented
cadehugger mf

2021-03-09 03:24 UTC, Kuro-ai commented
> cadehugger mf

Pools exist so marines cade hugging just makes them lose so lol

2021-03-09 03:27 UTC, usnpeepoo commented
this just make fob sieges absolute hell to deal with. and even more with a line of gpmg/lmg cadehuggers. even with pools, it's going to be extremely unfun to deal with as a xeno sieging the fob.

2021-03-10 02:44 UTC, SplinterGP commented
put on changelog the reason please

2021-03-10 02:46 UTC, SplinterGP requested changes
in exchange for the gpmg one, increase its falloff multiplier, getting hit by GPMG bullet spam  from very far away offscreen and also being a considerable damage is awfull, so you can nerf that to compensate a bit the buff.

2021-03-10 04:05 UTC, davidchan13 commented
GPMG I can understand but LMG doesn't need a buff. The thing is already assault rifle plus.

2021-03-10 14:56 UTC, SplinterGP commented
> GPMG I can understand but LMG doesn't need a buff. The thing is already assault rifle plus.

Its a compensation for something we found out(rof gets rounded to the closest highest 0.05 seconds multiple

2021-03-10 17:27 UTC, BraveMole commented
" that they are much weaker than what they were supposed to be"

What they are supposed to be is irrelevant. The t42 is already a really solid gun, there is abolutly no need for a buff.

Saying it should have been stronger 9 months ago, is not an interesting variable today.

If you want to buff t42, say why. I for myself see no reason to ever buff this gun, it's already strong as hell.

And GPMG is the cade huggin weapon by excellence, even if it's weak right now i don't really want it to be buffed

2021-03-10 17:43 UTC, SplinterGP commented
> 
> 
> " that they are much weaker than what they were supposed to be"
> 
> What they are supposed to be is irrelevant. The t42 is already a really solid gun, there is abolutly no need for a buff.
> 
> Saying it should have been stronger 9 months ago, is not an interesting variable today.
> 
> If you want to buff t42, say why. I for myself see no reason to ever buff this gun, it's already strong as hell.
> 
> And GPMG is the cade huggin weapon by excellence, even if it's weak right now i don't really want it to be buffed

all mostly because they need to be up to standards and their intended values, math and stuff has been calculated on those ones in comparison to their downsides, and as the GPMG being a cade huggy weapon this is not gonna buff it that much because you'll get more falloff as well, meaning you need to go forward to do more damage.

2021-03-10 17:55 UTC, BraveMole commented
> > " that they are much weaker than what they were supposed to be"
> > What they are supposed to be is irrelevant. The t42 is already a really solid gun, there is abolutly no need for a buff.
> > Saying it should have been stronger 9 months ago, is not an interesting variable today.
> > If you want to buff t42, say why. I for myself see no reason to ever buff this gun, it's already strong as hell.
> > And GPMG is the cade huggin weapon by excellence, even if it's weak right now i don't really want it to be buffed
> 
> all mostly because they need to be up to standards and their intended values, math and stuff has been calculated on those ones in comparison to their downsides, and as the GPMG being a cade huggy weapon this is not gonna buff it that much because you'll get more falloff as well, meaning you need to go forward to do more damage.

Ok, show me the math then?

2021-03-10 18:36 UTC, Kuro-ai commented
Changed the LMG buff from 10% bonus damage to allowing it to use more attachments.

2021-03-10 18:56 UTC, SplinterGP approved these changes

2021-03-10 19:00 UTC, merged