Ice Colony Storage Unit Control buttons removal
tgstation/TerraGov-Marine-Corps pull request #6292
Opened 2021-03-09 13:49 UTC by mrhugo13

## About The Pull Request
Simply removes these 3 buttons on ice colony's LZ1
![firefox_2021-03-09_14-44-06](https://user-images.githubusercontent.com/17747087/110479917-3120d200-80e6-11eb-96f0-933b8858edd4.png)

## Why It's Good For The Game
![Discord_2021-03-09_14-42-55](https://user-images.githubusercontent.com/17747087/110479930-341bc280-80e6-11eb-9752-7b95e93997bb.png)

Basically the buttons had ID set to null, and the transit shutters on the alamo also had the ID set to null, therefor the buttons could open/close the transit shutters on the alamo which can be a bit of a problem if, per say, a xeno were not to be able to enter a hijacked alamo because the transit shutters were activated and they couldn't get on it.

~~kindadread owes me a crash token or two for this favor~~
## Changelog
:cl: Vondiech
fix: Removed 3 storage unit control buttons on ice colony's LZ1 that used to be able to close the transit shutters on the alamo.
/:cl:

2021-03-09 17:30 UTC, SplinterGP commented
please change the alamo shutters ID, this is possible to happen again

2021-03-19 18:13 UTC, SplinterGP approved these changes

2021-03-19 18:14 UTC, SplinterGP requested changes
buttons are fluff and there are other buttons around map which also have null, need to change alamo shutter ID

2021-03-22 12:31 UTC, TiviPlus commented
@mrhugo13 ?

2021-03-22 13:01 UTC, mrhugo13 commented
There, my bad for procrastinating on this for so long.

2021-03-22 13:04 UTC, TiviPlus approved these changes

2021-03-22 13:04 UTC, merged