Droids can now use guns
tgstation/TerraGov-Marine-Corps pull request #6293
Opened 2021-03-09 17:53 UTC by TiviPlus

## About The Pull Request

guns
also fixed incorrect ammo datum usage
## Changelog
:cl:
add: Droids can now use guns
/:cl:

2021-03-09 18:23 UTC, TiviPlus commented
![Uploading image.png…]()

2021-03-10 00:26 UTC, XSlayer300 commented on code/modules/vehicles/unmanned/unmanned_vehicle.dm
> +		to_chat(user, "<span class='notice'>Theres already something attached!</span>")
```suggestion
		to_chat(user, "<span class='notice'>There's already something attached!</span>")
```

2021-03-13 12:02 UTC, BraveMole requested changes

2021-03-13 12:02 UTC, BraveMole commented on code/modules/vehicles/unmanned/unmanned_turrets.dm
> +	var/turret_pattern = PATTERN_TRACKED
autodoc :)

2021-03-19 18:48 UTC, SplinterGP approved these changes

2021-03-19 18:49 UTC, merged