Agrip now has an actual negative
tgstation/TerraGov-Marine-Corps pull request #6307
Opened 2021-03-10 19:08 UTC by Kuro-ai

## About The Pull Request

Agrip adds 5 scatter to your gun

## Why It's Good For The Game

Funny agrip man reduces wield timers for... unwielded scatter? that's not even a real negative, now it adds a bit of scatter to the gun.

## Changelog
:cl:
balance:agrip now adds scatter.
/:cl:

2021-03-10 20:33 UTC, Kuro-ai commented
> muh shotgun mains

shotgun mains aren't human,don't feel bad

2021-03-10 21:50 UTC, TiviPlus requested changes
Fix CL

2021-03-10 23:21 UTC, fernandos13 commented
MUH T35.... MUH T64
hell.. please muh T42 no .. no sactter no more

2021-03-10 23:38 UTC, Kuro-ai commented
> Fix CL

fixed

2021-03-11 04:40 UTC, davidchan13 commented
I'd agree with it reducing melee damage (and thus PB damage) but increasing scatter from a grip seems... wrong.

2021-03-11 07:12 UTC, GUDmood commented
A lot of attachments don't have negative at all.
A grip isn't the best one around, why nerfing it?

2021-03-11 18:45 UTC, merged