Engies build faster
tgstation/TerraGov-Marine-Corps pull request #6318
Opened 2021-03-11 13:52 UTC by BraveMole

## About The Pull Request

Boost engie construction time 

## Why It's Good For The Game

Less cadehugging, more combat engies. Maybe?

## Changelog
:cl:
balance: Engies build faster
/:cl:

2021-03-11 13:53 UTC, BraveMole commented on code/game/objects/items/stacks/stack.dm
> +			building_time -= R.time * ( usr.skills.getRating("construction") - R.skill_req ) * 0.3 // -10% time each extra skill point
```suggestion
			building_time -= R.time * ( usr.skills.getRating("construction") - R.skill_req ) * 0.3 // -30% time each extra skill point
```

2021-03-11 15:00 UTC, Swagile commented
nvm the one thing i thought needed fixing got fixed an hour ago

still won't fix engis sucking but this is a step in the right place at least

2021-03-11 18:35 UTC, TiviPlus requested changes

2021-03-11 18:35 UTC, TiviPlus commented on code/__DEFINES/skills.dm
> +#define SKILL_ENGINEER_ENGI 	3.5	//hacking&&planet engine fixing&&apc building (combat engi)
```suggestion
#define SKILL_ENGINEER_ENGI 	3	//hacking&&planet engine fixing&&apc building (combat engi)
```
keep these integers

2021-03-13 16:00 UTC, TiviPlus approved these changes

2021-03-13 16:00 UTC, merged