Queue system to spawn as larva
tgstation/TerraGov-Marine-Corps pull request #6335
Opened 2021-03-13 14:32 UTC by BraveMole

## About The Pull Request

If there is no burrowed larva when you try to respawn as a xenos, you'll get placed in a queue and you'll get priority when a larva spot is added

## Why It's Good For The Game

More fair than "the first to click get the larva"

## Changelog
:cl:
qol: Queue system to respawn as a xeno
/:cl:

2021-03-13 14:35 UTC, BraveMole commented on code/modules/mob/living/carbon/xenomorph/hive_datum.dm
> +			INVOKE_ASYNC(src, .proc/give_larva_next_in_queue)
If you are asking why async, i don't know

2021-03-13 16:22 UTC, TiviPlus requested changes

2021-03-13 16:22 UTC, TiviPlus commented on code/modules/mob/dead/observer/observer.dm
> +	var/larva_position
Is this a bool? an integer? Whats the default?

2021-03-13 16:22 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/hive_datum.dm
> +	candidate += observer
Lacking return

2021-03-13 16:22 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/hive_datum.dm
> +	while(stored_larva >= 1 && candidate.len)
```suggestion
	while(stored_larva > 0 && candidate.len)
```
clarity

2021-03-13 16:22 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/hive_datum.dm
> +	set waitfor = FALSE
Bad

2021-03-13 16:22 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/hive_datum.dm
> +		give_larva_to_next_in_queue()
Early return

2021-03-13 16:22 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/hive_datum.dm
> +	var/list/mob/dead/observer/candidate = list()
Why isnt this a lazylist

2021-03-13 19:25 UTC, BraveMole commented on code/modules/mob/living/carbon/xenomorph/hive_datum.dm
> +		observer_in_queue =LAZYACCESS(candidate, i)
```suggestion
		observer_in_queue = LAZYACCESS(candidate, i)
```

2021-03-14 19:24 UTC, Swagile commented
hello?

based department?

2021-03-15 01:50 UTC, Smudged commented
Ah, waiting in the Pool DMV, good times. 

Good change.

2021-03-16 05:38 UTC, davidchan13 commented
I definitely like this.

Is there anyway to weight this so every death as a xeno in the round sets you as a lower priority? 
I.E. someone who observed or died as marine wants to play xeno, they put higher on the list than say someone who has died 3+ times already in the same round?

2021-03-18 17:26 UTC, BraveMole commented
> I definitely like this.
> 
> Is there anyway to weight this so every death as a xeno in the round sets you as a lower priority?
> I.E. someone who observed or died as marine wants to play xeno, they put higher on the list than say someone who has died 3+ times already in the same round?

Looks like a good idea. Definitly not in the scope of this PR, but i might do it later

2021-03-19 18:58 UTC, TiviPlus approved these changes

2021-03-19 18:58 UTC, merged

2021-03-24 18:38 UTC, MiniMeatwad commented
Joined queue with 0 burrowed larva and no pools, position 1. Later, 1 burrowed larva appears, and I try to join again, says "You are already in queue!". Someone else gets the larva from the hive leader calling burrowed. I try again and it puts me in position 2. I also prefer the old system, since you can control when you become a xenomorph and wont randomly spawn on a silo under attack unexpectedly, and you have to be immediately available in order to become a xenomorph.

2021-03-24 20:33 UTC, BraveMole commented
> Joined queue with 0 burrowed larva and no pools, position 1. Later, 1 burrowed larva appears, and I try to join again, says "You are already in queue!". Someone else gets the larva from the hive leader calling burrowed. I try again and it puts me in position 2. I also prefer the old system, since you can control when you become a xenomorph and wont randomly spawn on a silo under attack unexpectedly, and you have to be immediately available in order to become a xenomorph.

Yeah there's a lot of broken thing in the system right now

2021-03-24 20:50 UTC, MiniMeatwad commented
Nevermind, thought that was how it worked since I saw a larva spawn afk and die.