Sandbags are no longer bulky, can hold in construction pouch and be build faster by engies
tgstation/TerraGov-Marine-Corps pull request #6336
Opened 2021-03-13 16:28 UTC by BraveMole

## About The Pull Request

Title

## Why It's Good For The Game

Sandbags are absolutly not convenient to use, this fixes it. Real combat engie one day?

## Changelog
:cl:
balance: Sandbags are no longer bulky, can hold in construction pouch and be build faster by engies
/:cl:

2021-03-13 16:29 UTC, Pariah919 commented
make sandbags bulky and make construction pouch bypass teh sandbag w class

2021-03-14 18:53 UTC, SplinterGP requested changes

2021-03-14 18:53 UTC, SplinterGP commented on code/game/objects/items/stacks/sandbags.dm
> +	var/building_time = 2 SECONDS *(1 - clamp(usr.skills.getRating("construction") * 0.10, 0 , 0.50))
```suggestion
	var/building_time = 2 SECONDS *(1 - clamp(user.skills.getRating("construction") * 0.10, 0 , 0.50))
```

2021-03-14 19:23 UTC, Swagile commented
> 
> 
> make sandbags bulky and make construction pouch bypass teh sandbag w class

this invalidates jaeger engi storage tho

engis already have storage issues that require jaeger engi storage if you actually play the class as intended (and not as a plasma cutter spammer)

2021-03-15 14:26 UTC, Chaznoodles commented
Fun fact, you can already put filled sandbags in the jaeger engineering storage module 👀

2021-03-15 22:05 UTC, SplinterGP requested changes

2021-03-15 22:05 UTC, SplinterGP commented on code/game/objects/items/stacks/sandbags.dm
> +	var/building_time = 2 SECONDS *(1 - clamp(user.skills.getRating("construction") * 0.10, 0 , 0.50))
use LERP here and replace fastest speed with low as can go and maximumskill with the point it reaches the maximum speed
```suggestion
	var/building_time = LERP(2 SECONDS, fastestspeed, user.skills.getPercent("construction", maximumskill)
```

2021-03-17 22:47 UTC, TiviPlus approved these changes

2021-03-17 22:47 UTC, merged