Adds 1 Synths job slot every 40 pop
tgstation/TerraGov-Marine-Corps pull request #6352
Opened 2021-03-14 14:42 UTC by lbnesquik

## About The Pull Request
This is a revive of https://github.com/tgstation/TerraGov-Marine-Corps/pull/6333

## Why It's Good For The Game
"As we are constantly moving towards high pop, I believe synthetics getting more slot every 40 pop makes sense as generally there is a lack of command. Synthetics can do most shipside job, and as the pop increases, it generally gets difficult to manage shipside. Addition of a support role of Synthetic will ensure this.

I may change the pop number upon testing and feedback. This needs testing."

## Changelog
:cl:
balance: Gives 1 Synth job slot every 40 pop.
/:cl:

2021-03-14 14:50 UTC, BraveMole requested changes

2021-03-14 14:50 UTC, BraveMole commented on code/datums/jobs/job/shipside.dm
> +		/datum/job/terragov/squad/smartgunner = SMARTIE_POINTS_REGULAR,)
```suggestion
		/datum/job/terragov/squad/smartgunner = SMARTIE_POINTS_REGULAR,
	)
```

2021-03-14 15:22 UTC, SpaceLoveSs13 commented
Thanks for getting my PR revived. Like the reason is mentioned above, this pr is good.

2021-03-16 14:19 UTC, fernandos13 commented
FINALLY THANKS!!!

2021-03-16 21:04 UTC, Losenis commented
MERGE WHEN

2021-03-17 21:38 UTC, Pariah919 commented
DELETE SYNTH

2021-03-17 22:52 UTC, TiviPlus commented
Go home MJP
Is this tested?

2021-03-18 02:42 UTC, SpaceLoveSs13 commented
> Go home MJP
> Is this tested?

Maybe TM it during a highpop round(80)

2021-03-18 12:54 UTC, lbnesquik commented
@TiviPlus I have no clue how to test this, but it was apparently working and git was the only issue.

2021-03-18 14:53 UTC, BraveMole commented
> @TiviPlus I have no clue how to test this, but it was apparently working and git was the only issue.

?? lower the number of points severly, and join the game to check if the job is really opened

2021-03-20 13:39 UTC, SpaceLoveSs13 commented
> 
> 
> @TiviPlus I have no clue how to test this, but it was apparently working and git was the only issue.

Tested the PR for you in local with 1 job point need. Code works fine. 
![Screenshot_5](https://user-images.githubusercontent.com/68121607/111871383-b8f0c100-89af-11eb-9c4c-346c941bfb5f.jpg)

2021-03-20 20:48 UTC, TiviPlus approved these changes

2021-03-20 20:48 UTC, merged

2021-03-20 23:17 UTC, Naaanii commented
More than one synth isn't needed.