Xenos have the choice to build less efficient silos
tgstation/TerraGov-Marine-Corps pull request #6408
Opened 2021-03-22 15:53 UTC by BraveMole

## About The Pull Request

Xenos can build small silo, which are only 600 points but produce half as much larva and have half as much HP.

## Why It's Good For The Game

This is to catter with low pop games, where xenos have a lot of issues to make more than one silo. Having only one target to defend is hard, and you can't afford to lose one pool. With this, xenos have the option to make more pools, at the price of having more place to defend at once

## Changelog
:cl:
add: Xenos can build small pools. Half the price for half the HP and half the larva output. Click on build xenos ability to switch silo type
/:cl:

2021-03-30 13:13 UTC, TiviPlus requested changes

2021-03-30 13:13 UTC, TiviPlus commented on code/controllers/subsystem/silo.dm
> +
```suggestion

```

2021-03-30 13:13 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/abilities.dm
> +	. = ..()
```suggestion
	return ..()
```

2021-03-30 13:13 UTC, TiviPlus commented on code/modules/xenomorph/xeno_structures.dm
> +	var/larva_spawn_rate = 0.5
Autodoc

2021-03-30 15:45 UTC, TiviPlus commented on code/modules/xenomorph/xeno_structures.dm
> +	desc = "A slimy, oozy resin bed filled"
Filled with what

2021-03-30 16:06 UTC, BraveMole commented on code/modules/xenomorph/xeno_structures.dm
> +	desc = "A slimy, oozy resin bed filled"
tear of marines?

2021-04-02 08:43 UTC, TiviPlus approved these changes

2021-04-02 08:43 UTC, merged