Resin door rebalance
tgstation/TerraGov-Marine-Corps pull request #6409
Opened 2021-03-22 16:02 UTC by BraveMole

## About The Pull Request

Removed the delay when opening a resin door.
Slightly more HP.
No longer stop the fire

## Why It's Good For The Game

Nowaydays, resin doors have two uses:
 - cancer wall to prevent marines from flaming to the silo, which is boring to dig out for marines and boring to do as a xenos
 - Noob trap to kill xenos that are slowed down by the door
 
 This remove the first use, while trying to give it a more interessting use in regular maze or things like that

## Changelog
:cl:
balance: Resin door opens instantly to xenos, more HP, closes automaticly faster, doesn't stop flamer fire.
/:cl:

2021-03-22 16:39 UTC, Glcbitj commented
Why did you almost double the doors HP? That makes them even more of a fucking cancer wall, not just for silo defending but for it's all other uses too.

2021-03-22 16:44 UTC, Chaznoodles commented
Your Pools PR is the cause of the first issue, as xenos are not intended to play defensively due to them primarily being forced on short ambushes or quick engagements, and spamming walls and doors is the only way to stop marines from giving pools the ol' weedwacker. Them being fireproof is the only way to stop marines from wooshing away the only viable defensive planning xenos can do for silos, namely spamming walls and doors.

You are slapping bandaids on symptoms to try and make the forced gameplay loop of rush/lose more palatable, without addressing the underlying cause.

2021-03-22 16:46 UTC, BraveMole commented
> Your Pools PR is the cause of the first issue, as xenos are not intended to play defensively due to them primarily being forced on short ambushes or quick engagements, and spamming walls and doors is the only way to stop marines from giving pools the ol' weedwacker. Them being fireproof is the only way to stop marines from wooshing away the only viable defensive planning xenos can do for silos, namely spamming walls and doors.
> 
> You are slapping bandaids on symptoms to try and make the forced gameplay loop of rush/lose more palatable, without addressing the underlying cause.

I've seen your cancer wall yesterday, and the one today too. You're almost the last one to do that kind of shit maze, the other xenos builder have adapted and have much more usefull maze, that doesn't lead to xenos defeat.

"the only viable defensive planning xenos can do for silos, namely spamming walls and doors." You're just a shit maze builder, period

2021-03-22 16:46 UTC, BraveMole commented
> > Your Pools PR is the cause of the first issue, as xenos are not intended to play defensively due to them primarily being forced on short ambushes or quick engagements, and spamming walls and doors is the only way to stop marines from giving pools the ol' weedwacker. Them being fireproof is the only way to stop marines from wooshing away the only viable defensive planning xenos can do for silos, namely spamming walls and doors.
> > You are slapping bandaids on symptoms to try and make the forced gameplay loop of rush/lose more palatable, without addressing the underlying cause.
> 
> I've seen your cancer wall yesterday, and the one today too. You're almost the last one to do that kind of shit maze, the other xenos builder have adapted and have much more usefull maze, that doesn't lead to xenos defeat.
> 
> "the only viable defensive planning xenos can do for silos, namely spamming walls and doors." You're just a shit maze builder, period

2021-03-22 17:14 UTC, Chaznoodles commented
> I've seen your cancer wall yesterday, and the one today too. You're almost the last one to do that kind of shit maze, the other xenos builder have adapted and have much more usefull maze, that doesn't lead to xenos defeat.
> 
> "the only viable defensive planning xenos can do for silos, namely spamming walls and doors." You're just a shit maze builder, period. I've seen plenty of different defensive planning, that allows huge clutch from xenos. And if you place smartly one or two turret at corners, you are golden.

So, underneath the attempt to deflect onto me being 'shit', everything I said was correct?

2021-03-22 17:16 UTC, BraveMole commented
> Why did you almost double the doors HP? That makes them even more of a fucking cancer wall, not just for silo defending but for it's all other uses too.

They are still way weaker than resin wall, especially since walls have 50% bullet armor and the door have none

2021-03-22 17:47 UTC, SplinterGP requested changes
only reduce the opening time and change the opening animation accordingly to it, preferably make it not use a sleep too

2021-03-23 15:54 UTC, usnpeepoo commented
removing the only thing xenos have at delaying flamers? i dont like that

2021-03-23 16:06 UTC, BraveMole commented
> So, underneath the attempt to deflect onto me being 'shit', everything I said was correct?

" spamming walls and doors is the only way to stop marines from giving pools the ol' weedwacker. " Spamming doors and wall like you do is a shit strat, it's not even a way to stop marines. Learn to do some real maze, and these use almost no doors.
So no, everything you said was wrong

2021-03-24 13:36 UTC, Glcbitj commented
> > So, underneath the attempt to deflect onto me being 'shit', everything I said was correct?
> 
> " spamming walls and doors is the only way to stop marines from giving pools the ol' weedwacker. " Spamming doors and wall like you do is a shit strat, it's not even a way to stop marines. Learn to do some real maze, and these use almost no doors.
> So no, everything you said was wrong

Ok, who gives a shit if you call your wall+door spam a "maze" or some other thing? "bohoo, you need to make the boring ass spam THIS WAY not THAT WAY" It's still a fucking cancerous way of defending the silo "haha just spam structrures that we can build infinitely and easily replace", even if they didn't block the fucking flamers, marines still need to reach the silo to kill it effectively, because if you can't you're probably losing the battleground and are gonna lose the round anyways.

2021-03-24 16:47 UTC, BraveMole commented
> Ok, who gives a shit if you call your wall+door spam a "maze" or some other thing? "bohoo, you need to make the boring ass spam THIS WAY not THAT WAY" It's still a fucking cancerous way of defending the silo "haha just spam structrures that we can build infinitely and easily replace".
> Even if they didn't block the fucking flamers, marines still need to reach the silo to kill it effectively, because if you can't you're probably losing the battleground and are gonna lose the round anyways.

Lel, maze were always the only defending tools of xenos for ever. And no, i don't spam doors in my maze, cause they are litteraly useless. The PR make them usefull in a way that is not boring

2021-04-02 20:18 UTC, SplinterGP requested changes
you touch code, you improve it, use timers for the sleep and the spawn below it please. on rest its alright then

2021-04-07 20:24 UTC, SplinterGP commented
spawn below, just make it a addtimer for same proc with close delay

![image](https://user-images.githubusercontent.com/29824735/113929171-1f564b80-97c6-11eb-8969-4846a6edf971.png)

2021-04-12 21:31 UTC, SplinterGP requested changes

2021-04-12 21:31 UTC, SplinterGP commented on code/game/objects/structures/xeno.dm
> +	if(!state || !loc ||isSwitchingStates)
```suggestion
	if(!state || !loc || isSwitchingStates)
```

2021-04-14 01:35 UTC, SplinterGP commented
change your CL

2021-04-21 18:15 UTC, BraveMole commented
@SplinterGP

2021-04-22 22:15 UTC, BraveMole commented
I've set the auto close delay to 2 seconds rather than 20, might be awfull to fight against as a marine, we will see

2021-04-23 17:47 UTC, BraveMole commented on code/game/objects/structures/xeno.dm
> +	max_integrity = 150
```suggestion
	max_integrity = 00
```

2021-04-24 20:19 UTC, SplinterGP commented
if this doenst go well just turn doors in what they actually can have some use for, remove autoclosing so you can just use it as a pre-deployed defense you leave open until you need it.

2021-04-25 21:53 UTC, Swagile commented
garbage levels of gameplay due to this PR

nothing but door spam and forced movement into door spam then doors close on you near instantly and your essentially dead forever

if i could down vote 3 times i would

2021-05-09 04:10 UTC, Wayland-Smithy commented
Ship it?

2021-05-09 11:43 UTC, merged