You can corrupt generators by clickint it
tgstation/TerraGov-Marine-Corps pull request #6451
Opened 2021-03-31 16:48 UTC by BraveMole

## About The Pull Request

Remove the corrupt generators ability, you know just have to click on it as a queen or shrike

## Why It's Good For The Game

Less button is good

## Changelog
:cl:
qol: You can corrupt a generator as queen or shrike by clicking on it. Corrupt generators ability is gone
/:cl:

2021-03-31 16:56 UTC, TiviPlus requested changes

2021-03-31 16:56 UTC, TiviPlus commented on code/modules/power/groundmap_geothermal.dm
> +		if(!is_corruptible)
This should be a caste flag

2021-03-31 18:59 UTC, TiviPlus requested changes

2021-03-31 18:59 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
> +	var/can_corrupt_gene = FALSE
caste_flags ??

2021-03-31 19:19 UTC, BraveMole commented on code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
> +	var/can_corrupt_gene = FALSE
aaah, yes, my bad

2021-04-02 08:31 UTC, TiviPlus commented on code/__DEFINES/mobs.dm
> +#define CASTE_CAN_CORRUPT_GENE (1<<16) //Can corrupt a generator
```suggestion
#define CASTE_CAN_CORRUPT_GENERATOR (1<<16) //Can corrupt a generator
```
the other one isnt that clear

2021-04-03 20:15 UTC, TiviPlus approved these changes

2021-04-03 20:16 UTC, merged