gpmg has 100% shrapnel rng
tgstation/TerraGov-Marine-Corps pull request #6476
Opened 2021-04-02 15:19 UTC by Pariah919

## About The Pull Request
the gpmg buff we've all been waiting for

## Why It's Good For The Game
i think this is a good idea

## Changelog
:cl:
balance: gpmg always shrapnels on hit
/:cl:

2021-04-02 15:21 UTC, Naaanii commented
Based.

2021-04-02 17:42 UTC, Swagile commented
april fools is over bro

2021-04-02 17:45 UTC, TGCMbetcher commented
Now bad t60 users can be banned for griefing

2021-04-02 20:11 UTC, neohenry commented
time for medics to take out more than 10 shrapnels from marines' chest

2021-04-02 20:48 UTC, Losenis commented
30 damage per tile walked over having 20 shrap in your torso

2021-04-02 23:05 UTC, TGCMbetcher commented
> 30 damage per tile walked over having 20 shrap in your torso

die in 5 steps from organ damage

2021-04-02 23:34 UTC, RyderFive commented
Exactly what the game needs.

2021-04-02 23:55 UTC, bowlofcereal commented
yes

2021-04-03 00:07 UTC, XSlayer300 commented on code/modules/projectiles/ammo_datums.dm
> +	shrapnel_chance = 100
```suggestion
	shrapnel_chance = 0
```

2021-04-03 00:59 UTC, SplinterGP commented
this is truly a wonder from balancing PR's

2021-04-03 05:43 UTC, Naaanii requested changes

2021-04-03 05:43 UTC, Naaanii commented on code/modules/projectiles/ammo_datums.dm
> +	shrapnel_chance = 100
```suggestion
	shrapnel_chance = 100
	sundering = 1
```
Because why not?

2021-04-03 11:54 UTC, TiviPlus commented
Funny

2021-04-03 11:54 UTC, closed without merging

2021-04-03 11:57 UTC, Naaanii commented
> Funny

https://github.com/tgstation/TerraGov-Marine-Corps/pull/6484#issuecomment-812854790