Hivemind collapse will now ALWAYS be 5 minutes
tgstation/TerraGov-Marine-Corps pull request #6479
Opened 2021-04-02 18:46 UTC by BraveMole

## About The Pull Request

Title. Sometimes it was 2.5 minutes

## Why It's Good For The Game

2.5 minutes is so short that some hives die cause drone forget to go to shrike. This is ridiculous

## Changelog
:cl:
balance: Hivemind collapse will now ALWAYS be 5 minutes
/:cl:

2021-04-02 22:24 UTC, Naaanii commented
Remove the rng good.

Keep the halfed timer for when there are fewer Xenos, maybe make it % of pop or 3-4 or less Xenos imo.

2021-04-03 20:33 UTC, SplinterGP approved these changes

2021-04-03 20:34 UTC, SplinterGP requested changes

2021-04-03 20:34 UTC, SplinterGP commented on code/modules/mob/living/carbon/xenomorph/hive_datum.dm
>  	var/timer_length = 5 MINUTES
```suggestion
```

2021-04-03 20:34 UTC, SplinterGP commented on code/modules/mob/living/carbon/xenomorph/hive_datum.dm
>  	D.orphan_hive_timer = addtimer(CALLBACK(D, /datum/game_mode.proc/orphan_hivemind_collapse), timer_length, TIMER_STOPPABLE)
```suggestion
	D.orphan_hive_timer = addtimer(CALLBACK(D, /datum/game_mode.proc/orphan_hivemind_collapse), 5 MINUTES, TIMER_STOPPABLE)
```

2021-04-03 21:15 UTC, SplinterGP approved these changes

2021-04-03 21:15 UTC, merged