GPGM nerf
tgstation/TerraGov-Marine-Corps pull request #6501
Opened 2021-04-04 20:20 UTC by BraveMole

## About The Pull Request

ROF from 0.15 to 0.2 seconds like it was before
damage_falloff_mult to 0.25 from 0.5 like it was before
delay from aim mode from 0.2 to 0.05 seconds, to compensate

## Why It's Good For The Game

GPMG is a cancerous weapon to deal with. The last buff made it almost as good for pushing than minigun, and that for free and roundstart. 

This gun is not thaat broke, but it encourages a way of playing that is atrocious to play against as a xenos, and frankly midly interesting to play as a marine (Requires zero skill?). 

The aim mode buff on this PR is here to compensate a bit

## Changelog
:cl:
balance: GPGM ROF back to 0.2, damage_falloff_mult back to 0.25, delay from aim mode buffed to 0.05
/:cl:

2021-04-04 20:40 UTC, neohenry commented
goodbye gpmg spam

2021-04-04 21:24 UTC, Walarks commented
goodbye gpgm spam

2021-04-05 00:40 UTC, MiniMeatwad commented
Thanks for fixing the GPMG.

2021-04-05 01:54 UTC, Swagile commented
goodbye gpmg spam

2021-04-05 02:49 UTC, Dolth commented
goodbye gpmg spam
hello smol smartgun

2021-04-05 08:48 UTC, EvilMelonTheSecond commented
Just remove aim mode and make it a decent gun rather than sending it to Brazil with those stats that get outmatched by pistols.

2021-04-05 09:28 UTC, BraveMole commented
> Just remove aim mode and make it a decent gun rather than sending it to Brazil with those stats that get outmatched by pistols.

I don't want this to be a decent gun. I much prefer playing against an unga with dual pistols, at least both the unga and me have fun

2021-04-05 09:47 UTC, EvilMelonTheSecond commented
> 
> 
> > Just remove aim mode and make it a decent gun rather than sending it to Brazil with those stats that get outmatched by pistols.
> 
> I don't want this to be a decent gun. I much prefer playing against an unga with dual pistols, at least both the unga and me have fun.
> With this PR, GPMG still keeps its niche, and is a decent gun for beginner

Just remove it from the game then. With such terrible stats its a noob trap gun to give shrap to everybody. If the gun won't even have a stationary defense niche why even bother with this stat nerf to make it unusable?

2021-04-05 11:29 UTC, BraveMole commented
> > > Just remove aim mode and make it a decent gun rather than sending it to Brazil with those stats that get outmatched by pistols.
> > 
> > 
> > I don't want this to be a decent gun. I much prefer playing against an unga with dual pistols, at least both the unga and me have fun.
> > With this PR, GPMG still keeps its niche, and is a decent gun for beginner
> 
> Just remove it from the game then. With such terrible stats its a noob trap gun to give shrap to everybody. If the gun won't even have a stationary defense niche why even bother with this stat nerf to make it unusable?

But i has a stationnary defence niche, it had it before the buff?

2021-04-05 12:30 UTC, Chaznoodles commented
> > Just remove aim mode and make it a decent gun rather than sending it to Brazil with those stats that get outmatched by pistols.
> 
> I don't want this to be a decent gun.

hmm

2021-04-05 12:54 UTC, Pariah919 commented
why are you making this gun a "stationary defense gun" when you've literally made the game unplayable and instantly a loss if you're ever on the defense in most rounds?

You're nerfing this and making it into a noobtrap for no reason other than your belief of """fun"""
People find using guns like the gpmg fun, you're stating it isn't fun for the other player? You've stated that you don't want it to be viable even.

2021-04-05 16:21 UTC, TGCMbetcher commented
Hello gmpg spam, 4 bullet a second aim mode

2021-04-05 16:43 UTC, SplinterGP requested changes
Give a better reasoning, the reasons you gave doens't even make sense compared to what you did of giving an even better aimmode to it, this just makes it worse on everything you said.

2021-04-05 16:56 UTC, BraveMole commented on code/modules/projectiles/guns/rifles.dm
> +	aim_fire_delay = 0.05 SECONDS
```suggestion
	aim_fire_delay = 0.2 SECONDS
```

2021-04-05 17:43 UTC, Pariah919 commented
Okay this now straight nerfing the gpmg for pretty flimsy reasons.

I don't really see your point in beliving that a staple normal kit weapon like the GPMG should be bad and that it needs to be nerfed when it isn't really a problem, and then state that its unfun to use for the player using it, and then state a uncommon gimmick loadout like akimbos is better overall (even though it probably is) that serves an entirely different role and purpose. 

This PR is wack

2021-04-06 00:36 UTC, SilencedMP5A5 commented
bad

2021-04-06 23:01 UTC, Tupinambis commented
If the issue is that the GPMG is being used too much outside its suppressive fire role for pushing, why not just make it worse when you are moving around with it? Make it take longer to wield, make it feel heavier in general. 

It always felt to me like a weapon you should be setting up on an entrenched position with a bipod so you could even just make it recoil harshly/be unreliable and inaccurate when it's just being held.

2021-04-07 20:03 UTC, SplinterGP commented
> 
> 
> If the issue is that the GPMG is being used too much outside its suppressive fire role for pushing, why not just make it worse when you are moving around with it? Make it take longer to wield, make it feel heavier in general.
> 
> It always felt to me like a weapon you should be setting up on an entrenched position with a bipod so you could even just make it recoil harshly/be unreliable and inaccurate when it's just being held.

it already is, using aimmode on it makes you almost unmovable

2021-04-08 20:16 UTC, closed without merging