Robo limbs no malfunction and slight damage reduction buff.
tgstation/TerraGov-Marine-Corps pull request #6509
Opened 2021-04-05 23:28 UTC by Swagile

## About The Pull Request

Makes it so you do not malfunction at all with robo limbs and slight buff from 0.66 to 0.50 reduction to damage.

## Why It's Good For The Game

Currently, robo limbs penalize you too much. They malfunction randomly (with no way to fix this except full repair), do not benefit from autodoc / chems, and on top of this require you to restructure your entire setup around it (welder, jaeger helmet or welding helmet if you use PAS, and cables).

This PR seeks to alleviate the worst aspect of the robo limbs (random malfunctions) by removing them entirely, and buffing the amount of damage robo limbs take. This still forces a permanent condition on marines (since they still have to re-order their gear around it), but it also makes it not a "im delimbed, might as well cryo" moment.

Reason why it is important to keep this aspect of the game still is that delimbs are one of the only ways to stop competent marines from constantly pushing; perma kills are basically gone, broken bones are fixed by valk, B18, or splinting.

This is more of a "I am not really good enough at coding to fix this issue entirely but I am good enough to fix it with a bandaid" kinda situations.

## Changelog
:cl:
balance: Robo limbs no longer malfunction.
balance: Robo limbs take more punishment; from 0.66 reduction to 0.50 reduction to brute and burn damage.
/:cl:

2021-04-06 00:02 UTC, SplinterGP requested changes
do the thing i told you at discord

2021-04-06 00:02 UTC, SplinterGP commented on code/modules/organs/limbs.dm
> +		if(prob(0))
```suggestion
		if(prob(5))
```

2021-04-06 01:47 UTC, Swagile commented
done and thanks @SplinterGP for teaching me how to add a proper threshold to malfunction; the no prob(0) was a bandaid fix cause i didn't know how to fix it

2021-04-06 10:46 UTC, TiviPlus approved these changes

2021-04-06 16:34 UTC, SplinterGP approved these changes

2021-04-07 18:00 UTC, merged

2021-04-07 20:26 UTC, DerrickChamberlain commented
Is applying cable only suppose to work when you do it, or is it a bug that other people can not apply the cables to robo limbs?

2021-04-07 20:41 UTC, Swagile commented
> 
> 
> Is applying cable only suppose to work when you do it, or is it a bug that other people can not apply the cables to robo limbs?

this PR doesn't affect that (or shouldn't, since it handles malfunctions and reduction to damage)

as to the answer to that, no idea

2021-04-08 01:28 UTC, DerrickChamberlain commented
> > Is applying cable only suppose to work when you do it, or is it a bug that other people can not apply the cables to robo limbs?
> 
> this PR doesn't affect that (or shouldn't, since it handles malfunctions and reduction to damage)
> 
> as to the answer to that, no idea

Oh I know. I was just asking. It sucks you can not use cable of other peoples robo limbs they have to apply them. If me apply cables does work, there needs to be some feed back.