Extinguisher QOL
tgstation/TerraGov-Marine-Corps pull request #6528
Opened 2021-04-08 01:13 UTC by XSlayer300

## Changelog
:cl:
qol: Clicking yourself with the fire extinguisher while on HELP intent and with the safety off will extinguish yourself instead of bashing.
/:cl:

2021-04-08 07:42 UTC, ZahaSanko commented
Does it also works with water cannon?

2021-04-08 09:07 UTC, XSlayer300 commented
> Does it also works with water cannon?

No, sadly. The flamer still acts as a weapon on its own right.

2021-04-09 07:59 UTC, TiviPlus requested changes

2021-04-09 07:59 UTC, TiviPlus commented on code/game/objects/items/tools/extinguisher.dm
> +		return ..()
No need for the else

2021-04-10 09:20 UTC, TiviPlus commented on code/game/objects/items/tools/extinguisher.dm
> +		return ..()
```suggestion
	if(user.a_intent == INTENT_HELP && !safety) //If we're on help intent and going to spray people, don't bash them.
		return FALSE
	return ..()
```

2021-04-10 13:03 UTC, TiviPlus approved these changes

2021-04-10 13:04 UTC, merged