Allows Roller beds to be converted into surgery tables with a wrench.
tgstation/TerraGov-Marine-Corps pull request #6536
Opened 2021-04-09 03:13 UTC by hyper2snyper

## About The Pull Request

Creates the capability in roller beds to be able to set them up as a surgery table, allowing all surgery table operations with it.
Using a wrench on a deployed roller bed with activate its surgery table mode. Once deployed it can be turned back into a portable roller bed with a wrench.
In surgery mode it can do all usual surgery table operations.

## Why It's Good For The Game

It will allow field surgery to be far less tedious as it allows surgery to be set up almost anywhere.
I can see how this could cause some balance problems since you wouldn't need shipside as much, however surgery is often not required for brining marines back to life in general.
Open to suggestions about how to balance this if it is needed.

## Changelog
:cl:
add: Allows Roller beds to be converted into surgery tables with a wrench.
/:cl:

2021-04-09 04:56 UTC, bobmancer343 commented
bad

2021-04-09 08:43 UTC, BraveMole requested changes

2021-04-09 08:43 UTC, BraveMole commented on code/game/objects/machinery/OpTable.dm
> +		icon_state = initial(icon_state) + "-active"
You missed an early return it seems. Also this could be made in one if return, not two

2021-04-09 08:43 UTC, BraveMole commented on code/game/objects/machinery/OpTable.dm
> +		icon_state = initial(icon_state) + "-active"
if (victim?handle_pulse())
    icon = thing
    return
icon = other thing

2021-04-09 08:43 UTC, BraveMole commented on code/game/objects/machinery/OpTable.dm
> +	. = ..()
```suggestion
	..()
```

2021-04-09 08:43 UTC, BraveMole commented on code/game/objects/machinery/OpTable.dm
> +	var/rollertype = /obj/structure/bed/roller
autodoc

2021-04-09 08:43 UTC, BraveMole commented on code/game/objects/machinery/OpTable.dm
> +/obj/machinery/optable/rollerop
This has no drawbacks compared to a regular optable? Should it not have some?

2021-04-09 08:43 UTC, BraveMole commented on code/game/objects/machinery/OpTable.dm
> +		icon_state = initial(icon_state) + "-active"
And anyway, this doesn't work.

2021-04-09 08:54 UTC, Chaznoodles commented
Powercreep. Allows surgery to be done anywhere with no fail chance from surface.

2021-04-09 13:24 UTC, TGCMbetcher commented
> Powercreep. Allows surgery to be done anywhere with no fail chance from surface.

Ye I was thinking a req item to do that, the only difference is the anesthetic part so something to do with that.

2021-04-09 17:19 UTC, hyper2snyper commented
> Powercreep. Allows surgery to be done anywhere with no fail chance from surface.

Yes I can see that quite obviously however.

Surgery in general is easy, and it is mainly done shipside and on the Alamo if the Op table has been installed.
Surgery is a long term fix to something that is almost always fixed shorterm, the main exception I can think of is removing larva.
All of these are done in surgery a few second however take anywhere from 30 seconds to 5 minutes depending on how often the Alamo is cycled.
My aim here is to make fixing things like fractures not require the Marine to stop playing for 5 minutes as they wait for transit, and to allow a MO or CMO to not have to leave the planet to tend marines.
For CMOs and MOs it should make setting up FoB surgery far easier, and for Corpsmen it would require them to carry all the extra equipment that is required for setting up the bed and performing surgery, not to mention it is immobile in that state and would most likely cause the marine and corpsmen to be vunerable.

An alternative I have thought about was making a few special rollers given to MOs and CMOs for this purpose, however most of their surplus medical gear is given out roundstart anyways so I don't think it would cause too much of a difference.

2021-04-09 18:40 UTC, Walarks commented
You could balance it around requiring electricity and batteries to stay active.

2021-04-09 18:58 UTC, BraveMole requested changes

2021-04-11 19:37 UTC, closed without merging

2021-04-11 19:37 UTC, hyper2snyper commented
Closing because of good discussion in #dev_general