bbuffs dmr and br
tgstation/TerraGov-Marine-Corps pull request #6539
Opened 2021-04-09 07:24 UTC by Pariah919

## About The Pull Request
br gets 40 round magazines
dmr gets slightly faster wield delay and less aim mode slowdown

## Why It's Good For The Game
battle rifle is bad, it should've had double the mag capacity from the start
dmr is a bit bad, it could use some minor love

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
qol: made something easier to use
balance: dmr has slightly less slowdown, les saim slowdown, and battle rifle has had its capacity upped from 25 to 40
/:cl:

2021-04-09 07:27 UTC, Tupinambis commented
The BR not having a reasonable magazine size was my main issue with it. If it could have a 3 round burst option that would be even better. Could even have 36 rounds to a mag.

2021-04-09 20:13 UTC, TiviPlus requested changes
Fix your CL

2021-04-09 20:13 UTC, TiviPlus commented on code/modules/projectiles/magazines/rifles.dm
> -	max_rounds = 25
35

2021-04-12 20:16 UTC, lKiseki commented
Good stuff. These weapons needed some love. Should be given the test merge candidate flag so we can see it in action.

2021-04-13 19:24 UTC, TiviPlus commented on code/modules/projectiles/magazines/rifles.dm
> +	max_rounds = 40
```suggestion
	max_rounds = 35
```

2021-04-13 19:25 UTC, TiviPlus approved these changes

2021-04-13 19:28 UTC, merged