Xeno get a message when silos/turrets are built. It is also registered in the game log
tgstation/TerraGov-Marine-Corps pull request #6557
Opened 2021-04-10 16:02 UTC by BraveMole

## About The Pull Request

Title

## Why It's Good For The Game

So you can know when a hivelord is puttin turrets everywhere like it's TF2. 

## Changelog
:cl:
qol: Xeno message is sent to the hive when silos/turrets are built
admin: Psy points spent are now saved in game log
/:cl:

2021-04-10 16:03 UTC, BraveMole commented on code/modules/mob/living/carbon/xenomorph/abilities.dm
> +	xeno_message("[X.name] has built a new turret get_area(A)!", "xenoannounce", 5, X.hivenumber)
```suggestion
	xeno_message("[X.name] has built a new turret at [get_area(A)]!", "xenoannounce", 5, X.hivenumber)
```

2021-04-10 16:07 UTC, TiviPlus requested changes

2021-04-10 16:07 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/abilities.dm
> +	log_game("[owner] has built a silo in [get_area(A)], spending [final_psych_cost] psy points in the process")
areacoord

2021-04-10 16:07 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/abilities.dm
> +	log_game("[owner] built a turret in get_area(A), spending [psych_cost] psy points in the process")
A) this doesnt work you forgot the []
B) areacoord

2021-04-10 16:32 UTC, TiviPlus approved these changes

2021-04-11 03:28 UTC, SilencedMP5A5 commented
next we'll get an alert whenever someone breaks a resin door :^)

2021-04-11 08:52 UTC, TiviPlus approved these changes

2021-04-11 13:58 UTC, bowlofcereal commented
this is good so you can see which motherfucker is placing 3000 turrets and preventing you from building a pool the entire game

2021-04-11 16:22 UTC, merged