Handholding
tgstation/TerraGov-Marine-Corps pull request #6563
Opened 2021-04-10 23:41 UTC by Swagile

## About The Pull Request

This is my meme PR for the month.

## Why It's Good For The Game

You thought I was joking, Tivi? Think again.

## Changelog
:cl:
add: Adds handholding. Now you can hold your SL's hand before you get atomized by a gravity crush. Help intent and aim at either hand (not arm).
/:cl:

2021-04-10 23:42 UTC, David-Stormwell commented
what have we done to this server

2021-04-10 23:43 UTC, Swagile commented
> 
> 
> what have we done to this server

you got your chance with queen charge

now suffer the wraith of ... marine hand holding

2021-04-10 23:50 UTC, XSlayer300 commented
dangit stop adding what i removed >:(

2021-04-10 23:53 UTC, Swagile commented
> 
> 
> dangit stop adding what i removed >:(

the only one who can stop me

is tivi

but will he dare?

tune in next time for Xeno Ball TGMC

2021-04-11 00:22 UTC, SplinterGP reviewed
lock to fun config

2021-04-11 00:22 UTC, SplinterGP requested changes

2021-04-11 00:22 UTC, SplinterGP commented on code/modules/mob/living/carbon/human/species.dm
> +	if(H.zone_selected == "chest")
```suggestion
	else
```

2021-04-11 01:56 UTC, Swagile commented
dunno how to fiddle with configs on local server, but when i tested, i couldn't hand hold again but no runtimes happened, so i presume the fun flag code i did is working

2021-04-11 04:31 UTC, SplinterGP approved these changes

2021-04-11 08:47 UTC, TiviPlus approved these changes

2021-04-11 12:26 UTC, AnCopper commented
degenerate...

2021-04-12 05:28 UTC, merged