Anti-Pette measures
tgstation/TerraGov-Marine-Corps pull request #6587
Opened 2021-04-13 14:26 UTC by BraveMole

## About The Pull Request

Make it so you have to finish wielding before firing a flamer

## Why It's Good For The Game

There is no innacuracy in flamer, so firing while wielding or after was exactly the same. This made chasing with a flamer too strong for good players, as the xeno cannot really do anything against this loadout, not even flee

## Changelog
:cl:
balance: You cannot shoot the flame fire if you didn't finish your wielding
/:cl:

2021-04-13 15:32 UTC, joookschad commented
wack

2021-04-13 16:48 UTC, Dolth commented
I approve. But this won't save you. Muhahahahaha!

2021-04-13 18:38 UTC, David-Stormwell commented
This had it coming sooner or later

2021-04-13 18:40 UTC, RyderFive commented
Am gonna take at least 50% credit for this.

2021-04-13 19:40 UTC, TiviPlus requested changes

2021-04-13 19:40 UTC, TiviPlus commented on code/__DEFINES/conflict.dm
> +#define GUN_WIELDED_STABLE_FIRING_ONLY	(1<<18)
Dont do this just leave one space

2021-04-18 08:23 UTC, TiviPlus approved these changes

2021-04-18 08:23 UTC, merged