i tried fixing the ghost fumble console time issue
tgstation/TerraGov-Marine-Corps pull request #6596
Opened 2021-04-15 04:12 UTC by joshypooh

## About The Pull Request

## Why It's Good For The Game

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2021-04-15 04:16 UTC, SpaceLoveSs13 commented
Follow the PR guidelines or maintainers may close this. And draft the PR if you need time in properly making it.

2021-04-15 04:21 UTC, SplinterGP commented
> 
> 
> Follow the PR guidelines or maintainers may close this. And draft the PR if you need time in properly making it.

it's alright its their first PR, they're learning

2021-04-15 05:50 UTC, SplinterGP requested changes

2021-04-15 05:50 UTC, SplinterGP commented on code/game/objects/structures/orbital_cannon.dm
> +if(!GLOB.marine_main_ship?.orbital_cannon)
```suggestion
	if(!GLOB.marine_main_ship?.orbital_cannon)
```

2021-04-25 07:40 UTC, closed without merging

2021-04-25 07:41 UTC, SplinterGP commented
https://github.com/tgstation/TerraGov-Marine-Corps/pull/6671 merged, feel free to ask wayland on help on another Fix pr or something