Log admin respawns
tgstation/TerraGov-Marine-Corps pull request #6607
Opened 2021-04-15 21:19 UTC by BraveMole

## About The Pull Request

Title

## Why It's Good For The Game

## Changelog
:cl:
admin: Bypassing respawn has an admin will leave a trace in admin logs
/:cl:

2021-04-15 22:17 UTC, Dolth commented
I thought it already did lol.

2021-04-16 15:55 UTC, TiviPlus requested changes
use key_name

2021-04-22 14:08 UTC, BraveMole commented on code/modules/mob/living/carbon/xenomorph/hive_datum.dm
> +				log_admin("[xeno_candidate.client.ckey] used his admin power to bypass respawn before his timer was over")
```suggestion
				log_admin("[key_name(xeno_candidate)] used his admin power to bypass respawn before his timer was over")
```

2021-04-22 14:08 UTC, BraveMole commented on code/modules/mob/mob_verbs.dm
> +				log_admin("[key_name(xeno_candidate)] used his admin power to bypass respawn before his timer was over")
```suggestion
				log_admin("[key_name(usr)] used his admin power to bypass respawn before his timer was over")
```

2021-04-22 14:53 UTC, TiviPlus approved these changes

2021-04-22 14:53 UTC, merged