Prae spit extinguishes fire
tgstation/TerraGov-Marine-Corps pull request #6611
Opened 2021-04-15 23:27 UTC by BraveMole

## About The Pull Request

Will extinguish all mobs hit by the projectile (including human, so double edged sword). Will also remove some fire stacks from the tile, or extinguish the turf if the fire is weak enough

## Why It's Good For The Game

Marines have more and more way of setting xenos on fire. 
Cas was introduced, then the vali, then the plasma pistol, then the latest mortar buff.
Meanwhile, xeno keeps having only two way of "contering" flamers, acid wells (terrible, cost so much plasma, so long to refill),
acid spray(usefull)
and of course hivelord, with jelly. 

Basicly, if you are against flamer, you NEED an hivelord, and sometimes you just can't have it with your comp.

This gives prae some utility against flames, nothing too crazy. 
This will also make prae as usefull to counter fire as spitter; 30 seconds between each spray is not enough to extinguish players, unlike spitter who can do it reliably. 

## Changelog
:cl:
balance: Prae spit extinguishes fire
/:cl:

2021-04-15 23:46 UTC, SplinterGP commented
i mean you can just extinguish yourself off by pressing B

2021-04-16 06:05 UTC, David-Stormwell commented
Thought this was already a thing, guess not.
It's fine.

2021-04-16 17:26 UTC, SplinterGP commented
what about instead of instant extinguish you can use it to reduce the firestacks/make the fire end earlier by reducing its remaining burn time

2021-04-16 17:28 UTC, BraveMole commented
> what about instead of instant extinguish you can use it to reduce the firestacks/make the fire end earlier by reducing its remaining burn time

It does that on the turf?
And doing that on the mob would make that feature barely usefull

2021-04-16 17:31 UTC, SplinterGP commented
i mean you can make it reduce some noticeable amount, instant extinguish is uh, a bit too much for me

2021-04-16 19:12 UTC, TiviPlus requested changes

2021-04-16 19:12 UTC, TiviPlus commented on code/modules/projectiles/ammo_datums.dm
> +	for (var/A in T)
Undescriptive af name

2021-04-16 19:12 UTC, TiviPlus commented on code/modules/projectiles/ammo_datums.dm
> +		if(istype(A, /obj/flamer_fire))
ditto

2021-04-16 19:12 UTC, TiviPlus commented on code/modules/projectiles/ammo_datums.dm
> +		if(istype(A, /obj/flamer_fire))
ditto

2021-04-20 03:14 UTC, Hydrinator commented
Yeah i don't see why not. Fire has been getting a bit carried away recently.

2021-04-20 20:40 UTC, TiviPlus requested changes

2021-04-20 20:40 UTC, TiviPlus commented on code/modules/projectiles/ammo_datums.dm
> +			target.ExtinguishMob()
Dont use atom it triggers syntax highlighting

2021-04-20 20:40 UTC, TiviPlus commented on code/modules/projectiles/ammo_datums.dm
> +			var/obj/flamer_fire/FF = atom
ditto

2021-04-20 20:40 UTC, TiviPlus commented on code/modules/projectiles/ammo_datums.dm
> +			var/obj/flamer_fire/FF = atom
ditto

2021-04-21 15:04 UTC, TiviPlus approved these changes

2021-04-21 15:04 UTC, merged