Building near FOB will be 3 times slower than in the field
tgstation/TerraGov-Marine-Corps pull request #6631
Opened 2021-04-19 12:52 UTC by BraveMole

## About The Pull Request

Building near FOB will be 3 times slower than building in the field.

## Why It's Good For The Game

Engies are full fobiting, this is extremly detrimental to the game:
- They are not helping the push, so marines are getting shreded with no place to rest and heal
- They are slowing down the end of the game tremendously, because xeno do not have proper siege capabilities. This is not making marines win; this is not making people have fun; this is just a pain for everyone

Most, if not all are playing minecraft. This would be fine if that was not ruining the game for everyone else. This PR is made to incentivize engie to actually try to be usefull, rather than just playing on their own producing absolutly nothing

## Changelog
:cl:
balance: Building near FOB will be 3 times slower than in the field
/:cl:

2021-04-19 13:17 UTC, Pariah919 commented
You should really stop attemping to make people play the game in the way you want it to be played, as they'll just leave, but I doubt you really care anymore, as all of your actions show that you wish the game to be massively incentivized around the marines being forced to do an all out push or just alt f4, as there's no point in playing anymore.
Making FOBs and planning them out is fun for people, so why punish them if they enjoy it?

Stating minifobs are useful ignores the reality that they rarely last more than a moment most of the time, and if your first ideal idea is to jump to making it take longer to make a normal fob then people will just ignore that and do it anyway, your reasonings are just an excuse to nerf FOB making in the long term for no real conceviable reason.

2021-04-19 13:19 UTC, BraveMole commented
> You should really stop attemping to make people play the game in the way you want it to be played, as they'll just leave, but I doubt you really care anymore, as all of your actions show that you wish the game to be massively incentivized around the marines being forced to do an all out push or just alt f4, as there's no point in playing anymore.
> Making FOBs and planning them out is fun for people, so why punish them if they enjoy it?
> 
> Stating minifobs are useful ignores the reality that they rarely last more than a moment most of the time, and if your first ideal idea is to jump to making it take longer to make a normal fob then people will just ignore that and do it anyway, your reasonings are just an excuse to nerf FOB making in the long term for no real conceviable reason.

So you are really defending the long as fuck sieges we have right now? Astounishing

2021-04-19 13:21 UTC, SpaceLoveSs13 commented
> You should really stop attemping to make people play the game in the way you want it to be played, as they'll just leave, but I doubt you really care anymore, as all of your actions show that you wish the game to be massively incentivized around the marines being forced to do an all out push or just alt f4, as there's no point in playing anymore.
> Making FOBs and planning them out is fun for people, so why punish them if they enjoy it?
> 
> Stating minifobs are useful ignores the reality that they rarely last more than a moment most of the time, and if your first ideal idea is to jump to making it take longer to make a normal fob then people will just ignore that and do it anyway, your reasonings are just an excuse to nerf FOB making in the long term for no real conceviable reason.

So is chaz gonna come and defend you and your cadehugging" too dude? FOB seiege is cancer and It was been 11 consecutive rounds that I have experienced fobbiting. Engineers making gigantic fob that is making xenoes either suicide or give up. Instead of posting snarky comments here, play the actual game. 11 rounda of fobbitting is a clear indication engi buff didn't fullfill t's intentions and conditions it was merged with.

2021-04-19 13:54 UTC, Windryn commented
I do not think a reactionary PR submitted so soon is the best approach to this problem. 

This could very much eliminate the Marines agility to make mini FOBs

The most concerning thing however is the lack of ability to now patch a FOB, as now one breach to a cadeline with this update is much more of a death sentence that it previously would have been. Essentially boilers now can spam gas and then engineers have no hope to replace the cade during combat. 

Essentially this PR either makes a engie sit next to their cades to repair them as soon as they take damage, as to not lose them. or the more likely outcome, those who still bother to suffer to play marines engineer simply wont.

2021-04-19 13:57 UTC, BraveMole commented
> I do not think a reactionary PR submitted so soon is the best approach to this problem.
> 
> This could very much eliminate the Marines ability to make mini FOBs
> 
> The most concerning thing however is the lack of ability to now patch a FOB, as now one breach to a cadeline with this update is much more of a death sentence that it previously would have been. Essentially boilers now can spam gas and then engineers have no hope to replace the cade during combat.
> 
> Essentially this PR either makes a engie sit next to their cades to repair them as soon as they take damage, as to not lose them. or the more likely outcome, those who still bother to suffer to play marine engineer simply wont.

This makes engie have the same building speed as before the buff. When fob sieging was already an issue.
And if engie cannot patch of FOB, good. FOB siege are not supposed to end up 5 hours.

2021-04-19 13:59 UTC, Windryn commented
> This makes engie have the same building speed as before the buff. When fob sieging was already an issue.


So w're just returning to an issue we already had?

2021-04-19 13:59 UTC, Naaanii commented
> I do not think a reactionary PR submitted so soon is the best approach to this problem.
> 
> This could very much eliminate the Marines ability to make mini FOBs
> 
> The most concerning thing however is the lack of ability to now patch a FOB, as now one breach to a cadeline with this update is much more of a death sentence that it previously would have been. Essentially boilers now can spam gas and then engineers have no hope to replace the cade during combat.
> 
> Essentially this PR either makes a engie sit next to their cades to repair them as soon as they take damage, as to not lose them. or the more likely outcome, those who still bother to suffer to play marine engineer simply wont.

The point of the PR is to make it easier for Xenos to breach and FOB defence harder, so once there is a breach, it becomes extremely difficult to fix with Xenos constantly pressuring. It's just slightly more forced gameplay trying to make engineers use their buffs in the intended manner.

2021-04-19 14:01 UTC, BraveMole commented
> > This makes engie have the same building speed as before the buff. When fob sieging was already an issue.
> 
> So w're just returning to an issue we already had?

We're returning to an issue, that was way worse than what is now. Engie buffs just allowed worse fob siege, that all

2021-04-19 14:05 UTC, InterroLouis commented
Does this affect the FOB drone?

2021-04-19 16:08 UTC, Tupinambis commented
I think this artificial solution might not be the best solution and will probably confuse players. I hate Fobbiting to death but I think reworking the distress gamemode itself to discourage fobbiting is the way to go (by giving marines a timed objective they MUST push out to achieve or they lose)

2021-04-19 16:17 UTC, SplinterGP requested changes

2021-04-19 16:17 UTC, SplinterGP commented on code/game/objects/items/stacks/sandbags.dm
> +		to_chat(usr, "<span class ='warning'>The fuel residues of the space ship prevent us from using our power tool, we build slower!</span>")
Message span everytime you build

2021-04-19 16:17 UTC, SplinterGP commented on code/game/objects/items/stacks/stack.dm
> +				to_chat(usr, "<span class ='warning'>The fuel residues of the space ship prevent us from using our power tool, we build slower!</span>")
Spam when you build

2021-04-19 16:18 UTC, SplinterGP commented
Just nerf the buff you did, instead of from 10 to 40 per skill just make 20%

2021-04-19 16:59 UTC, DerrickChamberlain commented
> Does this affect the FOB drone?

It does not affect drone. I am pretty sure it does not since it is only used before shutters.

2021-04-20 03:11 UTC, Hydrinator commented
This is a horrible idea in so many ways. Here's 3 reasons:

1. Any remotely long FOB siege is the result of uncoordinated and/or inexperienced xenos. A simple crusher + spitter combo can literally break through 4-5+ barricades protected with razorwire in seconds. Lots of turrets? Wraith. Lots of cade hugging marines? Boiler & Warrior/Ravager. Even carriers can counter these now by throwing acid huggers.

2. This would artificially create a new meta where engineers either build outside whatever this magical "build slower zone" is, build nowhere but at miners or abandon FOB building all together.

3. There is already a huge lack of engineer players. Changes like these would literally be kicking them in the balls for all the wrong reasons.

2021-04-20 10:37 UTC, BraveMole commented
> 1. Any remotely long FOB siege is the result of uncoordinated and/or inexperienced xenos. A simple crusher + spitter combo can literally break through 4-5+ barricades protected with razorwire in seconds. Lots of turrets? Wraith. Lots of cade hugging marines? Boiler & Warrior/Ravager. Even carriers can counter these now by throwing acid huggers.enbt

Even with sweaty xenox, an excellent composition and etc, it's still a pain to attack FOB even in a 1:1 ratio. You can do it, but it takes 20 minutes of unfun gameplay


> 2. This would artificially create a new meta where engineers either build outside whatever this magical "build slower zone" is, build nowhere but at miners or abandon FOB building all together.

Good. That's the purpose of the PR. Make them do other stuff than fobitting. I agree on the artificial part though


> 3. There is already a huge lack of engineer players. Changes like these would literally be kicking them in the balls for all the wrong reasons.

I buffed the engineers tremondously in the past month. This PR barely affect one part of their gameplay, so I don't think it's right to complain about that. 

What you don't understant, is that if no one find a solution to the hard fobbit, whether by this PR or another idea, the engie buffs will all be reverted. 
Because these cancer FOB cannot stay

2021-04-20 16:35 UTC, Hydrinator commented
> Even with sweaty xenox, an excellent composition and etc, it's still a pain to attack FOB even in a 1:1 ratio. You can do it, but it takes 20 minutes of unfun gameplay

... No, like i literally just said, it takes seconds to create breaches by utilizing a non-retarded crusher and a spitter to yeet both barricades and razorwire instantly. What takes time is killing all the marines inside if they're properly defending which these changes will not help with due to most breaches getting sealed with razorwire grenades.

> Good. That's the purpose of the PR. Make them do other stuff than fobitting. I agree on the artificial part though

Most engineers already do not give two shits about the FOB. The only ones that do are usually IRL busy or are doing FOB chores such as manning the mortar. I've had games where there are 8+ engineers and none of them don't bother putting up a single cade at the FOB, even if there's holes.

> I buffed the engineers tremondously in the past month. These buffs are allowing these utter cancer fobs. This PR barely affect one part of their gameplay, so I don't think it's right to complain about that.

Making things take slightly less time to build does not equal more engineer players. I myself didn't even notice the changes until someone told me and nor have we seen an increase in engineer players since then.

> What you don't understant, is that if no one find a solution to the hard fobbit, whether by this PR or another idea, the engie buffs will all be reverted because these cancer FOB cannot stay

Instead of looking at the FOB defenses, you can instead observe what causes cadehugging in the first place, which is currently the silo game mode that is in the process of being replaced.

Furthermore, adding more building time won't stop "cancer FOB" bases being built. It'll simply take more time to make.

2021-04-20 16:39 UTC, BraveMole commented
> Instead of looking at the FOB defenses, you can instead observe what causes cadehugging in the first place, which is currently the silo game mode that is in the process of being replaced.

Yeah uh, hilarious? Have you ever played during old distress to say this?

2021-04-21 12:57 UTC, JackTheJackhammer commented
The thing is, this with the worm would make FOB defense IMPOSSIBLE. I see xeno powercreep coming on and I, as a avid marine player, fear for the future of my chosen role. I have seen a queen literally walk up to a cade line, 3 marines looking at it, sitting there and placing  down a goddamn strong acid. SITTING THERE, TANKING THEIR BULLETS. This would make the problem even worse.

2021-04-21 17:53 UTC, BraveMole commented
Not feasable without shit code or being a pain in the ass

2021-04-21 17:53 UTC, closed without merging