Distress.
tgstation/TerraGov-Marine-Corps pull request #6636
Opened 2021-04-19 22:35 UTC by David-Stormwell

## About The Pull Request

If no one else works on it I will.

## Why It's Good For The Game

Remaking the old but better gamemode.
It'll have to be polished quite some.

## Changelog
:cl:
add: Re-added old Distress gamemode.
/:cl:

2021-04-19 22:36 UTC, Naaanii commented
Bless.

2021-04-19 22:36 UTC, BraveMole commented
give me back my blue color

2021-04-19 22:37 UTC, MiniMeatwad commented
Nice.

2021-04-19 22:38 UTC, David-Stormwell commented
Converting to draft in the meantime, probably gonna take a little while to work on this.

2021-04-19 22:38 UTC, David-Stormwell commented
> 
> 
> give me back my blue color

No.

2021-04-19 22:41 UTC, SplinterGP requested changes

2021-04-19 22:41 UTC, SplinterGP commented on code/datums/gamemodes/hunt.dm
> +		bioscan_current_interval += bioscan_ongoing_interval * bioscan_scaling_factor
Move this and all bioscan code to infestation typepath, the parent of this one and distress as both have the bioscan, and remove bioscan code from distress

2021-04-19 22:46 UTC, XSlayer300 commented on code/datums/gamemodes/hunt.dm
> +	name = "Hunt party"
```suggestion
	name = "Hunting Party"
```

2021-04-19 22:47 UTC, XSlayer300 commented on code/modules/mob/living/carbon/xenomorph/abilities.dm
> +	name = "Create hunt den"
```suggestion
	name = "Create Hunting Den"
```

2021-04-19 22:48 UTC, XSlayer300 commented on code/modules/mob/living/carbon/xenomorph/abilities.dm
> +	mechanics_text = "Creates a new hunt den, using 3 headbited bodies"
```suggestion
	mechanics_text = "Create a new hunting den, using 3 headbiten corpses."
```

2021-04-19 22:49 UTC, XSlayer300 commented on code/modules/mob/living/carbon/xenomorph/abilities.dm
> +		to_chat(owner, "<span class='warning'>There are not enough dead bodies, you need [required_mobs] bodies for a silo!</span>")
```suggestion
		to_chat(owner, "<span class='warning'>There are not enough dead bodies, we need [required_mobs] bodies for a silo!</span>")
```

2021-04-20 05:07 UTC, David-Stormwell commented
Closing if Bravemole goes on making his.

2021-04-22 18:15 UTC, David-Stormwell commented
Now closing as Bravemole's has gotten to the TM stage.

2021-04-22 18:15 UTC, closed without merging