Buffs Autoinjectors and Autoinjector pouches for Synth and Corpsman
tgstation/TerraGov-Marine-Corps pull request #6658
Opened 2021-04-22 20:21 UTC by Alterist

## About The Pull Request

## Why It's Good For The Game

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2021-04-23 02:15 UTC, Swagile commented
there's a reason you don't get oxy in advanced injectors

dermaline and meralyn instantly delete any oxycodone detected in your system

if you want to buff advanced autoinjectors, give them hydrocodone, or whatever the full name is that is located in the B18's autodoc system

2021-04-23 02:21 UTC, Swagile commented on code/game/objects/items/reagent_containers/autoinjectors.dm
> +	name = "tramadol autoinjector"
Name = "larvaway autoinjector"

2021-04-23 02:21 UTC, Swagile commented on code/game/objects/items/reagent_containers/autoinjectors.dm
> +	name = "tramadol autoinjector"
fix name mabe?
```suggestion
	name = "larvaway autoinjector"
```

2021-04-23 15:07 UTC, Alterist commented
This should have been a draft, will reopen when complete

2021-04-23 18:27 UTC, Alterist commented on code/game/objects/items/reagent_containers/autoinjectors.dm
> +	name = "tramadol autoinjector"
fixed

2021-04-23 20:15 UTC, SplinterGP commented
autoinjector pouch doenst need to hold more.

2021-04-24 18:01 UTC, Alterist commented
@SplinterGP they do, currently there's absolutely no reason you would pick them from the  as a synth or corpsman, and even less reason to use them as marine, as Medkit pouches does everything they do but better

2021-04-27 20:29 UTC, TiviPlus requested changes

2021-04-27 20:29 UTC, TiviPlus commented on code/game/objects/items/reagent_containers/autoinjectors.dm
> +	desc = "An auto-injector loaded with a dose of Polyhexanide, a sterilizer for internal surgical use."
larvaway?

2021-04-27 21:30 UTC, JackTheJackhammer commented
Definitely a needed change. Its horrible having to stick 2 needles to even get myself in a position to start healing

2021-04-27 21:38 UTC, Alterist commented on code/game/objects/items/reagent_containers/autoinjectors.dm
> +	desc = "An auto-injector loaded with a dose of Polyhexanide, a sterilizer for internal surgical use."
fixed

2021-04-28 09:02 UTC, TiviPlus approved these changes

2021-04-28 09:02 UTC, merged