Bull gore buff
tgstation/TerraGov-Marine-Corps pull request #6670
Opened 2021-04-23 16:22 UTC by BraveMole

## About The Pull Request

Bull gore does double the damage, and it's aimed at the groin for maximum gore

## Why It's Good For The Game

Gore was only doing one free attack, and this is really terrible if you compare to the 5 seconds stun of a headbutt charge.
This makes gore more competitive, and allow the bull players to actually chose what options is better for what situation

## Changelog
:cl:
balance: Double the damage of bull gore and make it aim the groin
/:cl:

2021-04-23 16:24 UTC, RenGusta commented
So is this just to induce organ failure and force topside trips if you're unlucky enough to get hit, or what?

2021-04-23 16:26 UTC, BraveMole commented
It's litteraly like bull is attacking twice and aiming groin. If you land a stun, you probably can do more free attack afterwards

2021-04-23 16:30 UTC, RenGusta commented
Yeah but why groin. Why not just free additional attack damage with a guaranteed bleed effect or something funny. Groin has organs in it and that makes it beneficial to fuck up. Like, in no small amount.

2021-04-23 20:13 UTC, SplinterGP commented
put it to attack wherever the player is aiming.

2021-04-23 21:19 UTC, BraveMole commented
> put it to attack wherever the player is aiming or actually where charges affect on.

Ah yes, even better

2021-04-27 18:54 UTC, TiviPlus approved these changes

2021-04-27 19:21 UTC, SplinterGP requested changes
changelog

2021-04-30 07:46 UTC, merged