Add linters for pixel z / pixel w and for centcomm with two m
tgstation/TerraGov-Marine-Corps pull request #6683
Opened 2021-04-25 18:08 UTC by BraveMole

## About The Pull Request

Title

## Why It's Good For The Game

Barely usefull, but centcomm with two m is ugly

## Changelog
:cl:
code: Linters for pixel z / pixel w and for centcomm with two m
/:cl:

2021-04-25 19:43 UTC, SplinterGP commented
wtf is pixel z and w, also pixel_x and pixel_y on maps are fine

2021-04-25 19:58 UTC, TiviPlus commented
> wtf is pixel z and w, also pixel_x and pixel_y on maps are fine

read the ref

2021-04-26 08:23 UTC, BraveMole commented
> wtf is pixel z and w, also pixel_x and pixel_y on maps are fine

there are zero pixel_x and pixel_y on maps, because you use pixe z and w to do this.

2021-04-26 08:32 UTC, TiviPlus requested changes

2021-04-26 08:32 UTC, TiviPlus commented on _maps/map_files/MarineHQ/MarineHQ.dmm
> -	},
replace z and w with x and y like they shoud be

2021-04-26 08:32 UTC, TiviPlus commented on tools/ci/check_grep.sh
> +fi;
x and y?

2021-04-26 09:18 UTC, BraveMole commented on tools/ci/check_grep.sh
> +fi;
ouh, stupid of me

2021-04-26 09:19 UTC, BraveMole commented on tools/ci/check_grep.sh
> +echo "Checking for pixel_[xy]"
```suggestion
echo "Checking for pixel_[wz]"
```

2021-04-26 09:19 UTC, BraveMole commented on tools/ci/check_grep.sh
> +    echo "pixel_x/pixel_y variables detected in maps, please remove them."
```suggestion
    echo "pixel_w/pixel_z variables detected in maps, please remove them."
```

2021-05-01 19:09 UTC, TiviPlus requested changes

2021-05-01 19:09 UTC, TiviPlus commented on tools/ci/check_grep.sh
> +if grep -nP 'pixel_[^xy]' _maps/**/*.dmm;	then
This still checks for x/y are you sure it works

2021-05-01 19:40 UTC, TiviPlus approved these changes

2021-05-01 19:40 UTC, merged