Pickup macro made null for two handed weapons (or 2 of them unwielded)
tgstation/TerraGov-Marine-Corps pull request #6688
Opened 2021-04-26 05:53 UTC by Wayland-Smithy

## About The Pull Request

No longer can you pull off inhuman throw and pickup speeds with multiple spears, or any other two handed weapons, in melee range.

## Why It's Good For The Game

While we can't stop in keyboard or in mouse keypress macros to switch hands, toggle throw, and click the targets direction we can make it a little harder to give yourself godlike DPS on the reload.

## Changelog
:cl:
tweak: Two-handed weapons can no longer be picked up with a macro.
/:cl:

2021-04-26 08:39 UTC, TiviPlus requested changes
Tweak label doesnt exist anymore

2021-04-26 08:45 UTC, Wayland-Smithy commented
Ahh, guess that's why the bot failed to label it

2021-04-26 11:34 UTC, Naaanii commented
Muh throwing knife spam...

2021-04-26 18:47 UTC, Wayland-Smithy commented
I thought about applying it to throwing knives too, or all throwables with any real damage, but they aren't even close in effectiveness compared to the DPS of 2 spears landing at your feet after each pair of throws.

Besides if it did affect throwing knives specifically you'd just need to take more than 2 into battle with you and spam them from your storage, trading inventory space for rapid reload. Think a quiver of knives instead of arrows. Stop depending on undocumented performance enhancing gamer buttons.

2021-04-26 23:08 UTC, usnpeepoo commented
bad pr spears and knives need macros for picking up its the only fun way to use it

2021-04-26 23:28 UTC, Wayland-Smithy commented
bad comment pointing out a literal flaw and admitting you need to depend on macros without proposing a better solution

2021-04-27 19:20 UTC, SplinterGP commented
i dont like removing pickup verbs because it makes that stuff a pain in the ass to deal with, i already feel death when theres a spot full of guns and i wanna take one and i cant rightclick pickup it

2021-04-28 01:27 UTC, Wayland-Smithy commented
Far as picking a weapon out of a pile is concerned you can still pull it from the context menu list to separate it out for easy clicking or scroll through the tiles contents via alt click and left click the weapon you want from a list that way.

If you think comparing guns to two handeds is unfair because they are harder to see and click with their sprites than that is a sprite issue. There is a reason we can't have nice things like pickup macros because like with the guns allowing it to be used for QOL purposes also allows sweaty robustos to abuse it.

Merge this and add some invisible bluk to the spears for ground clicking purposes, but without making the entire tile force pull it into your hand. ex.
![image](https://user-images.githubusercontent.com/64715958/116332195-28fc1f00-a786-11eb-97ed-44c9432b400c.png)

2021-04-28 20:43 UTC, SplinterGP commented
just add pickup keybind for everyone pepega

2021-04-29 15:37 UTC, InterroLouis commented
Just add a delay on how often you can use the pickup macro instead.

2021-04-30 01:46 UTC, SplinterGP commented
> 
> 
> Just add a delay on how often you can use the pickup macro instead.

cat

2021-04-30 07:30 UTC, DerFlammenwerfer commented
> Stop depending on undocumented performance enhancing gamer buttons.
Stop merging weapons with tiny, barely-clickable sprites?

2021-05-03 16:49 UTC, TiviPlus approved these changes

2021-05-03 16:49 UTC, merged