Larva queue QOL
tgstation/TerraGov-Marine-Corps pull request #6744
Opened 2021-05-01 19:54 UTC by BraveMole

## About The Pull Request

Action added to observers. Also you can leave the queue by clicking on the action another time

## Why It's Good For The Game

QOL

## Changelog
:cl:
qol: You can leave the larva queue. Also, a new action to join/leave the queue gave to observers
/:cl:

2021-05-02 01:56 UTC, XSlayer300 commented on code/datums/actions/observer_action.dm
> +	name = "Join larva queue"
```suggestion
	name = "Join Larva Queue"
```
consistency.

2021-05-02 01:57 UTC, XSlayer300 commented on code/modules/mob/living/carbon/xenomorph/hive_datum.dm
> +	to_chat(observer, "<span class='warning'>You left the larva queue</span>")
```suggestion
	to_chat(observer, "<span class='warning'>You left the Larva queue.</span>")
```

2021-05-02 01:57 UTC, XSlayer300 commented on code/modules/mob/living/carbon/xenomorph/hive_datum.dm
>  	to_chat(observer, "<span class='warning'>There are no burrowed larvas or no silos. You are in position [observer.larva_position] to become a xeno</span>")
```suggestion
	to_chat(observer, "<span class='warning'>There are no burrowed Larvae or no silos. You are in position [observer.larva_position] to become a Xenomorph</span>")
```
Maybe an additional fix too.

2021-05-02 20:42 UTC, TiviPlus requested changes

2021-05-02 20:42 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/hive_datum.dm
> +		observer_in_queue = LAZYACCESS(candidate, i)
why are you doing a lazyaccess when you already check length?

2021-05-03 16:35 UTC, TiviPlus approved these changes

2021-05-03 16:35 UTC, merged

2021-05-03 22:08 UTC, usnpeepoo commented
when will burrowed larva count towards larva queue so you can observe and wait for a burrowed to appear without needing a silo