Datumized view refactor and new view settings
tgstation/TerraGov-Marine-Corps pull request #6748
Opened 2021-05-02 20:40 UTC by TiviPlus

## About The Pull Request

Ports datumized view from tg 
Has systems for the actual player setting, but this should be TMed so Ill do it after I'm sure I hit all the view settings right
Also might use some code spruceup but I really want to test this before
backend for widescreen so stop asking me

## Changelog
:cl:
qol: Players can now set their pixel scaling and scaling method
refactor: refactored view code
/:cl:

2021-05-03 22:04 UTC, SplinterGP requested changes

2021-05-14 22:57 UTC, XSlayer300 commented
Shift + Scrolldown while ghosted allows you to zoom out the furtherest way possible, intentional?

2021-05-27 08:54 UTC, TiviPlus commented
Bug apparently didnt exist?

2021-07-02 22:02 UTC, SplinterGP requested changes

2021-07-02 22:02 UTC, SplinterGP commented on tgui/packages/tgui/interfaces/PlayerPreferences/FieldPreferences.tsx
> +  const { act} = useBackend<PlayerPreferencesData>(context);
```suggestion
  const { act } = useBackend<PlayerPreferencesData>(context);
```

2021-07-02 22:16 UTC, merged