Context Menu on Shift Right Click
tgstation/TerraGov-Marine-Corps pull request #6751
Opened 2021-05-03 02:45 UTC by SkeletalElite

## About The Pull Request
Puts context menu on shift right click, might make it a preference though.

Draft for 2 reasons:
1) I still need to go change stuff with the old preference that outright disabled it
2) I don't know if I should make it so the context menu is always on shift + right click and get rid of the preference or if I should change the old preference to just change the binding instead of disabling the menu

## Why It's Good For The Game
Allows you to have best of both worlds where you get context menu as well as using right click for game play.

## Changelog
:cl:
qol: Context/right click/verb menu is now accessed with shift right click
/:cl:

2021-05-03 12:35 UTC, BraveMole commented
Oh boy, strap yourself the haters are coming

2021-05-03 16:38 UTC, TiviPlus reviewed
shouldnt you also be setting show_popup_menus = false ?

2021-05-03 16:39 UTC, TiviPlus commented
Also ghosts should probably have right click menus on by default

2021-05-03 16:52 UTC, SkeletalElite commented
> shouldnt you also be setting show_popup_menus = false ?

show_popup_menus = false disables the menu entirely, this PR just makes it to where you need to press shift + right click to make it pop up

2021-05-03 19:12 UTC, TiviPlus commented on code/modules/client/client_procs.dm
> +/client/proc/set_right_click_menu_mode(shift_only)
autodoc

2021-05-04 10:56 UTC, TiviPlus approved these changes

2021-05-04 20:51 UTC, Texicos commented
this
but make it a preference

2021-05-04 21:47 UTC, GravitronBlue commented
Trying to melt things with acid just brings up the context menu still unlike the old toggle preference.

and as Bravemole predicted, thumbs down to the whole combat mode system in general.

2021-05-04 22:00 UTC, Al-1ce commented
If you're going to add this at the bare minimum make it a preference. The majority of players don't want anything to do with combat mode.

2021-05-05 01:16 UTC, Dolth commented
Please, make it a preference, this is really a hell to use when I've spent 5 years on CM/TGMC with regular right clicking.
I see no reason to do that.

2021-05-05 03:25 UTC, SplinterGP requested changes
people dindt like this much, the option is way more favourable from what i've seen people saying and having the option was better, a keybind for the option is honestly enough IMO and keeps the best of 2 worlds

2021-05-05 11:38 UTC, ZahaSanko commented
Begone, fiend! or do it as a choice

2021-05-05 11:39 UTC, SwagstylerS commented
The Quality Of Life tag is quite funny when it is just simply annoying. Make it an option and please do not put it on screen. Xenos already have shit ton of buttons on it.

2021-05-05 12:50 UTC, freshguacc commented
These controls add little, of use, since the middle mouse button already does what the right mouse button does at least for xenos. It's a control scheme with redundant buttons which should be avoided. If it really is added permanently it should be a preference or a toggle at least. For marines, Z is now the same as pressing RMB, which is again redundant controls. Pressing Z or MMB for fast actions is not a bothersome control scheme, however pressing both shift+RMB IS awkward for an action that you do as frequently as opening the context menu.

2021-05-05 13:30 UTC, Dolth commented
@freshguacc It's more a matter of letting people keybind the game like they want and not forcing them a single way to play. Especially when they're no visible use to enforce one way or another.

2021-05-05 15:32 UTC, jroinc commented
Does anyone actually like this? Serious question.

2021-05-05 15:49 UTC, jroinc commented
Hey, so does anyone actually like this? Serious question.

This isn't an off-topic question. This is a legitimate question. At the time of me posting this, it has one like from bravemole, and 11 dislikes. This appears to be change for the sake of change.

2021-05-05 15:56 UTC, Dolth commented
> Hey, so does anyone actually like this? Serious question.
> 
> This isn't an off-topic question. This is a legitimate question. At the time of me posting this, it has one like from bravemole, and 11 dislikes. This appears to be change for the sake of change.

https://i.gyazo.com/3c44ac306550a5397bdfc9ac5c33deb6.png

2021-05-05 17:16 UTC, MiniMeatwad commented
Make it optional, do not make it a requirement. Please don't merge this until it's optional.

2021-05-05 17:25 UTC, SkeletalElite commented
> Make it optional, do not make it a requirement. Please don't merge this until it's optional.

It's been optional for 13 hours now, the testmerge just hasn't been updated

2021-05-05 18:18 UTC, TiviPlus requested changes
Ok PSA
As of this PR the only supported control scheme is the shift right click menu
Any prs that do not conform to it will be made to 
Explanation can be seen at https://discord.com/channels/498569646014857217/500801682058379265/839516718208385086

2021-05-05 18:18 UTC, TiviPlus commented on code/modules/client/client_defines.dm
> +	var/shift_to_open_context_menu = TRUE ///remembers what our context menu setting is currently set to
Autodoc goes on the above line

2021-05-05 18:19 UTC, TiviPlus commented
Also keep off topic posting and ill lock the pr

2021-05-05 18:31 UTC, SkeletalElite commented
> As of this PR the only supported control scheme is the shift right click menu

Would you like me to revert to pre-toggle then?

2021-05-05 20:20 UTC, SplinterGP requested changes
can you make it a keybind instead of perma shift ? examine does it already, same with dragging that is ctrl but its still a keybind

2021-05-06 02:09 UTC, XSlayer300 commented on code/modules/client/preferences_toggles.dm
> +		to_chat(usr, "<span class='notice'>You will no longer need to hold shift to access the right click menu</span>")
```suggestion
		to_chat(usr, "<span class='notice'>You will no longer need to hold the Shift key to access the right click menu.</span>")
```

2021-05-06 02:09 UTC, XSlayer300 commented on code/modules/client/preferences_toggles.dm
> +		to_chat(usr, "<span class='notice'>You will need to hold shift to access the right click menu</span>")
```suggestion
		to_chat(usr, "<span class='notice'>You will need to hold the Shift key to access the right click menu.</span>")
```

2021-05-06 13:14 UTC, XSlayer300 commented
The pref is not saving, even after a round. Make sure atleast the player can just toggle it on and off once rather than doing it after each round. By default, it should be off.

2021-05-06 17:18 UTC, SkeletalElite commented
> The pref is not saving, even after a round. Make sure atleast the player can just toggle it on and off once rather than doing it after each round. By default, it should be off.

Can't test merge PRs that touch the save file

2021-05-06 20:45 UTC, TiviPlus commented
> can you make it a keybind instead of perma shift ? examine does it already, same with dragging that is ctrl but its still a keybind

That's not how it works you were in the discord conversation

2021-05-07 00:02 UTC, SplinterGP commented
> 
> 
> > can you make it a keybind instead of perma shift ? examine does it already, same with dragging that is ctrl but its still a keybind
> 
> That's not how it works you were in the discord conversation

the what, it can work

2021-05-09 11:41 UTC, merged