Lowers pistol sunder to 1.4
tgstation/TerraGov-Marine-Corps pull request #6752
Opened 2021-05-03 08:13 UTC by lovegreenstuff

## About The Pull Request

See title.

## Why It's Good For The Game

Fuck if I know, I'm doing this for someone else on discord.

## Changelog
:cl:
balance: lowered TP14 sunder to 1.4, kept most commonly used ammo types at 2.
/:cl:

2021-05-03 08:17 UTC, Georgeur commented
I asked for it. 
the basic reason is
tp14 with 33% less sunder has the same sunder per mag as the 23, its an oversight by the small arms rework, they changes all the vars and forgot the sunder on the tp14

2021-05-03 19:20 UTC, TiviPlus commented
Put the reason on the pr and give a justification beyond "I think it was an overight please"

2021-05-03 20:44 UTC, SplinterGP approved these changes

2021-05-03 21:32 UTC, Georgeur commented
Well if you want me to give a reason, the tp-23 having 66% sunder per mag as the tp-14, for the cost of 5 penetration, makes the tp-14 more effective than the tp-23 by a pretty considerable amount. 
Even though the tp-23 magdumps SLIGHTLY faster than the tp-14, the vast difference between 28 sunder per mag, and 42 sunder per mag, is too vast. 
To account for the 5 pen, I asked for its sunder to be 1.4 instead of 1.36. 

Another way you could go about it is by buffing the tp-23, or making more of a middle ground between the two guns.

2021-05-04 05:46 UTC, Georgeur commented
If I don't hear any feedback I'm going to ask the wonderful gentleman who made this for me, to give the tp14, and tp23, the following stats.

Tp-14:
sunder = 1.65

Tp-23:
sunder = 2.15

tp14 gets 4.55 more sunder per mag, as a result of being more highly effected by damage falloff
come on people feedback, please
at the very least these two need almost the same sunder per mag unless someone creates sunder damage falloff

2021-05-04 10:59 UTC, TiviPlus requested changes
Put the reason on the pr and give a justification beyond "I think it was an overight please" and consider whaat the other person requested too please

2021-05-05 05:38 UTC, lovegreenstuff commented
### **E.**

2021-05-09 14:30 UTC, TiviPlus approved these changes

2021-05-14 08:59 UTC, merged