In which two ways to get large quantities of metal for no cost are described fully and completely.
tgstation/TerraGov-Marine-Corps pull request #6782
Opened 2021-05-06 00:54 UTC by jroinc

## About The Pull Request

Method one-
Each T81 GL is worth 1.75 metal sheets when autolathed. No one ever takes them as they're single shot, so the 250 in the vendor became 430 metal sheets, or 8 and a half stacks.

They're now worth 10% of that, so yeah. No more shoveling half of the round's grenade launchers for near-unlimited metal.

Method two-
If you have an autolathe and a stack of 20 rglass, you can feed the rglass in.
Print off one sheet of rglass. Print off all the metal that the rglass gave you, 9 or 10 sheets. Print off a stack of 19 glass.
Click on the glass with the rglass. Now you have 9 metal created from nothing, 20 rglass, and an autolathe ready to go again. Elapsed time: 5-10 seconds for around 10 metal.

This brute-force fixes the metal glitch by making it so low value it's not worth attempting. If someone more experienced than me has a better idea of how to fix it, they're welcome to it.

## Why It's Good For The Game

Prevents people from gaining infinite metal.

## Changelog
:cl:
fix: fixed two exploits allowing production of arbitrarily large amounts of metal
/:cl:

2021-05-06 01:03 UTC, MiniMeatwad commented
Wasn't there a bug that made reinforced metal tiling infinitely wrenchable, where you use metal rods on plating and wrench the tile for infinite metal?

2021-05-06 01:04 UTC, jroinc commented
> 
> 
> Wasn't there a bug that made reinforced metal tiling infinitely wrenchable, where you use metal rods on plating and wrench the tile for infinite metal?

Probably, but I don't know about it. These are the only 2 I know.

2021-05-06 01:05 UTC, MiniMeatwad commented
You can also wire cut by spam clicking with wirecutters on fences and then repair them for infinite metal too.

2021-05-06 01:44 UTC, DerrickChamberlain commented
> Wasn't there a bug that made reinforced metal tiling infinitely wrenchable, where you use metal rods on plating and wrench the tile for infinite metal?

It was patched, and it was a crowbar.

2021-05-06 01:45 UTC, DerrickChamberlain commented
I mean that is hardly infinite, we can only get so much from it. It also requires someone to put in the effort to make it, engineers to build with it. I really see no problem with the stuff we have now. I have not seen any economy breaking metal generators as of yet.

2021-05-06 01:46 UTC, SkeletalElite commented
The GL change is a balance change not a fix. Other one is a fix though

2021-05-06 02:18 UTC, jroinc commented
> 
> 
> The GL change is a balance change not a fix. Other one is a fix though

https://github.com/tgstation/TerraGov-Marine-Corps/pull/6087

It's not intended. Almost all other guns had all their metal values removed to prevent this. I just lowered it cause I think it does make sense, just not enough sense to get 9 stacks of metal from.

2021-05-06 02:37 UTC, SplinterGP commented
> 
> 
> I mean that is hardly infinite, we can only get so much from it. It also requires someone to put in the effort to make it, engineers to build with it. I really see no problem with the stuff we have now. I have not seen any economy breaking metal generators as of yet.

the what

2021-05-06 02:37 UTC, SplinterGP commented
weapons are not meant to be put on autolathe, otherwise there would be no 250 of each

2021-05-06 02:38 UTC, SplinterGP requested changes

2021-05-06 02:38 UTC, SplinterGP commented on code/modules/projectiles/guns/specialist.dm
> +	materials = list(/datum/material/metal = 700)
or remove, dunno if it has parent without materials
```suggestion
	materials = list()
```

2021-05-06 16:26 UTC, jroinc commented
> 
> 
> I mean that is hardly infinite, we can only get so much from it. It also requires someone to put in the effort to make it, engineers to build with it. I really see no problem with the stuff we have now. I have not seen any economy breaking metal generators as of yet.

I have!

Hell, I described it step-by-step! It literally gives infinite metal.

2021-05-06 20:55 UTC, Georgeur commented
Two other issues:
In engineering, the pipe dispenser can be used for infinite metal if you put pipes into the autolathe, its really slow, but it is infinite.

Also in the sulaco, in the briefing room, in prep, and in one or two other places, you can deconstruct all the chairs for about 160 metal. This is because unlike the chairs in the pillar of spring prep, that use, obj/strcture/bed/chair/wood, the saluco uses obj/strcture/bed/chair.

2021-05-07 02:51 UTC, SplinterGP commented
> 
> 
> Two other issues:
> In engineering, the pipe dispenser can be used for infinite metal if you put pipes into the autolathe, its really slow, but it is infinite.
> 
> Also in the sulaco, in the briefing room, in prep, and in one or two other places, you can deconstruct all the chairs for about 160 metal. This is because unlike the chairs in the pillar of spring prep, that use, obj/strcture/bed/chair/wood, the saluco uses obj/strcture/bed/chair.

the chairs are known and since its limited and all we've never cared much about it as it always has been deconstructed anyway, so we take it into account

2021-05-07 03:10 UTC, SplinterGP requested changes

2021-05-07 03:10 UTC, SplinterGP commented on code/modules/projectiles/guns/specialist.dm
> +	materials = list()
actually just delete this
```suggestion
```

2021-05-07 20:41 UTC, SplinterGP approved these changes

2021-05-07 20:41 UTC, merged