Should fix double minimap when changing squad
tgstation/TerraGov-Marine-Corps pull request #6799
Opened 2021-05-09 14:27 UTC by BraveMole

## About The Pull Request

Title

## Why It's Good For The Game

Not tested cause i'm lazy

## Changelog
:cl:
fix: No longer duplicate minimap when changing squad
/:cl:

2021-05-09 14:28 UTC, TiviPlus requested changes
test it

2021-05-09 14:31 UTC, TiviPlus commented
Also fairly sure it doesnt fix it because the issue is a runtime iirc

2021-05-09 15:02 UTC, TiviPlus approved these changes

2021-05-11 00:59 UTC, SplinterGP approved these changes

2021-05-11 06:48 UTC, merged