Fix me
tgstation/TerraGov-Marine-Corps pull request #6839
Opened 2021-05-12 17:52 UTC by BraveMole

## About The Pull Request

Me is broke, this fix me. This is a me problem cause by me, so me fixed it. 

## Why It's Good For The Game

## Changelog
:cl:
fix: Me is fixed by me cause it was broke by me.
/:cl:

2021-05-12 18:33 UTC, usnpeepoo commented
u need fixing?

2021-05-12 20:42 UTC, TiviPlus commented
can you explain how it fixes it thnx

2021-05-13 19:56 UTC, SplinterGP commented
i wont fix you

2021-05-15 07:17 UTC, TiviPlus requested changes

2021-05-15 07:17 UTC, TiviPlus commented on code/modules/mob/emote.dm
> +	key = "emote_me"
Explain this change?

2021-05-15 09:14 UTC, TiviPlus approved these changes

2021-05-15 09:21 UTC, merged