jaeger storage modules no longer slow you down
tgstation/TerraGov-Marine-Corps pull request #6858
Opened 2021-05-14 02:03 UTC by Pariah919

## About The Pull Request
jaeger storage modules no longer slow you down

## Why It's Good For The Game
This is no longer necessary honestly, you don't need to be penalized for having a storage module and I did this with an entirely different expectation and belief that there'd be a wide variety of storage modules for you to pick, but then they literally never got expanded.
This doesn't need to exist anymore outside of extreme cases.

## Changelog
:cl:
balance: medical, general and engineering jaeger storage no longer slow you down at all, from 0.1.
/:cl:

2021-05-14 02:26 UTC, SpaceLoveSs13 commented
I like this pr. Because storage modules are extremely necessary now. However I think this same pr idea got rejected once already.

2021-05-14 07:19 UTC, SolarMacharius commented
I believe this PR would be a good quality life of feature. At the moment, the xenos have plenty of methods of slowing marine pushes down, including the innate slowdown that weeds confer upon marines. Therefore, eliminating the slowdown from storage would make everyday activity as a marine less tedious.

2021-05-14 08:17 UTC, David-Stormwell commented
I'm upvoting this, for about the same reason as Solar pointed out and MJP pointed out, as what should be the prime concern for a marine should be armor attachments, not storage weight.

2021-05-14 15:55 UTC, psykzz commented
but muh realism

2021-05-15 15:20 UTC, David-Stormwell commented
> but muh realism

If you want realism make the items in the storage weigh you down :xenosmirk:

2021-05-16 20:19 UTC, TiviPlus commented
I told you the last time you made this pr that it should stay to allow for no module as speed how did this change

2021-05-16 20:33 UTC, SpaceLoveSs13 commented
> I told you the last time you made this pr that it should stay to allow for no module as speed how did this change

That was lewdcifer not mjp. Also david seems to allow this balance?

2021-05-17 16:59 UTC, Losenis commented
"No module as speed" you might as well go PAS

2021-05-17 22:00 UTC, AdamElTablawy commented
@TiviPlus speaking as a xeno main marines need to be faster anyway

would prefer this pr

2021-05-18 20:48 UTC, TiviPlus requested changes
Discussed in maintainerbus keep the medic module slowdown remove the rest

2021-05-19 05:31 UTC, Pariah919 commented
> Discussed in maintainerbus keep the medic module slowdown remove the rest
give me a good reason that medic module needs slowdown

2021-05-19 09:09 UTC, TiviPlus commented
It's too good

2021-05-19 11:19 UTC, AdamElTablawy commented
> It's too good

your mom is too good at sucking me off

keep medic module slowdown removed

2021-05-19 14:22 UTC, Pariah919 commented
> It's too good
it's equivalent to a corpsman webbing and 5 more medical items aren't going to make you suddenly way more invincible considering instead of that I can just pick a medkit pouch and a general storage module and I'd have 0.1 less slowdown, if one of them are going to have slowdown they all are, frankly.

2021-05-19 14:38 UTC, Losenis commented
It's only 5 slots that I can get 2 more of through a medkit pouch while using a gen storage for 2 T42 drums. Even as corpsman I've been skipping it due to the slowdown.

It's pretty meh.

2021-05-21 09:33 UTC, TiviPlus commented
> > It's too good
> 
> it's equivalent to a corpsman webbing and 5 more medical items aren't going to make you suddenly way more invincible considering instead of that I can just pick a medkit pouch and a general storage module and I'd have 0.1 less slowdown, if one of them are going to have slowdown they all are, frankly.
> I don't see how the medical storage needs to have 0.1 slowdown, barely anyone has said anything about it and it isn't going to suddenly become massively more overpowered because of that in my opinion.

Well we discussed it and decided it is too good in relation to the other modules, another alternative you can try is nerfing the space it stores but if it doesnt make that massive of a difference then why not just leave it

2021-05-21 11:43 UTC, SkeletalElite commented
> Well we discussed it and decided it is too good in relation to the other modules, another alternative you can try is nerfing the space it stores but if it doesnt make that massive of a difference then why not just leave it

If you leave the slowdown on the medical storage module there is literally no reason to take it over a general storage module when you can just use a med belt/medkit pouch/med webbing for no slowdown. It's not like using any of those is robbing you of being able to store something else useful either since the large variety of pouches and satchel can easily be used to find a way to store everything you need.

2021-05-24 09:39 UTC, spookydonut commented
We talked and agreed to merge this but may look at nerfing or removing the med storage module

2021-05-24 09:39 UTC, merged