Adds a marine attachment that makes your bullets faster
tgstation/TerraGov-Marine-Corps pull request #6889
Opened 2021-05-18 03:52 UTC by Pariah919

## About The Pull Request
Makes your bullets faster, thats it

## Why It's Good For The Game
It makes bullets faster at the cost of not having any other barrel attachment

## Changelog
:cl:
balance: added a marine barrel attachment that makes bullets faster
/:cl:

2021-05-18 03:53 UTC, jroinc commented
*But MJP, Extended Barrel already does that!*

2021-05-18 03:55 UTC, Pariah919 commented
>But MJP, Extended Barrel already does that!

FASTER

2021-05-18 04:25 UTC, jroinc commented
> 
> 
> > But MJP, Extended Barrel already does that!
> 
> FASTER

Powercreep go BRRRRR

2021-05-18 05:01 UTC, David-Stormwell commented
bbbbbbbbbb uuuuuu tttttt exxxxxtttteeenndddd baarrrrweewwwelll

2021-05-18 05:02 UTC, lovegreenstuff commented
barrel charger.

that is all

2021-05-18 17:34 UTC, Losenis commented
MAKE BULLETS HITSCAN

2021-05-18 19:22 UTC, TiviPlus requested changes
A) give it a downside you noob
B) Extended barrel exists

2021-05-18 20:37 UTC, SplinterGP commented
> A) give it a downside you noob
> B) Extended barrel exists

Its downside is not using other attachments, kinda, still though it sucks

2021-05-19 01:02 UTC, David-Stormwell commented
> A) give it a downside you noob
> B) Extended barrel exists

To be honest, not having another barrel attachment is a pretty good downside as ext and rc are already great.
And faster bullets are to be honest... Interesting.
I'd like to see this

2021-05-19 09:13 UTC, TiviPlus commented
Not having a downside isn't a downside

2021-05-20 09:07 UTC, Pariah919 commented
it has minor downsides

2021-05-20 09:07 UTC, Pariah919 commented on code/modules/projectiles/gun_attachables.dm
> +	scatter_mod = 2
```suggestion
```

2021-05-21 01:50 UTC, SplinterGP commented
> 
> 
> Not having a downside isn't a downside

the other barrels dont have downsides, their "Downside" is theres another option which has different stats that are better in X

2021-05-21 09:48 UTC, TiviPlus approved these changes

2021-05-21 09:49 UTC, merged