Should fix synth blood loss
tgstation/TerraGov-Marine-Corps pull request #6982
Opened 2021-05-27 15:49 UTC by BraveMole

## About The Pull Request

Most probable reason why synth sometimes had blood loss

## Why It's Good For The Game

## Changelog
:cl:
fix: Should fix synth blood loss
/:cl:

2021-05-27 16:12 UTC, TiviPlus approved these changes

2021-05-27 20:25 UTC, SplinterGP requested changes

2021-05-27 20:25 UTC, SplinterGP commented on code/modules/mob/living/blood.dm
>  	..()
```suggestion
	return ..()
```

2021-05-28 19:57 UTC, SplinterGP approved these changes

2021-05-28 19:58 UTC, merged