New Hunter's Mark Ability
tgstation/TerraGov-Marine-Corps pull request #6994
Opened 2021-05-30 11:24 UTC by Surrealaser

Hunter gains the following abilities:

**Hunter's Mark, New Active Ability
Plasma Cost:** 75
**Cooldown:** 60 seconds
**Wind up:** 1 second
**Effect:** After the wind up, designates a living target in line of sight as the Hunter's quarry. The Hunter can then use Psychic Trace to gain info about the target. Can target allies.

**Psychic Trace, New Active Ability
Plasma Cost**: 1 (token)
**Cooldown:** 6 seconds
**Effect:** Reveals the direction, distance, health, area and infection status of the Hunter's quarry.

Gives the Hunter a fitting and useful new ability that allows it to track down and hunt specific targets.

:cl:
add: Added the Hunter's Mark Hunter ability.
add: Added the Psychic Trace Hunter ability.
/:cl:

2021-05-31 16:13 UTC, TiviPlus requested changes

2021-05-31 16:13 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
> +
typecast as xeno
```suggestion
	var/mob/living/carbon/xenomorph/X = owner

```

2021-05-31 16:13 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
> +			return "deceased"
should this happen? 
You might want to make this something else in case of bugs

2021-05-31 16:13 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
> +	var/mob/living/carbon/xenomorph/hunter/X = owner
```suggestion
	var/mob/living/carbon/xenomorph/X = owner
```

2021-05-31 16:13 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
> +	UnregisterSignal(hunter_mark_target, COMSIG_PARENT_PREQDELETED)
Missing SIGNAL_HANDLER

2021-05-31 16:13 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
> +
this COMSIG_PARENT_PREQDELETED should be 
COMSIG_PARENT_QDELETING, as well as all the other signals used here

2021-05-31 16:13 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
> +	arrow_hud.color = COLOR_ORANGE
Why is the color not set on the object declaration?

2021-05-31 16:13 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
> +	//Prepare the tracker object and set its parameters
```suggestion
	var/obj/screen/arrow/hunter_mark_arrow/arrow_hud = new
	//Prepare the tracker object and set its parameters
```

2021-05-31 16:13 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
> +		/datum/action/xeno_action/psychic_trace
```suggestion
		/datum/action/xeno_action/psychic_trace,
```

2021-06-16 10:00 UTC, SplinterGP commented
Does the mark never run out or something? Because it gives exact position and stuff and while it may not seem that muuuch usefull it gives the literal exact location of the person and it may be well too good if used on someone that flanked them once or twice already, letting them check every once in a while for a flank without even scouting around.

2021-06-16 19:27 UTC, Surrealaser commented
> Does the mark never run out or something? Because it gives exact position and stuff and while it may not seem that muuuch usefull it gives the literal exact location of the person and it may be well too good if used on someone that flanked them once or twice already, letting them check every once in a while for a flank without even scouting around.

It does not run out.

Also I've already got complaints about it being too weak, and I agree, it's pretty underwhelming as is outside of the future synergies planned with other Hunter abilities.

2021-06-16 23:07 UTC, SplinterGP commented
i mean it tells someone position, its not like it does something to the person, i dont get like how its underwhelming, it does whats supposed to, which then inst much and just finishes being something for avoiding getting flanked most times or keep track of someone important.

2021-06-21 00:20 UTC, SplinterGP requested changes
okay so i had some thought to this, and i think an effect like a small beam going from the hunter to the dude he's marking just that if the dude is paying attention he'll know he's marked somewhat

2021-06-21 01:41 UTC, Surrealaser commented
> okay so i had some thought to this, and i think an effect like a small beam going from the hunter to the dude he's marking just that if the dude is paying attention he'll know he's marked somewhat

It's literally not a problem; no one has complained

2021-06-22 03:08 UTC, merged