removes hard melee from shields and they make you slower
tgstation/TerraGov-Marine-Corps pull request #7021
Opened 2021-06-03 17:28 UTC by Pariah919

## About The Pull Request
you no longer have hard melee armor with a shield and they make you a decent bit slower

## Why It's Good For The Game
shields are innanely good in modern tgmc and -5 damage off every slash in the game and then -50% is way too much considering losing one hand is no longer as much of a downside as it used to be

## Changelog
:cl:
balance: shields no longer have hard melee armor and slow you down a bit more
/:cl:

2021-06-03 21:31 UTC, David-Stormwell commented
Considering everyone and their mother enjoy running either vali or one handed ocelot impersonating loadouts it's fine.

2021-06-04 01:03 UTC, SplinterGP approved these changes

2021-06-04 10:30 UTC, TiviPlus requested changes

2021-06-04 10:30 UTC, TiviPlus commented on code/game/objects/items/weapons/shields.dm
> +	slowdown = 0.5
```suggestion
	slowdown = 0.3
```

2021-06-07 12:42 UTC, Pariah919 commented on code/game/objects/items/weapons/shields.dm
> +	slowdown = 0.5
why

2021-06-12 10:00 UTC, merged