HvH mode, civil war
tgstation/TerraGov-Marine-Corps pull request #7025
Opened 2021-06-03 17:38 UTC by BraveMole

## About The Pull Request

This is a first batch of the HvH mode. It is playable-ish, it still lacks things like objectives or even a balance function.

WARNING: this is only playable on the ship map = twin pillars and on the ground map ice colony

This adds to the other PR:

The twin pillars shipmap, it's a map with two identical ships, one for the rebel faction, the other for the loyalist faction
Some small refactoring of the join system, so you are able to join the loyalist or rebel faction. This is very much WIP and will be improved in later PR, but this is good enough for some test
Another shuttle, the triumph. It's a copy of the alamo, but for the rebels.
Add the energy weapon in HvH vendors since david forgot to do it

This is meant for one or two tests rounds with probably a lot of admin intervention, as a lot is to be tested.

## Why It's Good For The Game

New gamemode

## Changelog
:cl:
add: New HvH gamemode, civil war. Very much WIP
/:cl:

2021-06-04 21:31 UTC, ZephyrTFA commented
This looks interesting. Can't wait to see how it functions in-game. Hopefully it gets to a state where it can be a common occurrence

2021-06-16 23:38 UTC, SplinterGP requested changes

2021-06-16 23:38 UTC, SplinterGP commented on code/controllers/subsystem/job.dm
> +		return
cant this be done other way, giving latejoin markers factions or something ?

2021-06-16 23:38 UTC, SplinterGP commented on code/game/objects/effects/landmarks/landmarks.dm
> +	..()
why here and not before ?

2021-06-20 22:57 UTC, SplinterGP requested changes

2021-06-20 22:57 UTC, SplinterGP commented on code/datums/gamemodes/game_mode.dm
> +			new /obj/machinery/computer/shuttle/shuttle_control/dropship(T)
```suggestion
		for(var/turf/T AS in GLOB.lz1_shuttle_console_turfs_list + GLOB.lz2_shuttle_console_turfs_list)
			new /obj/machinery/computer/shuttle/shuttle_control/dropship(T)
```

2021-06-20 23:06 UTC, SplinterGP approved these changes

2021-06-20 23:07 UTC, merged