Add location data to ghost and mob logout logs
tgstation/TerraGov-Marine-Corps pull request #7033
Opened 2021-06-04 22:06 UTC by Wayland-Smithy

## About The Pull Request

Title.

## Why It's Good For The Game

Admins can check logs (via PP even) on a mob to see where it was when a mind left from it.

## Changelog
:cl:
admin: Game logs now save the location of mob ghostings and logouts.
/:cl:

2021-06-04 22:07 UTC, BraveMole commented
totally not because of me

2021-06-05 00:55 UTC, SplinterGP approved these changes

2021-06-05 00:56 UTC, SplinterGP requested changes

2021-06-05 00:56 UTC, SplinterGP commented on code/modules/mob/living/living_verbs.dm
> +	log_game("[key_name(usr)] has ghosted at [AREACOORD(usr)].")
even better 
```suggestion
	log_game("[key_name(usr)] has ghosted at [AREACOORD(usr)] as [src].")
```

2021-06-05 00:58 UTC, SplinterGP commented
my github bonked hard

2021-06-05 00:58 UTC, SplinterGP requested changes

2021-06-05 00:58 UTC, SplinterGP commented on code/modules/mob/living/living_verbs.dm
> +	log_game("[key_name(usr)] has ghosted at [AREACOORD(usr)].")
```suggestion
	log_game("[key_name(usr)] has ghosted at [AREACOORD(usr)] as [src].")
```

2021-06-05 10:15 UTC, SplinterGP approved these changes

2021-06-05 11:04 UTC, TiviPlus commented on code/modules/mob/living/living_verbs.dm
> +	log_game("[key_name(usr)] has ghosted at [AREACOORD(usr)] as [src].")
```suggestion
	log_game("[key_name(usr)] has ghosted at [AREACOORD(usr)]")
```
key name already does this

2021-06-05 15:44 UTC, Wayland-Smithy commented on code/modules/mob/living/living_verbs.dm
> +	log_game("[key_name(usr)] has ghosted at [AREACOORD(usr)] as [src].")
maint code part 2 the undoing

2021-06-05 15:45 UTC, Wayland-Smithy commented on code/modules/mob/living/living_verbs.dm
> +	log_game("[key_name(usr)] has ghosted at [AREACOORD(usr)]")
```suggestion
	log_game("[key_name(usr)] has ghosted at [AREACOORD(usr)].")
```

2021-06-05 21:21 UTC, TiviPlus approved these changes

2021-06-05 21:21 UTC, merged