Fix nightfall + buff king
tgstation/TerraGov-Marine-Corps pull request #7040
Opened 2021-06-06 20:58 UTC by BraveMole

## About The Pull Request

King starts young with grav crush, windup of it is reduced to 1.5 seconds. To prevent spam, canceling grav crush will still consumme the plama.

Nightfall gains 2 more range, and i've fixed it

## Why It's Good For The Game

## Changelog
:cl:
balance: King starts young with grav crush, windup of it is reduced to 1.5 seconds. To prevent spam, canceling grav crush will still consumme the plama.
balance: Nightfall gain two more range
fix: Nightfall now applies on all electrical lights like it should
/:cl:

2021-06-07 03:20 UTC, RenGusta commented
Y U no separate balance and fix PR my dude

2021-06-07 23:06 UTC, KornFlaks commented
I fall to see how this in any way makes the King a viable option to waste points on rather than plopping down more silos.

I've tried summoning it once and even with a very good xeno player at its controls, it seemed to me to be a worse combat caste than the Queen herself and that's saying something.

If instead of summoning a King, it summons a Boiler, I would definitely consider saving points every single game just for the eventual FOB siege as it would be far more useful.

Yes I know, back when it first TM'ed, the King was brokenly over powered and could solo entire marine landings but in its current state it's something to be coddled like a boiler. Perhaps more given the investment required to create one. If the previous abilities were so overpowered as to be tuned into mere shadows of themselves, perhaps consider going back to the drawingboard and think up of new abilities rather than leaving the vestigial remnants hanging off the shambling corpse that is post-nerf King.

Dont get me wrong, the sprite is great but that is pretty much the only redeeming factor of the 1800 or 2500 point dump.

Apologies if this is off topic to the PR at hand. It appears that my frustration at the waste of points I invested into summoning the king in a game earlier is influencing my commenting.

I just would like to ask you to please reconsider the game design and abilities aspect of the King as, in it's current state, it will never be used.

2021-06-09 13:18 UTC, BraveMole commented
@TiviPlus

2021-06-12 05:24 UTC, SplinterGP requested changes

2021-06-12 05:24 UTC, SplinterGP commented on code/game/atoms.dm
> +	if(forced & !toggle_on) //Is true when turn light is called by nightfall and the light is already on
probably wanted the AND operator
```suggestion
	if(forced && !toggle_on) //Is true when turn light is called by nightfall and the light is already on
```

2021-06-16 10:06 UTC, merged