Add shuffling to diagonal movements
tgstation/TerraGov-Marine-Corps pull request #7072
Opened 2021-06-12 01:04 UTC by BraveMole

## About The Pull Request

You can now shuffle on diagonals

## Why It's Good For The Game

No more frustration for xeno because they were blocked because they were holding two movement keys rather than one

## Changelog
:cl:
qol: Allow to shuffle in diagonal movements
/:cl:

2021-06-12 20:33 UTC, SplinterGP commented on code/game/atoms_movable.dm
> +			olderloc = loc
do you actually need this var at all ? there's oldloc

2021-06-13 22:53 UTC, SplinterGP commented
only TM's allowed

2021-06-14 21:54 UTC, SplinterGP requested changes

2021-06-14 21:54 UTC, SplinterGP commented on code/modules/mob/mob_movement.dm
> +		add_delay *= 1.5
keep this at 2 for now
```suggestion
		add_delay *= 2
```

2021-06-15 08:22 UTC, EgorDinamit commented
Diagonal charge.  :eyes:

2021-06-23 01:05 UTC, SplinterGP commented
i'm gonna close this since i'm not going to deal with it and we don't have other maintainers up to reviewing it.

2021-06-23 01:05 UTC, closed without merging