Switching hugger uses radial + keybind for it
tgstation/TerraGov-Marine-Corps pull request #7089
Opened 2021-06-14 12:52 UTC by BraveMole

## About The Pull Request

Title

## Why It's Good For The Game

More convenient

## Changelog
:cl:
qol: Switching hugger uses radial + keybind for it
/:cl:

2021-06-18 04:06 UTC, Al-1ce commented
You can cook huggies still, right? If so Carrier may become god tier.

2021-06-18 05:00 UTC, SplinterGP approved these changes

2021-06-18 05:06 UTC, SplinterGP requested changes

2021-06-18 05:06 UTC, SplinterGP commented on code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
> +		))
try doing this using less assoc possible, as assoc lists are heavier than normal lists or vars

2021-06-18 15:32 UTC, BraveMole commented on code/__DEFINES/dcs/signals.dm
> +#define COMSIG_XENOABILITY_CHOOSE_HUGGER "xenoability_chooose_hugger"
```suggestion
#define COMSIG_XENOABILITY_CHOOSE_HUGGER "xenoability_choose_hugger"
```

2021-06-20 23:49 UTC, SplinterGP requested changes

2021-06-20 23:49 UTC, SplinterGP commented on code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
> +		))
unneeded list can use typesof?

2021-06-20 23:49 UTC, SplinterGP commented on code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
> +	for(var/obj/item/clothing/mask/facehugger/hugger_type AS in GLOB.hugger_type_list)
```suggestion
	for(var/obj/item/clothing/mask/facehugger/hugger_type AS in typesof(/obj/item/clothing/mask/facehugger))
```

2021-06-20 23:49 UTC, SplinterGP commented on code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
> +	for(var/obj/item/clothing/mask/facehugger/hugger_type AS in GLOB.hugger_type_list)
or subtypes of i dont know if we have that one

2021-06-22 23:46 UTC, merged