adds a tyr helmet module and antenna spinoff
tgstation/TerraGov-Marine-Corps pull request #7093
Opened 2021-06-14 22:59 UTC by Pariah919

## About The Pull Request
adds a tyr helmet module, sprites by kuro
adds an antenna spinoff, sprites by M4Y or whatever it is in russian

## Why It's Good For The Game
tyr helomet module kills head meta, finally
spinoff is pretty cool, i think it's the best sprite in the codebase, not at all bad

## Changelog
:cl:
add: Added antenna spinoff, and tyr helmet module
/:cl:

2021-06-14 23:00 UTC, Kuro-ai commented
yes this is the best addition in the history of additions,I endorse this pr

2021-06-14 23:00 UTC, BraveMole commented
I am bravemole and I endorse this PR

2021-06-14 23:01 UTC, TheBimmer231 approved these changes

2021-06-14 23:03 UTC, lKiseki commented
BRUHMMER HAS BEEN REPLACED BY A CAT, DON'T BELIEVE THIS, KILL THIS PR WITH HOLY FIRE, CAT EARS MUST REMAIN A RELIC OF THE PAST

2021-06-14 23:11 UTC, lovegreenstuff commented
remove all armor from helmets
make armor cover head

2021-06-14 23:19 UTC, Losenis commented
Speedmerge

2021-06-14 23:19 UTC, SplinterGP requested changes

2021-06-14 23:19 UTC, SplinterGP commented on code/modules/modular_armor/helmets.dm
> +	item_state = "antenna_cat"
denied

2021-06-14 23:23 UTC, Kuro-ai commented on code/modules/modular_armor/helmets.dm
> +	item_state = "antenna_cat"
you can't deny progress splinter

2021-06-14 23:37 UTC, SplinterGP requested changes
Also unathomic

2021-06-15 01:02 UTC, Pariah919 commented
jaeger is going to die

2021-06-15 01:02 UTC, closed without merging