Hemodile Buff
tgstation/TerraGov-Marine-Corps pull request #7099
Opened 2021-06-15 11:03 UTC by Surrealaser

## About The Pull Request

1. Hemodile no longer deals stamina damage.

2. Hemodile base slowdown increased from 1 to 1.5.

3. Hemodile slowdown is multiplied by 2 for each other Xeno chem in the victim's system (Neurotoxin and Transvitox).

## Why It's Good For The Game

Makes Hemodile worth a shit.

Adds interesting synergies with other Xeno chems and castes.

## Changelog
:cl:
balance: Hemodile no longer deals stamina damage.
balance: Hemodile base slowdown increased from 1 to 1.5.
balance: Hemodile slowdown is multiplied by 2 for each other Xeno chem in the victim's system (Neurotoxin and Transvitox).
/:cl:

2021-06-15 18:45 UTC, DerrickChamberlain commented
Yikes. I hope marines carry more water.

2021-06-22 23:57 UTC, SplinterGP commented
i don't know if i like that, it removes its stamina reducing stuff and then increases its slowdown as if 1 slowdown aint big already, then allows it to be peaked at 4.5 slowdown which i dont think its a good value since thats like 2x at minimum the ammount of slowdown a marine gets ingame.

2021-06-23 00:09 UTC, Surrealaser commented
> i don't know if i like that, it removes its stamina reducing stuff and then increases its slowdown as if 1 slowdown aint big already, then allows it to be peaked at 4.5 slowdown which i dont think its a good value since thats like 2x at minimum the ammount of slowdown a marine gets ingame.

This is effectively a nerf until it gets the battle royale triple threat stack.

Anyways, again, if we can TM INFINITE SPRINT an obviously retarded idea, we can TM and test this relatively modest change.

2021-06-23 00:33 UTC, SplinterGP commented
> 
> 
> > i don't know if i like that, it removes its stamina reducing stuff and then increases its slowdown as if 1 slowdown aint big already, then allows it to be peaked at 4.5 slowdown which i dont think its a good value since thats like 2x at minimum the ammount of slowdown a marine gets ingame.
> 
> This is effectively a nerf until it gets the battle royale triple threat stack.
> 
> Anyways, again, if we can TM INFINITE SPRINT an obviously retarded idea, we can TM and test this relatively modest change.

please avoid using those type of words you can get banned by github like derick already did

2021-07-05 23:33 UTC, SplinterGP requested changes
the other changes are fine, the multiplying with other chems is way too much and doenst seem like a good mechanic to me.

2021-07-06 04:31 UTC, Surrealaser commented
> the other changes are fine, the multiplying with other chems is way too much and doenst seem like a good mechanic to me.

It is arguably worse than the old Hemodile (which is not impressive) unless you get the trifecta which is not easy to do.

2021-07-06 22:45 UTC, SplinterGP commented
> 
> 
> > the other changes are fine, the multiplying with other chems is way too much and doenst seem like a good mechanic to me.
> 
> It is arguably worse than the old Hemodile (which is not impressive) unless you get the trifecta which is not easy to do.

its better in the slow in the exchange of stamina damage, for me you can just increase the slow and keep the stamina damage, i don't like the idea of scaling up per other chem because the other chem already has their effects, they dont need to double on each other due to that. you inject hemodile and transvitox you get the effect of hemodile and transvitox.

2021-07-07 00:00 UTC, Surrealaser commented
> > > the other changes are fine, the multiplying with other chems is way too much and doenst seem like a good mechanic to me.
> > 
> > 
> > It is arguably worse than the old Hemodile (which is not impressive) unless you get the trifecta which is not easy to do.
> 
> its better in the slow in the exchange of stamina damage, for me you can just increase the slow and keep the stamina damage, i don't like the idea of scaling up per other chem because the other chem already has their effects, they dont need to double on each other due to that. you inject hemodile and transvitox you get the effect of hemodile and transvitox.

Synergies make teamwork more compelling, and it is difficult to actually combo reagents with downside free unlimited gas protection from masks. Further, compounding effects make comboing compelling whereas they currently aren't.

Second, stamina damage steps on the toes of Neuro which is the primary reason I don't like it, besides making the focus of Hemodile too broad.

2021-07-15 15:06 UTC, merged