Alien Slashes Now Attack Bodybag Occupants
tgstation/TerraGov-Marine-Corps pull request #7140
Opened 2021-06-21 09:11 UTC by Surrealaser

## About The Pull Request

Alien Slashes Now Attack Bodybag Occupants

## Why It's Good For The Game

Alien Slashes Now Attack Bodybag Occupants

## Changelog
:cl:
fix: Alien slashes now hit bodybag occupants.
/:cl:

2021-06-21 09:11 UTC, lKiseki commented
Yes. All my yes.

2021-06-21 09:59 UTC, RenGusta commented
Won't this end up hitting hidden tarp users due to the tarp function being similar to bodybags?

2021-06-21 10:18 UTC, BraveMole commented
but why? just open then slash?

2021-06-21 10:29 UTC, BraveMole commented
Say it's because of tarp, because don't think you need to slash bodies in cry bags

2021-06-21 10:41 UTC, Surrealaser commented
> Say it's because of tarp, because don't think you need to slash bodies in cry bags

Well yes, but no bag should provide any slash protection.

2021-06-21 12:16 UTC, RenGusta commented
I still don't see whether or not this will impact bump slash, I can only hope it doesn't?

Otherwise this should probably be labelled balance, not fix.

2021-06-21 12:31 UTC, Surrealaser commented
> I still don't see whether or not this will impact bump slash, I can only hope it doesn't?
> 
> Otherwise this should probably be labelled balance, not fix.

Bump slashing has literally nothing to do with this.

2021-06-22 09:00 UTC, EgorDinamit commented
What about stasis bags? Can xenos open those?
If not, you could just hide in one and be revivable for eternity.

2021-06-22 11:41 UTC, Surrealaser commented
> What about stasis bags? Can xenos open those?
> If not, you could just hide in one and be revivable for eternity.

Yes

2021-06-24 02:49 UTC, SplinterGP requested changes

2021-06-24 02:49 UTC, SplinterGP commented on code/game/objects/items/bodybag.dm
> +		bodybag_occupant.attack_alien(X)
```suggestion
	bodybag_occupant?.attack_alien(X)
```

2021-06-24 06:24 UTC, merged