Make it so the OB beacons always have squad or human name tied to them.
tgstation/TerraGov-Marine-Corps pull request #7145
Opened 2021-06-22 04:20 UTC by lbnesquik

## About The Pull Request
Make it so the OB beacons always have squad or human name tied to them. Like  
`
Orbital beacon (Mandalore gaming)
`
## Why It's Good For The Game
Hopefully make it easier to avoid some friendly fire accidents.

## Changelog
:cl:
add: Added a 
/:cl:

2021-06-23 12:44 UTC, BraveMole requested changes

2021-06-23 12:44 UTC, BraveMole commented on code/game/objects/machinery/squad_supply/supply_beacon.dm
> +		//alt_name.squad_orbital_beacons += src
early return needed : 
if(H.assigned_squad)
		squad = H.assigned_squad
		name += " ([squad.name])"
		squad.squad_orbital_beacons += src
		return
alt_name = H.name
name += " ([alt_name])"

2021-06-23 12:44 UTC, BraveMole commented on code/game/objects/machinery/squad_supply/supply_beacon.dm
> +		name += " ([alt_name])"
```suggestion
		name += " ([H])"
```

2021-06-23 12:44 UTC, BraveMole commented on code/game/objects/machinery/squad_supply/supply_beacon.dm
> +	var/alt_name = null
uneeded

2021-06-23 13:05 UTC, BraveMole commented
Also, how bout the name of the area rather than the squad or human name?

2021-06-23 16:47 UTC, lbnesquik commented
> 
> 
> Also, how bout the name of the area rather than the squad or human name?

Except if we give exact coordinates (which i feel might be a bit too much), areas wont help that much IMO.

2021-06-25 01:57 UTC, SplinterGP approved these changes

2021-06-25 01:57 UTC, merged