Fixes infinite jelly duration
tgstation/TerraGov-Marine-Corps pull request #7156
Opened 2021-06-22 18:44 UTC by QualityVan

Fireproof jelly deactivation relies on a callback to the jelly in question, if it's deleted via being used by two people or acid'd the deactivation never occurs. This shifts it so the xeno is in charge of turning its own effect off. 

Fixes #7054 

:cl:
fix: Jelly shouldn't last forever any more in certain cases.
/:cl:

2021-06-22 18:49 UTC, BraveMole requested changes

2021-06-22 18:49 UTC, BraveMole commented on code/game/objects/structures/xeno.dm
> +/mob/living/carbon/xenomorph/proc/deactivate_jelly()
You need to autodoc new procs.

so here you do this

///Remove the jelly effect from the xenomorph
/mob/living/carbon/xenomorph/proc/deactivate_jelly()

And yes, three /

2021-06-23 00:11 UTC, SplinterGP commented
make resin jelly use status_effects() from code/datums/status_effects instead

2021-06-24 00:50 UTC, SplinterGP requested changes

2021-06-24 00:50 UTC, SplinterGP commented on code/datums/status_effects/xeno_buffs.dm
> +	duration = 150
```suggestion
	duration = 15 SECONDS
```

2021-06-25 01:49 UTC, SplinterGP approved these changes

2021-06-25 01:49 UTC, merged