Cleans up some code to do with hunter stealth and pouncing, stealth cd starts at exit
tgstation/TerraGov-Marine-Corps pull request #7159
Opened 2021-06-22 23:45 UTC by QualityVan

There's code in place for pouncing someone while stealthed, but it never got reached due to the relevant destealth signal firing at pounce start instead of end. It's more or less nothing (1 slowdown 3 stagger) since hunter already inherits runner's 2 second paralyze regardless of stealth.

Also cleans up some duplicate code (attacking out of stealth with harm and disarm intent is line for line identical) and some code that wouldn't be reached (once you unstealth via pounce you can't sneak attack).

Nerfs hunter stealth by making the five second cooldown start when you leave stealth instead of only having a cooldown when you first enter it and when you deactivate it manually, which was weird. Thoughts on this welcome, given its use and plasma cost I'm not sure the cooldown matters at all.

:cl:
fix: Hunter pounce out of stealth now correctly gets its tiny sneak attack bonus
code: Misc. hunter stealth code cleanup
balance: Hunter stealth cooldown starts on leaving stealth.
/:cl:

2021-06-22 23:49 UTC, SplinterGP commented
> Nerfs hunter stealth by making the five second cooldown start when you leave stealth instead of only having a cooldown when you first enter it and when you deactivate it manually, which was weird. Thoughts on this welcome, given its use and plasma cost I'm not sure the cooldown matters at all.

check if this doenst break anything, like keeping getting less visible when toggling it off instantly, the cooldown might just be so you dont break the skill.

2021-06-22 23:51 UTC, QualityVan commented
> check if this doenst break anything, like keeping getting less visible when toggling it off instantly, the cooldown might just be so you dont break the skill.

Did that, stealth hard sets your alpha layer and the callback to enable sneak attacks after stealthing checks to make sure you're still hidden.

2021-06-23 00:09 UTC, SplinterGP commented
> 
> 
> > check if this doenst break anything, like keeping getting less visible when toggling it off instantly, the cooldown might just be so you dont break the skill.
> 
> Did that, stealth hard sets your alpha layer and the callback to enable sneak attacks after stealthing checks to make sure you're still hidden.

understood

2021-06-24 01:30 UTC, SplinterGP requested changes

2021-06-24 02:51 UTC, QualityVan commented on code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
> -
Unless you want some specific effect for disarm strikes distinct from harm ones, it's not doing anything. And if someone decides they do want that later, it's very easy to copy/paste.

2021-06-24 02:55 UTC, SplinterGP commented on code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
> -
just leave it as is please, its intended

2021-06-25 02:21 UTC, SplinterGP approved these changes

2021-06-25 02:21 UTC, merged