Max compilation update
tgstation/TerraGov-Marine-Corps pull request #7169
Opened 2021-06-23 18:03 UTC by BraveMole

We compile on 1556 now.

2021-06-24 00:14 UTC, SplinterGP commented
test 1557

2021-06-24 20:03 UTC, ZephyrTFA commented
> test 1557

1557 works for us upstream

2021-06-25 23:37 UTC, SplinterGP requested changes

2021-06-25 23:37 UTC, SplinterGP commented on code/_compile_options.dm
> +#define MAX_COMPILER_BUILD 1556
```suggestion
#define MAX_COMPILER_BUILD 1557
```

2021-06-26 02:32 UTC, spookydonut commented
https://github.com/tgstation/TerraGov-Marine-Corps/blob/master/dependencies.sh

2021-06-30 20:59 UTC, TiviPlus commented
You need to make it pass ci

2021-07-07 22:29 UTC, SplinterGP requested changes

2021-07-07 22:29 UTC, SplinterGP commented on code/_compile_options.dm
> +#define MIN_COMPILER_BUILD 1557
why did you increase the minimum to 514 ?

2021-07-13 07:24 UTC, TiviPlus requested changes

2021-07-13 07:24 UTC, TiviPlus commented on code/modules/unit_tests/xeno_logical_scaling.dm
> +			var/mob/living/carbon/xenomorph/xeno_mob = new fullxenopath()
use allocate

2021-07-13 07:24 UTC, TiviPlus commented on code/_compile_options.dm
> +#define MIN_COMPILER_VERSION 514
Dont update minimum versions unless it is explicitly to make use of new features

2021-07-14 15:43 UTC, spookydonut commented
Yeah no

2021-07-14 15:43 UTC, closed without merging