Prevent too many xeno at start
tgstation/TerraGov-Marine-Corps pull request #7194
Opened 2021-06-26 11:56 UTC by BraveMole

## About The Pull Request

Xeno get two "free" jobs at roundstart. This is bad because it kinda make the ratio xeno/marines not linear with pop, so this prevents it. The free jobs are needed to let the job system works

Changes crash initial xeno/marines ratio

## Why It's Good For The Game

Consistent ratio.

Also fixes crash ratio that was completly boinkers the only round we played (It was even 12 previously)

## Changelog
:cl:
balance: Remove 2 xenos jobs at roundstart, no matter the pop
balance: Less xeno in crash
/:cl:

2021-06-26 17:16 UTC, David-Stormwell commented
Unneeded from what I've personally seen, if anything make it simply -1?

2021-06-26 20:29 UTC, SplinterGP commented
Crash has a problem(actually every gamemode has it) of low amount of xenis being way too weak while any amount over that is way way stronger, so at crash id like something like minimum amount of xenos

2021-06-26 20:30 UTC, SplinterGP commented
Ive noted this is not only a problem at crash since some days ago we were with a small pop like 50 to 60, xeno numbers wouondt be that big and that caused them to lose frequently (70% of time)

2021-06-27 12:37 UTC, EgorDinamit commented
Now prevent rounds from having too many marines.

2021-06-29 20:28 UTC, KornFlaks commented
11 xenos vs 42. So good.  Xenos been winning too much anyways. I say speedmerge.

2021-06-29 23:56 UTC, Al-1ce commented
Xeno pop isn't linear in accordance to marine pop anyways, since for every Xeno there are generally 5-10 marines.
This feels completely unnecessary and will just end up being a nerf in the long run, those two extra Xenos (commonly drones) tend to make the difference between the map being weeded and not, they may also aid in stopping a full steamroll should they opt for combat castes.

33% - 40% will not matter when you don't have enough ayys to actually defend the Silo, or that the ones you have are barely fresh larva & young.


> Also give back the ratio roundstart xeno vs marine i made 3 months ago, cause apparently marines cannot handle old ratio anymore


Name five people who cannot handle the old ratio.

2021-06-30 00:47 UTC, SplinterGP commented
> Name five people who cannot handle the old ratio.
the old ratio was not ingame has some lots of time

2021-06-30 03:13 UTC, Al-1ce commented
>the old ratio was not ingame has some lots of time

Has..some lots of time? I'm not sure what you intended to say at the end there, but then nothing changes if it has never been implemented. I'll say it again, this TM is unnecessary.

2021-06-30 06:57 UTC, BraveMole commented
> > the old ratio was not ingame has some lots of time
> 
> Has..some lots of time? I'm not sure what you intended to say at the end there, but then nothing changes if it has never been implemented. I'll say it again, this TM is unnecessary.

This was the ratio for 4 months ace. I just modified it 1 week ago, but almost all of pools was played with it

2021-07-03 10:59 UTC, SplinterGP requested changes

2021-07-03 13:48 UTC, Passe2142 commented
Mm the thing was that on crash some funny xenos stored dead colonists and memerines. Crash wise this is chill.

2021-07-03 13:57 UTC, BraveMole commented on code/datums/jobs/job/xenomorph.dm
> +	var/free_xeno_at_start = FREE_XENO_AT_START
both the define and the var is used?

2021-07-15 14:48 UTC, TiviPlus approved these changes
Gonna assume since noones saying anything this is fine

2021-07-15 14:49 UTC, merged