Reduces the prices of some req guns
tgstation/TerraGov-Marine-Corps pull request #7197
Opened 2021-06-27 04:08 UTC by Pariah919

## About The Pull Request
Railgun reduced to 40 from 75, as at 75 you mightas well get a SADAR
AMR/IFF snipper reduced by ten
1 use rpg reduced to 5

## Why It's Good For The Game
Makes lesser used req stuff more appealling

## Changelog
:cl:
balance: Reduced the price of the Railgun, IFF/AMR snipers and 1 use RPGs in req
/:cl:

2021-06-27 10:53 UTC, David-Stormwell commented
Should be 50, in order to leave the option for buffs to it in the future.

2021-07-01 16:44 UTC, TiviPlus requested changes
Remove therailgun change

2021-07-03 23:49 UTC, Pariah919 commented
the railgun is entirely worthless at 75
if you have 75 points just buy  a sadar instead
it'd be more worthwhile at 40, where you have a low bar to entry, and decent cost (You still need 3 points per shot in the first place?)

2021-07-05 23:42 UTC, SplinterGP approved these changes

2021-07-05 23:42 UTC, merged