Fix targeting code
tgstation/TerraGov-Marine-Corps pull request #7198
Opened 2021-06-27 11:59 UTC by BraveMole

## About The Pull Request

Better xeno ability targeting code, should do what the players want 99% of the time while still allowing easier targeting

## Why It's Good For The Game

## Changelog
:cl:
code: Targeting code should allow players to use xeno abilities on the desired target more easily 
/:cl:

2021-06-27 15:42 UTC, MLGTASTICa commented
Super awesome change for xenos

2021-06-27 15:43 UTC, BraveMole commented on code/_onclick/click.dm
> +	if(selected_ability.target_flags & XABB_TURF_TARGET && !isturf(A))
```suggestion
	if(selected_ability.target_flags & XABB_TURF_TARGET)
```

2021-06-27 23:54 UTC, SplinterGP commented
can you keep the define ?

2021-06-30 20:54 UTC, TiviPlus requested changes
Use the define

2021-06-30 21:10 UTC, TiviPlus approved these changes

2021-06-30 21:56 UTC, merged