Kill mesons
tgstation/TerraGov-Marine-Corps pull request #7199
Opened 2021-06-27 12:14 UTC by BraveMole

## About The Pull Request

Remove mesons from game and code

## Why It's Good For The Game

Powergamer gear, prone to multiple bugs (OW, CAS, etc...). This gives a advantages only to a fraction of marines, only because they are rushing/greytiding the engie vendor.

## Changelog
:cl:
del: Mesons are a goner
/:cl:

2021-06-27 12:16 UTC, Jeff-jefferson-jeffery commented
cope

2021-06-27 12:17 UTC, RenGusta commented
Fix them instead of removing them, since according to some dude they have weird behaviour with new lights that isn't intended.

2021-06-27 12:21 UTC, BraveMole commented
> Fix them instead of removing them, since according to some dude they have weird behaviour with new lights that isn't intended.

lel

2021-06-27 12:23 UTC, ilikesaying commented
now remove xenos xray and only give them thermal vision

2021-06-27 13:32 UTC, RenGusta commented
The video in the PR description is the one demonstrating a bug with tac binos, not the one with mesons. Don't be misleading in your PR.

I'd post the correct one but the file size is too large. 

Here's a link anyway. https://cdn.discordapp.com/attachments/504094319075131402/858691433967255582/2021-06-27_13-51-58_online-video-cutter.com.mp4

2021-06-27 13:37 UTC, BraveMole commented
> The video in the PR description is the one demonstrating a bug with tac binos, not the one with mesons. Don't be misleading in your PR.
> 
> I'd post the correct one but the file size is too large.
> 
> Here's a link anyway. https://cdn.discordapp.com/attachments/504094319075131402/858691433967255582/2021-06-27_13-51-58_online-video-cutter.com.mp4

It's a bug due to combination of mesons + binos, not just binos.

mesons are bugged out, period

2021-06-27 14:01 UTC, Georgeur commented
it is practically impossible to not use the bug so long as you're using binos and have mesons, the only reliable way I've found to cancel the bugged effect is by using a rail scope. 

but even with some armor like PAS or Baldur, the effect is virtually 100% night vision.
this is with PAS and mesons, without the bug. 
![image](https://user-images.githubusercontent.com/68168644/123547379-74b45000-d758-11eb-8425-eeaad5e63696.png)

2021-06-27 14:01 UTC, sunofang commented
Okay. And how are you gonna see where you are plasma cutting to?

2021-06-27 14:04 UTC, BraveMole commented
> Okay. And how are you gonna see where you are plasma cutting to?

You just don't. Don't see how that would make a difference anyway

2021-06-27 15:01 UTC, EvilMelonTheSecond commented
Just add it to req bro. 

On a serious note mesons are really valuable for engineers and the only way of using jaeger with baldur. I would much rather have a fix or a roundstart engi gear type of restriction instead of nuking it.

2021-06-27 15:55 UTC, Cowbin commented
I agree with EvilMelonTheSecond.  Just make mesons an item in engie vendors, as they are extremely useful for engineers and plasmacutters.  If you want to lower the amount of greytiding just take them away from anywhere but engineer kit.  Any other complaints about them should be bugfixes, not removals.

2021-06-27 16:02 UTC, AbsoluteJerry commented
Objectively, this is a bad PR. 120% not biased engineer main.

2021-06-27 16:11 UTC, bowlofcereal commented
coping

2021-06-27 16:13 UTC, Katsera commented
this is a massive nerf to CAS. Not even counting the bug that lets you see everything, just being unable to see in the dark kills CAS completely.

2021-06-27 16:14 UTC, Ieteihowmee commented
How about no. What unintended affect has what had on mesons? I have not yet seen it or experienced it. Now test that bug with PAS on and no light, I bet xenos will not show up. Fix it instead of removing it.

2021-06-27 16:16 UTC, Ieteihowmee commented
> it is practically impossible to not use the bug so long as you're using binos and have mesons, the only reliable way I've found to cancel the bugged effect is by using a rail scope.
> 
> but even with some armor like PAS or Baldur, the effect is virtually 100% night vision.
> this is with PAS and mesons, without the bug.
> ![image](https://user-images.githubusercontent.com/68168644/123547379-74b45000-d758-11eb-8425-eeaad5e63696.png)

Binos cause the issue? Interesting. I was thinking in the video brave posted that he was able to see the runner because of the baulder module. Since you CAN see them in some dark spots with mesons but only as far as light will emit and a few tiles out. Interesting. Still, should just fix it instead of remove it. More marine nerfs hold dang.

2021-06-27 16:16 UTC, Katsera commented
also: salt pr

2021-06-27 16:17 UTC, Alexeivichi commented
The community genuinely thinks this is a bad PR. Even worse than MJP's remove valk PR.

2021-06-27 16:17 UTC, BraveMole commented
> this is a massive nerf to CAS. Not even counting the bug that lets you see everything, just being unable to see in the dark kills CAS completely.

Ah yes, this is exactly the kind of stuff that is totally not intented and broken.

2021-06-27 16:18 UTC, MLGTASTICa commented
> this is a massive nerf to CAS. Not even counting the bug that lets you see everything, just being unable to see in the dark kills CAS complet

Dude , CAS is not meant to be able to be used through the dark , its an actual balance change , you need to light up a area if you want to use CAS

2021-06-27 16:19 UTC, Katsera commented
> 
> 
> > this is a massive nerf to CAS. Not even counting the bug that lets you see everything, just being unable to see in the dark kills CAS complet
> 
> Dude , CAS is not meant to be able to be used through the dark , its an actual balance change , you need to light up a area if you want to use CAS

Well then CAS is useless if that's the case.

2021-06-27 16:42 UTC, AbsoluteJerry commented
Just fix mesons instead of removing them completely

2021-06-27 17:44 UTC, AnCopper commented
> Just fix mesons instead of removing them completely

It's a shame that you can't read.

2021-06-27 17:46 UTC, ZahaSanko commented
cope

2021-06-27 22:24 UTC, lovegreenstuff commented
It's weird that you call it limited gear and say it should be in req, but instead of just removing it from every shipside instance and adding it to req, you just delete it in its entirety. 

Also, there's tons of limited supplies that are first come, first serve. Pills and certain guns and equipment come to mind.
Powergaming isn't a reason to delete something in a TDM where winning is the entire goal. 

What do I know? I'm just some dingus playing space game.
It just seems like another silly Bravemole PR with very questionable intentions.

2021-06-27 22:45 UTC, AbsoluteJerry commented
> > Just fix mesons instead of removing them completely
> 
> It's a shame that you can't read.

Explain to me what I missed or shove those words right back into your oxygen wasting mouth.

2021-06-27 22:51 UTC, Captiajoe commented
The mesons give you view of the dark tiles for sure, however you cant see anything that is on that tile, xenos or item until a light is in range of it, try to see a xenos in your corner of your screen that is bathed in darkness, than when it gets close to your armor light you will than see it on mesons and without it, unless that was changed.

2021-06-27 22:52 UTC, Georgeur commented
It does effectively give you night vision, and if you can't hold two separate beliefs at once, like mesons are unbalanced/bugged, but also we should have something to look for cave openings and building layouts. 
Try to use a few braincells, they're not wrong that mesons would be god awful to "fix".

2021-06-27 23:52 UTC, SplinterGP requested changes
you probably said nuuh, but fix the bugs not remove it, its completely possible to fix them as they were sometimes already fixed before.

2021-06-28 00:03 UTC, bowlofcereal commented
there is a distinct massive amount of copium occurring in this comment section

2021-06-29 04:22 UTC, Ragecrabbo commented
Medhud is better anyway

2021-06-29 04:31 UTC, Georgeur commented
I dont want some unrobust people talking the chat, it gives you NV, end of. 
Don't agree with the pr but it should be TM'd until we can find a solution.

2021-06-29 14:30 UTC, usnpeepoo commented
based pr, people crying about mesons being remove when they can't do the same prep routine of tiding mesons like they did with MJP's valk removal pr

2021-06-30 03:04 UTC, Ieteihowmee commented
> > Just fix mesons instead of removing them completely
> 
> It's a shame that you can't read.

Keep in mind. I am pretty sure that was an updated description post fact. But nice try, trying to be smart go you!

2021-06-30 21:07 UTC, TiviPlus commented
Next person to comment off topic means noone gets to comment but me

2021-06-30 21:07 UTC, TiviPlus commented
Next person to comment off topic means noone gets to comment but me

2021-06-30 21:09 UTC, TiviPlus commented on code/modules/clothing/glasses/meson.dm
> -	lighting_alpha = LIGHTING_PLANE_ALPHA_MOSTLY_VISIBLE
why arent you just removing the lighting alpha changes so you can only see as far as the light shines

2021-06-30 21:12 UTC, closed without merging