Changes, Fixes, and New Ranks
tgstation/TerraGov-Marine-Corps pull request #7218
Opened 2021-06-29 15:53 UTC by Captiajoe

Changes and adds new ranks and times to CO
CO 0hrs-30hrs
COMM 30hrs-70hrs
RADM 70hrs-125hrs
VADM 125hrs-1000hrs
ADM 1000hrs on

Fixes and changes ranks and timings on CSE
LTJG 0hrs-25hrs
LT 25hrs-50hrs
LCDR 50hrs-100hrs
CDR 100hrs-1000hrs
CO 1000hrs on

Adds the missing rank progression for CMOs
LT 0hrs-50hrs
LCDR 50hrs-100hrs
CDR 100hrs-1000hrs
CO 1000hrs on

## About The Pull Request

## Why It's Good For The Game

## Changelog
:cl:
add: Added new mechanics or gameplay changes
add: Added more mechanics or gameplay changes
expansion: Expands content of an existing thing
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2021-06-29 15:54 UTC, Captiajoe commented
i have no fucking clue if i did this right but i want my CMO ranks god damnit

2021-06-29 15:56 UTC, SpaceLoveSs13 commented
Cassie the captain rank changes were already proposed once by Nani ans tivi steictly said only 3 ranks, maximum 4. And about other ranks it was 3 ranks too. Now it can be changed obviously but that needs a good reasoning. Your PR is extremely incomplete, please provide a proper reasoning about why it's good for the game.

2021-06-29 15:59 UTC, Captiajoe commented
> Cassie the captain rank changes were already proposed once by Nani ans tivi steictly said only 3 ranks, maximum 4. And about other ranks it was 3 ranks too. Now it can be changed obviously but that needs a good reasoning. Your PR is extremely incomplete, please provide a proper reasoning about why it's good for the game.

i have no idea how github works so ill see if i can change it around

2021-06-29 16:09 UTC, SpaceLoveSs13 requested changes

2021-06-29 16:09 UTC, SpaceLoveSs13 commented on code/datums/jobs/job/shipside.dm
> +			nwe_human.wear_id.paygrade = "06" // CO
Change the var to new, typo here is nwe.

2021-06-29 16:44 UTC, SpaceLoveSs13 approved these changes

2021-06-29 16:44 UTC, SpaceLoveSs13 commented on code/datums/jobs/job/shipside.dm
> +			new_human.wear_id.paygrade = "06" // CO
👍

2021-06-29 16:45 UTC, Captiajoe commented
i have no idea how to fix anything else wrong with how i set this github request up ;~;

2021-06-29 16:47 UTC, SpaceLoveSs13 commented
> i have no idea how to fix anything else wrong with how i set this github request up ;~;

Click the three dots beside ghe pr description, edit then just remove the tags that you don't want and their comments and keep yours. A maintainer will fix the tags once they see it. Don't worry.

2021-06-30 22:41 UTC, SplinterGP approved these changes

2021-07-01 16:19 UTC, TiviPlus commented
I said it once I said it twice and now I saw it thrice:
NO NEW RANKS

2021-07-01 16:19 UTC, closed without merging