Xeno tunnel upgrades: minimap icons, plus fixing tunnel list and a couple bugs
tgstation/TerraGov-Marine-Corps pull request #7221
Opened 2021-06-29 22:24 UTC by QualityVan

Adds markers for xenos to the in-game minimap for tunnels built by hivelords. 
Fixes an issue that caused the Tunnel List verb to not work due to tunnel/hivenumber being assigned a reference instead of a string.
Clears out references to a hivelord from its created tunnels on destruction (usually due to evolving) that caused the tunnel to runtime on its own destruction.

## Changelog
:cl:
add: Hivelord tunnels show up on the minimap
fix: Xeno's Tunnel List verb should work now
/:cl:

2021-06-30 22:02 UTC, QualityVan commented
Didn't know that was a problem, but it looks like yes. Probably fixed by the same thing as tunnels breaking after their creator evolved.

2021-07-02 00:56 UTC, SplinterGP requested changes

2021-07-02 00:56 UTC, SplinterGP commented on code/modules/mob/living/carbon/xenomorph/castes/hivelord/hivelord.dm
> +	return ..()
make this a Register Signal on the tunnel instead

2021-07-11 04:29 UTC, SplinterGP approved these changes

2021-07-11 04:29 UTC, SplinterGP requested changes

2021-07-11 04:29 UTC, SplinterGP commented on code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
> +	newt.RegisterSignal(X, COMSIG_PARENT_QDELETING, /obj/structure/xeno/tunnel/proc/clear_creator)
```suggestion
	newt.RegisterSignal(X, COMSIG_PARENT_QDELETING, /obj/structure/xeno/tunnel.proc/clear_creator)
```

2021-07-13 08:48 UTC, TiviPlus approved these changes

2021-07-13 08:48 UTC, merged