Improved Anti-Shuffle Hug so Carrier Allies Don't Reset Jump Timers
tgstation/TerraGov-Marine-Corps pull request #7230
Opened 2021-07-01 02:17 UTC by Surrealaser

## About The Pull Request

Xenos from the same hive as the one that drops or throws a Facehugger no longer reset that Facehugger's jump timer when they leave its tile.

## Why It's Good For The Game

Xenos from the same hive as the one that drops or throws a Facehugger no longer reset that Facehugger's jump timer when they leave its tile.

## Changelog
:cl:
code: Xenos from the same hive as the one that drops or throws a Facehugger no longer reset that Facehugger's jump timer when they leave its tile.
/:cl:

2021-07-01 15:54 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/facehuggers.dm
> +	var/mob/living/carbon/xenomorph/source
No hard del protection

2021-07-02 01:07 UTC, Surrealaser commented on code/modules/mob/living/carbon/xenomorph/facehuggers.dm
> +	var/mob/living/carbon/xenomorph/source
Fixed probably

2021-07-02 06:35 UTC, TiviPlus requested changes

2021-07-02 06:35 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/facehuggers.dm
> +/obj/item/clothing/mask/facehugger/proc/facehugger_register_source(mob/living/carbon/xenomorph/S)
Autodoc

2021-07-02 06:35 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/facehuggers.dm
> +/obj/item/clothing/mask/facehugger/proc/clear_hugger_source()
Autodoc

2021-07-02 22:05 UTC, TiviPlus approved these changes

2021-07-02 22:06 UTC, merged