Azerty support for keybinds + better perfs on game prefs ui
tgstation/TerraGov-Marine-Corps pull request #7238
Opened 2021-07-01 09:15 UTC by BraveMole

## About The Pull Request

Change the way keybinds are registered (most code is from CM), and separate the data by tabs so it's more performant

This was merged already on https://github.com/tgstation/TerraGov-Marine-Corps/pull/7000 but had merge issues

## Why It's Good For The Game

I can use my whole keyboard, amazing.

Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/5578
Probably closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/6989

## Changelog
:cl:
add: New way of registering keybinds, you have to push the buttons for 2 seconds for it to register
code: better perfs on game prefs ui
/:cl:

2021-07-01 14:07 UTC, lbnesquik commented
God yes.

2021-07-01 20:50 UTC, TiviPlus approved these changes

2021-07-02 06:16 UTC, SplinterGP requested changes

2021-07-02 06:16 UTC, SplinterGP commented on tgui/packages/tgui/interfaces/ButtonKeybind.js
> +export class ButtonKeybind extends Component {
shoulnd't this be in button components file ?

2021-07-03 08:37 UTC, SplinterGP approved these changes

2021-07-03 08:37 UTC, merged

2021-07-03 10:35 UTC, stylemistake reviewed
In my opinion, this could've been implemented much cleaner as a modal that captures all input when visible, instead of a button.

And you should put this KeybindButton separately from the Button component, because it's a very specialized kind of button (you export it separately anyway), and it will be much easier to sync with upstream because Button component will remain untouched.