Allow the hivemind to reach further out of weeds.
tgstation/TerraGov-Marine-Corps pull request #7250
Opened 2021-07-02 17:13 UTC by lbnesquik

## About The Pull Request
Hivemind can now reach further

## Why It's Good For The Game
It makes the hivemind less painful, hopefully making it less common for you to get stuck on island on weeds, especially when marines are spamming grenades. 

## Changelog
:cl:
balance: The hivemind can now reach up to three tiles rather than one.
/:cl:

2021-07-02 17:20 UTC, EvilMelonTheSecond commented
Hiveminds spamming weeds to get in FOB is gonna be even more unbearable. Why not just jump to xenos when you are stuck?

2021-07-02 18:04 UTC, jroinc commented
There's a reason it's so low. The reason is *unkillable hiveminds phasing through walls*.

also you can clicc on weeds to jump to them at any range

2021-07-02 18:58 UTC, lbnesquik commented
> 
> 
> Hiveminds spamming weeds to get in FOB is gonna be even more unbearable. Why not just jump to xenos when you are stuck?

If they can weed the FOB, it means they got weeds literally all over behind, doesn't seem that bad to my eyes. 
Maybe i could try having it so the range extends with age?

2021-07-02 23:26 UTC, jroinc commented
> 
> 
> > Hiveminds spamming weeds to get in FOB is gonna be even more unbearable. Why not just jump to xenos when you are stuck?
> 
> If they can weed the FOB, it means they got weeds literally all over behind, doesn't seem that bad to my eyes.
> Maybe i could try having it so the range extends with age?

Because you haven't seen when they could do that. They can weed through a line of rwalls with 2-tile range.

2021-07-03 01:57 UTC, Elli-Skala commented
I've been playing quite abit of hive mind, and like jronic said, this would allow a hive mind to weed a fob before marines even land.

and being able to click on weed to jump solves most of the problem of being islanded and even being able to cross caps (though I found this after quite abit, maybe a tip of the round about hive mind being able to do this would be good?)

honestly the bigger problem I found with hivemind is that you basically have to have a second chat of just the xeno hive mind so you have links to jump to other xenos due to that being the only way to and not having follow buttons in the hive status like the queen does

2021-07-03 04:08 UTC, lbnesquik commented
I changed the feature. Now, only at the last age can you have three reach. For most of the game, it should be between one and two tiles of range. That should prevent the fob from being weeded early on. 

If the issue persist, then having a check for 'Is this place the FOB' is my next step.

2021-07-03 05:07 UTC, Al-1ce commented
> I changed the feature. Now, only at the last age can you have three reach. For most of the game, it should be between one and two tiles of range. That should prevent the fob from being weeded early on.

IIRC Hivemind takes at least an hour to reach ancient, far beyond the time marines actually land at least. This seems to be a pretty good fix - not to mention allowing weeds to grow that close to the FOB, to begin with should actually have a consequence like this.

2021-07-03 06:35 UTC, Elli-Skala commented
> > I changed the feature. Now, only at the last age can you have three reach. For most of the game, it should be between one and two tiles of range. That should prevent the fob from being weeded early on.
> 
> IIRC Hivemind takes at least an hour to reach ancient, far beyond the time marines actually land at least. This seems to be a pretty good fix - not to mention allowing weeds to grow that close to the FOB to begin with should actually have a consequence.

im liking it so far, though still abit sure as maps with long behind flanks (such as big red) still tend to always have weeds at the flanks even when xenos fully lost, meaning (atleast on big red) youll see ton of "back cap" of xeno resin

2021-07-03 18:55 UTC, BraveMole requested changes

2021-07-03 18:55 UTC, BraveMole commented on code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
> +	var/weeding_range_holder = 1	//Starts at 1 then reaches 3 at the end.
useless

2021-07-03 18:55 UTC, BraveMole commented on code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
> +	var/weeding_range = 1
autodoc, see pins in dev general

2021-07-03 18:55 UTC, BraveMole commented on code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
> +	for(var/obj/effect/alien/weeds/W in range(weeding_range_holder, T ? T : get_turf(src)))
```suggestion
	for(var/obj/effect/alien/weeds/W in range(xeno_caste.weeding_range, T ? T : get_turf(src)))
```

2021-07-03 18:55 UTC, BraveMole commented on code/modules/mob/living/carbon/xenomorph/castes/hivemind/castedatum_hivemind.dm
> +	weeding_range = 1
put that after the max_health var for example, not at random like this

2021-07-05 01:08 UTC, Al-1ce commented
> edit: but it will fix the abit of hell that is hive mind hijacking (outside again like stated above, another chat just for xenomorph comms so you have links to jump to the ship)


The hivemind cannot hijack. Very rarely it can weed into the Alamo but that is entirely the marines fault.

2021-07-05 19:01 UTC, lbnesquik commented
> 
> 
> > edit: but it will fix the abit of hell that is hive mind hijacking (outside again like stated above, another chat just for xenomorph comms so you have links to jump to the ship)
> 
> The hivemind cannot hijack. Very rarely it can weed into the Alamo but that is entirely the marines fault.

Even with three tiles of weeding, it would be pretty obvious when that attempt was happening anyway

2021-07-06 15:03 UTC, TiviPlus commented
Hivemind is too annoying with weeding in places it shouldnt be fix that for this to be considered

2021-07-06 15:03 UTC, closed without merging

2021-07-06 19:04 UTC, Elli-Skala commented
> > > edit: but it will fix the abit of hell that is hive mind hijacking (outside again like stated above, another chat just for xenomorph comms so you have links to jump to the ship)
> > 
> > 
> > The hivemind cannot hijack. Very rarely it can weed into the Alamo but that is entirely the marines fault.
> 
> Even with three tiles of weeding, it would be pretty obvious when that attempt was happening anyway

abit late i know but sorry i wasnt clear

i didnt mean the hive mind trying to hijack the shuttle

i ment playing hivemind during the hijacking phase on the ship because every time your on a weedless tile (often on the unpreped weeds there) youll be kicked back to the planet and need to jump back