Hunter Haunt Replaced With Silence Ability
tgstation/TerraGov-Marine-Corps pull request #7259
Opened 2021-07-03 08:49 UTC by Surrealaser

## About The Pull Request

Silence, New Active Ability (Replaces Haunt)
Plasma Cost: 75
Cooldown: 40 seconds
Effect: All living enemies in a 5x5 area are staggered for ~1 second, have slightly blurred vision and are muted and deafened for roughly 10 seconds. Hunter Mark target is muted and deafened for 50% longer.

## Why It's Good For The Game

Replaces the useless/cosmetic Haunt ability with a useful and thematic stealth and support oriented ability.

## Changelog
:cl:
add: The Silence ability replaces the Haunt ability on the Hunter.
/:cl:

2021-07-03 09:23 UTC, Elli-Skala commented
damn, there goes hunters dabbing on stealth miners knowing where the tad pilot is 24/7

2021-07-03 15:04 UTC, Wayland-Smithy commented
> damn, there goes hunters dabbing on stealth miners knowing where the tad pilot is 24/7

Nope? I don't think think this PR nerfs Hunters Mark at all unless I am reading it wrong.

2021-07-03 20:00 UTC, BraveMole requested changes
Neat ability

2021-07-03 21:02 UTC, Surrealaser commented on code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
> +	var/list/target_turfs = RANGE_TURFS(2, A)
isn't this more performant?

2021-07-03 21:11 UTC, Surrealaser commented on code/modules/mob/living/status_procs.dm
> +/mob/living/proc/IsMute()
Referenced by other procs

2021-07-03 21:19 UTC, Surrealaser commented on code/modules/mob/living/status_procs.dm
> +	return M
Future proofing/standardization of debuffs

2021-07-03 21:22 UTC, Surrealaser commented on code/modules/mob/living/status_procs.dm
> +		M = apply_status_effect(STATUS_EFFECT_MUTED, amount)
I think it's fine; this is the standard for Adjust procs.

2021-07-03 23:52 UTC, QualityVan commented
I'm not sure having a reduced cooldown on whiff is really necessary. Hunter's got good tools to get into range, plus it's a decent size aoe. If you manage to not hit anyone, that sounds firmly like your fault.

2021-07-03 23:55 UTC, Surrealaser commented
> I'm not sure having a reduced cooldown on whiff is really necessary. Hunter's got good tools to get into range, plus it's a decent size aoe. If you manage to not hit anyone, that sounds firmly like your fault.

Wind up.

2021-07-04 05:25 UTC, bobmancer343 commented
I think this ability would be better if it silenced everything that happens in one targetted area because marines can still hear slashing, screaming, gunfire etc

2021-07-04 09:51 UTC, Surrealaser commented on code/modules/mob/living/status_procs.dm
> +			qdel(M)
It's to directly set the mute stacks; if it's 0 or less, mute is nullified, otherwise its existing duration is set to the input amount accordingly.

2021-07-05 01:05 UTC, Al-1ce commented
>an actually creative and class-oriented xeno buff

Cheers.

2021-07-06 15:30 UTC, TiviPlus requested changes

2021-07-06 15:30 UTC, TiviPlus commented on code/__DEFINES/dcs/signals.dm
> +	#define COMPONENT_NO_MUTE (1<<0)
```suggestion
#define COMSIG_LIVING_STATUS_MUTE "living_mute"					//from base of mob/living/Mute()
	#define COMPONENT_NO_MUTE (1<<0)
```

2021-07-06 15:30 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
> +		for(var/mob/living/target as() in targetted.contents)
Use AS instead of as()

2021-07-06 15:30 UTC, TiviPlus commented on code/modules/mob/living/say.dm
>  		return FALSE
Use eiher the disabilities var or traits not both

For example you can make the bitflag be toggled by the status effect

2021-07-06 15:31 UTC, TiviPlus commented
Also you should have a unique icon for the affeced with the status effect

2021-07-10 19:27 UTC, TiviPlus requested changes

2021-07-10 19:27 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
> +	var/list/target_turfs = RANGE_TURFS(2, A)
no it is not

2021-07-10 19:27 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
> +	to_chat(X, "<span class='xenodanger'>We invade the mind of [victim_count] [victim_count > 1 ? "victims" : "victim"], silencing and muting them...</span>") //Notify privately
remove these spammy pointless comments

2021-07-17 20:18 UTC, TiviPlus approved these changes

2021-07-17 20:20 UTC, merged