Fancy lighting
tgstation/TerraGov-Marine-Corps pull request #7263
Opened 2021-07-03 19:46 UTC by TiviPlus

## About The Pull Request
Third times the charm?
## Why It's Good For The Game
Looks cool
Testing with players was apparently fine but if it breaks again im going to try mipmapping instead

## Changelog
:cl:
refactor: Lighting rework
/:cl:

2021-07-03 20:28 UTC, BraveMole requested changes
Yeah i'll probably never try to review the rest cause these vertex manipulation are killing me

2021-07-03 20:28 UTC, BraveMole commented on code/__DEFINES/colors.dm
> +#define LIGHT_COLOR_WHITE		"#FFFFFF"
```suggestion
#define LIGHT_COLOR_WHITE "#FFFFFF"
```

2021-07-03 20:28 UTC, BraveMole commented on code/__DEFINES/colors.dm
> +#define LIGHT_COLOR_RED        "#ff3b3b"
```suggestion
#define LIGHT_COLOR_RED "#ff3b3b"
```

2021-07-03 20:28 UTC, BraveMole commented on code/__DEFINES/lighting.dm
> +#define ALPHA_TO_INTENSITY(alpha) (-(((clamp(alpha, 0, 22) - 22) / 6) ** 4) + 255)
ew

2021-07-03 20:28 UTC, BraveMole commented on code/__DEFINES/lighting.dm
> +#define LIGHTING_ROUND_VALUE    (1 / 64) //Value used to round lumcounts, values smaller than 1/129 don't matter (if they do, thanks sinking points), greater values will make lighting less precise, b
lot of tabs

2021-07-03 20:28 UTC, BraveMole commented on code/__HELPERS/unsorted.dm
> +	GLOB.dview_mob.loc = null
lel this proc is hilarious, thanks byond

2021-07-03 20:28 UTC, BraveMole commented on code/__HELPERS/unsorted.dm
> +	var/ready_to_die = FALSE
autodoc?

2021-07-03 20:28 UTC, BraveMole commented on code/__HELPERS/unsorted.dm
> +	invisibility = 101
101?

2021-07-03 20:28 UTC, BraveMole commented on code/_compile_options.dm
> +//#define SHADOW_DEBUG
?

2021-07-03 20:28 UTC, BraveMole commented on code/controllers/subsystem/evacuation.dm
> +	var/list/alarm_lights = list()
autodoc

2021-07-03 20:28 UTC, BraveMole commented on code/controllers/subsystem/lighting.dm
> +	var/total_shadow_calculations = 0
autodocs?

2021-07-03 20:28 UTC, BraveMole commented on code/controllers/subsystem/lighting.dm
> +	for(updators_num in 1 to static_sources_queue.len)
```suggestion
	for(updators_num in 1 to length(static_sources_queue))
```

even though static_source being null is probably impossible

2021-07-03 20:28 UTC, BraveMole commented on code/controllers/subsystem/lighting.dm
> +	for(updators_num in 1 to corners_queue.len)
```suggestion
	for(updators_num in 1 to length(corners_queue))
```

2021-07-03 20:28 UTC, BraveMole commented on code/controllers/subsystem/lighting.dm
> +	for(updators_num in 1 to objects_queue.len)
```suggestion
	for(updators_num in 1 to length(objects_queue))
```

2021-07-03 20:28 UTC, BraveMole commented on code/controllers/subsystem/lighting.dm
> +	for(updators_num in 1 to mask_queue.len)
```suggestion
	for(updators_num in 1 to length(mask_queue))
```

2021-07-03 20:28 UTC, BraveMole commented on code/modules/lighting/lighting_area.dm
> +		add_base_lighting()
early return

2021-07-03 20:28 UTC, BraveMole commented on code/modules/lighting/lighting_atom.dm
> +/atom/proc/set_light(l_range, l_power, l_color = NONSENSICAL_VALUE, mask_type = null)
autodoc while you are here

2021-07-03 20:28 UTC, BraveMole commented on code/modules/lighting/lighting_atom.dm
> +		return
i don't get why the qdeleted check is not first

2021-07-03 20:28 UTC, BraveMole commented on code/modules/lighting/lighting_atom.dm
> +			QDEL_NULL(light)
if ((!light_power || !light_range) && light)
   QDEL_NULL(light)
   return

2021-07-03 20:28 UTC, BraveMole commented on code/modules/lighting/lighting_atom.dm
> +			QDEL_NULL(light)
you could even put this check with the other one

2021-07-03 20:28 UTC, BraveMole commented on code/modules/lighting/lighting_atom.dm
> +			light = new /datum/dynamic_light_source(src, light_mask_type)
early return

2021-07-03 20:28 UTC, BraveMole commented on code/modules/lighting/lighting_atom.dm
> +	QDEL_NULL(static_light)
return ..()

No?

2021-07-03 20:28 UTC, BraveMole commented on code/modules/lighting/lighting_mask/lighting_mask.dm
> +	color = colour
why does this exist?

2021-07-03 20:28 UTC, BraveMole commented on code/modules/lighting/lighting_mask/lighting_mask.dm
> +	rotate(dir2angle(new_direction) - 180)
should be a macro

2021-07-03 20:28 UTC, BraveMole commented on code/modules/lighting/lighting_mask/shadow_calculator.dm
> +/atom/movable/lighting_mask/proc/triangle_to_matrix(list/triangle)
bad autodoc format

2021-07-03 23:26 UTC, SplinterGP requested changes

2021-07-03 23:27 UTC, SplinterGP requested changes

2021-07-03 23:27 UTC, SplinterGP commented on code/controllers/subsystem/lighting.dm
> +		mask_queue.Cut(1, ++updators_num)
list index out of bounds in here

2021-07-04 08:59 UTC, TiviPlus commented on code/__HELPERS/unsorted.dm
> +#define FOR_DVIEW_END GLOB.dview_mob.loc = null
Why though this is a dview related proc

2021-07-04 08:59 UTC, TiviPlus commented on code/_compile_options.dm
> +//#define SHADOW_DEBUG
It's debug highlighting what do you want me to say it' what it says on the tin

2021-07-04 09:21 UTC, TiviPlus commented on code/controllers/subsystem/lighting.dm
> +		mask_queue.Cut(1, ++updators_num)
Fixed

2021-07-05 22:38 UTC, Al-1ce commented
no way to turn it off? fancy has always lagged me, I know a few other players too with the same issue.

2021-07-05 23:23 UTC, SplinterGP commented
Apparently way more people than me (who has a potato PC so i am to blame) has lag too

2021-07-05 23:41 UTC, Al-1ce commented
>it has to be seen if they werent on 514, which we need to bump for this at minimum.


this is barely english so I don't know if you were saying no one from 514 has had an issue or only people from 514 but I'm on 514 myself and still lagging

![514](https://user-images.githubusercontent.com/71247506/124524388-bcb62100-ddaf-11eb-9f05-ded1e6a07f4f.PNG)

2021-07-18 20:27 UTC, TiviPlus commented
> > it has to be seen if they werent on 514, which we need to bump for this at minimum.
> 
> this is barely english so I don't know if you were saying no one from 514 has had an issue or only people from 514 but I'm on 514 myself and still lagging.
> 
> I should also note I experienced lag on the stable version of BYOND with the fancy lighting which is what drove me to updating to 514.
> 
> ![514](https://user-images.githubusercontent.com/71247506/124524388-bcb62100-ddaf-11eb-9f05-ded1e6a07f4f.PNG)

There was a warning to update when you connect

2021-07-28 11:24 UTC, BraveMole commented on code/modules/client/client_procs.dm
>  #define MIN_RECOMMENDED_CLIENT 1526
and this?

2021-08-04 21:43 UTC, Losenis commented
Add a way to toggle this off, I'm getting like 5fps near fires

2021-08-05 02:42 UTC, Al-1ce commented
> Add a way to toggle this off, I'm getting like 5fps near fires


That's not how it works. Either the entire server has it or they don't. Fancy Lighting is understandable on slower/HRP servers but not fast-paced combat focused stuff like TGMC. It slows the server down and adds nothing in terms of quality.

2021-08-06 19:48 UTC, Losenis commented
Fires are wack
![image](https://user-images.githubusercontent.com/72712909/128563894-c3f272c5-1d73-411c-87b2-bfd4ca8d28dc.png)

2021-08-07 18:28 UTC, TiviPlus commented
Ping me in discord if you see black tiles

2021-08-19 06:42 UTC, Al-1ce commented
unmerge my potato can't take it *warcry

2021-08-19 22:35 UTC, PowerfulBacon commented
I worked on this for months and apart from the hard dels and runtimes causing lag in the original bee PR, I don't think byond is ready for something like this. 
It adds in way too many overlays, it can get up to hundreds for larger light sources (and I think not making the light sources tile bound causes byond to run a really laggy check to see if its in view).
The only way I can see it being done with the shadows is with changes to byond itself.
It needs a way to override the internal byond checks to see if something should be rendered, so that the lights can be rendered if their box is within view. (While typing this I was thinking, could you possible do something like with XRAY flags SEE_MOB or whatever so that you can always see lighting objects through walls, then make them tile bound?)
The other thing that would be a saviour for this lighting method is something like shader editting / a way to edit icons quickly so that instead of having a shit ton of overlays on an object, it can be a single icon where the overlay is generated in some efficient manner idk.

On bee, I've got it in an acceptable condition by adopting the TG overlay lighting approach.
Spinning lighting is still supported, direction lighting is still supported, fire flicker is still supported, however shadows are completely stripped out and the light is only rendered if you can see the source.
For the most part, it works pretty well there is a lot less lag and the effect of lights suddenly appearing isn't too noticeable unless the source is huge.
You could potentially use it for smaller lights, add TILE_BOUND to the lighting and see if that helps with the client lag, then you can have the lights update fast and have the shadows; however the major downside to that is the lights can't move smoothly with the moving object because the shadows dont have a way to animate between shadow states like in SS14.

It's not really a problem with peoples PCs not being able to handle it, its a problem with byond not being optimised / made for something working in this way.

https://github.com/BeeStation/BeeStation-Hornet/pull/5101

I experimented for so long with these and tried everything from overlays, filters, icon manipulation but everything is just simply too slow on the server, or too slow on the renderer.
The only thing I could see being quick in byond is baking every single light into an icon, however it is completely unreasonable to bake every single possible light source and shadow config since you would need millions of icons 😔

2021-08-19 23:06 UTC, Al-1ce commented
I don't really think there is much of a point to this. It doesn't really change how many things look and just slows down the server.

2021-08-19 23:10 UTC, BraveMole commented
> I don't really think there is much of a point to this. It doesn't really change how many things look and just slows down the server.

I don't think you have any data on how this slows or doesn't slow server? Have you really upgraded to the right version? Because you're basically the only one that still complains about performance

2021-08-20 10:35 UTC, TiviPlus commented
> It's not really a problem with peoples PCs not being able to handle it, its a problem with byond not being optimised / made for something working in this way.

Yea agreed lummox even admits byond's rendering isnt very well done and I tried what you stated as well even going as far as to trying to prebake icons in rust code 

As for the shadows things its less the size of them and relly just the massive quantities they're present in
I have some ideas to try minimize them by more selectively rendering them using render target/source but with how large this pr is I'll try to implement that after
I'm also know that this should be more viable with 515 since lummox said that he's fast tracking some more rendering features so hopefully those are useful as well
In the meanwhile though they work fine for centerpieces

2021-08-20 11:02 UTC, SplinterGP commented
Kaboom

2021-08-20 11:02 UTC, merged

2021-08-20 14:10 UTC, Losenis commented
>Because you're basically the only one that still complains about performance

Bro incen HE straight up tanks my game to single digits FPS, just because you don't hear it doesn't mean it's not happening

2021-08-20 14:10 UTC, Losenis commented
>Merged
Aight guess I'm fucking kicked out of anything with fire in a 2 screen radius, that's fucking cool

2021-08-21 05:15 UTC, Al-1ce commented
Can't play here anymore with this PR.

2021-08-21 05:22 UTC, Al-1ce commented
> > I don't really think there is much of a point to this. It doesn't really change how many things look and just slows down the server.
> 
> I don't think you have any data on how this slows or doesn't slow server? Have you really upgraded to the right version? Because you're basically the only one that still complains about performance

Do I as a regular player have multiple charts and elaborate diagrams showing in detail how this slows the server? No. Are you pretending to be daft or something? I'm going by my experience - as well as other people I've talked to in the community who have experienced the same problems in limited or hightened capacity. I can **fucking guarentee** you that I'm not the only person experiencing the issues, as Losenis above has chipped in as well. I _am_ however one of the few people in the community who is willing to talk about the issues with this PR on the github, which again, doesn't represent the entirety of the community. 

I'm not sure how you could miss this so I'm going to assume you did it intently knowing one of your buddies would merge it regardless, as with most PR's here. Majoriety of the server doesn't even know what the github is or how it works, but many people were upset in OOC when the lighting addition(s) were first added to begin with. You're blind to the problem or don't give a shit, and I'm crossed on believing the second option. Whatever. I don't play on severs with fancy lighting, and I won't be playing here anymore because of it.

2021-08-21 08:56 UTC, BraveMole commented
You are saying it is slowing down there sever box. It is not.

You are saying a lot of people complained ooc about fancy lights, when it was first introduced. Okay, but the code was changed and the identified bug and perfs drained were fixed.

Right now, with the pr merge, I don't see anyone complaining about fancy.

You didn't answer the question, what byond version are you?

And you're saying you don't play anymore with fancy, does that mean you never tested the new version with all the bug fixes, that is currently merged?

2021-08-21 17:54 UTC, Losenis commented
It's straight up fucking unplayable with the game tanking to like 3fps. I can't fucking play like this and this shitshow got merged because 'muh graphics' on a fucking BYOND game.
![image](https://user-images.githubusercontent.com/72712909/130330831-f2735b6c-f843-4ca7-b629-77410b405994.png)

2021-08-21 18:50 UTC, february-ops commented
Can corfirm also slows my game, itd beautifull and to do this in byond is amazing but this is combat server and lag and this makes a lot of lag unfortunately

2021-08-21 19:42 UTC, Losenis commented
>Right now, with the pr merge, I don't see anyone complaining about fancy in OOC.

absence of evidence etc

![image](https://user-images.githubusercontent.com/72712909/130333169-e0ed5139-5724-4ce9-a6d8-b01ed74cb01f.png)
![image](https://user-images.githubusercontent.com/72712909/130333171-af135f2a-3a71-4236-b9f1-fd510f69ec75.png)

2021-08-22 00:30 UTC, Al-1ce commented
In my experience, both from the initial TM and even before this was actually merged both time dilation and overall preformance for the server seemingly tanked. Regardless of the bugs that were fixed, you can't polish a turd into a diamond. I'm not trying to be crude or demeaning but that's just how BYOND and lighting seems to work. As PowerfulBacon mentioned above, BYOND is not optimised or made for something working in this way.

Right now, with the current merge just hopping back in the lobby I saw people upset over OOC about the sudden lag. I've talked to several players IRC who haven't played in numerous months, and despite their BYOND being the most recent version things are suddenly "much more slow"

I didn't answer your question about my BYOND version because it isn't relevant to the core structural issue with this - fancy lighting in an engine which is older than the technology & code to create this lighting to begin with. BYOND _at the core_ is not designed to support advanced or fancy lighting. It just isn't.

Again, I'm not sure how hard I have to bang it in but there is a **fundamental** issue with this PR and fancy lighting as a whole.

 If you're absolutely curious, I'm running the current beta version of BYOND whatever that is. Through what I've tested, swapping between the stable and beta version has no effect, and fancy lighting was as far as I can observe, is the only cause for lag.

Yes. I've played with the "bug fixes". I did when I came back to find people upset in OOC about the PR yesterday. You can fix as many bugs as you'd like with this PR and perfect the code, but there is a _**FUNDAMENTAL**_ issue with the Fancy Lighting.

As you can see from the people above, again, I'm not "basically the only one that still complains about performance".

2021-08-22 00:30 UTC, Al-1ce commented
In my experience, both from the initial TM and even before this was actually merged both time dilation and overall preformance for the server seemingly tanked. Regardless of the bugs that were fixed, you can't polish a turd into a diamond. I'm not trying to be crude or demeaning but that's just how BYOND and lighting seems to work. As PowerfulBacon mentioned above, BYOND is not optimised or made for something working in this way.

Right now, with the current merge just hopping back in the lobby I saw people upset over OOC about the sudden lag. I've talked to several players IRC who haven't played in numerous months, and despite their BYOND being the most recent version things are suddenly "much more slow"

I didn't answer your question about my BYOND version because it isn't relevant to the core structural issue with this - fancy lighting in an engine which is older than the technology & code to create this lighting to begin with. BYOND _at the core_ is not designed to support advanced or fancy lighting. It just isn't.

Again, I'm not sure how hard I have to bang it in but there is a **fundamental** issue with this PR and fancy lighting as a whole.

 If you're absolutely curious, I'm running the current beta version of BYOND whatever that is. Through what I've tested, swapping between the stable and beta version has no effect, and fancy lighting was as far as I can observe, is the only cause for lag.

Yes. I've played with the "bug fixes". I did when I came back to find people upset in OOC about the PR yesterday. You can fix as many bugs as you'd like with this PR and perfect the code, but there is a _**FUNDAMENTAL**_ issue with the Fancy Lighting.

As you can see from the people above, again, I'm not "basically the only one that still complains about performance".

2021-08-22 00:31 UTC, Al-1ce commented
In my experience, both from the initial TM and even before this was actually merged both time dilation and overall preformance for the server seemingly tanked. Regardless of the bugs that were fixed, you can't polish a turd into a diamond. I'm not trying to be crude or demeaning but that's just how BYOND and lighting seems to work. As PowerfulBacon mentioned above, BYOND is not optimised or made for something working in this way.

Right now, with the current merge just hopping back in the lobby I saw people upset over OOC about the sudden lag. I've talked to several players IRC who haven't played in numerous months, and despite their BYOND being the most recent version things are suddenly "much more slow"

I didn't answer your question about my BYOND version because it isn't relevant to the core structural issue with this - fancy lighting in an engine which is older than the technology & code to create this lighting to begin with. BYOND _at the core_ is not designed to support advanced or fancy lighting. It just isn't.

Again, I'm not sure how hard I have to bang it in but there is a **fundamental** issue with this PR and fancy lighting as a whole.

 If you're absolutely curious, I'm running the current beta version of BYOND whatever that is. Through what I've tested, swapping between the stable and beta version has no effect, and fancy lighting was as far as I can observe, is the only cause for lag.

Yes. I've played with the "bug fixes". I did when I came back to find people upset in OOC about the PR yesterday. You can fix as many bugs as you'd like with this PR and perfect the code, but there is a _**FUNDAMENTAL**_ issue with the Fancy Lighting.

As you can see from the people above, again, I'm not "basically the only one that still complains about performance".

2021-08-22 17:19 UTC, Hekzder commented
Adding on to this for more anecdotes, noticeable performance decrease since Fancy Lighting is merged that is generally linked to amount of flames on the screen. I am on the latest Byond version and generally have a pretty solid rig, the performance hits for _me_ aren't terrible or crippling in most circumstances but are noticeable and it has gotten me killed on one occasion so far. Incend OBs are serious pain though and are a massive performance hit. 

Generally speaking I just don't understand this PR at all. The added effect/up side seems incredibly minimal, the Ripley and SD spinning lights are cool but how is that (or anything else) worth the performance impact? I can only imagine what this is doing to people on low end rigs. 

> Right now, with the pr merge, I don't see anyone complaining about fancy in OOC.

Brave you're literally coping my man, don't know what to tell you. I've been seeing people complain about Fancy Lighting very frequently the past few days.

2021-08-23 16:06 UTC, Losenis commented
Fire isn't the only issue either. For some reason I'm lagging extremely hard in this particular spot.
![image](https://user-images.githubusercontent.com/72712909/130480083-d84d1862-b7be-45bd-954b-787fbf39e0b7.png)

Code an "off" button so I can opt out of this mandatory 'merged while people were crashing to fire' shenanigans.

2021-08-24 03:54 UTC, Al-1ce commented
I doubt this will get unmerged. They don't give a shit, it's clear.

2021-08-24 03:55 UTC, Al-1ce commented
Hopefully this gets unmerged.

2021-08-24 03:56 UTC, Al-1ce commented
> Code an "off" button so I can opt out of this mandatory 'merged while people were crashing to fire' shenanigans.


You don't seem to understand how this works. Either the entire server has fancy lighting or nobody does. It's all or nothing. I'm hoping it gets unmerged soon but I'm pretty doubtful.