Fix hvh comms
tgstation/TerraGov-Marine-Corps pull request #7272
Opened 2021-07-04 20:38 UTC by BraveMole

## About The Pull Request

Give rebel faction proper comms.

Also remove some station bounced radio, because they are able to listen to the loyalist common channel. 

## Why It's Good For The Game

Proper communication

## Changelog
:cl:
fix: Rebel have their own comms
/:cl:

2021-07-04 20:43 UTC, BraveMole commented on code/game/objects/items/radio/electropack.dm
> +		frequency = sanitize_frequency(frequency)
```suggestion
		frequency = sanitize_frequency(frequency + text2num(href_list["freq"]))
```

2021-07-04 20:44 UTC, BraveMole commented on code/game/objects/items/radio/headset.dm
> +		channel += " Rebel"
i am not even ashamed by this

2021-07-10 18:07 UTC, TiviPlus requested changes

2021-07-10 18:07 UTC, TiviPlus commented on code/game/objects/items/radio/headset.dm
> +		channel += " Rebel"
You should be, Why is it like this

2021-07-10 18:07 UTC, TiviPlus commented on code/__HELPERS/unsorted.dm
> -		. = clamp(frequency, MIN_FREQ, MAX_FREQ)
???

2021-07-15 15:02 UTC, TiviPlus approved these changes
This is better

2021-07-15 15:02 UTC, merged