Lets you choose the type of camo for PAS-11 and M-10 armor
tgstation/TerraGov-Marine-Corps pull request #7282
Opened 2021-07-06 13:50 UTC by CUST-0M

## About The Pull Request

Allows you to choose the camo sprite for the PAS-11 armour vest and M-10 standard helmet. You do this by using it in hand, waiting 3 seconds and choosing whichever colour you want from the menu. 

## Why It's Good For The Game

Lets you be tacticool

2021-07-06 14:02 UTC, BraveMole requested changes

2021-07-06 14:02 UTC, BraveMole commented on code/modules/clothing/head/helmet.dm
> +	var/static/list/helmet_colors = list(
what? why are you redeclaring the colors everytime.

Put that on the item, not in the proc


@@ -305,6 +305,28 @@
/obj/item/clothing/head/helmet/marine/standard
	flags_item_map_variant = (ITEM_JUNGLE_VARIANT|ITEM_ICE_VARIANT|ITEM_PRISON_VARIANT|ITEM_ICE_PROTECTION)
	var/static/list/helmet_colors = list( bla bla bla...

2021-07-06 14:26 UTC, CUST-0M commented
That should fix it. Also made it so that the surplus armor vendor gives /obj/item/clothing/head/helmet/standard instead of /obj/item/clothing/head/helmet since they're the same thing anyway.

2021-07-06 20:18 UTC, SplinterGP requested changes
Too much duplicated code

2021-07-10 18:58 UTC, TiviPlus requested changes
Dupe code, missing Changelog and code churn in code/game/objects/machinery/vending/marine_vending.dm

2021-07-22 00:24 UTC, closed without merging