Fix tarp shooting
tgstation/TerraGov-Marine-Corps pull request #7285
Opened 2021-07-06 15:31 UTC by BraveMole

## About The Pull Request

closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/6943

## Why It's Good For The Game

## Changelog
:cl:
fix: Cannot shoot while tarping anymore
/:cl:

2021-07-08 06:47 UTC, TiviPlus approved these changes

2021-07-09 23:11 UTC, SplinterGP requested changes

2021-07-09 23:11 UTC, SplinterGP commented on code/__DEFINES/traits.dm
> +#define BODYBAG_TRAIT "bodybag" //bodybag
```suggestion
```

2021-07-10 06:17 UTC, SplinterGP approved these changes

2021-07-10 06:18 UTC, SplinterGP requested changes

2021-07-10 06:18 UTC, SplinterGP commented on code/modules/projectiles/gun_system.dm
> +	if(QDELETED(gun_user) || !ismob(gun_user) || !able_to_fire(gun_user) || !target || !isturf(loc))
this ? gun loc is on user
```suggestion
	if(QDELETED(gun_user) || !ismob(gun_user) || !able_to_fire(gun_user) || !target || !isturf(gun_user.loc))
```

2021-07-10 07:40 UTC, BraveMole commented on code/modules/projectiles/gun_system.dm
> +	if(QDELETED(gun_user) || !ismob(gun_user) || !able_to_fire(gun_user) || !target || !isturf(loc))
Lel, I'm dumb dumb

2021-07-10 18:55 UTC, TiviPlus approved these changes

2021-07-10 18:55 UTC, merged