Zeus energy shields. ~Draft WIP PR~
tgstation/TerraGov-Marine-Corps pull request #7310
Opened 2021-07-08 06:52 UTC by David-Stormwell

## About The Pull Request
To be balanced, for now It's just the concept and I made it into a mod for Jeager.
Still a long to-do list which I'd like any other coders or maintainers to assist with.

1: Making Melee be affected same as projectiles/Making the shield tank the melee slashes. I managed to do it solo, but then came the error of the shield completely negating it, which I don't want either.

2: Making a way to check the re-charge and current charge of the shield.

3: Need coder-sprite-work to make the current energy shield look much less off-putting and ugly while not being a giant circle around the mob. 

4: Variants later on are planned once 1, 2 and 3 are finished.  
 
## Why It's Good For The Game
Once balanced, it'll provide a late tier Skirmishing mod, unlike the Valk which is for long constant battles of attrition.
No more having your splint be instantly Qdel'd without needing valk, and moreso in my own opinion balance-able vs the current standard marine shields. 

## Note for coders and maintainers to comment on the code, as I'm still a fairly newbie coder, and I'd like advice or help.

## Changelog
:cl:
add: Added new Jeager energy shields.
/:cl:

2021-07-09 23:18 UTC, SplinterGP requested changes

2021-07-09 23:18 UTC, SplinterGP commented on code/modules/modular_armor/attachables.dm
> +	parent.AddComponent(/datum/component/shield/overhealth/marine)
remove on detach

2021-07-10 19:10 UTC, TiviPlus requested changes

2021-07-10 19:10 UTC, TiviPlus commented on .vscode/settings.json
> +	"workbench.editorAssociations": {},
??

2021-07-11 03:02 UTC, Tristan63 commented
This is cool, will basically be like Spartan shields!

2021-07-22 00:24 UTC, closed without merging