makes packets under one parent and adds a tx-11 ammo packet box, general pouch can now hold packets
tgstation/TerraGov-Marine-Corps pull request #7320
Opened 2021-07-09 06:01 UTC by Pariah919

## About The Pull Request
david asked for the general pouch holding packets and it makes sense as a neat alternative to mag pouch
packets are all under one parent of ammo_magazine/packet
adds tx-11 packet (70x3)

## Why It's Good For The Game

## Changelog
:cl:
expansion: tx-11 has an ammo packet
balance: general pouches can hold ammo packets.
/:cl:

2021-07-10 18:52 UTC, TiviPlus requested changes

2021-07-10 18:52 UTC, TiviPlus commented on code/modules/projectiles/magazines/misc.dm
> +	w_class = WEIGHT_CLASS_NORMAL
inheritance

2021-07-10 20:19 UTC, Pariah919 commented on code/modules/projectiles/magazines/misc.dm
> +	w_class = WEIGHT_CLASS_NORMAL
```suggestion
```

2021-07-10 20:19 UTC, Pariah919 commented on code/modules/projectiles/magazines/misc.dm
> +	name = "box of 10x27mm"
```suggestion
	name = "box of 4.92x34mm"
```

2021-07-12 04:26 UTC, SplinterGP approved these changes

2021-07-12 04:26 UTC, merged