adds an iff-less heavy machinegun
tgstation/TerraGov-Marine-Corps pull request #7351
Opened 2021-07-11 06:30 UTC by Pariah919

## About The Pull Request
adds a heavy machinegun that has no iff, not to marine vendors yet though i'd like to add it as a even heavier counterpart that has no iff for chokepoint holding to the HSG, considering it has no IFF, and aimmode is broken on mounted guns.

## Why It's Good For The Game
Adds more interesting stuff to the marine arsenal.

## Changelog
:cl:
expansion: Adds an IFF-less heavy machinegun to the game, not in yet for acquireable players.
/:cl:

2021-07-11 08:55 UTC, SilencedMP5A5 commented
show sprite

2021-07-11 11:05 UTC, AnCopper commented
> show sprite

![image](https://user-images.githubusercontent.com/82319489/125192543-b8bf4e80-e248-11eb-9545-db30c661323c.png)

2021-07-12 05:40 UTC, lbnesquik commented
Is this a World War one machine gun?

2021-07-12 18:24 UTC, TiviPlus requested changes
The sprite is just an obvious copypaste of the hmg make it better

2021-07-12 22:25 UTC, Pariah919 commented
@TiviPlus i changed the tripod
![image](https://user-images.githubusercontent.com/46353991/125363379-8132ce00-e33e-11eb-8fb0-6794bc8f29a1.png)

2021-07-13 12:41 UTC, BraveMole commented
"not in yet for acquireable players" Why? :(

2021-07-13 18:03 UTC, Tristan63 commented
mg08 aircraft machinegun?

2021-07-13 20:21 UTC, TiviPlus commented on code/modules/projectiles/guns/mounted.dm
> +	name = "\improper MG-08/495 heavy machinegun"
dont use numbers in path names please

2021-07-13 20:21 UTC, TiviPlus commented on code/modules/projectiles/magazines/mounted.dm
> +/obj/item/ammo_magazine/mg08
Ditto

2021-07-13 22:15 UTC, Losenis commented
Finally. Now we can put down marines blocking benos in a few shots instead of having to dump a burst of 20 into them with a GPMG.

2021-07-14 04:36 UTC, lbnesquik commented
No way to spawn this gun

2021-07-14 15:14 UTC, TiviPlus approved these changes

2021-07-14 15:15 UTC, TiviPlus commented on code/modules/projectiles/gun_attachables.dm
> +	name = "MG-08/495 long range ironsights"
you forgot thsi typepath

2021-07-15 09:16 UTC, merged