buffs the automag and deagle by giving them their own bullet
tgstation/TerraGov-Marine-Corps pull request #7374
Opened 2021-07-12 09:13 UTC by Pariah919

## About The Pull Request
45/15/3, staggers, knocks back, no shake however.
Consdering the automag has one second fire delay, it has a 1.1 dmaage mult for 49.5 damage.
Considering these guns fire incredibly slowly I don't think this is too much damage.

## Why It's Good For The Game
The automag and deagle sucks.

## Changelog
:cl:
balance: buffed automag and deagle to do much more damage, stagger and slow xenos on hit
/:cl:

2021-07-12 23:22 UTC, SplinterGP commented
buff the automag more and reduce the deagle one, it has 1.2 damage mult and 0.7 fire delay, also remove knockback.

2021-07-12 23:58 UTC, SplinterGP approved these changes

2021-07-12 23:58 UTC, SplinterGP requested changes

2021-07-12 23:58 UTC, SplinterGP commented on code/modules/projectiles/guns/pistols.dm
> +	desc = "A, powerful semi-automatic pistol chambered in the devastating.50 AE caliber rounds. Used for centuries by law enforcement and criminals alike, recently recreated with this new model."
```suggestion
	desc = "A, powerful semi-automatic pistol chambered in the devastating .50 AE caliber rounds. Used for centuries by law enforcement and criminals alike, recently recreated with this new model."
```

2021-07-13 00:01 UTC, SplinterGP requested changes

2021-07-13 00:01 UTC, SplinterGP commented on code/modules/projectiles/guns/pistols.dm
> +	desc = "A, powerful semi-automatic pistol chambered in the devastating.50 AE caliber rounds. Used for centuries by law enforcement and criminals alike, recently recreated with this new model."
```suggestion
	desc = "A powerful semi-automatic pistol chambered in the devastating.50 AE caliber rounds. Used for centuries by law enforcement and criminals alike, recently recreated with this new model."
```

2021-07-13 00:02 UTC, Pariah919 commented on code/modules/projectiles/guns/pistols.dm
> +	desc = "A, powerful semi-automatic pistol chambered in the devastating .50 AE caliber rounds. Used for centuries by law enforcement and criminals alike, recently recreated with this new model."
```suggestion
	desc = "A powerful semi-automatic pistol chambered in the devastating .50 AE caliber rounds. Used for centuries by law enforcement and criminals alike, recently recreated with this new model."
```

2021-07-13 00:02 UTC, SplinterGP approved these changes

2021-07-13 06:20 UTC, TiviPlus approved these changes

2021-07-13 06:20 UTC, merged