Fix carrier trap not being killed when weeds are destroyed
tgstation/TerraGov-Marine-Corps pull request #7401
Opened 2021-07-13 17:42 UTC by BraveMole

## About The Pull Request

fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/6985

## Why It's Good For The Game

## Changelog
:cl:
fix: Fix carrier trap not being killed when weeds are destroyed
/:cl:

2021-07-13 18:11 UTC, InterroLouis commented
What about acid wells?

2021-07-13 18:11 UTC, BraveMole commented
> What about acid wells?

ah good point, forgot about those

2021-07-13 19:46 UTC, Ieteihowmee commented
Finally! I always thought it was weird most of them did not just break.

2021-07-14 04:41 UTC, Surrealaser commented
Man, this is going to make it way too easy to clear out xeno structures.

Also tunnels should not be subject to this if they are.

2021-07-14 12:00 UTC, QualityVan commented
Tunnels don't require resin to place one initially, it doesn't make sense that they'd die without it.

2021-07-14 18:07 UTC, Ragecrabbo commented
This is going to be a pretty big nerf to xeno structures but a necessary one (atleast for the carrier traps)
Hopefully something will be done to the costs to make up for it as i can see a lot of situations where a marine destroys one weed node and takes out multiple structures alongside it. Traps especially which rely on marines stepping them will have to have multiple nodes around them if you want to ensure they stay around long enough for someone to trigger them.

2021-07-14 20:58 UTC, SplinterGP commented
> Also tunnels should not be subject to this if they are (and they seem to be); it's a literal hole that has no reliance on resin whatsoever.
> 
> Jelly pods should probably not be subject to this given the cooldown involved with making them and their relative durability. If all you need to do to get rid of the things is just destroy the resin beneath them, that's pretty fucked.

^

2021-07-15 09:12 UTC, TiviPlus requested changes
make tunnels and jelly pods immune

2021-07-15 20:28 UTC, BraveMole commented
Tests are succeeding btw

2021-07-16 21:44 UTC, turnop commented
good pr

carrier traps that embed themselves into bedsheets are bull

2021-07-17 08:10 UTC, TiviPlus requested changes

2021-07-17 08:10 UTC, TiviPlus commented on code/__DEFINES/misc.dm
> +#define IGNORE_WEED_REMOVAL (1<<0)
This should not be in misc it shuld use the proper file

2021-07-17 08:10 UTC, TiviPlus commented on code/modules/xenomorph/xeno_structures.dm
> +		var/obj/item/clothing/mask/facehugger/FH = I
early return

2021-07-17 08:10 UTC, TiviPlus commented on code/modules/xenomorph/xeno_structures.dm
> +/obj/structure/xeno/trap/proc/drop_hugger()
autodoc

2021-07-17 08:10 UTC, TiviPlus commented on code/modules/xenomorph/xeno_structures.dm
> +	..()
why are return values not preserved here

2021-07-17 08:10 UTC, TiviPlus commented on code/modules/xenomorph/xeno_structures.dm
> +
early returns

2021-07-17 08:10 UTC, TiviPlus commented on code/modules/xenomorph/xeno_structures.dm
> +	var/mob/living/carbon/xenomorph/hivelord/creator = null
Autodoc

2021-07-17 08:10 UTC, TiviPlus commented on code/modules/xenomorph/xeno_structures.dm
> +	var/drop_loc = get_turf(src)
cast this

2021-07-17 08:10 UTC, TiviPlus commented on code/modules/xenomorph/xeno_structures.dm
> +		to_chat(M, "<span class='warning'>Our crawling was interrupted!</span>")
early return

2021-07-17 08:10 UTC, TiviPlus commented on code/modules/xenomorph/xeno_structures.dm
> +	var/mob/living/carbon/xenomorph/creator = null
autodoc

2021-07-18 20:49 UTC, TiviPlus requested changes
Rest is fine

2021-07-18 20:49 UTC, TiviPlus commented on code/modules/xenomorph/xeno_structures.dm
> +
Put this in a defines file where it belongs

2021-07-18 21:10 UTC, merged