Super Rage Gives Ravager Bloodborne/Life Leech Slashing
tgstation/TerraGov-Marine-Corps pull request #7406
Opened 2021-07-13 21:46 UTC by Surrealaser

## About The Pull Request

If Rage is used while at less than 0 HP, the Ravager will regain HP whenever it slashes a living target equal to 50% to 100% of the damage dealt depending on Rage Power (how low the Ravager's HP was when Rage was used).

## Why It's Good For The Game

Makes Raging and fighting while at critical HP actually worth the risk outside of strict 1 v 1 scenarios because you now might actually not get instantly deleted via life leech.

## Changelog
:cl:
balance: If Rage is used while at less than 0 HP, the Ravager will regain HP whenever it slashes a living target equal to 50% to 100% of the damage dealt depending on Rage Power (how low the Ravager's HP was when Rage was used).
/:cl:

2021-07-14 00:50 UTC, Pariah919 commented
make it so rav can't passively heal when in endure, then

2021-07-14 01:47 UTC, Surrealaser commented
> make it so rav can't passively heal when in endure with rage on, then. As Ravager with this would both passively heal and have leech.

Passive healing is basically irrelevant outside of resting

2021-07-14 06:26 UTC, KrabSpider commented
> > make it so rav can't passively heal when in endure with rage on, then. As Ravager with this would both passively heal and have leech.
> 
> Passive healing is basically irrelevant outside of resting

What about healing infusion?

2021-07-14 07:11 UTC, Surrealaser commented
> > > make it so rav can't passively heal when in endure with rage on, then. As Ravager with this would both passively heal and have leech.
> > 
> > 
> > Passive healing is basically irrelevant outside of resting
> 
> As for healing infusion?

Only applies during defensive fighting (i.e. you need to be on weeds), and is disabled by being on fire. Also the HP regained per tick isn't huge.

2021-07-14 18:24 UTC, Ragecrabbo commented
Fun flavourful addition to rage, dont think it will have too much of an impact as you basically need to be on the brink of death to use it and the health you get from a slash will be equal to one or maybe two marine shots on you.

2021-07-16 03:09 UTC, SplinterGP commented
i don't see why this is much needed or how its balanced, rage already does alot of stuff like sunder and something, what are the needs for it ?

2021-07-16 03:22 UTC, Surrealaser commented
> i don't see why this is much needed or how its balanced, rage already does alot of stuff like sunder and something, what are the needs for it ?

I think I was abundantly clear.

At the moment it is basically suicide to try to benefit from Rage at sub-zero health; this makes the risk/reward a little more viable.

2021-07-17 20:54 UTC, TiviPlus requested changes

2021-07-17 20:54 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
> +		return
```suggestion
```

2021-07-17 20:54 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
> +	UnregisterSignal(X, COMSIG_XENOMORPH_ATTACK_LIVING) //unregister the signals; party's over
```suggestion
	UnregisterSignal(X, COMSIG_XENOMORPH_ATTACK_LIVING)
```

2021-07-17 20:54 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
> +		RegisterSignal(X, COMSIG_XENOMORPH_ATTACK_LIVING, .proc/drain_slash) //We can now regain HP by dealing damage
```suggestion
		RegisterSignal(X, COMSIG_XENOMORPH_ATTACK_LIVING, .proc/drain_slash)
```

2021-07-18 21:09 UTC, TiviPlus approved these changes

2021-07-18 21:52 UTC, Carnage068 commented
> i don't see why this is much needed or how its balanced, rage already does alot of stuff like sunder and something, what are the needs for it ?

Piss off. Thanks.

2021-07-19 07:30 UTC, SplinterGP commented
> 
> 
> > i don't see why this is much needed or how its balanced, rage already does alot of stuff like sunder and something, what are the needs for it ?
> 
> I think I was abundantly clear.
> 
> At the moment it is basically suicide to try to benefit from Rage at sub-zero health; this makes the risk/reward a little more viable.

i mean it can be sometimes but it also gives some big damage increase at some point, i'd say it also goes kinda backwards when the skill itself wants you to have less health in order to deal more damage and not heal it out.

2021-07-19 09:10 UTC, Surrealaser commented
> > > i don't see why this is much needed or how its balanced, rage already does alot of stuff like sunder and something, what are the needs for it ?
> > 
> > 
> > I think I was abundantly clear.
> > At the moment it is basically suicide to try to benefit from Rage at sub-zero health; this makes the risk/reward a little more viable.
> 
> i mean it can be sometimes but it also gives some big damage increase at some point, i'd say it also goes kinda backwards when the skill itself wants you to have less health in order to deal more damage and not heal it out, so it can be counterproductive at some time.

The whole thing with Rage is a risk/reward tradeoff. Unfortunately and especially with MJP's nerf, the risk far outstrips the reward.

Life leech means the risk is ameliorated a bit, hopefully to the point of acceptability/viability, but only by aggressing.

2021-07-23 19:24 UTC, merged