Adds the HMG to marine vendors, HSG rebalance.
tgstation/TerraGov-Marine-Corps pull request #7442
Opened 2021-07-15 11:01 UTC by Pariah919

## About The Pull Request
HSG fires slower, (4 rounds a second from 5), 0.25 fire delay. Not the nested one though, it can stay as is for now.
HMG is added to marine vendors, marines only get one per round for now, they can buy more ammo, but not another one for now, so don't lose it?

-HMG is slower to deploy, has no IFF, has much more ammo (500 rounds) is harder overall to use on the move, as carrying extra ammo requires your back or belt slot.
-HSG fires slower than the HMG, but has IFF. Other than that, it's easier to carry around, as it fits in engi bags, the ammo also fits in a lot more places than the HMG.

## Why It's Good For The Game

## Changelog
:cl:
expansion: Marines get one HMG, it is harder to lug around than a TL-102, has no IFF, but it fires faster, and deploys slower. Better not lose it.
balance: TL-102 HSG fires slower (0.25 fire delay from 0.2), added one cool HMG gun to the marine vendor. Better not lose it.
/:cl:

2021-07-15 16:38 UTC, LoganKele commented
When is this gonna be merged and what vendor is it going to be in?

2021-07-17 05:19 UTC, David-Stormwell approved these changes
In theory, this sounds swell enough, of course though, It requires field testing, and once applied and tested and adjusted if required this should be a swell enough addition.
I'll leave the finer parts of the code for maintainer dissection.

2021-07-17 08:12 UTC, SplinterGP requested changes

2021-07-17 08:12 UTC, SplinterGP commented on code/game/objects/machinery/vending/marine_vending.dm
> +			/obj/item/ammo_magazine/heavymachinegun = 4,
put ammo below gun, forgot that on pepperball you can change this too

2021-07-17 08:22 UTC, SplinterGP requested changes

2021-07-17 08:22 UTC, SplinterGP commented on code/game/objects/machinery/vending/marine_vending.dm
>  			/obj/item/weapon/gun/launcher/m81 = -1,
```suggestion
			/obj/item/weapon/gun/launcher/m81 = -1,
			/obj/item/weapon/gun/heavymachinegun = 1,
			/obj/item/ammo_magazine/heavymachinegun = 4,
```

2021-07-23 22:41 UTC, merged