Lets xenos turn off rail flashlights by slashing the gun
tgstation/TerraGov-Marine-Corps pull request #7450
Opened 2021-07-15 23:23 UTC by QualityVan

## About The Pull Request
Xenos can now attack floor guns to turn off the rail light if there is one.

## Why It's Good For The Game
Tired of infinite pocket pistols lying around providing light forever until one of the castes with acid clears it. If you want lights to leave around as a marine bring flares.

## Changelog
:cl:
add: Slashing guns as a xeno will turn any lights on them off
/:cl:

2021-07-16 01:57 UTC, vilereaver41 commented
<3 thx man

2021-07-16 03:36 UTC, lbnesquik commented
Thank you!

2021-07-16 07:49 UTC, RuneQuester commented
Hello? Based Department?

2021-07-16 08:16 UTC, TheRealMedalis commented
Wouldn't it be easier to just remove the rail flashlight attachment from the pocket pistol options?

2021-07-16 10:05 UTC, David-Stormwell commented
> 
> 
> Wouldn't it be easier to just remove the rail flashlight attachment from the pocket pistol options?

Yes, but that would've not had solved the issue, marine mains would in fact just use other guns.

2021-07-16 10:46 UTC, BraveMole requested changes

2021-07-16 22:38 UTC, joniroq commented
Would it not be simpler to have the raillight turn off when the weapon is dropped? Armor lights turn off then removed so why not gun lights

2021-07-17 08:37 UTC, TiviPlus commented on code/modules/projectiles/gun_system.dm
> +///For letting xenos turn off the flashlights on any guns left lying around.
```suggestion
//For letting xenos turn off the flashlights on any guns left lying around.
```

2021-07-17 13:38 UTC, TiviPlus approved these changes

2021-07-17 21:17 UTC, merged