Facehugger catching
tgstation/TerraGov-Marine-Corps pull request #7506
Opened 2021-07-18 20:17 UTC by QualityVan

## About The Pull Request
Fixes #7499 which was an issue with an object being in two places at once, rather than duplication.
You can catch thrown facehuggers(even leaping ones) with an open hand and throw intent active, but they'll keep trying to attack you. Use in hand to kill it, you monster.
Fixes storages breaking if you put a facehugger inside, the hugger will jump out when you open it now.
Repaths non-larval huggers to condense their similarities and make them not fit on your face.

## Why It's Good For The Game
Fixes things mentioned above, a bit of code improvement, improves some ingame feedback on what huggers are doing.

## Changelog
:cl:
add: Humans can use a hugger in-hand to crush it.
fix: Huggers don't break storage containers and will leap out now.
fix: Catching huggers works now instead of causing quantum huggers.
/:cl:

2021-07-20 01:47 UTC, KrabSpider commented
Does crushing the hugger automatically drop it?

2021-07-20 10:30 UTC, BraveMole commented
I absolutly don't understand why you need to create a new combat hugger type.

2021-07-20 19:21 UTC, QualityVan commented
What's the cost on adding a parent type, what's the benefit to having them separated out, and what's the better way to have them inherit common behavior that isn't shared by their current parent?

2021-07-22 10:50 UTC, TiviPlus requested changes

2021-07-22 10:50 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/facehuggers.dm
> +	flags_equip_slot = 0
NONE

2021-07-22 20:30 UTC, TiviPlus approved these changes

2021-07-22 20:30 UTC, merged