Defender Can Charge From Fortify
tgstation/TerraGov-Marine-Corps pull request #7523
Opened 2021-07-19 07:58 UTC by Surrealaser

## About The Pull Request

Defender can now charge from its Fortify stance when both are off cooldown.

## Why It's Good For The Game

Makes Fortify more viable and improves its ability to be integrated into Defender combos, making Defender play more fluid and flexible.

## Changelog
:cl:
balance: Defender can now charge from its Fortify stance when both are off cooldown.
/:cl:

2021-07-19 15:00 UTC, SpaceLoveSs13 commented
Defenders get extra armor by fortifying and one kf the disadvantages of doing so is delay in movement. Why let this fundamental balance be changed? Plus wouldn't that means they negate the standing up time and directly goes to charging wind.

2021-07-19 19:25 UTC, hyper2snyper commented
make standing up after charge from fortify take longer.

2021-07-19 19:45 UTC, Surrealaser commented
> Defenders get extra armor by fortifying and one of the disadvantages of doing so is delay in standing up. Why let this fundamental balance be changed? Plus wouldn't that means they negate the standing up time and directly goes to charging wind.

This doesn't get around that delay. The cooldown on fortify has to be over before you can charge out of fortify.

2021-07-21 11:17 UTC, BraveMole requested changes

2021-07-21 11:17 UTC, BraveMole commented on code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
> +	var/mob/living/carbon/xenomorph/defender/D = X
![image](https://user-images.githubusercontent.com/25491240/126480377-d223d375-048f-4a00-b425-16ed44690e45.png)

Please surr, this really helps with readability

2021-07-21 21:13 UTC, BraveMole commented on code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
> +	var/mob/living/carbon/xenomorph/defender/D = X
EXACTLY

2021-07-24 09:23 UTC, TiviPlus approved these changes

2021-07-24 10:18 UTC, SplinterGP commented
I think this should have a small tm before merge.

2021-07-26 11:13 UTC, merged