Allow the AI to unbolt their core, added a noise for it too.
tgstation/TerraGov-Marine-Corps pull request #7532
Opened 2021-07-20 11:54 UTC by lbnesquik

## About The Pull Request
This is a simple which allows AI's to unbolt. There is little usage and it will probably get you killed, but hey, the option is here.

## Changelog
:cl:
expansion: Allow the AI to unbolt their core
/:cl:

2021-07-20 11:56 UTC, neohenry commented
The only time AI will unbolt is when xenomorphs hijack and the AI will be unsafe if remained in the AI core.

2021-07-20 14:29 UTC, BraveMole requested changes

2021-07-20 14:29 UTC, BraveMole commented on code/modules/mob/living/silicon/ai/ai_verbs.dm
> +/mob/living/silicon/ai/verb/toggle_anchor()
Don't add new verbs.

Make this an ability with a proper keybind, or something like that

2021-07-20 20:40 UTC, lbnesquik commented
There was a discussion in dev general where that verb usage was said to be okay.

2021-07-21 23:21 UTC, Ieteihowmee commented
Many times this would have been handy

2021-07-22 10:12 UTC, TiviPlus approved these changes

2021-07-22 10:12 UTC, merged