Allow the AI to turn on red alert using ctrl click
tgstation/TerraGov-Marine-Corps pull request #7550
Opened 2021-07-20 21:43 UTC by lbnesquik

## About The Pull Request
This PR allows the AI to turn on swipe related things such as red alert using ctrl click.

## Why It's Good For The Game
This PR raison d'être is that everyone keeps freaking dying, leaving the CIC deserted at the times we need it the most. 
Being that the AI is pretty much 70% of shipside command at any given game, it seems silly for them not to be able to u

## Changelog
:cl:
expansion: Allows the AI to use keycard devices using ctrl click
/:cl:

2021-07-20 21:57 UTC, BraveMole commented
Alt click will probably be very obscure, why not just clicking on the keycart auth? That could show a pop up asking you if you really want to go red alert?

2021-07-21 04:24 UTC, Ieteihowmee commented
Please, this is absolutely needed.

2021-07-21 08:14 UTC, lbnesquik commented
> 
> 
> Alt click will probably be very obscure, why not just clicking on the keycart auth? That could show a pop up asking you if you really want to go red alert?

I could try that, but i'd need to make an interface. I think.

2021-07-21 10:27 UTC, lbnesquik commented
I made the interface.

2021-07-29 23:24 UTC, SplinterGP requested changes

2021-07-29 23:24 UTC, SplinterGP commented on code/modules/security_levels/keycard_authentication.dm
> +	var/synth_activation = 0
autodoc

2021-08-10 22:32 UTC, SplinterGP approved these changes

2021-08-10 22:32 UTC, merged

2021-08-10 23:11 UTC, Ieteihowmee commented
Good work!