Ghost can pray
tgstation/TerraGov-Marine-Corps pull request #7573
Opened 2021-07-21 21:18 UTC by BraveMole

## About The Pull Request

fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/7571

## Why It's Good For The Game

## Changelog
:cl:
fix: Ghost can pray 
/:cl:

2021-07-22 09:56 UTC, TiviPlus requested changes

2021-07-22 09:56 UTC, TiviPlus commented on code/modules/admin/verbs/pray.dm
> -		to_chat(usr, "Your prayers have been received by the gods.")
Fix removing this

2021-07-22 21:03 UTC, SplinterGP commented
Religious ghosts Prayge

2021-07-23 16:11 UTC, BraveMole commented
Not spending an hour on this, don't see a solution to not shitcode

2021-07-23 16:11 UTC, closed without merging