Buffes drone speed on weeds
tgstation/TerraGov-Marine-Corps pull request #7588
Opened 2021-07-22 19:50 UTC by Passe2142

## About The Pull Request

Drones speed were neredf due to being used for the insta larval sting which was nerfed later.

## Why It's Good For The Game

Bringing back their speed on weed will help them prepare and maze/support and do a bit of combat.

## Changelog
:cl:
Drone weed speed: -0.1 to  -0.4.

2021-07-22 19:52 UTC, Pariah919 commented
Drone weed speed was nerfed because they literally ran faster than most castes, could weed, and are reasonably statted overall.
They don't need full weed speed back, considering they can make weeds themselves and already run reasonably fast.

2021-07-22 20:19 UTC, Passe2142 commented
> Drone weed speed was nerfed because they literally ran faster than most castes, could weed, and are reasonably statted overall.
> They don't need full weed speed back, considering they can make weeds themselves and already run reasonably fast.

Currently they are faster off weeds than on them , and they are mostly used as back line caste support and being slow doesnt help them, they run to help other castes.  I dont think its needed for them to be that slow on weeds.

2021-07-22 21:08 UTC, Pariah919 commented
> Currently they are faster off weeds than on them , and they are mostly used as back line caste support and being slow doesnt help them, they run to help other castes. I dont think its needed for them to be that slow on weeds.
>
they're faster on weeds, if you give them back their -0.4 speed up they become runner level fast on weeds and they're already a solid caste on their own, if drone was bad i'd agree but i'd argue it's probably the most solid t1 and this isn't really needed to round it out it's kit, i made the nerf because drone was literally runner fast on weeds with frenzy

2021-07-22 21:36 UTC, InterroLouis commented
> Currently they are faster off weeds than on them , and they are mostly used as back line caste support and being slow doesnt help them, they run to help other castes. I dont think its needed for them to be that slow on weeds.
This just doesn't even compute. No, they're not faster off weeds than on weeds, they still get a minor speed boost on weeds and DEFINITELY don't get a speed boost for not being on weeds.

2021-07-22 22:24 UTC, Passe2142 commented
> > Currently they are faster off weeds than on them , and they are mostly used as back line caste support and being slow doesnt help them, they run to help other castes. I dont think its needed for them to be that slow on weeds.
> > This just doesn't even compute. No, they're not faster off weeds than on weeds, they still get a minor speed boost on weeds and DEFINITELY don't get a speed boost for not being on weeds.

Im testing it and its not that different , got the recording for 0.1 and 0.4, maybe it could be 0.3. Only the ancient drone felt relative faster. Young/Mature are stone in the water.

2021-07-23 05:14 UTC, SilencedMP5A5 commented
speed creep time again?

2021-07-23 22:21 UTC, SplinterGP requested changes
unless you trade something other for it like damage or something i wont let this in since drone is as MJP said very good overall, and aside from skills can compete with runner without much prejudice as a combat caste.

2021-07-24 00:17 UTC, Passe2142 commented
> 
> 
> unless you trade something other for it like damage or something i wont let this in since drone is as MJP said very good overall, and aside from skills can compete with runner without much prejudice as a combat caste.

You did wanted to change its damage mm, 16/16/16/18? A support that its speed its not that different on weeds its not a power creep. Could i change its damage from within this PR? You also wanted it to do 17/17/17/17. Up to ya.

2021-07-24 07:03 UTC, SplinterGP commented
> 
> 
> > unless you trade something other for it like damage or something i wont let this in since drone is as MJP said very good overall, and aside from skills can compete with runner without much prejudice as a combat caste.
> 
> You did wanted to change its damage mm, 16/16/16/18? A support that its speed its not that different on weeds its not a power creep. Could i change its damage from within this PR? You also wanted it to do 17/17/17/17. Up to ya.

yeah you can change on this PR, 16/16/18/18 is fine imo

2021-07-24 14:44 UTC, Passe2142 commented
> 
> 
> > > unless you trade something other for it like damage or something i wont let this in since drone is as MJP said very good overall, and aside from skills can compete with runner without much prejudice as a combat caste.
> > 
> > 
> > You did wanted to change its damage mm, 16/16/16/18? A support that its speed its not that different on weeds its not a power creep. Could i change its damage from within this PR? You also wanted it to do 17/17/17/17. Up to ya.
> 
> yeah you can change on this PR, change title to accomodate it and all, 16/16/18/18 is fine imo

I think its done now, if wanna check it out just in case.

2021-07-24 20:52 UTC, SplinterGP requested changes
Fix your changelog its missing the format

2021-07-24 22:49 UTC, Passe2142 commented
> 
> 
> Fix your changelog its missing the format

Something like that? Sorry im new to this.

2021-07-26 05:32 UTC, SplinterGP commented
> 
> 
> > Fix your changelog its missing the format
> 
> Something like that? Sorry im new to this.

yes thats fine, put 18 damage on elder too.

2021-07-26 09:14 UTC, BraveMole commented
Nice, speed merge

2021-07-29 22:50 UTC, merged