Increases price of fultons, decreases price of ASRS, adds fulton to SL vendor
tgstation/TerraGov-Marine-Corps pull request #7602
Opened 2021-07-24 03:11 UTC by Hekzder

## About The Pull Request

Basically everything in the title, fulton gets a price increase from 5 to 12, ASRS gets a price decrease from 50 to 36, and the fulton is added to the SL vendor at 25 points. 

## Why It's Good For The Game

The ASRS is literally, completely useless in it's current state due to being completely overshadowed by fultons. This is meant to make the fultons somewhat more reasonably priced for their versatility and unlimited uses, while also making the ASRS more appealing. Do you approve the three fulton orders that the Marines put in or just give them an ASRS to use instead? Arguably this still isn't enough to make the ASRS very competitive but it's a step in the right direction and better than doing nothing and keeping things as they are. I'm willing to increase the price of fultons or decrease the price of ASRS further, or both, depending on feedback.

Adding it to the SL vendor makes sense, presents a competitive option to just buying the RB pack every round, and is somewhat of a compromise for fultons being made quite a bit more expensive from req. 

## Changelog
:cl:
add: Fultons can now be purchased from the SL vendor for 25 points
balance: Fultons now cost 12 points from req and the ASRS costs 36 points

/:cl:

2021-07-24 11:37 UTC, BraveMole commented
Really meh, ARSR should just disapear.

Asking req to invest points to get points is silly

2021-07-24 13:32 UTC, EvilMelonTheSecond commented
ASRS pad was for engineers to set up near miners to create a reliable point generator. People mainly used it in FOB due to lazy engineers/hard to secure miners but dragging a xeno corpse to FOB isn't much different than dragging it in to alamo for RO to collect them on cycle. I would say giving out a free ASRS pad at roundstart is a much better idea than fiddling with the price.

And the fulton price change seems unnecessary. High priced fultons will just lead to them being left in the FOB to make sure they aren't lost forever in the satchel of a dead marine.

2021-07-24 14:51 UTC, Hekzder commented
Yeah, probably just going to not be lazy and nerf fultons in a more proper way. Going to draft this for now, though I will address this: 



> Really meh, ARSR should just disapear.
> 
> Asking req to invest that much points to get points is silly

"That much points" is a silly notion when the cheapest Xeno sells for 30 and T2 sells for 40. Killing and selling Young Hunter (752) and selling it pays for the ASRS with a bit left over at that price point.

2021-07-24 15:55 UTC, Hekzder commented
Update the PR, this now makes fultons limited use but still does most of what was originally intended. A fulton price increase and ASRS price decrease. The code for the limited uses is potentially shit, I mostly just stole it from stack code, but it works. Someone can proof me on it and review.

Fultons also added to the req operational vendor at round start per @BraveMole's suggestion, makes sense since they will be becoming limited use and mining comps are already in there.

2021-07-24 19:01 UTC, Al-1ce commented
>I would say giving out a free ASRS pad at roundstart is a much better idea than fiddling with the price.
Yup. 

>And the fulton price change seems unnecessary. High priced fultons will just lead to them being left in the FOB to make sure they aren't lost forever in the satchel of a dead marine.
This would encourage use of the ASRS.

2021-07-24 19:11 UTC, Hekzder commented
> > I would say giving out a free ASRS pad at roundstart is a much better idea than fiddling with the price.
> 
> Yup.
> 
> > And the fulton price change seems unnecessary. High priced fultons will just lead to them being left in the FOB to make sure they aren't lost forever in the satchel of a dead marine.
> 
> This would encourage use of the ASRS.

I'd prefer to stick with Marines just getting a couple free fultons at round start by virtue of it requiring no mapping work, but if the maintainers would prefer a free ASRS at round start in lieu of the free fultons or as well as the free fultons I could go with that. I don't hate the idea. 

With two free fultons at round start and potential to get more via SL vendor I can see the ASRS being more of a sound purchase over buying some fultons, since you can have quite a few people running around with fultons on the ground but they are now limited use and there's always the chance they die and no one ever gets the fultons back. I don't think it would be a waste of points to get an ASRS early on (maybe not right at start of op, but early) and not spend any points on fultons, instead just relying on the SL fultons and the free op fultons for field recovery of Xenos.

2021-07-27 06:08 UTC, SplinterGP requested changes

2021-07-27 06:08 UTC, SplinterGP commented on code/modules/requisitions/fulton.dm
> +/obj/item/fulton_extraction_pack/proc/zero_uses()
No need for this proc just do it where the proc is called.

2021-07-29 12:36 UTC, BraveMole requested changes

2021-07-29 12:36 UTC, BraveMole commented on code/modules/requisitions/fulton.dm
> +	uses -= 1
```suggestion
	uses --
```

2021-07-29 12:36 UTC, BraveMole commented on code/modules/requisitions/fulton.dm
> +	var/uses = 3
autodoc

2021-07-29 12:36 UTC, BraveMole commented on code/modules/requisitions/fulton.dm
> +		return TRUE
do as splinter says. And why return TRUE anyway? You should just qdel when uses reach zero, but certainly not returning before qdel(spirited_away)

2021-08-02 04:08 UTC, Wayland-Smithy commented
> the cheapest Xeno sells for 30

I'd like to reiterate that for those who still disagree with the price increase and use limit. 1 lowest tier xeno pays for the 10 point fulton plus an extra 200% and you still have 2 more uses! Xeno corpses can not decompose and are a pain for other xenos to drag away and even then you are guaranteed to find them when pushing, sometimes at the silo you are heading toward anyway, for free points that can never be deleted once that xeno dies.

2021-08-02 04:25 UTC, Hekzder commented
Got busy and kind of forgot about this for a bit. Will try and address feedback and also hash out some issues soon to get this merge/TM ready. 

One issue I'm running into is that qdeling the fulton too soon, IE in the extract proc like I am now, doesn't play the animation for fultoning the third Xeno fultoned and just qdels them automatically, presumably because the rest of the procs no longer have an item to call from. Someone with more coding knowledge than me can probably help as to where the best position to place the proc is to prevent this. 

Placing it at the very end when it's running clean up for the extract causes the fulton to linger at zero uses for a few seconds, and then disappears once the entire animation and everything is done. Which _works_ but is obviously less than ideal in a pretty big way.

2021-08-02 15:44 UTC, Hekzder commented
The deletion proc upon zero uses now actually works thanks to some help from QV in Discord. This should be good for another review pass and/or a merge of some kind.

2021-08-04 10:40 UTC, TiviPlus requested changes

2021-08-04 10:40 UTC, TiviPlus commented on code/modules/requisitions/fulton.dm
> +	..()
. = ..()

2021-08-04 10:40 UTC, TiviPlus commented on code/modules/requisitions/fulton.dm
> +	var/uses = 3 //How many times you can use the fulton before it goes poof
autodoc

2021-08-04 10:40 UTC, TiviPlus commented on code/__DEFINES/loadout.dm
> +		/obj/item/fulton_extraction_pack = list(CAT_LEDSUP, "Fulton Extraction Pack", 22, "orange"),
```suggestion
		/obj/item/fulton_extraction_pack = list(CAT_LEDSUP, "Fulton Extraction Pack", 20, "orange"),
```

2021-08-04 14:53 UTC, Hekzder commented on code/modules/requisitions/fulton.dm
> +	..()
?

2021-08-04 14:53 UTC, Hekzder commented on code/modules/requisitions/fulton.dm
> +	var/uses = 3 //How many times you can use the fulton before it goes poof
?

2021-08-04 15:08 UTC, Hekzder commented on code/modules/requisitions/fulton.dm
> +	var/uses = 3 //How many times you can use the fulton before it goes poof
Should be fixed.

2021-08-04 15:08 UTC, Hekzder commented on code/modules/requisitions/fulton.dm
> +	..()
Should be fixed.

2021-08-04 15:47 UTC, SplinterGP requested changes

2021-08-04 15:47 UTC, SplinterGP commented on code/modules/requisitions/fulton.dm
> +	uses --
```suggestion
	uses--
```

2021-08-04 21:24 UTC, TiviPlus commented on code/modules/requisitions/fulton.dm
> +		usr.temporarilyRemoveItemFromInventory(src) //Removes the item without qdeling it, qdeling it this early will break the rest of the procs
user not usr

2021-08-05 02:24 UTC, Hekzder commented on code/modules/requisitions/fulton.dm
> +		usr.temporarilyRemoveItemFromInventory(src) //Removes the item without qdeling it, qdeling it this early will break the rest of the procs
Done.

2021-08-06 04:12 UTC, Pariah919 commented
IMO I like this other than the fact that i feel like there could be one use fulton packs
Marines have a deficit of utility items that they can bring outside of certain stuff and one use fulton packs could fill that niche very well in exchange for being storage inefficent as heck, and being decently limited (make them unbuyable, as the multi use one would outdo them anyway.)

2021-08-07 01:55 UTC, Hekzder commented
> IMO I like this other than the fact that i feel like there could be one use fulton packs
> Marines have a deficit of utility items that they can bring outside of certain stuff and one use fulton packs could fill that niche very well in exchange for being storage inefficent (normal sized or small) as heck, and being decently limited (make them unbuyable, as the multi use one would outdo them anyway, unless you make them like 3 points per).

I don't mind this idea but would prefer to pursue it in a separate PR once we have a finalized sprite for it and to not delay this PR getting potentially merged any longer.

2021-08-10 01:43 UTC, joniroq commented
This sucks. Getting marines to carry a fulton pack to actually fulton corpses is hard enough as it is. making it limited use makes it even less worthwhile

2021-08-10 03:58 UTC, Hekzder commented
> This sucks. Getting marines to carry a fulton pack to actually fulton corpses is hard enough as it is. making it limited use makes it even less worthwhile

You get two free fultons in operational vendor and SLs can buy them without using req points. With potentially four SLs and the two free fultons from req, with this PR there should overall be _more_ fultons in the hands of Marines, just the fultons that they are using aren't completely broken and unlimited use point generators. If you can't find two Marines out of the entirety of the Marine force that are willing to take and use a fulton it's probably like 10 pop and fultons don't matter because it's Crash.

2021-08-10 22:31 UTC, merged