Stalemate respawn buff
tgstation/TerraGov-Marine-Corps pull request #7613
Opened 2021-07-25 11:17 UTC by BraveMole

## About The Pull Request

If a stalemate is detected by the monitor (Xeno and Marines having the same forces for 15 minutes) and a lot of ghosts are waiting to play, the monitor will reduce the respawn time by 5 minutes every 5 minutes and will give xeno some larva points

So for exemple, if a stalemate is running for 30 minutes straight and there is in average 30 ghosts:
Every ghost will have it's respawn time lowered to 15 minutes rather than 30
Xeno will gain 4 new xeno (compare this to roughly 11 "free" marines)

## Why It's Good For The Game

In some games, everyone died and no one is able to take the upperhand. This leads to games where a majority of the players is watching other play; and this will keep on going because none of the factions is able to destroy the other.

Hence, if the game is balanced and in a stalemate, we allow more players to come back to play quicker

## Changelog
:cl:
add: In a situation of stalemate, marine and xeno respawn will be buffed
/:cl:

2021-07-25 21:44 UTC, MereWalker commented
An interesting fix! Look forward to it!

2021-07-26 11:39 UTC, TiviPlus requested changes

2021-07-26 11:39 UTC, TiviPlus commented on code/controllers/subsystem/monitor.dm
> +	log_game("5 minutes were removed from the respawn time of everyone, xeno won : [length(GLOB.observer_list) * 0.75 * 5] larvas")
Elaborate the message admins please

2021-07-26 11:45 UTC, BraveMole commented on code/controllers/subsystem/monitor.dm
> +	message_admins("Respawn buff system in action")
```suggestion
	message_admins("Stalemate detected, respawn buff system in action : 5 minutes were removed from the respawn time of everyone, xeno won : [length(GLOB.observer_list) * 0.75 * 5] larvas")
```

2021-07-29 20:46 UTC, TiviPlus approved these changes

2021-07-29 20:46 UTC, merged