readds 88mod stock, makes it buff 88mod quite a bit, reduces basefalloff
tgstation/TerraGov-Marine-Corps pull request #7616
Opened 2021-07-25 12:04 UTC by Pariah919

## About The Pull Request
88mod is pretty bad, just about nobody ever uses it, and honestly the stock should make it into a different gun overall.
-It increases aim slowdown, and wield delay to rifle level
-Gives it +1 to burst and 0.15 fire delay

## Why It's Good For The Game
Makes the 88mod into a more unique firearm rather than a meme you'll see a PVT pick once a year.

## Changelog
:cl:
balance: 88mod has it's stock back, makes it buff the guns firerate, burst amount at the cost of slowdown and wield speed increases. Falloff reduced to 0.5 from 1.
/:cl:

2021-07-25 16:04 UTC, Alterist commented
YES

2021-07-25 21:40 UTC, MereWalker commented
Im not really a fan of the mod too much. I use the tp45 often than most other guns. I however look forward to this. Could be a good medic gun.

2021-07-26 02:03 UTC, davidchan13 commented
I'd you're trying to buff the automatic pistol I'd suggest giving it more capacity than it's semiauto counterpart per mag (21 on tp14 vs 18 on 88mod)

2021-07-30 18:03 UTC, Kuro020 approved these changes
👍

2021-08-01 10:43 UTC, TiviPlus requested changes

2021-08-01 10:43 UTC, TiviPlus commented on code/modules/projectiles/gun_attachables.dm
> +
Autodoc

2021-08-01 10:43 UTC, TiviPlus commented on code/modules/projectiles/gun_attachables.dm
> +		return ..()
Uneded elsifs

2021-08-01 10:43 UTC, TiviPlus commented on code/modules/projectiles/gun_attachables.dm
> +		return ..(over_object)
uneeded args passed to ..()

2021-08-01 10:43 UTC, TiviPlus commented on code/modules/projectiles/gun_attachables.dm
> +	. = ..()
uneeded . = ..()
just use ..()

2021-08-12 23:02 UTC, Pariah919 commented
ehh
i'll fix this up one day, on further thought

2021-08-12 23:02 UTC, closed without merging