AI notifications tweaks
tgstation/TerraGov-Marine-Corps pull request #7644
Opened 2021-07-27 18:06 UTC by lbnesquik

## About The Pull Request
This PR has a few things bundled in together because i am a lazy POS : 
- Change the dropship take off notifications to be more accurate
- Fix the CAS laser notification giving coordinates to the AI core instead of the actual target
- Expand on the signal stuff i was shown so it works for the tadpole as well. It was rather difficult to test. Next stop, CAS plane.

## Why It's Good For The Game
Good signals, when they work.

## Changelog
:cl:
expansion: Expands content of an existing thing
fix: fixed a few things
/:cl:

2021-08-01 10:09 UTC, TiviPlus requested changes

2021-08-01 10:09 UTC, TiviPlus commented on code/modules/mob/living/silicon/ai/ai.dm
> +	UnregisterSignal(SSdcs, COMSIG_GLOB_TADPOLE_LANDED)
🍝 

Also just use a list() and unregister them all at once

2021-08-01 10:09 UTC, TiviPlus commented on code/modules/mob/living/silicon/ai/ai.dm
> +mob/living/silicon/ai/proc/notify_tadpole_movement_returning(datum/source)
Autodoc + missing /

2021-08-01 10:09 UTC, TiviPlus commented on code/modules/mob/living/silicon/ai/ai.dm
> +mob/living/silicon/ai/proc/notify_tadpole_movement_returning(datum/source)
Also dest isnt cast

2021-08-01 10:09 UTC, TiviPlus commented on code/modules/shuttle/mini_dropship.dm
> +	//	return
??

2021-08-01 10:09 UTC, TiviPlus commented on code/modules/shuttle/navigation_computer.dm
??

2021-08-01 17:01 UTC, lbnesquik commented on code/modules/shuttle/mini_dropship.dm
> +	//	return
Testing leftovers

2021-08-01 17:01 UTC, lbnesquik commented on code/modules/shuttle/navigation_computer.dm
Testing leftovers

2021-08-04 10:34 UTC, TiviPlus approved these changes

2021-08-04 10:34 UTC, merged