Allow everyone to pray
tgstation/TerraGov-Marine-Corps pull request #7675
Opened 2021-07-29 16:44 UTC by lbnesquik

## About The Pull Request
This put the verb on /client/ instead of /mob/

fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/7571

![image](https://user-images.githubusercontent.com/24830358/127531842-43775476-2450-4675-bf9e-1f913f1e0d24.png)

## Changelog
:cl:
qol: Allow everyone to pray!
/:cl:

2021-07-29 16:44 UTC, lbnesquik commented
fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/7571

2021-07-29 17:48 UTC, lbnesquik commented
![image](https://user-images.githubusercontent.com/24830358/127540406-dd305f5c-cb04-4644-abb5-f81465fc13ff.png)

2021-07-29 18:09 UTC, BraveMole requested changes

2021-07-29 18:09 UTC, BraveMole commented on code/modules/admin/verbs/pray.dm
> +					liaison = TRUE
what the fuck is that ?????

2021-07-29 19:04 UTC, Losenis commented
![image](https://user-images.githubusercontent.com/72712909/127551078-eed120df-d182-4ad0-91cb-db867dd7ebab.png)

2021-07-29 19:15 UTC, BraveMole requested changes

2021-07-29 19:15 UTC, BraveMole commented on code/modules/admin/verbs/pray.dm
> +		if(ishuman(usr))
a human is already a mob

2021-07-29 19:18 UTC, lbnesquik commented on code/modules/admin/verbs/pray.dm
> +		if(ishuman(usr))
agh

2021-07-30 21:02 UTC, TiviPlus approved these changes

2021-07-30 21:02 UTC, merged