Adds a new rifle type to marines-Skirmish Rifle
tgstation/TerraGov-Marine-Corps pull request #7692
Opened 2021-07-30 20:51 UTC by Pariah919

## About The Pull Request
Adds the T-21 Skirmish rifle, filling the void between a battle rifle and an assault rifle.
It does 30/10/1.5, fires Heavy bullets and it's packet is 125 rounds

## Why It's Good For The Game
Adds a new class of rifle which bridges a gap we really don't have right now, and hopefully opens up new styles of play. 
It also looks and sounds great.

## Changelog
:cl:
add: Added new Skirmish Rifle (T-21) to marines, it bridges the gap between a Battle rifle and a Assault rifle. It is 0.2- 30/10/1.5. Aim mode stats are +0.15 and 2.5.
/:cl:

2021-07-30 20:53 UTC, Kuro020 approved these changes
the blandest gun in the west, but it's ok

2021-07-30 20:55 UTC, David-Stormwell commented
> the blandest gun in the west, but it's ok

go harder on him, we both know the tan and middle section which looks like it was ripped from a carbine don't look swell.

2021-07-30 22:50 UTC, Kuro020 commented
> > the blandest gun in the west, but it's ok
> 
> go harder on him, we both know the tan and middle section which looks like it was ripped from a carbine don't look swell.

but the actual g3 is like that so uhhhhhhhhh

2021-07-31 00:28 UTC, Tristan63 commented
totally NOT a g3a3

2021-08-01 19:32 UTC, davidchan13 commented
Interesting idea but why does the step between the T-12 and T-64 have less mag capacity than both of them?

2021-08-02 04:58 UTC, Hekzder commented
I do agree with David that 25 rounds is incredibly low and doesn't make a lot of sense. Maybe 30 at least?

 I also feel with these kinds of stats it will just make the battle rifle even more obsolete? Though IMO that's more an issue of the battle rifle not being very good and less an issue of this being too power creep. If this does end up becoming a standard weapon I feel like a BR buff is even more overdue. Battle rifle will effectively fire almost half the speed while also being slower to handle for +2.5 damage, +5 penetration, +0.5 sunder, a somewhat larger magazine, and the bullets travel further. The bonuses you get for using the battle rifle, while there are a few, are incredibly small in nature and probably not worth it.

2021-08-02 08:30 UTC, SplinterGP requested changes

2021-08-02 08:30 UTC, SplinterGP commented on code/modules/projectiles/ammo_datums.dm
> +
absurd stats for same firerate as the T-12

2021-08-02 19:55 UTC, Hekzder commented
Should probably add a T-21 magazine box to the req operational vendor as well.

2021-08-04 03:17 UTC, Kuro020 requested changes
![image](https://user-images.githubusercontent.com/52428261/128116700-4736164a-fa76-4c5d-9e07-c1e905c7a94d.png)
mob sprites are awful, fix

2021-08-04 03:25 UTC, Kuro020 approved these changes

2021-08-04 06:04 UTC, Hekzder commented
Very cool, quite fun, and pretty well balanced as my first impressions. Seems like a pretty good addition.

2021-08-05 01:29 UTC, Al-1ce commented
This is good. Very good. I'm a x*no main but I've tested around with this and it seems pretty balanced to me. Fills the niche that the T-37 should've.

2021-08-05 01:42 UTC, Tristan63 commented
> I do agree with David that 25 rounds is incredibly low and doesn't make a lot of sense. Maybe 30 at least?
> 
> I also feel with these kinds of stats it will just make the battle rifle even more obsolete? Though IMO that's more an issue of the battle rifle not being very good and less an issue of this being too power creep. If this does end up becoming a standard weapon I feel like a BR buff is even more overdue. Battle rifle will effectively fire almost half the speed while also being slower to handle for +2.5 damage, +5 penetration, +0.5 sunder, a somewhat larger magazine, and the bullets travel further. The bonuses you get for using the battle rifle, while there are a few, are incredibly small in nature and probably not worth it at that point.

battle rifle has always been obsolete

2021-08-10 22:40 UTC, SplinterGP requested changes

2021-08-10 22:40 UTC, SplinterGP commented on code/modules/projectiles/ammo_datums.dm
> +
i say still reduce this sunder to like 1 or 1.25

2021-08-11 04:48 UTC, David-Stormwell approved these changes
Should be fine as is, feel free to enforce that sunder change though other things deal more sunder, so it really shouldn't matter.

2021-08-11 09:34 UTC, lbnesquik commented
I think we are done here. I'm up for a full merge.

2021-08-11 20:33 UTC, AnCopper commented
MJP is incapable of creating anything other than old war era guns.

2021-08-12 21:34 UTC, merged