adds tyr helmet attachment
tgstation/TerraGov-Marine-Corps pull request #7695
Opened 2021-07-30 23:00 UTC by Pariah919

## About The Pull Request
makes tyr mod 1 come in a set
+10 armor

## Why It's Good For The Game
tyr helmet attachment has been needed for a while

## Changelog
:cl:
add: Added new tyr helmet attachie. +10 To all armor stats. 15 to melee.
/:cl:

2021-07-31 00:05 UTC, turnop commented
yes god please

2021-07-31 00:10 UTC, Kuro020 approved these changes
sprite good

2021-07-31 00:38 UTC, Tristan63 commented
ballistic helmet module incoming?

2021-07-31 11:39 UTC, TiviPlus approved these changes

2021-07-31 21:19 UTC, bowlofcereal commented
This existed a long while ago im pretty sure I dont remember why it was removed but not having it invalidates the tyr mk2 because of head aiming meta

2021-08-01 03:02 UTC, SplinterGP requested changes
add it for tyr mk2

2021-08-01 15:04 UTC, SplinterGP requested changes

2021-08-01 15:04 UTC, SplinterGP commented on code/game/objects/machinery/vending/new_marine_vendors.dm
> +		/obj/effect/essentials_set/tyr,
Think thats a typo

2021-08-01 15:22 UTC, SplinterGP approved these changes

2021-08-01 15:28 UTC, merged