adds a marine flaregun and makes it fit in flare pouches
tgstation/TerraGov-Marine-Corps pull request #7709
Opened 2021-07-31 15:33 UTC by Pariah919

## About The Pull Request
makes a marine flaregun, makes flareguns tiny, makes them fit in flare pouches (only one though, makes some sense and makes flare pouch a more viable option to give you a reason to pick it over grenade pouch)
flare guns have miniscope level range of zoom now, not as good as binoculars but you can fire flares.
Flaregun flares now stop where you click.

## Why It's Good For The Game
Adds another interesting option to the marine arsenal of weaponry and gives a pouch a little more utility than it used to.

## Changelog
:cl:
add: Added new marine flaregun, it can look out to miniscope distance. Fits in your flare pouches too.
qol: flaregun fired flares now stop where you click.
balance: flareguns now have miniscope level range of zoom on them, when you zoom on them.
/:cl:

2021-07-31 16:15 UTC, Kuro020 approved these changes
Cute lil gun

2021-08-01 09:56 UTC, TiviPlus requested changes

2021-08-01 09:56 UTC, TiviPlus commented on code/modules/projectiles/gun_attachables.dm
> +	desc = "An unremovable set of long range ironsights for a flaregun."
/obj/item/attachable/scope/unremovable ?

2021-08-01 16:54 UTC, TiviPlus commented on code/game/objects/items/storage/pouch.dm
> +	storage_type_limits = list(/obj/item/weapon/gun/flare = 1)
```suggestion
	storage_type_limits = list(/obj/item/weapon/gun/flare = 1)
```

2021-08-01 16:54 UTC, TiviPlus commented on code/modules/projectiles/guns/misc.dm
> +	starting_attachment_types = list(/obj/item/attachable/scope/unremovable/flaregun)
```suggestion
	fire_delay = 0.5 SECONDS
	starting_attachment_types = list(/obj/item/attachable/scope/unremovable/flaregun)
```

2021-08-01 18:48 UTC, TiviPlus approved these changes

2021-08-01 19:13 UTC, merged