Fixes King Minimap Icon
tgstation/TerraGov-Marine-Corps pull request #7763
Opened 2021-08-04 06:01 UTC by KornFlaks

## About The Pull Request

Currently king minimap icons uses, for some reason, queen golden crown instead of the specifically sprited red crown. This fixes the bug by relocating the proc call of set minimap icon to after the king is spawned.

## Why It's Good For The Game

No longer will there be two queens wandering around on the minimap. The king gets their own specially sprited red crown, as intended.

## Changelog
:cl:
fix: Fixed King minimap icon to proper red crown.
/:cl:

2021-08-04 20:27 UTC, KornFlaks commented
Wait no, it works already in production?

![image](https://user-images.githubusercontent.com/29745705/128250063-a366aaef-c3b2-4644-b53f-e42c9a86dd15.png)

Well anyways, this removes the runtime error on local hosted server while also properly assigning the minimap icon.

2021-08-05 00:26 UTC, KornFlaks commented
Actually no it doesnt. I just watched a xeno ascend to king and it gave yellow crown leadership.

No clue what's going on in production. This will fix it 100% of the time.

2021-08-08 21:04 UTC, TiviPlus requested changes

2021-08-08 21:04 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/king/king.dm
> +	SSminimaps.add_marker(kong, kong.z, MINIMAP_FLAG_XENO, kong.xeno_caste.minimap_icon)
Typecat it correctly the first time

2021-08-09 19:22 UTC, TiviPlus approved these changes

2021-08-09 19:22 UTC, merged