Changes Dark Mode colors to more eye-friendly options
tgstation/TerraGov-Marine-Corps pull request #7777
Opened 2021-08-04 19:08 UTC by lKiseki

Per title. Changes most of the Dark Mode colors in hopes that these will be more friendly to our eyes, and attempts to deal with some major atrocities that will be displayed in this PR.

## About The Pull Request

Per title. Changes most of the Dark Mode colors in hopes that these will be better for our eyes, and attempts to deal with some atrocities currently present in Dark Mode.

## Why It's Good For The Game

Our old dark mode colors were sometimes too dark, in some cases. This pull request aims to change that for the better.
I figured I should explain this with the assistance of some screenshots.

Firstly, a side-by-side comparison of the old and new colors, respectively:

![image](https://user-images.githubusercontent.com/59634950/128235906-b6d1c9dc-df80-4428-adec-da0f9790c838.png)

The changes are barely noticeable save in some cases, such as the Alpha channel and Fire Support channel, which have much more tame color hues. The same can be said for the Requisitions channel.

Up next, xenomorph alerts/announcements. The top is the new one, and the bottom is the old one.

![image](https://user-images.githubusercontent.com/59634950/128236521-9829c196-f269-4369-93f9-e3d20bada30c.png)

As you can see, I've gone for a more bright option here since I felt it was too dark.
The old color is kept for xenomorph warnings _(hopefully)_ since those don't need to be so noticeable.

I've also taken the liberty of changing the colors for some admin-related stuff, such as asay colors, since there were some major offenders here and there:

![image](https://user-images.githubusercontent.com/59634950/128239929-a7c92e9d-26ad-42dd-8c18-e42956595775.png)

Top are the new colors, bottom are the old ones. Note the dark purple color for lead asay, which has been changed to a different hue.

## Changelog
:cl: Lewdcifer
qol: Changed Dark Mode colors to more eye-friendly alternatives.
/:cl:

2021-08-04 19:14 UTC, lKiseki commented
I would prefer if this got a test merge first before it gets merged, so I can gather feedback from our players.

2021-08-04 20:23 UTC, BraveMole requested changes
Need improvements

2021-08-04 20:23 UTC, BraveMole commented on tgui/packages/tgui-panel/styles/goon/chat-dark.scss
> +  color: #A4BAD6;
no, bad code, this is wrong

2021-08-04 20:23 UTC, BraveMole commented on tgui/packages/tgui-panel/styles/goon/chat-dark.scss
> +  color: #004ED8;
need autodoc

2021-08-04 20:23 UTC, BraveMole commented on tgui/packages/tgui-panel/styles/goon/chat-dark.scss
> +  color: #666666;
yeah, this really needs early return.

Please read the contrib guideline maybe?

2021-08-04 20:23 UTC, BraveMole commented on tgui/packages/tgui-panel/styles/goon/chat-dark.scss
> +  color: #4A6FDE;
I don't like this

2021-08-04 20:23 UTC, BraveMole commented on tgui/packages/tgui-panel/styles/goon/chat-dark.scss
> +  color: #3269FF;
Are you sure about this?

2021-08-04 20:23 UTC, BraveMole commented on tgui/packages/tgui-panel/styles/goon/chat-dark.scss
> +  color: #7F4648;
This is probably causing hard dels

2021-08-04 20:23 UTC, BraveMole commented on tgui/packages/tgui-panel/styles/goon/chat-dark.scss
> +  color: #CC631E;
you can maybe make this a component, probably?

2021-08-04 20:23 UTC, BraveMole commented on tgui/packages/tgui-panel/styles/goon/chat-dark.scss
> +  color: #99AAB5;
FUCKING READ THIS : http://www.byond.com/docs/ref/#/list/associations

AND MAYBE YOU WILL STOP DOING SHIT LIKE THIS

2021-08-04 20:23 UTC, BraveMole commented on tgui/packages/tgui-panel/styles/goon/chat-dark.scss
> +.userdanger{color: #FF0000;
bruh.

2021-08-05 03:46 UTC, Al-1ce commented
Xeno alert color should say the same, the alpha and fire support ones are pretty cool though.

2021-08-05 03:47 UTC, Al-1ce commented
> Eh, looks good enough. Fire support probably needs a little brightening but then it might conflict with Alpha.


How so? Fire is red and alpha is clearly orange. I'd swap the two, but that's pretty easy to tell apart.
Otherwise, Xeno Alert color should say the same, the alpha and fire support ones are pretty cool though.

2021-08-05 04:45 UTC, KornFlaks commented
Hrm, I have a screen filter that reduces blue content on my screen. Turning it off makes Alpha clearly orange.

Yea, it's my own settings. Ignore me.

2021-08-05 17:15 UTC, TiviPlus approved these changes

2021-08-05 20:25 UTC, merged