Trying to equip an enemy radio will make an explosion
tgstation/TerraGov-Marine-Corps pull request #7820
Opened 2021-08-06 13:02 UTC by BraveMole

## About The Pull Request

Boom.

## Why It's Good For The Game

Cannot steal the enemy comms

## Changelog
:cl:
expansion: You can no longer still enemy radios, they explode when trying to equip
/:cl:

2021-08-06 13:49 UTC, EvilMelonTheSecond commented
Won't they still work when held in hand or storage? I guess it would be fun to listen to comms like a radio in hand though.

2021-08-06 14:21 UTC, BraveMole commented
> Won't they still work when held in hand or storage? I guess it would be fun to listen to comms like a radio in hand though.

Needs to be in your ear :)

2021-08-06 20:15 UTC, KornFlaks commented
Command gives us radios that can be remotely detonated.

Is command trying to kill us all?

2021-08-07 19:01 UTC, TiviPlus requested changes
Make a tochat

2021-08-07 19:03 UTC, BraveMole commented on code/game/objects/items/radio/headset.dm
> +			playsound(user, 'sound/effects/bang.ogg', 50, 1)
```suggestion
			to_chat(user, span_warning("[src] violently buzzes and explodes in your ear"))
			playsound(user, 'sound/effects/bang.ogg', 50, 1)
```

2021-08-07 19:13 UTC, TiviPlus commented on code/game/objects/items/radio/headset.dm
> +			to_chat(user, span_warning("[src] violently buzzes and explodes in your ear"))
```suggestion
			to_chat(user, span_warning("[src] violently buzzes and explodes in your face as it's tampering mechanisms are triggered!"))
```

2021-08-07 19:15 UTC, BraveMole commented on code/game/objects/items/radio/headset.dm
> +			to_chat(user, span_warning("[src] violently buzzes and explodes in your face as it's tampering mechanisms are triggered!"))
```suggestion
			to_chat(user, span_warning("[src] violently buzzes and explodes in your face as its tampering mechanisms are triggered!"))
```

2021-08-07 19:33 UTC, TiviPlus approved these changes

2021-08-07 19:33 UTC, merged