Hnnngh Morty, this stops the hivemind from getting caugh ton razorwires
tgstation/TerraGov-Marine-Corps pull request #7838
Opened 2021-08-07 02:38 UTC by lbnesquik

## About The Pull Request
Fixes good
## Why It's Good For The Game
Bugs bad

## Changelog
:cl:
fix: fixed hivemind eyes getting caught onto razorwires by adding a check
/:cl:

2021-08-07 10:48 UTC, BraveMole requested changes

2021-08-07 10:48 UTC, BraveMole commented on code/game/objects/structures/razorwire.dm
> +		return
bad, there are status flag like incorporal

2021-08-07 18:20 UTC, TiviPlus requested changes

2021-08-07 18:20 UTC, TiviPlus commented on code/game/objects/structures/razorwire.dm
> +		return
Check against flags

2021-08-07 21:28 UTC, lbnesquik commented on code/game/objects/structures/razorwire.dm
> +		return
Done.

2021-08-08 05:18 UTC, Ieteihowmee commented
Wait they get stuck on razor wire??

2021-08-08 21:12 UTC, TiviPlus approved these changes

2021-08-08 21:12 UTC, merged