Juicy Cock Refactor and Single Action Revolvers
tgstation/TerraGov-Marine-Corps pull request #7868
Opened 2021-08-08 22:11 UTC by hyper2snyper

Something Something Cowboys Ranch Cock Something Something
~I'm such a child please stop me~

## About The Pull Request

Minor Cock() refactor. Mainly just cleaning up the unique_action() bloat.
Adds code for single-action revolvers. Have fun MJP

## Why It's Good For The Game

Pew Pew Clint Eastwood style

## Changelog
:cl:
code: Single Action Revolver Support
refactor: Cock() Refactor and removes some Unique_Action() bloat
/:cl:

2021-08-08 22:13 UTC, SplinterGP requested changes

2021-08-08 22:13 UTC, SplinterGP commented on code/modules/projectiles/guns/revolvers.dm
> +	update_icon_state()
what ?

2021-08-08 22:15 UTC, SplinterGP requested changes

2021-08-08 22:15 UTC, SplinterGP commented on code/modules/projectiles/guns/revolvers.dm
> +	var/primed = FALSE
snowflake ?

2021-08-08 22:23 UTC, SplinterGP requested changes
don't create new snowflake stuff, use the already existing guns proc that reloads, chambers, shoots and spins the barrel to next position to do it, overriding if necessary/adding a flagcheck on fire() if it should chamber next round automatically or not.

2021-08-09 20:12 UTC, TiviPlus requested changes

2021-08-09 20:12 UTC, TiviPlus commented on code/modules/projectiles/gun_system.dm
> +		return
return whatever cock returns when failing here I guess?

2021-08-09 20:12 UTC, TiviPlus commented on code/modules/projectiles/guns/revolvers.dm
> +	update_icon_state()
use update icon

2021-08-12 08:02 UTC, SplinterGP requested changes

2021-08-12 08:02 UTC, SplinterGP commented on code/modules/projectiles/guns/revolvers.dm
> -	return TRUE
why did you remove this.

2021-08-24 08:35 UTC, BraveMole commented on code/modules/projectiles/guns/revolvers.dm
> -	return TRUE
it's moved to unique action

2021-08-24 08:42 UTC, BraveMole requested changes
I kinda fail to see the point of this.

For exemple, switching to hydro in flamers is not cocking? Can you still use keybinds?

rather than moving unique action stuff to cock, why not doing the opposite?

2021-08-24 08:42 UTC, BraveMole commented on code/modules/projectiles/guns/revolvers.dm
> +/obj/item/weapon/gun/revolver/single_action/update_icon()
update_icon_state()

2021-08-24 08:42 UTC, BraveMole commented on code/modules/projectiles/gun_system.dm
> +		return
standing issue

2021-09-02 22:25 UTC, TiviPlus requested changes

2021-09-02 22:25 UTC, TiviPlus commented on code/modules/projectiles/guns/flamer.dm
> -		return
Should be unique action

2021-09-02 22:25 UTC, TiviPlus commented on code/modules/projectiles/guns/specialist.dm
> +	return laser_off(user)
ditto

2021-09-02 22:25 UTC, TiviPlus commented on code/modules/projectiles/guns/revolvers.dm
> +/obj/item/weapon/gun/revolver/single_action/update_icon()
use update_icon_state here

2021-09-03 21:07 UTC, BraveMole requested changes

2021-09-06 15:43 UTC, BraveMole requested changes
Can you explain where is the return for cock (and so for unique action) is used, and why sometimes you return TRUE, sometimes nothing?

2021-09-06 15:43 UTC, BraveMole commented on code/modules/projectiles/guns/revolvers.dm
> +/obj/item/weapon/gun/revolver/single_action/cock(mob/user)
this one is not returning anything for exemple

2021-09-06 15:43 UTC, BraveMole commented on code/modules/projectiles/guns/specialist.dm
> +	return TRUE
this one is returning true despite doing nothing

2021-09-06 17:26 UTC, TiviPlus approved these changes

2021-09-06 17:32 UTC, merged