Flare gun improvements
tgstation/TerraGov-Marine-Corps pull request #7869
Opened 2021-08-08 22:45 UTC by BraveMole

## About The Pull Request

Flare gun is now a child of a grenade launcher, which makes it able to launch cas flare, and the flares looks like flares not bullets.

I also improved gl code wich was really outdated.

## Why It's Good For The Game

## Changelog
:cl:
expansion: Flare gun can fire cas flares
/:cl:

2021-08-09 19:16 UTC, TiviPlus requested changes

2021-08-09 19:16 UTC, TiviPlus commented on code/modules/projectiles/guns/misc.dm
> +	to_chat(user, span_notice(" It is loaded with a flare."))
```suggestion
	to_chat(user, span_notice("It is loaded with a flare."))
```

2021-08-09 20:15 UTC, TiviPlus approved these changes

2021-08-10 22:45 UTC, Kuro020 approved these changes

2021-08-12 16:40 UTC, merged