removes revolver snubnose, makes revolvers fit in bags again
tgstation/TerraGov-Marine-Corps pull request #7898
Opened 2021-08-11 02:26 UTC by Pariah919

## About The Pull Request
Revolvers are bad
Backpack man meme got nerfed to the ground to non existance anyway, and if it's such an issue i'll just add a storage limit of revolvers or make them bulky and have a bypass
Snubs are ass and they're a terrible idea
With slowdown, knockback, 0.15 fire delay and decent damage at the cost of mag capacity and sustainablity

## Why It's Good For The Game
Revolvers are awful and snubnose did nothing to solve the issues it created, you can't vend out 15 bags full of revolvers anymore anyway because bag grabbing got nerfed to the ground and the screenshake is gone, aswell as the stagger

## Changelog
:cl:
balance: tp-44 revolver snubnoses are gone, tp-44 no longer staggers at all, revolver now fits normally everywhere again.
/:cl:

2021-08-11 16:28 UTC, Ieteihowmee commented
Good.

2021-08-11 16:42 UTC, Alexeivichi commented
Xenos on suicide watch again. Time to go full gamer.

2021-08-12 07:41 UTC, SplinterGP commented
> Revolvers are awful and snubnose did nothing to solve the issues it created, you can't vend out 15 bags full of revolvers anymore anyway because bag grabbing got nerfed to the ground and the screenshake is gone, aswell as the stagger

bag grabbing never got nerfed, indeed you can still take it out and take stuff instantly, it just has been added so you can pull it in your back without taking it out by having a delay instead of not being able to, and you can still use satchels.

also i don't know why you cant put the stagger and stuff removal just on snubnose, this is overall a nerf to who doenst use revolver by putting them on bags and shit.

2021-08-12 15:45 UTC, TiviPlus requested changes

2021-08-12 15:45 UTC, TiviPlus commented on code/modules/projectiles/ammo_datums.dm
> -		staggerstun(M, P, stagger = 1, slowdown = 0.5, knockback = 1, shake = 0)
You didnt delete these signals

2021-08-14 16:43 UTC, InterroLouis commented
Don't forget the sprite changes from the snubnose addition need to be undone.

2021-08-14 19:15 UTC, SilencedMP5A5 commented
now you can add your funny magnum revolver, mjp 💯

2021-08-15 22:02 UTC, Losenis commented
Revolverspam is bad because screenshake + stagger on full auto tier firerate that made any escape abilities effectively useless while the reload was so ass it was better to pack multiple of them instead of actually reloading the fucking thing, who the FUCK THOUGHT FUCKING OVER BACKPACKS AND REVOLVER STORAGE WAS THE SOLUTION

2021-08-21 10:05 UTC, TiviPlus approved these changes

2021-08-21 10:05 UTC, merged