Makes it clearer when you are denied access to a vendor
tgstation/TerraGov-Marine-Corps pull request #7910
Opened 2021-08-12 07:34 UTC by lbnesquik

## About The Pull Request
![image](https://user-images.githubusercontent.com/24830358/129156495-99871312-edf7-4088-b4ce-dee007ca8e6e.png)

## Why It's Good For The Game
It makes it clearer when you are actually not meant to have access, if the vendor is dead or if you are simply lagging.
It should also help new players orient themselves towards the proper vendors when they spawn as anything besides squad marine. I've had to help more than a couple new engis or whatever find their preps.

## Changelog
:cl:
qol: made it clear when you do not have access to a vendor. 
/:cl:

2021-08-12 07:51 UTC, BraveMole requested changes

2021-08-12 07:51 UTC, BraveMole commented on code/game/objects/machinery/vending/new_marine_vendors.dm
> +			to_chat(user, span_warning("Access denied. This vendor is heavily restricted.."))
```suggestion
			to_chat(user, span_warning("Access denied. This vendor is heavily restricted."))
```

2021-08-12 07:51 UTC, BraveMole commented on code/game/objects/machinery/vending/new_marine_vendors.dm
> +			to_chat(user, span_warning("Access denied. Your assigned squad isn't allowed to access this machinery"))
```suggestion
			to_chat(user, span_warning("Access denied. Your assigned squad isn't allowed to access this machinery."))
```

2021-08-13 15:06 UTC, TiviPlus approved these changes

2021-08-13 15:06 UTC, merged