PAS-11 armor and M10 helmets are now modular.
tgstation/TerraGov-Marine-Corps pull request #7911
Opened 2021-08-12 07:38 UTC by SplinterGP

## About The Pull Request
PAS-11 armor and M10 helmets have been replaced by the PAS-11X and M10X variants, which have been fit with attach points allowing them to accept modules, however, the PAS-11X doenst take different armor plates, its just the default. 

## Why It's Good For The Game
Removes the gap and difference between PAS-11/M10 with Jaeger by making them able to take modules, now they are the same thing and have pretty much the same balance.

## Changelog
:cl:
expansion: PAS-11 armor and M10 helmet have been fitted with attach points to be able to take modules like jaeger, a X has been added on end of their name to imply that.
balance: PAS-11X and M10X can take modules.
/:cl:

2021-08-12 07:58 UTC, token-map commented
dangerously based

2021-08-12 08:11 UTC, ilikesaying commented
based

2021-08-12 10:30 UTC, GradusNL commented on code/__DEFINES/loadout.dm
> +		/obj/item/clothing/head/modular/marine/m10x/leader  = list(CAT_HEL, "Regular leader helmet", 0, "black"),
Shouldn't this be M10X leader helmet to bring it in line with the others?

2021-08-12 11:01 UTC, neohenry commented
When greyscale for PAS?

2021-08-12 21:17 UTC, SplinterGP commented
> 
> 
> When greyscale for PAS?

suffer

2021-08-12 23:25 UTC, Kuro020 commented
> When greyscale for PAS?

after this is merged

2021-08-13 02:07 UTC, SplinterGP commented on code/__DEFINES/loadout.dm
> +		/obj/item/clothing/head/modular/marine/m10x/leader  = list(CAT_HEL, "Regular leader helmet", 0, "black"),
```suggestion
		/obj/item/clothing/head/modular/marine/m10x/leader  = list(CAT_HEL, "M10X leader helmet", 0, "black"),
```

2021-08-13 03:29 UTC, Tristan63 commented
attachable armor plate for m10x?

2021-08-13 03:55 UTC, Ieteihowmee commented
PAS seperated the men from the boys. I am not sure how I feel about this. Though I am curious to see how it all works. Can I get Mimir on my PAS? I certainly hope so :)

2021-08-14 21:56 UTC, SplinterGP commented
> 
> 
> PAS seperated the men from the boys. I am not sure how I feel about this. Though I am curious to see how it all works. Can I get Mimir on my PAS? I certainly hope so :)

ye

2021-08-21 06:30 UTC, David-Stormwell approved these changes
Approved from a balance standpoint, also required later so that MJP or anyone else can replace the sprites with better sprites while having some modularity.

2021-08-21 09:37 UTC, TiviPlus requested changes
Show pictures

2021-08-21 09:37 UTC, TiviPlus commented on code/modules/modular_armor/modular.dm
> -	)
why are you deleting head icons

2021-08-21 09:37 UTC, TiviPlus commented on code/modules/modular_armor/modular.dm
> +		slot_r_hand_str = 'icons/mob/items_righthand_1.dmi',)
formatting

2021-08-22 10:03 UTC, SplinterGP commented on code/modules/modular_armor/modular.dm
> +		slot_r_hand_str = 'icons/mob/items_righthand_1.dmi',)
```suggestion
	item_icons = list(
		slot_head_str = 'icons/mob/modular/m10.dmi',
		slot_l_hand_str = 'icons/mob/items_lefthand_1.dmi',
		slot_r_hand_str = 'icons/mob/items_righthand_1.dmi',
	)
```

2021-08-22 10:04 UTC, SplinterGP commented on code/modules/modular_armor/modular.dm
> -	)
it being null doenst do anything.

2021-08-23 14:54 UTC, mathis650 commented
based

2021-08-24 00:57 UTC, rusher210 commented
totally based

2021-08-24 12:45 UTC, BraveMole approved these changes
No bug reports

2021-08-24 12:45 UTC, merged