Look sir, synths with access to Binary radio!
tgstation/TerraGov-Marine-Corps pull request #7940
Opened 2021-08-15 19:45 UTC by lbnesquik

## About The Pull Request
This pull request gives synth access to binary using the :n key. Basically the same thing as cyborgs.
The AI actually has it already, but like, no one can actually listen to it lmao.
This also features a comment a check and general prettying up of this check. 

## Why It's Good For The Game
It gives synths and silicon a bit of their own mini group, distinct from command. Kind of like their own channel. 

## Changelog
:cl:
qol: Brought Binary radio for synths
/:cl:

2021-08-15 21:03 UTC, KornFlaks commented
Also give ghosts access to robotic channel please. Just to make sure no ERPing is going on in that channel...

2021-08-15 21:58 UTC, Losenis commented
.n cap is condom bolt him in showers

2021-08-15 22:48 UTC, lbnesquik commented
> 
> 
> Also give ghosts access to robotic channel please. Just to make sure no ERPing is going on in that channel...

Maybe they should get some synthetic upgrade if they wanted to see it.

2021-08-17 05:56 UTC, SplinterGP requested changes

2021-08-17 05:56 UTC, SplinterGP commented on code/modules/mob/living/carbon/human/species.dm
> +	return TRUE
```suggestion
/mob/living/carbon/human/species/synthetic/binarycheck(mob/H)
	return TRUE
```
no need for this

2021-08-17 05:56 UTC, SplinterGP commented on code/modules/mob/living/carbon/human/species.dm
> +	return TRUE
ditto
```suggestion
/mob/living/carbon/human/species/early_synthetic/binarycheck(mob/H)
	return TRUE
```

2021-08-21 09:48 UTC, TiviPlus requested changes
Ghosts need to be able to see robo chat for admin purposes

2021-08-22 10:10 UTC, SplinterGP approved these changes

2021-08-22 10:10 UTC, SplinterGP commented
> 
> 
> Ghosts need to be able to see robo chat for admin purposes

already does ?

2021-08-22 10:11 UTC, SplinterGP requested changes

2021-08-22 10:11 UTC, SplinterGP commented on code/modules/mob/living/silicon/say.dm
> +		if(binarycheck(M))
???

2021-08-24 09:04 UTC, BraveMole approved these changes

2021-08-24 09:04 UTC, merged