adds a 10x20mm packet
tgstation/TerraGov-Marine-Corps pull request #7965
Opened 2021-08-18 06:02 UTC by Pariah919

## About The Pull Request
adds a 10x20mm packet, it's small.
it holds 2 and a half p90 magazines or whatever, 125 rounds.

## Why It's Good For The Game
10x20mm has needed a packet for a while

## Changelog
:cl:
expansion: 10x20mm packets added.
/:cl:

2021-08-18 06:27 UTC, Ieteihowmee commented
Why do we not add speed loaders for magazines. They exist now to make magazine reloading so much easier, why not just add a little device you load/have preloaded with ammo? and in one click BOOM, mag is refeed.

2021-08-19 14:31 UTC, TiviPlus commented
Balance freeze

2021-08-19 18:39 UTC, David-Stormwell commented
where is my ammo packet tivi...

2021-08-23 11:59 UTC, SplinterGP commented
Balans freeze gone

2021-08-23 12:24 UTC, BraveMole requested changes

2021-08-23 12:24 UTC, BraveMole commented on code/modules/projectiles/magazines/misc.dm
> +	max_rounds = 125
Why 2.5 T90 magazines? why not 3?

2021-08-25 08:16 UTC, Pariah919 commented on code/modules/projectiles/magazines/misc.dm
> +	max_rounds = 125
```suggestion
	max_rounds = 150
```

2021-08-25 08:16 UTC, Pariah919 commented on code/modules/projectiles/magazines/misc.dm
> +	current_rounds = 125
```suggestion
	current_rounds = 150
```

2021-08-25 09:05 UTC, BraveMole approved these changes
ok

2021-08-25 09:05 UTC, merged