Makes it possible to feed xenos food.
tgstation/TerraGov-Marine-Corps pull request #7966
Opened 2021-08-18 12:23 UTC by lbnesquik

## About The Pull Request
They still do not process it.

## Why It's Good For The Game
You can now roleplay having a date with a bean. That's it.

## Changelog
:cl:
qol: allowed xenos to be fed food for the sake of fluff
/:cl:

2021-08-18 12:31 UTC, ilikesaying commented
they already can be fed food? i literally handfed a boiler a burger?

2021-08-18 12:57 UTC, lbnesquik commented
> 
> 
> they already can be fed food? i literally handfed a boiler a burger?

Last game, i couldn't feed a queen drinks or borgers. Soooo, it seems like there is inconsistent code.

2021-08-19 14:33 UTC, TiviPlus requested changes
Relative pathing, you tocuh it you fix it
also since when does this not work its been working

2021-08-20 21:59 UTC, lbnesquik commented
> 
> 
> Relative pathing, you tocuh it you fix it

Reeeeeeeeeeeeee

2021-08-24 00:06 UTC, Tristan63 commented
![](https://i.gyazo.com/ac8bacaff25860c2129218802ac71b1b.png)

2021-08-24 21:12 UTC, lbnesquik commented
Alright dweebs. I implemented changes to make sure condiments work like other food sources, fixed a weird proc, some bypasses and redundant checks.

2021-08-27 23:26 UTC, SplinterGP requested changes

2021-08-27 23:26 UTC, SplinterGP commented on code/game/objects/items/reagent_containers/food/condiment.dm
> +/obj/item/reagent_containers/food/condiment/attackby(obj/item/W as obj, mob/user as mob)
```suggestion
/obj/item/reagent_containers/food/condiment/attackby(obj/item/W, mob/user)
```

2021-08-27 23:26 UTC, SplinterGP commented on code/game/objects/items/reagent_containers/food/condiment.dm
> +/obj/item/reagent_containers/food/condiment/attack_self(mob/user as mob)
```suggestion
/obj/item/reagent_containers/food/condiment/attack_self(mob/user)
```

2021-08-27 23:26 UTC, SplinterGP commented on code/game/objects/items/reagent_containers/food/condiment.dm
> +/obj/item/reagent_containers/food/condiment/attack(mob/M as mob, mob/user as mob, def_zone)
```suggestion
/obj/item/reagent_containers/food/condiment/attack(mob/M, mob/user, def_zone)
```

2021-08-27 23:26 UTC, SplinterGP commented on code/game/objects/items/reagent_containers/food/condiment.dm
> +	var/datum/reagents/R = src.reagents
```suggestion
	var/datum/reagents/R = reagents
```

2021-08-27 23:26 UTC, SplinterGP commented on code/game/objects/items/reagent_containers/food/condiment.dm
> +/obj/item/reagent_containers/food/condiment/attackby(obj/item/I as obj, mob/user as mob)
```suggestion
/obj/item/reagent_containers/food/condiment/attackby(obj/item/I, mob/user)
```

2021-08-28 19:55 UTC, BraveMole approved these changes

2021-08-28 19:55 UTC, merged