Makes it so beans can't hit dead simple animals anymore.
tgstation/TerraGov-Marine-Corps pull request #7967
Opened 2021-08-18 12:58 UTC by lbnesquik

## About The Pull Request
I could make it a check for ravagers only but whatever.
This just makes it impossible to slash dead simple animals.

## Why It's Good For The Game
Fixes #7342

## Changelog
:cl:
fix: fixes ravager getting free rage from hitting simple mobs.
/:cl:

2021-08-18 13:40 UTC, BraveMole requested changes
I'm not a big fan on this, when the issue is only ravager fury. Can you check if the mob attacked is dead, and if so not give fury?

2021-08-18 13:40 UTC, BraveMole commented on code/modules/mob/living/carbon/xenomorph/attack_alien.dm
> +	if(isanimal(src) && (stat == DEAD))
bad. In general, istype(src) are verboten. 

Here you must overide attack_alien_harm for animal mobs.

2021-08-18 15:00 UTC, lbnesquik commented
Fuck you bravemole, making me do shit

2021-08-18 15:01 UTC, BraveMole commented
Kek self resolving an issue that will be blocking, bad smalls

2021-08-19 14:34 UTC, TiviPlus commented on code/datums/elements/plasma_on_attack.dm
>  	furious.gain_plasma(damage * damage_plasma_multiplier)
```suggestion
		return NONE
	furious.gain_plasma(damage * damage_plasma_multiplier)
```

2021-08-20 14:20 UTC, TiviPlus approved these changes

2021-08-20 14:20 UTC, merged