Grants Crushers a Minor Scope Ability
tgstation/TerraGov-Marine-Corps pull request #7993
Opened 2021-08-21 14:10 UTC by KornFlaks

## About The Pull Request

Inheriting from boiler zoom, this grants a smaller zoom function to crushers to scout for razorwire without dying.

## Why It's Good For The Game

This PR allows crushers to plan how they'll charge down crusher lanes without immediately dying to marines that can outrun it on weeds.

## Changelog
:cl:
add: Crushers now have a small scope ability to scout ahead of themselves for razor and marine concentrations.
/:cl:

2021-08-21 14:16 UTC, Hekzder commented
Bull too please. Not much of a reason I can think of that Crusher in particular should get this and not also Bull.

2021-08-21 14:22 UTC, KornFlaks commented
> Bull too please. Not much of a reason I can think of that Crusher in particular should get this and not also Bull.

Bull is focused more on single marine charge and damage, not FOB breaching which zoom is primarily used for.
They have reduced charge windup distance and massive stun times. 

I'm hesitant on giving bulls zoom as well and if so, not the same as crusher. If they will receive it, how much zoom, 4? 3? That's barely anything.

2021-08-21 14:25 UTC, Hekzder commented
> > Bull too please. Not much of a reason I can think of that Crusher in particular should get this and not also Bull.
> 
> Bull is focused more on single marine charge and damage, not FOB breaching which zoom is primarily used for.
> They have reduced charge windup distance and massive stun times.
> 
> I'm hesitant on giving bulls zoom as well and if so, not the same as crusher. If they will receive it, how much zoom, 4? 3? That's barely anything.

My argument is more so that I don't think Bull is such a strong caste it shouldn't also get zoom, and I don't think Crusher is such a weak caste it in particular needs zoom.

 Yes they use charge for different things, but I still can see plenty of reason that both should get an equal or basically equal zoom if the other gets it. All things considered they play quite similarly and IMO Bull would benefit from any love it can get.

2021-08-21 15:04 UTC, EvilMelonTheSecond commented
Crushers getting stuck in razorwire is literally a skill issue. There have been many times where I trapped low skill crushers with razorwire in my first attempt cuz they charge down the same lane over and over. There have also been many times where I couldn't trap a constantly charging crusher with 5+ razorwire cuz they constantly change lanes and angle (and sometimes even stop before hitting razorwire).

Instead of a crutch mechanic people should learn their weaknesses and how to cover them up. And maybe even rely on teamplay?

2021-08-21 16:30 UTC, Ieteihowmee commented
Ah yes, hard counter the only hard counter engineers/marines really have against crushers. If you can not be unga crusher that is YOUR problem.

2021-08-21 17:02 UTC, KornFlaks commented
> Ah yes, hard counter the only hard counter engineers/marines really have against crushers.

Razorwires arent going anywhere. Claymores as well. Use scopes, rocket launchers, flamers, grenades. Just shoot a crusher, they've been repeatedly hit with more slowing PRs.

A marine walking with FC move order can outrun a crusher not charging and you can cancel a charge with slugs, explosives, and other stunning devices.

Marines say skill issue well I respond with skill issue.

2021-08-21 18:46 UTC, davidchan13 commented
> > Ah yes, hard counter the only hard counter engineers/marines really have against crushers.
> 
> Razorwires arent going anywhere. Claymores as well. Use scopes, rocket launchers, flamers, grenades. Just shoot a crusher, they've been repeatedly hit with more slowing PRs.
> 
> A marine walking with FC move order can outrun a crusher on weeds not charging and you can cancel a charge with slugs, explosives, and other stunning devices.
> 
> Marines say skill issue well I respond with skill issue.

The entire point of razorwire is to catch and stun a caste that is immune to every other stun. Charger has stupid high bomb and bullet armor, razor is the only thing that will slow one down. The mechanic literally exists how easy it is for a crusher to charge a barricade, turn around and run back out of danger even if 10+ marines in a FOB are shooting it. 

If crusher can't work with Queen, Boiler or other xenos to scout and figure out good charge lanes, _**SKILL ISSUE.**_

2021-08-21 18:46 UTC, Pariah919 commented
I don't see the point of giving crusher better wallhacks because simply it can be oturan on weeds
the only way for a decent crusher to die is that they kept charging down the exact same lane like a dumbo, and crusher can stop charging anytime they want anyway so it's not hard to dodge razorwire
overall i don't like this of this as xenos already get a ton of information they need instantly for free

2021-08-22 08:18 UTC, usnpeepoo commented
This is just trying to baby crushers who have 0 gamesense

2021-08-22 18:05 UTC, Ieteihowmee commented
> > Ah yes, hard counter the only hard counter engineers/marines really have against crushers.
> 
> Razorwires arent going anywhere. Claymores as well. Use scopes, rocket launchers, flamers, grenades. Just shoot a crusher, they've been repeatedly hit with more slowing PRs.
> 
> A marine walking with FC move order can outrun a crusher on weeds not charging and you can cancel a charge with slugs, explosives, and other stunning devices.
> 
> Marines say skill issue well I respond with skill issue.

No. Crusher definitely has a skill issue if it runs into razorwire. I do not see it often anymore because they get smart. If you can not adapt it is a skill issue on behalf of the crusher. Not the marines. No free extra vision for crushers thanks.

2021-08-22 18:22 UTC, EgorDinamit commented
Regardless of razorwire, this PR is still good, Crusher should be able to see what he is charging into.

2021-08-24 08:57 UTC, BraveMole requested changes
Not a big fan, as many said crusher getting into tangled is mostly skill issue. 
Crusher can either go look before charging, or just stopping before the razor wire if he's carefull

2021-08-24 09:07 UTC, closed without merging

2021-08-24 09:09 UTC, David-Stormwell commented
Already closed, but I'll put in my 2 cents, this is quite a reason why you have teammates, other xenos.
Don't expect everything to be given to you, have another xeno such as a runner scout ahead, ask if there is razorwire, or even take a look before charging.
Not to mention how easy it is if you don't lag too much to cancel the charge.

2021-08-24 17:57 UTC, Wayland-Smithy commented
> No free extra vision for crushers thanks.

Pretty top kek when Sentry turrets can target and start shooting you off screen now, and wire can still be built inside of non-dense bushes like on LV and be near impossible to see until you enter overlapping lines of fire to inspect. Just keep nerfing crusher speed into the ground and buffing engis I'm sure the deathball problem will just go away on it's own yep.