orders last longer
tgstation/TerraGov-Marine-Corps pull request #7998
Opened 2021-08-21 18:50 UTC by Pariah919

## About The Pull Request
reopening of #7963
orders last way longer
10->25 ticks
may increase cd later if it's too opressive but i think 50 seconds is a good time for a order duration

## Why It's Good For The Game
orders are kinda trash and I tihnk making them last longer is a good start to up their viablity

## Changelog
:cl:
balance: marine orders last 30 seconds longer
/:cl:

2021-08-21 19:43 UTC, Passe2142 commented
Maybe 15?. Some marines can outrun queens with 20s. 
The game is attrition based for xenos , you can have 2 SLs spamming move order for masive chase and that would mean speed like no stam pr days on a lower scale. SLs arent the only ones with move order.
Well being fair it will take to coordinate the orders. Even with 20ish of duration it not "spammable", Its hard to make ungas stay with SLs unless you point and yell.

2021-08-23 12:30 UTC, BraveMole requested changes

2021-08-23 12:30 UTC, BraveMole commented on code/game/objects/machinery/overwatch.dm
> +	command_aura_tick = 25 //25 ticks, or 50 seconds apprx.
Lower this please, 15 seems ok

2021-08-23 22:52 UTC, Pariah919 commented on code/game/objects/machinery/overwatch.dm
> +	command_aura_tick = 25 //25 ticks, or 50 seconds apprx.
ok

2021-08-23 22:52 UTC, Pariah919 reviewed
brave

2021-08-23 22:52 UTC, Pariah919 commented on code/game/objects/machinery/overwatch.dm
> +	command_aura_tick = 25 //25 ticks, or 50 seconds apprx.
```suggestion
	command_aura_tick = 15//15 ticks, or 30 seconds apprx.
```

2021-08-23 22:52 UTC, Pariah919 commented on code/game/objects/machinery/overwatch.dm
> +	command_aura_cooldown = 45 //40 ticks, or 90 seconds overall CD, 35 practical.
```suggestion
	command_aura_cooldown = 45 //40 ticks, or 90 seconds overall CD, 60 practical.
```

2021-08-24 08:32 UTC, BraveMole approved these changes
Fix CL

2021-08-25 08:13 UTC, merged