Defile Ability Rework
tgstation/TerraGov-Marine-Corps pull request #8033
Opened 2021-08-24 00:25 UTC by Surrealaser

## About The Pull Request

1. Defile wind up reduced from 1.5 seconds to 0.5 seconds.
2. Defile plasma cost reduced from 150 to 100.
3. Defile cooldown reduced from 20 to 15 seconds.
4. Defile Brute damage reduced from 10 to 5 and Stamina damage reduced from 100 to 50.
4. Defile no longer injects larva; instead it purges all chemicals in the victim and deals toxin damage equal to 30 + half the total U of chemical purged from the victim's system multiplied by 2 for each unique xeno toxin in its system. The victim also exudes a cloud of blood red Sanguinal smoke that scales in size with the amount of toxin damage dealt in this way.
5. Sanguinal is a new toxin that deals minor brute and bleeding each tick.  For each other unique xeno toxin in the victim's system, it will deal minor damage of a corresponding type (Stamina for Hemodile, Toxin for Neurotoxin and Burn for Transvitox).

## Why It's Good For The Game

Removes vestiges of 'capture gameplay'.

Adds interesting and synergistic 'finisher' move to the Defiler that combos with its other abilities and other xenos.

## Changelog
:cl:
balance: Defile wind up reduced from 1.5 seconds to 0.5 seconds.
balance: Defile plasma cost reduced from 150 to 100.
balance: Defile cooldown reduced from 20 to 15 seconds.
balance: Defile Brute damage reduced from 10 to 5 and Stamina damage reduced from 100 to 50.
add: Defile no longer injects larva; instead it purges all chemicals in the victim and deals toxin damage equal to 30 + half the total U of chemical purged from the victim's system multiplied by 2 for each unique xeno toxin in its system. The victim also exudes a cloud of blood red Sanguinal smoke that scales in size with the amount of toxin damage dealt in this way.
add: New Sanguinal toxin added; deals minor brute and bleeding each tick.  For each other unique xeno toxin in the victim's system, it will also deal minor damage of a corresponding type (Stamina for Hemodile, Toxin for Neurotoxin and Burn for Transvitox).
/:cl:

2021-08-24 00:41 UTC, Lefunny commented
this sounds funny but we still need more balancment stuff for defiler, maybe deal some of his """super strong""" slash for speed or armor as it is a caste that need to deal with close range but dont have enough speed or armor to have a "safe" gameplay.

2021-08-24 04:00 UTC, bobmancer343 commented
I'd still want some larva defiler stings maybe as a seperate ability or a switchable one. Dunno I just like being a dickhead and defiling crit marines with larva.

2021-08-24 09:22 UTC, BraveMole requested changes
I like the concept, but i'm not a fan of the cd, plasma cost and windup reduction.

If it's a finisher, it doesn't need low plasma cost or low cd?

The windup is maybe fine on its own, but with the rest it's just too much

2021-08-24 21:01 UTC, BraveMole approved these changes
Unless splinter come and veto, fix this and i'll tm

2021-08-24 21:01 UTC, BraveMole commented on code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
> +	var/turf/target_turf = get_turf(living_target)
usless var

2021-08-24 21:01 UTC, BraveMole commented on code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
>  	var/mob/living/carbon/xenomorph/Defiler/X = owner
at any point, do you need it to be a defiler? If not, just cast as a xeno, this allows action to be portable

2021-08-25 06:23 UTC, SplinterGP commented
pretty much bonkers with current rainbow slashing, theres #8051 for that however, plus i dunno gotta test the explosion potential more with time for this, just TM for now

2021-08-28 12:05 UTC, merged