Removes an extra argument from mob reagent reaction
tgstation/TerraGov-Marine-Corps pull request #8036
Opened 2021-08-24 05:24 UTC by QualityVan

## About The Pull Request
Reaction_mob has an argument named metabolize. It's not used in the declaration or in any children, and I don't know what it would do given that it's called when a reagent comes into contact with a mob. Metabolization is handled by on_mob_life, so that's not it. The only thing that calls reaction_mob is the holder's reaction proc, and it's never used it.

## Why It's Good For The Game
Cleanup.
Also fixes acid hiding the message when it melts your mask/helmet, due to incorrect argument order.

## Changelog
:cl:
fix: Acid will now tell you when it melts your helmet or mask (sulphuric/polytrinic, not xeno acid)
/:cl:

2021-08-24 08:31 UTC, BraveMole approved these changes

2021-08-25 06:29 UTC, SplinterGP requested changes
did you check on the calls of it if youre not missing something on order ?

2021-08-25 06:31 UTC, QualityVan commented
> 
> 
> did you check on the calls of it if youre not missing something on arg order ?

Like I said, it's only called in one place and that one place wasn't accounting for it, which this fixes.

2021-08-25 08:16 UTC, BraveMole approved these changes
looks good

2021-08-25 08:16 UTC, merged