Large Vehicle refactor
tgstation/TerraGov-Marine-Corps pull request #8089
Opened 2021-08-27 18:49 UTC by TiviPlus

## About The Pull Request

Completely rewrites our vehicle code from the ground up to be more in line with TG
For testing added ATVs among several other vehicles such as bikes

## Changelog
:cl:
fix: the powerloader is now offset correctly
refactor: redid the vehicle code completely
/:cl:

2021-08-27 23:04 UTC, BraveMole approved these changes

2021-08-28 06:22 UTC, HeyMyNameIsLouie commented
![image](https://user-images.githubusercontent.com/59080633/131208425-78d0d31e-d6b4-4af2-b606-62b54c67ce51.png)
Jihadist Terrorist ATV drivers are finally here, truly the best timeline to live.

2021-08-28 20:57 UTC, SplinterGP commented on code/__DEFINES/vehicles.dm
> +///Will this car kidnap people by ramming into them?
CLOWN CAR?

2021-08-28 22:16 UTC, SplinterGP requested changes

2021-08-28 22:19 UTC, TiviPlus commented on code/_onclick/xeno.dm
> +		return
```suggestion
	if(HAS_TRAIT(src, TRAIT_HANDS_BLOCKED))
		return FALSE
```
it can only return false but w/e

2021-08-28 22:22 UTC, TiviPlus commented on code/modules/vehicles/_vehicle.dm
> +	var/list/mob/occupants //mob = bitflags of their control level.
```suggestion
	///mob = bitflags of their control level.
	var/list/mob/occupants
```

2021-08-28 22:22 UTC, TiviPlus commented on code/modules/vehicles/_vehicle.dm
> +	occupant_actions = list()
maybe but im not going to test it in this refactor

2021-08-28 22:22 UTC, TiviPlus commented on code/modules/vehicles/_vehicle.dm
> +	var/list/mob/occupant_actions //assoc list mob = list(type = action datum assigned to mob)
```suggestion
	///plain list of typepaths
	var/list/autogrant_actions_passenger
	///assoc list "[bitflag]" = list(typepaths)
	var/list/autogrant_actions_controller
	///assoc list mob = list(type = action datum assigned to mob)
	var/list/mob/occupant_actions
```

2021-08-28 22:35 UTC, BraveMole approved these changes

2021-08-28 22:36 UTC, merged