Map contrib guidelines added
tgstation/TerraGov-Marine-Corps pull request #8104
Opened 2021-08-28 11:41 UTC by BraveMole

This is a draft, feel free to express remarks

2021-08-28 13:12 UTC, vilereaver41 commented
Items of benefit such as barrels inside the fob should be a no go. LZ1 in lv has 70 free metal worth

2021-08-31 08:25 UTC, SplinterGP requested changes

2021-08-31 08:25 UTC, SplinterGP commented on .github/CONTRIBUTING.md
> +6. [Map specifications](#map-specifications)
make a big one i think like meet the team with Sub's

2021-09-10 12:38 UTC, TiviPlus approved these changes

2021-09-10 12:39 UTC, merged