make captain have level 3 surgery
tgstation/TerraGov-Marine-Corps pull request #8107
Opened 2021-08-28 15:29 UTC by Anystar1

## About The Pull Request

makes captain have level 3 surgery
## Why It's Good For The Game

so captain can do surgery when theres no shipside medical staff
## Changelog
:cl:
add: Captain now has level 3 surgery.
/:cl:

2021-08-28 15:32 UTC, Hekzder commented
It's called using the autodoc. Skill issue. Captain doesn't need to know how to do literally everything.

2021-08-28 15:33 UTC, Anystar1 commented
wrong place

2021-08-28 15:42 UTC, Anystar1 commented
edited the PR

2021-08-28 16:31 UTC, BraveMole requested changes

2021-08-28 16:31 UTC, BraveMole commented on code/datums/skills.dm
> +	surgery = SKILL_SURGERY_PROFESSIONAL
This is not level 1 ???

2021-08-28 17:28 UTC, Pariah919 commented
give him the skill to use an autodoc without fumbling

2021-08-28 18:52 UTC, Nirvan4 commented
This is not bad to captain, I had plenty of experiences as cap with no crew, its really painful to do everything and dont have skills to do half of them.

2021-08-29 02:26 UTC, Anystar1 commented on code/datums/skills.dm
> +	surgery = SKILL_SURGERY_PROFESSIONAL
i think i made it amateur now?

2021-09-02 12:27 UTC, BraveMole approved these changes

2021-09-02 12:27 UTC, merged