makes it so g8 pouch can't hold more than one gun
tgstation/TerraGov-Marine-Corps pull request #8108
Opened 2021-08-28 16:14 UTC by Pariah919

## About The Pull Request
that's it

## Why It's Good For The Game
nerfs pulling 8 pistols out of your ass 

## Changelog
:cl:
balance:g8 pouch can only hold one gun
/:cl:

2021-08-28 16:16 UTC, BraveMole approved these changes

2021-08-28 17:33 UTC, BraveMole requested changes

2021-08-28 17:33 UTC, BraveMole commented on code/game/objects/items/storage/belt.dm
> +		/obj/item/weapon/gun = 1,
```suggestion
		/obj/item/weapon/gun = 2,
```

akimbo shouldn't be affected by this

2021-08-29 02:26 UTC, mathis650 commented
xenos malding about ocelot

2021-08-29 16:37 UTC, BraveMole approved these changes
David said yes to bag, i assume he's saying yes to this too

2021-08-29 16:37 UTC, merged