Adds a sesonal only machinecarbine gun, and a bucket for it
tgstation/TerraGov-Marine-Corps pull request #8109
Opened 2021-08-28 17:25 UTC by Pariah919

## About The Pull Request
Adds the ALF-51B machine carbine and the seasonal for it, type 51 slight description change for the seasonal since moths aren't real.

stats of the ALF51-B are 80 round magazines, same bullet as skirmisher, but it has triple falloff so it does nearly no damage past CQC, other than that it's just a T-18 with a big box magazine and worse gun stats and no aim mode.

## Why It's Good For The Game
Adds a unique seasonal gun and the Type-71 deserved a seasonal for a bit.
I think the 51B will be a unique enough gun to warrant this, though it might need more tweaking

## Changelog
:cl:
add: machinecarbine, has the stats of a t-18, but with worse slowdown, incredibly high falloff, has a bigger damaging/sundering bullet, has more in the magazine. Also no aim mode.
expansion: Machinecarbine/Type-71 bucket for seasonals.
/:cl:

2021-08-28 17:40 UTC, Kuro020 commented
this is so ugly I'm crying

2021-08-28 17:46 UTC, Kuro020 approved these changes

2021-08-29 14:17 UTC, TiviPlus requested changes
rest is fine

2021-08-29 14:17 UTC, TiviPlus commented on code/modules/projectiles/guns/rifles.dm
> +	desc = "The ALF-51B is an unoffical modification of a ALF-4, or better known as the T-18 carbine, modified to SMG length of barrel, rechambered for a stronger round, and belt based. Truly the peak o
Dont use numbers in typepaths

2021-08-29 14:17 UTC, TiviPlus commented on code/modules/projectiles/magazines/rifles.dm
> +/obj/item/ammo_magazine/rifle/alf51b
ditto

2021-08-29 16:54 UTC, TiviPlus approved these changes

2021-08-29 17:56 UTC, BraveMole approved these changes

2021-08-29 18:19 UTC, merged

2021-08-30 02:58 UTC, Tristan63 commented
![](https://i.imgur.com/gpacdMm.jpeg)