Flashlights are now not useless
tgstation/TerraGov-Marine-Corps pull request #8119
Opened 2021-08-29 13:36 UTC by EvilMelonTheSecond

## About The Pull Request
Combat flashlights are now unacidable as a response to #8100

## Why It's Good For The Game
Combat flashlights are an inferior alternative to flares yet they somehow got nerfed without proper reason. Flares are easier to carry, easier to resupply AND have added utility of burning targets when thrown at them. Flashlights are generally used because of map spawns rather than somebody intentionally packing a whole bag of flashlights (instead of packing flares which is at least 4 times more space efficient I believe).

Now flashlights have a niche instead of becoming obsolete.

## Changelog
:cl:
balance: Combat flashlight is now unacidable
/:cl:

2021-08-29 13:38 UTC, RenGusta commented
the mad lad actually did it

2021-08-29 17:54 UTC, BraveMole requested changes
Xeno rarely take the time to melt flashlights, and frankly if they do, good for them IMO.

Flashlish niche is that it stays up until xenos come by, and after that you can light them up again beause most of the time xeno won't melt.

2021-08-30 09:04 UTC, EvilMelonTheSecond commented
> 
> 
> Xeno rarely take the time to melt flashlights, and frankly if they do, good for them IMO.
> 
> Flashlish niche is that it stays up until xenos come by, and after that you can light them up again beause most of the time xeno won't melt.

What do you mean "rarely melt flashlights"? They are literally the same as flares and I've never seen xeno treat flashlights differently than flares.

Flashlights HAD a niche of staying up permanently but now they can be slashed by a runner passing by the area thus making it fully obsolete compared to just putting up flares all over the place. If I read the code correctly than flares have a lifetime of 800-1000 ticks and assuming 1 tick = 2 seconds that gives us an average of 30 minutes of lifetime for flares which might as well be infinite considering average round duration.

2021-08-30 20:59 UTC, lbnesquik commented
> 
> 
> > Xeno rarely take the time to melt flashlights, and frankly if they do, good for them IMO.
> > Flashlish niche is that it stays up until xenos come by, and after that you can light them up again beause most of the time xeno won't melt.
> 
> What do you mean "rarely melt flashlights"? They are literally the same as flares and I've never seen xeno treat flashlights differently than flares.
> 
> Flashlights HAD a niche of staying up permanently but now they can be slashed by a runner passing by the area thus making it fully obsolete compared to just putting up flares all over the place. If I read the code correctly flares have a lifetime of 800-1000 ticks and assuming 1 tick = 2 seconds that gives us an average of 30 minutes of lifetime for flares which might as well be infinite considering average round duration.

1 tick is supposed to be 1/10th of a second.

2021-08-31 08:26 UTC, SplinterGP approved these changes
This is okay for me.

2021-08-31 08:27 UTC, SplinterGP commented
> 
> 
> Xeno rarely take the time to melt flashlights, and frankly if they do, good for them IMO.
> 
> Flashlish niche is that it stays up until xenos come by, and after that you can light them up again beause most of the time xeno won't melt.

okay but what they rarely doing it has to do with them being able or not ?, if xenos start having habit to acid them then you'd need this, and if they dont acid it, this doens't affect it at all.

2021-09-01 08:49 UTC, BraveMole approved these changes
Ok, if splinter likes it

2021-09-01 08:49 UTC, merged