Space agent no longer reset timeofdeath, support for ghostroles, players cannot steal aghosted xenos, ghost can take afk marines
tgstation/TerraGov-Marine-Corps pull request #8145
Opened 2021-09-02 13:51 UTC by BraveMole

## About The Pull Request

Fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/8143

you can no longer cheat respawn timer by spawning as a space agent

Support for ghost roles, aka it's possible to add ghost roles without killing respawn timer. Also allow admin memery without killing respawn timer

AFK marines are takable by ghosts, exactly like xenos.

## Why It's Good For The Game

QOL and bug fixes. AFK marines being free for the taking was approved by headmin

## Changelog
:cl:
fix: You can no longer steal aghosted bodies
fix: Spawning as a space agent no longer allow to bypass respawn timer
add: AFK marines can be taken by ghosts
/:cl:

2021-09-04 08:16 UTC, MereWalker commented
I don't know of any admins cheating the respawn system but this is much liked since most of us tend to keep track of our time since becoming an agent resets the timer. Regardless this is a great idea and the other additions are great! Thank you!

2021-09-06 13:59 UTC, XSlayer300 commented
I accidentally did abuse this, once, tbh. I'm glad that ppl can't steal aghosted xenos anymore thankfully.

2021-09-06 13:59 UTC, XSlayer300 commented on code/modules/mob/dead/observer/observer.dm
> +		to_chat(src, span_warning("You died too recently to be able to take a new mob"))
```suggestion
		to_chat(src, span_warning("You died too recently to be able to take a new mob."))
```

2021-09-06 14:00 UTC, XSlayer300 commented
I wonder, how long will be the AFK timer for the marines be? 5 minutes I guess?

2021-09-06 15:37 UTC, BraveMole commented
> I wonder, how long will be the AFK timer for the marines be? 5 minutes I guess?

5 minutes, but that's up for discussion

2021-09-07 19:37 UTC, BraveMole commented on tgmc.dme
> +#include "code\datums\elements\accelerate_on_cross.dm"
```suggestion
```

2021-09-09 21:24 UTC, TiviPlus requested changes

2021-09-09 21:24 UTC, TiviPlus commented on code/modules/mob/dead/observer/observer.dm
> +		to_chat(src, span_warning("You died too recently to be able to take a new mob."))
...afk timer?

2021-09-09 21:24 UTC, TiviPlus commented on code/modules/mob/living/living.dm
> +					return
early return

2021-09-12 12:17 UTC, TiviPlus approved these changes

2021-09-12 12:17 UTC, merged