Increases ammo belt storage slots.
tgstation/TerraGov-Marine-Corps pull request #8156
Opened 2021-09-02 23:03 UTC by SplinterGP

## About The Pull Request
increases the slots of ammo belt, letting you storage 7 magazines instead of 5.

## Why It's Good For The Game
The ammo belt is by far the generally most useless belt, letting you storage only 5 magazines while other belts let you storage ammo for much much longer staying, people often infact prefer to just put magazines in magazines pouch and take something else on belt since this carries so little ammo.

## Changelog
:cl:
balance: magazine ammo belt now has 7 slots from old 5
/:cl:

2021-09-03 00:08 UTC, Pariah919 commented
feels like powercreep
make it 6

2021-09-03 01:15 UTC, Hekzder commented
> feels like powercreep
> make it 6

Agree that 6 is better, 7 seems a bit much.

2021-09-03 08:22 UTC, BraveMole requested changes

2021-09-03 08:22 UTC, BraveMole commented on code/game/objects/items/storage/belt.dm
> +	storage_slots = 7
```suggestion
	storage_slots = 6
```

You've heard what MJP said old man

2021-09-03 08:22 UTC, BraveMole commented on code/game/objects/items/storage/belt.dm
> +	max_storage_space = 21
```suggestion
	max_storage_space = 18
```

2021-09-03 23:29 UTC, SplinterGP commented
> 
> 
> feels like powercreep
> make it 6

i kinda thought on 7 because 6 is not that much excusable when you can just take a medbelt/shotgun belt/holster pouch and 2 mag pouches

2021-09-05 14:49 UTC, Losenis commented
Were it on 6 you'd be better off looting a medical rig/lifesaver belt from medbay and taking 2 magazine pouches instead of taking an ammo belt and 2 medkit pouches.

2021-09-11 13:54 UTC, BraveMole approved these changes

2021-09-11 13:55 UTC, merged