Lets you clear a single recipe from dispensers
tgstation/TerraGov-Marine-Corps pull request #8158
Opened 2021-09-03 01:08 UTC by QualityVan

## About The Pull Request
As title. Hit the delete recipes button, choose 'only one', and then press the recipe you wanna clear.

## Why It's Good For The Game
Being able to clear a specific recipe is better than having to clear all recipes if you want to remove one and then readd all the others.

## Changelog
:cl:
add: You can choose to only remove a single chem recipe instead of all of them when using a dispenser.
/:cl:

2021-09-03 08:59 UTC, BraveMole requested changes
Can't you add a button to directly clear the specific recipe, rather than this two steps thingy?

2021-09-03 08:59 UTC, BraveMole commented on code/modules/reagents/machinery/chem_dispenser.dm
> +			var/confirm_clear = tgui_alert(usr, "Clear all recipes?", null, list("Yes","No", "Only one"))
use a switch

2021-09-03 09:57 UTC, QualityVan commented
> 
> 
> Can't you add a button to directly clear the specific recipe, rather than this two steps thingy?

If I do it this way I don't have to mess with tgui stuff. Also, I'm not sure about single-stage clearing. Would each recipe have its own remove button? You could clear by having the button let you input a recipe name, but that just seems less convenient than a two-button option.

2021-09-04 22:10 UTC, SplinterGP commented
I think this delete mode is better because having a delete button on the side of EACH recipe  is a bit annoying

2021-09-05 19:53 UTC, BraveMole requested changes

2021-09-05 19:53 UTC, BraveMole commented on code/modules/reagents/machinery/chem_dispenser.dm
> +				if(actually_clear == "Yes")
```suggestion
				if(tgui_alert(usr, "Clear recipe [params["recipe"]]?", null, list("Yes","No")  == "Yes"))
```

2021-09-05 19:53 UTC, BraveMole commented on code/modules/reagents/machinery/chem_dispenser.dm
> +				clearing_recipe = FALSE
eh, you have a clear recipe button to remove that already

2021-09-05 19:53 UTC, BraveMole commented on code/modules/reagents/machinery/chem_dispenser.dm
> +			switch(confirm_clear)
ditto, useless var

2021-09-06 15:38 UTC, BraveMole approved these changes

2021-09-06 15:38 UTC, merged