Miner module buff for reinforcement and overclock
tgstation/TerraGov-Marine-Corps pull request #8162
Opened 2021-09-03 17:47 UTC by EvilMelonTheSecond

## About The Pull Request
Adds extra features to reinforced upgrade and slightly buffs overclock upgrade for miners

## Why It's Good For The Game
I've literally never seen any upgrade other than automation module on miners for months. I hope the extra overclock buff makes it desirable for easy to defend miners and reinforcement for hard to defend ones.

## Changelog
:cl:
balance: Miner reinforcement upgrade protects against non-strong castes
balance: Miner overclock upgrade is 10 ticks faster
/:cl:

2021-09-03 17:49 UTC, Lefunny commented
Sounds good to me, lets make marines cadehugg overclocked miners and after five(5) minutes spam a b18 army, amazing

2021-09-03 17:50 UTC, EvilMelonTheSecond commented
> 
> 
> Sounds good to me, lets make marines cadehugg overclocked miners and after five(5) minutes spam a b18 army, amazing

Frankly I am kinda unsure about the overclock upgrade myself. But it's so underused that I figured a slight buff would be fine.

2021-09-03 20:14 UTC, BraveMole requested changes

2021-09-03 20:14 UTC, BraveMole commented on code/game/objects/machinery/miner.dm
> +	if( (miner_upgrade_type == MINER_RESISTANT) && !((X.mob_size == MOB_SIZE_BIG || X.xeno_caste.caste_flags & CASTE_IS_STRONG)) ) //Reinforced miners can't be attacked unless the caste is strong
```suggestion
	if(miner_upgrade_type == MINER_RESISTANT && !((X.mob_size == MOB_SIZE_BIG || X.xeno_caste.caste_flags & CASTE_IS_STRONG)) ) //Reinforced miners can't be attacked unless the caste is strong
```

2021-09-03 20:14 UTC, BraveMole commented on code/game/objects/machinery/miner.dm
> +		X.visible_message(span_notice("You can't slash through [src]'s reinforced plating!"))
check how other visible messages are, there are two parts

2021-09-03 20:53 UTC, EvilMelonTheSecond commented on code/game/objects/machinery/miner.dm
> +		X.visible_message(span_notice("You can't slash through [src]'s reinforced plating!"))
Fixed up... hopefully

2021-09-03 21:47 UTC, hyper2snyper commented on code/game/objects/machinery/miner.dm
> +	if(miner_upgrade_type == MINER_RESISTANT && !((X.mob_size == MOB_SIZE_BIG || X.xeno_caste.caste_flags & CASTE_IS_STRONG)) ) //Reinforced miners can't be attacked unless the caste is strong
```suggestion
	if(miner_upgrade_type == MINER_RESISTANT && !(X.mob_size == MOB_SIZE_BIG || X.xeno_caste.caste_flags & CASTE_IS_STRONG) ) //Reinforced miners can't be attacked unless the caste is strong
```

2021-09-03 21:47 UTC, hyper2snyper commented on code/game/objects/machinery/miner.dm
> +		span_notice("You can't slash through [src]'s reinforced plating!"))
```suggestion
		span_notice("We can't slash through [src]'s reinforced plating!"))
```
Xenos refer to themselves as we.

2021-09-03 23:28 UTC, SplinterGP commented on code/game/objects/machinery/miner.dm
> +		span_notice("You can't slash through [src]'s reinforced plating!"))
this is not enforced anymore.

2021-09-03 23:54 UTC, hyper2snyper commented on code/game/objects/machinery/miner.dm
> +		span_notice("You can't slash through [src]'s reinforced plating!"))
It isnt? Interesting.

2021-09-05 16:43 UTC, TiviPlus approved these changes

2021-09-05 16:43 UTC, TiviPlus commented on code/game/objects/machinery/miner.dm
> +		X.visible_message(span_notice("[X]'s claws bounce off of [src]'s reinforced plating."),
```suggestion
	if(miner_upgrade_type == MINER_RESISTANT && !(X.mob_size == MOB_SIZE_BIG || X.xeno_caste.caste_flags & CASTE_IS_STRONG))
		X.visible_message(span_notice("[X]'s claws bounce off of [src]'s reinforced plating."),
```

2021-09-06 09:02 UTC, BraveMole approved these changes

2021-09-06 09:02 UTC, merged