Toning down infections
tgstation/TerraGov-Marine-Corps pull request #8187
Opened 2021-09-06 02:42 UTC by QualityVan

## About The Pull Request
Tuning for wound/limb infection.
Wounds gaining germs is unchanged, but once they're closed they'll slowly clear out their own infection if it's not too high. Kitting and antibiotics help here.
Slightly rescaled how fast wound germs transfer to the limb: a minimum amount are required so a fresh wound won't start transferring instantly, but higher amounts scale a touch sharper.
Infected limbs are now much more apparent to their player, with repeating messages the same way broken bones show up. These're suppressed if you have spaceacillin in you.
Health analyzers have a lower threshold for detecting infected wounds.

Also a minor fix with wounds not changing their current state correctly when they worsen. Shouldn't affect function at all, just how they show up on examine.

## Why It's Good For The Game
They're a bit excessive right now. This might be too much, but there's plenty of knobs to tune back up later.

## Changelog
:cl:
qol: Infected limbs are less subtle to their owner.
balance: Wounds with smaller amounts of germs will now disinfect passively over time. Treatment speeds this up.
balance: Fresh wounds won't immediately start infecting the limb they're on.
fix: Wounds that worsen now do so more visibly.
/:cl:

2021-09-06 15:51 UTC, BraveMole requested changes

2021-09-06 15:51 UTC, BraveMole commented on code/modules/organs/limbs.dm
> +		if(!W.germ_level)
```suggestion
		if(W.germ_level <= 0)
```

2021-09-06 15:51 UTC, BraveMole commented on code/modules/organs/limbs.dm
> +	var/next_infection_message
We have cooldown declaration that are doing just that

2021-09-06 15:51 UTC, BraveMole commented on code/modules/organs/limbs.dm
> +					next_infection_message = world.time + 60 SECONDS + rand(0, 300) //Next message 60-90 seconds from now.
```suggestion
					next_infection_message = world.time + rand(60 SECONDS, 90 SECONDS)//Next message 60-90 seconds from now.
```
But use cooldown start anyway

2021-09-06 15:51 UTC, BraveMole commented on code/modules/organs/limbs.dm
> +					next_infection_message = world.time + 25 SECONDS + rand(0, 150) //Next message 25-40 seconds from now.
ditto

2021-09-08 21:09 UTC, QualityVan commented on code/modules/organs/limbs.dm
> +	var/next_infection_message
```suggestion
	COOLDOWN_DECLARE(next_infection_message)
``` Thusly?

2021-09-08 21:20 UTC, BraveMole approved these changes

2021-09-10 10:43 UTC, BraveMole approved these changes

2021-09-10 10:43 UTC, merged