BigredV2.2
tgstation/TerraGov-Marine-Corps pull request #8226
Opened 2021-09-09 13:17 UTC by vilereaver41

## About The Pull Request

Changes a lot of things for Bigred.

## Why It's Good For The Game

Gives more variety in gameplay for both sides

## Changelog
:cl:
Balance: I've weeded all-around big red as Xenos often times don't have enough weeders or don't weed at all, they should be focusing on defenses, this helps.
Balance: Re did attack points for LZ1 as well as LZ2
Add: a new section west of Cargo that connects to caves and Viro to make it more accessible as marines often times have to go all the way around whilst Xenos will get to stop heavy marine pushes from this side as well.
Balance: removed some leftovers from my previous 2.1 such as the supplies at LZ1 and stuff.
Balance: added a little path that connects cargo to Medbay.
Balance: Xenos should be able to build in the far Southwest caves as the no-build zones were to far extending outwards.
Balance: Added some more acid turrets around caves as they are the Xenos territory and marines shouldn't be able to push them so freely without worry, especially solo
/:cl:

![image](https://user-images.githubusercontent.com/64131993/132692340-fc81b73a-e42b-4fe0-9ae3-22dac7d4105d.png)
![image](https://user-images.githubusercontent.com/64131993/132692378-b48783e1-3664-4af7-a8d0-b4390bf0b140.png)
![image](https://user-images.githubusercontent.com/64131993/132692423-b4bd015c-d7b1-4aac-a24a-eeb95ad72c4d.png)

Closing notes: Both LZ's should be a bit tougher for Xenos to freely siege but at the same time it also gives them more options to keep a siege.

2021-09-10 21:28 UTC, GradusNL commented
Weeding the entire map is a bit much. Weeding the entire caves and labs should be enough.

2021-09-11 02:47 UTC, lKiseki commented
Admittedly not liking these changes much since they favor xenos a lot, what with both LZs allowing for easier routes, at least for them.

2021-09-11 03:33 UTC, RipGrayson commented
I'm getting Déjà vu to when we preweeded the entirety of LV624, which was about the time it became the incredibly unbalanced map we have today. I can understand weeding caves and labs, but does the whole map really need weeded?

2021-09-13 23:02 UTC, Pariah919 commented
hard dislike of big red changes
makes a big map even bigger and removes most of the interesting dynamic in mid since the sides are humongous

2021-09-14 08:39 UTC, BraveMole requested changes
I like the map, so small remarks to fix and then it's merged.

- Too much weed. Big red is already really xeno - sided, it doesn't need a xeno buff compared to the other maps. If you want to weed everything, do that in a separate pr so the discussion can be done, like with david

- Add back the sensor towers that were added in civil war, they are on the master branch big red version

- Similarly, the dropship console must be replaced by landmarks, like in the master branch version

- This is a deadend trap, i don't like it 
![image](https://user-images.githubusercontent.com/25491240/133224832-6370db19-0e06-49ad-af76-7be882cc8bef.png)

- Windows/doors here?
![image](https://user-images.githubusercontent.com/25491240/133224922-7da27604-1f5c-423a-8688-985640355aec.png)

2021-09-20 19:05 UTC, BraveMole commented
Untm until the changes are done

2021-09-23 10:16 UTC, BraveMole commented
Closing as stale. Feel free to ask for a reopen, or someone can take up the map and fix the issues

2021-09-23 10:16 UTC, closed without merging