Fixes combat injector ryetalyn doing nothing sometimes
tgstation/TerraGov-Marine-Corps pull request #8227
Opened 2021-09-09 15:24 UTC by QualityVan

## About The Pull Request
Combat injectors give 2.5u ryetalyn per jab, but come with bic and kelo which each purge 1u of it per life tick. If the mob also has neurotoxin in it, that means the whole 2.5u will be gone before it can tick once. This moves the ryetalyn before the b/k in chem order, which means it'll tick at least once before getting purged out.

## Why It's Good For The Game
Bugfix?

## Changelog
:cl:
fix: The ryetalyn in combat injectors will now always purge toxins at least a little, instead of sometimes not at all.
/:cl:

2021-09-10 10:46 UTC, BraveMole requested changes
IMO it's still dumb to have a mix of medicine that are pruging each other.

How about replacing this with dyloven? Since it doesn't cause satm damage if it's lower than 10 u,  that might do the trick

2021-09-10 14:33 UTC, jroinc commented
Too *much* purge in that case. Though I suppose swapping out the 2.5u ryetalin for 1u dylo would be the same effect.

2021-09-10 16:31 UTC, QualityVan commented
Swapping it to 5u total dylo, 2.5 per injection, is probably fine. It's significantly better at that point against light neuro but significantly worse against standard, and without the whole self-purging thing.

2021-09-15 23:02 UTC, QualityVan commented on code/game/objects/items/reagent_containers/autoinjectors.dm
>  		/datum/reagent/medicine/tramadol = 5,
```suggestion
		/datum/reagent/medicine/bicaridine = 10,
		/datum/reagent/medicine/kelotane = 10,
		/datum/reagent/medicine/dylovene = 5,
		/datum/reagent/medicine/tramadol = 5,
```

2021-09-15 23:13 UTC, BraveMole approved these changes

2021-09-15 23:13 UTC, merged