Update ooc.dm, Adds two new OOC verbs for team-based OOC.
tgstation/TerraGov-Marine-Corps pull request #8241
Opened 2021-09-11 07:22 UTC by MiniMeatwad

## About The Pull Request

Copies prefs and spans and bans from OOC because I don't know how to touch those, and since it involves preferences and possibly database stuff; I don't think we modify those until changes are fully merged permanently.

I'm not entirely sure about the safety of the admin-related checks since I didn't look into all of the admin code, but when I tested in-game alone (I don't know how to get multiple clients on a local server), it was fine.

## Why It's Good For The Game

So people can talk to their entire team through OOC means.

## Changelog
:cl:
add: Adds Team OOC, two new verbs in the OOC tab called XOOC and MOOC for Xeno and Marine.
code: Modified ooc.dm, adding two new verbs.
admin: XOOC and MOOC should have clickable player panel links for admins, and admins can see XOOC and MOOC chat.
/:cl:

Screenshot, 2 tests for admin and non-admin, and for observer/human/xeno:
![dreamseeker_P0kqvQxevi](https://user-images.githubusercontent.com/22848292/132939961-72cea5da-ce51-463d-b64a-8cba3d49723d.png)

2021-09-11 07:45 UTC, Alexeivichi commented
Been hoping for something like. You can connect multiple clients to one local server on the same machine by just logging in with a different user on your Byond pager, and connecting via Dream Maker as normal.

2021-09-11 07:45 UTC, MiniMeatwad commented
> 
> 
> Been hoping for something like. You can connect multiple clients to one local server on the same machine by just logging in with a different user on your Byond pager, and connecting via Dream Maker as normal.

Thanks.

2021-09-11 07:59 UTC, hyper2snyper commented on code/game/verbs/ooc.dm
> +		to_chat(src, span_warning("You must be a human to use XOOC."))
```suggestion
		to_chat(src, span_warning("You must be an xeno to use XOOC."))
```

2021-09-11 08:01 UTC, MiniMeatwad commented on code/game/verbs/ooc.dm
> +		to_chat(src, span_warning("You must be a human to use XOOC."))
lol thanks

2021-09-11 08:07 UTC, BraveMole requested changes
Pending headmins approval

2021-09-11 08:07 UTC, BraveMole commented on code/game/verbs/ooc.dm
> +	for(var/client/C in GLOB.clients)
```suggestion
	for(var/client/C AS in GLOB.clients)
```

2021-09-11 08:07 UTC, BraveMole commented on code/game/verbs/ooc.dm
> +		if(!GLOB.ooc_allowed)
a way to selectively mute each faction OOC would be nice IMO. Don't remove that though

2021-09-11 08:07 UTC, BraveMole commented on code/game/verbs/ooc.dm
> +	for(var/client/C in GLOB.admins)
```suggestion
	for(var/client/C AS in GLOB.admins)
```

2021-09-11 08:07 UTC, BraveMole commented on code/game/verbs/ooc.dm
> +	for(var/client/C in GLOB.admins)
```suggestion
	for(var/client/C AS in GLOB.admins)
```

2021-09-11 08:07 UTC, BraveMole commented on code/game/verbs/ooc.dm
> +	for(var/client/C in GLOB.clients)
```suggestion
	for(var/client/C AS in GLOB.clients)
```

2021-09-11 08:17 UTC, bobmancer343 commented
Yess, I have been asking for this concept for a bit. It's good for new players that want to ask for help from fellow marines, xenos.

2021-09-11 08:29 UTC, MiniMeatwad commented on code/game/verbs/ooc.dm
> +	for(var/client/C in GLOB.clients)
What does "AS in" do?

2021-09-11 08:34 UTC, MiniMeatwad commented on code/game/verbs/ooc.dm
> +	for(var/client/C in GLOB.admins)
Changed to "client/C AS in GLOB."

2021-09-11 08:34 UTC, MiniMeatwad commented on code/game/verbs/ooc.dm
> +	for(var/client/C in GLOB.admins)
Changed to "client/C AS in GLOB."

2021-09-11 08:34 UTC, MiniMeatwad commented on code/game/verbs/ooc.dm
> +	for(var/client/C in GLOB.clients)
Changed to "client/C AS in GLOB."

2021-09-11 08:34 UTC, MiniMeatwad commented on code/game/verbs/ooc.dm
> +	for(var/client/C in GLOB.clients)
Changed to "client/C AS in GLOB."

2021-09-11 15:34 UTC, lKiseki commented
> Pending headmins approval

Lewd seal of approval (TM).

2021-09-11 15:36 UTC, BraveMole requested changes
I don't see any keybinds? Defintly add thos

2021-09-12 00:37 UTC, MiniMeatwad commented
> 
> 
> I don't see any keybinds? Defintly add thos

Added, no assigned keys since the keybindings are already cluttered. Users can set them if they need them.

2021-09-12 08:07 UTC, BraveMole approved these changes

2021-09-12 09:11 UTC, MiniMeatwad commented
Changed title since someone said there should be less "update file.dm"s in my PRs, now missing TM label

2021-09-12 12:43 UTC, BraveMole approved these changes

2021-09-12 12:44 UTC, merged