Hunter is SUS SUS AMOGUS
tgstation/TerraGov-Marine-Corps pull request #8259
Opened 2021-09-11 16:36 UTC by BraveMole

## About The Pull Request

Stealth will transform the hunter into it's marked target. 
Also make staying in stealth less plasma expensive

## Why It's Good For The Game

SUS

## Changelog
:cl:
add: Hunter can disguise itself as it's marked target, this replaces stealth
balance: stealth is less expensive to maintain
/:cl:

2021-09-11 17:06 UTC, bobmancer343 commented
HUNTER VENTING IN IMPOSTER AMONG US

2021-09-11 17:07 UTC, joniroq commented
Can't wait to get bwoinked for shooting other marines and say I was "spy checking" them

2021-09-11 17:50 UTC, mcmeiler commented
> 
> 
> Can't wait to get bwoinked for shooting other marines and say I was "spy checking" them

Do it with a flamethrower as well for maximum funny

2021-09-11 18:46 UTC, neohenry commented
time to play prop HUNTer

2021-09-13 20:59 UTC, SplinterGP commented
is this some random fun config feature with a balance change

2021-09-13 21:08 UTC, BraveMole commented
> is this some random fun config feature with a balance change

Nah i just forgot to remove the balance part, it was there initially (when this wasn't a shitpost)

2021-09-15 00:41 UTC, Tristan63 commented
kek

2021-09-17 09:58 UTC, Ragecrabbo commented
I need this

2021-09-17 18:53 UTC, TiviPlus requested changes

2021-09-17 18:53 UTC, TiviPlus commented on config/config.txt
> +FUN_ALLOWED 1
```suggestion
#HARD_DELETES_OVERRUN_LIMIT 0
```

2021-09-17 19:06 UTC, TiviPlus approved these changes

2021-09-17 19:06 UTC, merged