Infinite gauze, finite brute kits
tgstation/TerraGov-Marine-Corps pull request #8267
Opened 2021-09-12 00:32 UTC by QualityVan

## About The Pull Request
Prevents restocking stacks if they don't have the amount the stack initially had.
Gauze and ointment in the marine meds are infinite.

## Why It's Good For The Game
Limiting the better, specialist option while making the general option more available.
If you really need more kits, you can buy 50 of each for 5 req points.

## Changelog
:cl:
balance: Marine meds have infinite gauze and ointment
balance: Stacks can't be restocked in vendors unless they have the count they started with.
/:cl:

2021-09-12 00:35 UTC, jroinc commented
Seems reasonable. Up the marinemed quantity some, to 20 total?

2021-09-12 07:34 UTC, EvilMelonTheSecond commented
So now people will run outta kits to revive people and have to beg req before bodies go cold. The "specialist" option is mandatory for revivals and the cheap option already has the upside of not having a low medical skill debuff, this isn't a good idea.

2021-09-12 15:51 UTC, BraveMole approved these changes

2021-09-12 15:52 UTC, BraveMole requested changes

2021-09-12 15:52 UTC, BraveMole commented on code/game/objects/machinery/vending/vending.dm
> +		else if(istype(item_to_stock, /obj/item/stack))
isitemstack

2021-09-12 17:00 UTC, QualityVan commented on code/game/objects/machinery/vending/vending.dm
> +		else if(istype(item_to_stock, /obj/item/stack))
```suggestion
		else if(isitemstack(item_to_stock))
```

2021-09-13 11:23 UTC, merged

2021-09-14 17:36 UTC, Losenis commented
>Has a delay if you're not a corpsman
>Covers only one single bodypart
>You have to check what bodypart is damaged first, either by scan of self-check
>One stack doesn't even cover for all bodyparts since there's 10 kits for 11 bodyparts if the guy just got fucked over by explosives or god forbid being on the literal last tile of an HE OB
>Bruh let's nerf it