Readds the ZX-76
tgstation/TerraGov-Marine-Corps pull request #8299
Opened 2021-09-15 01:19 UTC by Pariah919

## About The Pull Request
By David request it readds the ZX76, 120 points from Req, it is a CQC monster, basically useless past that due to scatter, outside of burst.

Deals big dick damage and doesn't require special ammo to work, it's pretty nice.

Sprite by Joniroquai#8011 on discord.

---
STATS
0.9 damage mult, 2 scatter on semi, 12 on burst fire. 0.45 aim slowdown, 0.75 Wield delay. 0.001 burst delay. +1.25 secondso f extra delay on burst fire
---
Changes from old ZX
- Wield delay is higher overall, aim slowdown is lower since it isn't a roundstart gun anymore.
-10% less damage
-More scatter on burst
-RC/EB removed, if you want to lower that scatter, go get a vert grrip, noob
-+1.25 fire delay if you fire with it on burst.

## Why It's Good For The Game

## Changelog
:cl:
add: the ZX-76 returns in it's (nerfed) glory, avaliable for 100 req points.
balance: zx no longer has rc/eb, deals 10% less damage, burst fire has far more scatter, fires .25 faster. 
/:cl:

2021-09-15 04:50 UTC, David-Stormwell commented
Make it 120 points instead, otherwise 100 is too cheap for it's skill ceiling, having a big dick damage cqc weapon which can use standard ammo might make xenos cringe a little, but it does give a good option other then people spamming sadar/minigun like the nerds they are.

2021-09-15 06:10 UTC, Pariah919 commented
>Make it 120 points instead, otherwise 100 is too cheap for it's skill ceiling, having a big dick damage cqc weapon which can use standard ammo might make xenos cringe a little, but it does give a good option other then people spamming sadar/minigun like the nerds they are.
>
it's 120 now, should be ok

2021-09-15 07:53 UTC, BraveMole requested changes
Some remarks:
- Does this insta delete let's say mature drones? or mature defenders?
- If this is only useable in CQC, make a special ammo for it, reduce the price of the gun a bit. That's for the sake of consistency (T2 guns have T2 ammo). Also make that ammo expensive, shotguns tends to use a low ammount of shells anyway
- This sprites is way to banal. Xenos should be able to spot the gun and play accordingly, not think it's just another stupid shotguner but ending up blasted in half a sec

2021-09-15 07:53 UTC, BraveMole commented on code/modules/projectiles/guns/shotguns.dm
> +						/obj/item/attachable/attached_gun/grenade)
Why would you ever add attached_gun? It's a gimmick gun with only CQC in mind, this doesn't belong there

2021-09-15 08:20 UTC, David-Stormwell commented
> 
> 
> Some remarks:
> 
>     * Does this insta delete let's say mature drones? or mature defenders?
> 
>     * If this is only useable in CQC, make a special ammo for it, reduce the price of the gun a bit. That's for the sake of consistency (T2 guns have T2 ammo). Also make that ammo expensive, shotguns tends to use a low ammount of shells anyway
> 
>     * This sprites is way to banal. Xenos should be able to spot the gun and play accordingly, not think it's just another stupid shotguner but ending up blasted in half a sec

1: So does the SADAR, and other meme weapons/builds.

2: Shotguns use more shells then you realize in long engagements, and if you're maining it, which you'd probably be doing so with the ZX you'll run though quite a bit of ammo.

3: I semi agree, but the sound of it is different enough most of the time that you'll know, and xenos already cope with DBs and normal shotguns ok enough.

4: The utility of it seems fine, if anything, at most, making it so flechette can't be used can be a thing **_At most_**.

Daily reminder other spec weapons exist which can end a xeno's life quite easily, from the scout rifle nobody uses for some odd reason, to the sadar and antimat marine rifle, this fills in the role of being another choice while not being off-screen delete button, and do mind CQC is much more dangerous , from warriors to even a simple defender tailsweep ending your rampage quite easily.

2021-09-15 15:28 UTC, Kuro020 requested changes
well like bravemole said,this probably should stand out more,paint it red or something

2021-09-16 03:21 UTC, vilereaver41 commented
That sprite is disgusting for a 120 req wep.

2021-09-16 05:54 UTC, Pariah919 commented
>
    Does this insta delete let's say mature drones? or mature defenders?
    If this is only useable in CQC, make a special ammo for it, reduce the price of the gun a bit. That's for the sake of consistency (T2 guns have T2 ammo). Also make that ammo expensive, shotguns tends to use a low ammount of shells anyway
    This sprites is way to banal. Xenos should be able to spot the gun and play accordingly, not think it's just another stupid shotguner but ending up blasted in half a sec
>

Doesn't one shot mature drones, if you're shooting a mature drone at 3 tile which is the intended distance for a 120 point weapon, then this seems decent. Considering it's b18 level of price it should have a noticeable affect on the field.

Attached guns are there because it's a normal gun overall, I don't see the need for it to not have them outside of maybe removing masterkey.

Special ammo would mean I'd reduce the price to 90 or so, this uses up ammo quick, ZX is a ammo hog and the loss of most scatter attachments in this rework means that it needs to make it's shots count more.

Sprite is tan, no other gun is tan, and the shape is recognizable.

2021-09-18 00:06 UTC, TGCMbetcher commented
Im more worried about how say a flak vest premed SL would do against the queen while running and having the stamina regen command active. You can keep pace with the queen using normal armor sometimes with the command, high cqc burst and can keep up with t3s would be a deletion machine

2021-09-19 11:27 UTC, XSlayer300 commented on code/modules/projectiles/guns/shotguns.dm
> +	desc = "The ZX-76 Assault Shotgun, a incredibly rare, double barreled semi-automatic combat shotgun with a twin shot mode. Possibly the unrivaled master of CQC. Has a 9 round internal magazine."
```suggestion
	desc = "The ZX-76 assault shotgun, an incredibly rare, double barreled semi-automatic combat shotgun with a twin shot mode. Possibly the unrivaled master of CQC, and feared amongst other militaries for that reason alone. Has a 9 round internal magazine."
```

2021-09-19 11:28 UTC, XSlayer300 commented on code/modules/projectiles/guns/shotguns.dm
> +	caliber = "12 gauge shotgun shells" //codex
```suggestion
	caliber = "12 gauge" //codex
```
weapon literally became incompatible with shells once you pull them out

2021-09-26 14:55 UTC, BraveMole approved these changes
well, david like it and it's expensive, so i guess it's okay

2021-09-26 14:55 UTC, merged