Jeager refactor.
tgstation/TerraGov-Marine-Corps pull request #8303
Opened 2021-09-15 03:17 UTC by hyper2snyper

## About The Pull Request
Another Chonker here. So lets start.

### **Codewise:**
Rebases the jaeger system onto the coponent/element system that gun attachments use. 
This will mean that adding new attachment slots and devices will be much easier to add than the typecast single vars that determined armor pieces beforehand.

### **Features:**
Pas can now be recolored using the facepaint to its various map variants.
Helmets visors can be removed and I have added alternate metal faceplate versions. If you choose to not have a visor at all the helmet will shift itself to make it look better.

### **ALT CLICK WILL NOW REMOVE ATTACHMENTS! NO MORE TOOLS NEEDED!**

## Why It's Good For The Game
Adds a lot of support for more attachments and armor pieces.
Adds some extra cosmetic visors.
Allows visorless helmets.
Recolorable PAS as well as savable PAS colors.

## Changelog
:cl:
add: Visors can be removed from helmets. They can also be swapped out for new variants.
add: PAS can be recolored using green facepaint.
code: ALT-CLICK will now remove jaeger attachments.
refactor: CHONKY Jaeger refactor. Switching its base to that of the gun attachments.
/:cl:

2021-09-15 03:38 UTC, Kuro020 reviewed
nope,the faceplate and visorless helmets look bad,I'm not approving those sprites

2021-09-15 08:08 UTC, BraveMole commented
DNM until you convince the art director.

Also, Jeager? really?

2021-09-16 07:53 UTC, BraveMole requested changes

2021-09-16 07:53 UTC, BraveMole commented on _maps/map_files/Barrenquilla_Mining/Barrenquilla_Mining_Facility.dmm
> +/obj/machinery/vending/marine/shared/cigarette/colony,
lel

2021-09-16 07:53 UTC, BraveMole commented on code/__DEFINES/loadout.dm
>  GLOBAL_LIST_INIT(accepted_loadout_versions, list(5,6))
this has to change too. And delete the previous version transition code i did in save

2021-09-16 07:53 UTC, BraveMole commented on code/datums/components/attachment_handler.dm
> +				return
Just use ?

2021-09-16 07:53 UTC, BraveMole commented on code/datums/components/attachment_handler.dm
> +		var/icon_state = attachment.icon_state + "_a"
why adding "_a" ?

2021-09-16 07:53 UTC, BraveMole commented on code/datums/loadout/item_representation/_item_representation.dm
> +	var/item_icon_state
bad idea. If the icon state change in a future pr, you'll have no way of knowing this and the slot will be blank.

2021-09-16 07:53 UTC, BraveMole commented on code/datums/loadout/item_representation/armor_representation.dm
> +	for(var/datum/item_representation/armor_module/module in attachments)
AS?

2021-09-16 07:53 UTC, BraveMole commented on code/datums/loadout/item_representation/helmet_representation.dm
> +	for(var/datum/item_representation/armor_module/module in attachments)
AS

2021-09-16 07:53 UTC, BraveMole commented on code/game/objects/machinery/vending/marine_vending.dm
> +/obj/machinery/vending/marine/shared/cigarette
yeah no, move that to another PR

2021-09-16 07:53 UTC, BraveMole commented on code/modules/modular_armor/storage.dm
> +	storage = new storage(src)
ew. Where have you seen this, you've taken it of an exemple?

2021-09-16 07:53 UTC, BraveMole commented on code/modules/modular_armor/storage.dm
> +	QDEL_NULL(storage)
Is it possible to destroy a module without killing the armor it is on?
Is it possilbe to destroy an armor, but the module on it somewhat survive?

2021-09-16 07:53 UTC, BraveMole commented on code/modules/modular_armor/storage.dm
> +	icon_state = "invisable" //It is invisable
invisible?

2021-09-17 09:42 UTC, BraveMole requested changes
I'm not forcing you on the cache issue, i'll ask tivi her opinion on the matter first.

2021-09-17 09:42 UTC, BraveMole commented on code/modules/modular_armor/modular.dm
> +	var/list/attachments_allowed = list(
both of those could be cached IMO, but it's non blocking if you don't want to do it

2021-09-17 09:42 UTC, BraveMole commented on code/modules/modular_armor/modular.dm
> +	var/list/starting_attachments = list()
can be cached

2021-09-17 09:42 UTC, BraveMole commented on code/modules/modular_armor/storage.dm
> +	QDEL_NULL(storage)
If one of the above is true, then it's creating harddels

2021-09-17 19:27 UTC, BraveMole commented on code/datums/loadout/item_representation/armor_representation.dm
> +	modular_armor.current_variant = current_variant in modular_armor.icon_state_variants ? current_variant : initial(modular_armor.current_variant)
```suggestion
	modular_armor.current_variant = (current_variant in modular_armor.icon_state_variants) ? current_variant : initial(modular_armor.current_variant)
```

2021-09-17 22:41 UTC, TiviPlus requested changes

2021-09-17 22:41 UTC, TiviPlus commented on code/__DEFINES/loadout.dm
There needsto be conversionn instead of a full whipe

2021-09-17 22:41 UTC, TiviPlus commented on code/datums/loadout/item_representation/_item_representation.dm
> +
is this a signal used as a proccall

2021-09-17 22:41 UTC, TiviPlus commented on code/game/objects/machinery/vending/vending_types.dm
> -	name = "cigarette machine" //OCD had to be uppercase to look nice with the new formating
id appreciate if you atomized the cigar change in future

2021-09-17 22:41 UTC, TiviPlus commented on code/modules/modular_armor/attachments.dm
> +
autdoc

2021-09-17 22:41 UTC, TiviPlus commented on code/modules/modular_armor/attachments.dm
> +	slowdown = 0
redifine before new declare

2021-09-17 22:41 UTC, TiviPlus commented on code/modules/modular_armor/attachments.dm
> +/obj/item/armor_module/armor
missing documentation?

2021-09-17 22:41 UTC, TiviPlus commented on code/modules/modular_armor/attachments.dm
> +		return
for the sake of organization please use multiple files here
ie helmtet/chestölate0/moduless for example

2021-09-17 22:41 UTC, TiviPlus commented on code/modules/modular_armor/attachments.dm
> +/** Shoulder lamp strength module */
incorrect documentation formatting

2021-09-17 22:41 UTC, TiviPlus commented on code/modules/modular_armor/attachments.dm
> +	slot = ATTACHMENT_SLOT_MODULE
more var definition ordering

2021-09-17 22:41 UTC, TiviPlus commented on code/modules/modular_armor/attachments.dm
> +	return COMPONENT_NO_AFTERATTACK
always .proc/ for proc paths

2021-09-17 22:41 UTC, TiviPlus commented on code/modules/modular_armor/attachments.dm
> +	to_chat(user, "Right click the helmet to toggle the visor internal lighting.")
note to self
why isnt this using examine signal

2021-09-17 22:41 UTC, TiviPlus commented on code/datums/loadout/item_representation/helmet_representation.dm
> +		return
note to self
 whats going on here

2021-09-17 22:41 UTC, TiviPlus commented on code/datums/greyscale/greyscale_configs.dm
>  	icon_file = 'icons/mob/modular/eva.dmi'
not to self visor checks that visor exists

2021-09-17 22:41 UTC, TiviPlus commented on code/datums/components/attachment_handler.dm
> +			return
if can attach doesnt exist will this just fail and never work

2021-09-20 09:59 UTC, BraveMole requested changes
Ok so new directive for the loadout vendor:

You up the version to 7

You accept version 5,6 and 7

If the loadout version is accepted, you check the armor slot. If it's a modular armor, you remove it for the loadout, you bump the version of the loadout, and you save it

2021-09-20 09:59 UTC, BraveMole commented on code/datums/components/attachment_handler.dm
> +		if(can_attach && can_attach.Invoke(attachment))
i'm sure there's an operator that can help you here. I wonder what it is

2021-09-21 09:16 UTC, BraveMole requested changes
Also, standind tivi's issues, resolve them if you spoke to tivi about this, or fix it otherwise

2021-09-21 09:16 UTC, BraveMole commented on code/datums/loadout/loadout_manager.dm
> +				add_loadout(loadout)
a message to ui.user telling him that the loadout was updated would be nice. Like inside each if, say, the helmet was deleted for exemple

2021-09-21 19:21 UTC, TiviPlus requested changes

2021-09-21 19:21 UTC, TiviPlus commented on code/modules/modular_armor/attachments/storage.dm
> +
.proc

2021-09-21 19:21 UTC, TiviPlus commented on code/datums/loadout/item_representation/_item_representation.dm
> +	return storage
```suggestion
		item_to_insert.forceMove(get_turf(user))
```

2021-09-21 19:35 UTC, TiviPlus commented
other things to fix:
dont use the wrapper for the double-signal call
get kuro to yes/no on colorable skull
use a attackhand_alternate signal instead of right click signal (must call parent would be nice but if it doesnt work not required)

2021-09-22 09:31 UTC, TiviPlus approved these changes

2021-09-22 09:31 UTC, TiviPlus commented on code/modules/modular_armor/modular.dm
> +
```suggestion
	return ..()

```

2021-09-25 08:04 UTC, TiviPlus approved these changes

2021-09-25 08:04 UTC, merged