Adds Winchester lever action rifle
tgstation/TerraGov-Marine-Corps pull request #8306
Opened 2021-09-15 21:08 UTC by joniroq

## About The Pull Request

Add a Winchester Lever Action Rifle to the marine vendor (Rifle Category). Using .44 rounds it can hold 14 rounds plus one in the chamber. It fires considerably slower than the T-44 Revolver (comparable to the T-39 in terms of speed) and so DPS wise it is actually more effective to use two revolvers. The only real advantage is the lower damage fall off allowing it to be used more like a rifle at range.

Currently using inhands from the mosin and it doesn't animate. Will look to fix those at a later date.

## Why It's Good For The Game

Rootin' Tootin' Beno Shootin'. Only Lever action gun we have is the Mare's Leg, which is terrible. This adds an option for players that want to complete the cowboy loadout (sans cowboy hat)

## Changelog
:cl: Joniroq
add: Added Winchester lever action rifle. Uses .44 caliber rounds.

/:cl:

2021-09-15 21:09 UTC, joniroq commented
Wait where the hell did the sprites go?

2021-09-16 02:54 UTC, Pariah919 commented
disagree with making an entirely new gun with this, replace the mare's leg, considering this is basically a clone of it. And would ask to relent from refrencing a specific model of lever action rifle, make up a name or something.

As for balancing, set up 1 second FD and 0.2 Pump delay and give it a 1.5x damage mult.

2021-09-17 12:05 UTC, BraveMole requested changes
I don't really care about it being a duplicate of a surv weapon, but do the rest of what MJP said please.

2021-09-17 12:52 UTC, joniroq commented
Drafting this for now as I won't have time to work on it til monday or tuesday. @BraveMole

2021-09-20 14:49 UTC, BraveMole requested changes

2021-09-20 14:49 UTC, BraveMole commented on code/modules/projectiles/guns/shotguns.dm
> +/obj/item/weapon/gun/shotgun/pump/lever/unload(mob/user)
you messed up and this is duplicate

2021-09-20 14:49 UTC, BraveMole commented on code/modules/projectiles/guns/shotguns.dm
> +/obj/item/weapon/gun/shotgun/pump/lever/pump_notice(mob/user)
duplicate

2021-09-20 14:49 UTC, BraveMole commented on code/modules/projectiles/guns/shotguns.dm
> +/obj/item/weapon/gun/shotgun/pump/lever/pump_fail_notice(mob/user)
duplicate

2021-09-20 14:49 UTC, BraveMole commented on code/modules/projectiles/guns/shotguns.dm
> +/obj/item/weapon/gun/shotgun/pump/repeater
you've put this in the middle of the lever proc, put that in the end of the file for exemple

2021-09-20 14:54 UTC, joniroq commented on code/modules/projectiles/guns/shotguns.dm
> +/obj/item/weapon/gun/shotgun/pump/lever/pump_fail_notice(mob/user)
That's the gun?

2021-09-20 15:01 UTC, BraveMole commented on code/modules/projectiles/guns/shotguns.dm
> +/obj/item/weapon/gun/shotgun/pump/lever/pump_fail_notice(mob/user)
That's not the gun read closely

2021-09-20 15:10 UTC, joniroq commented on code/modules/projectiles/guns/shotguns.dm
> +/obj/item/weapon/gun/shotgun/pump/lever/pump_fail_notice(mob/user)
I think I understand what you mean now.

2021-09-20 17:43 UTC, BraveMole approved these changes

2021-09-20 19:11 UTC, Kuro020 requested changes
the obj sprite is good but the mob sprites are just the mosin,guns should have unique mob sprites even if they're a bit scuffed

2021-09-21 09:11 UTC, BraveMole requested changes
![image](https://user-images.githubusercontent.com/25491240/134144439-8b5fbdf2-c2c5-4746-b59d-a90f4e78dc15.png)

this doesn't compile

2021-09-21 09:11 UTC, BraveMole commented on code/game/objects/machinery/vending/marine_vending.dm
> +			/obj/item/weapon/gun/shotgun/pump/repeater = -1,
```suggestion
			/obj/item/weapon/gun/shotgun/pump/lever/repeater = -1,
```

2021-09-21 14:15 UTC, BraveMole approved these changes

2021-09-21 14:18 UTC, merged