Rebalances the PPSh and readds it to normal vendors.
tgstation/TerraGov-Marine-Corps pull request #8338
Opened 2021-09-18 23:52 UTC by SplinterGP

## About The Pull Request
Rebalances the PPSh and its magazines, now the PPSh has a bit better stats overall with the normal mags.

Normal mags now have the size small, like the T-90 does and had a bit of an ammo increase.
The drum mags now have the size NORMAL like T-12 mags and had a bit of ammo increase as well, it now also increases the gun aim slowdown, scatter, unwielded scatter and wield delay, trading some efficiency for more ammo.
and the PPSh now has more attachments to use.

This also removes PPSh from seasonals and puts it back on normal vendors, since its the only sidegrade there is to the T-90 overall, the T-19 being more of a sidearm than an actual SMG.

## Why It's Good For The Game
Rebalances the PPSh and gives it some unique quirk of extended mags stat + some overall usability when compared to the T-90/any other equivalent gun, it is now overall a hybrid of a SMG/Carbine, being able to use mags with more ammo but being slower overall when doing so.

## Changelog
:cl:
balance: PPSh can now take way more attachments than before.
balance: PPSh stats change to take in account the magazine stats + overall buff to make it competitive with the T-90
balance: PPSh extended mags now provide scatter increase and, wield and movement speed debuffs
balance: PPSh magazines now have proper size, the normal mags being SMALL like the T-90 magazines and extended mags being NORMAL like T-12 magazines.
/:cl:

2021-09-19 03:39 UTC, Pariah919 commented
ppsh fits more in seasonals than it does inside normal marine vendors mechanically and visually considering it has next to no attachment options, doesn't really consitute it's own niche and feels more like a half done gimmick
also you didn't replace anything on the mkh seasonal which breaks the pattern of 2 guns

2021-09-19 10:18 UTC, BraveMole commented
MJP just did a PPSh rebalance. For the putting back into vendor, ask david first

2021-09-19 22:52 UTC, SplinterGP commented
> 
> 
> ppsh fits more in seasonals than it does inside normal marine vendors mechanically and visually considering it has next to no attachment options, doesn't really consitute it's own niche and feels more like a half done gimmick
> also you didn't replace anything on the mkh seasonal which breaks the pattern of 2 guns

i just gave it attachments doe.

2021-09-21 04:20 UTC, Sirsnek15 commented
> ppsh fits more in seasonals than it does inside normal marine vendors mechanically and visually considering it has next to no attachment options, doesn't really consitute it's own niche and feels more like a half done gimmick
> also you didn't replace anything on the mkh seasonal which breaks the pattern of 2 guns

There's literally no reason for it to be in seasonals, and it shouldn't have been given up just to fit a "pattern" in the first place.

2021-09-21 11:30 UTC, BraveMole requested changes

2021-09-21 11:30 UTC, BraveMole commented on code/modules/projectiles/ammunition.dm
> +/obj/item/ammo_magazine/proc/on_inserted(obj/item/weapon/gun/master_gun)
autodoc

2021-09-21 11:30 UTC, BraveMole commented on code/modules/projectiles/ammunition.dm
> +/obj/item/ammo_magazine/proc/on_removed(obj/item/weapon/gun/master_gun)
autodoc

2021-10-02 00:26 UTC, closed without merging