Some harddel fix
tgstation/TerraGov-Marine-Corps pull request #8344
Opened 2021-09-19 13:19 UTC by BraveMole

More to come

2021-09-20 18:45 UTC, TiviPlus requested changes

2021-09-20 18:45 UTC, TiviPlus commented on code/modules/projectiles/guns/energy.dm
> +	RegisterSignal(cell, COMSIG_PARENT_QDELETING, .proc/clean_cell)
src.var

2021-09-20 20:14 UTC, BraveMole commented on code/modules/projectiles/guns/energy.dm
> +	RegisterSignal(cell, COMSIG_PARENT_QDELETING, .proc/clean_cell)
```suggestion
    if(cell)
	    RegisterSignal(cell, COMSIG_PARENT_QDELETING, .proc/clean_cell)
```

2021-09-21 19:24 UTC, TiviPlus approved these changes

2021-09-21 19:24 UTC, merged