Lazy click drag fix
tgstation/TerraGov-Marine-Corps pull request #8354
Opened 2021-09-20 15:49 UTC by MiniMeatwad

## About The Pull Request

If you click drag an object onto itself, it'll click on the object. No problems in-game after some testing.

## Why It's Good For The Game

Less missed clicks, you can click on moving targets properly, and you don't need to have esoteric knowledge to have an advantage over other players.

## Changelog
:cl:
code: Click dragging an object onto itself will click on the object instead of doing nothing.
/:cl:

2021-09-20 15:59 UTC, BraveMole approved these changes
Good pr

2021-09-20 18:35 UTC, BraveMole requested changes

2021-09-20 18:35 UTC, BraveMole commented on code/_onclick/drag_drop.dm
> +		usr.ClickOn(over_object, over_location, params)
```suggestion
		usr.ClickOn(over_object, over_location, params)
		return
```

2021-09-21 19:26 UTC, TiviPlus approved these changes

2021-09-21 19:26 UTC, merged