infinite med
tgstation/TerraGov-Marine-Corps pull request #8376
Opened 2021-09-21 19:36 UTC by SpaceLoveSs13

About The Pull Request
Makes every basic pill bottles and autoinjectors infinite.
Gives marines a special webbing with 1 slot less and medkit pouch with 2 slot less as well.
Medical jaeger and normal corpsman webbing and medkit pouch, both of which remain with same slot are now Squad Corpsman locked now.

Why It's Good For The Game
Having marines choose between their space with ammo and meds as well as what meds they should consider taking is a much better choice than making them choose the meds that might have ran out. Currently anyone who joins early can take away most meds and late joiners never get meds in spite of having a loadout saved. This fixes those balance issues by decreasing the total space available for meds while making them infinite on vendor.

@David-Stormwell and @BraveMole approved this pr idea so did @TiviPlus I believe.

If I am missing any chance/you have opinion on something being limited/more nerfed comment on the pr.

Changelog
🆑
add: Added marine corpsman webbing with 5 slots[originally 6 slots].
add: Added marine medkit pouch with 5 slots[originally 7 slots].
del: Medical jaeger exosuit storage module as well as normal webbing and medkits are now Squad Corpsman locked.
balance: Most medical pill bottles and autoinjectors are now infinite.
/🆑

2021-09-21 21:09 UTC, AnCopper commented
Lol what.

2021-09-21 22:19 UTC, Captiajoe commented
so what you are telling me is that in exhange for some of the better chems and extra peri+ and qc+ pouches i am gonna get the medkit pouches that have 7 slots (which i usually get from spare vendor) and gives me only splints and trauma kits and burn kits, is this what you are telling me? (???????)

2021-09-22 01:08 UTC, joniroq commented
The Medkit Pouch and the _Medkit Pouch_ are identically named? which is only gonna confused people unless they examine

2021-09-22 01:29 UTC, SpaceLoveSs13 commented
> so what you are telling me is that in exhange for some of the better chems and extra peri+ and qc+ pouches i am gonna get the medkit pouches that have 7 slots (which i usually get from spare vendor) and gives me only splints and trauma kits and burn kits, is this what you are telling me? (???????)

No with this PR you wont be getting 7 slot medkit pouch anymore. Only 5 slots. The 7 slot will be locked for medics only. Same for corpsman webbing.

2021-09-22 05:15 UTC, jroinc commented
I guess I'm gonna have to nerf marine meds into the ground now under the assumption that every unga is on them all the time.

2021-09-22 06:57 UTC, spookydonut commented
@jroinc that comment is not acceptable, consider this a warning.

2021-09-22 09:09 UTC, BraveMole requested changes

2021-09-22 09:09 UTC, BraveMole commented on code/game/objects/items/storage/pouch.dm
> +
useless new lines

2021-09-22 09:09 UTC, BraveMole commented on code/game/objects/machinery/vending/new_marine_vendors.dm
> +
useless new line

2021-09-22 09:09 UTC, BraveMole commented on code/game/objects/items/storage/pouch.dm
> +/obj/item/storage/pouch/medkit/corpsman
you're not giving this to anyone

2021-09-22 09:15 UTC, BraveMole requested changes

2021-09-22 09:15 UTC, BraveMole commented on code/game/objects/items/storage/pouch.dm
> +/obj/item/storage/pouch/medkit/corpsman
It's not full like it should.

2021-09-22 09:15 UTC, BraveMole commented on code/game/objects/items/storage/pouch.dm
>  /obj/item/storage/pouch/medkit/full/Initialize()
```suggestion
/obj/item/storage/pouch/medkit/corpsman/Initialize()
```

2021-09-22 09:15 UTC, BraveMole commented on code/game/objects/machinery/vending/new_marine_vendors.dm
> +
standing issue

2021-09-22 09:19 UTC, QualityVan commented
The primary issue you're describing isn't actually about a shortage of supplies, it's about resource mismanagement. As is, non-corps marines are assured available meds via pouch selection. If those options aren't good enough, buff them. Personally, I'd rec swapping the ointment, gauze, and tram injector in first aid pouches out for bkt pill packets, leaving in the tricord and splints.

2021-09-22 09:34 UTC, BraveMole requested changes

2021-09-22 09:34 UTC, BraveMole commented on code/game/objects/items/storage/pouch.dm
> +	desc = "A standard use medkit pouch that can contain all kinds of stuff.This Marine version has 5 slots."
```suggestion
	desc = "A standard use medkit pouch that can contain all kinds of stuff. This Marine version has 5 slots."
```

2021-09-22 09:34 UTC, BraveMole commented on code/game/objects/machinery/vending/new_marine_vendors.dm
> +
This is STILL a standing bloody issue, remove that line that you added

2021-09-22 09:37 UTC, BraveMole approved these changes

2021-09-22 09:50 UTC, AndroidMK2 commented
I just say I don't like this change.

2021-09-22 13:37 UTC, Losenis commented
If chems are too powerful then just buff the antichem benos

2021-09-22 16:54 UTC, jroinc commented
> 
> 
> @jroinc that comment is not acceptable, consider this a warning.

If infinimeds are added, I'll treat ungas as though they're on all meds all the time. This will need some changes.

2021-09-22 17:03 UTC, EvilMelonTheSecond commented
> 
> 
> > @jroinc that comment is not acceptable, consider this a warning.
> 
> If infinimeds are added, I'll treat ungas as though they're on all meds all the time. This will need some changes.

I already get BKT with the current limited meds cuz I rush loadouts for em. I can say for sure that 100% uptime is not sustainable on the frontlines even with the current storage and even then xeno will burst me down rapidly when I have meds. This PR has been needed for a long time in my opinion.

2021-09-22 17:08 UTC, jroinc commented
> 
> 
> > > @jroinc that comment is not acceptable, consider this a warning.
> > 
> > 
> > If infinimeds are added, I'll treat ungas as though they're on all meds all the time. This will need some changes.
> 
> I already get BKT with the current limited meds cuz I rush loadouts for em. I can say for sure that 100% uptime is not sustainable on the frontlines even with the current storage and even then xeno will burst me down rapidly when I have meds. This PR has been needed for a long time in my opinion.

With my experience, there are many ungas who routinely have 100+ units of chemicals in them while fighting. This is now sustainable long-term because *stuff a backpack with pill bottles* same as people used to do with revolvers. I'mma nerf long-term sustain some, if it becomes an issue.

Which it will.

2021-09-22 17:23 UTC, Losenis commented
> With my experience, there are many ungas who routinely have 100+ units of chemicals in them while fighting.

And wth my experience treating the octodecigorillion ungas while running medical, 100 of those units are either neurotox or killer ODs.

2021-09-22 17:32 UTC, jroinc commented
Yeah, that doesn't line up with what I see by chemical breakdown, *but* I still am gonna collect more evidence first.

2021-09-22 18:26 UTC, bowlofcereal commented
I don't know how this solves anything or makes anything remotely better. Hell, I don't even know what the problem here is in this instance, it's a chore to decipher this PR.

2021-09-22 19:18 UTC, Alexeivichi commented
Honestly, as much as I'd love this, it'll throw a certain balance off: The supply and demand for healing chems, and consequences. This is actually a pretty strong buff, and marines will always find a way to maximize their play. This will enable a lot of things that would be "bad" for the meta, IMO.

It'll be far better to increase the amount of basic pills roundstart. Adding lesser version of existing storage items for medical items would result in people relying on medical players for the better versions, or even result in them greytiding as usual moreso. I could be wrong but if I recall correctly: This would also result in "reverse powercreep". Correct me on this, I'm 90% I'm wrong though. Pretty sure people can save the better items in their Loadout Managers and spawn them that way.

On the playing field, marines would have **less of a reason to conserve pills** other than having to return to the F.O.B and resupply. This would be a heavy buff and is certain to piss xenomorph players off. 

Heck it could even result in harder fobbiting and harder sieges of F.O.B. I believe healing chemicals should be in limited supply, and if you need more: Ask Shipside medbay to produce more. (Just like #8267 made advance kits and splints limited, we had to learn to use it better and more sparingly, and spend Requisition points if we needed more).

Anywho, enough passive rambling: This PR would honestly be better if #8358 were to get implemented, but I sadly have to disapprove of this.

2021-09-27 05:07 UTC, David-Stormwell commented
Question, why can't instead of having infinite meds, make it easier to order them via req? 
@BraveMole Perhaps a order button on marine meds to request a type of chem? Just a alternative instead of having this + req factorio exists now which might be able to be linked and solve this issue better.

2021-09-27 19:13 UTC, closed without merging