Halve weed and building cost before shutters open
tgstation/TerraGov-Marine-Corps pull request #8423
Opened 2021-09-25 19:03 UTC by TiviPlus

## About The Pull Request

Note i think SHUTTERS_CLOSED is the permanent state of SSmonitor in crash so idk if this would be op there or something
## Why It's Good For The Game

Weeding and building should be allowed to be done more freely before marines arrive to give builder xenos a proper chance to build with less resting needed
## Changelog
:cl:
balance: Halve weed and building cost before shutters open
/:cl:

2021-09-26 22:55 UTC, David-Stormwell commented
Looks good, just wondering how this will affect tadpole and droppod operations?

2021-09-26 23:26 UTC, neohenry commented
Make aciding walls, frames, and etc half, too. Would help acid xenos to melt more stuff.

2021-09-27 08:48 UTC, BraveMole requested changes
You need to register COMSIG_GLOB_OPEN_SHUTTERS_EARLY as well in monitor, otherwise this will always be active before 12:33 despite shutters being manually opened

2021-09-27 18:39 UTC, BraveMole approved these changes

2021-09-27 18:39 UTC, merged