change /droid/welder_act wording and update droid healthbar again
tgstation/TerraGov-Marine-Corps pull request #8424
Opened 2021-09-25 20:23 UTC by Pill-U

Simple enough

## About The Pull Request
Changes the alerts and adds an alert for when you try to repair a full hp droid
Droid healthbar updates when the droid gets repaired

## Why It's Good For The Game
Current alerts sound a bit off. These new ones are a bit large due to [src] but acceptable as long as you play above 800x600
Also you can rename the droid to shitfart14 MK9001 and it'll work
The healthbar health being different from the actual health is annoying and confusing

## Changelog
:cl:
fix:droid healthbar updates when repaired
spellcheck:(I guess?) changed welder_act wording
/:cl:

2021-09-25 20:25 UTC, Pill-U commented
> > I did not tho? I only have my main branch currently
> 
> You need one new branch for each new pr. This branch need to be created from a fresh master

done as requested

2021-09-25 20:38 UTC, BraveMole approved these changes

2021-09-26 15:46 UTC, TiviPlus requested changes

2021-09-26 15:46 UTC, TiviPlus commented on code/modules/vehicles/unmanned/unmanned_droid.dm
>  	if(user.do_actions)
```suggestion
/obj/vehicle/unmanned/droid/welder_act(mob/living/user, obj/item/I)
	if(user.do_actions)
```
Comment doesnt add anything

2021-09-26 15:46 UTC, TiviPlus commented on code/modules/vehicles/unmanned/unmanned_droid.dm
> +		balloon_alert(user, "You try to repair [src]")
Do not use [src] here, ballon alerts must be as short as possible and targets are already known because src is where the aler comes from

2021-09-26 15:46 UTC, TiviPlus commented on code/modules/vehicles/unmanned/unmanned_droid.dm
> +		balloon_alert(user, "You finish repairing [src]")
Same here

2021-09-26 16:15 UTC, TiviPlus approved these changes

2021-09-27 08:49 UTC, merged