Minions and hivemind no longer alert hive when low health, and the alert will be smaller when they die
tgstation/TerraGov-Marine-Corps pull request #8706
Opened 2021-10-29 14:33 UTC by BraveMole

## About The Pull Request

Title

Also delete CASTE_DECAY_PROOF

## Why It's Good For The Game

Less spam

## Changelog
:cl:
qol: Minions and hivemind no longer alert hive when low health, and the alert will be smaller when they die
/:cl:

2021-10-31 22:09 UTC, TiviPlus requested changes

2021-10-31 22:09 UTC, TiviPlus commented on code/_globalvars/bitfields.dm
>  		"CASTE_HIDE_IN_STATUS" = CASTE_HIDE_IN_STATUS,
missing new flag

2021-10-31 22:21 UTC, BraveMole commented on code/_globalvars/bitfields.dm
>  		"CASTE_CAN_BE_LEADER" = CASTE_CAN_BE_LEADER,
```suggestion
		"CASTE_DO_NOT_ALERT_LOW_LIFE" = CASTE_DO_NOT_ALERT_LOW_LIFE,
		"CASTE_CAN_BE_LEADER" = CASTE_CAN_BE_LEADER,
```

2021-11-01 17:38 UTC, TiviPlus approved these changes

2021-11-01 17:38 UTC, merged

2021-11-16 05:25 UTC, Al-1ce commented
I'd suggest removing minions entirely, or at the very least heavily reducing the amount that can spawn or exist at one time. After recent additions, most rounds just feel like Whiskey Outpost with very few player-controlled aliens involved in the combat. This is all coming from somebody who was initially all for the minion PR. Just a thought.