removes RNG chance for scatter to not happen
tgstation/TerraGov-Marine-Corps pull request #8736
Opened 2021-11-02 21:02 UTC by SplinterGP

## About The Pull Request
Scatter now always happens if you have it, instead of having a RNG chance to not happen at all

## Why It's Good For The Game
Low value scatters now matter more, as it wont have a big chance for it to not scatter at all, which is a issue because big scatter values, which have more chance to happen ALSO goes more out of the straight line, i of course plan to adjust gun scatter after this.

## Changelog
:cl:
balance: gun scatter doens't have a RNG chance to not happen at all anymore
/:cl:

2021-11-03 10:52 UTC, BraveMole requested changes
Ok but you change scatter values now, rather than just making scatter more prevalant

2021-11-03 17:48 UTC, SplinterGP commented
WIP then

2021-11-03 20:39 UTC, jroinc commented
I'd love to see a mechanic that caps accuracy loss (from unwielding, attachies, ect) to a certain amount, and any additional accuracy loss is added as scatter. Low accuracy doesn't seem to mean much, but scatter scares ungas.

2021-11-05 14:38 UTC, SplinterGP commented
> 
> 
> I'd love to see a mechanic that caps accuracy loss (from unwielding, attachies, ect) to a certain amount, and any additional accuracy loss is added as scatter. Low accuracy doesn't seem to mean much, but scatter scares ungas.

intent is pretty much to remove accuracy except on extreme cases like past 15 tiles

2021-11-16 00:27 UTC, closed without merging