Aweksey the Femboy medic
tgstation/TerraGov-Marine-Corps pull request #8741
Opened 2021-11-04 22:08 UTC by ZahaSanko

## About The Pull Request
Adds Aweksey the Femboy medic to the game in a form of a plushie.

## Why It's Good For The Game
Funny and people like it

## Changelog
:cl:
add: a new plushie
/:cl:
![awd](https://user-images.githubusercontent.com/78666349/140426763-49f4a379-599e-4a39-a67c-f441ecafa22d.PNG)

2021-11-04 22:12 UTC, Captiajoe commented
"mUh ImmERsiOn", in all seriousness we tease the poor guy quite a bit already, no need to add jet fuel to this dumpster fire that is his existence. (however that is a cute plushy and good job)

2021-11-04 22:15 UTC, chrapacz2000 commented
WHERE THE HELL IS CHIPRAPS PLUSHIE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

2021-11-04 22:20 UTC, Alexeivichi commented
wife approves of this

2021-11-04 22:25 UTC, ChungusGamer666 commented
honestly quite incredible

2021-11-04 22:25 UTC, Kuro020 requested changes
lock it behind fun mode, that's where memes go

2021-11-04 22:26 UTC, neohenry commented
> 
> 
> lock it behind fun mode, that's where memes go

lock it inside a jar

2021-11-05 02:30 UTC, jroinc commented
This doesn't need to be PR'd, we already *have* him ingame.

2021-11-05 02:39 UTC, Moggram commented
![1462479884923](https://user-images.githubusercontent.com/63105585/140449210-139d8df4-7faa-4839-abd0-b5178c967fb6.gif)

2021-11-05 05:20 UTC, XSlayer300 commented on code/game/objects/items/toys/toys.dm
> +	name = "aweksey the femboy medic"
```suggestion
	name = "Aweksey the Femboy Medic"
```

2021-11-05 05:20 UTC, XSlayer300 commented on code/game/objects/items/toys/toys.dm
> +	desc = "A soft and breedable Plushie of TGMC's famous femboi."
```suggestion
	desc = "A soft and breedable plushie of TGMC's famous femboi."
```
>breedable 
🤔

2021-11-05 08:35 UTC, SpaceLoveSs13 commented
No

2021-11-05 09:45 UTC, Walarks commented
I'll put it in rare xeno research

2021-11-05 14:13 UTC, TiviPlus commented
https://www.youtube.com/watch?v=OiKxFJAt7Yg

2021-11-05 14:13 UTC, TiviPlus commented
No player references

2021-11-05 14:13 UTC, closed without merging

2021-11-05 18:16 UTC, Alexeivichi commented
YES! I'M FREE!