Auto fire spit and spitter primordial.
tgstation/TerraGov-Marine-Corps pull request #8744
Opened 2021-11-06 01:55 UTC by hyper2snyper

## About The Pull Request
Rewrites xeno spit to use the autofire component. 
Primordial Spitter gets super BRRRRRT.

Dont get used to it, I'm not becoming a xeno coder.

## Why It's Good For The Game

Carpal tunnel spit bad. Brrt spit good.

## Changelog
:cl:
add: Xeno spit now uses autofire.
add: Primordial Spitter: now with an incredible automatic firerate.
/:cl:

2021-11-06 05:06 UTC, Moggram commented
>
>
>>Dont get used to it, I'm not becoming a xeno coder.

That's what all the DMs say....

2021-11-07 11:24 UTC, TiviPlus requested changes
@BraveMole autofire code

2021-11-07 11:24 UTC, TiviPlus commented on code/_onclick/click.dm
> +			return CHECK_BITFIELD(selected_ability.use_state_flags, XACT_DO_AFTER_ATTACK) ? FALSE : TRUE
suggestions are broken but you can jst use

return !(var & flag)

2021-11-07 11:24 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
> +	caste_desc = "Master of ranged combat, this xeno knows no equal."
You need an primordial_upgrade_name and a hive_upgrade datum for this too

2021-11-08 20:51 UTC, BraveMole requested changes

2021-11-08 20:51 UTC, BraveMole commented on code/modules/mob/living/carbon/xenomorph/abilities.dm
> +	var/current_target
autodoc

2021-11-08 20:51 UTC, BraveMole commented on code/modules/mob/living/carbon/xenomorph/abilities.dm
> +	xeno?.client?.mouse_pointer_icon = 'icons/effects/supplypod_target.dmi'
another icon would be great

2021-11-08 20:51 UTC, BraveMole commented on code/modules/mob/living/carbon/xenomorph/abilities.dm
> +	AddComponent(/datum/component/automatedfire/autofire, get_cooldown(), _fire_mode = GUN_FIREMODE_AUTOMATIC,  _callback_reset_fire = CALLBACK(src, .proc/reset_fire), _callback_fire = CALLBACK(src, .pr
need a remove action as well

2021-11-10 18:54 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/abilities.dm
> +
qdel the component dont call removecomonent

2021-11-12 01:39 UTC, Lumipharon commented
I'm guessing it's this PR, but scorpion minions don't seem to be able to shoot anymore... This is the only thing tested merged right now afaik.

2021-11-15 18:14 UTC, BraveMole requested changes

2021-11-16 17:01 UTC, BraveMole requested changes
primo ability needs to be balanced.

Give primo a secondary spit with lesser damage, low spit delay for a slight increase in dps maybe?

2021-11-17 18:43 UTC, hyper2snyper commented
> primo ability needs to be balanced.
> 
> Give primo a secondary spit with lesser damage, low spit delay for a slight increase in dps maybe?
> 
> Also, are ai xeno spit working?

i didnt get any pings about ai spit not working. In any case it should be fine considering if you still wanted to spam click spit itd work just the same.

2021-11-19 10:55 UTC, BraveMole requested changes

2021-11-19 10:55 UTC, BraveMole commented on code/modules/mob/living/carbon/xenomorph/abilities.dm
> +	if(((modifiers["right"] || modifiers["middle"]) && (modifiers["shift"] || modifiers["ctrl"] || modifiers["left"])) || \
Still standing it seems

2021-11-19 10:55 UTC, BraveMole commented on code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
> +	spit_types = list(/datum/ammo/xeno/acid/auto)
how about making it so you can choose between old and new spit?

2021-11-24 18:24 UTC, merged

2022-01-28 18:31 UTC, vilereaver41 commented
please fix the bug that makes it spit like a normal spitter. spitter primo right now makes spitter useless as its spit speed is normal but it keeps the reduction in spit dmg to 10