Shoulder Gun Module
tgstation/TerraGov-Marine-Corps pull request #8768
Opened 2021-11-10 05:10 UTC by hyper2snyper

## About The Pull Request
Adds a new gun attachment/armor module that is a t3-4 drop from the researcher console.
This attachment, goes onto a gun. Once on a guns rail slot you can attach the gun to your modular armor as if it was an armor attachment. Once its attached you can reload the mounted gun by right clicking it with the ammo in hand. Right clicking with an empty hand will allow you to select whether the gun fires on right/left/middle click. The unique action keybind will activate a shoulder gun as well.

## Why It's Good For The Game
Really cool researcher content.
Using t4 research material I only acquired one after using about 8 materials. I doubt this will have much effect on balance.
It is a module so no other armor modules are compatible.

## Changelog
:cl:
add: Adds the Shoulder Gun Module, a new gun attachment/armor module that is a t3-4 drop from the researcher console.
/:cl:

2021-11-10 05:46 UTC, jroinc commented
Upping unga DPS with additional wield slots for guns is a bad precedent. They really, really don't need shouldershotguns or more DPS with no wield requirement.

I am aware that it's hard to acquire in this PR, and I'm not opposed to that, it'll just open the gates for the inevitable "add it to req" PR.

2021-11-10 06:21 UTC, Lumipharon commented
Triple wielding sounds hilarious.
And you do have two shoulders...

2021-11-10 08:28 UTC, Walarks commented
I think a lightweight shoulder turret would be interesting

2021-11-10 08:35 UTC, DarkWolfKai commented
Add a arm blade for it and boom, Were the Marine Slayer, Pretty good concept Bird.

2021-11-10 08:46 UTC, AndroidMK2 commented
Add predator shoulder turrets 😳

2021-11-10 10:23 UTC, BraveMole requested changes
Still a hard no for me.

Maybe for a flare launcher, or a pepper gun.

Revolvers, flamers, pistols, rifles, laserrifle, shotguns (SHOTGUNS???!), smgs,  snipers, no.

2021-11-10 12:18 UTC, ThelastArchiver commented
imagine shoulder mounted rocket launcher

2021-11-10 13:34 UTC, Moggram commented
> 
> 
> imagine shoulder mounted rocket launcher

Ya, no. I am going to side with BraveMole here. This is right in the ball-park of over powered.

2021-11-10 14:27 UTC, Tennessee116 commented
Possible modification: shoulder-mounted spears

2021-11-12 13:51 UTC, BraveMole requested changes
you should not be able to PB with this gun IMO

2021-11-12 13:51 UTC, BraveMole commented on code/modules/projectiles/gun_attachables.dm
> +	for(var/action_to_update in actions)
AS in

2021-11-12 13:51 UTC, BraveMole commented on code/modules/projectiles/gun_system.dm
> +	muzzle_flash(firing_angle, flash_loc)
use ?

2021-11-12 13:51 UTC, BraveMole commented on code/__DEFINES/attachments.dm
> +#define ATTACH_BYPASS_ALLOWED_LIST (1<<6)
what is this doing?

2021-11-12 16:39 UTC, Kuro020 approved these changes
sprites aokay even though this pr is gonna get mole'd kekw

2021-11-13 15:29 UTC, Tristan63 commented
stinky

2021-11-14 09:35 UTC, XSlayer300 commented on code/modules/projectiles/gun_attachables.dm
> +	name = "Experimental Shoulder Attachment Point"
```suggestion
	name = "experimental shoulder attachment point"
```

2021-11-14 09:38 UTC, XSlayer300 commented on code/modules/projectiles/gun_attachables.dm
> +	desc = "A brand new advance in combat technology. This device, once attached to a firearm, will allow the firearm to be mounted onto any piece of modular armor. Once attached to the armor and activa
```suggestion
	desc = "A brand new advance in combat technology. This device, once attached to a firearm, will allow the firearm to be mounted onto any piece of modular armor. Once attached to the armor and activated, the gun will fire when the user chooses.\nOnce attached to the armor, <b>right clicking</b> the armor with an empty hand will select what click will fire the armor (middle, right, left). <b>Right clicking</b> with ammunition will reload the gun. Using the <b>Unique Action</b> keybind will perform the weapon's unique action only when the gun is active."
```

2021-11-15 20:17 UTC, TiviPlus requested changes
and slayers grammer changes pls

2021-11-15 20:17 UTC, TiviPlus commented on code/datums/elements/attachment.dm
> +	. = ..()
```suggestion
/datum/element/attachment/Detach(datum/source, force)
	UnregisterSignal(source, COMSIG_ITEM_IS_ATTACHING)
	return ..()
```

2021-11-15 20:17 UTC, TiviPlus commented on code/modules/projectiles/gun_attachables.dm
>  /obj/item/attachable/flamer_nozzle
```suggestion
	SIGNAL_HANDLER
	master_gun.cock(master_gun.gun_user)

/obj/item/attachable/flamer_nozzle
```

2021-11-19 12:16 UTC, vilereaver41 commented
i'm willing to give anything atleast a chance despite the opness this might be i mean why not. you get some laughs from it.

2021-11-19 17:24 UTC, Tristan63 commented
could make it a req only item for like 40 points

2021-11-19 20:18 UTC, hyper2snyper commented
> could make it a req only item for like 40 points

Well. That was the original plan. However this module mainly has coolness going for it. therefore it is best suited for research content

2021-11-21 12:50 UTC, BraveMole approved these changes

2021-11-24 22:37 UTC, Lumipharon commented
It's quite dirty with sadar etc, since it solves storage issues, and effectively means you have 2 magharnessed guns. If it's locked behind research though it will probably be fine.

2021-11-27 00:29 UTC, BraveMole approved these changes

2021-11-27 00:29 UTC, merged