Toxin buildup
tgstation/TerraGov-Marine-Corps pull request #8801
Opened 2021-11-15 21:15 UTC by EvilMelonTheSecond

## About The Pull Request
An alternative to #8772. Light neurotox now gains purge with the higher effect tiers.

## Why It's Good For The Game
Instead of being almost completely ignorable light neurotoxin now builds up to being the same as neurotoxin if not purged from the metabolism. Range xeno are rewarded for focusing down marines with their chem combat and smart marines can avoid getting purged from range, the peak of balance.

## Changelog
:cl:
balance: Light neurotox now has purge if metabolized too long
/:cl:

2021-11-15 21:19 UTC, EvilMelonTheSecond commented
Please ignore the wall of commits, they are there to keep me company at night.

2021-11-16 13:49 UTC, BraveMole requested changes

2021-11-16 13:49 UTC, BraveMole commented on code/modules/reagents/reagents/toxin.dm
> +			purge_rate = (purge_rate == 1) ? 1 : 1
just directly set the purge rate as 1 here, and 0.2 at l 488.
These check are useless

2021-11-17 10:54 UTC, BraveMole requested changes

2021-11-19 09:53 UTC, BraveMole requested changes
@David-Stormwell

2021-11-19 11:02 UTC, BraveMole commented on code/modules/reagents/reagents/toxin.dm
> +			purge_rate = 1 //Even neurotoxins with no purge will start purging in the last stage
why are you even affecting normal neurotox

2021-11-19 13:57 UTC, EvilMelonTheSecond commented on code/modules/reagents/reagents/toxin.dm
> +			purge_rate = 1 //Even neurotoxins with no purge will start purging in the last stage
The reason is I'm bad at code. I dunno how to call parent function and modify it afterwards

2021-11-19 14:10 UTC, BraveMole approved these changes

2021-11-26 22:01 UTC, BraveMole approved these changes

2021-11-26 22:01 UTC, merged