mini pepperball attachment
tgstation/TerraGov-Marine-Corps pull request #8814
Opened 2021-11-19 20:19 UTC by Pill-U

## About The Pull Request##
Adds the mini pepperball gun, an attachable variant of the pepperball gun and a mag for it.
It has a slower rate of fire than the regular version and a smaller magazine size.
Todo:
Can currently shoot while unattached and while single-handed. (you don't want to use it that way anyways since it's just a worse pepperball gun)
Fire mode can currently only be changed while the gun is unattached. (Possibly remove its autofire)
Find more bugs.
Remove unnecessary code.
Sprites. (I'm not a spriter, any help and tips are appreciated)
Attachment can currently take regular mags.
Balance the thing.
Add it to guns.
Add it to vendors.

## Why It's Good For The Game
The regular pepperball gun sees next to no use in-game and is more frequently used to commit friendly fire. This aims to make it more useful by letting you use it without the downside of having no gun to do damage with, in exchange for not having a better underbarrel attachment and a smaller magazine capacity and fire rate.
BALANCE CONCERN: This gun can currently in theory remove any xenos entire plasma supply if you hit all 20 shots and can fire at the same time as the gun it's attached to.

## Changelog
:cl:
add: Add pepperball attachment
add: Add ammo for the pepperball attachment
/:cl:

2021-11-19 20:24 UTC, hyper2snyper commented on code/modules/projectiles/gun_attachables.dm
> +/obj/item/weapon/gun/rifle/pepperball/pepperball_mini
ok so let me explain this. You are defining the gun a second time. in gun_attachables. You dont want to do this. Put the attach delay underneathe the gun and remove this.

2021-11-19 20:26 UTC, hyper2snyper commented on code/modules/projectiles/guns/specialist.dm
> +	name = "mini pepperball gun"						//TODO: gun can currently still be fired unattached
GUN_ATTACHMENT_FIRE_ONLY under flags_gun_features to make sure it only fires when attached.

2021-11-19 20:26 UTC, hyper2snyper commented on code/modules/projectiles/guns/specialist.dm
> +/obj/item/weapon/gun/rifle/pepperball/pepperball_mini	//TODO: firemode currently has to be changed before attaching the gun
firemode changing is something i have to add support for. If you are capable thatd be much appreciated.

2021-11-19 20:27 UTC, hyper2snyper approved these changes
This is something ive wanted for a bit. Im super stoked.

2021-11-23 16:31 UTC, Kuro020 commented
but how does it look

2021-11-23 20:21 UTC, hyper2snyper commented on code/game/objects/machinery/vending/marine_vending.dm
> +			/obj/item/ammo_magazine/rifle/pepperball/pepperball_mini,
you want this to have a value.
```suggestion
			/obj/item/ammo_magazine/rifle/pepperball/pepperball_mini = -1,
```

2021-11-23 20:23 UTC, hyper2snyper requested changes

2021-11-23 20:23 UTC, hyper2snyper commented on code/game/objects/machinery/vending/marine_vending.dm
> +			/obj/item/weapon/gun/rifle/pepperball/pepperball_mini,
```suggestion
			/obj/item/weapon/gun/rifle/pepperball/pepperball_mini = -1,
```

2021-11-23 20:23 UTC, hyper2snyper commented on code/modules/projectiles/magazines/specialist.dm
> +	gun_type = /obj/item/weapon/gun/rifle/pepperball/
```suggestion
	gun_type = /obj/item/weapon/gun/rifle/pepperball
```

2021-11-23 20:23 UTC, hyper2snyper commented on code/modules/projectiles/magazines/specialist.dm
> +	icon_state_mini = "mag_pepperball" //TODO: Custom Sprite
icon_state_mini is just the icon_state for when its inside an ammo box. you probably dont need a custom sprite for this.

2021-11-23 20:44 UTC, Pill-U commented
I already did all of those I just didn't want to push the commit yet because I wanted to commit the sprites for the attachment at the same time. They're just modified versions of the original pepperball gun and Pariah hasn't answered if I can actually use them in 3 days. If he doesn't answer by the time your gun modularization PR gets merged I'll make some new ones or hope to get some made.

2021-12-06 22:06 UTC, Pill-U commented
gonna do the sprites tomorrow mb then this damned thing will be done after a 10 days hiatus

2021-12-07 13:27 UTC, Pill-U commented
![pepperball empty](https://user-images.githubusercontent.com/54630159/145037539-13effff8-7d6c-4362-96dc-0724e4a9ee6f.png)
![pepperball loaded](https://user-images.githubusercontent.com/54630159/145037543-bdf3e3fd-2a10-4720-b17b-bdc42a86b148.png)
empty and full sprites. Nothing amazing I know.

2021-12-07 17:18 UTC, hyper2snyper requested changes
Looks good. If you could include screenshots of it attached to a gun itd be good.

2021-12-07 17:18 UTC, hyper2snyper commented on code/modules/projectiles/ammo_datums.dm
> +	var/drain_multiplier = 0.05
autodoc

2021-12-07 17:18 UTC, hyper2snyper commented on code/modules/projectiles/guns/specialist.dm
> +	attach_delay = 3
```suggestion
	attach_delay = 3 SECONDS
```
otherwise its actually 0.3 seconds

2021-12-07 18:11 UTC, Kuro020 approved these changes

2021-12-07 18:39 UTC, Pill-U commented
![image](https://user-images.githubusercontent.com/54630159/145087187-ec3b171e-cf8b-4b8a-8505-405659c7a2a2.png)

2021-12-08 08:49 UTC, BraveMole approved these changes

2021-12-08 08:49 UTC, merged