TGS Minerva
tgstation/TerraGov-Marine-Corps pull request #8820
Opened 2021-11-21 04:23 UTC by AzonStarfall

## About The Pull Request

Adds a new low(ish) pop shipmap, the TGS Minerva. Originally designed as a survey vessel, decommissioned and refitted as a science ship, then recalled and once again retrofitted as a marine deployment cruiser, the TGS Minerva has seen a long life; The xenomorphs may be the end of it.

![Minerva](https://user-images.githubusercontent.com/66712007/142749259-d860ec5b-fe3f-4b5e-a733-1d164bde6514.png)

The research sector is given additional equipment in service of the Minerva's former science designation, coming equipped with Surplus Armor and Munition vendors for the deploying research staff.

Requisitions uses a similar shutter access system to the TGS Sulaco, in response to recent notices from High Command regarding the unnecessary demolition of shipside airlocks.

As part of the retrofit, a smaller-than-average command bunks were constructed on-site. While still functionally usable, testing officers have complained about their cramped quarters. Nanotrasen was happy to provide a substantial subsidy for the construction of their Liaison office, which nearly mirrors the entire command bunks section in size.

To cut costs, the onboard chemical stores from the research designation were shifted to the rear of the vessel for use as a self-destruct system. Upon activation, the reaction process will begin, and crew are required to lift control rods in order to manually direct the chemical flow. Upon procedural completion, the final reaction stage can be initiated from the self-destruct console. 
The necessary chemicals are stored on the starboard and port sides of the self-destruct room, which has been cited as a potential breach risk if hostiles were to gain control of the relevant chambers.
This is functionally identical to a standard self destruct.

## Why It's Good For The Game

Adding new shipmap options increases gameplay possibilities. Shipmap is balanced around Pillar of Spring resource levels, in terms of CAS and medical equipment.

## Changelog
:cl:
add: Adds the TGS Minerva, a new shipmap.
config: Adds Minerva to the shipmaps config.
/:cl:

2021-11-21 08:01 UTC, Walarks commented
I'd be interested in testing this in terms of lowering prep time since most of the resources are very close to each-other and the Alamo.

Also to me it seems to be a spacious enough map for high-pop as well.

2021-11-21 08:50 UTC, AzonStarfall commented
> Also to me it seems to be a spacious enough map for high-pop as well.

I'm a bit worried about using it for high pop, since the prep room is limited and kind of cramped. It'd be a large early-round bottleneck.

2021-11-21 15:30 UTC, Licherr commented
> > Also to me it seems to be a spacious enough map for high-pop as well.
> 
> I'm a bit worried about using it for high pop, since the prep room is limited and kind of cramped. It'd be a large early-round bottleneck.

their fault for voting it at that point

2021-11-21 20:07 UTC, AzonStarfall commented
Updated map image regarding new commits:

![Minerva](https://user-images.githubusercontent.com/66712007/142777266-246cb48c-6131-4643-9a81-35f2e7e33a7b.png)

2021-11-23 21:10 UTC, BraveMole requested changes
Supply drop consol should be unique

![image](https://user-images.githubusercontent.com/25491240/143127677-53a1a05c-934b-4b19-928e-eab55b23b9e9.png)

No maint access here, why?

Rest looks solid

2021-11-23 21:21 UTC, AzonStarfall commented
> No maint access here, why?

Intention was to have those areas function as SD stalemate blockers, so that Xenos could acid in for alternative attack points. Since you can only access them by taking either CIC or Engineering, I don't feel like it's completely unbalanced in the Xenos favor.

Correcting the Supply Console.

2021-11-24 02:11 UTC, RipGrayson commented
I don't see any problems with it, looks fine to me

2021-11-24 21:52 UTC, Luxyboo commented
Does the AI have protective glass?

2021-11-25 01:47 UTC, AzonStarfall commented
> Does the AI have protective glass?

It doesn't have the internal 1-directional safety layer, but it's kept in a shuttered room, and it's own kevlar-windowed room inside of that.

2021-11-27 18:35 UTC, AzonStarfall commented on code/__DEFINES/__game.dm
> +//for whether AI eyes see static, and whether it is mouse-opaque or not
I still don't know why this is counting as an alteration, or if I need to fix it.

2021-11-27 19:38 UTC, Lumipharon commented
Posting the feedback we discussed the other day:
The public chem is too much.

On other maps, not many people can or will powergame chem because only one person can use it at a time, and if people can't do it before deployment they won't usually bother.

Having 4 public chem stations means you can simply have four times as many people use it in the same amount of time.

2021-11-27 21:56 UTC, AzonStarfall commented
> Having 4 public chem stations means you can simply have four times as many people use it in the same amount of time.

I feel like this is a more general issue with TGMC chemistry, though. Since everyone can theoretically do it, people are still going to despite it being Medbay's "thing". Locking it off with two dispensers clearly doesn't work, as seen with Theseus and Pillar especially, which both moderately resolve the availability problem by adding another chemistry area. This just elaborates on those fixes, and reduces hassle by having the area publicly accessible rather than requiring a window deconstruction.

That said, having 3000 charge on each is definitely a problem, putting production capacity well over what any other ship is capable of. I'm going to try and reduce the charge and recharge rate of each by half (3000 to 1500), so that the total production amount is the same.

2021-11-28 12:38 UTC, BraveMole requested changes
The public chem is iffy and should not be a specific map feature.

If you want to make chem a public space, you post a separate pr for all maps, so it can be properly discussed

2021-11-28 15:20 UTC, AzonStarfall commented
Gotcha. In the mean time, to avoid break-ins, would changing it to a shutter-access system kind of like Requisitions be acceptable? Only medbay can open it to the public, so it's still their choice.

2021-11-28 15:43 UTC, AzonStarfall commented
Finalized version of the Minerva:

![Minerva](https://user-images.githubusercontent.com/66712007/143775190-07fbe291-0cbf-46c3-8fdb-6da76f6cbd1e.png)

2021-11-29 09:38 UTC, ThelastArchiver commented
here some feedback from playing as Ai the map is missing cameras at several locations resulting in blindspots for the Ai like in atmos the cls office , the western landing pad and the kitchen no cams in maints is ok but maybe ad a few hologram projectors for the ai for some extra ai fun.

2021-11-30 17:07 UTC, BraveMole approved these changes
Another round of test and then merge

2021-12-02 14:13 UTC, merged