Scatter spit Range & Scatter balance.
tgstation/TerraGov-Marine-Corps pull request #8836
Opened 2021-11-24 23:39 UTC by vilereaver41

## About The Pull Request

Changes scatter spit range  and scatter rate

## Why It's Good For The Game

Scatter spit isn't very good right now, it does little damage even if you manage to PB people. right now its a mosquito bite. and when you get in range you are often times punished by losing half your hp to marine fire just to use the ability. this at least makes it more usable. 

this should help make Spitter more useful as its spit damage even at ancient does little damage that is including the 15%+ per maturity.  

Abilitys like this are overlooked and their damage is considered "ok" but people dont take into account acid armor, not to mention the projectiles speed is quite slow compared to marine bullets.

## Changelog
:cl:
balance: range is no 10 and scatter is now 2
/:cl:

2021-11-25 00:41 UTC, KrabSpider commented
Hi. It is literally the equivalent of 2 spits. That's 18 damage after medium armor calcs. There is hardly any point in trying to put scatterspit off if
1) Channeling it means you are _going_ to be shot away as you prep it.
2) It is much more costly than simply spitting at a marine

2021-11-26 09:31 UTC, maikilangiolo commented
Scatter spit already has greater range than view screen and bypasses wired cades.

2021-11-28 10:00 UTC, David-Stormwell commented
Damage is an extreme jump, nothing more then x2 should be done.

2021-11-28 12:22 UTC, BraveMole requested changes

2021-11-28 13:42 UTC, vilereaver41 commented
> Damage is an extreme jump, nothing more then x2 should be done.

done made it 20

2021-11-28 13:42 UTC, vilereaver41 commented on code/modules/projectiles/ammo_datums.dm
> +	max_range = 10
done

2021-11-28 13:47 UTC, BraveMole approved these changes

2021-11-28 13:50 UTC, merged