Buffs Engineering Storage Module
tgstation/TerraGov-Marine-Corps pull request #8844
Opened 2021-11-26 11:08 UTC by Three333Digit

## About The Pull Request
Title.
Increases the storage slots of the module to 5, same as medical storage module.
The storage module can now hold almost everything only an engineer would use (does not include plasma cutter and miner modules).
(Honestly? The list might be an overkill)

## Why It's Good For The Game
Not even Engineers uses this module, hopefully this will give the module some use.

## Changelog
:cl:
balance: Increases the storage slot of the engineering storage module to 5
The storage module can now hold filled sandbags, razorwire, handheld charger, c4, razorburn grenades, detpack, signaler, circuitboards, and the light replacer
/:cl:

2021-11-26 15:21 UTC, T1MM5H commented
Strongly approve, old engineering storage module was basically a construction pouch, in fact it would not surprise me if the code was supposed to be placeholder and was just forgotten

2021-11-26 17:42 UTC, EvilMelonTheSecond commented
The expanded list is cool, the extra slot is storagecreep since it makes construction pouch obsolete. But since engineer storage slots suck ass anyways its probably not gonna make much difference

2021-11-27 17:07 UTC, BraveMole requested changes

2021-11-27 17:07 UTC, BraveMole commented on code/modules/clothing/modular_armor/attachments/storage.dm
> +		/obj/item/stack/sandbags,
eh, that kinda defeat the mecanics of sandbags

2021-11-27 23:36 UTC, BraveMole approved these changes

2021-11-27 23:36 UTC, merged