Nerfs Metal Foam health
tgstation/TerraGov-Marine-Corps pull request #8854
Opened 2021-11-27 10:53 UTC by lKiseki

## About The Pull Request
Per title. Metal Foam health has been decreased from 200 to 120, which takes about roughly 4-6 slashes depending on the caste.

## Why It's Good For The Game
Makes Metal Foam less of a pain to deal with.

## Changelog
:cl: Lewdcifer
balance: Metal Foam health 200 > 120.
/:cl:

2021-11-27 10:54 UTC, David-Stormwell commented
Make it 100 if you want, something that shouldn't had ever existed.
Brings me back to my survivor days when I'd use it to block off xenos.

2021-11-27 10:55 UTC, Derrick2Electricboogaloo commented
Negative ghost rider. This sure is a Salt PR if I have seen one. Something that only really gets used by a minority of players.

2021-11-27 10:57 UTC, Derrick2Electricboogaloo commented
Nerfing the health by a whopping 60%. Why is it when engineers utilize any of their utility effectively it gets nerfed. Why are we punishing engineer mains for playing their role. Why is it acceptable for xenos to delay to try and eck out a win but marines it is frowned upon?

2021-11-27 10:57 UTC, Derrick2Electricboogaloo commented
Xenos have counters to this. EMPLOY THE USE OF CRUSHERS. Pit could and used to counter my metal foam delay tactic why can xenos not do that now?

2021-11-27 11:05 UTC, Derrick2Electricboogaloo commented
> Make it 100 if you want, something that shouldn't had ever existed. Brings me back to my survivor days when I'd use it to block off xenos.

You may as well just delete it then since who in their right mind would use metal foam then? Literally useless at 100 HP. I am sorry but nerfing it because you have to click instead of getting a crusher to smash it is just sad.

2021-11-27 11:14 UTC, ilikesaying commented
ah yes, force the xenos to bring a crusher so they can counter one tardass instead of focusing on everyone else, just like razorwire spam needing spitters/boilers/praetorians to be countered

2021-11-27 11:17 UTC, revelation-8468 commented
me when the maintainers nerf an entire mechanic because one person is good at using it

2021-11-27 11:23 UTC, Derrick2Electricboogaloo commented
> 

Accurate. We should have nerfed everything pit was good at. The only nerf I thought was 100% fair was the razorburn cheese.

2021-11-27 11:26 UTC, lKiseki commented
> Lewd is good at RAV NERF THAT SHIT.

sir yes sir we have a super rage nerf out there

2021-11-27 14:19 UTC, Losenis commented
>ah yes, force the xenos to bring a crusher so they can counter one tardass instead of focusing on everyone else, just like razorwire spam needing spitters/boilers/praetorians to be countered

You could argue the same about marines needing to bring a PC to counter one single HL mazing the whole planet or have to do exactly what this pr is about.

2021-11-27 17:11 UTC, BraveMole requested changes
not a fan, this make foamed metal wall useless.

I'd rather nerfing the size of the foam spread

2021-11-28 01:33 UTC, Captiajoe commented
This may be one of the contenders for the most nerfs for an item that sees the least gameplay

2021-11-28 01:56 UTC, vilereaver41 commented
> This may be one of the contenders for the most nerfs for an item that sees the least gameplay

i have seen it spammed before lol, its insane

2021-11-28 03:24 UTC, Lumipharon commented
I assume this is in reaction to that god awful ice game the other day. 

If Brave would rather nerf the range, then by all means, but it really does need something. It's really just horrible having to smash though endless foam, and saying 'force someone to evolve into this one specific caste to counter this one dude' is not good gameplay. Atleast with razor, there are multiple castes that can acid them down. And foam can be spammed along with razor, so that's just asking to die for crushers.

2021-11-28 10:04 UTC, David-Stormwell commented
> not a fan, this make foamed metal wall useless.
> 
> I'd rather nerfing the size of the foam spread

That makes it more useless, the idea of the foam is to cover multiple tiles in order to create or block off entire flanks or entryways to more effectively push Xenos where the engi wants them.

Nerfing the range would be too much, and I'll be ok with at least a .5% decrease in health/150 if marines cry hard enough.
Reminder other smaller case types exist that Marines can spam, such as sandbags or even fastdeploy plasteel cades.

2021-11-28 13:09 UTC, merged