Removes starting Plasma Cutters from shipside
tgstation/TerraGov-Marine-Corps pull request #8855
Opened 2021-11-27 11:13 UTC by lKiseki

## About The Pull Request
Per title, and a different approach towards nerfing the Plasma Cutter. Leaves it as-is, but makes it so that you have to purchase it from reqs.

## Why It's Good For The Game
The Plasma Cutter has always been a tool that has been too good at its job. It's more easily justifiable if it's locked behind reqs rather than being an item you can just get from reqs at the start of a round.

## Changelog
:cl: Lewdcifer
del: Plasma Cutters no longer spawn roundstart.
/:cl:

2021-11-27 11:38 UTC, vilereaver41 commented
true true

2021-11-27 14:16 UTC, Losenis commented
I feel targeted

2021-11-27 17:13 UTC, BraveMole requested changes
PC is too good at what it does, ok, but marines don't have a good alternatives.

Before doing that,i think you should give marines another way of cleaning mazes, something less powerfull than current PC. Maybe make C4 kill walls at a range?

2021-11-27 18:08 UTC, Losenis commented
Also this may indirectly be a synth/tadpole nerf, since synths' only other option for wallbreaking is meleeing it to death and the roundstart PC allows the front of the tadpole to be PC'd off without having to pray some engi spawns and goes PC to ask for it borrowed. Realistically, nobody's going to buy a PC roundstart either.

2021-11-28 00:39 UTC, Walarks commented
PC is very good at clearing mazes and xenos are very good at making them quickly. I'm not sure about replacing PC with a more limited tool, but at the same time I think engi can get it from their prep vendor.

2021-11-28 01:51 UTC, vilereaver41 commented
> PC is too good at what it does, ok, but marines don't have a good alternatives.
> 
> Before doing that,i think you should give marines another way of cleaning mazes, something less powerfull than current PC. Maybe make C4 kill walls at a range?

flamers and melee?

2021-11-28 10:07 UTC, David-Stormwell commented
> PC is too good at what it does, ok, but marines don't have a good alternatives.
> 
> Before doing that,i think you should give marines another way of cleaning mazes, something less powerfull than current PC. Maybe make C4 kill walls at a range?

C4 has already been buffed.
If you want a large explosion then Demo charges exist.
In fact, might as well buff them accordingly as well, decrease the timer, increase the damage to be able to blow up walls, and also decrease range to comp.
Then in the end make them a little more accessible to marines as well.

2021-11-28 10:09 UTC, lKiseki commented
> C4 has already been buffed. If you want a large explosion then Demo charges exist. In fact, might as well buff them accordingly as well, decrease the timer, increase the damage to be able to blow up walls, and also decrease range to comp. Then in the end make them a little more accessible to marines as well.

Can do this on another PR. Sir, yes sir, oorah.

2021-11-28 13:05 UTC, lKiseki commented
mole said he preferred nerfing the PC, david wants the PC nerfed either way and the detpack buffed, i don't mind either way

2021-11-28 13:05 UTC, closed without merging