Removes delay for using reagent dispensers
tgstation/TerraGov-Marine-Corps pull request #8857
Opened 2021-11-27 23:46 UTC by Walarks

## About The Pull Request
Removes the delay for using chem machines by unskilled marines. The current iteration doesn't do much more than delaying the start of the round. I can add more personal chem machines for personal use by the doctors if need be.

## Why It's Good For The Game
The chem machines are usually mostly used roundstart for people to make chems that they use during the rest of the round. While the delay is put to discourage this, what it mostly accomplishes is to delay the round-start since marines can just take a couple more minutes to wait until they can go groundside. I'm removing the delay in favor of not wasting more time to prep since the wait can already be very long.

## Changelog
:cl:
balance: removes usage delay for chem machines
/:cl:

2021-11-28 03:21 UTC, Lumipharon commented
Encouraging everyone to prechem is bad. As we've seen in Minerva, extra machines and public access already encourages far more people to do it because it's easier and more accessible, and the number of marines that can do it before deployment is x4. Removing the delay is the same thing, just to a lesser degree.

Most people won't bother if they can't do it before deployment, which is honestly for the better.
If people want to go out of the way to waste their own time doing so after the fighting has actually started, then that's reducing unga effectiveness on the ground, so balances itself out.

2021-11-28 03:57 UTC, S1tr3p commented
> Encouraging everyone to prechem is bad. As we've seen in Minerva, extra machines and public access already encourages far more people to do it because it's easier and more accessible, and the number of marines that can do it before deployment is x4. Removing the delay is the same thing, just to a lesser degree.
> 
> Most people won't bother if they can't do it before deployment, which is honestly for the better. If people want to go out of the way to waste their own time doing so after the fighting has actually started, then that's reducing unga effectiveness on the ground, so balances itself out.

Making peoples preps time longer won't discourage them from making synap oxy or any other decent premed drug. They still make it with the delay.

2021-11-28 04:03 UTC, Al-1ce commented
>I can add more personal chem machines for personal use by the doctors if need be.

It would be a godsend.

2021-11-28 05:25 UTC, Derrick2Electricboogaloo commented
Absolutely love this! Good work! Merge please.

2021-11-28 05:26 UTC, Derrick2Electricboogaloo commented
> Encouraging everyone to prechem is bad. As we've seen in Minerva, extra machines and public access already encourages far more people to do it because it's easier and more accessible, and the number of marines that can do it before deployment is x4. Removing the delay is the same thing, just to a lesser degree.
> 
> Most people won't bother if they can't do it before deployment, which is honestly for the better. If people want to go out of the way to waste their own time doing so after the fighting has actually started, then that's reducing unga effectiveness on the ground, so balances itself out.

What Sitrep said, nothing will change, people will still get their meds they will just get them faster.

2021-11-28 12:55 UTC, BraveMole requested changes
The current situation is stupid, yes. Either we should go full locked chem, or full open chem, not just "you can have access to chem but it's pain in the ass".

But if we want to go on the open chem route, multiple things:
- There should be separate dispensers for marines in prep, they should not have to go to medbay for this. (So lock this dispenser)
- Maybe a energy-per-marine system? This would prevent marines having a whole pharmacy on them, which is just a powergamer wet dream but is making xeno life just so much harder. And then we could balance that energy number so marines get some good chems, but not all

2021-11-28 14:40 UTC, Walarks commented
> The current situation is stupid, yes. Either we should go full locked chem, or full open chem, not just "you can have access to chem but it's pain in the ass".
> 
> But if we want to go on the open chem route, multiple things:
> 
> * There should be separate dispensers for marines in prep, they should not have to go to medbay for this. (So lock this dispenser)
> * Maybe a energy-per-marine system? This would prevent marines having a whole pharmacy on them, which is just a powergamer wet dream but is making xeno life just so much harder. And then we could balance that energy number so marines get some good chems, but not all

I could do the first part. For the second part, I'll need to look more into it since current med UIs can be interacted with by multiple people at the same time, though FOB drone is locked when someone is using it I think so I can check that.

2021-11-28 17:38 UTC, S1tr3p commented
> The current situation is stupid, yes. Either we should go full locked chem, or full open chem, not just "you can have access to chem but it's pain in the ass".
> 
> But if we want to go on the open chem route, multiple things:
> 
> * There should be separate dispensers for marines in prep, they should not have to go to medbay for this. (So lock this dispenser)
> * Maybe a energy-per-marine system? This would prevent marines having a whole pharmacy on them, which is just a powergamer wet dream but is making xeno life just so much harder. And then we could balance that energy number so marines get some good chems, but not all

So, what about corpsmen? I can see the direction we wanna go here and its not a bad one but corpsmen often need to make a decent amount of pills with their loadout.

2021-11-28 18:39 UTC, BraveMole commented
> So, what about corpsmen? I can see the direction we wanna go here and its not a bad one but corpsmen often need to make a decent amount of pills with their loadout.

could have more energy

2021-11-28 20:08 UTC, Lumipharon commented
Keep in mind the medical vendor allows for infinite amounts of most basic chems, including oxycodone etc. So you can actually do a lot with just the vendor and the chem master (and the nanomed).

I think open chem is a bad idea and a really big marine buff. But if you do decide to go that way, would it not be easier to just give a light version of the medic prep vendor thing to marines in the normal prep vendors (i.e. normal marines get 20 points or whatever vs the 45~ odd medics get to spend on med stuff, and with some stuff not available)?

2021-11-28 20:22 UTC, Losenis commented
An additional problem with making chem difficult or locked to marines is that if you're latejoining you're pretty much completely fucked since pill bottles are limited, and go out insanely fast since they're taken for loadouts as well. Sometimes they can run out in one single minute.

I've argued that if marines are too strong with chems, rather than nerf it save for the few lucky ones that joined roundstart and completely gimping the experience of everyone else, we should just buff the antichem capability of xenos. A quadrillion units of healing reagents wont do a whole lot when the marine has enough neurotox to purge, threaten death, or force hypervene wasting all those chems anyway.

To summarize, making chem more difficult or outright locking it just means "You latejoined? Go fuck yourself." and is not even a bandaid to the root problem of most xenos not having anti-chem options other than certain castes.

2021-11-29 02:01 UTC, bowlofcereal commented
> An additional problem with making chem difficult or locked to marines is that if you're latejoining you're pretty much completely fucked since pill bottles are limited, and go out insanely fast since they're taken for loadouts as well. Sometimes they can run out in one single minute.
> 
> I've argued that if marines are too strong with chems, rather than nerf it save for the few lucky ones that joined roundstart and completely gimping the experience of everyone else, we should just buff the antichem capability of xenos. A quadrillion units of healing reagents wont do a whole lot when the marine has enough neurotox to purge, threaten death, or force hypervene wasting all those chems anyway.
> 
> To summarize, making chem more difficult or outright locking it just means "You latejoined? Go fuck yourself." and is not even a bandaid to the root problem of most xenos not having anti-chem options other than certain castes.
> 
> EDIT: Now that I am thinking about it thoroughly, the appeal of chem might be over how shit trauma kits and god forbid bandages are. Not that they're bad per se, but rather they're so absolutely inefficient in space that it's laughable if not useless at times. A fire or explosion will consume an entire stack of an item (11 bodyparts vs stacks of 10) if you don't want to risk an infection, and that's after a good while of manually applying it on you with generous use of numpad + spamclick. Meanwhile with pills that'd only take 1/16 of a slot to use with the simplicity of just two clicks to heal the entire body, so no checking for which bodypart, targetting, etc. Before any ideas of nerfing chem I'd like to see bandages and trauma kits applying to the entire body, even if their effect is nerfed in return, since otherwise there's no real effective alternative to chems other than greytiding/powergaming what the game actually lets you use involving chems.
> 
> I can tell you that as a synth, getting accidentally naded and having to heal 11 bodyparts not only with wire but also with blowtorch is such a pain in the ass that sometimes I've decided to medevac myself and cryo rather than go through it. The same extends to kits and bandages/ointment that self-examination won't tell you which bodypart is bleeding to skip on the rest. At times I've eaten bwoinks for breaking into chem roundstart, because the root problem is that the alternative to chemicals just aren't that viable other than in complement to said chems or healing dead people.

I have never seen a more true statement. The reason **nobody**, not even the medics themselves, use anykind of kit, and instead prefer to pill you, is because they are absolutely useless. The only thing they are good at is stopping bleeding on a very damaged limb so you dont have to waste isotonic injectors on them. Pills are 10000x more faster then actually closing the wound, and I feel that is a serious problem that nobody else seems to think about in these kinds of things.

Adding a delay to reagent dispensers is just annoying as fuck, and should be done away with as this PR plans to do. Make trauma, burn, and everything else kit-wise more useful or nothing will change and we will be stuck in the current endless loop of "meds too op, nerf but then realize how bad of a change it is and then revert".

2021-11-29 02:36 UTC, Losenis commented
They're not only faster but also more efficient. Naded and all limbs have 5 damage? Either waste a full bandage stack or just 1 single pill of either bica or kelo, **or even less than a pill** if a corpsman is running tricord hypo like I used to run back in the day.

2021-11-29 03:10 UTC, Lumipharon commented
They're mainly for corpses (as a medic), stopping bleeding as you said, or speeding healing up a tiny bit.

They would make considerably more sense if marines had plentiful access to kits, but NOT chems. I.e. they can triage themselves, stop the bleeding and avoid infections, until an actual medic can treat them.

But yeah, if everyone has access to chems, they're objectively worst most of the time.

This is kinda a bigger discussion about chem/med balance though, ultimately this PR doesn't really change a lot either way.

2021-11-30 04:56 UTC, usnpeepoo commented
i think we should kill powergaming and preppers by removing everything related to so and only giving marines base items to work with and nothing else outside of req.

2021-11-30 15:05 UTC, Losenis commented
You're thinking of crash

2021-12-03 17:38 UTC, Franky2025 commented
Literal cacner, fix the big picture issue of marines and chems first, supporting a development of this issue by making it easier to chem for marines is not a good idea. BraveMole suggested a great idea for marines having some sort of their own limited chem.

2021-12-03 23:18 UTC, Losenis commented
> fix the big picture issue of marines and chems first

That same thing can be argued for getting rid of this bandaid pr that doesn't even do what it's supposed to do. Most of the delay can be bypassed by simply chaining inputs. This pr being in place if nothing else would just be justification to not touch marine chems because "well the chem machines have a big delay already".

2021-12-04 10:03 UTC, Franky2025 commented
> That same thing can be argued for getting rid of this bandaid pr that doesn't even do what it's supposed to do. Most of the delay can be bypassed by simply chaining inputs. This pr being in place if nothing else would just be justification to not touch marine chems because "well the chem machines have a big delay already".

This is literally a "lets ignore the skill system because it annoying :(". Chem access for marines is a fucking overkill always, it should not be default, all the marinemed items are fine and do their job, this removal just encourages it.

2021-12-04 14:24 UTC, Losenis commented
> Chem access for marines is a fucking overkill always

No. Marines are mostly designed around the idea that everyone should be able to do everything because at its core TGMC isn't a AAA 2022 game with 1000s of players, some roles might end up not filled. This was the reasoning behind the pr that made marines able to install miner modules. The skill system is there to make things faster for select roles, not annoy the everloving shit of everyone who doesn't happen to have the correct icon for actual life or death stuff.

 That, and vendors are pitifully limited to the point latejoining and hoping they have chems left is wishful thinking at best. Alternative to chems like bandages, ointment, and kits are nigh useless at the time being so there's no real option other than chems, which is the actual crux of the issue that causes chem prs to be constant back and forth of buffs and nerfs to this day.

Until alternatives are made just as viable it'll be nerfing chems, marines get absolutely mercilessly stomped because they don't have anything else, chems get buffed, xenos get stomped, chems get nerfed, ad infinitum. If adding a delay to chem machines that can be easily bypassed by chaining inputs is considered a solution instead of removed for the stupid bandaid it is to hide the problem, then the problem you want solved will absolutely never be solved.

2021-12-05 23:33 UTC, Lumipharon commented
Letting marines install miners lets them do an engineers job if they're not there/fucking about.
Marines accessing chem is so they can try avoid any reliance on medics at all cost and heal real fast during combat 24/7.

This is not equivalent. Marines already have access to basic chems from prep, and can stack bicard/kele/tricord/tram just fine. They're supposed to rely on medics to actually do their job long term. It's why pill bottles changed to smaller packets.

2021-12-06 13:10 UTC, Losenis commented
>Marines accessing chem is so they can try avoid any reliance on medics at all cost and heal real fast during combat 24/7

Not only is this beyond hyperbole given often you have like only 3 corpsmen for 30 marines, that last part had its own pr (https://github.com/tgstation/TerraGov-Marine-Corps/pull/8561) seeking to lower the rate at which marines actually healed during combat but it got closed for some reason. And this pr has ZERO effect on actual combat healing anyway, so bringing it up is ???.

2021-12-06 17:40 UTC, Walarks commented
Someone can complete the other requests and finish the PR if they want to. I'm too tired to do it.

2021-12-06 17:40 UTC, closed without merging