Nerfs revolver fire rate
tgstation/TerraGov-Marine-Corps pull request #8862
Opened 2021-11-29 21:08 UTC by lKiseki

## About The Pull Request
![image](https://user-images.githubusercontent.com/59634950/143943057-3a2f1ef6-7569-4f84-a70f-f17aa1f282d9.png)
Apparently, an increased fire delay was supposed to be part of the recently merged TP-44 changes. This PR aims to actually reduce the fire rate a little bit. Tested it in-game, felt fine.

## Why It's Good For The Game
Gives the TP-44 its intended balancing, makes them a little bit less overpowered than they are currently.

## Changelog
:cl: Lewdcifer
balance: TP-44 fire delay 0.15 > 0.18.
/:cl:

2021-11-29 21:14 UTC, BraveMole requested changes

2021-11-29 21:14 UTC, BraveMole commented on code/modules/projectiles/guns/revolvers.dm
> +	fire_delay = 0.18 SECONDS
doesn't exist, it's needs to be a multiple of 0.05

2021-11-29 22:30 UTC, Moggram commented
![46813165](https://user-images.githubusercontent.com/63105585/143952824-59e399a7-2bd7-45b1-842d-c30cef9f00de.png)


Is there a gun that has more RP then the TP-44?

2021-11-30 00:02 UTC, Walarks commented
I wonder how many of the pistol gamers click to fire them vs using a macro and going autofire.

2021-11-30 09:39 UTC, SilencedMP5A5 commented
this + the previous nerf = lame as hell

2021-11-30 17:08 UTC, merged