Add 2 tesla guns in armament vendor under spec tab
tgstation/TerraGov-Marine-Corps pull request #8883
Opened 2021-12-02 22:17 UTC by neohenry

## About The Pull Request

Add 2 tesla guns in armament vendor for marines to get instead of buying them from req.

## Why It's Good For The Game

The tesla gun is picking up spider webs and dust in the req order because (1) no one wants to buy them, (2) barely anyone knows it existence, meaning (3) barely, if at all no one, anyone knows how to use it in the current meta.

Power creep, but at least it doesn't cause damage to xenomorphs; it just ruin their plan.

Two to test out the water of how often marines grab it and go.

Tesla gun is currently under maintained, so expect jank from it. This PR is not to fix telsa gun but to make it more accessable.

## Changelog
Nova_epee :cl:
expansion: add two tesla guns, a weapon that drain xenomorph's plasma, into armament  vendor under speciality tab; you can buy more at req
/:cl:

2021-12-02 22:18 UTC, neohenry commented
yay, first pr

2021-12-03 19:31 UTC, BraveMole commented
"Tesla gun is currently under maintained, so expect jank from it. This PR is not to fix telsa gun but to make it more accessable." 

Honestly you need to work on the testla gun first, it's jank

2021-12-03 21:02 UTC, hyper2snyper commented
Define 'Jank'

2021-12-04 03:26 UTC, novaepee commented
> Define 'Jank'

Check Discord tag.

2021-12-04 17:37 UTC, TiviPlus commented
@Kuro020

2021-12-06 06:48 UTC, novaepee commented
https://www.youtube.com/watch?v=z5kfoLcyyp4

Check video to see in its beauty.

2021-12-06 12:34 UTC, TiviPlus commented
Checks failing

2021-12-06 20:12 UTC, hyper2snyper requested changes

2021-12-06 20:12 UTC, hyper2snyper commented on code/modules/projectiles/guns/rifles.dm
> +	gun_firemode_list = list(GUN_FIREMODE_SEMIAUTO GUN_FIREMODE_AUTOMATIC, GUN_FIREMODE_AUTOBURST)
```suggestion
	gun_firemode_list = list(GUN_FIREMODE_SEMIAUTO, GUN_FIREMODE_AUTOMATIC, GUN_FIREMODE_AUTOBURST)
```

2021-12-07 20:09 UTC, novaepee commented on code/modules/projectiles/guns/rifles.dm
> +	gun_firemode_list = list(GUN_FIREMODE_SEMIAUTO GUN_FIREMODE_AUTOMATIC, GUN_FIREMODE_AUTOBURST)
Will give smartrifle burst fire later.

2021-12-07 20:26 UTC, merged