Improvement lava queue
tgstation/TerraGov-Marine-Corps pull request #8893
Opened 2021-12-03 11:04 UTC by BraveMole

## About The Pull Request

Window flashs and there is a loud sound played when it's your turn to be a larva. 
More anti-afk security

## Why It's Good For The Game

QOL mostly

## Changelog
:cl:
qol: Window flashs and there is a loud sound played when it's your turn to be a larva (larva queue)
/:cl:

2021-12-03 12:19 UTC, Walarks commented
only og remember when it was lava queue

2021-12-06 13:11 UTC, TiviPlus requested changes

2021-12-06 13:11 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/hive_datum.dm
> +		join.remove_selected_frame()
Can't you use actions by type here

2021-12-08 01:37 UTC, bowlofcereal commented
real ones remember when it was just plain luck on whether or not you could become a xeno, + waiting 30 minutes during headbite gameplay to even play

2021-12-11 13:43 UTC, merged