Makes powerloader faster during prep
tgstation/TerraGov-Marine-Corps pull request #8904
Opened 2021-12-04 19:09 UTC by Walarks

## About The Pull Request
Makes loader very fast during prep to make prep take less time. When the shutters drop, its speed returns to normal. This might seem immersion-breaking on one hand, but I think that this could save around 10m of prep and getting to the actual round faster makes up for it.

I'm not sure how harmed xenos would be by marines finishing prep faster, but if it is noticeable I think this can be offset by increasing pre-shutters evolution/aging gains.

## Why It's Good For The Game
It makes the round start and get to the core of the gameplay faster. Currently prep takes a large amount of time and a lot of it is spent performing the same routine every round.

## Changelog
:cl:
qol: makes loader much faster during prep
/:cl:

2021-12-04 19:20 UTC, BraveMole requested changes
You said it yourself, completely breaks immersion for a a benefit that i suspect is very small, if not inexistant.

If you want to buff the powerloader, (let's say a speed of 3, 2) throughout the whole game, why not, but this is not credible in the slightest

2021-12-04 19:25 UTC, Walarks commented
> You said it yourself, completely breaks immersion for a a benefit that i suspect is very small, if not inexistant.
> 
> If you want to buff the powerloader, (let's say a speed of 3, 2) throughout the whole game, why not, but this is not credible in the slightest

I think that most people are here for the roleplay and things that come after prep for prep immersion to matter that much. Considering the amount of stuff that is moved around, I think that this may decrease the time it takes to prep by a noticeable amount.

2021-12-05 00:36 UTC, Losenis commented
I don't think people care for immersion pre-shutters. Either they're focused in their prep to care about ripleys, or they're alt tabbed having already prepped. A faster ripley is less of an immersion breaker than a moshpit at req or chem break-in #748.

2021-12-05 14:59 UTC, Misha600 commented
> > You said it yourself, completely breaks immersion for a a benefit that i suspect is very small, if not inexistant.
> > If you want to buff the powerloader, (let's say a speed of 3, 2) throughout the whole game, why not, but this is not credible in the slightest
> 
> I think that most people are here for the roleplay and things that come after prep for prep immersion to matter that much. Considering the amount of stuff that is moved around, I think that this may decrease the time it takes to prep by a noticeable amount.

no i'm here to shoot bug and FF marines

2021-12-06 13:09 UTC, TiviPlus requested changes
I think that this could save around 10m of prep and getting to the actual round faster makes up for it.

Ok but people aren't waiting fir power loader they're usually waiting for fob drone so this doesn't fix anything

2021-12-06 15:27 UTC, closed without merging

2021-12-06 15:29 UTC, Losenis commented
Fucking

Bruh