Fix hivemind cooldown exploit
tgstation/TerraGov-Marine-Corps pull request #8924
Opened 2021-12-08 13:15 UTC by BraveMole

## About The Pull Request

Title. Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/8681

## Why It's Good For The Game

## Changelog
:cl:
fix: Fix hivemind cooldown exploit
/:cl:

2021-12-08 19:00 UTC, Mrrpip commented
Oh well. It was my big brain counter to razorwire spam while it lasted!

*salute

2021-12-08 19:01 UTC, BraveMole commented
> Oh well. It was my big brain counter to razorwire spam while it lasted!
> 
> *salute

probably gonna make a cooldown buff after

2021-12-20 01:34 UTC, psykzz commented on code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
> +	var/list/datum/action/chached_actions = other_actions?.Copy()
```suggestion
	var/list/datum/action/cached_actions = other_actions?.Copy()
```

don't forget the other references as well.

2021-12-20 12:31 UTC, psykzz approved these changes

2021-12-20 12:41 UTC, psykzz requested changes
Agreed to move the relevant abilities to should_show instead of removing / adding them each time.

2021-12-20 12:51 UTC, psykzz commented on code/datums/actions/xeno_action.dm
> +	if(cooldown_id && !keep_cooldown)
Do you still plan to keep this?

2021-12-20 12:52 UTC, BraveMole commented on code/datums/actions/xeno_action.dm
> +	if(cooldown_id && !keep_cooldown)
ah no oups

2021-12-20 20:36 UTC, psykzz approved these changes

2021-12-29 19:36 UTC, merged