First Funky(Tm) attachment
tgstation/TerraGov-Marine-Corps pull request #8931
Opened 2021-12-09 01:04 UTC by hyper2snyper

## About The Pull Request
HEY YOU! WOULDNT IT BE COOL IF YOU HAD AN ITEM THAT COULD MAKE ANY GUN YOU WANT BE LEVER ACTION??!!
WELL THEN THIS IS FOR YOU!

Introducing the new "lever-action conversion kit".
Found as research loot, this attachment will halve the fire delay of any gun in exchange for making it lever action.
You want a GL with twice the firing speed? The cost will be carpal tunnel, but it will be worth it.

I have also divided the attachment file into a folder so each attachment type gets their own file.

## Why It's Good For The Game
The new gun system will allow for a lot of wacky things. This will add a minor wacky attachment to research content.
I dont see this having any real balance consequences.

## Changelog
:cl:
add: New gun attachment: Lever-action conversion kit. Halves any guns fire rate in exchange for it being made lever action. This is found as research loot.
/:cl:

2021-12-09 02:20 UTC, SilencedMP5A5 commented
time for a lever action revolver :)

2021-12-09 04:48 UTC, Three333Digit commented
basically https://www.youtube.com/watch?v=6oMUiZXYQC4

2021-12-09 05:10 UTC, MereWalker commented
Lever action minigun... LETS GOOOOOOO

2021-12-09 05:18 UTC, novaepee commented
I like the idea of that the more marines robust xenomorphs the more toys marines get.

2021-12-09 08:00 UTC, Pariah919 commented
gonna make a macro

2021-12-09 09:40 UTC, ThelastArchiver commented
cant wait for autosniper to shred through boilers via now ( even more) insane damage

2021-12-09 15:27 UTC, BraveMole requested changes
Ok so: 

- The PR is unreviewable, 1800 lines change for one attachment. I could maybe navigate if you made some commits to help, but right there, i can't see what you did.
- I asked you to make one attachment to prove that your concept is balancable, you added an attachment that halves the fire rate to all the guns; if this is not balance hell, i don't know what is.
- Even as a concept, smashing a key ==> better firerate is not something i'd like to promote.

2021-12-09 19:49 UTC, Mechanelize commented
unbased maintainer vs chad 1800 line coder

2021-12-09 20:22 UTC, Pill-U commented
did you based mf refactor attachment code for ONE meme attachment or what the fuck am I looking at

2021-12-10 16:29 UTC, XSlayer300 commented on code/modules/projectiles/attachments/underbarrel.dm
> +/obj/item/attachable/lever_action
The lever action shenanigans start here by the way.

2021-12-10 16:30 UTC, XSlayer300 commented on code/modules/projectiles/attachments/underbarrel.dm
> +		to_chat(attacher, span_warning("You cannot attach [src] to a gun that is already manual."))
```suggestion
		to_chat(attacher, span_warning("You cannot attach [src] to a gun that is already manually operated."))
```

2021-12-17 20:21 UTC, Tristan63 commented
![image0](https://user-images.githubusercontent.com/66579448/146603292-765baf53-5ebb-4d3c-9942-270235d720cd.gif)

2021-12-22 10:01 UTC, BraveMole commented
Closing as stale

2021-12-22 10:01 UTC, closed without merging