Icarus Shipyard. (New map)
tgstation/TerraGov-Marine-Corps pull request #8932
Opened 2021-12-09 04:16 UTC by vilereaver41

## About The Pull Request

Add's a brand new map fresh from StrongDm

## Why It's Good For The Game

new map = more content

## Changelog
:cl:
add: new map
/:cl:

Currently has no lore. make some if you want?

I expect a lot of playtesting lol, if you find a bug post it here with a screenshot please, don't DM me.
took me just under half a month to make. hours spent, most likely uhh 16-23 total?

![image](https://user-images.githubusercontent.com/64131993/145333305-691ddb7e-baf7-4ffb-b20d-8dbdb9540972.png)

2021-12-09 09:38 UTC, ThelastArchiver commented
is this a crash or lowpop map ?

2021-12-09 09:51 UTC, vilereaver41 commented
> is this a crash or lowpop map ?

Crash should work on it. as for ship positions when they land. not tested yet. lowpop i really dont know how many it would fit. maybe 30+

2021-12-09 15:51 UTC, BraveMole requested changes
@RipGrayson Hello your opinion please.

On my part:
- The map has a unique look and it's very cool
- You placed a bit too much ai nodes, but honestly it's far better than what you did on ice colony and should work fine.
Like here you could have place 1/3 of ai nodes and it would have worked fine
![image](https://user-images.githubusercontent.com/25491240/145428539-5ac60319-8a2e-4568-ba80-f185e575b336.png)
This probably links
![image](https://user-images.githubusercontent.com/25491240/145428766-a269f4bb-c2ce-429a-8fb6-0b62e78fe60e.png)
You need way less diagonals; if two diagonals links together the ai will ultra derp
![image](https://user-images.githubusercontent.com/25491240/145428936-365fa8c1-902b-46c1-936d-d8194a799681.png)
Overall, don't make diagonals unless really needed. Never makes two diagonal linking together
- I think this will be hard to play on as a xeno, but map balancing is hard and we will see
- The medbay is too close to the fob, this makes is too easy for marines to capture and keep it
![image](https://user-images.githubusercontent.com/25491240/145428282-263b3161-0e85-438d-b354-7b7ea29c16eb.png)
- Lore wise i think corpsepawner should be primary army/pfc, i don't get why there would be any miner
- 40 players mins seems a lot, probably 30 min/ 60 max?
- I removed parallax groundside because it is very expensive; it would be great to add back on this specific map because you see space. Ping me when the review requests are done and validated so i can help you code this
- You have .pyc files added, remove them

2021-12-09 17:58 UTC, RipGrayson commented
Alright first thoughts and some errors that need corrected before we TM this map.
I like the theme, the map is somewhat undetailed but that's not a huge problem. I'm somewhat concerned with all the open space and the small size that Xenos will either roll or get rolled with very little in-between every round. 
As Mole, said we'll have to see how it plays out.

Now to some bigger problems,
-You have no flight computers in either LZ, the xenos cannot hijack without them.
-Engineering has no floodlight switch, making the floodlights in the cave sections useless.
-Engineering is disconnected from the rest of the grid by one cable.
![1](https://user-images.githubusercontent.com/49290523/145446508-7f223531-2e59-41b1-914d-d2ba71fb2308.png)

-Due to the recent NanoMed resprite, you cannot put wallmeds inside walls anymore, they have to be treated like APCs. You already did that in some places, but some areas still have the wallmeds inside closed turf.
![2](https://user-images.githubusercontent.com/49290523/145447205-167f0472-6ef2-46e0-80b9-3cdf09900186.png)


-There's no release button for these shutters
![4](https://user-images.githubusercontent.com/49290523/145448390-29e06cfa-9978-4dd5-afe2-ad01932376dd.png)
Because of that the marines leaving LZ2 will either have to shuffle through this corridor (which the xenos will make hell if they have any sort of sense)
![5](https://user-images.githubusercontent.com/49290523/145448468-5d2fd761-d55a-4b71-bb3c-cdbb237163f6.png)
Go single file through broken windows at the shutters.
![7](https://user-images.githubusercontent.com/49290523/145449079-26af2cd7-32a2-42a6-b1e5-24c611586790.png)
Or work through caves and enter medical through a number of broken grilles, which isn't ideal for a number of reasons including some 1 tile straights they would have to defend/advance through.
![6](https://user-images.githubusercontent.com/49290523/145449530-6e4ec216-1bc4-4dcc-b9ca-4b874c3de3ac.png)
Overall I like the map concept, keep up the good work.

2021-12-10 13:54 UTC, vilereaver41 commented
Did changes that Grayson found. Didn't add to many entrances near cas padlocks as they are destructible. Did reduce qi nodes by 70% of what it was before. Added tcoms to

2021-12-10 15:25 UTC, RipGrayson commented
> Did changes that Grayson found. Didn't add to many entrances near cas padlocks as they are destructible. Did reduce qi nodes by 70% of what it was before. Added tcoms to

-There's still no flight computers
-There are no xeno spawns
-Engineering is still disconnected from grid
-About half the NanoMeds are still improperly placed
-There's still no floodlight switch in engineering

2021-12-10 22:34 UTC, vilereaver41 commented
> > Did changes that Grayson found. Didn't add to many entrances near cas padlocks as they are destructible. Did reduce qi nodes by 70% of what it was before. Added tcoms to
> 
> -There's still no flight computers -There are no xeno spawns -Engineering is still disconnected from grid -About half the NanoMeds are still improperly placed -There's still no floodlight switch in engineering

yeah i fixed it but did testing and got versions confused my bad

2021-12-28 01:42 UTC, vilereaver41 commented
Reopened because im done venting and shouldn't punish players for the actions of 1 person

2022-01-06 04:49 UTC, Redstonize commented
This is my first review. Bear with me, as I give my opinion. I like the idea of adding a new map. But...

1. "The medbay is too close to the fob,"
-> Shuffle and rotate (I don't know if that's possible) the medbay by minus 90 degrees and push it towards the north of the map, merging it with the northern most cave cluster but not removing it (so as to keep the upper part of it).
2. I do think this should be a map for a minimum of 30 players and a maximum of 50 players as the cave sections are relatively short and the map overall not very big, unless you could venture on the conveyor belts in the northwest corner and next to the north cave, or adding more caves.
3. LZ1 is surrounded by caves. That's fine, but at least make the entrance into not-a-cave segment. In my opinion that would be better so xenos don't have to push through a chokepoint right as they come near fob. Close quarters combat is good for marines generally but we generally don't have it right outside the fob, that's per most maps, and would give them an unfair advantage I think if they could easily slip the noobish xenos right outside where they land.

Thank you for reading my first review.

2022-01-07 17:35 UTC, BraveMole commented
Stale

2022-01-08 08:58 UTC, BraveMole requested changes
military not millitary.
And the code name should contains icarus

2022-01-08 15:17 UTC, ChocolateBickie commented
I rolled researcher during today's test round and there were not excavation sites.

![Screenshot (87)](https://user-images.githubusercontent.com/73966686/148649544-69f03738-3387-4aef-a7b3-9924326c1191.png)

2022-01-09 15:21 UTC, RipGrayson commented
Aside from other things mentioned, this map is now 280x280, the limit is supposed to be 255x255 due to performance issues.

2022-01-10 00:27 UTC, vilereaver41 commented
> Aside from other things mentioned, this map is now 280x280, the limit is supposed to be 255x255 due to performance issues.

Il fix

2022-01-10 00:27 UTC, vilereaver41 commented
> I rolled researcher during today's test round and there were no excavation sites.
> 
> ![Screenshot (87)](https://user-images.githubusercontent.com/73966686/148649544-69f03738-3387-4aef-a7b3-9924326c1191.png)

Will fix

2022-01-10 08:56 UTC, BraveMole requested changes
There is still a huge typo that's glaring. For the record, it's writen correctly in config so the minimum amount of players wasn't correct.

And i asked for icarus to be in the .dm name

2022-01-12 01:24 UTC, FosterGrime-Heymynameslouie commented
Auto begin firemission on cas no worky
can you add a cas node or something

2022-01-12 01:40 UTC, AzonStarfall commented
- Misaligned signs. Signs should be placed one tile above where you want them visible, in order to correctly display.

- Monorail area. Not sure if it's supposed to look like a crash site, but the whole area looks disorganized and doesn't properly convey a "damaged" feel, moreso just glitched.

- Strange tile placement choices. Not sure if it's intentional, but many tiles look out of place, such as random catwalks in maintenance or random 4-tile colored floors mixed inside mono tile floor areas.

- Triumph corners are still labelled as Alamo.

- Hull placed over window above the Condor pad area.

- VERY low miner count. Should increase volume.

-South/Southeast is VERY open, consider adding pillars or other natural barricades.

2022-01-12 10:52 UTC, BraveMole requested changes
Need less hallways, less caves, and the rest was already said

2022-01-15 01:02 UTC, vilereaver41 commented
Iv done the majority of changes and fixed things up, hallways are more populated. It doesent make sense to have every hallway full and cluttered as it feels non professional from a lore standpoint. Crash disks more balanced, nuke to. Hulls though I think is a server side issue

2022-01-17 22:04 UTC, InterroLouis commented
I just don't like it. Poison poo gas everywhere that does practically nothing to xenos, and the rest of the map is just too big for the populations we get. The FOBs are easy to defend and the caves are also...easy to defend. Which makes it just turn into horrible slogs of rounds where neither side can do much of anything.

2022-01-18 01:27 UTC, private-tristan commented
on crash it seems that the fog is doubled specifically around the southwest silo spot.
https://cdn.discordapp.com/attachments/877777075027714148/932807890002141194/unknown.png
https://cdn.discordapp.com/attachments/877777075027714148/932808325811286056/unknown.png

2022-01-23 00:21 UTC, RipGrayson commented
Alright I completed a couple rounds in this map and here are my thoughts.

This map is LV-624 caves, except it's the **entire** map instead of half and it's also **huge**. 
There's a mazing concept where you drag marines out over a big enough maze and let attrition reduce marine numbers because they can't hope to actually control the entire maze at once and xenos can always recover and ambush from some uncontested corner, **this is that map form.** 

There's enough open space and enough distance that xenos are realistically in no danger because marines cannot hope to coherently control all the emptiness and xenos can play hit and run and then fade when things get too dangerous.
I also haven't seen marines advance more than 1/3rd of the way across the map because their push can't realistically guard all angles and xenos can use any number of uncontested hallways to whittle the marine force down.

In my opinion, there are two options here, either reduce the size of the map or increase the required player number.

2022-01-23 13:05 UTC, Texicos commented
Seems there is an exploitable area south of FOB one, next to the dropship that can be entered are windowed areas that marines cannot enter where a hivemind or wraith can warp to place weeds or shadows.

2022-01-23 13:19 UTC, SpaceLoveSs13 commented
another exploit found in same round. Please get rid of these secret exploitable areas. 
![image](https://user-images.githubusercontent.com/68121607/150680408-95a16ce4-bb8c-4863-b53b-3f8f2624664b.png)
You should take a look at this and texico's one and prolly reconsider this tm until these are resolved @BraveMole

2022-01-23 13:21 UTC, SpaceLoveSs13 commented
> Seems there is an exploitable area south of FOB one, next to the dropship that can be entered are windowed areas that marines cannot enter where a hivemind or wraith can warp to place weeds or shadows.
![image](https://user-images.githubusercontent.com/68121607/150680518-139498bf-8111-4caa-8568-f797ebfc80fe.png)

2022-01-23 14:10 UTC, SpaceLoveSs13 commented
@vilereaver41 appreciate the quick fixes

2022-01-27 18:50 UTC, DeltaFire15 commented
You can get in the walled-off tank's room via a single non-indestructible wall.
![image](https://user-images.githubusercontent.com/46569814/151424160-b1ce09fc-9585-41b8-ad5f-336a1632cc17.png)

2022-01-30 22:38 UTC, Mechanelize commented
BASICALLY some indestructible versions need to be resprited too
![image](https://user-images.githubusercontent.com/52432736/151720846-ab626c44-731e-48a9-8c90-60bf86bb47e5.png)

2022-01-31 07:36 UTC, vilereaver41 commented
> BASICALLY some indestructible versions need to be resprited too ![image](https://user-images.githubusercontent.com/52432736/151720846-ab626c44-731e-48a9-8c90-60bf86bb47e5.png)

gotta ask greyson for that.

2022-01-31 07:37 UTC, vilereaver41 commented
all changes via feedback and here are done except stuff i have no control of like indestructible wall resprites.

2022-02-02 16:17 UTC, BraveMole requested changes
![image](https://user-images.githubusercontent.com/25491240/152192506-0a8de497-7b02-4d53-803b-0abbf01d9d48.png)

This whole area is empty, uninteresting and bad for gameplay. The map is too big, just cut that part

![image](https://user-images.githubusercontent.com/25491240/152192127-b7592d44-7879-4a7d-83ec-e6473cf5c512.png)

These bridges (all, not just this one) are just creating ultra stale situation where no side can push

![image](https://user-images.githubusercontent.com/25491240/152192989-c3f46116-cd6d-4a0f-85c5-9a2311835a78.png)

Do no do big walls of doors

2022-02-05 23:48 UTC, BraveMole commented
You have to look all ai nodes, you broke a lot of them in your changes

2022-02-06 10:40 UTC, vilereaver41 commented
> You have to look all ai nodes, you broke a lot of them in your changes

fixed

2022-02-06 10:54 UTC, BraveMole requested changes
![image](https://user-images.githubusercontent.com/25491240/152677517-98a9d52d-2f1b-45a0-a2d9-87a6419f2b93.png)

Still some silly big array of walls. Make resin look more organic

2022-02-12 01:30 UTC, Lumipharon commented
LZ2 is hard to defend as it has a huge perimeter that is all just 1 wall deep. Also, the alamo should be moved a couple of tiles north, as it's super close to the south wall so you can't build adequate defences there.

If you made a few more rwall rooms along the east side as little storage rooms or something (kind of like how that memorial space does now) it could have some more natural defence that is easier to cade.

2022-02-12 15:03 UTC, vilereaver41 commented
> LZ2 is hard to defend as it has a huge perimeter that is all just 1 wall deep. Also, the alamo should be moved a couple of tiles north, as it's super close to the south wall so you can't build adequate defences there.
> 
> If you made a few more rwall rooms along the east side as little storage rooms or something (kind of like how that memorial space does now) it could have some more natural defence that is easier to cade.

Il see what I can do

2022-02-12 18:18 UTC, TiviPlus commented
There seems to be a number of indestructible walls (also the shutters near LZ1), marine routing issues mean that they tend to camp near to LZ, a lot of corridors, nodrop ripley claw next to LZ, some people have stated its worth exploring having one LZ here instead of two, pipes going into space, pipes being apparently unchanged since the map was shrinked, I saw an AI get stuck on the jets as well

2022-02-17 04:21 UTC, Lumipharon commented
LZ2 has a perspective issue on that raised platform it has. Both the top and bottom edge of the platform show the southern tiles being below the northern tiles.

2022-02-19 04:18 UTC, vilereaver41 commented
> LZ2 has a perspective issue on that raised platform it has. Both the top and bottom edge of the platform show the southern tiles being below the northern tiles.

Will fix soon

2022-03-03 02:42 UTC, Luxyboo commented
make it to where the map isnt 90% caves so i can droppod and not die instantly

2022-03-25 03:27 UTC, RipGrayson commented
I'm not trying to be picky here, but Spooky has said that I need to do more maps reviews so here it is.
Multiple disconnected APCs need wired to the powernet.
![apc1](https://user-images.githubusercontent.com/49290523/160047560-87bce4b4-bca0-466a-a2dc-9738714f6234.png)
![apc2](https://user-images.githubusercontent.com/49290523/160047570-0dbaff40-4336-4c40-b40b-b0b4323e30f9.png)
![apc3](https://user-images.githubusercontent.com/49290523/160047617-0c1c7bbb-cab9-49d5-84db-e37f529add3f.png)
![apc11](https://user-images.githubusercontent.com/49290523/160047680-39f1d752-764e-42ab-9b81-10aa750fb9c2.png)
![apc12](https://user-images.githubusercontent.com/49290523/160047726-8d23b055-8d58-4d16-8421-434dc631412c.png)
![apc5](https://user-images.githubusercontent.com/49290523/160047866-112ad549-70ea-435d-b48d-da8f2f31f17f.png)

Wire missing here, means engineering isn't connected to grid.
![apc10](https://user-images.githubusercontent.com/49290523/160047951-ce9da031-066c-483c-ba31-b92062005775.png)

In the future, I wouldn't put cables underneath walls, it makes the power net hard to follow. I could swear this used to be against map policy but I don't think it currently is.

2022-03-27 10:28 UTC, vilereaver41 commented
> I'm not trying to be picky here, but Spooky has said that I need to do more maps reviews so here it is. Multiple disconnected APCs need wired to the powernet. ![apc1](https://user-images.githubusercontent.com/49290523/160047560-87bce4b4-bca0-466a-a2dc-9738714f6234.png) ![apc2](https://user-images.githubusercontent.com/49290523/160047570-0dbaff40-4336-4c40-b40b-b0b4323e30f9.png) ![apc3](https://user-images.githubusercontent.com/49290523/160047617-0c1c7bbb-cab9-49d5-84db-e37f529add3f.png) ![apc11](https://user-images.githubusercontent.com/49290523/160047680-39f1d752-764e-42ab-9b81-10aa750fb9c2.png) ![apc12](https://user-images.githubusercontent.com/49290523/160047726-8d23b055-8d58-4d16-8421-434dc631412c.png) ![apc5](https://user-images.githubusercontent.com/49290523/160047866-112ad549-70ea-435d-b48d-da8f2f31f17f.png)
> 
> Wire missing here, means engineering isn't connected to grid. ![apc10](https://user-images.githubusercontent.com/49290523/160047951-ce9da031-066c-483c-ba31-b92062005775.png)
> 
> In the future, I wouldn't put cables underneath walls, it makes the power net hard to follow. I could swear this used to be against map policy but I don't think it currently is.

fixed

2022-04-08 16:16 UTC, merged