.44 Rimfire (Do-over...)
tgstation/TerraGov-Marine-Corps pull request #8946
Opened 2021-12-10 22:33 UTC by KrabSpider

## About The Pull Request

## Why It's Good For The Game

## Changelog
:cl:
add: Added new mechanics or gameplay changes
add: Added more mechanics or gameplay changes
expansion: Expands content of an existing feature
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2021-12-11 22:02 UTC, AndroidMK2 commented
Sprite looking very nice, would really like to see these changes implemented

2021-12-12 03:56 UTC, KrabSpider commented
MJP I hate you so much. Anyway thank you

2021-12-12 14:19 UTC, XSlayer300 commented on code/modules/projectiles/magazines/misc.dm
> +	desc = "A packet containing 50 rounds of .45-70 Government.."
```suggestion
	desc = "A packet containing 50 rounds of .45-70 Government."
```

2021-12-13 13:32 UTC, BraveMole requested changes
On the cl:
![image](https://user-images.githubusercontent.com/25491240/145821561-f739ef7d-04cb-4749-880b-af00c2fc3e3a.png)
First should be balance, the two last are unneeded.

State was were the previous dp, sunder, etc of the gun

2021-12-13 18:56 UTC, Kuro020 approved these changes

2021-12-13 18:58 UTC, BraveMole approved these changes

2021-12-13 18:58 UTC, merged