I can't BELIEVE it's not shoe MRE's!
tgstation/TerraGov-Marine-Corps pull request #8951
Opened 2021-12-11 11:30 UTC by mrhugo13

## About The Pull Request
Added `/obj/item/storage/box/MRE` to the list of allowed items that can be put inside of the marine combat boots.

This PR has been fully tested on a local build with zero (0) runtimes or errors (the shoe sprite not updating, #8950, is unrelated)
![2021-12-11_12-08-50](https://user-images.githubusercontent.com/17747087/145674641-25e67fb2-a616-4cb2-94aa-ab3d5c4c3d79.gif)

Fixes the grievances outlined in #8856
## Why It's Good For The Game
As outlined in #8856 the grievances caused by lack of spaghetti MRE filled shoes is clear, without the marine ability to put MRE's in their boots to be ready for consumption in battle it will severely affect their morale and ability to fight in such a way that it can affect the balance of the in-game round and therefor cause an unfair advantage to xenos.

Also this'd work nicely for those whom wish to have a mid-fight snack.

## Changelog
:cl: Vondiech
balance: The TGMC has heard the grievances of the poor defenseless marines, unable to fit their MRE foods into their combat boots, feeling the weight of their mortality as they need to put their spaghetti in their backpack for a mid-fight snack as opposed to putting it in their boots were it may be kept warm and tight for mid-fight consumption. And as a show of empathy, sympathy, and a bit of corporate marketing, the TGMC engineering design corps have redesigned the new combat marine boots to feature the ability to put your MRE foods into them!
/:cl:

2021-12-11 11:31 UTC, ilikesaying commented
fucking cursed

2021-12-11 12:29 UTC, chesse20 commented
a much needed buff for machete users who can now have a new source of blood when they lose it due to trying to sword fight the gorger

2021-12-11 12:49 UTC, SilencedMP5A5 commented
FINALLY, SOME GOOD CONTENT

2021-12-11 17:55 UTC, novaepee commented
This reminds me of how my OCP pant's cargo pocket can fit MREs.

MRE IN THE POCKET, BABYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY

2021-12-13 11:02 UTC, BraveMole requested changes
fix the meme cl please

2021-12-13 13:26 UTC, mrhugo13 commented
@BraveMole Done as requested.

2021-12-13 13:27 UTC, merged