Kills Repeater Stagger
tgstation/TerraGov-Marine-Corps pull request #9000
Opened 2021-12-17 01:42 UTC by KrabSpider

## About The Pull Request
I'm embarrassed to make this PR.
Removes stagger from the repeater.

## Why It's Good For The Game
4 tiles was a little too much and since it already does pretty high damage on a pretty short rate of fire, it probably won't need it. 

## Changelog
:cl:
balance: removes stagger from .45-70 Government bullets, aka repeater bullets.
/:cl:

2021-12-17 17:53 UTC, KrabSpider commented
I'm giving this another go. Let's go.

2021-12-17 17:58 UTC, ZahaSanko commented
if really needed, limit it to 2 tiles like you said instead of deleting it permamently.

2021-12-19 10:33 UTC, BraveMole requested changes
![image](https://user-images.githubusercontent.com/25491240/146671872-727daed2-776b-406d-92ba-14fa7222e06b.png)

Twice the same code, make up your mind

2021-12-22 10:01 UTC, BraveMole approved these changes

2021-12-22 10:01 UTC, merged