Medical Nanites buff
tgstation/TerraGov-Marine-Corps pull request #9024
Opened 2021-12-20 13:49 UTC by Franky2025

## About The Pull Request
Reduces the time it takes to adopt to 100 cycles.
Slightly reduces the amount of damage nanites will do in the adopting period.
Adds pain reduction to nanites based on the amount of them in the blood in the adopted state. Less nanites = more being used = smart nanites reduce pain.

## Why It's Good For The Game
Nanites are not being used much, the only way to get them anyways is to bug an engineer, minor heal based on your constant blood consumption and toxin damage after almost 5 minutes of close to dying crit even with meds.

## Changelog
:cl: Kait
balance: Nanites buffed: Paid reduction added, time to adopt shortened. 
/:cl:

2021-12-20 13:53 UTC, psykzz requested changes

2021-12-20 13:53 UTC, psykzz commented on code/modules/reagents/reagents/medical.dm
> +				L.reagent_pain_modifier += PAIN_REDUCTION_VERY_HEAVY
Check your indentation these are currently not valid.

2021-12-20 14:03 UTC, Franky2025 commented
i have an idea now to make it based on the damage you have at the moment, gonna try that better cause i dont see where did i make a mistake

2021-12-20 14:17 UTC, Franky2025 commented
it actually worked, so stupid to me, after lua, that it actually does matter.

2021-12-22 09:58 UTC, BraveMole commented
Allright, after thinking about this, such a "useless" item does not belong with shoulder gun and armblade. So we'll go with the other solution instead

2021-12-22 10:03 UTC, BraveMole commented
Sorry wrong pr lel

2021-12-22 10:49 UTC, BraveMole approved these changes
Ok we can try that.

2021-12-23 04:48 UTC, KAAITTT commented
rethinking this and discussing this, concerns of this being too good will be reviewed after some playtesting, i dont want to contribute a part of the powercreep issue.

2021-12-23 19:00 UTC, ThelastArchiver commented
doc turn off my pain inhibitors ! ( sounds like a good pr)

2021-12-27 14:34 UTC, Licherr commented
I personally don't like any changes to the medical nanites as I perceive that the reason it was made alongside some other "useless" chems for experimental funsies for the researcher pre-gacha, and not to be a viable medical chem. When the nanites became public everyone now thinks it should be less destructive and more viable. I just don't like having new chems that already has the same functions as the present chems we already have.

2021-12-28 11:19 UTC, KAAITTT commented
> I personally don't like any changes to the medical nanites as I perceive that the reason it was made alongside some other "useless" chems was for experimental funsies for the researcher pre-gacha, and not to be a viable medical chem. When the nanites became public everyone now thinks it should be less destructive and more viable. I just don't like having new chems that already has the same functions as the present chems we already have.

Stop mentioning the idiotic merge of the "nanites for all", its irrelevant to the state of the chem independently, and this pull request was made before it.
This is a basic misunderstanding of the researcher.
Researcher things exist not only for the researchers to just DO THEM and thats it, they have effects for a reason. There is a reason researchers get REWARDS out of xenos, like implants and so on, that can be used. This whole game relays on team work, and your job being: doing something not for the sake of it but because it does something to the whole state of your workplace.

So the researchers gimmicks of "nanites" and them not needing to be useful makes no sense. This is an item that requires quite a bit of chem resources and work to get, for a single portion, for a single person to use. These changes were made looking at the whole state of it, work needing to be done and the balance of it in mind. This is an improvement to of it, because i think nanites need to have better performance, a better pay off for their process of creation.

2021-12-30 09:08 UTC, BraveMole commented
since no one likes nanites being there

2021-12-30 09:08 UTC, closed without merging