Ports fancy conveyor sprites from TG and CEV Eris
tgstation/TerraGov-Marine-Corps pull request #9033
Opened 2021-12-22 22:41 UTC by RipGrayson

## About The Pull Request

Replaces our old outdated conveyors with new fresh conveyor sprites, taken from CEV Eris.  
![BNMLqj8Kad](https://user-images.githubusercontent.com/49290523/147162513-cd837f66-6d0c-4e64-8fce-f5e4773b773d.gif)

I also borrowed a small bit of code (and this .gif) from https://github.com/tgstation/tgstation/pull/63240 to deal with belt directions.
![144683936-51776957-c9d6-46a0-ab98-493fb1b3fc52](https://user-images.githubusercontent.com/49290523/147162898-e4704294-8646-498a-a023-15a63c67e369.gif)

## Why It's Good For The Game

It just looks better, the old ones don't match our art style anymore and are fairly low quality. You can also tell at a glance where a conveyor is heading just by looking at it.

## Changelog
:cl:
imageadd: Ported fancy conveyor sprites from Eris.
/:cl:

2021-12-23 00:53 UTC, Derrick2Electricboogaloo commented
Yes please!

2021-12-23 05:19 UTC, GoldenAlpharex commented
Hey look it's my PR :)

2021-12-23 05:20 UTC, GoldenAlpharex commented
Also you should probably mention the code improvement/refactor part of it in the PR, but I'd suggest you wait for the PR to be merged on /tg/ first.

2021-12-23 14:13 UTC, RipGrayson commented
> Also you should probably mention the code improvement/refactor part of it in the PR

I didn't really take that part of your PR. TGMC is an entirely different codebase forked from ancient Baystation and CM and is at least one previous conveyor refactor behind. To use your refactor I would (at least) have to make conveyors a subsystem here.
As such the only code part I borrowed from your PR was the flipped variable and some of the logic around updating the icon state.
If you want I can credit you personally in the PR description though.

2021-12-31 04:23 UTC, RipGrayson commented
This PR isn't stale, nobody has reviewed it. Curse of opening a pull at the end of the year.

2022-01-03 01:15 UTC, Kuro020 approved these changes

2022-01-05 00:45 UTC, BraveMole requested changes

2022-01-05 00:45 UTC, BraveMole commented on code/modules/recycling/conveyor2.dm
> +	var/verted = FALSE		// Inverts the direction the conveyor belt moves.
No you had to keep the other one lel

2022-01-05 00:45 UTC, BraveMole commented on code/modules/recycling/conveyor2.dm
> +		icon_state = "["conveyor"][verted ? -operating : operating ][flipped ? "-flipped" : ""]"
```suggestion
		icon_state = "conveyor[verted ? -operating : operating ][flipped ? "-flipped" : ""]"
```
should work?

2022-01-07 16:46 UTC, BraveMole requested changes

2022-01-07 16:46 UTC, BraveMole commented on code/modules/recycling/conveyor2.dm
> +	var/verted = FALSE		// Inverts the direction the conveyor belt moves when false.
```suggestion
	/// Inverts the direction the conveyor belt moves when false.
	var/verted = FALSE		
```
```suggestion
	var/verted = FALSE		// Inverts the direction the conveyor belt moves when false.
```

2022-01-07 17:15 UTC, merged