New dress and service uniform!
tgstation/TerraGov-Marine-Corps pull request #9101
Opened 2021-12-29 04:13 UTC by novaepee

## About The Pull Request

Resprite dress uniform to what #267 intended to be (HOLY SMOKES, A PR THAT OLD), but #3682 deleted them and gave us cringe dress uniform that make marines look bad.

Also, adding in service uniform! Sprites by Fitz 'Pancake' Sholl!

ALSO, making it easier to vent out dress and service uniform.

## Why It's Good For The Game

Dress and service uniform make a marine prideful of serving Uncle Sam, or for TGMC lore SPACE SAM. If it looks ugly, why even wear it?

## Changelog
:cl:
fix: Dress uniform to the intended sprites. I choose not to delete the old dress uniform.
imageadd: Add service uniform; say thanks to Fitz 'Pancake' Sholl!
add: Make it easy to get service and dress uniform without having to click so much buttons.
/:cl:

2021-12-29 04:30 UTC, novaepee commented
Sprites before and after

![image](https://user-images.githubusercontent.com/6610922/147627510-224f89c8-dff2-4fbf-83ce-c53eaef8d426.png)

2021-12-29 04:31 UTC, novaepee commented
Here is the service uniform! Wear those boots.

![image](https://user-images.githubusercontent.com/6610922/147627552-440f32ac-ee9b-4f52-8b67-61c6cec1466d.png)

2021-12-29 11:45 UTC, AndroidMK2 commented
I like the new service uniform but the white pants on the dress uniform don't fit as much as the black pants from before.

2021-12-29 15:39 UTC, Verlurk commented
New dress uniform looks like a shapeless blob because none of it is broken up. Former looks better, in my opinion.

Service looks nice though. Do these actually have a purpose for a role, or is it just excess vendor?

2021-12-29 17:52 UTC, Tennessee116 commented
If you're going to use the ICCG dress uniform, at least port the boots.

2021-12-29 19:23 UTC, novaepee commented
> I like the new service uniform but the white pants on the dress uniform don't fit as much as the black pants from before.

They are baggy, which is an interesting choice from the spriters.

2021-12-29 19:24 UTC, novaepee commented
> Do these actually have a purpose for a role, or is it just excess vendor?

Excess vendor.

2022-01-04 17:58 UTC, BraveMole requested changes

2022-01-04 17:58 UTC, BraveMole commented on code/game/objects/machinery/vending/marine_vending.dm
> +			/obj/effect/essentials_set/white_dress = -1,
no. This makes it not savable in loadouts

2022-01-14 21:43 UTC, BraveMole commented
Stale. Get kuro to open and review this

2022-01-15 19:22 UTC, Kuro020 approved these changes
I JUST WANT TO PLAY TERRARIA FOR GODS SAKE

2022-01-15 19:41 UTC, Luxyboo commented
> I JUST WANT TO PLAY TERRARIA FOR GODS SAKE

lmao

2022-01-15 22:14 UTC, merged

2022-01-17 03:04 UTC, FosterGrime-Heymynameslouie commented
can we get the old dress uniform back in the form of a seperate uniform?