Reduces purge rate of larval accelerant from 3 to 1
tgstation/TerraGov-Marine-Corps pull request #9106
Opened 2021-12-30 07:43 UTC by private-tristan

## About The Pull Request

see title 

## Why It's Good For The Game

standing still for half a second and getting punished by having all of your meds removed in half a second isn't that great.

also
## Changelog
:cl:
balance: reduced larval accelerant's purge rate from 3 to 1
/:cl:

2021-12-30 11:07 UTC, BraveMole requested changes
Just remove larval and replace it by neurotox

2021-12-30 15:52 UTC, Losenis commented
>People keep complaining that marine meds are too strong
>Let's nerf the ways xenos have to purge them

2021-12-30 17:16 UTC, Araulius commented
>nerfing the counter to b18 and premedders

are you stupid? you have oodles of pills and injectors. what a non-issue.

2021-12-30 21:08 UTC, private-tristan commented
alright, I'll see if I can replace it with neurotoxin.

2021-12-30 21:51 UTC, BraveMole requested changes
remove larval from the game, it's no longer used by anything

2021-12-30 21:55 UTC, Losenis commented
It's no longer used by anything because you fucks keep removing it from everything, as queen screech + larval was my go-to tactic but you fucking people canned it due to some wild thing like too many buttons or whatever else and now claim nothing uses it

2021-12-30 22:03 UTC, BraveMole commented
> It's no longer used by anything because you fucks keep removing it from everything, as queen screech + larval was my go-to tactic but you fucking people canned it due to some wild thing like too many buttons or whatever else and now claim nothing uses it
> 
> I see zero point for this PR other than nerfing for the sake of nerfing. Larval could already work as "purges meds hard as hell but doesn't actually damage/kill you" alternative. Not even could, already DOES.

neurotox is not worse than larval.

2021-12-30 22:06 UTC, BraveMole commented
> It's no longer used by anything because you fucks keep removing it from everything, as queen screech + larval was my go-to tactic but you fucking people canned it due to some wild thing like too many buttons or whatever else and now claim nothing uses it
> 
> I see zero point for this PR other than nerfing for the sake of nerfing. Larval could already work as "purges meds hard as hell but doesn't actually damage/kill you" alternative. Not even could, already DOES.

Also if you want to add queen injection back, i don't think it's an issue. Especially with neuro

2021-12-31 02:15 UTC, private-tristan commented
okay, I'll go delete larval from the game

2021-12-31 02:16 UTC, Losenis commented
Neurotox is actually worse than larval in very short engagements because the premeds will still be doing something for a while longer than larval due to the far lower purge rate, and needs stam to drop to zero before even starting to do oxy and tox damage. If the guy is running paracetamol and ryetalin neurotox is basically useless since its purgerate is peanuts to do much in those few cycles. Defiler already has melee neurotox delivery, keep something else for the other xenos.

2021-12-31 02:43 UTC, private-tristan commented
I THINK that was all mentions of larval accelerant in the code. not sure though because forks don't allow searching.

2021-12-31 03:10 UTC, private-tristan commented
Okay, all checks passed!

2021-12-31 04:13 UTC, usnpeepoo commented
why are you letting xenos larval inject you in the first place? this should be left alone

2021-12-31 05:07 UTC, novaepee commented
Larval growth sting is a relic of capture gameplay. Like other relics of capture gameplay, they hit marines harder when spawners and silos replace larba burst. Carrier, disarm, eggs, defiler (remember when defiler puts an actual larva inside you?), and now larcval growth sting are subject to be corrected for the silo era.

The future is now.

2021-12-31 05:08 UTC, novaepee commented
> > It's no longer used by anything because you fucks keep removing it from everything, as queen screech + larval was my go-to tactic but you fucking people canned it due to some wild thing like too many buttons or whatever else and now claim nothing uses it
> > I see zero point for this PR other than nerfing for the sake of nerfing. Larval could already work as "purges meds hard as hell but doesn't actually damage/kill you" alternative. Not even could, already DOES.
> 
> Also if you want to add queen injection back, i don't think it's an issue. Especially with neuro

I can do that after this PR get merged if Tristan doesn't do it.

2021-12-31 06:16 UTC, Waselon commented
Next step: Remove lavral huggers

2021-12-31 09:26 UTC, BraveMole requested changes
rest looks good

2021-12-31 09:26 UTC, BraveMole commented on code/game/objects/machinery/vending/vending_types.dm
> +/*w
small mistake

2021-12-31 15:14 UTC, private-tristan commented on code/game/objects/machinery/vending/vending_types.dm
> +/*w
fixed.

2021-12-31 16:29 UTC, BraveMole approved these changes

2021-12-31 16:29 UTC, merged