Ghosts can assume control of minions
tgstation/TerraGov-Marine-Corps pull request #9115
Opened 2021-12-31 16:54 UTC by BraveMole

## About The Pull Request

Title. Also move taking ssd mobs form verb to an observer action

## Why It's Good For The Game

Need the minion nerf, and possibly more balance later on

## Changelog
:cl:
add: Ghosts can assume control of minions
/:cl:

2021-12-31 16:57 UTC, Mrrpip commented
Beetlin Ramis.

2021-12-31 18:06 UTC, private-tristan commented
I feel this will be wildly unbalanced, I like it.

2021-12-31 19:45 UTC, novaepee commented
Marines get vatborn, xenomorphs get minions. Good game design, ngl.

2022-01-03 01:02 UTC, Kuro020 approved these changes

2022-01-04 22:16 UTC, Rayfod commented
The AI of the mantis sometimes permanently takes over while you are controlling the mob.
The spit of the scorpion does also sometimes get stuck, leaving you spitting at whatever you targeted at that time, until you hit the spit button again.
I do not know about the bettle, but I would assume that there are a few bugs for them as well.

2022-01-05 02:53 UTC, Luxyboo commented
i have an issue with this because of the balance issues, currently scorpion and beetle are on par, if not better, than spitter and defender respectively. possibly nerfing the damage, speed, or ability to heal would be some concepts to take into account when it comes to balancing these player controlled ai. maybe minions only on low pop but on high pop they arent available.

2022-01-06 05:43 UTC, SrSC0ndition commented
Scorpion being a better spitter? Beetle over defender? Have you read these lines without a smile? If so, I am afraid you know little bit nothing about spitter and defender
The only issue with controllable minions being they have no cooldown on taking, only limitation being the amount of spawners and silos, other round xenos had cheesy 7 minions on top of their usual pop, and you don't want get mauled by 3 beetles at the same time

2022-01-10 21:48 UTC, hyper2snyper requested changes
we can merge after

2022-01-10 21:48 UTC, hyper2snyper commented on code/datums/actions/observer_action.dm
> +		if(ssd_mob.afk_status == MOB_RECENTLY_DISCONNECTED)
combine this and the above

2022-01-10 21:48 UTC, hyper2snyper commented on code/datums/actions/observer_action.dm
> +	if(ishuman(new_mob))
early return for my sanity

2022-01-12 07:39 UTC, novaepee commented
I miss it when players get to control minons before hive has to buy abilities for ghosts to control minions.

2022-01-12 09:55 UTC, AndroidMK2 commented
I would apply nerfs to minions but Only to those currently being player controlled, when a ghost takes over a minion the minion itself has lower stats than the same minion without a player controlling it so that minions are still useful when there's no one to control them and not too strong when they are.

2022-01-12 14:37 UTC, Mrrpip commented
> I would apply nerfs to minions but ONLY to those currently being player controlled, when a ghost takes over a minion the minion itself has lower stats than the same minion without a player controlling it so that minions are still useful when there's no one to control them and not too strong when they are.

But that'd leave you with a gimped minion that doesn't have perfect accuracy.

2022-01-14 00:06 UTC, Dueu commented
I have played minions a bit and if the health reduction is in general I prefer not to play as minions, such a nerf to that degree makes minions much less useful to have, player controlled minions is not a guaranteed as the amount of players connected changes depending the time of the day. As AndroidMK2 recommended, the nerf should come if a player is controlling it.

2022-01-14 00:15 UTC, BraveMole commented
> I have played minions a bit and if the health reduction is in general I prefer not to play as minions, such a nerf to that degree makes minions much less useful to have, player controlled minions is not something guaranteed as the amount of players connected changes depending the time of the day. As AndroidMK2 recommended, the nerf should come if a player is controlling it.

The health nerf is not that huge. Before, minions were running away at 40% health. I have removed that behaviour, and some removed 40% of beetle health (so it has no effect but costing less bullets and never escaping, but it was almost never espacting) and 25% of mantis health (this was actually a buff of controlled one). 

The only major nerf for ai minions is the speed. But i have a pr to fix that

2022-01-18 08:34 UTC, XSlayer300 commented on code/datums/actions/observer_action.dm
> +	name = "Take ssd mob"
```suggestion
	name = "Take SSD mob"
```

2022-01-18 08:35 UTC, XSlayer300 commented on code/datums/actions/observer_action.dm
> +		to_chat(owner, span_warning("There aren't any ssd mobs."))
```suggestion
		to_chat(owner, span_warning("There aren't any SSD mobs."))
```

2022-01-21 18:40 UTC, merged