SleevesProject
tgstation/TerraGov-Marine-Corps pull request #9126
Opened 2022-01-01 08:50 UTC by EvilMelonTheSecond

## About The Pull Request

## Why It's Good For The Game

## Changelog
:cl:
add: Added new mechanics or gameplay changes
add: Added more mechanics or gameplay changes
expansion: Expands content of an existing feature
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2022-01-01 18:09 UTC, hyper2snyper requested changes

2022-01-01 18:09 UTC, hyper2snyper commented on code/modules/clothing/under/under.dm
> +		"Half" = "_h",
This is adding a halve version of sleeves to ALL the uniforms. Unless you have sprites for them all, you should overwrite on the specific ones you have sprites for.

2022-01-02 00:27 UTC, hyper2snyper requested changes

2022-01-02 00:27 UTC, hyper2snyper commented on code/modules/clothing/under/marine_uniform.dm
> +	adjustment_variants = list()
why are you removing the variants for these?

2022-01-02 00:27 UTC, hyper2snyper commented on code/modules/clothing/under/marine_uniform.dm
> +	adjustment_variants = list()
this is overwriting the `adjustment_variants` right above it.
look two lines up.

2022-01-02 07:58 UTC, EvilMelonTheSecond commented
I should check my own code to spare the sanity of maintainers, this PR is too simple to have been corrected two times.

2022-01-03 01:03 UTC, Kuro020 requested changes
isnt this missing some of the marine jumpsuits?

2022-01-03 07:42 UTC, EvilMelonTheSecond commented
> isnt this missing some of the marine jumpsuits?

They are. The sprites aren't mine I was just the one to implement them

2022-01-09 05:31 UTC, merged