Give Corpsmen MORE Hypospray
tgstation/TerraGov-Marine-Corps pull request #9138
Opened 2022-01-02 06:47 UTC by novaepee

## About The Pull Request

RELEASE THE ~~KRAKEN~~ hypospray!

Corpsmen now have preloaded bica, kelo, and tram hypospray in essential kit. It's up to them if they want to use it or not.

More hyposprays can be find in the TerraGovTech Medic Vendor. Which that in mind, there are no more hyposprays in the Nanotrasen Plus medical vendor.

## Why It's Good For The Game

JPR approves of this. He is the residental medical balance person.

## Changelog
:cl:
add: more hyposprays for corpsmen! Find them in your essential kit and TerraGovTech Medic Vendor
del: Remove hypospray in Nanotrasen Plus medical vendor
qol: more hyposprays for corpsmen!
balance: more hyposprays for corpsmen
/:cl:

2022-01-02 06:54 UTC, novaepee commented
I may add reagent bottles in the TerraGovTech Medic Vendor just for corpsmen to make their own blend of madness at the comfort of their squad prep.

What do you mean you can't save custom mixed hypospray? Get out of here!

2022-01-02 08:00 UTC, EvilMelonTheSecond commented
Finally I can stop stealing tric hypos from medbay vendors. Age of pills is over

2022-01-03 14:48 UTC, BraveMole requested changes
this is given for absolutly free, why?

2022-01-05 21:57 UTC, BraveMole requested changes

2022-01-05 21:57 UTC, BraveMole commented on code/__DEFINES/loadout.dm
> +		/obj/item/storage/belt/combatLifesaver = list(CAT_BEL, "Lifesaver medic belt", 0, "orange"),
this will break loadouts. Just change the medicLifesaver, no?

2022-01-05 21:57 UTC, BraveMole commented on code/game/objects/items/storage/belt.dm
> +	new /obj/item/stack/medical/heal_pack/advanced/bruise_pack(src)
out of scope

2022-01-05 21:57 UTC, BraveMole commented on code/game/objects/items/storage/belt.dm
> -		/obj/item/reagent_containers/glass/bottle,
out of scope

2022-01-05 21:57 UTC, BraveMole commented on code/game/objects/machinery/vending/marine_vending.dm
> +			/obj/item/reagent_containers/hypospray/advanced/bicaridine,
```suggestion
			/obj/item/reagent_containers/hypospray/advanced/bicaridine = -1,
```
ditto for the rest

2022-01-07 17:04 UTC, BraveMole requested changes

2022-01-07 17:04 UTC, BraveMole commented on code/game/objects/items/storage/belt.dm
> -		/obj/item/reagent_containers/glass/bottle,
No, there should be no changes at all. Put them back where it was

2022-01-07 17:04 UTC, BraveMole commented on code/game/objects/items/storage/belt.dm
> +	new /obj/item/stack/medical/heal_pack/advanced/bruise_pack(src)
I said : out of scope.

2022-01-07 17:04 UTC, BraveMole commented on code/game/objects/machinery/vending/marine_vending.dm
> +			/obj/item/reagent_containers/hypospray/advanced/tricordrazine,
All

2022-01-11 22:30 UTC, novaepee commented
Going to atomize this PR.

2022-01-11 22:30 UTC, closed without merging