Common Supply Channel
tgstation/TerraGov-Marine-Corps pull request #9151
Opened 2022-01-03 14:50 UTC by EvilMelonTheSecond

## About The Pull Request
Adds supply channel to all radio headsets

## Why It's Good For The Game
Allows communication between req and field much more effectively than RO shouting "GET MINERS" or "WE GOT POINTS, WHAT DO YOU WANT?" in common channel. Cleaner common channel and more supply orders, lovely.

## Changelog
:cl:
add: Added supply channel to all headsets
/:cl:

2022-01-03 14:52 UTC, BraveMole requested changes
check that:
- this doesn't conflict with req channel being given to ro and such.
- people can make this channel quiet (i think activating the headset allow to shut it down?)

2022-01-03 15:22 UTC, Verlurk commented
So, if everyone has this channel, what's the point of Common existing?

2022-01-03 15:41 UTC, Losenis commented
>What's the point of common existing

Color coding makes things easier to identify at a glance rather than outright reading the channel name, much like how each squad channel has its own color for each squad

2022-01-04 22:37 UTC, BraveMole approved these changes

2022-01-04 22:37 UTC, merged