Change "sentinels stung" to "neurotoxin sting was used" in roundend statistics
tgstation/TerraGov-Marine-Corps pull request #9157
Opened 2022-01-03 22:10 UTC by novaepee

## About The Pull Request

Stealing #9132

## Why It's Good For The Game

More than sents are using neurotoxin sting.

## Changelog
:cl:
fix: Change "sentinels stung" to "neurotoxin sting was used" in roundend statistics
/:cl:

2022-01-03 22:16 UTC, novaepee commented
Okay, some of the roundend statistics are old, so time to change that up.

PR CHANGE, LETS GO!

2022-01-04 12:34 UTC, BraveMole approved these changes

2022-01-04 12:35 UTC, BraveMole requested changes
you have to remove completly those indicators from the game

2022-01-07 18:59 UTC, BraveMole approved these changes

2022-01-07 18:59 UTC, merged