Allows sentries to accept any type of cell
tgstation/TerraGov-Marine-Corps pull request #9166
Opened 2022-01-05 09:19 UTC by Three333Digit

## About The Pull Request
Title. 
Sentries on deployment comes with a power cell with a power rating of 1000
Sentry crates such as UA580 and UA571 comes with 2 power cells with a power rating of 1000

## Why It's Good For The Game
Radial mode is completely useless as it is because of the battery capacity. Engineer tries to make use of radial mode, it shoots <10 bullets and runs out of battery quick, and if the xeno it was shooting at isn't a stationary NPC it is now stuck looking at an angle where it's useless, and then the engineer is left crying as he adjusts the turret back to only look at one direction. Having the option to give the sentry a higher battery capacity will open up more strategies for the engineer to play around with. 

## Changelog
:cl:
balance: sentries accept any type of power cell
balance: sentry crates comes with 2 1000u power cells
balance: sentries on deployment comes with a 1000u power cell
/:cl:

2022-01-05 13:31 UTC, BraveMole requested changes
Considering this is IIRC also making lasgun sentries have way more ammo, no.

Now, i agree that radial is a bit of a mess rn. What is suggest is removing baterries from sentries all together, and making radial have less range

2022-01-07 16:42 UTC, BraveMole requested changes

2022-01-07 16:42 UTC, BraveMole commented on code/modules/projectiles/sentries.dm
> +		range = gun.turret_range - 2
This should be done l48, you are setting range twice. Also this should be using trinary ( ? operator)

2022-01-07 17:01 UTC, BraveMole requested changes

2022-01-07 17:01 UTC, BraveMole commented on code/modules/projectiles/sentries.dm
> +	range = !CHECK_BITFIELD(gun.turret_flags, TURRET_RADIAL) ? gun.turret_range : gun.turret_range - 2
```suggestion
	range = CHECK_BITFIELD(gun.turret_flags, TURRET_RADIAL) ?  gun.turret_range - 2 : gun.turret_range
```

2022-01-07 17:07 UTC, BraveMole approved these changes

2022-01-07 18:57 UTC, hyper2snyper commented
this hurts my soul

2022-01-08 09:57 UTC, BraveMole approved these changes

2022-01-08 09:57 UTC, merged