Railgun projectiles now penetrate
tgstation/TerraGov-Marine-Corps pull request #9195
Opened 2022-01-07 19:27 UTC by Waselon

## About The Pull Request

Railgun projectiles now can penetrate mobs/objects/turfs, losing 33% of its current damage/sunder/penetration per pierce.

## Why It's Good For The Game

Bravemole wanted to see this on railgun first, so here it is. Also slightly buffs underused gun.

## Changelog
:cl:
balance: Railgun projectiles now penetrate stuff
/:cl:

2022-01-07 20:44 UTC, Lumipharon commented
I am hyped for next level FF.

2022-01-07 21:36 UTC, Moggram commented
> I am hyped for next level FF.

I can see it now. bro fires the railgun and hits 5 guys. adman plays [this](https://www.youtube.com/watch?v=cGsuGAb5NUQl)

2022-01-09 22:01 UTC, BraveMole requested changes
Plus what i said on disc

2022-01-13 09:25 UTC, BraveMole requested changes

2022-01-13 16:46 UTC, BraveMole requested changes

2022-01-13 16:46 UTC, BraveMole commented on code/modules/projectiles/projectile.dm
> +	if(((proj.ammo.flags_ammo_behavior & AMMO_PASS_THROUGH_MOVABLE) || (proj.ammo.flags_ammo_behavior & AMMO_PASS_THROUGH_TURF)) && HAS_TRAIT(proj, TRAIT_PROJ_HIT_SOMETHING))
(proj.ammo.flags_ammo_behavior & AMMO_PASS_THROUGH_MOVABLE|AMMO_PASS_THROUGH_TURF) works. But uh, is it even possible to call bullet_act twice if you are not AMMO_PASS_THROUGH anyway? In that case the flags check is useless

2022-01-13 16:46 UTC, BraveMole commented on code/modules/projectiles/projectile.dm
> +	var/sundering = 0
New vars must be autodoced

/// A comment on what is penetration
var/penetration = 0

2022-01-13 16:46 UTC, BraveMole commented on code/modules/projectiles/ammo_datums.dm
> +	var/on_pierce_multiplier 		= 1			// A multiplier applied to piercing projectile, that reduces its damage/penetration/sundering on hit
ditto, need autodoc

2022-01-13 16:46 UTC, BraveMole commented on code/modules/projectiles/projectile.dm
> +	ADD_TRAIT(proj, TRAIT_PROJ_HIT_SOMETHING, TRAIT_PROJ_HIT_SOMETHING)
it should be ADD_TRAIT(proj, TRAIT_PROJ_HIT_SOMETHING, BULLET_ACT_TRAIT)

the last argument is the "origin" of the trait

2022-01-16 11:09 UTC, BraveMole commented
Not sure anyone used the railgun BUT this didn't fucked at all with regular bullet so good to go

2022-01-16 11:09 UTC, merged