Add teleporters pad to req
tgstation/TerraGov-Marine-Corps pull request #9207
Opened 2022-01-08 10:21 UTC by BraveMole

## About The Pull Request

They can be bought in req, in pairs. They are prelinked, and if one is destroyed, the other explode. 
You can move crates, machinery and marines from one teleporter to the other, if it's on the same z level.

Needs to be anchored and the area needs to be powered.

## Why It's Good For The Game

It's quite hard to setup so this shouldn't be too op. This makes forward bases stronger since you can more easily refurnish/retreat from those places

## Changelog
:cl:
add: Add teleporters pad to req
/:cl:

2022-01-08 14:38 UTC, EvilMelonTheSecond commented
Now this is something that can connect shipside roles to groundside. You could already do this with medevacs but now its properly in the game. I expect cool results from this.

2022-01-08 14:58 UTC, Losenis commented
>Now this is something that can connect shipside roles to groundside

He did say same z-level so this is mostly going to be linking FOB and forward bases rather than the actual ship.

2022-01-08 15:47 UTC, BraveMole commented
I thought of allowing z level transfers but i think this would be to game breaking

2022-01-08 19:19 UTC, EvilMelonTheSecond commented
Oh, then this is almost obsolete. Marine gameplay rarely allows frontline outposts let alone a powered one. Even if marines established one they would still have to keep the push and leave it undefended. Carrying ammo with a crate is more useful than this.

2022-01-08 19:24 UTC, Losenis commented
Counterpoint, tadpole

2022-01-08 19:30 UTC, EvilMelonTheSecond commented
> Counterpoint, tadpole

Make it a tadpole upgrade like the HMG and operating table then. 50 points is just meh for a tadpole only upgrade

2022-01-08 20:18 UTC, Losenis commented
>Make it a tadpole upgrade

Why?

2022-01-08 20:24 UTC, EvilMelonTheSecond commented
> > Make it a tadpole upgrade
> 
> Why?

It needs power, marines almost never stay in places with power (most of the time because there is no power in caves/open areas). Previously floodlights were changed to use a battery instead of area power by Bravemole for that exact reason. The game wants marines to push to kill silo/spawners which are 100% in caves, meaning setting these up either needs unwilling manpower or even more points and time for sentries and a big cadeline to keep it defended.

2022-01-08 22:45 UTC, Losenis commented
That still is no reason to make it a module that competes with two literally free modules found at roundstart. Its already limited use would be limited even more down to uselessness if you can't even use groundside power to have it be a teleporter from LZ1 to gens in big red for example, and stopping engis from using it unless someone else who'd use tadpole also comes along.

2022-01-09 04:17 UTC, Tristan63 commented
make it 60 points and turn it into portal gun

2022-01-09 21:43 UTC, Lumipharon commented
Can this be powered directly from the grid (i.e. a generator on the tad etc), or apc power only? Either way looks FUN.

2022-01-12 18:06 UTC, EvilMelonTheSecond commented
The added cell powered function changes a lot of things. This can now connect FOB to forward bases properly in really far pushes, which gives marines a reason to bunker down near frontlines. A dedicated engineer can now alleviate the attrition of giant maps like Big Red or Ice Colony. Finally an engi tool to help pushes.

2022-01-13 19:19 UTC, hyper2snyper requested changes
looks good. TM after this

2022-01-13 19:19 UTC, hyper2snyper commented on code/game/objects/structures/teleporter.dm
> +		CRASH("A teleporter was linked with another teleporter eve though it already has a twin!")
```suggestion
		CRASH("A teleporter was linked with another teleporter even though it already has a twin!")
```

2022-01-13 19:19 UTC, hyper2snyper commented on code/game/objects/structures/teleporter.dm
> +		return
'return FALSE' ?

2022-01-13 19:24 UTC, BraveMole commented on code/game/objects/structures/teleporter.dm
> +		return
```suggestion
		return FALSE
```

2022-01-18 08:36 UTC, XSlayer300 commented on code/game/objects/structures/teleporter.dm
> +		to_chat(user, span_warning("The [src] is not linked to any other teleporter"))
```suggestion
		to_chat(user, span_warning("The [src] is not linked to any other teleporter."))
```

2022-01-18 08:37 UTC, XSlayer300 commented on code/game/objects/structures/teleporter.dm
> +		to_chat(user, span_warning("The [src] and the [linked_teleporter] are too far appart"))
```suggestion
		to_chat(user, span_warning("The [src] and the [linked_teleporter] are too far apart!"))
```

2022-01-19 15:24 UTC, FosterGrime-Heymynameslouie commented
Teleporter pads aren't linked if one is using room power and the other is using cell power.
Teleporter linker has no sprite.
Teleporter Linker cant be picked up.

2022-01-27 19:57 UTC, hyper2snyper commented
this ready?

2022-01-27 21:24 UTC, BraveMole commented
Yes

2022-01-29 19:27 UTC, merged