The Hypospray Belt
tgstation/TerraGov-Marine-Corps pull request #9237
Opened 2022-01-11 22:38 UTC by novaepee

## About The Pull Request

Recent concerns from some corpsmen want to base themselves around the hypospray but is in short supply of them. The Research and Development team provides! Now, they get a hypospray belt dedicated to holding reagent bottles and hyposprays to their heart's content! It's up to them if they want to use it or not.

Hypospray belt can only hold analyser, hyposprays, and reagent bottles.

Corpsmen cannot have preloaded hyposprays consisting of bicaridine, kelotane, tramadol, dexalin, inaprovaline, peridaxon, and quickclot YET! I just need to do some magic about that.

## Why It's Good For The Game

JPR approves of this. He is the residental medical balance person.

Bravemole gives better gameplay choices and design on hypospray.

Many good corpmen carry multiple hypospray since they can use this for marines that are running away from the corpsmen. Using autoinjectors as corpmen is kinda wack.

I swear, this won't be like how corpsmen have big hypospray for free. I might get yelled at by MJP since #5700.

Also, impending #9236 .

## Changelog
:cl:
add: the hypospray belt! The belt is loaded with bicaridine, kelotane, tramadol, dexalin, inaprovaline, peridaxon, and quickclot hypospray along with reagent bottles.
/:cl:

2022-01-11 22:56 UTC, Lumipharon commented on code/game/objects/items/storage/belt.dm
> +		/obj/item/reagent_containers/hypospray/autoinjector,
Doesn't this mean you can't actually put hypos in it?
```suggestion
		/obj/item/reagent_containers/hypospray/,
```

2022-01-11 22:58 UTC, Lumipharon commented
Definitely cool to have, but I do wonder how useful it is in practice, as you can get the same outcome more efficiently without this belt.

The reagent bottles are only 60u, where as a pill bottle holds up to 240u (or 480u, in the case of inaprov).
Because you can just add pills to a hypo as easily as using a reagent bottle, if I wanted to replicate a hypo belt I could have a medkit with the 7 hypos you've got in the belt (excluding inaprov, that's almost always used on poor sods that can't run away), then fill the normal medic belt with a hugely more expansive amount of all those reagents, as well as all the other junk medics need.

For the hypo belt medic, they'll have less reagents, and will still need to devote storage space else where to all the non reagent junk they need to carry.

2022-01-11 23:44 UTC, novaepee commented
MJP and others told me to put in reagent bottle cases that hold 3 reagent bottles inside of them. I won't be surprise if storage creep, but MJP knows storage creep well, so I trust his word on this.

2022-01-11 23:45 UTC, novaepee commented
![image](https://user-images.githubusercontent.com/6610922/149038845-1ee3341d-638b-47b6-89e6-9050f33ac231.png)

2022-01-12 18:40 UTC, BraveMole requested changes

2022-01-12 18:40 UTC, BraveMole commented on code/game/objects/items/storage/firstaid.dm
> +/obj/item/storage/bottlecase
why does this exist ?

2022-01-12 20:12 UTC, BraveMole approved these changes

2022-01-16 07:41 UTC, novaepee commented
After getting feedback, corpsmen want additional types of hypospray and a dex bottle case.

2022-01-16 11:15 UTC, BraveMole requested changes
I'm freezing this pr until mjp finishes medical rebalance

2022-01-16 11:15 UTC, BraveMole commented on code/game/objects/items/storage/belt.dm
>  	new /obj/item/reagent_containers/hypospray/advanced/quickclot(src)
all the single hypospray should not be hyposray, but injectors. This should definitly not procure more reagants than normal medbelt

2022-01-16 11:15 UTC, BraveMole commented on code/game/objects/items/storage/belt.dm
>  	new /obj/item/reagent_containers/hypospray/advanced/tricordrazine(src)
no other belts procure tricordrazine like that free

2022-01-20 20:25 UTC, Kuro020 approved these changes

2022-02-01 12:19 UTC, BraveMole approved these changes

2022-02-01 12:19 UTC, merged