updating corpsman vendor
tgstation/TerraGov-Marine-Corps pull request #9238
Opened 2022-01-11 22:49 UTC by novaepee

## About The Pull Request

The age old TerraGov Medic Vendor is in dire need of update. Might update it further in light of #9236.

Corpsmen now have preloaded hyposprays consisting of bicaridine, kelotane, tramadol, dexalin, inaprovaline, peridaxon, and quickclot. More hyposprays can be find in the TerraGovTech Corpsman Vendor, you know, that vendor that is in squad corpsman prep.

## Why It's Good For The Game

## Changelog
:cl:
expanded: the TerraGovTech Corpsman Vendor is now ACTUALLY not outdated!
add: more preloaded hyposprays for corpsmen! Corpsmen get bica, kelo, and tram hypospray, the holy three, among other!. Find them in the TerraGovTech Corpsman Vendor
add: reagent bottles in the TerraGovTech Corpsman Vendor
del: Remove stuff in TerraGovTech CORPSMAN Vendor; why do you need to get a pistol pouch from there?
qol: more hyposprays for corpsmen!
balance: more hyposprays for corpsmen
/:cl:

2022-01-11 23:04 UTC, novaepee commented
Currently, hypospray paths are not defined since hypospray belt PR has the code but this PR doesn't.

2022-01-16 10:58 UTC, BraveMole requested changes

2022-01-16 10:58 UTC, BraveMole commented on code/game/objects/machinery/vending/marine_vending.dm
> +			/obj/item/reagent_containers/glass/bottle/bicaridine = 4,
reagants added here must be removed elsewhere

2022-01-21 12:52 UTC, BraveMole commented
mjp pr take priority on this

2022-01-21 12:52 UTC, closed without merging