fixes autofire getting scatter debuff from burst
tgstation/TerraGov-Marine-Corps pull request #9273
Opened 2022-01-14 02:49 UTC by SplinterGP

## About The Pull Request
title
Closes #9272 

## Why It's Good For The Game

## Changelog
:cl:
fix: fixed autofire getting burst fire debuff on guns that has burst fire
/:cl:

2022-01-14 17:06 UTC, BraveMole requested changes

2022-01-14 17:06 UTC, BraveMole commented on code/modules/projectiles/gun_system.dm
>  	switch(gun_firemode)
You're ignoring the deployed scatter change + there is no reason to have a switch here

2022-01-15 03:58 UTC, SplinterGP commented on code/modules/projectiles/gun_system.dm
>  				. += deployed_scatter_change
```suggestion
	if(CHECK_BITFIELD(flags_item, IS_DEPLOYED)) //if our gun is deployed, change the scatter by this number, usually a negative
		. += deployed_scatter_change
```

2022-01-15 21:37 UTC, BraveMole approved these changes

2022-01-15 21:37 UTC, merged