TX-11 and T-18 no longer have extra delay on burst fire.
tgstation/TerraGov-Marine-Corps pull request #9278
Opened 2022-01-14 20:58 UTC by Pariah919

## About The Pull Request
TX-11 and T-18 have had extra delay removed.

## Why It's Good For The Game
These weapons are burst focused and making their one upside over other firearms (or sidegrade gimmick in the case of the tx-11) seems quite unneeded now, if the issue lies with BFA, add extra delay to BFA.

## Changelog
:cl:
balance: TX-11 and T-18 extra delay removed.
/:cl:

2022-01-14 21:33 UTC, BraveMole requested changes
i smell powercreep?

2022-01-14 22:02 UTC, BraveMole approved these changes

2022-01-14 23:08 UTC, Lumipharon commented
TX11 has pretty high DPS, and the burst delay 0.1. without the extra delay, isn't this going to skyrocket the DPS?

2022-01-15 01:16 UTC, KrabSpider commented
Hey MJP. Let's not repeat the T- "no delay, 97.5 burst damage, 15 AP, 2 sunder" 64 incident and turn the TX11 into a high sunder budget LMG.

2022-01-18 19:44 UTC, merged