Add specialist armor to requisition
tgstation/TerraGov-Marine-Corps pull request #9309
Opened 2022-01-17 09:40 UTC by Waselon

## About The Pull Request

Adds 4 missing specialist sets of armor to requisition (Demolitionist, Scout, Sniper, Pyrotechnician), for 50 points per set.

## Why It's Good For The Game

It looks badass (especially Pyro), has some quirks, and people requested to add it back. I dont see a reason not to add it (for a reasonable price), along with B17 and B18.

## Changelog
:cl:
add: added 4 sets of specialist armor to requisition
/:cl:

2022-01-17 13:24 UTC, Mrrpip commented
So uh...Looking at it a bit, the Pyro kit is a Tyr 2 + Surt, which is a niche.

But the Scout/Sniper/Demo are too similar stat wise, with the caveat that Scout has better melee/bullet/acid.

Demo can hold a rocket launcher, but.....That isn't unique to it and the extra bomb armor is not very outstanding (55 compared to a full jaegar, any type as bomb armor is uniform at 50 by default).

They also have poor acid armor around the board.

So, I guess it'd have an interesting dynamic of armored but speedy gear with the scout kit, but it outmatches the Demo/Sniper variants.

...Atleast it ain't the riot gear.

2022-01-18 22:05 UTC, BraveMole requested changes
Should be atomised, and every addition to req should be justified from a gameplay perspective

2022-01-19 05:53 UTC, Waselon commented
> Should be atomised, and every addition to req should be justified from a gameplay perspective

Theres only 2 armors in reqisition, B17 for 80 points (which is rarely used), and B18 for 120 points (which is expensive as hell).

4 armor sets i want to add offer a middleground between price and power, a small upgrade/sidegrade from jaeger+modules for moderate price.

2022-01-19 20:40 UTC, Tristan63 commented
The sprites are sexy as hell and should be used in some capacity

2022-01-23 10:34 UTC, OpsCoretango commented
If you not gotta do something this PR go to forever box

2022-01-23 12:48 UTC, Waselon commented
> If you not gotta do something this PR go to forever box

what else should i do?

2022-01-26 21:41 UTC, BraveMole commented
Stale. I told you what to do, a pr for each armor and every item added should be justified balance and design wise

2022-01-26 21:41 UTC, closed without merging