Adds population dependent map inserts
tgstation/TerraGov-Marine-Corps pull request #9322
Opened 2022-01-18 03:46 UTC by RipGrayson

## About The Pull Request

I've been needing to do this for a bit, essentially allows for mappers to define min and max player values needed for a modular mapping insert to be in "rotation" for a given map.
E.g I could define a LV dome to only show up with a population of between 50 and 100. 

## Why It's Good For The Game

This sort of thing has been needed for quite a while and the potential is fairly limitless. We could theoretically define places in big maps like Chigusa and Magmoor that shrink on lower pop and grow at higher pop, allowing for much more flexible maps.

## Changelog
:cl:
code: Added population dependent mapping insert support.
/:cl:

2022-01-18 19:49 UTC, hyper2snyper approved these changes
this is pretty cool

2022-01-18 19:49 UTC, hyper2snyper commented on code/modules/mapping/modular_mapping.dm
> +	var/min_player_num //minimum player number for a modular to be added to the pool of potential modular map spawns.
autodoc these two like the rest.

2022-01-20 04:10 UTC, Lumipharon commented
Not directly related to the pop based mechanic, but does this functionality mean you could in theory go completely nuts and have a map with a (relative) degree of randomisation? Like shifting buildings around and that sort of thing?

2022-01-20 20:19 UTC, RipGrayson commented
Had a talk with Mole, this isn't going to work in any real world situation. Please don't merge it while I work on a better solution.

2022-01-21 12:49 UTC, BraveMole requested changes
How did you test this?

2022-01-21 12:49 UTC, BraveMole commented on code/controllers/subsystem/mapping.dm
> +	//The number of connected clients for the previous round
```suggestion
	///The number of connected clients for the previous round
```

2022-01-21 14:52 UTC, RipGrayson commented
> How did you test this?

The first iteration was tested with a modified version of Big Red that has 5 debug modular inserts that I would alter the min and max population for, along with a debug message that told me when an insert had entered the map pool and which insert it was.

The current version largely used the same system, except I could alter the .json file to report a larger number of players allowing for more extensive testing of higher population. It wasn't as extensively tested as the first version, because the core of the map selection process is the same, it's just pulling the player number from a stored .json file from the last round instead of checking for currently connected clients.

2022-01-24 20:18 UTC, merged