revolver changes- non akimbo firerate buff, and knockback readded
tgstation/TerraGov-Marine-Corps pull request #9343
Opened 2022-01-20 07:07 UTC by Pariah919

revolver changes

## About The Pull Request
Readds knockback to revolver, makes akimbo have the same firerate as before so no change. And readds knockback to the bullet.

## Why It's Good For The Game
Everyone has cooled off about revolver. Let it have SOME gimmick.
This should give it a neat gimmick without making it top tier overpowered.

## Changelog
:cl:
balance: Revolver fires at 0.15 when non akimboed, and has knockback again.
/:cl:

2022-01-20 17:54 UTC, turnop commented
good changes, if le revolver man becomes too funny with these just make revolver not fit in backpacks or satchels

2022-01-20 18:58 UTC, Lumipharon commented
Akimbo additional delay is a multiplier, not additive AFAIK.

2022-01-20 19:19 UTC, Pariah919 commented on code/modules/projectiles/guns/revolvers.dm
> +	akimbo_additional_delay = 0.05 SECONDS
```suggestion
	akimbo_additional_delay = 1.6 // Ends up as 0.249, so it'll get moved up to 0.25.
```

2022-01-21 19:25 UTC, BraveMole requested changes

2022-01-21 19:25 UTC, BraveMole commented on code/modules/projectiles/guns/revolvers.dm
> +	akimbo_additional_delay = 1.6 // Ends up as 0.249, so it'll get moved up to 0.25.
0.6

2022-01-22 01:04 UTC, Pariah919 commented on code/modules/projectiles/guns/revolvers.dm
> +	akimbo_additional_delay = 1.6 // Ends up as 0.249, so it'll get moved up to 0.25.
```suggestion
	akimbo_additional_delay = 0.6 // Ends up as 0.249, so it'll get moved up to 0.25.
```

2022-01-22 01:04 UTC, Pariah919 commented on code/modules/projectiles/guns/revolvers.dm
> +	akimbo_additional_delay = 1.6 // Ends up as 0.249, so it'll get moved up to 0.25.
done

2022-01-22 11:01 UTC, GravitronBlue commented
> good changes, if le revolver man becomes too funny with these just make revolver not fit in backpacks or satchels

I'm way overdue thinking this, but would disabling quickdrawing weapons from storage containers curb the unga meta of just having a stockpile of revolver bags to magdump(cylinderdump?) with?

> Everyone has cooled off about revolver.

Only so long as the xeno hive's T1s aren't being shredded by Ocelot ungas on bikes.
Readding knockback could also mean a FUN return of flank cheese jetpack ungas.

Though frankly I don't mind the knockback so long as heavy/large xeno castes aren't being bullied around by it.

2022-01-22 20:41 UTC, Lumipharon commented
@Pariah919 Keep in mind the default akimbo additional delay is 0.5, so increasing it to 0.6 is actually a very minor akimbo nerf (I need to change my PR as well...)
For comparison, akimbo ROF per gun is changing from 0.375 (rounds to 0.4 or 0.35? I unno) to 0.24, rounding to 0.25.

2022-01-23 17:55 UTC, BraveMole approved these changes

2022-01-23 17:55 UTC, merged