Combat Robots no longer get heart damage from defib and shrapnel
tgstation/TerraGov-Marine-Corps pull request #9347
Opened 2022-01-20 21:39 UTC by Three333Digit

## About The Pull Request
Title. Closes #9256
The shrapnel change also affects anything robotic, that means synths and any human with robotic limbs gained through surgery won't get shrapnel in that specific robotic limb. If that's not good, tell me.

## Why It's Good For The Game
Bugfix. The main reason why combat robots get heart damage is from defibs from what I've found.

## Changelog
:cl:
fix: combat robots no longer get heart damage from defib
fix: robots and synths no longer get shrapnel
/:cl:

2022-01-20 22:10 UTC, Lumipharon commented
What's the big deal with shrapnel? Just being a beepboop doesn't mean bullets can't lodge themselves in you, and they can still be removed by tweezer afaik.

2022-01-20 22:15 UTC, jroinc commented
If you have a chance, I'd go into organs/organs_internal.dm OR carbon/human/species.dm and add, say, a 1 pt/tick autoheal for either prosthetic organs OR robot organs, given as we're assuming that they shouldn't be hurt by anything. That'll catch any edge cases that slip through.

2022-01-20 22:20 UTC, ilikesaying commented
> What's the big deal with shrapnel? Just being a beepboop doesn't mean bullets can't lodge themselves in you, and they can still be removed by tweezer afaik.

shrapnel damage is worse to heal since robots can't take medicine to automatically heal the damage, meaning they get damage every time they walk that they have to manually repair while searching for the closest corpsman

2022-01-20 22:28 UTC, Moggram commented
could have it so that wirecutters remove shrapnel.

2022-01-20 22:30 UTC, Lumipharon commented
> > What's the big deal with shrapnel? Just being a beepboop doesn't mean bullets can't lodge themselves in you, and they can still be removed by tweezer afaik.
> 
> shrapnel damage is worse to heal since robots can't take medicine to automatically heal the damage, meaning they get damage every time they walk that they have to manually repair while searching for the closest corpsman

True, but robots are second class citizens, if they choose to play robots they should accept the drawbacks. Not being able to get shrapnel at all is a straight upgrade compared to meatbags.

2022-01-20 23:28 UTC, Naaanii commented
I'd say keep shrap but remove organ damage if possible.

2022-01-20 23:47 UTC, Mrrpip commented
> > > What's the big deal with shrapnel? Just being a beepboop doesn't mean bullets can't lodge themselves in you, and they can still be removed by tweezer afaik.
> > 
> > 
> > shrapnel damage is worse to heal since robots can't take medicine to automatically heal the damage, meaning they get damage every time they walk that they have to manually repair while searching for the closest corpsman
> 
> True, but robots are second class citizens, if they choose to play robots they should accept the drawbacks. Not being able to get shrapnel at all is a straight upgrade compared to meatbags.

But we have ballistic armor?

2022-01-21 01:54 UTC, Losenis commented
> True, but robots are second class citizens, if they choose to play robots they should accept the drawbacks. Not being able to get shrapnel at all is a straight upgrade compared to meatbags.

Pretty sure the lack of boots and gloves, a new loadout altogether, the inability of using chems, being a robot, effectively being critdrag bait because no oxyloss on crit, being conveniently FFd when you earrape someone with warcry, and inability to run are wild enough drawbacks.

2022-01-21 12:57 UTC, BraveMole requested changes
the heart damage is a straight bug fix, cool.

The shrap one, eh, i'm not a fan. 
Removing organ damage (or organs) would be cool though

2022-01-22 07:25 UTC, Three333Digit commented
Might need to TM first.

2022-01-23 11:35 UTC, BraveMole requested changes

2022-01-23 11:35 UTC, BraveMole commented on code/game/objects/items/scanners.dm
> +	if (M.getBrainLoss() >= 100 || !M.has_brain() && !isrobot(M))
Logic seems flawed here

2022-01-23 17:58 UTC, BraveMole approved these changes

2022-01-23 17:58 UTC, merged