T-26 Antimaterial Sniper Rifle added to smartgunner; also, T-25 Smart assault rifle name change
tgstation/TerraGov-Marine-Corps pull request #9376
Opened 2022-01-23 01:33 UTC by novaepee

## About The Pull Request

The T-26 Antimaterial Sniper Rifle found a home in the smartgunner family. It has gun_skill_category = GUN_SKILL_SMARTGUN, so only smartgunner can use it.

T-26 is the most expensive out of all the smartgunner weapon so far. It spawns with 90 total rounds, so you have to make your shot count.

Since we have two rifles in smartgunner vendor, give the adjective assault to T-25 Smart assault rifle. Yeah, it's an assault rifle.

Bravemole approves. MJP, better luck next time.

## Why It's Good For The Game

This weapon belongs to marines, and marines barely use it. It was collecting web and dust in req, so it is time to give this baby a go.

Bravemole approves of putting this in smartgunner.

## Changelog
:cl:
add: T-26 Antimaterial Sniper Rifle added to smartgunner
expansion: T-25 smart rifle is now called T-25 smart assault rifle
balance: Smartgunners have new weapon!
/:cl:

2022-01-23 01:33 UTC, novaepee commented
![image](https://user-images.githubusercontent.com/6610922/150661170-9387a916-e041-40df-a36f-15f4bc6f03f6.png)

2022-01-23 01:44 UTC, MereWalker commented
Is this T26 the T81?

2022-01-23 01:50 UTC, Pariah919 commented
```
holy balls
why are you giving a 75 point weapon to sg

2022-01-23 01:51 UTC, Pariah919 commented
Stop trying to shove another weapon into your SG sniper fantasy and wait for someone to make either a new sprite or go grab an old one, because it needs specialized balance instead of shoving something like this in, which will probably break balance.

2022-01-23 02:05 UTC, novaepee commented
> Is this T26 the T81? Or is this the Big anti material rifle.

Big anti-material. T-26

2022-01-23 02:05 UTC, novaepee commented
> Stop trying to shove another weapon into your SG sniper fantasy and wait for someone to make either a new sprite or go grab an old sprite or something, because it needs specialized balance instead of shoving something like this in, which will probably break balance.

Someone else asked me to code it, and somehow Bravemole approves.

2022-01-23 02:40 UTC, Pariah919 commented
>Someone else asked me to code it, and somehow Bravemole approves.
>
Bravemole approving doesn't fix the issue that you're shoving a weapon that is a power weapon into smartgunners hands for no real reason than "People don't use it very often".

I do PR's for others all the time, it doesn't block you from criticism.

The main issue the AMR has which makes people not use it is twofold-

-I overbuffed the autosniper and never got feedback until recently, but people nerfed it recently to be better, though I think it needs to be moved to .75.
-The lase is broken and doesn't work half the time.

Giving it to SG is absurd because it let's you stack 6 AMRs and kill people instantly, and if you rework it entirely you should just make an entirely different gun.

2022-01-23 02:48 UTC, KrabSpider commented
> > Stop trying to shove another weapon into your SG sniper fantasy and wait for someone to make either a new sprite or go grab an old sprite or something, because it needs specialized balance instead of shoving something like this in, which will probably break balance.
> 
> Someone else asked me to code it, and somehow Bravemole approves.

I never really asked. 😐

2022-01-23 03:36 UTC, SrSC0ndition commented
Why did you restrict niche req weapon even more, putting it solely into hands of SG? Thanks for another taken opportunity for no reason lol

2022-01-23 10:13 UTC, Mrrpip commented
But can't you stick a scope on the t-29 anyhow?

2022-01-23 17:56 UTC, BraveMole requested changes
I already said this need specialised balance, MJP is 100% right

2022-01-23 19:27 UTC, novaepee commented
> I already said this need specialised balance, MJP is 100% right

Waiting for L-Catcher to give me balance values.

2022-01-24 02:23 UTC, KrabSpider commented
> > I already said this need specialised balance, MJP is 100% right
> 
> Waiting for L-Catcher to give me balance values.

😐 
Just close the PR and buff the fire delay to 2 from 2.5. 

It doesnt need to be made roundstart, and I quite honestly played with the idea myself because I was seeking approval from Brave. 

If you're still going through with this; 
Decrease the mags given to 4. 
Decrease the sunder.

2022-01-24 17:44 UTC, hyper2snyper requested changes

2022-01-24 17:44 UTC, hyper2snyper commented on code/modules/projectiles/guns/specialist.dm
> +	name = "\improper T-26 Antimaterial sniper rifle"
```suggestion
	name = "\improper T-26 Antimaterial rifle"
```
antimat guns are sniper rifles by definition. this makes the name less long

2022-01-24 20:37 UTC, Kuro020 requested changes
Give it a new sprite, no reusing existing sprites

2022-01-28 21:44 UTC, closed without merging