Attempts to fix the holsters no one uses (again)
tgstation/TerraGov-Marine-Corps pull request #9382
Opened 2022-01-24 01:36 UTC by Notamaniac

## About The Pull Request

Stops the shotgun holsters and SMG holsters from showing an error sprite or just plain vanishing.

Closes #9096

## Why It's Good For The Game

For that rare specimen of a PO who uses their MR25 holster.

## Changelog
:cl:
fix: The sprites for the MR25 holster should work now. What, you didn't know we still had those?
/:cl:

2022-01-24 17:37 UTC, hyper2snyper requested changes

2022-01-24 17:37 UTC, hyper2snyper commented on code/game/objects/items/storage/large_holster.dm
> +	..()
```suggestion
	. = ..()
```

2022-01-24 17:37 UTC, hyper2snyper commented on code/game/objects/items/storage/large_holster.dm
>  	if(istype(user)) user.update_inv_back()
put these all under the same if().
dont need three identical ifs

2022-01-24 17:37 UTC, hyper2snyper commented on code/game/objects/items/storage/large_holster.dm
> +	. = ..()
```suggestion
	return ..()	
```

2022-01-26 15:41 UTC, Notamaniac commented
@hyper2snyper 
Done

2022-01-26 21:38 UTC, BraveMole approved these changes

2022-01-26 21:38 UTC, merged