Nerfs the Scout rifle impact bullet stats
tgstation/TerraGov-Marine-Corps pull request #9388
Opened 2022-01-24 07:46 UTC by lKiseki

## About The Pull Request
Per title. MJP does not give a shit despite me nagging about this for ages, so I took it upon myself to nerf this.

Stats have been changed as follows;
- Penetration reduced from 45 > 20. Seriously.
- Stagger removed. It already has slowdown and knockback.

## Why It's Good For The Game
TX-8 impact ammo has been really dumb for too long. Stagger, slowdown, and knockback on a gun with 25 damage, 45 penetration, and 5 sunder per bullet. I have no idea why MJP thought this was a healthy addition for the purposes of balance, but I vehemently disagree.

## Changelog
:cl: Lewdcifer
balance: TX-8 impact ammo; 45 > 20 pen, stagger removed.
/:cl:

2022-01-24 07:54 UTC, Pariah919 commented
```
MJP does not give a shit despite me nagging about this for ages
```
I didn't even realize the gun he was shooting you with if you're angry at me, and I said owned because I just saw someone die in a 1x1 closet, didn't really mean it offensively.
Other than that that's like, the only time of me being able to remember you complaining about this, and looking at your discord history that seems to line up.

Other than that, this sort of removes High Impacts entire gimmick of hilariously high pen and slowdown, but personally I'd drop it to 30 or 35 pen, and add penetration even if it is quite situational. I'd keep the knockback because it let's things get away decently easier, and keep the slowdown. That'd give it something over incend.

2022-01-24 15:25 UTC, BraveMole approved these changes
mjp said it was fine

2022-01-24 18:25 UTC, EvilMelonTheSecond commented
Do piercing bullets even have a niche? I'm having a hard time visualizing a scenario where 2 xeno line up to get shot by an automatic rifle. In the best cases you will hit an extra xeno 1-2 times per mag, not worth the trade at all in my opinion

2022-01-24 19:02 UTC, BraveMole approved these changes

2022-01-24 19:55 UTC, Lumipharon commented
As above, there is zero reason to actually buy this ammo with this change. Unless you're like, shooting a boiler behind a defender, I guess?

2022-01-25 20:05 UTC, KrabSpider commented
Maybe inverse the sunder on regular TX8 bullets and the impact mags and raise the damage to 30?

2022-01-27 01:58 UTC, hyper2snyper requested changes

2022-01-27 01:58 UTC, hyper2snyper commented on code/modules/projectiles/ammo_datums.dm
> +/datum/ammo/bullet/rifle/tx8//on_hit_mob(mob/M, obj/projectile/P)
```suggestion
/datum/ammo/bullet/rifle/tx8/on_hit_mob(mob/M, obj/projectile/P)
```

2022-01-30 00:23 UTC, merged