Light Marksman T64 bullet Buff
tgstation/TerraGov-Marine-Corps pull request #9479
Opened 2022-02-02 02:08 UTC by Redstonize

## About The Pull Request

As per title says. This bullet is for the T-64 BR exclusively. Currently, pretty underpowered, even with burst.

## Why It's Good For The Game

Makes the Battle Rifle bullets less underpowered. This will reward marines using the T-64 BR for it's higher magazine capacity over the T-37 DMR but has less damage, range and accuracy.  Burst fire is EQUIVALENT OR WORSE than using full auto. T-64 does NOT TAKE BFA.

## Changelog
:cl:
balance: Added 10 damage, 2 AP, 0.2 sundering to the Light Marksman Bullet for the T-64 BR (from 30 damage, 10 penetration, 1 sunder).
/:cl:

2022-02-02 02:17 UTC, Lumipharon commented
This makes it even better than prenerf though?
And the total delay in a burst is 0.65. So you're shooting 3 bullets faster than auto is shooting 2.

BFA is generally pretty shit as well due to how burst scatter works, it just used to be good on some guns due to a bug.

2022-02-02 02:21 UTC, Redstonize commented
Pref-nerf is using the DMR T-37 bullet, which has a lot more to it than what I'm proposing.
**Pref-nerf** means we're dealing with 65 damage, 15 AP, 2 sunder, which is a lot but got compensated in the old days by a "generic" **weapon damage quirk of -30%.**

2022-02-02 02:24 UTC, Lumipharon commented
> Pref-nerf is using the DMR T-37 bullet, which has a lot more to it than what I'm proposing. **Pref-nerf** means we're dealing with 65 damage, 15 AP, 2 sunder, which is a lot but got compensated in the old days by a "generic" **weapon damage quirk of -30%.**

It was a 50% damage multiplier, so it used to do 32.5 damage.
The extra delay was also increased from 0.15 to 0.35, so honestly if you think the gun needs the buff, that's the bit I would look at.

2022-02-02 03:08 UTC, KrabSpider commented
😐 I think removing the burst is perhaps the better solution?


Or...
____
Increase the AP to 15. 
Decrease the damage to 35 (or just dont buff it at all)
Decrease the burst delay to 0.05.

2022-02-02 03:37 UTC, Redstonize commented
Testing shows solution B: 
35 damage, 15 AP, 
0.05 burst delay
0.20 extra delay 
= better DPS on burst
That could work.

2022-02-02 05:12 UTC, KrabSpider commented
> 

Oh no no. I meant solution A as "if we remove the burst then perhaps the BR could be easier to balance and give its own niche as an answer to the laser's overcharge mode. It is hardly a marksman gun and just a glorified AR."

But yes. Good.

2022-02-03 23:56 UTC, BraveMole requested changes

2022-02-03 23:56 UTC, BraveMole commented on code/modules/projectiles/gun_system.dm
> +	AddComponent(/datum/component/automatedfire/autofire, fire_delay, burst_delay, _auto_burst_fire_shot_delay, burst_amount, gun_firemode, CALLBACK(src, .proc/set_bursting), CALLBACK(src, .proc/reset_f
```suggestion
	AddComponent(/datum/component/automatedfire/autofire, fire_delay, burst_delay, auto_burst_fire_shot_delay, burst_amount, gun_firemode, CALLBACK(src, .proc/set_bursting), CALLBACK(src, .proc/reset_fire), CALLBACK(src, .proc/Fire)) //This should go after handle_starting_attachment() and setup_firemodes() to get the proper values set.
```

2022-02-04 00:38 UTC, SplinterGP commented on code/datums/components/autofire.dm
> +	auto_burst_fire_shot_delay = _auto_burst_fire_shot_delay ? auto_burst_fire_shot_delay : 3 * auto_fire_shot_delay
```suggestion
	auto_burst_fire_shot_delay = _auto_burst_fire_shot_delay ? _auto_burst_fire_shot_delay : 3 * auto_fire_shot_delay
```

2022-02-04 00:38 UTC, SplinterGP commented on code/modules/projectiles/gun_system.dm
> +	AddComponent(/datum/component/automatedfire/autofire, fire_delay, burst_delay, auto_burst_fire_shot_delay, burst_amount, gun_firemode, CALLBACK(src, .proc/set_bursting), CALLBACK(src, .proc/reset_fi
```suggestion
	AddComponent(/datum/component/automatedfire/autofire, fire_delay, burst_delay, auto_burst_fire_delay, burst_amount, gun_firemode, CALLBACK(src, .proc/set_bursting), CALLBACK(src, .proc/reset_fire), CALLBACK(src, .proc/Fire)) //This should go after handle_starting_attachment() and setup_firemodes() to get the proper values set.
```

2022-02-04 03:23 UTC, Redstonize reviewed
Ok so now the guns are firing too fast, they also have an additional bullet on auto-burst.

2022-02-04 04:53 UTC, closed without merging