Refactors some plasmacutter behavior, squashes a number of plasmacutter bugs
tgstation/TerraGov-Marine-Corps pull request #9480
Opened 2022-02-02 04:13 UTC by RipGrayson

## About The Pull Request

Refactors plasmacutter behavior when used on walls, fixing a number of bugs (see changelog for details) and making the code more concise. Also addresses and fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/9468.

## Why It's Good For The Game

Bugs are bad, fixes good.

## Changelog
:cl:
fix: Plasmacutters now respect resistance flags and cannot destroy turfs that have RESIST_ALL or PLASMACUTTER_IMMUNE. 
fix: Plasmacutters no longer spam "can't cut through this" messages when destroying some closed turfs.
fix: Fixes a rare situation where plasmacutters would take multiple charges to cut down some ship walls.
refactor: Refactored plasmacutter behavior for closed turfs.
/:cl:

2022-02-02 09:18 UTC, TiviPlus requested changes

2022-02-02 09:18 UTC, TiviPlus commented on code/game/turfs/closed.dm
>  			return
istype src is bad

2022-02-02 09:18 UTC, TiviPlus commented on code/game/turfs/closed.dm
> +			ChangeTurf(/turf/open/floor/plating) //if none of the above apply regular plating as a fallback
yuck but not your fault

2022-02-03 14:27 UTC, TiviPlus requested changes

2022-02-03 14:27 UTC, TiviPlus commented on code/game/turfs/closed.dm
> +
there can only be one turf on a turf

2022-02-04 09:50 UTC, BraveMole requested changes

2022-02-04 09:50 UTC, BraveMole commented on code/game/turfs/closed.dm
> +		else if(isvolcanicturf(src))
No no no :).

you need to add a var to turfs (let's call it open_turf_type) 
and then you do ChangeTurf(open_turf_type)

2022-02-05 10:06 UTC, TiviPlus approved these changes

2022-02-05 10:11 UTC, BraveMole requested changes

2022-02-07 10:47 UTC, merged