Warrior lunge range qol
tgstation/TerraGov-Marine-Corps pull request #9486
Opened 2022-02-02 16:03 UTC by BraveMole

## About The Pull Request

Prevent from lunging if the target is too far

## Why It's Good For The Game

## Changelog
:cl:
qol: Prevent warrior from lunging if the target is too far
/:cl:

2022-02-02 16:26 UTC, Lefunny commented
pov: instead of fixing how horrible warrior lunge is they nerf it even more instead

2022-02-03 14:18 UTC, TiviPlus requested changes

2022-02-03 14:18 UTC, TiviPlus commented on code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
> +			to_chat(owner, span_xenonotice("You are too far!"))
shouldnt this 36 be a define

2022-02-04 01:05 UTC, Naaanii commented
Will it also prevent the lunge into corners but missing the target?

2022-02-04 09:46 UTC, BraveMole commented
> Will it also prevent the lunge into corners but missing the target?

no

2022-02-05 09:54 UTC, TiviPlus approved these changes

2022-02-05 09:55 UTC, merged