Sunder recovery by weeds, recovery pheromones, and resting weeds nerfed.
tgstation/TerraGov-Marine-Corps pull request #9491
Opened 2022-02-03 04:14 UTC by Pariah919

## About The Pull Request
Halved for all of these sources.

## Why It's Good For The Game
Sunder recovery is absurd, frankly. It's been powercreeped very high. Which makes anything but insanely high sources of it basically irrelevant.
This makes sunder for DPS a general mechanic, I want to cut down on sunder recovery powercreep, not increase it.

## Changelog
:cl:
balance: sunder bonuses for resting, recovery weeds and pheromones halved.
/:cl:

2022-02-03 04:19 UTC, Mechanelize commented
sunder is extreme pain for any tank xeno (george)

2022-02-03 04:21 UTC, SplinterGP commented
thats the point of it

2022-02-03 06:45 UTC, novaepee commented
get primo drone now before xeno winrate dunks

2022-02-03 07:51 UTC, SplinterGP commented on code/modules/mob/living/carbon/xenomorph/life.dm
> +		sunder_recov *= 1.5
tbh i think the resting one could just be removed overall, since i think sunder healing SHOULNDT be par on par with normal healing

2022-02-03 11:41 UTC, Lefunny commented
Sunder is already a pain in ass for almost every xeno since time to rest inst something with you always have, hivelords arent that used and a shitton of guns does this sort of damage

2022-02-03 20:45 UTC, BraveMole requested changes
You are not telling why sunder being relevant again would be any good for the game

2022-02-03 21:35 UTC, Araulius commented
> You are not telling why sunder being relevant again would be any good for the game

I'll give you a reason.

It gives underused tools relevance. rail gun, slugs, and t-29's.

if sunder becomes too much of an issue, perhaps beno HP should be increased. this would both add xeno ability to last under fire a bit more, and doubly increase the need for sunder tools. Double down on making sunder relevant. make tanki benos scary without using these tools.

2022-02-03 21:40 UTC, SplinterGP commented
> You are not telling why sunder being relevant again would be any good for the game

it not being relevant is also bad for the game, considering its a balance value of guns and is intended to make xenos just not heal and go back into battle immediately, giving marines breath room.

2022-02-04 01:18 UTC, Lefunny commented
> > You are not telling why sunder being relevant again would be any good for the game
> 
> it not being relevant is also bad for the game, considering its a balance value of guns and is intended to make xenos just not heal and go back into battle immediately, giving marines breath room.

marines actually can heal while walk, any sort of real heal for xenos need rest with takes time and makes the xeno unable to move himself, marines actually got enough time to breath since we also got a ratio of 1:3 xenos to marines

2022-02-04 04:14 UTC, closed without merging