Adds dispenser, take two
tgstation/TerraGov-Marine-Corps pull request #9501
Opened 2022-02-03 22:35 UTC by SplinterGP

## About The Pull Request
Adds a Dispenser for the engineer, currently it ~heals~(salves and bandages, direct heals robotic limbs) nearby humans and allows them to carry alot of items in, might make it do other stuff on future, its equipped on backpack slot
![image](https://user-images.githubusercontent.com/29824735/152324370-17e2444c-23d9-4dab-8269-55162c05b5ec.png)

## Why It's Good For The Game
Lets engineers drag around alot of items with them without being immediately accessible and also gives them a small healing utility(similar to tricordrazine but only burn and brute).

## Changelog
:cl:
add: Added the engineer dispenser which is equipped on back slot and carries alot of items, can only heal and access items when deployed
imageadd: new title screen announcing the new engineer dispenser
/:cl:

2022-02-03 22:35 UTC, SplinterGP commented
![image](https://user-images.githubusercontent.com/29824735/152440712-b28c80a8-88b6-4b61-8e27-77959300a94a.png)

2022-02-04 01:31 UTC, Luxyboo commented
id say this would be pretty good for when primos are fully in.

2022-02-04 05:03 UTC, ilikesaying commented
Engineers start receiving empty welders and yellow pipe cleaners after the new dispensers are out

2022-02-04 14:26 UTC, ZahaSanko commented
where credit

2022-02-04 16:37 UTC, iLikeMemes commented
If you didnt know there is actually a game called TerraTech, I highly doubt this will cause any kind of copyright shenanigans but just a heads up. (https://store.steampowered.com/app/285920/TerraTech/) besides that, based PR

2022-02-06 19:54 UTC, TiviPlus requested changes
Remove the salving, robot heal is ok

Also please remove the following copyrighted/trademarked content
- Valve/TF2 poster
- Terratech references (if these are on sprites/code)

2022-02-06 19:54 UTC, TiviPlus commented on code/__DEFINES/equipment.dm
> +#define DEPLOYED_NO_PICKUP  (1<<17) //Disables deployed item pickup
why indent

2022-02-06 19:54 UTC, TiviPlus commented on code/game/objects/items/storage/backpack.dm
> +	var/list/affecting_list
autodoc

2022-02-06 19:54 UTC, TiviPlus commented on code/game/objects/items/storage/backpack.dm
> +/obj/item/storage/backpack/dispenser/proc/deploy()
ditto, do the rest as well

2022-02-06 19:54 UTC, TiviPlus commented on code/game/objects/items/storage/backpack.dm
> +			continue
>view
>checks view again

2022-02-06 19:54 UTC, TiviPlus commented on code/game/objects/items/storage/backpack.dm
> +		RegisterSignal(turfs, COMSIG_ATOM_ENTERED, .proc/entered_tiles)
range_turf and AS

2022-02-06 19:54 UTC, TiviPlus commented on code/game/objects/items/storage/backpack.dm
> +	affecting_list -= source
Signal handlers are missing

2022-02-06 19:54 UTC, TiviPlus commented on code/game/objects/items/storage/backpack.dm
> +	return ..()
early return

2022-02-06 19:54 UTC, TiviPlus commented on code/game/objects/items/storage/backpack.dm
> +		density = FALSE
both early return and autodoc

2022-02-06 19:54 UTC, TiviPlus commented on code/game/objects/items/storage/backpack.dm
> +/obj/item/storage/backpack/dispenser/proc/entered_tiles(datum/source, mob/living/carbon/human/entering)
bla bla autodoc im not gonna do it for the rest

2022-02-07 10:27 UTC, Pill-U commented
How do you get one? I'd assume from engi prep / req but I don't see it

2022-02-08 00:24 UTC, novaepee commented
If this gets merged, I might just make this a title painting.

2022-02-08 00:26 UTC, SplinterGP commented
> If this gets merged, I might just make this a title painting.

already made

2022-02-08 00:29 UTC, SplinterGP commented on code/game/objects/items/storage/backpack.dm
> +			continue
```suggestion
```

2022-02-08 00:29 UTC, SplinterGP commented on code/game/objects/items/storage/backpack.dm
> +	affecting_list -= source
```suggestion
/obj/item/storage/backpack/dispenser/proc/on_affecting_qdel(datum/source)
	SIGNAL_HANDLER
	affecting_list -= source
```

2022-02-08 00:31 UTC, SplinterGP commented on code/game/objects/items/storage/backpack.dm
> +	return ..()
```suggestion
	if(CHECK_BITFIELD(flags_item, IS_DEPLOYED) && !CHECK_BITFIELD(flags_item, IS_DEPLOYING))
		return ..()
	if(!can_interact(user))
		return
	balloon_alert_to_viewers("Undeploying...")

	icon_state = "dispenser"
	flick("dispenser_undeploy", src)
	ENABLE_BITFIELD(flags_item, IS_DEPLOYING)
	for(var/turf/turfs in range(2, src))
		UnregisterSignal(turfs, COMSIG_ATOM_ENTERED)
	for(var/mob/living/carbon/human/affecting AS in affecting_list)
		qdel(affecting_list[affecting])
		UnregisterSignal(affecting, COMSIG_PARENT_QDELETING)
	affecting_list = null
	STOP_PROCESSING(SSobj, src)
	addtimer(CALLBACK(src, .proc/undeploy), 4.2 SECONDS)
```

2022-02-08 00:32 UTC, SplinterGP commented on code/game/objects/items/storage/backpack.dm
> +		DISABLE_BITFIELD(flags_item, IS_DEPLOYING)
```suggestion
/obj/item/storage/backpack/dispenser/proc/undeploy()
	if(CHECK_BITFIELD(flags_item, IS_DEPLOYED))
		return
	density = FALSE
	anchored = FALSE
	DISABLE_BITFIELD(flags_item, IS_DEPLOYED)
	DISABLE_BITFIELD(flags_item, IS_DEPLOYING)
```

2022-02-08 00:33 UTC, SplinterGP commented on code/__DEFINES/equipment.dm
> +	#define IS_DEPLOYING (1<<16) //If this is on an item, said item is currently deploying
```suggestion
#define IS_DEPLOYING (1<<16) //If this is on an item, said item is currently deploying
```

2022-02-08 00:36 UTC, SplinterGP commented
>     * Terratech references (if these are on sprites/code)

Nope, those are just on the comment for funs.

2022-02-08 00:36 UTC, SplinterGP commented
will do autodoc soon

2022-02-10 16:56 UTC, TiviPlus commented
![image](https://user-images.githubusercontent.com/57223640/153457179-fcd8b53a-ff0e-439f-a82a-65286cfbdbea.png)

2022-02-10 21:23 UTC, BraveMole requested changes

2022-02-10 21:23 UTC, BraveMole commented on code/__DEFINES/equipment.dm
> +#define IS_DEPLOYING (1<<16) //If this is on an item, said item is currently deploying
should be a trait

2022-02-10 21:23 UTC, BraveMole commented on code/game/objects/items/storage/backpack.dm
> +
.

2022-02-10 21:23 UTC, BraveMole commented on code/game/objects/items/storage/backpack.dm
> +	///list of stuff we're currently affecting in our area.
of stuff? Need a cast

2022-02-10 21:23 UTC, BraveMole commented on code/game/objects/items/storage/backpack.dm
> +	icon_state = "dispenser_deployed"
should be done in update_icon_state

2022-02-10 21:23 UTC, BraveMole commented on code/game/objects/items/storage/storage.dm
> +	for(var/mob/M in content_watchers)
AS

2022-02-11 21:52 UTC, SplinterGP commented on code/game/objects/items/storage/storage.dm
> +	for(var/mob/M in content_watchers)
```suggestion
	for(var/mob/M AS in content_watchers)
```

2022-02-12 16:16 UTC, TiviPlus requested changes

2022-02-12 16:16 UTC, TiviPlus commented on code/game/objects/items/storage/backpack.dm
> +
cast this and define "stuff" above

2022-02-12 16:16 UTC, TiviPlus commented on code/game/objects/items/storage/backpack.dm
> +	if(check_blocked_turf(deploy_location))
no parentcall?

2022-02-20 01:17 UTC, theta006 commented
PR going stale i cry

2022-02-23 03:17 UTC, SplinterGP commented
going to unstale it soon, just got busy with some stuff

2022-02-27 00:37 UTC, closed without merging