Makes autoburst extra (extra) delay a var
tgstation/TerraGov-Marine-Corps pull request #9509
Opened 2022-02-04 04:35 UTC by Lumipharon

## About The Pull Request
Currently autoburst serves no purpose other than to lower your dps in exchange for less carpal tunnel, as it adds a significant extra delay multiplier between bursts.

This PR adds a multiplier var that can be configured on guns to change this extra delay, so guns can get this tweaked to make it actually useful.

## Why It's Good For The Game
Autoburst might have a reason to exist.

## Changelog
:cl:
add: new var to control autoburst extra (extra) delay
/:cl:

2022-02-04 04:46 UTC, Lumipharon commented
@BraveMole what are you thoughts on changing the default value here? x3 delay is bizarre, x1 makes it a better autofire in most cases, but you've said before 'clicking faster shouldn't give you an advantage'?

2022-02-04 09:39 UTC, BraveMole requested changes

2022-02-04 09:39 UTC, BraveMole commented on code/datums/components/autofire.dm
> +	auto_burst_fire_shot_delay = _auto_burst_fire_shot_delay * auto_fire_shot_delay
not a fan of this solution, this is less modular than having a value independant of auto_fire_shot_delay.

It's not that bad though, but in that case you need to rename the argument _auto_burst_fire_shot_delay into like auto_burst_fire_shot_multiplicator or something

2022-02-04 09:39 UTC, BraveMole commented on code/datums/components/autofire.dm
> +	auto_burst_fire_shot_delay = _auto_burst_fire_shot_delay
if you don't allow for a direct set in the constructor, it seems weird to allow it here

2022-02-04 09:39 UTC, BraveMole commented on code/modules/projectiles/gun_system.dm
> +	var/autoburst_delay = 3
if it's a multiplier, change the name accordingly

2022-02-04 13:58 UTC, Losenis commented
>x3 delay is bizarre, x1 makes it a better autofire in most cases, but you've said before 'clicking faster shouldn't give you an advantage'?

If I knew code I'd have rather changed the default value to 2 while also creating a var that changes normal burst delay also to 2. This'd probably make tx11 autoburst better than full auto, but that's kind of the point of the gun so it'd be reasonable for it. Yet to do the math on the T12 and T18 dps on either mode.

2022-02-04 22:20 UTC, Lumipharon commented
Made the var a fixed amount instead of a multiplier.
Made the default x2 instead of x3 firedelay.

2022-02-04 23:52 UTC, BraveMole requested changes

2022-02-04 23:52 UTC, BraveMole commented on code/modules/projectiles/gun_system.dm
> +	var/autoburst_delay = null
```suggestion
	var/autoburst_delay = 0
```

2022-02-05 06:54 UTC, Lumipharon commented
@BraveMole should be set now.

2022-02-05 10:23 UTC, TiviPlus approved these changes

2022-02-08 00:15 UTC, BraveMole approved these changes

2022-02-08 00:15 UTC, merged