Hypospray has 30u mode and QoL with amount per transfer menu
tgstation/TerraGov-Marine-Corps pull request #9518
Opened 2022-02-05 00:32 UTC by novaepee

## About The Pull Request

Title.

## Why It's Good For The Game

It's kinda wack that hypospray, for all its advancement, doesn't have a 30u option. Also, adjust the set transfer menu on hypospray to make it a LOT easier to choose what you want. QoL over ordinal sense.

## Changelog
:cl:
add: Hypospray has 30u for set transfer reagent
qol: amount per transfer in hypospray menu
/:cl:

2022-02-05 00:32 UTC, novaepee commented
![image](https://user-images.githubusercontent.com/6610922/152620709-a7443a49-44d1-4df8-9ce9-b6fc9d92f06d.png)

2022-02-05 09:59 UTC, TiviPlus requested changes

2022-02-05 09:59 UTC, TiviPlus commented on code/game/objects/items/reagent_containers/hypospray.dm
> +		var/N = tgui_input_list(usr, "Amount per transfer from this:", "[src]", list(15, 30, 1, 3, 5, 10, 20, 25))
use a proper order instead of this arbitrary set

2022-02-05 13:46 UTC, Losenis commented
Now all I need is a 60u option and I'll finally stop getting carpal tunnel when I'm healing people off a medvendor's reagent bottles

2022-02-06 12:46 UTC, TiviPlus approved these changes

2022-02-06 12:47 UTC, merged