Remove stored egg from carrier's game panel
tgstation/TerraGov-Marine-Corps pull request #9535
Opened 2022-02-06 00:02 UTC by novaepee

## About The Pull Request

Title.

## Why It's Good For The Game

Carrier doesn't have ability to store eggs anymore. This is a relic of an old time.

## Changelog
:cl:
del: Remove stored egg from carrier's game panel
/:cl:

2022-02-06 00:03 UTC, novaepee commented
![image](https://user-images.githubusercontent.com/6610922/152663078-3ddfb1ee-fefe-486a-b8d4-874cb001eb11.png)

2022-02-06 19:40 UTC, BraveMole requested changes

2022-02-06 19:40 UTC, BraveMole commented on code/modules/mob/living/carbon/xenomorph/castes/carrier/carrier.dm
> -		stat("Stored Eggs:", "[LAZYLEN(eggs_cur)] / [xeno_caste.eggs_max]")
why does eggs_max exist, why does eggs_cur exist?

2022-02-07 00:27 UTC, novaepee commented on code/modules/mob/living/carbon/xenomorph/castes/carrier/carrier.dm
> -		stat("Stored Eggs:", "[LAZYLEN(eggs_cur)] / [xeno_caste.eggs_max]")
No idea, can delete them.

2022-02-08 10:24 UTC, BraveMole approved these changes

2022-02-08 10:24 UTC, merged