Fix autofire akimbo
tgstation/TerraGov-Marine-Corps pull request #9565
Opened 2022-02-07 22:04 UTC by Lumipharon

## About The Pull Request
When firing guns akimbo, there is an extra fire delay associated with it that means you shoot a bit slower. It turns out that while this works for semi autofiring (i.e. revolver memes) autofiring while akimbo simply ignores the extra fire delay akimbo has.
Makes autofire actually respect the akimbo_additional_delay var.

## Why It's Good For The Game
Akimbo additional delay now actually works. This has balance implications for guns that are used akimbo with autofire :^)

## Changelog
:cl:
fix: Autofiring while akimbo now actually shots slower like it should
/:cl:

2022-02-08 10:14 UTC, BraveMole requested changes
akimbo_additional_delay is a multiplier

2022-02-08 19:50 UTC, Lumipharon commented
> akimbo_additional_delay is a multiplier

I realised this yesterday, but testing is weird.
If it was adding 0.5, delay it should be 0.65 (like a dmr) but it definitely isn't that slow. It does however seem to shoot slower than one handed... code, how do you work.

2022-02-08 22:19 UTC, BraveMole requested changes

2022-02-08 22:19 UTC, BraveMole commented on code/modules/projectiles/gun_system.dm
> +		modify_fire_delay(-(fire_delay - fire_delay/(1 + akimbo_additional_delay))) // Removes the additional delay from auto_fire
```suggestion
		modify_fire_delay(-fire_delay + fire_delay/(1 + akimbo_additional_delay)) // Removes the additional delay from auto_fire
```

2022-02-08 23:27 UTC, BraveMole requested changes
ok for 0,2 for t90, but what about the other rifles/mg? they should stay at zero, it's not like they are any good

2022-02-08 23:52 UTC, Lumipharon commented
> ok for 0,2 for t90, but what about the other rifles/mg? they should stay at zero, it's not like they are any good

Default is still 0.5, but does anyone actually use any rifles akimbo? You need RC + Gyro to fire straight, and you still have terrible accuracy.
I'm happy to add lower values in case people do though.

2022-02-10 16:53 UTC, TiviPlus commented on code/modules/projectiles/gun_system.dm
> +		modify_fire_delay(-fire_delay + fire_delay/(1 + akimbo_additional_delay)) // Removes the additional delay from auto_fire
```suggestion
	if(dual_wield)
		modify_fire_delay(-fire_delay + fire_delay/(1 + akimbo_additional_delay)) // Removes the additional delay from auto_fire
```

2022-02-10 20:33 UTC, Lumipharon commented on code/modules/projectiles/gun_system.dm
> +		modify_fire_delay(-fire_delay + fire_delay/(1 + akimbo_additional_delay)) // Removes the additional delay from auto_fire
Neat

2022-02-10 20:59 UTC, BraveMole approved these changes

2022-02-10 20:59 UTC, merged