Alters X-ray rifle to swap modes with unique action
tgstation/TerraGov-Marine-Corps pull request #9638
Opened 2022-02-13 17:43 UTC by Losenis

## About The Pull Request
Gives X-ray rifle the ability to swap modes with unique action rather than using a radial menu.

## Why It's Good For The Game
The rifle had 2 modes, so if you wanted to swap you'd switch to the other mode rather than picking from >2 like the laser pistol. Now hitting spacebar will swap modes on the fly, which for the xray rifle is very important due to the ability to change to a mode that ignores walls.

https://cdn.discordapp.com/attachments/606917654812295190/942475801717248030/2022-02-13_14-37-03.webm
![image](https://user-images.githubusercontent.com/72712909/153767285-05738219-f439-42ee-97ec-973e2f4742a8.png)

## Changelog
:cl:
add: X-Ray laser rifle can now swap modes on the fly with Unique Action (default: spacebar)
/:cl:

2022-02-13 17:47 UTC, Luxyboo commented
pretty cool, you think you can do this with the other las guns?

2022-02-13 18:00 UTC, hyper2snyper commented
Don't make a new proc, just make the other lasgun code switch between the options when the firemode list is 2

2022-02-13 18:59 UTC, Losenis commented
Tell splinter that, he's the guy that helped me because I didn't know how to do that

2022-02-14 09:45 UTC, Araulius commented
Oh *please* merge this, it would make the thing so much more viable.

2022-02-14 10:37 UTC, TiviPlus requested changes

2022-02-14 10:37 UTC, TiviPlus commented on code/modules/projectiles/guns/energy.dm
> +	SEND_SIGNAL(src, COMSIG_GUN_BURST_SHOTS_TO_FIRE_MODIFIED, burst_amount)
This code has major issues ping me on discord about it

2022-02-21 23:29 UTC, TiviPlus commented
Author was made aware of issues in disc, did not adress, closing as stale

2022-02-21 23:29 UTC, closed without merging