Makes plasma pistol attachment shoot only while wielded
tgstation/TerraGov-Marine-Corps pull request #9666
Opened 2022-02-19 03:50 UTC by 2whatever2

## About The Pull Request
This doesn't stop the plasma pistol from normally shooting in it's unattached version. I also stole this code from #9316 thanks to Notamaniac for making this.

https://user-images.githubusercontent.com/24631139/154784939-9b6d6ea2-b345-4728-a9c4-67ff3579ef27.mp4

(tested the code anyway so I don't perish)

## Why It's Good For The Game
A less nuclear option than #9664 as shotguns aren't really the main problem here, it's mostly underattachments as a whole not having a clear indication that the gun possesses them, blindsiding xenos with surprise ugl impacts or ubf/masterkey, but the big difference between these under attachments and plasmapistol is that they need to be fully wielded to actually start shooting, giving xenos that are more hit and run a moment to leave. (runners, hunters etc.) Most stuns are only for 2 seconds, making marines with synaptazine instantly get up and shoot their plasma pistol attachment, while prepping up for another volley/burst punishing you even if you used your tools well.

## Changelog
:cl:
balance: Plasma pistol can no longer shoot onehanded while attached to a gun. Note that this doesn't prevent from plasma pistol shooting one-handed while unattached.
/:cl:

2022-02-19 10:23 UTC, TiviPlus requested changes

2022-02-19 10:23 UTC, TiviPlus commented on code/modules/projectiles/guns/pistols.dm
> +	. = ..()
use return ..() instead of . = ..() at the end of procs and use the proper bitfield toggles

2022-02-19 23:04 UTC, Notamaniac commented on code/modules/projectiles/guns/pistols.dm
> +	. = ..()
- 
```suggestion
	if(!CHECK_BITFIELD(flags_gun_features,GUN_WIELDED_FIRING_ONLY))
		TOGGLE_BITFIELD(flags_gun_features,GUN_WIELDED_FIRING_ONLY)
	return ..()
```

2022-02-19 23:06 UTC, Notamaniac commented on code/modules/projectiles/guns/pistols.dm
> +	. = ..()
```suggestion
	if(CHECK_BITFIELD(flags_gun_features,GUN_WIELDED_FIRING_ONLY))
		TOGGLE_BITFIELD(flags_gun_features,GUN_WIELDED_FIRING_ONLY)
	return ..()
```

2022-02-21 22:35 UTC, TiviPlus approved these changes

2022-02-21 23:17 UTC, merged