Entrenching Tools can now be saved in loadouts and will not pick up snow piles while folded.
tgstation/TerraGov-Marine-Corps pull request #9716
Opened 2022-03-01 00:46 UTC by Arctrooper8

## About The Pull Request

Fixes #7317 https://github.com/tgstation/TerraGov-Marine-Corps/issues/7317
This is accomplished by making shovels start folded, I made sure to test for any unintended side effects and found none but I did find a new bug: 
A folded shovel can pick up a snow pile, not the snow on the ground but the snow pile item itself. This bug has also been fixed with an if else check in the snow file.

## Why It's Good For The Game

Bugfixes are always good.

## Changelog
:cl:
fix: Entrenching tools now start folded and as such will now save in loadouts.
fix: Folded Entrenching tools can no longer pick up snow piles.
/:cl:

2022-03-01 02:46 UTC, Luxyboo commented
make it so i dont have to shovel 5 snow tiles for a single cade

2022-03-01 03:05 UTC, Arctrooper8 commented
> make it so i dont have to shovel 5 snow tiles for a single cade

That'd have to be a different PR but not a bad idea, especially with snow being limited sometimes. Unlike the magic let me pull 100 dirt from one tile big red and LZ ground. Filling sandbags honestly makes them super situational.

2022-03-01 18:31 UTC, TiviPlus requested changes
in future please split fixes so that its faster and easier to review

2022-03-01 18:31 UTC, TiviPlus commented on code/game/objects/items/stacks/snow.dm
> +			to_chat(user, span_warning("You must unfold your shovel first!"))
use early returns

2022-03-02 00:03 UTC, Arctrooper8 commented
It now uses an early return. And in the future I shall atomize even further with fixes.

2022-03-02 01:29 UTC, Arctrooper8 commented
> make it so i dont have to shovel 5 snow tiles for a single cade

https://github.com/tgstation/TerraGov-Marine-Corps/pull/9719 Tada, thanks for the idea.

2022-03-03 19:39 UTC, TiviPlus approved these changes

2022-03-03 19:39 UTC, merged