Better snow digging and related minor vending QOL
tgstation/TerraGov-Marine-Corps pull request #9719
Opened 2022-03-02 01:28 UTC by Arctrooper8

## About The Pull Request

Right now every other diggable tile in game can give you an infinite amount of dirt to fill your sandbags with. However on the ice planets you have to dig 5 snow layers to make one sandbag cade (and often times most snow is shallow). This makes it easier and less annoying to fill sandbags on ice planets while making sure there aren't any snow duplication silliness. Snow cades now also require 5 snow as part of this.

Shovels themselves along with signalers are now free and in infinite numbers in the utility. Extinguishers have also been moved there as is befitting their role of tool. And jetpacks have been moved to specialized as it better suits their limited number status and relatively combat focused role.
 
Minor reorganizations to utility and engi vend. 
![new utility](https://user-images.githubusercontent.com/95723150/156277039-4da9d887-3a20-4d96-9f1b-724629653b58.png)
![Engi reorg](https://user-images.githubusercontent.com/95723150/156277134-58a199f2-d81b-4f75-84e2-21645587a568.png)

## Why It's Good For The Game

Right now every other diggable tile in game can give you an infinite amount of dirt to fill your sandbags with. However on the ice planets you have to dig 5 snow layers to make one sandbag cade (and often times most snow is shallow). This makes it easier and less annoying to fill sandbags on ice planets while making sure there aren't any snow duplication silliness. Snow cades now also require 5 snow as part of this.

It's silly that a shovel and simple signaling device (which already has 20 in vendor and is only used with detpacks) are in limited supply. And extinguishers and jetpack just logically look better when swapped.

The minor reorganization just puts things together that are logically similar (flashlight with flare gun, knives in one spot, extinguishers in another, and things nobody uses at the bottom). For example notice how all the wall removing stuff is in one place: 
![kaboom](https://user-images.githubusercontent.com/95723150/156277239-51a22a50-ddd4-4864-85a2-5f7d88452063.png)

## Changelog
:cl:
qol: shovels and signalers are now free and infinite under the reorganized utility tab along with newly moved extinguishers.
balance: Digging up snow now gives a 5 stack of snow like all other dig tiles, snow cades now also need five to be built.
/:cl:

2022-03-02 01:48 UTC, Luxyboo commented
you have my respect for actually coding it and not telling me "wyci"

2022-03-06 08:51 UTC, TiviPlus requested changes
"Reorganization changes" have balance changes remove them

2022-03-06 11:07 UTC, Arctrooper8 commented
> "Reorganization changes" have balance changes remove them

Do you mean me moving extinguishers? Me just moving stuff in the loadout vendors lists? Or the shovels and signalers? That sentence isn't very clear.

2022-03-07 06:40 UTC, TiviPlus approved these changes

2022-03-07 06:41 UTC, merged