Minor module tweaking and description updates.
tgstation/TerraGov-Marine-Corps pull request #9732
Opened 2022-03-06 19:04 UTC by Arctrooper8

## About The Pull Request

Right now a lot of modules reference Jaeger despite the fact they also work with Xenonauten. Some of their descriptions are misleading with the weight section in particular having no standard. So I changed them while working on another PR, but because atomization is good I have split this part up. This is also a good place for discussion of the changes. 

As for the actual module changes:
Surt is no longer a death trap. now having .2 slowdown instead of .4 and having the ridiculous light range debuff removed.
Valk has .05 more slowdown, because even numbers are nice and it's pretty good.
And finally the friendly fire module now has laser armour due to their new prevalence throughout marines ranks. That's not all though, it also has a new name so it matches the other norse god themed armours.
Vör (the careful one) is a goddess associated with wisdom. It's quite a careful action to bring extra armour against your own allies (but in this case it's quite smart considering the marines). 

## Why It's Good For The Game

Better descriptions make clear where a module goes, what it does and if it needs anything (Mimir mask and helmet module), and how it will affect you (slowdown standards, ex: 0.2 = "Will impact mobility"). 

Right now the Surt is a death trap, first off it has a strange light range debuff that no other module has. An ancient PR says it was fair because the flames make light but in terms of actually debuffing it's just annoying and not a hinderance. As for the speed, .4 is way too much for a module that only protects you from fire. When other modules such as hlin only have .2 slowdown yet practical immunity to explosions it makes you wonder why Surt is so heavily targeted. Flamethrowers are annoying but xenos have resin and acid well, besides if flamethrowers are too powerful they should be nerfed and not the armour.
Valk slowdown nerf is mostly just to get a nice even number, I can round down if maintainers want. Besides, it's not like .05 will ruin the incredible usefulness of the valk.
Seeing as to how prevalent laser weapons are between marines, a good argument can be made to grant the friendly fire module laser armour. Xenos have no laser attacks so this shouldn't be any issue.
And giving it a cool name just brings it on the same level as other neat modules such as Hlin or Mimir.

## Changelog
:cl:
add: standardizes, modernizes, and improves all the module descriptions. Friendly Fire module has a new name!
balance: Minor module stat tweaking 
/:cl:

2022-03-06 19:09 UTC, revelation-8468 commented
hehe vor(e) module

2022-03-06 19:11 UTC, Arctrooper8 commented
> hehe vor(e) module

God damn it

2022-03-07 21:34 UTC, TiviPlus requested changes
A) Surt rebalance is in the same PR as desc and name changes??
B) do not rename the ballistic armor typepath for loadout reasons
C) Puck some other name not Vor choose like Hodr

2022-03-08 01:50 UTC, Arctrooper8 commented
> A) Surt rebalance is in the same PR as desc and name changes?? B) do not rename the ballistic armor typepath for loadout reasons C) Puck some other name not Vor choose like Hodr

Will do all of those things! Surt will be seperate PR, will get a new god (Stupid vore joke) and I will not change the typepath.

2022-03-08 23:06 UTC, Arctrooper8 commented
> A) Surt rebalance is in the same PR as desc and name changes?? B) do not rename the ballistic armor typepath for loadout reasons C) Puck some other name not Vor choose like Hodr

All complete! Here is the new PR: https://github.com/tgstation/TerraGov-Marine-Corps/pull/9745

2022-03-09 08:47 UTC, TiviPlus approved these changes
rest ok

2022-03-09 08:47 UTC, TiviPlus commented on code/modules/clothing/modular_armor/attachments/modules.dm
> +	slowdown = 0.2 //Something this useful needs a downside.
```suggestion
	slowdown = 0.2
```

2022-03-09 23:48 UTC, Arctrooper8 commented
> rest ok

Committed your suggestion, ready to merge!

2022-03-10 08:11 UTC, merged