Porting CM 2x1 door sprites
tgstation/TerraGov-Marine-Corps pull request #9761
Opened 2022-03-11 06:40 UTC by novaepee

## About The Pull Request

More mapping options! Thanks to this CM PR for the sprites: https://gitlab.com/cmdevs/colonial-warfare/-/merge_requests/2701

Open source, baby.

## Why It's Good For The Game

It's for the mappers that want to have more spice into their life, including me. I'm doing this so that RipGrayson can make Big Red have like 10000 variances.

## Changelog
:cl: novaepee, RipGrayson
imageadd: more door sprites from CM!
/:cl:

2022-03-11 06:42 UTC, novaepee commented on code/game/objects/machinery/doors/multi_tile.dm
> +	icon = 'icons/obj/doors/mainship/2x1secdoor_glass.dmi'
In the port, CM's 2x1secdoor_glass.dmi is 95% the same as TGMC's 2x1secdoor.dmi **BUT** CM's 2x1secdoor.dmi is very different. I had to change this and pray no mistakes in porting were made.

2022-03-11 06:42 UTC, novaepee commented on code/game/objects/machinery/doors/multi_tile.dm
> +	icon = 'icons/obj/doors/mainship/2x1secdoor_glass.dmi'
![image](https://user-images.githubusercontent.com/6610922/157816112-3d1bf8c6-71bb-4545-9f47-6304fd33bb75.png)

Only these maps are affected.

2022-03-12 01:53 UTC, novaepee commented
![image](https://user-images.githubusercontent.com/6610922/157999176-ed57cf7a-f912-44b0-983f-f07e3a182a9d.png)

Pictures. forgot to show.

2022-03-12 16:17 UTC, Kuro020 approved these changes

2022-03-12 18:34 UTC, TiviPlus requested changes
Where are the typepaths for these

2022-03-13 00:35 UTC, novaepee commented
> Where are the typepaths for these

Right now, I'm only porting sprites. If you want me to make doors for these, I'm willing to do so.

2022-03-13 20:10 UTC, TiviPlus requested changes

2022-03-13 20:10 UTC, TiviPlus commented on code/game/objects/machinery/doors/multi_tile.dm
> +	icon = 'icons/obj/doors/mainship/2x1almayerdoor_glass.dmi'
A) dont use numbers in typepaths
B) Why is the base glass

2022-03-13 20:10 UTC, TiviPlus commented on code/game/objects/machinery/doors/multi_tile.dm
> +	glass = TRUE
this is inherited

2022-03-13 20:10 UTC, TiviPlus commented on code/game/objects/machinery/doors/multi_tile.dm
> +
you dont even set the icon/iconstates here go do it properly im not reviewing this

2022-03-30 20:13 UTC, novaepee commented
![image](https://user-images.githubusercontent.com/6610922/160920676-296583c6-af19-4d37-b57c-99fa2870a541.png)
Theseus with new general prep door.

![image](https://user-images.githubusercontent.com/6610922/160920866-ace26923-44d2-4e53-846b-991fbb3c8dd9.png)
Minerva engineering

![image](https://user-images.githubusercontent.com/6610922/160922712-c342df80-9f7f-4e78-ad9b-3117aa16adcf.png)
Minerva firing range

![image](https://user-images.githubusercontent.com/6610922/160922797-c930e0e5-e5d9-4555-ad27-d65ac59eb273.png)
Pillar of Spring firing range and prep

2022-04-08 03:09 UTC, merged