Fixes invisible balloon alerts
tgstation/TerraGov-Marine-Corps pull request #9817
Opened 2022-03-19 23:16 UTC by RipGrayson

## About The Pull Request

They were invisible under 99% of circumstances, addresses https://github.com/tgstation/TerraGov-Marine-Corps/issues/9735.

## Why It's Good For The Game

Fixes good, apparently a ton of feedback relying on balloon_alert is currently missing because of this bug.

## Changelog
:cl:
fix: Fixed balloon alerts being invisible.
/:cl:

2022-03-20 02:07 UTC, Lumipharon commented
Thank you for fixing this, I didn't know enough about planes to know where to start.

2022-03-21 09:01 UTC, TiviPlus requested changes
A) planes use integers
B) Backpacking on another plane is not the correct fix, as I believe I already told you the cause was no plane master for balloon alerts

2022-03-22 10:36 UTC, TiviPlus requested changes

2022-03-22 10:36 UTC, TiviPlus commented on code/_onclick/hud/rendering/plane_master.dm
> +	appearance_flags = PLANE_MASTER
```suggestion
/obj/screen/plane_master/balloon_chat
	name = "balloon alert plane"
	plane = BALLOON_CHAT_PLANE
	render_relay_plane = RENDER_PLANE_NON_GAME
```

2022-03-22 15:29 UTC, merged