Jones Gets Sturdy
tgstation/TerraGov-Marine-Corps pull request #9819
Opened 2022-03-20 09:55 UTC by EvilMelonTheSecond

## About The Pull Request
Gives cat hats half the armor of FC beret and decap immunity.

## Why It's Good For The Game
The brave companions that oversee marines from above now get to join the fight themselves. This tactically vital improvement will both boost the morale of troops and utilization of our limited yet considerable feline forces. As a side effect this might also cause marines to protect cats harder and in the future may even inspire other quad-pedal companions to get inspired to be on the frontlines themselves.

## Changelog
:cl:
add: Cat as helmets now provide decap immunity and half the protection of FC beret
/:cl:

2022-03-20 10:14 UTC, ilikesaying commented
what?
why?
why?
why?
why?

2022-03-20 11:10 UTC, Pill-U commented
how about something more original like letting jones tank one hit for the wearer and then dying (shitcooders inc. does not condone animal violence except for xenomorphs)

2022-03-22 02:25 UTC, UsernameIs-UnAvailable commented
Just fucking remove decap at this point. It’s obvious that maintainers don’t want it in the game if berets and a fucking headband can stop your head from flying off.

2022-03-24 07:29 UTC, David-Stormwell commented
uhm okay?

2022-03-25 22:17 UTC, TiviPlus requested changes

2022-03-25 22:17 UTC, TiviPlus commented on code/modules/mob/living/simple_animal/friendly/cat.dm
> +	soft_armor = list("melee" = 25, "bullet" = 25, "laser" = 25, "energy" = 25, "bomb" = 10, "bio" = 5, "rad" = 0, "fire" = 50, "acid" = 50)
A) You did not test this
B) This is not how to implement this

2022-03-26 09:53 UTC, Pill-U commented
I found two ways of implementing this:
A: replace with obj/item/clothing/head
![image](https://user-images.githubusercontent.com/54630159/160234212-8b3a267e-cb9d-4a14-8e85-13eb49fe2e35.png)
B: set the cat item's parent_type to obj/item/clothing/head, but I don't think this one is compliant with coding guidelines
![image](https://user-images.githubusercontent.com/54630159/160234252-1bd270d3-e948-4d86-9646-fd0da352dd80.png)

2022-03-30 07:11 UTC, TiviPlus requested changes
rest ok

2022-03-30 07:11 UTC, TiviPlus commented on code/modules/mob/living/simple_animal/friendly/cat.dm
>  	var/mob/living/simple_animal/cat/cat
```suggestion
```

2022-03-30 07:11 UTC, TiviPlus commented on code/modules/mob/living/simple_animal/friendly/cat.dm
```suggestion
	flags_armor_features = ARMOR_NO_DECAP
	soft_armor = list("melee" = 25, "bullet" = 25, "laser" = 25, "energy" = 25, "bomb" = 10, "bio" = 5, "rad" = 0, "fire" = 50, "acid" = 50)
	var/mob/living/simple_animal/cat/cat
```

2022-04-01 17:23 UTC, TiviPlus approved these changes

2022-04-01 17:23 UTC, merged