Tesla gun nerf
tgstation/TerraGov-Marine-Corps pull request #9824
Opened 2022-03-21 15:53 UTC by goose4429

## About The Pull Request

About The Pull Request
Tesla gun is a rarely used weapon, highly underestimated by marines. But in fact when it is used, it can have unexpectedly high impact. Current effects are:
- Skill block for xenos for LONG time
- Strong plasma drain with effect lasting for 10 seconds, draining 60% of your max plasma
- Slowdown, which usually makes difference between whether you are faster than marine or not
- All this with abysmally large effect range
- But also slow speed and firerate

This PR is trying to make tesla gun less painful for xenos.

## Why It's Good For The Game

Before, one pew pew from marine could break Queen Screech assault by blocking skills of every xenos in large radius. Even more painful, it made possible to hunt xeno by having few marines by your side when you shoot the tesla to hamper xeno retreat who are slowed and cannot use skills to escape tesla's large effect radius.

Now the tesla has less one-time impact, but steadier and more reliable performance. Slowdown removed, so it's not a xeno-bully weapon, but a disable weapon. Firerate improved along with projectile speed for better responsiveness. Ammo efficiency improved to make it more viable. You can still block Queen screeches and give benos a bad day.

**Note:** stagger stacks for each tick the beno is in radius, usually 2 times. Stagger decrease only matters when there are 4 stacks, reducing total stagger from 4 to 3 seconds (since otherwise you could perma-stagger a beno).

## Changelog
:cl:

balance: Reduced range of tesla from 4 to 2
balance: Increased direct hit damage from 20 to 40
balance: Decreased plasma drain effect time from 10 to 4
balance: Decreased plasma regen stop time from 10 to 4
balance: Decreased stagger time from 1 to 0.75
balance: Increased ball speed from 0.1 to 0.3
balance: Increased ammo per cell from 4 to 6
balance: Decreased time between shots from 4 to 3.5
balance: Removed slowdown effect

/:cl:

2022-03-21 15:57 UTC, Naaanii commented
Would be better to honestly keep it back as req only now that the strength is realised and let marines stick to T-gas as the budget Tesla.

2022-03-21 16:03 UTC, goose4429 commented
> Would be better to honestly keep it back as req only now that the strength is realised and let marines stick to T-gas as the budget Tesla.

Probably a good idea as well. Make it reasonably expensive, and stick it there. Still needs some reworks though.

2022-03-21 16:23 UTC, Mrrpip commented
> Would be better to honestly keep it back as req only now that the strength is realised and let marines stick to T-gas as the budget Tesla.

Meh, might as-well mention while we're at it, that the Tesla can randomly spawn at T1 weapon sites on some maps(Most frequently seen on Icy Caves).

So whatever you guys do, keep that in mind, yeah?

2022-03-21 18:29 UTC, EvilMelonTheSecond commented
Nerfing EVERY stat is a bit much, the gun barely has a niche even as a freebie. It is only effective is open areas with nothing to stop the projectile, can escaped by moving a few tiles away, deals no damage and is limited by line of sight. If nobody can deal with a gun in that narrow of a niche just send it to req hell where nobody will ever see it again.

2022-03-21 19:26 UTC, goose4429 commented
> Nerfing EVERY stat is a bit much, the gun barely has a niche even as a freebie. It is only effective in open areas with nothing to stop the projectile, can escaped by moving a few tiles away, deals no damage and is limited by line of sight. If nobody can deal with a gun in that narrow of a niche just send it to req hell where nobody will ever see it again.

It is indeed much less effective in tighter spaces. What do you think should be changed instead? This is my first take on this stuff, and I'd be glad to hear what you'd do

2022-03-21 22:19 UTC, EvilMelonTheSecond commented
> > Nerfing EVERY stat is a bit much, the gun barely has a niche even as a freebie. It is only effective in open areas with nothing to stop the projectile, can escaped by moving a few tiles away, deals no damage and is limited by line of sight. If nobody can deal with a gun in that narrow of a niche just send it to req hell where nobody will ever see it again.
> 
> It is indeed much less effective in tighter spaces. What do you think should be changed instead? This is my first take on this stuff, and I'd be glad to hear what you'd do

Another idea for balance might be to give it IFF in exchange for stat nerfs to broaden the niche while taking down the effect. I'm not a good at number balancing though so I would recommend balance testing at either side of extremes and adjusting as time shows.

2022-03-21 22:26 UTC, goose4429 commented
> > > Nerfing EVERY stat is a bit much, the gun barely has a niche even as a freebie. It is only effective in open areas with nothing to stop the projectile, can escaped by moving a few tiles away, deals no damage and is limited by line of sight. If nobody can deal with a gun in that narrow of a niche just send it to req hell where nobody will ever see it again.
> > 
> > 
> > It is indeed much less effective in tighter spaces. What do you think should be changed instead? This is my first take on this stuff, and I'd be glad to hear what you'd do
> 
> Another idea for balance might be to give it IFF in exchange for stat nerfs to broaden the niche while taking down the effect. I'm not a good at number balancing though so I would recommend balance testing at either side of extremes and adjusting as time shows.

That sounds like a very good idea - it both makes it less cumbersome to use, and more viable as a support weapon.

2022-03-22 09:24 UTC, goose4429 commented
I've received some feedback. Increased range to 3. Gave the gun built-in IFF because why the hell not, it's a support weapon. Added on-hit stagger and slowdown.

2022-03-24 09:27 UTC, OpsCoretango commented
oh no, balance moment
![meta_tag_9a21b46b75d7e272fa07cf232fe44d73.jpg](https://user-images.githubusercontent.com/55478690/159885371-e47c1af8-4813-45a5-a7a7-6b60ef1b7e25.jpg)

2022-03-25 22:32 UTC, TiviPlus requested changes
Your changelog is not player legible

I have some concerns:
Why make it do more damage and effects on hit, I neither see the point or benefot
Why add IFF
Why make the shell move faster (especially since you say you want consistent performance yet a faster shell makes it less consistent)

2022-03-26 19:29 UTC, goose4429 commented
> Your changelog is not player legible
> 
> I have some concerns: Why make it do more damage and effects on hit, I neither see the point or benefit Why add IFF Why make the shell move faster (especially since you say you want consistent performance yet a faster shell makes it less consistent)

1. More damage and effects just to encourage xenos to dodge the ball. In current state, you're better off by taking the ball on, because you'll be affected by less zap procs
2. I can't see how you can properly use the weapon without some kind of aim. To use it you need to be on the frontline, or have small number of marines nearby, like for shotguns of laser weapons. Laser weapons are used much less often than ballistic weapons. Shotguns are used because they have strong damage, and stagger. Tesla has stagger, but doesn't have the damage to back it up, so you must rely on your allies. And as described above, it conflicts with having no aim mode. I think having IFF or aim mode is necessary.
3.  This is the very reason I have started to try to rework tesla. Slow move speed allows for many many procs of zap(), which gives stagger and slow. Slow doesn't stack (but is still pain). However stagger _does_ stack, and personal experience + testing showed that you can get 10 seconds of stagger quite easily. And if it affects a sleeping (or otherwise standing still xeno), 15 seconds. Both of these are absurd, given it's 4 sec of reload.

All in all, I tried to conserve the idea of the weapon but making it more balanced and fun. Of these three changes, I think that:
Projectile speed - very important
IFF/aim - important, but not required
damage/on-hit effects - not important at all

I'd be glad to hear what you think

2022-03-29 12:58 UTC, FosterGrime-Heymynameslouie commented
speedmehrg

2022-03-29 13:06 UTC, FosterGrime-Heymynameslouie commented
> Would be better to honestly keep it back as req only now that the strength is realised and let marines stick to T-gas as the budget Tesla.

if this was to happen, CAS Tangle MIssle should be buffed back to 25 or 50 because the reason why it was nerfed in the first place was because Tesla gun was going to be free for all marines to use and it needed a counter balance, thus cas tangle got murked.

also speedmehgr based pr

2022-03-30 16:58 UTC, AGasCanister commented
![image](https://user-images.githubusercontent.com/55928412/160889996-63b5812e-d1f9-4ef9-9c8d-982ebbbfda38.png)
Terra Experimental Tesla Shock Rifle, you were a great weapon, almost never used because no one acknowledged your existence, I used you several times and got some good assists, I will remember you. I drink water in your honor

2022-04-01 19:19 UTC, Pariah919 commented
Concur with Tivi on this one.

2022-04-07 00:16 UTC, FosterGrime-Heymynameslouie commented
the IFF tesla gun was pretty fun
can it be split
like the standard tesla gun is the current one without IFF but higher plasma drain
but an "exprimental" version of the tesla gun that does have IFF with lower plasma drain be added to the vendors or req maybe

2022-04-07 07:42 UTC, merged