Adds the M40 Adhesive grenade
tgstation/TerraGov-Marine-Corps pull request #9833
Opened 2022-03-24 04:08 UTC by hyper2snyper

## About The Pull Request

It is a sticky grenade.
It currently has the power of an impact grenade.

When you throw it, it sticks to things.
You cannot remove it once its stuck. It has a 5 second delay.
It wont stick to turf. walls and floors are made with no stick stuff.

## Why It's Good For The Game
This adds a new and interesting type of grenade, it is about the same power of an impact.
Each day we get closer to becoming Halo.
Nova-Epee is the one who commisioned this, they are allowed to put more reasons below.

## Changelog
:cl:
add: Adds the M40 Adhesive grenade. A sticky grenade to stick to ~~friendlies~~ xenos. Has the same power of an impact grenade and a 5 second fuse.
/:cl:

2022-03-24 04:17 UTC, novaepee commented
Reasons:

1. Provide marines a unique toolset. There is one tool that stick onto a xeno: using a flare and litting up xeno on fire. Interesting for sure, but niche and not a serious threat. Here is a tool that is a serious threat and the xenomorph must run away in a safe distance so they don't blow themselves up and other xenomorphs.
2. Provide xenomorphs a new way to make marines friendly fire each other. Aim mode decreases the chance of xenomorphs using marines' weapons against each other, and a funny xenomorph can bring the nade BACK to the marines. Don't be shooting these on minions that suicide charge you.
4. Halo

2022-03-24 04:24 UTC, Lumipharon commented
The crusher charge deliberately eating sticky nades will be hilarious.

2022-03-24 06:49 UTC, BraveMole approved these changes
Need to clean ref on qdelete as well

2022-03-24 11:02 UTC, ThelastArchiver commented
two important things first of all does that mean xenos get flung (in a random direction) and staggered when it explodes and second are they gonna be req grenades or free?

2022-03-24 12:53 UTC, Pill-U commented
can xenos fling missed nades back?

2022-03-24 15:21 UTC, Losenis commented
Finally, counterplay to GL FF. Just run up to the fucker.

2022-03-24 17:38 UTC, Kuro020 approved these changes

2022-03-24 21:46 UTC, RuneQuester commented
Unavoidable grenade blasts??

2022-03-25 03:18 UTC, MiniMeatwad commented
Make it so you can resist it off

2022-03-25 17:41 UTC, novaepee commented
The random direction is going to get discussed with the coder.

> are they gonna be req grenades or free?

Check the code. They are free with 125 stocked.

> can xenos fling missed nades back?

If they don't stick on mobs, yes. The sticky nade doesn't stick on turf, walls, and floors, so by implication, the shrike can still play baseball with marines.

> Unavoidable grenade blasts that stagger?

You have 5 seconds to find a counterplay. If we're comparing this to impact nade, and it is important that we do, impact nade gives you no counter when you get click on. Currently, #9738 removes impact nade, and Bravemole expresses approval of sticky nade replacing impact nade.

> if it has the same power as an impact nade how is it nerfed

"the damage is delayed, so if you get crit you'll probably get crit behind allies line you can cause damage to marines you have more control over things"

"this is impact nade but xenos have more way to deal with it"

2022-03-25 22:11 UTC, TiviPlus requested changes

2022-03-25 22:11 UTC, TiviPlus commented on code/game/objects/items/explosives/grenades/marines.dm
> +	stuck_overlay.pixel_y += rand(-7, 7)
why add just set it

2022-03-25 22:11 UTC, TiviPlus commented on code/game/objects/items/explosives/grenades/marines.dm
> +	forceMove(hit_atom)
use the proper helpers

2022-03-28 12:14 UTC, FosterGrime-Heymynameslouie commented
can you theoretically stick loads of nades to a marine, charge in and blow up, essentially being a worse version of the suicide vest

2022-03-28 18:29 UTC, hyper2snyper commented
> can you theoretically stick loads of nades to a marine, charge in and blow up, essentially being a worse version of the suicide vest

they are five seconds till detonate.
have a small amount of damage.
and can only stick when activated.
tops you get 4 stuck to you then ~2 seconds to "charge" before they blow you up and ruin your day

2022-03-30 07:31 UTC, TiviPlus commented
Its cut not remove at least compile once smh

2022-04-06 09:48 UTC, TiviPlus requested changes
rest lgtm

2022-04-06 09:48 UTC, TiviPlus commented on code/game/objects/items/explosives/grenades/marines.dm
> +		clean_refs()
```suggestion
		stuck_to.cut_overlay(saved_overlay)
		clean_refs()
```

2022-04-08 15:53 UTC, merged