Medical Scanner Buff + Qol
tgstation/TerraGov-Marine-Corps pull request #9848
Opened 2022-03-28 06:35 UTC by hyper2snyper

## About The Pull Request

Med scanner is now tgui.
Larvas are now directly detected.
Fractures too.

Scanner now auto updates for corpmen and will even update within bags.
It has a range of three currently for health tracking.

![image](https://user-images.githubusercontent.com/43631032/160337336-a0646bb9-8568-4e4e-be23-94fa3d54b285.png)
![image](https://user-images.githubusercontent.com/43631032/160337351-18c81769-8c69-4e1d-8f16-fd9a1d6340e2.png)
![image](https://user-images.githubusercontent.com/43631032/160337366-796269ff-5c03-4072-bfc2-08b577eb4de6.png)
![image](https://user-images.githubusercontent.com/43631032/160337380-fef2fc3e-dca3-4d93-ab5c-5cb5fc9bb39c.png)
![image](https://user-images.githubusercontent.com/43631032/160337392-b48ef33a-4ace-4920-95b6-e6ff54fa176c.png)
![image](https://user-images.githubusercontent.com/43631032/160337437-aa9a536d-cd08-45b0-bdd5-1059cbfce397.png)
Noone is allowed to point out the 'Slaved' or the fact that the brute numbers are shifted 5 pixels to the right and arent aligned. They are all fixed see

![image](https://user-images.githubusercontent.com/43631032/160338875-de469b93-6bc5-453c-8d27-edf98c7e9646.png)
![image](https://user-images.githubusercontent.com/43631032/160337420-16b8e811-fb2f-4c5a-9e6d-37a6ef17a028.png)

## Why It's Good For The Game
The medical scanner is hard to look at and annoying to use as a corpman since you have to keep clicking the patient. This modernizes it and clears up the information it gives.

## Changelog
:cl:
qol: Med Scanner is now TGUI. 
balance: Med Scanner now auto updates for Corpmen and has a remote distance of 3
/:cl:

2022-03-28 08:10 UTC, Andrewhedge commented
seal man good

2022-03-28 16:12 UTC, Losenis commented
Does the autoupdate need the scanner held in hand or can it be put back in storage/thrown?

2022-03-28 16:48 UTC, hyper2snyper commented
> Does the autoupdate need the scanner held in hand or can it be put back in storage/thrown?

Can be in storage. 
If it's dropped the window will stay open but it will stop refreshing.
If you move out of range of the patient then it'll stop refreshing as well

2022-03-29 00:38 UTC, Lumipharon commented
To clarify, you can always see exactly where fracs are with this change?

2022-03-29 01:32 UTC, Arctrooper8 commented
And what about shrapnel too? You said in discord you'd just show where it was. Is that still true?

2022-03-29 03:36 UTC, hyper2snyper commented
> And what about shrapnel too? You said in discord you'd just show where it was. Is that still true?

oh right i forgot about that. well currently it shows that there is shrapnel and tells how much, but it doesnt show exactly where

2022-03-29 03:37 UTC, hyper2snyper commented
> To clarify, you can always see exactly where fracs are with this change?

yes

2022-03-29 22:29 UTC, Arctrooper8 commented on code/game/objects/items/scanners.dm
> +	if(!iscarbon(M) || issynth(M))
We should just remove the no scan trait for Synth, you can scan combat robots and they're basically just synth that can use guns.

2022-03-30 17:54 UTC, Losenis commented
How does this show IB damage?

2022-03-30 19:57 UTC, bowlofcereal commented
Does this specify that a certain limb has an implant in it and NOT shrapnel, so the medic doesnt yank it out and do significant amounts of damage and ruin the implant?

2022-04-01 19:18 UTC, Pariah919 commented
QOL is good, a +1 from me.

2022-04-03 09:01 UTC, bluezorua commented
does this also apply/work for armour attachments that add internal analysers like Valk/Vali?

2022-04-07 19:01 UTC, Losenis commented
Doesn't show IB nor Necrotizing, needs it asap

2022-04-07 20:52 UTC, hyper2snyper commented
> Doesn't show IB nor Necrotizing, needs it asap

It does show both

2022-04-07 22:48 UTC, ilikesaying commented
![image](https://user-images.githubusercontent.com/65475697/162331965-8feeb53e-f76f-42ad-b222-6fe67ad403e3.png)

2022-04-07 23:04 UTC, Losenis commented
It doesn't show IB in that it only shows brute damage that isn't healing, I haven't seen anything that'd point to it being actual IB other than the player already knowing that brute damage that refuses to heal is IB, unlike old scanner that says there's IB somewhere.

2022-04-08 21:54 UTC, BraveMole requested changes
You can use scanner on you, throw it away, and you get infini health information. Please fix. Not having in your hand should stop the info feed

2022-05-15 05:06 UTC, FosterGrime-Heymynameslouie commented
I know when you bleed

2022-05-15 08:00 UTC, TiviPlus approved these changes

2022-05-15 08:21 UTC, merged