Lowers the cost of feast for gorger.
tgstation/TerraGov-Marine-Corps pull request #9881
Opened 2022-04-01 05:30 UTC by vilereaver41

## About The Pull Request

Feast used to be 200 blood/plasma now its 130 blood/plasma to activate.

## Why It's Good For The Game

Gorger is a bullet sponge shielder support caste, that being said 90% of the time it wont have the required blood to activate its feast as it will need to heal and make shields for the hive which is more beneficial so its not seen much,  I believe 130 is a good starting point rather then 200.

This will allow the ability to be used more and grant gorger more bullet sponge soaking as a target for marines.

This will help gorger's survivability and presence on the field more so with marines constant additions of weapons and to fine tune itself as the main support for the hive.

## Changelog
:cl:
balance: feast now 130 down from 200
/:cl:

2022-04-01 05:33 UTC, lovegreenstuff commented
skill issue

2022-04-01 19:13 UTC, Pariah919 requested changes
Cooldown timers too sledgehammery, even for me. The sledgehammer man.

2022-04-01 19:13 UTC, Pariah919 commented on code/modules/mob/living/carbon/xenomorph/castes/gorger/abilities_gorger.dm
> +	cooldown_timer = 30 SECONDS
```suggestion
	cooldown_timer = 100 SECONDS
```
You're lieterally reducing this by like, 3 minutes. Try 100 seconds. First. Reduce later.

2022-04-04 00:32 UTC, vilereaver41 commented
Done

2022-04-10 13:41 UTC, BraveMole commented
stale

2022-04-10 13:41 UTC, closed without merging