Wraith fixes
tgstation/TerraGov-Marine-Corps pull request #9897
Opened 2022-04-02 20:23 UTC by breadhunt

## About The Pull Request

Lot of wraith fixes
Stuff I couldn't reproduce/seemed to be already fixed:
-timestop not working https://github.com/tgstation/TerraGov-Marine-Corps/issues/9859#issue-1185977445
-wraiths can't unbanish themselves https://github.com/tgstation/TerraGov-Marine-Corps/issues/9690#issue-1147646063
-Banished xenos taking fire damage https://github.com/tgstation/TerraGov-Marine-Corps/issues/9136
-Blinking marines past fog (the fog just stops you) https://github.com/tgstation/TerraGov-Marine-Corps/issues/7268

What is fixed:
- https://github.com/tgstation/TerraGov-Marine-Corps/issues/9045
- https://github.com/tgstation/TerraGov-Marine-Corps/issues/9680
- https://github.com/tgstation/TerraGov-Marine-Corps/issues/9466
- https://github.com/tgstation/TerraGov-Marine-Corps/issues/9364
- https://github.com/tgstation/TerraGov-Marine-Corps/issues/9137
- https://github.com/tgstation/TerraGov-Marine-Corps/issues/8648
- Tadpole can no longer be slashed **while in phase shift** (this was extremely funny)
- Starting/ending phase shift in no-phase zones and objects
^ This means you can no longer accidentally get stuck in no-phase shutters, you just get teleported out

Alamo/canter fuckery is still very possible but since you can't use phase shift to get in (shifting into walls, shifting into cockpit) it might be a bit harder (probably for the best)

I don't know how to fix timestop bugs. If someone with better c*ding socks can figure them out here's a (probably) list of things to check out:
- Lasers can completely crash the game if spammed into timestop
- Lag means bullets travel further before being stopped by timestop (sometimes making it completely worthless)
- Bullets probably shouldn't be able to be fired at all in timestop considering it's a timestop

## Why It's Good For The Game

Bugfixes good. Wraith has a bad rep for a few REALLY bad bugs that haven't been fixed for too long. Fixes them and might Make Wraith Playable Again:tm:

## Changelog
:cl:
fix: Wraiths can no longer banish tunnels, deleting any xenos climbing inside
fix: Prison Station hull windows can no longer be banished, allowing access to space
fix: Wraiths can no longer use phase shift in no-phase areas (e.g LZs, dropships, spess)
fix: Wraiths can no longer end phase shift, or have phase shift ended, in no-phase areas or dense objects (walls)
fix: This means your buddy wraith won't get stuck in a phase shutter in a wall by accident again
fix: Wraith can no longer slash tadpole console while in phase shift
fix: Wraiths can banish opaque objects (shutters, doors) again
fix: Wraith can no longer regress in phase shift (caused issues because of how health updates work with phase shift, sorry)
fix: Banish portal being deleted (by a shuttle, etc), or otherwise made impossible to move to, no longer keeps the marine in banish indefinitely. Instead they are teleported to the coordinates the portal was originally at
/:cl:

2022-04-02 20:31 UTC, Wayland-Smithy commented
Very cool. Unfortunately though all those issues will not auto close on merge because github typically parses for "Fixes: #xxxx" or "Closes: #xxxx" and I'm not sure just adding the prefix will work with the nice named links, read more about it [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue). You'll now it's working when the issues are listed in the Development section on the right side.

2022-04-02 21:51 UTC, breadhunt commented
> Very cool. Unfortunately though all those issues will not auto close on merge because github typically parses for "Fixes: #xxxx" or "Closes: #xxxx" and I'm not sure just adding the prefix will work with the nice named links, read more about it [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue). You'll know it's working when the issues are listed in the Development section on the right side.

GOD BLESS YOU WAYLAND.
Done

2022-04-04 06:46 UTC, BraveMole commented
Next time please atomize, it is pain to review this

2022-04-04 06:53 UTC, BraveMole requested changes

2022-04-04 06:53 UTC, BraveMole commented on code/modules/shuttle/mini_dropship.dm
> +	if(isxenowraith(X) && X.status_flags & INCORPOREAL)
Istype(src) not allowed

2022-04-04 06:53 UTC, BraveMole commented on code/modules/shuttle/mini_dropship.dm
> +	if(isxenowraith(X) && X.status_flags & INCORPOREAL)
But you probaboy just needs the status flag anyway

2022-04-04 06:53 UTC, BraveMole commented on code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
> +	var/backup_y
The fix idea looks correct, please save the coordinates into an array

2022-04-04 17:39 UTC, BraveMole approved these changes

2022-04-04 17:39 UTC, BraveMole commented on code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
> +		banishment_target.forceMove(locate(backup_coordinates[1],backup_coordinates[2],backup_coordinates[3]))
```suggestion
		banishment_target.forceMove(locate(backup_coordinates[1], backup_coordinates[2], backup_coordinates[3]))
```

2022-04-10 10:11 UTC, merged