Adds balloon_alerts to lots of actions
tgstation/TerraGov-Marine-Corps pull request #9901
Opened 2022-04-03 17:22 UTC by RipGrayson

## About The Pull Request

This is the QOL update that TGMC needs but didn't know it needed. Most construction/surgery/xeno actions now inform their user with overhead text.
No more missing a cooldown notification for your xeno ability because it got lost in the textbox during a fight.
No more missing a rookie doctor botching a surgery because the notification for the step he used got lost during a command announcement.
No more missing the notification for running out of ammo in a fire fight because there's 20 other marines firing and the text alert gets shuffled off the screen.

## Why It's Good For The Game

We're moving away from the philosophy of needing to stare at chat in order to see what's going on, runechat did it for speech, balloon_alerts do it for actions. It's just so much easier to see what's going on by looking at your character than it is to dig around in a bunch of text.
On the aesthetic side it actually looks really cool to see overhead notifications like "Franklin Ramis fixes the internal wiring of platinum miner" or "Queen (236) starts emitting pheremones", it makes us look very smooth.
So by implementing this not only do we look fancy, but it also enhances team cooperation because xenos/marines can see what their teammates are doing while being focused on combat. (Not that they couldn't before, they would just have to scroll through chat, which made it impractical).

## Changelog
:cl:
qol: Added balloon_alerts to many many different actions.
spellcheck: Fixed a few typos while adding balloon_alerts
/:cl:

2022-04-04 15:08 UTC, TiviPlus requested changes
Very good pr

However you cant just copy paste the to chat, you need to remove the to chat (In some cases though you might want to keep it in case the log is useful)
Ex. conversions:
balloon_alert(usr, "cannot reach")
to_chat(src, span_warning("We cannot reach this from here!"))

X.balloon_alert(X, "Cannot do this here")
to_chat(owner, span_warning("We can't do this here!"))

buckling_mob.balloon_alert(buckling_mob, "Unable to buckle")
to_chat(buckling_mob, span_warning("You are unable to buckle yourself to [src]!"))

IE note: no punctuation, short as possible, generally avoid name inserts unless needed because they make text longer

Otherwise very good PR hope you finish this, ping me if you need any help

2022-04-15 19:26 UTC, TiviPlus requested changes

2022-04-15 19:26 UTC, TiviPlus commented on code/game/objects/items/reagent_containers/robodropper.dm
> +				user.balloon_alert(user, "You can't fill this object")
```suggestion
				balloon_alert(user, "You can't fill this object")
```

2022-04-15 19:26 UTC, TiviPlus commented on code/game/objects/items/reagent_containers/robodropper.dm
> +						user.balloon_alert(user, "You transfer [trans] units of the solution.")
```suggestion
						balloon_alert(user, "Transferred [trans] units")
```

2022-04-15 19:26 UTC, TiviPlus commented on code/game/objects/items/reagent_containers/spray.dm
> +			user.balloon_alert(user, "[A] is empty")
```suggestion
			A.balloon_alert(user, "It is empty")
```

2022-04-15 19:26 UTC, TiviPlus commented on code/game/objects/items/reagent_containers/spray.dm
> +			user.balloon_alert(user, "[src] is full")
```suggestion
			balloon_alert(user, "It is full")
```

2022-04-21 01:58 UTC, RipGrayson commented
I don't have time to manually check all things right now for review compliance, will reopen when I have more free time

2022-04-21 01:58 UTC, closed without merging