Sulaco armory
tgstation/TerraGov-Marine-Corps pull request #9941
Opened 2022-04-06 17:19 UTC by Naaanii

## About The Pull Request

Adds an armory to the Sulaco CIC. Mirrors a bit of the resources available in the POS CIC armory and adds them to the Sulaco CIC and rearranges a bit of the already available resources.

## Why It's Good For The Game

Makes for better consistency regarding ships. Most of the armory equipment was already available while a bit more was added without changing the original design too much. This also slightly buffs CIC holds, so balance might be involved.

## Changelog
:cl:
qol: rearranged a few lockers and vendors.
balance: added more stuff to armory like mats, medkits etc. (mirrored from PoS)
/:cl:

2022-04-06 20:22 UTC, Pariah919 approved these changes
I like ship maps having minute differences.

This makes sense, however.

2022-04-06 20:52 UTC, Derrick2Electricboogaloo commented
Already got an armory in my PR

2022-04-06 23:22 UTC, Ragecrabbo commented
0/10 PR cant see spess from CIC anymore without opening armory

2022-04-09 20:12 UTC, BraveMole requested changes
This is lower prio compared to the other sulaco pr.

2022-04-17 20:28 UTC, Naaanii commented
Closing because Derrick's PR should get merged soon.

2022-04-17 20:28 UTC, closed without merging