Give Hivemind Transfer Plasma
tgstation/TerraGov-Marine-Corps pull request #9951
Opened 2022-04-07 22:31 UTC by novaepee

## About The Pull Request

Title.

## Why It's Good For The Game

The hivemind is one of the premiere support roles in the hive. It provides healing, building, and weeding against all odds from marines' superior firepower. It's the drone that keeps on supporting.

Weirdly, even though it can heal, it cannot give plasma to other xenomorphs. This can be an alternative to #9911 , but it depends on the maintainers. I'm giving it the drone plasma transfer since hivelord has a lot more compared to drone, and it makes sense that hivemind is drone that saw the weakness of fresh and embrace the resin.

## Changelog
:cl:
add: Give Hivemind Transfer Plasma
balance: Provide Hivemind Transfer plasma so it can support xenos
/:cl:

2022-04-07 22:33 UTC, Naaanii commented
Could give it it's own version imo.

More plasma transfer than drone, slightly higher plasma cost, much longer CD, almost on par with heal so it's not spammable like drones and hivelord.

2022-04-08 16:05 UTC, BraveMole requested changes
Pretty sure you can use it even when unmanifested, so no

2022-04-09 20:23 UTC, BraveMole requested changes

2022-04-09 20:23 UTC, BraveMole commented on code/modules/mob/living/carbon/xenomorph/castes/hivemind/abilities_hivemind.dm
> +	plasma_transfer_amount = PLASMA_TRANSFER_AMOUNT * 3
that's just way too strong, no

2022-04-10 08:48 UTC, BraveMole approved these changes

2022-04-10 08:48 UTC, merged