README Rework
tgstation/TerraGov-Marine-Corps pull request #9981
Opened 2022-04-09 23:22 UTC by ElectronicsArchiver

## About The Pull Request

Please check the **[Preview](https://github.com/ElectronicsArchiver/TerraGov-Marine-Corps)**.

- Converted raw links to referenced links
- General formatting / spacing / separation
- Refactored licensing information into table
- Added license badges
- Linked license material sources

CC licenses are of version 4.0, but since they were
designed as direct upgrades to 3.0, there shouldn't
be any issues.

CC Attribution -> CC BY ? 

## Why It's Good For The Game

No the game, but its repo.

Better overview of licensing notices.
Cleaner look, improved readbility.

## Changelog
:cl:
refactor: Refactored README content
/:cl:

2022-04-10 15:20 UTC, mrhugo13 commented
Since this isn't actually affecting anything game-related, then it's probably better to not have it as part of the changelog.

2022-04-10 15:40 UTC, ElectronicsArchiver commented
Sure, I removed the changelog section~

2022-04-10 20:04 UTC, BraveMole requested changes
I understand less this than the current readme.

And you are changing licences ? 

Ok it looks pretty but simple MD is good enough fore a readme, especially if it contains 10 lines

2022-04-10 20:33 UTC, ElectronicsArchiver commented
As I said, CC4 licenses graduate CC3 ones 
( no license changes, they just refined them and are now the common standard )

> Ok it looks pretty but simple MD is good enough fore a readme, especially if it contains 10 lines

You say that, but have you compared the **[Old]** & **[New]** versions?
The actual content part is much cleaner .. 

[New]: https://github.com/ElectronicsArchiver/TerraGov-Marine-Corps/blob/master/README.md?plain=1
[Old]: https://github.com/tgstation/TerraGov-Marine-Corps/blob/master/README.md?plain=1

2022-04-10 20:44 UTC, BraveMole commented
Ok but sentences are clearer than your table IMO

2022-04-10 20:49 UTC, ElectronicsArchiver commented
Well it's not about reading in this case is it?

If you wanted to check for licensing you'd be interesting 
in for example the type kind of material, in that case 
you'd have to simply check the first column.

If you wanted to check what licenses the repo 
contains you would check the last column.

I'm not sure how in this situation a written version 
would be more of use than a diagram?

2022-04-10 20:55 UTC, BraveMole commented
![image](https://user-images.githubusercontent.com/25491240/162639412-97995746-85fc-4998-ad74-0bb60bf6269f.png)

I do not get what's going on here, despite already knowing what's written on original readme. I do not expect someone just coming to this repo to understand either.

2022-04-10 21:01 UTC, ElectronicsArchiver commented
And I'm honestly not sure what you don't understand about it.

**What** material 
**From** where
is under which **License**

*On that note, what is `-this commit-` anyways?*
What commit was meant with that?
( In the original the next referenced thing was a PR )

2022-04-10 21:02 UTC, ElectronicsArchiver commented
I could rename the table headers if you'd like to for example 
`Material Type`, `Licensing Material`, `Source` or something.

2022-04-11 11:10 UTC, TiviPlus requested changes

2022-04-11 11:10 UTC, TiviPlus commented on README.md
> +`Artwork`       | *after -this commit-*                | [![Badge CC-BY-NC]][License CC-BY-NC]
Please add that this means https://github.com/tgstation/TerraGov-Marine-Corps/commit/92ee94da6e144d4420c1ec4f83a4ee785d61dc9b

2022-04-11 11:10 UTC, TiviPlus commented on README.md
> +:--------------:|:------------------------------------:|:------------------------:
See discussion with brave maybe change this "What" to "Asset type" or similar?

2022-04-18 10:43 UTC, TiviPlus approved these changes

2022-04-18 10:43 UTC, merged